### PR TITLE
fix(ecs-patterns): resolve target group conflict when updating ALB internetFacing or loadBalancerName (under feature flag)

### LINKED ISSUE #33253: (aws_ecs_patterns): ApplicationLoadBalancedFargateService fails to update when switched from public to private - Fails due to target group
### Describe the bug

When the ApplicationLoadBalancedFargateService pattern is used to create an ALB along with a target group, it creates a public facing load balancer. Once this is created, if I try to switch it to a private ALB, using the parameter `publicLoadBalancer: false`, it fails with error:

Resource handler returned message: "The following target groups cannot be associated with more than one load balancer: arn:aws:elasticloadbalancing:eu-west-1:318627068478:targetgroup/EcsCon-Sampl-HV24A4ZHHGG1/829e923a9abe6705 (Service: ElasticLoadBalancingV2, Status Code: 400, Request ID: dbe30509-a4b7-42fa-9087-bcff22fdb55b)" (RequestToken: 544175ba-248a-5a75-3458-50b0f5d80582, HandlerErrorCode: ServiceLimitExceeded)

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

The target group should be disassociated from the previous load balancer and then attempted to be attached to the new load balancer or a new target group could be created to attach to the new load balancer.

Here's the CDK diff:
```
Resources
[~] AWS::ElasticLoadBalancingV2::LoadBalancer SampleNetworkLoadBalancedFargateService/LB SampleNetworkLoadBalancedFargateServiceLB3B04F5EA replace
 ├─ [~] Scheme (requires replacement)
 │   ├─ [-] internet-facing
 │   └─ [+] internal
 └─ [~] Subnets
     └─ @@ -1,4 +1,4 @@
        [ ] [
        [-]   "subnet-08d2e5e9a5526d5cd",
        [-]   "subnet-03639cc2fb087e322"
        [+]   "subnet-0be5b8bc6890cdfd1",
        [+]   "subnet-002110f783fd87957"
        [ ] ]
[~] AWS::ElasticLoadBalancingV2::Listener SampleNetworkLoadBalancedFargateService/LB/PublicListener SampleNetworkLoadBalancedFargateServiceLBPublicListener8ED1C5F0 replace
 └─ [~] LoadBalancerArn (requires replacement)
     └─ [~] .Ref:
         ├─ [-] SampleNetworkLoadBalancedFargateServiceLB3B04F5EA
         └─ [+] SampleNetworkLoadBalancedFargateServiceLB3B04F5EA (replaced)


✨  Number of stacks with differences: 1
```

### Current Behavior

Stack deployment fails because the target group is not attached to the private load balancer since it is already attached to the public load balancer

### Reproduction Steps

Create an application load balanced fargate service using the construct as follows:

```
const fargateService = new ApplicationLoadBalancedFargateService(this, "SampleNetworkLoadBalancedFargateService", {
  vpc,
  taskDefinition: taskDefinition,
  minHealthyPercent: 100
});

// fargateService.service.connections.allowFromAnyIpv4(Port.tcp(80), "Allow inbound HTTP traffic");

fargateService.targetGroup.healthCheck = {
  port: "80",
  protocol: Protocol.HTTP,
  path: "/alive",
  interval: Duration.seconds(20),
}
```

Simply add the `publicLoadBalancer: false` to the construct ApplicationLoadBalancedFargateService as follows:
```
const fargateService = new ApplicationLoadBalancedFargateService(this, "SampleNetworkLoadBalancedFargateService", {
      vpc,
      taskDefinition: taskDefinition,
      minHealthyPercent: 100,
      publicLoadBalancer: false
});

// fargateService.service.connections.allowFromAnyIpv4(Port.tcp(80), "Allow inbound HTTP traffic");

fargateService.targetGroup.healthCheck = {
  port: "80",
  protocol: Protocol.HTTP,
  path: "/alive",
  interval: Duration.seconds(20),
}
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

v2.177.0

### Framework Version

_No response_

### Node.js Version

v20.17.0

### OS

Windows

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by puretension**
fix(ecs-patterns): resolve target group conflict when switching ALB public/private

Fixes #33253

### Issue # (if applicable)
Closes #33253.

### Reason for this change
When switching ApplicationLoadBalancedFargateService from public to private (or vice versa), CloudFormation fails with "target group cannot be associated with more than one load balancer" error. This happens because both old and new load balancers try to use the same target group during replacement.

Updating the `loadBalancerName` of ApplicationLoadBalancedFargateService can also trigger the same issue.

### Description of changes
Modified target group naming in `ApplicationLoadBalancedServiceBase` to include the load balancer type and name. e.g:
- Public load balancer: target group named "ECS" 
- Private load balancer: target group named "ECSPrivate"
- Private load balancer with name "Foo": target group named "ECSFooPrivate"

This ensures each load balancer gets its own target group, preventing conflicts during CloudFormation updates.

## ⚠️ Destructive Changes

This PR contains intentional destructive changes to fix the target group conflict issue:

- **Target Group Names Changed**, e.g: 
  - Public ALB: `ECS` (unchanged)
  - Private ALB: `ECSPrivate` (new)

- **Impact**: When switching from public to private ALB (or vice versa), CloudFormation will:
  1. Create new target group with different name
  2. Delete old target group
  3. This prevents the "target group cannot be associated with more than one load balancer" error

- **Justification**: This is the intended fix for issue #33253. The destructive change is necessary to resolve the CloudFormation conflict.

**Breaking Change**: ❌ No - This only affects the internal target group naming, not user-facing APIs.

### Describe any new or updated permissions being added
No new IAM permissions required.

### Description of how you validated changes
- Added unit tests verifying target group names for both public and private configurations
- Created integration test `integ.alb-fargate-service-public-private-switch.ts` that deploys both public and private ALB services
- Verified CloudFormation templates generate different target group names

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

### CODE REVIEW

File: packages/aws-cdk-lib/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts [hunk 1]
```diff
@@ -519,7 +519,9 @@ export abstract class ApplicationLoadBalancedServiceBase extends Construct {
       open: props.openListener ?? defaultOpenListener,
       sslPolicy: props.sslPolicy,
     });
-    this.targetGroup = this.listener.addTargets('ECS', targetProps);
+    // Include publicLoadBalancer in target group ID to force replacement when switching between public/private
+    const targetGroupId = internetFacing ? 'ECS' : 'ECSPrivate';
```
Comment (Abogical) [inline packages/aws-cdk-lib/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts]: The root issue this PR aims to fix is caused whenever the LoadBalancer is replaced by Cloudformation. This is triggered if any of the "Replacement" properties (listed [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-elasticloadbalancingv2-loadbalancer.html)) are updated. From the properties we set in this construct, there are 2 property updates which can trigger the replacement:

- internetFacing, as it sets the replacement property [`Scheme`](https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2-loadbalancer-scheme)
- `props.loadBalancerName`, as it sets the replacement property [`Name`](https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2-loadbalancer-name)

This PR fixes the issue when updating `internetFacing`, but not when updating `props.loadBalancerName`. We can incorporate the load balancer name when setting the target ID to fix this as well.

```suggestion
    const targetGroupId = `ECS{props.loadBalancerName ?? ''}{internetFacing? '' : 'Private'}`;
```

**Review by Abogical — DISMISSED** [review]
Hi @puretension, Thank you for your contribution!

As this PR has breaking (destructive) changes, a feature flag will be needed here. See [this guide](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#feature-flags) which will help you add a new feature flag for this PR. This fix will then only take effect when the feature flag is set.

Also, see my comment on setting the ID below.

File: packages/aws-cdk-lib/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts (hunk 1 above)
Comment (puretension) [reply packages/aws-cdk-lib/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts]: Hi @Abogical! Thank you for the detailed feedback and suggestions!

I've implemented both of your recommendations. 
Added the `ECS_PATTERNS_UNIQUE_TARGET_GROUP_ID` feature flag in `cx-api/lib/features.ts` and 
wrapped the new logic with `FeatureFlags.of(this).isEnabled()` to ensure backward compatibility.

Also incorporated your suggested target ID logic to handle both replacement scenarios the internetFacing changes (Scheme property) and loadBalancerName changes (Name property). 
Used `ECS${props.loadBalancerName ?? ''}${internetFacing ? '' : 'Private'}` as you recommended.

Please let me know if there's anything else I should address or if I missed something!
Thanks again for the thorough review and guidance!

**Review by Abogical — DISMISSED** [review]
Thank you for the quick edit!

Following steps 4-6 in the [feature flag guide](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#feature-flags), the following is needed:

> 4. Add an entry for your feature flag in the [README](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/cx-api/README.md) file.
> 5. In your tests, ensure that you test your feature with and without the feature flag enabled. You can do this by passing the feature flag to the `context` property when instantiating an `App`.
>    ```ts
>    const myFeatureFlag = { [cxapi.MY_FEATURE_FLAG]: true };
>    const app = new App({
>       context: myFeatureFlag,
>    }),
>    const stackUnderTest = new Stack(app);
>    ```
> 7. In your PR title (which goes into CHANGELOG), add a `(under feature flag)` suffix. e.g:
> 
>     `fix(core): impossible to use the same physical stack name for two stacks (under feature flag)`
>    context: myFeatureFlag,
> }),
> const stackUnderTest = new Stack(app);
> In your PR title (which goes into CHANGELOG), add a (under feature flag) suffix. e.g:
> 
> `fix(core): impossible to use the same physical stack name for two stacks (under feature flag)`

**Comment by puretension** [comment]
Thank you for the really quick feedback! I've completed missed steps 4-6.

I added the feature flag documentation to the README, implemented tests for both enabled and disabled scenarios following 
your specified pattern, and the PR title already includes the "(under feature flag)" suffix. I really appreciate your 
detailed guidance as this is my first CDK contribution.

All changes have been committed and pushed. Please let me know if there's anything else needed!

File: README.md [hunk 2]
```diff
@@ -153,6 +153,18 @@ This solution collects anonymous operational metrics to help AWS improve the
...
+The AWS CDK uses feature flags to enable new breaking changes only for new projects. Existing projects continue to use the old behavior until the feature flag is enabled. For more information, see [Feature Flags](https://docs.aws.amazon.com/cdk/latest/guide/featureflags.html) in the CDK Developer Guide.
+
+### ECS Patterns Unique Target Group ID
+
+**Flag:** `@aws-cdk/aws-ecs-patterns:uniqueTargetGroupId`
+
+When enabled, ECS patterns will generate unique target group IDs that include the load balancer name and type (public/private). This prevents CloudFormation conflicts when switching between public and private load balancers.
+
+Without this flag, switching an ApplicationLoadBalancedFargateService from public to private (or vice versa) fails with "target group cannot be associated with more than one load balancer" error.
+
```
Comment (Abogical) [inline README.md]: This is the wrong README file to edit. The README file to edit is at `packages/aws-cdk-lib/cx-api/README.md`

**Review by Abogical — DISMISSED** [review]

File: README.md (hunk 2 above)
Comment (puretension) [reply README.md]: @Abogical  Thank you for the correction! 
I apologize for the basic mistake of editing the wrong README file.😅 
I've now moved the feature flag documentation from the root README.md to the correct location at `packages/aws-cdk-lib/cx-api/README.md` as requested. 

I'll be more careful to follow the documentation guidelines precisely in future contributions. 
Thank you for your patience and guidance!

**Review by Abogical — DISMISSED** [review]
Integration test snapshot needs to be updated:

```
CHANGED    aws-elasticloadbalancingv2-targets/test/integ.alb-target 3.735s
@aws-cdk-testing/framework-integ:       Resources
@aws-cdk-testing/framework-integ:       [-] AWS::ElasticLoadBalancingV2::TargetGroup ServiceLBPublicListenerECSGroup0CC8688C destroy
@aws-cdk-testing/framework-integ:       [+] AWS::ElasticLoadBalancingV2::TargetGroup ServiceLBPublicListenerECSPrivateGroup93D5832E
@aws-cdk-testing/framework-integ:       [~] AWS::ElasticLoadBalancingV2::Listener ServiceLBPublicListener46709EAA
@aws-cdk-testing/framework-integ:        └─ [~] DefaultActions
@aws-cdk-testing/framework-integ:            └─ @@ -1,7 +1,7 @@
@aws-cdk-testing/framework-integ:               [ ] [
@aws-cdk-testing/framework-integ:               [ ]   {
@aws-cdk-testing/framework-integ:               [ ]     "TargetGroupArn": {
@aws-cdk-testing/framework-integ:               [-]       "Ref": "ServiceLBPublicListenerECSGroup0CC8688C"
@aws-cdk-testing/framework-integ:               [+]       "Ref": "ServiceLBPublicListenerECSPrivateGroup93D5832E"
@aws-cdk-testing/framework-integ:               [ ]     },
@aws-cdk-testing/framework-integ:               [ ]     "Type": "forward"
@aws-cdk-testing/framework-integ:               [ ]   }
@aws-cdk-testing/framework-integ:       [~] AWS::ECS::Service Service9571FDD8
@aws-cdk-testing/framework-integ:        ├─ [~] LoadBalancers
@aws-cdk-testing/framework-integ:        │   └─ @@ -3,7 +3,7 @@
@aws-cdk-testing/framework-integ:        │      [ ]     "ContainerName": "nginx",
@aws-cdk-testing/framework-integ:        │      [ ]     "ContainerPort": 80,
@aws-cdk-testing/framework-integ:        │      [ ]     "TargetGroupArn": {
@aws-cdk-testing/framework-integ:        │      [-]       "Ref": "ServiceLBPublicListenerECSGroup0CC8688C"
@aws-cdk-testing/framework-integ:        │      [+]       "Ref": "ServiceLBPublicListenerECSPrivateGroup93D5832E"
@aws-cdk-testing/framework-integ:        │      [ ]     }
@aws-cdk-testing/framework-integ:        │      [ ]   }
@aws-cdk-testing/framework-integ:        │      [ ] ]
@aws-cdk-testing/framework-integ:        └─ [~] DependsOn
@aws-cdk-testing/framework-integ:            └─ @@ -1,5 +1,5 @@
@aws-cdk-testing/framework-integ:               [ ] [
@aws-cdk-testing/framework-integ:               [ ]   "ServiceLBPublicListener46709EAA",
@aws-cdk-testing/framework-integ:               [-]   "ServiceLBPublicListenerECSGroup0CC8688C",
@aws-cdk-testing/framework-integ:               [+]   "ServiceLBPublicListenerECSPrivateGroup93D5832E",
@aws-cdk-testing/framework-integ:               [ ]   "TaskTaskRoleE98524A1"
@aws-cdk-testing/framework-integ:               [ ] ]
@aws-cdk-testing/framework-integ:       [~] AWS::ElasticLoadBalancingV2::TargetGroup NlblistenerTargetsGroupDD2A3CB0
@aws-cdk-testing/framework-integ:        └─ [~] DependsOn
@aws-cdk-testing/framework-integ:            └─ @@ -1,4 +1,4 @@
@aws-cdk-testing/framework-integ:               [ ] [
@aws-cdk-testing/framework-integ:               [ ]   "ServiceLBPublicListener46709EAA",
@aws-cdk-testing/framework-integ:               [-]   "ServiceLBPublicListenerECSGroup0CC8688C"
@aws-cdk-testing/framework-integ:               [+]   "ServiceLBPublicListenerECSPrivateGroup93D5832E"
@aws-cdk-testing/framework-integ:               [ ] ]
```

**Review by Abogical — DISMISSED** [review]
Yet another snapshot to be updated. Unfortunately, there can be a lot of snapshots to update especially modifying this package:

```
CHANGED    aws-ecs-patterns/test/fargate/integ.alb-fargate-service-public-private-switch
```

**Comment by puretension** [comment]
@Abogical Thank you for pointing out the additional snapshot that needed updating! 
I've just pushed the updated snapshots for both 
`aws-elasticloadbalancingv2-targets/test/integ.alb-target` 
and `aws-ecs-patterns/test/fargate/integ.alb-fargate-service-public-private-switch`. 

I understand there can be quite a few snapshots to update when modifying the ecs-patterns package. 
I'll keep an eye on the CI results to see if any other snapshots need attention. 
Appreciate your patience with the iterative snapshot updates.

**Comment by puretension** [comment]
All build tests have passed successfully. 
However, the CI pipeline has automatically generated changes to these two files:
- packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md
- packages/aws-cdk-lib/recommended-feature-flags.json

These appear to be auto-generated by the feature flag system. Should I commit these changes, or is there a different process for handling auto-generated feature flag documentation?

**Review by Abogical — DISMISSED** [review]
The generated files you mentioned come from rosetta. Updates to the documentation might need an update via rosetta if it contains code snippets. Run the command listed [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#rosetta) to generate and commit those files.

**Comment by puretension** [comment]
@Abogical Thanks for your continued attention to this. 
All build tests have been resolved and the Rosetta-generated files have been properly committed. 
Please let me know if there's anything else needed to move this forward!

**Review by Abogical — APPROVED** [review]
LGTM. Thank you for your contribution to CDK!

**Comment by Abogical** [comment]
@mergifyio update

**Comment by Abogical** [comment]
@mergifyio rebase

**Comment by puretension** [comment]
@Abogical Thank you so much for your patience, guidance, and approval throughout this entire contribution process! 🙏

The previous CI Codebuild PR Build failure was likely due to the branch being out of sync🤔.
The rebase should have resolved the ESLint issues that were blocking the merge.

Should I change something more for safely merge? Or is there anything else I need to address before this can be merged?

**Comment by Abogical** [comment]
> @Abogical Thank you so much for your patience, guidance, and approval throughout this entire contribution process! 🙏

@puretension You're welcome!

> The previous CI Codebuild PR Build failure was likely due to the branch being out of sync🤔.
> The rebase should have resolved the ESLint issues that were blocking the merge.
>
> Should I change something more for safely merge? Or is there anything else I need to address before this can be merged?

There seems to be a build issue in our workflow that approves PR's. We're working on this atm. Hopefully, when this is resolved, the PR can be merged.

**Comment by Abogical** [comment]
@mergifyio rebase
