### PR TITLE
fic(ecs): fix `fromClusterAttributes`

### LINKED ISSUE #2631: Using VPC in Cluster with CDK 0.32.0 does not work: Error: There are no 'Private' subnets in this VPC. Use a different VPC subnet selection
In CDK 0.31.0 our stack looked like this:

```
const vpcProps: ec2.VpcNetworkImportProps = {
  vpcId: 'vpc-xxxx',
  availabilityZones: ['eu-central-1a', 'eu-central-1b', 'eu-central-1c'],
  publicSubnetIds: ['subnet-xxxx', 'subnet-xxxx', 'subnet-xxxx'],
  privateSubnetIds: ['subnet-xxxx', 'subnet-xxxx', 'subnet-xxxx'],
};
    const cluster = ecs.Cluster.fromClusterAttributes(this, `Cluster`, {
      clusterName: clusterName,
      vpc: vpcProps,
      securityGroups: [ ]
    });

```

with CDK 0.32.0 we are forced to use a VPC with cluster import:

```
    const cluster = ecs.Cluster.fromClusterAttributes(this, `Cluster`, {
      clusterName: clusterName,
      vpc: vpcProps,
      securityGroups: [ ]
    });
```

which causes an error `Error: There are no 'Private' subnets in this VPC. Use a different VPC subnet selection.`

Somehow the cluster seems to lose the specified private subnets with this new model. Is there any workaround for this functionality?

### PR DESCRIPTION
**Pull request by rix0rrr**
Remove unnecessary import.

Fixes #2631.

----

### Pull Request Checklist

* [ ] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [ ] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
  - __Design__: For significant features, design document added to `design` folder
* [ ] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [ ] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-ecs/lib/cluster.ts [hunk 1]
```diff
@@ -394,7 +394,7 @@ class ImportedCluster extends Construct implements ICluster {
   constructor(scope: Construct, id: string, props: ClusterAttributes) {
     super(scope, id);
     this.clusterName = props.clusterName;
-    this.vpc = ec2.Vpc.fromVpcAttributes(this, "vpc", props.vpc);
```
Comment (eladb) [inline packages/@aws-cdk/aws-ecs/lib/cluster.ts]: How did `fromVpcAttributes` accept `IVpc`? Structural typing?

**Comment by eladb** [comment]
Test?

File: packages/@aws-cdk/aws-ecs/lib/cluster.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-ecs/lib/cluster.ts]: Yep.
