### PR TITLE
fix(events): allow adding same target to rule multiple times

### LINKED ISSUE #3173: Permission check in aws-events-targets does not work with singleton functions
* **I'm submitting a ...**
  - [x] :beetle: bug report

* **What is the current behavior?**

When working with singleton functions as rule targets, the following check (L33) will always return `true` (`this.handler.node` has no children for singleton functions):
https://github.com/awslabs/aws-cdk/blob/cd1b16f42abca205f3ab6ab1fafd92a4d043a3e3/packages/%40aws-cdk/aws-events-targets/lib/lambda.ts#L27-L39

This is because singleton functions create a new function attached on the stack and add permissions to this created function:
https://github.com/awslabs/aws-cdk/blob/cd1b16f42abca205f3ab6ab1fafd92a4d043a3e3/packages/%40aws-cdk/aws-lambda/lib/singleton-lambda.ts#L61-L74

This results in `There is already a Construct with name ...` error messages.

* **What is the expected behavior (or behavior of feature suggested)?**
Permission constructs with same ids should not be created.

* **What is the motivation / use case for changing the behavior or adding this feature?**
It's a common case to have singleton functions as targets for events

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.36.0
  - Module Version: 0.36.0
  - OS: all
  - Language: all

### PR DESCRIPTION
**Pull request by jogold**
As rule targets can have different input configurations adding the same target multiple times
must be possible.

Move rule target id generation to `aws-events` where it's easy to simply increment a counter. This
id is passed as an argument to `bind()` for targets that need to know their given id (e.g. `EcsTask`).

Add `permissionsNode` on `IFunction` to handle permission checks for both functions and singleton
functions.

Fixes #3173

----

Please read the [contribution guidelines](https://github.com/awslabs/aws-cdk/blob/master/CONTRIBUTING.md) and follow the pull-request checklist.

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-events/lib/rule.ts [hunk 1]
```diff
@@ -127,14 +127,11 @@ export class Rule extends Resource implements IRule {
   public addTarget(target?: IRuleTarget) {
     if (!target) { return; }
 
-    const targetProps = target.bind(this);
-    const id = sanitizeId(targetProps.id);
-    const inputProps = targetProps.input && targetProps.input.bind(this);
+    // Simply increment id for each `addTarget` call. This is guaranteed to be unique.
+    const id = `Target${this.targets.length}`;
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-events/lib/rule.ts]: I'm not sure this will work correctly if we update a list of 2 elements to a list of 2 different elements.

I believe what will happen is CloudFormation will call `addTarget("Rule1", { ... })` (the new Rule1), and then `removeTarget("Rule1")` (intending to remove the old rule1).

Anything that depends on addition order is super scary to me. I'd rather have a different consistent way of generating IDs.

Comment (rix0rrr) [reply packages/@aws-cdk/aws-events/lib/rule.ts]: Either an optional "id" field on every target that can be used in lieu of the default id, or we hash in the target configuration to make the ID unique.

Comment (jogold) [reply packages/@aws-cdk/aws-events/lib/rule.ts]: Are you sure? CF will likely use [PutTargets](https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_PutTargets.html) which updates everything in one go?

Comment (jogold) [reply packages/@aws-cdk/aws-events/lib/rule.ts]: OK I get what you mean, let's hash the configuration.

Comment (jogold) [reply packages/@aws-cdk/aws-events/lib/rule.ts]: How do you suggest passing the id to the `EcsTask` target (which needs the id for its `AwsCustomResource`) if we hash it in `aws-events` after receiving the full configuration?

Comment (jogold) [reply packages/@aws-cdk/aws-events/lib/rule.ts]: > I'm not sure this will work correctly if we update a list of 2 elements to a list of 2 different elements.

Actually I tested this and it works fine. If this was the case we would already have a problem with the current implementation because when you change a target configuration (let's say `message` for `targets.SnsTopic`) you are basically updating the target but keeping the same id. Rule targets are not CF resources by themselves, they are properties of `AWS::Events::Rule`.

You can try the following:
First depoy:
```ts
event.addTarget(new targets.SqsQueue(queue));
event.addTarget(new targets.SnsTopic(topic));
```
Second deploy:
```ts
event.addTarget(new targets.SnsTopic(topic));
event.addTarget(new targets.SqsQueue(queue));
```
After second deploy targets are correctly inverted.

Let me know if you still think that the id generation should be updated.

Comment (rix0rrr) [reply packages/@aws-cdk/aws-events/lib/rule.ts]: Why do they have an ID then... :x

**Comment by rix0rrr** [comment]
Oh well I guess this breaks API compatibility now.

```
err  - METHOD @aws-cdk/aws-events-targets.CodeBuildProject.bind: returns @aws-cdk/aws-events.RuleTargetConfig: formerly required property 'id' is missing in @aws-cdk/aws-events.RuleTargetConfig [change-return-type:@aws-cdk/aws-events-targets.CodeBuildProject.bind]
```

**Comment by jogold** [comment]
This rather technical/internal... what do you suggest?

**Comment by rix0rrr** [comment]
I have to context switch to get back into it... but offhand: `id` can't be removed. So can you make it so that it is used if nonempty, and the new behavior applies if the string is empty?

Not as good as an optional `id` field, but it'll have to do.

**Comment by jogold** [comment]
@rix0rrr this is now non breaking.

(shouldn't `jsii-diff` consider a change from required to optional as non breaking?)

**Comment by rix0rrr** [comment]
> (shouldn't `jsii-diff` consider a change from required to optional as non breaking?)

Not if the field is on a struct that is *returned* from a function. Consider the following:

```ts
interface OutputStruct {
  value: string;
}

const struct : OutputStruct = giveMeTheStruct();
functionThatExpectsAString(struct.value);
```

Now change `value` to be optional -- the code breaks! It used to be able to expect that `value` was always there, but that's no longer true.

**Comment by rix0rrr** [comment]
After merging it it broke `master`, so I undid the merge and revived the PR here: https://github.com/aws/aws-cdk/pull/3352

**Comment by rix0rrr** [comment]
This is a better pR: https://github.com/aws/aws-cdk/pull/3353
