### PR TITLE
fix(s3-deployment): updating memoryLimit or vpc results in stack update failure

### LINKED ISSUE #7128: Updating a BucketDeployment's memoryLimit causes stack update failure
Changing the `memoryLimit` of an existing `BucketDeployment` (`@aws-cdk/aws-s3-deployment`) causes the CloudFormation deploy of the update to fail with the error "Modifying service token is not allowed."

### Reproduction Steps

Create a bucket deployment:

```
const deployment = new BucketDeployment(this, 'BucketDeployment', {
  destinationBucket: myDestinationBucket,
  sources: [Source.bucket(myBucket, myS3Obj)],
});
```

Then add `memoryLimit: 1792,` (for example) to its properties and redeploy. The CFN changeset will fail to deploy and rollback.

### Error Log

CloudFormation reports the error "Modifying service token is not allowed." for the "BucketDeploymentCustomResource."

### Environment

  - **CLI Version      :** 1.30
  - **Framework Version:** 1.23
  - **OS               :** Mac/Linux
  - **Language         :** Typescript

### Workaround

For anyone struggling with this issue, here's how I worked around the problem:

1. Remove your bucket deployment construct.
2. Deploy to all environments. The contents of the S3 bucket might be stale momentarily, but they aren't deleted or anything.
3. Add it back with the correct `memoryLimit`.
4. Deploy to all environments.

In retrospect, just changing the construct name (add `2` to the end or something) to destroy the old and create the new would **probably** also have worked. I haven't tested that.

### Other

I noticed this was noted on the original pull request by someone else as well: https://github.com/aws/aws-cdk/pull/4204#issuecomment-584770041

### Additional request

I strongly believe the default `memoryLimit` should be set to 1792, which is the documented number for a full vCPU for a Lambda.

Our experience with even a small 2MB zip file showed we had a 40s deploy at 128 MB and a 3s deploy at 1792 MB. That's 13X faster at 14X resources, a basically linear speedup, which means it's nearly free in terms of cost. I strongly believe there's no reason whatsoever for this lambda to ever have a smaller memory limit, which means this is a very bad default.

Of course, to safely update that default, this bug needs fixing first. Otherwise everyone's deploy will fail.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by corymhall**
This fixes the issue where updating the memoryLimit or vpc of the
BucketDeployment resource would result in a stack update failure. In
order to fix this the ID of the BucketDeployment CustomResource includes
info on the memoryLimit and vpc in the same way that the Lambda function
does. This means that when either of these values are updated, the
BucketDeployment CustomResource will be recreated along with the Lambda
function.

If anyone is setting `retainOnDelete=false` (default is `true`) then
this change would result in the data in the bucket being deleted. In
order to avoid this scenario, this PR introduces a bucket tag that
controls whether or not a BucketDeployment resource can delete data from
the bucket.

The BucketDeployment resource will now add a tag to the deployment
bucket with a format like `aws-cdk:cr-owned:{keyPrefix}:{uniqueHash}`.
For example:

```
{
  Key: 'aws-cdk:cr-owned:deploy/here/:240D17B3',
  Value: 'true',
}
```

Each bucket+keyPrefix can be "owned" by 1 or more BucketDeployment
resources. Since there are some scenarios where multiple BucketDeployment
resources can deploy to the same bucket and key prefix
(e.g. using include/exclude) we also append part of the id to
make the key unique.

As long as a bucket+keyPrefix is "owned" by a BucketDeployment
resource, another CR cannot delete data. There are a couple of
scenarios where this comes into play.

1. If the LogicalResourceId of the CustomResource changes
(e.g. memoryLimit is updated) CloudFormation will first issue a 'Create'
to create the new CustomResource and will update the Tag on the bucket.
CloudFormation will then issue a 'Delete' on the old CustomResource
and since the new CR "owns" the Bucket+keyPrefix (indicated by the
presence of the tag), the old CR will not delete the contents of the bucket

2. If the BucketDeployment resource is deleted _and_ it is the only CR
for that bucket+keyPrefix then CloudFormation will first remove the tag
from the bucket and then issue a "Delete" to the CR. Since there are no
tags indicating that this bucket+keyPrefix is "owned" then it will delete
the contents.

3. If the BucketDeployment resource is deleted _and_ it is *not* the only
CR for that bucket:keyPrefix then CloudFormation will first remove the tag
from the bucket and then issue a "Delete" to the CR.
Since there are other CRs that also "own" that bucket+keyPrefix
(indicated by the presence of tags), there will
still be a tag on the bucket and the contents will not be removed. The
contents will only be removed after _all_ BucketDeployment resource that
"own" the bucket+keyPrefix have been removed.

4. If the BucketDeployment resource _and_ the S3 Bucket are both removed,
then CloudFormation will first issue a "Delete" to the CR and since there
is a tag on the bucket the contents will not be removed. If you want the
contents of the bucket to be removed on bucket deletion, then
`autoDeleteObjects` property should be set to true on the Bucket.

Scenario 3 & 4 are changes to the existing functionality in that they
now do *not* delete data in some scenarios when they did previously.

fixes #7128

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts [hunk 1]
```diff
@@ -15,6 +15,8 @@ import { ISource, SourceConfig } from './source';
 // eslint-disable-next-line no-duplicate-imports, import/order
 import { Construct as CoreConstruct } from '@aws-cdk/core';
 
+// tag value has a limit of 256 characters
```
Comment (otaviomacedo) [inline packages/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts:18]: But this is part of the _key_, which is limited to 128 characters. In any case, how do you enforce this limit, given that the `destinationKeyPrefix` property doesn't seem to have any length constraint?

Comment (corymhall) [reply packages/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts]: Good call. I added some validation which will throw an error if the tag key is > 128 characters (`destinationKeyPrefix` can't be > 104 characters). That is a _very_ long key prefix so I don't think we will ever hit that limit, but I also can't think of a better way of handling this.

**Review by otaviomacedo — APPROVED** [review]
