### PR TITLE
fix(cloudwatch): cannot create Alarms from labeled metrics that start with a digit

### LINKED ISSUE #13434: (Cloudwatch): Metrics with labels can't be used in alarms for API Gateway metrics
Just getting this with v1.92 (worked fine <=1.91)
updating Cloudwatch alarm yields: `Invalid metrics list (Service: AmazonCloudWatch; Status Code: 400; Error Code: ValidationError`

### Reproduction Steps

```python
alarm = metric.create_alarm(
            self,
            id=id_alarm,
            alarm_description=kwargs['alarm_description'],
            threshold=kwargs['threshold'],
            period=core.Duration.minutes(kwargs['period_in_minutes']),
            comparison_operator=cw.ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD,
            evaluation_periods=kwargs['evaluation_periods'],
            statistic=kwargs['statistic']
        )
```
these are the parameters I'm passing to it:
```
{
        "metric_name": "5XXError",
        "label": "HTTP 5XX",
        "statistic": "sum",
        "color": "#d62728",
        "period_in_minutes": 1,
        "alarm": {
          "alarm_description": "5XX at 1 threshold",
          "threshold": 1,
          "period_in_minutes": 5,
          "evaluation_periods": 1,
          "statistic": "sum"
        }
}
```
### What did you expect to happen?

a Cloudwatch alarm resource created/updated

### What actually happened?

```bash
UPDATE_FAILED        | AWS::CloudWatch::Alarm     |  
Invalid metrics list (Service: AmazonCloudWatch; Status Code: 400; Error Code: ValidationError;
```

### Environment

  - **CDK CLI Version  : 1.92**
  - **Framework Version: 1.92**
  - **Node.js Version: 10** 
  - **OS : amazonlinux2-x86_64-standard:1.0**
  - **Language (Version): Python (3.7)** 

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by BLasan**
fixes #13434

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by BLasan** [comment]
@rix0rrr @NetaNir Please review

File: packages/@aws-cdk/aws-cloudwatch/lib/alarm.ts [hunk 1]
```diff
@@ -283,7 +283,7 @@ export class Alarm extends AlarmBase {
                 stat: stat.statistic,
                 unit: stat.unitFilter,
               },
-              id: stat.metricName,
+              id: id,
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-cloudwatch/lib/alarm.ts:286]:
```suggestion
              id,
```

Otherwise the linter will yell at you

Comment (BLasan) [reply packages/@aws-cdk/aws-cloudwatch/lib/alarm.ts:286]: My bad. Thanks for pointing me out :)

**Review by rix0rrr — APPROVED** [review]
