### PR TITLE
fix(rds): read replica instance cannot join domain

### LINKED ISSUE #18786: (rds): Read Replica cannot join kerberos domain
### What is the problem?

When creating a [`rds.DatabaseInstanceReadReplica`](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_rds/DatabaseInstanceReadReplica.html), while it accepts `domain` and `domain_role` parameters, it does not accept an `engine` parameter. 

Then deployment fails with 
> To use Domain, you must provide an eligible SQL Server, Oracle, or Postgres engines

### Reproduction Steps

```python
 vpc: ec2.Vpc

# source_instance: rds.DatabaseInstance

rds.DatabaseInstanceFromSnapshot(self, "Instance",
    snapshot_identifier="my-snapshot",
    engine=rds.DatabaseInstanceEngine.postgres(version=rds.PostgresEngineVersion.VER_12_3),
    vpc=vpc
)
instance = rds.DatabaseInstanceReadReplica(self, "ReadReplica",
    source_database_instance=source_instance,
    instance_type=ec2.InstanceType.of(ec2.InstanceClass.BURSTABLE2, ec2.InstanceSize.LARGE),
    vpc=vpc,
    domain='my-domain',
    domain_role=my_domain_role
)
assert instance.engine is None
```

### What did you expect to happen?

Initially, suspected it would inherit the engine from the referenced database; or at least be able to provide an engine

### What actually happened?

Could not join the domain
> To use Domain, you must provide an eligible SQL Server, Oracle, or Postgres engines

### CDK CLI Version

2.9.0

### Framework Version

_No response_

### Node.js Version

14.15.1

### OS

Ubuntu 18

### Language

Python

### Language Version

3.7

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jogold**
The read replica instance always uses the same engine as the source instance
but some CF validations require the engine to be explicitely passed when some
properties are specified.

Pass the `engine` property to the CF resource if `domain` is specified.

Closes #18786

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-rds/lib/instance.ts [hunk 1]
```diff
@@ -1171,12 +1171,20 @@ export class DatabaseInstanceReadReplica extends DatabaseInstanceNew implements
       throw new Error(`Cannot set 'backupRetention', as engine '${engineDescription(props.sourceDatabaseInstance.engine)}' does not support automatic backups for read replicas`);
     }
 
+    // The read replica instance always uses the same engine as the source instance
+    // but some CF validations require the engine to be explicitely passed when some
+    // properties are specified.
+    let shouldPassEngine = anyDefined(
```
Comment (jogold) [inline packages/@aws-cdk/aws-rds/lib/instance.ts:1177]:
```suggestion
    const shouldPassEngine = anyDefined(
```

File: packages/@aws-cdk/aws-rds/lib/instance.ts [hunk 2]
```diff
@@ -1171,12 +1171,20 @@ export class DatabaseInstanceReadReplica extends DatabaseInstanceNew implements
       throw new Error(`Cannot set 'backupRetention', as engine '${engineDescription(props.sourceDatabaseInstance.engine)}' does not support automatic backups for read replicas`);
     }
 
+    // The read replica instance always uses the same engine as the source instance
+    // but some CF validations require the engine to be explicitely passed when some
+    // properties are specified.
+    const shouldPassEngine = anyDefined(
+      props.domain,
+    );
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/instance.ts:1179]: How about just

```suggestion
    const shouldPassEngine = props.domain != null;
```

?

File: packages/@aws-cdk/aws-rds/test/instance.test.ts [hunk 3]
```diff
@@ -1617,6 +1617,31 @@ describe('instance', () => {
...
+      vpc,
+      domain: 'my-domain',
+    });
+
+    // THEN
+    Template.fromStack(stack).hasResourceProperties('AWS::RDS::DBInstance', {
+      SourceDBInstanceIdentifier: Match.anyValue(),
+      Engine: 'postgres',
+    });
+  });
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/test/instance.test.ts:1644]: I wonder... since this is a CFN validation, do we need a new small integration test for this, to confirm it deploys?

**Review by skinny85 — COMMENTED** [review]
Thanks for the fix @jogold!

Two small comments/questions.

File: packages/@aws-cdk/aws-rds/lib/instance.ts (hunk 2 above)
Comment (jogold) [reply packages/@aws-cdk/aws-rds/lib/instance.ts:1179]: Yeah ok, this was just in case we wanted to easily add other props later that also require engine to be passed.

File: packages/@aws-cdk/aws-rds/test/instance.test.ts (hunk 3 above)
Comment (jogold) [reply packages/@aws-cdk/aws-rds/test/instance.test.ts:1644]: Ideally yes but it's complicated because it means we need to create a domain using L1 resources from `@aws-cdk/aws-directoryservice`...

(`domain` is currently a `string` but could have been a `IDirectory` if we had L2 resources for this)

Comment (skinny85) [reply packages/@aws-cdk/aws-rds/test/instance.test.ts:1644]: OK.

**Review by skinny85 — APPROVED** [review]
Thanks @jogold, awesome work as always 🙂.
