### PR TITLE
fix(dynamodb): allow using PhysicalName.GENERATE_IF_NEEDED as the Table name

### LINKED ISSUE #9374: [aws-dynamodb] when setting PhysicalName.GENERATE_IF_NEEDED to tableName, throwing error `Invalid physical name passed to CloudFormation. Use "this.physicalName" instead`
Hi team, I'm trying to do a cross-env reference on a ddb table. After I specify the tableName to PhysicalName.GENERATE_IF_NEEDED, synthesizing process breaks. 

The error message says:
```
Error: Resolution error: Invalid physical name passed to CloudFormation. Use "this.physicalName" instead.
```
I suspect this is a bug, as my experiment on a cross-env referenced IAM role works just fine with PhysicalName.GENERATE_IF_NEEDED (not included in the example below)

And I think this error message is confusing. I have no idea what to do with this message. Any context how should I interpret it?

### Reproduction Steps

here is an example I used: https://github.com/flyingImer/cdk-mkii

`cdk synth` breaks even without `SomeStack` referencing to the ddb table defined in `CdkMkiiStack`

### Error Log

```
Error: Resolution error: Invalid physical name passed to CloudFormation. Use "this.physicalName" instead.
    at GeneratedWhenNeededMarker.resolve (/Users/Can/ws-local/github/cdk-mkii/node_modules/@aws-cdk/core/lib/private/physical-name-generator.ts:89:11)
    at DefaultTokenResolver.resolveToken (/Users/Can/ws-local/github/cdk-mkii/node_modules/@aws-cdk/core/lib/resolvable.ts:134:24)
    at resolve (/Users/Can/ws-local/github/cdk-mkii/node_modules/@aws-cdk/core/lib/private/resolve.ts:133:29)
    at Object.resolve [as mapToken] (/Users/Can/ws-local/github/cdk-mkii/node_modules/@aws-cdk/core/lib/private/resolve.ts:49:32)
    at TokenizedStringFragments.mapTokens (/Users/Can/ws-local/github/cdk-mkii/node_modules/@aws-cdk/core/lib/string-fragments.ts:71:33)
    at DefaultTokenResolver.resolveString (/Users/Can/ws-local/github/cdk-mkii/node_modules/@aws-cdk/core/lib/resolvable.ts:155:22)
    at resolve (/Users/Can/ws-local/github/cdk-mkii/node_modules/@aws-cdk/core/lib/private/resolve.ts:91:31)
    at Object.resolve (/Users/Can/ws-local/github/cdk-mkii/node_modules/@aws-cdk/core/lib/private/resolve.ts:49:32)
    at Object.resolve (/Users/Can/ws-local/github/cdk-mkii/node_modules/@aws-cdk/core/lib/private/resolve.ts:155:39)
    at CdkMkiiStack.resolve (/Users/Can/ws-local/github/cdk-mkii/node_modules/@aws-cdk/core/lib/stack.ts:363:12)
```

### Environment

  - **CLI Version      :** 1.55.0 (build 48ccf09)
  - **Framework Version:** 1.55.0
  - **Node.js Version:** v12.16.2
  - **OS               :** macOS 10.15.6
  - **Language (Version):**  TypeScript

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by skinny85**
Fixes #9374

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-dynamodb/lib/table.ts [hunk 1]
```diff
@@ -913,15 +913,15 @@ export class Table extends TableBase {
...
-    if (props.tableName) { this.node.addMetadata('aws:cdk:hasPhysicalName', props.tableName); }
-
     this.tableArn = this.getResourceArnAttribute(this.table.attrArn, {
       service: 'dynamodb',
       resource: 'table',
       resourceName: this.physicalName,
     });
     this.tableName = this.getResourceNameAttribute(this.table.ref);
 
+    if (props.tableName) { this.node.addMetadata('aws:cdk:hasPhysicalName', this.tableName); }
```
Comment (NetaNir) [inline packages/@aws-cdk/aws-dynamodb/lib/table.ts:923]: For my own understanding, what is this? This is the only place in the CDK this pattern is used

Comment (skinny85) [reply packages/@aws-cdk/aws-dynamodb/lib/table.ts:923]: I think this was an old idea to mark things with physical names set explicitly in our L2s. I don't think it was adapted widely.

Comment (NetaNir) [reply packages/@aws-cdk/aws-dynamodb/lib/table.ts:923]: >I don't think it was adapted widely.
Screen Shot 2020-08-03 at 8 02 06 AM
