### PR TITLE
fix(codecommit): add a Repository.fromRepositoryName() method

### LINKED ISSUE #2514: CodeCommit's Repository is missing a fromRepositoryName method
It was apparently missed when doing the `import` -> `fromXyz` conversion.

### PR DESCRIPTION
**Pull request by skinny85**
Fixes #2514

----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
  - __Design__: For significant features, design document added to `design` folder
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by skinny85** [comment]
Added some tests, because I felt bad.

File: packages/@aws-cdk/aws-codecommit/lib/repository.ts [hunk 1]
```diff
@@ -263,6 +261,37 @@ export class Repository extends RepositoryBase {
...
+        return {
+          repositoryArn: this.repositoryArn,
+          repositoryName: this.repositoryName,
+        };
+      }
+    }
+
+    return new Import(scope, id);
+  }
+
```
Comment (eladb) [inline packages/@aws-cdk/aws-codecommit/lib/repository.ts]: Change these to free floating functions.
