### PR TITLE
fix(opensearchservice): access denied when creating a new domain in regions without cognito support

### LINKED ISSUE #21192: (opensearchservice): Access denied for operation 'You don?t have permissions to integrate with Cognito.
### Describe the bug

In China region, Access denied for operation 'You don?t have permissions to integrate with Cognito. 

### Expected Behavior

create opensearch domain successful ,and without integrate with Cognito.

### Current Behavior

10:18:57 AM | CREATE_FAILED        | AWS::OpenSearchService::Domain | Domain66AC69E0
Resource handler returned message: "Access denied for operation 'You don?t have permissions to integrate with Cognito. Contact your admin if you need help. (Service: OpenSearch, Status Code: 409, Req
uest ID: b040b85a-e421-4a53-b1f0-ec4b89c1f675, Extended Request ID: null)'." (RequestToken: 50a94fb6-80ea-f789-d0af-773b41f90163, HandlerErrorCode: AccessDenied)

 ❌  XXXX-workshop failed: Error: The stack named XXXX-workshop failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Access denied for operation 'You don?t have permissions to integrate with Cognito. Contact your admin if you need help. (Service: OpenSearch, Status Code: 409, Request ID: b040b85a-e421-4a53-b1f0-ec4b89c1f675, Extended Request ID: null)'." (RequestToken: 50a94fb6-80ea-f789-d0af-773b41f90163, HandlerErrorCode: AccessDenied)
    at prepareAndExecuteChangeSet (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:386:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:210:24)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/lib/cli.ts:346:12)

### Reproduction Steps

// In China Region
const domain = new os.Domain(this, 'Domain', {
      domainName: domainName,
      version: os.EngineVersion.OPENSEARCH_1_2,
      capacity: {
        dataNodes: 1,
        dataNodeInstanceType: "t3.small.search",
      },
      ebs: {
        volumeSize: 10,
        volumeType: ec2.EbsDeviceVolumeType.GENERAL_PURPOSE_SSD,
      },
      nodeToNodeEncryption: true,
      encryptionAtRest: {
        enabled: true,
      },
      accessPolicies: [new iam.PolicyStatement({
        actions: ["es:*"],
        principals:[new iam.AccountRootPrincipal()],
        resources: [`arn:${Aws.PARTITION}:es:${Aws.REGION}:${Aws.ACCOUNT_ID}:domain/${domainName}/*`,],
        })],
      removalPolicy: RemovalPolicy.DESTROY,
    });

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.32.1

### Framework Version

_No response_

### Node.js Version

v16.15.1

### OS

MacOS 12.3.1 

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by MikeJamesWhite**
Closes #21192

Currently the `CognitoOptions` attribute is always populated in the CloudFormation output when creating a new OpenSearch Domain, even if `cognitoDashboardsAuth` is not passed into the constructor.

Including this attribute, even with just the default body of `{ "Enabled": false }`, causes deployments to fail in regions where Cognito isn't supported (e.g. `cn-north-1`), with the message: `You don't have permissions to integrate with Cognito. Contact your admin if you need help`. This change fixes this behavior by completely omitting the attribute if `cognitoDashboardsAuth` is not passed into the constructor.

I also updated the package.json file to fix several build warnings, and the README and default Rosetta fixture to fix a build error and make the docs align with the style recommendations in the contribution guidelines.

**NOTE:** Current snapshots are updated after running the integration tests, since the existing templates should no longer have `CognitoOptions` populated. However, the snapshot for the newly added integration test has this attribute populated.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by MikeJamesWhite** [comment]
**Update:** I've sorted out access to an account for running the integration tests, so I'll run them myself and update the PR (reviewer will no longer need to execute them as indicated in the original PR body).

I also found that the documentation currently fails to build a couple of code examples -- dove a bit deeper and noticed that the README is not following the [recommendations from the contributions guide](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#documentation). Since I'm adding to the README in this PR anyway, I'm also going to add a commit to update existing code examples to follow the guidelines, and make them all build successfully in the process.

File: packages/@aws-cdk/aws-opensearchservice/rosetta/default.ts-fixture [hunk 1]
```diff
@@ -1,12 +1,12 @@
...
-import { RemovalPolicy, Stack } from '@aws-cdk/core';  
-import * as opensearch from '@aws-cdk/aws-opensearchservice';
+import { Domain, DomainProps, EngineVersion } from '@aws-cdk/aws-opensearchservice';
+import * as core from '@aws-cdk/core'
 import * as lambda from '@aws-cdk/aws-lambda';
 import * as ec2 from '@aws-cdk/aws-ec2';
 import * as iam from '@aws-cdk/aws-iam';
 
-class Fixture extends Stack {           
+class Fixture extends core.Stack {
```
Comment (TheRealAmazonKendra) [inline packages/@aws-cdk/aws-opensearchservice/rosetta/default.ts-fixture:9]: These updates aren't really necessary.

File: yarn.lock [hunk 2]
```diff
@@ -3256,7 +3256,7 @@ co@^4.6.0:
   resolved "https://registry.npmjs.org/co/-/co-4.6.0.tgz#6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184"
   integrity sha512-QVb0dM5HvG+uaxitm8wONl7jltx8dqhfU33DcqtOZcLSVIKSDDLDi7+0LbAKiyI8hD9u42m2YxXSkMGWThaecQ==
 
-codemaker@^1.62.0, codemaker@^1.63.1:
+codemaker@^1.62.0:
```
Comment (TheRealAmazonKendra) [inline yarn.lock:3259]: No changes to yarn.lock, please.

File: packages/@aws-cdk/aws-opensearchservice/package.json [hunk 3]
```diff
@@ -89,11 +89,25 @@
     "@aws-cdk/integ-runner": "0.0.0",
     "@aws-cdk/cfn2ts": "0.0.0",
     "@aws-cdk/pkglint": "0.0.0",
+    "@aws-cdk/aws-certificatemanager": "0.0.0",
```
Comment (TheRealAmazonKendra) [inline packages/@aws-cdk/aws-opensearchservice/package.json:92]: Why are all these dependencies now necessary? I'm not seeing a change that would have necessitated it.

File: packages/@aws-cdk/aws-opensearchservice/package.json [hunk 4]
```diff
@@ -89,11 +89,25 @@
...
+    "@aws-cdk/aws-cognito": "0.0.0",
+    "@aws-cdk/aws-ec2": "0.0.0",
+    "@aws-cdk/aws-iam": "0.0.0",
+    "@aws-cdk/aws-kms": "0.0.0",
+    "@aws-cdk/aws-logs": "0.0.0",
+    "@aws-cdk/aws-route53": "0.0.0",
+    "@aws-cdk/aws-secretsmanager": "0.0.0",
+    "@aws-cdk/core": "0.0.0",
+    "@aws-cdk/custom-resources": "0.0.0",
+    "@aws-cdk/integ-tests": "0.0.0",
```
Comment (TheRealAmazonKendra) [inline packages/@aws-cdk/aws-opensearchservice/package.json:103]: As far as I can tell, this should be the only additional dependency needed.

File: packages/@aws-cdk/aws-opensearchservice/package.json [hunk 5]
```diff
@@ -115,6 +130,7 @@
     "@aws-cdk/aws-secretsmanager": "0.0.0",
     "@aws-cdk/core": "0.0.0",
     "@aws-cdk/custom-resources": "0.0.0",
+    "@aws-cdk/integ-tests": "0.0.0",
```
Comment (TheRealAmazonKendra) [inline packages/@aws-cdk/aws-opensearchservice/package.json:133]: But not needed here.

**Review by TheRealAmazonKendra — DISMISSED** [review]
Thank you for your contribution. Just a few small comments inline.

File: packages/@aws-cdk/aws-opensearchservice/package.json (hunk 3 above)
Comment (MikeJamesWhite) [reply packages/@aws-cdk/aws-opensearchservice/package.json:92]: Each of these was causing a build warning -- they're not strictly necessary, but it also seemed odd for the build to produce so many warnings.

File: yarn.lock (hunk 2 above)
Comment (MikeJamesWhite) [reply yarn.lock:3259]: Sure, will roll this back (I think it was done automatically by the build and didn't realise it shouldn't be added to the change)

File: packages/@aws-cdk/aws-opensearchservice/rosetta/default.ts-fixture (hunk 1 above)
Comment (MikeJamesWhite) [reply packages/@aws-cdk/aws-opensearchservice/rosetta/default.ts-fixture:9]: While not strictly necessary, I thought it made sense to update it to follow the documentation recommendations in the contribution guidelines. Specifically `Types from other modules should be qualified:` and `Types from the documented module should be un-qualified:`

File: packages/@aws-cdk/aws-opensearchservice/package.json (hunk 5 above)
Comment (MikeJamesWhite) [reply packages/@aws-cdk/aws-opensearchservice/package.json:133]: Is there a guideline of how internal dependencies should be added? From what I can see, it seems to be standard to add them as peerDependencies, but if not added as devDependencies as well then the build produces warnings, which doesn't seem right?

File: yarn.lock (hunk 2 above)
Comment (MikeJamesWhite) [reply yarn.lock]: Rolled back

File: packages/@aws-cdk/aws-opensearchservice/rosetta/default.ts-fixture (hunk 1 above)
Comment (TheRealAmazonKendra) [reply packages/@aws-cdk/aws-opensearchservice/rosetta/default.ts-fixture:9]: If you want to change formatting of the documentation, please do it as a separate PR. Large PRs with changes that get lost in formatting changes will not receive the same level of detailed feedback because it's harder to do with so much extra noise. We certainly don't mind better documentation!

File: packages/@aws-cdk/aws-opensearchservice/package.json (hunk 5 above)
Comment (TheRealAmazonKendra) [reply packages/@aws-cdk/aws-opensearchservice/package.json:133]: hmm. I'm not actually sure if we have this documented anywhere but basically, if it doesn't produce an error, don't add it.

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Additional requested changes still pending.

File: packages/@aws-cdk/aws-opensearchservice/rosetta/default.ts-fixture (hunk 1 above)
Comment (MikeJamesWhite) [reply packages/@aws-cdk/aws-opensearchservice/rosetta/default.ts-fixture:9]: Alright, I'll split it out into a new PR, though this does mean that the documentation build will continue to fail (it was failing before I made any changes due inconsistent use of "Domain" vs "opensearch.Domain" added in previous PRs). 

That being said, in advance I'm just wondering about this: "Rosetta files, however, should not be manually touched". How is it expected to adjust how imports are represented in the documentation without adjusting the Rosetta file? I'm new to this, so may be missing something, but seems like this is necessary?

File: packages/@aws-cdk/aws-opensearchservice/package.json (hunk 5 above)
Comment (MikeJamesWhite) [reply packages/@aws-cdk/aws-opensearchservice/package.json:133]: Alright, will change this back

Comment (MikeJamesWhite) [reply packages/@aws-cdk/aws-opensearchservice/package.json]: After taking a look, I think the warnings may actually be the result of these being declared as both peer dependencies *and* normal dependencies. But I'll check that theory in another PR with the documentation updates.

File: packages/@aws-cdk/aws-opensearchservice/rosetta/default.ts-fixture (hunk 1 above)
Comment (TheRealAmazonKendra) [reply packages/@aws-cdk/aws-opensearchservice/rosetta/default.ts-fixture]: If you're adding new imports it's fine, but the formatting we use for importing from core is consistent across all packages. No lie, I don't know why that's our convention and why we do it that way, but it's pretty consistent and we should keep it that way.

Comment (TheRealAmazonKendra) [reply packages/@aws-cdk/aws-opensearchservice/rosetta/default.ts-fixture]: Also, there's a lot of stuff that we autogenerate in various processes through scripts and JSII. To your point about build failures from previous documentation inconsistency, if it's small, it's fine to include with other stuff but in general I'd just open the PR to make that fix first and then do the code change in a subsequent PR. Doc changes usually get merged pretty fast.

File: packages/@aws-cdk/aws-opensearchservice/package.json (hunk 5 above)
Comment (TheRealAmazonKendra) [reply packages/@aws-cdk/aws-opensearchservice/package.json]: Keep in mind some of why we do these oddities is that we translate these libraries into a half dozen languages and between v1 and v2 structure/conventions. Some of it might not align with what you've seen elsewhere because of that.

**Review by TheRealAmazonKendra — APPROVED** [review]
Looks good now.

File: packages/@aws-cdk/aws-opensearchservice/rosetta/default.ts-fixture (hunk 1 above)
Comment (MikeJamesWhite) [reply packages/@aws-cdk/aws-opensearchservice/rosetta/default.ts-fixture]: Makes sense -- thanks for the feedback!

Comment (TheRealAmazonKendra) [reply packages/@aws-cdk/aws-opensearchservice/rosetta/default.ts-fixture]: So, yes, you can actually update the rosetta file, but you shouldn't change the style of imports. I misspoke earlier when I said they shouldn't be touched at all.
