### PR TITLE
fix(docdb): secret rotation ignores excluded characters in password

### LINKED ISSUE #17347: (aws_docdb): addRotationSingleUser() not consistent with aws_rds.Cluster.addRotationSingleUser()
### What is the problem?

https://docs.aws.amazon.com/cdk/api/latest/docs/aws-rds-readme.html#rotating-credentials describes the `aws_rds.Cluster.addRotationSinglerUser()`, as implemented by aws_docdb there is no support for `excludeCharacters`. And sure enough, I went to update a stack containing a

```
const cluster = aws_docdb.DatabaseCluster(...);
cluster.addRotationSingleUser();
```

and got

```
The parameter MasterUserPassword is not a valid password. Only printable ASCII characters besides '/', '@', '"', ' ' may be used. (Service: AmazonRDS; Status Code:
400; Error Code: InvalidParameterValue; Request ID: 38bc6735-286e-41f2-89d4-3d2c8cb78ef9; Proxy: null)
```

### Reproduction Steps

I'm not sure how to reliably repro this one. The problem, I think, is that the secret rotator generates an illegal password. The deeper problem is that the secret rotator doesn't follow the good example in `aws_rds` and allow for configurable `excludeCharacters`, so there's no simple way to fix this. This might be the root cause of https://github.com/aws/aws-cdk/issues/17288 (I'm imagining if the rotator generates an illegal password and DocDB refuses to accept it).

### What did you expect to happen?

I expect to never have to think about the (unfortunately named) masterUser's password. The rotation should Just Work.

### What actually happened?

First try: (pulled from the CloudFormation console)
``` 
The parameter MasterUserPassword is not a valid password. Only printable ASCII characters besides '/', '@', '"', ' ' may be used. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 38bc6735-286e-41f2-89d4-3d2c8cb78ef9; Proxy: null)
```

Second try: 

```
❯ npx cdk deploy --require-approval never Whiteboard
Deploying to "euDev" in "eu-central-1".
defaultRegion: "eu-central-1"
Whiteboard: deploying...
[0%] start: Publishing 5cc75ebf91260fff71aff7bfd82508a3d015ff54fefac979088541de57bb66ad:414375883647-eu-central-1
[100%] success: Published 5cc75ebf91260fff71aff7bfd82508a3d015ff54fefac979088541de57bb66ad:414375883647-eu-central-1
Whiteboard: creating CloudFormation changeset...

 ❌  Whiteboard failed: Error [ValidationError]: Stack:arn:aws:cloudformation:eu-central-1:414375883647:stack/Whiteboard/ee1bf3f0-3d9a-11ec-9fae-021733604472 is in UPDATE_ROLLBACK_FAILED state and can not be updated.
    at Request.extractError (/Users/ahammond/Documents/ClickUp/whiteboard-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/ahammond/Documents/ClickUp/whiteboard-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/ahammond/Documents/ClickUp/whiteboard-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/ahammond/Documents/ClickUp/whiteboard-cdk/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/Users/ahammond/Documents/ClickUp/whiteboard-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/ahammond/Documents/ClickUp/whiteboard-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/ahammond/Documents/ClickUp/whiteboard-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/ahammond/Documents/ClickUp/whiteboard-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/ahammond/Documents/ClickUp/whiteboard-cdk/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/Users/ahammond/Documents/ClickUp/whiteboard-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2021-11-05T01:17:48.814Z,
  requestId: '8ec0b437-4a02-41df-8637-5e698c28e3b5',
  statusCode: 400,
  retryable: false,
  retryDelay: 30.455530850638013
}
Stack:arn:aws:cloudformation:eu-central-1:414375883647:stack/Whiteboard/ee1bf3f0-3d9a-11ec-9fae-021733604472 is in UPDATE_ROLLBACK_FAILED state and can not be updated.
```

### CDK CLI Version

2.0.0-rc.27 (build 435e6f6)

### Framework Version

2.0.0-rc.27 (build 435e6f6)

### Node.js Version

v14.17.5

### OS

MacOS

### Language

Typescript

### Language Version

4.4.4

### Other information

_No response_

### LINKED ISSUE #17575: (docdb): Secretrotation can generate Secrets that are not accepted by cloudformation
### What is the problem?

Changing properties of a deployed DocDB may fail, because the rotated secret contains characters, that cloudformation won't accept (even if they are "accepted" and rotated by the secret rotation).

```bash
   1/30 |5:59:20 PM | UPDATE_FAILED        | AWS::DocDB::DBCluster                       | my-beautifull-database/Database (Database123456789) The parameter MasterUserPassword is not a valid password. Only printable ASCII characters besides '/', '@', '"', ' ' may be used. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterValue; Request ID:  ...)
```

The password did contain an ```@```

### Reproduction Steps

Create a database with CDK and activate secret rotation single user ... after a while and some secret rotations you will maybe find a situation where neither update nor rollback will succeed... because cloudformation won't accept the password.

### What did you expect to happen?

Create a database with CDK and activate secret rotation single user ... after a while and some secret rotations you will maybe find a situation where neither update nor rollback will succeed... because cloudformation won't accept the password.

### What actually happened?

Cloudformation was not able to update - Rollback failed also

### CDK CLI Version

1.121

### Framework Version

_No response_

### Node.js Version

12

### OS

mac

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by markussiebert**
We need to pass whatever `excludeCharacters` were passed to the generated Secret to the application responsible for the rotation.

Fixes #17347
Fixes #17575 

------

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-docdb/lib/database-secret.ts [hunk 1]
```diff
@@ -68,8 +77,10 @@ export class DatabaseSecret extends Secret {
           masterarn: props.masterSecret?.secretArn,
         }),
         generateStringKey: 'password',
-        excludeCharacters: props.excludeCharacters ?? '"@/',
+        excludeCharacters: excludedCharacters,
       },
     });
+
+    this.excludedCharacters = excludedCharacters;
```
Comment (skinny85) [inline packages/@aws-cdk/aws-docdb/lib/database-secret.ts:84]: We can simplify this code:

```ts
  constructor(scope: Construct, id: string, props: DatabaseSecretProps) {
    this.excludedCharacters = props.excludeCharacters ?? '"@/';

    super(scope, id, {
      // ...
        excludeCharacters: this.excludedCharacters,
      },
    });
```

File: packages/@aws-cdk/aws-docdb/lib/database-secret.ts [hunk 2]
```diff
@@ -48,7 +48,16 @@ export interface DatabaseSecretProps {
...
  */
 export class DatabaseSecret extends Secret {
+
+  /**
+   * the excluded characters for this Secret
+   */
+  readonly excludedCharacters: string;
+
   constructor(scope: Construct, id: string, props: DatabaseSecretProps) {
+
```
Comment (skinny85) [inline packages/@aws-cdk/aws-docdb/lib/database-secret.ts:58]: No need for this empty line.

File: packages/@aws-cdk/aws-docdb/lib/database-secret.ts [hunk 3]
```diff
@@ -48,7 +48,16 @@ export interface DatabaseSecretProps {
  * @resource AWS::SecretsManager::Secret
  */
 export class DatabaseSecret extends Secret {
+
+  /**
+   * the excluded characters for this Secret
+   */
+  readonly excludedCharacters: string;
```
Comment (skinny85) [inline packages/@aws-cdk/aws-docdb/lib/database-secret.ts:55]: Missing `public`?

**Review by skinny85 — CHANGES_REQUESTED** [review]
Looks good @markussiebert, but I have some questions 🙂.

File: packages/@aws-cdk/aws-docdb/lib/cluster.ts [hunk 4]
```diff
@@ -293,6 +293,11 @@ export class DatabaseCluster extends DatabaseClusterBase {
    */
   public readonly secret?: secretsmanager.ISecret;
 
+  /**
+   * The secret attached to this cluster
+   */
+  public readonly databaseSecret?: DatabaseSecret | undefined;
```
[the remark this answers is not in the document]
Comment (markussiebert) [reply packages/@aws-cdk/aws-docdb/lib/cluster.ts:299]: the secret itself was not enough. We need the DatabaseSecret, because only it has the excludeCharacters property. But I think, we can change the type of the secret instead.

File: packages/@aws-cdk/aws-docdb/lib/database-secret.ts [hunk 5]
```diff
@@ -36,7 +36,7 @@ export interface DatabaseSecretProps {
   /**
    * Characters to not include in the generated password.
    *
-   * @default "\"@/"
+   * @default '\"@/'
```
[the remark this answers is not in the document]
Comment (markussiebert) [reply packages/@aws-cdk/aws-docdb/lib/database-secret.ts:39]: ok

File: packages/@aws-cdk/aws-docdb/lib/database-secret.ts (hunk 1 above)
Comment (markussiebert) [reply packages/@aws-cdk/aws-docdb/lib/database-secret.ts:84]: no we can not ;-) at least I cannot access this before the super call?
But I need this variable inside the super call ... so kind of chicken or the egg problem?

That was the reason I firs assigned the default to a const and later made it accessible in the scope of the class.

**Comment by skinny85** [comment]
Also, we're missing a new unit test for the non-default case.

File: packages/@aws-cdk/aws-docdb/lib/database-secret.ts (hunk 3 above)
Comment (markussiebert) [reply packages/@aws-cdk/aws-docdb/lib/database-secret.ts:55]: yes! I was just wondering why it works ... but it seams as if public is TS default... but setting it public in the code is better!

File: packages/@aws-cdk/aws-docdb/lib/database-secret.ts (hunk 2 above)
Comment (markussiebert) [reply packages/@aws-cdk/aws-docdb/lib/database-secret.ts:58]: Yes!

File: packages/@aws-cdk/aws-docdb/lib/cluster.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (markussiebert) [reply packages/@aws-cdk/aws-docdb/lib/cluster.ts]: > Also, we're missing a new unit test for the non-default case.

Do we? There is no logic handling a custom excludeCharacters string so I thought testing / ensuring that excludeCharacters inside the secret and the secretrotation match would be enough. Just my thoughts

**Comment by skinny85** [comment]
> the secret itself was not enough. We need the DatabaseSecret, because only it has the excludeCharacters property.
>
> I tried to. change it to DatabaseSecret and assign it directly, not via attachSecret, but then it would be a breaking change the tests showed:
>
> ```
> "SecretId": {
>          "Ref": "DatabaseSecretAttachmentE5D1B020"
>        },
> ```
> 
> would change to
>
> ```
> "SecretId": {
> "Ref": "DatabaseSecret3B817195"
> },
> ```

What you want to do is create a new, private field, of type `DatabaseSecret`. Remove the public `secret` field, replacing it with a getter that returns the above private field, just the declared type of the getter is `Secret`, not `DatabaseSecret`.

Presto, you have only one field.

**Comment by skinny85** [comment]
@markussiebert Thinking about it some more, can't you just save the `excludedCharacters` in a `private` `readonly` field, instead of the entire `DatabaseSecret`? That will be much simpler, and will also mean you won't have to make any changes to the  `DatabaseSecret`.

What do you think?

**Comment by markussiebert** [comment]
@skinny85 I think I don't understand the problem that we are trying to solve.

Ok, if I introduce the ```exculdedCharacters``` private readonly field on cluster class level, i would to something like

```ts
private readonly excludedCharacters: string;

// than in the constructor

this.excludedCharacters = props.masterUser.excludeCharacters ?? '"@/';

// and later on pass this to the created secret...
if (!props.masterUser.password) {
      this.secret = new DatabaseSecret(this, 'Secret', {
        username: props.masterUser.username,
        encryptionKey: props.masterUser.kmsKey,
        excludeCharacters: this.excludedCharacters,
        secretName: props.masterUser.secretName,
      });
    }
```

This solution would lead to duplicated "default values" for excluded Characters in the DatabaseSecret. My opinion: not good. The defaults for the secret should be set on secret creation and be accessible for further use, not be hold redundant in 2 variables.

Then: there was already a variable containing the secret. I don't understand why it was a constructor local variable until know and only the ISecret from the ```attach``` call was written to the ```private readonly secret?```. It would be better to write the secret to this and only attach it? It only contains a small subset of the properties already known. And the original Secret Resource would have satisfied the interface.

Ok, just looking at the two cases:
 
In my PR I there are the following changes

the ``` let secret = ...``` converted to ```private readonly databaseSecret ...``` so no new variable - "only" a shift in scope? still not accessible from the outside. Not changing any API.

I added a public readonly field for the DatabaseSecret, allowing to read its excludedCharacters from the outside. I think it's a small change in the api, but not causing any damage.

Your suggestion would 

still leave the ```let secret = ...``` part, but won't enforce the shift to the class scope

introduce a new variable excludedCharacters at the cluster scope - still private, but it's new variable (but is this better than making the databaseSecret accessible at class scope that was still there?)

this new variable has to be filled, so there are 2 options:
a) set them with the same default as the DatabaseSecret
b) remove the default from the DatabaseSecret and pass in every case the excluded characters - that get their default value inside the cluster - to the database secret.

I think for consistency we have to chose b and therefore touch the DatabaseSecret.

All in all - I still like my PR more than your suggestion. As already mentioned - I didn't introduced new variables - only moved the constructor variable secret to the class scope (as databasesecret). And still don't understand why this was done:

https://github.com/aws/aws-cdk/blob/ddf2881ee24cbf3083463a6e772a5c91acc229aa/packages/%40aws-cdk/aws-docdb/lib/cluster.ts#L402

The secret could have been stored the whole time in the class variable secret instead of only storing the secretattachment?
I only tried to make the change non breaking. I would like to handle the database secret as the secret - but this would cause a breaking change that cloudformation could not handle.

**Comment by markussiebert** [comment]
I don't like the idea holding redundant information (as i would, if i introduce a second string).

I don't understand the problem with the DatabaseSecret moving from the constructor to the class scope to be accessed later.  I would have build it like this from the beginning... but now problem.

So i created a new "try" ... what do you think about this?

**Review by skinny85 — DISMISSED** [review]
> I don't like the idea holding redundant information (as i would, if i introduce a second string).
> 
> I don't understand the problem with the DatabaseSecret moving from the constructor to the class scope to be accessed later. I would have build it like this from the beginning... but now problem.
> 
> So i created a new "try" ... what do you think about this @skinny85

I don't think this attempt is correct, because you don't always create a `Secret` with that ID (there's an `if` guarding creating that construct). So, when that `if` is `false`, your code will crash.

I have to say,  I don't understand what you mean by "I don't like the idea holding redundant information". That's exactly what you're doing when saving `databaseSecret` as a field, no?

Let's do a compromise. Make `excludedCharacters` in `DatabaseSecret` internal (call it `_excludedCharacters` and annotate with `@internal`), and save that as a field instead of the entire `DatabaseSecret`.

 I really don't think saving both `Secret`, and `DatabaseSecret`, is a good idea. It makes the code pretty confusing in my opinion.

**Comment by markussiebert** [comment]
@skinny85 I can't see a case where this won't work!

both, single and multiuser rotation start with the following lines:

```ts
if (!this.secret) {
   throw new Error('Cannot add single user rotation for a cluster without secret.');
}
```

so we know, that there is this.secret set... and looking in the constructor:

```ts
if (secret) {
   this.secret = secret.attach(this);
}
```

we know this secret is only set if this secret isn't undefined and ...

```ts
// Create the secret manager secret if no password is specified
let secret: DatabaseSecret | undefined;
if (!props.masterUser.password) {
  secret = new DatabaseSecret(this, 'Secret', {
    username: props.masterUser.username,
    encryptionKey: props.masterUser.kmsKey,
    excludeCharacters: props.masterUser.excludeCharacters,
    secretName: props.masterUser.secretName,
  });
}
```
this is the only case where secret is defined - and it will allways have the ID Secret...

>I have to say, I don't understand what you mean by "I don't like the idea holding redundant information". That's exactly what you're doing when saving databaseSecret as a field, no?

with this I mean: 

We say that the default value will be ```"@/``` inside the DatabaseSecretProps. And when initializing the DatabaseInstance, we ensure this with:
```props.excludeCharacters ?? '"@/'```

So, if we say ```excludedCharaters``` is another string property inside DatabaseCluster as you suggested, we would have to initialize it exactly the same way (because, we can't read it from the DatabaseSecret, because it's not accessible - no changes to the DatabaseSecret.

So we would store the exact same information in two places and initialize two variables exactly the same way. Thats what i mean redundant information.
My attempt only tries to make the once stored information accessible.

>I really don't think saving both Secret, and DatabaseSecret, is a good idea. It makes the code pretty confusing in my opinion.

I agree - so if I won't care about not breaking anything I would like to replace the type of ```ISecret``` with ```DatabasSecert``` and only attach the Secret, without referencing the secret attachment.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secrettargetattachment.html#aws-resource-secretsmanager-secrettargetattachment-return-values
It's return values content is the same as of the secret itself - but for cdk context paths move and so some resources will be recreated. That won't break anything I hope ;-)

**Review by skinny85 — APPROVED** [review]
Alright, you've convinced me 😉.
