### PR TITLE
Lambda: Fix CloudWatch event rule permissions

### LINKED ISSUE #555: InvokePermission not automatically added to Lambda when triggered via Cloudwatch Rule
Trying wire up an EventRule as an input/trigger to a Lambda function but the permission to allow Cloudwatch to invoke the Lambda is not being added automatically.

e.g. would expect the following to add the permission automatically but doesn't
```
       const lambdaFunction = new lambda.Lambda(this, 'lambdaFunction', {
            code: new lambda.LambdaS3Code(bucket, 'lambda-cloudwatch-triggered.zip'),
            runtime: lambda.LambdaRuntime.NodeJS810,
            handler: 'index.handler',
            functionName: 'my-cdk-lambda-function'
        });

        const rule = new events.EventRule(this, 'Rule', {
            scheduleExpression: 'cron(0 0 * * ? *)',
        });
        rule.addTarget(lambdaFunction);
```

Have to add this code in to get the permission added:
```
        lambdaFunction.addPermission('allowCloudWatchInvocation', {
            principal: new ServicePrincipal('events.amazonaws.com'),
            sourceArn: rule.ruleArn
        });
```

Output from cdk synth shows this:

```
    lambdaFunctionInvokedByCloudWatchB3D0554C:
        Type: 'AWS::Lambda::Permission'
        Properties:
            Action: 'lambda:InvokeFunction'
            FunctionName:
                Ref: lambdaFunction940E68AD
            Principal: events.amazonaws.com
```

@eladb suspected in a gitter chat this was because the sourceArn is missing.

### PR DESCRIPTION
**Pull request by eladb**
Lambda permissions granted when it was added as an event rule target did not include "SourceArn" as required. This allowed any event rule to trigger the function, and also did not show as a trigger in the AWS Lambda console.

Added a integration test to verify.

### BREAKING CHANGE

To fix this, we needed to modify `IEventRuleTarget` to pass the ARN of the rule and a unique ID to the registered target in order to allow it to specify the Source ARN. This required fixing all existing event rule targets (which, so far would return a role to be assumed by CWE, so the source ARN was not required).

Fixes #555

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-codebuild/lib/project.ts [hunk 1]
```diff
@@ -254,7 +254,7 @@ export abstract class ProjectRef extends cdk.Construct implements events.IEventR
     /**
      * Allows using build projects as event rule targets.
      */
-    public get eventRuleTarget(): events.EventRuleTargetProps {
+    public asEventRuleTarget(_ruleArn: events.RuleArn, _ruleId: string): events.EventRuleTargetProps {
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-codebuild/lib/project.ts]: Maybe nicer to pass the `Rule` itself, or pass these as props, no?

**Comment by rix0rrr** [comment]
> and also did not show as a trigger in the AWS Lambda console.

But it did *work*, right? Irrespective of the security issue, is that not a failing of the console?

File: packages/@aws-cdk/aws-codebuild/lib/project.ts (hunk 1 above)
Comment (eladb) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: There's a good chance we would want to extract `IEventRuleTarget` into a separate module to prevent cyclic references (which is what I am doing with bucket notifications), so I am trying to standardize on a low-level signature for event targets, and this is the same signature as `IBucketNotificationDestination` will have.

**Comment by eladb** [comment]
@rix0rrr correct, the events would trigger Lambda.
