### PR TITLE
fix(ecr): grants for cross-account principals result in failed deployments

### LINKED ISSUE #15070: (aws-codepipeline-actions): TagParameterContainerImage unusable cross-account
Using `TagParameterContainerImage` as a property for a stack in a different account causes a resolution error.

### Reproduction Steps

```typescript
const myPipeline = new MyPipeline(app, 'my-pipeline', {
  env: nonprod
}

new MyFargateApp(app, 'my-app', {
  env: prod
  image: myPipeline.tagParameterContainerImage
}
```

### What did you expect to happen?

Stack `my-app` should reference the ECR repo from `my-pipeline`.

### What actually happened?

`Error: Resolution error: Resolution error: Resolution error: Resolution error: Resolution error: Cannot use resource 'my-app/FargateService/TaskDef/ExecutionRole' in a cross-environment fashion, the resource's physical name must be explicit set or use 'PhysicalName.GENERATE_IF_NEEDED'.`

### Environment

  - **CDK CLI Version  : 1.107.0 (build 52c4434)**
  - **Framework Version: 1.107.0**
  - **Node.js Version: 14.16.0**
  - **OS : WSL2 Ubuntu 20.04.02 LTS on Windows 10 1909**
  - **Language (Version): TypeScript (3.9.9)**

--- 

### Other details
I'm using `ApplicationLoadBalancedFargateService`.

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by skinny85**
When performing grants in ECR's Repository class for principals from other accounts,
we put the ARN of the principal inside the Resource Policy of the Repository.
However, ECR validates that all principals included in its Policy exist at the time of deploying the Repository,
so if this cross-account principal was not created before the Repository,
its deployment would fail.

Detect that situation in the Repository class,
and trust the entiure account of the principal if this situation happens.

This was spotted by a customer when using the `TagParameterContainerImage` class.

Fixes #15070

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-ecr/lib/repository.ts [hunk 1]
```diff
@@ -292,6 +316,43 @@ export abstract class RepositoryBase extends Resource implements IRepository {
...
+    }
+
+    // condition #2
+    if (!iam.principalIsANewlyCreatedResource(principal)) {
+      return undefined;
+    }
+
+    // condition #3
+    const principalStack = Stack.of(principal);
+    if (this.stack.dependencies.includes(principalStack)) {
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-ecr/lib/repository.ts:350]: I don't think this is safe or even likely to be true. Might as well leave this out.

**Review by rix0rrr — DISMISSED** [review]
I'm not sure I agree with this approach. We're actually now doing something different than what the user asked for, and they could equally well just do what we're doing, but explicitly. So we can add a warning for it, and/or add it to the docs. Or tell the user to do authz based on tags.

Either that, or we potentially add the stack dependency automatically. 

But trusting the whole account "just because" it happens to work out, although it does something different than what the user requested... I don't think that's a good idea.

**Review by jaresuth — APPROVED** [review]

**Comment by skinny85** [comment]
@rix0rrr I want to resurrect this old PR, if you don't mind 🙂.

> I'm not sure I agree with this approach. We're actually now doing something different than what the user asked for, and they could equally well just do what we're doing, but explicitly. So we can add a warning for it, and/or add it to the docs. Or tell the user to do authz based on tags.
> 
> Either that, or we potentially add the stack dependency automatically.
> 
> But trusting the whole account "just because" it happens to work out, although it does something different than what the user requested... I don't think that's a good idea.

I'm not sure there's something else we can do. If we don't change the logic inside the ECR Repository, then, regardless of what the customer tries to do "manually" themselves, we already add the Role from the Service Stack (which doesn't exist yet) to the resource policy of the ECR repo that lives in the pipeline Stack. Which means, regardless of what else the customer wants to do there (trust the entire account, use tags for permissions, etc.), the problem is already there, and the repository will fail to deploy - so, no amount of tinkering (short of something really low-level, like escape hatches) can fix that.

File: packages/@aws-cdk/aws-ecr/lib/repository.ts (hunk 1 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-ecr/lib/repository.ts:350]: Actually, we [already do this for KMS Keys](https://github.com/aws/aws-cdk/blob/572b52c45a9eb08b62a0f9cc6520c1722089bae6/packages/%40aws-cdk/aws-kms/lib/key.ts#L220-L222), so I think it's not the worst idea.

**Comment by skinny85** [comment]
@rix0rrr you want to reply here, before the PR gets closed? 🙂 https://github.com/aws/aws-cdk/pull/16376#issuecomment-1113640454

**Comment by TheRealAmazonKendra** [comment]
Psssst: If you resolve the conflicts, it resets the timer.

**Comment by skinny85** [comment]
> Psssst: If you resolve the conflicts, it resets the timer.

Thanks, I really hope so, because solving these conflicts was super irritating 😃.

File: packages/@aws-cdk/aws-ecr/lib/repository.ts [hunk 2]
```diff
@@ -319,6 +343,43 @@ export abstract class RepositoryBase extends Resource implements IRepository {
       'ecr:UploadLayerPart',
       'ecr:CompleteLayerUpload');
   }
+
+  /**
+   * Returns the account ID of the account to put into the Resource Policy
+   * if we cannot put a reference to the principal itself there,
+   * and 'undefined' in case we can.
+   */
+  private principalCannotBeSafelyAddedToResourcePolicy(grantee: iam.IGrantable): string | undefined {
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-ecr/lib/repository.ts:352]: Can't this return the correct `IGrantable` instead?

```ts
private correctGrantable(grantee: IGrantable): IGrantable {
  if (needsToBeDifferent) {
    return new AccountRootPrincipal(correctAccount);
  }

  return grantee;
}
```

File: packages/@aws-cdk/aws-ecr/lib/repository.ts [hunk 3]
```diff
@@ -319,6 +343,43 @@ export abstract class RepositoryBase extends Resource implements IRepository {
...
+    // A principal cannot be safely added to the Resource Policy of this repo if:
+    // 1. The principal is from a different account.
+    // 2. The principal is a new resource (meaning, not imported).
+    // 3. The Stack this repo belongs to doesn't depend on the Stack the principal belongs to.
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-ecr/lib/repository.ts:356]: Do these combine with AND or OR?

File: packages/@aws-cdk/aws-iam/lib/utils.ts [hunk 4]
```diff
@@ -0,0 +1,38 @@
+import { Resource } from '@aws-cdk/core';
+import { Construct, IConstruct } from 'constructs';
+import { IPrincipal } from './principals';
+
+/**
+ * Determines whether the given Principal is a newly created resource managed by the CDK,
+ * or if it's only an imported existing resource.
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-iam/lib/utils.ts:7]: "referenced" is the new term, "importing" is confusing

File: packages/@aws-cdk/aws-ecr/lib/repository.ts [hunk 5]
```diff
@@ -319,6 +343,43 @@ export abstract class RepositoryBase extends Resource implements IRepository {
...
+    }
+
+    // condition #2
+    if (!iam.principalIsOwnedResource(principal)) {
+      return undefined;
+    }
+
+    // condition #3
+    const principalStack = Stack.of(principal);
+    if (this.stack.dependencies.includes(principalStack)) {
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-ecr/lib/repository.ts:377]: You can't really know this. Dependencies probably get resolve really late, especially implicit ones.

**Review by rix0rrr — CHANGES_REQUESTED** [review]
I still don't like opening up to an entire account. 

Can we do something like the following:

```ts
class Role {

  public crossAccountSafeGrantable(): IGrantable {
    if (!this.roleTag) {
      this.roleTag = `${Stack.of(this).stackName}${this.node.addr}`; 
      Tags.of(this).add(this.roleTag, 'aws-cdk:id', this.roleTag);
    }

    return new AccountRootPrincipal(Stack.of(this.account), {
      conditions: {
        StringEquals: { 'aws-cdk:id', this.roleTag },
      },
    });
  }
}
```

?

**Comment by Naumel** [comment]
@Mergifyio update

File: packages/@aws-cdk/aws-iam/lib/utils.ts (hunk 4 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-iam/lib/utils.ts:7]: Fixed.

File: packages/@aws-cdk/aws-ecr/lib/repository.ts (hunk 5 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-ecr/lib/repository.ts:377]: I still think it's better to make this check than not (even if it doesn't work 100% of the time, it might work some of the time).

File: packages/@aws-cdk/aws-ecr/lib/repository.ts (hunk 3 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-ecr/lib/repository.ts:356]: And. Clarified in the comments.

File: packages/@aws-cdk/aws-ecr/lib/repository.ts (hunk 2 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-ecr/lib/repository.ts:352]: Unfortunately, the code you suggested:

```ts
    return new AccountRootPrincipal(Stack.of(this.account), {
      conditions: {
        StringEquals: { 'aws:PrincipalTag/aws-cdk:id', this.roleTag },
      },
    });
```

doesn't work (conditions are attached to Policies, not to Principals).

However, added the tag to the Role in a different way, let me know if that works!

**Comment by skinny85** [comment]
> The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.

Yep. The validation error is because of missing integration tests:

> The pull request linter fails with the following errors:
> 
> ```
> ❌ Fixes must contain a change to an integration test file and the resulting snapshot.
> ```
> 
> PRs must pass status checks before we can provide a meaningful review.

But, this is a cross-account scenario, and CDK integration tests are meant to run in a single account.

The functionality has unit tests that confirm the cross-account scenario works as expected.

**Comment by skinny85** [comment]
@rix0rrr incorporated your comments, would appreciate another review!

**Comment by skinny85** [comment]
Is the build for `main` broken right now? This is what I get:

```
aws-cdk: In package package.json
aws-cdk: - [@aws-cdk/node-bundle => outdated-attributions] THIRD_PARTY_LICENSES is outdated (fixable)
aws-cdk: Error: Some package.json files had errors
aws-cdk:     at main (/codebuild/output/src765710805/src/github.com/aws/aws-cdk/tools/@aws-cdk/pkglint/bin/pkglint.js:30:15)
aws-cdk:     at Object.<anonymous> (/codebuild/output/src765710805/src/github.com/aws/aws-cdk/tools/@aws-cdk/pkglint/bin/pkglint.js:33:1)
aws-cdk:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
aws-cdk:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
aws-cdk:     at Module.load (internal/modules/cjs/loader.js:950:32)
aws-cdk:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
aws-cdk:     at Module.require (internal/modules/cjs/loader.js:974:19)
aws-cdk:     at require (internal/modules/cjs/helpers.js:101:18)
aws-cdk:     at Object.<anonymous> (/codebuild/output/src765710805/src/github.com/aws/aws-cdk/tools/@aws-cdk/pkglint/bin/pkglint:2:1)
aws-cdk:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
aws-cdk: Error: pkglint exited with error code 1
aws-cdk: Build failed.!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
aws-cdk: error Command failed with exit code 1.
aws-cdk: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
aws-cdk: error Command failed with exit code 1.
aws-cdk: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build+test exited 1 in 'aws-cdk'
```

I haven't touched the CLI in this PR, but I also had to update the third-party license attribution for two other packages to make them build, so I suspect something is up with `main`.

**Comment by skinny85** [comment]
OK, looks like `main` was fixed with regard to the 3rd-party license issues, and the build is passing.

@rix0rrr this is ready for another round of reviews!

**Review by rix0rrr — DISMISSED** [review]
Thanks!

**Comment by skinny85** [comment]
> (Sorry for the late reply 😓 )

It's all good brother ❤️. I needed a few months to address your comments, so I don't blame you at all for taking a few days to review this one!

**Comment by skinny85** [comment]
(BTW, I had to merge from `main`, as Mergify didn't want to add the PR to the merge queue, as it claimed there was a difference in a GitHub Actions workflow - I guess one of the workflows changed on `main` in the meantime... so if you could approve again, I would appreciate it!)

**Review by Naumel — APPROVED** [review]
