### PR TITLE
fix(core): splitting tree.json produces a lot of files

### LINKED ISSUE #34627: core: "Could not find parent of" error in FragmentedTreeWriter for tree.json
### Describe the bug

In https://github.com/aws/aws-cdk/pull/34478, `FragmentedTreeWriter` was introduced to prevent `tree.json` from exceeding 512MB. When I play around with the `maxNodes` value, I find that choosing a low value (5000 for my application) causes the error "Error: Could not find parent of <root node>".

Because our project is private, I unfortunately cannot provide its code. However, I'll try to create a small example that triggers the bug if I get a chance to.

At first glance, do you see any issues that may have caused this, though? @rix0rrr @QuantumNeuralCoder 

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Library Version

_No response_

### Expected Behavior

No error

### Current Behavior

There's an error as described above.

### Reproduction Steps

N/A for now

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### AWS CDK Library version (aws-cdk-lib)

2.198

### AWS CDK CLI version

2.1011.0 (build cd4ec06)

### Node.js Version

v24.0.2

### OS

Mac

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by rix0rrr**
In #34478, we made sure that `tree.json` would not exceed 512MB, by splitting parts of the construct tree to separate files.

The method we chose led to a lot of files.

In this PR we are combining the various small subtrees into larger "forest" files. Since there are no official readers for the new file format yet, we're not losing a lot of effort by changing the format.

The protocol is that if `treeId` is set in a subtree reference, the target file is a forest file, otherwise it's a tree file.

Closes #34627.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/core/lib/private/tree-metadata.ts [hunk 1]
```diff
@@ -178,14 +207,59 @@ class FragmentedTreeWriter {
...
+
+    // We can now write the forest files, and the main file.
+    const mainTree = this.forest.find(t => t.referencingNode === this.mainTreePointer);
+    if (mainTree) {
+      const treeFile: TreeFile = { version: 'tree-0.1', tree: mainTree.root };
+      fs.writeFileSync(path.join(this.outdir, this.rootFilename), JSON.stringify(treeFile), { encoding: 'utf-8' });
+    }
+
+    for (const forestFile of forestFiles) {
+      fs.writeFileSync(path.join(this.outdir, forestFile.fileName), JSON.stringify(forestFile.file), { encoding: 'utf-8' });
```
Comment (otaviomacedo) [inline packages/aws-cdk-lib/core/lib/private/tree-metadata.ts:220]: Can we write the files in parallel?

**Review by otaviomacedo — APPROVED** [review]
