### PR TITLE
fix: stop passing the deprecated property to Cfn construct

### LINKED ISSUE #34895: aws-ecs: aws-cdk-lib.aws_ecs.CfnTaskDefinitionProps#inferenceAccelerators deprecation warning
### Describe the bug

Same bug as issue #33505 but the warning message is from the L1 construct code (false warning for a deprecated property of `CfnTaskDefinition` not of `TaskDefinition`).

```
[WARNING] aws-cdk-lib.aws_ecs.CfnTaskDefinitionProps#inferenceAccelerators is deprecated.
  this property has been deprecated
  This API will be removed in the next major release.
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Library Version

_No response_

### Expected Behavior

No warning should be displayed if property is not used.

### Current Behavior

See above.

### Reproduction Steps

See https://github.com/aws/aws-cdk/issues/33505.

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### AWS CDK Library version (aws-cdk-lib)

2.203.0

### AWS CDK CLI version

2.1020.0

### Node.js Version

22.14.0

### OS

AL2023

### Language

Python

### Language Version

Python 3.11

### Other information

_No response_

### PR DESCRIPTION
**Pull request by rantoniuk**
Follow-up of https://github.com/aws/aws-cdk/pull/34618 as it did not fully fix the warnings.

### Change

Stop passing the deprecated property to Cfn object.

### Tests

Tested on minimal stack and an actual production stack.

Fixes #34895

### CODE REVIEW

**Comment by rantoniuk** [comment]
Exemption Request - as previously, I don't think this needs tests.

**Comment by rantoniuk** [comment]
@pahud any chance you can help finding a reviewer?

File: packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts [hunk 1]
```diff
@@ -539,7 +535,19 @@ export class TaskDefinition extends TaskDefinitionBase {
...
+    };
+
+    if (props.inferenceAccelerators) {
+      taskDefProps = {
+        ...taskDefProps,
+        inferenceAccelerators: Lazy.any({
+          produce: () =>
+            this.renderInferenceAccelerators(),
+        }),
+      };
```
Comment (Abogical) [inline packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts:547]: You can simplify this to:
```suggestion
      taskDefProps.inferenceAccelerators = Lazy.any({
        produce: () =>
          this.renderInferenceAccelerators(),
      }),
```

**Review by Abogical — CHANGES_REQUESTED** [review]
I believe a unit test (at `packages/aws-cdk-lib/aws-ecs/test/task-definition.test.ts`) is needed here just to check that the inferenceAccelerator is not added by default and that it is only added iff an inferenceAccelerator is passed.

File: packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts (hunk 1 above)
Comment (rantoniuk) [reply packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts:547]: No, that's not possible, `taskDefProps.inferenceAccelerators` is a read-only property.

**Comment by rantoniuk** [comment]
> I believe a unit test (at packages/aws-cdk-lib/aws-ecs/test/task-definition.test.ts) is needed here just to check that the inferenceAccelerator is not added by default and that it is only added iff an inferenceAccelerator is passed.

This is already [covered by unit tests](https://github.com/rantoniuk/aws-aws-cdk/blob/bf6ef59fff3ff1a38838f69f6fac534f56dfd210/packages/aws-cdk-lib/aws-ecs/test/ec2/ec2-task-definition.test.ts#L1287-L1296).

**Comment by Abogical** [comment]
> > I believe a unit test (at packages/aws-cdk-lib/aws-ecs/test/task-definition.test.ts) is needed here just to check that the inferenceAccelerator is not added by default and that it is only added iff an inferenceAccelerator is passed.
> 
> This is already [covered by unit tests](https://github.com/rantoniuk/aws-aws-cdk/blob/bf6ef59fff3ff1a38838f69f6fac534f56dfd210/packages/aws-cdk-lib/aws-ecs/test/ec2/ec2-task-definition.test.ts#L1287-L1296).

Is there a unit test to test that inferenceAccelerator is **not** passed if not provided? (by using `Match.absent` for example)

**Review by Abogical — CHANGES_REQUESTED** [review]
Per my comment above. A unit test to test that inferenceAccelerator is **not** passed is needed here. You can use `Match.absent` to achieve this.

File: packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts (hunk 1 above)
Comment (Abogical) [reply packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts:547]: Oh, I see. Alright.

**Review by Abogical — APPROVED** [review]

**Comment by rantoniuk** [comment]
I don't think that's anyhow related to my change.
