### PR TITLE
fix(cognito-identitypool-alpha): remove `RoleAttachment` construct

### LINKED ISSUE #23449: cognito-identity-pool: Can't attach IdentityPoolRoleAttachment even if not present
### Describe the bug

If you create an identity pool like this, without specifying an authenticated and unauthenticated role, it generates default roles rather than just leaving them blank.

```typescript
const idPool = new IdentityPool(stack, "xxx-cognito-id-pool", {
    identityPoolName: "xxx-id-pool",
    allowUnauthenticatedIdentities: true,
    authenticationProviders: {
        userPools: [new UserPoolAuthenticationProvider({userPool: userPool})]
    }
})
```

Then, later, when you try to attach your own roles, like this:

```typescript
const roleAttachment = new IdentityPoolRoleAttachment(stack,
    "xxx-id-pool-attachment",
    {
        identityPool: idPool,
        authenticatedRole: authenticatedRole,
        unauthenticatedRole: unauthenticatedRole
    })
```

it fails with this error:

```
CREATE_FAILED
AWS::Cognito::IdentityPoolRoleAttachment
xxx-stack/xxx-id-pool-attachment (xxxidpoolattachmentE8645D23) us-east-1:bc70b990-d038-43b8-8501-e7cd3dda6ae7 already exists in stack
```

Its beef seems to be that even though I created the identity pool without roles attached, it created default ones on its own.  Then later when I go to 'attach' my own, it won't let me because it thinks there is already an attachment.

### Expected Behavior

I expected that when I create an identity pool with no roles, it would not generate default roles.

### Current Behavior

Testing this with only this code and a brand new stack:

```typescript
    const idPool = new IdentityPool(stack, "my-cognito-id-pool", {
        identityPoolName: "my-id-pool",
        allowUnauthenticatedIdentities: true,
        authenticationProviders: {
            userPools: [new UserPoolAuthenticationProvider({userPool: userPool})]
        }
    })
```

it created default IAM roles for authenticated and unauthenticated users.  This caused a conflict when I then tried to create my own IdentityPoolRoleAttachment, because it says there was already an attachment.

### Reproduction Steps

```typescript

const idPool = new IdentityPool(stack, "my-cognito-id-pool", {
    identityPoolName: "my-id-pool",
    allowUnauthenticatedIdentities: true,
    authenticationProviders: { userPools: [new UserPoolAuthenticationProvider({userPool: userPool})] }
})


const authenticatedRole = new Role(stack, "my-cognito-authenticated-role", {
    roleName: "my-cognito-authenticated-role",
    assumedBy: new WebIdentityPrincipal('cognito-identity.amazonaws.com',
        {
            StringEquals: {
                'cognito-identity.amazonaws.com:aud': `${stack.region}:${idPool.identityPoolId}`,
            },
            'ForAnyValue:StringLike': {
                'cognito-identity.amazonaws.com:amr': 'unauthenticated',
            },
        })
});

const unauthenticatedRole = new Role(stack, "my-cognito-unauthenticated-role", {
    roleName: "my-cognito-unauthenticated-role",
    assumedBy: new WebIdentityPrincipal('cognito-identity.amazonaws.com',
        {
            StringEquals: {
                'cognito-identity.amazonaws.com:aud': `${stack.region}:${idPool.identityPoolId}`,
            },
            'ForAnyValue:StringLike': {
                'cognito-identity.amazonaws.com:amr': 'authenticated',
            },
        })
});

const roleAttachment = new IdentityPoolRoleAttachment(stack,
    "my-id-pool-attachment",
    {
        identityPool: idPool,
        authenticatedRole: authenticatedRole,
        unauthenticatedRole: unauthenticatedRole
    })
```

### Possible Solution

I think the way to fix this is that if you create an identity pool without specifying roles it actually leaves them empty rather than generating default roles.  [This document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypool.html) tells me this should be possible as the attachment is something completely separate.

Why this is important is that I want to add constraints to my roles that only allow those role to be assumed by this specific identity pool.  To do that, I need a reference to the identity pool.  So for this to work you have to do things in this order:

1. Create the identity pool with no attached roles
2. Create the authorized and unauthorized roles with a trust policy constrained to that identity pool
3. Attach these roles to the identity pool

### Additional Information/Context

My versions of the pieces I am using from packages.json are:

```
    "@aws-cdk/aws-apigatewayv2-alpha": "^2.56.0-alpha.0",
    "@aws-cdk/aws-apigatewayv2-authorizers-alpha": "^2.56.0-alpha.0",
    "@aws-cdk/aws-apigatewayv2-integrations-alpha": "^2.56.0-alpha.0",
    "@aws-cdk/aws-cognito-identitypool-alpha": "^2.56.0-alpha.0",
    "aws-cdk": "2.56.0",
    "aws-cdk-lib": "2.56.0",
```

### CDK CLI Version

2.56.0 (build 1485f48)

### Framework Version

2.56.0-alpha.0

### Node.js Version

v16.18.0

### OS

Windows 10

### Language

Typescript

### Language Version

4.9.3

### Other information

```
    "aws-cdk": "2.56.0",
    "aws-cdk-lib": "2.56.0",

### PR DESCRIPTION
**Pull request by Leo10Gama**
### Issue # (if applicable)

Closes #23449 

### Reason for this change

What we had assumed was a bug from the service team had been investigated and revealed to be expected behaviour: an `IdentityPool` can only have a single `IdentityPoolRoleAttachment` attached to it. This went against our initial assumptions that were supported by previously-written code, which was that multiple of these attachments could be created. As such, to ensure clarity and prevent ambiguity, this library will be updated to abstract away the role attachment, as one is already created by default.

### Description of changes

* Deleted `identitypool-role-attachment.ts`, moving or deleting its contents:
  * Removed `IdentityPoolRoleAttachment` class
  * `IdentityPoolRoleAttachment.configureRoleMappings()` function has been moved inside of `IdentityPool`
  * Removed `IIdentityPoolRoleAttachment` and `IdentityPoolRoleAttachmentProps` interfaces
  * Moved `IdentityPoolRoleMapping`, `RoleMatchingMatchType`, and `RoleMappingRule` to `lib/identitypool.ts`
* `IdentityPool`'s `private roleAttachmentCount` attribute has been removed, as it never should have been there to begin with
* `IdentityPool.addRoleMappings()` method has been removed
* The logic for creating a default role attachment has been altered to create the L1 instead of the L2. **This will trigger redeployments for all users of the `IdentityPool` construct.**
* Unit tests have been tweaked to reflect this new behaviour

### Describe any new or updated permissions being added

N/A

### Description of how you validated changes

`yarn test` runs and the integ test snapshot was updated via `yarn integ`.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

BREAKING CHANGE: The `IdentityPoolRoleAttachment` construct and `IdentityPool.addRoleMappings()` function will no longer exist. This is to disambiguate that only one role attachment can exist per Identity Pool. If you are using the `IdentityPool` construct, this change will trigger a redeployment. If you need to add role mappings, please do so when the `IdentityPool` is created.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by kaizencc — COMMENTED** [review]
<s>It feels like there's a bunch of breaking changes here. They need to be called out in the PR description so that they show up in the changelog. </s>

didn't see em, sorry

File: packages/@aws-cdk/aws-cognito-identitypool-alpha/lib/identitypool.ts [hunk 1]
```diff
@@ -268,6 +267,94 @@ export interface IdentityPoolAuthenticationProviders {
...
+  readonly mappedRole: IRole;
+
+  /**
+   * The value of the claim that must be matched
+   */
+  readonly claimValue: string;
+
+  /**
+   * How to match with the claim value
+   * @default RoleMappingMatchType.EQUALS
```
Comment (paulhcsun) [inline packages/@aws-cdk/aws-cognito-identitypool-alpha/lib/identitypool.ts:353]: nit: add line break between description and `@default`
```suggestion
   * How to match with the claim value
   *
   * @default RoleMappingMatchType.EQUALS
```

File: packages/@aws-cdk/aws-cognito-identitypool-alpha/lib/identitypool.ts [hunk 2]
```diff
@@ -465,4 +543,48 @@ export class IdentityPool extends Resource implements IIdentityPool {
       },
     }, 'sts:AssumeRoleWithWebIdentity');
   }
+
+  /**
+   * Configures role mappings for the Identity Pool Role Attachment
+   */
+  private configureRoleMappings(
```
Comment (paulhcsun) [inline packages/@aws-cdk/aws-cognito-identitypool-alpha/lib/identitypool.ts:550]: Is this method the exact same implementation as the old one or were there any modifications made?

**Review by paulhcsun — COMMENTED** [review]
> The logic for creating a default role attachment has been altered to create the L1 instead of the L2. This will trigger redeployments for all users of the IdentityPool construct.

Can you elaborate on this decision to replace the L2 with the L1?

Overall looks good, just a few clarifying questions.

File: packages/@aws-cdk/aws-cognito-identitypool-alpha/lib/identitypool.ts (hunk 2 above)
Comment (Leo10Gama) [reply packages/@aws-cdk/aws-cognito-identitypool-alpha/lib/identitypool.ts:551]: It's directly copy-pasted from the old `IdentityPoolRoleAttachment` class, so all the logic is preserved.

**Comment by Leo10Gama** [comment]
> > The logic for creating a default role attachment has been altered to create the L1 instead of the L2. This will trigger redeployments for all users of the IdentityPool construct.
> 
> Can you elaborate on this decision to replace the L2 with the L1?

Previously, the "role attachment" that links authenticated and unauthenticated roles to the identity pool were their own construct. The L1s exist separately, but since only one role attachment can exist for a given identity pool, the L2 is effectively useless, since we already create one by default. The `IdentityPool` L2 was previously creating an `IdentityPoolRoleAttachment` L2, but since we're removing that construct entirely, we can just create the L1 instead.

**Review by paulhcsun — APPROVED** [review]
Thanks for addressing the questions, the changes look good to me. I've approved and added the `do-not-merge` label for now. If replacing the L2 with the L1 will cause redeployments for anyone using this construct, this should also be called out in the BREAKING CHANGES section. You can remove the label after that's been addressed.
