### PR TITLE
fix(pipelines): cross-stack step dependencies have wrong name

### LINKED ISSUE #21843: pipelines: Wrong action name when adding dependency between steps
### Describe the bug

When a second stack's post action is a dependency of a first stack's post action, it incorrectly gets prefixed with the first stack's name

### Expected Behavior

the prefix would not change when adding the dependency (e.g name should be `fe.customFeDeployment`)

### Current Behavior

adding the dependency changes the prefix. (e.g name becomes `be.customFeDeployment`)

### Reproduction Steps

Below is `pipelines.ts`.
you need `aws-cdk@1`, `ts-node`, `monocdk` and `typescript`.
Run
```shell
npx cdk --app "ts-node pipeline.ts" synth
```

Then you can see the generated steps with

```shell
jq '.Resources | to_entries[] | select(.value.Type=="AWS::CodePipeline::Pipeline") | .value.Properties.Stages[] | select(.Name=="stage") | .Actions[] | {runOrder:.RunOrder, Name:.Name}' cdk.out/PipelineStack.template.json
```

```typescript
import { Construct, StackProps, Stage, StageProps } from "monocdk";
import { Stack } from "monocdk";
import { Repository } from "monocdk/aws-codecommit";
import { CodeBuildStep, CodePipeline, CodePipelineSource, StackSteps } from "monocdk/pipelines";
import { App } from "monocdk";


class PipelineStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);
    const repoInput = CodePipelineSource.codeCommit(Repository.fromRepositoryName(this, "Repository", "repo"), "mainline");
    const synthStep = new CodeBuildStep("Synth", {
      installCommands: [],
      commands: [],
      input: repoInput,
    });

    const pipeline = new CodePipeline(this, "Pipeline", {
      pipelineName: "Repro",
      synth: synthStep,
      crossAccountKeys: true,
    });

    const wave = pipeline.addWave("test");
    const stage = new TestStage(this, "stage");
    wave.addStage(stage, { stackSteps: stage.steps });
  }
}

class TestStage extends Stage {
    public steps: StackSteps[];
    constructor(scope: Construct, id: string, props?: StageProps) {
        super(scope, id, props);
        const be = new BeStack(this, "be");
        const e2eTests = new CodeBuildStep("e2eTests", { commands: ["echo test"] });
        const fe = new FeStack(this, "fe");
        const customFeDeployment = new CodeBuildStep("customFeDeployment", { commands: ["echo test"] });
        this.steps = [
            {stack: be, post: [e2eTests]},
            { stack: fe, post: [customFeDeployment]}
        ];
        e2eTests.addStepDependency(customFeDeployment);
    }    
}

class BeStack extends Stack {
    constructor(scope: Construct, id: string, props?: StackProps) {
        super(scope, id, props);
    }
}

class FeStack extends Stack {
    constructor(scope: Construct, id: string, props?: StackProps) {
        super(scope, id, props);
    }
}

const app = new App();
new PipelineStack(app, "PipelineStack");
app.synth();

```

### Possible Solution

_No response_

### Additional Information/Context

When removing the dependency (e.g comment out line 42: `e2eTests.addStepDependency(customFeDeployment);`), the name is correct

### CDK CLI Version

1.169.0

### Framework Version

_No response_

### Node.js Version

v16.15.1

### OS

macOs 12.5.1

### Language

Typescript

### Language Version

TypeScript  (4.7.4)

### Other information

_No response_

### PR DESCRIPTION
**Pull request by rix0rrr**
We used to immediately recurse into the dependencies of a Step, and add a new Node for them to the current Graph if they didn't exist yet.

This was originally written like this to support `inputs` for the `ShellSteps`, which would automatically add in any necessary Nodes into the same Graph as necessary without explicitly adding them.

However, it would also have the effect that Steps which **would have** been added to the Graph would be parented incorrectly (they would be eagerly added to the wrong parent).

Do this in two stages now: first try to resolve all step dependencies between things that are added to the graph, then create new Nodes for missing Step dependencies later.

Fixes #21843.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/pipelines/lib/helpers-internal/graph.ts [hunk 1]
```diff
@@ -304,12 +365,32 @@ export class GraphNodeCollection<A> {
...
     }
   }
 
+  /**
+   * Return the topographically first node in the collection
+   */
+  public first() {
+    const nodes = new Set(this.nodes);
+    const sorted = this.nodes[0].rootGraph.sortedLeaves();
+    for (const tranche of sorted) {
```
Comment (Naumel) [inline packages/@aws-cdk/pipelines/lib/helpers-internal/graph.ts:383]: [tangent][non-blocking] An unexpected word: `tranche`: portion.

**Review by Naumel — APPROVED** [review]
