### PR TITLE
fix(aws-ecs): allow linux parameters to be settable

### LINKED ISSUE #2380: ECS task definition does not allow you to set `linuxParameters`, it is read only
There is no way to set the `linuxParameters` on an ECS task definition. It is present on the underlying CfnTaskDefinition.ContainerDefinitionProperty but is a readonly property on the actual CDK construct, with no way to set it

See the official ECS docs here: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_linuxparameters

And the corresponding CFN docs here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-linuxparameters.html

### PR DESCRIPTION
**Pull request by SoManyHs**
Fixes #2380

----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
  - __Design__: For significant features, design document added to `design` folder
* [ ] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by SoManyHs** [comment]
Note: Running `npm run build` spits out a lot of warnings about breaking API changes, though they seemed to be for unrelated resources?

File: packages/@aws-cdk/aws-ecs/test/test.container-definition.ts [hunk 1]
```diff
@@ -408,38 +408,80 @@ export = {
...
+    // GIVEN
+    const stack = new cdk.Stack();
+    const taskDefinition = new ecs.Ec2TaskDefinition(stack, 'TaskDef');
+
+    const linuxParameters = new ecs.LinuxParameters(stack, 'LinuxParameters', {
+      initProcessEnabled: true,
+      sharedMemorySize: 1024,
+    });
+
+    linuxParameters.addCapabilities(ecs.Capability.All);
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-ecs/test/test.container-definition.ts]: Can you add a test where we do `linuxParameters.addCapabilities()` *after* passing them to `addContainer()`? Since the object is mutable, I'd like to confirm that order doesn't matter, and that this stays true even if we refactor in the future.
