### PR TITLE
fix(ec2): Vpc.fromVpcAttributes cannot be used with EKS

### LINKED ISSUE #12160: Cannot find right method to import existing vpc with ec2.Vpc.fromLookup or ec2.Vpc.fromVpcAttributes
**Issue:**
I am trying to import an existing vpc to deploy few lambda, ecs and albs in private subnets. Running into issues when trying to import the vpc using ec2.Vpc.fromLookup or ec2.Vpc.fromVpcAttributes.

The existing vpcid, azs, privatesubnets are exported as 
dev-vpcId. - value: 'vpc-xxxxx'
dev-azs - value: 'us-east-1a,us-east-1b' 
dev-privateSubnets - 'subnet-xxxx,subnet-yyyy'

```
    const vpc = ec2.Vpc.fromVpcAttributes(this,'vpc',{
      vpcId: Fn.importValue(envName+'-vpcId'),
      availabilityZones: Fn.split(',',Fn.importValue(envName+'-azs')),
      privateSubnetIds: Fn.split(',',Fn.importValue(envName+'-privateSubnets')),
    })
```
**Error**
```
...../node_modules/@aws-cdk/core/lib/private/resolve.ts:94
      throw new Error('Found an encoded list token string in a scalar string context. Use \'Fn.select(0, list)\' (not \'list[0]\') to extract elements from token lists.');
            ^
Error: Found an encoded list token string in a scalar string context. Use 'Fn.select(0, list)' (not 'list[0]') to extract elements from token lists.
```

with ec2.Vpc.fromLookup() we cannot use import values

```
    const vpc = ec2.Vpc.fromLookup(this, 'vpc',{
      vpcId: Fn.importValue(envName+'-vpcId')
    })
```

**Error**
```
..../node_modules/@aws-cdk/aws-ec2/lib/vpc.ts:1040
      routerId: natGatewayId,
            ^
Error: All arguments to Vpc.fromLookup() must be concrete (no Tokens)
```

Please advise on the right method to import an existing vpc with details from the export values. 

---

This is a 📕 documentation issue

### PR DESCRIPTION
**Pull request by rix0rrr**
This PR has a fix similar to #12040, and introduces more explanations
and safeguards around the mechanism of importing a VPC using
`fromVpcAttributes()`. This is not the recommended way of importing
VPCs, but many users really don't want to use lookups so we'd better
make it a little safer.

This PR contains:

* A fix in the EKS library to have it stop logging subnet IDs to
  metadata if it looks like the subnet ID will lead to the
  aforementioned synthesis error (similar to the fix in the linked
  PR).
* A validation in the EKS library to stop a similar-but-different
  error from occurring if people select multiple VPC subnet groups
  from a VPC imported from token lists; this can never work and we
  might as well tell them directly.
* A metadata warning added to VPCs imported using
  `Vpc.fromVpcAttributes()`, to inform users that their VPC imported
  in this way has a good chance of not working in all cases they
  expect it to.
* A mechanism to specify the length of deploy-time lists at synthesis
  time, by passing an `assumedLength` parameter to `Fn.split()`. This
  will produce a list that is safe for manipulation, and removes the limitations
  addressed by the previous bullets.
* A note on how to use `Vpc.fromVpcAttributes()` in the `ec2` README.

Fixes #12160.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-eks/lib/cluster.ts [hunk 1]
```diff
@@ -961,8 +961,13 @@ export class Cluster extends ClusterBase {
 
     this.vpcSubnets = props.vpcSubnets ?? [{ subnetType: ec2.SubnetType.PUBLIC }, { subnetType: ec2.SubnetType.PRIVATE }];
 
+    const selectedSubnetIds = this.vpcSubnets.map(s => this.vpc.selectSubnets(s).subnetIds);
+    if (selectedSubnetIds.some(Token.isUnresolved) && selectedSubnetIds.length > 1) {
+      throw new Error('eks.Cluster: cannot select multiple subnet groups from a VPC imported from list tokens with unknown length. Select only one subnet group, pass a length to Fn.split, or switch to Vpc.fromLookup.');
```
Comment (eladb) [inline packages/@aws-cdk/aws-eks/lib/cluster.ts:966]: Maybe refer to the docs for an example?

**Review by eladb — COMMENTED** [review]
@iliapolo can you take a look?

**Review by adriantaut — APPROVED** [review]

File: packages/@aws-cdk/aws-eks/lib/cluster.ts [hunk 2]
```diff
@@ -961,8 +961,13 @@ export class Cluster extends ClusterBase {
 
     this.vpcSubnets = props.vpcSubnets ?? [{ subnetType: ec2.SubnetType.PUBLIC }, { subnetType: ec2.SubnetType.PRIVATE }];
 
+    const selectedSubnetIds = this.vpcSubnets.map(s => this.vpc.selectSubnets(s).subnetIds);
```
Comment (iliapolo) [inline packages/@aws-cdk/aws-eks/lib/cluster.ts:964]:
```suggestion
    const selectedSubnetIdsPerGroup = this.vpcSubnets.map(s => this.vpc.selectSubnets(s).subnetIds);
```

Or something, the current name makes it sound like these are individual subnets.

**Review by iliapolo — APPROVED** [review]
Added `do-not-merge` to let you address the minor comments
