### PR TITLE
fix(custom-resources): correctly convert values to Date type

### LINKED ISSUE #27962: integ-tests: awsApiCall assertion is not handling dates properly for GetMetricData with CloudWatch
### Describe the bug

When attempting to use the `IntegTest(...).assertion.awsApiCall()` method with _CloudWatch_ and the _GetMetricData_ function, it returns the error:
```
INFO	TypeError: input.StartTime.toISOString is not a function
    at serializeAws_queryGetMetricDataInput (/var/runtime/node_modules/@aws-sdk/client-cloudwatch/dist-cjs/protocols/Aws_query.js:2506:48)
    at serializeAws_queryGetMetricDataCommand (/var/runtime/node_modules/@aws-sdk/client-cloudwatch/dist-cjs/protocols/Aws_query.js:224:12)
    at serialize (/var/runtime/node_modules/@aws-sdk/client-cloudwatch/dist-cjs/commands/GetMetricDataCommand.js:30:71)
    at /var/runtime/node_modules/@aws-sdk/middleware-serde/dist-cjs/serializerMiddleware.js:12:27
    at /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:28
    at CloudWatchClient.send (/var/runtime/node_modules/@aws-sdk/smithy-client/dist-cjs/client.js:20:20)
    at AwsApiCallHandler.processEvent (/var/task/index.js:32265:35)
    at AwsApiCallHandler.handle (/var/task/index.js:31915:37)
    at Runtime.handler (/var/task/index.js:32320:35)
    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1147:29)
```
The `awsApiCall()` method executes an API call from the Lambda custom resource generated by the assertion. Here, the lib parses the parameters it receives with the `encode()` function which [converts all values to strings](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/integ-tests-alpha/lib/assertions/providers/provider.ts#L214-L236) and pass them as string properties to the Lambda function.

The issue comes up when we use an API call that requires `Date()` types like in this case for the `GetMetrciData` request. For `Date()` types, it returns a JSON string representation of the timestamp (e.g. `"2023-11-08T14:53:09.225Z"`).  As the Lambda function uses `@aws-sdk` to make the API call, it expects a Date() object that will be [converted to ISO string](https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-cloudwatch/src/protocols/Aws_query.ts#L3575-L3580), but in this scenario, it receives a string type, and because of this, it returns the error `TypeError: input.StartTime.toISOString is not a function`

### Expected Behavior

Get a response from the AWS API after running the assertion `integ.assertions.awsApiCall('CloudWatch', 'GetMetricData', params);`****

### Current Behavior

After running the `integ.assertions.awsApiCall('CloudWatch', 'GetMetricData', params);` the code fails because the Date() object is not parsed properly.
`INFO	TypeError: input.StartTime.toISOString is not a function`

### Reproduction Steps

1. Create the following files:

_test/integ.cloudwatch-call.ts_
```
import { IntegTest } from '@aws-cdk/integ-tests-alpha';
import { GetMetricDataCommandInput } from '@aws-sdk/client-cloudwatch' 
import { App } from 'aws-cdk-lib';

const app = new App();
const integ = new IntegTest(app, 'integ', {
    testCases: [],
});
const params: GetMetricDataCommandInput = {
    MetricDataQueries: [
        {
            Id: "id",
            Label: "label",
            MetricStat: {
                Metric: {
                    Namespace: "namespace",
                    MetricName: "metric",
                    Dimensions: [
                        {
                            Name: "key",
                            Value: "value",
                        },
                    ],
                },
                Period: 60,
                Stat: "MAX",
            },
        },
    ],
    StartTime: new Date(),
    EndTime: new Date(),
};
integ.assertions.awsApiCall('CloudWatch', 'GetMetricData', params);
```
_package.json_
```
{
  "name": "integ-tests",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@aws-cdk/integ-runner": "^2.106.1-alpha.0",
    "@aws-cdk/integ-tests-alpha": "^2.106.1-alpha.0",
    "@aws-sdk/client-cloudwatch": "^3.449.0",
    "aws-cdk-lib": "^2.106.1",
    "constructs": "^10.3.0",
    "esbuild": "^0.19.5",
    "ts-node": "^10.9.1",
    "typescript": "^5.2.2"
  }
}
```
3. Run `yarn install`
4. Run `npx integ-runner --parallel-regions us-west-2 --update-on-failed` 

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.106.1

### Framework Version

_No response_

### Node.js Version

v18.17.1

### OS

macOS Version 14.1 (23B74)

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by sakurai-ryo**
## Description
The following issue reports an error that occurs when calling an API that takes the `Date` type as a parameter, such as `GetMetricData` API, from a Custom Resource Lambda function, where the parameter is passed as `string` type to the AWS SDK.
https://github.com/aws/aws-cdk/issues/27962
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cloudwatch/command/GetMetricDataCommand/#:~:text=Description-,EndTime,-Required

To resolve this error, the `string` type must be properly converted to `Date` type when calling the AWS SDK from Lambda.
In this PR, I added the conversion to Date type in the same way as the existing conversion to `number` and `Uint8Array` types.
`Uint8Array`: https://github.com/aws/aws-cdk/pull/27034
`number`: https://github.com/aws/aws-cdk/pull/27112

### `update-sdkv3-parameters-model.ts` script
If the type is `timestamp` in the `smithy` specification, write `d` to the state machine so that it can be converted to a Date type later.
https://smithy.io/2.0/spec/simple-types.html#timestamp

`update-sdkv3-parameters-model.sh` script was not called from anywhere, so I called it manually and updated the JSON file.
Please let me know if there is a problem.

### `sdk-v2-to-v3-adapter` module
I added code to convert value marked `d` in state machine to `Date` type.
If the conversion to `Date` type fails, the `Date` class does not throw an exception, so the error is handled in a slightly tricky way.
Also added a unit test for this process.

### `integ-tests-alpha` module
Added integ-test to verify that errors reported in the related issue have been resolved.
The IAM Policy added internally by the call to `adPolicyStatementFromSdkCall` looks like the following and does not call `GetMetricData` correctly, so the `addToRolePolicy` method was used to explicitly add a new Policy is added explicitly with the `addToRolePolicy` method.
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "monitoring:GetMetricData"
            ],
            "Resource": [
                "*"
            ],
            "Effect": "Allow"
        }
    ]
}
```
https://github.com/aws/aws-cdk/blob/1a9c30e55e58203bd0a61de82711cf10f1e04851/packages/aws-cdk-lib/custom-resources/lib/helpers-internal/sdk-v3-metadata.json#L174

fixes #27962

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by sakurai-ryo** [comment]
Exemption Request: Since this PR is an internal behavior fix, I don't think it is necessary to change the README.

File: scripts/update-sdkv3-parameters-model.ts [hunk 1]
```diff
@@ -332,6 +338,10 @@ function isNumber(shape: SmithyShape): boolean {
     isShape('byte')(shape);
 }
 
+function isDate(shape: SmithyShape): boolean {
+  return isShape('timestamp')(shape)
```
Comment (kaizencc) [inline scripts/update-sdkv3-parameters-model.ts:342]:
```suggestion
  return isShape('timestamp')(shape);
```

File: packages/@aws-cdk/sdk-v2-to-v3-adapter/lib/sdk-v2-to-v3.json
Comment (kaizencc) [inline packages/@aws-cdk/sdk-v2-to-v3-adapter/lib/sdk-v2-to-v3.json:1]: Mostly because I'm not too familiar with this section of the repo, can you explain how you arrived at these updates?

File: packages/@aws-cdk/sdk-v2-to-v3-adapter/lib/sdk-v3-metadata.json
Comment (kaizencc) [inline packages/@aws-cdk/sdk-v2-to-v3-adapter/lib/sdk-v3-metadata.json:1]: As well as these updates...

**Review by kaizencc — COMMENTED** [review]
Thank you for the very detailed PR @sakurai-ryo! This looks mostly reasonable to me, but because I'm not too familiar with this part of our repo I'm going to toss it over to @mrgrain or @MrArnoldPalmer for a second look.

File: packages/@aws-cdk/sdk-v2-to-v3-adapter/lib/sdk-v2-to-v3.json
Comment (mrgrain) [reply packages/@aws-cdk/sdk-v2-to-v3-adapter/lib/sdk-v2-to-v3.json:1]: Should be coming from running the `update-sdkv3-parameters-model.sh ` script.

File: packages/@aws-cdk/sdk-v2-to-v3-adapter/lib/sdk-v3-metadata.json
Comment (mrgrain) [reply packages/@aws-cdk/sdk-v2-to-v3-adapter/lib/sdk-v3-metadata.json:1]: Should be coming from running the `update-sdkv3-parameters-model.sh ` script.

File: scripts/update-sdkv3-parameters-model.ts (hunk 1 above)
Comment (sakurai-ryo) [reply scripts/update-sdkv3-parameters-model.ts]: Oops, I fixed it.

**Comment by paulhcsun** [comment]
@sakurai-ryo There are some merge conflicts that need to be addressed. The changes look good to me, @kaizencc @mrgrain are there any other questions or changes to be made?

**Comment by sakurai-ryo** [comment]
Thanks @paulhcsun! Fixed conflicts.

**Comment by paulhcsun** [comment]
hey @sakurai-ryo,

Apologies for not getting around to this. It doesn't seem like there are any other major concerns and I'm good to merge this in. It seems like the integ snapshots are outdated. Could you rerun with latest changes to update those? I'll keep an eye on this and approve when the build is happy.

**Comment by sakurai-ryo** [comment]
Hi @paulhcsun
I know the CDK team is busy, so that's not a problem at all.
Thanks for taking care of this PR.
I fixed the conflicts, please check it out.
