### PR TITLE
fix(cognito-identitypool-alpha): cannot configure roleMappings with imported userPool and client

### LINKED ISSUE #30304: aws-cdk-aws-cognito-identitypool-alpha: IdentityPoolProviderUrl.user_pool cant handle imported userpools
### Describe the bug

Our Userpool and clients are created outside our application. We now want to attach a identity pool to this userpool. Today i updated from version `aws-cdk-aws-cognito-identitypool-alpha==2.96.0a0` to `aws-cdk-aws-cognito-identitypool-alpha == 2.141.0a0` and changed the role_mappings accordingly. While running `cdk synth` i get the error: `TypeError: type of argument user_pool must be aws_cdk.aws_cognito.UserPool; got jsii._reference_map.InterfaceDynamicProxy instead
`

### Expected Behavior

Since the `UserPoolAuthenticationProvider` is able to handle imported userpools and clients, the `IdentityPoolProviderUrl` should also be

### Current Behavior

```
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    pipeline = PipelineStack(
  File "/Users/spielernogard/Documents/Repositories/bestoraged-okean-control-backend/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/Users/spielernogard/Documents/Repositories/bestoraged-okean-control-backend/pipeline/pipeline_stack.py", line 34, in __init__
    self._add_stages(pipeline=pipeline, id_suffix="Prod", branch=branch)
  File "/Users/spielernogard/Documents/Repositories/bestoraged-okean-control-backend/pipeline/pipeline_stack.py", line 69, in _add_stages
    services = Services(
  File "/Users/spielernogard/Documents/Repositories/bestoraged-okean-control-backend/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/Users/spielernogard/Documents/Repositories/bestoraged-okean-control-backend/pipeline/deployment.py", line 68, in __init__
    gui_backend = GUIBackendStack(
  File "/Users/spielernogard/Documents/Repositories/bestoraged-okean-control-backend/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/Users/spielernogard/Documents/Repositories/bestoraged-okean-control-backend/services/gui_backend/stack_gui_backend.py", line 18, in __init__
    ControlUserPool(scope=self, id="UserPool")
  File "/Users/spielernogard/Documents/Repositories/bestoraged-okean-control-backend/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/Users/spielernogard/Documents/Repositories/bestoraged-okean-control-backend/services/gui_backend/user_pool/infrastructure.py", line 106, in __init__
    provider_url=IdentityPoolProviderUrl.user_pool(
  File "/Users/spielernogard/Documents/Repositories/bestoraged-okean-control-backend/.venv/lib/python3.8/site-packages/aws_cdk/aws_cognito_identitypool_alpha/__init__.py", line 1411, in user_pool
    check_type(argname="argument user_pool", value=user_pool, expected_type=type_hints["user_pool"])
  File "/Users/spielernogard/Documents/Repositories/bestoraged-okean-control-backend/.venv/lib/python3.8/site-packages/typeguard/__init__.py", line 785, in check_type
    raise TypeError(
TypeError: type of argument user_pool must be aws_cdk.aws_cognito.UserPool; got jsii._reference_map.InterfaceDynamicProxy instead
```

### Reproduction Steps

```python
import os  
  
import aws_cdk as cdk  
import aws_cdk.aws_cognito as cognito  
from aws_cdk import aws_iam as iam  
from aws_cdk.aws_cognito_identitypool_alpha import (  
    IdentityPool,  
    IdentityPoolAuthenticationProviders,  
    IdentityPoolRoleMapping,  
    IdentityPoolProviderUrl,  
    UserPoolAuthenticationProvider,  
)    
from constructs import Construct  

  
USER_POOL_ARN = 'ARN_HERE'
USER_POOL_CLIENT_ID = "CLIENT_ID_HERE"
  
class ControlUserPool(Construct):  
    """Construct"""  
  
    def __init__(self, scope: Construct, id: str):  
        super().__init__(scope, id)   
        this_dir = os.path.dirname(__file__)  
  
        # import userpool
        self.user_pool = cognito.UserPool.from_user_pool_arn(  
	        scope=self, id="CognitoUserPool", user_pool_arn=USER_POOL_ARN  
        )  
        
        # import userpool client
        self.user_pool_client = cognito.UserPoolClient.from_user_pool_client_id(  
	        scope=self,  
	        id="UserPoolClientId",  
	        user_pool_client_id=USER_POOL_CLIENT_ID,  
        )  
        
        # create and attach identity pool
        self.identity_pool = IdentityPool(  
	        scope=self,  
	        id="IdentityPool",  
	        identity_pool_name=resource_name(  
		        self, name="IdentityPool"  
	        ),  
	        authentication_providers=IdentityPoolAuthenticationProviders(  
		        user_pools=[  
			        UserPoolAuthenticationProvider(  
				        user_pool=self.user_pool,  
				        user_pool_client=self.user_pool_client,  
			        )  
		        ]  
	        ),  
	        role_mappings=[  
		        IdentityPoolRoleMapping(  
			        mapping_key="cognito",  
			        provider_url=IdentityPoolProviderUrl.user_pool(  
				        user_pool=self.user_pool,  
				        user_pool_client=self.user_pool_client,  
			        ),  
			        use_token=True,  
		        )  
	        ],  
	        allow_unauthenticated_identities=False,  
        )
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.142.1 (build ed4e152)

### Framework Version

_No response_

### Node.js Version

v21.1.0

### OS

Mac OS 14.5 (23F79)

### Language

Python

### Language Version

3.8.18 3.12.0 3.11.6

### Other information

_No response_

### PR DESCRIPTION
**Pull request by sakurai-ryo**
### Issue # (if applicable)

Closes #30304

### Reason for this change
Currently, we cannot use imported user pools and clients for role mapping in an identity pool.
This is because the `IdentityPoolProviderUrl.userPool` method takes an L2 construct as its argument type instead of Interface (`IUserPool`, `IUserPoolClient`).

```ts
    const userPool = cognito.UserPool.fromUserPoolArn(this, 'CognitoUserPool', 'arn');
    const userPoolClient = cognito.UserPoolClient.fromUserPoolClientId(this, 'UserPoolClientId', 'client-id');
    const identityPool = new cognitoidp.IdentityPool(this, 'IdentityPool', {
      // ~
      roleMappings: [
        {
          mappingKey: 'cognito', 
          providerUrl: cognitoidp.IdentityPoolProviderUrl.userPool(userPool, userPoolClient), // ! type error here !
          useToken: true
        }
      ],
      allowUnauthenticatedIdentities: false
    });
```

### Description of changes
The argument types of the `IdentityPoolProviderUrl.userPool` method are changed to `IUserPool` and `IUserPoolClient`.
This method requires the `userPoolProviderName` of the userPool, but since it does not exist for `IUserPool`, a property was added.
Since this property is required in the `UserPool` construct, it is also required in `IUserPool`.
https://github.com/aws/aws-cdk/blob/c3003ab41f0efc763f39eb2cab490c8a005e146b/packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts#L902

I add a required attribute to the Interface of the aws-cognito module(stable), but I do not think this to be a breaking change.
Please let me know if it is not.

### Description of how you validated changes
Unit tests and integ tests are added to verify that the imported userPool and clinet can be used.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts [hunk 1]
```diff
@@ -874,6 +906,48 @@ export class UserPool extends UserPoolBase {
...
+    }
+
+    return new ImportedUserPool();
+  }
+
+  /**
+   * Import an existing user pool into the stack.
+   */
+  public static fromUserPoolAttributes(scope: Construct, id: string, attrs: UserPoolAttributes): IUserPool {
+    if (!attrs.userPoolArn && !attrs.userPoolId) {
```
Comment (TheRealAmazonKendra) [inline packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts:931]: I'm not sure that this function is really needed here. The fromId and fromArn functions should be able to assemble and return all of the missing attributes. 

Correct me if I'm wrong but the attributes for a UserPool are:
```
Arn: arn:<partition>:cognito-idp:<region>:<account>:userpool/<userpoolId>
ProviderName: cognito-idp.<region>.<url-suffix>/<userpoolId>
ProviderURL: https://cognito-idp.<region>.<url-suffix>/userpoolId/.well-known/jwks.json (this is listed as the token signing key url, which I think is what's being referred to here?)
UserPoolId: userpoolId
```
So, given that, you could add each of the missing fields as attributes in the IUserPool and then construct each of these (assuming same region as in the id for fromId) in the existing fromXxx functions so that you don't even need to create a new function.

Comment (TheRealAmazonKendra) [reply packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts:931]: Doing so would mitigate every one of my comments above.

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Thank you for your contribution. Please see my comments inline.

File: packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts [hunk 2]
```diff
@@ -767,6 +767,12 @@ export interface IUserPool extends IResource {
    */
   readonly userPoolArn: string;
 
+  /**
+   * User pool provider name
+   * @attribute
+   */
+  readonly userPoolProviderName: string;
```
Comment (Leo10Gama) [inline packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts:774]: Is there anything that would prevent us from making this new attribute optional for the interface and base class instead? I'm thinking of the case of users who may be either implementing this interface or extending the abstract class, so adding a new mandatory field would likely break their implementations.

File: packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts [hunk 3]
```diff
@@ -805,6 +811,7 @@ export interface IUserPool extends IResource {
 abstract class UserPoolBase extends Resource implements IUserPool {
   public abstract readonly userPoolId: string;
   public abstract readonly userPoolArn: string;
+  public abstract readonly userPoolProviderName: string;
```
Comment (Leo10Gama) [inline packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts:814]: Same comment as left in `IUserPool.userPoolProviderName`. Does this field need to be mandatory for the new logic to work?

File: packages/aws-cdk-lib/aws-cognito/test/user-pool.test.ts [hunk 4]
```diff
@@ -293,13 +293,16 @@ describe('User Pool', () => {
 
   test('import using arn', () => {
     // GIVEN
-    const stack = new Stack();
+    const stack = new Stack(undefined, undefined, {
+      env: { region: 'us-east-1', account: '0123456789012' },
+    });
```
Comment (Leo10Gama) [inline packages/aws-cdk-lib/aws-cognito/test/user-pool.test.ts:298]: Can we keep the stack identical for this test, or does it need these additional properties to work? If so, that would probably make these breaking changes. If not, can we update the logic that checks for the new `userPoolProviderName` so that it works without additional props?

File: packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts [hunk 5]
```diff
@@ -767,6 +767,12 @@ export interface IUserPool extends IResource {
    */
   readonly userPoolArn: string;
 
+  /**
+   * User pool provider name
```
Comment (Leo10Gama) [inline packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts:771]: Can we update the docstring to be more similar to some of the other attributes? Feels redundant to have an attribute `userPoolProviderName` with the description `User pool provider name`.

**Review by Leo10Gama — CHANGES_REQUESTED** [review]
Thanks for the changes! Left a few more comments looking for a bit more clarification on these changes.

File: packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts (hunk 2 above)
Comment (Leo10Gama) [reply packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts:774]: Update: I have since looked a little more into these sorts of changes. We don't currently support extending interfaces or abstract classes, so adding a mandatory attribute here isn't a problem!

File: packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts (hunk 3 above)
Comment (Leo10Gama) [reply packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts:814]: Same update as above: no issue here

File: packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts [hunk 6]
```diff
@@ -870,10 +877,14 @@ export class UserPool extends UserPoolBase {
     }
 
     const userPoolId = arnParts.resourceName;
+    // ex) cognito-idp.us-east-1.amazonaws.com/us-east-1_abcdefghi
+    const providerName = `cognito-idp.${Stack.of(scope).region}.amazonaws.com/${userPoolId}`;
```
Comment (Leo10Gama) [inline packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts:881]: The formation logic of this string should be changed, since `amazonaws.com` is a partition that could be different for different users. Can you use the `arnParts` attributes for this instead? Something along the lines of:
```
`cognito-idp.${arnParts.region}.${arnParts.partition}/${userPoolId}`;
```

**Review by Leo10Gama — CHANGES_REQUESTED** [review]

File: packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts [hunk 7]
```diff
@@ -767,6 +767,12 @@ export interface IUserPool extends IResource {
    */
   readonly userPoolArn: string;
 
+  /**
+   * The provider name of this user pool resource
+   * @attribute
```
Comment (paulhcsun) [inline packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts:772]: nit: add a line break
```suggestion
   * The provider name of this user pool resource
   *
   * @attribute
```

**Review by paulhcsun — APPROVED** [review]
Nice work, thanks @sakurai-ryo and @Leo10Gama both!

**Comment by paulhcsun** [comment]
@Mergifyio update

**Comment by paulhcsun** [comment]
@Mergifyio update

**Review by paulhcsun — APPROVED** [review]
