### PR TITLE
fix(apigateway): permission error in lambda integration when function name is modified

### LINKED ISSUE #5306: API Gateway proxy Lambda loses permissions when functionName is changed
### Reproduction Steps

1. Create an API Gateway RestAPI and a LambdaIntegration
2. Deploy
3. Change the Lambda's functionName property.
4. Deploy

### Error Log
API Gateway fails to invoke the function and reports:
Execution failed due to configuration error: Invalid permissions on Lambda function

### Environment

  - **CLI Version**      : 1.18.0 (build bc924bc)
  - **Framework Version**: 1.18.0
  - **OS**               : Mac OSX
  - **Language**         : TypeScript

### Other
--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by nija-at**
Changing function name triggers a resource replacement - the old
function is removed and replaced with a new function.
However, the RestApi deployment remains untouched and is still pointing
at the ARN of the, now stale, function.

The fix is to trigger a new deployment if the function name changes.

fixes #5306

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-apigateway/lib/integration.ts [hunk 1]
```diff
@@ -156,8 +168,8 @@ export class Integration {
    * Can be overridden by subclasses to allow the integration to interact with the method
    * being integrated, access the REST API object, method ARNs, etc.
    */
-  public bind(_method: Method) {
-    return;
+  public bind(_method: Method): IntegrationConfig {
```
Comment (eladb) [inline packages/@aws-cdk/aws-apigateway/lib/integration.ts:171]: Why not `IntegrationConfig | undefined` for backwards compat and also returning empty objects is yakk.

File: packages/@aws-cdk/aws-apigateway/lib/method.ts [hunk 2]
```diff
@@ -192,6 +192,9 @@ export class Method extends Resource {
       authorizer._attachToApi(this.api);
     }
 
+    const integration = props.integration ?? this.resource.defaultIntegration ?? new MockIntegration();
```
Comment (eladb) [inline packages/@aws-cdk/aws-apigateway/lib/method.ts:195]: Is this another bug that's being fixed here?

File: packages/@aws-cdk/aws-apigateway/lib/integration.ts [hunk 3]
```diff
@@ -134,6 +134,18 @@ export interface IntegrationProps {
...
+/**
+ * Result of binding an Integration to the Method
+ */
+export interface IntegrationConfig {
+  /**
+   * Triggers a new Deployment if the value of this property changes.
+   * Use this property to trigger new deployments for changes to values in this integration.
+   * @default - deployments are not triggered for any change of this integration.
+   */
+  readonly triggerDeployment?: any;
```
Comment (eladb) [inline packages/@aws-cdk/aws-apigateway/lib/integration.ts:146]: I think using a verb semantics here is weird because it's not an active thing the producer needs to do. Perhaps `deploymentFingerprint`.

I would also force this to be a `string` and have the producer serialize to ensure people understand this needs to be a serializable value and not any random object with cyclic references to the world.

File: packages/@aws-cdk/aws-apigateway/lib/method.ts (hunk 2 above)
Comment (nija-at) [reply packages/@aws-cdk/aws-apigateway/lib/method.ts:195]: No, this is code being moved from `renderIntegration()` method below.

See the first few lines of this method below that is being deleted.

Comment (eladb) [reply packages/@aws-cdk/aws-apigateway/lib/method.ts:195]: ok cool, missed that

File: packages/@aws-cdk/aws-apigateway/lib/integrations/aws.ts [hunk 4]
```diff
@@ -92,7 +92,8 @@ export class AwsIntegration extends Integration {
     });
   }
 
-  public bind(method: Method) {
+  public bind(method: Method): IntegrationConfig | undefined {
     this.scope = method;
+    return;
```
Comment (eladb) [inline packages/@aws-cdk/aws-apigateway/lib/integrations/aws.ts:97]: Is this needed?

File: packages/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts [hunk 5]
```diff
@@ -72,5 +73,16 @@ export class LambdaIntegration extends AwsIntegration {
         sourceArn: method.testMethodArn,
       });
     }
+
+    const cfnFunction = this.handler.node.defaultChild as lambda.CfnFunction;
+    let deploymentFingerprint;
+    if (!Token.isUnresolved(cfnFunction.functionName)) {
+      const md5 = crypto.createHash('md5');
+      md5.update(JSON.stringify({ functionName: cfnFunction.functionName }));
+      deploymentFingerprint = md5.digest('hex');
```
Comment (eladb) [inline packages/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts:82]: Why do we need to calculate a hash here? Just just the function name or (`JSON.stringify({ functionName }`) as string, isn't that sufficient?

File: packages/@aws-cdk/aws-apigateway/lib/integration.ts [hunk 6]
```diff
@@ -134,6 +134,19 @@ export interface IntegrationProps {
...
 
+/**
+ * Result of binding an Integration to the Method
+ */
+export interface IntegrationConfig {
+  /**
+   * This value is included in computing the Deployment's fingerprint. When the fingerprint
+   * changes a new deployment is triggered.
+   * This property should carry a different value when the Deployment needs to be refreshed.
+   * @default - deployments are not triggered for any change of this integration.
```
Comment (eladb) [inline packages/@aws-cdk/aws-apigateway/lib/integration.ts:145]: Add a note that it can be an arbitrary string and does not have to be a hash.

File: packages/@aws-cdk/aws-apigateway/lib/integrations/aws.ts (hunk 4 above)
Comment (nija-at) [reply packages/@aws-cdk/aws-apigateway/lib/integrations/aws.ts:97]: Yes. The return type is no longer `void`.

File: packages/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts (hunk 5 above)
Comment (nija-at) [reply packages/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts:82]: That'll work too, but is it a fingerprint anymore? https://en.wikipedia.org/wiki/Fingerprint_(computing).

If not, what is it? (so we can correctly name it)

Comment (eladb) [reply packages/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts:82]: You are right. Maybe `deploymentToken` or `deploymentKey` or something along those lines

File: packages/@aws-cdk/aws-apigateway/lib/integration.ts (hunk 6 above)
Comment (nija-at) [reply packages/@aws-cdk/aws-apigateway/lib/integration.ts:145]: Switched to index type <string, string> so the user doesn't have to do JSON.stringify() unless they're adding a nested struct. The input to the hash gen will also be a bit nicer without the serialized objects.

File: packages/@aws-cdk/aws-apigateway/lib/integration.ts [hunk 7]
```diff
@@ -134,6 +134,20 @@ export interface IntegrationProps {
...
+ */
+export interface IntegrationConfig {
+  /**
+   * This value is included in computing the Deployment's fingerprint. When the fingerprint
+   * changes, a new deployment is triggered.
+   * This property should contain values associated with the Integration that upon changing
+   * should trigger a fresh the Deployment needs to be refreshed.
+   * @default undefined deployments are not triggered for any change to this integration.
+   */
+  readonly deploymentToken?: { [key: string]: string };
```
Comment (eladb) [inline packages/@aws-cdk/aws-apigateway/lib/integration.ts:148]: why complicate?  Make it a string. It's opaque, so making it a key/value sends the wrong message.

File: packages/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts [hunk 8]
```diff
@@ -72,5 +72,15 @@ export class LambdaIntegration extends AwsIntegration {
         sourceArn: method.testMethodArn,
       });
     }
+
+    const cfnFunction = this.handler.node.defaultChild as lambda.CfnFunction;
+    let deploymentToken;
+    if (!Token.isUnresolved(cfnFunction.functionName)) {
+      // functionName cannot be undefined since isUnresolved() filteres undefined. So use exclamation (!)
+      deploymentToken = JSON.stringify({ functionName: cfnFunction.functionName! });
```
Comment (eladb) [inline packages/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts:80]:
```suggestion
      deploymentToken = JSON.stringify({ functionName: cfnFunction.functionName });
```
