### PR TITLE
fix(iam): can't use `OrganizationPrincipal` for assuming Role

### LINKED ISSUE #5732: Usage of OrganizationPrincipal in IAM Role creation is causing MalformedPolicyDocument
Stack can't be deployed when OrganizationPrincipal is used in IAM Role creation because of MalformedPolicyDocument.

### Reproduction Steps

Code:
```
r = aws_iam.Role(self, 'myrole',
    assumed_by=aws_iam.OrganizationPrincipal(organization_id='o-123')
)
```

CloudFormation template:
```
  myrole81024481:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:PrincipalOrgID: o-123
            Effect: Allow
            Principal: "*"
        Version: "2012-10-17"
```

### Error Log

Error:
```
$ cdk deploy

...

  1/14 | 1:41:32 PM | CREATE_FAILED        | AWS::IAM::Role     | raster-nonprod/linz-raster-read-role (linzrasterreadrole81024481) AssumeRolepolicy contained an invalid principal: "STAR":"*". (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: 95c21901-e6c5-4279-b6da-41d4a68c998f)
        new Role (/tmp/jsii-kernel-27K1yW/node_modules/@aws-cdk/aws-iam/lib/role.js:35:22)
        \_ /home/imincik/Projects/dev/linz/linz-data-lake/code/aws/data-stores/.env/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7762:49
        \_ Kernel._wrapSandboxCode (/home/imincik/Projects/dev/linz/linz-data-lake/code/aws/data-stores/.env/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8222:20)
        \_ Kernel._create (/home/imincik/Projects/dev/linz/linz-data-lake/code/aws/data-stores/.env/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7762:26)
        \_ Kernel.create (/home/imincik/Projects/dev/linz/linz-data-lake/code/aws/data-stores/.env/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7509:21)
        \_ KernelHost.processRequest (/home/imincik/Projects/dev/linz/linz-data-lake/code/aws/data-stores/.env/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7296:28)
        \_ KernelHost.run (/home/imincik/Projects/dev/linz/linz-data-lake/code/aws/data-stores/.env/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7236:14)
        \_ Immediate._onImmediate (/home/imincik/Projects/dev/linz/linz-data-lake/code/aws/data-stores/.env/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7239:37)
        \_ processImmediate (internal/timers.js:439:21)

```

### Environment

  - **CLI Version      :** 1.20.0 (build 021c521)
  - **Framework Version:**
  - **OS               :** Ubuntu 18.04
  - **Language         :** Python

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
`Principal: "*"` supposedly works to allow any Principal to assume
a Role (restricted by `Conditions`, of course), but doesn't work in
practice. The IAM API rejects it as a MalformedPolicyDocument.

In order to not generate a large diff on existing policies, disable
simplification of `Principal: { AWS: * }` to `Principal: *` only
for AssumeRole policy documents.

Fixes #5732.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

---

## Commit Message
fix(iam): can't use `OrganizationPrincipal` for assuming Role

`Principal: "*"` supposedly works to allow any Principal to assume
a Role (restricted by `Conditions`, of course), but doesn't work in
practice. The IAM API rejects it as a MalformedPolicyDocument.

In order to not generate a large diff on existing policies, disable
simplification of `Principal: { AWS: * }` to `Principal: *` only
for AssumeRole policy documents.

Fixes #5732.

### CODE REVIEW

File: packages/@aws-cdk/aws-iam/lib/role.ts [hunk 1]
```diff
@@ -439,3 +439,18 @@ function validateMaxSessionDuration(duration?: number) {
...
 }
+
+/**
+ * A PolicyStatement that doesn't normalize its Principal field.
+ */
+class NonPrincipalNormalizingStatement extends PolicyStatement {
+  public toStatementJson(): any {
+    const stat = super.toStatementJson();
+
+    if (stat.Principal && stat.Principal === '*') {
```
Comment (skinny85) [inline packages/@aws-cdk/aws-iam/lib/role.ts]: Can this be simplified to just `stat.Principal === '*'`? If `stat.Principal` is `undefined`, that will return `false`, like it does now.

**Comment by imincik** [comment]
Thank you very much for your work guys.

File: packages/@aws-cdk/aws-iam/lib/role.ts [hunk 2]
```diff
@@ -439,3 +439,18 @@ function validateMaxSessionDuration(duration?: number) {
     throw new Error(`maxSessionDuration is set to ${duration}, but must be >= 3600sec (1hr) and <= 43200sec (12hrs)`);
   }
 }
+
+/**
+ * A PolicyStatement that doesn't normalize its Principal field.
```
Comment (eladb) [inline packages/@aws-cdk/aws-iam/lib/role.ts]: Sounds to me like it DOES normalize the principal field (it normalizes `"*"` to `{AWS:"*"}`, no?).
