### PR TITLE
fix(aws-ec2): fix SecurityGroup's all egress traffic rule

### LINKED ISSUE #987: ASG Instance Security Group AllowOutbound Bug
If you create an ASG with the L2 in version 0.13.0 and set `allowOutbound: true` (also the default) and later set up rules that can not be inlined, the outbound access is removed. The CFN template does not remove it, but it also does not work. 

This EKS Example is a working a reproduction of the bug: https://github.com/moofish32/cdk-eks-example/blob/test/lib/eks-node-group.ts#L46-L94

You can see the synth output has the outbound but if you build this stack (you'll need to build the cluster first).

This might be solve-able with a documentation update, but it seems we should likely fix this? @rix0rrr I think you have an open doc task.

### PR DESCRIPTION
**Pull request by rix0rrr**
Make "allowAllOutbound" traffic a property of a SecurityGroup. By making
the SecurityGroup aware of this configuration property, we can make sure
that future egress rules don't get added to the SecurityGroup. There's
no need to, because all traffic is allowed by default anyway.

If we don't do this, our behavior of adding reciprocal rules between
SecurityGroups conflicts with CloudFormation's behavior to strip the
"default outbound" rule when another rule gets added, and it becomes
impossible to configure "all outbound" traffic on a
SecurityGroup.

Fixes #987.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-ec2/lib/security-group.ts [hunk 1]
```diff
@@ -233,8 +263,66 @@ export class SecurityGroup extends SecurityGroupRef implements ITaggable {
...
+/**
+ * Egress rule that purposely matches no traffic
+ *
+ * This is used in order to disable the "all traffic" default of Security Groups.
+ *
+ * No machine can ever actually have the 255.255.255.255 IP address, but
+ * in order to lock it down even more we'll restrict to a nonexistent
+ * ICMP traffic type.
+ */
+const BOGUS_RULE = {
```
Comment (eladb) [inline packages/@aws-cdk/aws-ec2/lib/security-group.ts]: Why not call this BLOCK_ALL_TRAFFIC?

Comment (rix0rrr) [reply packages/@aws-cdk/aws-ec2/lib/security-group.ts]: Yeah, probably more professional.

File: packages/@aws-cdk/aws-ec2/lib/security-group.ts [hunk 2]
```diff
@@ -149,11 +160,16 @@ export class SecurityGroup extends SecurityGroupRef implements ITaggable {
...
 
+  private readonly allowAllOutbound: boolean;
+
   constructor(parent: Construct, name: string, props: SecurityGroupProps) {
     super(parent, name);
 
     this.tags = new TagManager(this, { initialTags: props.tags});
     const groupDescription = props.description || this.path;
+
+    this.allowAllOutbound = props.allowAllOutbound || false;
```
Comment (moofish32) [inline packages/@aws-cdk/aws-ec2/lib/security-group.ts]: Just for my future coding preference do we prefer:
```
this.allowAllOutbound = props.allowAllOutbound || false;
// or 
this.allowAllOutbound = !!props.allowAllOutbound
```
My bigger question here is defaulting this to `false`. I **think** most users expect this to be `true`? However, other infra code products take this approach so perhaps that is better?

Comment (rix0rrr) [reply packages/@aws-cdk/aws-ec2/lib/security-group.ts]: My thinking here has been torn between two ways.

This is the "secure by default" solution.

However, it takes more work to get to "what you want", if you want to access things outside your VPC (which you almost always want, to use AWS services). All constructs that create SG's now have to set the default to `true` (which ASGs also do), which is kinda silly.

Yeah, maybe you're right.

Comment (moofish32) [reply packages/@aws-cdk/aws-ec2/lib/security-group.ts]: To be clear I'm also on the fence just like you, just highlighting the pivot in AWS status quo on this particular feature. I can support either direction.

Comment (rix0rrr) [reply packages/@aws-cdk/aws-ec2/lib/security-group.ts]: Going to go with "works by default" over "secure by default" after all I think.
