### PR TITLE
fix(core): Duration incorrectly renders Days

### LINKED ISSUE #9906: [core] Duration toIsoString() not following ISO Standard
### Reproduction Steps

    const duration = Duration.days(14)
    const stringDuration = duration.toIsoString() 

### What did you expect to happen?

    stringDuration is `P14D` 

### What actually happened?
     
     stringDuration is `PT14D` 
       
### Environment

  - **CDK CLI Version:** 1.32.2
  - **Node.js Version:** 12.18.2
  - **OS:**  macOS Catalina
  - **Language:**  TypeScript 

### Other

[Link to docu](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Duration.html#to-wbr-iso-wbr-string)

**Explanation of my use case**

I am creating a Dashboard for my service using CDK. I would like the dashboard to have a time range like:

    start time: ~today - 14 days
    end time: ~today

I know I can do this by specifying: `start: "-P14D" `

However I would like to use Duration instead of a string. Something like:

    const duration = Duration.days(14)
    ....
    start: "-" + duration.toIsoString()

This is not working because duration.toIsoString() prints PT14D and not P14D .

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
We used to render all periods as `PT...`, but the correct
formatting is `P(days)T(hms)`.

Fixes #9906.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/core/lib/duration.ts [hunk 1]
```diff
@@ -238,15 +224,33 @@ export class Duration {
...
+   * Only components != 0 will be returned.
+   *
+   * Can combine millis and seconds together for the benefit of toIsoString,
+   * makes the logic in there simpler.
+   */
+  private components(combineMillisWithSeconds: boolean): Array<[number, TimeUnit]> {
+    const ret = new Array<[number, TimeUnit]>();
+    let millis = convert(this.amount, this.unit, TimeUnit.Milliseconds, { integral: false });
+
+    for (const unit of [TimeUnit.Days, TimeUnit.Hours, TimeUnit.Hours, TimeUnit.Minutes, TimeUnit.Seconds]) {
```
Comment (njlynch) [inline packages/@aws-cdk/core/lib/duration.ts:239]:
```suggestion
    for (const unit of [TimeUnit.Days, TimeUnit.Hours, TimeUnit.Minutes, TimeUnit.Seconds]) {
```

**Review by njlynch — APPROVED** [review]
I wonder how this got missed for so long? Looks good! One change to address before merging.
