### PR TITLE
fix(aws-eks): cap generated stack names at 128 characters

### LINKED ISSUE #20124: After upgrading to cdk v2, getting Stack name must be <= 128 characters
### Describe the bug

I have been using cdk with version 1.147.1, and my cdk apps were successfully deployed.
After upgrading to cdk v2, I cant deploy my cdk app, getting "Stack name must be <= 128 characters" error message.

Looking at the stack name it tried to create, I cant understand what is going on, why is this name generated when I have provided a short logical id to all my resources and to the stack name itself.

I have a construct that exports an existing eks cluster (code is simplified just for example)
```python
class EksCluster(Construct):
    def __init__(
        self,
        scope: Construct,
        stack_name: str,
        stage: str,
    ) -> None:
        super().__init__(scope, stack_name)
       self.cluster = self.import_cluster()

    def import_cluster(self) -> aws_eks.ICluster:
        return aws_eks.Cluster.from_cluster_attributes(
            self,
            id="imported-eks-cluster",
            cluster_name=cluster_name,
            kubectl_role_arn=kubectl_role_arn,
            open_id_connect_provider=open_id_provider,
            vpc=vpc,
        )
```

Then a simple app.py with the cdk app
```python
app = App()
aws_lb_controller_stack = AwsLBControllerStack(
    app,
    f"aws-load-balancer-controller-{STAGE}",
    stage=STAGE,
    cluster_config=cluster_config,
    env=Environment(region=REGION, account=ACCOUNT),
)
app.synth()
```
And finally the stack itself, that uses the construct to use the eks cluster and create a service account for example
```python
class AwsLBControllerStack(Stack):
    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        stage: str,
        cluster_config: dict,
        **kwargs,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)
        self.eks_cluster = EksCluster(self, "eks-cluster", stage=stage)
        service_account = self.eks_cluster.cluster.add_service_account(
            "aws-lb-controller-service-account",
            name=AWS_LB_CONTROLLER_SERVICE_ACCOUNT_NAME,
            namespace=AWS_LB_CONTROLLER_NAMESPACE,
        )
```

This worked fine on cdk v1.147.1, but now after upgrading the cdk version and trying to deploy this code, it returns the following error:
```sh
jsii.errors.JSIIError: Stack name must be <= 128 characters. Stack name: 'awsloadbalancercontrollersandboxzolaawsloadbalancercontrollersandboxzolaeksclusterimportedeksekscluster980273B4KubectlProviderC92A5312'
```

Can you please explain what generated such a long name? 
And most importantly, how can this be fixed?

### Expected Behavior

Stack names should be short and understandable like they are defined in their logical ids, and most importantly it should allow me to deploy my cdk app without generating the name and then not allowing me to deploy when I did not define such name anywhere in the app.

### Current Behavior

Stack names are generated with multiple duplicates inside and just unreadable names.

### Reproduction Steps

Posted above a simple setup in python

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.21.1

### Framework Version

_No response_

### Node.js Version

v17.9.0

### OS

macOS monterey 12.3.1

### Language

Python

### Language Version

3.10.2

### Other information

_No response_

### PR DESCRIPTION
**Pull request by comcalvi**
When imported, Kubectl Providers result in a new nested stack being created. Nested stack names are created by generating a unique ID (which includes the entire construct id path). Kubectl provider ids are constructed the same way (they can't be specified manually, so the code uses a unique ID). This results in the final ID for the stack containing the id of the provider repeated twice. The makes the name hard to decipher, and more importantly can result in stack names being longer than 128 characters.

This caps all generated stack names at 128 characters. Ideally, we would be able to change way in which these stack names are generated; however, that would be a breaking change.

Fixes #20124.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by corymhall — COMMENTED** [review]
I think this fixes the issue, but I'm worried it might give us a stack name that isn't descriptive. From the linked issue, this fix would rename the generated stack like this (I think): 

`ApplicationStage-ApplicationStackApplicationPipelineStackApplicationStageApplicationStackApplicationClusterF3918940KubectlProvider5C2B31FB` -------------------------->`ApplicationStage-ApplicationStackApplicationPipelineStackApplicationStageApplicationStackApplicationClusterF3918940Kubec5C2B31FB`

If any part of the path was longer we might end up without even the `Kubec` and just end with a 16 character hash at the end.

I almost feel like it should be the job of the id creator to make sure the id is within a certain length. In this case it would be the `KubectlProvider`.

I'm also curious if this is somehow a breaking change between v1 & v2. If the name of the stack is changing between v1 & v2 the user can't just deploy a new stack name. The user may need to just override the stack name.

**Comment by comcalvi** [comment]
This is no longer a breaking change, because we only rename stacks that are longer than 128 characters; that is, an error would be thrown if we didn't trim it (it used to be a breaking change, because previously this PR included logic to reduce the duplication in the name for all stacks made from the Kubectl provider logic regardless of name length).

We could have the kubectl provider try to estimate the length of its stack name and then cap it from there, but I think that may be inaccurate; we don't truly know the stack name until the stack constructor is called. I'll investigate to see if we can improve the readability of the stack name

**Comment by corymhall** [comment]
> This is no longer a breaking change, because we only rename stacks that are longer than 128 characters; that is, an error would be thrown if we didn't trim it (it used to be a breaking change, because previously this PR included logic to reduce the duplication in the name for all stacks made from the Kubectl provider logic regardless of name length).

By breaking change I was meaning that on v1 no error was thrown (stack name was < 128) and on v2 an error is thrown (stack name is now > 128). Why is the stack name changing between v1 & v2? For some reason on v2 the generated stack name is longer than it was on v2. If we trim the stack name, the name will still be different than what it was on v1 for customers that are running into this issue won't it?

**Comment by comcalvi** [comment]
I have not been able to detect a difference in the stack names between v1 and v2. I'm not sure what caused the issue the submitter experienced when they upgraded, but I can reproduce this exact same error on both v1 and v2. Therefore I don't believe this to be a breaking change.

File: packages/@aws-cdk/core/lib/private/uniqueid.ts [hunk 1]
```diff
@@ -67,6 +68,10 @@ export function makeUniqueId(components: string[]) {
     .join('')
     .slice(0, MAX_HUMAN_LEN);
 
+  if (maxLength && human.length + hash.length > maxLength) {
+    return human.slice(0, maxLength - hash.length) + hash;
+  }
```
Comment (Naumel) [inline packages/@aws-cdk/core/lib/private/uniqueid.ts:73]: This might be me being in way too many interviews, but would it not be nicer to find the longest duplicated substring in the string and remove the redundancy before the length checks?

`ApplicationStage-ApplicationStackApplicationPipelineStackApplicationStageApplicationStackApplicationClusterF3918940KubectlProvider5C2B31FB`
==>
`ApplicationStage-ApplicationStackApplicationPipelineStackApplicationStageClusterF3918940KubectlProvider5C2B31FB`

Comment (Naumel) [reply packages/@aws-cdk/core/lib/private/uniqueid.ts:73]: OR, to swing the opposite way, would a map from word to abbreviation work?
Keeps all the semantic, but trims the length.

Comment (comcalvi) [reply packages/@aws-cdk/core/lib/private/uniqueid.ts:73]: We have to remove any redundancy after the length checks (otherwise, it's a breaking change). I'll update this PR to remove the longest duplicated substring if the length is larger than 128; if the resulting string is still longer, it will fall back to the logic here.

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
We've talked about wanting to remove use of `uniqueId` because it isn't actually always unique. In fact, it's on my list of things to do to start deprecating it.

I would recommend switching to use of `Names.uniqueResourceName` instead.

**Comment by comcalvi** [comment]
@TheRealAmazonKendra are you planning to deprecate `Names.uniqueId` (https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/core/lib/names.ts#L17) or `makeUniqueId` (https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/core/lib/private/uniqueid.ts#L32)? This PR only uses `makeUniqueId`.

File: packages/@aws-cdk/core/lib/private/uniqueid.ts [hunk 2]
```diff
@@ -61,12 +85,24 @@ export function makeUniqueId(components: string[]) {
...
   const hash = pathHash(components);
-  const human = removeDupes(components)
+  let human = removeDupes(components)
     .filter(x => x !== HIDDEN_FROM_HUMAN_ID)
     .map(removeNonAlphanumeric)
     .join('')
     .slice(0, MAX_HUMAN_LEN);
 
+  if (maxLength && human.length + hash.length > maxLength) {
+    const indices = findLongestDuplicatedSubstring(human);
```
[the remark this answers is not in the document]
Comment (comcalvi) [reply packages/@aws-cdk/core/lib/private/uniqueid.ts:95]: Readability only

**Review by otaviomacedo — APPROVED** [review]

File: packages/@aws-cdk/core/lib/private/uniqueid.ts [hunk 3]
```diff
@@ -20,16 +20,40 @@ const HASH_LEN = 8;
...
  * This is done by calculating a hash on the full path and using it as a suffix
  * of a length-limited "human" rendition of the path components.
  *
  * @param components The path components
- * @returns a unique alpha-numeric identifier with a maximum length of 255
+ * @param maxLength The maximum length of the return value
+ * @returns a unique alpha-numeric identifier with a maximum length of 255 or the maxLength parameter
  */
-export function makeUniqueId(components: string[]) {
+export function makeUniqueId(components: string[], maxLength?: number) {
```
Comment (TheRealAmazonKendra) [inline packages/@aws-cdk/core/lib/private/uniqueid.ts:56]: This [function](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/core/lib/private/unique-resource-name.ts#L50) is already doing what these changes aim to do. I think we should use this instead. The only places where `makeUniqueId` is currently used is in `stack.ts`, where you're making the change and in `Names.uniqueId` which is not actually a unique id and should be deprecated. Can we use `makeUniqueResourceName` instead so we can eliminate the nearly duplicated code?

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]

**Comment by comcalvi** [comment]
adding `do-not-merge` so @Naumel can review

**Review by Naumel — APPROVED** [review]
lgtm
