### PR TITLE
fix(s3): missing http on website url

### LINKED ISSUE #4113: s3: Bucket property websiteUrl has invalid value on imported buckets
If you import an S3 bucket using `fromBucketName` the websiteUrl property has the wrong default value because it is missing the `http://` in front the the URL.

### Environment

  - **Framework Version:** 1.8.0

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by hoegertn**
fixes #4113 
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-s3/lib/bucket.ts [hunk 1]
```diff
@@ -883,16 +883,16 @@ export class Bucket extends BucketBase {
...
       : `${bucketName}.s3-website-${region}.${urlSuffix}`;
 
     class Import extends BucketBase {
       public readonly bucketName = bucketName!;
       public readonly bucketArn = parseBucketArn(scope, attrs);
       public readonly bucketDomainName = attrs.bucketDomainName || `${bucketName}.s3.${urlSuffix}`;
-      public readonly bucketWebsiteUrl = attrs.bucketWebsiteUrl || websiteUrl;
-      public readonly bucketWebsiteDomainName = Fn.select(2, Fn.split('/', attrs.bucketWebsiteUrl || websiteUrl));
+      public readonly bucketWebsiteUrl = attrs.bucketWebsiteUrl || `http://${websiteDomain}`;
+      public readonly bucketWebsiteDomainName = attrs.bucketWebsiteUrl ? attrs.bucketWebsiteUrl.split('/')[2] : websiteDomain;
```
Comment (eladb) [inline packages/@aws-cdk/aws-s3/lib/bucket.ts]: Since you don't know if `attrs.bucketWebsiteUrl` is a token or a concrete value, use `Fn.split` and `Fn.select` to parse it. Otherwise, it will fail if `bucketWebsiteUrl` is a token.
