### PR TITLE
fix(dynamoDB): make TableV2 taggable

### LINKED ISSUE #30631: (dynamodb): Dynamo TableV2 does not work with Tags.of
### Describe the bug

The `aws_dynamodb.TableV2` construct does not support adding tags via `Tags.of`.

I.e., the following code does not create the `myKey` tag.

``` 
import * as cdk from 'aws-cdk-lib';
import {aws_dynamodb, Tags} from "aws-cdk-lib";

const app = new cdk.App();
const stack = new cdk.Stack(app, 'Stack');

const globalTable = new aws_dynamodb.TableV2(stack, 'GlobalTable', {
    partitionKey: {name: 'pk', type: aws_dynamodb.AttributeType.STRING},
});

Tags.of(globalTable).add('myKey', 'myValue');
```

### Expected Behavior

Creates tag.

### Current Behavior

Does not create tag.

### Reproduction Steps

``` 
import * as cdk from 'aws-cdk-lib';
import {aws_dynamodb, Tags} from "aws-cdk-lib";

const app = new cdk.App();
const stack = new cdk.Stack(app, 'Stack');

const globalTable = new aws_dynamodb.TableV2(stack, 'GlobalTable', {
    partitionKey: {name: 'pk', type: aws_dynamodb.AttributeType.STRING},
});

Tags.of(globalTable).add('myKey', 'myValue');
```

cdk synth

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.147.0 (build 3338fc0)

### Framework Version

_No response_

### Node.js Version

v20.3.1

### OS

Macos

### Language

TypeScript

### Language Version

TypeScript 5.4.5

### Other information

_No response_

### PR DESCRIPTION
**Pull request by 5d**
### Issue # (if applicable)

Closes #30631 

### Reason for this change

The [`AWS::DynamoDB::GlobalTable`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-globaltable.html) resource does not natively support tags. However, at the L2 level (`TableV2`), the [`tags`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_dynamodb.TableV2.html#tags) option is available when creating this resource, which may give customers the impression that it is taggable. When customers apply tags using the aspect at the `TableV2` level, it’s likely they intend to tag all replicas, as each replica has its own `tags` property as well. This behavior also aligns with the related [construct documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_dynamodb.TableV2.html#tags).

### Description of changes

- Enable tagging for `TableV2`
- If a tag key is defined in the replica `tags` properties, it will take precedence over the `TagAspect` for that key, as it is more specific.
- Keep the `tags` property behavior in `TableV2`
  - Update the description doc on it to reflect that it only applies to the default replica table

### Description of how you validated changes

- added new unit test cases
- deployed related integration test cases

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-dynamodb/lib/table-v2.ts [hunk 1]
```diff
@@ -516,6 +533,7 @@ export class TableV2 extends TableBaseV2 {
     this.partitionKey = props.partitionKey;
     this.hasSortKey = props.sortKey !== undefined;
     this.region = this.stack.region;
+    this.tags = new TagManager(TagType.STANDARD, CfnGlobalTable.CFN_RESOURCE_TYPE_NAME, props.tags);
```
Comment (GavinZZ) [inline packages/aws-cdk-lib/aws-dynamodb/lib/table-v2.ts:536]: We don't typically add TagManager to the L2 resource. Typically the Cfn L1 resource is already extending ITaggable and the tags are directly added to the L1 resource. This might be some edge case we need to fix in the L1 generation.

File: packages/aws-cdk-lib/aws-dynamodb/test/table-v2.test.ts [hunk 2]
```diff
@@ -777,7 +777,10 @@ describe('table', () => {
             KMSMasterKeyId: 'arn:aws:kms:us-east-1:123456789012:key/g24efbna-az9b-42ro-m3bp-cq249l94fca6',
           },
           TableClass: 'STANDARD_INFREQUENT_ACCESS',
-          Tags: [{ Key: 'USE1Key', Value: 'USE1Value' }],
+          Tags: [
+            { Key: 'USW2Key', Value: 'USW2Value' },
+            { Key: 'USE1Key', Value: 'USE1Value' },
+          ],
```
Comment (GavinZZ) [inline packages/aws-cdk-lib/aws-dynamodb/test/table-v2.test.ts:783]: I don't see any change in the CDK app, why is there an additional tag?

File: packages/aws-cdk-lib/aws-dynamodb/test/table-v2.test.ts [hunk 3]
```diff
@@ -1293,6 +1299,72 @@ describe('replica tables', () => {
...
+            { Key: 'tableTagProperty', Value: 'replicaTagPropertyValue' },
+            { Key: 'tagAspect', Value: 'tagAspectValue' },
+          ],
+        },
+        {
+          Region: 'us-east-1',
+          Tags: [
+            { Key: 'tableTagProperty', Value: 'globalTagPropertyValue' },
+            { Key: 'tagAspect', Value: 'tagAspectValue' },
+          ],
```
Comment (GavinZZ) [inline packages/aws-cdk-lib/aws-dynamodb/test/table-v2.test.ts:1362]: Is this the right behaviour? `tableTagProperty` is only added to `us-west-1` replica but showed up in `us-east-1` too.

File: packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb-v2.ondemand.js.snapshot/aws-cdk-global-table.template.json [hunk 4]
```diff
@@ -124,7 +124,13 @@
...
       },
       "Region": "eu-west-1",
-      "TableClass": "STANDARD_INFREQUENT_ACCESS"
+      "TableClass": "STANDARD_INFREQUENT_ACCESS",
+      "Tags": [
+       {
+        "Key": "primaryTableTagKey",
+        "Value": "primaryTableTagValue"
+       }
+      ]
```
Comment (GavinZZ) [inline packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb-v2.ondemand.js.snapshot/aws-cdk-global-table.template.json:133]: Where's this change from?

**Review by GavinZZ — DISMISSED** [review]
IMO I think this is an issue with the spec2cdk generation and something we should fix in the L1 generation instead of L2 side.

File: packages/aws-cdk-lib/aws-dynamodb/test/table-v2.test.ts (hunk 3 above)
Comment (GavinZZ) [reply packages/aws-cdk-lib/aws-dynamodb/test/table-v2.test.ts:1362]: Our current documentation seems to specifically say `You can add tags to a `TableV2` in several ways. By adding the tags to the construct itself it will apply the tags to the primary table.`

File: packages/aws-cdk-lib/aws-dynamodb/lib/table-v2.ts (hunk 1 above)
Comment (GavinZZ) [reply packages/aws-cdk-lib/aws-dynamodb/lib/table-v2.ts:536]: I took a deep dive into the Global Table usage and you're right. We wouldn't be able to make L1 ITaggable directly. I agree with you that this is a good workaround. 

My second question is on why did you choose to use TagManager (which is the TagV2 solution) instead of directly using the V1. I believe using V1, you can directly add 

```
protected readonly tags?: CfnTag[];
```

File: packages/aws-cdk-lib/aws-dynamodb/test/table-v2.test.ts (hunk 3 above)
Comment (GavinZZ) [reply packages/aws-cdk-lib/aws-dynamodb/test/table-v2.test.ts:1362]: https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-dynamodb/README.md#tags

File: packages/aws-cdk-lib/aws-dynamodb/lib/table-v2.ts (hunk 1 above)
Comment (GavinZZ) [reply packages/aws-cdk-lib/aws-dynamodb/lib/table-v2.ts:536]: You didn't make the construct `ITaggable` or `ITaggableV2` either right? When you use `Tags.of().add`, it is essentially adding an Aspect that will run during synthesis, https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/core/lib/tag-aspect.ts#L74. It will subsequently check whether if it's taggable using V1 or V2. 

For V1 tagging, it will only check the following:
```
const tags = (construct as any).tags;
return tags !== undefined && tags !== null && typeof tags === 'object' && (tags as any)[TAG_MANAGER_SYM];
```

I'm not sure when should we use V1 and when to use V2, i.e. when to define a tags object and when to define tagManager.

Comment (GavinZZ) [reply packages/aws-cdk-lib/aws-dynamodb/lib/table-v2.ts:536]: Ahh nice catch, I didn't realize `ITaggable` interface uses `TagManager`.

**Comment by GavinZZ** [comment]
Thanks for addressing the other comments. I'm happy to approve once we check with the service team and update the documentation.

File: packages/aws-cdk-lib/aws-dynamodb/lib/table-v2.ts [hunk 5]
```diff
@@ -483,6 +498,8 @@ export class TableV2 extends TableBaseV2 {
 
   protected readonly region: string;
 
+  protected readonly tags: TagManager;
```
Comment (moelasmar) [inline packages/aws-cdk-lib/aws-dynamodb/lib/table-v2.ts:501]: I see that you chose [the ITaggable  approach ](https://github.com/aws/aws-cdk/blob/be70c822a1608cb43a4b4b17fc0430f3352797c6/packages/aws-cdk-lib/core/lib/tag-manager.ts#L236). Why not to add it to the interfaces that this class implements to be easier for readers to know that this class is taggable.

File: packages/aws-cdk-lib/aws-dynamodb/lib/table-v2.ts [hunk 6]
```diff
@@ -674,6 +693,15 @@ export class TableV2 extends TableBaseV2 {
...
 
+    const propTags: Record<string, string> = (props.tags ?? []).reduce((p, item) =>
+      ({ ...p, [item.key]: item.value }), {},
+    );
+
+    const tags: CfnTag[] = Object.entries({
+      ...this.tags.tagValues(),
+      ...propTags,
+    }).map(([k, v]) => ({ key: k, value: v }));
+
```
Comment (moelasmar) [inline packages/aws-cdk-lib/aws-dynamodb/lib/table-v2.ts:704]: can you use TagManager.renderTags function instead of handling it manually. You can check [this example](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/sagemaker/create-transform-job.ts#L174) for how to use it

File: packages/aws-cdk-lib/aws-dynamodb/test/table-v2.test.ts [hunk 7]
```diff
@@ -1293,6 +1293,78 @@ describe('replica tables', () => {
...
+
+    // WHEN
+    const table = new TableV2(stack, 'Table', {
+      partitionKey: { name: 'pk', type: AttributeType.STRING },
+      replicas: [{
+        region: 'us-west-1',
+      }],
+    });
+
+    Tags.of(table).add('tagKey', 'tagValue');
```
Comment (moelasmar) [inline packages/aws-cdk-lib/aws-dynamodb/test/table-v2.test.ts:1308]: can you add a new test case where you can Tag a parent constructor like the stack itself, and figure out if the Table resource will be tagged as with. Like for example I want to tag all resources in Production stack as `resourceType - > Prod`

Comment (moelasmar) [reply packages/aws-cdk-lib/aws-dynamodb/test/table-v2.test.ts:1308]: also add it to the integ testing

**Review by moelasmar — DISMISSED** [review]
In general looks good to me, I just left some minor comments.

**Review by moelasmar — APPROVED** [review]
