### PR TITLE
fix(lambda): fromDockerBuild output is located under /asset

### LINKED ISSUE #13439: (aws-lambda): fromDockerBuild output is located incorrectly
In `v1.92.0`, when `fromDockerBuild` is used, it is expected that _contents_ `/asset` is copied, but instead the whole `/asset` is copied to output path, this makes Lambda handler reference `index.handler` failed, it has to be `asset/index.handler`.

### Reproduction Steps

Create a index.js.

```js
exports.handler = () => {
  console.info("Test");
}
```
A Dockerfile:

```dockerfile
FROM amazon/aws-sam-cli-build-image-nodejs14.x
COPY index.js /asset/
```

Use `lambda.Code.fromDockerBuild`:

```ts
export class ExampleStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new lambda.Function(this, "ExampleFunction", {
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: "index.handler",
      code: lambda.Code.fromDockerBuild(ROOT_DIR),
    });
  }
}
```

### What did you expect to happen?

The Lamda code contains only `index.js`.

### What actually happened?

The Lambda code contains `asset/index.js`.

### Environment

  - **CDK CLI Version  :** 1.92.0
  - **Framework Version:** 1.92.0
  - **Node.js Version:** 14
  - **OS               :** macOS Catalina
  - **Language (Version):**  TypeScript 4.2.3

### Other

This is caused by expected behavior of [`docker cp`](https://docs.docker.com/engine/reference/commandline/cp/).

Suggestion: automatically append `/.` to `imagePath` if it doesn't.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by jogold**
Ensure `imagePath` ends with `/.` so that the content at that location
is copied.

See https://docs.docker.com/engine/reference/commandline/cp/

Closes #13439

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jogold** [comment]
@eladb

File: packages/@aws-cdk/aws-lambda/lib/code.ts [hunk 1]
```diff
@@ -67,9 +67,11 @@ export abstract class Code {
    * @param options Docker build options
    */
   public static fromDockerBuild(path: string, options: DockerBuildAssetOptions = {}): AssetCode {
+    const imagePath = options.imagePath ?? '/asset';
     const assetPath = cdk.DockerImage
       .fromBuild(path, options)
-      .cp(options.imagePath ?? '/asset', options.outputPath);
+      // ensure imagePath ends with /. to copy the **content** at this path
+      .cp(imagePath.replace(/(\/|\/\.)?$/, '/.'), options.outputPath);
```
Comment (eladb) [inline packages/@aws-cdk/aws-lambda/lib/code.ts:74]: I rather avoid the regex here and write simple code like:

```ts
const parts = imagePath.split('/');
if (parts[parts.length - 1] !== '.') {
  parts.push('.')
}
return parts.join('/');
```

Or something like this.

**Review by eladb — DISMISSED** [review]
Test missing?

**Review by eladb — APPROVED** [review]
