### PR TITLE
fix(custom-resources): IAM policy incorrect for SDKv3 names

### LINKED ISSUE #27255: (custom-resources): AwsCustomResourcePolicy.fromSdkCalls does not work with v3 command format
### Describe the bug

Creating an AwsCustomResource with a service/action using the AWS CDK v3 format and a policy AwsCustomResourcePolicy.fromSdkCalls fails

### Expected Behavior

A policy is correctly created

### Current Behavior

```
Error: Action '@aws-sdk/client-ec2:ModifyInstanceMetadataOptionsCommand' is invalid. An action string consists of a service namespace, a colon, and the name of an action. Action names can include wildcards.
    at PolicyStatement.validatePolicyActions (/home/jonathan/Development/eterna/infra/node_modules/aws-cdk-lib/aws-iam/lib/policy-statement.js:2:3414)
    at PolicyStatement.addActions (/home/jonathan/Development/eterna/infra/node_modules/aws-cdk-lib/aws-iam/lib/policy-statement.js:2:1290)
    at new PolicyStatement (/home/jonathan/Development/eterna/infra/node_modules/aws-cdk-lib/aws-iam/lib/policy-statement.js:2:579)
    at new AwsCustomResource (/home/jonathan/Development/eterna/infra/node_modules/aws-cdk-lib/custom-resources/lib/aws-custom-resource/aws-custom-resource.js:1:5701
```

### Reproduction Steps

The call I'm currently running into this with:

```ts
new AwsCustomResource(instance, `enableMetadataTags`, {
  onCreate: {
    service: '@aws-sdk/client-ec2',
    action: 'ModifyInstanceMetadataOptionsCommand',
    parameters: {
      InstanceId: instance.instanceId,
      InstanceMetadataTags: 'enabled'
    },
    physicalResourceId: PhysicalResourceId.of('EnableMetadataTags')
  },
  onDelete: {
    service: '@aws-sdk/client-ec2',
    action: 'ModifyInstanceMetadataOptionsCommand',
    parameters: {
      InstanceId: instance.instanceId,
      InstanceMetadataTags: 'disabled'
    }
  },
  policy: AwsCustomResourcePolicy.fromSdkCalls({
    resources: AwsCustomResourcePolicy.ANY_RESOURCE
  })
});
```

### Possible Solution

I'm assuming to construct the correct policy, the service name needs to strip `@aws-sdk/client-` and the action needs to strip `Command`

### Additional Information/Context

_No response_

### CDK CLI Version

2.94.0 (build 987c329)

### Framework Version

_No response_

### Node.js Version

v18.17.1

### OS

Linux

### Language

Typescript

### Language Version

_No response_

### Other information

If my assessment is correct, this should be easy for me to submit a PR for if that would be helpful!

### LINKED ISSUE #27395: (integ-tests-alpha): invokeFunction is returning Uint8ArrayBlobAdapter each time versus converting to String or JSON object
### Describe the bug

Hey I'm using the `import { IntegTest, ExpectedResult } from '@aws-cdk/integ-tests-alpha';` for writing some integration tests. I'm trying to invoke a lambda function and then check the response payload that it sends back but seems the payload sent back is always of Uint8ArrayBlobAdapter instead of a string or JSON object.

At a high level gist.

``` typescript
integ.assertions.invokeFunction({
  functionName: testLambda.functionName,
}).expect(ExpectedResult.objectLike({
  StatusCode: 200,
  Payload: JSON.stringify({
    code: 200,
  }),
}));
```

CDK Version: `2.99.1`

### Expected Behavior

Be able to check the Payload and validate its the expected response in String or JSON format

### Current Behavior

From the logs I see the following coming back to the lambda

```text
2023-10-03T19:25:14.966Z	44e46c89-f5c2-4f0e-a119-8fddd2ab6000	INFO	SDK response received 
{
    "$metadata": {
        "httpStatusCode": 200,
        "requestId": "5ffd7187-3dc6-4bfb-b0d0-7191d2daadbf",
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "ExecutedVersion": "$LATEST",
    "Payload": {
        "0": 34,
        "1": 53,
        "2": 48,
        "3": 48,
        "4": 34
    },
    "StatusCode": 200
}
```

For now I'm just gonna fail the lambda :sad

### Reproduction Steps

```
import { IntegTest, ExpectedResult } from '@aws-cdk/integ-tests-alpha';
import { App, Stack } from 'aws-cdk-lib';
import * as lambda from 'aws-cdk-lib/aws-lambda';

const accountID = '123456789012';
const region = 'us-east-1';

const app = new App();

const stack = new Stack(app, 'SampleAppStack', {
  tags: {
    blockCode: 'xxxx',
  },
  env: {
    account: accountID,
    region: region,
  },
});

new lambda.Function(stack, 'lambda', {
  runtime: lambda.Runtime.NODEJS_18_X,
  handler: 'index.handler',
  code: lambda.Code.fromInline(`exports.handler = async (event) => {
      return "200"
    };`),
});

// Initialize Integ Test construct
const integStack = new Stack(app, 'IntegrationTestAssertions', {
  tags: {
    blockCode: 'xxxxx',
  },
  env: {
    account: accountID,
    region: region,
  },
});

const integ = new IntegTest(app, 'DatabaseStackIntegrationTest', {
  testCases: [stack], // Define a list of cases for this test
  cdkCommandOptions: {
    // Customize the integ-runner parameters
    destroy: {
      args: {
        force: true,
      },
    },
  },
  assertionStack: integStack,
  regions: [stack.region],
});

const invokeFunction = new lambda.Function(integStack, 'lambda', {
  runtime: lambda.Runtime.NODEJS_18_X,
  handler: 'index.handler',
  code: lambda.Code.fromInline(`exports.handler = async (event) => {
        return "200"
      };`),
});

integ.assertions.invokeFunction({
  functionName: invokeFunction.functionName,
  payload: JSON.stringify({ data: 'Hello World!' }),
}).expect(ExpectedResult.objectLike({
  StatusCode: 200,
  Payload: '200',
}));

```

### Possible Solution

_No response_

### Additional Information/Context

https://github.com/aws/aws-sdk-js-v3/issues/2252#issuecomment-1603298789 is interesting regarding Uint8ArrayBlobAdapter

### CDK CLI Version

2.99.1

### Framework Version

2.99.1

### Node.js Version

v18.15.0

### OS

mac

### Language

Typescript

### Language Version

~5.1.0

### Other information

    '@aws-cdk/integ-runner@^2.99.1-alpha.0',
    '@aws-cdk/integ-tests-alpha@^2.99.1-alpha.0',

### PR DESCRIPTION
**Pull request by rix0rrr**
In the `AwsCustomResource` and the `Assertions` libraries, we advertise accepting all of the following service name formats:

* The SDKv3 service name: `api-gateway`
* The full SDKv3 package name: `@aws-sdk/client-api-gateway`
* The SDKv2 constructor name: `APIGateway`
* The SDKv2 constructor name in all lower case: `apigateway`

And the following action name formats:

* The API call name: `GetRestApi`
* The API call name with a lowercase starting letter method name: `getRestApi`
* The SDKv3 command class name: `GetRestApiCommand`

However, the code that was taking care of mapping service names into an IAM name was not handling all cases correctly. There was also an issue with some commands that end in the word `"Command"`, like ECS's `ExecuteCommand`, which according to the rules above should work both written as `ExecuteCommand` as well as `ExecuteCommandCommand`: we did not have enough information to know if we saw the string `ExecuteCommand`, whether we should interpret it as `Execute` or `ExecuteCommand`.

Also, we were recommending to use the full SDKv3 package name and class name formats:

```
{
  service: '@aws-sdk/client-api-gateway',
  action: 'GetRestApiCommand',
}
```

Which looks ugly (imo) and leaks too many of the underlying implementation details.

This PR changes the following:

- Deprecate the `sdk-api-metadata.json` we extracted from SDKv2.
- From SDKv3 models, extract a new `sdk-v3-metadata.json` which contains the following information:
  - IAM prefix for every service
  - A list of APIs that end in the word `Command`, so we can disambiguate around these.
- From `aws-sdk-codemod`, extract a mapping from SDKv2 service names to SDKv3 service names (replacing the copy/pasted code we used to have with a build-time extraction).
- Unfortunately, both of these mappings are duplicated: once for the construct library, and once for the handlers. I did not want to go into deduplicating between these for now.
- At runtime, we now map a potential V2 service name to a V3 service name, then look up the V3 metadata to determine the IAM prefix and the normalized action name.
- There was a lot of duplication between the `assertions` handler and the `AwsCustomResource` handler (and to a lesser degree, the `events.ApiCall` handler), around loading SDKs and coercing values. Introduce a new `ApiCall` class that unifies the behavior between these call sites.
- Change the recommendation in the README from using SDKv3 names to using shorter form names (`api-gateway` and `GetRestApi`).
- Add "dynamic reuqire" protection to the `esbuild` commands for custom resources. 

Fixes #27255, closes #27268, closes #27270, closes #27395.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/sdk-v2-to-v3-adapter/lib/api-call.ts [hunk 1]
```diff
@@ -0,0 +1,249 @@
...
+   *
+   * @default false
+   */
+  readonly flattenResponse?: boolean;
+}
+
+/**
+ * Wrapper to make an SDKv3 API call, with SDKv2 compatibility
+ */
+export class ApiCall {
```
Comment (MrArnoldPalmer) [inline packages/@aws-cdk/sdk-v2-to-v3-adapter/lib/api-call.ts:54]: I wonder if we should name this coupling it to the version of the sdk it uses? IE `V3ApiCall`. I get that it's an API call and not necessarily an "SdkCall", but since `v3PackageName` is a public field it seems to be coupled to v3 of the sdk and once v4 is a thing we would essentially deprecate it in favor of a new one?

Comment (MrArnoldPalmer) [reply packages/@aws-cdk/sdk-v2-to-v3-adapter/lib/api-call.ts:54]: Or is this only for testing purposes too?

**Review by MrArnoldPalmer — APPROVED** [review]
Approved with DNM. I'm onboard with the deprecation of metadata and the change in opinion to not use the v3 specific library service formatting, and of course all the dedupe stuff.

A question around naming/versioning but on second thought I'm less concerned with it but I'll give you a chance to respond in case it does spark something for you or @mrgrain .

**Comment by gerardorn** [comment]
Not sure if this is will solve the issue but im having the same problem with @aws-sdk/client-network-firewall

```go
fwEndpoints := customresources.NewAwsCustomResource(nested, jsii.String("route"), &customresources.AwsCustomResourceProps{
  OnCreate: &customresources.AwsSdkCall{
    Service:            jsii.String("@aws-sdk/client-network-firewall"),
    Action:             jsii.String("DescribeFirewallCommand"),
    PhysicalResourceId: customresources.PhysicalResourceId_Of(jsii.String("route")),
    Parameters: map[string]interface{}{
      "FirewallName": jsii.String(*fw.FirewallName()),
    },
  },
  Policy: customresources.AwsCustomResourcePolicy_FromSdkCalls(&customresources.SdkCallsPolicyOptions{
    Resources: customresources.AwsCustomResourcePolicy_ANY_RESOURCE(),
  }),
})
```

Error message:
`panic: Action '@aws-sdk/client-network-firewall:DescribeFirewallCommand' is invalid. An action string consists of a service namespace, a colon, and the name of an action. Action names can include wildcards.`

File: packages/@aws-cdk/sdk-v2-to-v3-adapter/lib/api-call.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/@aws-cdk/sdk-v2-to-v3-adapter/lib/api-call.ts:54]: With a little luck for V4 we would keep the public API the same... and yeah maybe add a `v4PackageName` and/or remove the old one.

**Comment by rix0rrr** [comment]
@gerardorn yes it will. You can unblock yourself by not using the SDKv3 package names, but just using the simple (V2) service and action name (`networkfirewall`, `describeFirewall`), or adding the IAM permission explicitly.

File: packages/@aws-cdk/sdk-v2-to-v3-adapter/lib/api-call.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/@aws-cdk/sdk-v2-to-v3-adapter/lib/api-call.ts:54]: Honestly, the only reason the `v3PackageName` is in there is because I didn't want to lift `installLatestAwsSdk` into this as well (which I friggin' hate 🤪), and so it needs to be POSSIBLE for someone else to load the SDK from somewhere

**Comment by gerardorn** [comment]
hey @rix0rrr, thanks for your answer 🙏🏼 
Tried using all lower case and didn't work

`Received response status [FAILED] from custom resource. Message returned: Client 'networkfirewall' is either deprecated or newly added. Please consider using the v3 package format (@aws-sdk/client-xxx). (RequestId: ab36f12a-7d03-4fce-8237-38b91f7cc5c6)`

Had to use this approach

```go
fwEndpoints := customresources.NewAwsCustomResource(nested, jsii.String("route"), &customresources.AwsCustomResourceProps{
  OnCreate: &customresources.AwsSdkCall{
    Service:            jsii.String("NetworkFirewall"),
    Action:             jsii.String("describeFirewall"),
    PhysicalResourceId: customresources.PhysicalResourceId_Of(jsii.String("route")),
    Parameters: map[string]interface{}{
      "FirewallName": jsii.String(*fw.FirewallName()),
    },
  },
  Policy: customresources.AwsCustomResourcePolicy_FromSdkCalls(&customresources.SdkCallsPolicyOptions{
    Resources: customresources.AwsCustomResourcePolicy_ANY_RESOURCE(),
  }),
})
```

Hope this helps 🙌🏼

**Review by mrgrain — APPROVED** [review]
