### PR TITLE
fix(events-targets): EventBus IAM statements are only added for the first target

### LINKED ISSUE #19407: (events-targets): Wrong role used when adding multiple EventBus targets
### What is the problem?

When adding an `EventBus` target to a rule, CDK creates a role that grants `PutEvents` on the event bus. If we add multiple event buses this way, they will all share a single role that only grant access to the first event bus that we pass.

### Reproduction Steps

Consider the following code:

```
rule = events.Rule(
    self,
    "rule",
    event_pattern=events.EventPattern(
        source=["aws.ecr"],
    ),
)
for i in range(5):
   bus = events.EventBus(self, f"bus-{i}")
   rule.add_target(events_targets.EventBus(bus))
```

The rule will use a role that only has access to `bus-0`, and it will use this role for all targets.

### What did you expect to happen?

Each target uses a different role with proper access.

### What actually happened?

All targets share a role that only grant access to a single target.

### CDK CLI Version

2.16

### Framework Version

2.16

### Node.js Version

17.7.1

### OS

MacOS

### Language

Typescript, Python

### Language Version

_No response_

### Other information

I understand the issue may be here: https://github.com/aws/aws-cdk/blob/e63a03dd2d39502328b0f6baf1ee5529038a4f54/packages/%40aws-cdk/aws-events-targets/lib/event-bus.ts#L42

### PR DESCRIPTION
**Pull request by comcalvi**
If the `EventBus` constructor is called with no arguments, then attaching more than a single target to its policy will silently fail to add them. This is because of a strange edge case in the implementation that was not accounted for previously; it is possible for `props.role` to be `undefined`, yet `singletonEventRole()` is still capable of finding the desired role. `singletonEventRole()` does not add the new statements to any IAM policies that it finds, so as a result adding multiple targets does not add any of them.

Fixes #19407.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-events-targets/lib/event-bus.ts [hunk 1]
```diff
@@ -36,10 +36,8 @@ export class EventBus implements events.IRuleTarget {
   constructor(private readonly eventBus: events.IEventBus, private readonly props: EventBusProps = {}) { }
 
   bind(rule: events.IRule, _id?: string): events.RuleTargetConfig {
-    if (this.props.role) {
-      this.props.role.addToPrincipalPolicy(this.putEventStatement());
-    }
-    const role = this.props.role ?? singletonEventRole(rule, [this.putEventStatement()]);
+    const role = this.props.role ?? singletonEventRole(rule, []);
```
Comment (corymhall) [inline packages/@aws-cdk/aws-events-targets/lib/event-bus.ts:39]: I wonder if we should change the implementation of `singletonEventRole` to _not_ take any statements to prevent this from happening in the future.
