### PR TITLE
fix(lambda): grantInvoke fails on second invocation

### LINKED ISSUE #8553: One lambda with two ALBs --> Error: There is already a Construct with name 'InvokeServicePrincipal(elasticloadbalancing.amazonaws.com)' in Function
### The Question
When I'm trying to add one lambda function to two Application Load Balancers I'm getting this error:
```
\node_modules\constructs\lib\construct.ts:487
      throw new Error(`There is already a Construct with name '${childName}' in ${typeName}${name.length > 0 ? ' [' + name + ']' : ''}`);
            ^
Error: There is already a Construct with name 'InvokeServicePrincipal(elasticloadbalancing.amazonaws.com)' in Function [SharedLambda]
    at Node.addChild (shared-lambda\node_modules\constructs\lib\construct.ts:487:13)
    at new Node (shared-lambda\node_modules\constructs\lib\construct.ts:73:22)
    at new ConstructNode (shared-lambda\node_modules\@aws-cdk\core\lib\construct-compat.ts:265:24)
    at Object.createNode (shared-lambda\node_modules\@aws-cdk\core\lib\construct-compat.ts:71:11)
    at new Construct (shared-lambda\node_modules\constructs\lib\construct.ts:528:26)
    at new Construct (shared-lambda\node_modules\@aws-cdk\core\lib\construct-compat.ts:68:5)
    at new CfnElement (shared-lambda\node_modules\@aws-cdk\core\lib\cfn-element.ts:54:5)
    at new CfnRefElement (shared-lambda\node_modules\@aws-cdk\core\lib\cfn-element.ts:145:1)
    at new CfnResource (shared-lambda\node_modules\@aws-cdk\core\lib\cfn-resource.ts:83:5)
    at new CfnPermission (shared-lambda\node_modules\@aws-cdk\aws-lambda\lib\lambda.generated.ts:2649:9)
Subprocess exited with error 1
```
This looks like a bug because there are no problems when I'm doing this in Console. 
Or maybe I'm doing something wrong?

### Environment

  - **CDK CLI Version:** 1.45.0 (build 0cfab15)
  - **Module Version:** 1.45.0
  - **Node.js Version:** v12.16.1
  - **OS:** all
  - **Language (Version):** all

```Typescript
export class SharedLambdaStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = new ec2.Vpc(this, 'VpcForAlbs', {
      cidr: '10.0.0.0/16',
      subnetConfiguration: [{
        cidrMask: 28,
        name: 'Public',
        subnetType: ec2.SubnetType.PUBLIC,
      }], 
      maxAzs: 2, 
    })

    const sharedLambda = new lambda.Function(this, 'SharedLambda', {
      runtime: lambda.Runtime.NODEJS_12_X,
      code: lambda.Code.fromAsset('lambda'),
      handler: 'hello.handler'
    })

    this.addLb('FirstAlb', vpc, sharedLambda);
    this.addLb('SecondAlb', vpc, sharedLambda);
  }

  private addLb(id: string, vpc: IVpc, func: lambda.Function) {
    const lb = new elbv2.ApplicationLoadBalancer(this, id, {
      vpc,
      internetFacing: true
    });

    const listener = lb.addListener(`${id}-Listener`, { port: 80, open: true });
    listener.addTargets(`${id}-Targets`, {
      targets: [new targets.LambdaTarget(func)],
    });
  }
}
```

### PR DESCRIPTION
**Pull request by njlynch**
If `grantInvoke()` is called twice for the same principal, the second call fails
due to attempting to create two `CfnPermission` nodes with the same id. This
(simple) fix skips the second creation if the node already exists.

A more robust check would be to check the existing `CfnPermission`, comparing
every field, skipping creation if the two are identical and throwing an error
otherwise, as well as handling that in the upstream `grantInvoke` call. I opted
for the simpler solution for now, but willing to take arguments for something
more complex.

I also nested the existing grantInvoke tests for future readability. The tests weren't changed,
just the last one added.

fixes #8553

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by nija-at** [comment]
Looking at the original ALB issue, this 'feels' like a case where the two ALBs should be (but are not) calling `addPermission()` with unique scope/id combination.

Can you point to the calling point where this error is occurring?

**Comment by njlynch** [comment]
> Can you point to the calling point where this error is occurring?

It's actually not `addPermission` directly, but indirectly through `grantInvoke`:

https://github.com/aws/aws-cdk/blob/3c116f3b5854726bef610e425fc35f2d2b50a179/packages/@aws-cdk/aws-elasticloadbalancingv2-targets/lib/lambda-target.ts#L21

All ALBs will make the same `grantInvoke` call with `elasticloadbalancing.amazonaws.com`, which generates the same id for the `addPermission` call.

File: packages/@aws-cdk/aws-lambda/lib/function-base.ts [hunk 1]
```diff
@@ -209,14 +209,17 @@ export abstract class FunctionBase extends Resource implements IFunction {
...
-    new CfnPermission(scope, id, {
-      action,
-      principal,
-      functionName: this.functionArn,
-      eventSourceToken: permission.eventSourceToken,
-      sourceAccount: permission.sourceAccount,
-      sourceArn: permission.sourceArn,
-    });
+    // Skip duplicate permissions nodes. A more robust check would verify if the existing node matches the new one exactly.
+    if (!scope.node.tryFindChild(id)) {
```
Comment (eladb) [inline packages/@aws-cdk/aws-lambda/lib/function-base.ts:213]: This doesn't feel like the right place to fix this bug. If two unaware 3rd party construct libraries call `fn.addPermission()` with the same `id`, the second will be silently ignored? Doesn't make sense.

Feels like the right place to fix this is at the higher level API where there is more context

**Review by eladb — CHANGES_REQUESTED** [review]

**Comment by eladb** [comment]
> > Can you point to the calling point where this error is occurring?
> 
> It's actually not `addPermission` directly, but indirectly through `grantInvoke`:
> 
> https://github.com/aws/aws-cdk/blob/3c116f3b5854726bef610e425fc35f2d2b50a179/packages/@aws-cdk/aws-elasticloadbalancingv2-targets/lib/lambda-target.ts#L21
> 
> All ALBs will make the same `grantInvoke` call with `elasticloadbalancing.amazonaws.com`, which generates the same id for the `addPermission` call.

I think the solution should be in the ELB code, not lambda.

**Comment by nija-at** [comment]
> > Can you point to the calling point where this error is occurring?
> 
> It's actually not `addPermission` directly, but indirectly through `grantInvoke`:
> 
> https://github.com/aws/aws-cdk/blob/3c116f3b5854726bef610e425fc35f2d2b50a179/packages/@aws-cdk/aws-elasticloadbalancingv2-targets/lib/lambda-target.ts#L21
> 
> All ALBs will make the same `grantInvoke` call with `elasticloadbalancing.amazonaws.com`, which generates the same id for the `addPermission` call.

What I gather is happening is that - there are two ALBs using the same lambda function and hence need to `AWS::Lambda::Permission` resources. Did I get that correctly?

If so, I think the resource id should either be the ALB name (+ function name) scoped under the lambda function construct, or the other way around (i.e. id should be function construct, scope should be ALB).
I gather the second one would be better in preventing cyclic dependencies when used across stacks.

File: packages/@aws-cdk/aws-lambda/lib/function-base.ts (hunk 1 above)
Comment (njlynch) [reply packages/@aws-cdk/aws-lambda/lib/function-base.ts:213]: One other alternative I toyed with was fixing this just one level up, in the `grantInvoke` call. That feels like a slightly better compromise to me than making ELB have to deal with this. It makes reasonable sense to me that `grantInvoke` should be an idempotent operation, and not explode on duplicate calls. 

If the ELB code deals with this, the ELB code will have to have implementation-level details of how the Lambda grant is implemented, either by looping through all possible associated permissions or looking for the `Invoke${grantee}`-id'ed node, both of which seem like abstraction leakage to me.

**Comment by njlynch** [comment]
> What I gather is happening is that - there are two ALBs using the same lambda function and hence need two `AWS::Lambda::Permission` resources. Did I get that correctly?

Yes and no. The use case is two ALBs using the same Lambda function (yes); they do **not** need two `Permission` resources though (no). There is nothing resource-specific about the `Permission`; it is generally allowing ELB to invoke the Lambda, not a specific invocation by a specific load balancer.

We _could_ create two resources (I think - haven't tested if this explodes for some reason), but there's no need to. Much better to detect that the permission already exists and re-use it. @eladb  and I disagree on whether that should be Lambda's job or ELB's job. Feel free to act as a tie-breaker. :)

File: packages/@aws-cdk/aws-lambda/lib/function-base.ts (hunk 1 above)
Comment (eladb) [reply packages/@aws-cdk/aws-lambda/lib/function-base.ts:213]: Maybe we can offer something like `fn.hasPermission(id)` or something to that affect to prevent the leakage?

Agreed that `grantInvoke()` should not explode on duplicate calls but we can't use the ID as the arbiter. It has to be the entire configuration.

**Comment by nija-at** [comment]
Calling `addPermission()` with the same `scope` and `id` but with different parameters **must** throw an error. Silently succeeding is the wrong customer experience because it gives the sense that the permission grant worked but actually it didn't.

Either the check/cache needs to go higher up the stack, or the comparison needs to be deeper. 
Going down the deep comparison route, keep in mind that the logic should take into account that the `Permission` struct, in the future, can expand to include more properties that may or may not have to be included in the deep comparison.

**Review by njlynch — COMMENTED** [review]
I moved the logic up one layer and used memoization to be able to retrieve the previous `Grant`. I believe this satisfies both sets of feedback.

**Review by eladb — APPROVED** [review]
