### PR TITLE
fix(core): removalpolicy correct default

### LINKED ISSUE #4416: core.RemovalPolicy indicates wrong default
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.RemovalPolicy.html

The documentation indicates that `DESTROY` is the "default removal policy", though the source code seems to indicate that `RETAIN` is the default. 
I assume the code is more correct and thus the documentation is wrong.

---

This is a 📕 documentation issue

### PR DESCRIPTION
**Pull request by NGL321**
Fixes #4416

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/core/lib/removal-policy.ts [hunk 1]
```diff
@@ -16,7 +16,8 @@ export interface RemovalPolicyOptions {
   /**
    * The default policy to apply in case the removal policy is not defined.
    *
-   * @default RemovalPolicy.Retain
+   * The default value is resource specific. To determine the default value for a resoure,
```
Comment (rix0rrr) [inline packages/@aws-cdk/core/lib/removal-policy.ts]: Would prefer you kept this under the `@default - ` tag . Go `@default - Default value is resource specific ... `
