### PR TITLE
fix(cfn-diff): handle Fn::If inside policies and statements

### LINKED ISSUE #12887: (cloudformation_include): Usage of `Fn::If` breaks diff
When including a cloud formation stack that uses `Fn::If` in certain places, cdk diff fails with an exception. I have attached a small example derived from a real world use-case that triggers two of these exceptions. In both cases it affects the creation of an IAM role:

1. The handling of the `ManagedPolicyArns` property assumes that a `string[]` is passed, but in the case of an `Fn::If` a string is passed. (see @aws-cdk/cloudformation-diff/lib/iam/managed-policy.ts)
2. In the case of the `Policies` property an array of policy definitions is assumed. However, if one of these definitions is included conditionally, this assumption breaks. (see @aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts: `readIdentityPolicies`)

### Reproduction Steps

Run `cdk diff` on the following application (Note, that the observed behavior is for a stack that has not yet been deployed either manually or via `cdk deploy`):

CloudFormation template (save as `reproduction.json`):
```json
{
	"Conditions": {
		"HasPolicyArns": {
			"Fn::Equals": [
				"True",
				"True"
			]
		},
		"HasVpc": {
			"Fn::Equals": [
				"True",
				"True"
			]
		}
	},
	"Resources": {
		"TestRole": {
			"Type": "AWS::IAM::Role",
			"Properties": {
				"AssumeRolePolicyDocument": {
					"Version": "2012-10-17",
					"Statement": {
						"Effect": "Allow",
						"Principal": {
							"Service": "codebuild.amazonaws.com"
						},
						"Action": "sts:AssumeRole"
					}
				},
				"ManagedPolicyArns": {
					"Fn::If": [
						"HasPolicyArns",
						[],
						[
							"arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
						]
					]
				},
				"Policies": [
					{
						"Fn::If": [
							"HasVpc",
							{
								"PolicyName": "VPC",
								"PolicyDocument": {
									"Version": "2012-10-17",
									"Statement": [
										{
											"Effect": "Allow",
											"Action": "s3:GetObject",
											"Resource": "*"
										}
									]
								}
							},
							{
								"Ref": "AWS::NoValue"
							}
						]
					}
				]
			}
		}
	}
}
```

CDK App:
```python
#!/usr/bin/env python3

from aws_cdk import cloudformation_include as cfn, core

app = core.App()

class Reproduction(core.Stack):
    def __init__(self, scope: core.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        cfn.CfnInclude(
            self,
            construct_id,
            template_file="reproduction.json",
        )

dummy = Reproduction(app, "reproduction")

app.synth()
```

### What did you expect to happen?

A diff of the Cfn template is successfully being rendered.

### What actually happened?

Executing `cdk diff` on the following app fails with the exception:

```
arns.map is not a function
TypeError: arns.map is not a function
    at Object.parseManagedPolicies (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/iam/managed-policy.ts:21:15)
    at IamChanges.readManagedPolicies (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts:242:4)
    at IamChanges.readPropertyChange (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts:154:45)
    at new IamChanges (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts:36:12)
    at new TemplateDiff (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/diff/types.ts:52:23)
    at calculateTemplateDiff (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:110:10)
    at Object.diffTemplate (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:43:19)
    at Object.printStackDiff (/usr/local/lib/node_modules/aws-cdk/lib/diff.ts:24:24)
    at CdkToolkit.diff (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:103:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

When setting `ManagedPolicyArns` to `[]`, `cdk diff` fails with

```
Cannot read property 'Statement' of undefined
TypeError: Cannot read property 'Statement' of undefined
    at /usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts:188:8
    at Object.flatMap (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/util.ts:46:17)
    at IamChanges.readIdentityPolicies (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts:186:12)
    at IamChanges.readPropertyChange (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts:144:40)
    at new IamChanges (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts:36:12)
    at new TemplateDiff (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/diff/types.ts:52:23)
    at calculateTemplateDiff (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:110:10)
    at Object.diffTemplate (/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:43:19)
    at Object.printStackDiff (/usr/local/lib/node_modules/aws-cdk/lib/diff.ts:24:24)
    at CdkToolkit.diff (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:103:18)
```

### Environment

  - **CDK CLI Version  :** 1.88
  - **Framework Version:** 1.88
  - **Node.js Version:** v14.15.4
  - **OS               : Fedora 33**
  - **Language (Version):** Python 3.9.1

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by skinny85**
cloudformation-diff assumes the policies and statements it encounters are simple JSON objects.
However, in reality, everywhere that simple object can be used,
the Fn::If function can be used as well.
Add code that handles that eventuality.

Fixes #12887

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/cloudformation-diff/lib/iam/statement.ts [hunk 1]
```diff
@@ -32,36 +32,52 @@ export class Statement {
...
-    this.sid = expectString(statement.Sid);
-    this.effect = expectEffect(statement.Effect);
-    this.resources = new Targets(statement, 'Resource', 'NotResource');
-    this.actions = new Targets(statement, 'Action', 'NotAction');
-    this.principals = new Targets(statement, 'Principal', 'NotPrincipal');
-    this.condition = statement.Condition;
+  private readonly serializedIntrinsic: string | undefined;
+
+  constructor(statement: UnknownMap | string) {
+    if (typeof statement === 'string') {
```
Comment (rix0rrr) [inline packages/@aws-cdk/cloudformation-diff/lib/iam/statement.ts:38]: I don't get what this object is invoked with if it's not an object.

A JSON-ified object? But that's not a change, was that already there? Because that seems very silly.

**Review by rix0rrr — APPROVED** [review]

**Comment by skinny85** [comment]
@rix0rrr I know you already approved this one (thanks!), but do you mind taking another look? As it turns out, the `toJson()` method that we talked about was a red herring - it's only used in tests, and there's a different method in `IamChanges` (`summarizeManagedPolicies()`) that's responsible for rendering the actual diff.

I did a refactoring to be able to control how the rendering of a `Statement` happens - let me know what you think about it!

File: packages/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts [hunk 2]
```diff
@@ -71,21 +71,13 @@ export class IamChanges {
     for (const statement of this.statements.additions) {
       ret.push([
         '+',
-        renderTargets(statement.resources),
-        statement.effect,
-        renderTargets(statement.actions),
-        renderTargets(statement.principals),
-        renderCondition(statement.condition),
+        ...statement.render(),
```
Comment (rix0rrr) [inline packages/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts:74]: I mean... yeah... but the concern about the table and what columns there were in what order USED to be in `summarizeStatements()` and now it's split across `summarizeStatements()` and `statement.render()`.

`statement.render()` should return an object and `summarizeStatements()` should pick fields out of that object in the right order.

**Review by rix0rrr — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts (hunk 2 above)
Comment (skinny85) [reply packages/@aws-cdk/cloudformation-diff/lib/iam/iam-changes.ts:74]: Done!

**Comment by skinny85** [comment]
@rix0rrr included your latest comments, please re-review when you have a chance!

**Review by rix0rrr — APPROVED** [review]
