### PR TITLE
fix(ecr-assets): docker images are not built if .dockerignore includes an entry that ignores the dockerfile.

### LINKED ISSUE #6004: Docker image assets do not copy the Dockerfile if Dockerfile is included in the .dockerignore file
According to the Docker spec you can include the `Dockerfile` in your `.dockerignore` file: 

> You can even use the .dockerignore file to exclude the Dockerfile and .dockerignore files. These files are still sent to the daemon because it needs them to do its job. But the ADD and COPY instructions do not copy them to the image.

https://docs.docker.com/engine/reference/builder/

However if you follow this pattern with AWS CDK the asset fails to build with an error about being unable to find the Dockerfile. When inspected the contents of the asset folder the Dockerfile is indeed missing.

It appears that AWS CDK is attempting to produce smaller assets by respecting the `.dockerignore` file and not copying those assets into the assets folder, however, it does not follow the special case for the `Dockerfile`

### Reproduction Steps

Create a project with a `Dockerfile` and a `.dockerignore` file that ignores the Dockerfile to avoid adding the dockerfile to the built image.
example `.dockerignore`:

```
.git
*Dockerfile*
*docker-compose*
node_modules
```

Then attempt to build the asset using AWS CDK:

```js
ecs.ContainerImage.fromAsset('./path/to/folder'),
```

### Error Log

```
chatter-message: deploying...
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Users/peckn/Documents/Code/demo/cdk.out/asset.ae8c5499264f2f5958258b94afa7493583862df2a023e45404c6cb5a01e84917/Dockerfile: no such file or directory

 ❌  chatter-message failed: Error: docker build --tag 209640446841.dkr.ecr.us-east-1.amazonaws.com/aws-cdk/assets:ae8c5499264f2f5958258b94afa7493583862df2a023e45404c6cb5a01e84917 cdk.out/asset.ae8c5499264f2f5958258b94afa7493583862df2a023e45404c6cb5a01e84917 exited with error code 1
    at ChildProcess.<anonymous> (/Users/peckn/Documents/Code/demo/node_modules/aws-cdk/lib/os.ts:39:16)
    at Object.onceWrapper (events.js:428:26)
    at ChildProcess.emit (events.js:321:20)
    at ChildProcess.EventEmitter.emit (domain.js:485:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
docker build --tag 209640446841.dkr.ecr.us-east-1.amazonaws.com/aws-cdk/assets:ae8c5499264f2f5958258b94afa7493583862df2a023e45404c6cb5a01e84917 cdk.out/asset.ae8c5499264f2f5958258b94afa7493583862df2a023e45404c6cb5a01e84917 exited with error code 1
```

### Environment

  - **CLI Version      : 1.22.0**
  - **Framework Version:  1.22.0**
  - **Language         : typescript**

### Other

We should add a special case for the "Dockerfile" and ".dockerignore" file so that it always gets copied into the asset folder, even if it is included in the `.dockerignore` folder

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by nathanpeck**
This fixes #6004 by ensuring that `Dockerfile` and `.dockerignore` will always be added to the asset staging folder, even if included in the .dockerignore file. This obeys the spec according to Docker:

> You can even use the .dockerignore file to exclude the Dockerfile and .dockerignore files. These files are still sent to the daemon because it needs them to do its job. But the ADD and COPY instructions do not copy them to the image.

(https://docs.docker.com/engine/reference/builder/)

Note: this PR adds new dependency `minimatch` to the `@aws-cdk/aws-ecr-asset` package, in order to do file glob matching. However this package is also used in `@aws-cdk/assets` so this is not a new dependency for the overall project

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts [hunk 1]
```diff
@@ -95,6 +96,17 @@ export class DockerImageAsset extends Construct implements assets.IAsset {
...
     }
 
+    // .dockerignore files allow you to ignore the Dockerfile and .dockerignore file
+    // so that these files do not get sent to the Daemon during COPY or ADD. The
+    // files are still utilized by the Docker daemon, even if they are ignored
+    // We need to copy these files into the asset folder, even if they
+    // are included in the .dockerignore, so that these files can be used during the
+    // docker build, so remove any excludes that would match these two essential files
+    exclude = exclude.filter(ignoreExpression => {
+      return !(minimatch('Dockerfile', ignoreExpression, { dot: true }) ||
```
Comment (eladb) [inline packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts]: What if users specify a custom name for the docker file. Also, why do we need minimatch here? Let’s just always copy the dockerfile to the staging area instead of patching up the exclude list

Comment (nathanpeck) [reply packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts]: Yes good catch, I will follow up with a feature to always add the custom name for the docker file.

For your second suggestion it looks like the copy to the staging area is happening here: https://github.com/aws/aws-cdk/blob/a50fd94aacc1c97e3e9e1e6405967d4795003bf1/packages/%40aws-cdk/aws-ecr-assets/lib/image-asset.ts#L127-L134

But I'm not seeing any method on the [`assets.Staging()` constructor](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_assets.Staging.html), or any method on the `Staging` class for copying a specific file into the staging area? It looks like my only options are to supply a single source folder path, and then a list of file globs to exclude, hence my approach was to filter out excluding file globs that would cause the required files to be excluded. I figured that would be the most minimal way to ensure that a required file doesn't get excluded.

What would be your recommended approach for ensuring that it a required file always makes it into the staging area? Should I extend the `assets.Staging()` with a new property which is a list of `includes`?

Maybe something like:

1. Copy the source path but excluding the files matching `excludes`
2. Copy the source path again but this time copy only files matching `includes`

Comment (nathanpeck) [reply packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts]: Alternative I could try to add a new method that works like this:

```
const staging = new assets.Staging(this, 'Staging', { 
   ...props, 
   exclude, 
   sourcePath: dir, 
   extraHash: Object.keys(extraHash).length === 0 
     ? undefined 
     : JSON.stringify(extraHash) 
 }); 

staging.addFiles(sourcePath, fileGlob);
```

However this appears like it would require a fairly significant change to the Staging class, to make it keep track of a list of sourcePaths and patterns, and then in the [synthesize method](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/assets/lib/staging.ts#L69-L91) loop through the list copying each into the asset folder.

Comment (iliapolo) [reply packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts]: At first glance I was also leaning towards what @eladb suggested. 

But @nathanpeck is right, there is no straightforward way of explicitly adding files to the staging area, since the copy only happens during `synthesize`. And it seems that every attempt to enable this only makes the flow less clear. Im good with filtering the `excludes` list.

Regarding the custom docker file, yeah, this needs a fix. You can just use the already defined `file` const. 

Also - the fact the CI passed with this bug means we are missing a test. Could you add a test that uses a custom docker file in the ignore file?

File: packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts [hunk 2]
```diff
@@ -95,6 +96,17 @@ export class DockerImageAsset extends Construct implements assets.IAsset {
...
+             minimatch('.dockerignore', ignoreExpression, { dot: true }));
```
Comment (iliapolo) [inline packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts]: You can just use the already defined `ignore` const.

File: packages/@aws-cdk/aws-ecr-assets/package.json [hunk 3]
```diff
@@ -96,10 +97,13 @@
   "engines": {
     "node": ">= 10.3.0"
   },
+  "bundledDependencies": [
```
Comment (iliapolo) [inline packages/@aws-cdk/aws-ecr-assets/package.json]: Wondering if this is necessary. I do see we bundle `minimatch` in other place though i'm not sure why. Do you have some context of this?

Comment (nathanpeck) [reply packages/@aws-cdk/aws-ecr-assets/package.json]: I tried without but it would not pass linter rules. The linter required that I add it to the module's package.json and then it also required that I add it as a hoisted package. I assume this is because someone might possible pull in the `aws-ecr-asset` module without the rest of the project?

File: packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts (hunk 2 above)
Comment (nathanpeck) [reply packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts]: Updated!

File: packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts [hunk 4]
```diff
@@ -95,6 +96,17 @@ export class DockerImageAsset extends Construct implements assets.IAsset {
       exclude = [...exclude, ...fs.readFileSync(ignore).toString().split('\n').filter(e => !!e)];
     }
 
+    // .dockerignore files allow you to ignore the Dockerfile and .dockerignore file
+    // so that these files do not get sent to the Daemon during COPY or ADD. The
+    // files are still utilized by the Docker daemon, even if they are ignored
+    // We need to copy these files into the asset folder, even if they
+    // are included in the .dockerignore, so that these files can be used during the
+    // docker build, so remove any excludes that would match these two essential files
```
[the remark this answers is not in the document]
Comment (nathanpeck) [reply packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts]: Updated

**Comment by nathanpeck** [comment]
PR is now updated with support for custom Dockerfile names. Per @iliapolo feedback I have retained the approach of filtering the list of excludes, reduced the explanatory comment verbosity, and reused some existing constants.

Tests were actually already existing on this package, but the tested sample was just missing the right conditions to trigger this bug. I added relevant lines to the `.dockerignore` files for the existing tests in order to trigger the right conditions for the bug to manifest, verified that the tests broke as expected, added new code to fix the bug, and then verified that the tests went back to passing.

If wanted I can still break this out into its own entirely new separate test case for clarity, but I figured for the sake of conciseness it made sense to just use the existing test cases. It appears those test cases are already being overloaded to do multiple different types of tests for correctness, so it didn't look like this project has a strict 1 to 1 policy for test condition to test case

File: packages/@aws-cdk/aws-ecr-assets/test/dockerignore-image/.dockerignore [hunk 5]
```diff
@@ -1 +1,3 @@
 foobar.txt
+Dockerfile
```
Comment (nathanpeck) [inline packages/@aws-cdk/aws-ecr-assets/test/dockerignore-image/.dockerignore]: For reference these added lines are what cause the existing tests to also validate the correctness of this bug fix

File: packages/@aws-cdk/aws-ecr-assets/package.json (hunk 3 above)
Comment (iliapolo) [reply packages/@aws-cdk/aws-ecr-assets/package.json]: Hmm, I don't have knowledge/context on this. But if the linters require it, its probably for a good reason. All hail the linters 👍

File: packages/@aws-cdk/aws-ecr-assets/test/dockerignore-image/.dockerignore (hunk 5 above)
Comment (iliapolo) [reply packages/@aws-cdk/aws-ecr-assets/test/dockerignore-image/.dockerignore]: Yeah this great, but it didn't cover the custom docker file scenario. I saw you did add a `.dockerignore` for the custom test case as well, which is great 💯

**Comment by iliapolo** [comment]
@nathanpeck Looks great. Just a small phrasing issue...

We want the PR title to describe the bug itself, and not the solution. That is: 

docker images are not built if `.dockerignore` includes an entry that ignores the docker file.

For example: https://github.com/aws/aws-cdk/pull/5507

This is because this title is then shown in the release notes, and it helps customers clearly 
understand what was fixed. 

Sorry for not mentioning this before, it just dawned on me.
