### PR TITLE
fix(rds): subnet selection not respected for multi user secret rotation

### LINKED ISSUE #19233: aws-rds: Subnet selection doesn't work for cluster.addRotationMultiUser
### What is the problem?

There's a bug in VPC selection for addRotationMultiUser. Commented on original issue as well: https://github.com/aws/aws-cdk/issues/17265

Even if you pass in props for the subnet type to place the rotation lambda, it will always get placed in the same subnets as the cluster. See https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-rds/lib/cluster.ts line 611 for the addRotationMultiUser function. Notice how the '...options' line gets overridden by the cluster subnets.

The addRotationSingleUser function doesn't have this problem because the options are injected after the defaults. See the same file as above.

Not sure if there's another section of aws-rds that has an addRotationMultiUser function but worth checking the other rotation functions for the same bug.

I won't have time to work on a PR for a few months so someone else can feel free to pick this up. Just want to make sure the bug gets tracked.

### Reproduction Steps

Create a vpc with private and isolated subnets and place an Aurora cluster in the isolated subnets. Then set up a multi user rotation:

```
    this.secret = new rds.DatabaseSecret(this, 'Secret', {
      username: username,
      masterSecret: cluster.secret
    }).attach(cluster);

    cluster.addRotationMultiUser('Rotation', {
      secret: this.secret,
      automaticallyAfter: Duration.days(90),
      vpcSubnets: {
        subnetType: ec2.SubnetType.PRIVATE_WITH_NAT
      }
    });
```

### What did you expect to happen?

Rotation lambda created in private subnet and able to talk to secrets manager through the internet.

### What actually happened?

Rotation lambda created in isolated subnet (same subnet as cluster) and times out because it can't talk to the internet.

### CDK CLI Version

2.12.0 (build c9786db)

### Framework Version

_No response_

### Node.js Version

v16.14.0

### OS

macOS Monterey v12.1

### Language

Typescript

### Language Version

TypeScript Version 4.5.5

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jogold**
The subnet selection was always overriden by the subnet selection of the
instance/cluster.

Avoid these kinds of errors by explicitely defining rotation options and
their defaults.

Closes #19233

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-rds/lib/serverless-cluster.ts [hunk 1]
```diff
@@ -580,14 +586,21 @@ export class ServerlessCluster extends ServerlessClusterNew {
...
-    return new secretsmanager.SecretRotation(this, id, {
-      ...options,
+    // Rotation options with defaults
+    const rotationOptions: Complete<RotationMultiUserOptions> = {
+      automaticallyAfter: options.automaticallyAfter,
+      endpoint: options.endpoint,
       excludeCharacters: options.excludeCharacters ?? DEFAULT_PASSWORD_EXCLUDE_CHARS,
+      secret: options.secret,
+      vpcSubnets: options.vpcSubnets ?? this.vpcSubnets,
+    };
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/serverless-cluster.ts:596]: This block is repeated 6 times (yes, I know `secret` is not always there 😛). Can we get rid of this duplication?

File: packages/@aws-cdk/aws-rds/test/cluster.test.ts [hunk 2]
```diff
@@ -954,6 +954,76 @@ describe('cluster', () => {
     });
   });
 
+  test('addRotationMultiUser() with options', () => {
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/test/cluster.test.ts:957]: Can we write a better description of what this test is checking?

File: packages/@aws-cdk/aws-rds/test/cluster.test.ts [hunk 3]
```diff
@@ -954,6 +954,76 @@ describe('cluster', () => {
...
+          'Fn::GetAtt': [
+            'DatabaseuserSecurityGroupFB2AA194',
+            'GroupId',
+          ],
+        },
+        excludeCharacters: '°_@',
+        masterSecretArn: {
+          Ref: 'DatabaseSecretAttachmentE5D1B020',
+        },
+      },
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/test/cluster.test.ts:1023]: I have to say - I don't understand this assertion...

1. Do we need _all_ of these properties here? Are we not worried only about the `vpcSubnetIds`?
2.
    ``` 
          'Fn::Join': ['', [
            { Ref: 'VpcprivateSubnet1SubnetCEAD3716' },
            ',',
            { Ref: 'VpcprivateSubnet2Subnet2DE7549C' },
          ]],
    ```

    Is there a clearer way we can formulate this assertion? Maybe imported subnets? It is not clear to me that these are the `PRIVATE_WITH_NAT` that we provided when creating the rotation.

File: packages/@aws-cdk/aws-rds/test/instance.test.ts [hunk 4]
```diff
@@ -858,6 +858,71 @@ describe('instance', () => {
...
+            'GroupId',
+          ],
+        },
+        excludeCharacters: '°_@',
+        masterSecretArn: {
+          Ref: 'DatabaseSecretAttachmentE5D1B020',
+        },
+      },
+    });
+  });
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/test/instance.test.ts:925]: Same comment here as for the test above.

**Review by skinny85 — DISMISSED** [review]
Thank for the fix @jogold! A few minor comments.

File: packages/@aws-cdk/aws-rds/test/cluster.test.ts (hunk 2 above)
Comment (jogold) [reply packages/@aws-cdk/aws-rds/test/cluster.test.ts:957]: We are testing here that those rotation options are correctly passed: `automaticallyAfter`, `excludeCharacters` and `vpcSubnets`.

Same as here:
https://github.com/aws/aws-cdk/blob/e0f863a4c56041860e14c75b9aa5a6d35860fae6/packages/%40aws-cdk/aws-rds/test/instance.test.ts#L800

File: packages/@aws-cdk/aws-rds/test/cluster.test.ts (hunk 3 above)
Comment (jogold) [reply packages/@aws-cdk/aws-rds/test/cluster.test.ts:1023]: > 1. Do we need all of these properties here? Are we not worried only about the vpcSubnetIds?

We can remove `functionName` and `vpcSecurityGroupIds`. We need the other ones because we are checking that options are correctly passed (and `endpoint` is also an option).

Comment (jogold) [reply packages/@aws-cdk/aws-rds/test/cluster.test.ts:1011]: > 2. Is there a clearer way we can formulate this assertion?

See the propostion with `stack.resolve()`. Do we want to update the same test for single user rotation?

File: packages/@aws-cdk/aws-rds/test/cluster.test.ts (hunk 2 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-rds/test/cluster.test.ts:957]: OK, can we write something like that? 🙂

File: packages/@aws-cdk/aws-rds/test/cluster.test.ts (hunk 3 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-rds/test/cluster.test.ts:1011]: Instead of weird `resolve()` tricks, can't we do this?

```ts
      // GIVEN
      vpc = ec2.Vpc.fromVpcAttributes(stack, 'Vpc', {
        vpcId: 'vpc-id',
        availabilityZones: ['az1'],
        publicSubnetIds: ['public-subnet-id-1', 'public-subnet-id-2'],
        publicSubnetNames: ['public-subnet-name-1', 'public-subnet-name-2'],
        privateSubnetIds: ['private-subnet-id-1', 'private-subnet-id-2'],
        privateSubnetNames: ['private-subnet-name-1', 'private-subnet-name-2'],
        isolatedSubnetIds: ['isolated-subnet-id-1', 'isolated-subnet-id-2'],
        isolatedSubnetNames: ['isolated-subnet-name-1', 'isolated-subnet-name-2'],
      });
    });
    const instance = new rds.DatabaseInstance(stack, 'Instance', {
      engine: rds.DatabaseInstanceEngine.MYSQL,
      vpc: vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PUBLIC },
    });

    // WHEN
    instance.addRotationMultiUser('user', {
      secret: new rds.DatabaseSecret(stack, 'DatabaseSecret', {
        username: 'user',
      }),
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_NAT },
    });

    // THEN
    Template.fromStack(stack).hasResourceProperties('AWS::Serverless::Application', {
      Parameters: {
        vpcSubnetIds: 'private-subnet-id-1,private-subnet-id-2',
      },
    });
```
?

**Review by skinny85 — DISMISSED** [review]
Almost there! 🙂

File: packages/@aws-cdk/aws-rds/lib/props.ts [hunk 5]
```diff
@@ -456,7 +456,7 @@ export abstract class SnapshotCredentials {
 /**
  * Properties common to single-user and multi-user rotation options.
  */
-interface CommonRotationUserOptions {
+export interface CommonRotationUserOptions {
```
[the remark this answers is not in the document]
Comment (jogold) [reply packages/@aws-cdk/aws-rds/lib/props.ts:459]: Unfortunately not possible to have a public interface that extends an interface from a non exported file with `jsii`...


```
error JSII9002: Unable to resolve type "@aws-cdk/aws-rds.CommonRotationUserOptions". It may be @internal or not exported from the module's entry point (as configured in "package.json" as "main").
```

File: packages/@aws-cdk/aws-rds/lib/private/util.ts [hunk 6]
```diff
@@ -134,3 +135,14 @@ export function helperRemovalPolicy(basePolicy?: RemovalPolicy): RemovalPolicy {
 export function renderUnless<A>(value: A, suppressValue: A): A | undefined {
   return value === suppressValue ? undefined : value;
 }
+
+/**
+ * Applies defaults for rotation options
+ */
+export function applyDefaultRotationOptions(options: CommonRotationUserOptions, defaultvpcSubnets?: ec2.SubnetSelection): CommonRotationUserOptions {
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/private/util.ts:142]: So much simpler, love it!

File: packages/@aws-cdk/aws-rds/lib/props.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (skinny85) [reply packages/@aws-cdk/aws-rds/lib/props.ts:459]: That's weird, because this interface used to be not exported, but JSII is gonna JSII...😉. Let's leave it as-is.

File: packages/@aws-cdk/aws-rds/test/cluster.test.ts (hunk 3 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-rds/test/cluster.test.ts:1000]: Love it!

**Review by skinny85 — APPROVED** [review]
Love it, thanks @jogold!

File: packages/@aws-cdk/aws-rds/test/instance.test.ts [hunk 7]
```diff
@@ -839,26 +842,69 @@ describe('instance', () => {
...
+    // THEN
+    Template.fromStack(stack).hasResourceProperties('AWS::SecretsManager::RotationSchedule', {
+      RotationRules: {
+        AutomaticallyAfterDays: 15,
+      },
+    });
+
+    vpcWithIsolated.selectSubnets({
+      subnetType: ec2.SubnetType.PRIVATE_WITH_NAT,
+    }).subnetIds;
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/test/instance.test.ts:890]: I think we can kill this safely:

```suggestion
```
