### PR TITLE
fix(stepfunctions-tasks): Athena* APIs have incorrect supported integration patterns

### LINKED ISSUE #11246: aws-stepfunctions-tasks: Athena missing .sync option
Just recently, support was added for AWS Athena to Step Functions, and subsequently support was also added to AWS CDK for that. In Step Functions, `StartQueryExecution` (and only that) supports also executing the query as a job and not request/response. However, in CDK, this does not seem to be the case:

https://github.com/aws/aws-cdk/blob/v1.71.0/packages/@aws-cdk/aws-stepfunctions-tasks/lib/athena/start-query-execution.ts#L55-L58

Documentation on Step Functions Athena:

https://docs.aws.amazon.com/step-functions/latest/dg/connect-athena.html

### Reproduction Steps

```typescript
new sfn_tasks.AthenaStartQueryExecution(this, 'step', {
  integrationPattern: sfn.IntegrationPattern.RUN_JOB,
  queryString: `SELECT 1;`
});
```

### What did you expect to happen?

The call to succeed, running as job.

### What actually happened?

Error being thrown due to `validatePatternSupported`.

### Environment

  - **CLI Version      :**
  - **Framework Version:** 1.71.0
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

Sorry, did not actually test this live - just read the code, and it seems obvious.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by akiym**
The changes made by #11045 seem to support `WAIT_FOR_TASK_TOKEN (.waitForTaskToken)` but according to the documentation, only `Request Response` and `Run a job (.sync)` are supported: https://docs.aws.amazon.com/step-functions/latest/dg/connect-athena.html

closes #11246

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-stepfunctions-tasks/lib/athena/start-query-execution.ts [hunk 1]
```diff
@@ -87,7 +87,7 @@ export class AthenaStartQueryExecution extends sfn.TaskStateBase {
           }),
 
         ],
-        actions: ['athena:getDataCatalog', 'athena:startQueryExecution'],
+        actions: ['athena:getDataCatalog', 'athena:startQueryExecution', 'athena:getQueryExecution'],
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-stepfunctions-tasks/lib/athena/start-query-execution.ts:90]: can you add the rationale for this addition into the commit body. I didn't see it in there

**Review by shivlaks — DISMISSED** [review]
@akiym thanks for submitting the fix!! amazing given we haven't released this yet :)
had one minor comment to update commit body, but otherwise looks good

File: packages/@aws-cdk/aws-stepfunctions-tasks/lib/athena/start-query-execution.ts (hunk 1 above)
Comment (akiym) [reply packages/@aws-cdk/aws-stepfunctions-tasks/lib/athena/start-query-execution.ts:90]: added a link of this documentation: https://docs.aws.amazon.com/step-functions/latest/dg/athena-iam.html

**Review by shivlaks — APPROVED** [review]
