### PR TITLE
fix(ecs): Can't enable both Fargate and ASG capacity providers on ECS Cluster

### LINKED ISSUE #14730: (aws-ecs): Can't enable both Fargate and ASG capacity providers
According to [the ECS Cluster Capacity Providers docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cluster-capacity-providers.html) it should be possible to have both Fargate and ASG powered capacity providers associated with a ECS cluster.

> _**A cluster may contain a mix of both Auto Scaling group capacity providers and Fargate capacity providers**, however a capacity provider strategy may only contain one or the other but not both._

This seem to not be the case with CDK. Cloudformation fails with a "The cluster already contains capacity provider associations" message when trying to provision a cluster that have both `enableFargateCapacityProviders` set to `true` and an ASG provided through `addAsgCapacityProvider(...)`.

### Reproduction Steps

```ts
const cluster = new Cluster(this, 'EcsCluster', {
  vpc,
  clusterName: props.clusterName,
  enableFargateCapacityProviders: true,
});

const autoScalingGroup = new AutoScalingGroup(this, 'Asg', {
  vpc,
  machineImage: EcsOptimizedImage.amazonLinux2(),
  instanceType: new InstanceType('t3.micro'),
  minCapacity: 1,
  maxCapacity: 100,
});

const capacityProvider = new AsgCapacityProvider(
  this,
  'AsgCapacityProvider',
  {
    autoScalingGroup,
    capacityProviderName: props.clusterName,
  },
);
cluster.addAsgCapacityProvider(capacityProvider);
```

### What did you expect to happen?

The CF stack to finish successfully and for the cluster to be associated with both Fargate and ASG capacity providers, thus allowing for a service to decide if it should run on EC2 or Fargate, in the same ECS cluster.

### What actually happened?

```
Resource handler returned message: "The cluster already contains capacity provider associations" (RequestToken: 5c5f5982-c7d4-37ae-535a-92833ee7bef6, HandlerErrorCode: AlreadyExists)
```

### Environment

  - **CDK CLI Version:** 1.104.0
  - **Framework Version:** 1.104.0
  - **Node.js Version:** 14.16.1
  - **OS:** MacOS 10.15.7
  - **Language (Version):** Typescript 4.2.4

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by SoManyHs**
Previously, adding/enabling Fargate capacity providers would add the FARGATE and FARGATE_SPOT capacity providers a part of the [capacityProviders field](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-cluster.html#cfn-ecs-cluster-capacityproviders) on the ECS::Cluster resource. However, ASG Capacity Providers can only be specified as part of the [capacityProviders field on the ECS::ClusterCapacityProviderAssociation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-clustercapacityproviderassociations.html#cfn-ecs-clustercapacityproviderassociations-capacityproviders)
resource, due to circular dependency issues.

However, when a cluster is created, any capacity providers regardless of type must all be specified *either* on the cluster *or* as a ClusterCapacityProviderAssociation.  Therefore, in order to support both types on the same cluster, Fargate capacity providers must also be specified as a ClusterCapacityProviderAssociation.

This change removes the Fargate capacity providers from the Cluster resource and adds them as a ClusterCapacityProviderAssociation.

Fixes #14730.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-ecs/lib/cluster.ts [hunk 1]
```diff
@@ -216,16 +210,16 @@ export class Cluster extends Resource implements ICluster {
     // since it's harmless, but we'd prefer not to add unexpected new
     // resources to the stack which could surprise users working with
     // brown-field CDK apps and stacks.
-    Aspects.of(this).add(new MaybeCreateCapacityProviderAssociations(this, id, this._asgCapacityProviders));
+    Aspects.of(this).add(new MaybeCreateCapacityProviderAssociations(this, id, this._capacityProviderNames));
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-ecs/lib/cluster.ts:213]: Passing `id` onward here is a bit dangerous. Ideally you'd want to give this its own identifier.

Although that might be impossible to change now for backwards compatibility reasons, as changing the `id` now will cause resources to be replaced for people who already deployed the previous version.

File: packages/@aws-cdk/aws-ecs/lib/cluster.ts [hunk 2]
```diff
@@ -1340,22 +1334,24 @@ export class AsgCapacityProvider extends CoreConstruct {
 class MaybeCreateCapacityProviderAssociations implements IAspect {
   private scope: CoreConstruct;
   private id: string;
-  private capacityProviders: AsgCapacityProvider[]
+  private capacityProviders: string[]
+  private resource?: CfnClusterCapacityProviderAssociations
 
-  constructor(scope: CoreConstruct, id: string, capacityProviders: AsgCapacityProvider[]) {
+  constructor(scope: CoreConstruct, id: string, capacityProviders: string[] ) {
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-ecs/lib/cluster.ts:1340]:
```suggestion
  constructor(scope: Construct, id: string, capacityProviders: string[] ) {
```

File: packages/@aws-cdk/aws-ecs/lib/cluster.ts [hunk 3]
```diff
@@ -1340,22 +1334,24 @@ export class AsgCapacityProvider extends CoreConstruct {
...
     this.scope = scope;
     this.id = id;
     this.capacityProviders = capacityProviders;
   }
+
   public visit(node: IConstruct): void {
     if (node instanceof Cluster) {
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-ecs/lib/cluster.ts:1347]: By the way this is instantiated, you *know* that `this.scope` is the `Cluster` you're looking for. You could do something like `if (node === this.scope)`.

File: packages/@aws-cdk/aws-ecs/lib/cluster.ts (hunk 1 above)
Comment (SoManyHs) [reply packages/@aws-cdk/aws-ecs/lib/cluster.ts:213]: Yes, I had thought about changing this to something more unique to the CPAssociation so it's less confusing but thought that would be breaking, and also was running into the strange issue of this singleton class being created twice for some reason. I guess we'll leave it as is?

File: packages/@aws-cdk/aws-ecs/lib/cluster.ts (hunk 3 above)
Comment (SoManyHs) [reply packages/@aws-cdk/aws-ecs/lib/cluster.ts:1347]: true. for whatever reason though, changing the condition to your suggestion causes a different complaint (clusterName not being on node, in line 1350).  will keep it as is since it works for now.

File: packages/@aws-cdk/aws-ecs/test/cluster.test.ts [hunk 4]
```diff
@@ -1779,7 +1795,11 @@ nodeunitShim({
     cluster.addCapacityProvider('FARGATE'); // does not add twice
 
     // THEN
-    expect(stack).to(haveResource('AWS::ECS::Cluster', {
+    // expect(stack).to(haveResource('AWS::ECS::Cluster', {
+    //   CapacityProviders: ABSENT,
+    // }));
```
Comment (madeline-k) [inline packages/@aws-cdk/aws-ecs/test/cluster.test.ts:1800]: Can this commented out code be removed?

**Review by madeline-k — APPROVED** [review]

**Comment by dadoeyad** [comment]
I see that this fix has been released in v2.0.0-rc.8
Will it be released in a stable v1 version too?

**Comment by flavioleggio** [comment]
I need it in v1 too. Any chance to fix it?
