### PR TITLE
fix(autoscaling): StepScalingPolicy intervals not checked for going over allowable maximum

### LINKED ISSUE #26215: (aws-autoscaling/aws-applicationautoscaling): StepScalingPolicy supports at most 40 steps
### Describe the bug

If you create a StepScalingPolicy with more than 40 steps, the Cloudformation deployment fails with the message "There can be at most 20 step adjustments per scaling policy".

The reason the limit is 40 and not 20 is because StepScalingPolicy creates two policies, an [UpperPolicy](https://github.com/aws/aws-cdk/blob/bc029fe5ac69a8b7fd2dfdbcd8834e9a2cf8e000/packages/aws-cdk-lib/aws-autoscaling/lib/step-scaling-policy.ts#L136-L166) and a [LowerPolicy](https://github.com/aws/aws-cdk/blob/bc029fe5ac69a8b7fd2dfdbcd8834e9a2cf8e000/packages/aws-cdk-lib/aws-autoscaling/lib/step-scaling-policy.ts#L105-L134), each containing half the steps.

### Expected Behavior

The deployment succeeds, with the steps split across the required number of policies.

If I've misunderstood the code, and there's a reason to specifically have two policies, I'd expect a build time failure from CDK when the number of steps exceeds 40, rather than a build time failure.

### Current Behavior

Cloudformation deployment fails with the message "There can be at most 20 step adjustments per scaling policy".

### Reproduction Steps

Starting with a Fargate Service and an SQS queue (I'm trying to reproduce the tracking policy https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-target-tracking-metric-math.html describes without using metric math).

```
        maximum_number_of_tasks = 50
        desired_messages_per_task = 20

        scaling = service.auto_scale_task_count(
            min_capacity=1,
            max_capacity=maximum_number_of_tasks,
        )

        scaling_steps = [
            aws_applicationautoscaling.ScalingInterval(
                lower=step_number * desired_messages_per_task,
                upper=step_number * (desired_messages_per_task + 1) - 1,
                change=step_number + 1,
            )
            for step_number
            in range(0, maximum_number_of_tasks)
        ]

        scaling.scale_on_metric(
            id="Track visible messages per task",
            metric=queue.metric_approximate_number_of_messages_visible(
                statistic="Average",
                period=Duration.minutes(1),
            ),
            adjustment_type=aws_autoscaling.AdjustmentType.EXACT_CAPACITY,
            scaling_steps=scaling_steps,
            cooldown=Duration.minutes(3),
        )
```

### Possible Solution

Allow for more than two scaling policies to be created (this may not make sense, my understanding of these policies is not great).

### Additional Information/Context

_No response_

### CDK CLI Version

2.86.0 (build 1130fab)

### Framework Version

2.81.0

### Node.js Version

v16.18.1

### OS

Ubuntu (Windows Subsystem for Linux)

### Language

Python

### Language Version

3.9.7

### Other information

_No response_

### PR DESCRIPTION
**Pull request by scanlonp**
`StepScalingPolicy` did not have a validation that the number of intervals in `scalingSteps` was in the allowable range. The [Autoscaling documentation](https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-quotas.html) states 20 is the maximum step changes in a policy, and since autoscaling creates 2 policies (an [UpperPolicy](https://github.com/aws/aws-cdk/blob/bc029fe5ac69a8b7fd2dfdbcd8834e9a2cf8e000/packages/aws-cdk-lib/aws-autoscaling/lib/step-scaling-policy.ts#L136-L166) and a [LowerPolicy](https://github.com/aws/aws-cdk/blob/bc029fe5ac69a8b7fd2dfdbcd8834e9a2cf8e000/packages/aws-cdk-lib/aws-autoscaling/lib/step-scaling-policy.ts#L105-L134)), our cap is 40.

There is an identical change in Application Autoscaling.

Closes #26215.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by scanlonp** [comment]
Clarification Request: this PR should not require an integration test because it does not change the API nor add any features. It moves an error that would have been thrown at deploy time to one that is thrown at synth time. Correct?

File: packages/aws-cdk-lib/aws-applicationautoscaling/lib/step-scaling-policy.ts [hunk 1]
```diff
@@ -111,6 +113,10 @@ export class StepScalingPolicy extends Construct {
       throw new Error('You must supply at least 2 intervals for autoscaling');
     }
 
+    if (props.scalingSteps.length > 40) {
+      throw new Error('You must have less than 40 steps in StepScalingPolicyProps.scalingSteps');
```
Comment (kaizencc) [inline packages/aws-cdk-lib/aws-applicationautoscaling/lib/step-scaling-policy.ts:117]: should mention how many steps were requested

File: packages/aws-cdk-lib/aws-autoscaling/lib/step-scaling-policy.ts [hunk 2]
```diff
@@ -96,6 +98,10 @@ export class StepScalingPolicy extends Construct {
       throw new Error('You must supply at least 2 intervals for autoscaling');
     }
 
+    if (props.scalingSteps.length > 40) {
+      throw new Error('You must have less than 40 steps in StepScalingPolicyProps.scalingSteps');
```
Comment (kaizencc) [inline packages/aws-cdk-lib/aws-autoscaling/lib/step-scaling-policy.ts:102]: same here

**Review by kaizencc — CHANGES_REQUESTED** [review]
Looks pretty solid, one minor comment

File: packages/aws-cdk-lib/aws-applicationautoscaling/lib/step-scaling-policy.ts (hunk 1 above)
Comment (scanlonp) [reply packages/aws-cdk-lib/aws-applicationautoscaling/lib/step-scaling-policy.ts]: Done.

**Review by kaizencc — APPROVED** [review]
