### PR TITLE
fix(eks): fargate profile deployment fails with missing iam:PassRole

### LINKED ISSUE #8546: failed to create eks fargate profile
Creating fargate profile in amazon eks now returns not authorized to perform iam:PassRole error

圖片

### Reproduction Steps

```ts

    const mastersRole = new iam.Role(this, 'AdminRole', {
      assumedBy: new iam.AccountRootPrincipal()
    });

    const cluster = new eks.Cluster(this, 'Cluster', {
      vpc,
      mastersRole,
      version: '1.16',
    });

    cluster.addFargateProfile('FargateProfile', {
      selectors: [
        { namespace: 'default' },
        { namespace: 'kube-system' },
      ]
    })
```

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by pahud**
fix(eks): fargate profile deployment fails with missing iam:PassRole

This PR allows the cluster creation role to `iam:PassRole` the fargate pod execution role.

Closes #8546 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by pahud** [comment]
Hi @eladb 

Looks like we need allow the cluster creation role to `iam:PassRole` the fargate pod execution role. Not sure if this is a good fix. But this works in my integ testing.  Any comments?

**Comment by eladb** [comment]
@pahud any documentation around this?

**Comment by pahud** [comment]
> @pahud any documentation around this?

Unfortunately, no.  Looks like `eksctl` has been using a much wider scope which literally allow the cluster creation role to `iam:PassRole` `role/eksctl-*` and `role/eksctl-managed-*`.([source](https://github.com/weaveworks/eksctl/blob/1273981b31e2cb1d6fde18a7e5b39b9e52502e06/userdocs/src/usage/minimum-iam-policies.md))

圖片

It makes sense that the creation role should be able to 'iam:PassRole' the pod execution role when creating the fargate profile. I just don't know why we encounter this error today.

File: packages/@aws-cdk/aws-eks/lib/fargate-profile.ts [hunk 1]
```diff
@@ -145,6 +145,9 @@ export class FargateProfile extends Construct implements ITaggable {
       managedPolicies: [ iam.ManagedPolicy.fromAwsManagedPolicyName('AmazonEKSFargatePodExecutionRolePolicy') ],
     });
 
+    const creationRoleArn = props.cluster._getKubectlCreationRoleArn();
```
Comment (eladb) [inline packages/@aws-cdk/aws-eks/lib/fargate-profile.ts:148]: There is an `iam.Role` object hiding there behind this method. Let's change it to return it instead of its ARN so we don't need `fromRoleArn` here.

Comment (pahud) [reply packages/@aws-cdk/aws-eks/lib/fargate-profile.ts:148]: > There is an `iam.Role` object hiding there behind this method. Let's change it to return it instead of its ARN so we don't need `fromRoleArn` here.

I didn't get it. Do you mean to expose the creationRole from the custom resource so we can access it?

https://github.com/aws/aws-cdk/blob/03e85eb5629f87b34005422dfeb367d5581e85e8/packages/%40aws-cdk/aws-eks/lib/cluster-resource.ts#L32

Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/fargate-profile.ts:148]: I think so... I need to dive a little deeper.

**Comment by pahud** [comment]
> @pahud I pushed some changes to your branch. Can you please verify that everything looks good?

OK. WIP.

**Comment by pahud** [comment]
> @pahud I pushed some changes to your branch. Can you please verify that everything looks good?

LGTM and I just updated the integ to use single natgateway to avoid hitting max EIP address error during integ testing in the development. FYI

https://github.com/aws/aws-cdk/blob/820d7bf7ee705ac42702c6c375afac55e293534f/packages/%40aws-cdk/aws-eks/test/integ.eks-cluster.ts#L19

**Comment by pahud** [comment]
@eladb ready now.
