### PR TITLE
fix(@aws-cdk/aws-elasticloadbalancingv2)/logAccessLogs provides open permissions on log bucket for alb

### LINKED ISSUE #2824: Application Load Balancer, LogAccessLogs doesnt follow best practise
**Describe the bug**
The policy generated by the LogAccessLogs method allows too wide of a permission on a prefix of `loadbalancer`

`${log-bucket.Arn}/loadbalancer*`
vs
`${log-bucket.Arn}/arn:aws:s3:::${log-bucket}/loadbalancer/AWSLogs/${AWS::AccountId}/*`

**To Reproduce**
Create a ALB and call LogAccessLogs on it, with a bucket
Generates a bucket policy with `${log-bucket.Arn}/loadbalancer*`

**Expected behavior**
Generate a bucket policy with `${log-bucket.Arn}/arn:aws:s3:::${log-bucket}/loadbalancer/AWSLogs/${AWS::AccountId}/*`

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html

**Version:**
 - OS - Win 10
 - Programming Language - CSharp
 - CDK Version - 0.28

### PR DESCRIPTION
**Pull request by made2591**
Bug
The policy generated by the LogAccessLogs method allows too wide of a permission on a prefix of loadbalancer
```
${log-bucket.Arn}/loadbalancer*
```
vs
```
${log-bucket.Arn}/arn:aws:s3:::${log-bucket}/loadbalancer/AWSLogs/${AWS::AccountId}/*
```

To Reproduce
Create a ALB and call LogAccessLogs on it, with a bucket generates a bucket policy with ```${log-bucket.Arn}/loadbalancer*```. 

Expected behavior
```
Generate a bucket policy with ${log-bucket.Arn}/arn:aws:s3:::${log-bucket}/loadbalancer/AWSLogs/${AWS::AccountId}/*
```

Fixed with correct permission as suggested in [doc](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html).

close #2824

----

### Pull Request Checklist

* [ ] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [ ] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
  - __Design__: For significant features, design document added to `design` folder
* [ ] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [ ] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts [hunk 1]
```diff
@@ -97,7 +98,7 @@ export class ApplicationLoadBalancer extends BaseLoadBalancer implements IApplic
     }
 
     prefix = prefix || '';
-    bucket.grantPut(new iam.AccountPrincipal(account), prefix + '*');
+    bucket.grantPut(new iam.AccountPrincipal(account), cdk.Fn.sub((prefix ? prefix + "/" : "") + 'AWSLogs/' + "${AWS::AccountId}" + '/*'));
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts]: What is the `sub` used for?

I feel like the following should work:

```ts
bucket.grantPut(new iam.AccountPrincipal(account), `${prefix ? prefix + "/" : "")}AWSLogs/${Stack.of(this).account}/*`));

```

Comment (made2591) [reply packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts]: Believe me or not, this was my first idea (I also came into #1754). Then, I thought I wouldn't have the accountId *hardcoded* inside the template and ```${Stack.of(this).account}``` will do like that by using the ```account``` ([source](https://github.com/awslabs/aws-cdk/blob/c5e43e2652f7d499e2382e2085250349a555ec1b/packages/%40aws-cdk/cdk/lib/stack.ts#L112)). This will be a concrete value only if an account was specified in `env` when the stack was defined.  Otherwise, it will be a string that resolves to `{ "Ref": "AWS::AccountId" }`. I was wondering if this will ever be true because I tried with a sample account and it resolved to my account ID, even without defining it in env. So, I noticed that if env is not defined, the account from context will be taken ([source](https://github.com/awslabs/aws-cdk/blob/c5e43e2652f7d499e2382e2085250349a555ec1b/packages/%40aws-cdk/cdk/lib/stack.ts#L22)) - (I guess propagated from my credentials?)... so I moved to sub to produce an output like this:

```
...
Resource:
    Fn::Join:
    - ""
    - - Fn::GetAtt:
            - testS352B11FD6
            - Arn
        - /AWSLogs/
        - Fn::Sub: ${AWS::AccountId}
        - /*
...
```

Make senses? Did I misunderstand something?

Comment (rix0rrr) [reply packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts]: It does. As a side note, instead of `Stack.of(this).account` you could also have used `Aws.accountId` which would lead to the same result (without the `Fn.sub()`).

However, the `Stack.of(...).account` variant is correct, would also be correct if the bucket was in another account (the "current account" variant would not be), and we are making some other changes to make sure that you won't see hardcoded IDs anymore where you're not expecting them.

So I would still vote for the other variant.

Comment (made2591) [reply packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts]: Ok, thank you @rix0rrr ! I will change to `Stack.of(...).account` as you proposed ^^
