### PR TITLE
fix(eks): Helm chart timeout expects duration

### LINKED ISSUE #8718: (EKS): CDK uses integer for timeout; Helm expects duration
Wanted to test the new timeout parameter in the EKS Helm construct as I had problems deploying a large Helm chart like the prometheus-operator chart. But I just ran it and hit a problem: CDK translates the timeout to an integer value in seconds but the Helm version used (v3) expects a duration specification. So 900s instead of 900.

### Reproduction Steps

```
        cluster.addChart('prometheus-operator', {
            chart: 'prometheus-operator',
            namespace: 'monitoring',
            release: 'prometheus-operator',
            repository: 'https://kubernetes-charts.storage.googleapis.com',
            timeout: Duration.minutes(15),
            wait: true
```

### Error Log

```
[ERROR] Exception: b'Error: invalid argument "900" for "--timeout" flag: time: missing unit in duration 900\n' Traceback (most recent call last):   File "/var/task/index.py", line 16, in handler     return helm_handler(event, context)   File "/var/task/helm/__init__.py", line 49, in helm_handler     helm('upgrade', release, chart, repository, values_file, namespace, version, wait, timeout)   File "/var/task/helm/__init__.py", line 90, in helm     raise Exception(output)
```

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

Not sure if this could be related to an upgrade @pahud is working on in **aws-lambda-layer-kubectl**?

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by eduardomourar**
This resolves a problem with timeout parameter being passed down to Helm. The Helm version used (v3) expects a duration (in our case, in seconds such as `600s`) instead of integer.

fixes #8718

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by eduardomourar** [comment]
Is there a way to have a unit test for the python EKS custom resources?

**Comment by pahud** [comment]
Not sure if it's related to this issue but I kept hitting lambda timeout when I deploy the [integ.eks-cluster.ts](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-eks/test/integ.eks-cluster.ts).

@eduardomourar did you hit this error?


圖片

**Comment by pahud** [comment]
Hi @eladb 

Looks like we have to first get this PR sorted before I can successfully build my integ test and continue my PRs.

File: packages/@aws-cdk/aws-eks/lib/helm-chart.ts [hunk 1]
```diff
@@ -100,7 +100,7 @@ export class HelmChart extends Construct {
         Chart: props.chart,
         Version: props.version,
         Wait: props.wait ?? false,
-        Timeout: timeout,
+        Timeout: timeout && `${timeout.toString()}s`, // Helm v3 expects duration instead of integer
```
Comment (eladb) [inline packages/@aws-cdk/aws-eks/lib/helm-chart.ts:103]:
```suggestion
        Timeout: timeout ? `${timeout.toString()}s` : undefined, // Helm v3 expects duration instead of integer
```

File: packages/@aws-cdk/aws-eks/test/integ.eks-cluster.ts [hunk 2]
```diff
@@ -59,12 +59,18 @@ class EksClusterStack extends TestStack {
...
-    // // apply a kubernetes manifest
+    // apply a kubernetes manifest
     cluster.addResource('HelloApp', ...hello.resources);
 
-    // // add two Helm charts to the cluster. This will be the Kubernetes dashboard and the Nginx Ingress Controller
+    // add two Helm charts to the cluster. This will be the Kubernetes dashboard and the Nginx Ingress Controller
     cluster.addChart('dashboard', { chart: 'kubernetes-dashboard', repository: 'https://kubernetes-charts.storage.googleapis.com' });
-    cluster.addChart('nginx-ingress', { chart: 'nginx-ingress', repository: 'https://helm.nginx.com/stable', namespace: 'kube-system' });
+    cluster.addChart('nginx-ingress', {
+      chart: 'nginx-ingress',
```
Comment (eladb) [inline packages/@aws-cdk/aws-eks/test/integ.eks-cluster.ts:68]: Expecting to see an integ test update

Comment (eduardomourar) [reply packages/@aws-cdk/aws-eks/test/integ.eks-cluster.ts:78]: yes, i am update the integ test to check the logic for the both wait and timeout

**Comment by eduardomourar** [comment]
> Not sure if it's related to this issue but I kept hitting lambda timeout when I deploy the [integ.eks-cluster.ts](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-eks/test/integ.eks-cluster.ts).
> 
> @eduardomourar did you hit this error?

No, I did not. But this looks like a error coming from the fact that we are actually running all those helm charts with wait set to true (because there is a bug even if you set to false).
