### PR TITLE
fix(codepipeline): work around CodeBuild's pipeline key bug

### LINKED ISSUE #4033: Add validation for CodeBuild project's key being different than the pipeline's key
The CodeBuild action ignores the `EncryptionKey` part of the CodePipeline's `ArtifactStore`, and always uses they KMS key that was set on the project itself (the default account key if none was set). This is a problem in cross-account pipelines, as the other actions will get an 'Access Denied' when trying to read artifacts encrypted with a key they don't have permissions for.

* Add validation that fails if a customer tries to create a pipeline with at least 1 cross-account action, with a CodeBuild action whose project has key set to something different than the artifact bucket key
* Create an issue in our backlog that points to the CodeBuild troubleshooting guide, and add a link to this issue to the validation message created above
* Consider adding a property like `skipCrossAccountKeyValidation: boolean` (default: `false`) that allows a customer to get rid of this validation once CodeBuild fixes the issue without having to update their CDK version. Later we can deprecate that field, remove the validation and never use the property anymore

### PR DESCRIPTION
**Pull request by skinny85**
CodeBuild has a bug where they ignore the encryption key of the pipeline's artifact bucket,
instead always using the project's key
(the account's default S3 key if the project key has not been set).
This makes the CodeBuild actions unusable in a cross-account pipeline,
as subsequent actions will get an 'Access Denied' error when trying to download the incorrectly encrypted artifacts.

The fix is to always set the project's key to be the same as the pipeline key in the CodeBuild action.

Fixes #4033

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by skinny85** [comment]
This is a similar issue as addressed in #4171 . In this case though, it's more complicated, for 2 reasons:

1. The problem, while present for all pipelines, is actually only fatal (and thus noticeable) for cross-account pipelines.
2. There is a possible workaround.

Right now, I've implemented a "simple" variant, that just errors out always (with an escape hatch).
But I think it's worth discussing whether we want to do something different here:

1. Only have the validation for pipelines that are cross-account (a little tricky, but probably doable with some fiddling).
2. Automatically set the `encryptionKey` for the project to the same key that's used in the pipeline's bucket (some subtleties here as well, for example what happens with imported projects?).

Let me know what you think!

**Comment by skinny85** [comment]
@eladb did you want to post [this comment](https://github.com/aws/aws-cdk/pull/4171#discussion_r326888645) in this PR?

**Comment by skinny85** [comment]
@eladb ping

File: packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts [hunk 1]
```diff
@@ -60,6 +60,20 @@ export interface CodeBuildActionProps extends codepipeline.CommonAwsActionProps
...
+   * the project called by this action uses the same key.
+   * This is to work around a CodeBuild bug
+   * where a project used in a pipeline ignores the pipeline's key,
+   * instead always using the project's own key.
+   * Pass false here to skip this validation.
+   *
+   * @default true
+   * @see https://github.com/aws/aws-cdk/issues/4182
+   */
+  readonly validatePipelineStoreKey?: boolean;
```
[the remark this answers is not in the document]
Comment (skinny85) [reply packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts]: See [this comment](https://github.com/aws/aws-cdk/pull/4183#issuecomment-533757149).

Specifically, what would you do with imported projects?

[the remark this answers is not in the document]
Comment (skinny85) [reply packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts]: Changed to setting the key automatically in the new version.

**Comment by skinny85** [comment]
Changed to approach to automatically set the key in the newest revision, according to @eladb 's comments.

**Comment by skinny85** [comment]
> Wouldn’t it make more sense for this to be inside codebuild.Project so the ugliness stays local and doesn’t require exposing a mutating property (which is a big no no).

How do you see that's happening, considering it's a CodePipeline thing we're changing (we're setting the project's key to a key from CodePipeline)?

**Comment by eladb** [comment]
> How do you see that's happening, considering it's a CodePipeline thing we're changing (we're setting the project's key to a key from CodePipeline)?

It's not a CodePipeline thing, it's a CodeBuild thing. Maybe we need the pipeline to "bind" to the CodeBuild project when it's added through an action and it will provide an opportunity for the build project to read the key from the pipeline.

**Comment by skinny85** [comment]
> It's not a CodePipeline thing, it's a CodeBuild thing. Maybe we need the pipeline to "bind" to the CodeBuild project when it's added through an action and it will provide an opportunity for the build project to read the key from the pipeline.

How is that different? That will expose a `bind` method that mutates the project's `encryptionKey` property, which you said is a big no no.

**Comment by skinny85** [comment]
Added the method `bindToCodePipeline()` to `IProject`.

File: packages/@aws-cdk/aws-codebuild/lib/project.ts [hunk 2]
```diff
@@ -146,6 +157,14 @@ export interface IProject extends IResource, iam.IGrantable, ec2.IConnectable {
...
    */
   metricFailedBuilds(props?: cloudwatch.MetricOptions): cloudwatch.Metric;
+
+  /**
+   * A callback invoked when the given project is added to a CodePipeline.
+   *
+   * @param scope the construct the binding is taking place in
+   * @param options additional options for the binding
+   */
+  bindToCodePipeline(scope: Construct, options: BindToCodePipelineOptions): void;
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild/lib/project.ts]: Why is this in IProject? There is no way to modify the key to an imported project. Just check “instanceof Project” and then call bindToPipeline.

File: packages/@aws-cdk/aws-codebuild/lib/project.ts [hunk 3]
```diff
@@ -388,6 +407,10 @@ abstract class ProjectBase extends Resource implements IProject {
       ...props,
     });
   }
+
+  public bindToCodePipeline(_scope: Construct, _options: BindToCodePipelineOptions): void {
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild/lib/project.ts]: Pass in the pipeline itself and expose the artifacts bucket as a readonly property from the pipeline if it’s not already there.

File: packages/@aws-cdk/aws-codebuild/lib/project.ts [hunk 4]
```diff
@@ -742,6 +767,22 @@ export class Project extends ProjectBase {
     this._secondaryArtifacts.push(secondaryArtifact.bind(this, this).artifactsProperty);
   }
 
+  public bindToCodePipeline(_scope: Construct, options: BindToCodePipelineOptions): void {
+    // work around a bug in CodeBuild: it ignores the KMS key set on the pipeline,
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild/lib/project.ts]: Can you validate here that this project uses pipeline source?

Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: Sure.

File: packages/@aws-cdk/aws-codebuild/lib/project.ts (hunk 3 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: That won't work. This might be either the artifact's main bucket, or a replication bucket if this project is used in a cross-region fashion. It's the same reason `bucket` is a property on `ActionBindOptions` in `IAction`, instead of being accessed through `stage.pipeline.artifactBucket`.

File: packages/@aws-cdk/aws-codebuild/lib/project.ts (hunk 2 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: Sure.

**Comment by skinny85** [comment]
Included the last comments.

**Comment by skinny85** [comment]
@eladb ping

File: packages/@aws-cdk/aws-codepipeline-actions/test/integ.lambda-deployed-through-codepipeline.lit.ts [hunk 5]
```diff
@@ -47,7 +47,7 @@ pipeline.addStage({
 // synthesize the Lambda CDK template, using CodeBuild
 // the below values are just examples, assuming your CDK code is in TypeScript/JavaScript -
 // adjust the build environment and/or commands accordingly
-const cdkBuildProject = new codebuild.Project(pipelineStack, 'CdkBuildProject', {
+const cdkBuildProject = new codebuild.PipelineProject(pipelineStack, 'CdkBuildProject', {
```
Comment (eladb) [inline packages/@aws-cdk/aws-codepipeline-actions/test/integ.lambda-deployed-through-codepipeline.lit.ts]: Why is this change needed?

File: packages/@aws-cdk/aws-codebuild/test/test.project.ts [hunk 6]
```diff
@@ -148,6 +149,24 @@ export = {
 
       test.done();
     },
+
+    'cannot have bindToCodePipeline() be called on it'(test: Test) {
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild/test/test.project.ts]: Where is the test that actually verifies the new behaviour?

File: packages/@aws-cdk/aws-codebuild/lib/project.ts [hunk 7]
```diff
@@ -760,6 +799,11 @@ export class Project extends ProjectBase {
     return ret;
   }
 
+  private set encryptionKey(encryptionKey: kms.IKey) {
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild/lib/project.ts]: Move the into `bindToCodePipeline`. This is not something we expect other private logic to implement.

#keephackslocal

Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: This setter is used twice (once in the constructor, and another time in `bindToCodePipeline`). If I moved it to `bindToCodePipeline`, this logic would have to be duplicated.

Does it make sense to leave it then?

Comment (eladb) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: Okay yes makes sense.

File: packages/@aws-cdk/aws-codepipeline-actions/test/integ.lambda-deployed-through-codepipeline.lit.ts (hunk 5 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codepipeline-actions/test/integ.lambda-deployed-through-codepipeline.lit.ts]: It's because of the validation that you asked to add in the previous revision (checking that the source of the project is pipeline: https://github.com/aws/aws-cdk/pull/4183#discussion_r332232965 ).
