### PR TITLE
fix(stepfunctions-tasks): sageMakerCreateTrainingJob does not correctly support empty inputDataConfig

### LINKED ISSUE #31132: aws-stepfunctions-tasks: SageMakerCreateTrainingJob does not correctly support empty inputDataConfig
### Describe the bug

`inputDataconfig` is incorrectly marked as a required field on `SageMakerCreateTrainingJobProps`. Forcing this value to undefined throws a `Cannot read properties of undefined` error.

Relevant SageMakerCreateTrainingJob docs: https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateTrainingJob.html#sagemaker-CreateTrainingJob-request-InputDataConfig`

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

A valid `SageMakerCreateTrainingJob` step function task can be created when `inputDataConfig` is undefined.

### Current Behavior

`SageMakerCreateTrainingJob` throws an error when `inputDataConfig` is undefined.

```
Argument of type '{ trainingJobName: string; algorithmSpecification: { trainingImage: aws_stepfunctions_tasks.DockerImage; trainingInputMode: aws_stepfunctions_tasks.InputMode.FILE; }; outputDataConfig: { ...; }; resourceConfig: { ...; }; stoppingCondition: { ...; }; hyperparameters: {}; }' is not assignable to parameter of type 'SageMakerCreateTrainingJobProps'.
  Property 'inputDataConfig' is missing in type '{ trainingJobName: string; algorithmSpecification: { trainingImage: aws_stepfunctions_tasks.DockerImage; trainingInputMode: aws_stepfunctions_tasks.InputMode.FILE; }; outputDataConfig: { ...; }; resourceConfig: { ...; }; stoppingCondition: { ...; }; hyperparameters: {}; }' but required in type 'SageMakerCreateTrainingJobProps'.ts(2345)
```

### Reproduction Steps

```
import { Duration, Size } from 'aws-cdk-lib';
import { InstanceType } from 'aws-cdk-lib/aws-ec2';
import { JsonPath } from 'aws-cdk-lib/aws-stepfunctions';
import { DockerImage, InputMode, S3Location, SageMakerCreateTrainingJob } from 'aws-cdk-lib/aws-stepfunctions-tasks';
import { Construct } from 'constructs';

class Workflow extends Construct {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    const sageMakerInvocation = new SageMakerCreateTrainingJob(this, 'Start SageMaker', {
      trainingJobName: JsonPath.stringAt('$.JobName'),
      algorithmSpecification: {
        trainingImage: DockerImage.fromJsonExpression('$.DockerImagePath'),
        trainingInputMode: InputMode.FILE,
      },
      inputDataConfig: [],
      outputDataConfig: {
        s3OutputLocation: S3Location.fromJsonExpression('$.S3OutputPath'),
      },
      resourceConfig: {
        instanceCount: 1,
        instanceType: new InstanceType(JsonPath.stringAt('$.InstanceType')),
        volumeSize: Size.gibibytes(JsonPath.numberAt('$.InstanceVolumeSize')),
      },
      stoppingCondition: {
        maxRuntime: Duration.seconds(JsonPath.numberAt('$.MaximumJobDuration')),
      },
    });
  }
}
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.151.0 (build b8289e2)

### Framework Version

_No response_

### Node.js Version

Node.js v20.12.2

### OS

macOS 14.6.1

### Language

TypeScript

### Language Version

macOS 14.6.1

### Other information

_No response_

### PR DESCRIPTION
**Pull request by xazhao**
### Issue # (if applicable)

Closes #31132.

### Reason for this change

`inputDataConfig` is not a required property in the API:
https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateTrainingJob.html#sagemaker-CreateTrainingJob-request-InputDataConfig

However in `SageMakerCreateTrainingJob`, it's marked as required. We should make it align with the API.

### Description of changes

Make the property optional.

### Description of how you validated changes

unit test and integration test

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/sagemaker/create-training-job.ts [hunk 1]
```diff
@@ -50,8 +50,10 @@ export interface SageMakerCreateTrainingJobProps extends sfn.TaskStateBaseProps
 
   /**
    *  Describes the various datasets (e.g. train, validation, test) and the Amazon S3 location where stored.
+   *
+   * @default - No inputDataConfig
    */
-  readonly inputDataConfig: Channel[];
+  readonly inputDataConfig?: Channel[];
```
Comment (GavinZZ) [inline packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/sagemaker/create-training-job.ts:56]: This could technically be a breaking changes depending on users setup. For example, if I define the `SageMakerCreateTrainingJobProps` like 
```
const props = {
    algorithmSpecification: {
      algorithmName: 'BlazingText',
      trainingInputMode: InputMode.FAST_FILE,
    },
    inputDataConfig: [{
      channelName: 'InputData',
      dataSource: {
        s3DataSource: {
          s3Location: S3Location.fromBucket(trainingData, 'data/'),
        },
      },
    }],
    outputDataConfig: { s3OutputLocation: S3Location.fromBucket(trainingData, 'result/') },
    trainingJobName: 'mytrainingjob',
}

props.inputDataConfig.push({
    channelName: 'InputConfig',
    dataSource: {
      s3DataSource: {
        s3Location: S3Location.fromBucket(trainingData, 'XXXXXXX'),
      },
    },
  })
```
After your change, users would have linting errors and a couple setup on typescript projects is to fail build on linter errors. 

This is pretty edge case but can be possible. I also understand the fact that this is optional in CFN schema now. Let's bring it up to team discussion?

Comment (xazhao) [reply packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/sagemaker/create-training-job.ts:56]: That's a great point. Will bring it to the team to discuss.

Comment (TheRealAmazonKendra) [reply packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/sagemaker/create-training-job.ts:56]: Linting errors would not be something we take into account when we define breaking changes. Linters are typically a matter of preference, not correctness.

In general, weakening an input type is not a breaking change. This should be fine.

Comment (GavinZZ) [reply packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/sagemaker/create-training-job.ts:56]: Thanks Kendra for clarification.

**Review by GavinZZ — APPROVED** [review]
LGTM

File: packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/sagemaker/create-training-job.ts (hunk 1 above)
Comment (GavinZZ) [reply packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/sagemaker/create-training-job.ts:56]: Thanks Kendra for clarification.

**Comment by xazhao** [comment]
@Mergify update
