### PR TITLE
fix(core): regression: source directory is fingerprinted even if bundling is skipped

### LINKED ISSUE #11459: [core] AssetStaging by bundling not using custom assetHash when doing quick 'skip' hash
`AssetStaging` provides a shortcut when using custom bundling interface which allows to `skip` the normal hashing method. Instead it falls back to `AssetHashType.SOURCE` with a comment implying it would be quicker. This code path seems to be only invoked when `cdk list` is called, but I might have misunderstood the condition. 

Code Reference: https://github.com/aws/aws-cdk/blob/21ccfce514e10cfcdde36148b45f085d3494c540/packages/%40aws-cdk/core/lib/asset-staging.ts#L240-L248

This shortcut is also taken when a custom assetHash is provided and `assetHashType` set to `CUSTOM`. 
Besides from calculating a different hash, fingerprinting source files will always be slower than using a pre-computed hash.

### Reproduction Steps

Apologies for not providing a code sample at this point. But it can be recreated with a simple setup:
- Add a `S3.Asset` to a stack pointing to a large folder (e.g. one that contains a lot of `node_modules`)
- Provide a custom `assetHash` and type
- Run `time cdk synth`, then run `time cdk ls`

### What did you expect to happen?

`cdk ls` should be quicker or at leat taking the same time as `cdk synth`.

### What actually happened?

`cdk ls` takes significantly longer than `cdk synth`, since calculating the assetHash from a large source takes much longer than using a pre-provided hash.

### Environment

  - **CDK CLI Version:** 1.73.0
  - **Framework Version:** 1.73.0
  - **Node.js Version:** v12.18.0
  - **OS               :** macOS 10.15.7 (19H2) 
  - **Language (Version):** TypeScript 4.0.5

### Other
 
This is related to the sibling issue: #11460 : [core] AssetStaging by bundling ignoring `AssetHashType.OUTPUT` when doing quick 'skip' hash

I'm happy to work on this issue, it seems very straight forward. However as pointed out in the other issue there might be a more generic or better solution to it.

--- 

This is :bug: Bug Report

### LINKED ISSUE #11460: [core] AssetStaging by bundling ignoring AssetHashType.OUTPUT when doing quick 'skip' hash
`AssetStaging` provides a shortcut when using custom bundling interface which allows to `skip` the normal hashing method. Instead it falls back to `AssetHashType.SOURCE` with a comment implying it would be quicker. This code path seems to be only invoked when `cdk list` is called, but I might have misunderstood the condition. 

Code Reference: https://github.com/aws/aws-cdk/blob/21ccfce514e10cfcdde36148b45f085d3494c540/packages/%40aws-cdk/core/lib/asset-staging.ts#L240-L248

This shortcut is also taken when `assetHashType` set to `OUTPUT`. Obviously this won't be calculating the correct hash, but I'm not sure what the implication of a different hash is. In any case, I believe the assumption that `SOURCE` hashing is always faster than `OUTPUT` is a wrong assumption.

### Reproduction Steps

Apologies for not providing a code sample at this point. But it can be recreated with a simple setup:
- Add a `S3.Asset` to a stack pointing to a large folder (e.g. one that contains a lot of `node_modules`)
- Provide a bundling method that can do bundling really really fast (e.g. `esbuild` or a fake one)
- Run `time cdk synth`, then run `time cdk ls`

### What did you expect to happen?

`cdk ls` should be quicker or at leat taking the same time as `cdk synth`.

### What actually happened?

`cdk ls` takes significantly longer than `cdk synth`, since calculating the assetHash from a large source takes much longer than running a very quick bundler and hashing a very small number of output files.

### Environment

  - **CDK CLI Version:** 1.73.0
  - **Framework Version:** 1.73.0
  - **Node.js Version:** v12.18.0
  - **OS               :** macOS 10.15.7 (19H2) 
  - **Language (Version):** TypeScript 4.0.5

### Other
 
I'm happy to work on this issue, it seems very straight forward enough.

However, combined with its sibling issue #11459 this would just result in removing the `skip` part of `stageByBundling`. I'm wondering if we could just remove random or empty data instead, but I'm not sure if `cdk ls` will rely on any of it.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by jogold**
If the asset uses OUTPUT or BUNDLE it's generally because its source is
a very large directory. This is the case for the `NodejsFunction` which
mounts the project root (along with the `node_modules` folder!).

Use a custom hash in this case when skipping bundling. Otherwise running
`cdk ls` can result in heavy fingerprinting operations (again this is
the case for the `NodejsFunction`) and can be much slower than running
`cdk synth` or `cdk diff`, making it pointless to skip bundling.

Regression introduced in #11008
(https://github.com/aws/aws-cdk/pull/11008/files#diff-62eef996be8abeb157518522c3cbf84a33dd4751c103304df87b04eb6d7bbab6L160)

Before #11008:
https://github.com/aws/aws-cdk/blob/c1453147e7c484c54f1380d2fa9ba0cdf2859002/packages/%40aws-cdk/core/lib/asset-staging.ts#L159-L160

Closes #11459 
Closes #11460 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jogold** [comment]
@rix0rrr can you take a look?

File: packages/@aws-cdk/core/lib/asset-staging.ts [hunk 1]
```diff
@@ -239,10 +240,16 @@ export class AssetStaging extends CoreConstruct {
...
+      // If the asset uses OUTPUT or BUNDLE, we use a CUSTOM hash to avoid fingerprinting
+      // a potentially very large source directory.
+      let hashType = AssetHashType.SOURCE;
+      if (this.hashType === AssetHashType.OUTPUT || AssetHashType.BUNDLE) {
+        this.customSourceFingerprint = Names.uniqueId(this);
+        hashType = AssetHashType.CUSTOM;
+      }
       return {
-        assetHash: this.calculateHash(AssetHashType.SOURCE),
+        assetHash: this.calculateHash(hashType),
```
Comment (jogold) [inline packages/@aws-cdk/core/lib/asset-staging.ts:252]: Maybe we can always use a custom hash in this case?

**Comment by mrgrain** [comment]
This looks good! Using a unique id seems appropriate. I was considering hashing the `BundlingOptions` object.

I don't think it would fix #11459 though, since the `AssetHashType` is set to `source` unless it's one of the output/bundle ones.

I was thinking maybe something like this? It mimics the hash calculation before bundling (just after the skip block).
```
    if (skip) {
      // We should have bundled, but didn't to save time. Still pretend to have a hash.
      // If the asset uses OUTPUT (or BUNDLE), we use a CUSTOM hash to avoid fingerprinting
      // a potentially very large source directory. Other hash types are kept the same.
      let hashType = this.hashType;
      if (hashType === AssetHashType.OUTPUT || hashType === AssetHashType.BUNDLE) {
        this.customSourceFingerprint = Names.uniqueId(this);
        hashType = AssetHashType.CUSTOM;
      }

      return {
        assetHash: this.calculateHash(hashType, bundling),
        stagedPath: this.sourcePath,
      };
    }
```

**Comment by jogold** [comment]
@rix0rrr ping... would be nice if this could be merge before the next release with the new `NodejsFunction`. Without this doing `cdk ls` on a app with `NodejsFunction` almost never completes.

File: packages/@aws-cdk/core/lib/asset-staging.ts [hunk 2]
```diff
@@ -239,10 +240,16 @@ export class AssetStaging extends CoreConstruct {
    */
   private stageByBundling(bundling: BundlingOptions, skip: boolean): StagedAsset {
     if (skip) {
-      // We should have bundled, but didn't to save time. Still pretend to have a hash,
-      // but always base it on sources.
+      // We should have bundled, but didn't to save time. Still pretend to have a hash.
+      // If the asset uses OUTPUT or BUNDLE, we use a CUSTOM hash to avoid fingerprinting
+      // a potentially very large source directory. Other hash types are kept the same.
+      let hashType = this.hashType;
+      if (hashType === AssetHashType.OUTPUT || AssetHashType.BUNDLE) {
```
Comment (rix0rrr) [inline packages/@aws-cdk/core/lib/asset-staging.ts:247]: That's not what that means :)

**Review by rix0rrr — DISMISSED** [review]

**Comment by rix0rrr** [comment]
Feels like running the Docker container during `synth` is just asking for all kinds of performance issues, which then need a big slew of workarounds.

Is there really now way to defer this work to asset publishing time? Is the whole reason we do this during `synth` simply to get an artifact hash? 

And if that's true, is that only because a source hash is too expensive?

I'm starting to think we need an alternative approach here (though I don't know what it should be yet).

File: packages/@aws-cdk/core/lib/asset-staging.ts (hunk 2 above)
Comment (jogold) [reply packages/@aws-cdk/core/lib/asset-staging.ts:247]: What do you mean here exactly? This is not a Docker performance issue here. It's the fact that we are fingerprinting the wrong directory.

If someone asks for a hash based on the bundle/output you currently change it to source if bundling is skipped. You introduced this in #11008. 

Before #11008, when bundling was skipped hash calculation was changed to CUSTOM.

It's a regression because we are now fingerprinting the source arbitrally and it could be a very large directory.

I agree that there should be a discussion around deferring bundling but how can we first fix this regression?

Comment (jogold) [reply packages/@aws-cdk/core/lib/asset-staging.ts:247]: A note on why the `NodejsFunction` uses `OUTPUT` as hash type and not `SOURCE`: it bundles not only the user's code but also all referenced node modules so it would be impractical to fingerprint the whole node modules folder. Moreover, we don't want to fingerprint .ts/.js files that represent the CDK infra code because this would incorrectly impact the hash of an asset representing runtime code.

**Comment by mrgrain** [comment]
I think you're right @rix0rrr about the need for a more generic solution to this. I have also noticed that Lambda Functions (maybe CodeAssets?) cause the asset to be staged every time a CDK command is run, whereas most other assets are cached and won't be run again if they exist already (or maybe it's got to do with the hash being different?).

In any case, I believe we have two regressions at the moment, which I tried to put into #11459 and #11646 

These come down to the current implementation for bundling:

- It ignores a custom asset hash.
- It prefers the source hash in an attempt to "speed" things up. However this is a very biased assumption and the best way to really speed things up would be using a static or options based hash. Alternatively I think no assumption should be made and the code should be bundled and use the output hash as one would expect.

In my opinion these are regressions that should be addresses asap before looking into a future solution.

**Comment by mrgrain** [comment]
> I'm starting to think we need an alternative approach here (though I don't know what it should be yet).
For anything using Node.js we can get around this mostly by using a source hash and ignore the `node_modules` directory. However the current version has deprecated the `exclude` option on some higher level asset related classes.

Generally speaking, I'm not sure we should make an assumption here for the user. If they decide to hash based on the output of a bundle, that's their decision. We could however provide a better interface to allow different hashing at various stages. I.e. leave it up to them to pick between OUTPUT (default), SOURCE, CUSTOM or even a function?

**Comment by jogold** [comment]
The problem is also present when doing `cdk synth STACK1 -e`.

File: packages/@aws-cdk/core/lib/asset-staging.ts (hunk 2 above)
Comment (rix0rrr) [reply packages/@aws-cdk/core/lib/asset-staging.ts:247]: No I mean, 

```ts
if (hashType === AssetHashType.OUTPUT || AssetHashType.BUNDLE) {
```

was probably intended to read:

```ts
if (hashType === AssetHashType.OUTPUT || hashType === AssetHashType.BUNDLE) {
```

**Review by rix0rrr — APPROVED** [review]

**Comment by jogold** [comment]
Merging master because this branch is too much behind it and gives incorrect API breaking changes

```
Updated assembly:  @aws-cdk/core@0.0.0
API elements with incompatible changes:
err  - METHOD @aws-cdk/core.Lazy.list: has been removed [removed:@aws-cdk/core.Lazy.list]
err  - IFACE @aws-cdk/core.IStableAnyProducer: has been removed [removed:@aws-cdk/core.IStableAnyProducer]
err  - IFACE @aws-cdk/core.IStableNumberProducer: has been removed [removed:@aws-cdk/core.IStableNumberProducer]
err  - IFACE @aws-cdk/core.IStableStringProducer: has been removed [removed:@aws-cdk/core.IStableStringProducer]
err  - PROP @aws-cdk/core.BootstraplessSynthesizer.DEFAULT_FILE_ASSET_PREFIX: has been removed [removed:@aws-cdk/core.BootstraplessSynthesizer.DEFAULT_FILE_ASSET_PREFIX]
err  - PROP @aws-cdk/core.DefaultStackSynthesizer.DEFAULT_FILE_ASSET_PREFIX: has been removed [removed:@aws-cdk/core.DefaultStackSynthesizer.DEFAULT_FILE_ASSET_PREFIX]
err  - METHOD @aws-cdk/core.Lazy.any: has been removed [removed:@aws-cdk/core.Lazy.any]
err  - IFACE @aws-cdk/core.IStableListProducer: has been removed [removed:@aws-cdk/core.IStableListProducer]
err  - METHOD @aws-cdk/core.Lazy.number: has been removed [removed:@aws-cdk/core.Lazy.number]
err  - METHOD @aws-cdk/core.Lazy.string: has been removed [removed:@aws-cdk/core.Lazy.string]
err  - METHOD @aws-cdk/core.Lazy.uncachedAny: has been removed [removed:@aws-cdk/core.Lazy.uncachedAny]
err  - METHOD @aws-cdk/core.Lazy.uncachedList: has been removed [removed:@aws-cdk/core.Lazy.uncachedList]
err  - METHOD @aws-cdk/core.Lazy.uncachedNumber: has been removed [removed:@aws-cdk/core.Lazy.uncachedNumber]
err  - METHOD @aws-cdk/core.Lazy.uncachedString: has been removed [removed:@aws-cdk/core.Lazy.uncachedString]
err  - PROP @aws-cdk/core.DefaultStackSynthesizerProps.bucketPrefix: has been removed [removed:@aws-cdk/core.DefaultStackSynthesizerProps.bucketPrefix]
```

**Review by rix0rrr — APPROVED** [review]
