### PR TITLE
fix(cloudwatch): don't ignore 'stacked' property in GraphWidget class

### LINKED ISSUE #2103: [aws-cloudwatch] fix: GraphWidgetProps contains "stacked" but it is not forwarded to the output
The stacked flag is in GraphWidgetProps but is not forwarded to the final object in ToJson();

https://github.com/awslabs/aws-cdk/blob/c968588fa18aadae65027628cbc6b4274247426f/packages/%40aws-cdk/aws-cloudwatch/lib/graph.ts#L144

### PR DESCRIPTION
**Pull request by loganek**
Stacked property was available and documented in the GraphWidget class, but it wasn't used for generating the cloudformation template. This change fixes the problem.

Fixes #2103

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-cloudwatch/lib/graph.ts [hunk 1]
```diff
@@ -181,6 +181,7 @@ export class GraphWidget extends ConcreteWidget {
         view: 'timeSeries',
         title: this.props.title,
         region: this.props.region || cdk.Aws.REGION,
+        stacked: this.props.stacked || false,
```
Comment (eladb) [inline packages/@aws-cdk/aws-cloudwatch/lib/graph.ts]: To preserve current behavior, we should not emit `stacked` if it's `false` since this is the default, so this should be sufficient I believe, correct?

```ts
stacked: this.props.stacked
```

File: packages/@aws-cdk/aws-cloudwatch/test/test.dashboard.ts [hunk 2]
```diff
@@ -85,7 +85,7 @@ export = {
       DashboardBody: { "Fn::Join": [ "", [
         "{\"widgets\":[{\"type\":\"metric\",\"width\":1,\"height\":1,\"x\":0,\"y\":0,\"properties\":{\"view\":\"timeSeries\",\"region\":\"",
         { Ref: "AWS::Region" },
-        "\",\"yAxis\":{}}}]}"
+        "\",\"stacked\":false,\"yAxis\":{}}}]}"
```
Comment (eladb) [inline packages/@aws-cdk/aws-cloudwatch/test/test.dashboard.ts]: revert

File: packages/@aws-cdk/aws-cloudwatch/test/test.dashboard.ts [hunk 3]
```diff
@@ -113,7 +113,7 @@ export = {
         "{\"start\":\"-9H\",\"end\":\"2018-12-17T06:00:00.000Z\",\"periodOverride\":\"inherit\",\
 \"widgets\":[{\"type\":\"metric\",\"width\":1,\"height\":1,\"x\":0,\"y\":0,\"properties\":{\"view\":\"timeSeries\",\"region\":\"",
         { Ref: "AWS::Region" },
-        "\",\"yAxis\":{}}}]}"
+        "\",\"stacked\":false,\"yAxis\":{}}}]}"
```
Comment (eladb) [inline packages/@aws-cdk/aws-cloudwatch/test/test.dashboard.ts]: revert

File: packages/@aws-cdk/aws-cloudwatch/test/test.graphs.ts [hunk 4]
```diff
@@ -54,6 +80,7 @@ export = {
         metrics: [
           ['CDK', 'Test', { yAxis: 'left', period: 300, stat: 'Average', label: 'MyMetric', color: '000000' }],
         ],
+        stacked: false,
```
Comment (eladb) [inline packages/@aws-cdk/aws-cloudwatch/test/test.graphs.ts]: revert

File: packages/@aws-cdk/aws-cloudwatch/test/test.graphs.ts [hunk 5]
```diff
@@ -155,6 +182,7 @@ export = {
           fill: 'below',
           label: 'this is the annotation',
         }] },
+        stacked: false,
```
Comment (eladb) [inline packages/@aws-cdk/aws-cloudwatch/test/test.graphs.ts]: revert

File: packages/@aws-cdk/aws-cloudwatch/test/test.graphs.ts [hunk 6]
```diff
@@ -197,6 +225,7 @@ export = {
             label: 'Test >= 1000 for 2 datapoints within 10 minutes',
           }]
         },
+        stacked: false,
```
Comment (eladb) [inline packages/@aws-cdk/aws-cloudwatch/test/test.graphs.ts]: revert

File: packages/@aws-cdk/aws-cloudwatch/test/test.graphs.ts [hunk 7]
```diff
@@ -239,6 +268,7 @@ export = {
           ['CDK', 'Test', { yAxis: 'left', period: 300, stat: 'Average' }],
           ['CDK', 'Tast', { yAxis: 'right', period: 300, stat: 'Average' }]
         ],
+        stacked: false,
```
Comment (eladb) [inline packages/@aws-cdk/aws-cloudwatch/test/test.graphs.ts]: revert

File: packages/@aws-cdk/aws-cloudwatch/lib/graph.ts (hunk 1 above)
Comment (loganek) [reply packages/@aws-cdk/aws-cloudwatch/lib/graph.ts]: That's correct, changed it.
