### PR TITLE
fix(core): unable to reference resources across multiple nested stacks

### LINKED ISSUE #5888: NestedStack parent resource reference generates Circular Dependency
I have the following stack structure:
```
Root(Stack) => AppSync(NestedStack) => Resolvers(NestedStack)
```
In `AppSync(NestedStack)` I am creating API, schema and instantiating nested stack for Resolvers, main reason for this this that there are many resolvers and to not hit 200 Resrouce limit I will be manually splitting resources between multiple Resolvers nested stack. Currently I don't know an automated way for splitting resources, if there is please, please share :).

I also tried changing the structure to have nested stacks as siblings, which get's rid of Circular dependency but then it just fails on deploy:
```
Root(Stack) => AppSync(NestedStack) => ApiStack(NestedStack)
                                    => Resolvers(NestedStack)
```
```
creating CloudFormation changeset...
 0/3 | 2:07:56 PM | CREATE_IN_PROGRESS   | AWS::CDK::Metadata         | CDKMetadata
 0/3 | 2:07:56 PM | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack | appsync-bizon.NestedStack/appsync-bizon.NestedStackResource (appsyncbizonNestedStackappsyncbizonNestedStackResource814A53CF)
 0/3 | 2:07:57 PM | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack | appsync-bizon.NestedStack/appsync-bizon.NestedStackResource (appsyncbizonNestedStackappsyncbizonNestedStackResource814A53CF) Resource creation Initiated
 0/3 | 2:07:58 PM | CREATE_IN_PROGRESS   | AWS::CDK::Metadata         | CDKMetadata Resource creation Initiated
 1/3 | 2:07:58 PM | CREATE_COMPLETE      | AWS::CDK::Metadata         | CDKMetadata
 2/3 | 2:08:19 PM | CREATE_FAILED        | AWS::CloudFormation::Stack | appsync-bizon.NestedStack/appsync-bizon.NestedStackResource (appsyncbizonNestedStackappsyncbizonNestedStackResource814A53CF) Embedded stack arn:aws:cloudformation:eu-west-2:452364846299:stack/ProductName-bizon-appsyncbizonNestedStackappsyncbizonNestedStackResource814A53CF-4NAE12ZLOQGT/a92a4b40-3c46-11ea-9fec-06452e71541c was not successfully created: The following resource(s) failed to create: [dynamodbstackbizonNestedStackdynamodbstackbizonNestedStackResource0AACEAF0, productnameresolversNestedStackproductnameresolversNestedStackResource42DF9B6A].
```

### Reproduction Steps

**cdk.ts**:
```
new RootStack(app, getResourceName(PRODUCT_NAME), {
  tags: TAGS
});
```

**root-stack.ts**:
```
new AppSyncStack(this, getResourceName('appsync'));
```

**appsync-stack.ts**
```
  export class AppSyncStack extends cfn.NestedStack {
  public readonly api: CfnGraphQLApi;
  public readonly schema: CfnGraphQLSchema;

  constructor(scope: cdk.Construct, id: string, props?: cfn.NestedStackProps) {
    super(scope, id, props);

    this.api = this.create();
    this.schema = this.createSchema();
    this.createTable();
    this.createResolvers();
  }

  private create(): CfnGraphQLApi {
    const name = getResourceName(`${getProductName()}-appsync`);
    return new CfnGraphQLApi(this, name, {
      name,
      authenticationType: 'AMAZON_COGNITO_USER_POOLS',
      additionalAuthenticationProviders: [{
        authenticationType: 'API_KEY'
      }]
    });
  }

  private createSchema(): CfnGraphQLSchema {
    return new CfnGraphQLSchema(this, getResourceName(`${getProductName()}-schema`), {
      apiId: this.api.attrApiId,
      definition: fs.readFileSync(SCHEMA_FILE_PATH).toString()
    });
  }

  private createTable(): void {
    // tslint:disable-next-line:no-unused-expression
    new DynamoDbStack(this, getResourceName('dynamodb-stack'));
  }

  private createResolvers(): void {
    // tslint:disable-next-line:no-unused-expression
    new ResolversStack(this, getResourceName(`${getProductName()}-resolvers`),{
      parameters: {
        apiId: this.api.attrApiId
      }
    });
  }
}
```

**resolvers-stack**:
```
new CfnResolver(this, name, {
  typeName,
  fieldName,
  requestMappingTemplate,
  responseMappingTemplate,
  apiId: this.props?.parameters?.apiId || '',
});
```

### Error Log

```
creating CloudFormation changeset...

 ❌  ProducName-bizon failed: ValidationError: Circular dependency between resources: [appsyncbizonNestedStackappsyncbizonNestedStackResource814A53CF]
Circular dependency between resources: [appsyncbizonNestedStackappsyncbizonNestedStackResource814A53CF]
```

**CFN template generates reference to itself(root-stack.template)**:
```
"appsyncbizonNestedStackappsyncbizonNestedStackResource814A53CF": {
      "Type": "AWS::CloudFormation::Stack",
      "Properties": {
        ...
        },
        "Parameters": {
          "referencetoProductNamebizonappsyncbizonproductnameappsyncbizon6498FF74ApiId": {
            "Fn::GetAtt": [
              "appsyncbizonNestedStackappsyncbizonNestedStackResource814A53CF",
              "Outputs.ProuctNamebizonappsyncbizonproductnameappsyncbizon6498FF74ApiId"
            ]
          },
```
**appsync-stack.template**:
```
"productnameresolversbizonNestedStackproductnameresolversbizonNestedStackResource7E007811": {
      "Type": "AWS::CloudFormation::Stack",
      "Properties": {
        ...
        },
        "Parameters": {
          "apiId": {
            "Fn::GetAtt": [
              "productnameappsyncbizon",
              "ApiId"
            ]
          }
        }
      .....
      "Outputs": {
    "ProductNamebizonappsyncbizonprodcutnameappsyncbizon6498FF74ApiId": {
      "Value": {
        "Fn::GetAtt": [
          "productnameappsyncbizon",
          "ApiId"
        ]
      }
    }
  }
```

**resolvers-stack.template**:
```
{
  "Resources": {
    "AreaprimaryContact": {
      "Type": "AWS::AppSync::Resolver",
      "Properties": {
        "ApiId": {
          "Ref": "referencetoProductNamebizonappsyncbizonproductnameappsyncbizon6498FF74ApiId"
        },
        "FieldName": "primaryContact",
        "TypeName": "Area",
        "RequestMappingTemplate": "\n\n#set( $customerId = $context.identity.claims.get(\"custom:customer\") )\n#if( $util.isNullOrEmpty($customerId) )\n  #set( $customerId = \"mydev\" )\n#end\n    \n#set( $pk = \"Person#$customerId\" )\n#set( $sk = \"Person#$customerId#$ctx.source.ownerId\" )\n{\n    \"version\": \"2017-02-28\",\n    \"operation\": \"GetItem\",\n    \"key\": {\n        \"pk\": $util.dynamodb.toDynamoDBJson($pk),\n        \"sk\": $util.dynamodb.toDynamoDBJson($sk)\n    }\n}\n    ",
        "ResponseMappingTemplate": "\n$util.toJson($ctx.result)\n    "
      },
      "Metadata": {
        "aws:cdk:path": "ProductName-bizon/appsync-bizon/productname-resolvers-bizon/Area.primaryContact"
      }
    }
  }
}
```

### Environment

  - **CLI Version: 1.21.0**
  - **Framework Version:**
  - **OS: Windows**
  - **Language: Typescript**

### Other

--- 

This is :bug: Bug Report

### LINKED ISSUE #6473: Unable to reference resources across multiple levels of nested stacks
### Minimal repro

```ts
const top = new Stack();
const topLevel = new CfnResource(top, 'toplevel', { type: 'TopLevel' });
const nested1 = new NestedStack(top, 'nested1');
const nested2 = new NestedStack(nested1, 'nested2');

new CfnResource(nested2, 'refToTopLevel', {
  type: 'BottomLevel',
  properties: { RefToTopLevel: topLevel.ref }
});
```

### Original issue

I'm trying to create an EKS Cluster on a NestedStack.

I have all my dependencies separated in NestedStacks (VPC, LoadBalancer, Services). So, it makes sense to have a NestedStack to create my EKS Cluster.

The EKS Cluster can be included in a Main Stack, but not on a Nested. When the EKS Cluster is on a Nested Stack, the cdk gives me the follow error:
```
jsii.errors.JSIIError: Nested stack 'eks-test/EksCluster' cannot depend on a parent stack 'eks-test'
```

### Reproduction Steps

- Create a sample app using the cdk
- Create a NestedStack including an eks cluster
- Try to synth

### Error Log
```
(.env) ⋊> ~/P/s/eks_test on master ⨯ cdk synth                                                                                                                                                                                      [18:46:48]
jsii.errors.JavaScriptError:
  Error: Nested stack 'eks-test/EksCluster' cannot depend on a parent stack 'eks-test'
      at Object.addDependency (/private/var/folders/w2/t7tdyk5576q1k8kqyjg2ndhh0000gp/T/jsii-kernel-r9YaoT/node_modules/@aws-cdk/core/lib/deps.js:57:15)
      at NestedStack.addDependency (/private/var/folders/w2/t7tdyk5576q1k8kqyjg2ndhh0000gp/T/jsii-kernel-r9YaoT/node_modules/@aws-cdk/core/lib/stack.js:200:16)
      at KubectlProvider.prepareCrossReference (/private/var/folders/w2/t7tdyk5576q1k8kqyjg2ndhh0000gp/T/jsii-kernel-r9YaoT/node_modules/@aws-cdk/core/lib/stack.js:692:28)
      at KubectlProvider.prepareCrossReference (/private/var/folders/w2/t7tdyk5576q1k8kqyjg2ndhh0000gp/T/jsii-kernel-r9YaoT/node_modules/@aws-cdk/aws-cloudformation/lib/nested-stack.js:111:26)
      at KubectlProvider.prepare (/private/var/folders/w2/t7tdyk5576q1k8kqyjg2ndhh0000gp/T/jsii-kernel-r9YaoT/node_modules/@aws-cdk/core/lib/stack.js:560:43)
      at Function.prepare (/private/var/folders/w2/t7tdyk5576q1k8kqyjg2ndhh0000gp/T/jsii-kernel-r9YaoT/node_modules/@aws-cdk/core/lib/construct.js:87:27)
      at Function.synth (/private/var/folders/w2/t7tdyk5576q1k8kqyjg2ndhh0000gp/T/jsii-kernel-r9YaoT/node_modules/@aws-cdk/core/lib/construct.js:51:14)
      at App.synth (/private/var/folders/w2/t7tdyk5576q1k8kqyjg2ndhh0000gp/T/jsii-kernel-r9YaoT/node_modules/@aws-cdk/core/lib/app.js:71:52)
      at _wrapSandboxCode (/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7665:51)
      at Kernel._wrapSandboxCode (/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8301:19)
      at ret._ensureSync (/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7665:25)
      at Kernel._ensureSync (/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8274:20)
      at Kernel.invoke (/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7664:26)
      at KernelHost.processRequest (/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7372:28)
      at KernelHost.run (/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7312:14)
      at Immediate.setImmediate [as _onImmediate] (/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7315:37)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 13, in <module>
    app.synth()
  File "/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/aws_cdk/core/__init__.py", line 3585, in synth
    return jsii.invoke(self, "synth", [])
  File "/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 113, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 288, in invoke
    args=_make_reference_for_native(self, args),
  File "/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 348, in invoke
    return self._process.send(request, InvokeResponse)
  File "/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Nested stack 'eks-test/EksCluster' cannot depend on a parent stack 'eks-test'
Subprocess exited with error 1
```

### Environment

  - **CLI Version      : 1.26.0 (build e251651)**
  - **Framework Version: 1.26.0**
  - **OS               : MacOS Catalina**
  - **Language         : python**

### Other

For more information I create the public repository [rzamana/cdk_eks_tests](https://github.com/rzamana/cdk_eks_tests)

--- 

This is :bug: Bug Report

### LINKED ISSUE #7059: Nested stacks template will not be republished when a reference is added/updated
When a user creates a NestedStack that reference a property in a sibling NestedStack, e.g:
```
                            +--------+                 
                       +----| Parent |-------+         
                       |    +--------+       |         
                       |                     |         
                       |                     |         
                       v                     v  
                +------------+      +------------------+
                |  Nested1   |      |     Nested2      |
                |            |      |                  |
                | Producer   |      |     Consumer     |
                | SNSTopic   |      |   Ref:SNSTopic   |
                +------------+      +------------------+
```

The CDK will create an output of the property, the Topic in the picture, on the producer stack. And the corresponding parameter on the consumer stack.
The outputs and parameters are created in the `prepare` phase of the CDK. In this phase, `prepare` is called on every construct in the tree, from leaves to root, ensuring that when a construct is being "prepared" it has all the knowledge it needs since all of its children have already been "prepared". 
Since sibling nested stacks does not have a parent-child dependency it is not guaranteed  that the consumer stack will be prepared before the producer stack,  the order is dependent on the order in which the children array is processed.

Nested stack templates are uploaded to S3 using the CDK assets mechanism. In order to avoid uploading an unchanged assets, a hash is calculate for each asset and is used as the object key in S3. The hash is calculated differently for every type of assets.  For CloudFormation templates, the hash is calculated based on all the template elements, including outputs and parameters, ensuring that every change to the template will result in a new file uploaded to S3. 
The nested stack template file hash is calculated in the stack `prepare` method:
```typescript 
    if (this.nestedStackParent) {
      // add the nested stack template as an asset
      const cfn = JSON.stringify(this._toCloudFormation());
      const templateHash = crypto.createHash('sha256').update(cfn).digest('hex');
      const parent = this.nestedStackParent;
      const templateLocation = parent.addFileAsset({
        packaging: FileAssetPackaging.FILE,
        sourceHash: templateHash,
        fileName: this.templateFile
      });
```   
> [full code](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/core/lib/stack.ts#L790)

In the consumer producer example, the outputs and parameters on the respective stacks will be created when `prepare` is called on the consumer stack (the consumer stack is the one that needs the reference). This means that if the producer stack is prepared before the consumer stack, when the hash of the producer template file is calculated, it will not include the output, which means that the updated template will not be uploaded to S3, resulting in deployment failure.
Simply put, the hash is not calculated on the final template.

To traverse the tree from leaves to root in the prepare phase we create the topological sorting of the tree using:
```typescript
root.findAll(ConstrcutOrder.Preorder).reverse()
```
> [code](https://github.com/aws/constructs/blob/master/lib/construct.ts)

Which means that the children in each level of the tree are processed from right to left. 
Given the way the children are stored on the parent node and `get children()` [implementation](https://github.com/aws/constructs/blob/master/lib/construct.ts#L169), the right to left order of the children array is  **opposite** to the order in which the children were added to the node(1), which means that this code:
```typescript
const producer = new ProducerNestedStack(this, 'Nested1');
const consumer =  new ConsumerNestedStack(this, 'Nested2', producer.topic);
```
Will result in the consumer stack being "prepared" before the producer stack.
Luckily, although not required, in most cases when referencing a property between resources, the producer resource will be created (and added to the children array) before the consumer resource. When the producer is created before the consumer the current logic works.
> The producer resource **must exist** when the reference is added to the consumer resource but this does not implies anything on the creations order, for example: 
> 
>```typescript
>consumer =  new ConsumerNestedStack(this, 'Nested2');
>producer = new ProducerNestedStack(this, 'Nested1');
> consumer.topic = producer.topic;
>```
>
 
### So how did this suddenly break?

 
As apart of the fix in https://github.com/aws/constructs/pull/23, the topological sorting was changed from: 

```typescript
root.findAll(ConstrcutOrder.Preorder).reverse()
```
To:

```typescript
root.findAll(ConstrcutOrder.Postorder)
```
Resulting in the children array processing order to change from right->left to left->right, causing the producer to be prepared before the consumer, breaking(2) the nested stacks [integ test](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-cloudformation/test/integ.nested-stacks-refs3.ts). 
Since this change in the constructs module broke the CDK integ test we reverted the change and kept the original order. 

(1) We store the children in a map based on their id (string), and retrieve the actual constructs using `Object.values(children)` which returns string keys in the order in which they were added to the object (see [reference](https://2ality.com/2015/10/property-traversal-order-es6.html#traversing-the-own-keys-of-an-object)) 
(2) The integration test only fail because it was run as part of an integration test suite. The test suite that includes a test which produces the same template as the one produced by the test that fail, **minus the outputs element**. This resulted in the template with the outputs not being uploaded, failing the deployment. If the test was run independently, it would have passed :/ (AI, more extensive integ test for assets?)

### PR DESCRIPTION
**Pull request by eladb**
### Commit Message
fix(core): unable to reference resources across multiple nested stacks (#7187) 

Fixes #6473 by centralizing the logic to resolve cross-references and prepare nested stack template assets in `App.prepare`, which has a global view of the app and is the last prepare to execute before synthesis. This dramatically simplified reference resolution and allows dealing with nested stack assets only after all cross references have been resolved (the root cause for #7059).

This logic is implemented in a function called `prepareApp` which is normally called from `App.prepare()` but if a `Stack` is created as a root (normally in unit tests, we invoke this logic from there to retain current behavior).

This algorithm takes care of both resolving cross references and add template assets for nested stacks. This is because assets are currently addressed using CFN parameters, which means that when we adding them to the parent of a nested stack, the parent is mutated, so we need to rectify references again. To make sure this is done correctly, we always create assets in DFS order.

All changes to the test snapshots stem from new asset IDs of nested stack templates, not the template themselves. The change is a result of the fact that the refactor caused the "Parameters" section to appear in a different place in the template, but the template itself is identical.

Fixes #7059 by first resolving all references in the app and only then calculating the hash of the nested stack templates for their assets.

Fixes #5888 but this was not verified.

### End Commit Message

TODO:

- [x] Validate: https://github.com/aws/aws-cdk/issues/7059
- [x] Verify DDB Global is not a breaking change

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/core/lib/private/refs.ts [hunk 1]
```diff
@@ -0,0 +1,276 @@
...
+  // ----------------------------------------------------------------------
+  // export/import
+  // ----------------------------------------------------------------------
+
+  // export the value through a cloudformation "export name" and use an
+  // Fn::ImportValue in the consumption site.
+
+  // delcare a dependency between the two top-level (non-nested) stacks to make
+  // sure the producer is deployed before the consumer.
+  const producerDep = producer.nestedStackParent ?? producer;
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/private/refs.ts:100]: Bug? What is `.nestedStackParent` is a nested stack? We need to find the top level!

File: packages/@aws-cdk/core/lib/private/refs.ts [hunk 2]
```diff
@@ -0,0 +1,276 @@
...
+
+  // ----------------------------------------------------------------------
+  // consumer is nested in the producer (directly or indirectly)
+  // ----------------------------------------------------------------------
+
+  // if the consumer is a child of the producer, wire the reference through a
+  // CloudFormation parameter on the consumer and resolve recursively.
+  if (isParent(producer, consumer)) {
+    const parameterValue = createNestedStackParameter(consumer, reference);
+    return resolveValue(consumer, parameterValue);
```
Comment (NetaNir) [inline packages/@aws-cdk/core/lib/private/refs.ts:69]: Im missing something here, when will this call result in an actual recursion, the `parameterValue` is always defined on the on the consumer so this call will always result in:
```typescript
 if (producer === consumer) {
    return reference;
  }
```
https://github.com/aws/aws-cdk/pull/7187/files#diff-ce0a307ecd3c9f405ff4510a2516fd13R45

File: packages/@aws-cdk/core/lib/private/refs.ts [hunk 3]
```diff
@@ -0,0 +1,276 @@
...
+
+  // ----------------------------------------------------------------------
+  // producer is a nested stack
+  // ----------------------------------------------------------------------
+
+  // if the producer is nested, always publish the value through a
+  // cloudformation output and resolve recursively with the Fn::GetAtt
+  // of the output in the parent stack.
+
+  // one might ask, if the consumer is not a parent of the producer,
```
[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/core/lib/private/refs.ts:80]: The problem would be how to synthesize the import side. We will need to somehow propagate the nested stack’s name to the consumer, so we might as well just propagate the actual value.

File: packages/@aws-cdk/core/lib/private/refs.ts [hunk 4]
```diff
@@ -0,0 +1,276 @@
...
+/**
+ * @returns true if this stack is a direct or indirect parent of the nested
+ * stack `nested`.
+ *
+ * If `child` is not a nested stack, always returns `false` because it can't
+ * have a parent, dah.
+ */
+export function isParent(parent: Stack, child: Stack): boolean {
+  // if "nested" is not a nested stack, then by definition we cannot be its parent
+  if (!child.nestedStackParent) {
```
[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/core/lib/private/refs.ts:265]: This is required because it is the stopping condition for when the child is *not* a descendent of this parent. Maybe I should reverse the order of the stopping conditions so it will read cleaner:

- If `child.parent === parent` return true
- If `child.parent == null` return false
- otherwise, recurse with `child.parent` as the child

Makes more sense?

[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/core/lib/private/refs.ts:265]: I also renamed this to `isNested` and reversed the order so it's `isNested(child, parent)`. I hope that's a bit clearer.

File: packages/@aws-cdk/core/lib/private/refs.ts (hunk 2 above)
Comment (eladb) [reply packages/@aws-cdk/core/lib/private/refs.ts:69]: If we have multiple levels of nesting (i.e. the producer is not a direct parent of the consumer), we will need to create a parameter in each parent until we eventually reach the producer.

Comment (NetaNir) [reply packages/@aws-cdk/core/lib/private/refs.ts:70]: Since we don't change the consumer when we call the recursion we will not climb up the tree to get to the LSA.
I think that the reason this  pass tests is due to the reference being added on the nestedStack resource in the parent in `createNestedStackParameter`. Since the added assets triggers another round of `resolveReferences` while will resolve the added reference

File: packages/@aws-cdk/core/lib/private/refs.ts (hunk 1 above)
Comment (NetaNir) [reply packages/@aws-cdk/core/lib/private/refs.ts:101]: Will `producer.nestedStackParent` ever be `true`? 
In line 87 we handle `producer.nested` case

File: packages/@aws-cdk/core/lib/private/refs.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (NetaNir) [reply packages/@aws-cdk/core/lib/private/refs.ts:81]: There is one caveat to this, when the consumer stack and the producer stack are not in the same nested stack group, we must use export/import. We can create the export on the nested stack or on the root stack. Stacks have output/export limits,  If all are submitted on the root stack we are `wasting` outputs/export on the root stack. (disclaimer: the hard limit for outputs is 150 so one may argue this does not really matter)

[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/core/lib/private/refs.ts:81]: We will still need to somehow export the nested stack’s name from the top level stack, so this still uses at least one export for each nested stack and rather complicates the scheme so I prefer not to prematurely optimize this. We can introduce this later if there is a strong use case, right?

File: packages/@aws-cdk/core/lib/private/refs.ts (hunk 1 above)
Comment (NetaNir) [reply packages/@aws-cdk/core/lib/private/refs.ts:101]: If you meant the consumer, then yes, I think there is a bug here. 
The only thing we know about the consumer is that it's not a child of the producer, but it can still be a nested stack which means we need to bubble the parameter up.

File: packages/@aws-cdk/core/lib/private/refs.ts (hunk 2 above)
Comment (eladb) [reply packages/@aws-cdk/core/lib/private/refs.ts:70]: Yes I think you are correct that the recursive call will always stop immediately by returning the `parametetValue`. Let me clean this up.

File: packages/@aws-cdk/core/lib/private/refs.ts (hunk 1 above)
Comment (eladb) [reply packages/@aws-cdk/core/lib/private/refs.ts:101]: This is not about the parameter, it’s about the dependency, but yes. 

I actually want to move the dependency resolution logic to `app.prepare` loop as well, so I can simply specify the dependencies between the two nodes and the dep resolution logic will take care of the rest. But I will do it in a subsequent PR once this is merged.

Comment (NetaNir) [reply packages/@aws-cdk/core/lib/private/refs.ts:101]: I think this will happen on the consumer though. All we know on the consumer is that **it is not a child of the producer**, but it still can be a nested stack which means we need to create the dependency on its root parent.

File: packages/@aws-cdk/core/lib/private/refs.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (NetaNir) [reply packages/@aws-cdk/core/lib/private/refs.ts:81]: Wouldn't it be a breaking change?  Exports can't be moved.

File: packages/@aws-cdk/core/lib/private/refs.ts (hunk 2 above)
Comment (eladb) [reply packages/@aws-cdk/core/lib/private/refs.ts:70]: Fixed.

File: packages/@aws-cdk/core/lib/private/refs.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/core/lib/private/refs.ts:81]: Yes, you are correct. It will be a breaking change, and we can introduce under a feature flag if this will ever be an issue. 

Do you think it's worth the added complexity (and bugs that come with it)?

File: packages/@aws-cdk/core/lib/private/refs.ts (hunk 1 above)
Comment (eladb) [reply packages/@aws-cdk/core/lib/private/refs.ts:101]: Yes, you are right. At any rate I changed this to:

```ts
const producerDep = findTopLevel(producer);
const consumerDep = findTopLevel(consumer);
```

So we always define the dependency between the top-level stacks.

Comment (eladb) [reply packages/@aws-cdk/core/lib/private/refs.ts:101]: Okay this can be even simpler because `stack.addDependency` has all the logic to handle nested stacks already, so this became `consumer.addDependency(producer)`. yey!

File: packages/@aws-cdk/core/lib/private/refs.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (rix0rrr) [reply packages/@aws-cdk/core/lib/private/refs.ts:79]: Based on intuition alone, I strongly prefer the "all communication with the outside world goes through the top-level stack" version.

Feels more manageable/locally correct/verifiable... otherwise I'm getting visions of global variables.

Now, this might all be superstition and it's not really based on arguments. As I said it's just intuition.

[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/core/lib/private/refs.ts:79]: This is how it’s implemented. The value is outputted from the nested stack and will propagate all the way to the top before it is exported to the outside world.

**Comment by eladb** [comment]
> I'm fuzzy on the details, but when we were last discussion this you had a:
> 
> 
> 
> ```
> 
> while (!stable) {
> 
>   for each (stabilizableThing) {
> 
>     if (!stabilizableThing.alreadyDidIt) { 
> 
>       stabilizableThing.doit();
> 
>     }
> 
>   }
> 
> }
> 
> ```
> 
> 
> 
> loop, and we figured out it there were cases it wouldn't be good enough (depending on sibling ordering, I believe).
> 
> 
> 
> I still see much the same structure in the current solution. Is the objection we had then not true anymore?

The important order is that assets are added depth-first so that parameters can be resolved and that’s how it’s explicitly implemented here.

Unless I missed something again ?

**Comment by rix0rrr** [comment]
> Unless I missed something again ?

Ah, no, that's right. I think last time we discussed this we had an arbitrary order between stacks. Or maybe even top-down.

As long as no parent pushes down values into its childs, we should be fine.

BTW, is it worth locking the NestedStack subtree using `construct.node.lock()`? At least that would protect against most "naive" attempts at post-stabilization modifications, and may help us catch bugs?

**Comment by eladb** [comment]
> BTW, is it worth locking the NestedStack subtree using `construct.node.lock()`? At least that would protect against most "naive" attempts at post-stabilization modifications, and may help us catch bugs?

Nothing runs after `app.prepare()` (besides synthesis), and we don't run any arbitrary code in there, so I am not sure what would be the value in locking...

**Comment by eladb** [comment]
@rix0rrr let me know if you have additional notes here

File: packages/@aws-cdk/core/lib/private/refs.ts (hunk 2 above)
Comment (NetaNir) [reply packages/@aws-cdk/core/lib/private/refs.ts]: Just to make sure I get it, we removed the recursion because we rely on `createNestedStackParameter ` to trigger another round of resolve?

Comment (NetaNir) [reply packages/@aws-cdk/core/lib/private/refs.ts]: Here is what I find unintuitive in the current code. Assume we have the following stacks structure:
```
              A (Root)
              |
              B (Nested)
              |
              C (Nested)
```
Stack C references a resource in stack A, which requires wiring the parameter from A all the way down to C.  Since we don't recurse when creating the parameter on the consumer, the first round of `resolveReferences` will not create the required parameter on B (it will only create the parameter in C's template and the parameter on the respective  NestedStack resource in B). The required parameter on B will only be created on the subsequent round of `resolveReferences` which is only triggered due to `defineNestedStackAssets` returning true. This works, however, it's not intuitive. `defineNestedStackAssets` logic and name implies it will trigger only the resolution of asset references but its return result is relied upon to trigger the resolving of other references. In the above examples, B's parameters are created as a result of this side effect. For example one might see this code:
```typescript 
while (more) {
  resolveReferences(root);
  more = defineNestedStackAssets(nestedStacks);
}
```

And change it to:

```typescript
resolveReferences(root);
while (more) {
  more = defineNestedStackAssets(nestedStacks);
}
```

As the coupling between methods is not clear from their names or the `more` parameter name. 
Since this works due to the DFS order in which we process nestedStacks we can keep the code but maybe we should change the flag name to be more intuitive, e.g `moreResolveRequired`.

**Comment by NetaNir** [comment]
@eladb I added one comment which is more a style issue, other than that, looks great.

File: packages/@aws-cdk/core/lib/private/refs.ts (hunk 2 above)
Comment (eladb) [reply packages/@aws-cdk/core/lib/private/refs.ts]: It’s a good point. Let me see if I can improve.

**Comment by eladb** [comment]
@NetaNir made some updates following your comments. What do you think?

**Comment by NetaNir** [comment]
@eladb the changes to the main loop looks great. 

Could the loop in `resolveReferences` be replaced with a recursive call in `resolveValue`?  Similarly to the first version of this PR?

```typescript
// complier does not like consumer.parentStack type, hacking it for the code sample
if (consumer.parentStack && isNested(consumer, producer)) {
    const param =  createNestedStackParameter(consumer, reference);
    resolveValue(consumer.parentStack, reference);
    return param;
 }
```
Since we know that `createNestedStackParameter` only creates unresolved references on the parent stack we can resolve them immediately.

**Comment by eladb** [comment]
> Could the loop in `resolveReferences` be replaced with a recursive call in `resolveValue`?  Similarly to the first version of this PR?

@NetaNir what’s the reason you think this would be better? Do you see an issue with the current version?

**Comment by eladb** [comment]
Okay @NetaNir last iteration. I think you’ll like it.
