### PR TITLE
fix(stepfunctions): prefixes not appended to states in parallel branches

### LINKED ISSUE #17354: (aws_stepfunctions): Parallel inside StateMachineFragment causes validation errors
### What is the problem?

If a StateMachineFragment contains a Parallel state (with at least one branch) and that StateMachineFragment is used multiple times in a state machine (using StateMachineFragment.prefix_states()), then an error is raised when the stack is synth'd. Example error:
`jsii.errors.JSIIError: State with name 'DoThing1' occurs in both Parallel 'InnerParallelState' branch 1 (Prefix1DoThing1) and Parallel 'InnerParallelState' branch 1 (Prefix2DoThing1). All states must have unique names.`
Judging by the error, it might be some sort of ordering issue, since the prefixes have been correctly applied in the error text.

### Reproduction Steps

```python
    from typing import List
    from aws_cdk import Stack
    from constructs import Construct
    import aws_cdk as cdk
    from aws_cdk import aws_stepfunctions as sfn
    
    
    class SubMachine(sfn.StateMachineFragment):
        def __init__(
            self,
            scope: Construct,
            construct_id: str,
        ) -> None:
            super().__init__(scope, construct_id)
    
            do_thing_1 = sfn.Pass(self, "DoThing1")
            do_thing_2 = sfn.Pass(self, "DoThing2")
    
            parallel_state = sfn.Parallel(self, "InnerParallelState")
    
            chain = parallel_state.branch(do_thing_1).branch(do_thing_2)
            self._start_state: sfn.State = parallel_state
            self._end_states: List[sfn.INextable] = [chain]
    
        @property
        def start_state(self) -> sfn.State:
            return self._start_state
    
        @property
        def end_states(self) -> List[sfn.INextable]:
            return self._end_states
    
    
    class CdkTestStack(Stack):
        def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
            super().__init__(scope, construct_id, **kwargs)
    
            chain = (
                SubMachine(self, "SubMachine1").prefix_states("Prefix1")
                .next(SubMachine(self, "SubMachine2").prefix_states("Prefix2"))
            )
    
            machine = sfn.StateMachine(self, "Machine", definition=chain)
    
    
    app = cdk.App()
    CdkTestStack(app, "CdkTestStack")
    
    app.synth()
```

Code is collapsed into one file for the sake of verifying the bug. The bug occurs whether do_thing_2 is included or not (i.e. it doesn't seem to matter how many branches the Parallel state has).

### What did you expect to happen?

The stack to successfully synth, and produce a state machine that runs DoThing1 and DoThing2 in parallel two times.

### What actually happened?

An execption is raised when running `cdk synth` or executing the file with python.
Error message:

```sh
    jsii.errors.JSIIError: State with name 'DoThing1' occurs in both Parallel 'InnerParallelState' branch 1 (Prefix1DoThing1) and Parallel 'InnerParallelState' branch 1 (Prefix2DoThing1). All states must have unique names.
```

### CDK CLI Version

2.0.0-rc.27 (build 435e6f6)

### Framework Version

Tested on 2.0.0rc24 and 2.0.0rc27

### Node.js Version

v14.16.1

### OS

Windows 10

### Language

Python

### Language Version

Python (3.9.7)

### Other information

Stack trace:

```sh
    jsii.errors.JavaScriptError: 
      Error: State with name 'DoThing1' occurs in both Parallel 'InnerParallelState' branch 1 (Prefix1DoThing1) and Parallel 'InnerParallelState' branch 1 (Prefix2DoThing1). All states must have unique names.
          at StateGraph.registerContainedState (C:\Users\chghea\AppData\Local\Temp\jsii-kernel-72It7f\node_modules\aws-cdk-lib\lib\aws-stepfunctions\lib\state-graph.js:136:23)
          at StateGraph.pushContainedStatesUp (C:\Users\chghea\AppData\Local\Temp\jsii-kernel-72It7f\node_modules\aws-cdk-lib\lib\aws-stepfunctions\lib\state-graph.js:146:24)
          at StateGraph.registerSuperGraph (C:\Users\chghea\AppData\Local\Temp\jsii-kernel-72It7f\node_modules\aws-cdk-lib\lib\aws-stepfunctions\lib\state-graph.js:95:14)
          at Parallel.bindToGraph (C:\Users\chghea\AppData\Local\Temp\jsii-kernel-72It7f\node_modules\aws-cdk-lib\lib\aws-stepfunctions\lib\states\state.js:175:20)
          at new StateGraph (C:\Users\chghea\AppData\Local\Temp\jsii-kernel-72It7f\node_modules\aws-cdk-lib\lib\aws-stepfunctions\lib\state-graph.js:54:20)
          at new StateMachine (C:\Users\chghea\AppData\Local\Temp\jsii-kernel-72It7f\node_modules\aws-cdk-lib\lib\aws-stepfunctions\lib\state-machine.js:271:23)
          at C:\Users\chghea\AppData\Local\Temp\tmpjigtgzu4\lib\program.js:8432:58
          at Kernel._wrapSandboxCode (C:\Users\chghea\AppData\Local\Temp\tmpjigtgzu4\lib\program.js:8860:24)
          at Kernel._create (C:\Users\chghea\AppData\Local\Temp\tmpjigtgzu4\lib\program.js:8432:34)
          at Kernel.create (C:\Users\chghea\AppData\Local\Temp\tmpjigtgzu4\lib\program.js:8173:29)
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "C:\Users\chghea\PycharmProjects\CdkTest\cdk_test\cdk_test_stack.py", line 47, in <module>
        CdkTestStack(app, "CdkTestStack")
      File "C:\Users\chghea\PycharmProjects\CdkTest\.venv\lib\site-packages\jsii\_runtime.py", line 86, in __call__
        inst = super().__call__(*args, **kwargs)
      File "C:\Users\chghea\PycharmProjects\CdkTest\cdk_test\cdk_test_stack.py", line 43, in __init__
        machine = sfn.StateMachine(self, "Machine", definition=chain)
      File "C:\Users\chghea\PycharmProjects\CdkTest\.venv\lib\site-packages\jsii\_runtime.py", line 86, in __call__
        inst = super().__call__(*args, **kwargs)
      File "C:\Users\chghea\PycharmProjects\CdkTest\.venv\lib\site-packages\aws_cdk\aws_stepfunctions\__init__.py", line 5595, in __init__
        jsii.create(self.__class__, self, [scope, id, props])
      File "C:\Users\chghea\PycharmProjects\CdkTest\.venv\lib\site-packages\jsii\_kernel\__init__.py", line 290, in create
        response = self.provider.create(
      File "C:\Users\chghea\PycharmProjects\CdkTest\.venv\lib\site-packages\jsii\_kernel\providers\process.py", line 344, in create
        return self._process.send(request, CreateResponse)
      File "C:\Users\chghea\PycharmProjects\CdkTest\.venv\lib\site-packages\jsii\_kernel\providers\process.py", line 326, in send
        raise JSIIError(resp.error) from JavaScriptError(resp.stack)
    jsii.errors.JSIIError: State with name 'DoThing1' occurs in both Parallel 'InnerParallelState' branch 1 (Prefix1DoThing1) and Parallel 'InnerParallelState' branch 1 (Prefix2DoThing1). All states must have unique names.
```

### PR DESCRIPTION
**Pull request by kaizencc**
There is an order mismatch issue when calling `Parallel.branch()`. `branch` used to immediately create the state graph of the branch which locks in the `stateIds` of the branch states. This fails to take into account the following scenario: 

```ts
class ParallelMachineFragment extends stepfunctions.StateMachineFragment {
  public readonly startState: stepfunctions.State;
  public readonly endStates: stepfunctions.INextable[];

  constructor(scope: Construct, id: string) {
    super(scope, id);

    const step1 = new stepfunctions.Pass(this, 'Step 1');
    const parallelState = new stepfunctions.Parallel(this, 'Parallel State');
    const chain = parallelState.branch(step1);
    this.startState = parallelState;
    this.endStates = [chain];
  }
}

class MyStack extends Stack {
  constructor(scope: Construct, id: string) {
    const fragment1 = new ParallelMachineFragment(this, 'Fragment 1').prefixStates();
    const fragment2 = new ParallelMachineFragment(this, 'Fragment 2').prefixStates();
    
    new stepfunctions.StateMachine(stack, 'State Machine', {
      definition: fragment1.next(fragment2),
    });
  }
}
```

Here, the branches in the `parallelState` do not get prefixes before they are evaluated, causing an error since they have the same `stateId`.

The fix is to make the state graph creation late-bound; it now happens when we call `Parallel.bindToGraph()`. At this point, it will know of any prefixes. 

Fixes #17354. 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-stepfunctions/lib/states/state.ts [hunk 1]
```diff
@@ -82,13 +82,26 @@ export abstract class State extends CoreConstruct implements IChainable {
...
     const queue = [root];
     while (queue.length > 0) {
       const el = queue.splice(0, 1)[0]!;
       if (isPrefixable(el)) {
         el.addPrefix(prefix);
       }
-      queue.push(...Node.of(el).children);
+      if (isBranchable(el)) {
+        addToQueue(el.branchableBranches);
+      }
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-stepfunctions/lib/states/state.ts:94]: Remind me why this is necessary?

It seems like otherwise it wouldn't prefix states which aren't the construct's children, but that is fine...?

File: packages/@aws-cdk/aws-stepfunctions/test/state-machine-fragment.test.ts [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+      definition: fragment1.next(fragment2),
+    });
+
+    // THEN
+    const definitionString = new Capture();
+    Template.fromStack(stack).hasResourceProperties('AWS::StepFunctions::StateMachine', {
+      DefinitionString: definitionString,
+    });
+
+    expect(JSON.parse(definitionString.asString())).toEqual({
```
Comment (nija-at) [inline packages/@aws-cdk/aws-stepfunctions/test/state-machine-fragment.test.ts:25]: Why not just do -

```suggestion
    const definitionString = new Capture();
    Template.fromStack(stack).hasResourceProperties('AWS::StepFunctions::StateMachine', {
      DefinitionString: Match.stringifiedJson(StartAt: 'Fragment 1: Parallel State',
        States: {
          'Fragment 1: Parallel State': {
            Type: 'Parallel',
            Next: 'Fragment 2: Parallel State',
            Branches: [{
              StartAt: 'Fragment 1: Step 1',
              ...
           }],
         },
        },
        ...
      }),
    });
```

File: packages/@aws-cdk/aws-stepfunctions/lib/states/state.ts (hunk 1 above)
Comment (kaizen3031593) [reply packages/@aws-cdk/aws-stepfunctions/lib/states/state.ts]: not necessary unfortunately :(. deleted.

**Review by rix0rrr — APPROVED** [review]
