### PR TITLE
fix(cli): re-bootstrapping loses previous configuration

### LINKED ISSUE #10091: [cli] Bootstrap always resets existing stack's termination protection to false
Running `cdk bootstrap` with a flag that affects the bootstrap template, will cause the stack's termination protection setting to be reset to `Disabled`. 

### Reproduction Steps

`cdk bootstrap aws://<account>/<region>`

Now go the console and manually set the termination protection of the stack to `Enabled`.

Screen Shot 2020-09-01 at 1 18 45 PM

Now run:

`cdk bootstrap --bootstrap-bucket-name a-different-name aws://<account>/<region>`

You'll see that the termination protection was reset:

Screen Shot 2020-09-01 at 1 20 27 PM

### What did you expect to happen?

Stack's termination protection to remain the same.

### What actually happened?

Stack's termination protection was reset to `Disabled`

### Environment

  - **CLI Version      :1.61.0**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
Various properties of the bootstrapping stack you configured with
switches on the command line would be lost again if you performed
bootstrapping again. This includes:

- Template parameters such as the `qualifier`,
  `public-access-block-configuration`, `trust`,
  `cloudformation-execution-roles`.
- Stack attributes such as `termination-protection`, `tags`.

ALSO IN THIS PR

- In the CLI integ tests, only show the CLI output if the test fails.
  This reduces noise when trying to inspect the causes of a failed test.
- Some light refactoring (but not too much) of the division of
  responsibilities between `BootstrapStack`, `ToolkitInfo` and
  `CloudFormationStack`.

Fixes #10091.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk/lib/api/toolkit-info.ts [hunk 1]
```diff
@@ -83,7 +63,10 @@ export class ToolkitInfo {
    * @experimental
    */
   public async prepareEcrRepository(repositoryName: string): Promise<EcrRepositoryInfo> {
-    const ecr = await this.ecr();
+    if (!this.sdk) {
+      throw new Error('ToolkitInfo needs to have been initialized with an sdk to call prepareEcrRepository');
+    }
+    const ecr = this.sdk?.ecr();
```
Comment (njlynch) [inline packages/aws-cdk/lib/api/toolkit-info.ts:69]:
```suggestion
    const ecr = this.sdk.ecr();
```

File: packages/aws-cdk/lib/settings.ts [hunk 2]
```diff
@@ -234,10 +234,21 @@ export class Settings {
...
+   * Parse tags out of arguments
+   *
+   * Return undefined if no tags were provided, return an empty array if only empty
+   * strings were provided
+   */
+  private static parseStringTagsListToObject(argTags: string[] | undefined): Tag[] | undefined {
+    if (argTags === undefined) { return undefined; }
+    if (argTags.length === 0) { return undefined; }
+    const nonEmptyTags = argTags.filter(t => t !== '');
+    if (nonEmptyTags.length === 0) { return []; }
```
Comment (njlynch) [inline packages/aws-cdk/lib/settings.ts:247]: Is the input to this function just the input from the cli (`cli.ts`), or could it also be from an existing stack? I'm trying to wrap my head around if passing the CLI tags through `arrayFromYargs` would effectively de-dupe this logic.

**Review by njlynch — APPROVED** [review]
Looks good. One minor nit, one question/comment.

File: packages/aws-cdk/lib/settings.ts (hunk 2 above)
Comment (rix0rrr) [reply packages/aws-cdk/lib/settings.ts:247]: I know! I wanted to do that originally but the types of doing that don't really work out.

It doesn't sit well with me where this parsing is done, but I didn't want to change the existing code too much more because the diff was already growing too large for my tastes.
