### PR TITLE
fix(eks): throw error when kubectl subnets are isolated

### LINKED ISSUE #26613: aws_eks: Error creating `FargateCluster` in `cn-north-1` due to `CoreDnsComputeTypePatch` creation error
### Describe the bug

Towards the end of a FargateCluster deployment, several resources fail to create, resulting in a rollback/delete.

### Expected Behavior

I expect the cluster to be created smoothly, as I believe it is supported in this region and has successfully deployed on `us-east-1` with the same configuration.

### Current Behavior

When creating a resource with a logical ID `k8sclusterCoreDnsComputeTypePatch2EEF5C89`, it fails with the following status reason:

> CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [4af278ec-eb20-4abc-8d38-4e76661d6112]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.

Create for the last remaining necessary resources also fails because this one fails.

### Reproduction Steps

Cluster creation code:

```python
cluster = eks.FargateCluster(
            self,
            "k8s-cluster",
            cluster_name=f"k8s-{stage_name}",
            version=eks.KubernetesVersion.V1_26,
            vpc=self.vpc,
            vpc_subnets=[subnet_selection],
            cluster_logging=[
                eks.ClusterLoggingTypes.API,
                eks.ClusterLoggingTypes.AUTHENTICATOR,
                eks.ClusterLoggingTypes.SCHEDULER,
            ],
            kubectl_layer=lambda_layer_kubectl_v26.KubectlV26Layer(
                self, "kubectl-v26-layer"
            ),
            masters_role=masters_role,
        )
```

### Possible Solution

Possibly trying to apply a patch that requires Global internet access, but needs to use a mirror in China? Other than that, not sure why something in China would fail.

### Additional Information/Context

_No response_

### CDK CLI Version

2.86.0

### Framework Version

_No response_

### Node.js Version

18.30

### OS

Mac OS X

### Language

Python

### Language Version

3.9.15

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Abogical**
### Issue # (if applicable)

Closes #26613.

### Reason for this change

When creating an `eks.FargateCluster` (or any EKS cluster with `coreDnsComputeType: FARGATE`) in a VPC with only `PRIVATE_ISOLATED` subnets and private endpoint access enabled, the kubectl Lambda is placed in those isolated subnets. Since isolated subnets have no internet access by definition (no NAT Gateway, no Internet Gateway route), the Lambda cannot reach the EKS API, STS, or other AWS service endpoints. This causes the `CoreDnsComputeTypePatch` custom resource (and any other kubectl operation) to silently time out after 15 minutes, resulting in a confusing CloudFormation deployment failure.

### Description of changes

Added a `ValidationError` at synth time in both `aws-eks` and `aws-eks-v2` modules that detects when the selected kubectl private subnets include `PRIVATE_ISOLATED` subnets. The check runs in the `Cluster` constructor, right after `kubectlPrivateSubnets` is assigned, by comparing the selected subnets against `vpc.isolatedSubnets`.

The error message tells users exactly what is wrong and how to fix it:
- Use `PRIVATE_WITH_EGRESS` subnets with a NAT Gateway
- Or configure VPC endpoints for STS, EKS, and ECR
- Links to the AWS private clusters documentation

**Why a hard error instead of a warning:** `PRIVATE_ISOLATED` subnets are created by CDK with no egress route. If CDK created the VPC and the kubectl subnets are isolated, we know with certainty there is no egress and the deployment will fail. Failing fast at synth time is better than a 15-minute Lambda timeout.

**Files changed:**
- `packages/aws-cdk-lib/aws-eks/lib/cluster.ts` — validation after `kubectlPrivateSubnets` assignment
- `packages/aws-cdk-lib/aws-eks-v2/lib/cluster.ts` — same validation after `kubectlSubnets` assignment
- `packages/aws-cdk-lib/aws-eks/test/cluster.test.ts` — 2 new tests
- `packages/aws-cdk-lib/aws-eks-v2/test/cluster.test.ts` — 2 new tests

### Describe any new or updated permissions being added

No new or updated IAM permissions. This is a synth-time validation only.

### Description of how you validated changes

- Added 4 unit tests (2 per module):
  - `throws when kubectl private subnets include isolated subnets` — verifies the `ValidationError` is thrown
  - `does not throw when kubectl private subnets are PRIVATE_WITH_EGRESS` — verifies no error for valid subnets
- All 147 existing `aws-eks` tests pass
- All 120 existing `aws-eks-v2` tests pass
- No TypeScript diagnostics errors in any modified file

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-eks/lib/cluster.ts [hunk 1]
```diff
@@ -1868,6 +1868,23 @@ export class Cluster extends ClusterBase {
...
+      const hasIsolatedSubnets = privateSubnets.some(s => isolatedSubnetIds.has(s.subnetId));
+      if (hasIsolatedSubnets) {
+        throw new ValidationError(
+          'Isolated subnets cannot be used for kubectl private subnets. Isolated subnets have no internet access, '
+          + 'which is required for the kubectl Lambda to reach the EKS API, STS, and other AWS service endpoints. '
+          + 'Use PRIVATE_WITH_EGRESS subnets with a NAT Gateway instead, or configure VPC endpoints for STS, EKS, and ECR. '
+          + 'See https://docs.aws.amazon.com/eks/latest/userguide/private-clusters.html',
+          this,
+        );
+      }
```
Comment (vishaalmehrishi) [inline packages/aws-cdk-lib/aws-eks/lib/cluster.ts]: This validation throws unconditionally for isolated subnets, but the error message itself suggests VPC endpoints as a valid alternative. Users who have properly configured VPC endpoints for STS, EKS, ECR, and S3 in their isolated subnets will be blocked at synth time with no workaround.

The DNS validation directly above (line 1867) uses `this.vpc instanceof ec2.Vpc` to avoid false positives with imported VPCs. Consider applying the same guard here — when the VPC is CDK-created, we know isolated subnets have no egress; when it's imported, we can't be sure.

Per the [AWS private clusters documentation](https://docs.aws.amazon.com/eks/latest/userguide/private-clusters.html), isolated subnets with VPC endpoints are a supported configuration.

```typescript
if (this.vpc instanceof ec2.Vpc) {
  const isolatedSubnetIds = new Set(this.vpc.isolatedSubnets.map(s => s.subnetId));
  const hasIsolatedSubnets = privateSubnets.some(s => isolatedSubnetIds.has(s.subnetId));
  if (hasIsolatedSubnets) {
    throw new ValidationError(
      'Isolated subnets cannot be used for kubectl private subnets. ...',
      this,
    );
  }
}
```

File: packages/aws-cdk-lib/aws-eks/lib/cluster.ts [hunk 2]
```diff
@@ -1868,6 +1868,23 @@ export class Cluster extends ClusterBase {
...
+      // See https://github.com/aws/aws-cdk/issues/26613
+      const isolatedSubnetIds = new Set(this.vpc.isolatedSubnets.map(s => s.subnetId));
+      const hasIsolatedSubnets = privateSubnets.some(s => isolatedSubnetIds.has(s.subnetId));
+      if (hasIsolatedSubnets) {
+        throw new ValidationError(
+          'Isolated subnets cannot be used for kubectl private subnets. Isolated subnets have no internet access, '
+          + 'which is required for the kubectl Lambda to reach the EKS API, STS, and other AWS service endpoints. '
+          + 'Use PRIVATE_WITH_EGRESS subnets with a NAT Gateway instead, or configure VPC endpoints for STS, EKS, and ECR. '
+          + 'See https://docs.aws.amazon.com/eks/latest/userguide/private-clusters.html',
+          this,
```
Comment (vishaalmehrishi) [inline packages/aws-cdk-lib/aws-eks/lib/cluster.ts]: The error message mentions "VPC endpoints for STS, EKS, and ECR" but per the [AWS private clusters documentation](https://docs.aws.amazon.com/eks/latest/userguide/private-clusters.html), ECR also requires an S3 gateway endpoint (`com.amazonaws.region-code.s3`) for pulling container images. Consider updating to "STS, EKS, ECR, and S3" for completeness.

File: packages/aws-cdk-lib/aws-eks-v2/lib/cluster.ts [hunk 3]
```diff
@@ -1385,6 +1385,23 @@ export class Cluster extends ClusterBase {
         throw new UnscopedValidationError('Private endpoint access requires the VPC to have DNS support and DNS hostnames enabled. Use `enableDnsHostnames: true` and `enableDnsSupport: true` when creating the VPC.');
       }
 
+      // Validate that kubectl subnets are not isolated. Isolated subnets have no
+      // internet access by definition, so the kubectl Lambda will not be able to
+      // reach the EKS API, STS, or other AWS service endpoints required for
+      // kubectl operations (including the CoreDNS compute type patch).
+      // See https://github.com/aws/aws-cdk/issues/26613
+      const isolatedSubnetIds = new Set(this.vpc.isolatedSubnets.map(s => s.subnetId));
```
Comment (vishaalmehrishi) [inline packages/aws-cdk-lib/aws-eks-v2/lib/cluster.ts]: Same as the `aws-eks` module — consider adding the `this.vpc instanceof ec2.Vpc` guard here for consistency with the DNS validation at line 1384 and to avoid blocking users with VPC endpoints on imported VPCs.

Per the [AWS private clusters documentation](https://docs.aws.amazon.com/eks/latest/userguide/private-clusters.html), isolated subnets with VPC endpoints are a supported configuration.

**Review by vishaalmehrishi — APPROVED** [review]
