### PR TITLE
fix(elasticsearch): log policies are overwritten when creating 2 domains which also results in a failure while destroying the stack  

### LINKED ISSUE #12016: (elasticsearch): Two Domains in same account/region cause LogGroup Policy Failure
When 2 or more elasticsearch Domains are created in the same account/region both with logging configurations,  Cloudformation will throw an error when the second domain is deleted: 

Cloudformation resource DELETE failed error: 
ESLogGroupPolicy | Custom::CloudwatchLogResourcePolicy | DELETE_FAILED | Failed to delete resource. Policy with name [ESLogPolicy] does not exist.
-- | -- | -- | --

Cloudformation event:
2020-12-10 17:16:37 UTC-0600 | ElasticsearchTestTsESDomain2ESLogGroupPolicy7BC68A84 | DELETE_FAILED | Failed to delete resource. Policy with name [ESLogPolicy] does not exist.
-- | -- | -- | --

### Reproduction Steps
```
#!/usr/bin/env node
import { App, Stack } from '@aws-cdk/core';
import { Domain, ElasticsearchVersion } from '@aws-cdk/aws-elasticsearch';

const app = new App();
const stack = new Stack(app, 'es-bug-stack');
new Domain(stack, 'domain1', {
    version: ElasticsearchVersion.V7_7,
    logging: { appLogEnabled: true }
})
const stack2 = new Stack(app, 'es-bug-stack2');
new Domain(stack2, 'domain2', {
    version: ElasticsearchVersion.V7_7,
    logging: { appLogEnabled: true }
})
app.synth()
```

```
$ cdk deploy '*'
$ cdk destroy
```

Detailed example: 
```
$ cdk deploy '*' --require-approval never
 es-bug-stack
 es-bug-stack: deploying...
 ✅  es-bug-stack
 es-bug-stack2
 es-bug-stack2: deploying...
 ✅  es-bug-stack2

$ cdk destroy es-bug-stack --force
 es-bug-stack: destroying... 
 9:52:38 AM | DELETE_IN_PROGRESS   | AWS::CloudFormation::Stack          | es-bug-stack
 9:58:56 AM | DELETE_IN_PROGRESS   | AWS::IAM::Role                      | AWS679f53fac002430...bd2287/ServiceRole

 ✅  es-bug-stack: destroyed

$ cdk destroy es-bug-stack2 --force
 10:18:32 AM | DELETE_FAILED        | Custom::CloudwatchLogResourcePolicy | domain2ESLogGroupPolicyC8E72CCB
 Failed to delete resource. Policy with name [ESLogPolicy] does not exist.

        new CustomResource (/Users/req96588/Projects/moo-elastic-testing/node_modules/@aws-cdk/core/lib/custom-resource.ts:115:21)
        \_ new AwsCustomResource (/Users/req96588/Projects/moo-elastic-testing/node_modules/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts:376:27)
        \_ new LogGroupResourcePolicy (/Users/req96588/Projects/moo-elastic-testing/node_modules/@aws-cdk/aws-elasticsearch/lib/log-group-resource-policy.ts:28:5)
        \_ new Domain (/Users/req96588/Projects/moo-elastic-testing/node_modules/@aws-cdk/aws-elasticsearch/lib/domain.ts:1416:32)
        \_ Object.<anonymous> (/Users/req96588/Projects/moo-elastic-testing/bin/app.ts:12:1)
10:18:32 AM | DELETE_FAILED        | Custom::CloudwatchLogResourcePolicy | domain2/ESLogGroup...y/Resource/Default
Failed to delete resource. Policy with name [ESLogPolicy] does not exist.
10:18:37 AM | DELETE_FAILED        | AWS::CloudFormation::Stack          | es-bug-stack2
The following resource(s) failed to delete: [domain2ESLogGroupPolicyC8E72CCB].

 ❌  es-bug-stack2: destroy failed Error: The stack named es-bug-stack2 is in a failed state. You may need to delete it from the AWS console : DELETE_FAILED (The following resource(s) failed to delete: [domain2ESLogGroupPolicyC8E72CCB]. )
    at Object.waitForStackDelete (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:277:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.destroyStack (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:381:28)
    at CdkToolkit.destroy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:252:9)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:200:9)
The stack named es-bug-stack2 is in a failed state. You may need to delete it from the AWS console : DELETE_FAILED (The following resource(s) failed to delete: [domain2ESLogGroupPolicyC8E72CCB]. )
```

### What did you expect to happen?

That two elastic search domains can be created in the same AWS account/region without issue

### What actually happened?

1. When the second domain is created, it  overwrites the first domains CloudWatch LogGroup policy (becuase the Domain uses a statically named `ESLogPolicy`)
2. When the second domain is deleted, cloudformation throw an error. (Because when the first domain is deleted, it should not delete the second domain's policy) 

### Environment

  - **CDK CLI Version  :** 1.70.0
  - **Framework Version:** 1.70.0
  - **Node.js Version:** v12.18.4
  - **OS               : macos
  - **Language (Version):** all | typescript@3.9.7

### Other
It appears that @aws-cdk/aws-elasticsearch Domain creates a custom resources to set cloudwatch log group resource policy here and the yes the policy name "ESLogPolicy" 
https://github.com/aws/aws-cdk/blob/ae2e9c1a40070509e2fb5a95de8881906b500546/packages/%40aws-cdk/aws-elasticsearch/lib/domain.ts#L1418
```
      // Use a custom resource to set the log group resource policy since it is not supported by CDK and cfn.
      // https://github.com/aws/aws-cdk/issues/5343
      logGroupResourcePolicy = new LogGroupResourcePolicy(this, 'ESLogGroupPolicy', {
        policyName: 'ESLogPolicy',
        policyStatements: [logPolicyStatement],
      });
```

The custom resource deletes that log policy when the Domain is deleted 
https://github.com/aws/aws-cdk/blob/33ce50f9ae131730115b59e2c0a961692b27d6ee/packages/%40aws-cdk/aws-elasticsearch/lib/log-group-resource-policy.ts#L41
```
/**
 * Creates LogGroup resource policies.
 */
export class LogGroupResourcePolicy extends cr.AwsCustomResource {
  constructor(scope: cdk.Construct, id: string, props: LogGroupResourcePolicyProps) {
    const policyDocument = new iam.PolicyDocument({
      statements: props.policyStatements,
    });

    super(scope, id, {
      resourceType: 'Custom::CloudwatchLogResourcePolicy',
      onUpdate: {
        service: 'CloudWatchLogs',
        action: 'putResourcePolicy',
        parameters: {
          policyName: props.policyName,
          policyDocument: JSON.stringify(policyDocument),
        },
        physicalResourceId: cr.PhysicalResourceId.of(id),
      },
      onDelete: {
        service: 'CloudWatchLogs',
        action: 'deleteResourcePolicy',
        parameters: {
          policyName: props.policyName,
        },
        ignoreErrorCodesMatching: '400',
      },
      policy: cr.AwsCustomResourcePolicy.fromSdkCalls({ resources: ['*'] }),
    });
  }
}
```

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by peterb154**
2 Domains in same account/region each create & delete LogGroup Resource Policies statically named 'ESLogPolicy'.

Fixes #12016

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-elasticsearch/lib/domain.ts [hunk 1]
```diff
@@ -1415,7 +1415,8 @@ export class Domain extends DomainBase implements IDomain {
       // Use a custom resource to set the log group resource policy since it is not supported by CDK and cfn.
       // https://github.com/aws/aws-cdk/issues/5343
       logGroupResourcePolicy = new LogGroupResourcePolicy(this, 'ESLogGroupPolicy', {
-        policyName: 'ESLogPolicy',
+        // create a cloudwatch logs resource policy name that is unique to this domain instance
+        policyName: `ESLogPolicy${this.node.addr}`,
```
Comment (iliapolo) [inline packages/@aws-cdk/aws-elasticsearch/lib/domain.ts:1419]: We should also use this is the logical id of the custom resource, otherwise the previous policy would remain orphaned. This would be the behavior if CFN had support for log policies and would generate a physical name for us.

File: packages/@aws-cdk/aws-elasticsearch/test/domain.test.ts [hunk 2]
```diff
@@ -233,6 +233,23 @@ describe('log groups', () => {
     });
   });
 
+  test('appLogEnabled should create a uniquely named log group policy', () => {
```
Comment (iliapolo) [inline packages/@aws-cdk/aws-elasticsearch/test/domain.test.ts:236]:
```suggestion
  test('log group policy is uniquely named for each domain', () => {
```

I would also add another domain to the test and make sure the policy names are different, the current assertion doesn't **strictly** validate that.

**Review by iliapolo — CHANGES_REQUESTED** [review]

**Review by iliapolo — APPROVED** [review]
