### PR TITLE
fix(ecs-patterns): feature flag missing for breaking change passing container port for target group port

### LINKED ISSUE #19411: (ecs-patterns): breaking target group port change introduced after upgrading cdk
### What is the problem?

We recently upgraded the cdk version from 1.13x to 1.147 and noticed a breaking change prevent us from deploying.

The change is introduced by this commit: #18157 from #18073

In ecs-patterns, target group was generated with port 80, and now changed to containerPort that in our case is 8080. 
This triggered a replacement of the target group, and in production, we certainly cannot replace the target group or LB.

The service is currently working fine, and my understanding is when used with ECS, the port in target group is meaningless as ECS ports are random: https://stackoverflow.com/questions/42715647/whats-the-target-group-port-for-when-using-application-load-balancer-ec2-con  
Looks like even ECS is hard coding target group port to 80 when create service in console.

So what is the exact issue of #18073, what is it trying to fix? Looks like the change is meaningless and introduced breaking replacement to people who are already using the construct.

### Reproduction Steps

Upgraded the cdk version from 1.130 to 1.147 and compared the generated TargetGroup from NetworkLoadBalancedEc2Service

### What did you expect to happen?

Generated template should remain unchanged without any code change:

      "Type": "AWS::ElasticLoadBalancingV2::TargetGroup",
      "Properties": {
        "HealthCheckPort": "traffic-port",
        "HealthCheckProtocol": "TCP",
        "HealthyThresholdCount": 10,
        "Port": 80,
        "Protocol": "TCP",

### What actually happened?

Target group port changed to container port:

      "Type": "AWS::ElasticLoadBalancingV2::TargetGroup",
      "Properties": {
        "HealthCheckPort": "traffic-port",
        "HealthCheckProtocol": "TCP",
        "HealthyThresholdCount": 10,
        "Port": 8080,
        "Protocol": "TCP",

### CDK CLI Version

1.147

### Framework Version

_No response_

### Node.js Version

14

### OS

Mac

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by TheRealAmazonKendra**
PR #18157 results in a new TargetGroup being created from NetworkLoadBalancedEc2Service, NetworkLoadBalancedFargateService, NetworkMultipleTargetGroupsEc2Service,
and NetworkMultipleTargerGroupsFargateService even when no change is made because we are now passing through the containerPort props to TargetGroups's Port.

For existing services, this is a breaking change so a feature flag is needed. This PR adds that feature flag.

Closes #19411.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/cx-api/lib/features.ts [hunk 1]
```diff
@@ -233,6 +233,15 @@ export const EC2_UNIQUE_IMDSV2_LAUNCH_TEMPLATE_NAME = '@aws-cdk/aws-ec2:uniqueIm
...
 export const IAM_MINIMIZE_POLICIES = '@aws-cdk/aws-iam:minimizePolicies';
 
+/**
+ * Enable this feature flag to pass through the `NetworkLoadBalanced<Ec2|Fargate>ServiceProps.taskImageOptions.containerPort`
+ * and the `NetworkMultipleTargetGroups<Ec2|Fargate>ServiceProps.targetGroups[X].containerPort` to the generated
+ * `ElasticLoadBalancingV2::TargetGroup`'s `Port` property.
+ *
+ * This is a feature flag because updating `Port` causes a replacement of the target groups, which is a breaking change.
+ */
+export const ECS_PATTERNS_TARGET_GROUP_PORT_FROM_COTAINER_PORT = '@aws-cdk/aws-ecs-patterns:containerPortToTargetGroupPort';
```
Comment (rix0rrr) [inline packages/@aws-cdk/cx-api/lib/features.ts:243]: Typo :)
```suggestion
export const ECS_PATTERNS_TARGET_GROUP_PORT_FROM_CONTAINER_PORT = '@aws-cdk/aws-ecs-patterns:containerPortToTargetGroupPort';
```

**Review by rix0rrr — APPROVED** [review]

File: packages/@aws-cdk/cx-api/lib/features.ts (hunk 1 above)
Comment (TheRealAmazonKendra) [reply packages/@aws-cdk/cx-api/lib/features.ts]: Crap. Fixed.
