### PR TITLE
fix(opensearch): add I4I and R7GD to list of OpenSearch nodes not requiring EBS volumes

### LINKED ISSUE #32070: (aws_opensearchservice): i4i instances say they need EBS
### Describe the bug

See https://github.com/aws/aws-cdk/issues/31764 and its fix, https://github.com/aws/aws-cdk/pull/31948

While the above PR added i4g to the list of AWS Opensearch instances that don't require EBS options, i4i should be in this list as well as they use attached SSD drives: https://aws.amazon.com/opensearch-service/pricing/

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

I should be able to create an Opensearch domain without using `EBSOptions`.

### Current Behavior

An error is thrown when trying to use i4i instances.

```
  File "/home/runner/work/scaling-eureka/scaling-eureka/infra/management_stack/management_stack/opensearch.py", line 245, in initialize_opensearch
    domain = opensearch.Domain(
             ^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/scaling-eureka/scaling-eureka/.venv/lib/python3.12/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/scaling-eureka/scaling-eureka/.venv/lib/python3.12/site-packages/aws_cdk/aws_opensearchservice/__init__.py", line 8505, in __init__
    jsii.create(self.__class__, self, [scope, id, props])
  File "/home/runner/work/scaling-eureka/scaling-eureka/.venv/lib/python3.12/site-packages/jsii/_kernel/__init__.py", line 334, in create
    response = self.provider.create(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/scaling-eureka/scaling-eureka/.venv/lib/python3.12/site-packages/jsii/_kernel/providers/process.py", line 365, in create
    return self._process.send(request, CreateResponse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/scaling-eureka/scaling-eureka/.venv/lib/python3.12/site-packages/jsii/_kernel/providers/process.py", line 342, in send
    raise RuntimeError(resp.error) from JavaScriptError(resp.stack)
RuntimeError: EBS volumes are required when using instance types other than R3, I3, R6GD, I4G, or IM4GN.
```

### Reproduction Steps
```python
from aws_cdk import (
    aws_opensearchservice as opensearch,
)

# VPC creation omitted

subnets = vpc.select_subnets(
        availability_zones=opensearch.ZoneAwarenessConfig(
          availability_zone_count=2, enabled=True
       ),
        one_per_az=True,
        subnet_type=ec2.SubnetType.PUBLIC,
    )

security_group = ec2.SecurityGroup(
        stack,
        sg_name,
        allow_all_outbound=True,
        allow_all_ipv6_outbound=True,
        description=f"foo.",
        security_group_name="Opensearch Security Group",
        vpc=vpc,
    )

capacity_config = opensearch.CapacityConfig(
        data_nodes=8,
        data_node_instance_type="i4i.2xlarge.search",
        master_node_instance_type="m5.large.search",
        master_nodes=3,
        multi_az_with_standby_enabled=False,
    )

os_version = opensearch.EngineVersion.open_search("2.15")

domain = opensearch.Domain(
        stack,
        "OS",
        capacity=capacity_config,
        ebs=opensearch.EbsOptions(enabled=False),
        enable_auto_software_update=True,
        encryption_at_rest=opensearch.EncryptionAtRestOptions(enabled=True),
        enforce_https=use_https,
        fine_grained_access_control=None,
        node_to_node_encryption=True,
        security_groups=[security_group],
        tls_security_policy=opensearch.TLSSecurityPolicy.TLS_1_2,
        version=os_version,
        vpc=vpc,
        vpc_subnets=[ec2.SubnetSelection(subnets=[subnet for subnet in subnets.subnets])],
        zone_awareness=True,
    )
```

### Possible Solution

See https://github.com/aws/aws-cdk/pull/31948 . This PR essentially needs to be replicated but with `i4i` instances.

### Additional Information/Context

_No response_

### CDK CLI Version

2.166.0 (build 7bb9203)

### Framework Version

_No response_

### Node.js Version

20.11.1

### OS

MacOS 14.6.1

### Language

Python

### Language Version

Python (3.12)

### Other information

_No response_

### LINKED ISSUE #32138: aws-opensearchservice/domain: `r7gd` not usable
### Describe the bug

When trying to create a domain with `dataNodeInstanceType` of `r7gd.4xlarge.search`, CDK reports `Error: EBS volumes are required when using instance types other than R3, I3, R6GD, I4G, or IM4GN.` - however, `gd` instances have integrated storage and do *not* use EBS storage.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

I expected `r7gd` instances to be allowed, as the AWS console is urging me to upgrade to the newer generation.

### Current Behavior

I get the error noted above.

### Reproduction Steps

See description.

### Possible Solution

Correct the list.  (Having a hard-coded list seems really brittle - is there another way to achieve this?)

### Additional Information/Context

_No response_

### CDK CLI Version

2.166.0 (build 7bb9203)

### Framework Version

_No response_

### Node.js Version

v18.18.2

### OS

macOS Monterey Version 12.7.6

### Language

TypeScript

### Language Version

typescript 5.4.3

### Other information

_No response_

### PR DESCRIPTION
**Pull request by mazyu36**
### Issue # (if applicable)

Closes #32070.
Closes #32138.

### Reason for this change
`I4I` and `R7GD` instances don't require ebs volumes.
But at the moment, a domain with `I4I` and `R7GD` instances cannot be deployed.

### Description of changes
Added `I4I` and `R7GD` to not requiring EBS volumes instances list.

### Describe any new or updated permissions being added
Add unit tests and integ tests.
<!— What new or updated IAM permissions are needed to support the changes being introduced ? -->

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts [hunk 1]
```diff
@@ -1576,8 +1576,8 @@ export class Domain extends DomainBase implements IDomain, ec2.IConnectable {
 
     // Validate against instance type restrictions, per
     // https://docs.aws.amazon.com/opensearch-service/latest/developerguide/supported-instance-types.html
-    if (isSomeInstanceType('i3', 'r6gd', 'i4g', 'im4gn') && ebsEnabled) {
-      throw new Error('I3, R6GD, I4G, and IM4GN instance types do not support EBS storage volumes.');
+    if (isSomeInstanceType('i3', 'r6gd', 'i4g', 'i4i', 'im4gn', 'r7gd') && ebsEnabled) {
```
Comment (nmussy) [inline packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts:1579]: It would be nice to refactor these instance type lists and store them in a named constant, to improve readability and maintenance. You could also use their human-friendlier `InstanceClass` names, something like:

```ts
private static readonly UNSUPPORTED_EBS = [
  ec2.InstanceClass.IO3,
  ec2.InstanceClass.MEMORY6_GRAVITON2_NVME_DRIVE,
  // ...
];

// ...
if(isSomeInstanceType(...UNSUPPORTED_EBS) && ebsEnabled) throw
```

You could also generate the error message using this list, without having to update them both manually:

```ts
function formatInstanceTypesList(instanceTypes: string[]): string {
  return instanceTypes.map((type) => type.toUpperCase()).join(', ').replace(/, ([^,]*)$/, ' and $1');
}

throw new Error(`${formatInstanceTypesList(UNSUPPORTED_EBS)} instance types do not support EBS storage volumes.`);
```

File: packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ebs.ts [hunk 2]
```diff
@@ -7,23 +7,26 @@ class TestStack extends Stack {
...
+          dataNodeInstanceType: instanceType,
+          dataNodes: 1,
+        },
+        // force ebs configuration to be disabled
+        ebs: {
+          enabled: false,
+        },
+      };
+
+      new opensearch.Domain(this, `Domain${index + 1}`, domainProps);
```
Comment (nmussy) [inline packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ebs.ts:28]: The `domainProps` variable seems unnecessary, especially because it has to be typed to get IDE hints instead of inheriting the constructor's signature 

```suggestion
      new opensearch.Domain(this, `Domain${index + 1}`, {
        removalPolicy: RemovalPolicy.DESTROY,
        version: opensearch.EngineVersion.OPENSEARCH_2_17,
        // specify the instance type that supports instance store
        capacity: {
          multiAzWithStandbyEnabled: false,
          dataNodeInstanceType: instanceType,
          dataNodes: 1,
        },
        // force ebs configuration to be disabled
        ebs: {
          enabled: false,
        },
      });
```

File: packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts [hunk 3]
```diff
@@ -1574,10 +1574,24 @@ export class Domain extends DomainBase implements IDomain, ec2.IConnectable {
...
+      ec2.InstanceClass.I3,
+      ec2.InstanceClass.R6GD,
+      ec2.InstanceClass.I4G,
+      ec2.InstanceClass.I4I,
+      ec2.InstanceClass.IM4GN,
+      ec2.InstanceClass.R7GD,
+    ];
+
+    const supportInstanceStorageInstanceType = [
+      ec2.InstanceClass.R3,
```
Comment (mazyu36) [inline packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts:1587]: I'm not sure whether R3 should be included in `unSupportEbsInstanceType` because I couldn't find any documentation, and it has already been deprecated.

To avoid breaking changes, I decided to separate `unSupportEbsInstanceType` and `supportInstanceStorageInstanceType` in line with the current implementation, just in case.

File: packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ebs.ts (hunk 2 above)
Comment (mazyu36) [reply packages/@aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.ebs.ts]: fixed.

File: packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts (hunk 1 above)
Comment (mazyu36) [reply packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts]: Thank you. I took your suggestions into account and tried refactoring the relevant parts for this fix.
As for unrelated parts, I plan to refactor them in a separate PR.

File: packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts (hunk 3 above)
Comment (nmussy) [reply packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts:1587]: You should still be able to deploy previous gen instances to test this, but it probably doesn't matter either way

**Review by nmussy — APPROVED** [review]
LGTM, thanks for the refactor

**Review by moelasmar — APPROVED** [review]
