### PR TITLE
fix(dynamodb): add missing iam permissions to custom resource for deleting dynamodb replica table

### LINKED ISSUE #22069: aws-cdk-lib/aws-dynamodb: Impossible to delete replica table
### Describe the bug

Updating `Table` construct with some replication regions removed throws AccessDenied error. Stack update kind of succeeds but replica tables need to be removed manually

### Expected Behavior

Updating `Table` construct with some replication regions removed should actually remove replica table(s) and no errors should be thrown

### Current Behavior

Replica table(s) not removed because of access denied errors.

### Reproduction Steps

1. Deploy the following stack
```
class DynamoDbReplicaAccessDeniedDemo extends Stack {

    constructor(scope: Construct, id: string, props?: StackProps) {
        super(scope, id, props);

        new Table(this, 'DemoTable', {
            partitionKey: {
                name: 'keyA',
                type: AttributeType.STRING
            },
            replicationRegions: ['us-west-1', 'us-west-2']
        })
    }
}

new DynamoDbReplicaAccessDeniedDemo(app, 'ddb-replica-access-denied-demo', {
    env: {
        region: 'us-east-1'
    }
});
```

2. Then deploy updated version
```

class DynamoDbReplicaAccessDeniedDemo extends Stack {

    constructor(scope: Construct, id: string, props?: StackProps) {
        super(scope, id, props);

        new Table(this, 'DemoTable', {
            partitionKey: {
                name: 'keyA',
                type: AttributeType.STRING
            },
            replicationRegions: ['us-west-1'] //!!!! us-west-2 removed from here
        })
    }
}

new DynamoDbReplicaAccessDeniedDemo(app, 'ddb-replica-access-denied-demo', {
    env: {
        region: 'us-east-1'
    }
});

```
3. Observe the error in cloudformation events:
> Received response status [FAILED] from custom resource. Message returned: User: arn:aws:sts::<account-id>:assumed-role/ddb-replica-access-denied-OnEventHandlerServiceRol-AAAAAAAAAAAA/ddb-replica-access-denied-d-OnEventHandlerBBBBBBBBBB-CCCCCCCCCC is not authorized to perform: dynamodb:DeleteTableReplica on resource: arn:aws:dynamodb:us-west-2:<account-id>:table/ddb-replica-access-denied-demo-DemoTableAAAAAAAA-BBBBBBB because no identity-based policy allows the dynamodb:DeleteTableReplica action

4. Replica table in us-west-2 still present after stack update is complete

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.38.1

### Framework Version

_No response_

### Node.js Version

v14.20.0

### OS

GNU/Linux

### Language

Typescript

### Language Version

4.7.4

### Other information

_No response_

### PR DESCRIPTION
**Pull request by ahmetsoykan**
> Adding missing iam permissions to custom resource for deleting replicated regions. Since DeleteTableReplica is not enough on its own, DeleteTable permission has also been added.
>
>
> is not authorized to perform: dynamodb:DeleteTableReplica on resource: arn:aws:dynamodb:us-east-2::table/global-replica-region-table because no identity-based policy allows the dynamodb:DeleteTableReplica action
> is not authorized to perform: dynamodb:DeleteTable on resource: arn:aws:dynamodb:us-east-2::table/global-replica-region-table because no identity-based policy allows the dynamodb:DeleteTable action

Closes #22069.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-dynamodb/lib/replica-provider.ts [hunk 1]
```diff
@@ -84,6 +84,14 @@ export class ReplicaProvider extends NestedStack {
       }),
     );
 
+    // Required for replica table deletion
+    this.onEventHandler.addToRolePolicy(
+      new iam.PolicyStatement({
+        actions: ['dynamodb:DeleteTable', 'dynamodb:DeleteTableReplica'],
```
Comment (MrArnoldPalmer) [inline packages/@aws-cdk/aws-dynamodb/lib/replica-provider.ts:90]: Seems like only `DeleteTableReplica` should be required, is `DeleteTable` also necessary?

Comment (ahmetsoykan) [reply packages/@aws-cdk/aws-dynamodb/lib/replica-provider.ts:90]: While i was running integration test from scratch, it was requesting this permission too. @MrArnoldPalmer 

>  ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named global-replica-single-region-delete failed to deploy: CREATE_FAILED (The following resource(s) failed to create: [CustomResourceLambdauseast21CE92864]. ): Received response status [FAILED] from custom resource. Message returned: User: arn:aws:sts:::assumed-role/global-replica-single-reg-AWS679f53fac002430cb0da5-773B4IWO1P2L/global-replica-single-reg-AWS679f53fac002430cb0da5-GPv2ZsyPAzba is not authorized to perform: dynamodb:DeleteTable on resource: arn:aws:dynamodb:us-east-2::table/global-replica-region-table because no identity-based policy allows the dynamodb:DeleteTable action (RequestId: cb9c2ab7-b18b-4e5c-9687-1853379dc36a)
>     at exports.deployStacks (/Users/ahmetsoykan/projects/repos/github.com/ahmetsoykan/aws-cdk/packages/aws-cdk/lib/deploy.js:43:15)
>     at async CdkToolkit.deploy (/Users/ahmetsoykan/projects/repos/github.com/ahmetsoykan/aws-cdk/packages/aws-cdk/lib/cdk-toolkit.js:266:13)
>     at async exec (/Users/ahmetsoykan/projects/repos/github.com/ahmetsoykan/aws-cdk/packages/aws-cdk/lib/cli.js:374:16)
> 
> Stack Deployments Failed: Error: The stack named global-replica-single-region-delete failed to deploy: CREATE_FAILED (The following resource(s) failed to create: [CustomResourceLambdauseast21CE92864]. ): Received response status [FAILED] from custom resource. Message returned: User: arn:aws:sts:::assumed-role/global-replica-single-reg-AWS679f53fac002430cb0da5-773B4IWO1P2L/global-replica-single-reg-AWS679f53fac002430cb0da5-GPv2ZsyPAzba is not authorized to perform: dynamodb:DeleteTable on resource: arn:aws:dynamodb:us-east-2::table/global-replica-region-table because no identity-based policy allows the dynamodb:DeleteTable action (RequestId: cb9c2ab7-b18b-4e5c-9687-1853379dc36a)
>   FAILED     integ.global-replica-single-region-delete-global-replica-single-region-delete-integ/DefaultTest (undefined/us-east-1) 619.274s
>       Integration test failed: Error: Command exited with status 1

File: packages/@aws-cdk/aws-dynamodb/test/integ.global-replica-single-region-delete.ts
Comment (MrArnoldPalmer) [inline packages/@aws-cdk/aws-dynamodb/test/integ.global-replica-single-region-delete.ts:1]: I'm not sure how useful this integ test is. Basically we are just testing that a region can be deleted, not that the actual replica handler can delete it. I think we should just replace this with a unit test that asserts that the correct policy is added to the role. I'll exempt this PR from needing an integration test addition.

If we had utilities for doing multi phase stack deploys with the integ runner we could deploy the stack once, then remove the region and deploy it again. That is a feature of the integ runner we can investigate separately though.

**Review by MrArnoldPalmer — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-dynamodb/lib/replica-provider.ts (hunk 1 above)
Comment (ahmetsoykan) [reply packages/@aws-cdk/aws-dynamodb/lib/replica-provider.ts:90]: I also saw that these permissions are documented at [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/V2gt_IAM.html)

**Comment by ahmetsoykan** [comment]
Exemption Request

File: packages/@aws-cdk/aws-dynamodb/lib/replica-provider.ts [hunk 2]
```diff
@@ -84,6 +84,14 @@ export class ReplicaProvider extends NestedStack {
...
+        resources: ['*'],
```
Comment (MrArnoldPalmer) [inline packages/@aws-cdk/aws-dynamodb/lib/replica-provider.ts:91]: Are we able to scope down the policy here to only affect the appropriate table?

**Review by MrArnoldPalmer — DISMISSED** [review]

**Comment by MrArnoldPalmer** [comment]
looks good, thank you @ahmetsoykan !
