### PR TITLE
fix(codepipeline): allow multiple CodeCommit source actions using events

### LINKED ISSUE #7802: CodePipeline add multiple source CodeCommit on the same stage
### The Question

I want to add multiple source stages from CodeCommit to trigger the same pipeline depending on the branch (master,dev,qa)

```python
       source_output = codepipeline.Artifact()
       master_action = codepipeline_actions.CodeCommitSourceAction(
           action_name="Codemaster",
           repository=repo,
           output=source_output,
           branch="master"
       )
       devaction = codepipeline_actions.CodeCommitSourceAction(
           action_name="Codedev",
           repository=repo,
           output=source_output,
           branch="dev"
       )
       qaaction = codepipeline_actions.CodeCommitSourceAction(
           action_name="Codeqa",
           repository=repo,
           output=source_output,
           branch="qa"
       )
       pipeline.add_stage(
           stage_name="SourceCode",
           actions=[master_action,devaction,qaaction]
       )
```

Then I get the issue:

```
jsii.errors.JavaScriptError: 
  Error: There is already a Construct with name 'dockerpipeline2F0CA39F7EventRule' in Repository [docker-repo]
      at Node.addChild (/private/var/folders/1b/0_087b815pq9q3gd01q32s845c1810/T/jsii-kernel-gXpn5y/node_modules/constructs/lib/construct.js:414:19)
```

I can add multiple actions in the CodeBuild part, but I am getting an error here. I can add manually trough the AWS console and it's fine.

### Environment

  - **CDK CLI Version:** 1.36.1 (build 4df7dac 
  - **Module Version:** 
  - **OS:** OSX Mojave
  - **Language:** Python

### PR DESCRIPTION
**Pull request by skinny85**
There are use-cases when you want to add the same CodeCommit
repository to a CodePipeline multiple times, with different branches.
This wouldn't work when using CloudWatch Events to trigger the pipeline,
as the ID of the generated Event only used the pipeline ID for uniqueness.
Change it to also use the branch name when generating the Event ID
(which cannot be empty, as it turns out, so validate that as well).

Fixes #7802

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by skinny85** [comment]
@rix0rrr ping

File: packages/@aws-cdk/aws-codepipeline-actions/lib/codecommit/source-action.ts [hunk 1]
```diff
@@ -119,7 +122,7 @@ export class CodeCommitSourceAction extends Action {
     const createEvent = this.props.trigger === undefined ||
       this.props.trigger === CodeCommitTrigger.EVENTS;
     if (createEvent) {
-      this.props.repository.onCommit(stage.pipeline.node.uniqueId + 'EventRule', {
+      this.props.repository.onCommit(`${stage.pipeline.node.uniqueId}-${this.branch}-EventRule`, {
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-codepipeline-actions/lib/codecommit/source-action.ts:125]: Let's do this without breaking existing templates. It's a chore, but our customers will thank us.

Only insert the branch if its `!= 'master'` ?

(Not 100% guaranteed to not change anyone's templates, but like 90% good enough).

Comment (skinny85) [reply packages/@aws-cdk/aws-codepipeline-actions/lib/codecommit/source-action.ts]: Done!
