### PR TITLE
fix(s3): setting `autoDeleteObjects` to `false` empties the bucket

### LINKED ISSUE #16603: !!WARNING!! s3: toggling off auto_delete_objects for Bucket empties the bucket
If a stack is deployed with an S3 bucket with `auto_delete_objects=True`, and then re-deployed with `auto_delete_objects=False`, all the objects in the bucket will be deleted.

### Reproduction Steps

1. Deploy a stack with an S3 bucket created with `auto_delete_objects=True`.
2. Upload files into the bucket.
3. Deploy the stack again with `auto_delete_objects=False`.
4. Observe that the bucket is now empty.

### What did you expect to happen?

The bucket should not have been emptied.

### What actually happened?

Since the custom resource was deleted, the bucket was emptied.

### Environment

  - **CDK CLI Version  :** 1.118.0
  - **Framework Version:**
  - **Node.js Version:** 14.17.5
  - **OS               :** debian bullseye (running inside a container)
  - **Language (Version):** Python 3.9.6

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
This was caused by the Custom Resource--which had previously been
deployed when `autoDeleteObjects: true`--being removed when
`autoDeleteObjects` is flipped off again. The custom resource would
indiscriminately empty the bucket as it was being deleted.

Fix by tagging the bucket to confirm that it needs to be emptied. If
any deployment removes the CR but keeps the bucket, the ordering of
CloudFormation updates will make sure that the untagging happens before
the CR gets activated, thereby saving the bucket contents.

Fixes #16603.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-s3/lib/auto-delete-objects-handler/index.ts [hunk 1]
```diff
@@ -1,7 +1,36 @@
...
+/**
+ * The custom resource should clear the bucket in one of the following cases:
+ *
+ * - The stack is deleted
+ * - The target bucket is removed from the template
+ * - The target bucket is replaced
+ * - The target bucket is created in a deployment that gets rolled back
+ *
+ * In particular, it should NOT clear the bucket in a case the custom resource is deleted
+ * but the target bucket is unaffected. This could happen in the follwoing cases:
```
Comment (ryparker) [inline packages/@aws-cdk/aws-s3/lib/auto-delete-objects-handler/index.ts:14]:
```suggestion
 * but the target bucket is unaffected. This could happen in the following cases:
```

**Review by ryparker — APPROVED** [review]
Nice fix 🚀

**Comment by ryparker** [comment]
Looks like CI found an integration test that needs an update: 
`yarn integ integ.bucket-auto-delete-objects.js`

**Review by ryparker — APPROVED** [review]

**Comment by rittneje** [comment]
@rix0rrr @ryparker FWIW, as a workaround, we were investigating using CDK metadata on the S3 bucket as a means of telling the lambda whether it should actually clear the bucket or not. (The metadata would be set when `auto_delete_objects` is true, and unset otherwise.) I'm not sure how airtight that is though.

File: packages/@aws-cdk/aws-s3/lib/auto-delete-objects-handler/index.ts [hunk 2]
```diff
@@ -48,9 +77,58 @@ async function emptyBucket(bucketName: string) {
...
+  // Case 4: we're rolling back a failed update.
+  // In both cases, either the bucket is also being deleted here, or it's just
+  // the CR that's being deleted.
+  // `GetTemplate` will show us the template we are moving to ('new' in case 3,
+  // 'old' in case 4). We will check if the bucket is in the template returned
+  // by `GetTemplate` to see if we need to clean it.
+  const destinationTemplateResponse = await cfn.getTemplate({ StackName: stackId, TemplateStage: 'Processed' }).promise();
+  let template;
+  try {
+    template = yaml.parse(destinationTemplateResponse.TemplateBody ?? '{}', {
```
Comment (jogold) [inline packages/@aws-cdk/aws-s3/lib/auto-delete-objects-handler/index.ts:120]: If you [describe the changeset](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFormation.html#describeChangeSet-property) here instead of analyzing the template then you don't need the `yaml` dependency (and the script to include it in the handler). Better?

File: packages/@aws-cdk/aws-s3/pre-build.sh [hunk 3]
```diff
@@ -0,0 +1,7 @@
+#!/bin/bash
+# Bundle `node_modules/yaml` into the auto-delete-object handler
+tgt=lib/auto-delete-objects-handler/node_modules/yaml
+if [[ ! -d $tgt ]]; then
+  mkdir -p $tgt
+  cp -R node_modules/yaml/ $tgt/
```
Comment (jogold) [inline packages/@aws-cdk/aws-s3/pre-build.sh:6]: what if `yaml` gets updated and comes with dependencies?

**Review by iliapolo — COMMENTED** [review]
@rix0rrr Have you considered coupling the custom resource with the **bucket**, instead of a specific **property**? 

I.e the CR will always exist, and the lambda will either no-op if `autoDeleteObjects` is `false` (or `undefined`), and will delete otherwise.

**Comment by rix0rrr** [comment]
> @rix0rrr Have you considered coupling the custom resource with the **bucket**, instead of the `autoDeleteObjects` **property**?

We have considered it. It means that every single one of the 1243891 templates out there that contains an S3 bucket will automatically gain 3 more resources:

- Role
- Lambda
- CR

And so be "polluted", not to mention the diff we'd be introducing to all customers everywhere. I don't think it would be looked upon graciously

**Comment by rix0rrr** [comment]
> @rix0rrr @ryparker FWIW, as a workaround, we were investigating using CDK metadata on the S3 bucket as a means of telling the lambda whether it should actually clear the bucket or not. (The metadata would be set when auto_delete_objects is true, and unset otherwise.) I'm not sure how airtight that is though.

You know what -- I rejected that initially because of assumptions I made on the CFN lifecycle. Specifically: I thought the following use case would be broken:

* Bucket already exists with data
* New deployment activates `autoDeleteObjects: true`, but gets rolled back. 
* In the process of applying `autoDeleteObjects`, we would set a tag on the bucket:

My assumption was that the rollback would happen in reverse topological order, and so the CR deletion would happen before the untagging:

|   UPDATE_IN_PROGRESS                               | UPDATE_ROLLBACK_IN_PROGRESS        |
|----------------------------------------------------|------------------------------------|
| Tag bucket -> create custom resource -> (ROLLBACK) | -> delete custom resource -> untag |

However, after documenting the lifecycle, I think the order would actually be:

|   UPDATE_IN_PROGRESS                               | UPDATE_ROLLBACK_IN_PROGRESS  | UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS     |
|----------------------------------------------------|------------------------------|---------------------------------|
| Tag bucket -> create custom resource -> (ROLLBACK) | -> untag                     | -> delete custom resource  |

In which case the tag-based approach is actually completely valid, and requires a smaller code change.

I think I will pivot to that. Thanks for reminding me!

File: packages/@aws-cdk/aws-s3/lib/auto-delete-objects-handler/index.ts (hunk 2 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-s3/lib/auto-delete-objects-handler/index.ts:120]: Maybe. It artificially limits the template's use to cases where we deploy using change sets. Granted, the CDK always does that, but I hate artificially limiting ourselves in that way.

**Comment by rix0rrr** [comment]
```
monocdk: FATAL ERROR: NewSpace::Rebalance Allocation failed - JavaScript heap out of memory

```

File: packages/@aws-cdk/aws-s3/pre-build.sh [hunk 4]
```diff
@@ -0,0 +1,7 @@
+#!/bin/bash
```
Comment (jogold) [inline packages/@aws-cdk/aws-s3/pre-build.sh:1]: Remove this file?
