### PR TITLE
fix(stepfunctions): JsonPath.listAt does not accept strings starting with `$[`

### LINKED ISSUE #22471: (aws-stepfunctions): JsonPath doest not accept strings starting with $[
### Describe the bug

When going through a parallel task, the result is an array and to work with it, it needs to be referenced through strings starting with `$[`

### Expected Behavior

Make the JsonPath.listAt function able to process strings starting with `$[`

### Current Behavior

When trying to process a task with the `JsonPath.listAt` function after a parallel task we get the following error

```bash
Error: Data JSON path values must either be exactly equal to '$' or start with '$.'
    at validateDataPath (/home/marcio/marcio/stepfunctions-dynamodb-playground/node_modules/aws-cdk-lib/aws-stepfunctions/lib/fields.js:1:4081)
    at Function.listAt (/home/marcio/marcio/stepfunctions-dynamodb-playground/node_modules/aws-cdk-lib/aws-stepfunctions/lib/fields.js:1:434)
```

### Reproduction Steps

This error can be seen when trying to insert a string set into DynamoDB where the initial input went through a parallel task

```ts
const table = new ddb.Table(this, 'Table', {
  partitionKey: { name: 'pk', type: ddb.AttributeType.STRING },
  removalPolicy: cdk.RemovalPolicy.DESTROY,
});

const passPK = new sfn.Pass(this, 'passPK', {
  parameters: { 'pk.$': '$.pk' },
});
const passStringSet = new sfn.Pass(this, 'PassStringSet', {
  parameters: { 'stringset.$': '$.stringset' },
});

const parallel = new sfn.Parallel(this, 'Parallel', {
  resultPath: '$',
});
parallel.branch(passPK)
  .branch(passStringSet);

const putItem = new tasks.DynamoPutItem(this, 'PutItem', {
  table: table,
  item: {
    pk: tasks.DynamoAttributeValue.fromString('$[0].pk'),
    stringset: tasks.DynamoAttributeValue.fromStringSet(sfn.JsonPath.listAt('$[1].stringset')),
  },
});

const definition = sfn.Chain.start(parallel).next(putItem);

new sfn.StateMachine(this, 'StateMachine', {
  definition: definition,
});
```

### Possible Solution

add the possibility for the `JsonPath.listAt` function to process strings starting with `$[`

### Additional Information/Context

_No response_

### CDK CLI Version

2.45.0

### Framework Version

_No response_

### Node.js Version

v18.10.0

### OS

Linux

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by marciocadev**
`JsonPath.listAt` doest not accept strings starting with `$[`.

When going through a parallel task, the result is an array and to work with it, it needs to be referenced through strings starting with `$[`

This problem particularly affects cases where we want to work with String Sets in DynamoDB where the `DynamoAttributeValue.fromStringSet` function expects an array via the `JsonPath.listAt` function

Closes #22471 

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/integ.stringset-after-parallel.ts [hunk 1]
```diff
@@ -0,0 +1,46 @@
+import * as ddb from '@aws-cdk/aws-dynamodb';
```
Comment (TheRealAmazonKendra) [inline packages/@aws-cdk/aws-stepfunctions-tasks/test/dynamodb/integ.stringset-after-parallel.ts:1]: Yay tests!!!

**Review by TheRealAmazonKendra — DISMISSED** [review]
Thanks for taking the time to implement this fix! Please see my comments inline (which are mostly just me being happy about the amount of testing).

**Review by TheRealAmazonKendra — APPROVED** [review]
