### PR TITLE
fix(applicationautoscaling): typo in `DYANMODB_WRITE_CAPACITY_UTILIZATION`

### LINKED ISSUE #17209: (aws-applicationautoscaling): Typo in PredefinedMetric enum
### What is the problem?

`DynamoDBWriteCapacityUtilization` value in PredefinedMetric enum is defined as `DYANMODB_WRITE_CAPACITY_UTILIZATION` and it should be `DYNAMODB_WRITE_CAPACITY_UTILIZATION`

### Reproduction Steps

Create any `TargetTrackingScalingPolicy` with predefined metric `DynamoDBWriteCapacityUtilization`

### What did you expect to happen?

The enum property should be `DYNAMODB_WRITE_CAPACITY_UTILIZATION`

### What actually happened?

The enum property is `DYANMODB_WRITE_CAPACITY_UTILIZATION`

### CDK CLI Version

2.0.0-rc.26

### Framework Version

2.0.0-rc26

### Node.js Version

v16.13.0

### OS

MacOS 11.6

### Language

Python

### Language Version

3.8.9

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jumic**
Enum value `DYANMODB_WRITE_CAPACITY_UTILIZATION` in `PredefinedMetric` has a typo in `DYANMODB`.
This PR deprecates this value and adds the new value `DYNAMODB_WRITE_CAPACITY_UTILIZATION`.

I think we don't need to add a test case to this PR. Please add the label `pr-linter/exempt-test` if you agree.

Fixes #17209.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-applicationautoscaling/lib/target-tracking-scaling-policy.ts [hunk 1]
```diff
@@ -186,8 +186,14 @@ export enum PredefinedMetric {
...
    * DYANMODB_WRITE_CAPACITY_UTILIZATION
    * @see https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PredefinedMetricSpecification.html
+   * @deprecated use `PredefinedMetric.DYNAMODB_WRITE_CAPACITY_UTILIZATION`
    */
   DYANMODB_WRITE_CAPACITY_UTILIZATION = 'DynamoDBWriteCapacityUtilization',
+  /**
+   * DYNAMODB_WRITE_CAPACITY_UTILIZATION
+   * @see https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PredefinedMetricSpecification.html
+   */
+  DYNAMODB_WRITE_CAPACITY_UTILIZATION = 'DynamoDBWriteCapacityUtilization',
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-applicationautoscaling/lib/target-tracking-scaling-policy.ts:196]: The new property needs to be above the deprecated property (see https://github.com/aws/aws-cdk/pull/17731 for details).

**Review by comcalvi — CHANGES_REQUESTED** [review]
This looks great! One tiny change and this will be perfect.

File: packages/@aws-cdk/aws-applicationautoscaling/lib/target-tracking-scaling-policy.ts (hunk 1 above)
Comment (jumic) [reply packages/@aws-cdk/aws-applicationautoscaling/lib/target-tracking-scaling-policy.ts]: Changed as proposed.

Comment (jumic) [reply packages/@aws-cdk/aws-applicationautoscaling/lib/target-tracking-scaling-policy.ts]: @comcalvi Do you have any ideas how I could fix the build error? Value `DYANMODB_WRITE_CAPACITY_UTILIZATION` was not removed. Is there something wrong with the validation? Thanks.

```
@aws-cdk/aws-applicationautoscaling... CHANGES.
Original assembly: @aws-cdk/aws-applicationautoscaling@1.137.0
Updated assembly:  @aws-cdk/aws-applicationautoscaling@0.0.0
API elements with incompatible changes:
err  - ENUM VALUE @aws-cdk/aws-applicationautoscaling.PredefinedMetric.DYANMODB_WRITE_CAPACITY_UTILIZATION: member DYANMODB_WRITE_CAPACITY_UTILIZATION has been removed [removed:@aws-cdk/aws-applicationautoscaling.PredefinedMetric.DYANMODB_WRITE_CAPACITY_UTILIZATION]
```

Comment (comcalvi) [reply packages/@aws-cdk/aws-applicationautoscaling/lib/target-tracking-scaling-policy.ts]: @jumic I was mistaken about the effects of the above-mentioned jsii bug. It turns out that because only the first enum member is accepted, the second one is entirely removed from the jsii assembly, which is equivalent to deleting it; this results in a breaking change. 

The only way to truly fix this is to give the new enum a dummy value that will be replaced by the correct value whenever it's used. We can do this as follows:

1. Change the value of `DYNAMODB_WRITE_CAPACITY_UTILIZATION`  to a dummy value, something like `'DynamoDBWriteCapacityUtilization-dummy'`.
2. Anytime the props are used to assign a value (pretty sure [here](https://github.com/aws/aws-cdk/blob/6f318b5d8fa4d7a2ada79ceb78d4d26b40a93720/packages/%40aws-cdk/aws-applicationautoscaling/lib/target-tracking-scaling-policy.ts#L146-L149) is the only spot), add a check (`if` statement or ternary operator, preferably) to find the dummy value and replace it with the correct value (which `DYANMODB_WRITE_CAPACITY_UTILIZATION` will have).

Would you be willing to make those changes? It's totally fine if you're not, this is a good bit more work than this change should be.

Comment (jumic) [reply packages/@aws-cdk/aws-applicationautoscaling/lib/target-tracking-scaling-policy.ts]: @comcalvi Thanks, this fixed the build.
I also added a test case for this special logic. I hope this is okay.

File: packages/@aws-cdk/aws-applicationautoscaling/lib/target-tracking-scaling-policy.ts [hunk 2]
```diff
@@ -183,9 +188,15 @@ export enum PredefinedMetric {
    * @see https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PredefinedMetricSpecification.html
    */
   DYNAMODB_READ_CAPACITY_UTILIZATION = 'DynamoDBReadCapacityUtilization',
+  /**
+   * DYNAMODB_WRITE_CAPACITY_UTILIZATION
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-applicationautoscaling/lib/target-tracking-scaling-policy.ts:192]: could we put a small comment explaining the `-dummy` here?

File: packages/@aws-cdk/aws-applicationautoscaling/test/target-tracking.test.ts [hunk 3]
```diff
@@ -53,6 +53,25 @@ describe('target tracking', () => {
...
+      predefinedMetric: appscaling.PredefinedMetric.DYNAMODB_WRITE_CAPACITY_UTILIZATION,
+      targetValue: 0.9,
+    });
+
+    // THEN
+    expect(stack).toHaveResourceLike('AWS::ApplicationAutoScaling::ScalingPolicy', {
+      TargetTrackingScalingPolicyConfiguration: {
+        PredefinedMetricSpecification: { PredefinedMetricType: 'DynamoDBWriteCapacityUtilization' },
+      },
+    });
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-applicationautoscaling/test/target-tracking.test.ts:72]: Can we add the `targetValue` to the `expect()`?

**Review by comcalvi — CHANGES_REQUESTED** [review]
Very nice work! Two minor comments and this should be perfect.

**Review by comcalvi — APPROVED** [review]
LGTM!
