### PR TITLE
fix(ec2-alpha): do not use string comparison in `rangesOverlap`

### LINKED ISSUE #32145: (ec2-alpha): rangesOverlap utility function is wrong
### Describe the bug

rangesOverlap uses string comparison to determine overlap, which I believe is incorrect.

```typescript
// example
rangesOverlap(
  ["10.0.0.0", "10.0.15.255"], // 10.0.0.0/20 
  ["10.0.128.0", "10.0.143.255"] // 10.0.128.0/20
)
```

The above example should return false, but it returns true. Double checked some online tool to confirm that the cidrs do not actually overlap (https://cidrclash.com/clash-results).

image

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

rangesOverlap implements proper cidr comparison

### Current Behavior

Implementation is incorrect

### Reproduction Steps

See description

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.167.0-alpha.0

### Framework Version

_No response_

### Node.js Version

22

### OS

MacOS

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by awsdro**
### Issue #32145

Closes #32145.

### Reason for this change

The rangesOverlap method was using string comparison to check if IP ranges overlapped.

### Description of changes

The rangesOverlap method was updated to compare IP ranges using the ip-num library

### Description of how you validated changes

Added two unit tests to verify correct behavior

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-ec2-alpha/lib/util.ts [hunk 1]
```diff
@@ -269,11 +270,13 @@ export class CidrBlock {
...
-    const [start2, end2] = range2;
-
+    // Convert range strings to IPv4 objects
+    const start1 = IPv4.fromString(range1[0]);
+    const end1 = IPv4.fromString(range1[1]);
+    const start2 = IPv4.fromString(range2[0]);
+    const end2 = IPv4.fromString(range2[1]);
     // Check if ranges overlap
-    return start1 <= end2 && start2 <= end1;
+    return start1.isLessThanOrEquals(end2) && start2.isLessThanOrEquals(end1);
```
Comment (nmussy) [inline packages/@aws-cdk/aws-ec2-alpha/lib/util.ts:279]: This would go back to being:

```ts
const [start1, end1] = range1.map(this.ipv4ToNumber);
const [start2, end2] = range2.map(this.ipv4ToNumber);

// Check if ranges overlap
return start1 <= end2 && start2 <= end1;
```

**Review by nmussy — CHANGES_REQUESTED** [review]
Given how little `ip-num` is being used, I would advise against adding it as a dependency

File: packages/@aws-cdk/aws-ec2-alpha/lib/util.ts [hunk 2]
```diff
@@ -1,6 +1,7 @@
 /*eslint no-bitwise: ["error", { "allow": ["~", "|", "<<", "&"] }] */
 
 import { ISubnet } from 'aws-cdk-lib/aws-ec2';
+import { IPv4 } from 'ip-num/IPNumber';
```
[the remark this answers is not in the document]
Comment (awsdro) [reply packages/@aws-cdk/aws-ec2-alpha/lib/util.ts:4]: Thanks for the feedback. I agree, adding a dependency just to compare IPv4 addresses is a bit too much. I will add a private method to convert the IP addresses to comparable numbers, like you suggested.

File: packages/@aws-cdk/aws-ec2-alpha/test/util.test.ts
[the remark this answers is not in the document]
Comment (awsdro) [reply packages/@aws-cdk/aws-ec2-alpha/test/util.test.ts:1]: Everywhere `rangesOverlap` is called, the range is calculated like `cidrBlock.minIp(), cidrBlock.maxIp()`, so it's always "in order". The implicit assumption with checking for overlap using `start1 <= end2 && start2 <= end1` is that `start1 <= end1` and `start2 <= end2`.

**Review by nmussy — APPROVED** [review]
LGTM. And I didn't see there was already a `ipToNum` method. Gave it a look, kind of funny to see the "hardcore" maths vs my naive proposed implementation 😆

File: packages/@aws-cdk/aws-ec2-alpha/test/integ.subnet-v2.ts
Comment (godwingrs22) [inline packages/@aws-cdk/aws-ec2-alpha/test/integ.subnet-v2.ts:1]: nit: Any reason we need to change the existing ip range defined in the integ test? As i could see the existing ipranges defined in the subnets doesn't overlap anyways.

File: packages/@aws-cdk/aws-ec2-alpha/test/util.test.ts [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+    const testCidr = new CidrBlock('10.0.0.0/16');
+    const range1 = ['10.0.0.0', '10.0.127.255'] as [string, string];
+    const range2 = ['10.0.64.0', '10.0.65.255'] as [string, string];
+    expect(testCidr.rangesOverlap(range1, range2)).toBe(true);
+  });
+
+  test('Should return true for overlapping IP ranges where the last IP of one range is the first IP of the other', () => {
+    const testCidr = new CidrBlock('10.0.0.0/16');
+    const range1 = ['10.0.0.0', '10.0.15.255'] as [string, string];
+    const range2 = ['10.0.15.255', '10.0.255.255'] as [string, string];
```
Comment (godwingrs22) [inline packages/@aws-cdk/aws-ec2-alpha/test/util.test.ts:28]: Ips from `10.0.15.255` to `10.0.255.255` consists of multiple CIDR range blocks such as below and not a single CIDR range block
```
10.0.15.255/32
10.0.16.0/20
10.0.32.0/19
10.0.64.0/18
10.0.128.0/17
```

nit: It would be better to have ips that are from a single CIDR range block so it will be easy to understand. I would suggest to provide a single CIDR range block something like below.

Range 1: 10.0.0.0/24 [10.0.0.0 - 10.0.0.255]
Range 2: 10.0.0.255/32 [10.0.0.255 - 10.0.0.255]

Note: In a single CIDR range, usually the last ip can't be first ip of another valid CIDR range except for /32. So for this unit test, testing last ip of one range to another range, we could test only for /32 range ip(range 2).

**Review by godwingrs22 — DISMISSED** [review]
@awsdro Thanks for your contribution. Left some minor comments.

File: packages/@aws-cdk/aws-ec2-alpha/test/util.test.ts (hunk 3 above)
Comment (awsdro) [reply packages/@aws-cdk/aws-ec2-alpha/test/util.test.ts:28]: The IPs used in some of the unit tests are not valid CIDR ranges, I only added them to test the actual comparison logic in the `rangesOverlap` method. During actual use, the method would not be called with invalid CIDR ranges, but it might worth having tests around the logic regardless, as was recommended in previous feedback.

File: packages/@aws-cdk/aws-ec2-alpha/test/integ.subnet-v2.ts
Comment (awsdro) [reply packages/@aws-cdk/aws-ec2-alpha/test/integ.subnet-v2.ts:1]: This helps check against regression in the `rangesOverlap` method. Without the bugfix in the `rangesOverlap` method, the integration test using these new IPs throws an error (as the `rangesOverlap` method falsely identifies these ranges as overlapping due to string comparison).

**Review by godwingrs22 — APPROVED** [review]

**Comment by awsdro** [comment]
@mergifyio refresh

**Comment by awsdro** [comment]
@mergifyio requeue

**Comment by awsdro** [comment]
Hi @godwingrs22, could you please help with merging this Pull Request? I am seeing the following message:
`
Pull request https://github.com/aws/aws-cdk/pull/32269 has been dequeued. The pull request could not be merged. This could be related to an activated [branch protection](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches) or [ruleset rule](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets) that prevents us from merging. (detail: 4 of 6 required status checks are expected.)
`

I do not have permissions to requeue the PR.

**Comment by godwingrs22** [comment]
@mergifyio requeue

**Comment by godwingrs22** [comment]
@Mergifyio refresh
