### PR TITLE
fix(cloudwatch): MathExpression period of <5 minutes is not respected

### LINKED ISSUE #9156: [aws-cloudwatch] The period of a MathExpression is not respected on CloudWatch
The `period` of a `MathExpression` CloudWatch metric that is used in a `GraphWidget` is currently not respected. In particular, it is possible to specify a period of 1 minute, but for data points still to be spaced every 5 minutes.

### Reproduction Steps

Assume below that `queue` is some `aws_sqs.Queue`, and `dashboard` is some `aws_cloudwatch.Dashboard`. Then consider the following:

    metric = queue.metric_approximate_number_of_messages_visible()

    dashboard.add_widgets(
        aws_cloudwatch.GraphWidget(
            left=[
                aws_cloudwatch.MathExpression(
                    expression=f"2 * x",
                    using_metrics={"x": metric},
                    period=core.Duration.minutes(1)
                )
            ]
        )
    )

In CloudWatch, this produces a widget showing data points every 5 minutes, rather than every 1 minute as expected.

### Error Log

The actual JSON produced for the widget above will be similar to the following (apart from QueueName and region changes):

```
{
    "view": "timeSeries",
    "region": "us-east-1",
    "metrics": [
        [ { "label": "2 * x", "expression": "2 * x", "region": "us-east-1" } ],
        [ "AWS/SQS", "ApproximateNumberOfMessagesVisible", "QueueName", "MY_QUEUE_NAME", { "period": 60, "stat": "Maximum", "visible": false, "id": "x" } ]
    ],
    "period": 300
}
```

This corresponds to showing measurements spaced every 5 minutes by default. 

If the first `metrics` item in the dictionary above is replaced with

```
        [ { "label": "2 * x", "expression": "2 * x", "region": "us-east-1", "period": 60 } ],
```

then data points are spaced correctly every 1 minute. However, the code produced by the CDK does not generate this.

### Environment

  - **CLI Version      :** `aws-cli/1.18.8 Python/3.7.4 Linux/5.3.0-62-generic botocore/1.15.8`
  - **Framework Version:** `1.45.0 (build 0cfab15)`
  - **Node.js Version:**  `v10.16.3`
  - **OS               :** `Linux 5.3.0-62-generic #56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
  - **Language (Version):**  `Python 3.7.4`

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by otaviomacedo**
fixes #9156

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-cloudwatch/lib/private/rendering.ts [hunk 1]
```diff
@@ -55,6 +55,7 @@ function metricGraphJson(metric: IMetric, yAxis?: string, id?: string) {
 
     withExpression(expr) {
       options.expression = expr.expression;
+      if (expr.period && expr.period !== 300) { options.period = expr.period; }
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-cloudwatch/lib/private/rendering.ts:58]: I omitted this originally because what would happen is the expression period would be propagated down to the queried metrics.

Have we confirmed this is really necessary? Does it actually solve the problem it says it's addressing?

**Review by rix0rrr — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-cloudwatch/lib/private/rendering.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-cloudwatch/lib/private/rendering.ts:58]: I mean... I know I suggested this fix in the linked bug report.

But I'm very much interested in WHY this change is necessary.

It might also be because of the `period` field in the enclosing graph, for example.

Looking for someone to do a slightly deeper dive and experimenting a bit with the combinations and telling us WHAT EXACTLY the behavior of CloudWatch is (and by extension, what the construct library needs to produce).

Comment (otaviomacedo) [reply packages/@aws-cdk/aws-cloudwatch/lib/private/rendering.ts:58]: Ok, I can create a minimal stack with a graph widget and deploy to my AWS account to see the difference between the two cases.

Comment (rix0rrr) [reply packages/@aws-cdk/aws-cloudwatch/lib/private/rendering.ts:58]: Thanks!

Comment (otaviomacedo) [reply packages/@aws-cdk/aws-cloudwatch/lib/private/rendering.ts:58]: When you define a metric using `MathExpression`, CDK will generate a new invisible metric for each component of the expression. For example, let's say you want to create a widget with three metrics for a DynamoDB table: one for ConsumedReadCapacityUnits, one for ConsumedWriteCapacityUnits and one for the sum of the other two. The generated CloudFormation template will have five metrics altogether:

1. A visible one for ConsumedReadCapacityUnits
1. A visible one for ConsumedWriteCapacityUnits
1. An invisible one for ConsumedReadCapacityUnits
1. An invisible one for ConsumedWriteCapacityUnits
1. A visible one for ConsumedReadCapacityUnits + ConsumedWriteCapacityUnits

Metric 5 is the sum of metrics 3 and 4.

As it is now, if you specify a period in a `MathExpression`, that period is not being respected in the aggregate metric, but it is already being propagated down to its components. Note that this only affect the components of the math expression. Their visible counterparts remain unchanged. In the example above, only metrics 3 and 4 have the period changed. Since they are invisible, there is no noticeable effect in the final widget, which shows data at a default interval for the aggregate metric. For DynamoDB tables, for example, this default is 10 minutes.

This change solves the problem by overriding the period in the aggregate metric and not changing anything else in the final CloudFormation template. I also deployed stacks with different combinations of periods and overrides and the result is as expected.

**Review by rix0rrr — APPROVED** [review]
