### PR TITLE
fix(@aws-cdk/aws-events-targets): event-rules cannot have targets with the same construct id

### LINKED ISSUE #2377: EventRules cannot have targets with the same Construct ID.
**Describe the bug**
Two Lambda `Function`s with the same Construct ID but in different scopes cannot both be used as targets to the same `EventRule`:

```
Error: Duplicate event rule target with ID: Resource
    at EventRule.addTarget (.../node_modules/@aws-cdk/aws-events/lib/rule.js:57:19)
    at new EventRule (.../node_modules/@aws-cdk/aws-events/lib/rule.js:26:18)
```

The issue is that `Function`'s `asEventRuleTarget` uses `node.id` as the `id` field for the `EventRuleTargetProps` ([source](https://github.com/awslabs/aws-cdk/blob/48d536b191fb205869ef6724b718540be1037135/packages/%40aws-cdk/aws-events-targets/lib/lambda.ts#L32)).  This isn't unique, as it's just the ID that was passed when creating the `Function` construct - instead it should use `node.uniqueId` ([source](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/cdk/lib/construct.ts#L31-L36)). This needs to be globally unique as when calling EventRule.addTarget this value is used as a unique identifier ([source](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-events/lib/rule.ts#L124-L126)).

**To Reproduce**
```
class CustomConstruct extends Construct {
  public readonly lambda: Function;

  constructor(scope: Construct, id: string) {
    super(scope, id);

    this.lambda = new Function(this, "Resource", {
      code: new InlineCode("def handler:\n\tprint(\"Hello\")"),
      handler: "index.handler",
      runtime: Runtime.Python36
    });
  }
}

const construct1 = new CustomConstruct(this, "Construct1");
const construct2 = new CustomConstruct(this, "Construct2");

new EventRule(this, "ConflictingRule", {
  description: "This will fail because the targets both have the same Construct ID",
  scheduleExpression: "rate(1 minute)",
  enabled: true,
  targets: [
    construct1.lambda,
    construct2.lambda
  ]
});
```

**Expected behavior**
I can name my constructs in any manner I want, they can still be accepted as distinct EventRule targets without collision between two distinct construct instances.

**Version:**
 - OS: Mac OS
 - Programming Language: TypeScript
 - CDK Version: 0.26.0

### PR DESCRIPTION
**Pull request by made2591**
Extend the Target for Event Rule Lambda cannot have same construct ID

Two supported Event Targets resources with the same Construct ID but in different scopes cannot both be used as targets to the same EventRule:
```
Error: Duplicate event rule target with ID: Resource
    at EventRule.addTarget (.../node_modules/@aws-cdk/aws-events/lib/rule.js:57:19)
    at new EventRule (.../node_modules/@aws-cdk/aws-events/lib/rule.js:26:18)
```
Assuming a Lambda Function as a RuleTarget, the issue is that Function's asEventRuleTarget uses `node.id` as the id field for the EventRuleTargetProps ([source](https://github.com/awslabs/aws-cdk/blob/48d536b191fb205869ef6724b718540be1037135/packages/%40aws-cdk/aws-events-targets/lib/lambda.ts#L32)). This isn't unique, as it's just the ID that was passed when creating the Function construct - instead, it should use `node.uniqueId` ([source](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/cdk/lib/construct.ts#L31-L36)). This needs to be globally unique as when calling EventRule.addTarget this value is used as a unique identifier ([source](https://github.com/awslabs/aws-cdk/blob/master/packages/@aws-cdk/aws-events/lib/rule.ts#L124-L126)).

I fix the bug as suggested by @robwettach in the package `@aws-cdk/aws-events` by using 64-maximum chars taken from the `uniqueId` - that is unique across the same app. This changes affects every binding in the supported event targets ([source](https://github.com/made2591/aws-cdk/blob/feature/aws-events-targets-sqs/packages/%40aws-cdk/aws-events-targets/lib/)).

close #2377
----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
  - __Design__: For significant features, design document added to `design` folder
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by made2591** [comment]
@rix0rrr do you also think we have to change this in the other targets as well? If so, I can open the respective issues and work on them

**Comment by eladb** [comment]
I don’t see a reason why not

**Comment by made2591** [comment]
I started working on SNS ([source](https://github.com/made2591/aws-cdk/blob/feature/aws-events-targets-sqs/packages/%40aws-cdk/aws-events-targets/lib/sqs.ts)) and I noticed that it also violates the `least privilege principle` we discussed in #2683. Should I have to change it together with this fix or is it something to address in another PR? If it can be solved here, I would introduce also this change... the [code](https://github.com/made2591/aws-cdk/blob/feature/aws-events-targets-sqs/packages/%40aws-cdk/aws-events-targets/lib/sqs.ts)) should be like this 

```
this.topic.grantPublish(new iam.ServicePrincipal("events.amazonaws.com",
  {
    conditions: {
      ArnEquals: { "aws:SourceArn": _rule.ruleArn }
    }
  })
);

return {
  id: this.topic.node.uniqueId,
  arn: this.topic.topicArn,
  input: this.props.message
};
```

What do you think?

**Comment by jogold** [comment]
Note that the `id` is limited to 64 characters (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-target.html) and `uniqueId` to 255. Something similar to https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-servicediscovery/lib/instance.ts#L51 should be done here.

**Comment by rix0rrr** [comment]
> I started working on SNS ([source](https://github.com/awslabs/aws-cdk/blob/master/packages/@aws-cdk/aws-events-targets/lib/sns.ts)) and I noticed that it also violates the _least privilege principle_ we discussed in #2683. Should I have to change it together with this fix or is it something to address in another PR?

Another PR please, if it's not too much effort for you. Let's try and keep unrelated fixes in separate PRs (as long as they don't interfere with each other too much, which this seems like they don't).

**Comment by made2591** [comment]
@jogold you're right, thank you for your feedback: I will do like that

**Comment by made2591** [comment]
I fixed the error, tested on the following stack... it seems fine but I'm getting a problem in the build regarding. The error I get during the build 🤔

```
@aws-cdk/cdk: [2019-06-06T20:38:37.622] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
@aws-cdk/cdk: lib/synthesis.d.ts:1:10 - error TS2305: Module '"../../../../../../../../Users/matteo/Github/aws-cdk/packages/@aws-cdk/cdk/node_modules/@aws-cdk/cx-api/lib"' has no exported member 'BuildOptions'.
@aws-cdk/cdk: 1 import { BuildOptions, CloudAssembly, CloudAssemblyBuilder } from '@aws-cdk/cx-api';
@aws-cdk/cdk:            ~~~~~~~~~~~~
@aws-cdk/cdk: Error: /Users/matteo/Github/aws-cdk/tools/cdk-build-tools/node_modules/jsii/bin/jsii --project-references exited with error code 1
@aws-cdk/cdk: Build failed. Total time (5.5s) | /Users/matteo/Github/aws-cdk/tools/cdk-build-tools/node_modules/jsii/bin/jsii (5.5s)
@aws-cdk/cdk: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
@aws-cdk/cdk: npm ERR! code ELIFECYCLE
@aws-cdk/cdk: npm ERR! errno 1
@aws-cdk/cdk: npm ERR! @aws-cdk/cdk@0.33.0 build: `cdk-build`
@aws-cdk/cdk: npm ERR! Exit status 1
@aws-cdk/cdk: npm ERR!
@aws-cdk/cdk: npm ERR! Failed at the @aws-cdk/cdk@0.33.0 build script.
@aws-cdk/cdk: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@aws-cdk/cdk: npm ERR! A complete log of this run can be found in:
@aws-cdk/cdk: npm ERR!     /Users/matteo/.npm/_logs/2019-06-06T18_38_37_981Z-debug.log
@aws-cdk/cdk: npm ERR! code ELIFECYCLE
@aws-cdk/cdk: npm ERR! errno 1
@aws-cdk/cdk: npm ERR! @aws-cdk/cdk@0.33.0 build+test: `npm run build && npm test`
@aws-cdk/cdk: npm ERR! Exit status 1
@aws-cdk/cdk: npm ERR!
@aws-cdk/cdk: npm ERR! Failed at the @aws-cdk/cdk@0.33.0 build+test script.
@aws-cdk/cdk: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@aws-cdk/cdk: npm ERR! A complete log of this run can be found in:
@aws-cdk/cdk: npm ERR!     /Users/matteo/.npm/_logs/2019-06-06T18_38_38_007Z-debug.log
lerna ERR! npm run build+test exited 1 in '@aws-cdk/cdk'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.

real	0m40.808s
user	2m47.675s
sys	0m20.022s
❌  Last command failed. Scroll up to see errors in log (search for '!!!!!!!!').
```

The test stack after successfully `build+test` over the module events-targets (the lambda throws error for syntax but is not relevent, they get called properly):

```
import cdk = require('@aws-cdk/cdk');
import events = require('@aws-cdk/aws-events');
import lambda = require('@aws-cdk/aws-lambda');
import targets = require('@aws-cdk/aws-events-targets');
import { Construct } from '@aws-cdk/cdk';
import { Runtime } from '@aws-cdk/aws-lambda';

export class CustomConstruct extends Construct {
  public readonly lambda: lambda.Function;

  constructor(scope: Construct, id: string) {
    super(scope, id);

    this.lambda = new lambda.Function(this, "Resource", {
      code: new lambda.InlineCode("def handler:\n\tprint(\"Hello\")"),
      handler: "index.handler",
      runtime: Runtime.Python36
    });
  }
}

export class AwsEventsNodeUniqueIdStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const construct1 = new CustomConstruct(this, "Construct1");
    const construct2 = new CustomConstruct(this, "Construct2");

    var rule = new events.Rule(this, "ConflictingRule", {
      description: "This will fail because the targets both have the same Construct ID",
      scheduleExpression: "rate(1 minute)",
      enabled: true,
    });

    rule.addTarget(new targets.LambdaFunction(construct1.lambda));
    rule.addTarget(new targets.LambdaFunction(construct2.lambda));

  }
}
```

I don't have a lot of idea about the error (outside of the scope of modified code)... any idea? 😕

**Comment by made2591** [comment]
I think it's fine now

File: packages/@aws-cdk/aws-events-targets/lib/lambda.ts [hunk 1]
```diff
@@ -37,9 +37,10 @@ export class LambdaFunction implements events.IRuleTarget {
         sourceArn: rule.ruleArn
       });
     }
+    const id = this.handler.node.uniqueId;
 
     return {
-      id: this.handler.node.id,
+      id: id.substring(Math.max(id.length - 64, 0), id.length),
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-events-targets/lib/lambda.ts]: Might I suggest a slightly different solution:

- Just return `uniqueId` here. Please make the same change for all rule targets at once, I don't really see a point in having a single PR for each one.
- Add the substring operation here: https://github.com/awslabs/aws-cdk/blob/master/packages/@aws-cdk/aws-events/lib/rule.ts#L233 , it will be automatically applied to all rule targets.

Comment (made2591) [reply packages/@aws-cdk/aws-events-targets/lib/lambda.ts]: Ok, got it: you mean pass the `uniqueId` from outside *as is* and the `sanitizeId()` will cut it accordingly to be compliant with `AWS::Events::Rule Target` specification. Makes perfect sense, thank you for your feedback :)

File: packages/@aws-cdk/aws-events-targets/test/ecs/integ.event-fargate-task.expected.json [hunk 2]
```diff
@@ -609,7 +609,7 @@
                     "Arn"
                   ]
                 },
-                "Id": "TaskDef-on-EcsCluster",
+                "Id": "awsecsintegfargateTaskDef8878AF94-on-awsecsintegfargateEcsCluster46E816CB",
```
Comment (jogold) [inline packages/@aws-cdk/aws-events-targets/test/ecs/integ.event-fargate-task.expected.json]: The custom resource will not work anymore now because the `Id` here is not the same as the real `Id` of the target: `awsecsintegfargateTaskDef8878AF94-on-awsecsintegfargateEcsCluster46E816CB` vs `egfargateTaskDef8878AF94-on-awsecsintegfargateEcsCluster46E816CB`

Comment (made2591) [reply packages/@aws-cdk/aws-events-targets/test/ecs/integ.event-fargate-task.expected.json]: 😞I think you are right, need to be changed I guess

Comment (jogold) [reply packages/@aws-cdk/aws-events-targets/test/ecs/integ.event-fargate-task.expected.json]: The test here should also check that both `Custom::AWS` and `AWS::Events::Rule` have the same id https://github.com/awslabs/aws-cdk/blob/696f53f8ee426a7a7958d0807c7ad89b72f587ae/packages/%40aws-cdk/aws-events-targets/test/ecs/event-rule-target.test.ts#L59

Comment (made2591) [reply packages/@aws-cdk/aws-events-targets/test/ecs/integ.event-fargate-task.expected.json]: > The custom resource will not work anymore now because the `Id` here is not the same as the real `Id` of the target: `awsecsintegfargateTaskDef8878AF94-on-awsecsintegfargateEcsCluster46E816CB` vs `egfargateTaskDef8878AF94-on-awsecsintegfargateEcsCluster46E816CB`

I don't know if it makes sense but... for this, I made some reasoning about and I thought that maybe we could just use the `this.taskDefinition.node.uniqueId`: this is because if you look in `Construct` ([source](https://github.com/awslabs/aws-cdk/blob/e4fb811c5b12de4d42fea71510e5bb3ee6b0a73e/packages/%40aws-cdk/cdk/lib/construct.ts#L108)), the `uniqueId` is guaranteed to be *unique* across the same app - and this should be enough to satisfy the constraint of being *scope-unique*. If this makes sense, then the same reasoning should be valid for the `cluster.node` and this could be used as well, but the taskDefinition fits better imho. Am I wrong? 

> The test here should also check that both Custom::AWS and AWS::Events::Rule have the same id

For this, I'm not sure if it is already ok the test (it works, but I'm not convinced): my doubt are about the transformation. I mean, for the custom resource do we have somehow to assume how the id is *sanitized*? If yes, then maybe is not ok yet and it has to be changed because it doesn't cover the scenario you described...but tbh, I'm not sure 🤔

Comment (jogold) [reply packages/@aws-cdk/aws-events-targets/test/ecs/integ.event-fargate-task.expected.json]: Using `this.taskDefinition.node.uniqueId` seems a good solution. 

Even if the `uniqueId` is guaranteed to be unique across the app note that in the rare event that someone would want to use the same task definition in a different cluster but in the same rule it won't work... don't think it's problematic.

**Comment by made2591** [comment]
The change to ecs breaks the integ test across some packages: if the uniqueId reasoning above makes sense, I will fix them as well...
