### PR TITLE
fix(docdb): make most attributes of DatabaseClusterAttributes optional

### LINKED ISSUE #14492: (docdb): Not all properties of Interface DatabaseClusterAttributes should be required
`DatabaseCluster.fromDatabaseClusterAttributes(scope, id, attrs)` expects too many mandatory attributes (attrs - DatabaseClusterAttributes) to simply import a DocumentDB Cluster, which makes method's usage not friendly as it should be.

### What did you expect to happen?
Only necessary properties of DatabaseClusterAttributes should be mandatory for `fromDatabaseClusterAttributes()` usage, for example: clusterIdentifier.

### What actually happened?
There is no simple way to create a reference of DocumentDB inside CDK App using `DatabaseCluster.fromDatabaseClusterAttributes()` unless **all** properties are passed, which makes it cumbersome and not practical. Besides, the interface accepts `securityGroup` but the L1 construct CfnDBCluster accepts an array - of vpcSecurityGroupIds.

A similar issue was reported and fixed for **rds** (see reference below). Perhaps, the same fix could fit docdb lib as well.

### Environment

  - **CDK CLI Version  :** 1.100.0
  - **Framework Version:** 1.100.0
  - **Node.js Version:** v.14.16.1
  - **OS               :** win 10 (64 bits)
  - **Language (Version):** TypeScript (3.8.3)

### Other
Related issue: https://github.com/aws/aws-cdk/issues/3587 

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by Synohara**
Fixes #14492

- Test Result
```
❯ yarn test
yarn run v1.22.17
$ cdk-test
PASS test/endpoint.test.js (17.557 s)
PASS test/parameter-group.test.js (17.601 s)
PASS test/instance.test.js (18.16 s)
PASS test/cluster.test.js (19.233 s)

 

=============================== Coverage summary ===============================
Statements   : 98.76% ( 160/162 )
Branches     : 99.02% ( 102/103 )
Functions    : 100% ( 27/27 )
Lines        : 98.75% ( 158/160 )
================================================================================

 

Test Suites: 4 passed, 4 total
Tests:       51 passed, 51 total
Snapshots:   0 total
Time:        19.946 s
Ran all test suites.
Verifying integ.cluster-rotation.lit.js against integ.cluster-rotation.lit.expected.json ... OK.
Verifying integ.cluster.js against integ.cluster.expected.json ... OK.
Tests successful. Total time (26.2s) | /Users/yoshitaka.koitabashi/Desktop/OSS/tmp/aws-cdk/node_modules/jest/bin/jest.js (23.8s) | cdk-integ-assert (2.4s)
✨  Done in 26.72s.
```
----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `cdk-integ` to deploy the infrastructure and generate the snapshot (i.e. `cdk-integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-docdb/lib/cluster.ts [hunk 1]
```diff
@@ -234,6 +234,74 @@ abstract class DatabaseClusterBase extends Resource implements IDatabaseCluster
   }
 }
 
+/**
+ * Represents an imported database cluster.
+ */
+class ImportedDatabaseCluster extends DatabaseClusterBase implements IDatabaseCluster {
```
Comment (skinny85) [inline packages/@aws-cdk/aws-docdb/lib/cluster.ts:240]: Out of curiosity - why did you move this class from where it was defined?

Let's maybe leave it where it is - this way, the diff will be significantly smaller?

File: packages/@aws-cdk/aws-docdb/test/cluster.test.ts [hunk 2]
```diff
@@ -518,6 +518,30 @@ describe('DatabaseCluster', () => {
...
+    const cluster = DatabaseCluster.fromDatabaseClusterAttributes(stack, 'Database', {
+      clusterIdentifier: 'identifier',
+    });
+
+    expect(() => cluster.clusterEndpoint).toThrow(/Cannot access `clusterEndpoint` of an imported cluster/);
+    expect(() => cluster.clusterReadEndpoint).toThrow(/Cannot access `clusterReadEndpoint` of an imported cluster/);
+    expect(() => cluster.instanceIdentifiers).toThrow(/Cannot access `instanceIdentifiers` of an imported cluster/);
+    expect(() => cluster.instanceEndpoints).toThrow(/Cannot access `instanceEndpoints` of an imported cluster/);
+    expect(() => cluster.securityGroupId).toThrow(/Cannot access `securityGroupId` of an imported cluster/);
+  });
```
Comment (skinny85) [inline packages/@aws-cdk/aws-docdb/test/cluster.test.ts:543]: Let's maybe merge these 2 into one test?

**Review by skinny85 — DISMISSED** [review]
Looks great @Synohara! 2 minor comments.

File: packages/@aws-cdk/aws-docdb/lib/cluster.ts (hunk 1 above)
Comment (Synohara) [reply packages/@aws-cdk/aws-docdb/lib/cluster.ts]: Thanks all for the lighting fast response!
I have made changes based on the following code.
https://github.com/aws/aws-cdk/blob/4071d9b0b6af241e1d91d6e5b828334f1693b8a5/packages/%40aws-cdk/aws-rds/lib/cluster.ts#L427-L487

but I agree with your suggestion. So I left it as is and made fix.

File: packages/@aws-cdk/aws-docdb/lib/cluster.ts [hunk 3]
```diff
@@ -257,20 +257,70 @@ export class DatabaseCluster extends DatabaseClusterBase {
    */
   public static fromDatabaseClusterAttributes(scope: Construct, id: string, attrs: DatabaseClusterAttributes): IDatabaseCluster {
     class Import extends DatabaseClusterBase implements IDatabaseCluster {
-      public readonly defaultPort = ec2.Port.tcp(attrs.port);
+      public readonly clusterIdentifier = attrs.clusterIdentifier;
+      public readonly defaultPort = attrs.port ? ec2.Port.tcp(attrs.port) : undefined;
```
Comment (skinny85) [inline packages/@aws-cdk/aws-docdb/lib/cluster.ts:261]: Remember that `0` is falsy in JavaScript/TypeScript. You probably want to compare against `undefined` here.

File: packages/@aws-cdk/aws-docdb/lib/cluster.ts [hunk 4]
```diff
@@ -257,20 +257,70 @@ export class DatabaseCluster extends DatabaseClusterBase {
...
       public readonly connections = new ec2.Connections({
-        securityGroups: [attrs.securityGroup],
+        securityGroups: !!attrs.securityGroup ? [attrs.securityGroup] : undefined,
```
Comment (skinny85) [inline packages/@aws-cdk/aws-docdb/lib/cluster.ts:263]: Why the double `!!` here, all of a sudden? Removing it will not change this code.

File: packages/@aws-cdk/aws-docdb/lib/cluster.ts [hunk 5]
```diff
@@ -257,20 +257,70 @@ export class DatabaseCluster extends DatabaseClusterBase {
...
+      }
+
+      public get instanceEndpoints() {
+        if (!this._instanceEndpoints) {
+          throw new Error('Cannot access `instanceEndpoints` of an imported cluster without instanceEndpointAddresses and port');
+        }
+        return this._instanceEndpoints;
+      }
+
+      public get securityGroupId() {
```
Comment (skinny85) [inline packages/@aws-cdk/aws-docdb/lib/cluster.ts:315]: Can you specify the return types for all of these getters?

**Review by skinny85 — CHANGES_REQUESTED** [review]
Looks great @Synohara! A few last stylistic changes before we merge this in.

File: packages/@aws-cdk/aws-docdb/lib/cluster.ts [hunk 6]
```diff
@@ -257,17 +257,55 @@ export class DatabaseCluster extends DatabaseClusterBase {
...
+        securityGroups: attrs.securityGroup ? [attrs.securityGroup] : undefined,
         defaultPort: this.defaultPort,
       });
       public readonly clusterIdentifier = attrs.clusterIdentifier;
-      public readonly instanceIdentifiers = attrs.instanceIdentifiers;
-      public readonly clusterEndpoint = new Endpoint(attrs.clusterEndpointAddress, attrs.port);
-      public readonly clusterReadEndpoint = new Endpoint(attrs.readerEndpointAddress, attrs.port);
-      public readonly instanceEndpoints = attrs.instanceEndpointAddresses.map(a => new Endpoint(a, attrs.port));
-      public readonly securityGroupId = attrs.securityGroup.securityGroupId;
+      private readonly _instanceIdentifiers?= attrs.instanceIdentifiers;
```
Comment (skinny85) [inline packages/@aws-cdk/aws-docdb/lib/cluster.ts:266]: Why the `?=`? I think this should just be a `=`. Also, missing space:

```suggestion
      private readonly _instanceIdentifiers = attrs.instanceIdentifiers;
```

Same comment in the other fields added in the PR.

**Review by skinny85 — CHANGES_REQUESTED** [review]
Looks almost perfect @Synohara!

File: packages/@aws-cdk/aws-docdb/lib/cluster.ts (hunk 6 above)
Comment (Synohara) [reply packages/@aws-cdk/aws-docdb/lib/cluster.ts]: Thank you for suggestion! I fixed the use of optional properties.

**Review by skinny85 — APPROVED** [review]
Thanks for the contribution @Synohara!

**Review by skinny85 — APPROVED** [review]
