### PR TITLE
fix(pipelines): stackOutput generates names too long to be used in useOutputs

### LINKED ISSUE #13552: (pipelines): ShellScriptAction with useOutput option fails with Artifact name length
I'm using a ShellScriptAction within a CDK pipeline combined with the output option via Stack Outputs.

However, I'm getting the following error:

```
Artifact name must match regular expression: /^[a-zA-Z0-9_-]{1,100}$/`,
got 'Artifact_<PipelineName><StageName><StackName><Hash>_Outputs'
```
The issue is, that the "artifact name" is too long and the regex is violated.

### Reproduction Steps

```typescript
 new ShellScriptAction({
        actionName: `Run_SmokeTests`,
        runOrder: smokeTestStage.nextSequentialRunOrder(),
        rolePolicyStatements: [],
        useOutputs: {
            URL_CONFIGS: pipeline.stackOutput(appStage.outConfigs),
            URL_FOO: pipeline.stackOutput(appStage.outFoo),
            URL_BAR: pipeline.stackOutput(appStage.outBar),
            URL_ASDF: pipeline.stackOutput(appStage.outAsdf),
            URL_AUTH_ENDPOINT: pipeline.stackOutput(appStage.outTokenEndpoint),
            AUTH_CLIENTID: pipeline.stackOutput(appStage.outAppClientId),
        },
        environmentVariables: {
            COGNITO_AUTH: {
                type: BuildEnvironmentVariableType.SECRETS_MANAGER,
                value: `${appStage.secretNameCognitoAuth}:my.secret.path`
            }
        },
        commands: [
            `export TOKEN=curl -X POST --user $AUTH_CLIENTID:$COGNITO_AUTH $URL_AUTH_ENDPOINT -H 'Content-Type: application/x-www-form-urlencoded'`,
            `curl -X POST $URL_CONFIGS -H 'Content-Type: application/json' -H 'Authorization:$TOKEN' -d '"{\"uuid\":\"43e112c6-0c75-4a8f-9c03-b73ac0ae4fd0\",\"config\":\"316477\"}'`
        ],
    });

```

### What did you expect to happen?

Either the name of the generated artifact can be set 
or reduced to match the regex, in my example to match the 100 characters.

### What actually happened?

When running the cdk synth command, it caused the error.
I tried to change the exportNames and the node name of the CfnOutputs of the exporting stacks, but that didn't help.

### Environment

  - **CDK CLI Version  : 1.91 & 1.93**
  - **Framework Version: 1.91 & 1.93**
  - **Node.js Version: 12.20.1** 
  - **OS               : Linux**
  - **Language (Version): Typescript 4.1.5**
--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by otaviomacedo**
If the name is ends up longer than 100 characters, it will drop as many characters as needed from the beginning of the string, since the last ones are usually more significant.

Fixes #13552
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/assert-internal/lib/assertions/have-resource-matchers.ts [hunk 1]
```diff
@@ -260,6 +260,22 @@ export function stringLike(pattern: string): PropertyMatcher {
   });
 }
 
+export function stringIsNoLongerThan(length: number): PropertyMatcher {
```
Comment (rix0rrr) [inline packages/@aws-cdk/assert-internal/lib/assertions/have-resource-matchers.ts:263]:
```suggestion
export function stringNoLongerThan(length: number): PropertyMatcher {
```

**Review by rix0rrr — APPROVED** [review]
