### PR TITLE
fix(core): temp cleanup does not work with jest

### LINKED ISSUE #802: .NET generation needs to use full type names for reused names cross-construct.
Names can be re-used across packages. Full type names need to be used to protect against naming conflicts.

See #786

### PR DESCRIPTION
**Pull request by rix0rrr**
> Re-roll of #36226. The previous version had to be reverted because it was causing `ENOMEM` errors on the build server. In this one, raise the per-process memory requirements from 4GB -> 6GB, so that we run fewer tests in parallel. In the test pipeline this makes the build pass.

Our temporary cleanup fix submitted in https://github.com/aws/aws-cdk/pull/36043 doesn't work for tests run with `jest`, because `jest` suppresses the standard Node `exit` event, causing the cleanup to never run.

Instead, we introduce a new public static function which people using `jest` can call:

```ts
afterAll(CloudAssembly.cleanupTemporaryDirectories);
```

As well as a convenience script to automatically inject this handler into all jest tests:

```
$ jest --setupFilesAfterEnv aws-cdk-lib/testhelpers/jest-autoclean
```

Once this PR has been merged and released we will add the above to all CLI init templates.

Closes https://github.com/aws/aws-cdk/issues/802, hopefully for good.

### CODE REVIEW

File: build.sh [hunk 1]
```diff
@@ -101,7 +101,7 @@ if [[ "$concurrency" == "" ]]; then
     # Auto-limit top-level concurrency to:
     # - available CPUs - 1 to limit CPU load
     # - total memory / 4GB  (N.B: constant here may need to be tweaked, configurable with $CDKBUILD_MEM_PER_PROCESS)
```
Comment (Abogical) [inline build.sh]:
```suggestion
    # - total memory / 6GB  (N.B: constant here may need to be tweaked, configurable with $CDKBUILD_MEM_PER_PROCESS)
```

**Review by Abogical — CHANGES_REQUESTED** [review]

**Review by Abogical — APPROVED** [review]
