### PR TITLE
fix(stepfunctions): incorrect/missing permissions to run/redrive DistributedMap in state machine

### LINKED ISSUE #35390: (stepfunction): distributedmap incorrect and missing policies being added to the state machine
### Describe the bug

Currently when adding a DistributedMap to a statemachine, the permissions run run the Distributed map is not quite right and the permissions needed to redrive the distributed map is not present at all. These are required as stated here: https://docs.aws.amazon.com/step-functions/latest/dg/iam-policies-eg-dist-map.html

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Library Version

_No response_

### Expected Behavior

The distributedmap should apply the correct permissions to the state machine

```diff
  action: ["states:DescribeExecution", "states:StopExecution"]
- resource: "arn:aws:states:us-east-2:account-id:stateMachine:myStateMachine:*"
+ resource: "arn:aws:states:us-east-2:account-id:execution:myStateMachine:*"
//...
+ action: "states:RedriveExecution"
+ resource: "arn:aws:states:us-east-2:account-id:execution:myStateMachine/*:*"
```

### Current Behavior

Some users report errors with running the distributedmap (See this issue for long list of comments: https://github.com/aws/aws-cdk/issues/28820), this could be attributed to the typo in the permissions. Currently, redriving a state machine with a failed distributedmap deployed via CDK is not possible out of the box.

### Reproduction Steps

The following map, when added to a state machine cannot be redrived:

```ts
const map = new DistributedMap(this, 'map').itemProcessor(new Fail(this, 'fail'))
```

### Possible Solution

Add the appropriate redrive permissions 

### Additional Information/Context

The same issue is relevant with distributedmaps created in nested state graphs, like a `Parallel` branch, except more severe because those state machines cannot even be run.

### AWS CDK Library version (aws-cdk-lib)

v2.213.0

### AWS CDK CLI version

2.1023.0

### Node.js Version

20

### OS

Macos

### Language

TypeScript

### Language Version

_No response_

### Other information

Fixed by https://github.com/aws/aws-cdk/pull/34760

### PR DESCRIPTION
**Pull request by Kasra-G**
### Issue # (if applicable)

Closes #35390.

### Reason for this change

When using the `DistributedMap` state, the state machine cannot be redriven without additional configuration from the user. These additional steps seem to sometimes lead users into circular dependency issues (see [example](https://github.com/aws/aws-cdk/issues/28820#issuecomment-2065316882)). 

Additionally, the `DistributedMap` assigns incorrect permissions for the `states:StopExecution` and `states:DescribeExecution` as these need to be applied to the execution arn, not the state machine arn ([AWS Docs](https://docs.aws.amazon.com/step-functions/latest/dg/iam-policies-eg-dist-map.html) vs [code reference](https://github.com/aws/aws-cdk/blob/aea1372ab7bc68c489cea5ee5e499233755910e8/packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts#L178-L180).

This PR also fixes an inconsistency for the recently added `grantRedriveExecution` function as it does not work for state machines that have DistributedMaps. 
The root cause is that when adding a DistributedMap to a state machine, additional permissions need to be added to the state machine's execution role to permit redriving a map run. Otherwise, when the state machine is redriven, the map run will fail to redrive. The docs provide a minimum permissions example https://docs.aws.amazon.com/step-functions/latest/dg/iam-policies-eg-dist-map.html#iam-policy-redrive-dist-map
The key permission is `states:RedriveExecution` on the following arn:
`arn:aws:states:us-east-2:123456789012:execution:myStateMachineName/myMapRunLabel:*`

However, when creating a state machine manually in the AWS Console, if there are any unlabeled distributed maps, the following policy is generated for the generated state machine role:
`arn:aws:states:us-east-2:123456789012:execution:myStateMachineName/*:*`

This change mirrors that logic in CDK.

### Description of changes

Minor: fix `map-with-catch` integ test failing because it was not emptying the bucket before attempting to delete it

- Updated the permissions granted in the `bind` method for DistributedMaps to include correct redrive permissions
- Fixed incorrect resource on the `states:StopExecution` and `states:DescribeExecution` permissions
- ~~Fix missing DistributedMap policy statements when the DistributedMap state was in a child `StateGraph` such as a `Parallel.branch`~~ This will be handled in a separate PR.

These changes fix the root cause of `grantRedriveExecution` not working for state machines with DistributedMaps

### Describe any new or updated permissions being added

when there is any unlabeled distributed map run state
```diff
  action: ["states:DescribeExecution", "states:StopExecution"]
- resource: "arn:aws:states:us-east-2:account-id:stateMachine:myStateMachine:*"
+ resource: "arn:aws:states:us-east-2:account-id:execution:myStateMachine:*"
//...
+ action: "states:RedriveExecution"
+ resource: "arn:aws:states:us-east-2:account-id:execution:myStateMachine/*:*"
```
when there are only labeled distributed map runs
```diff
  action: ["states:DescribeExecution", "states:StopExecution"]
- resource: "arn:aws:states:us-east-2:account-id:stateMachine:myStateMachine:*"
+ resource: "arn:aws:states:us-east-2:account-id:execution:myStateMachine:*"
//...
+ action: "states:RedriveExecution"
+ resource: [
+   "arn:aws:states:us-east-2:account-id:execution:myStateMachine/myLabel1:*", 
+   "arn:aws:states:us-east-2:account-id:execution:myStateMachine/myLabel2:*"
+ ]
```

### Description of how you validated changes

Unit & Integration tests

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by Kasra-G** [comment]
I think I would rather rewrite this to not change the `grantRedriveExecution` permissions as that technically doesn't need to change as long as the state machine has the permissions to redrive execution on all of its own labeled executions. One way I can think of doing this is adding a new optional field to `grantExecutions` that lets you specify the map run label, which we then pass '*' to.

Another way is to simply do the same parsing logic we use to in `statemachine.executionArn` in `stage-graph.ts`

Alternatively, we could make the state machine `executionArn` public so we could add whatever permissions we want from the `bind` method without having to wrap it in a `grant` method.

It depends on what concepts we want visible to the end user. Personally, I'd rather hide that permissions can even be granted to map run labels separately as that is quite counter-intuitive and it's not clear what permissions have an effect. Even the IAM policy builder in the UI does not show this as being an option.

Curious about thoughts on this

File: packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts [hunk 1]
```diff
@@ -168,21 +168,11 @@ export class StateGraph {
...
-                resources: [`${stateMachine.stateMachineArn}:*`],
-              }),
-            ],
-          }),
-        }));
-
+        const distributedMapPolicy = new iam.Policy(stateMachine, 'DistributedMapPolicy');
+        stateMachine.grantStartExecution(distributedMapPolicy);
+        stateMachine.grantExecution(distributedMapPolicy, 'states:DescribeExecution', 'states:StopExecution');
+        stateMachine.grantRedriveExecution(distributedMapPolicy);
```
Comment (kumvprat) [inline packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts]: Based on the linked issue, it seems like the StartExecution, StopExecution and DescribeExecution permissions are not enough for the DistributedMap state to work and it needs the RedriveExecution permission also to function porperly. Is this summarization correct ? ([comment link](https://docs.aws.amazon.com/step-functions/latest/dg/iam-policies-eg-dist-map.html#iam-policy-redrive-dist-map))

File: packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts [hunk 2]
```diff
@@ -301,8 +301,16 @@ abstract class StateMachineBase extends Resource implements IStateMachine {
   /**
    * Grant the given identity permission to redrive the execution of the state machine
    */
-  public grantRedriveExecution(identity: iam.IGrantable) {
-    return this.grantExecution(identity, 'states:RedriveExecution');
+  public grantRedriveExecution(identity: iam.IGrantable): iam.Grant {
+    const executionArn = this.executionArn();
+    return iam.Grant.addToPrincipal({
+      grantee: identity,
+      actions: ['states:RedriveExecution'],
```
Comment (kumvprat) [inline packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts]: I see that the RedriveExecution policy can be further refined to the exact mapLabel, [docs](https://docs.aws.amazon.com/step-functions/latest/dg/iam-policies-eg-dist-map.html#iam-policy-redrive-dist-map)

The DistributedMap construct also has this property : [Code reference](https://github.com/abdelnn/aws-cdk/blob/main/packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map.ts#L78)

In the interest of least-privileges principle for policies, it should be possible to narrow down the resource arn to the specific mapLabel like the format : 
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "states:RedriveExecution"
      ],
      "Resource": "arn:aws:states:us-east-2:123456789012:execution:myStateMachineName/myMapRunLabel:*"
    }
  ]
}
```

and also let go of the line : `${executionArn}:*` as it's not required for the RedriveExecution permissions

File: packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map-redrive.ts [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+
+// describe the results of the execution
+const describe = testCase.assertions.awsApiCall('StepFunctions', 'describeExecution', {
+  executionArn: start.getAttString('executionArn'),
+});
+start.next(describe);
+
+// assert the results
+describe
+  .expect(ExpectedResult.objectLike({ status: 'FAILED' }))
```
Comment (kumvprat) [inline packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map-redrive.ts]: I am a bit confused here : How do we ensure that the state function fails on first try and execute a redrive of the state function? Would be good to call it out explicitly

File: packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts (hunk 1 above)
Comment (kumvprat) [reply packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts]: It could be that the faulty policy before was the reason as it had stateMachine arn instead of execution arn  : 
```
new iam.PolicyStatement({
                actions: ['states:DescribeExecution', 'states:StopExecution'],
                resources: [`${stateMachine.stateMachineArn}:*`],
              }),
```

**Review by kumvprat — COMMENTED** [review]
@Kasra-G Thanks for the contribution, this seems to be a niche one
I will add inline comments for this

Since it has been a while since the issue was reported, I am not sure if having the RedriveExecution policy on the DistributedMap state type is a default expectation(maybe it's called out in the documentation and I missed it, if so would be nice to link it in the PR description)

There are integration tests which cover the basic distributed map functionality : `packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.ts` which were working before(?)without explictly adding the `RedriveExecution` based policy. (trying to make a case for not needing the `RedriveExecution` policy by default)

File: packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map-redrive.ts (hunk 3 above)
Comment (Kasra-G) [reply packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map-redrive.ts]: I can make the code clearer here. The distributed map just attempts to get an s3 object. If it exists, it succeeds, if it doesn't, it fails.

On the first run, the object `pass-flag.txt` doesn't exist, so the state machine fails.
Between the first and second run, we upload the `pass-flag.txt`
On the 2nd run, the object exists, so the state machine succeeds.

File: packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts (hunk 2 above)
Comment (Kasra-G) [reply packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts]: Thanks for the comment. Perhaps I am misremembering, though I thought the docs stated needing `execution:stateMachineName:*` and `execution:stateMachineName/*:*` being necessary.

> in the interest of least-privileges principle for policies, it should be possible to narrow down the resource arn to the specific mapLabel like the format 

Using the autogenerated permissions when specifying a state machine in the console with a distributedmap as a source of truth, it seems that if there are any unlabeled distributed map states, the redrive policy becomes the following:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "states:RedriveExecution"
      ],
      "Resource": "arn:aws:states:us-east-2:123456789012:execution:myStateMachineName/*:*"
    }
  ]
}
```

When there are no unlabeled distributed map states, the policy becomes the following:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "states:RedriveExecution"
      ],
      "Resource": [
        "arn:aws:states:us-east-2:123456789012:execution:myStateMachineName/myMapRunLabel1:*",
        "arn:aws:states:us-east-2:123456789012:execution:myStateMachineName/myMapRunLabel2:*",
        "arn:aws:states:us-east-2:123456789012:execution:myStateMachineName/myMapRunLabel3:*",
         ...
      ]
    }
  ]
}
```

I can look into mimicking the functionality seen in the console.

I would love to be able to reuse `stateMachine.grantExecution()` and add an optional parameter specifying the map run label to grant to, but it seems there would be no way to do that without causing a breaking change (due to the `actions` vararg). I will workaround this by just creating the ARN to grant to manually. This will result in duplicate logic, unfortunately.

File: packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts (hunk 1 above)
Comment (Kasra-G) [reply packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts]: > StartExecution, StopExecution and DescribeExecution permissions are not enough for the DistributedMap state to work and it needs the RedriveExecution permission also to function porperly

Correct, it also needs RedriveExecution, otherwise, when the state machine is redriven, it will fail to redrive the map run.

> it could be that the faulty policy before was the reason as it had stateMachine arn instead of execution arn

This might have contributed to other users facing errors, but its not quite clear to me what the effect of the incorrect permissions are. The docs state you need  the permissions on the execution and not the state machine, so that change was made. The generated permissions in the console is not helpful in this regard as the resources being granted to is just `*` for the `DescribeExecution` permissions.

**Comment by Kasra-G** [comment]
Thanks for taking a look at the PR & the review. I have updated it and have a few responses:

> Since it has been a while since the issue was reported, I am not sure if having the RedriveExecution policy on the DistributedMap state type is a default expectation(maybe it's called out in the documentation and I missed it, if so would be nice to link it in the PR description)

I have updated the PR description with link to AWS docs talking about the permissions needed when adding a DistributedMap to a state machine. 

> There are integration tests which cover the basic distributed map functionality : `packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map.ts` which were working before(?)without explictly adding the `RedriveExecution` based policy. 

Yes, those integ tests work, but they do not test the redrive capability. That is why I have added a new integration test that tests the redrive capability for a state machine with a distributed map. 

> (trying to make a case for not needing the `RedriveExecution` policy by default)

The redrive permissions are added when creating a distributed map in a state machine via the AWS Console (and selecting the option to create a new role), but not in CDK

Just an additional note, I updated the new integ test `integ.distributed-map-redrive` to be a bit more comprehensive and test both distributedMap with a label and without a label, since the permissions are different.

Please let me know if there's any questions

**Comment by Kasra-G** [comment]
Sidenote: any idea why PR Build workflow isn't running?

**Comment by Kasra-G** [comment]
I also have changes that would fix the same underlying issue as https://github.com/aws/aws-cdk/pull/29913 before it was closed for inactivity. ~~I was going to open another PR for that one after this one, but since the changes conflict, I can merge the changes into the same PR to reduce overhead - just let me know.~~

I have decided to add on these changes to this PR, let me know if it should be a separate PR.

File: packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts (hunk 2 above)
Comment (kumvprat) [reply packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts]: >I would love to be able to reuse stateMachine.grantExecution() and add an optional parameter specifying the map run label to grant to, but it seems there would be no way to do that without causing a breaking change (due to the actions vararg). I will workaround this by just creating the ARN to grant to manually. This will result in duplicate logic, unfortunately.

Makes sense

File: packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts [hunk 4]
```diff
@@ -173,16 +187,375 @@ describe('State Machine', () => {
...
+      },
+      Roles: [
+        {
+          Ref: stateMachineRoleLogicalId,
+        },
+      ],
+    });
+  }),
+
+  test('Instantiate State Machine With Self Referencing Distributed Map State', () => {
```
Comment (kumvprat) [inline packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts]: Amazing that we are adding new tests : Are these possibilities allowed, like a self-referencing distributedmap state ?

It seems counter-intuitive that this use of the sfns will be helpful but if that is the case a few lines of comment above the test around when it's possible will be helpful

File: packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts [hunk 5]
```diff
@@ -163,28 +163,69 @@ export class StateGraph {
...
+  }
+
+  /**
+   * Returns all the states referenced in this StateGraph and all child StateGraphs
+   */
+  private getAllStatesInAllReferencedStateGraphs(): State[] {
+    const discoveredStateGraphs = new Set<StateGraph>();
+    const stateGraphsToSearch: StateGraph[] = [this];
+
+    // Do a DFS of all sub graphs
```
Comment (kumvprat) [inline packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts]: This seems like a BFS approach

File: packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts [hunk 6]
```diff
@@ -163,28 +163,69 @@ export class StateGraph {
...
+      service: 'states',
+      resourceName: `${Arn.split(stateMachine.stateMachineArn, ArnFormat.COLON_RESOURCE_NAME).resourceName}/${mapRunLabel}:*`,
+      arnFormat: ArnFormat.COLON_RESOURCE_NAME,
+    });
+  }
+
+  /**
+   * Returns all the states referenced in this StateGraph and all child StateGraphs
+   */
+  private getAllStatesInAllReferencedStateGraphs(): State[] {
```
Comment (kumvprat) [inline packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts]: In reply to your comment : [Link](https://github.com/aws/aws-cdk/pull/34760#issuecomment-3239413038), I think this should be a separate PR

Would make it easier to review once the sub-graph traversal logic is made separate, as the current PR mainly handles permissions

File: packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts [hunk 7]
```diff
@@ -163,28 +163,69 @@ export class StateGraph {
...
+      .filter(state => DistributedMap.isDistributedMap(state))
+      .map(state => state.toStateJson() as any);
+
+    if (distributedMapStates.length === 0) return;
+
+    const distributedMapPolicy = new iam.Policy(stateMachine, 'DistributedMapPolicy');
+    stateMachine.role.attachInlinePolicy(distributedMapPolicy);
+    stateMachine.grantStartExecution(distributedMapPolicy);
+    stateMachine.grantExecution(distributedMapPolicy, 'states:DescribeExecution', 'states:StopExecution');
+
```
Comment (kumvprat) [inline packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts:179]: > The redrive permissions are added when creating a distributed map in a state machine via the AWS Console (and selecting the option to create a new role), but not in CDK

It makes sense to add these permissions by default then , could you attach a screenshot of that i.e creation of the DistributeMap state via console ?

Comment (Kasra-G) [reply packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts:179]: When in Inline Map mode (not distributed)

image

Policies:
image

When in Distributed Mode:

image

Policies:
image

Statements in the policies:
image

Seems there also some eventbridge rules added, not sure what that is for. We can always change to add those event bridge permissions in CDK if its needed.

File: packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts (hunk 6 above)
Comment (Kasra-G) [reply packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts]: Sure, I can separate it out, though comments on the reference issue cite distributed maps inside parallel states not running because of missing permissions https://github.com/aws/aws-cdk/issues/28820#issuecomment-3050416978. I figured that could be in scope of this PR given it aims to fix these policies

I will then create a new issue and reference that in this PR to prevent the main discussion issue from being closed while the other PR is reviewed.

File: packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts (hunk 5 above)
Comment (Kasra-G) [reply packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts]: True, I will update. I had BFS at first but forgot which side of the array `push()` puts the elements in. Either way theres no real difference as we are just trying to find all reachable states.

File: packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts (hunk 4 above)
Comment (Kasra-G) [reply packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts]: I wont be the judge of if it is useful to customers but the console does allow self referencing distributed maps. Its certainly possible when combined with a `Choice` state, for example, to keep looping a state until some condition is met and break out the loop. The test ensures CDK supports this for DistributedMap (as it should any other state)

image

I can add a comment that explains why we are testing it, (to make sure theres no infinite loop in the BFS), but I won't explain why customers would do it; that seems out of scope.

**Comment by Kasra-G** [comment]
@kumvprat I have removed the fix for DistributedMap policies not showing up in nested StateGraphs and will raise a new PR as requested for that once when this one gets merged. Let me know if we actually want to put those changes in this PR. 

I will change the linked issue to a new one that is not the main discussion thread, as I do not want that thread accidentally getting resolved when there are still pending changes.

File: packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts (hunk 7 above)
Comment (kumvprat) [reply packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts:179]: Thanks for sharing this. I think the main thing we want is parity in how the sfn permissions are created in AWS console and in cdk

File: packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts (hunk 4 above)
Comment (kumvprat) [reply packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts]: That makes sense, we do want to point out why we are testing it. Customers would be free to use the functionality if it's available.

A comment on the test would help us understand in future why is this being tested out

**Comment by Kasra-G** [comment]
> Are the changes to just the index.js for aws-lambda-python-alphs and aws-ses packages integ tests needed

Probably not. I think those integ tests failed on my first version of the PR so I ran them to update the files but there wasn't really any changes. I'll try resetting those changes. I'm actually still getting CHANGED integ tests in the `aws-lambda-python-alpha` in my local but I will just ignore those, probably something wrong with my local environment.

**Comment by Kasra-G** [comment]
Apologies, just noticed I have committed snapshot files for an integ test that I renamed all the way back in my first or second pr revision. I will remove those snapshot files.

**Review by kumvprat — APPROVED** [review]
Thank you for detailed work on the PR
