### PR TITLE
fix(ec2): default gateway endpoint fails without private subnets

### LINKED ISSUE #7619: Cannot create VPC without NAT Gateways
I am trying to create a VPC without NAT Gateways. And I do not need private subnets.

Received error message `There are no 'Private' subnet groups in this VPC. Available types: Isolated,Public` when trying to create a new VPC via TypeScript CDK without a Private subnet.

```ts
this.vpc = new Vpc(this, 'Vpc', {
  cidr: '10.180.0.0/16',
  vpnGateway: false,
  subnetConfiguration: [
    { cidrMask: 23, name: 'Public', subnetType: SubnetType.PUBLIC },
    { cidrMask: 23, name: 'Isolated', subnetType: SubnetType.ISOLATED },
  ]
})
```

I have also tried a workaround - creating Private subnet but with amount of NAT Gateways set to 0. And then I received error message `If you do not want NAT gateways (natGateways=0), make sure you don't configure any PRIVATE subnets in 'subnetConfiguration' (make them PUBLIC or ISOLATED instead)`.

```ts
this.vpc = new Vpc(this, 'Vpc', {
  cidr: '10.180.0.0/16',
  vpnGateway: false,
  natGateways: 0,
  natGatewaySubnets: { subnets: [] },
  subnetConfiguration: [
    { cidrMask: 23, name: 'Public', subnetType: SubnetType.PUBLIC },
    { cidrMask: 23, name: 'Private', subnetType: SubnetType.PRIVATE },
    { cidrMask: 23, name: 'Isolated', subnetType: SubnetType.ISOLATED },
  ]
})
```

I know the second scenario is not a bug. It's just here to show there is no successful workaround I could find.

### Environment

  - **CLI Version  1.35.0 (build e0810c8):**
  - **Framework Version MacBook Pro (15-inch, 2018):**
  - **OS MacOS 10.15.3 (19D76):**
  - **Language TypeScript:**

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
### Commit Message
fix(ec2): default gateway endpoint fails without private subnets

Gateway endpoints can't be added to a VPC that doesn't have private
subnets.

Unless indicated otherwise, make the gateway endpoints routable from all
subnets. It'll only be routable from inside the VPC anyway (since
it will have a private IP address).

Fixes #7619.
### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts [hunk 1]
```diff
@@ -113,7 +113,10 @@ export interface GatewayVpcEndpointOptions {
   /**
    * Where to add endpoint routing.
    *
-   * @default private subnets
+   * By default, this endpoint will be routable from all subnets in the VPC.
+   * Specify a list of subnet selection objects here to be more specific.
+   *
```
Comment (eladb) [inline packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts:118]: Maybe provide an inline "@example". The name `subnets` has been confusing people in untyped languages like Python since the dawn of time.
