### PR TITLE
fix: customer aspect cannot add Tags if a BucketNotifications construct is present

### LINKED ISSUE #33943: Adding an aspect to Bucket with S3 notifications leads to an error
### Describe the bug

In our setup we use an aspect, which adds common tags to most of the resources (like "Name" tag).
Unfortunately, this aspect stopped working after update to 2.181.0 .

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

2.180.0

### Expected Behavior

Tags should be applied, CDK should be executed successfully.

### Current Behavior

'Error: Cannot invoke Aspect Tag with priority 200 on node CdkReproStack/test-bucket/Notifications: an Aspect Object with a lower priority (500) was already invoked on this node.'

### Reproduction Steps

```csharp
    public class CdkReproStack : Stack
    {
        internal CdkReproStack(Construct scope, string id, IStackProps props = null) : base(scope, id, props)
        {
            var bucket = new Bucket(this, "test-bucket", new BucketProps
            {
                BucketName = "test-bucket"
            });

            var function = new Function(this, "test-function", new FunctionProps
            {
                FunctionName = "test-function",
                Handler = "handler",
                Runtime = Runtime.NODEJS_22_X,
                Code = Code.FromInline("function(){ }")
            });

            function.AddEventSource(new S3EventSourceV2(bucket, new S3EventSourceProps
            {
                Events = [EventType.OBJECT_CREATED]
            }));

            Aspects.Of(this).Add(new TagNameAspect(), new AspectOptions { Priority = 10 });
        }
    }

    class TagNameAspect : Amazon.JSII.Runtime.Deputy.DeputyBase, IAspect
    {
        public void Visit(IConstruct node)
        {
            var name = node switch
            {
                Bucket => "test-bucket-name",
                _ => null
            };

            // Auto-generated names start with $, we skip them.
            if (name != null)
            {
                Tags.Of(node).Add("Name", name.ToLowerInvariant(), new TagProps { Priority = 10 });
            }
        }
    }
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.1004.0

### Framework Version

v2.186.0

### Node.js Version

v22.5.1

### OS

AmazonLinux

### Language

.NET

### Language Version

net8.0

### Other information

I have tried adding `@aws-cdk/core:aspectStabilization` feature flag, but it changes nothing.

### PR DESCRIPTION
**Pull request by rix0rrr**
The title refers to a specific case in which we discovered this, but the problem was more general.

Now that Aspects have a priority, we want to execute based on priority as the primary sort key. To make sure we don't make mistakes, the new AspectsV2 invocation (enabled with flag `@aws-cdk/core.aspectStabilization: true`) throws an error if it detects a violation of the strict priority execution order.

Because of the moment aspects are looked up and sorted by priority, this currently goes wrong if:

- Aspects with a low and high priority order (say, 100 and 700) are already present in the construct tree
- The invocation of the low-priority Aspect adds another Aspect with a priority in between 100 and 700.

The reason is that we used to look up the aspects before iterating, and iterate over them. At that point we have the list `[100, 700]`, and we invoke both. Then, when we go around again, the new list is `[100, 500, 700]` with the `500` Aspect having not been invoked yet -- but also the Aspect with priority `700` already having been invoked. If we invoke `500` at that point, we would have inverted the priority order, so we fail instead.

That is undesirable: what we *should* have done is noticed that `500` got inserted between `100` and `700` and do that next.

Currently achieve that with the following:

- We associate a global revision number with the entire construct tree, at the root.
- Every time an aspect gets added, we increment that number.
- This allows us to detect Aspect order cache validations, so we can abort what we're doing and recalculate the tree.

The system of inserting and recalculating could probably all be made more efficient, but aspects adding aspects should be relatively rare so until we have evidence that it is too expensive, this will do for now.

In the specific case reported for this, a customer Aspect with priority 10 adds a Tag Aspect (priority 200) while the `BucketNotification` construct also adds an Aspect on itself with priority 500. The mere presence of this `BucketNotification` construct with its self-added Aspect prevents any Aspect from adding tags.

Closes #33943.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/core/lib/private/synthesis.ts [hunk 1]
```diff
@@ -310,25 +311,38 @@ function invokeAspectsV2(root: IConstruct) {
       const lastInvokedAspect = invoked[invoked.length - 1];
       if (lastInvokedAspect && lastInvokedAspect.priority > aspectApplication.priority) {
         throw new Error(
-          `Cannot invoke Aspect ${aspectApplication.aspect.constructor.name} with priority ${aspectApplication.priority} on node ${node.path}: an Aspect ${lastInvokedAspect.aspect.constructor.name} with a lower priority (${lastInvokedAspect.priority}) was already invoked on this node.`,
+          `Cannot invoke Aspect ${aspectApplication.aspect.constructor.name} with priority ${aspectApplication.priority} on node ${node.path}: an Aspect ${lastInvokedAspect.aspect.constructor.name} with a lower priority (added at ${lastInvokedAspect.construct.node.path} with priority ${lastInvokedAspect.priority}) was already invoked on this node.`,
         );
       }
 
-      aspectApplication.aspect.visit(construct);
+      aspectApplication.aspect.visit(construct); // +500
```
Comment (iliapolo) [inline packages/aws-cdk-lib/core/lib/private/synthesis.ts:318]:
```suggestion
      aspectApplication.aspect.visit(construct);
```

**Review by iliapolo — APPROVED** [review]
