### PR TITLE
fix(lambda-nodejs): do not require a frozen lockfile for bun

### LINKED ISSUE #32906: (aws-lambda-nodejs): bun depenedencies fail with `error: lockfile had changes, but lockfile is frozen`
### Describe the bug

When a `bun` lockfile contains additional entries compared to what's installed in the docker container at bundling time, the bundling fails with this error:

```shell
error: lockfile had changes, but lockfile is frozen
note: try re-running without --frozen-lockfile and commit the updated lockfile
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

N/A - this is new behavior I implemented against #31753

### Expected Behavior

I expect changes to the lockfile to be allowed and the synth to pass.

### Current Behavior

```shell
error: lockfile had changes, but lockfile is frozen
note: try re-running without --frozen-lockfile and commit the updated lockfile
```

### Reproduction Steps

See https://github.com/blimmer/cdk-bug-reports/pull/3 for a working repro case.

### Possible Solution

We need to not enforce `--frozen-lockfile`, like we do for other package managers: https://github.com/aws/aws-cdk/blob/fb2b229912f7400f810959eeb51008e680216718/packages/aws-cdk-lib/aws-lambda-nodejs/lib/package-manager.ts#L34-L49

### Additional Information/Context

_No response_

### CDK CLI Version

2.175.1

### Framework Version

_No response_

### Node.js Version

22 LTS

### OS

MacOS

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by blimmer**
### Issue #32906

Closes #32906.

### Reason for this change

When I implemented `bun` support, I accidentally used `--frozen-lockfile`, which caused issues when the lockfile contained additional entries other than what's being bundled in the docker container.

The issue has a small repro-case.

### Description of changes

I removed the `--frozen-lockfile` flag, which resolved the problem.

### Describe any new or updated permissions being added

N/A

### Description of how you validated changes

I added an additional package to the `bun.lockb` file in the integration test. This caused the issue to occur in the test suite. Once I made the changes in this PR, the test started passing again.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.dependencies-bun.ts [hunk 1]
```diff
@@ -10,7 +10,7 @@ const stack = new cdk.Stack(app, 'TestStack');
 
 const handler = new lambda.NodejsFunction(stack, 'Function', {
   entry: path.join(__dirname, 'integ-handlers/bun/dependencies-bun.ts'),
-  runtime: Runtime.NODEJS_20_X,
+  runtime: Runtime.NODEJS_22_X,
```
Comment (blimmer) [inline packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.dependencies-bun.ts:13]: Just bumped this to make the PR linter happy and to force re-run the integration test.

File: packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ-handlers/bun/_package.json [hunk 2]
```diff
@@ -0,0 +1,8 @@
+{
```
Comment (blimmer) [inline packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ-handlers/bun/_package.json:1]: cc @rix0rrr - I see that you were working with this setup in #33022. Does this setup seem reasonable to you? I need to make sure that the lockfile will be modified during bundling to avoid the origin issue this PR fixes.

**Comment by blimmer** [comment]
It looks like the codecoverage collection step is failing on all PRs right now.

File: packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ-handlers/bun/_package.json (hunk 2 above)
Comment (rix0rrr) [reply packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ-handlers/bun/_package.json:1]: Hey @blimmer,

It seems as reasonable as anything. I honestly don't quite know what the best way is to go about updating this test, I know it gave me a lot of grief in my previous PR.

I confess I haven't dived into the possible solutions too deeply, so you have more context than I do on this right now. If you think this is the way to go, I'll happily give it a shot!

File: packages/aws-cdk-lib/aws-lambda-nodejs/lib/package-manager.ts [hunk 3]
```diff
@@ -50,7 +50,9 @@ export class PackageManager {
       case LockFile.BUN:
         return new PackageManager({
           lockFile: LockFile.BUN,
-          installCommand: logLevel && logLevel !== LogLevel.INFO ? ['bun', 'install', '--frozen-lockfile', '--backend', 'copyfile', '--silent'] : ['bun', 'install', '--frozen-lockfile', '--backend', 'copyfile'],
+          // Bun's default is to not force `--frozen-lockfile`, so it's not specified here. If they ever add a
+          // flag to explicitly disable it, we should add it here. https://github.com/oven-sh/bun/issues/16387
+          installCommand: logLevel && logLevel !== LogLevel.INFO ? ['bun', 'install', '--backend', 'copyfile', '--silent'] : ['bun', 'install', '--backend', 'copyfile'],
```
Comment (samson-keung) [inline packages/aws-cdk-lib/aws-lambda-nodejs/lib/package-manager.ts:55]: @blimmer Thanks for continuing to work on this. I am not familiar with `bun` so I have a few questions hoping you can help.

1. It seems that `bun` is in early stage and looks like they changed the lockfile to be text based now ([bun's blog](https://bun.sh/blog/bun-lock-text-lockfile)). As they evolve, I expect more changes like these in the future. Should we mark `bun` support in CDK as experimental for now? Because otherwise, we will have to maintain backward compatibility for old `bun` behaviour.
3. Will removing `--frozen-lockfile` have impact to CDK users who rely on or expects having `--frozen-lockfile` on?  I see @suds-sky was interested in the original `bun` support feature requests. @suds-sky maybe you would have some input as well? I worry about this being a potential breaking change.

**Review by samson-keung — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ-handlers/bun/_package.json (hunk 2 above)
Comment (blimmer) [reply packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ-handlers/bun/_package.json:1]: Gotcha. I TDD'ed this, and before my change, this test was broken. So I think this is as good as anything 👍

File: packages/aws-cdk-lib/aws-lambda-nodejs/lib/package-manager.ts (hunk 3 above)
Comment (blimmer) [reply packages/aws-cdk-lib/aws-lambda-nodejs/lib/package-manager.ts:55]: Hey @samson-keung - thank you for your review.

### Experimental?

> It seems that bun is in early stage and looks like they changed the lockfile to be text based now ([bun's blog](https://bun.sh/blog/bun-lock-text-lockfile)). As they evolve, I expect more changes like these in the future. Should we mark bun support in CDK as experimental for now? Because otherwise, we will have to maintain backward compatibility for old bun behaviour.

Yes, `bun` is evolving rapidly. I filed https://github.com/aws/aws-cdk/issues/33270 a while back to support the text-based lockfile. From the linked blog:

> We're planning to make bun.lock the default in Bun v1.2.0. In the meantime, we continue to support the binary bun.lockb format and will do so for awhile.

So it sounds like, for proper CDK support, we'd want to identify and support both. I did not tackle that as part of this PR, though, since it would increase scope and the behavior today is broken for most people.

I'm not very familiar with experimental features, so I'm open to additional ideas/discussion of this!

### Affecting Existing Users?

> Will removing --frozen-lockfile have impact to CDK users who rely on or expects having --frozen-lockfile on? I see @suds-sky was interested in the original bun support feature requests. @suds-sky maybe you would have some input as well? I worry about this being a potential breaking change.

I feel confident that this is not a breaking change for existing users of this feature. This bug is caused by having a `package.json`/`bun.lockb` file with additional packages from what's being bundled in-container via the `nodeModules` property.

When a `nodeModules` array is passed, this logic executes: https://github.com/aws/aws-cdk/blob/7538a8431290fe76d9ad6bbf80977eb2cb17e007/packages/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.ts#L285-L294

As part of that logic, the lockfile is copied over, and `bun install <packagename>` is run. But, because the lockfile contains other dependencies, the error is thrown.

This is why we don't enforce a frozen lockfile on any other package managers.

So, the only way this feature would have _worked_ for existing users is if:

a) they didn't specify any `nodeModules`, or;
b) their lockfile _only_ contained the packages passed as `nodeModules`.

Therefore, I think it's OK to make this change without breaking existing users.

Comment (samson-keung) [reply packages/aws-cdk-lib/aws-lambda-nodejs/lib/package-manager.ts:55]: > Experimental?

Thank you for sharing your thoughts. I don't have historical context on how CDK typically add experimental features either. I will check with the team. But this shouldn't be a blocker on this PR.

> Affecting Existing Users?

Thank you for the clear explanation so I can understand how this part work! I agree that it shouldn't be a breaking change.

**Review by samson-keung — APPROVED** [review]

**Review by samson-keung — APPROVED** [review]
