### PR TITLE
fix(toolkit): stop 'cdk doctor' from printing AWS_ variables

### LINKED ISSUE #1931: cdk doctor potentially exposes secrets
`cdk doctor` emits all environment variables that begin with `AWS_`, including AWS credentials.

### PR DESCRIPTION
**Pull request by rix0rrr**
Fixes #1931.

----

### Pull Request Checklist

* [ ] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [ ] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
  - __Design__: For significant features, design document added to `design` folder
* [ ] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [ ] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/aws-cdk/lib/commands/doctor.ts [hunk 1]
```diff
@@ -68,3 +68,10 @@ function displayCdkEnvironmentVariables() {
   }
   return healthy;
 }
+
+function anonymizeAwsVariable(name: string, value: string) {
+  if (name === 'AWS_ACCESS_KEY_ID') { return value.substr(0, 4) + '*'.repeat(Math.max(0, value.length - 4)); }
+  if (name === 'AWS_SECRET_ACCESS_KEY') { return '*'.repeat(value.length); }
```
Comment (RomainMuller) [inline packages/aws-cdk/lib/commands/doctor.ts]: No strong feelings, but I'd usually literally output `<redacted>` for those instead of a string of `*`s.

File: packages/aws-cdk/lib/commands/doctor.ts [hunk 2]
```diff
@@ -68,3 +68,10 @@ function displayCdkEnvironmentVariables() {
...
+  if (name === 'AWS_SESSION_TOKEN') { return '*'.repeat(50); }
```
Comment (RomainMuller) [inline packages/aws-cdk/lib/commands/doctor.ts]: No strong feelings, but I'd usually literally output `<redacted>` for those instead of a string of `*`s.

File: packages/aws-cdk/lib/commands/doctor.ts [hunk 3]
```diff
@@ -68,3 +68,10 @@ function displayCdkEnvironmentVariables() {
   }
   return healthy;
 }
+
+function anonymizeAwsVariable(name: string, value: string) {
+  if (name === 'AWS_ACCESS_KEY_ID') { return value.substr(0, 4) + '*'.repeat(Math.max(0, value.length - 4)); }
```
Comment (RomainMuller) [inline packages/aws-cdk/lib/commands/doctor.ts]: And here, I would put `####<redacted>`. I also don't know whether the "common" practice is to show few first or few last... Maybe should research some weak evidence of what others do (we don't want to cause leaking a head when other tools leak the tail - that'd be us giving out additional info)?

**Comment by RomainMuller** [comment]
Would be nice to have a test for this...

**Comment by rix0rrr** [comment]
> Would be nice to have a test for this...

Needs to be an integ test, so goes into a different package.

File: packages/aws-cdk/lib/commands/doctor.ts (hunk 3 above)
Comment (rix0rrr) [reply packages/aws-cdk/lib/commands/doctor.ts]: I'm leaking the first 4 characters on purpose, because they tell us the *type* of access key used:

* AKIA for long-lived (user) keys.
* ASIA for short-lived (session, role) keys.

These are standardized and not part of the secret material.
