### PR TITLE
fix(dynamodb): replication regions are incompatible with resource policies in TableV2 and feature flag

### LINKED ISSUE #30705: dynamodb: Replication regions are incompatible with resource policies in TableV2
### Describe the bug

As stated in the [AWS documentation for resource policies](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/rbac-considerations.html), we cannot create a replica and add a resource policy to that replica in the same stack update.

This means every time we want to add a new replication region in the CDK we need to somehow not add the resource policy to that new region for the initial deployment. TableV2 allows us to customize each replica, including whether or not we want a resource policy, but it too eagerly adds the resource policy under TableV2 construct and we are unable to override it with an `undefined` to not include any resourcePolicy.

### Expected Behavior

When adding a new replica region that specifies an undefined resource policy, TableV2 should not add the resource policy defined within it's construct.

### Current Behavior

TableV2 eagerly adds the resource policy to all replicas, even when specifying it should be undefined, and the deployment fails. The only way to add a new replica without adding a resource policy is to first deploy a stack update that creates the new replica and removes the resource policy from **all** other replicas. Then following up with a second stack update that re-adds the resource policy to all replicas. This means between the first and second update none of the tables will have a resource policy attached.

### Reproduction Steps

Using a TableV2 WITHOUT replicas, but WITH the resource policy and this works
```
new TableV2(this, `MyTable-${stage}`, {
      pointInTimeRecovery: true,
      partitionKey: {
        name: 'key',
        type: AttributeType.STRING,
      },
      tableName: 'MyTable',
      resourcePolicy: tablePolicyDocument,
    });
```
If I then try to deploy WITH a replica (us-east-1) and WITH a resource policy, it fails due same stack update error
```
new TableV2(this, `MyTable-${stage}`, {
      pointInTimeRecovery: true,
      partitionKey: {
        name: 'key',
        type: AttributeType.STRING,
      },
      tableName: 'MyTable',
      replicas: [{ region: 'us-east-1' }],
      resourcePolicy: tablePolicyDocument,
    });
```
When I delete the stack and restart and try to deploy WITH a replica (us-east-1) but WITHOUT the resource policy, this succeeds
```
new TableV2(this, `MyTable-${stage}`, {
      pointInTimeRecovery: true,
      partitionKey: {
        name: 'key',
        type: AttributeType.STRING,
      },
      tableName: 'MyTable',
      replicas: [{ region: 'us-east-1' }]
    });
```
When I then add the resource policy WITHOUT adding a new replica region, this works and the resource policy is added to both the table in us-west-2 and us-east-1
```
new TableV2(this, `MyTable-${stage}`, {
      pointInTimeRecovery: true,
      partitionKey: {
        name: 'key',
        type: AttributeType.STRING,
      },
      tableName: 'MyTable',
      replicas: [{ region: 'us-east-1' }],
      resourcePolicy: tablePolicyDocument,
    });
```
But when I then try to add another region (us-east-2), it then fails with the same stack update error
```
new TableV2(this, `MyTable-${stage}`, {
      pointInTimeRecovery: true,
      partitionKey: {
        name: 'key',
        type: AttributeType.STRING,
      },
      tableName: 'MyTable',
      replicas: [{ region: 'us-east-1' }, { region: 'us-east-2' }],
      resourcePolicy: tablePolicyDocument,
    });
```
If I try to override the resourcePolicy in the new replica to not include one, TableV2 still adds `tablePolicyDocument` to it in the CFN template and the deployment fails with the same stack update error
```
new TableV2(this, `MyTable-${stage}`, {
      pointInTimeRecovery: true,
      partitionKey: {
        name: 'key',
        type: AttributeType.STRING,
      },
      tableName: 'MyTable',
      replicas: [{ region: 'us-east-1' }, { region: 'us-east-2', resourcePolicy: undefined }],
      resourcePolicy: tablePolicyDocument,
    });
```

I've so far been able to work around this by using the L1 escape hatch with `CfnGlobalTable` and manually specifying each replica and selectively adding the resource policy to each replica.

```
    new CfnGlobalTable(this, `MyTable-${stage}`, {
      tableName: 'MyTable',
      attributeDefinitions: [{ attributeName: 'key', attributeType: AttributeType.STRING }],
      keySchema: [{ attributeName: 'key', keyType: 'HASH' }],
      replicas: [
        {
          pointInTimeRecoverySpecification: {
            pointInTimeRecoveryEnabled: true,
          },
          region: 'us-west-2', // main table region
          resourcePolicy: { policyDocument: tablePolicyDocument },
        },
        {
          pointInTimeRecoverySpecification: {
            pointInTimeRecoveryEnabled: true,
          },
          region: 'us-east-1',
        },
      ],
      billingMode: 'PAY_PER_REQUEST',
      streamSpecification: { streamViewType: 'NEW_AND_OLD_IMAGES' },
    });
```

### Possible Solution

The easiest solution is to update [this line](https://github.com/aws/aws-cdk/blob/9437b4dbbea15db18ff2991d410e033cc3437001/packages/aws-cdk-lib/aws-dynamodb/lib/table-v2.ts#L618) from:

>const resourcePolicy = props.resourcePolicy ?? this.tableOptions.resourcePolicy;

to

>const resourcePolicy = props.resourcePolicy

and require all replicas to manually include a resourcePolicy if one is desired.

Ideally, the construct could allow `null` and when `null` is specified in a specific replica, no resourcePolicy is added to that replica even when one is defined in the TableV2 itself

```
new TableV2(this, `MyTable-${stage}`, {
      pointInTimeRecovery: true,
      partitionKey: {
        name: 'key',
        type: AttributeType.STRING,
      },
      tableName: 'MyTable',
      // us-east-2 should not have tablePolicyDocument added in the template
      replicas: [{ region: 'us-east-1' }, { region: 'us-east-2', resourcePolicy: null }], 
      resourcePolicy: tablePolicyDocument,
    });
```

### Additional Information/Context

_No response_

### CDK CLI Version

2.136.0

### Framework Version

_No response_

### Node.js Version

v18.18.2

### OS

Linux

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by LeeroyHannigan**
### Issue # (if applicable)

Closes #30705

### Reason for this change

Resource policies were shared across all replicas in a region.

### Description of changes

Changed the logic to only apply resource policy to the local replica region, or to specific replicas only when defined.

### Description of how you validated changes

yes

### Checklist
- [X] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-dynamodb/lib/table-v2.ts [hunk 1]
```diff
@@ -664,7 +665,14 @@ export class TableV2 extends TableBaseV2 {
...
     const contributorInsights = props.contributorInsights ?? this.tableOptions.contributorInsights;
-    const resourcePolicy = props.resourcePolicy ?? this.tableOptions.resourcePolicy;
+    /*
+    * Feature flag set as the following may be a breaking change.
+    * @see https://github.com/aws/aws-cdk/pull/31097
+    * @see https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/cx-api/FEATURE_FLAGS.md
+    */
+    const resourcePolicy = FeatureFlags.of(this).isEnabled(cxapi.DYNAMODB_TABLEV2_RESOURCE_POLICY_PER_REPLICA)
+      ? (this.region ? this.tableOptions.resourcePolicy : props.resourcePolicy)
+      : (props.region === this.region ? this.tableOptions.resourcePolicy : props.resourcePolicy) || undefined;
```
Comment (GavinZZ) [inline packages/aws-cdk-lib/aws-dynamodb/lib/table-v2.ts:675]: On feature flag false case,  can we stick to the original behaviour?

File: packages/aws-cdk-lib/cx-api/lib/features.ts [hunk 2]
```diff
@@ -108,6 +108,7 @@ export const LOG_API_RESPONSE_DATA_PROPERTY_TRUE_DEFAULT = '@aws-cdk/custom-reso
 export const S3_KEEP_NOTIFICATION_IN_IMPORTED_BUCKET = '@aws-cdk/aws-s3:keepNotificationInImportedBucket';
 export const USE_NEW_S3URI_PARAMETERS_FOR_BEDROCK_INVOKE_MODEL_TASK = '@aws-cdk/aws-stepfunctions-tasks:useNewS3UriParametersForBedrockInvokeModelTask';
 export const REDUCE_EC2_FARGATE_CLOUDWATCH_PERMISSIONS = '@aws-cdk/aws-ecs:reduceEc2FargateCloudWatchPermissions';
+export const DYNAMODB_TABLEV2_RESOURCE_POLICY_PER_REPLICA = '@aws-cdk/aws-dynamodb:resourcePolicyPerReplica';
```
Comment (GavinZZ) [inline packages/aws-cdk-lib/cx-api/lib/features.ts:111]: Can you add this to https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/cx-api/README.md

File: packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb-v2.policy.ts [hunk 3]
```diff
@@ -4,7 +4,11 @@ import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
 import * as iam from 'aws-cdk-lib/aws-iam';
 import { IntegTest } from '@aws-cdk/integ-tests-alpha';
 
-const app = new App();
+const app = new App({
+  postCliContext: {
+    '@aws-cdk/aws-dynamodb:resourcePolicyPerReplica': false,
+  },
+});
```
Comment (GavinZZ) [inline packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb-v2.policy.ts:11]: Can we add a test for `true` case?

**Review by GavinZZ — CHANGES_REQUESTED** [review]
Thanks for drafting the changes!

**Review by GavinZZ — APPROVED** [review]

**Review by GavinZZ — DISMISSED** [review]

**Review by GavinZZ — APPROVED** [review]
