### PR TITLE
fix(sfn): can't override toStateJson() from other languages

### LINKED ISSUE #14639: (aws_stepfunctions): Overriding to_stete_json() fails if result_path=sfn.JsonPath.DISCARD
Overriding `to_stete_json()` on the `DynamoUpdateItem` construct raises an exception if `result_path=sfn.JsonPath.DISCARD`

### Reproduction Steps

Run `cdk synth` on the provided sample

```python
from aws_cdk import aws_dynamodb as dynamodb
from aws_cdk import aws_stepfunctions as sfn
from aws_cdk import aws_stepfunctions_tasks as tasks
from aws_cdk import core


class CustomDynamoUpdateItem(tasks.DynamoUpdateItem):
    def to_state_json(self):
        return super().to_state_json()


class TestStack(core.Stack):
    def __init__(self, scope: core.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        table = dynamodb.Table(
            self,
            "Table",
            partition_key=dynamodb.Attribute(
                name="id", type=dynamodb.AttributeType.STRING
            ),
        )
        sfn.StateMachine(
            self,
            "StateMachine",
            definition=CustomDynamoUpdateItem(
                self,
                "Update Item",
                table=table,
                result_path=sfn.JsonPath.DISCARD,
                key={
                    "id": tasks.DynamoAttributeValue.from_string(
                        sfn.JsonPath.string_at("$.id")
                    )
                },
                update_expression="SET value=:value",
                expression_attribute_values={
                    ":value": tasks.DynamoAttributeValue.from_string(
                        sfn.JsonPath.string_at("$.value")
                    )
                },
            ),
        )
```

### What did you expect to happen?

It should produce a valid cloudformation stack.

### What actually happened?

It produces this error:

```
jsii.errors.JavaScriptError: 
  Error: Got 'undefined' for non-optional instance of {"type":{"primitive":"json"}}
      at nullAndOk (/private/var/folders/m1/lyhg812d7wn8tgcxk8_xmhbm0000gp/T/tmp84la7qu9/lib/program.js:9318:23)
      at Object.deserialize (/private/var/folders/m1/lyhg812d7wn8tgcxk8_xmhbm0000gp/T/tmp84la7qu9/lib/program.js:8880:25)
      at Kernel._toSandbox (/private/var/folders/m1/lyhg812d7wn8tgcxk8_xmhbm0000gp/T/tmp84la7qu9/lib/program.js:8505:69)
      at /private/var/folders/m1/lyhg812d7wn8tgcxk8_xmhbm0000gp/T/tmp84la7qu9/lib/program.js:9007:81
      at mapValues (/private/var/folders/m1/lyhg812d7wn8tgcxk8_xmhbm0000gp/T/tmp84la7qu9/lib/program.js:9341:35)
      at Object.deserialize (/private/var/folders/m1/lyhg812d7wn8tgcxk8_xmhbm0000gp/T/tmp84la7qu9/lib/program.js:9007:36)
      at Object.deserialize (/private/var/folders/m1/lyhg812d7wn8tgcxk8_xmhbm0000gp/T/tmp84la7qu9/lib/program.js:8884:59)
      at Kernel._toSandbox (/private/var/folders/m1/lyhg812d7wn8tgcxk8_xmhbm0000gp/T/tmp84la7qu9/lib/program.js:8505:69)
      at DynamoUpdateItem.value (/private/var/folders/m1/lyhg812d7wn8tgcxk8_xmhbm0000gp/T/tmp84la7qu9/lib/program.js:8333:41)
      at StateGraph.toGraphJson (/private/var/folders/m1/lyhg812d7wn8tgcxk8_xmhbm0000gp/T/jsii-kernel-6nqdST/node_modules/@aws-cdk/aws-stepfunctions/lib/state-graph.js:106:43)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 15, in <module>
    TestStack(app, "TestStack")
  File "/Users/weaveri/test/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/weaveri/test/test/test_stack.py", line 23, in __init__
    sfn.StateMachine(
  File "/Users/weaveri/test/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/weaveri/test/.venv/lib/python3.8/site-packages/aws_cdk/aws_stepfunctions/__init__.py", line 5100, in __init__
    jsii.create(StateMachine, self, [scope, id, props])
  File "/Users/weaveri/test/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 287, in create
    obj.__jsii_ref__ = _callback_till_result(self, response, CreateResponse)
  File "/Users/weaveri/test/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 220, in _callback_till_result
    response = kernel.sync_complete(response.cbid, None, result, response_type)
  File "/Users/weaveri/test/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 386, in sync_complete
    return self.provider.sync_complete(
  File "/Users/weaveri/test/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 382, in sync_complete
    resp = self._process.send(_CompleteRequest(complete=request), response_type)
  File "/Users/weaveri/test/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Got 'undefined' for non-optional instance of {"type":{"primitive":"json"}}
Subprocess exited with error 1
```

### Environment

  - **CDK CLI Version  :** 1.103.0
  - **Framework Version:** 1.103.0
  - **Node.js Version:** v14.16.0
  - **OS               :** macOS Catalina
  - **Language (Version):** Python 3.8.2

### Other

I'm attempting to use `States.Format()` in the update expression to parameterize the index of a dynamodb list based on the index of a Map state. Because `States.Format()` isn't supported yet (#11286) my attempted work-around is to override `to_stete_json()`. However, that's producing the above error.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by RomainMuller**
If any part of a state's JSON representation is `null`, that value will be replaced by `undefined` when jsii sends data to the other language, resulting in a change of semantics.

Multi-language APIs cannot differentiate between `null` and `undefined` as non-JS languages typically fail to distinguish between them... In order to address that, a `JsonNull` value was added which serializes to `null` (via Javascript's standard `toJSON` method), which must be used in such cases where `null` may need to cross the language boundary.

The `JsonPath.DISCARD` value is now a string-token representation of the `JsonNull` instance.

Fixes #14639
Fixes https://github.com/aws/jsii/issues/3999

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by Naumel — APPROVED** [review]

File: packages/@aws-cdk/aws-stepfunctions/lib/states/state.ts [hunk 1]
```diff
@@ -579,7 +580,7 @@ export function renderJsonPath(jsonPath?: string): undefined | null | string {
   if (jsonPath === undefined) { return undefined; }
   if (jsonPath === JsonPath.DISCARD) { return null; }
```
Comment (beck3905) [inline packages/@aws-cdk/aws-stepfunctions/lib/states/state.ts:581]: I think this line might still need to be updated for this to work properly.  Even though `JsonPath.DISCARD` has been updated to a JsonNull token, this line will still evaluate truthy and return null, which in other languages like Python would translate to `undefined`.  Perhaps this should return a JsonNull token as well?
