### PR TITLE
fix(stepfunctions-tasks): cannot specify part of execution data or task context as input to the `RunLambda` service integration

### LINKED ISSUE #7371: StepFunctions - RunLambdaTask with Payload not working
I am seeing more issues with RunLambdaTask:
below is the code which works with InvokeFunction..$.Payload has my model in json string
```csharp
 Task = new InvokeFunction(lambdaFunction),                
                InputPath = "$.Payload",
                ResultPath = "$.lambdaResult",
                OutputPath = "$.lambdaResult"
```

The same code when using RunLambdaTask...not sure how to access $.Payload in the Payload property, so that it can be passed over to the Lambda function? This is what I have
```csharp
Task = new RunLambdaTask(lambdaFunction,
                            new RunLambdaTaskProps 
                                        { Payload = new Dictionary<string, object>() 
                                                { { "lambdaResult", Context.StringAt("$$.Payload") } } }),
                InputPath = "$.Payload",
                ResultPath = "$.lambdaResult",
                OutputPath = "$.lambdaResult"
```
When I do Context.StringAt(...) in RunLambdaTask, i think it takes the execution's input and not the task input..i think, maybe there is another way to access the TaskState input?

Basically, the model sent to my lambda is NULL in case of RunLambdaTask.

### Environment

  - **CLI Version      :**
  - **Framework Version:** 1.31
  - **OS               :** Windows
  - **Language         :** C#

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by shivlaks**
### Commit Message
fix(stepfunctions-tasks): cannot specify part of execution data or task context as input to the `RunLambda` service integration (#7428)

The Lambda service integration requires an input field called `payload`.
We modeled this as a `{[key: string]: any}` which precludes the usage of
execution data or context data as inputs to a Lambda function.

Fix:
Change the type of `payload` to be `TaskInput` which has already modeled
a type union for task classes that accept multiple types of payload.
This will enable usage of literal strings, objects, execution data, and
task context as input types supported for invoking a Lambda function.

Rationale:
Although this is a breaking change, the workarounds for enabling usage of
different types is not user friendly and incomplete as all of the types
above cannot be expressed in the current modeling of `payload`

Fixes #7371

BREAKING CHANGE:
`payload` in RunLambdaTask is now of type `TaskInput` and has a default of the state input instead of the empty object.
You can migrate your current assignment to payload by supplying it to the `TaskInput.fromObject()` API
### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-stepfunctions-tasks/lib/lambda/run-lambda-task.ts [hunk 1]
```diff
@@ -12,7 +12,7 @@ export interface RunLambdaTaskProps {
    *
    * @default - No payload
    */
-  readonly payload?: { [key: string]: any };
+  readonly payload?: sfn.TaskInput;
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-stepfunctions-tasks/lib/lambda/run-lambda-task.ts:15]: Is it worth introducing a new field for this? (Let's say, `input?: sfn.TaskInput`) and `@deprecate`ing the old one?

Are you okay taking the breakage?

-----

Next question: since we're touching this anyway, does it make sense to change the `@default` while we're at it?

Comment (nija-at) [reply packages/@aws-cdk/aws-stepfunctions-tasks/lib/lambda/run-lambda-task.ts:15]: I'm ok with the breaking change, given the migration is straight forward.

Why do you suggest changing the default? It seems to me that the current default makes sense, no?

**Comment by nija-at** [comment]
> If this change does not reflect in the `README` in any way, that means there is a missing example in there.
> 
> I would expect the first example of invoking a Lambda in the README to show how to pass the entire execution state to the Lambda (just like the old Lambda invocation used to do).

+1. I would further and say that a change to the README is useful given that this is a breaking change. We should have a couple of code snippets in the README of the common use cases.

File: packages/@aws-cdk/aws-stepfunctions-tasks/lib/lambda/run-lambda-task.ts (hunk 1 above)
Comment (wong-a) [reply packages/@aws-cdk/aws-stepfunctions-tasks/lib/lambda/run-lambda-task.ts:15]: I don't see any problems with no payload being the default as long as there is a code example that shows how to set `"Payload.$": "$"` as @rix0rrr suggests.

`$` (the entire input) could be a sensible default value, mostly out of convenience for users of the "old-style" `InvokeFunction` which always sent the effective input as the payload. I noted some caveats in https://github.com/aws/aws-cdk/issues/7371#issuecomment-615935009.

It may be worth adding test coverage for setting payload to `$` since that's such a common use case.

Comment (shivlaks) [reply packages/@aws-cdk/aws-stepfunctions-tasks/lib/lambda/run-lambda-task.ts:15]: I'm also okay with taking the breakage here for the same reason as @nija-at 

good point: I do think the `@default` should be the entire task input while we're at it as I think that's a more common usage than sending the empty object into a Lambda. I've left it as is for now, but happy to make that change

**Comment by shivlaks** [comment]
> > If this change does not reflect in the `README` in any way, that means there is a missing example in there.
> > I would expect the first example of invoking a Lambda in the README to show how to pass the entire execution state to the Lambda (just like the old Lambda invocation used to do).
> 
> +1. I would further and say that a change to the README is useful given that this is a breaking change. We should have a couple of code snippets in the README of the common use cases.

I've added some common cases. I'm in the middle of rewriting all of the Tasks section into `stepfunctions-tasks` package. It's taking be a bit longer than I thought, but I'd love to get all of this into the package (in another PR).

**Comment by shivlaks** [comment]
@nija-at @rix0rrr - I started drafting the updated README for `stepfunctions-tasks` in #7469
Going to be adding in all the service integrations before that one will be ready for review. Happy to port over wherever we land on this one.

One thing I've noticed is inconsistency in how we name these task integrations.

Some services have `Run` as a prefix -> i.e. `RunBatchJob`
Some services have `Task` at the suffix as well `RunLambdaTask`, `RunGlueJobTask`
Some services have `<service-name><api-name>` - i.e. `EmrAddStep`, `DynamoPutItem`
Some services are excluded altogether - i.e. `PublishToTopic`, `SendToQueue`

I guess it would be nice if the naming wasn't so heterogeneous. Do we want to align the naming? If we do, maybe we rename RunLambdaTask to whatever we settle on. I personally like <service-name><api-name> -> `LambdaInvoke`

**Comment by nija-at** [comment]
> Do we want to align the naming?

Would be nice to align. If I was starting off, I would do `<ServiceName><ApiName>Task`; service name first is easier to discover.

We should be ok changing the names of more recent ones that were added (batch, dynamo, emr, etc.). We'll break fewer customers. I'm sure most people using stepfunctions will use lambda.

File: packages/@aws-cdk/aws-stepfunctions/README.md [hunk 2]
```diff
@@ -159,17 +159,81 @@ similar to (for example) `inputPath`.
...
       payload: {
-        token: sfn.Context.taskToken
+        token: sfn.Context.taskToken,
+        input: sfn.TaskInput.fromDataAt('$.someField'),
       }
     })
   });
 ```
 
+⚠️ The Lambda function should call `SendTaskSuccess` or `SendTaskFailure` with the
```
Comment (wong-a) [inline packages/@aws-cdk/aws-stepfunctions/README.md:234]: `.waitForToken` would typically be used with Lambda to send the token somewhere else (an on-prem service, S3, etc) for processing. Calling `SendTaskSuccess/Failure` in the same function that received the token probably isn't the typical use case. If the work can be started and completed within a single function invocation, it makes more sense to just use the Request Response integration pattern.

The example you linked in this section is for a sample project where the token is actually sent to SQS using `arn:aws:states:::sqs:sendMessage.waitForTaskToken`. In that example, the Lambda function is triggered by SQS outside of the state machine. I think the conceptual documentation Wait for Task Token is more appropriate here. 

https://docs.aws.amazon.com/step-functions/latest/dg/connect-to-resource.html#connect-wait-token

File: packages/@aws-cdk/aws-stepfunctions/README.md [hunk 3]
```diff
@@ -159,17 +159,81 @@ similar to (for example) `inputPath`.
...
+  }),
+  outputPath: '$.Payload',
+});
+```
+
+You can have Step Functions pause a task, and wait for an external process to
+return a task token. Read more about the [callback pattern](https://docs.aws.amazon.com/step-functions/latest/dg/callback-task-sample-sqs.html#call-back-lambda-example)
+
+To use the callback pattern, set the `token` property on the task and have the
+Lambda function Lambda function call the Step Functions API `SendTaskSuccess`
```
Comment (wong-a) [inline packages/@aws-cdk/aws-stepfunctions/README.md:215]: typo: Lambda function x2
typo: Step Functions `SendTaskSuccess` or `SendTaskFailure` APIs

This should just say that *something* needs to callback. It's more typical for a Lambda invoked with `.waitForTaskToken` to send the token elsewhere for processing.

File: packages/@aws-cdk/aws-stepfunctions/README.md [hunk 4]
```diff
@@ -159,17 +159,81 @@ similar to (for example) `inputPath`.
...
+
+The following snippet invokes a Lambda Function by referencing the `$.Payload` path
+to reference the output of a Lambda executed before it.
+
+```ts
+new sfn.Task(this, 'Invoke with task context', {
+  task: new tasks.RunLambdaTask(myLambda),
+});
+
+new sfn.Task(this, 'Invoke with output from another Lambda', {
```
Comment (wong-a) [inline packages/@aws-cdk/aws-stepfunctions/README.md:192]: How about `Invoke with output from the previous task` or `Invoke with the Payload field in the state input`?

It's kind of presented here as a generic way to invoke Lambda but only applies if you've structured your states exactly in this way. I can see users who don't understand input/output processing to just expect it to work all the time. The second option makes sense on its own.

File: packages/@aws-cdk/aws-stepfunctions/README.md [hunk 5]
```diff
@@ -159,17 +159,81 @@ similar to (for example) `inputPath`.
...
+When a function is invoked, the Lambda service sends back the following
+[response elements](https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html#API_Invoke_ResponseElements)
+
+⚠️ The response from the Lambda function is in an attribute called `Payload`
+
+The following snippet invokes a Lambda Function by referencing the `$.Payload` path
+to reference the output of a Lambda executed before it.
+
+```ts
+new sfn.Task(this, 'Invoke with task context', {
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-stepfunctions/README.md:188]:
```suggestion
new sfn.Task(this, 'Invoke with empty payload', {
```

File: packages/@aws-cdk/aws-stepfunctions/README.md (hunk 4 above)
Comment (shivlaks) [inline packages/@aws-cdk/aws-stepfunctions/README.md:192]:
```suggestion
new sfn.Task(this, 'Invoke with payload field in the state input', {
```

File: packages/@aws-cdk/aws-stepfunctions/README.md [hunk 6]
```diff
@@ -159,17 +159,81 @@ similar to (for example) `inputPath`.
...
+  }),
+});
+```
+
+The following snippet invokes a Lambda and sets the task output to only include
+the Lambda function response.
+
+```ts
+new sfn.Task(this, 'Invoke and set function response as task output', {
+  task: new tasks.RunLambdaTask(checkJobStateLambda, {
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-stepfunctions/README.md:204]:
```suggestion
  task: new tasks.RunLambdaTask(myLambda, {
```

File: packages/@aws-cdk/aws-stepfunctions/README.md [hunk 7]
```diff
@@ -159,17 +159,81 @@ similar to (for example) `inputPath`.
...
+});
+```
+
+You can have Step Functions pause a task, and wait for an external process to
+return a task token. Read more about the [callback pattern](https://docs.aws.amazon.com/step-functions/latest/dg/callback-task-sample-sqs.html#call-back-lambda-example)
+
+To use the callback pattern, set the `token` property on the task and have the
+Lambda function Lambda function call the Step Functions API `SendTaskSuccess`
+or `SendTaskFailure` API with the token to indicate that the task has completed
+and the state machine should resume execution.
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-stepfunctions/README.md:217]:
```suggestion
To use the callback pattern, set the `token` property on the task. Call the Step
Functions `SendTaskSuccess` or `SendTaskFailure` APIs with the token to
indicate that the task has completed and the state machine should resume execution.
```

File: packages/@aws-cdk/aws-stepfunctions/README.md [hunk 8]
```diff
@@ -159,17 +159,81 @@ similar to (for example) `inputPath`.
...
-        token: sfn.Context.taskToken
+        token: sfn.Context.taskToken,
+        input: sfn.TaskInput.fromDataAt('$.someField'),
       }
     })
   });
 ```
 
+⚠️ The Lambda function should call `SendTaskSuccess` or `SendTaskFailure` with the
+token provided as input or the State Machine will not resume.
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-stepfunctions/README.md:235]:
```suggestion
⚠️ The task will pause until it receives that task token back with a SendTaskSuccess or SendTaskFailure call. Read [more](https://docs.aws.amazon.com/step-functions/latest/dg/connect-to-resource.html#connect-wait-token)
```

File: packages/@aws-cdk/aws-stepfunctions/README.md [hunk 9]
```diff
@@ -159,17 +159,79 @@ similar to (for example) `inputPath`.
 
 #### Lambda example
 
+[Invoke](https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html) a Lambda function.
+
+You can specify the input to your Lambda function through the `payload` attribute.
+By default, no payload is specified so Step Functions invokes Lambda with the empty
+object `{ }` as input.
+
+The following snippet invokes a Lambda Function with the task context as the input
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-stepfunctions/README.md:168]:
```suggestion
The following snippet invokes a Lambda Function with the state input as the payload
```

**Comment by shivlaks** [comment]
> > Do we want to align the naming?
> 
> Would be nice to align. If I was starting off, I would do `<ServiceName><ApiName>Task`; service name first is easier to discover.
> 
> We should be ok changing the names of more recent ones that were added (batch, dynamo, emr, etc.). We'll break fewer customers. I'm sure most people using stepfunctions will use lambda.

I agree, I'll take a stab at a first approximation in another PR

File: packages/@aws-cdk/aws-stepfunctions-tasks/lib/lambda/run-lambda-task.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-stepfunctions-tasks/lib/lambda/run-lambda-task.ts:15]: I think we should optimize for the most common use case. What do we expect MOST people to do? @wong-a I would hope your team has some info on the most common ways people use each task type.

Furthermore, naively I would say that changing payload to `$` by default is a non-breaking change. If people leave it empty, today they would get no parameters, so not expect them and not read them, so adding more parameters should be fine.

There's also the case of what the default `outputPath` should be. Feels like for maximum convenience it should be `$.Payload`, and similar for all other task types. But changing that is not backwards compatible so I guess that ship has sailed, huh...?

Comment (rix0rrr) [reply packages/@aws-cdk/aws-stepfunctions-tasks/lib/lambda/run-lambda-task.ts:15]: Hey @wong-a, since we got you here anyway... what is the official term for the JSON blob that travels along with the execution, which is updated using inputPath, outputPath, etc?

I was struggling to find a good, clear and concise name for it while writing the library, so ultimately settled on something unsatisfying like `Data`. I wonder what you call it internally?

I guess we could do ExecutionState or something, but any term I can come up with feels so generic as to be worthless... :/

File: packages/@aws-cdk/aws-stepfunctions-tasks/test/lambda/integ.run-lambda.ts [hunk 10]
```diff
@@ -0,0 +1,62 @@
+import { Code, Function, Runtime } from '@aws-cdk/aws-lambda';
+import * as sfn from '@aws-cdk/aws-stepfunctions';
+import * as cdk from '@aws-cdk/core';
+import * as tasks from '../../lib';
+
+const app = new cdk.App();
```
Comment (nija-at) [inline packages/@aws-cdk/aws-stepfunctions-tasks/test/lambda/integ.run-lambda.ts:6]: Nice integration test!

I would add a small comment like this - https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#integration-tests - at the top. 

I believe the verification steps are the state machine should be in a completed state and not a failed state.

File: packages/@aws-cdk/aws-stepfunctions/README.md [hunk 11]
```diff
@@ -159,17 +159,79 @@ similar to (for example) `inputPath`.
...
+```ts
+new sfn.Task(this, 'Invoke with task context', {
+  task: new tasks.RunLambdaTask(myLambda, {
+    payload: sfn.TaskInput.fromDataAt('$'),
+  }),
+});
+```
+
+When a function is invoked, the Lambda service sends back the following
+[response elements](https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html#API_Invoke_ResponseElements)
```
Comment (nija-at) [inline packages/@aws-cdk/aws-stepfunctions/README.md:180]:
```suggestion
When a function is invoked, the Lambda service sends  [these response
elements](https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html#API_Invoke_ResponseElements)
back.
```

File: packages/@aws-cdk/aws-stepfunctions/README.md [hunk 12]
```diff
@@ -159,17 +159,79 @@ similar to (for example) `inputPath`.
...
+});
+
+new sfn.Task(this, 'Invoke with payload field in the state input', {
+  task: new tasks.RunLambdaTask(myOtherLambda, {
+    payload: sfn.TaskInput.fromDataAt('$.Payload'),
+  }),
+});
+```
+
+The following snippet invokes a Lambda and sets the task output to only include
```
Comment (nija-at) [inline packages/@aws-cdk/aws-stepfunctions/README.md:199]: "only include" - as opposed to what else?

File: packages/@aws-cdk/aws-stepfunctions/README.md [hunk 13]
```diff
@@ -159,17 +159,79 @@ similar to (for example) `inputPath`.
...
       payload: {
-        token: sfn.Context.taskToken
+        token: sfn.Context.taskToken,
+        input: sfn.TaskInput.fromDataAt('$.someField'),
       }
     })
   });
 ```
 
+⚠️ The task will pause until it receives that task token back with a SendTaskSuccess or SendTaskFailure call. Read [more](https://docs.aws.amazon.com/step-functions/latest/dg/connect-to-resource.html#connect-wait-token)
```
Comment (nija-at) [inline packages/@aws-cdk/aws-stepfunctions/README.md:233]:
```suggestion
⚠️ The task will pause until it receives that task token back with a `SendTaskSuccess` or `SendTaskFailure`
call. Learn more about [Callback with the Task
Token](https://docs.aws.amazon.com/step-functions/latest/dg/connect-to-resource.html#connect-wait-token).
```

File: packages/@aws-cdk/aws-stepfunctions/README.md (hunk 12 above)
Comment (shivlaks) [reply packages/@aws-cdk/aws-stepfunctions/README.md:200]: as opposed to all of the response elements `StatusCode`, `ExecutionResult`, etc... https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html#API_Invoke_ResponseElements

so this only returns the Lambda return which will be in the `Payload` attribute. I think this is covered in the blurb above though?

File: packages/@aws-cdk/aws-stepfunctions-tasks/test/lambda/integ.run-lambda.ts (hunk 10 above)
Comment (shivlaks) [reply packages/@aws-cdk/aws-stepfunctions-tasks/test/lambda/integ.run-lambda.ts:14]: added

File: packages/@aws-cdk/aws-stepfunctions-tasks/lib/lambda/run-lambda-task.ts (hunk 1 above)
Comment (wong-a) [reply packages/@aws-cdk/aws-stepfunctions-tasks/lib/lambda/run-lambda-task.ts:15]: > What do we expect MOST people to do? @wong-a I would hope your team has some info on the most common ways people use each task type.

The old-style Lambda is the most used Task type, which uses the entire effective input and I think most customers would be happy with it as the default. If someone wants to pass an empty object as the payload they can easily do so by passing an empty object as the value of `Payload`.

> what is the official term for the JSON blob that travels along with the execution, which is updated using inputPath, outputPath, etc?

There's no special name for it. It's generally referred to within the [ASL spec](https://states-language.net/spec.html#filters) and Step Functions documentation as "state input" or output.

Comment (shivlaks) [reply packages/@aws-cdk/aws-stepfunctions-tasks/lib/lambda/run-lambda-task.ts:15]: thanks for that valuabe input @wong-a 

I flipped this to default to `$` as I agree with @rix0rrr that changing the payload from empty object to the state input is not *likely* to break the lambda being invoked as it wasn't expecting to read any input.

I will call it out in the breaking change entry.
