### PR TITLE
fix(iam): principal with implicit conditions overwrite each other

### LINKED ISSUE #3227: Adding multiple principals role using assumeRolePolicy.addStatements override conditions
* **I'm submitting a ...**
  - [x] :beetle: bug report

* **What is the current behavior?**

When Adding multiple conditional principals to the same PolicyStatment  which has same conditions **key** will result in only one of the conditions:
```javascript
if (role.assumeRolePolicy) { 
  role.assumeRolePolicy.addStatements(
    new PolicyStatement({
      principals: [
        new ServicePrincipal('myService.amazon.com', {
          conditions: {
            StringEquals: {
              hairColor: 'blond',
              pet: 'cat'
            }
          }
        }),
        new ServicePrincipal('yourservice.amazon.com', {
          conditions: {
            StringEquals: {
              hairColor: 'black'
            }
          }
        })
      ]
    }));
  } 
```
will result in this template:
```javascript
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": "sts:AssumeRole",
              "Effect": "Allow",
              "Principal": {
                "Service": "sqs.amazonaws.com"
              }
            },
            {
              "Condition": {
                "StringEquals": {
                  "hairColor": "black"
                }
              },
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "myService.amazon.com",
                  "yourservice.amazon.com"
                ]
              }
            }
          ],
          "Version": "2012-10-17"
        }
```
 
This is because the conditions are added to a map  in the statement which causes  the first added role conditions to be override:
```typescript
  public addConditions(conditions: {[key: string]: any}) {
    Object.keys(conditions).map(key => {
      this.addCondition(key, conditions[key]);
    });
  }
```
Adding each principal in it's own statement results in the correct behavior, If this is the expected behavior maybe it will be better to not allow multiple conditioned principals add to a single statement (like in the composite principals)

* **Please tell us about your environment:**
  
  - CDK CLI Version: 1.0
  - Module Version: 1.0

### PR DESCRIPTION
**Pull request by rix0rrr**
### Commit Message
fix(iam): principal with implicit conditions overwrite each other

Principals can come with implicit conditions, which is useful for
representing principals that can't be expressed with a single field
in IAM.

However, you should not be allowed to use principals with mixed
conditions in a single statement, because IAM can't properly
express the implied OR there.

Fixes #3227.
### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-iam/lib/policy-statement.ts [hunk 1]
```diff
@@ -56,6 +56,7 @@ export class PolicyStatement {
   private readonly resource = new Array<any>();
   private readonly notResource = new Array<any>();
   private readonly condition: { [key: string]: any } = { };
+  private principalConditions?: string;
```
Comment (eladb) [inline packages/@aws-cdk/aws-iam/lib/policy-statement.ts:59]:
```suggestion
  private principalConditionsJson?: string;
```
