### PR TITLE
fix(iam): cannot grant lambda:InvokeFunction on ManagedPolicy or Policy via `grantInvoke()` method

### LINKED ISSUE #32980: iam: cannot pass iam.ManagedPolicy or iam.Policy to lambda.Function.grantInvoke
### Describe the bug

Following code fails:
```ts
const func = new lambda.Function(this, 'Function', { /* ... */ });
const managedPolicy = new iam.ManagedPolicy(this, 'ManagedPolicy');
func.grantInvoke(managedPolicy);
```
The error message is:
> Cannot use a ManagedPolicy 'MyStack/Function' as the 'Principal' or 'NotPrincipal' in an IAM Policy

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

Grant `lambda:InvokeFunction` to `ManagedPolicy` or `Policy`.

### Current Behavior

`grantInvoke()` throws an error described above.

### Reproduction Steps

See the description above.

### Possible Solution

`grantInvoke()` calls `grantee.grantPrincipal.policyFragment.conditions` to create a dedupe hash.
https://github.com/aws/aws-cdk/blob/2b2443de2f566f1595657f94195d8b61243fb800/packages/aws-cdk-lib/aws-lambda/lib/function-base.ts#L435-L442

But `policyFragment` getter of `ManagedPolicy` and `Policy` throws an error. (see #22712)
It should return a dummy policy fragment like `Group`.
https://github.com/aws/aws-cdk/blob/2b2443de2f566f1595657f94195d8b61243fb800/packages/aws-cdk-lib/aws-iam/lib/group.ts#L82-L84

`Group` is blocked in `PolicyStatement`
https://github.com/aws/aws-cdk/blob/2b2443de2f566f1595657f94195d8b61243fb800/packages/aws-cdk-lib/aws-iam/lib/policy-statement.ts#L240-L244

### Additional Information/Context

_No response_

### CDK CLI Version

2.176.0

### Framework Version

2.176.0

### Node.js Version

22.13.0

### OS

Ubuntu

### Language

TypeScript

### Language Version

_No response_

### Other information

Related to #32795

### PR DESCRIPTION
**Pull request by Tietew**
### Issue # (if applicable)

Closes #32980.

### Reason for this change

`lambda.Function.grantInvoke()` throws an error when a `ManagedPolicy` or a `Policy` is passed.
It should add a policy statement to grant `lambda:InvokeFunction` on the policy document.

#### Core changes in `(Managed)PolicyGrantPrincipal` internal classes
Since `grantInvoke()` wants `policyFragment.conditions`, `policyFragment` now returns a `PolicyFragment` object with the principal ARN refers a token.
When the grantPrincipal is used as a resource policy, the token will cause a resolution error.

#### Additional changes
see also [rix0rrr's comment](https://github.com/aws/aws-cdk/pull/32984#pullrequestreview-2863553504)
- `assumeRoleAction` now throws an error instead of `'sts:AssumeRole'`.
- Updated the error message.

### Describe any new or updated permissions being added

N/A

### Description of how you validated changes

- Added/updated tests to verify `grantInvoke()` works.
- Updated unit tests to verify `app.synth()` throws instead of `Grant.addTo...()`.
- Some `class DummyResource implements IResourceWithPolicy` are replaced by S3 bucket to ensure to create a resource policy (S3 bucket policy).

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-iam/lib/managed-policy.ts [hunk 1]
```diff
@@ -309,6 +313,18 @@ export class ManagedPolicy extends Resource implements IManagedPolicy, IGrantabl
     this.groups.push(group);
   }
 
+  /**
+   * Adds an IAM statement to the policy document.
+   */
+  public addToPrincipalPolicy(statement: PolicyStatement): AddToPrincipalPolicyResult {
+    this.addStatements(statement);
```
Comment (5d) [inline packages/aws-cdk-lib/aws-iam/lib/managed-policy.ts:320]: ## Best Practices for AWS IAM Managed Policies

From a best practices perspective, an **AWS IAM ManagedPolicy** functions as a shared state. Since it can be attached to multiple entities—users, roles, and groups—any change to the policy affects all consumers simultaneously.

The recommended approach is to **define all required permissions at creation time** and treat the policy as **immutable** throughout its lifecycle. This offers several key benefits:

1. **Predictability**  
   Changes to a shared policy propagate instantly, which can unintentionally alter access across your environment.

2. **Versioning Complexity**  
   Although AWS supports managed policy versioning, relying on it for rollback or audits introduces additional complexity.

3. **Least Privilege Enforcement**  
   Updating a shared policy risks granting broader permissions than intended.

4. **Governance and Control**  
   Because of their wide impact, shared policies should be subject to formal review and change control processes.

> 💡 **Note**: If a policy truly needs to change after creation, it may indicate the need for a **dedicated IAM role** or a purpose-built policy to better isolate and manage those permissions.

**Review by 5d — CHANGES_REQUESTED** [review]

File: packages/aws-cdk-lib/aws-iam/lib/managed-policy.ts (hunk 1 above)
Comment (Tietew) [reply packages/aws-cdk-lib/aws-iam/lib/managed-policy.ts:320]: @5d Thank you for reviewing.

This method is required by `IPrincipal`.
Constructing permissions step by step (calling `addStatements` multiple times) in CDK apps does not mean the managed policy is to be mutated after creation.

Are you saying that we should avoid to expose this method directly in `ManagedPolicy`, right?

Comment (5d) [reply packages/aws-cdk-lib/aws-iam/lib/managed-policy.ts:320]: The fundamental issue is that `Policy` and `ManagedPolicy` are not principals in the AWS IAM model. In AWS, policies are permission documents that are attached to principals (such as users, roles, or services), but they are not principals themselves.

By implementing the `IPrincipal` interface on `Policy` and `ManagedPolicy`, the CDK introduces a conceptual mismatch with the underlying AWS service model. While this implementation may add some convenience, such as allowing policies to be passed directly to grant methods, it creates an abstraction that does not align with how IAM actually works. This can lead to confusion for users who understand the underlying AWS IAM concepts.

The concern here is not primarily about method mutability, but about the architectural decision to make policy objects implement an interface meant for principals, when policies are fundamentally not principals in AWS IAM.

Comment (Tietew) [reply packages/aws-cdk-lib/aws-iam/lib/managed-policy.ts:320]: Thanks for the explanation.
I'll withdraw implementing IPrincipal directly, and work on them for a few days.

**Comment by Tietew** [comment]
@5d
I've made following changes:

- Revert implementing `IPrincipal` directly to `(Managed)Policy` constructs.
- Move `grantPrincipal` implementations (`(Managed)PolicyGrantPrincipal` internal classes) to `private` subdir in order to be referred from `policy-statement.ts`

And also I've updated the PR description.

**Comment by 5d** [comment]
> @5d I've made following changes:
> 
> * Revert implementing `IPrincipal` directly to `(Managed)Policy` constructs.
> * Move `grantPrincipal` implementations (`(Managed)PolicyGrantPrincipal` internal classes) to `private` subdir in order to be referred from `policy-statement.ts`
> 
> And also I've updated the PR description.


Sorry @Tietew, I think there may be a misunderstanding. In your latest commit, it looks like you're treating `Policy` and `ManagedPolicy` as if they can behave like principals. However, this doesn't align with how AWS IAM works.

* **Policies** are collections of permission statements that define *what* actions are allowed or denied. They don’t represent an identity and cannot be granted permissions themselves.
* **Principals** (such as users, roles, or groups) are entities that *receive* permissions through policies.

**In IAM terms: principals define *who* can act, while policies define *what* actions are allowed.**

Could you clarify the reasoning behind granting permissions to a policy object? In what scenarios would this be necessary?

**Comment by Tietew** [comment]
`ManagedPolicy` and `Policy` constructs *already* implement `IGrantable`.
The implementation PR is #22712, which have been merged 2 years ago.

This PR *just fixes* unintentional error on lambda.Function's `grantInvoke()`.
#32980 describes the root cause.

```ts
declare const mp: iam.ManagedPolicy;
declare const bucket: s3.Bucket;
declare const func: lambda.Function;

// We can do this currently because ManagedPolicy is IGrantable
bucket.grantReadWrite(mp);

// Throws an error unintentionally - THIS PR FIXES THE ERROR
// Error: Cannot use a ManagedPolicy 'xxxxxx' as the 'Principal' or 'NotPrincipal' in an IAM Policy
func.grantInvoke(mp);
```

**Comment by Tietew** [comment]
> If you truly need to modify a policy after it's been created

No. I want to *construct* policy statements during creating a (managed) policy.

Of cause, sometimes I need to modify policy statements after the stack have been deployed.
But I think there are no differences between adding a `grantInvoke()` and adding a `new iam.PolicyStatement()`.

> why not just use the standard approach with `addStatements`?

There are some reasons.
- `grantXXX()` is convenience and shorter than `addStatements`.
- `grantXXX()` guarantees the action name and ARNs are correct. (`lambda:InvokeFunction` differs than the API `lambda.invoke()`)

**Review by rix0rrr — CHANGES_REQUESTED** [review]
Responding to this:

> PolicyStatment throws an error when a (Managed)PolicyGrantPrincipal is specified as principal or notPrincipal.

This is too specific. Avoid class instance testing if you can.

Instead, it seems that the access of `.grantPrincipal` should have thrown a descriptive error of the form `This grant operation needs to add a resource policy so needs access to a principal. Grant permissions to a Role or User, instead of a Policy`.

Instead of this:

```ts
  // This is incorrect. A policy doesn't have a principal to grant to, because a principal implies
  // identity and a policy by itself doesn't have an identity.
  public readonly grantPrincipal: IPrincipal = this;
```

Do this:

```ts
  public get grantPrincipal(): IPrincipal {
    throw new Error('...'); 
  }
```

-----

Then the next question is why the `grantInvoke()` thinks it needs to add a resource policy, but that will be easier to figure out if you stop this code path dead in its tracks.

**Comment by 5d** [comment]
> > If you truly need to modify a policy after it's been created
> 
> No. I want to _construct_ policy statements during creating a (managed) policy.
> 
> Of cause, sometimes I need to modify policy statements after the stack have been deployed. But I think there are no differences between adding a `grantInvoke()` and adding a `new iam.PolicyStatement()`.
> 
> > why not just use the standard approach with `addStatements`?
> 
> There are some reasons.
> 
> * `grantXXX()` is convenience and shorter than `addStatements`.
> * `grantXXX()` guarantees the action name and ARNs are correct. (`lambda:InvokeFunction` differs than the API `lambda.invoke()`)

While I understand the desire for convenience when using `grant` methods, I believe this PR attempts to work around fundamental IAM concepts rather than align with them. I'm not fully sure why we decided to allow policies to implement `IGrantable`, but this introduces a conceptual mismatch with the AWS IAM model, leading to confusion and increased maintenance complexity.

Specifically, the use of dummy `ArnPrincipal` fragments and special error handling in `PolicyStatement` also reveals the **fragility** of this approach. Some `grantXxx` methods work, others fail — demonstrating inconsistent behavior.

---

### Suggestion: Use Utility Methods for PolicyStatements

A more predictable and testable approach is to generate `PolicyStatement`s explicitly using utility factory methods.

#### Option 1: Static Utility Class

```ts 
class LambdaPolicyStatements {
  static invoke(fn: IFunction): PolicyStatement {
    return new PolicyStatement({
      actions: ['lambda:InvokeFunction'],
      resources: [fn.functionArn],
    });
  }
}
```

**Usage:**

```ts
policy.addStatements(LambdaPolicyStatements.invoke(myFunction));
```

#### Option 2: Subclass `Function` with Helper Method

```ts
class EnhancedFunction extends Function {
  getInvokeStatement(): PolicyStatement {
    return new PolicyStatement({
      actions: ['lambda:InvokeFunction'],
      resources: [this.functionArn],
    });
  }
}
```

**Usage:**

```ts
policy.addStatements(myFunction.getInvokeStatement());
```

---

### Why this is better:

* **Aligned with IAM model**: No misuse of principals or policies
* **Predictable**: No hidden logic or branching behavior
* **Testable**: Easy to unit test utility methods
* **No side effects**: Doesn’t mutate constructs under the hood
* **Reusable**: Clear, explicit permission definitions

---

This approach retains the convenience of grant methods while being more explicit and principled about the relationship between resources and IAM policies, without violating the abstraction model.

I appreciate your effort to improve the developer experience, but I'm concerned that the current solution creates more conceptual confusion than it resolves.

**Comment by Tietew** [comment]
@rix0rrr 
> Throwing an error at `assumeRoleAction` instead seems to be a nice idea.
> I'll try it.
Unfortunately, it wasn't a solution.
Because a resource policy, such as `S3::BucketPolicy`, never need `assumeRoleAction`.

**Comment by Tietew** [comment]
@5d
I'd understand what you want to say.
However, it's far too large for the issue I want to solve;
Just one method `grantInvoke()` has this issue.

**Comment by Abogical** [comment]
Re-adding approval of @rix0rrr after merge conflict fix.
