### PR TITLE
fix(pipelines): asset stage can't support more than 50 assets

### LINKED ISSUE #9353: [pipelines] Asset stage can't support more than 50 assets.
When attempting to deploy a pipeline with more than 50 assets, the deploy fails due to the Asset stage having more than 50 actions.

### Reproduction Steps

Deploy a pipeline with > 50 assets.

```ts
    for (let i = 0; i < 32; i++) {
      const websiteBucket = new s3.Bucket(this, `WebsiteBucket${i}`, {
        websiteIndexDocument: 'index.html',
      });

      new s3deploy.BucketDeployment(this, `DeployWebsite${i}`, {
        sources: [s3deploy.Source.asset('./test-file-asset', { assetHash: `file-asset-${i}` })],
        destinationBucket: websiteBucket,
      });

      new ecr_assets.DockerImageAsset(this, `DockerAsset${i}`, {
        directory: './test-docker-asset',
        extraHash: `docker-asset-${i}`,
      });
    }
```

### Error Log

On deploy, the following error is hit:

`Pipeline stage 'Assets' has too many actions. There can only be up to 50 actions in a pipeline stage (Service: AWSCodePipeline; Status Code: 400; Error Code: InvalidStageDeclarationException; Request ID: xxx)`

### Other

The approach will likely be to dynamically create new asset publishing stages to the pipeline when > 50 assets are created. This will require API support in CodePipelines, as currently stages can't be inserted, only added to the end of the pipeline.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by njlynch**
CodePipelines has a hard limit of 50 actions per stage. Currently, all asset
publishing actions are assigned to a single stage, limiting pipelines to 50
total assets.

This change dynamically creates new stages as necessary to allow expansion
beyond 50 assets. This should allow for hundreds (or thousands) of assets before
hitting the 50 stages per pipeline hard limit.

fixes #9353

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/pipelines/lib/pipeline.ts [hunk 1]
```diff
@@ -410,13 +414,23 @@ class AssetPublishing extends CoreConstruct {
 
     let action = this.publishers[command.assetId];
     if (!action) {
+      // Dynamically create new stages as needed, with `MAX_PUBLISHERS_PER_STAGE` assets per stage.
+      const stageIndex = Math.floor((this._fileAssetCtr + this._dockerAssetCtr) / this.MAX_PUBLISHERS_PER_STAGE);
+      if (stageIndex >= this.stages.length) {
+        const previousStage = this.stages.slice(-1)[0] ?? this.lastStageBeforePublishing;
```
Comment (rix0rrr) [inline packages/@aws-cdk/pipelines/lib/pipeline.ts:420]: You crazy sumbitch.

**Review by rix0rrr — APPROVED** [review]
🙌
