### PR TITLE
fix(apigatewayv2-integrations): fix broken lambda websocket integration uri

### LINKED ISSUE #13679: (aws_cdk.aws_apigatewayv2_integrations.LambdaWebSocketIntegration): produces wrong integration_uri
`LambdaWebSocketIntegration` (per the example [here](https://github.com/aws/aws-cdk/blob/fe1c8393e0840fb273c4a5f325cb3cebc784bf4b/packages/%40aws-cdk/aws-apigatewayv2-integrations/README.md#websocket-apis)) seems designed to plug a lambda handler into a WebSocket API Gateway.  But it produces the wrong `IntegrationUri`.

### Reproduction Steps

see example [here](https://github.com/aws/aws-cdk/blob/fe1c8393e0840fb273c4a5f325cb3cebc784bf4b/packages/%40aws-cdk/aws-apigatewayv2-integrations/README.md#websocket-apis)

### What did you expect to happen?

Expected a working API Gateway.

### What actually happened?

Ended up with a broken API Gateway because the generated `IntegrationUri` is wrong.

### Environment

  - **CDK CLI Version  :** 1.94.1 (build 60d8f91)
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

The `IntegrationUri` produced is

```
            "IntegrationUri": "arn:aws:lambda:us-east-2:$$ACCOUNT ID redacted$$:function:sampleContainerFunction",
```

but a correct one would be

```
            "IntegrationUri": "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:$$ACCOUNT ID redacted$$:function:sampleContainerFunction/invocations",
```

For documentation on this "invocations" format for the `IntegrationUri`, please see this [doc](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-integration-requests.html).

The correct AWS CLI command `create-integration` shows the format:

```
aws apigatewayv2 create-integration --api-id aabbccddee --integration-type AWS_PROXY --integration-method POST --integration-uri arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:123412341234:function:simpleproxy-echo-e2e/invocations
```

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by ayush987goyal**
fix(apigatewayv2-integrations): fix broken lambda websocket integration uri

closes #13679 

The previous integration uri provided working functionality and was implemented similar to how HTTP Api's lambda integration uri works. But the current implementation breaks the API Gateway Console for WebSocket Lambda integration.

This change fixes the same based on docs:
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-integration-requests.html

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-apigatewayv2-integrations/lib/websocket/lambda.ts [hunk 1]
```diff
@@ -36,9 +36,16 @@ export class LambdaWebSocketIntegration implements IWebSocketRouteIntegration {
       }),
     });
 
+    const integrationUri = Stack.of(route).formatArn({
```
Comment (nija-at) [inline packages/@aws-cdk/aws-apigatewayv2-integrations/lib/websocket/lambda.ts:39]: https://github.com/aws/aws-cdk/blob/aa9fd9cd9bbaea4149927e08d57d29e547933f49/packages/%40aws-cdk/aws-apigatewayv2-integrations/lib/http/lambda.ts#L51

Looks like this should also be fixed.

Comment (nija-at) [inline packages/@aws-cdk/aws-apigatewayv2-integrations/lib/websocket/lambda.ts:39]: This URI is used in quite a few places. 

This - https://github.com/aws/aws-cdk/pull/13181/files#diff-2c8f1a771d6f62decf7e5ef20ebf6de6218c25ade0f1531ed5e78609f3bc23bdR110 - being another instance.

Let's move this as a getter - `invocationUri` - on `IFunction` and reuse?

**Review by nija-at — CHANGES_REQUESTED** [review]
Thanks for the super quick turn around on this @ayush987goyal.

File: packages/@aws-cdk/aws-apigatewayv2-integrations/lib/websocket/lambda.ts (hunk 1 above)
Comment (ayush987goyal) [reply packages/@aws-cdk/aws-apigatewayv2-integrations/lib/websocket/lambda.ts:39]: I could not find anywhere in the [docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html) for HTTP API (or CFN) about this. I also deployed the integration stack and could see the console working fine for HTTP APIs. 

In the CFN [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-integration.html#cfn-apigatewayv2-integration-integrationuri) it is mentioned that this should be URI of lambda function (not sure if that means ARN?).

I think we should leave this as is since it might cause unnecessary regression. What do you think?

Comment (ayush987goyal) [reply packages/@aws-cdk/aws-apigatewayv2-integrations/lib/websocket/lambda.ts:39]: This seems very specific to `apigateway` service and is evident from the `invocationUri` itself. I am not sure if it would be a correct place to put this in `IFunction`. If this use case is common for any other service as well, then we can add a helper in `IFuntion` which accepts `service` as an argument. Thoughts?

**Comment by ayush987goyal** [comment]
Hi @nija-at , could you please help me with your thoughts on the above comments?

**Comment by ayush987goyal** [comment]
Hi @nija-at , based on your [comment](https://github.com/aws/aws-cdk/pull/13181/files#r614698723) on the other PR, I think it is safe to merge this without the change in Lambda package?

**Review by nija-at — APPROVED** [review]
Hi @ayush987goyal - This PR somehow fell between the cracks. Apologies.

Approved.
