### PR TITLE
fix(secretsmanager): can't export secret name from Secret

### LINKED ISSUE #10914: [rds] Can't export the secret name from a DatabaseCluster
It is not possible to export the name of the secret that is generated by the DatabaseCluster construct.

### Reproduction Steps

```python
        # Create the cluster
        cluster = rds.DatabaseCluster(
            self,
            "Database",
            engine=rds.DatabaseClusterEngine.aurora_mysql(
                version=rds.AuroraMysqlEngineVersion.VER_2_09_0
            ),
            instance_props={
                "instance_type": ec2.InstanceType.of(
                    ec2.InstanceClass.BURSTABLE2, ec2.InstanceSize.MEDIUM
                ),
                "vpc_subnets": {"subnet_type": ec2.SubnetType.PRIVATE},
                "vpc": vpc,
                "security_groups": [aurora_sg],
            },
        )

        # Output RDS secret name
        _ = core.CfnOutput(
            self,
            "MySecretOut",
            value=cluster.secret.secret_name,
            export_name="my-secret-name",
        )
```

### What did you expect to happen?

The secret name should be exported in the synthesized template.

### What actually happened?

The resource in the template is missing the Value, which causes a deployment failure.

```json
    "MySecretOut": {
      "Export": {
        "Name": "my-secret-name"
      }
    }
```

### Environment

  - **CLI Version      :** 1.68
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

We should also modify CfnOutput to fail when the value provided is undefined.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by njlynch**
For owned Secrets, `secretName` was set to the physical name, which was set to
the provided `secretName` if given, or a Token otherwise. However, the Token was
never resolved, as the `secretName` isn't actually a return vaue / attribute.

The fix explicitly sets the `secretName` either to the inputted name or the
parsed name from the ARN. Note that this means the secret name will be the
partial/"friendly" name (e.g., 'MySecret') if the secret name was passed in,
and the full name (e.g., 'MySecret-123abc') otherwise.

fixes #10914

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-secretsmanager/lib/secret.ts [hunk 1]
```diff
@@ -351,7 +351,7 @@ export class Secret extends SecretBase {
     });
 
     this.encryptionKey = props.encryptionKey;
-    this.secretName = this.physicalName;
+    this.secretName = props.secretName ?? parseSecretName(this, this.secretArn);
```
Comment (eladb) [inline packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:354]: I feel we need a way to return a token that encodes the implicit dependency. Otherwise this might not behave as expected. 

If some resource references `secret.secretName` in its CFN props, there's an expectation that this will resolve in CFN as a Ref/GetAtt and then an implicit dependency will be formed.

Comment (njlynch) [reply packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:354]: I'm not quite sure I understand. Do you mean even the `props.secretName` case should be tokenized? We could certainly just always use `parseSecretName`. The downside would be this:

```ts
const secretName = 'SuperImportant';
const secret = new Secret(this, 'Secret', { secretName });
secret.secretName === secretName // false
```

Not the end of the world perhaps, but slightly unexpected.

---

Sidenote - I'm not treating this as a breaking change, because I'm viewing the use case here (of referencing the `secretName` post-creation) as broken for all users who haven't explicitly set the secretName in the props; those users would have a Token that would never resolve and so wouldn't have been able to accomplish anything with it. Opting for always tokenizing does run the slightest risk of breaking something for someone who _has_ supplied the secret name and is using it. This would be pretty esoteric (e.g., later looking up secrets in a hashmap by their secret name or something), but I figure it's worth calling out.

Comment (eladb) [reply packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:354]: yes, as far as I know this is the approach we've been taking across the library to ensure implicit dependencies are recorded in the CFN template.

File: packages/@aws-cdk/aws-secretsmanager/test/secret.test.ts [hunk 2]
```diff
@@ -425,6 +425,23 @@ test('secretValue', () => {
...
+      secretName,
+    });
+    new cdk.CfnOutput(stack, 'MySecretName', {
+      value: secret.secretName,
+    });
+
+    // Creates secret name by parsing ARN.
+    expect(stack).toHaveOutput({
+      outputName: 'MySecretName',
+      outputValue: { 'Fn::Select': [6, { 'Fn::Split': [':', { Ref: 'SecretA720EF05' }] }] },
```
Comment (skinny85) [inline packages/@aws-cdk/aws-secretsmanager/test/secret.test.ts:440]: So, if I understand this correctly, this will return the name with the auto-generated suffix? So if I provide `seretName` as `'MySecret'` when constructing the, I'll get back `MySecret-123456`? Is it obvious to customers that this is what they'll get?

Comment (njlynch) [reply packages/@aws-cdk/aws-secretsmanager/test/secret.test.ts:440]: > So, if I understand this correctly, this will return the name with the auto-generated suffix?

Yes.

> Is it obvious to customers that this is what they'll get?

I'm not sure, but it's all we can do, without doing something like resorting to creating a custom resource to parse the secret name. How would you suggest we increase the obvious-ness of this?

Comment (skinny85) [reply packages/@aws-cdk/aws-secretsmanager/test/secret.test.ts:440]: One idea I have is, in the case the customer passed the `secretName` when creating the `Secret`, to return a Token that resolves to `secretName`, but adds the dependency between the two resources on resolution, kind of similar to how our automatic cross-stack references work (I understand this might be tricky to implement).

Basically, I'm worried that someone will use `secretName` somewhere where the name of the Secret is expected, and when it resolves to `MySecret-123456`, it will fail at deploy time.

@eladb want to pitch in here with your opinion, since you've reviewed a few of these last SecretsManager PRs?

Comment (eladb) [reply packages/@aws-cdk/aws-secretsmanager/test/secret.test.ts:440]: It seems totally fine to me, especially given the result is only resolved during deployment. 

As far as I understand, For all intents and purposes this _is_ the secret name and should be usable everywhere a secret name is expected. 

(The opposite is actually not always true - I.e there are places where only qualified names are allowed).

**Review by eladb — APPROVED** [review]

File: packages/@aws-cdk/aws-secretsmanager/test/secret.test.ts (hunk 2 above)
Comment (njlynch) [reply packages/@aws-cdk/aws-secretsmanager/test/secret.test.ts:440]: For the record here, @skinny85  was absolutely correct here (+10 internet points!). SecretsManager actually *doesn't* accept the resource name as an identifier for DescribeSecret -- it's just about the only form of identifier they don't support. This is documented in their API and frankly, I should have caught this. SecretsManager is hard. :/

See #11736 for the fix.
