### PR TITLE
fix(cloudwatch): MathExpression `id` contract is not clear

### LINKED ISSUE #13942: (aws-cloudwatch): Missing ids when creating math expressions
There’s no way to assign an ID to a metric in CDK at this point. If you’re creating **multiple math expressions** within a single dashboard widget, the IDs for the math expressions are missing, and you’ll see that they have the same IDs in the CloudWatch Dashboard, and the metrics in the dashboard widget will be messed up. 

### Reproduction Steps

```
new cloudWatch.GraphWidget({
    left: [
        new MathExpression(...),
        new MathExpression(...),
        new MathExpression(...)
    ]
});
```

The generated CloudFormation file doesn't contain ID for MathExpression (see example below). After deployed, in the CloudWatch, we'll see that all the math expressions are assigned with the same ID, and the dashboard widget shows incorrect metrics

```
{ "label": "percentage", "expression": "m1 / m2", "region": "us-east-1" }
```

### What did you expect to happen?

* There should be a way to auto or manually set the ID for MathExpression
* The above example should finally contain an id, something like

```
{ "label": "percentage", "expression": "m1 / m2", "region": "us-east-1", id: "e1" }
```

### What actually happened?

The generated Math Expression widget doesn't have an id

```
{ "label": "percentage", "expression": "m1 / m2", "region": "us-east-1" }
```

### Environment

  - **CDK CLI Version  :** any
  - **Framework Version:** 1.95
  - **Node.js Version:**  any
  - **OS               :** any
  - **Language (Version):**  TypeScript (but I think this issue is in all the languages)

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
It is intended that all metric identifiers referenced in a
MathExpression are included in the `usingMetrics` map. This
allows passing around complex metrics as a single object,
because the math expression object carries around its dependencies
with it.

This is slightly different than what people might be used
to from raw CloudWatch, where there is no hierarchy and all
metrics are supposed to be listed in the graph widget or alarm
with a unique ID, and then referenced by ID.

We can't make this contract obvious anymore by adding a hard
validation, but we can add warnings to hint people at the right
way to reference metrics in math expressions.

Fixes #13942, closes #17126.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-cloudwatch/lib/dashboard.ts [hunk 1]
```diff
@@ -127,7 +127,29 @@ export class Dashboard extends Resource {
...
+  const ret = new Array<IWidget>();
+  ws.forEach(recurse);
+  return ret;
+
+  function recurse(w: IWidget) {
+    ret.push(w);
+    if (hasSubWidgets(w)) {
+      w.widgets.forEach(recurse);
+    }
+  }
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-cloudwatch/lib/dashboard.ts:150]: Is there a chance that we have a circular dependency in any `widgets`? That is, is it possible for a widget to be a subwidget of itself? If so we should add a depth check and throw a useful error message if we catch one.

Comment (rix0rrr) [reply packages/@aws-cdk/aws-cloudwatch/lib/dashboard.ts:150]: You can write code to do that, but it already won't work today with a stack blowing error. I'm not too concerned that someone would do it in practice and then not know what's going on.

**Review by comcalvi — APPROVED** [review]
