### PR TITLE
fix(eks): failures when creating or updating clusters

### LINKED ISSUE #4087: EKS fails to deploy with  CancelRequest not implemented by *exec.roundTripper\nerror: unable to recognize "/tmp/manifest.yaml"
### The Question
```
eks_cluster = aws_eks.Cluster(
            scope=self,
            id=cluster_name,
            cluster_name=cluster_name,
            default_capacity=0,
            masters_role=cluster_masters_role,
            version='1.12',
            vpc=vpc
        )

with open('assets/tiller-service-account.yml', 'r') as file:
    eks_cluster.add_resource('TillerServiceAccount', yaml.safe_load(file))

with open('assets/tiller-cluster-role-binding.yml', 'r') as file:
    eks_cluster.add_resource('TillerClusterRoleBinding', yaml.safe_load(file))

with open('assets/tiller-deployment.yml', 'r') as file:
    eks_cluster.add_resource('TillerDeployment', yaml.safe_load(file))

with open('assets/tiller-service.yml', 'r') as file:
    eks_cluster.add_resource('TillerService', yaml.safe_load(file))
```

Manifests are tiller deployment files. The work when deployed manually. I can attach the files if needed.

Deployment fails with:

```
 36/41 | 09:24:23 | CREATE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource | DevEksCluster/manifest-TillerDeployment/Resource/Default (DevEksClustermanifestTillerDeployment81AA2785) Failed to create resource. b'E0916 07:23:46.832354      13 round_trippers.go:174] CancelRequest not implemented by *exec.roundTripper\nerror: unable to recognize "/tmp/manifest.yaml": Get https://3E59AF23B9E843E291570C60FFFDAF2C.gr7.us-east-1.eks.amazonaws.com/api?timeout=32s: dial tcp 52.2.151.216:443: i/o timeout\n'
	new CustomResource (/tmp/jsii-kernel-otb6xc/node_modules/@aws-cdk/aws-cloudformation/lib/custom-resource.js:32:25)
	\_ new KubernetesResource (/tmp/jsii-kernel-otb6xc/node_modules/@aws-cdk/aws-eks/lib/k8s-resource.js:22:9)
	\_ Cluster.addResource (/tmp/jsii-kernel-otb6xc/node_modules/@aws-cdk/aws-eks/lib/cluster.js:215:16)
	\_ _wrapSandboxCode (/home/lky/Repositories/HuuugeStarsCfConfig/contrib/cloudformation/cdk/eks/cluster/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6498:51)
	\_ Kernel._wrapSandboxCode (/home/lky/Repositories/HuuugeStarsCfConfig/contrib/cloudformation/cdk/eks/cluster/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7131:20)
	\_ ret._ensureSync (/home/lky/Repositories/HuuugeStarsCfConfig/contrib/cloudformation/cdk/eks/cluster/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6498:25)
	\_ Kernel._ensureSync (/home/lky/Repositories/HuuugeStarsCfConfig/contrib/cloudformation/cdk/eks/cluster/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7102:20)
```
rest of the stack trace ommited.

### Environment

  - **CDK CLI Version:**  1.4.0 (build 175471f)
  - **Module Version:** 1.4
  - **OS:** all
  - **Language:** python

### LINKED ISSUE #4695: Missing unit tests for EKS custom resource
The custom resource is complex and we currently don't have a good unit test harness to validate the various cases and ensure there is no regression.

As soon as we have the AsyncCustomResource framework we will migrate the EKS custom resource to TypeScript and add a unit test framework for it.

### LINKED ISSUE #5259: EKS - 1.18.0 - Configuration changes to Cluster which require replacement create cluster with random name causing CF Stack to be inconsistent
Replacing a cluster with specified name cause the new cluster to be created with a random name. Trying to delete the stack fails throwing a ResourceNotFoundException

### Reproduction Steps

before:
```
        Cluster(
            self,
            cluster_name,
            cluster_name="dev-EKS-Cluster"
            vpc=vpc,
            version=kubernetes_version,
            default_capacity=0,
            masters_role=cluster_admin_role,
            vpc_subnets=[SubnetSelection(subnet_type=SubnetType.PRIVATE)],
        )
```

after:
```
        Cluster(
            self,
            cluster_name,
            cluster_name="dev-EKS-Cluster"
            vpc=vpc,
            version=kubernetes_version,
            default_capacity=0,
            masters_role=cluster_admin_role,
            vpc_subnets=[SubnetSelection(subnet_type=SubnetType.PRIVATE), SubnetSelection(subnet_type=SubnetType.PUBLIC)],
        )
```

### Error Log

The update applies correctly, but the created cluster name is `cluster-RandomAlphaNumericString`

Trying to delete the stack causes this:

```
  32 | 3:06:09 PM | DELETE_FAILED        | Custom::AWSCDK-EKS-Cluster            | dev-EKS-Cluster/Resource/Resource/Default (devEKSCluster5CC73604) Failed to delete resource. An error occurred (ResourceNotFoundException) when calling the DeleteCluster operation: No cluster found for name: dev-EKS-Cluster.
	new CustomResource (/tmp/jsii-kernel-MirCRQ/node_modules/@aws-cdk/aws-cloudformation/lib/custom-resource.js:56:25)
	\_ new ClusterResource (/tmp/jsii-kernel-MirCRQ/node_modules/@aws-cdk/aws-eks/lib/cluster-resource.js:46:26)
	\_ new Cluster (/tmp/jsii-kernel-MirCRQ/node_modules/@aws-cdk/aws-eks/lib/cluster.js:73:24)
	\_ /home/circleci/.local/share/virtualenvs/cdk_app--h4ksco0/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7749:49
	\_ Kernel._wrapSandboxCode (/home/circleci/.local/share/virtualenvs/cdk_app--h4ksco0/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8202:20)
	\_ Kernel._create (/home/circleci/.local/share/virtualenvs/cdk_app--h4ksco0/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7749:26)
	\_ Kernel.create (/home/circleci/.local/share/virtualenvs/cdk_app--h4ksco0/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7503:21)
	\_ KernelHost.processRequest (/home/circleci/.local/share/virtualenvs/cdk_app--h4ksco0/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7293:28)
	\_ KernelHost.run (/home/circleci/.local/share/virtualenvs/cdk_app--h4ksco0/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7233:14)
	\_ Immediate._onImmediate (/home/circleci/.local/share/virtualenvs/cdk_app--h4ksco0/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7236:37)
```

### Environment

  - **CLI Version      :*1.18.0*
  - **Framework Version:*1.18.0*
  - **OS               :*Linux*
  - **Language         :*python*

### Other

--- 

This is :bug: Bug Report

### LINKED ISSUE #5501: EKS cluster got deleted because of the name conflict in two different cdk apps
An EKS cluster got deleted when I am trying to deploy a new cluster. I was trying to install a new EKS cluster in same region and different VPC where already an EKS cluster was running. Both clusters where created using two different CDK app.

### Reproduction Steps

1. Deploy a CDK app for EKS with the specified name. ex (devEKSCluster)
2. Deploy the different named CDK app for the EKS cluster with the same name as the previous one. ex (devEKSCluster)

```
new EKSStack(app, "test1")
new EKSStack(app, "test2")

export class EKSStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: cdk.StackProps) {
    super(scope, id, props);
    const cluster = new eks.Cluster(this, "devEKSCluster", {
      clusterName: current_env+eksClusterName}
    );
  }
}
```

### Error Log

```
PS D:\work\cdk-apps\eks> cdk deploy
[Warning at /TestEksStack/EKSCluster] Could not auto-tag private subnets with "kubernetes.io/role/internal-elb=1", please remember to do this manually
This deployment will make potentially sensitive changes according to your current security approval level (--require-approval broadening).
Please confirm you intend to make the following modifications:

IAM Statement Changes
┌───┬────────────────────────────────────────────────────────┬────────┬───────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────┬───────────┐
│   │ Resource                                               │ Effect │ Action                                                                        │ Principal                                              │ Condition │
├───┼────────────────────────────────────────────────────────┼────────┼───────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────┼───────────┤
│ + │ ${EKSCluster/ClusterRole.Arn}                          │ Allow  │ sts:AssumeRole                                                                │ Service:eks.amazonaws.com                              │           │
│ + │ ${EKSCluster/ClusterRole.Arn}                          │ Allow  │ iam:PassRole                                                                  │ AWS:${EKSCluster/Resource/ResourceHandler/ServiceRole} │           │
├───┼────────────────────────────────────────────────────────┼────────┼───────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────┼───────────┤
│ + │ ${EKSCluster/Resource/ResourceHandler/ServiceRole.Arn} │ Allow  │ sts:AssumeRole                                                                │ Service:lambda.amazonaws.com                           │           │
├───┼────────────────────────────────────────────────────────┼────────┼───────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────┼───────────┤
│ + │ ${TestEksStackAdminRole.Arn}                           │ Allow  │ sts:AssumeRole                                                                │ AWS:arn:${AWS::Partition}:iam::533263886719:root       │           │
├───┼────────────────────────────────────────────────────────┼────────┼───────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────┼───────────┤
│ + │ ${devASG/InstanceRole.Arn}                             │ Allow  │ sts:AssumeRole                                                                │ Service:ec2.amazonaws.com                              │           │
├───┼────────────────────────────────────────────────────────┼────────┼───────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────┼───────────┤
│ + │ *                                                      │ Allow  │ eks:CreateCluster                                                             │ AWS:${EKSCluster/Resource/ResourceHandler/ServiceRole} │           │
│   │                                                        │        │ eks:DeleteCluster                                                             │                                                        │           │
│   │                                                        │        │ eks:DescribeCluster                                                           │                                                        │           │
│   │                                                        │        │ eks:UpdateClusterVersion                                                      │                                                        │           │
└───┴────────────────────────────────────────────────────────┴────────┴───────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────┴───────────┘
IAM Policy Changes
┌───┬────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────┐
│   │ Resource                                           │ Managed Policy ARN                                                             │
├───┼────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ + │ ${EKSCluster/ClusterRole}                          │ arn:${AWS::Partition}:iam::aws:policy/AmazonEKSClusterPolicy                   │
│ + │ ${EKSCluster/ClusterRole}                          │ arn:${AWS::Partition}:iam::aws:policy/AmazonEKSServicePolicy                   │
├───┼────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ + │ ${EKSCluster/Resource/ResourceHandler/ServiceRole} │ arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole │
├───┼────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ + │ ${devASG/InstanceRole}                             │ arn:${AWS::Partition}:iam::aws:policy/AmazonEKSWorkerNodePolicy                │
│ + │ ${devASG/InstanceRole}                             │ arn:${AWS::Partition}:iam::aws:policy/AmazonEKS_CNI_Policy                     │
│ + │ ${devASG/InstanceRole}                             │ arn:${AWS::Partition}:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly       │
└───┴────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────┘
Security Group Changes
┌───┬─────────────────────────────────────────────────┬─────┬────────────────┬─────────────────────────────────────────────────┐
│   │ Group                                           │ Dir │ Protocol       │ Peer                                            │
├───┼─────────────────────────────────────────────────┼─────┼────────────────┼─────────────────────────────────────────────────┤
│ + │ ${EKSCluster/ControlPlaneSecurityGroup.GroupId} │ In  │ TCP 443        │ ${devASG/InstanceSecurityGroup.GroupId}         │
│ + │ ${EKSCluster/ControlPlaneSecurityGroup.GroupId} │ Out │ Everything     │ Everyone (IPv4)                                 │
├───┼─────────────────────────────────────────────────┼─────┼────────────────┼─────────────────────────────────────────────────┤
│ + │ ${devASG/InstanceSecurityGroup.GroupId}         │ In  │ Everything     │ ${devASG/InstanceSecurityGroup.GroupId}         │
│ + │ ${devASG/InstanceSecurityGroup.GroupId}         │ In  │ TCP 443        │ ${EKSCluster/ControlPlaneSecurityGroup.GroupId} │
│ + │ ${devASG/InstanceSecurityGroup.GroupId}         │ In  │ TCP 1025-65535 │ ${EKSCluster/ControlPlaneSecurityGroup.GroupId} │
│ + │ ${devASG/InstanceSecurityGroup.GroupId}         │ Out │ Everything     │ Everyone (IPv4)                                 │
└───┴─────────────────────────────────────────────────┴─────┴────────────────┴─────────────────────────────────────────────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Do you wish to deploy these changes (y/n)? y
TestEksStack: deploying...
TestEksStack: creating CloudFormation changeset...
  0/21 | 3:26:34 PM | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack            | kubectl-layer-8C2542BC-BF2B-4DFE-B765-E181FD30A9A0 (kubectllayer8C2542BCBF2B4DFEB765E181FD30A9A0617C4ADA)
  0/21 | 3:26:34 PM | CREATE_IN_PROGRESS   | AWS::IAM::Role                        | EKSCluster/Resource/ResourceHandler/ServiceRole (EKSClusterResourceHandlerServiceRoleFD631254)
  0/21 | 3:26:34 PM | CREATE_IN_PROGRESS   | AWS::IAM::Role                        | EKSCluster/ClusterRole (EKSClusterClusterRoleB72F3251)
  0/21 | 3:26:34 PM | CREATE_IN_PROGRESS   | AWS::IAM::Role                        | TestEksStackAdminRole (TestEksStackAdminRole889EDF60)
  0/21 | 3:26:34 PM | CREATE_IN_PROGRESS   | AWS::CDK::Metadata                    | CDKMetadata
  0/21 | 3:26:34 PM | CREATE_IN_PROGRESS   | AWS::EC2::SecurityGroup               | EKSCluster/ControlPlaneSecurityGroup (EKSClusterControlPlaneSecurityGroup580AD1FE)
  0/21 | 3:26:34 PM | CREATE_IN_PROGRESS   | AWS::IAM::Role                        | EKSCluster/Resource/ResourceHandler/ServiceRole (EKSClusterResourceHandlerServiceRoleFD631254) Resource creation Initiated
  0/21 | 3:26:34 PM | CREATE_IN_PROGRESS   | AWS::IAM::Role                        | EKSCluster/ClusterRole (EKSClusterClusterRoleB72F3251) Resource creation Initiated
  0/21 | 3:26:34 PM | CREATE_IN_PROGRESS   | AWS::IAM::Role                        | TestEksStackAdminRole (TestEksStackAdminRole889EDF60) Resource creation Initiated
  0/21 | 3:26:34 PM | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack            | kubectl-layer-8C2542BC-BF2B-4DFE-B765-E181FD30A9A0 (kubectllayer8C2542BCBF2B4DFEB765E181FD30A9A0617C4ADA) Resource creation Initiated
  0/21 | 3:26:35 PM | CREATE_IN_PROGRESS   | AWS::CDK::Metadata                    | CDKMetadata Resource creation Initiated
  1/21 | 3:26:35 PM | CREATE_COMPLETE      | AWS::CDK::Metadata                    | CDKMetadata
  1/21 | 3:26:38 PM | CREATE_IN_PROGRESS   | AWS::EC2::SecurityGroup               | EKSCluster/ControlPlaneSecurityGroup (EKSClusterControlPlaneSecurityGroup580AD1FE) Resource creation Initiated
  2/21 | 3:26:39 PM | CREATE_COMPLETE      | AWS::EC2::SecurityGroup               | EKSCluster/ControlPlaneSecurityGroup (EKSClusterControlPlaneSecurityGroup580AD1FE)
  3/21 | 3:26:48 PM | CREATE_COMPLETE      | AWS::IAM::Role                        | TestEksStackAdminRole (TestEksStackAdminRole889EDF60)
  4/21 | 3:26:48 PM | CREATE_COMPLETE      | AWS::IAM::Role                        | EKSCluster/Resource/ResourceHandler/ServiceRole (EKSClusterResourceHandlerServiceRoleFD631254)
  5/21 | 3:26:48 PM | CREATE_COMPLETE      | AWS::IAM::Role                        | EKSCluster/ClusterRole (EKSClusterClusterRoleB72F3251)
  5/21 | 3:26:50 PM | CREATE_IN_PROGRESS   | AWS::IAM::Policy                      | EKSCluster/Resource/ResourceHandler/ServiceRole/DefaultPolicy (EKSClusterResourceHandlerServiceRoleDefaultPolicy4D087A98)
  5/21 | 3:26:51 PM | CREATE_IN_PROGRESS   | AWS::IAM::Policy                      | EKSCluster/Resource/ResourceHandler/ServiceRole/DefaultPolicy (EKSClusterResourceHandlerServiceRoleDefaultPolicy4D087A98) Resource creation Initiated
  6/21 | 3:26:56 PM | CREATE_COMPLETE      | AWS::CloudFormation::Stack            | kubectl-layer-8C2542BC-BF2B-4DFE-B765-E181FD30A9A0 (kubectllayer8C2542BCBF2B4DFEB765E181FD30A9A0617C4ADA)
  7/21 | 3:27:04 PM | CREATE_COMPLETE      | AWS::IAM::Policy                      | EKSCluster/Resource/ResourceHandler/ServiceRole/DefaultPolicy (EKSClusterResourceHandlerServiceRoleDefaultPolicy4D087A98)
  7/21 | 3:27:05 PM | CREATE_IN_PROGRESS   | AWS::Lambda::Function                 | EKSCluster/Resource/ResourceHandler (EKSClusterResourceHandler31198B21)
  7/21 | 3:27:10 PM | CREATE_IN_PROGRESS   | AWS::Lambda::Function                 | EKSCluster/Resource/ResourceHandler (EKSClusterResourceHandler31198B21) Resource creation Initiated
  8/21 | 3:27:11 PM | CREATE_COMPLETE      | AWS::Lambda::Function                 | EKSCluster/Resource/ResourceHandler (EKSClusterResourceHandler31198B21)
  8/21 | 3:27:12 PM | CREATE_IN_PROGRESS   | Custom::AWSCDK-EKS-Cluster            | EKSCluster/Resource/Resource/Default (EKSClusterE11008B6)
  8/21 | 3:27:15 PM | CREATE_IN_PROGRESS   | Custom::AWSCDK-EKS-Cluster            | EKSCluster/Resource/Resource/Default (EKSClusterE11008B6) Resource creation Initiated
  9/21 | 3:27:15 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-Cluster            | EKSCluster/Resource/Resource/Default (EKSClusterE11008B6) Failed to create resource. An error occurred (ResourceInUseException) when calling the CreateCluster operation: Cluster already exists with name: devEKSCluster
        new CustomResource (D:\work\cdk-apps\eks\node_modules\@aws-cdk\aws-cloudformation\lib\custom-resource.ts:163:21)
        \_ new ClusterResource (D:\work\cdk-apps\eks\node_modules\@aws-cdk\aws-eks\lib\cluster-resource.ts:69:22)
        \_ new Cluster (D:\work\cdk-apps\eks\node_modules\@aws-cdk\aws-eks\lib\cluster.ts:377:18)
        \_ new EKSStack (D:\work\cdk-apps\eks\lib\eks-stack.ts:79:21)
        \_ Object.<anonymous> (D:\work\cdk-apps\eks\bin\eks.ts:8:1)
        \_ Module._compile (internal/modules/cjs/loader.js:701:30)
        \_ Module.m._compile (D:\work\cdk-apps\eks\node_modules\ts-node\src\index.ts:530:23)
        \_ Module._extensions..js (internal/modules/cjs/loader.js:712:10)
        \_ Object.require.extensions.(anonymous function) [as .ts] (D:\work\cdk-apps\eks\node_modules\ts-node\src\index.ts:533:12)
        \_ Module.load (internal/modules/cjs/loader.js:600:32)
        \_ tryModuleLoad (internal/modules/cjs/loader.js:539:12)
        \_ Function.Module._load (internal/modules/cjs/loader.js:531:3)
        \_ Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
        \_ main (D:\work\cdk-apps\eks\node_modules\ts-node\src\bin.ts:212:14)
        \_ Object.<anonymous> (D:\work\cdk-apps\eks\node_modules\ts-node\src\bin.ts:470:3)
        \_ Module._compile (internal/modules/cjs/loader.js:701:30)
        \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
        \_ Module.load (internal/modules/cjs/loader.js:600:32)
        \_ tryModuleLoad (internal/modules/cjs/loader.js:539:12)
        \_ Function.Module._load (internal/modules/cjs/loader.js:531:3)
        \_ Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
        \_ findNodeScript.then.existing (C:\Users\tamizharasanr\AppData\Roaming\npm\node_modules\npm\node_modules\libnpx\index.js:268:14)
  9/21 | 3:27:15 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack            | TestEksStack The following resource(s) failed to create: [EKSClusterE11008B6]. . Rollback requested by user.
  9/21 | 3:27:38 PM | DELETE_IN_PROGRESS   | AWS::IAM::Role                        | TestEksStackAdminRole (TestEksStackAdminRole889EDF60)
  9/21 | 3:27:38 PM | DELETE_IN_PROGRESS   | AWS::CDK::Metadata                    | CDKMetadata
  9/21 | 3:27:38 PM | DELETE_IN_PROGRESS   | Custom::AWSCDK-EKS-Cluster            | EKSCluster/Resource/Resource/Default (EKSClusterE11008B6)
 10/21 | 3:27:39 PM | DELETE_COMPLETE      | AWS::CDK::Metadata                    | CDKMetadata
 11/21 | 3:27:39 PM | DELETE_COMPLETE      | AWS::IAM::Role                        | TestEksStackAdminRole (TestEksStackAdminRole889EDF60)
11/21 Currently in progress: TestEksStack, EKSClusterE11008B6
 12/21 | 3:37:17 PM | DELETE_COMPLETE      | Custom::AWSCDK-EKS-Cluster            | EKSCluster/Resource/Resource/Default (EKSClusterE11008B6)
 12/21 | 3:37:18 PM | DELETE_IN_PROGRESS   | AWS::EC2::SecurityGroup               | EKSCluster/ControlPlaneSecurityGroup (EKSClusterControlPlaneSecurityGroup580AD1FE)
 12/21 | 3:37:18 PM | DELETE_IN_PROGRESS   | AWS::Lambda::Function                 | EKSCluster/Resource/ResourceHandler (EKSClusterResourceHandler31198B21)
 13/21 | 3:37:19 PM | DELETE_COMPLETE      | AWS::Lambda::Function                 | EKSCluster/Resource/ResourceHandler (EKSClusterResourceHandler31198B21)
 14/21 | 3:37:19 PM | DELETE_COMPLETE      | AWS::EC2::SecurityGroup               | EKSCluster/ControlPlaneSecurityGroup (EKSClusterControlPlaneSecurityGroup580AD1FE)
 14/21 | 3:37:19 PM | DELETE_IN_PROGRESS   | AWS::CloudFormation::Stack            | kubectl-layer-8C2542BC-BF2B-4DFE-B765-E181FD30A9A0 (kubectllayer8C2542BCBF2B4DFEB765E181FD30A9A0617C4ADA)
 14/21 | 3:37:19 PM | DELETE_IN_PROGRESS   | AWS::IAM::Policy                      | EKSCluster/Resource/ResourceHandler/ServiceRole/DefaultPolicy (EKSClusterResourceHandlerServiceRoleDefaultPolicy4D087A98)
 15/21 | 3:37:20 PM | DELETE_COMPLETE      | AWS::IAM::Policy                      | EKSCluster/Resource/ResourceHandler/ServiceRole/DefaultPolicy (EKSClusterResourceHandlerServiceRoleDefaultPolicy4D087A98)
 15/21 | 3:37:20 PM | DELETE_IN_PROGRESS   | AWS::IAM::Role                        | EKSCluster/Resource/ResourceHandler/ServiceRole (EKSClusterResourceHandlerServiceRoleFD631254)
 15/21 | 3:37:20 PM | DELETE_IN_PROGRESS   | AWS::IAM::Role                        | EKSCluster/ClusterRole (EKSClusterClusterRoleB72F3251)
 16/21 | 3:37:22 PM | DELETE_COMPLETE      | AWS::IAM::Role                        | EKSCluster/ClusterRole (EKSClusterClusterRoleB72F3251)
 17/21 | 3:37:22 PM | DELETE_COMPLETE      | AWS::IAM::Role                        | EKSCluster/Resource/ResourceHandler/ServiceRole (EKSClusterResourceHandlerServiceRoleFD631254)

 ❌  TestEksStack failed: Error: The stack named TestEksStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
The stack named TestEksStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
```

### Environment

  - **CLI Version      :**  1.18.0 (build bc924bc)
  - **Framework Version:**  "@aws-cdk/aws-eks": "^1.15.0"
  - **OS               :** Windows 10
  - **Language         :** typescript

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by eladb**
There were two causes of timeouts for EKS cluster creation: create time which is longer than the AWS Lambda timeout (15min) and lack of retry when applying kubectl after the cluster has been created.

The change fixes the first issue by leveraging the custom resource provider framework to implement the cluster resource as an async resource. The custom resource providers are now bundled as nested stacks so they don't take up too many resources from users, and are also reused by multiple clusters within the same stack. This required that the creation role will not be the same as the lambda role, so we define this role separately and assume it within the providers.

The second issue is fixed by adding 3 retries to "kubectl apply".

**Backwards compatibility**: as described in #5544, since the resource provider handler of `Cluster` and `KubernetesResource` has been changed, this change requires a replacement of existing clusters (deployment fails with "service token cannot be changed" error). Since this can be disruptive to users, this change includes an exact copy of the previous version under a new module called `@aws-cdk/aws-eks-legacy`, which can be used as a drop-in replacement until users decide to upgrade to the new version. Using the legacy cluster will emit a synthesis warning that this module will no longer be released as part of the CDK starting March 1st, 2020.

- [x] Fixes #4087
- [x] Fixes #4695
- [x] Fixes #5259
- [x] Fixes #5501

---

BREAKING CHANGE: (in experimental module) the providers behind the AWS EKS module have been rewritten to address multiple stability issues. Since this change requires cluster replacement, the old version of this module is available under `@aws-cdk/aws-eks-legacy`. Please read https://github.com/aws/aws-cdk/issues/5544 carefully for upgrade instructions.

---

TODO:

- [x] Decide what to do about backwards compatibility (since we replaced the resource providers)
- [x] Verify if this resolves other pending EKS bugs
- [x] Migrate the `HelmChartResource` construct to CR framework
- [ ] Unit tests for `KubernetesResource` and `HelmChartResource`

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/index.ts [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+  return eks;
+}
+
+export async function onEvent(event: AWSLambda.CloudFormationCustomResourceEvent) {
+  const provider = new ClusterResourceHandler(defaultEksClient, event);
+  switch (event.RequestType) {
+    case 'Create': return provider.onCreate();
+    case 'Update': return provider.onUpdate();
+    case 'Delete': return provider.onDelete();
+  }
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/index.ts]: Hmmm... `ClusterResourceHandler` has the `event`, so it could determine by itself which method should be invoked... Maybe have a single `onEvent()` or `handleEvent()` method instead?

File: packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/index.ts [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+}
+
+export async function isComplete(event: AWSLambda.CloudFormationCustomResourceEvent): Promise<IsCompleteResponse> {
+  const provider = new ClusterResourceHandler(defaultEksClient, event);
+  switch (event.RequestType) {
+    case 'Create': return provider.isCreateComplete();
+    case 'Update': return provider.isUpdateComplete();
+    case 'Delete': return provider.isDeleteComplete();
+  }
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/index.ts]: Same here... this could be a simple `isComplete` from here...

File: packages/@aws-cdk/aws-eks/lib/cluster-resource-provider.ts [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+      runtime: HANDLER_RUNTIME,
+      handler: 'index.isComplete',
+      timeout: Duration.minutes(1)
+    });
+
+    this.provider = new cr.Provider(this, 'Provider', {
+      onEventHandler: onEvent,
+      isCompleteHandler: isComplete,
+      totalTimeout: Duration.hours(1),
+      queryInterval: Duration.minutes(1)
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-eks/lib/cluster-resource-provider.ts]: I would not find what the rate limits are for the EKS service endpoints. I feel like `1 minute` may be very aggressive... And could cause throttling if multiple clusters deploy simultaneously.

File: packages/@aws-cdk/aws-eks/lib/cluster-resource.ts [hunk 4]
```diff
@@ -32,51 +30,66 @@ export class ClusterResource extends Construct {
...
 
     // the CreateCluster API will allow the cluster to assume this role, so we
     // need to allow the lambda execution role to pass it.
-    handler.addToRolePolicy(new iam.PolicyStatement({
+    this.creationRole.addToPolicy(new iam.PolicyStatement({
       actions: [ 'iam:PassRole' ],
       resources: [ props.roleArn ]
     }));
 
+    // since we don't know the cluster name at this point, we must give this role star resource permissions
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-eks/lib/cluster-resource.ts]: We know the cluster name if the user specified it...

File: packages/@aws-cdk/aws-eks/lib/cluster-resource.ts [hunk 5]
```diff
@@ -32,51 +30,66 @@ export class ClusterResource extends Construct {
    * that gets administrator privilages on the cluster (`system:masters`), and
    * will be able to issue `kubectl` commands against it.
    */
-  public readonly creationRole: iam.IRole;
+  private readonly creationRole: iam.Role;
+  private readonly trustedPrincipals: string[] = [];
 
   constructor(scope: Construct, id: string, props: CfnClusterProps) {
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-eks/lib/cluster-resource.ts]: This accepts `CfnClusterProps`, makes it a very leaky abstraction, and I'd argue this is not ideal. Especially not since you don't control that API and CloudFormation can shamelessly break it under you.

File: packages/@aws-cdk/aws-eks/lib/cluster-resource.ts [hunk 6]
```diff
@@ -32,51 +30,66 @@ export class ClusterResource extends Construct {
...
+    // since we don't know the cluster name at this point, we must give this role star resource permissions
+    this.creationRole.addToPolicy(new iam.PolicyStatement({
+      actions: [ 'eks:CreateCluster', 'eks:DescribeCluster', 'eks:DeleteCluster', 'eks:UpdateClusterVersion', 'eks:UpdateClusterConfig' ],
+      resources: [ '*' ]
+    }));
+
     const resource = new cfn.CustomResource(this, 'Resource', {
       resourceType: ClusterResource.RESOURCE_TYPE,
-      provider: cfn.CustomResourceProvider.lambda(handler),
+      provider: provider.provider,
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-eks/lib/cluster-resource.ts]: The `provider` provides the `provider` that is the `provider`.

File: packages/@aws-cdk/aws-eks/lib/cluster-resource.ts [hunk 7]
```diff
@@ -32,51 +30,66 @@ export class ClusterResource extends Construct {
...
       properties: {
-        Config: props
+        Config: props,
+        AssumeRoleArn: this.creationRole.roleArn
       }
     });
 
+    resource.node.addDependency(this.creationRole);
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-eks/lib/cluster-resource.ts]: Is this dependency not implied by the fact it receives the `creationRole.roleArn` through it's properties? Or is this so you also catch any separate `Policy` resources that may be created & attached?

File: packages/@aws-cdk/aws-eks/lib/cluster-resource.ts [hunk 8]
```diff
@@ -32,51 +30,66 @@ export class ClusterResource extends Construct {
...
+   * Returns the ARN of the cluster creation role and grants `trustedRole`
+   * permissions to assume this role.
+   */
+  public getCreationRoleArn(trustedRole: iam.IRole): string {
+    if (!this.trustedPrincipals.includes(trustedRole.roleArn)) {
+      this.creationRole.assumeRolePolicy?.addStatements(new iam.PolicyStatement({
+        actions: [ 'sts:AssumeRole' ],
+        principals: [ new iam.ArnPrincipal(trustedRole.roleArn) ]
+      }));
+      this.trustedPrincipals.push(trustedRole.roleArn);
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-eks/lib/cluster-resource.ts]: This is a lie if `this.creationRole.assumeRolePolicy` is undefined, as the above statement is defensive against...

File: packages/@aws-cdk/aws-eks/lib/helm-chart.ts [hunk 9]
```diff
@@ -93,31 +97,49 @@ export class HelmChart extends Construct {
...
+   * The custom resource provider.
+   */
+  public readonly provider: cr.Provider;
+
+  /**
+   * The IAM role used to execute this provider.
+   */
+  public readonly role: iam.IRole;
+
+  constructor(scope: Construct, id: string) {
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-eks/lib/helm-chart.ts]: Should this be `private`? I reckon people ought to use `getOrCreate` and only that...

File: packages/@aws-cdk/aws-eks/lib/helm-chart/index.py [hunk 10]
```diff
@@ -1,10 +1,7 @@
-import subprocess
-import os
 import json
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-eks/lib/helm-chart/index.py]: Any reason why this is `python` when the other is `Javascript`? I'm strongly in favor of reducing the amount of different runtimes involved in all those custom resources we maintain (increases barrier to contributions by requiring multiple languages, makes it more difficult to track security & reliability issues that need patching, ...).

File: packages/@aws-cdk/aws-eks/lib/k8s-resource-handler/index.py [hunk 11]
```diff
@@ -0,0 +1,66 @@
+import json
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-eks/lib/k8s-resource-handler/index.py]: Likewise here - would much rather have everything be `Javascript` and not sometimes Python, sometimes JS for no apparent reason.

File: packages/@aws-cdk/aws-eks/lib/k8s-resource.ts [hunk 12]
```diff
@@ -51,23 +56,69 @@ export class KubernetesResource extends Construct {
...
+   * The custom resource provider.
+   */
+  public readonly provider: cr.Provider;
+
+  /**
+   * The IAM role used to execute this provider.
+   */
+  public readonly role: iam.IRole;
+
+  constructor(scope: Construct, id: string) {
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-eks/lib/k8s-resource.ts]: As before, this should probably be `private`.

File: packages/@aws-cdk/aws-eks-legacy/README.md [hunk 13]
```diff
@@ -0,0 +1,423 @@
+## Amazon EKS Construct Library
+
+<!--BEGIN STABILITY BANNER-->
+
+---
+
+![Stability: Deprecated](https://img.shields.io/badge/stability-Deprecated-critical.svg?style=for-the-badge)
```
[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/aws-eks-legacy/README.md]: `@aws-cdk/aws-eks/legacy` won't be available in jsii, so it has to be a top-level package at the moment.

> I kinda would like us to decide when we'd drop the legacy version support

I like this idea. I'll add a warning that the legacy will no longer be released after March 1st, 2020 (some arbitrary time).

File: packages/@aws-cdk/aws-eks-legacy/README.md [hunk 14]
```diff
@@ -0,0 +1,423 @@
...
+
+> This API may emit warnings. Backward compatibility is not guaranteed.
+
+---
+<!--END STABILITY BANNER-->
+
+#### It is recommended to use @aws-cdk/aws-eks instead of this module.
```
[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/aws-eks-legacy/README.md]: Done

File: packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts [hunk 15]
```diff
@@ -0,0 +1,222 @@
...
+    console.log('createCluster:', JSON.stringify(this.newProps, undefined, 2));
+    if (!this.newProps.roleArn) {
+      throw new Error('"roleArn" is required');
+    }
+
+    const clusterName = this.newProps.name || `${this.logicalResourceId}-${this.requestId}`;
+
+    const resp = await this.eks.createCluster({
+      name: clusterName,
+      ...this.newProps,
```
[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts]: fixed. thanks

File: packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts [hunk 16]
```diff
@@ -0,0 +1,222 @@
...
+    });
+
+    return {
+      PhysicalResourceId: resp.cluster!.name
```
[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts]: Fixed.

File: packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts [hunk 17]
```diff
@@ -0,0 +1,222 @@
...
+  }
+
+  // ------
+  // UPDATE
+  // ------
+
+  public async onUpdate() {
+    const updates = analyzeUpdate(this.oldProps, this.newProps);
+
+    console.log(updates);
```
[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts]: Fixed.

File: packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts [hunk 18]
```diff
@@ -0,0 +1,222 @@
...
+
+    // if there is an update that requires replacement, go ahead and just create
+    // a new cluster with the new config. The old cluster will automatically be
+    // deleted by cloudformation upon success.
+    if (updates.replaceName || updates.replaceRole || updates.replaceVpc) {
+      return await this.onCreate();
+    }
```
[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts]: This is usually the behavior for replacement of resources with physical names. If the name is different, all is good. If the name is the same, it will simply fail creating the new cluster saying there's already a cluster with that name.

I guess we can proactively fail with a nicer error, but most CFN resources actually just fail with the error I described above, so I don't know if this is really required. Punting for now, but added some commentary.

[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts]: ok, I am convinced, added an explicit check with a nice error

File: packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts [hunk 19]
```diff
@@ -0,0 +1,222 @@
...
+
+    return {
+      IsComplete: true,
+      Data: {
+        Name: cluster.name,
+        Endpoint: cluster.endpoint,
+        Arn: cluster.arn,
+        CertificateAuthorityData: cluster.certificateAuthority && cluster.certificateAuthority.data
+      }
+    };
```
[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts]: The resource provider framework explicitly forbids returning data as long as the operation is not complete (otherwise, it will need to somehow synthesize the state from all retries).

`Data` is the CloudFormation resource attributes (`Fn::GetAtt`). `Status` is not an attribute of the resource since it's a transient value.

File: packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts [hunk 20]
```diff
@@ -0,0 +1,222 @@
...
+  configureAssumeRole(request: aws.STS.AssumeRoleRequest): void;
+  createCluster(request: aws.EKS.CreateClusterRequest): Promise<aws.EKS.CreateClusterResponse>;
+  deleteCluster(request: aws.EKS.DeleteClusterRequest): Promise<aws.EKS.DeleteClusterResponse>;
+  describeCluster(request: aws.EKS.DescribeClusterRequest): Promise<aws.EKS.DescribeClusterResponse>;
+  updateClusterConfig(request: aws.EKS.UpdateClusterConfigRequest): Promise<aws.EKS.UpdateClusterConfigResponse>;
+  updateClusterVersion(request: aws.EKS.UpdateClusterVersionRequest): Promise<aws.EKS.UpdateClusterVersionResponse>;
+}
+
+function parseProps(props: any): aws.EKS.CreateClusterRequest {
+  return (props && props.Config) || { };
```
[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts]: Yey!

File: packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/index.ts [hunk 21]
```diff
@@ -0,0 +1,52 @@
...
+  updateClusterConfig: req => getEksClient().updateClusterConfig(req).promise(),
+  updateClusterVersion: req => getEksClient().updateClusterVersion(req).promise(),
+  configureAssumeRole: req => {
+    console.log(JSON.stringify({ assumeRole: req }, undefined, 2));
+    const creds = new aws.ChainableTemporaryCredentials({
+      params: req
+    });
+
+    eks = new aws.EKS({ credentials: creds });
+  }
```
[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/index.ts]: Life is shameful

File: packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/index.ts (hunk 2 above)
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/index.ts]: Done!

File: packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/index.ts (hunk 1 above)
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/index.ts]: Done!

File: packages/@aws-cdk/aws-eks/lib/cluster-resource-provider.ts (hunk 3 above)
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource-provider.ts]: Haven't seen any throttling issues, but I agree that 1 min is aggressive given in average it takes about 15 minutes to provision a cluster...

Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource-provider.ts]: Changed to 5min

File: packages/@aws-cdk/aws-eks/lib/cluster-resource.ts (hunk 4 above)
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource.ts]: That's a good point, I can use it if it is explicitly specified.

Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource.ts]: Dobne

File: packages/@aws-cdk/aws-eks/lib/cluster-resource.ts (hunk 5 above)
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource.ts]: This is intentional. I wanted the custom resource (which is not publically exported) to have the exact same API as the stock CFN resource.

File: packages/@aws-cdk/aws-eks/lib/cluster-resource.ts (hunk 6 above)
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource.ts]: Exactly.

File: packages/@aws-cdk/aws-eks/lib/cluster-resource.ts (hunk 7 above)
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource.ts]: yes, the policy is a different and it is not implied.

Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource.ts]: That was the IAM issue I needed your help with

File: packages/@aws-cdk/aws-eks/lib/cluster-resource.ts (hunk 8 above)
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource.ts]: fair enough, added a defensive check

File: packages/@aws-cdk/aws-eks/lib/helm-chart.ts (hunk 9 above)
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/helm-chart.ts]: Yap, changed.

File: packages/@aws-cdk/aws-eks/lib/helm-chart/index.py (hunk 10 above)
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/helm-chart/index.py]: yes, I need to use the AWS CLI (from the layer) and it requires a python runtime

File: packages/@aws-cdk/aws-eks/lib/k8s-resource-handler/index.py (hunk 11 above)
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/k8s-resource-handler/index.py]: Same reason.

File: packages/@aws-cdk/aws-eks/lib/k8s-resource.ts (hunk 12 above)
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/k8s-resource.ts]: Done

File: packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts [hunk 22]
```diff
@@ -0,0 +1,222 @@
...
+  console.log('new props: ', JSON.stringify(newProps));
+
+  const newVpcProps = newProps.resourcesVpcConfig || { };
+  const oldVpcProps = oldProps.resourcesVpcConfig || { };
+
+  return {
+    replaceName: newProps.name !== oldProps.name,
+    replaceVpc:
+      JSON.stringify(newVpcProps.subnetIds) !== JSON.stringify(oldVpcProps.subnetIds) ||
+      JSON.stringify(newVpcProps.securityGroupIds) !== JSON.stringify(oldVpcProps.securityGroupIds),
```
[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts]: Indeed, I'll leave this for now given there is no simple solution.

File: packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts (hunk 19 above)
[the remark this answers is not in the document]
Comment (RomainMuller) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts]: Oh I see. Thanks for RTFM for me :)

File: packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts (hunk 22 above)
[the remark this answers is not in the document]
Comment (RomainMuller) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts]: I'm happy to let it fly so long as false positives here result in idempotent success (wasting a little effort, but not bailing out on the user).

File: packages/@aws-cdk/aws-eks/lib/cluster-resource.ts (hunk 5 above)
Comment (RomainMuller) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource.ts]: Okay - but then this class' stability _must_ be the same as the stock CFN resource's (aka `@stability external`).

File: packages/@aws-cdk/aws-eks-legacy/README.md (hunk 13 above)
[the remark this answers is not in the document]
Comment (RomainMuller) [reply packages/@aws-cdk/aws-eks-legacy/README.md]: Oh right. Of all people you'd think I would think about `jsii` support... 🤦🏻‍♂️

File: packages/@aws-cdk/aws-eks/lib/cluster-resource.ts (hunk 5 above)
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource.ts]: This is an internal unexported class. There is no meaning to it’s @stability annotation.

File: packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts (hunk 22 above)
[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts]: Cool

File: packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts [hunk 23]
```diff
@@ -0,0 +1,222 @@
...
+  private async updateClusterVersion(newVersion: string) {
+    // update-cluster-version will fail if we try to update to the same version,
+    // so skip in this case.
+    const cluster = (await this.eks.describeCluster({ name: this.clusterName })).cluster!;
+    if (cluster.version === newVersion) {
+      console.log(`cluster already at version ${cluster.version}, skipping version update`);
+      return;
+    }
+
+    await this.eks.updateClusterVersion({ name: this.clusterName, version: newVersion });
```
[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/handler.ts]: I’ll leave this for a future fix. It is a potential race condition but I suspect it won’t be an issue for most customers and worst case the version update will fail.
