### PR TITLE
fix(batch):  undeprecate useOptimalInstanceClasses   property

### LINKED ISSUE #36291: aws-batch: deprecated useOptimalInstanceClasses property is still needed
### Describe the bug

Issue #35515 / release 2.220 deprecated property `useOptimalInstanceClasses` of managed compute environments. But this option is still needed if users want to avoid including `optimal` in a compute environment's instance types.

Please remove the deprecation warning for use of this property, or change its default to `false`.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Library Version

2.219

### Expected Behavior

No deprecation warning.

### Current Behavior

Deprecation warning when use `useOptimalInstanceClasses`.

### Reproduction Steps

Synthesize a cdk stack with a Batch compute environment and setting `useOptimalInstanceClasses`.

### Possible Solution

Revert the deprecation.

### Additional Information/Context

_No response_

### AWS CDK Library version (aws-cdk-lib)

2.220

### AWS CDK CLI version

2.1033.0

### Node.js Version

22.18.0

### OS

AL2023

### Language

Python

### Language Version

3.11

### Other information

_No response_

### PR DESCRIPTION
**Pull request by badmintoncryer**
### Issue # (if applicable)

Closes #36291.

### Reason for this change

The `useOptimalInstanceClasses` property was deprecated in v2.220 in favor of `defaultInstanceClasses`, but there is no way to exclude the `optimal` instance type using `defaultInstanceClasses` alone. Users who want to specify only custom instance types (e.g., R4 only) without `optimal` being automatically added have no non-deprecated path forward.

Setting `defaultInstanceClasses: []` (empty array) does not prevent `optimal` from being added because the current logic treats an empty array the same as `undefined`.

### Description of changes

- Removed `@deprecated` annotation from `useOptimalInstanceClasses` property
- Updated README to remove the deprecation warning and reorganized the "Choosing Your Instance Types" section with:
  - Clear subsections for each use case (Default Instance Classes, Specific Instance Types Only, Optimal Instance Classes)
  - A configuration reference table for quick lookup
  - Example showing how to use `useOptimalInstanceClasses: false` to exclude `optimal`

#### Alternatives considered

Three options were discussed in #36291:

1. **Remove deprecation** (this PR) - Restores `useOptimalInstanceClasses` as a non-deprecated property
2. **Treat empty `defaultInstanceClasses: []` as "exclude all defaults"** - Would introduces implicit behavior
3. **Change default behavior** - Breaking change, not acceptable

Option 1 was chosen because:
- Minimal code change (documentation only)
- No risk of breaking existing users
- `useOptimalInstanceClasses` provides explicit, clear control that `defaultInstanceClasses` cannot fully replace

### Describe any new or updated permissions being added

N/A

### Description of how you validated changes

Existing tests

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts [hunk 1]
```diff
@@ -942,7 +941,6 @@ export interface ManagedEc2EksComputeEnvironmentProps extends ManagedComputeEnvi
    * C4, M4, and R4 instance classes. You can specify other instance classes
    * (of the same architecture) in addition to the optimal instance classes.
    *
-   * @deprecated use defaultInstanceClasses instead
```
Comment (aemada-aws) [inline packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts:945]: Need to also change the error message here on line 1074 to remove "Please remove deprecated `useOptimalInstanceClasses"
 
https://github.com/aws/aws-cdk/pull/36353/files#diff-7ae09067a7ce8a58d494da3c01be13161be021e9cdb96008221d6e16cd0366b3R1074

File: packages/aws-cdk-lib/aws-batch/README.md [hunk 2]
```diff
@@ -65,68 +65,84 @@ For stateful or otherwise non-interruption-tolerant workflows, omit `spot` or se
...
+##### Using Optimal Instance Classes (Default Behavior)
 
-Unless you explicitly specify `useOptimalInstanceClasses: false`, this compute environment will use `'optimal'` instances,
-which tells Batch to pick an instance from the C4, M4, and R4 instance families.
-*Note*: Batch does not allow specifying instance types or classes with different architectures.
-For example, `InstanceClass.A1` cannot be specified alongside `'optimal'`,
-because `A1` uses ARM and `'optimal'` uses x86_64.
-You can specify both `'optimal'` alongside several different instance types in the same compute environment:
+By default, `useOptimalInstanceClasses` is `true`, which adds the `optimal` instance type.
+The `optimal` type tells Batch to pick instances from the C4, M4, and R4 families.
```
Comment (aemada-aws) [inline packages/aws-cdk-lib/aws-batch/README.md]: Can you add that starting from 11/01/2025, the behavior of `optimal` is equivalent to `defaultInstanceClasses: [DefaultInstanceClass.X86_64]`? 
Source: https://docs.aws.amazon.com/batch/latest/userguide/optimal-default-instance-troubleshooting.html

**Comment by badmintoncryer** [comment]
@aemada-aws Thank you for your review. I've addressed all of your comments. Could you please confirm this again?

**Review by aemada-aws — APPROVED** [review]

**Review by aemada-aws — APPROVED** [review]
