### PR TITLE
fix(iam): Role policies cannot grow beyond 10k

### LINKED ISSUE #19276: Tracking: Policy-generation creates oversized templates
### Overview

A number of customers in separate issues (as well as internal tickets) have reported problems with automatic policy generation executed by the CDK for various services. The most recurrent and problematic of those are the oversized policies generated that exceed maximum size.

This issue is to aggregate and track those separate issues and resolve once system has been revamped/revised.

### Link to the service’s CDK Construct Library API reference page.

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam-readme.html

### Maturity: CloudFormation Resources Only

Stable

## PRs
- [fix(iam): IAM Policies are too large to deploy by rix0rrr · Pull Request #19114 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/pull/19114)
- [fix(codepipeline): large cross-region pipelines exceed IAM policy size limit by skinny85 · Pull Request #16350 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/pull/16350)
- [feat(iam): session tagging by rix0rrr · Pull Request #17689 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/pull/17689)

## Reports
- [(aws-iam): changes in #17689 increase assume role policy size · Issue #18564 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/18564)
- [ECS: Task role default policies race condition · Issue #18675 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/18675)
- [IAM: Maximum policy size of 10240 bytes exceeded for role.. · Issue #18457 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/18457)
- [aws-codepipeline: cross region support creates huge inline policy document for the pipeline role · Issue #16244 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/16244)
- [(iam) Role policies are frequently exceeding 10kB · Issue #14261 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/14261)
- [ECS Secrets from SSM ParamStore exceeds IAM Policy size · Issue #8435 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/8435)
- [How to avoid zillions of conditional policy statements? · Issue #7732 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/7732)
- [aws-cdk_pipelines: Maximum policy size of 10240 bytes exceeded for role · Issue #18531 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/18531)
- [CodePipeline: Maximum policy size of 10240 bytes exceeded for role xxx · Issue #19243 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/19243)
- [(aws_ecs): CDK insists on Modifying the ECS Execution/Task Role with duplicate permissions, resulting policy Is too big to deploy · Issue #18926 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/18926)
- [(IAM Role) : Maximum policy size of 10240 bytes exceeded for role · Issue #12403 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/12403)
- [[cdk-pipelines] Pipeline template grows very fast reaching the 460,800 bytes limit from CloudFormation · Issue #9225 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/9225)
- [[@aws-cdk/pipelines] Maximum policy size of 10240 bytes exceeded for role · Issue #9316 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/9316)
- [CodePipeline/CodeBuild: Maximum policy size of 10240 bytes exceeded for role xxx-role · Issue #4465 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/4465)
- [(aws-cdk/pipelines): mutates role even if `withoutPolicyUpdates()` is passed · Issue #18167 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/18167)
- [(@aws-cdk/aws-apigatewayv2-alpha): After adding around 30 routes to a http api, I got policy PolicyLengthExceededException](https://github.com/aws/aws-cdk/issues/19535#)
- [APIGateway LambdaIntegration: Add option to create a single trigger/permission with wildcards only instead of one for each ApiGateway Resource](https://github.com/aws/aws-cdk/issues/9327#)
- [CodePipeline: still getting 'Maximum policy size of 10240 bytes exceeded for role' for cross-account pipeline](https://github.com/aws/aws-cdk/issues/19835#)

## Potential Workarounds/Suggestions
- [CDK Grants into AWS Managed Policy · Issue #7448 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/7448)
- [IAM/Secrets Manager/ECS: Consolidate IAM policies under path · Issue #18458 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/18458)
- [(aws-s3): supply custom role when adding bucket notifications · Issue #13241 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/13241)
- [[iam] iam.Group should check if inline policy exceeds maximum size · Issue #11562 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/11562)
- [lambda policy size exceeds limit when used with multiple RestApi methods · Issue #5774 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/5774)
- [(iam): how to create combined managed policy? · Issue #12111 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/12111)
- [(aws-iam): policy document optimization · Issue #14713 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/14713)

### LINKED ISSUE #19835: CodePipeline: still getting 'Maximum policy size of 10240 bytes exceeded for role' for cross-account pipeline
### Describe the bug

We recently filed an issue about how CodePipeline was failing due to the generation of extremely large IAM policy documents:

https://github.com/aws/aws-cdk/issues/19243

Our issue was closed and it was suggested that this PR might fix it:

https://github.com/aws/aws-cdk/pull/19114

This tracking issue was closed via that PR:

https://github.com/aws/aws-cdk/issues/19276

We have since upgraded our CDK version to `2.19.0` and set `@aws-cdk/aws-iam:minimizePolicies` to `true`.

This did seem to decrease the size of some IAM policies, but we are still hitting the same failure.

### Expected Behavior

Expected https://github.com/aws/aws-cdk/pull/19114 to reduce generated IAM policy sizes so that our pipeline would deploy.

### Current Behavior

Pipeline still fails to deploy with `Maximum policy size of 10240 bytes exceeded for role xxx`.

See attachment for example of the offending IAM policy.  The policy contains three statements, and the third one is the offending one.  It is granting `AssumeRole` to all of the roles for all of the actions in all of the accounts that this pipeline is trying to deploy to.

See attachment for example (sanitized) policy.
[pipelineofpipelinesstackcoreinfrastructurepipeline03AEF9CA.template.JUST_OFFENDING_POLICY.sanitized.json.gz](https://github.com/aws/aws-cdk/files/8455041/pipelineofpipelinesstackcoreinfrastructurepipeline03AEF9CA.template.JUST_OFFENDING_POLICY.sanitized.json.gz)

There are 97 resources in that statement, they look like this:

```
                {
                  "Fn::GetAtt": [
                    "pipelinecoreinfrastructureDeployProdcelluseast1produseast1synthCodePipelineActionRole8A60FDE1",
                    "Arn"
                  ]
                },
```

and this:

```
                {
                  "Fn::Join": [
                    "",
                    [
                      "arn:",
                      {
                        "Ref": "AWS::Partition"
                      },
                      ":iam::111111111111:role/core-infrastructure-pipelhangesactionroleb355ae8d7595154ac81b"
                    ]
                  ]
                },
```

### Reproduction Steps

Create a CodePipeline that creates additional Pipelines.  In one of those additional pipelines, create a large number of actions that target multiple AWS accounts.

It would take some non-trivial effort for me to extract a concise reproducer from our current (private) code, but pending the responses to the questions above about whether this is still expected behavior, how to override the Role, etc., I am willing to try to put one together!

### Possible Solution

It's not clear to me whether this behavior is still expected after the fix in https://github.com/aws/aws-cdk/pull/19114 was released.

We are looking for guidance on:

* Whether this is still a known issue in CDK
* Whether it is expected that additional fixes will be merged to address this

Also, there seem to be a ton of other tickets related to this, and in several of them it is hinted that users with advanced use cases like ours may need to opt out of this automatic policy generation, and override the Role with one that we manage ourselves (which might use wildcards or multiple policy attachments, etc.).  If that is the current prescription, it would be wonderful if there were some official docs or examples that illustrated how to do this; I haven't really seen anything so far that gives me a concrete idea of how to even attempt it.

### Additional Information/Context

_No response_

### CDK CLI Version

2.19.0

### Framework Version

2.19.0

### Node.js Version

v16.5.0

### OS

Amazon Linux 2

### Language

Typescript

### Language Version

TypeScript 4.4.2

### Other information

_No response_

### LINKED ISSUE #19939: CodePipeline: AssetsFileRoleDefaultPolicy exceeds IAM policy limit (10KB) when deploying to ~72 targets
### Describe the bug

In order for CDK actions to deploy to remote accounts/regions, CloudFormation templates and local assets (i.e. Lambda zip files) are uploaded to an assets bucket in each of those accounts/regions. 

As the CDK manages `AssetsFileRoleDefaultPolicy` associated to the IAM role used by CodeBuild to publish those assets, it keeps updating it with allow actions for assuming the remote `file-publishing-role` roles creating by the bootstrap process. This method of 1 block per account/region pair causes the policy size to exceed IAM policy maximum limit at 72 targets (72 accounts in 1x region, or 31 in 2x regions, etc.). 

### Expected Behavior

It is common for enterprises to deploy to 100s (if not 1000s of targets). We expect the CDK to allow us to pass our own policies for every stage of the pipeline, including assets publishing stage. We also expect the CDK to be aware of CloudFormation and IAM limits and abstract the complexity of managing those services.

### Current Behavior

This is an example of the policy created by the CDK (minified size > 10KB)

```
{
    "accountsbaseliningpipelinexxxxxxxxxxxx0AssetsFileRoleDefaultPolicyxxxxxxxx": {
        "Type": "AWS::IAM::Policy",
        "Properties": {
            "PolicyDocument": {
                "Statement": [
                    {
                        "Action": [
                            "logs:CreateLogGroup",
                            "logs:CreateLogStream",
                            "logs:PutLogEvents"
                        ],
                        "Effect": "Allow",
                        "Resource": {
                            "Fn::Join": [
                                "",
                                [
                                    "arn:",
                                    {
                                        "Ref": "AWS::Partition"
                                    },
                                    ":logs:region-1:xxxxxxxxxxxx:log-group:/aws/codebuild/*"
                                ]
                            ]
                        }
                    },
                    {
                        "Action": [
                            "codebuild:CreateReportGroup",
                            "codebuild:CreateReport",
                            "codebuild:UpdateReport",
                            "codebuild:BatchPutTestCases",
                            "codebuild:BatchPutCodeCoverages"
                        ],
                        "Effect": "Allow",
                        "Resource": {
                            "Fn::Join": [
                                "",
                                [
                                    "arn:",
                                    {
                                        "Ref": "AWS::Partition"
                                    },
                                    ":codebuild:region-1:xxxxxxxxxxxx:report-group/*"
                                ]
                            ]
                        }
                    },
                    {
                        "Action": [
                            "codebuild:BatchGetBuilds",
                            "codebuild:StartBuild",
                            "codebuild:StopBuild"
                        ],
                        "Effect": "Allow",
                        "Resource": "*"
                    },
                    {
                        "Action": "sts:AssumeRole",
                        "Effect": "Allow",
                        "Resource": [
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/cdk-cdkqualifier-file-publishing-role-${AWS::AccountId}-${AWS::Region}"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-1"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/cdk-cdkqualifier-file-publishing-role-${AWS::AccountId}-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            },
                            {
                                "Fn::Sub": "arn:${AWS::Partition}:iam::xxxxxxxxxxxx:role/cdk-cdkqualifier-file-publishing-role-xxxxxxxxxxxx-region-2"
                            }
                        ]
                    },
                    {
                        "Action": [
                            "s3:GetObject*",
                            "s3:GetBucket*",
                            "s3:List*"
                        ],
                        "Effect": "Allow",
                        "Resource": [
                            {
                                "Fn::GetAtt": [
                                    "accountsbaseliningpipelinexxxxxxxxxxxx0skeletonArtifactsBucket2201989E",
                                    "Arn"
                                ]
                            },
                            {
                                "Fn::Join": [
                                    "",
                                    [
                                        {
                                            "Fn::GetAtt": [
                                                "accountsbaseliningpipelinexxxxxxxxxxxx0skeletonArtifactsBucket2201989E",
                                                "Arn"
                                            ]
                                        },
                                        "/*"
                                    ]
                                ]
                            }
                        ]
                    },
                    {
                        "Action": [
                            "kms:Decrypt",
                            "kms:DescribeKey"
                        ],
                        "Effect": "Allow",
                        "Resource": {
                            "Fn::GetAtt": [
                                "accountsbaseliningpipelinexxxxxxxxxxxx0skeletonArtifactsBucketEncryptionKeyF3A5899F",
                                "Arn"
                            ]
                        }
                    }
                ],
                "Version": "2012-10-17"
            },
            "PolicyName": "accountsbaseliningpipelinexxxxxxxxxxxx0AssetsFileRoleDefaultPolicyxxxxxxxx",
            "Roles": [
                {
                    "Ref": "accountsbaseliningpipelinexxxxxxxxxxxx0AssetsFileRolexxxxxxxx"
                }
            ]
        },
        "Metadata": {
            "aws:cdk:path": "cdk-deployment-pipelines/accounts-baselining-pipeline-3-xxxxxxxxxxxx/Assets/FileRole/DefaultPolicy/Resource"
        }
    }
}
```

### Reproduction Steps

You can reproduce the issue by creating a CodePipeline with actions deploying assets to ~72 account/region pairs.

### Possible Solution

Similar to the CodePipeline Pipeline role that we can pass, allowing us to pass an assets publishing role or policy would solve the problem.

### Additional Information/Context

_No response_

### CDK CLI Version

2.20.0

### Framework Version

_No response_

### Node.js Version

6.14.15

### OS

Amazon Linux 2

### Language

Python

### Language Version

Python 3.8.13

### Other information

_No response_

### PR DESCRIPTION
**Pull request by rix0rrr**
(This change has been split off from https://github.com/aws/aws-cdk/pull/20189 because that PR was growing
too big)

We add all Role policy statements to the Inline policy, which
has a maximums size of 10k. Especially when creating CDK Pipelines
that deploy to a lot of environments, the list of Role ARNs
the Pipeline should be allowed to assume exceeds this size.

Roles also have the ability to have Managed Policies attached
(10 by default, 20 with a quota increase), each of them can be 6k
in size. By spilling over from inline policies into Managed Policies
we can get a total of 70k of statements attached to reach Role.

This PR introduces `IComparablePrincipal` to be able to value-compare
two principals: since we want to merge first before we split (to get the
most bang for our buck), we now need to do statement merging during the
prepare phase, while we are still working on the object graph (instead
of the rendered CloudFormation template).
* That means statement merging had to be modified to work on
  PolicyStatement objects, which requires being able to compare
  Principal objects.

Closes #19276, closes #19939, closes #19835.

----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-iam/lib/policy-document.ts [hunk 1]
```diff
@@ -1,6 +1,8 @@
 import * as cdk from '@aws-cdk/core';
 import * as cxapi from '@aws-cdk/cx-api';
+import { IConstruct } from 'constructs';
 import { PolicyStatement } from './policy-statement';
+import { mergeStatements } from './private/merge-statements';
```
Comment (Naumel) [inline packages/@aws-cdk/aws-iam/lib/policy-document.ts:5]: [nit pick] The capitalization breaks the expected pattern.

File: packages/@aws-cdk/aws-iam/lib/policy-statement.ts [hunk 2]
```diff
@@ -624,4 +704,8 @@ class JsonPrincipal extends PrincipalBase {
       conditions: {},
     };
   }
-}
+
+  public dedupeString(): string | undefined {
+    return JSON.stringify(this.policyFragment);
+  }
+}
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-iam/lib/policy-statement.ts:711]: missing EOF blank line

File: packages/@aws-cdk/aws-iam/lib/principals.ts [hunk 3]
```diff
@@ -312,8 +362,13 @@ export class SessionTagsPrincipal extends PrincipalAdapter {
       return statement;
     }));
   }
+
+  public dedupeString(): string | undefined {
+    return this.appendDedupe('');
+  }
 }
 
+
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-iam/lib/principals.ts:371]: why this blank line?

File: packages/@aws-cdk/aws-iam/lib/private/comparable-principal.ts [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+    }
+  }
+
+  return { comparable, nonComparable };
+}
+
+export interface PartitionResult {
+  readonly nonComparable: IPrincipal[];
+  readonly comparable: Record<string, IPrincipal>;
+}
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-iam/lib/private/comparable-principal.ts:22]: missing EOF blank line.

File: packages/@aws-cdk/aws-iam/lib/policy-statement.ts [hunk 5]
```diff
@@ -473,14 +469,98 @@ export class PolicyStatement {
...
+   */
+  public get conditions(): any {
+    return { ...this._condition };
+  }
+
+  /**
+   * Estimate the size of this policy statement
+   *
+   * By necessity, this will not be accurate. We'll do our best to overestimate
+   * so we won't have nasty surprises.
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-iam/lib/policy-statement.ts:534]: Is there any fallback for underestimates? If we underestimate the size, we could run into Policy size limitations; that could be a deploy time error.

File: packages/@aws-cdk/aws-iam/lib/private/merge-statements.ts [hunk 6]
```diff
@@ -59,34 +89,41 @@ export function mergeStatements(statements: StatementSchema[]): StatementSchema[
...
 
   if (setsEqual < 2 || unmergeablePrincipals(a, b)) { return; }
 
+  const combined = a.statement.copy({
+    actions: setMerge(a.statement.actions, b.statement.actions),
+    resources: setMerge(a.statement.resources, b.statement.resources),
+    principals: setMergePrincipals(a.statement.principals, b.statement.principals),
+  });
+
+  if (limitSize && combined._estimateSize() > MAX_MERGE_SIZE) { return undefined; }
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-iam/lib/private/merge-statements.ts:121]: I am a bit weary of relying on estimate sizes, but I don't see a better way here...

File: packages/@aws-cdk/aws-iam/lib/policy-statement.ts [hunk 7]
```diff
@@ -473,14 +469,98 @@ export class PolicyStatement {
...
+   *
+   * @internal
+   */
+  public _estimateSize(): number {
+    let ret = 0;
+
+    const actionEstimate = 20;
+    const arnEstimate = 120; // A safe (over)estimate on how long ARNs typically are
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-iam/lib/policy-statement.ts:542]: Per this doc: https://docs.aws.amazon.com/IAM/latest/APIReference/API_Policy.html

ARNs can be up to 2048 characters in length. The only way the estimate would be (dangerously) inaccurate is if the user imports an ARN, in which case they likely know the length of it themselves. Can we add an optional argument to ARN import methods, `arnLength?: number`, which we could use here? This way if users run into a deploy time issue they can specify the ARN length and `_estimateSize()` can correct for that here.

File: packages/@aws-cdk/aws-iam/lib/private/merge-statements.ts [hunk 8]
```diff
@@ -144,106 +150,56 @@ function makeComparable(s: StatementSchema): ComparableStatement {
...
+  return nonComp && comp;
 }
+
+function setMergePrincipals(xs: IPrincipal[], ys: IPrincipal[]): IPrincipal[] {
+  const xPrincipals = partitionPrincipals(xs);
+  const yPrincipals = partitionPrincipals(ys);
+
+  const comparable = { ...xPrincipals.comparable, ...yPrincipals.comparable };
+  return [...Object.values(comparable), ...xPrincipals.nonComparable, ...yPrincipals.nonComparable];
+}
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-iam/lib/private/merge-statements.ts:205]: missing EOF blank line.

File: packages/@aws-cdk/aws-iam/lib/private/postprocess-policy-document.ts [hunk 9]
```diff
@@ -147,3 +149,32 @@ function noUndef(x: any): any {
...
+
+  const intermediate = new Map<string, A>();
+  for (const x of xs) {
+    intermediate.set(JSON.stringify(x), x);
+  }
+
+  const sorted = Array.from(intermediate.keys()).sort().map(k => intermediate.get(k)!);
+  xs.splice(0, xs.length, ...sorted);
+  return xs.length !== 1 ? xs : xs[0];
+}
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-iam/lib/private/postprocess-policy-document.ts:180]: missing EOF blank line.

File: packages/@aws-cdk/aws-iam/lib/util.ts [hunk 10]
```diff
@@ -135,6 +138,6 @@ export class UniqueStringSet implements IResolvable, IPostProcessor {
   }
 }
 
-function isEmptyObject(x: { [key: string]: any }): boolean {
-  return Object.keys(x).length === 0;
-}
+export function sum(xs: number[]) {
+  return xs.reduce((a, b) => a + b, 0);
+}
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-iam/lib/util.ts:143]: missing EOF blank line.

**Review by comcalvi — DISMISSED** [review]
Nice work on this @rix0rrr! This PR is enormous, so this is a first pass, mainly style comments. My only concern with this PR is the estimation of ARN lengths. The estimates are *probably* safe but in the event a user does something we didn't forsee, they should have a way of specifying the ARN length.

File: packages/@aws-cdk/aws-iam/lib/policy-statement.ts (hunk 7 above)
Comment (Naumel) [inline packages/@aws-cdk/aws-iam/lib/policy-statement.ts:542]: https://docs.aws.amazon.com/IAM/latest/APIReference/API_Role.html mentions 2048 as the upper boundary.

Does the "typically" here imply computations based on average?

File: packages/@aws-cdk/aws-iam/lib/policy-document.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-iam/lib/policy-document.ts:5]: Oh aha, is this what you meant.

* `PolicyStatement` is a class
* `mergeStatements` is a function

That's why the capitalization is different

File: packages/@aws-cdk/aws-iam/lib/policy-statement.ts [hunk 11]
```diff
@@ -20,6 +21,22 @@ const ensureArrayOrUndefined = (field: any) => {
...
 };
 
+/**
+ * An estimate on how long ARNs typically are
+ *
+ * This is used to decide when to start splitting statements into new Managed Policies.
+ * Because we often can't know the length of an ARN (it may be a token and only
+ * available at deployment time) we'll have to estimate it.
+ *
+ * The estimate can be overridden by setting the `@aws-cdk/aws-iam.arnSizeEstimate` context key.
```
Comment (Naumel) [inline packages/@aws-cdk/aws-iam/lib/policy-statement.ts:31]: I like the option of a value that can be set.

File: packages/@aws-cdk/aws-iam/lib/policy-statement.ts (hunk 5 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-iam/lib/policy-statement.ts:551]: The size estimate is now configurable.

File: packages/@aws-cdk/aws-iam/lib/role.ts [hunk 12]
```diff
@@ -473,6 +496,55 @@ export class Role extends Resource implements IRole {
...
+  /**
+   * Split large inline policies into managed policies
+   *
+   * This gets around the 10k bytes limit on role policies.
+   */
+  private splitLargePolicy() {
+    if (!this.defaultPolicy || this._didSplit) {
+      return;
+    }
+    this._didSplit = true;
```
Comment (Naumel) [inline packages/@aws-cdk/aws-iam/lib/role.ts:509]: Am I understanding correctly that this is a marker for an (attempted) split? The `true` holds whether or not the split actually happens.

File: packages/@aws-cdk/pipelines/test/codepipeline/codepipeline.test.ts [hunk 13]
```diff
@@ -52,24 +53,91 @@ describe('CodePipeline support stack reuse', () => {
...
+      }
+
+      rolePolicies[roleLogicalId].push(pol.Properties.PolicyDocument);
+    }
+  }
+
+
+  // Validate sizes
+  //
+  // Not entirely accurate, because our "Ref"s and "Fn::GetAtt"s actually need to be evaluated
```
Comment (Naumel) [inline packages/@aws-cdk/pipelines/test/codepipeline/codepipeline.test.ts:118]: How likely is that with enough time (code changes) this test will start failing?

**Review by Naumel — APPROVED** [review]
The size approximation can be tweaked, the problem is complex and the solution addresses the main concerns.
