### PR TITLE
fix: CDK does not honor NO_PROXY settings

### LINKED ISSUE #7121: CDK ignores no_proxy config
It appears like CDK ignores the [`no_proxy` configuration](https://www.gnu.org/software/emacs/manual/html_node/url/Proxies.html).

I attempted to run CDK on an EC2 instance and I expect it to use the instance profile. I therefore added the flag `--ec2creds`.

The environment contains the vars `http_proxy` and `https_proxy` which points the the proxy of my organization. This proxy has an explicit black and whitelist. On the blacklist also are all AWS related endpoints and these cannot be queried though the proxy. Therefore the environment var `no_proxy` contains these, e.g. `...,169.254.169.254,169.254.170.2,...`

When `cdk --ec2creds -v deploy` now is executed it shows it correctly found the proxy var but makes no mention of the `no_proxy`. I also was not able to find this string anywhere in the codebase.

### Reproduction Steps

Quite a bit hard to fully reproduce. Set up an HTTP proxy which blocks 169.254.169.254 169.254.170.2 etc

Set http_proxy, https_proxy and no_proxy vars as described above on an EC2 instance.

Then run any cdk command with `--ec2creds`.

### Error Log

```text
Using proxy server: http://my.company.proxy:8080

...

Setting "CDK_DEFAULT_REGION" environment variable to eu-central-1
Resolving default credentials
Looking up default account ID from STS
Unable to determine the default AWS account (did you configure "aws configure"?): 403: Forbidden
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'Forbidden',
  code: 403,
  time: 2020-04-01T15:31:39.434Z,
  requestId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 96.63323741736052
}

...

Cannot retrieve value from context provider vpc-provider since account/region are not specified at the stack level. Either configure "env" with explicit account and region when you define your stack, or use the environment variables "CDK_DEFAULT_ACCOUNT" and "CDK_DEFAULT_REGION" to inherit environment information from the CLI (not recommended for production stacks)
```

### Environment

  - **CLI Version      : 1.31.0**
  - **Framework Version: 1.31.0**
  - **OS               : Amazon Linux 2**
  - **Language         : Typescript**

```
$ cdk doctor
ℹ️ CDK Version: 1.31.0 (build 8f3ac79)
ℹ️ AWS environment variables:
  - AWS_DEFAULT_REGION = eu-central-1
ℹ️ No CDK environment variables
```

### Other

No problem to run  `aws sts get-caller-identity`

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by RomainMuller**
CDK was extracting the value of `HTTPS?_PROXY` and passing this to
`proxy-agent` explicitly, which resulted in not honoring the `NO_PROXY`
setting.

This removes that behavior and lets `proxy-agent` delegate to
`proxy-from-env`, which will leverage values in `HTTPS?_PROXY` and
NO_PROXY correctly.

Fixes #7121

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by njlynch — APPROVED** [review]

File: packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/common.ts [hunk 1]
```diff
@@ -39,15 +39,13 @@ export abstract class ResourceHandler {
...
-      aws.config.update({
-        httpOptions: { agent: new ProxyAgent(proxyAddress) },
-      });
-    }
+    // Configure the proxy agent. By default, this will use HTTPS?_PROXY and
+    // NO_PROXY environment variables to determine which proxy to use for each
+    // request.
+    //
+    // eslint-disable-next-line @typescript-eslint/no-require-imports, import/no-extraneous-dependencies
+    const ProxyAgent: any = require('proxy-agent');
```
Comment (ryparker) [inline packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/common.ts:47]: I believe this change is causing EKS deployments to fail. CloudFormation now throws `Internal Failure.` when trying to create. 

This handler is used in the "onComplete" Lambda function which does not have the `proxy-agent` available. We only pass an `http_proxy` env var into the "onEvent" Lambda since that is the only Lambda that makes requests with the `aws-sdk-js`.

I tested this by moving the proxy logic to the `onEvent()` method and was able to successfully deploy again. I'll make a PR.

Comment (ryparker) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/common.ts:47]: I also noticed that `new ProxyAgent()` does not automatically detect `process.env.http_proxy` or `process.env.HTTP_PROXY`.

Comment (ryparker) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/common.ts:47]: Here's what ProxyAgent looks like when you log it in the Lambda:

Code:
```ts
const agent = new ProxyAgent()
console.log(`agent: ${JSON.stringify(agent, null, 2)}`);
```
Logs:
```log
2021-10-01T22:32:09.812Z	03de5aeb-e937-4b3d-91a3-aee2c524cb47	INFO	agent: {}
```

---

Code:
```ts
const agent = new ProxyAgent(process.env.http_agent);
console.log(`agent: ${JSON.stringify(agent, null, 2)}`);
```
Logs:
```log
2021-10-01T22:32:09.812Z	03de5aeb-e937-4b3d-91a3-aee2c524cb47	INFO	agent: {}
```

Comment (ryparker) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/common.ts:47]: Tested using https://github.com/ryparker/aws-cdk-sample-eks

Comment (RomainMuller) [reply packages/@aws-cdk/aws-eks/lib/cluster-resource-handler/common.ts:47]: It's normal and expected that the `ProxyAgent` instance does not look the same. If provided with a proxy, it will use ALWAYS and ONLY that proxy. When not specified, it will delegate to `proxy-from-env`, which will look at the correct proxy environment variable for the request' protocol & honor NO_PROXY.

I'd argue that the broken Lambda function should receive an `HTTPS_PROXY` and not `HTTP_PROXY`, as the AWS SDK typically makes only TSL connections... So it should be expected NOT to use `HTTP_PROXY` (using that value is incorrect there and should be considered a bug).
