### PR TITLE
fix(aws-cloudfront): Fix loggingConfig being ignored

### LINKED ISSUE #721: Logging property not present on creating a Cloudfront distribution using construct
I've tried passing in an empty object for log bucket as well as an S3 Bucket, but the template generated by cdk doesn't have the Logging property.
```
new cfront.CloudFrontWebDistribution(
            this.props.stack,
            'CFWebDistribution',
            {
                originConfigs: [
                    {
                        s3OriginSource: {
                            s3BucketSource: this.props.originBucket,
                            originAccessIdentity: this.props.originAccessIdentity
                        },
                        behaviors: [{ isDefaultBehavior: true }]
                    }
                ],
                loggingConfig: {}
            }
        );
```
```
new cfront.CloudFrontWebDistribution(
            this.props.stack,
            'CFWebDistribution',
            {
                originConfigs: [
                    {
                        s3OriginSource: {
                            s3BucketSource: this.props.originBucket,
                            originAccessIdentity: this.props.originAccessIdentity
                        },
                        behaviors: [{ isDefaultBehavior: true }]
                    }
                ],
                loggingConfig: {
                    bucket: this.props.logsBucket   
                }
            }
        );
```
I'm generating the template using cdk sdk (stack.toCloudformation()). This seems to be a bug.

### PR DESCRIPTION
**Pull request by ZeldoKavira**
feat(aws-s3): Add support for domainName on BucketRef instead of just Bucket

Fixes #721

Note: I know this goes against the policy of one fix/feature/ect per PR, but the s3 feature was required to complete this PR.

Reopened PR from #805 since I was being silly and overlooking the export() function

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts [hunk 1]
```diff
@@ -622,6 +633,14 @@ export class CloudFrontWebDistribution extends cdk.Construct {
       };
     }
 
+    if (props.loggingConfig) {
+      distributionConfig.logging = {
+        bucket: (props.loggingConfig.bucket || new s3.Bucket(parent, `${name}LoggingS3Bucket`)).domainName,
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts]: The `id` parameter can just be `"LogginBucket"`.

And please assign the resulting bucket (either the provided or generated one) to a public readonly member variable.

Comment (rix0rrr) [reply packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts]: Oh and does the bucket not need IAM permissions?

Comment (ZeldoKavira) [reply packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts]: Fixed the bucket name!

For the IAM:
Short: No
Long: CloudFront uses the root account it is attached to, that account needs permissions to change the ACL of the bucket. When a bucket is created inside an account it defaults to having these permissions. CloudFront uses that ACL permission to grant write perms to an internal amazon resource that collates the CloudFront logs into your one region.

**Comment by rix0rrr** [comment]
Huh! TIL

**Comment by ZeldoKavira** [comment]
Sorry about that @rix0rrr , updated the tests

**Comment by ZeldoKavira** [comment]
@rix0rrr Is it possible to get a release cut for all the CloudFront changes?

**Comment by rix0rrr** [comment]
Yes, but the process is a little involved and all of us are a little busy with other things at the moment. It might be next week before we get around to it.
