### PR TITLE
fix(iam): `conditions` parameters accept array values

### LINKED ISSUE #20974: (iam): principal conditions are not type-checked correctly
### Describe the bug

When adding a permission to a lambda function, there is an error since CDK 2.30.0.
Adding a PrincipalWithConditions supports less conditions than before.

### Expected Behavior

I expect, that synthing the project still works fine like in the prior version.

### Current Behavior

When synthing the following error appears:
```
Error: PrincipalWithConditions had unsupported conditions for Lambda permission statement: [{"operator":"0","key":"StringEquals"}]. Supported operator/condition pairs: [{"operator":"ArnLike","key":"aws:SourceArn"},{"operator":"StringEquals","key":"aws:SourceAccount"},{"operator":"StringEquals","key":"aws:PrincipalOrgID"}]
```

### Reproduction Steps

```typescript
secretRotationFunction.grantInvoke(new ServicePrincipal('secretsmanager.amazonaws.com', {
      conditions: [
        {
          StringEquals: {
            'aws:SourceAccount': Accounts.MAIN.account,
          }
        }
      ]
    }));
```

### Possible Solution

_No response_

### Additional Information/Context

I guess the responsible change is in `packages/@aws-cdk/aws-lambda/lib/function-base.ts` directly below line 596 / 643 in the diff: https://github.com/aws/aws-cdk/compare/v2.29.1...v2.30.0#diff-6cd0e14e946761622244e7c236ddb2c328b1881f050b1638897231ea27e5e62eR645.

### CDK CLI Version

2.30.0

### Framework Version

_No response_

### Node.js Version

18.2.0

### OS

OSX/CodeBuild

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by rix0rrr**
Because of the type declaration of `Conditions`, which was `{ [key: string]: any }`, and the way TypeScript interprets `any`, it was possible to pass arrays in where maps/objects were expected.

Change the type of `Condition` to `unknown`, which makes the type of `Conditions == { [key: string]: unknown }`. This makes TypeScript no longer accept arrays where objects were expected.

Would love loved to make the type of `Condition == { [key: string]: unknown }` as well to be even tighter, but apparently we rely on being able to pass `CfnJson` in where a condition goes, which is an object.

Closes #20974.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-iam/lib/policy-statement.ts [hunk 1]
```diff
@@ -664,19 +664,7 @@ export enum Effect {
...
-//
-// However, if we were to change this right now, the Java bindings for CDK would
-// emit a type of `Map<String, Object>`, but the most common types people would
-// instantiate would be an `ImmutableMap<String, String>` which would not be
-// assignable to `Map<String, Object>`. The types don't have a built-in notion
-// of co-contravariance, you have to indicate that on the type. So jsii would first
-// need to emit the type as `Map<String, ? extends Object>`.
-//
-// Feature request in https://github.com/aws/jsii/issues/1517
+export type Condition = Record<string, unknown>;
```
Comment (Naumel) [inline packages/@aws-cdk/aws-iam/lib/policy-statement.ts:667]: This has all my non-full-context alarms blaring: is this a victimless change of 1 line, no dependencies?

Comment (rix0rrr) [reply packages/@aws-cdk/aws-iam/lib/policy-statement.ts:667]: It should have been, but it doesn't work.

**Review by mrgrain — DISMISSED** [review]

**Review by mrgrain — APPROVED** [review]
Looking good now!
