### PR TITLE
fix(eks): add tag update support for eks cluster

### LINKED ISSUE #19388: (eks): EKS tags do not update if edited after initial deploy
### What is the problem?

When attempting to add tags to an already-deployed EKS cluster, tags never get added to resource. There is no issue when adding tags in the initial resource creation, so this can be worked around by either destroying and redeploying the stack, or by adding tags using the AWS SDKs.

This is likely related to the [fix](https://github.com/aws/aws-cdk/pull/18109) for the previously reported [issue](https://github.com/aws/aws-cdk/issues/4995).

### Reproduction Steps

1. Deploy below resource 
```typescript
const cluster = new eks.Cluster(this, 'eks3', {
    defaultCapacity: 0,
    version: eks.KubernetesVersion.V1_21,
    vpc,
    //tags: {
    //    "test": "123"
    //}
});
```

2. Remove comment of `tags` then redeploy

### What did you expect to happen?

Tags that were not created for first deployment should have been created in the update.

### What actually happened?

No tags were added to Cluster resource.

### CDK CLI Version

2.16.0

### Framework Version

2.16.0

### Node.js Version

16.9.1

### OS

OSX Sierra

### Language

Typescript

### Language Version

_No response_

### Other information

Best current workaround is to add tags via the [SDK `tagResource()`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EKS.html#tagResource-property) property, but this does not exist within the CDK, so is unideal.

_Reported internally in ticket P59680747_

### PR DESCRIPTION
**Pull request by mrlikl**
### Issue # (if applicable)

Closes #19388

### Reason for this change

Adding tag/untag for eks cluster post its creation

### Description of changes

Added API calls tagResource and untagResource in Cluster resource handler to handle tag changes

### Description of how you validated changes

Have tested the changes by first deploying a cluster with below config: 
```ts
const vpc = ec2.Vpc.fromLookup(stack, 'Vpc', { isDefault: true });
new eks.Cluster(stack, 'Cluster', {
  vpc,
  ...getClusterVersionConfig(stack, eks.KubernetesVersion.V1_29),
  defaultCapacity: 0,
 tags: {
    foo: 'bar',
  },
});
``` 
TestCase - 1 Update to add one more tag
```ts
new eks.Cluster(stack, 'Cluster', {
  vpc,
  ...getClusterVersionConfig(stack, eks.KubernetesVersion.V1_29),
  defaultCapacity: 0,
  tags: {
    foo: 'bar',
   hello: "world"
  },
});
```
Logs - 
```
{
    "updates": {
        "replaceName": false,
        "replaceVpc": false,
        "updateAccess": false,
        "replaceRole": false,
        "updateVersion": false,
        "updateEncryption": false,
        "updateLogging": false,
        "updateTags": true
    }
}
```

```
{
  clientName: 'EKSClient',
  commandName: 'TagResourceCommand',
  input: {
    resourceArn: 'arn:aws:eks:us-east-1:xxxxx:cluster/Cluster9EE0221C-f0d60e8e0bf14fb5896ade518b5bbc15',
    tags: { hello: 'world' }
  },
  output: {},
  metadata: {}
}
```

TestCase2 - Add, update and remove at the same time 
```ts
new eks.Cluster(stack, 'Cluster', {
  vpc,
  ...getClusterVersionConfig(stack, eks.KubernetesVersion.V1_29),
  defaultCapacity: 0,
  tags: {
    hello: 'world1',
    foobar: 'baz',
  },
  endpointAccess: eks.EndpointAccess.PUBLIC,
  vpcSubnets: [{ subnetType: ec2.SubnetType.PUBLIC }],
});
```

```
{
  clientName: 'EKSClient',
  commandName: 'TagResourceCommand',
  input: {
    resourceArn: 'arn:aws:eks:us-east-1:xxxxx:cluster/Cluster9EE0221C-f0d60e8e0bf14fb5896ade518b5bbc15',
    tags: { foobar: 'baz', hello: 'world1' }
  },
  output: {},
  metadata: {}
}
```

```
{
  clientName: 'EKSClient',
  commandName: 'UntagResourceCommand',
  input: {
    resourceArn: 'arn:aws:eks:us-east-1:xxxxx:cluster/Cluster9EE0221C-f0d60e8e0bf14fb5896ade518b5bbc15',
    tagKeys: [ 'foo' ]
  },
  output: {},
  metadata: {}
}
```

TestCase - 3 Remove all tags

```ts
new eks.Cluster(stack, 'Cluster', {
  vpc,
  ...getClusterVersionConfig(stack, eks.KubernetesVersion.V1_29),
  defaultCapacity: 0,
  endpointAccess: eks.EndpointAccess.PUBLIC,
  vpcSubnets: [{ subnetType: ec2.SubnetType.PUBLIC }],
});
```
```
{
  clientName: 'EKSClient',
  commandName: 'UntagResourceCommand',
  input: {
    resourceArn: 'arn:aws:eks:us-east-1:xxxxx:cluster/Cluster9EE0221C-f0d60e8e0bf14fb5896ade518b5bbc15',
    tagKeys: [ 'foobar', 'hello' ]
  },
  output: {},
  metadata: {}
```

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts [hunk 1]
```diff
@@ -338,9 +385,38 @@ function analyzeUpdate(oldProps: Partial<EKS.CreateClusterCommandInput>, newProp
...
 
 function setsEqual(first: Set<string>, second: Set<string>) {
   return first.size === second.size && [...first].every((e: string) => second.has(e));
 }
+
+function getTagsToUpdate<T extends Record<string, string>>(obj1: T, obj2: T): T {
+  const diff: T = {} as T;
+  // Get all tag keys that are newly added and keys whose value have changed
+  for (const key in obj2) {
+    if (obj2.hasOwnProperty(key)) {
```
Comment (shikha372) [inline packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts:400]: could you help in understanding what we are trying to validate here since we are iterating over tag key of obj2 or new props as I understand.
also instead of naming it obj1 or obj2 can we rename to something like oldTags and newTags since that's the only type of object we are expecting currently ?

File: packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts [hunk 2]
```diff
@@ -129,6 +129,52 @@ export class ClusterResourceHandler extends ResourceHandler {
...
+      try {
+        //Describe cluster to get arn and to make sure Cluster exists
+        const cluster = (await this.eks.describeCluster({ name: this.clusterName })).cluster;
+        if (this.oldProps.tags) {
+          if (this.newProps.tags) {
+            //Update tags
+            const tagsToAdd = getTagsToUpdate(this.oldProps.tags, this.newProps.tags);
+            if (tagsToAdd) {
+              const tagConfig: EKS.TagResourceCommandInput = {
+                resourceArn: cluster?.arn,
```
Comment (shikha372) [inline packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts:143]: can there be any case where this value be empty or does not exist in which case we should add additional check to make sure we got the cluster arn value ?

File: packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts [hunk 3]
```diff
@@ -129,6 +129,52 @@ export class ClusterResourceHandler extends ResourceHandler {
...
+            const tagsToRemove = getTagsToRemove(this.oldProps.tags, this.newProps.tags);
+            if (tagsToRemove.length > 0 ) {
+              const config: EKS.UntagResourceCommandInput = {
+                resourceArn: cluster?.arn,
+                tagKeys: tagsToRemove,
+              };
+              await this.eks.untagResource(config);
+            }
+          } else {
+            //Remove all tags
```
Comment (shikha372) [inline packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts:158]: why are we removing all the tags here?

**Review by shikha372 — COMMENTED** [review]
Hey @mrlikl , Thank you for your contribution, left some comments for your inputs.

File: packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts (hunk 1 above)
Comment (mrlikl) [reply packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts:400]: It is to check if there are new tags (tags with new keys) which are not present in the old props. 
For update, at this part, getting both the tags that are updated and newly added. 

```
old - 
{
  foo: "bar"
}
new - 
{
 foo: "bars"
 hello: "world"
}
```
with the above props, we have to send both the tag keys [foo, hello] in the tagresource API

I will change the names to oldTags and newTags

File: packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts (hunk 2 above)
Comment (mrlikl) [reply packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts:143]: The describe is already in the try block, hence if there is any exception or cluster does not exist, it will throw `ResourceNotFoundException`. Apart from that we should get the cluster ARN at all times.

File: packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts (hunk 3 above)
Comment (mrlikl) [reply packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts:158]: This is the else where `newtags` would be empty hence we have to remove all the `oldtags` from the cluster

Comment (shikha372) [reply packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts]: to make sure I understood correctly, newtags can be empty in case where customer doesn't want to introduce any change to the existing ones eg. looking at the condition here, in case tags under newProps come as empty would this remove all the existing ones ?
`updateTags: JSON.stringify(newProps.tags) !== JSON.stringify(oldProps.tags)`

File: packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts (hunk 1 above)
Comment (shikha372) [reply packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts]: Thank you, changing obj names would be helpful

File: packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts (hunk 3 above)
Comment (mrlikl) [reply packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts]: >newtags can be empty in case where customer doesn't want to introduce any change to the existing ones

In that case, `newTags` and `oldTags` would be same. `newTags` would be empty if customer wish to remove all tags from the cluster. 

`newTags` represent the desired state that we want the cluster tags to be in post the update. It will be the same as compared to `oldTags` if there has been no changes to tags done in CDK code.

File: packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts (hunk 1 above)
Comment (mrlikl) [reply packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts]: The names have been changed, along with more comments

**Comment by mrlikl** [comment]
@shikha372 I have made the proposed changes, please take a look

File: packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts (hunk 3 above)
Comment (shikha372) [reply packages/@aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts]: Got it, thank you for explaning

File: packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-tags.ts [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+  constructor(scope: App, id: string) {
+    super(scope, id);
+
+    // just need one nat gateway to simplify the test
+    const vpc = new ec2.Vpc(this, 'Vpc', { maxAzs: 2, natGateways: 1, restrictDefaultSecurityGroup: false });
+    new eks.Cluster(this, 'Cluster', {
+      vpc,
+      ...getClusterVersionConfig(this, eks.KubernetesVersion.V1_29),
+      defaultCapacity: 0,
+      tags: {
```
Comment (shikha372) [inline packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-tags.ts:19]: how are we verifying the tag update scenario here ?

**Comment by shikha372** [comment]
> @shikha372 I have made the proposed changes, please take a look

Thank you @mrlikl full coverage with unit tests now :)... wdyt about integ test , just last step of verification to confirm that API is working as expected

**Comment by mrlikl** [comment]
> Thank you @mrlikl full coverage with unit tests now :)... wdyt about integ test , just last step of verification to confirm that API is working as expected

The updates were manually tested I was unable to convert that flow to an integ test.

**Review by shikha372 — DISMISSED** [review]

**Comment by shikha372** [comment]
@mergifyio update

**Review by shikha372 — APPROVED** [review]
