### PR TITLE
fix(cloudfront): fix validation for unresolved webAclId tokens

### LINKED ISSUE #34099: (aws-cloudfront): WebACL validate throws error `webAclId.startsWith` is not a function
### Describe the bug

The error is introduced by the PR: https://github.com/aws/aws-cdk/pull/32252

When doing validation, it only consider the value is type of string, but it could also be `Token` if pass as reference .

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

CDK should build and deploy successfully.

### Current Behavior

CDK throws `webAclId.startsWith` is not a function error during build and deploy.

Image

### Reproduction Steps

1. Create a distribution with `webAclId` parameter.
2. Passing token type value to `webAclId`, for example:
```ts
cfn.getNestedStack("WafStack").includedTemplate.getOutput("WebAclArn").value
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.188

### Framework Version

_No response_

### Node.js Version

18.20.4

### OS

ubuntu

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by pahud**
### Issue # (if applicable)

Closes #34099.

### Reason for this change

Fixes a bug where CloudFront `Distribution` validation would throw a `TypeError` when `webAclId` was a CloudFormation token or intrinsic, instead of a plain string. This prevented users from passing unresolved tokens or references as `webAclId`.

### Description of changes

- Updated `validateWebAclId()` to **skip validation** if `webAclId` is **not a string** or is an **unresolved token**.
- This prevents `.startsWith()` from being called on non-string values, avoiding runtime errors.
- Added unit tests to cover unresolved tokens and non-string values.
- Removed the integration test that attempted to deploy dummy WebACL ARNs, which caused CloudFront deployment failures due to invalid account ownership.

This change enables users to safely pass CloudFormation references or tokens as `webAclId` without causing synthesis errors.

### Describe any new or updated permissions being added

None.

### Description of how you validated changes

- Added and updated unit tests for `validateWebAclId()` to cover tokens and non-string values.
- Removed the failing integration test that was not suitable for automated deployment.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts [hunk 1]
```diff
@@ -663,6 +663,10 @@ export class Distribution extends Resource implements IDistribution {
   }
 
   private validateWebAclId(webAclId: string) {
+    if (Token.isUnresolved(webAclId) || typeof webAclId !== 'string') {
```
Comment (shikha372) [inline packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts:666]: how is it possible to not have the webAclId as string when we have the type defined in function definition ?
`private validateWebAclId(webAclId: string)`

Comment (sampsonjoliver) [reply packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts:666]: In the case of our particular CDK app, we have
```ts
const cfn = new Cfn.CfnInclude(this, "BaseTemplate", { templateFile: "our/cfn.yaml" })

const webAclArn = cfn
  .getNestedStack("OurStack")
  .includedTemplate.getOutput("WebAclArn").value // .value has type `any`

const distribution = new Distribution({ defaultBehavior: { webAclId } , ...})
```

However, I feel this question is a more universal question around how [CDK Tokens](https://docs.aws.amazon.com/cdk/v2/guide/tokens.html) should be represented within CDK's type definitions?

The docs say that
> String-encoded tokens ... can be passed around like regular strings ...

and so many construct type definitions do not accept `string | Token` but rather just `string`. The caveat of course is that `Token`s are _not_ strings until after synthesis, and no string functions like `.startsWith` cannot be called on them.

Comment (pahud) [reply packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts:666]: @shikha372 

Yes this is tricky but without that, the `startsWith()` would throws an error. This is because of the nature of CDK Tokens and they are treated differently in compile time and runtime.

This is what I've observed from the source code. I am not sure if we have a better approach to validate that but this is my findings:

**Compile Time:** TypeScript allows both real strings and Tokens (typed as strings) to be passed to the function.
**Runtime:** The code first checks if the value is an unresolved Token.
**If Not Unresolved:** It then must check if the value is actually a string at runtime.
Why? Because a resolved token (like a CloudFormation intrinsic { Ref: ... }) is not an unresolved token, but it's also not a string (it's an object).
The `typeof value !== 'string'` check catches these resolved, non-string objects, preventing the code from crashing when it tries to call .startsWith() on them.

This runtime check is crucial for handling the difference between TypeScript's compile-time types and JavaScript's runtime reality, especially with CDK's token system.


```mermaid
graph TD
A["Function Call: validateWebAclId(value)"]
B{"TypeScript Type Check (Compile Time)"}
C["Passes Compile Check"]
D{"Runtime Execution"}
E{"Is value an unresolved Token?"}
F["Skip Validation (Token.isUnresolved)"]
G{"Is value actually a string?"}
H["Call .startsWith()"]
I["Value is NOT a string (e.g., resolved CFN object)"]
J["Calling .startsWith() would CRASH!"]
K["Check: typeof value !== 'string'"]
L["Skip Validation (Runtime Check)"]
M["Validation Logic"]
N["Validation Skipped Safely"]

A --> B
B -- "value: string" --> C
B -- "value: Token (typed as string)" --> C
C --> D
D --> E
E -- Yes --> F
E -- No --> G
G -- Yes --> H
G -- No --> I
I --> J
I --> K
K -- True --> L
H --> M
F --> N
L --> N
```

Comment (shikha372) [reply packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts:666]: Understood Thanks @pahud , so just validating `Token.isUnresolved(webAclId)` can still throw an error if don't skip this check for all other types except string.

**Comment by pahud** [comment]
Please don't merge for now. I'll share more info here to clarify why we need all those checks.

File: packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts (hunk 1 above)
Comment (pahud) [reply packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts]: Discussed offline. Agree to remove this check  as it's unlikely CDK users would resolve this token before passing to the prop. This aligns to our practice in other modules as well.

**Review by shikha372 — APPROVED** [review]
