### PR TITLE
fix(iam): policy statement tries to validate tokens

### LINKED ISSUE #13479: aws-iam: policy statements are trying to validate tokens
## :question: General Issue

Are IAM PolicyDocument Actions limited to string types?  I am trying to reference a cloudformation parameter as my action.

```ts
 new iam.PolicyStatement({
      actions: [
         core.Fn.join('',
          [ core.Fn.ref(Parameters.myparameter, ':*' )]
      ],
      effect: iam.Effect.ALLOW,
      resources: [ '*' ] 
    }
)
```

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):**

### PR DESCRIPTION
**Pull request by hollanddd**
Looking for guidance on error messaging and/or docs to update
Fixes #13479

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-iam/lib/policy-statement.ts [hunk 1]
```diff
@@ -64,6 +64,10 @@ export class PolicyStatement {
   constructor(props: PolicyStatementProps = {}) {
     // Validate actions
     for (const action of [...props.actions || [], ...props.notActions || []]) {
+      if (cdk.Token.isUnresolved(action)) {
+        throw new Error('Cannot add \'Action\' that contains an unresolved token');
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-iam/lib/policy-statement.ts:68]: I think what we want to do is only validate if we detect the value is NOT unresolved.

That way, we'll validate when we can and won't complain when we can't.

Add a test to check that we can pass in an unresolved value in a position we previously couldn't.

**Review by rix0rrr — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-iam/lib/policy-statement.ts (hunk 1 above)
Comment (hollanddd) [reply packages/@aws-cdk/aws-iam/lib/policy-statement.ts]: Thank you. I think I have addressed your feedback. As an aside I'm newish to major contributions and wasn't sure how to `git` the changes up with out forcing (with lease) and that makes me feel bad so.... Any tips in that area would be greatly appreciated.

Comment (rix0rrr) [reply packages/@aws-cdk/aws-iam/lib/policy-statement.ts]: :) yeah, I get that.

Here's the knowledge that will set you free: in our repository, you are allowed to not care about having a clean commit history on your PRs!

Because we will always squash-merge every PR into the main branch (collapsing it all into one commit, with the contents of the PR as the commit title & body), it doesn't actually matter whether your branch' commit history is clean or not. All that is going to go away anyway.

So I add commits named "oops" and "review" and "fix test" with wild abandon, and merge (without rebase!) from "master", and it's all good, **as long as** attention is paid to the PR body. 

Two additional notes:

* This happens to be true in our repository--might not be true in others, so I'm not sure how much this knowledge transfers to other projects (in case you're interested).
* In fact, for **GitHub** (not `git`) it's better to **never** force-push any branches, especially if they have review comments on them. It looks like GitHub remembers comments based on a combination of  something like *(commit hash, line number)*, and if the commit disappears because of force pushing, comments become orphaned and disappear from a thread.

File: packages/@aws-cdk/aws-iam/lib/policy-statement.ts [hunk 2]
```diff
@@ -64,8 +64,13 @@ export class PolicyStatement {
...
     for (const action of [...props.actions || [], ...props.notActions || []]) {
-      if (!/^(\*|[a-zA-Z0-9-]+:[a-zA-Z0-9*]+)$/.test(action)) {
-        throw new Error(`Action '${action}' is invalid. An action string consists of a service namespace, a colon, and the name of an action. Action names can include wildcards.`);
+
+      let subj = cdk.Token.isUnresolved(action)
+        ? cdk.Tokenization.resolve(action, { scope: this, resolver: new cdk.DefaultTokenResolver(new cdk.StringConcat()) })
+        : action;
+
+      if (!/^(\*|[a-zA-Z0-9-]+:[a-zA-Z0-9*]+)$/.test(subj)) {
+        throw new Error(`Action '${subj}' is invalid. An action string consists of a service namespace, a colon, and the name of an action. Action names can include wildcards.`);
```
[the remark this answers is not in the document]
Comment (rix0rrr) [reply packages/@aws-cdk/aws-iam/lib/policy-statement.ts:73]: We DO care! I like it when error messages tell me the value they saw (vs the value they were expecting). I find it makes it much easier in my head to reason about where that value is coming from.

**Review by rix0rrr — APPROVED** [review]
