### PR TITLE
fix(pipelines): prevent self-mutation on asset updates

### LINKED ISSUE #9080: [cdk-pipelines] Every asset update mutates the pipeline
The `UpdatePipepline` stage fails although the `SelfMutate` action has completed successfully and causes the pipeline to start over again. This leads to the pipeline getting caught in an infinite loop.

### Reproduction Steps

I have a CDK app with a `PipelineStack` containing a `CdkPipeline` (with two `Cdk.Stages`). I committed my CDK code to git, and then run `cdk deploy PipelineStack --profile ...` (all environments were bootstrapped before).

### Error Log

After creating the pipeline, the first pipeline execution is being triggered by a `CreatePipeline` event. `Source` and `Build` stage succeed, the `SelfMutate` action succeeds, but the `UpdatePipeline` stage fails. The next execution gets triggered by a `StartPipelineExecution` event (probably triggered by the pipeline itself?).

Screenshot 2020-07-15 at 14 43 38

I don't know where to find more detailed error messages of what causes the stage to fail. Please point me to the releavnt locations and I will provide more information.
### Environment

  - **CLI Version      : 1.51.0 (build 8c2d53c)**
  - **Framework Version: 1.51.0 (build 8c2d53c)**
  - **Node.js Version: v12.18.0** 
  - **OS               : aws/codebuild/standard:4.0**
  - **Language (Version): TypeScript (3.9.5)** 

### Other

Other users have reported the same issue on Gitter, but no resolution has been provided so far.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by njlynch**
Currently, changes to the asset hashes of content results in changes to the
definitions of the pipeline, causing the self-mutate state to trigger. This can
cause infinite loops for systems where build artifacts change on each build.

The cause for this looping is that the asset hash was embedded as the pipeline
action name. By replacing the asset hash with a simple asset counter (already
used for the action CloudFormation id), the pipeline definition should remain
stable on asset changes.

_Testing:_ Due to the pipeline executing the current version of CDK within the
pipeline, it's impossible to actual verify that this corrects the issue. To
test + verify, created a sample app where the asset hash changed on each build.
Then ran subsequent 'cdk synth' commands and diff'ed the output. Prior to this
change, there were numerous changes related to the asset hash in the pipeline
stack. After, only the buildspec of the CodeBuild project that referenced the
hash changed. This does not change the definition of the CodePipeline itself.

fixes #9080

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/pipelines/lib/pipeline.ts [hunk 1]
```diff
@@ -279,7 +279,7 @@ class AssetPublishing extends Construct {
       const id = command.assetType === AssetType.FILE ? `FileAsset${this._fileAssetCtr++}` : `DockerAsset${this._dockerAssetCtr++}`;
 
       action = this.publishers[command.assetId] = new PublishAssetsAction(this, id, {
-        actionName: command.assetId,
+        actionName: id,
```
Comment (eladb) [inline packages/@aws-cdk/pipelines/lib/pipeline.ts:282]: Add a comment explaining why we are using the ID for the action name

**Comment by asterikx** [comment]
Short question:

Imagine the case where a new asset is added to a CDK app and all other assets remained unchanged (same hash as before). This PR leads to all assets having to be published again (in the worst case), as assets might get assigned to a different publishing action as before. E.g. if the newly added asset gets assigned to publishing action No. 1 and the unchanged assets get "shifted" by one publishing action.

This might be a trade-off to accept though. Thanks for this PR @njlynch!

**Comment by eladb** [comment]
> Short question:
> 
> 
> 
> Imagine the case where a new asset is added to a CDK app and all other assets remained unchanged (same hash as before). This PR leads to all assets having to be published again (in the worst case), as assets might get assigned to a different publishing action as before. E.g. if the newly added asset gets assigned to publishing action No. 1 and the unchanged assets get "shifted" by one publishing action.
> 
> 
> 
> This might be a trade-off to accept though. Thanks for this PR @njlynch!

Since the asset hash of all other assets would not change, the publisher (`cdk-assets publish`) will succeed with no-op

**Comment by ldecaro** [comment]
Hi CDK team, I'm confused whether the fix is really working. 

  The comment from the @njlynch in the commit tab is exactly the use case I tested and I'm posting the two PipelineStacks from two subsequent runs. It seems this should not have generated a pipeline update. Would you kindly validate this?
  
  I'm adding these two stacks for validation in a zip file. A simple diff would be enough. In addition the image below shows  what I get from CloudFormation:
  
image (10)
 
[pipeline-changes.zip](https://github.com/aws/aws-cdk/files/8004734/pipeline-changes.zip)
