### PR TITLE
fix(cloudwatch): metric period in AnomalyDetectionAlarm is not being respected

### LINKED ISSUE #34614: cloudwatch: AnomalyDetectionAlarm metric period is not applied properly
### Describe the bug

It seems with 2.198.0 AnomalyDetectionAlarm was introduced. In the past we used the normal Alarm and adjusted then the CfnAlarm via escape hatches. So we tried to update to the AnomalyDetectionAlarm construct. Sadly we receive some warnings:
[Warning at /.../.../...] Periods of metrics in 'usingMetrics' for Math expression 'ANOMALY_DETECTION_BAND(m0, 2)' have been overridden to 300 seconds. [ack: CloudWatch:Math:MetricsPeriodsOverridden]

This happens although the userd Metric itself has the period of 60s defined. The only way to get rid of this was to set the period directly on the AnomalyDetectionAlarm. This method is deprecated though with the information to use the period of the used Metric.

What is the intended way to solve this issue?

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Library Version

_No response_

### Expected Behavior

The period of the metric is used for the math expression period

### Current Behavior

Currently the period of the metric is not used and the construct falls back to the default of 5m period.

### Reproduction Steps

Define a AnomalyDetectionAlarm as in the documentation:
```java
 // Create a metric
 Metric metric = Metric.Builder.create()
         .namespace("AWS/EC2")
         .metricName("CPUUtilization")
         .statistic("Average")
         .period(Duration.minutes(5))
         .build();
 // Create an anomaly detection alarm
 AnomalyDetectionAlarm alarm = AnomalyDetectionAlarm.Builder.create(this, "AnomalyAlarm")
         .metric(metric)
         .evaluationPeriods(1)
         // Number of standard deviations for the band (default: 2)
         .stdDevs(2)
         // Alarm outside on either side of the band, or just below or above it (default: outside)
         .comparisonOperator(ComparisonOperator.LESS_THAN_LOWER_OR_GREATER_THAN_UPPER_THRESHOLD)
         .alarmDescription("Alarm when metric is outside the expected band")
         .build();
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### AWS CDK Library version (aws-cdk-lib)

2.199.0

### AWS CDK CLI version

2.1017.1

### Node.js Version

22.x

### OS

Mac OSX

### Language

Java

### Language Version

21

### Other information

_No response_

### PR DESCRIPTION
**Pull request by vivekashok1221**
Fixes issue where anomaly detection band alarm's period defaulted to 300 seconds regardless of the metric's period. AnomalyDetectionAlarmProps didn't have a period property because it was deprecated in the parent interface and removed by jsii during compilation, causing the internal MathExpression to default to 300 seconds.

I am an Amazon employee (see commit email).

### Issue

Should fix #34614 (the issue was closed as duplicate but I'm not sure [the issue it was linked to](https://github.com/aws/aws-cdk/issues/32221) is actually the same issue)

### Reason for this change

Although I passed in the duration of 1 day as the `period` for the alarm metric, the actual period for the evaluation of the anomaly detection band is overridden to 5 minutes (300 seconds).
i.e, `cdk synth` shows this warning:
> [Warning at /TestCdkStack/TestAnomalyAlarm] Periods of metrics in 'usingMetrics' for Math expression 'ANOMALY_DETECTION_BAND(m0, 2)' have been overridden to 300 seconds. [ack: CloudWatch:Math:MetricsPeriodsOverridden]

And, on deployment, I can see on the CloudWatch alarm dashboard that the period is 5 minutes.

Example alarm:
```typescript
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { AnomalyDetectionAlarm, ComparisonOperator, Metric, Stats } from 'aws-cdk-lib/aws-cloudwatch';

export class TestCdkStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new AnomalyDetectionAlarm(this, 'TestAnomalyAlarm', {
      alarmName: 'TestAnomalyDetectionAlarm',
      metric: new Metric({
        namespace: 'TestNamespace',
        metricName: 'TestMetric',
        statistic: Stats.SUM,
        period: cdk.Duration.days(1), // This will get overriden
      }),
      // period: cdk.Duration.days(1),  I can't add period here since AnomalyDetectionAlarmProps doesn't have period prop
      stdDevs: 2,
      comparisonOperator: ComparisonOperator.GREATER_THAN_UPPER_THRESHOLD,
      evaluationPeriods: 1,
    });
  }
}
```

This happens because `AnomalyDetectionAlarm` creates an internal `MathExpression` for the anomaly detection band, and since `AnomalyDetectionAlarmProps` doesn't have a period property, no period gets passed to that math expression. The math expression then defaults to 300 seconds which overrides the period I've set on the metric used within it (math expression always [overrides](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudwatch.MathExpressionProps.html#period) the periods of the metrics passed into it)

I believe this is a bug in aws-cdk-lib where the metric's period isn't being respected by the Anomaly Detection Alarm.

If I try to include the `period` property in `AnomalyDetectionAlarmProps`, I get the error: `Object literal may only specify known properties, and 'period' does not exist in type 'AnomalyDetectionAlarmProps'` despite  `AnomalyDetectionAlarmProps` extending `CreateAlarmOptionsBase`, which has the `period` property.

This is because the `period` property has been marked as [deprecated](https://github.com/aws/aws-cdk/blob/6966c03b1a7aece0846f5a91bbeb825cd7491689/packages/aws-cdk-lib/aws-cloudwatch/lib/private/alarm-options.ts#L16-L18) so [`jsii` removed that property](https://github.com/aws/aws-cdk/blob/86638f6daca6ead382d0b9c1cf65bb04f70d4b3d/packages/aws-cdk-lib/package.json#L32) during compilation, which resulted in `AnomalyDetectionAlarmProps` not receiving this property from the parent interface.

### Possible Fixes
1. Add a `period` property to `AnomalyDetectionAlarmProps`
2. Have the AnomalyDetectionAlarm use the period set in the `metric` passed into it 

This PR implements approach 2 (see [discussion](https://github.com/aws/aws-cdk/pull/35319#discussion_r2407134489))

### Describe any new or updated permissions being added

N/A

### Description of how you validated changes

Added two new unit tests
Added an integration test
#### Steps I took for testing
(listing it here to catch if I missed anything/did something wrong)
- I made a `testCDK` package with the example alarm I've provided above.
- Made the change to `aws-cdk-lib` and ran `npx lerna run build --scope=aws-cdk-lib`
- Ran `../aws/link-all.sh` in `testCDK` directory.
- Also had to follow the second option mentioned [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#import-errors) since I faced the same issue.
- Ran `npx cdk synth` to make sure the generated file is correct.
- Also deployed to my aws account with `npx cdk deploy` and verified that the dashboard is displaying the correct duration.
- Ran `yarn test` in `aws-cdk/packages/aws-cdk-lib`
- Ran `npx lerna run build --scope=@aws-cdk-testing/framework-integ` followed by `yarn integ --update-on-failed`

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts [hunk 1]
```diff
@@ -60,6 +61,16 @@ export interface AnomalyDetectionAlarmProps extends CreateAlarmOptionsBase {
...
+
+  /**
+   * The period over which the anomaly detection band's statistics are applied.
+   * This period is passed into the underlying math expression.
+   *
+   * This period overrides the period set in the metric used.
+   *
+   * @default Duration.minutes(5)
+   */
+  readonly period?: cdk.Duration;
```
Comment (vivekashok1221) [inline packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts]: I'm not sure if it's a bad pattern to add a property to a child interface when the same property exists on the parent, especially when the parent property is marked as deprecated. Maybe I could rename this to `anomalyDetectionPeriod` or something similar.

File: packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts [hunk 2]
```diff
@@ -639,8 +650,9 @@ export class AnomalyDetectionAlarm extends Alarm {
   public static readonly PROPERTY_INJECTION_ID: string = 'aws-cdk-lib.aws-cloudwatch.AnomalyDetectionAlarm';
 
   constructor(scope: Construct, id: string, props: AnomalyDetectionAlarmProps) {
+    const { period, ...alarmProps } = props;
     super(scope, id, {
-      ...props,
+      ...alarmProps,
```
Comment (vivekashok1221) [inline packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts]: Without this, the `period` prop will get passed into `Alarm` constructor which led to me getting this error on deployment:
```
❌  TestCdkStack failed: ToolkitError: The stack named TestCdkStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Period should not be set if list of Metrics is set. (Service: CloudWatch, Status Code: 400, Request ID: <request id>) (SDK Attempt Count: 1)" (RequestToken: <request token>, HandlerErrorCode: GeneralServiceException) 
```
... which I believe is understandable since `period` has to be passed to the `MathExpresion` "metric", not the alarm itself.

File: packages/aws-cdk-lib/aws-cloudwatch/README.md [hunk 3]
```diff
@@ -479,14 +479,15 @@ const metric = new cloudwatch.Metric({
...
-  period: Duration.minutes(5),
 });
 
 // Create an anomaly detection alarm
 const alarm = new cloudwatch.AnomalyDetectionAlarm(this, 'AnomalyAlarm', {
   metric: metric,
   evaluationPeriods: 1,
 
+  // The period over which the anomaly detection band's statistics are applied (default: 5 minutes)
+  period: Duration.minutes(5),
```
Comment (Miles123K) [inline packages/aws-cdk-lib/aws-cloudwatch/README.md]: We shouldn't be passing in period here. Period is an attribute of metric. Most (all) other CloudWatch alarms use the metric period as monitoring period.

Comment (vivekashok1221) [reply packages/aws-cdk-lib/aws-cloudwatch/README.md]: Math expressions have their own period attribute which overrides the period attributes of the metrics passed into it (which makes sense since you can pass multiple metrics with different period attributes into it).

I felt this was a way to transparently pass this period into the math expression without changing existing behaviour. 

Maybe we can rename `period` here to `anomalyDetectionPeriod`.
Or I guess we could have the math expression pick up the monitoring period from the metric passed into it.

Comment (Miles123K) [reply packages/aws-cdk-lib/aws-cloudwatch/README.md]: One thing that confused me when I was trying to debug why the alarm wasn't picking up the period of my metric was that [AnomalyDetectionAlarmProps](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts#L34) through [CreateAlarmOptionsBase ](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-cloudwatch/lib/private/alarm-options.ts#L18) already had a `period` member, but it is marked as deprecated, and I can't even find it as an option in my version of cdk-lib for some reason. (I see you mentioned it [here](https://github.com/aws/aws-cdk/pull/35319/files/e29643b41fbb6ce8c82b15f1afdb54fbc52d4302#r2297366692) as well). If the base interface marks `period` as deprecated, we probably shouldn't reintroduce it. 

It does seem the easier (and better) way would be to [remove the period field from the MathExpression](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-cloudwatch/lib/metric.ts#L419). If we do that, we also won't need this [workaround](https://github.com/aws/aws-cdk/pull/35319/files/e29643b41fbb6ce8c82b15f1afdb54fbc52d4302#r2297373248).

File: packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts [hunk 4]
```diff
@@ -639,8 +650,9 @@ export class AnomalyDetectionAlarm extends Alarm {
...
       comparisonOperator: props.comparisonOperator ?? ComparisonOperator.LESS_THAN_LOWER_OR_GREATER_THAN_UPPER_THRESHOLD,
       metric: Metric.anomalyDetectionFor(props),
```
Comment (vishaalmehrishi) [inline packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts]: Hi @vivekashok1221 , I started working on fixing the bug before I saw this PR. The correct fix should be:

```suggestion
      metric: Metric.anomalyDetectionFor({
        ...props,
        // AnomalyDetectionAlarmProps.period is deprecated - the guidance recommends encoding the period in the metric itself
        period: metricPeriod(props.metric),
      }),
```

This uses the period provided in the metric object, which is in line with the guidance: https://github.com/aws/aws-cdk/blob/812ee49f3d1c0deda2ce7493a930b4d22656fbcd/packages/aws-cdk-lib/aws-cloudwatch/lib/private/alarm-options.ts#L16

File: packages/aws-cdk-lib/aws-cloudwatch/README.md (hunk 3 above)
Comment (vishaalmehrishi) [reply packages/aws-cdk-lib/aws-cloudwatch/README.md]: Hi folks, thank you for looking into this. I have proposed a fix here: https://github.com/aws/aws-cdk/pull/35319/files#r2394391941

Comment (vivekashok1221) [reply packages/aws-cdk-lib/aws-cloudwatch/README.md]: > One thing that confused me when I was trying to debug why the alarm wasn't picking up the period of my metric was that [AnomalyDetectionAlarmProps](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts#L34) through [CreateAlarmOptionsBase ](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-cloudwatch/lib/private/alarm-options.ts#L18) already had a `period` member, but it is marked as deprecated, and I can't even find it as an option in my version of cdk-lib for some reason. (I see you mentioned it [here](https://github.com/aws/aws-cdk/pull/35319/files/e29643b41fbb6ce8c82b15f1afdb54fbc52d4302#r2297366692) as well).

Hey @Miles123K 
I believe this is the case because, as I've mentioned in my PR description, [`jsii` removes deprecated properties](https://github.com/aws/aws-cdk/blob/86638f6daca6ead382d0b9c1cf65bb04f70d4b3d/packages/aws-cdk-lib/package.json#L32) during compilation

File: packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts (hunk 4 above)
Comment (vivekashok1221) [reply packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts]: Thanks, I'll try to implement your suggestion.

I wanted to confirm one thing: _correcting_ the anomaly detection alarm to use the metric's period will change the alarm duration for everyone who has specified a period in the metric object passed into the alarm- it will switch from the current 5 minute default (set by math expression [here](https://github.com/aws/aws-cdk/blob/3bd7cf944f2ec0b4b0191942682d19b954423536/packages/aws-cdk-lib/aws-cloudwatch/lib/metric.ts#L838)) to match their metric period (This was why I added an explicit way to specify duration in `AnomalyDetectionAlarm` construct in the first place). Is this approach acceptable?

(I agree this approach is correct. I initially expected the alarm to pick up the metric's period anyway. However, I do have some concerns about changing existing behaviour for current users.)

Comment (vishaalmehrishi) [reply packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts]: That is a good callout, thanks.

I understand the risk here; that said, there are two considerations which make me comfortable with fixing the bug directly instead of adding the extra period property:
1. While there may be customers who realised that the default was _incorrectly_ set to 5 minutes despite their configuration (i.e. the behaviour is a bug), there may also be customers who did not realise this (i.e they still think the alarm is configured with the correct period) - fixing the period to match the metric will automatically fix the bug for them.
2. The current (incorrect) default period of 5 minutes is not documented anywhere as intended behaviour (i.e. it is not a contract) - it is purely a result of buggy behaviour and requires users to actually read CDK code to find the MathExpression where it is set.

Also, ultimately we want the correct long-term solution in place. A user who might start with AnomalyDetection next week might be confused by the extra period property - the direct fix helps them (and all future users) to understand expected behaviour better.

Let me know what you think.

**Comment by vishaalmehrishi** [comment]
Let's update the commit + PR title to `fix(cloudwatch)...` so it appears as a fix in the release notes.

File: packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts (hunk 4 above)
Comment (vivekashok1221) [reply packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts]: SGTM 👍 , I'll do as you've suggested

**Comment by vivekashok1221** [comment]
Sure, I'll do that.
By the way, does this repo have any policy against rebasing my commits locally (to squash them/amend commit message) and force pushing my branch? 
Or shall I just make a new commit and request the person merging it to squash and merge?

**Comment by vishaalmehrishi** [comment]
> Sure, I'll do that. By the way, does this repo have any policy against rebasing my commits locally (to squash them/amend commit message) and force pushing my branch? Or shall I just make a new commit and request the person merging it to squash and merge?

There's no specific policy. However, you do not have to rebase locally - you can just make your commit and Mergify will take care of squashing and merging (assuming no conflicts of course).

File: packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts (hunk 4 above)
Comment (vivekashok1221) [reply packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts]: https://github.com/aws/aws-cdk/pull/35319/commits/8388ee033ee7ef923f8fa29f8021a445afa3b357

File: packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts [hunk 5]
```diff
@@ -642,7 +642,10 @@ export class AnomalyDetectionAlarm extends Alarm {
     super(scope, id, {
       ...props,
       comparisonOperator: props.comparisonOperator ?? ComparisonOperator.LESS_THAN_LOWER_OR_GREATER_THAN_UPPER_THRESHOLD,
-      metric: Metric.anomalyDetectionFor(props),
+      metric: Metric.anomalyDetectionFor({
+        ...props,
+        period: metricPeriod(props.metric),
```
Comment (vishaalmehrishi) [inline packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts]: I'd recommend adding this from my comment (https://github.com/aws/aws-cdk/pull/35319#discussion_r2394391941) as well. Might seem like overkill but it will save folks time searching for context in the future:

> // AnomalyDetectionAlarmProps.period is deprecated - the guidance recommends encoding the period in the metric itself

File: packages/aws-cdk-lib/aws-cloudwatch/test/alarm-anomaly-detection.test.ts [hunk 6]
```diff
@@ -80,8 +80,71 @@ describe('AnomalyDetectionAlarm', () => {
...
+        Metrics: Match.arrayWith([
+          Match.objectLike({
+            Expression: 'ANOMALY_DETECTION_BAND(m0, 2)',
+            Id: 'expr_1',
+            ReturnData: true,
+          }),
+          Match.objectLike({
+            Id: 'm0',
+            MetricStat: Match.objectLike({
+              Period: 300,
```
Comment (vishaalmehrishi) [inline packages/aws-cdk-lib/aws-cloudwatch/test/alarm-anomaly-detection.test.ts:140]: This is interesting. Given the alarm period should respect the metric period when provided, should it also do so when not provided?

If a user does not provide a period, then the default metric period will be 60s ([documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html#CloudWatchPeriods)), whereas the default anomaly detection alarm period will be 300s

Comment (vivekashok1221) [reply packages/aws-cdk-lib/aws-cloudwatch/test/alarm-anomaly-detection.test.ts:140]: According to AWS CDK docs, the default duration for metric class' period is 5 minutes: [docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudwatch.MetricProps.html#period), [code](https://github.com/aws/aws-cdk/blob/6966c03b1a7aece0846f5a91bbeb825cd7491689/packages/aws-cdk-lib/aws-cloudwatch/lib/metric.ts#L482)
If I had to assume, I'd guess that the doc you linked applies to creating metrics through AWS dashboard and the CDK team has decided to default to 5 minutes (probably) for cost/performance reasons.

Comment (vishaalmehrishi) [reply packages/aws-cdk-lib/aws-cloudwatch/test/alarm-anomaly-detection.test.ts:140]: Perfect - thank you for finding that detail.

File: packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts (hunk 5 above)
Comment (vivekashok1221) [reply packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts]: Done https://github.com/aws/aws-cdk/pull/35319/commits/422791908fce13194dc434e0f1a42de65b797366

**Review by vishaalmehrishi — DISMISSED** [review]

**Comment by vishaalmehrishi** [comment]
@vivekashok1221 Thank you so much for sticking with this and fixing the issue! Much appreciated.

Looking forward to getting this fix out to customers.

**Comment by vivekashok1221** [comment]
Forgot to run `yarn lint` for the integ tests 😅

**Comment by vivekashok1221** [comment]
I'm curious to know how your force push fixed the `cli-changes` job (`request-cli-integ-test`) (which I was assuming wasn't working because of my rebase + force-push)

**Comment by vishaalmehrishi** [comment]
> I'm curious to know how your force push fixed the `cli-changes` job (`request-cli-integ-test`) (which I was assuming wasn't working because of my rebase + force-push)

Maintainers have the option to update the branch. In this case I was seeing integ test failures which seemed related to the branching itself, so I rebased.

Screenshot 2025-10-09 at 09 43 12

**Comment by vivekashok1221** [comment]
@mergifyio requeue

**Comment by vivekashok1221** [comment]
I think the build job is failing in CI due to [an OOM error](https://github.com/aws/aws-cdk/actions/runs/18370204828/job/52331423195?pr=35319#step:9:4869). Rerunning the job by requeuing my PR might fix it.

**Comment by vishaalmehrishi** [comment]
Mergify was failing because the PR could not be updated. Rebase from the UI wasn't working either so pushed a merge commit - hopefully this will get it done
