### PR TITLE
fix: UserPool, Volume, ElasticSearch, FSx are now RETAIN by default

### LINKED ISSUE #12563: (many): a number of stateful resources don't have a removal policy
- [ ] AWS::CloudFormation::Stack
- [x] AWS::Cognito::UserPool
- [x] AWS::DocDB::DBInstance
- [x] AWS::EC2::Volume
- [x] AWS::Elasticsearch::Domain
- [x] AWS::FSx::FileSystem
- [x] AWS::SQS::Queue

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
(Gave this change an eye-catching title so it would stand out in the change log)

`cfn-lint` expects all stateful resources to have a removal policy, but we weren't providing that option at the L2 level yet, and the L1 API is cumbersome.

Add the `removalPolicy` option to the following resources:

* Cognito User Pools (default: RETAIN)
* EC2 Volume (default: RETAIN)
* ElasticSearch Domain (default: RETAIN)
* FSx FileSystem (default: RETAIN)
* SQS Queue (default: DESTROY)
* Nested Stack (default: DESTROY)

All L2 resources now have an `applyRemovalPolicy` method, so it can be set even for non-stateful resources.

A mechanism has been added to the codegen so that new L2 authors cannot forget about the `removalPolicy` when they're writing an L2.

I'm aware that the choice to make most of these RETAIN by default is going to be contentious. There are 2 questions here:

* Is RETAIN the correct default in general?
* Can we afford switching from implicit-DESTROY to implicit-RETAIN?

### Is RETAIN the correct default?

I would argue "yes", by process of elimination:

Defaulting `removalPolicy` for all resources to `DESTROY` if nothing is given (and writing `DESTROY` to the template) is just going to put us back to the situation in CloudFormation *before* `cfn-lint` existed (your stateful resources are going to be destroyed and nothing is going to warn you about it).

Making `removalPolicy` explicitly required for all stateful resources is a backwards-breaking change, and the point about CDK is that it will have sane defaults.

I can't come up with a better solution than picking RETAIN as default. 

### Can we afford changing the default here?

I'm sensitive to the arguments that this a breaking change which we can't afford. 

It feels like this is the value we would have given the resources had we thought about this earlier, and not being able to correct past mistakes by saying they are "locked in" is going to be a death knell for the project. 

We could go for a "future behavior" flag, but the risk here seems minimal: this is a change that REDUCES risk of data loss. It might increase risk of deployment errors (duplicate resource names), but that can be manually managed. I will fast-follow with a change that will introduce warnings for resources that have a physical name set and also a RETAIN policy, to clearly identify you're doing something dangerous in CloudFormation. I'm not sure it's worth the effort to go further than that.

Although please: discussion welcome.

Fixes #12563.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by PatMyron** [comment]
> but we weren't providing that option at the L2 level yet, and the L1 API is cumbersome

Is it possible to tackle this specifically? [I agree none of the options here are clearly better without downsides](https://github.com/aws/aws-cdk/issues/12563#issuecomment-774981078), but making it more obvious and less cumbersome to set `removalPolicy` when CDK hasn't set defaults seems strictly better

File: packages/@aws-cdk/aws-cognito/lib/user-pool.ts [hunk 1]
```diff
@@ -567,6 +567,13 @@ export interface UserPoolProps {
    * @default AccountRecovery.PHONE_WITHOUT_MFA_AND_EMAIL
    */
   readonly accountRecovery?: AccountRecovery;
+
+  /**
+   * Policy to apply when the user pool is removed from the stack
+   *
+   * @default - The user pool will be orphaned.
```
Comment (PatMyron) [inline packages/@aws-cdk/aws-cognito/lib/user-pool.ts:574]: assumed these `@default` comments themselves were setting defaults since I don't see the default being set anywhere else in `lib/`, so this one confuses me. Not sure how this gets `Cognito User Pools (default: RETAIN)` from the PR description, should it be something like this?

```suggestion
   * @default RemovalPolicy.RETAIN
```

**Comment by eladb** [comment]
@rix0rrr do we have some kind of enforcement/linting that future stateful resources also have a removal policy?

**Comment by eladb** [comment]
@rix0rrr also - see https://github.com/aws/aws-cdk-rfcs/issues/23 - perhaps would be useful to reference.

**Comment by rix0rrr** [comment]
> do we have some kind of enforcement/linting that future stateful resources also have a removal policy?

Not at the moment, because it's not clear where that information should live. I suppose in the doc comments of each L2 is as good a place as any... though I'm not quite sure how linting and static analysis is going to help us verify (for example) default behavior.

What we CAN do is say "if a resource has `@stateful`, then it MUST accept a `removalPolicy?: RemovalPolicy` as property." 

That's good as far as it goes, but just adding:

```ts
class Resource {
  public removalPolicy: RemovalPolicy;
}

**Comment by eladb** [comment]
> Not at the moment, because it's not clear where that information should live.

Where can we obtain a list of stateful resources? Does `cfn-lint` have that info somewhere?

> Also, what is the point of the stateful: boolean property you described in that RFC? Not sure how it would be used

The RFC issue is just a bunch of preliminary ideas. I wouldn't read too much into it. If I recall, the `stateful: boolean` is intended to allow runtime introspection. I.e.  "I want to traverse the tree and apply some policy to all stateful resources."

**Comment by rix0rrr** [comment]
> Where can we obtain a list of stateful resources? Does `cfn-lint` have that info somewhere?

It does. We aren't really set up for this yet, but we could potentially start extending our L1 model with information from external sources such as cfnlint.

The behavior I think would work is that we would mimic the same check cfn-lint would perform during validation: we can emit code for stateful L1s (as marked as such by cfn-lint) to require that they have a removal policy set.

That doesn't force anyhthing about HOW the removal policy is set, but you will encounter this while developing an L2 and the path of least resistance will be to just add that `removalPolicy` prop that all the other resources have.

**Comment by eladb** [comment]
@rix0rrr sounds like a step in the right direction!

**Comment by rix0rrr** [comment]
Shit, cfn-lint's copy of that list isn't machine-readable:

https://github.com/aws-cloudformation/cfn-python-lint/blob/d964639fd3fb679eeb615a90c85de187c1fd02ca/src/cfnlint/rules/resources/UpdateReplacePolicyDeletionPolicyOnStatefulResourceTypes.py#L22

**Comment by eladb** [comment]
> Shit, cfn-lint's copy of that list isn't machine-readable:

Maybe submit a PR to them which extracts this to a simple file that we can query.

File: packages/@aws-cdk/aws-rds/lib/cluster.ts [hunk 2]
```diff
@@ -310,7 +310,7 @@ abstract class DatabaseClusterNew extends DatabaseClusterBase {
       description: `Subnets for ${id} database`,
       vpc: props.instanceProps.vpc,
       vpcSubnets: props.instanceProps.vpcSubnets,
-      removalPolicy: props.removalPolicy === RemovalPolicy.RETAIN ? props.removalPolicy : undefined,
+      removalPolicy: props.removalPolicy,
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster.ts:313]: Why this change? A `SubnetGroup` is not a stateful resource I think? Or is it?

Also, pretty sure this doesn't work for `props.removalPolicy` equal to `SNAPSHOT`.

File: packages/@aws-cdk/aws-rds/lib/cluster.ts [hunk 3]
```diff
@@ -712,13 +712,12 @@ function createInstances(cluster: DatabaseClusterNew, props: DatabaseClusterBase
...
-    // Because of that, in this case,
-    // we can safely use the CFN default of Delete for DbInstances with dbClusterIdentifier set.
-    if (props.removalPolicy) {
-      applyRemovalPolicy(instance, props.removalPolicy);
-    }
+    // The RemovalPolicy on the cluster is SNAPSHOT by default, or explicitly configured.
+    // We can safely default to DESTROY for instances that are part of a cluster.
+    //
+    // TODO: This should probably be `DESTROY` always, no, instead of inheriting the
+    // cluster removal policy? It would lead to useless additional snapshots or retentions...
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster.ts:719]: Did you see the comment above, that you removed?

The default for `DbInstance`s is `SNAPSHOT` if `DBClusterIdentifier` is not set, but `DELETE` if `DBClusterIdentifier` is set (like it is here). So no, no useless additional snapshots will be generated. Maybe leave that comment in place?

Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html

File: packages/@aws-cdk/aws-rds/lib/instance.ts [hunk 4]
```diff
@@ -642,7 +642,7 @@ abstract class DatabaseInstanceNew extends DatabaseInstanceBase implements IData
       description: `Subnet group for ${this.node.id} database`,
       vpc: this.vpc,
       vpcSubnets: this.vpcPlacement,
-      removalPolicy: props.removalPolicy === RemovalPolicy.RETAIN ? props.removalPolicy : undefined,
+      removalPolicy: props.removalPolicy,
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/instance.ts:645]: Same question here (`SubnetGroup`).

File: packages/@aws-cdk/aws-rds/lib/private/util.ts [hunk 5]
```diff
@@ -78,8 +78,8 @@ export function engineDescription(engine: IEngine) {
 
 export function applyRemovalPolicy(cfnDatabase: CfnResource, removalPolicy?: RemovalPolicy): void {
   if (!removalPolicy) {
-    // the default DeletionPolicy is 'Snapshot', which is fine,
-    // but we should also make it 'Snapshot' for UpdateReplace policy
+    // Even though 'SNAPSHOT' is the default for RDS, make it explicit so cfnlint won't complain
+    cfnDatabase.cfnOptions.deletionPolicy = CfnDeletionPolicy.SNAPSHOT;
     cfnDatabase.cfnOptions.updateReplacePolicy = CfnDeletionPolicy.SNAPSHOT;
   } else {
     // just apply whatever removal policy the customer explicitly provided
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/private/util.ts:85]: Gotta say, I find this current function to be pretty confusing... Wouldn't something like this be equivalent?

```ts
export function applyRemovalPolicy(cfnDatabase: CfnResource, removalPolicy: RemovalPolicy = RemovalPolicy.SNAPSHOT): void {
  cfnDatabase.applyRemovalPolicy(removalPolicy);
}
```

? And if it is, maybe it's actually better to inline this function at the call sites at this point, since it's so simple?

**Review by skinny85 — DISMISSED** [review]
I only took a look at the RDS part, but I have some comments/questions to that part.

File: packages/@aws-cdk/aws-rds/lib/cluster.ts [hunk 6]
```diff
@@ -712,13 +712,12 @@ function createInstances(cluster: DatabaseClusterNew, props: DatabaseClusterBase
...
-    // it's Snapshot for Cluster.
-    // Because of that, in this case,
-    // we can safely use the CFN default of Delete for DbInstances with dbClusterIdentifier set.
-    if (props.removalPolicy) {
-      applyRemovalPolicy(instance, props.removalPolicy);
-    }
+    // The RemovalPolicy on the cluster is SNAPSHOT by default, or explicitly configured.
+    // We can safely default to DESTROY for instances that are part of a cluster.
+    //
+    // TODO: This should probably be `DESTROY` always, no, instead of inheriting the
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster.ts:718]: Definitely should not be `DESTROY` if the Cluster has `RETAIN`...

File: packages/@aws-cdk/aws-rds/lib/cluster.ts (hunk 3 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-rds/lib/cluster.ts:719]: Yes, but since we're making a `DBInstance` here as part of a `DBCluster`, the cluster identifier will always be set, right? So we fall into one branch of that statement, where the CFN default would be `DELETE` (and that's the same default we set).

However, what also happens now (because we reuse `props.removalPolicy`), is that if `SNAPSHOT` or `RETAIN` are set on the cluster, they are **also set on the DBInstance**. This is pointless -- if the cluster is already snapshotted or retained, we don't need to snapshot or retain the individual instances as well, do we?

File: packages/@aws-cdk/aws-rds/lib/private/util.ts (hunk 5 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-rds/lib/private/util.ts:85]: Yeah, true :)

File: packages/@aws-cdk/aws-rds/lib/cluster.ts (hunk 6 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-rds/lib/cluster.ts:718]: Maybe my understanding of how RDS works is incorrect then.

File: packages/@aws-cdk/aws-rds/lib/cluster.ts (hunk 2 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-rds/lib/cluster.ts:313]: > Why this change?

This change was just to simplify.

This used to only set a removalPolicy if the value was `RETAIN`, and not otherwise (so it would filter out `SNAPSHOT`, basically).

Kinda don't care for that behavior. I'd rather have CloudFormation yell at a user for choosing `SNAPSHOT` than for us to silently filter that out and implicitly defaulting to `DELETE`.

File: packages/@aws-cdk/aws-rds/lib/cluster.ts (hunk 3 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-rds/lib/cluster.ts:719]: We definitely need to `RETAIN` if Cluster is `RETAIN` (otherwise, the instances themselves will be deleted, even if if the Cluster is retained, making the Cluster useless).

Comment (skinny85) [reply packages/@aws-cdk/aws-rds/lib/cluster.ts:719]: If `props.removalPolicy` is `SNAPSHOT`, we can probably leave it as `DELETE` on the instance.

File: packages/@aws-cdk/aws-rds/lib/cluster.ts (hunk 2 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-rds/lib/cluster.ts:313]: I don't understand, sorry.

`SNAPSHOT` is a valid removal policy to set for the Cluster. But it's not a valid removal policy to set for `SubnetGroup`. So you're actually breaking a valid customer scenario with this change (that worked fine before).

File: packages/@aws-cdk/aws-rds/lib/cluster.ts (hunk 3 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-rds/lib/cluster.ts:719]: However, the unnecessary `SNAPSHOT` on the instance is the behavior today, so if you want to leave it as-is in this PR, I'm fine with it.

The `RETAIN` has to be changed though.

**Comment by NetaNir** [comment]
Curious, why didn't you add the call to `applyRemovalPolicy` on the `Resource` level? Similar to how what we do with Physical name?

**Comment by rix0rrr** [comment]
> Curious, why didn't you add the call to `applyRemovalPolicy` on the `Resource` level? Similar to how what we do with Physical name?

I think I did?

**Comment by NetaNir** [comment]
Let me explain, in the suggested implementation the removal policy is passed to the individual resource and then, on every resource the policy is applied. For example, in the `UserPool` resource:

```
userPool.applyRemovalPolicy(props.removalPolicy);
```   

My question (just a question!) is why not pass the removal policy via `super` and call `apply` in the Resource:

```
super(scope, id, {
      physicalName: props.name,
       removalPolicy: props.removalPolicy
    });
```

And then call `apply` in the Resource. Granted it will not save any code, but it could make it less likely to forget adding it when writing an L2.

**Comment by rix0rrr** [comment]
Ah, right.

Here's the thing: I don't actually *want* a `removalPolicy` in all `Props` types. It's going to clutter up the interface for *everything*, and if it really applies to *everything* there should be an out-of-band way for users to set it, so construct authors aren't left doing busywork. That way is `applyRemovalPolicy`.

Now, there is a subset of resources for which we actually DO want to set it, and those are stateful resources.

Because of the way we use cfn-lint's stateful resource database, we do detect when a stateful L1 is wrapped by an L2, and we throw an error saying that `removalPolicy` needs to be set--so you can't forget to think about this while authoring an L2.

File: packages/@aws-cdk/aws-rds/lib/cluster.ts (hunk 3 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-rds/lib/cluster.ts:719]: Yeah we have to look at this in aggregate.

Let me see if I understand correctly:

| If the Cluster policy is... | ...then the Instance policy has to be | Notes |
|----------|--------------|--------------|
| Delete | Delete | This one is easy |
| Snapshot | Delete | Right? |
| Retain | Retain | Right? |

Comment (rix0rrr) [reply packages/@aws-cdk/aws-rds/lib/cluster.ts]: Okay did that.

File: packages/@aws-cdk/aws-rds/lib/cluster.ts (hunk 2 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-rds/lib/cluster.ts:313]: This is still broken.

File: packages/@aws-cdk/aws-rds/lib/instance.ts (hunk 4 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-rds/lib/instance.ts:645]: This is still broken.

**Review by skinny85 — CHANGES_REQUESTED** [review]
Looks good minus the Cluster and Instance `SubnetGroup` changes that I commented on previously.

File: packages/@aws-cdk/aws-rds/test/cluster.test.ts [hunk 7]
```diff
@@ -1840,6 +1840,37 @@ nodeunitShim({
   },
 });
 
+test.each([
+  [cdk.RemovalPolicy.RETAIN, 'Retain', 'Retain'],
+  [cdk.RemovalPolicy.SNAPSHOT, 'Snapshot', 'Delete'],
+  [cdk.RemovalPolicy.DESTROY, 'Delete', 'Delete'],
+])('if Cluster RemovalPolicy is \'%s\', the DBCluster has DeletionPolicy \'%s\' and the DBInstance has \'%s\'', (removalPolicy, cluster, instance) => {
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/test/cluster.test.ts:1847]: Can we rename this variable to `clusterRemovalPolicy` instead?

**Comment by rix0rrr** [comment]
Ah yep, you are right. Completely glossed over the `DBSubnetGroup` changes.

I split the logic of the original ternary into 2 parts: first determine what the correct removal policy should be, and then decide whether or not to render it to the template (to minimize diffs).

I know it looks more complicated but I feel it factors out better this way.

**Review by skinny85 — APPROVED** [review]
I've only reviewed the RDS part. LGTM.

File: packages/@aws-cdk/cfnspec/build-tools/build.ts [hunk 8]
```diff
@@ -29,9 +40,53 @@ async function main() {
...
+
+  const files = await fs.readdir(inputDir);
+  for (const file of files.filter(n => n.endsWith('.json')).sort()) {
+    const data = await fs.readJson(path.join(inputDir, file));
+    if (file.indexOf('patch') === -1) {
+      // Copy properties from current object into structure, adding/overwriting whatever is found
+      Object.assign(structure, data);
+    } else {
+      // Apply the loaded file as a patch onto the current structure
+      patch(structure, data);
```
Comment (nija-at) [inline packages/@aws-cdk/cfnspec/build-tools/build.ts:85]: minor clarification - this the same patching mechanism as the cfn spec, yeah?

File: packages/@aws-cdk/cfnspec/build-tools/update-cfnlint.sh [hunk 9]
```diff
@@ -0,0 +1,18 @@
...
+scriptdir=$(cd $(dirname $0) && pwd)
+
+# Download (parts of) the cfn-lint repo that we use to enhance our model
+intermediate="$(mktemp -d)/tmp.zip"
+
+url="https://github.com/aws-cloudformation/cfn-python-lint/archive/master.zip"
+echo >&2 "Downloading from ${url}..."
+curl -sSfL "${url}" -o ${intermediate}
+
+for file in StatefulResources; do
```
Comment (nija-at) [inline packages/@aws-cdk/cfnspec/build-tools/update-cfnlint.sh:12]: minor: not familiar with this bash-ism: what is `StatefulResources`?

**Review by iliapolo — APPROVED** [review]
- [X] ElasticSearch
- [X] EKS

File: tools/cfn2ts/lib/codegen.ts [hunk 10]
```diff
@@ -385,6 +390,44 @@ export default class CodeGenerator {
...
+   * ```
+   * protected validate(): string[] {
+   *   const errors = new Array<string>();
+   *   // Validation here...
+   *   return errors;
+   * }
+   * ```
+   */
+  private emitConstructValidator(resourceType: genspec.CodeName) {
+    this.code.openBlock('protected validate(): string[]');
```
Comment (nija-at) [inline tools/cfn2ts/lib/codegen.ts:407]: Assume you're trying to use the validate API on constructs. This is going away with v2 - https://github.com/aws/aws-cdk-rfcs/blob/master/text/0192-remove-constructs-compat.md#08-validation-the-validate-hook-is-now-nodeaddvalidation

Use `addValidation()` instead.

**Review by nija-at — APPROVED** [review]
Please fix this - https://github.com/aws/aws-cdk/pull/12920#discussion_r578525128

Would also like to hear about the cfn-lint guarantee.

Otherwise looks good.

File: packages/@aws-cdk/aws-sqs/lib/queue.ts [hunk 11]
```diff
@@ -137,6 +137,18 @@ export interface QueueProps {
...
+   * Policy to apply when the user pool is removed from the stack
+   *
+   * Even though queues are technically stateful, their contents are transient and it
+   * is common to add and remove Queues while rearchitecting your application. The
+   * default is therefore `DESTROY`. Change it to `RETAIN` if the messages are so
+   * valuable that accidentally losing them would be unacceptable.
+   *
+   * @default RemovalPolicy.DESTROY
+   */
+  readonly removalPolicy?: RemovalPolicy;
```
[the remark this answers is not in the document]
Comment (rix0rrr) [reply packages/@aws-cdk/aws-sqs/lib/queue.ts:151]: It is not. I've chosen to make this the default.

File: packages/@aws-cdk/cfnspec/spec-source/cfn-lint/StatefulResources/000.json [hunk 12]
```diff
@@ -0,0 +1,30 @@
+{
+  "ResourceTypes": {
```
[the remark this answers is not in the document]
Comment (rix0rrr) [reply packages/@aws-cdk/cfnspec/spec-source/cfn-lint/StatefulResources/000.json:2]: Not really, but I don't see any way around that.

File: packages/@aws-cdk/cfnspec/build-tools/build.ts (hunk 8 above)
Comment (rix0rrr) [reply packages/@aws-cdk/cfnspec/build-tools/build.ts:85]: Yes.

File: packages/@aws-cdk/cfnspec/build-tools/update-cfnlint.sh (hunk 9 above)
Comment (rix0rrr) [reply packages/@aws-cdk/cfnspec/build-tools/update-cfnlint.sh:12]: A literal string :D

File: tools/cfn2ts/lib/codegen.ts (hunk 10 above)
Comment (rix0rrr) [reply tools/cfn2ts/lib/codegen.ts]:
```
@aws-cdk/core: [96mlib/cloudformation.generated.ts[0m:[93m883[0m:[93m23[0m - [91merror[0m[90m TS2339: [0mProperty 'addValidation' does not exist on type 'ConstructNode'.
```

Comment (nija-at) [reply tools/cfn2ts/lib/codegen.ts]: cc @eladb

Comment (nija-at) [reply tools/cfn2ts/lib/codegen.ts]: oh wait. Is this because this doesn't exist on `constructs` pre-10.x?

Comment (eladb) [reply tools/cfn2ts/lib/codegen.ts]: It does exist: https://github.com/aws/constructs/blob/117d3f1fee039eeac2d2aefa1b3e2d81530a63ff/src/construct.ts#L415
