### PR TITLE
fix(rds): fix incorrect import/export combination check in AuroraMysqlEngineVersion.of()

### LINKED ISSUE #33562: aws_rds: DatabaseCluster s3ExportBuckets fails with AuroraMysqlEngineVersion.of(...)
### Describe the bug

When using AuroraMysqlEngineVersion.of(...) instead of AuroraMysqlEngineVersion.VER_3_07_1, the s3ExportBuckets feature produces an incorrect CloudFormation configuration.

Specifically, the DBClusterParameterGroup gets an unexpected difference:
	•	AuroraMysqlEngineVersion.of(...) adds .aurora_select_into_s3_role
	•	AuroraMysqlEngineVersion.VER_3_07_1 adds .aws_default_s3_role

This affects the behavior of S3 export functionality and results in inconsistent CloudFormation stacks.

This issue appears related to [Issue #19735](https://github.com/aws/aws-cdk/issues/19735).

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

When specifying the engine version with AuroraMysqlEngineVersion.of(...), the s3ExportBuckets behavior should be the same as when using AuroraMysqlEngineVersion.VER_3_07_1.

Additionally, the DBClusterParameterGroup should have the same parameters, ensuring consistency.

### Current Behavior

Using AuroraMysqlEngineVersion.of("8.0.mysql_aurora.3.07.1", "8.0") results in the following incorrect CloudFormation diff:

```bash
Resources
[+] AWS::S3::Bucket sampleBucket sampleBucket14E4F90B
[~] AWS::RDS::DBClusterParameterGroup sampleParameterGroup sampleParameterGroup4231F25B
 └─ [~] Parameters
     └─ [+] Added: .aurora_select_into_s3_role  <-- INCORRECT
```

However, when using AuroraMysqlEngineVersion.VER_3_07_1, the expected behavior occurs:

```bash
Resources
[+] AWS::S3::Bucket sampleBucket sampleBucket14E4F90B
[~] AWS::RDS::DBClusterParameterGroup sampleParameterGroup sampleParameterGroup4231F25B
 └─ [~] Parameters
     └─ [+] Added: .aws_default_s3_role  <-- CORRECT
```
This discrepancy causes s3ExportBuckets to behave inconsistently.

### Reproduction Steps

The issue can be reproduced using the following CDK code:

**Incorrect behavior (AuroraMysqlEngineVersion.of(...))**
```typescript
new DatabaseCluster(this, 'sampleId', {
  engine: DatabaseClusterEngine.auroraMysql({
      version: AuroraMysqlEngineVersion.of("8.0.mysql_aurora.3.07.1", "8.0")
  }),
  iamAuthentication: true,
  parameterGroup,
  vpc: props.vpc,
  defaultDatabaseName: "sampleDatabase",
  writer: ClusterInstance.provisioned('writerInstance', {
      instanceType: InstanceType.of(InstanceClass.BURSTABLE3, InstanceSize.MEDIUM),
  }),
  s3ExportBuckets: [
      new Bucket(this, "sampleBucket", {
          bucketName,
          removalPolicy: RemovalPolicy.DESTROY,
      })
  ]
});
```

**Expected behavior (AuroraMysqlEngineVersion.VER_3_07_1)**
```typescript
new DatabaseCluster(this, 'sampleId', {
  engine: DatabaseClusterEngine.auroraMysql({
      version: AuroraMysqlEngineVersion.VER_3_07_1
  }),
  iamAuthentication: true,
  parameterGroup,
  vpc: props.vpc,
  defaultDatabaseName: "sampleDatabase",
  writer: ClusterInstance.provisioned('writerInstance', {
      instanceType: InstanceType.of(InstanceClass.BURSTABLE3, InstanceSize.MEDIUM),
  }),
  s3ExportBuckets: [
      new Bucket(this, "sampleBucket", {
          bucketName,
          removalPolicy: RemovalPolicy.DESTROY,
      })
  ]
});
```

### Possible Solution

In cluster-engine.ts, update the of method to ensure that _combineImportAndExportRoles is correctly set based on the major version.

Specifically, if the major version is not "5.7", _combineImportAndExportRoles should be set to true.

### Additional Information/Context

- This issue is problematic because AuroraMysqlEngineVersion.of(...) is required for emergency upgrades, but it currently leads to incorrect behavior in s3ExportBuckets and parameter groups.
- The behavior should be consistent regardless of how the engine version is specified.

### CDK CLI Version

v2.177.0

### Framework Version

_No response_

### Node.js Version

v22.3.0

### OS

macOS Sequoia 15.3

### Language

TypeScript

### Language Version

5.2.2

### Other information

_No response_

### PR DESCRIPTION
**Pull request by k1e1n04**
Previously, AuroraMysqlEngineVersion.of() incorrectly determined whether import and export roles should be combined.

This caused inconsistent behavior when specifying engine versions manually using AuroraMysqlEngineVersion.of(...), leading to incorrect parameter settings in the DBClusterParameterGroup.

### Issue #33562

Closes #33562

### Reason for this change

The issue arises when specifying a custom Aurora MySQL version using AuroraMysqlEngineVersion.of(...).
The logic for determining whether import and export roles should be combined is incorrect.
It should be based on the major version.

This bug causes s3ExportBuckets to configure DBClusterParameterGroup incorrectly:
- It adds .aurora_select_into_s3_role instead of .aws_default_s3_role
- This behavior differs from using built-in versions like AuroraMysqlEngineVersion.VER_3_07_1

### Description of changes

If the major version is not "5.7", _combineImportAndExportRoles is set to true

### Describe any new or updated permissions being added

None.

### Description of how you validated changes

- Ran unit tests to confirm that the changes work as expected

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts [hunk 1]
```diff
@@ -653,7 +653,7 @@ export class AuroraMysqlEngineVersion {
    *   defaults to "5.7"
    */
   public static of(auroraMysqlFullVersion: string, auroraMysqlMajorVersion?: string): AuroraMysqlEngineVersion {
-    return new AuroraMysqlEngineVersion(auroraMysqlFullVersion, auroraMysqlMajorVersion);
+    return new AuroraMysqlEngineVersion(auroraMysqlFullVersion, auroraMysqlMajorVersion, !!auroraMysqlMajorVersion && auroraMysqlMajorVersion !== '5.7');
```
Comment (shikha372) [inline packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts:656]: My concern is for the users using the current configuration for deployment, if we enforce this they'll see the unintended role change in their template: 
1. would like to confirm with the current behaviour whether the CFN deployment pass or not
2. If above statement is true and CFN deployment pass the current configuration, we need to fix this behind a feature flag

**Review by shikha372 — DISMISSED** [review]
Thanks @k1e1n04 for submitting this pull, before approval i would like to confirm the current behaviour in CFN so that it doesn't introduce any breaking changes for the users.

**Comment by k1e1n04** [comment]
@shikha372 Thanks for your comment.

I've run integration tests (such as `integ.cluster-s3.mysql-engine-version.js`) and confirmed that the current configuration can be deployed and deleted successfully with CloudFormation.

Regarding the feature flag implementation, would it be best if I handle that within this PR as well?

**Review by shikha372 — CHANGES_REQUESTED** [review]
Thank you @k1e1n04 for submitting this PR, please see the comment to confirm whether this change is backwards compatible

**Comment by shikha372** [comment]
> Regarding the feature f

yes the feature flag changes needs to be a part of this PR, from current configuration i meant to check the existing behaviour i.e. would you be able to deploy the CFN template without these PR changes, i believe yes CFN is still deployable though it is with the incorrect configuration, so best way to fix this without a breaking change is to enforce the right configuration behind a feature flag.

**Comment by k1e1n04** [comment]
@shikha372 
I misunderstood your point.
If we deploy with the previous configuration, the deployment will fail with the error:
Resource handler returned message: "Invalid / Unmodifiable / Unsupported DB Parameter: aurora_select_into_s3_role".

```shell
Failed resources:
SampleStack | 9:25:18 PM | CREATE_FAILED        | AWS::RDS::DBClusterParameterGroup           | sampleId/ClusterParameterGroup (sampleIdClusterParameterGroup2ED0FEB9) Resource handler returned message: "Invalid / Unmodifiable / Unsupported DB Parameter: aurora_select_into_s3_role" (RequestToken: 4451fbcf-e928-1e9b-a7d4-92ccbcc87c66, HandlerErrorCode: InvalidRequest)
```

Therefore, since this does not cause any breaking changes for users, I don’t think implementing a feature flag is necessary.

File: packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts [hunk 2]
```diff
@@ -657,7 +657,7 @@ export class AuroraMysqlEngineVersion {
...
```
Comment (shikha372) [inline packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts:660]:
```suggestion
    return new AuroraMysqlEngineVersion(auroraMysqlFullVersion, auroraMysqlMajorVersion, auroraMysqlMajorVersion ? auroraMysqlMajorVersion !== '5.7' : false);
```

Comment (shikha372) [reply packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts:660]: just making it more readable for the future, let me know if you've any concerns.

**Review by shikha372 — DISMISSED** [review]

**Review by shikha372 — APPROVED** [review]
