### PR TITLE
fix(ec2): instance not replaced when changing asset in UserData

### LINKED ISSUE #11704: (ec2): Asset based file hash is not in fingerprint included in ec2 user data
Hi,
i have a bug which is VERY related to https://github.com/aws/aws-cdk/issues/10206 but not the same.
While the first covers initFileOptions this one fails for `userData.addS3DownloadCommand`

Changing the file content of an Asset which is used in `userData.addS3DownloadCommand` does not change the userData Hash. Thus `userDataCausesReplacement: true` does not have an effect.

The root problem seeems to be that the Hash is calculated of the userData while Tokens are still included, not the resolved hashes.

### Reproduction Steps

```javascript
const asset = new Asset(this, 'UserDataAssets', {
      path: join(__dirname, 'configure.sh'),
})
const userData = ec2.UserData.forLinux()
const filePath = userData.addS3DownloadCommand({
      bucket: asset.bucket,
      bucketKey: asset.s3ObjectKey,
})
userData.addExecuteFileCommand({
      filePath,
      arguments: fileSystem.fileSystemId
})
const instance = new ec2.Instance(this, 'instance', {
      ...,
      userData,
      userDataCausesReplacement: true
})
```
1. Deploy
2. Change content of configure.sh
3. Redeploy

### What did you expect to happen?

A Replacement of the ec2 instance because the logical id changed.

### What actually happened?

No Replacement. Id did not change.
```
npm run cdk synth > /dev/null && cat ./cdk.out/ASPStack.template.json | grep AWS::EC2::Instance --before-context=1
    "instanceB7CCE68771905c98fce2b70f": {
      "Type": "AWS::EC2::Instance",
```

### Environment

  - **CDK CLI Version  :** 1.74
  - **Framework Version:**
  - **Node.js Version:** 14.15.0
  - **OS               :** Mac
  - **Language (Version):** Typescript 4.0

### Other

My current workaround:
```javascript
    userData.addCommands(`#${asset.assetHash}`)
```

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
The Logical ID hash used in Instance was based on the UserData string,
but it needed to be based on the *resolved* version of the UserData
string (since only the resolved version shows the asset hash).

Slight complication because the resolution of the UserData may refer
back to the LogicalID, which we need to account for by using a
recursion breaker.

Fixes #11704.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-ec2/lib/instance.ts [hunk 1]
```diff
@@ -384,16 +384,27 @@ export class Instance extends Resource implements IInstance {
...
+      produce: (context) => {
+        if (recursing) { return originalLogicalId; }
+        if (!(props.userDataCausesReplacement ?? props.initOptions)) { return originalLogicalId; }
+
+        const md5 = crypto.createHash('md5');
+        recursing = true;
+        try {
+          md5.update(JSON.stringify(context.resolve(this.userData.render())));
+        } finally {
+          recursing = false;
```
Comment (njlynch) [inline packages/@aws-cdk/aws-ec2/lib/instance.ts:404]: For my own edification, is this just paranoia, or is there a legitimate case where not resetting this would cause issues? Typically, any errors thrown are going to stop synthesis in its tracks, right? Is this guarding against a case of someone writing their own custom synthesizer, or is there something in the "native" CDK that merits this `finally`?

**Review by njlynch — APPROVED** [review]

File: packages/@aws-cdk/aws-ec2/lib/instance.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-ec2/lib/instance.ts:404]: I think it might just be paranoia :)
