### PR TITLE
fix(acm-certificatemanager): DnsValidatedCertificateHandler support for `SubjectAlternativeNames`

### LINKED ISSUE #4659: aws-certificatemanager DnsValidatedCertificateHandler does not properly handle certs with SubjectAlternativeNames
A DnsValidatedCertificate will never successfully validate when SubjectAlternativeNames are present. This seems to be due to the custom resource only adding the first DomainValidationOptions record to Route53. See [line 110](https://github.com/aws/aws-cdk/blob/c0c0513b68cc12e6696c57d2305bf84311ad9c59/packages/%40aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/lib/index.js#L110) here. This should add a new ResourceRecordSet for every DomainValidationOptions result.

### Reproduction Steps

Create a `DnsValidatedCertificate` and add at least one record to `subjectAlternativeNames`.

### Environment

  - **CLI Version      :** 1.14.0
  - **Framework Version:** 1.14.0
  - **OS               :** MacOS 10.14
  - **Language         :** Typescript

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by nlang**
First, sorry to create another PR for that issue. I did just find out that this issue already exists and has an open PR when I was about to share the fix I created for myself.

Here is a clean PR that only addresses the issue (#nohousekeeping) and also handles the case that a certificate exposes multiple `DomainValidationOptions` with the same `CNAME` record. That happens when you add subdomains of the main domain (e.g. `example.com` as domain and `*.example.com` in alt names). Of course I also added some tests ;)

And btw: Thank you for making CDK and your overall awsomeness!

### Commit Message

- [x] added support for certificates with `SubjectAlternativNames` by creating a Dns Record in Route53 for distinct entries in `DomainValidationOptions` (packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/lib/index.js)
- [x] added unittests

fixes #4659

### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/lib/index.js [hunk 1]
```diff
@@ -99,15 +99,24 @@ const requestCertificate = async function(requestId, domainName, subjectAlternat
...
+      // as the main domain (eg. example.com + *.example.com)
+      // filtering duplicates to avoid errors with adding the same record
+      // to the route53 zone twice
+      const unique = options
+        .map((val) => val.ResourceRecord)
+        .reduce((acc, cur) => {
+          acc[cur.Name] = cur;
+          return acc;
+        }, {});
+      records = Object.keys(unique).sort().map((key) => unique[key]);
```
Comment (skinny85) [inline packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/lib/index.js]: I believe the parens around `key` are not required, so this can be: `.map(key => unique[key])`.

**Comment by nlang** [comment]
Thank you @skinny85. I made the updates as requested. Build is still failing, but I'm not sure if that is still because of my changes?

File: packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/lib/index.js (hunk 1 above)
Comment (nlang) [reply packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/lib/index.js]: You are right, they are not _needed_. Omitting them is usually considered bad coding style though, but that's probably arguable and since it's your rules here I'm happy to change it ;)

**Comment by skinny85** [comment]
> Thank you @skinny85. I made the updates as requested. Build is still failing, but I'm not sure if that is still because of my changes?

Nope, still failing in `@aws-cdk/aws-ecs-patterns`:

```
@aws-cdk/aws-ecs-patterns: Verifying fargate/integ.load-balanced-fargate-service.js against fargate/integ.load-balanced-fargate-service.expected.json ... CHANGED.
@aws-cdk/aws-ecs-patterns: Parameters
@aws-cdk/aws-ecs-patterns: [-] Parameter AssetParameters01b2187f99280c53b7d58040d494b5d051e1e253601fc32dee62ba56712db247ArtifactHashFB4438F1: {"Type":"String","Description":"Artifact hash for asset \"01b2187f99280c53b7d58040d494b5d051e1e253601fc32dee62ba56712db247\""}
@aws-cdk/aws-ecs-patterns: [+] Parameter AssetParameters19e461d2ff1a5b90438fed6ceee4c197d7efee8712a6f76d85b501ab20bfb1a2ArtifactHash652C125C: {"Type":"String","Description":"Artifact hash for asset \"19e461d2ff1a5b90438fed6ceee4c197d7efee8712a6f76d85b501ab20bfb1a2\""}
@aws-cdk/aws-ecs-patterns: [~] Parameter AssetParameters19e461d2ff1a5b90438fed6ceee4c197d7efee8712a6f76d85b501ab20bfb1a2S3BucketFCCD3A76: {"Type":"String","Description":"S3 bucket for asset \"01b2187f99280c53b7d58040d494b5d051e1e253601fc32dee62ba56712db247\""} to {"Type":"String","Description":"S3 bucket for asset \"19e461d2ff1a5b90438fed6ceee4c197d7efee8712a6f76d85b501ab20bfb1a2\""}
@aws-cdk/aws-ecs-patterns: [~] Parameter AssetParameters19e461d2ff1a5b90438fed6ceee4c197d7efee8712a6f76d85b501ab20bfb1a2S3VersionKey07AF06B6: {"Type":"String","Description":"S3 key for asset version \"01b2187f99280c53b7d58040d494b5d051e1e253601fc32dee62ba56712db247\""} to {"Type":"String","Description":"S3 key for asset version \"19e461d2ff1a5b90438fed6ceee4c197d7efee8712a6f76d85b501ab20bfb1a2\""}
```

(BTW, you have access to the build log - it is posted as a comment on this PR once it finishes, for example [here's a comment for your last build](https://github.com/aws/aws-cdk/pull/7050#issuecomment-606893816)).

**Comment by nlang** [comment]
@skinny85 ok, so now the build went through :)
Thanks a bunch!
