### PR TITLE
fix(cloudtrail): Invalid resource for policy when using sendToCloudWatchLogs

### LINKED ISSUE #1848: Cloudtrail with sendToCloudWatchLogs: true, invalid Resource for Policy
Steps: Enable CloudTrail Construct in Typescript CDK version 0.24.1

sendToCloudWatchLogs: false,  : OK

sendToCloudWatchLogs: true, : Error in Resource name
Resource: undefined:log-stream:*

```
3/5 | 16:26:47 | CREATE_FAILED        | AWS::IAM::Policy         | CloudTrail/CloudTrail/LogsRole/DefaultPolicy (CloudTrailLogsRoleDefaultPolicyA8386E82) Partition "log-stream" is not valid for resource "arn:log-stream:*:*:*:*". (Service: AmazonIdentityManagement;
Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: 377ea60c-3840-11e9-a2a3-5910350b4863)
```

YAML for policy:
```yaml
CloudTrailLogsRoleDefaultPolicyA8386E82:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:PutLogEvents
              - logs:CreateLogStream
            Effect: Allow
            Resource: undefined:log-stream:*
        Version: "2012-10-17"
      PolicyName: CloudTrailLogsRoleDefaultPolicyA8386E82
      Roles:
        - Ref: CloudTrailLogsRole81106C20
    Metadata:
      aws:cdk:path: sdllaas-ivp-01admin-yg/CloudTrail/CloudTrail/LogsRole/DefaultPolicy/Resource
```

code:
```ts
const trail = new cloudtrail.CloudTrail(this, 'CloudTrail',{
                isMultiRegionTrail: false,
                trailName: 'Trail-' + this.stackName + '-' + this.region,
                sendToCloudWatchLogs: true,
                cloudWatchLogsRetentionTimeDays: LogRetention.OneYear
            });
```

YAML:
```yaml
Resources:
  CloudTrailS3857D5C80:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: sdllaas-ivp-01admin-yg/CloudTrail/CloudTrail/S3/Resource
  CloudTrailS3Policy4A413820:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: CloudTrailS3857D5C80
      PolicyDocument:
        Statement:
          - Action: s3:GetBucketAcl
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Resource:
              Fn::GetAtt:
                - CloudTrailS3857D5C80
                - Arn
          - Action: s3:PutObject
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - CloudTrailS3857D5C80
                      - Arn
                  - /AWSLogs/
                  - Ref: AWS::AccountId
                  - /*
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: sdllaas-ivp-01admin-yg/CloudTrail/CloudTrail/S3/Policy/Resource
  CloudTrailLogGroupDFE5546D:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 365
    Metadata:
      aws:cdk:path: sdllaas-ivp-01admin-yg/CloudTrail/CloudTrail/LogGroup
  CloudTrailLogsRole81106C20:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: sdllaas-ivp-01admin-yg/CloudTrail/CloudTrail/LogsRole/Resource
  CloudTrailLogsRoleDefaultPolicyA8386E82:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:PutLogEvents
              - logs:CreateLogStream
            Effect: Allow
            Resource: undefined:log-stream:*
        Version: "2012-10-17"
      PolicyName: CloudTrailLogsRoleDefaultPolicyA8386E82
      Roles:
        - Ref: CloudTrailLogsRole81106C20
    Metadata:
      aws:cdk:path: sdllaas-ivp-01admin-yg/CloudTrail/CloudTrail/LogsRole/DefaultPolicy/Resource
  CloudTrailF3F91E1B:
    Type: AWS::CloudTrail::Trail
    Properties:
      IsLogging: true
      S3BucketName:
        Ref: CloudTrailS3857D5C80
      CloudWatchLogsLogGroupArn:
        Fn::GetAtt:
          - CloudTrailLogGroupDFE5546D
          - Arn
      CloudWatchLogsRoleArn:
        Fn::GetAtt:
          - CloudTrailLogsRole81106C20
          - Arn
      EnableLogFileValidation: true
      EventSelectors: []
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: false
      TrailName:
        Fn::Join:
          - ""
          - - Trail-
            - Ref: AWS::StackName
            - "-"
            - Ref: AWS::Region
    DependsOn:
      - CloudTrailS3Policy4A413820
    Metadata:
      aws:cdk:path: sdllaas-ivp-01admin-yg/CloudTrail/CloudTrail/Resource
```

### PR DESCRIPTION
**Pull request by RomainMuller**
Sets `this.cloudWatchLogsGroupArn` before using it, such that a correct
resource ARN is used in the policy generated for CloudTrail to be able
to create and use the required log stream.

Fixes #1848

----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-cloudtrail/lib/index.ts [hunk 1]
```diff
@@ -149,14 +149,13 @@ export class CloudTrail extends cdk.Construct {
       });
       this.cloudWatchLogsGroupArn = logGroup.logGroupArn;
 
-      const logsRole = new iam.Role(this, 'LogsRole', {assumedBy: new iam.ServicePrincipal(cloudTrailPrincipal) });
+      const logsRole = new iam.Role(this, 'LogsRole', { assumedBy: new iam.ServicePrincipal(cloudTrailPrincipal) });
+      this.cloudWatchLogsRoleArn = logsRole.roleArn;
 
       const streamArn = `${this.cloudWatchLogsRoleArn}:log-stream:*`;
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-cloudtrail/lib/index.ts]: Wait why was this not a static analysis error?

File: packages/@aws-cdk/aws-cloudtrail/lib/index.ts [hunk 2]
```diff
@@ -149,14 +149,13 @@ export class CloudTrail extends cdk.Construct {
       });
       this.cloudWatchLogsGroupArn = logGroup.logGroupArn;
 
-      const logsRole = new iam.Role(this, 'LogsRole', {assumedBy: new iam.ServicePrincipal(cloudTrailPrincipal) });
+      const logsRole = new iam.Role(this, 'LogsRole', { assumedBy: new iam.ServicePrincipal(cloudTrailPrincipal) });
+      this.cloudWatchLogsRoleArn = logsRole.roleArn;
```
Comment (eladb) [inline packages/@aws-cdk/aws-cloudtrail/lib/index.ts]: Why is `cloudWatchLogsArn` optional?

File: packages/@aws-cdk/aws-cloudtrail/lib/index.ts (hunk 1 above)
Comment (RomainMuller) [reply packages/@aws-cdk/aws-cloudtrail/lib/index.ts]: The field is `string | undefined` (there is no value if you don't enable CloudWatch/Logs output) - and unassigned it is `undefined`, which is valid. Interpolating `undefined` is totally valid (and it'll output a literal `undefined`).

File: packages/@aws-cdk/aws-cloudtrail/lib/index.ts (hunk 2 above)
Comment (RomainMuller) [reply packages/@aws-cdk/aws-cloudtrail/lib/index.ts]: Because it is meaningless if you do not enable output in CloudWatch Logs.

**Comment by RomainMuller** [comment]
The real question in fact was why do we have private members that are only ever accessed from the constructor. I'm removing those and that'll make the code a lot safer.
