### PR TITLE
fix(cognito): imported userpool not retaining environment from arn

### LINKED ISSUE #13691: (aws-appsync): userPoolConfig authorizer ignores the userpool region
When adding an authorizer to the appSync, using the userPoolConfig, we can import the authorizer from the Arn, however the the CF will add the deployment region rather than the authorizer region for that particular instance.

### Reproduction Steps

```typescript
    const currentAuthorizer = cognito.UserPool.fromUserPoolArn(this, 'AuthInAnotherRegion', userPoolArn);
    const featuresApi = new appsync.GraphqlApi(this, 'GqlApi', {
      name: 'feature-control',
      schema: appsync.Schema.fromAsset('graphql/schema.graphql'),
      authorizationConfig: {
        defaultAuthorization: {
          authorizationType: appsync.AuthorizationType.USER_POOL,
          userPoolConfig: {
            userPool: currentAuthorizer,
          },
        },
    });
```

### What did you expect to happen?

```yaml
Resources:
  GqlApi4E487465:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      AuthenticationType: AMAZON_COGNITO_USER_POOLS
      Name: feature-control
      UserPoolConfig:
        AwsRegion: eu-west-2
        DefaultAction: ALLOW
        UserPoolId: eu-west-2_USERPOOLID
    Metadata:
      aws:cdk:path: FeaturesBackendFrankFurt/GqlApi/Resource
```

### What actually happened?

```yaml
Resources:
  GqlApi4E487465:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      AuthenticationType: AMAZON_COGNITO_USER_POOLS
      Name: feature-control
      UserPoolConfig:
        AwsRegion: eu-central-1
        DefaultAction: ALLOW
        UserPoolId: eu-west-2_USERPOOLID
    Metadata:
      aws:cdk:path: FeaturesBackendFrankFurt/GqlApi/Resource
```

### Environment

  - **CDK CLI Version  :** 1.94.1
  - **Framework Version:**
  - **Node.js Version:** 14.16.0
  - **OS               :** macOS Darwin
  - **Language (Version):** typescript

### Other

I have tried overwriting the env to see if that would be picked up as a workaround to no avail: 

```typescript
defaultAuthorization: {
          authorizationType: appsync.AuthorizationType.USER_POOL,
          userPoolConfig: {
            userPool: currentAuthorizer,
          },
        },
```

I expect the region to be picked up based on the retuned authorizer. As it most likely will include its own region (or picked up from the id as it is also included...)

--- 

This is :bug: Bug Report

Thanks!

### PR DESCRIPTION
**Pull request by DaWyz**
Importing a `UserPool` using `fromUserPoolArn()` method would not retain the account/region from the ARN and would instead use the environment from the scope it is imported to.

Closes #13691

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-cognito/lib/user-pool.ts [hunk 1]
```diff
@@ -1041,6 +1045,33 @@ export class UserPool extends UserPoolBase {
...
+   * The physical ID of this user pool resource
+   */
+  userPoolId: string;
+  /**
+   * The ARN of the user pool
+   */
+  userPoolArn: string
+}
+
+class ImportedUserPool extends UserPoolBase {
```
Comment (nija-at) [inline packages/@aws-cdk/aws-cognito/lib/user-pool.ts:1059]: Could you try and retain the original structure of keeping the 'Import' class local to the `fromXXX()` methods?

You should be able to move the full implementation to within `fromUserPoolArn()` and call this method from `fromUserPoolId()`. Something like -


```ts
public static fromUserPoolId(...) {
  return fromUserPoolArn(..., Stack.of(scope).formatArn(...));
}
```

File: packages/@aws-cdk/aws-cognito/lib/user-pool.ts [hunk 2]
```diff
@@ -660,22 +660,26 @@ export class UserPool extends UserPoolBase {
...
+    });
   }
 
   /**
    * Import an existing user pool based on its ARN.
    */
   public static fromUserPoolArn(scope: Construct, id: string, userPoolArn: string): IUserPool {
-    return UserPool.fromUserPoolId(scope, id, Stack.of(scope).parseArn(userPoolArn).resourceName!);
+    return new ImportedUserPool(scope, id, {
+      userPoolId: Stack.of(scope).parseArn(userPoolArn).resourceName!,
```
Comment (nija-at) [inline packages/@aws-cdk/aws-cognito/lib/user-pool.ts:680]: Avoid the `!`. 

Instead add a conditional that throws an error is `resourceName` is undefined.

**Review by nija-at — CHANGES_REQUESTED** [review]
@DaWyz - Thanks for submitting this PR. 

See my comments below.

File: packages/@aws-cdk/aws-cognito/lib/user-pool.ts (hunk 1 above)
Comment (DaWyz) [reply packages/@aws-cdk/aws-cognito/lib/user-pool.ts:1065]: @nija-at Are we sure we want to do this ?
I'm asking for the two following reasons:

- I've been asked in the past to extract the Import class (That was for EventBus) and it's done that way in a few other modules (search for `class Imported` in the codebase).
- I would need to find a different name for scope and id since I'm getting [eslint(@typescript-eslint/no-shadow)](https://github.com/typescript-eslint/typescript-eslint/blob/v4.16.1/packages/eslint-plugin/docs/rules/no-shadow.md) eslint error.

File: packages/@aws-cdk/aws-cognito/lib/user-pool.ts (hunk 2 above)
Comment (DaWyz) [reply packages/@aws-cdk/aws-cognito/lib/user-pool.ts]: Updated the code to check for resourceName + added a test.

File: packages/@aws-cdk/aws-cognito/lib/user-pool.ts (hunk 1 above)
Comment (nija-at) [reply packages/@aws-cdk/aws-cognito/lib/user-pool.ts:1065]: I prefer the class to be inline since this acts as an added check to ensure that we don't export this class into the public API. If we extracted this out, it would be easy to just add an 'export' keyword and could easily be missed in reviews. However if you feel strongly on extracting this, that's fine with me. 

However, I would either rename of not use the `UserPoolAttributes` interface. This is reserved for specific types of import APIs - https://github.com/aws/aws-cdk/blob/master/docs/DESIGN_GUIDELINES.md#from-attributes - and I wouldn't want this to be incorrectly used.

File: packages/@aws-cdk/aws-cognito/lib/user-pool.ts [hunk 3]
```diff
@@ -660,22 +660,32 @@ export class UserPool extends UserPoolBase {
...
 
   /**
    * Import an existing user pool based on its ARN.
    */
   public static fromUserPoolArn(scope: Construct, id: string, userPoolArn: string): IUserPool {
-    return UserPool.fromUserPoolId(scope, id, Stack.of(scope).parseArn(userPoolArn).resourceName!);
+    let userPoolId = Stack.of(scope).parseArn(userPoolArn).resourceName;
+
+    if (!userPoolId) {
+      throw new Error('UserPool.fromUserPoolArn requires an arn with a resourceName.');
```
Comment (nija-at) [inline packages/@aws-cdk/aws-cognito/lib/user-pool.ts:682]:
```suggestion
      throw new Error('invalid user pool ARN');
```

**Review by nija-at — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-cognito/lib/user-pool.ts (hunk 1 above)
Comment (DaWyz) [reply packages/@aws-cdk/aws-cognito/lib/user-pool.ts]: That makes sense. I'm moving the Imported class within the `fromUserPoolArn`. Thanks for the explanation @nija-at

File: packages/@aws-cdk/aws-cognito/lib/user-pool.ts [hunk 4]
```diff
@@ -660,22 +660,47 @@ export class UserPool extends UserPoolBase {
...
+
+        this.userPoolArn = attrs.userPoolArn;
+        this.userPoolId = attrs.userPoolId;
+      }
+    }
+
+    return new ImportedUserPool(scope, id, {
+      userPoolId: userPoolId,
+      userPoolArn: userPoolArn,
+    });
```
Comment (nija-at) [inline packages/@aws-cdk/aws-cognito/lib/user-pool.ts:703]: Is this simpler? Fewer lines of code to achieve the same thing and removes the need for `_scope` and `_id`.

```suggestion
    class ImportedUserPool extends UserPoolBase {
      public readonly userPoolArn = userPoolArn;
      public readonly userPoolId = userPoolId;
      constructor() {
        const arnParts = Stack.of(scope).parseArn(userPoolArn);
        super(scope, id, {
          account: arnParts.account,
          region: arnParts.region,
        });
      }
    }

    return new ImportedUserPool();
```

File: packages/@aws-cdk/aws-cognito/test/user-pool.test.ts [hunk 5]
```diff
@@ -211,17 +211,35 @@ describe('User Pool', () => {
...
+      env: {
+        account: '111111111111',
+        region: 'us-east-2',
+      },
     });
+
+    // WHEN
+    const pool = UserPool.fromUserPoolArn(stack, 'userpool', userPoolArn);
+    expect(pool.env.account).toEqual('0123456789012');
+    expect(pool.env.region).toEqual('us-east-1');
```
Comment (nija-at) [inline packages/@aws-cdk/aws-cognito/test/user-pool.test.ts:242]: Can you also verify the arn -

```suggestion
    expect(pool.env.region).toEqual('us-east-1');
    expect(pool.userPoolArn).toEqual('arn:aws:cognito-idp:us-east-1:0123456789012:userpool/test-user-pool');
```

**Review by nija-at — DISMISSED** [review]
Thanks for the change @DaWyz. A couple of small suggestions.

**Comment by DaWyz** [comment]
Updated the code following the comments !

**Review by nija-at — APPROVED** [review]
