### PR TITLE
fix(stepfunctions-tasks): policies created for EMR tasks have ARNs that are not partition-aware

### LINKED ISSUE #11503: [stepfunctions-tasks] Wrong ARN of emr iam policy getting attached in iam role
while trying to create step functions using CDK, We pass an iam-role to be used for step function execution. 
CDK by default is attaching some policies to the iam role.

In one of the policy statement of the default policy. The partition in the ARN seems to be hard coded to 'aws' which brings the problem that stack deployment fails when a given stack is deployed to any region other than classic. eg- in ZHY

The resultant json in template file which tells the Partition in resultant ARN is hard coded-
```
"Resource": {
                "Fn::Join": [
                  "",
                  [
                    "arn:aws:elasticmapreduce:",
                    {
                      "Ref": "AWS::Region"
                    },
                    ":",
                    {
                      "Ref": "AWS::AccountId"
                    },
                    ":cluster/*"
                  ]
```

### Reproduction Steps

potential bug location- 
```
arn:aws:elasticmapreduce:${Aws.REGION}:${Aws.ACCOUNT_ID}:cluster/*
```
The partition in ARN here is not getting picked dynamically.
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-cancel-step.ts#L39

### What did you expect to happen?
Ideally the partition should have been picked dynamically like- ${Aws.PARTITION} so that when stack is getting deployed in regions like ZHY, the arn will have the partition "aws-cn" and not "aws". 

### What actually happened?

the error logs- 
```
Partition "aws" is not valid for resource 
"arn:aws:elasticmapreduce:cn-north-1:<aws-account-id>:cluster/*". 
(Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; 
Request ID: <some-request-id>; Proxy: null)
```
The partition ideally should have been here "aws-cn".

### Environment

  - **CDK CLI Version  :** 1.45
  - **Node.js Version:**  12.x
  - **OS               :** Mac 
  - **Language (Version):**  TypeScript

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by shivlaks**
closes #11503

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by shivlaks** [comment]
whoops, meant to tag this as `needs-tests`. keeping it in draft until then.

File: packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-add-step.ts [hunk 1]
```diff
@@ -165,7 +165,7 @@ export class EmrAddStep extends sfn.TaskStateBase {
           'elasticmapreduce:DescribeStep',
           'elasticmapreduce:CancelSteps',
         ],
-        resources: [`arn:aws:elasticmapreduce:${Aws.REGION}:${Aws.ACCOUNT_ID}:cluster/*`],
+        resources: [`arn:${Aws.PARTITION}:elasticmapreduce:${Aws.REGION}:${Aws.ACCOUNT_ID}:cluster/*`],
```
Comment (nija-at) [inline packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-add-step.ts:168]: Use `Stack.formatArn()` API instead. This takes care of setting region, account and partition correctly.

**Review by nija-at — DISMISSED** [review]

File: packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-add-step.ts (hunk 1 above)
Comment (shivlaks) [reply packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-add-step.ts:168]: good call, will do

**Review by nija-at — APPROVED** [review]
