### PR TITLE
fix(event-targets): circular dependency when the lambda target is in a different stack

### LINKED ISSUE #10942: [lambda] Cannot avoid circular dependency when lambda and cloudwatch-events resources are in different stacks
From v1.68.0, it became impossible to avoid circular dependencies in certain cases.

The cases are for example:
* when lambda function and cloudwatch events which invoke the lambda function are defined in different stacks.

I assume this PR https://github.com/aws/aws-cdk/pull/10622 introduced this behavior, but not sure.

### Reproduction Steps

Define two stacks as below.
One is a stack which defines a lambda function.
Another is a stack which defines CloudWatch event to invoke the lambda repeatedly. 

```ts
import cdk = require('@aws-cdk/core');
import lambda = require('@aws-cdk/aws-lambda');
import events = require('@aws-cdk/aws-events');
import eventsTarget = require('@aws-cdk/aws-events-targets');

class LambdaStack extends cdk.Stack {
    readonly handler: lambda.IFunction;

    constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
        super(scope, id, props);
        const handler = new lambda.Function(this, 'handler', {
            runtime: lambda.Runtime.NODEJS_12_X,
            handler: 'main.handler',
            code: lambda.Code.fromInline('hoge'),
            
        });

        this.handler = handler;
        // Uncomment this line to avoid circular dependency. It worked before v1.68.0
        // this.handler = lambda.Function.fromFunctionArn(this, `handler-ref`, handler.functionArn);
    }
}

class CwStack extends cdk.Stack {
    constructor(scope: cdk.App, id: string, handler: lambda.IFunction, props?: cdk.StackProps) {
        super(scope, id, props);
        const target = new eventsTarget.LambdaFunction(handler);

        new events.Rule(this, `rule`, {
            schedule: events.Schedule.rate(cdk.Duration.minutes(10)),
            targets: [target],
        });
    }
}

const lambdaStack = new LambdaStack(app, 'LambdaStack');
new CwStack(app, 'CwStack', lambdaStack.handler);
```

And run `cdk synth`

### What did you expect to happen?
Before v1.68.0, the error below happens.

```
Error: 'LambdaStack' depends on 'CwStack' (LambdaStack -> CwStack/rule/Resource.Arn). 
Adding this dependency (CwStack -> LambdaStack/handler/Resource.Arn) would create a cyclic reference.
```

To avoid this error, as it was an only work-around I know, you can pass the reference of the lambda function retrieved by `fromFunctionArn`.
So uncommenting the line in the above code resolved this problem and `cdk synth` passes successfully.

### What actually happened?

From v1.68.0, unfortunately, the reference of the lambda also creates circular dependencies.
So whether we use the actual lambda function or the reference of it, the same error below happens.

```
Error: 'LambdaStack' depends on 'CwStack' (LambdaStack -> CwStack/rule/Resource.Arn). 
Adding this dependency (CwStack -> LambdaStack/handler/Resource.Arn) would create a cyclic reference.
```

There's no possible work-around I found so far.

### Environment

  - **CLI Version      :** v1.68.0
  - **Framework Version:** v1.68.0
  - **Node.js Version:**  v14.13.0
  - **OS               :** macOS
  - **Language (Version):**  TypeScript

### Other
This composition of stacks are commonly used in our production environment, because there're many cases that several stacks share the same lambda function.
Rather than defining a lambda function in several stacks duplicately, we'd like to define it in a single stack and referring to it from other stacks.

It'll be great if you provide us with a option which enables the previous behavior of lambda reference. (maybe specifying `canCreatePermissions` from outside?)
https://github.com/aws/aws-cdk/blob/2640d9aa06039a6eb539d959d2126749486c7ef3/packages/%40aws-cdk/aws-lambda/lib/function-base.ts#L211-L215

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by nija-at**
The Lambda Permission resource causes a cyclic dependency when the rule
is in a seprate stack from the lambda target for the rule.
(a picture is worth a thousand words)

```
     +-------------------+        +---------------+
     |Lamda Stack        |        |Event Stack    |
     |                   |        |               |
     |   +----------+    |        |    +------+   |
     |   |          |    |        |    |      |   |
     |   | Function |<-----------------+ Rule |   |
     |   |          |    |        |    |      |   |
     |   +----------+    |        |    +------+   |
     |        ^          |        |       ^       |
     |        |          |        |       |       |
     |  +-----+------+   |        |       |       |
     |  |            |   |        |       |       |
     |  | Permission +--------------------+       |
     |  |            |   |        |               |
     |  +------------+   |        |               |
     |                   |        |               |
     +-------------------+        +---------------+
```

The fix is to move the Permission resource into the event stack instead.

fixes #10942

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-events-targets/lib/util.ts [hunk 1]
```diff
@@ -27,9 +27,16 @@ export function singletonEventRole(scope: IConstruct, policyStatements: iam.Poli
  * Allows a Lambda function to be called from a rule
  */
 export function addLambdaPermission(rule: events.IRule, handler: lambda.IFunction): void {
+  let scope: Construct | undefined;
+  let node: ConstructNode = handler.permissionsNode;
+  if (rule instanceof Construct) {
```
Comment (njlynch) [inline packages/@aws-cdk/aws-events-targets/lib/util.ts:32]: Deserves a comment explaining what we're doing here; obvious in the context of this PR, but possibly less so 3-4 months down the line.

File: packages/@aws-cdk/aws-events-targets/test/lambda/lambda.test.ts [hunk 2]
```diff
@@ -100,7 +100,27 @@ test('adding same singleton lambda function as target mutiple times creates perm
...
+    runtime: lambda.Runtime.PYTHON_2_7,
+  });
+
+  const eventStack = new cdk.Stack(app, 'EventStack');
+  new events.Rule(eventStack, 'Rule', {
+    schedule: events.Schedule.rate(cdk.Duration.minutes(1)),
+    targets: [new targets.LambdaFunction(fn)],
+  });
+
+  expect(() => app.synth()).not.toThrow();
```
Comment (njlynch) [inline packages/@aws-cdk/aws-events-targets/test/lambda/lambda.test.ts:123]: Obviously, this is testing that there's not a circular dependency, and so we don't fail. A slightly stronger assertion would verify the Function, Rule, and Permission all landed in the right stack (much like the count resources above).

File: packages/@aws-cdk/aws-events-targets/test/lambda/lambda.test.ts [hunk 3]
```diff
@@ -100,7 +100,27 @@ test('adding same singleton lambda function as target mutiple times creates perm
   }));
 
   // THEN
-  expect(stack).to(countResources('AWS::Lambda::Permission', 1));
+  expect(stack).toCountResources('AWS::Lambda::Permission', 1);
+});
+
+test('lambda handler and cloudwatch event across stacks', () => {
```
Comment (njlynch) [inline packages/@aws-cdk/aws-events-targets/test/lambda/lambda.test.ts:106]: Should there also be a test for an imported Rule, as that changes the behavior?

Comment (nija-at) [reply packages/@aws-cdk/aws-events-targets/test/lambda/lambda.test.ts:106]: Why is this any different for imported Rule? An imported rule also follows the same logic.

Comment (njlynch) [reply packages/@aws-cdk/aws-events-targets/test/lambda/lambda.test.ts:106]: Because of the `if (rule instanceof Construct) {` check?

Comment (nija-at) [reply packages/@aws-cdk/aws-events-targets/test/lambda/lambda.test.ts:106]: Imported resources are also a `Construct`. They inherit `Resource` which is a subclass of `Construct`.

The `if` statement is needed because `IRule` and `Construct` don't overlap. But so far there is no case when the Rule will not be a `Construct`.

**Review by njlynch — APPROVED** [review]
