### PR TITLE
fix(core): `serviceTimeout` for `CustomResource` does not work with token

### LINKED ISSUE #33513: CustomResource: The `serviceTimeout` prop does not work with token
### Describe the bug

The `CustomResource` construct takes a `serviceTimeout` prop. The construct has some validation logic for the value if it isn't a token:
https://github.com/aws/aws-cdk/blob/bc96ee17a18c19b98e4ad052bed7c24da2371050/packages/aws-cdk-lib/core/lib/custom-resource.ts#L148

But I was not able to pass a token for `serviceTimeout`. I have the following unit test:
```
test('set serviceTimeout', () => {
    // GIVEN
    const stack = new Stack();
    const durToken = new CfnParameter(stack, 'MyParameter', {
      type: 'Number',
      default: 60,
    });

    // WHEN
    new CustomResource(stack, 'MyCustomResource', {
      serviceToken: 'MyServiceToken',
      serviceTimeout: durToken as any,
    });
  });
```

It fails with following error:
```
props.serviceTimeout?.toSeconds is not a function
TypeError: props.serviceTimeout?.toSeconds is not a function
```

I also tried the following test:
```
test('set serviceTimeout', () => {
    // GIVEN
    const stack = new Stack();
    const durToken = new CfnParameter(stack, 'MyParameter', {
      type: 'Number',
      default: 60,
    });

    // WHEN
    new CustomResource(stack, 'MyCustomResource', {
      serviceToken: 'MyServiceToken',
      serviceTimeout: Duration.seconds(durToken.valueAsNumber),
    });
  });
```

It fails with following error:
```
Error: serviceTimeout must either be between 1 and 3600 seconds, got -1.8881545897087526e+289
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

It should take a token as the value.

### Current Behavior

Using token would cause error. See above.

### Reproduction Steps

See above

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.179.0

### Framework Version

_No response_

### Node.js Version

20

### OS

Mac

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by go-to-k**
### Issue # (if applicable)

Closes #33513.

### Reason for this change

The `serviceTimeout` for `CustomResource` does not work with token.

The way the token is handled is wrong, and the `isUnresolved` method that the `Duration` type has should be used.

### Description of changes

Use the `props.serviceTimeout.isUnresolved()`.

Also add a doc that the token must be specified in `Duration.seconds()` since it is converted by `toSeconds` internally. (Because it is a token and unknown MINUTES value cannot be converted to SECONDS. This is due to the token mechanism.)

see:

https://github.com/go-to-k/aws-cdk/blob/75e52619cd09f363882ff62561a53cd5cd79ab30/packages/aws-cdk-lib/core/lib/custom-resource.ts#L169

https://github.com/go-to-k/aws-cdk/blob/75e52619cd09f363882ff62561a53cd5cd79ab30/packages/aws-cdk-lib/core/lib/duration.ts#L332

### Description of how you validated changes

Unit tests.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/core/lib/custom-resource.ts [hunk 1]
```diff
@@ -67,6 +67,18 @@ export interface CustomResourceProps {
    *
    * Maps to [ServiceTimeout](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-customresource.html#cfn-cloudformation-customresource-servicetimeout) property for the `AWS::CloudFormation::CustomResource` resource
    *
+   * A token can be specified for this property, but it must be specified with `Duration.seconds()`.
+   *
+   * @example
```
Comment (go-to-k) [inline packages/aws-cdk-lib/core/lib/custom-resource.ts:72]:
```suggestion
   * @example
   * const stack = new Stack();
```

**Comment by go-to-k** [comment]
@mergifyio update

**Review by GavinZZ — APPROVED** [review]

**Comment by go-to-k** [comment]
@Mergifyio update

**Comment by go-to-k** [comment]
@Mergifyio update

**Review by GavinZZ — APPROVED** [review]
