### PR TITLE
fix(region-info): ssm service principal is wrong in majority of regions

### LINKED ISSUE #16188: ssm: service principals are incorrect for all regions since `ap-east-1`
### The Issue

iam.ServicePrincipal (https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_iam/ServicePrincipal.html) offers a "region" parameter. Presumably this parameter is so you can say something like ssm.ap-us-east-1.amazonaws.com to be inclusive of regional-only service endpoints. 

Such as the ones called out on this page: https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-inventory-datasync.html#systems-manager-inventory-resource-data-sync-AWS-Organizations

> 
> "Note
> 
> The Asia Pacific Region came online in April 25, 2019. If you create a resource data sync for an AWS Region that came online since the Asia Pacific (Hong Kong) Region (ap-east-1) or later, then you must enter a Region-specific service principal entry in the SSMBucketDelivery section. The following example includes a Region-specific service principal entry for ssm.ap-east-1.amazonaws.com."

However

Here is a snippet of CDK Python that results in some odd behavior: 

```
        kmsKey = kms.Key(
            self,
            "S3-KMSKey",
        )

        kmsKey.add_to_resource_policy(
            statement=iam.PolicyStatement(
                sid="ssm-access-policy",
                conditions=[],
                effect=iam.Effect.ALLOW,
                actions=["kms:GenerateDataKey"],
                principals=[
                    iam.ServicePrincipal(service="ssm.amazonaws.com"),
                    iam.ServicePrincipal(
                        service="ssm.amazonaws.com", region="ap-east-1"
                    ),
                    iam.ServicePrincipal(service="ssm", region="ap-east-1"),
                ],
                resources=[kmsKey.key_arn],
            )
        )
```

That snippet uses ServicePrincipal three different ways, two of which should result in regional endpoints, and yet none of them do. 

That snippet spits out something that looks like... 

```
Resources:
  S3KMSKey26947010:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Statement:
          - Action: kms:*
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":iam::"
                    - Ref: AWS::AccountId
                    - :root
            Resource: "*"
          - Action: kms:GenerateDataKey
            Effect: Allow
            Principal:
              Service:
                - ssm.amazonaws.com
                - ssm.amazonaws.com
                - ssm.amazonaws.com
            Resource:
              Fn::GetAtt:
                - S3KMSKey26947010
                - Arn
            Sid: ssm-access-policy
        Version: "2012-10-17"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: SsmInventoryAthenaStack/S3-KMSKey/Resource
```
Notice that none of the Principal -> Service definitions have 'ap-east-1' in their URLs. 

This might be related to these two issues:
https://github.com/aws/aws-cdk/issues/2622
https://github.com/aws/aws-cdk/issues/2999

Where CDK was exclusively crafting regional endpoints

### Environment

  - **CDK CLI Version:**  2.0.0-rc.17 (build fb5dc58)
  - **Module Version:**  2.0.0rc17 (I think, pulled from python's Pipfile.lock for aws-cdk-libs)
  - **Node.js Version:**  v14.17.1
  - **OS:**  OSX
  - **Language:**  Python

### LINKED ISSUE #17646: @aws-cdk/aws-iam: ServicePrincipal generates an invalid principal in policy, MalformedPolicyDocument
### What is the problem?

While creating a role with a principal, the default region is used (the region from the stack) or a specified region. That generates a regional principal endpoint, which looks like is not the case for SSM and other services I suppose. That makes the CloudFormation process fail, stating that is an invalid IAM principal in the policy.

I'm open this in the @aws-cdk/aws-iam, where I found the issue, but maybe this is a CloudFormation or incompatibility?

### Reproduction Steps

```typescript
const lambdaRole = new iam.Role(this.scope, 'MyRole', {
  assumedBy: new iam.ServicePrincipal('ssm.amazonaws.com'),
  roleName: 'my-role',
});
```

Generated CloudFormation: 

```json
{
    "MyRoleA6F33B68": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": "sts:AssumeRole",
              "Effect": "Allow",
              "Principal": {
                "Service": {
                  "Fn::Join": [
                    "",
                    [
                      "ssm.",
                      {
                        "Ref": "AWS::Region"
                      },
                      ".amazonaws.com"
                    ]
                  ]
                }
              }
            }
          ],
          "Version": "2012-10-17"
        }
      }
    }
}
```

### What did you expect to happen?

Successful deployment with cdk deploy

### What actually happened?

```shell
cdk deploy
```
UPDATE_FAILED | Invalid principal in policy: "SERVICE":"ssm.eu-west-1.amazonaws.com" (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: 5763050d-c789-49ef-b7d7-9e80a62f0e9e; Proxy: null)
-- | --

### CDK CLI Version

1.133.0

### Framework Version

_No response_

### Node.js Version

v14.15.4

### OS

MacOs Monterey 12.0.1 (21A559)

### Language

Typescript

### Language Version

Typescript (4.5.2)

### Other information

There is a workaround for that:

```typescript
const lambdaRole = new iam.Role(this.scope, 'MyRole', {
      assumedBy: new iam.ServicePrincipal('ssm.amazonaws.com'),
      roleName: 'my-role',
    });
    const lambdaRoleAsCfn = lambdaRole.node.defaultChild as iam.CfnRole;
    // Workaround: Invalid principal in policy: "SERVICE":"ssm.eu-west-1.amazonaws.com" (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument;
    // eslint-disable-next-line max-len
    lambdaRoleAsCfn.addOverride('Properties.AssumeRolePolicyDocument.Statement.0.Principal.Service', 'ssm.amazonaws.com');
```

With this, the deployment works.

### PR DESCRIPTION
**Pull request by rix0rrr**
The SSM service principal format depends on the region. Older regions have a "global" service principal (`ssm.amazonaws.com`), while newer regions have only regional service principals (`ssm.ap-east-1.amazonaws.com`).

A number of things have been changed to address this:

* Add the notion of a "region order" into the `region-info` library. This allows us to express things like "does this region predate or postdate the change of some convention", and allows us to express that certain regions are *after* SSM introduced this change.
* For region-agnostic stacks, it is no longer possible to supply a single value for the template that will suffice in all regions, as the *format itself* will have changed (neither `"ssm.amazonaws.com"` nor `"ssm.$REGION.amazonaws.com"` will work in all regions). That means we must always introduce a lookup map for region-agnostic stacks. Add `stack.regionalFact()` to generate lookup maps from facts in case it is necessary.
  * Detect if all map values are just an instantiation of a token pattern, and return the simplification if possible (e.g.: if the lookup values are `service.us-east-1.amazonaws.com`, `service.us-east-2.amazonaws.com`, etc, then simplify to `service.$REGION.$URL_SUFFIX` and avoid emitting a lookup).   
  * Simplify existing usage sites of `RegionInfo.regionMap()` in Lambda and CodeBuild to use the new `stack.regionalFact()`.
* Because lookup maps would always include information for all regions, including GovCloud regions, and those are only rarely necessary: add the infrastructure for users to restrict what partitions they want to include information for, by means of a context flag. Defaults to all regions if not specified (so we don't break old templates), but for new projects restricts itself to `['aws', 'aws-cn']`. Set to just `['aws']` for integration tests so we don't break all of our snapshot tests.

Fixes #16188, fixes #17646.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-lambda/lib/lambda-insights.ts [hunk 1]
```diff
@@ -88,47 +85,5 @@ function getVersionArn(context: IResolveContext, insightsVersion: string): strin
...
-   * - us-east-2
-   * -- {'arn': 'arn2'}
-   * LambdaInsightsVersions10890 // a separate mapping version 1.0.89.0
-   * - us-east-1
-   * -- {'arn': 'arn3'},
-   * - us-east-2
-   * -- {'arn': 'arn4'}
-   */
-
-  const mapName = DEFAULT_MAPPING_PREFIX + insightsVersion.split('.').join('');
```
Comment (njlynch) [inline packages/@aws-cdk/aws-lambda/lib/lambda-insights.ts:121]: I'm not seeing where this was replicated/replaced. If I'm reading the above comment correctly, that means the new mappings won't actually deploy.

File: packages/@aws-cdk/core/lib/stack.ts [hunk 2]
```diff
@@ -803,6 +803,59 @@ export class Stack extends CoreConstruct implements ITaggable {
...
+  public regionalFact(factName: string, defaultValue?: string): string {
+    if (!Token.isUnresolved(this.region)) {
+      const ret = Fact.find(this.region, factName) ?? defaultValue;
+      if (ret === undefined) {
+        throw new Error(`region-info: don't know ${factName} for region ${this.region}. Use 'Fact.register' to provide this value.`);
+      }
+      return ret;
+    }
+
+    const regions = Node.of(this).tryGetContext(cxapi.TARGET_PARTITIONS);
```
Comment (njlynch) [inline packages/@aws-cdk/core/lib/stack.ts:834]:
```suggestion
    const partitions = Node.of(this).tryGetContext(cxapi.TARGET_PARTITIONS);
```

File: packages/@aws-cdk/cx-api/lib/features.ts [hunk 3]
```diff
@@ -161,7 +161,17 @@ export const LAMBDA_RECOGNIZE_VERSION_PROPS = '@aws-cdk/aws-lambda:recognizeVers
...
+ *
+ * Has no effect on stacks that have a defined region, but will limit the amount
+ * of unnecessary regions included in stacks without a known region.
+ *
+ * The type of this value should be a list of strings.
+ */
+export const TARGET_PARTITIONS = '@aws-cdk/core:target-partitions';
+
+/**
+ *  This map includes context keys and values for feature flags that enable
```
Comment (njlynch) [inline packages/@aws-cdk/cx-api/lib/features.ts:174]:
```suggestion
 * This map includes context keys and values for feature flags that enable
```

File: packages/@aws-cdk/region-info/lib/aws-entities.ts [hunk 4]
```diff
@@ -0,0 +1,147 @@
+// Rule prefix
+const RULE_ = 'RULE_';
+
+/**
+ * After this point, SSM only creates regional principals anymore
```
Comment (njlynch) [inline packages/@aws-cdk/region-info/lib/aws-entities.ts:5]:
```suggestion
 * After this point, SSM only creates regional principals
```

File: packages/@aws-cdk/region-info/lib/default.ts [hunk 5]
```diff
@@ -82,10 +89,9 @@ export class Default {
 
       // Services with a regional principal
       case 'states':
-      case 'ssm':
         return `${service}.${region}.amazonaws.com`;
 
-      // Services with a partitional principal
+      // Services with a partitional pricnipal
```
Comment (njlynch) [inline packages/@aws-cdk/region-info/lib/default.ts:94]:
```suggestion
      // Services with a partitional principal
```

**Review by njlynch — CHANGES_REQUESTED** [review]
Looks good, except it's not 100% clear the Lambda insights stuff is 1:1 compatible.

File: packages/@aws-cdk/aws-lambda/lib/lambda-insights.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-lambda/lib/lambda-insights.ts:121]: They will deploy, the mapping name will just be different.

Comment (njlynch) [reply packages/@aws-cdk/aws-lambda/lib/lambda-insights.ts:121]: Ah, ok. FWIW, I checked out this branch locally and ran the aws-lambda tests, and got several failures (looks related to the rename).

File: packages/@aws-cdk/aws-codebuild/lib/linux-gpu-build-image.ts [hunk 6]
```diff
@@ -109,37 +107,34 @@ export class LinuxGpuBuildImage implements IBindableBuildImage {
...
+  public readonly imageId: string;
 
-  private readonly accountExpression: string;
+  private _imageId?: string;
 
-  private constructor(private readonly repositoryName: string, tag: string, private readonly account: string | undefined) {
-    this.accountExpression = account ?? core.Fn.findInMap(mappingName, core.Aws.REGION, 'repositoryAccount');
-    this.imageId = `${this.accountExpression}.dkr.ecr.${core.Aws.REGION}.${core.Aws.URL_SUFFIX}/${repositoryName}:${tag}`;
+  private constructor(private readonly repositoryName: string, private readonly tag: string, private readonly account: string | undefined) {
+    this.imageId = core.Lazy.string({
```
Comment (njlynch) [inline packages/@aws-cdk/aws-codebuild/lib/linux-gpu-build-image.ts:116]: This is a potentially breaking change, no?

```ts
const myImage = codebuild.LinuxGpuBuildImage.DLC_TENSORFLOW_1_14_0;
createCBJob(myImage);

// ...
function createCBJob(myImage: codebuild.IBindableBuildImage) {
  const jobId = myImage.imageId.includes('pytorch-training') ? 'pytorchjob' : 'tensorflowjob';
  new codebuild.Project(this, jobId, { ... });
}
```

Obviously, a fabricated example, but can we really convert a string from a concrete to Lazy, tokenized value in a stable module and guarantee we won't break customers?

Comment (rix0rrr) [reply packages/@aws-cdk/aws-codebuild/lib/linux-gpu-build-image.ts:116]: **Sigh**. I suppose not, and it's a good catch. But based on those kinds of arguments I don't think we can't make any changes at all because anybody anywhere might have taken a dependency on anything.

I want to say how big is the chance people have actually done that... and I think not too big?

**Review by njlynch — APPROVED** [review]
