### PR TITLE
fix(codebuild): correctly handle permissions for Projects inside a VPC

### LINKED ISSUE #2651: CodeBuild: Associating an existing IAM role to a CodeBuild project results in exception
**Describe the bug**
Creating a new CodeBuild project and associating an existing IAM role results in: `Policy must be attached to at least one principal: user, group or role` during synthesis. My best guess is that the default policy generated by CDK is getting orphaned instead of disregarded in the case where an existing IAM role is specified?

**To Reproduce**
Using the following code to make the association:

```
val codeBuildProjectRole = Role.fromRoleArn(
            this,
            "code-build-project-role",
            "arn:aws:iam::1234567890:role/service-role/codebuild-bruiser-service-role"
        )

        val projectProps = ProjectProps.builder()
            .withEnvironment(buildEnvironment)
            .withProjectName(appName)
            .withSource(gitHubEnterpriseSource)
            .withBuildSpec("buildspec.yml")
            .withVpc(props.vpc)
            .withRole(codeBuildProjectRole)
            .withArtifacts(NoBuildArtifacts())
            .withSecondaryArtifacts(
                listOf(
                    s3BucketBuildArtifacts
                )
            )
            .build()

        val project = Project(this, "code-build-project", projectProps)
```

**Expected behavior**
Associating a valid existing role to a CodeBuild project should not result in exception.

**Version:**
 - Ubuntu 18.04
 - Kotlin using Java CDK artifacts
 - 0.32.0

### LINKED ISSUE #2652: CodeBuild: A project with default role results in `Not authorized to perform DescribeSecurityGroups`
**Describe the bug**
Creating a new CodeBuild project without defining a role, results in exception during deploy: "Not authorized to perform DescribeSecurityGroups (Service: AWSCodeBuild; Status Code: 400; Error Code: InvalidInputException".  

Looking at the generated CF template, it appears there are two IAM policy documents that are generated and reference the CodeBuild project role. One is the default policy with a name similar to `codebuildprojectRoleDefaultPolicy4FA15962` and another "CodeBuildEC2Policy" with a name similar to `codebuildprojectPolicyDocument1DCF3D9B`. Based on the exception it seems the "CodeBuildEC2Policy" is not recognized or perhaps a race condition?

After a brief search on the interwebs, I found this: https://stackoverflow.com/questions/52843460/receive-not-authorized-to-perform-describesecuritygroups-when-creating-new-pro which seems similar to the issue here.

**To Reproduce**
Using something like the following code will reproduce:
```
val projectProps = ProjectProps.builder()
            .withEnvironment(buildEnvironment)
            .withProjectName(appName)
            .withSource(gitHubEnterpriseSource)
            .withBuildSpec("buildspec.yml")
            .withVpc(props.vpc)
            .withArtifacts(NoBuildArtifacts())
            .withSecondaryArtifacts(
                listOf(
                    s3BucketBuildArtifacts
                )
            )
            .build()

        val project = Project(this, "code-build-project", projectProps)
```

**Expected behavior**
Using default role with CodeBuild project should not result in exception.

**Version:**
 - Ubuntu 18.04
 - Kotlin using Java CDK artifacts
 - 0.32.0

### PR DESCRIPTION
**Pull request by skinny85**
A CodeBuild Project needs to have appropriate EC2 permissions on creation
when it uses a VPC. However, the default Policy that a Project Role has
depends on the Project itself (for CloudWatch Logs permissions).
Because of that, add a dependency between the Policy containing the EC2
permissions and the Project.

Also correctly handle the case when the Project's Role is imported.

Fixes #2651
Fixes #2652

----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
  - __Design__: For significant features, design document added to `design` folder
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-codebuild/lib/project.ts [hunk 1]
```diff
@@ -891,22 +901,31 @@ export class Project extends ProjectBase {
...
-    return {
-      vpcId: props.vpc.vpcId,
-      subnets: props.vpc.selectSubnets(props.subnetSelection).subnetIds,
-      securityGroupIds: this._securityGroups.map(s => s.securityGroupId)
-    };
+  }
+
+  private addInlineEc2Policy(statement: iam.PolicyStatement) {
+    if (this.role) {
+      // If the Role is imported, the Policy will be left dangling,
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-codebuild/lib/project.ts]: I don't understand what this means. Doesn't this signal that there is an error in the imported Role class? If so, isn't that a better place to work around it then?

File: packages/@aws-cdk/aws-codebuild/lib/project.ts [hunk 2]
```diff
@@ -891,22 +901,31 @@ export class Project extends ProjectBase {
...
+          statements: [statement]
+        });
+        this.role.attachInlinePolicy(policy);
+
+        // add an explicit dependency between the EC2 Policy and this Project -
+        // otherwise, creating the Project fails,
+        // as it requires these permissions to be already attached to the Project's Role
+        const cfnPolicy = policy.node.findChild('Resource') as CfnResource;
+        const cfnProject = this.node.findChild('Resource') as CfnResource;
+        cfnProject.addDependsOn(cfnPolicy);
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-codebuild/lib/project.ts]: `this.addDependsOn(policy)` should also do this (and more). Any reason you can't use it?

**Comment by rix0rrr** [comment]
If we get an imported role to create a policy as usual (if the imported role is in the same account as the deployed stack!), we can also solve this at the same time: https://github.com/awslabs/aws-cdk/issues/2381

File: packages/@aws-cdk/aws-codebuild/lib/project.ts (hunk 2 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: The `Project` class doesn't have an `addDependsOn()` method.

File: packages/@aws-cdk/aws-codebuild/lib/project.ts (hunk 1 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: It's because of this code: https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-iam/lib/role.ts#L125

Comment (rix0rrr) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: Yes, but as far as I know that function could actually do the work it was intended to do. Am I wrong?

File: packages/@aws-cdk/aws-codebuild/lib/project.ts (hunk 2 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: Okay, I guess `cfnProject.addDependsOn(policy)` then.

But `this.node.findChild('Resource')` should never be necessary. We made that child, so we could also just keep a reference to it. So:

```
this.project.addDependsOn(policy);
```
?

File: packages/@aws-cdk/aws-codebuild/lib/project.ts (hunk 1 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: I don't know, actually. I assume there's some reason the method was left empty...?

In the issue you linked to, #2381 , I think @eladb is waiting for a comment from your side:

> 1. Since the role is external to the stack, the permissions are added to the queue policy instead of attached to the role. I am wondering why [this is the behavior](https://github.com/awslabs/aws-cdk/blob/56f544e9dea532c26c4224a30cd08a5b6cae7a66/packages/%40aws-cdk/aws-iam/lib/role.ts#L120) for imported roles. We can technically define an iam.Policy and attach it to the imported role. I've tested this approach and it works and seems more robust. @rix0rrr any insight on why we prefer to use a resource policy instead of an attached policy for imported roles?

Can you follow up in that other issue? Thanks!

File: packages/@aws-cdk/aws-codebuild/lib/project.ts (hunk 2 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: Heh, that's funny. I actually added a field for the L1 initially, but then I removed it because it was used in only this single place.

I'll add it back if you think that's better.

File: packages/@aws-cdk/aws-codebuild/lib/project.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: It's a bug in ImportedRole.

For one, it should not be returning `false`. For two, it might as well create the policy.

**Comment by cjyclaire** [comment]
+ 1 and thanks! :D

**Comment by skinny85** [comment]
Waiting for #2805 to land before resuming work on this.

File: packages/@aws-cdk/aws-codebuild/lib/project.ts (hunk 2 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: Done.

**Comment by skinny85** [comment]
#2805 has been merged, so I rebased this PR on top of it. @rix0rrr , please re-review. Thanks!

File: packages/@aws-cdk/aws-codebuild/lib/project.ts (hunk 1 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: Done.

**Comment by skinny85** [comment]
Rebased to resolve conflicts.

**Comment by skinny85** [comment]
@cjyclaire Merged :)
