### PR TITLE
fix(s3-deployment): list tokens in Source.jsonData are not resolved.

### LINKED ISSUE #35145: aws-s3-deployment v2.207: BucketDeployment broken for SSM StringListParameter source.
### Describe the bug

Previously, we worked around https://github.com/aws/aws-cdk/issues/22843 via SSM parameters, like:

stack 1:
```
const subnetIds = ourVpc.publicSubnets.map((subnet) => subnet.subnetId);
    new StringListParameter(this, `subnetIds-${props.env.account}-${props.env.region}`, {
      parameterName: subnetIdsParamName,
      stringListValue: subnetIds,
    });
```

stack 2:

```
    const subnetIdsParam = StringListParameter.fromStringListParameterName(
      this,
      `subnetIdsRead-${props.env.account}-${props.env.region}`,
      props.subnetIdsParamName,
    );
```

then. we'd reference `subnetIdsParam.stringListValue` in `Source.jsonData`.

However, as of version 2.207, this behavior is broken. While the SSM parameter is stored correctly, it is not resolved before the stack 2 template is deployed (token value is deployed in place of real value).

I believe this pattern may have been broken by https://github.com/aws/aws-cdk/issues/34916, which ironically solves the issue that prompted our use of the workaround.

Contact: tymcd@amazon.com

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### Last Known Working CDK Library Version

2.206.0

### Expected Behavior

SSM parameter resolved in stack 2 and stored in json object via BucketDeployment.

### Current Behavior

SSM parameter was not resolved (Token string deployed instead).

### Reproduction Steps

* Create SSM stringlist parameter as shown above (string parameter appears to work).

* Create source.jsondata in another stack from stringlist parameter as show above.

* Create a bucket deployment that uses this json data included in the `sources` list.

* Deploy the stacks. Observe the value deployed in the bucket.

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### AWS CDK Library version (aws-cdk-lib)

2.207.0

### AWS CDK CLI version

2.1023.0

### Node.js Version

18

### OS

MacOS

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Abogical**
### Issue #35145 

Closes #35145.

### Reason for this change

The recent fix to Source.jsonData did not work for list tokens such as SSM string list parameters. There was a mistake with the fix that assumed `stack.toJsonString` handled those, when in fact the tokens were serialized by `JSON.stringify`, breaking the token itself. `Token.isUnresolved` does not check all object properties for tokens, so it considered the object resolved and passed it to the regular JSON serializer.

### Description of changes

I've rewritten the JSON and YAML serializer such that it will use `stack.toJsonString` whenever it encounteres tokens in any of the object's children. One exception this is if the key in an object is a token, the token is assumed to be a string (because it has to in JSON) and is passed directly.

### Describe any new or updated permissions being added

N/A.

### Description of how you validated changes

- Unit and Integration tests added.
- Via manual inspection of stack in AWS Console, I checked that the JSON result was valid.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts [hunk 1]
```diff
@@ -262,5 +258,33 @@ export class Source {
...
+  private static escapeTokens(scope: Construct, obj: any): any {
+    if (Token.isUnresolved(obj)) {
+      // Return tokens as numbers. This is a hack to prevent the JSON serializer to wrap this token as a string.
+      // Stack.toJsonString should take care of escaping the object output for JSON.
+      return Token.asNumber(Stack.of(scope).toJsonString(obj));
+    }
+
+    if (Array.isArray(obj)) {
+      return obj.map(v => Source.escapeTokens(scope, v));
+    }
```
Comment (vishaalmehrishi) [inline packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts:276]: A better approach might be to have `escapeTokens` accept an array, and perform the operation for each. If there is a single object, then the array would contain a single object.

File: packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts [hunk 2]
```diff
@@ -262,5 +258,33 @@ export class Source {
...
 
+  /**
+   * Process objects such that it escapes token output suitable for JSON output.
+   *
+   * @param scope Parent construct scope
+   * @returns Object with with tokens escaped for JSON output.
+   */
+  private static escapeTokens(scope: Construct, obj: any): any {
+    if (Token.isUnresolved(obj)) {
+      // Return tokens as numbers. This is a hack to prevent the JSON serializer to wrap this token as a string.
```
Comment (vishaalmehrishi) [inline packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts:269]: Is there a better approach which removes the need for the hack entirely?

File: packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts [hunk 3]
```diff
@@ -262,5 +258,33 @@ export class Source {
...
+      // Stack.toJsonString should take care of escaping the object output for JSON.
+      return Token.asNumber(Stack.of(scope).toJsonString(obj));
```
Comment (vishaalmehrishi) [inline packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts:271]: Would be great to see what the string and number representations of the token look like. Maybe add a comment with an example

**Review by vishaalmehrishi — CHANGES_REQUESTED** [review]

File: packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts (hunk 2 above)
Comment (Abogical) [reply packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts:269]: Only other approach I can think of is either:
- Create a custom JSON serializer
- Process the output of the JSON serialization such that the markers don't have string (`"..."`) escape.

Both methods are quite error-prone.

File: packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts (hunk 3 above)
Comment (Abogical) [reply packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts:271]: Not sure how we could make this clearer. Number tokens are just random numbers recorded by the CDK token system and token strings are in the form of `"${TOKEN[..]}"`. There's also list tokens in the form of `["#${TOKEN[...]"]`. This info wouldn't add much info beyond what is already written in https://docs.aws.amazon.com/cdk/v2/guide/tokens.html

File: packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts (hunk 1 above)
Comment (Abogical) [reply packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts:276]: There may be a misunderstanding, `escapeTokens` already accepts an array.

File: packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts (hunk 2 above)
Comment (vishaalmehrishi) [reply packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts:269]: > Process the output of the JSON serialization such that the markers don't have string ("...") escape.

Can you elaborate on why this is error prone? It would help to explain how these are different from the current approach, and why converting to a number helps.

If an approach is the right one but a little more complex, we'd still prefer that to a hack.

Comment (Abogical) [reply packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts:269]: I don't think there's a "right" approach here. However this is by far the simplest. One possible issue with the point you mention is with YAML serialization. In YAML serialization, a string can be represented in either a quoted or unquoted fashion. We'd have to create logic to handle both cases when escaping tokens. It can also also mean that the tokens string itself could be escaped by the serializer, leading to malformed tokens such as `$\{TOKEN[...]\}`. We want to avoid this escaping behavior altogether by putting a number instead of a string.

File: packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts (hunk 3 above)
Comment (mrgrain) [inline packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts:271]: I don't think this is doing what you think it is. `Token.asNumber()` is just casting a value as number. If the value is a a number, it's returned unchanged otherwise it's wrapped as a number token. This is mainly used to convert CFN attributes (which are all strings) to "numbers" so they can be used in CDK.

Comment (Abogical) [reply packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts:271]: This is intentional. It's a hack to prevent the JSON serializer (`JSON.stringify`) or YAML serializer to wrap the token with quotes ("..."). I want the cast to it being a number even if it does not actually represent a number.

Comment (mrgrain) [inline packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts:271]: I think this and than it's fine.
```suggestion
      return Token.asString(Stack.of(scope).toJsonString(obj));
```

File: packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts (hunk 2 above)
Comment (mrgrain) [reply packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts:269]: > Create a custom JSON serializer

Probably much nicer, but what you have should work.

File: packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts (hunk 3 above)
Comment (Abogical) [reply packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts:271]: I intentionally want to return a number, not a string in this case. So that the JSON serializer won't wrap the string with quotes. The output of toJsonString will have its own quotes by default, or array if its a list token.

Comment (mrgrain) [reply packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts:271]: Any chance of conflicts with real numbers?

Comment (mrgrain) [reply packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts:271]: Huh. I'm just surprised this works.

Comment (Abogical) [reply packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts:271]: To quote Amazon Q:

---

## How Number Tokens are Generated by `Token.asNumber()`

When you call `Token.asNumber(value)`, here's what happens:

### 1. **Initial Check**
If the value is already a number, it's returned as-is:
```typescript
if (typeof value === 'number') { return value; }
```

### 2. **Token Registration**
For non-number values, the token is registered in the `TokenMap` singleton:
```typescript
return TokenMap.instance().registerNumber(Token.asAny(value));
```

### 3. **Number Generation Process**
The `registerNumber` method generates a unique number through these steps:

**a) Counter Increment:**
- Uses an internal counter (`tokenCounter`) that starts at a random number (0-9)
- This randomization prevents accidental dependencies on token values between runs

**b) Special Double Encoding:**
- Calls `createTokenDouble(counter)` to create a special IEEE 754 double
- Uses a specific bit pattern in the top 16 bits to mark it as a token
- The marker pattern is `0xFBFF << 16` (can't be all 1s as that would create NaN)

**c) Bit Manipulation:**
```typescript
const buf = new ArrayBuffer(8);
const ints = new Uint32Array(buf);
ints[0] = x & 0x0000FFFFFFFF; // Bottom 32 bits of counter
ints[1] = (shr32(x) & 0xFFFF) | DOUBLE_TOKEN_MARKER_BITS; // Top 16 bits + marker
return (new Float64Array(buf))[0];
```

### 4. **Key Properties**
- **Unique**: Each call generates a new unique number, even for the same token
- **Reversible**: The number can be decoded back to extract the original token
- **Detectable**: Special pattern allows detection of encoded tokens vs regular numbers
- **JSON-safe**: The encoded numbers survive JSON serialization/deserialization
- **Range**: Can encode up to 2^48-1 different token indices

### 5. **Example**
```typescript
const myToken = Token.asNumber(someResolvable);
// Returns something like: -1.2345678901234e+289
// This special number encodes the token's unique identifier
```

The generated numbers look like very large negative scientific notation numbers (e.g., `-1.1234567890123e+289`) but are actually specially crafted IEEE 754 doubles that encode the token's unique identifier in their bit representation.

---

Given this info, I think a conflict is very unlikely.

**Comment by mrgrain** [comment]
@mergifyio update

**Review by vishaalmehrishi — APPROVED** [review]
