### PR TITLE
fix(cli): make new CLI recognize old assembly versions

### LINKED ISSUE #4294: CDK CLI can only be used with apps created by CDK >= 1.10.0
### Reproduction Steps

Only upgraded to CDK 1.10.0 and tried to run `cdk diff` command

### Error Log

```
CDK CLI can only be used with apps created by CDK >= 1.10.0
```

### Environment

  - **CLI Version** : 1.10.0 (build 19ae072)
  - **Framework Version**: 1.10.0 (build 19ae072)
  - **OS**: OSX Mojave
  - **Language** : python

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
In the latest release, we changed the CX protocol, requiring users of a
newer CLI to upgrade their CDK framework libraries (to be safe).

This particular change was actually backwards compatible, so add the
requisite code to the CLI to recognize and fix that condition.

Fixes #4294.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/cx-api/lib/versioning.ts [hunk 1]
```diff
@@ -27,14 +42,30 @@ export function verifyManifestVersion(manifetVersion: string) {
...
   if (semver.gt(frameworkVersion, toolkitVersion)) {
-    throw new Error(`CDK CLI >= ${frameworkVersion} is required to interact with this app`);
+    throw new Error(`A newer version of the CDK CLI (>= ${frameworkVersion}) is necessary to interact with this app`);
   }
 
   // if framework < cli, we require a newer framework version
   if (semver.lt(frameworkVersion, toolkitVersion)) {
     throw new Error(
-      `CDK CLI can only be used with apps created by CDK >= ${CLOUD_ASSEMBLY_VERSION}`);
+      `A newer version of the CDK framework (>= ${CLOUD_ASSEMBLY_VERSION}) is necessary to interact with this version of the CLI`);
```
Comment (eladb) [inline packages/@aws-cdk/cx-api/lib/versioning.ts]: Maybe something like “the CDK CLI you are using requires your CDK app to use CDK modules with version >= xxx”

Comment (rix0rrr) [reply packages/@aws-cdk/cx-api/lib/versioning.ts]: :sob:

**Comment by eladb** [comment]
For reference: https://t.co/CEircxyDqv

File: packages/@aws-cdk/cx-api/lib/versioning.ts [hunk 2]
```diff
@@ -27,14 +42,29 @@ export function verifyManifestVersion(manifetVersion: string) {
 
   // if framework > cli, we require a newer cli version
   if (semver.gt(frameworkVersion, toolkitVersion)) {
-    throw new Error(`CDK CLI >= ${frameworkVersion} is required to interact with this app`);
+    throw new Error(`A newer version of the CDK CLI (>= ${frameworkVersion}) is necessary to interact with this app`);
```
Comment (eladb) [inline packages/@aws-cdk/cx-api/lib/versioning.ts]: For future generations maybe rename “frameworkVersion” to “frameworkAssemblyVersion” or “appAssemblyVersion”

File: packages/aws-cdk/lib/api/cxapp/exec.ts [hunk 3]
```diff
@@ -73,6 +74,10 @@ export async function execProgram(aws: ISDK, config: Configuration): Promise<cxa
   debug('outdir:', outdir);
   env[cxapi.OUTDIR_ENV] = outdir;
 
+  // Send version information
+  env[cxapi.CLI_ASM_VERSION_ENV] = cxapi.CLOUD_ASSEMBLY_VERSION;
```
Comment (eladb) [inline packages/aws-cdk/lib/api/cxapp/exec.ts]: Curious why through environment variables and not through context... not that I have a strong opinion...

**Comment by rix0rrr** [comment]
> So either way we needed to bump both sides (or gracefully degrade at the framework level, which we couldn’t).

Or make the CLI understand old assembly types, which in this case is totally safe.
