### PR TITLE
fix(rds): do not allow aurora engines when using DatabaseInstance

### LINKED ISSUE #5345: RDS errorous use of StorageType by creating DatabaseInstance with engine AURORA_POSTGESQL
I want to create a DBInstance, I do not have set storageType in the DatabaseInstancdeProps.
The deployment stops with an error.

### Reproduction Steps

```
private createDbInstance():DatabaseInstance {
    const props:DatabaseInstanceProps = {
      engine: DatabaseInstanceEngine.AURORA_POSTGRESQL,
      instanceClass: InstanceType.of(InstanceClass.T3, InstanceSize.MEDIUM),
      multiAz: false,
      vpc: this.vpc,
      vpcPlacement: {
        subnetType: SubnetType.PRIVATE
      },
      databaseName: "test",
      masterUsername: "dbuser",
    };
    return new DatabaseInstance(this, "db-instance", props);
  }
```

### Error Log

```
db-instance (dbinstance310A317F) Invalid storage type: gp2 (Service: AmazonRDS; Status Code: 400; Error Code: StorageTypeNotSupported; Request ID: 94bc0136-a3f8-4bca-9cdf-de8ff9ec3820)
        new DatabaseInstance (/test/node_modules/@aws-cdk/aws-rds/lib/instance.ts:743:22)
        \_ EksTest.createDbInstance (/test/deployment/lib/eks-test.ts:102:16)
        \_ new EksTest (/test/deployment/lib/eks-test.ts:16:32)
        \_ Object.<anonymous> (/test/deployment/bin/eks-test.ts:8:1)
        \_ Module._compile (internal/modules/cjs/loader.js:689:30)
        \_ Module.m._compile (/.npm/_npx/46590/lib/node_modules/ts-node/src/index.ts:536:23)
        \_ Module._extensions..js (internal/modules/cjs/loader.js:700:10)
        \_ Object.require.extensions.(anonymous function) [as .ts] (/.npm/_npx/46590/lib/node_modules/ts-node/src/index.ts:539:12)
        \_ Module.load (internal/modules/cjs/loader.js:599:32)
        \_ tryModuleLoad (internal/modules/cjs/loader.js:538:12)
        \_ Function.Module._load (internal/modules/cjs/loader.js:530:3)
        \_ Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
        \_ main (/npm/_npx/46590/lib/node_modules/ts-node/src/bin.ts:212:14)
        \_ Object.<anonymous> (/.npm/_npx/46590/lib/node_modules/ts-node/src/bin.ts:470:3)
        \_ Module._compile (internal/modules/cjs/loader.js:689:30)
        \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
        \_ Module.load (internal/modules/cjs/loader.js:599:32)
        \_ tryModuleLoad (internal/modules/cjs/loader.js:538:12)
        \_ Function.Module._load (internal/modules/cjs/loader.js:530:3)
        \_ Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
        \_ findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)

```

### Environment

  - **CLI Version      :*aws-cli/1.16.273 Python/3.7.5 Darwin/18.7.0 botocore/1.13.9*
  - **Framework Version:*1.18.1
  - **OS               :*Mac OS 10.14.6*
  - **Language         :*Typescript*

### Other

There should no key storageType in DatabasInstanceProps, when engine is AURORA*

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by jogold**
Aurora instances can only be created inside a cluster and should use the
`DatabaseCluster` construct.

Closes #5345

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-rds/lib/instance.ts [hunk 1]
```diff
@@ -670,6 +670,10 @@ abstract class DatabaseInstanceSource extends DatabaseInstanceNew implements IDa
   constructor(scope: Construct, id: string, props: DatabaseInstanceSourceProps) {
     super(scope, id, props);
 
+    if (/aurora/.test(props.engine.name)) {
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/instance.ts]: I'm not sure I love this test...

How about a method on `Engine`, something like `get allowedOutsideCluster(): boolean` (name TBD of course)? Then, this code could be:

```ts
    if (!props.engine.allowedOutsideCluster) {
      throw new Error(`${props.engine.name} instances can only be created inside a cluster. Please use the DatabaseCluster class instead`);
    }
```

What do you think?
```

Comment (jogold) [reply packages/@aws-cdk/aws-rds/lib/instance.ts]: Yes, it's cleaner.

Comment (jogold) [reply packages/@aws-cdk/aws-rds/lib/instance.ts]: Actually just a `public readonly isDatabaseInstanceEngine = true;` in `DatabaseInstanceEngine` is enough no? Because then the typing system will not allow to use a `DatabaseInstanceCluster` for a `DatabaseInstance` and we don't need to check anymore?

Comment (skinny85) [reply packages/@aws-cdk/aws-rds/lib/instance.ts]: Yep. This works:

```ts
export class DatabaseInstanceEngine extends DatabaseClusterEngine {
  // ...

  /** To make it a compile-time error to pass a DatabaseClusterEngine where a DatabaseInstanceEngine is expected. */
  public readonly isDatabaseInstanceEngine = true;
}
```

Having it be a compile-time error is even better than adding runtime validation.
