### PR TITLE
fix(appmesh): Move Client Policy from Virtual Service to backend structure

### LINKED ISSUE #11996: (aws-appmesh): Client Policies object should not be part of the Virtual Service
Client Policies are inherently not related to the Virtual Service. It should be thought of as the client (the VN) telling envoy what connections they want to allow to the server (the Virtual Service). The server `shouldn't` be the one to define what policies are used to enforce connections with itself.

### Reproduction Steps
None

### What did you expect to happen?
Client policy object should be a part of Virtual Node, not Virtual Service. A VirtualNode can have a VirtualService as a backend and an associated client policy and a different VirtualNode should have the same VirtualService backend without associated client policy. 

### What actually happened?
Client Policy is a part of Virtual Service. We cannot use same VirtualService with different client policies as the client policy is now attached to a Virtual Service itself. 

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by alexbrjo**
@sshver:
 
> Client Policies are inherently not related to the Virtual Service. It should be thought of as the client (the VN) telling envoy what connections they want to allow to the server (the Virtual Service). The server shouldn't be the one to define what policies are used to enforce connections with itself.

## Description of changes
I refactored the client policy from Virtual Service to a separate backend structure. This mirrors how our API is designed. Also ran `npm run lint -- --fix` and removed some comments to fix lint warnings.

```ts
/* Old backend defaults */
backendsDefaultClientPolicy: appmesh.ClientPolicy.fileTrust({
  certificateChain: 'path-to-certificate',
}),

/* result of this PR */
backendDefaults: {
  clientPolicy: appmesh.ClientPolicy.fileTrust({
    certificateChain: 'path-to-certificate',
  }),
},
```

```ts
/* Old Virtual Service with client policy */
const service1 = new appmesh.VirtualService(stack, 'service-1', {
  virtualServiceName: 'service1.domain.local',
  virtualServiceProvider: appmesh.VirtualServiceProvider.none(mesh),
  clientPolicy: appmesh.ClientPolicy.fileTrust({
    certificateChain: 'path-to-certificate',
    ports: [8080, 8081],
  }),
});

/* result of this PR; client policy is defined in the Virtual Node */
const service1 = new appmesh.VirtualService(stack, 'service-1', {
  virtualServiceName: 'service1.domain.local',
  virtualServiceProvider: appmesh.VirtualServiceProvider.none(mesh),
});

const node = new appmesh.VirtualNode(stack, 'test-node', {
  mesh,
  serviceDiscovery: appmesh.ServiceDiscovery.dns('test'),
});

node.addBackend({
  virtualService: service1,
  clientPolicy: appmesh.ClientPolicy.fileTrust({
    certificateChain: 'path-to-certificate',
    ports: [8080, 8081],
  }),
});
```

BREAKING CHANGE: Backend, backend default and Virtual Service client policies structures are being altered
* **appmesh**: you must use the backend default interface to define backend defaults in `VirtualGateway`.
  The property name also changed from `backendsDefaultClientPolicy` to `backendDefaults`
* **appmesh**:  you must use the backend default interface to define backend defaults in `VirtualNode`,
  (the property name also changed from `backendsDefaultClientPolicy` to `backendDefaults`),
  and the `Backend` class to define a backend
* **appmesh**: you can no longer attach a client policy to a `VirtualService`

Resolves #11996

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by alexbrjo** [comment]
I'm getting 500s from refreshing this page and I see a couple of the checks failed with 500s too. Maybe a Github availability dip - I'll wait and rerun them.

File: packages/@aws-cdk/aws-appmesh/lib/backend.ts [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+   */
+  public static backend(props: BackendOptions): Backend {
+    return new Backend(props.virtualService, props.clientPolicy);
+  }
+}
+
+/**
+ * Represents all the backends that aren't specifically defined using the backend .
+ */
+export class BackendDefaults {
```
Comment (dfezzie) [inline packages/@aws-cdk/aws-appmesh/lib/backend.ts:59]: I wonder if we could just make this an interface. I'm trying to think of a situation where we would need to enforce mutual exclusivity for this field and I'm not sure if we would need this. What do you think?

Comment (alexbrjo) [reply packages/@aws-cdk/aws-appmesh/lib/backend.ts:59]: Not sure if I'm following. Do you mean both `Backend` and `BackendDefaults` would implement an interface that enforces a method to get the client policy?

Comment (dfezzie) [reply packages/@aws-cdk/aws-appmesh/lib/backend.ts:59]: Like, just defining BackendDefaults as an interface type

```typescript
interface BackendDefaults {
      readonly clientPolicy?: ClientPolicy;
}
```

and then instead of having to call `Backends.backendDefaults` you could just create a new object like:


```typescript
new VirtualNode(stack, 'VirtualNode', {
    ...
    backendDefaults: {
        clientPolicy: appmesh.ClientPolicy.acm({ ... }),
    }
);
```

Comment (dfezzie) [reply packages/@aws-cdk/aws-appmesh/lib/backend.ts:59]: My understanding is the `bind()` methods are used to enforce exclusivity. Like you cannot define both `file` and `acm` types for ClientPolicies. For backend defaults, I don't see us needing to enforce this mutual exclusivity

File: packages/@aws-cdk/aws-appmesh/test/integ.mesh.ts [hunk 2]
```diff
@@ -23,11 +23,21 @@ const router = mesh.addVirtualRouter('router', {
   ],
 });
 
-const virtualService = new appmesh.VirtualService(stack, 'service', {
+const virtualService1 = new appmesh.VirtualService(stack, 'service1', {
```
Comment (skinny85) [inline packages/@aws-cdk/aws-appmesh/test/integ.mesh.ts:26]: Let's leave this ID as-is, and just start adding `'service2'` below. We should minimize these changes as much as possible.

**Review by skinny85 — CHANGES_REQUESTED** [review]
Looks nice @alexbrjo ! But I think this is one of the places where we don't need the `bind()` pattern, and we can just go with simple interfaces instead.

Also, make sure to include all of the breaking changes in this PR in the description - see our [Contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#step-4-commit) for how these should be structured.

File: packages/@aws-cdk/aws-appmesh/lib/backend.ts (hunk 1 above)
Comment (dfezzie) [reply packages/@aws-cdk/aws-appmesh/lib/backend.ts:59]: I would hesitate to remove to remove the `bind()` pattern for the backend itself. I could see there being other targets in the future that might not be a `IVirtualService`. We don't have any immediate plans for this, but adding a different type here is within the realm of reason.

**Comment by alexbrjo** [comment]
Builds fail with an error in another module. Looking into it

```
@aws-cdk-containers/ecs-service-extensions: lib/extensions/appmesh.ts(349,33): error TS2345: Argument of type 'VirtualService' is not assignable to parameter of type 'Backend'.
@aws-cdk-containers/ecs-service-extensions:   Property 'virtualService' is missing in type 'VirtualService' but required in type 'Backend'.
```

File: packages/@aws-cdk/aws-appmesh/lib/backend.ts (hunk 1 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-appmesh/lib/backend.ts]: Fair enough. I defer to the expert(s) here 🙂.

File: packages/@aws-cdk/aws-appmesh/lib/shared-interfaces.ts [hunk 3]
```diff
@@ -194,3 +196,32 @@ class FileAccessLog extends AccessLog {
   }
 }
 
+/**
+ * Represents the properties needed to define a backend
+ */
+export interface Backend {
```
Comment (dfezzie) [inline packages/@aws-cdk/aws-appmesh/lib/shared-interfaces.ts:202]: I'm still partial to leaving this as a `bind()` class. We could have other backend types in the future

Comment (alexbrjo) [reply packages/@aws-cdk/aws-appmesh/lib/shared-interfaces.ts:202]: I couldn't imagine any fundamentally different outbound traffic (other backend types). I could only think of additional handling logic for the outbound traffic (client side throttling), which would be implemented by adding properties to the backend.

Also the `backends` property in the [API is a list](https://docs.aws.amazon.com/app-mesh/latest/APIReference/API_VirtualNodeSpec.html#appmesh-Type-VirtualNodeSpec-backends) and I don't think that leaves room to create other backend types in the future.

Comment (dfezzie) [reply packages/@aws-cdk/aws-appmesh/lib/shared-interfaces.ts:202]: The `backend` property is [not a list though](https://docs.aws.amazon.com/app-mesh/latest/APIReference/API_Backend.html). We could easily introduce a different type here in the future, such as using a Virtual Gateway as a target or some sort of egress type.

File: packages/@aws-cdk/aws-appmesh/lib/shared-interfaces.ts [hunk 4]
```diff
@@ -197,31 +197,83 @@ class FileAccessLog extends AccessLog {
...
+  public abstract bind(_scope: Construct): BackendConfig;
+}
+
+/**
+ * Represents the properties needed to define a Virtual Service backend
+ */
+class VirtualServiceBackend extends Backend {
+
+  constructor (private readonly virtualService: IVirtualService,
+    private readonly clientPolicy: ClientPolicy | undefined) {
```
Comment (dfezzie) [inline packages/@aws-cdk/aws-appmesh/lib/shared-interfaces.ts:262]: Does this just store these in class properties without having to declare/assign them explicitly?

**Review by dfezzie — APPROVED** [review]
Changes LGTM at this point. 👍  

I'll defer the rest of the review to Adam

File: packages/@aws-cdk/aws-appmesh/lib/shared-interfaces.ts [hunk 5]
```diff
@@ -194,3 +196,84 @@ class FileAccessLog extends AccessLog {
...
+
+
+/**
+ * Contains static factory methods to create backends
+ */
+export abstract class Backend {
+  /**
+   * Construct a Virtual Service backend
+   */
+  public static virtualServiceBackend(props: VirtualServiceBackendOptions): Backend {
```
Comment (skinny85) [inline packages/@aws-cdk/aws-appmesh/lib/shared-interfaces.ts:246]: How about calling this method just `virtualService`? The `Backend` part is kind of implied by the class it's on 🙂.

File: packages/@aws-cdk/aws-appmesh/lib/virtual-gateway.ts [hunk 6]
```diff
@@ -180,7 +179,9 @@ export class VirtualGateway extends VirtualGatewayBase {
       meshName: this.mesh.meshName,
       spec: {
         listeners: this.listeners.map(listener => listener.listener),
-        backendDefaults: props.backendsDefaultClientPolicy?.bind(this),
+        backendDefaults: props.backendDefaults !== undefined ? {
+          clientPolicy: props.backendDefaults?.clientPolicy?.bind(this).clientPolicy,
+        } : undefined,
```
Comment (skinny85) [inline packages/@aws-cdk/aws-appmesh/lib/virtual-gateway.ts:184]: Can we indent this slightly differently?

```suggestion
        backendDefaults: props.backendDefaults !== undefined
          ? {
            clientPolicy: props.backendDefaults?.clientPolicy?.bind(this).clientPolicy,
          }
          : undefined,
```

File: packages/@aws-cdk/aws-appmesh/lib/virtual-node.ts [hunk 7]
```diff
@@ -185,7 +183,9 @@ export class VirtualNode extends VirtualNodeBase {
       spec: {
         backends: cdk.Lazy.anyValue({ produce: () => this.backends }, { omitEmptyArray: true }),
         listeners: cdk.Lazy.anyValue({ produce: () => this.listeners.map(listener => listener.listener) }, { omitEmptyArray: true }),
-        backendDefaults: props.backendsDefaultClientPolicy?.bind(this),
+        backendDefaults: props.backendDefaults !== undefined ? {
+          clientPolicy: props.backendDefaults?.clientPolicy?.bind(this).clientPolicy,
+        } : undefined,
```
Comment (skinny85) [inline packages/@aws-cdk/aws-appmesh/lib/virtual-node.ts:188]: Same here:

```suggestion
        backendDefaults: props.backendDefaults !== undefined
          ? {
            clientPolicy: props.backendDefaults?.clientPolicy?.bind(this).clientPolicy,
          }
          : undefined,
```

File: packages/@aws-cdk/aws-appmesh/test/integ.mesh.expected.json [hunk 8]
```diff
@@ -650,7 +650,7 @@
               "VirtualService": {
                 "VirtualServiceName": {
                   "Fn::GetAtt": [
-                    "service27C65CF7D",
```
Comment (skinny85) [inline packages/@aws-cdk/aws-appmesh/test/integ.mesh.expected.json:653]: Why did these change their IDs? Will this cause replacement for current customers of the library?

**Review by skinny85 — DISMISSED** [review]
Looks good! Couple of minor comments/questions.

Also, I believe the ReadMe file of the module also needs updating with these changes!

File: packages/@aws-cdk/aws-appmesh/test/integ.mesh.expected.json (hunk 8 above)
Comment (alexbrjo) [reply packages/@aws-cdk/aws-appmesh/test/integ.mesh.expected.json:653]: They were previously created inline and I refactored them so I could reference them at multiple spots. This isn't needed anymore so I can take it out of the diff.

File: packages/@aws-cdk/aws-appmesh/lib/shared-interfaces.ts (hunk 5 above)
Comment (alexbrjo) [reply packages/@aws-cdk/aws-appmesh/lib/shared-interfaces.ts:246]: I added `backend` because I though `Backend.virtualService` sounded like it implied creation of a new virtual service. On second thought, I agree and I think we can expect a user to infer this. So I'm fine renaming it.

**Comment by alexbrjo** [comment]
Merge from master, addressed all comments + noticed I didn't previously update the README. So added that

**Comment by alexbrjo** [comment]
The `AWS CodeBuild CI Report` succeeded (see above comment) and the logs look fine at a glance. but the "AWS CodeBuild us-east-1 (AutoBuildProject89A8053A-LhjRyN9kxr8o)" check below failed. How can I figure out why this happened?

**Comment by skinny85** [comment]
@alexbrjo Not sure why the failing build did not post the logs, but the build is failing on:

```
@aws-cdk-containers/ecs-service-extensions: lib/extensions/appmesh.ts(350,49): error TS2339: Property 'virtualServiceBackend' does not exist on type 'typeof Backend'.
--
981 | @aws-cdk-containers/ecs-service-extensions: Error: /codebuild/output/src634370312/src/github.com/aws/aws-cdk/node_modules/typescript/bin/tsc --build exited with error code 1
982 | @aws-cdk-containers/ecs-service-extensions: Build failed.!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
983 | @aws-cdk-containers/ecs-service-extensions: error Command failed with exit code 1.
984 | @aws-cdk-containers/ecs-service-extensions: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
985 | @aws-cdk-containers/ecs-service-extensions: error Command failed with exit code 1.
986 | @aws-cdk-containers/ecs-service-extensions: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
987 | lerna ERR! yarn run build+test exited 1 in '@aws-cdk-containers/ecs-service-extensions'
988 | lerna WARN complete Waiting for 5 child processes to exit. CTRL-C to exit immediately.
```

File: packages/@aws-cdk/aws-appmesh/lib/shared-interfaces.ts [hunk 9]
```diff
@@ -194,3 +196,84 @@ class FileAccessLog extends AccessLog {
...
+/**
+ * Contains static factory methods to create backends
+ */
+export abstract class Backend {
+  /**
+   * Construct a Virtual Service backend
+   */
+  public static virtualService(props: VirtualServiceBackendOptions): Backend {
+    return new VirtualServiceBackend(props.virtualService, props.clientPolicy);
+  }
```
Comment (skinny85) [inline packages/@aws-cdk/aws-appmesh/lib/shared-interfaces.ts:248]: How about we add `virtualService` as the first positional argument to this method, and remove it from `VirtualServiceBackendOptions`?

The reason I ask is because, right now, you have to do:

```ts
Backend.virtualService({ virtualService: virtualService })
```

That's a lot of `virtualService`!

Instead, if we could do `Backend.virtualService(virtualService, { optionalPropsHere: false } )`, it seems a lot more natural.

Thoughts on this idea?

**Review by skinny85 — COMMENTED** [review]
Everything looks great @alexbrjo !

I have one suggestion - I'm curious what your opinion is on it.

File: packages/@aws-cdk/aws-appmesh/lib/shared-interfaces.ts (hunk 9 above)
Comment (alexbrjo) [reply packages/@aws-cdk/aws-appmesh/lib/shared-interfaces.ts:248]: A reference to the Virtual Service is a [required parameter](https://docs.aws.amazon.com/app-mesh/latest/APIReference/API_VirtualServiceBackend.html) so IMO this is a smart and safe simplification. done

File: packages/@aws-cdk-containers/ecs-service-extensions/lib/extensions/appmesh.ts [hunk 10]
```diff
@@ -347,7 +347,7 @@ export class AppMeshExtension extends ServiceExtension {
     // Next update the app mesh config so that the local Envoy
     // proxy on this service knows how to route traffic to
     // nodes from the other service.
-    this.virtualNode.addBackend(appmesh.Backend.virtualService({ virtualService: otherAppMesh.virtualService }));
+    this.virtualNode.addBackend(appmesh.Backend.virtualService(otherAppMesh.virtualService ));
```
Comment (skinny85) [inline packages/@aws-cdk-containers/ecs-service-extensions/lib/extensions/appmesh.ts:350]: No need for the space before the `))`:

```suggestion
    this.virtualNode.addBackend(appmesh.Backend.virtualService(otherAppMesh.virtualService));
```

File: packages/@aws-cdk/aws-appmesh/README.md [hunk 11]
```diff
@@ -230,14 +232,16 @@ const virtualService = new appmesh.VirtualService(stack, 'service-1', {
   }),
 });
 
-node.addBackend(virtualService);
+node.addBackend(appmesh.Backend.virtualService({
+  virtualService: virtualService,
+}));
```
Comment (skinny85) [inline packages/@aws-cdk/aws-appmesh/README.md:237]: Should be changed now that `virtualService` is a positional parameter:

```suggestion
node.addBackend(appmesh.Backend.virtualService(virtualService));
```

File: packages/@aws-cdk/aws-appmesh/lib/shared-interfaces.ts (hunk 4 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-appmesh/lib/shared-interfaces.ts:258]: Yep! TypeScript magic 🙂. typescriptlang.org/docs/handbook/2/classes.html#parameter-properties

**Review by skinny85 — DISMISSED** [review]
Looks great @alexbrjo!

**Review by skinny85 — APPROVED** [review]
