### PR TITLE
fix(codebuild): validate if a CodePipeline action that is cross-account does not have outputs

### LINKED ISSUE #4032: Add validation for a cross-account CodeBuild CodePipeline action with outputs
A CodeBuild action that has outputs cannot be cross-account - it will fail at CodePipeline runtime.

* Add validation that fails if a customer tries to create a cross-account CodeBuild action with outputs
* Create an issue in our backlog that points to the CodeBuild troubleshooting guide, and add a link to this issue to the validation message created above
* Consider adding a property like `skipCrossAccountOutputsValidation: boolean` (default: `false`) that allows a customer to get rid of this validation once CodeBuild fixes the issue without having to update their CDK version. Later we can deprecate that field, remove the validation and never use the property anymore

### PR DESCRIPTION
**Pull request by skinny85**
CodeBuild does not honor the key set on the project if the key is from a different account. That means a cross-account CodeBuild action effectively cannot have outputs (as they will be written with the default S3 key of the CodeBuild account, which the other actions won't have access to).

Add validation that throws an error if there is an attempt to add a cross-account CodeBuild action with outputs.

Fixes #4032

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts [hunk 1]
```diff
@@ -60,6 +60,21 @@ export interface CodeBuildActionProps extends codepipeline.CommonAwsActionProps
...
+   * If the action is cross-account, and has outputs,
+   * and this property is true (which is the default),
+   * an exception will be thrown.
+   * You can set this to false to skip this validation.
+   *
+   * @default true
+   * @see https://github.com/aws/aws-cdk/issues/4169
+   */
+  readonly validateCrossAccountOutputs?: boolean;
 }
```
Comment (eladb) [inline packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts]: What’s the benefit of having this option if it doesn’t work?

Comment (skinny85) [reply packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts]: At some point, CodeBuild will fix this behavior, and this escape hatch allows the customer to override our check without having to upgrade their version of the CDK.

**Comment by skinny85** [comment]
Rebased on top of `1.9.0`.

File: packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts (hunk 1 above)
Comment (eladb) [reply packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts]: Will their fix block CDK users? Seems like this will still work even after this will be fixed by CodeBuild, and then we can leisurely remove this workaround without breaking users, no?

Comment (eladb) [reply packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts]: Sorry I thought this was about the encryption key workaround and not the output artifacts. Still... I prefer that we didn’t pollute our API with this because after the issue is fixed, we will stay with an api that doesn’t have a meaning. Let’s not expose this for now. We update the cdk every week. When this issue is resolved by codebuild we can easily remove this fix and release an update.

Comment (skinny85) [reply packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts]: After the issue is fixed, this is one deprecated property that will simply not be used anywhere. In my opinion, the cost for us is pretty much zero.

Comment (eladb) [reply packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts]: Let's not future proof. When CodeBuild fixes the issue we can remove the workaround.

Comment (skinny85) [reply packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts]: Removed `validateCrossAccountOutputs`.

**Comment by skinny85** [comment]
Newest version - rebased + removed `validateCrossAccountOutputs`.

**Comment by skinny85** [comment]
Rebased.

File: packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts (hunk 1 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts]: I just thought of an edge-case with this.

If the subsequent action that reads the output of the CodeBuild action is in the same account as the CodeBuild project, the artifact will be read correctly (even though it can't be read by anything from the pipeline account, because of the wrong key used to encrypt this).

Does this possibly change your stance on having an escape hatch with `validateCrossAccountOutputs` @eladb ?

Comment (eladb) [reply packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts]: Let's leave it out for now and add if users will request this capability. Then we can think what's the best way to expose it. OK?

Comment (skinny85) [reply packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts]: OK. I'm merging this in then.
