### PR TITLE
fix(secretsmanager): Secret.fromSecretName doesn't work with ECS

### LINKED ISSUE #10519: ecs.Secret.fromSecretsManager generates secret name instead of secret ARN
```typescript
import * as secretsMgr from "@aws-cdk/aws-secretsmanager";

const mySecret = secretsMgr.Secret.fromSecretName(this,"mysecret",`${appSecretBase}/MySecret`);
const mySecretEnv = ecs.Secret.fromSecretsManager(mySecret)
mySecret.grantRead(fargateTaskExecutionRole);
mySecretEnv.grantRead(fargateTaskExecutionRole);

// ...

const container = fargateTaskDefinition.addContainer("appserver", {

// ...

      secrets: {
        MY_SECRET: mySecretEnv,

// ...


 
```

### What did you expect to happen?

Expect the fargate task to launch

### What actually happened?

Fargate task failed to launch with the following error:

```
Fetching secret data from SSM Parameter Store in us-west-2: AccessDeniedException: User: arn:aws:sts::---:assumed-
role/...taskDefExecutionRole9295-1N6FDVCBGB6RK/67766c7d-d908-4b49-b196--:parameter/my path/MySecret 
status code: 400, request id: 2ed367bc-35a9-42ad-b807-e1b2a70ea8f1

```
Notice, the error is complaining about *SSM* (parameter store), not *Secrets Manager*.

### Environment

  - **CLI Version      :**  1.64.0
  - **Framework Version:** 1.64.0
  - **Node.js Version:** 12.18.3
  - **OS               :** macos 10.15.6 
  - **Language (Version):** typescript 3.9.7

### Other

Looking at the generated secrets configuration, I see

```
# ...
            "Secrets": [
              {
                "Name": "MY_SECRET",
                "ValueFrom": "/my path/MySecret"
              },
```

This is a simple parameter name, NOT an ARN to a secret in secret manager, which is what the CloudFormation docs indicate should be here.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by njlynch**
The ability to import and reference a Secret purely by the secret name was
introduced in #10309. One of the original requests was modelled after the
integration with CodeBuild, where either the secret name or the full ARN
-- including the SecretsManager-provided suffix -- were accepted, but not a
"partial" ARN without the suffix. To ease integrations with other services
in this case, the `secretArn` was defined as returning the `secretName` for
these secrets imported by name.

However, other services -- like ECS -- require that an ARN format is provided,
even as a partial ARN. This introduces a dual behavior where sometimes the
secretName works and partial ARN fails, and other times the partial ARN works
and the secretName fails.

This change deprecates `fromSecretName` and introduces a new, better-behaved
`fromSecretNameV2` that sets the ARN to a "partial" ARN without the Secrets
Manager suffix. It also introduces a `secretFullArn` that is an optional version
of `secretArn` that will be undefined for secrets imported by name.

Related changes
* I improved the suffix-strippiung logic of `parseSecretName` to only strip a
  suffix if it's exactly 6 characters long, as all SecretsManager
  suffixes are 6 characters. This prevents accidentally stripping the last word
  off of a hyphenated secret name like 'github-token'.
* Updated the CodeBuild integration and added CodeBuild tests.

fixes #10519

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-secretsmanager/lib/secret.ts [hunk 1]
```diff
@@ -299,8 +317,8 @@ export class Secret extends SecretBase {
     });
 
     if (props.generateSecretString &&
-        (props.generateSecretString.secretStringTemplate || props.generateSecretString.generateStringKey) &&
-        !(props.generateSecretString.secretStringTemplate && props.generateSecretString.generateStringKey)) {
+      (props.generateSecretString.secretStringTemplate || props.generateSecretString.generateStringKey) &&
```
Comment (skinny85) [inline packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:320]: I would leave this as-is, look better indented IMO.

File: packages/@aws-cdk/aws-secretsmanager/lib/secret.ts [hunk 2]
```diff
@@ -250,19 +264,23 @@ export class Secret extends SecretBase {
...
     return new class extends SecretBase {
       public readonly encryptionKey = undefined;
-      public readonly secretArn = secretName;
+      public readonly secretArn = options.supportPartialSecretArn ? this.partialArn : secretName;
       public readonly secretName = secretName;
       protected readonly autoCreatePolicy = false;
       // Overrides the secretArn for grant* methods, where the secretArn must be in ARN format.
       // Also adds a wildcard to the resource name to support the SecretsManager-provided suffix.
       protected get arnForPolicies() {
+        return this.partialArn + '*';
```
Comment (skinny85) [inline packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:276]: I wonder - should this be `-*`?

File: packages/@aws-cdk/aws-secretsmanager/lib/secret.ts [hunk 3]
```diff
@@ -604,9 +622,13 @@ function parseSecretName(construct: IConstruct, secretArn: string) {
...
-    // Secret resource names are in the format `${secretName}-${SecretsManager suffix}`
-    // If there is no hyphen, assume no suffix was provided, and return the whole name.
-    return resourceName.substr(0, resourceName.lastIndexOf('-')) || resourceName;
+    // Secret resource names are in the format `${secretName}-${6-character SecretsManager suffix}`
+    // If there is no hyphen (or 6-character suffix) assume no suffix was provided, and return the whole name.
+    const lastHyphenIndex = resourceName.lastIndexOf('-');
+    if (lastHyphenIndex !== -1 && resourceName.substr(lastHyphenIndex + 1).length === 6) {
+      return resourceName.substr(0, lastHyphenIndex);
+    }
+    return resourceName;
```
Comment (skinny85) [inline packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:631]: Can you re-write this just slightly?

```suggestion
    const hasHyphenAndSixCharSuffix = lastHyphenIndex !== -1 && resourceName.substr(lastHyphenIndex + 1).length === 6;
    return hasHyphenAndSixCharSuffix ? resourceName.substr(0, lastHyphenIndex) : resourceName;
```

**Review by skinny85 — COMMENTED** [review]
Looks good! A few comments / questions.

File: packages/@aws-cdk/aws-secretsmanager/lib/secret.ts (hunk 2 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:276]: Actually... should this be `-??????`?

File: packages/@aws-cdk/aws-secretsmanager/lib/secret.ts [hunk 4]
```diff
@@ -237,6 +237,20 @@ abstract class SecretBase extends Resource implements ISecret {
   protected get arnForPolicies() { return this.secretArn; }
 }
 
+/** Options for `Secret.fromSecretName` */
+export interface SecretFromSecretNameOptions {
+  /**
+   * Whether the secret imported by name will respond with a "partial" ARN without the Secrets Manager suffix.
+   * If this is set, `secretArn` will return a composed ARN without the Secrets Manager suffix.
+   * If not set, 'secretArn' will return the `secretName`.
```
Comment (nija-at) [inline packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:245]: Don't like this quirk. It's so non-trivial and easy to miss. 
`arn` should return ARN, not name.

How about instead introduce three things in `ISecret` - `secretName`, `secretPartialArn` and `secretArn`?
And then have the combination of import APIs as needed. 

However, if a customer imports a secret with only the name or the partial ARN and their integration (i.e., ECS) requests a fullArn, the API will fail.

**Review by nija-at — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-secretsmanager/lib/secret.ts (hunk 4 above)
Comment (njlynch) [reply packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:245]: > However, if a customer imports a secret with only the name or the partial ARN and their integration (i.e., ECS) requests a fullArn, the API will fail.

This means customers who currently import the secret by name and make some reference to `secretArn` somewhere will go from having a working synth/deploy to an error.

The only way to make the above work -- I think -- would be to deprecate `fromSecretName` and introduce a new `fromSecretNameV2` or `fromSecretNameWithProperPartialArnHandling` (or `fromSecretNameButNotDeprecated`) or something. Any suggestions? 

--- 

This also doesn't quite solve how the integration knows what forms are available. Requesting the `secretArn` and catching an error doesn't fit. The only sane thing I can think of is that integrations must always just use the "weakest" form they can accept. For example, CodeBuild would always just use the `secretName`, even if the full ARN was available.

This has some implications, especially given that today users can provide either a partial or full ARN to `fromSecretArn`, and the code that determines the `secretName` from the ARN can't deterministically know which was provided. An ARN of `arn:aws:secretsmanager:eu-west-1:111111111111:secret:github-tokens` will be treated like a full ARN with a SecretsManager suffix of 'tokens', rather than a partial ARN.

```ts
const secret = secretsmanager.Secret.fromSecretArn(this, 'secret', 'arn:aws:secretsmanager:eu-west-1:111111111111:secret:github-tokens');
secret.secretName; // 'github'
```

There are likely scenarios where an integrating service will break due to the above, but be fine with the `secretArn` (or even `partialArn`).

In lieu of error checking, I suppose we could introduce new fields to track what is available (e.g., `hasFullArn`), but that feels gross.

What do you think?

Comment (skinny85) [reply packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:245]: I think it's worth it to look from the perspective of the consumers of the SecretsManager library. How should using it look like?

For example, we have code in CodeBuild that uses `ISecret`: https://github.com/aws/aws-cdk/blob/0537598a065c74c713d1ec58c96f09f0d66b12ca/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L966-L966

Is there any way we can sensibly make a decision in that CodeBuild Project code to use either `secretName` or `secretArn`, considering CodeBuild is one of the services that supports both?

Comment (njlynch) [reply packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:245]: @nija-at / @skinny85 - How much do you both hate something like this?

```ts
  /**
   * Returns an identifier for the secret that can be used to reference the secret in other constructs.
   * For owned secrets, this will always be the secret ARN. For imported secrets,this identifier may be either
   * the full secret ARN (with SecretsManager-suffix),
   * partial secret ARN (without the suffix),
   * or just the secret name, depending on what values are available.
   * Returns the "strongest" identifier available (full > partial > secret name), unless `acceptPartialArns` is false.
   */
  public secretId(acceptPartialArns: boolean = true): string {
    return (!this._isPartialArn || acceptPartialArns) ? this.secretArn : this.secretName;
  }
```

`_isPartialArn` would only be true for secrets imported by name; a new `fromPartialSecretArn` could also be created as well to set the flag but otherwise behave like `fromSecretArn`.

This moves the responsibility from the end-user to construct library author.

The CodeBuild code would be updated to read like this:

```ts
credential: this.buildImage.secretsManagerCredentials.secretId(false), 
```

And the ECS code could be updated as well:

https://github.com/aws/aws-cdk/blob/a4a41b5e006110304b51ee55c34e91cc3f129281/packages/@aws-cdk/aws-ecs/lib/container-definition.ts#L39

```ts
arn: field ? `${secret.secretId()}:${field}::` : secret.secretId(),
```

--- 

The above could be done in conjunction with -- or independently from -- creating a `fromSecretNameV2` (better name suggestions welcome).

Comment (skinny85) [reply packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:245]: Oh man. This is such a mess.

I actually think the simplest solution would be to have `secretName` return `string | undefined`. I actually thought that was already the case, because of #10914. So then, in CodeBuild, you could do:

```ts
credential: this.buildImage.secretsManagerCredentials.secretName ?? this.buildImage.secretsManagerCredentials.secretArn,
```

 (I assume a new Secret without a `secretName` set in `SecretProps` would return an undefined `secret.secretName`)

While on ECS you would always use `secretArn`.

Is it too late to go this route?

Comment (njlynch) [reply packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:245]: > I actually think the simplest solution would be to have secretName return string | undefined. I actually thought that was already the case, because of #10914.

:cry: Well, it *is*, but only for owned `Secrets`. Imported secrets always set the `secretName`. This is frankly just an oversight on my part; owned `Secrets` were intended to have `secretName` set as well; I think I mistakenly believed that the below line would treat `this.physicalName` as a `Token` and set the name after creation. Whoops.

https://github.com/aws/aws-cdk/blob/a4a41b5e006110304b51ee55c34e91cc3f129281/packages/@aws-cdk/aws-secretsmanager/lib/secret.ts#L354

> Is it too late to go this route?

With the existing `fromSecretName`, yes. With a new `fromSecretNameV2`, no, but I question whether it's the right route. It does make that above usage possible, but at the cost of not having a `secretName` in cases where we definitely could.

Comment (njlynch) [reply packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:245]: I wouldn't mind if @eladb weighed in here with some thoughts...

Comment (eladb) [reply packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:245]: Definitely feels wrong to put the burden on the user. This is precisely stuff we would want to completely encapsulate within the library. But I am not sure I completely understand all the implications.

@njlynch can you please summarize what would be the ideal API, if we had designed it from the ground up? Then, can you describe which aspects of this API break the existing behavior.

Comment (njlynch) [reply packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:245]: **Background:**

Secrets are given a name on creation, either by users or generated by CloudFormation. The name is then suffixed with a hyphen plus a six-character string to form the "full" name (e.g., `MySecret` becomes `MySecret-abc123`). The ARN is formatted as `arn:aws:secretsmanager:$REGION:$ACCOUNT:secret:$SECRET_NAME`. Depending on the scenario (which API or CloudFormation integration you're using), the secret name (with and without the suffix) or ARN (with and without the suffix) can be used. Additional complexity comes from the fact that secret names can contain hyphens themselves, so 'my-secret-abc123' could be a "partial" secret name or a "full" secret name, and there's no deterministic way to know. Secrets Manager [discourages](https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_DescribeSecret.html#SecretsManager-DescribeSecret-request-SecretId) creating secrets of this format, but doesn't prevent it.

Given a secret name (without a 6-character suffix), a partial ARN may be created. Given an ARN, a partial ARN and secret name can be derived; however, this runs into issues when the secret name itself contains a 6-character suffix (which is valid).

**Desired state:**

Users want to be able to import existing secrets by both (partial|full) ARN and (partial|full) name. Importing by partial name is often the most convenient for multi-environment setups, as the partial name is the only identifier that may be the same across accounts and regions. Ideally, a user imports the secret given a (partial|full) (name|ARN) and then is able to use it anywhere an `ISecret` is accepted, without worrying about the underlying details.

Various constructs have different rules for which secret identifier they can accept. CodeBuild will not accept a partial ARN but can accept a secret name. ECS will only accept an ARN, either partial or full. The onus of determining which identifier(s) are available and which to use should fall on the construct library, not the user. Generally, the construct library should prefer to use the "strongest" (full ARN > partial ARN > secret name) identifier available, as it reduces ambiguity.

Ideal API:

```ts
interface ISecret {
  readonly encryptionKey?: kms.IKey;
  readonly secretArn: string;
  readonly secretName: string;
  readonly secretValue: SecretValue;
  // True iff the `secretArn` does not contain the SecretsManager-provided suffix.
  readonly secretArnIsPartial: boolean;
}

// Open to slightly different representations, see https://github.com/aws/aws-cdk/pull/10410#discussion_r490465209
interface SecretAttributes {
  readonly secretArn?: string;
  readonly encryptionKey?: kms.IKey;
  readonly secretName?: string;
}

// Imports the secret by name, sets `secretArnIsPartial = true`.
public static fromSecretName(scope: Construct, id: string, secretName: string)
// Imports the secret by ARN, automatically sets the secret name. `secretArnIsPartial = false`
public static fromSecretArn(scope: Construct, id: string, secretArn: string)
// Imports the secret by ARN or name.
// If secretName and secretArn are both provided, explicitly sets secretName,
// and sets `secretArnIsPartial` based on the comparison of the ARN and secretName.
// Use case is for handling the worst-case secret names with 6-character suffixes.
public static fromSecretAttributes(scope: Construct, id: string, attrs: SecretAttributes)

constructor(scope: Construct, id: string, props: SecretProps) {
 // secretArnIsPartial = false;
}
```

Consumers of the `ISecret` use the `secretArnIsPartial` flag to make a determination on how to handle the secret. For example, CodeBuild's logic would be:

```ts
credential: secret.secretArnIsPartial ? secret.secretName : secret.secretArn;
```

ECS would simply continue using `secretArn` as today.

**Why can't we do this today?:**

Today, `fromSecretName` sets `secretArn === secretName`. This breaks several existing integrations, but can't be unset because it also *works* for some integrations.

The easiest way around that is deprecating `fromSecretName` and introducing `fromSecretNameV2` which conforms to the above behavior.

---

Thoughts? Counter proposals?

Comment (nija-at) [reply packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:245]: (discussed offline and here's where we landed)

The API is going to look like this -

```ts
export interface ISecret {
  readonly secretName: string;
  readonly secretPartialArn: string;

  // fromSecretName() and fromSecretPartialArn() throws an exception
  readonly secretFullArn: string;

  // This will return false only when a secret is imported using its name or partial ARN
  public trySecretFullArn(): boolean;

  // returns `trySecretFullArn() ?? secretPartialArn`;
  // so that 15 uses of `secretArn` across the CDK still works
  // and according to @njlynch either works just fine in most cases.
  readonly secretArn: string; 
}
```

Following this the `fromSecretName()` API will be deprecated and another `fromSecretNameV2()` introduced that does the correct thing. Also introduce, `fromSecretPartialArn()` and `fromSecretFullArn()`.

Comment (njlynch) [reply packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:245]: I am [not yet] aware of any use case for `secretPartialArn`, and I don't believe creating it for owned secrets is possible (there's no equivalent of `lastIndexOf` as a CloudFormation `Fn`). So that means either having `secretPartialArn` throw for owned secrets, having a `trySecretPartialArn`, or just removing it entirely. Of the three options, the latter seems cleanest.

So this is @nija-at's (modified) `ISecret`.
```ts
export interface ISecret {
  readonly encryptionKey?: kms.IKey;
  readonly secretName: string;
  readonly secretValue: SecretValue;
  // Behaves exactly as today. Will return a partial ARN from `fromSecretNameV2`.
  readonly secretArn: string; 
  // throws when used via fromSecretName() and fromSecretNameV2(),
  // returns secretArn otherwise.
  readonly secretFullArn: string;
  // return undefined when used via fromSecretName() and fromSecretNameV2(),
  // returns secretArn otherwise.
  readonly trySecretFullArn?: string;
}
```

And this is my proposal for comparison `ISecret`:
```ts
export interface ISecret {
  readonly encryptionKey?: kms.IKey;
  readonly secretName: string;
  readonly secretValue: SecretValue;
  // Behaves exactly as today. Will return a partial ARN from `fromSecretNameV2`.
  readonly secretArn: string;
  // True when used via `fromSecretNameV2`.
  readonly secretArnIsPartial: boolean;
}
```

File: packages/@aws-cdk/aws-codebuild/lib/project.ts [hunk 5]
```diff
@@ -956,14 +956,15 @@ export class Project extends ProjectBase {
...
       type: this.buildImage.type,
       image: this.buildImage.imageId,
       imagePullCredentialsType: imagePullPrincipalType,
-      registryCredential: this.buildImage.secretsManagerCredentials
+      registryCredential: secret
         ? {
           credentialProvider: 'SECRETS_MANAGER',
-          credential: this.buildImage.secretsManagerCredentials.secretArn,
+          credential: secret.secretFullArn ?? secret.secretName,
         }
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild/lib/project.ts:967]: Add a comment detailing why this is needed

**Review by eladb — APPROVED** [review]

**Comment by eladb** [comment]
Added do not merge

File: packages/@aws-cdk/aws-secretsmanager/lib/secret.ts [hunk 6]
```diff
@@ -305,14 +372,30 @@ export class Secret extends SecretBase {
...
+        throw new Error('cannot use `secretArn` with `secretCompleteArn` or `secretPartialArn`');
+      }
+      secretArn = attrs.secretArn;
+      secretArnIsPartial = false;
+    } else {
+      if ((attrs.secretCompleteArn && attrs.secretPartialArn) ||
+          (!attrs.secretCompleteArn && !attrs.secretPartialArn)) {
+        throw new Error('must use only one of `secretCompleteArn` or `secretPartialArn`');
+      }
+      [secretArn, secretArnIsPartial] = attrs.secretCompleteArn ? [attrs.secretCompleteArn, false] : [attrs.secretPartialArn!, true];
```
Comment (skinny85) [inline packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:389]: I wonder - if `secretCompleteArn` was passed, should we validate it with `arnIsComplete`, and throw if it doesn't match?

File: packages/@aws-cdk/aws-secretsmanager/lib/secret.ts [hunk 7]
```diff
@@ -297,6 +335,35 @@ export class Secret extends SecretBase {
     }(scope, id);
   }
 
+  /**
+   * Imports a secret by secret name.
+   * A secret with this name must exist in the same account & region.
+   * Replaces the deprecated `fromSecretName`.
+   */
+  public static fromSecretNameV2(scope: Construct, id: string, secretName: string): ISecret {
```
Comment (skinny85) [inline packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:343]: I know the names are tough here, but I don't love `fromSecretNameV2`. How about something like `fromSecretNameWithoutSuffix` / `fromSecretNameNoSuffix`?

**Review by skinny85 — COMMENTED** [review]
Looks great! 2 minor suggestions.

File: packages/@aws-cdk/aws-secretsmanager/lib/secret.ts (hunk 6 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:389]: And same in `fromSecretCompleteArn()`?

Comment (njlynch) [reply packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:392]: Yes, I originally had that, then removed it for fear of false positives from `fromSecretArn`; however, that was before I added the `arnIsComplete` check within `fromSecretArn` itself. Check re-added.

File: packages/@aws-cdk/aws-secretsmanager/lib/secret.ts (hunk 7 above)
Comment (njlynch) [reply packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:343]: Discussed that briefly (with Elad) but there is no reasonable use case for `fromSecretName**With**Suffix`, and `fromSecretNameWithoutSuffix` seems to imply that `fromSecretName` _should_ be used if you have the suffix. Neither name is good, but I feel just calling it 'V2' makes it clear it's an improved version of the former, rather than a version skewed toward a particular use case.
