### PR TITLE
fix(core): adding warnings to alert when properties will be overwritten

### LINKED ISSUE #32468: CustomResource: ServiceToken clobbered by properties
### Describe the bug

The [properties](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.CustomResource.html#properties) construct props implies that all the properties are sent to the lambda. However if a key `ServiceToken` is added to the properties object it will set the service token for the custom resource, and even overwrite the value provided in the [seviceToken](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.CustomResource.html#servicetoken) constructor prop.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

The service token of the custom resource should always be the value provided in serviceToken

### Current Behavior

The ServiceToken property of the custom resource is overwritten with the value in the property.

### Reproduction Steps

# Warning
Deploying this stack will fail and take 2 hours too resolve due to custom resource timeout, Only synth is needed to verify the bug.
## Create a basic typescript cdk app,
```
mkdir testApp
cd testApp
cdk init app --language=typescript
```
## update ./bin/test_app.ts 
```
#!/usr/bin/env node
import * as cdk from 'aws-cdk-lib'
import { Code, Function, Runtime } from 'aws-cdk-lib/aws-lambda';
import { Provider } from 'aws-cdk-lib/custom-resources';
import { Construct } from 'constructs';
const app = new cdk.App();
export class TestCdkAppStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
Function
    const myFunction = new Function(this, 'MyFunction', {
      runtime: Runtime.NODEJS_18_X,
      handler: 'index.handler',
      code: Code.fromInline(`
        exports.handler = async (event) => {
          return(JSON.stringify(event, undefined, 2));
        };
      `),
    });
    const provider = new Provider(this, 'Provider', {
      onEventHandler: myFunction,
    });
    const invoker = new cdk.CustomResource(this, 'Invoker', {
      serviceToken: provider.serviceToken,
      properties: {
        ServiceToken: myFunction.functionArn
      },
    });
  }
}
new TestCdkAppStack(app, 'TestCdkAppStack', {

});
```
### Run CDK synth and observe the cdk.out/TestCdkAppStack.template.json. See that the invoker has the service token of the lambda function instead of the provider. 

```
  "Invoker": {
   "Type": "AWS::CloudFormation::CustomResource",
   "Properties": {
    "ServiceToken": {
     "Fn::GetAtt": [
      "MyFunction3BAA72D1",
      "Arn"
     ]
    }
   },
   "UpdateReplacePolicy": "Delete",
   "DeletionPolicy": "Delete",
   "Metadata": {
    "aws:cdk:path": "TestCdkAppStack/Invoker/Default"
    }
```

### Comment out the `properties` attribute of the custom resource and synth again. Observe that it is now correctly has the service token of the provider,
```
    const invoker = new cdk.CustomResource(this, 'Invoker', {
      serviceToken: provider.serviceToken,
      // properties: {
      //   ServiceToken: myFunction.functionArn
      // },
    });
```
```
  "Invoker": {
   "Type": "AWS::CloudFormation::CustomResource",
   "Properties": {
    "ServiceToken": {
     "Fn::GetAtt": [
      "ProviderframeworkonEvent83C1D0A7",
      "Arn"
     ]
    }
   },
   "UpdateReplacePolicy": "Delete",
   "DeletionPolicy": "Delete",
   "Metadata": {
    "aws:cdk:path": "TestCdkAppStack/Invoker/Default"
   }
  },
```

### Possible Solution

properties object overwrites the invokers base properties. Potentially provide a warning of this.

### Additional Information/Context

_No response_

### CDK CLI Version

2.171.1 (build a95560c)

### Framework Version

_No response_

### Node.js Version

v20.12.2

### OS

linux

### Language

TypeScript

### Language Version

5.6.3

### Other information

_No response_

### PR DESCRIPTION
**Pull request by IkeNefcy**
### Issue #

Closes #32468

### Reason for this change

When using a custom resource, the values for `serviceToken` and `serviceTimeout` are added to the construct prop `properties` during the synth. Thus passing those values through to the lambda. The issue is that these values can be overwritten if you also include the exact keys in your own properties argument. 

So if I include `serviceToken`, which is a required arg, then I set properties 
```
properties: {
  ServiceToken: 'something else',
},
```

the value of `serviceToken` is set to `ServiceToken`, then my property I wrote to `ServiceToken` takes over and replaces the value with my own. 

This change is to add a warning to the user so they can understand that what they are doing is overwriting that key, as well as add some more detailed flavor text to the properties and readme to help convey this.

### Description of changes

Previously the props like `serviceToken` were being written directly to properties, along with the user provided properties broken out with `...` notation. 

I moved the automatically added props out of this 

```
    const constructPropertiesPassed = {
      ServiceToken: props.serviceToken,
      ServiceTimeout: props.serviceTimeout?.toSeconds().toString(),
    };

    const hasCommonKeys = Object.keys(properties).some(key => key in constructPropertiesPassed);

    if (hasCommonKeys) {
      Annotations.of(this).addWarningV2('@aws-cdk/core:customResourcePropDuplicate', `CustomResource properties should not contain keys that are automatically added by the CDK. Found: ${Object.keys(properties).filter(key => key in constructPropertiesPassed)}`);
    }

    this.resource = new CfnResource(this, 'Default', {
      type,
      properties: {
        ...constructPropertiesPassed,
        ...properties,
      },
    });
```

This allowed for a simple comparison between the 2 dicts, which allows for the warning to be initiated from. 

### Description of how you validated changes

I added a test to check if this warning is being generated. 

I did not change any integs because the actual synth in the end is the exact same as before. 

### Checklist
- [X] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by IkeNefcy** [comment]
Exemption Request : No integs need to be changed, this is just adding a warning test during synth. As far as I'm aware this is not something we can test with integs. The actual Synth'ed template should be the same as before.

File: packages/aws-cdk-lib/core/lib/custom-resource.ts [hunk 1]
```diff
@@ -54,6 +55,8 @@ export interface CustomResourceProps {
    *   serviceToken: myTopic.topicArn,
    * });
    * ```
+   *
+   * serviceToken is passed to properties with key "ServiceToken"
```
Comment (samson-keung) [inline packages/aws-cdk-lib/core/lib/custom-resource.ts:59]:
```suggestion
   * Maps to [ServiceToken](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-customresource.html#cfn-cloudformation-customresource-servicetoken) properties for the `AWS::CloudFormation::CustomResource` resource
```

This is a nit but would the above reads better? I think the links would help. Same goes to the `serviceTimeout` code comment (line 68 and 69).

File: packages/aws-cdk-lib/core/lib/custom-resource.ts [hunk 2]
```diff
@@ -154,11 +163,21 @@ export class CustomResource extends Resource {
...
 
+    const constructPropertiesPassed = {
+      ServiceToken: props.serviceToken,
+      ServiceTimeout: props.serviceTimeout?.toSeconds().toString(),
+    };
+
+    const hasCommonKeys = Object.keys(properties).some(key => key in constructPropertiesPassed);
+
+    if (hasCommonKeys) {
+      Annotations.of(this).addWarningV2('@aws-cdk/core:customResourcePropDuplicate', `CustomResource properties should not contain keys that are automatically added by the CDK. Found: ${Object.keys(properties).filter(key => key in constructPropertiesPassed)}`);
```
Comment (samson-keung) [inline packages/aws-cdk-lib/core/lib/custom-resource.ts:174]:
```suggestion
      Annotations.of(this).addWarningV2('@aws-cdk/core:customResourcePropConflict', `The following keys will be overwritten as they exist in the 'properties' prop. Keys found: ${Object.keys(properties).filter(key => key in constructPropertiesPassed)}`);
```

**Review by samson-keung — CHANGES_REQUESTED** [review]
A few minor comments on the wording. Thank you for making the change.

File: packages/aws-cdk-lib/core/lib/custom-resource.ts (hunk 2 above)
Comment (IkeNefcy) [reply packages/aws-cdk-lib/core/lib/custom-resource.ts:174]: Makes sense, will change tomorrow

File: packages/aws-cdk-lib/core/lib/custom-resource.ts (hunk 1 above)
Comment (IkeNefcy) [reply packages/aws-cdk-lib/core/lib/custom-resource.ts:59]: I agree yeah, help with clarity

File: packages/aws-cdk-lib/core/lib/custom-resource.ts [hunk 3]
```diff
@@ -62,13 +65,19 @@ export interface CustomResourceProps {
...
    * @default Duration.seconds(3600)
    */
   readonly serviceTimeout?: Duration;
 
   /**
    * Properties to pass to the Lambda
    *
+   * Some propery values are passed into this dictionary automatically.
+   * Please keep in mind that these keys should not be repeated in this prop or they will be overwritten.
+   * E.g. `ServiceToken`, `ServiceTimeout`
```
[the remark this answers is not in the document]
Comment (samson-keung) [reply packages/aws-cdk-lib/core/lib/custom-resource.ts:79]: You are right. I thought it is the other way around where lower case will overwrite. Edited the code suggestion above.

[the remark this answers is not in the document]
Comment (IkeNefcy) [reply packages/aws-cdk-lib/core/lib/custom-resource.ts]: Added

File: packages/aws-cdk-lib/core/lib/custom-resource.ts (hunk 1 above)
Comment (IkeNefcy) [reply packages/aws-cdk-lib/core/lib/custom-resource.ts]: Added

**Review by samson-keung — APPROVED** [review]
LGTM. Thanks!
