### PR TITLE
fix(autoscaling): can't use `MathExpression` in `scaleOnMetric`

### LINKED ISSUE #5776: AutoScalingGroup.scaleOnMetric with MathExpression as metric created invalid template
When attempting to create an Autoscaling Group that uses a Math Expression as the scaling metric, CDK will generate a template that is rejected by CloudFormation. 

### Reproduction Steps

Starting from the Application Load Balancer Typescript example (https://github.com/aws-samples/aws-cdk-examples/blob/master/typescript/application-load-balancer/index.ts), add the following:

```
import { MathExpression } from '@aws-cdk/aws-cloudwatch';
```

```
asg.scaleOnMetric('MyScalingMetric', {
      metric: new MathExpression({
        expression: 'activeConnections / processedBytes',
        usingMetrics: {
          activeConnections: lb.metricActiveConnectionCount({
            statistic: 'avg',
            period: Duration.minutes(5)
          }),
          processedBytes: lb.metricProcessedBytes({
            statistic: 'avg',
            period: Duration.minutes(5)
          })
        }
      }),
      adjustmentType: AdjustmentType.CHANGE_IN_CAPACITY,
      scalingSteps: [
        { change: -1, lower: 0, upper: 49 },
        { change: 0, lower: 50, upper: 99 },
        { change: 1, lower: 100 }
      ]
    });
```

(I'm not suggesting that this is a useful metric! It's just an example)
run cdk stack synth to generate the stack.
Note in the generated output, the generated `ASGMyScalingMetricUpperAlarm` `ASGMyScalingMetricLowerAlarm` both include the `Period` property, which according to the docs, should not be supplied for Math expression metrics: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html#cfn-cloudwatch-alarms-period

When deploying the stack, the upper and lower alarms will fail to be created with an error.

### Error Log

```
Period should not be set if list of Metrics is set. (Service: AmazonCloudWatch; Status Code: 400; Error Code: ValidationError; Request ID: 869ad658-bae4-4006-b93f-5bd085eeaa17)
```
--

### Environment

  - **CLI Version      : 1.20.0
  - **Framework Version: 1.20.0
  - **OS               : MacOSX
  - **Language         : Typescript

### Other

- Looks like the period is hard-coded in  https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-autoscaling/lib/step-scaling-policy.ts#L107
- Editing the generated template to remove the `Period` property from the alarms resolves the problem.
--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Commit Message
fix(autoscaling): can't use `MathExpression` in `scaleOnMetric`

It was not possible to use `MathExpression` objects in AutoScaling,
because the `Alarm` interface has a bug: it takes "override" arguments
like "period" and "statistic" that could and should have already been
encoded into the `Metric` object passed to the alarm.

Subsequently, AutoScaling used this ill-advised feature to force the
period of metrics to 1 minute. This caused an invalid render for math
expressions and was probably ill-advised to begin with. We should be
respecting the customer's period on the metric they pass in.

Fixes #5776.

BREAKING CHANGE: AutoScaling by using `scaleOnMetric` will no longer
force the alarm period to 1 minute, but use the period from the Metric
object instead (5 minutes by default). Use `metric.with({ period:
Duration.minute(1) })` to create a high-frequency scaling policy.

### CODE REVIEW

File: packages/@aws-cdk/aws-cloudwatch/lib/metric.ts [hunk 1]
```diff
@@ -672,7 +678,7 @@ function changeAllPeriods(metrics: Record<string, IMetric>, period: cdk.Duration
  * both implementations of IMetric have a `period` member that contains that particular
```
Comment (MrArnoldPalmer) [inline packages/@aws-cdk/aws-cloudwatch/lib/metric.ts]: Minor nit, is this doc paragraph still relevant?
