### PR TITLE
fix(cloudwatch): can't override Alarm statistic with percentile

### LINKED ISSUE #7341: CDK generates alarm with both ExtendedStatistic and Statistic when percentile is used
description of the bug: when I use percentile in Statistic, alarm is generated with both Statistic and ExtendedStatistic.

### Reproduction Steps

CDK code: 

```
function getAlarm(construct: cdk.Construct, id: string, alarmName: string, metricName: string, threshold: number, alarmDescription: string, statistic: string): Alarm {
            return new Alarm(construct, id, {
                alarmName,
                alarmDescription,
                metric: new Metric({
                    namespace: 'AWS/ES',
                    metricName,
                    dimensions: {
                        DomainName: esDomain.domainName,
                        ClientId: account
                    }
                }),
                threshold,
                statistic,
                evaluationPeriods: 3,
                period: cdk.Duration.minutes(5),
                comparisonOperator: ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD,
                treatMissingData: TreatMissingData.NOT_BREACHING
            });
        }

            getAlarm(this, 'ES_DOMAIN_HIGHWRITELATENCY_ALARM', 'ES_DOMAIN_HIGHWRITELATENCY', 'WriteLatency', 2/* seconds */, 'Alarm for when the ES cluster has high write latency', 'p90'),

```

Generated template:

```
"ESDOMAINHIGHWRITELATENCYALARM8819DAF6": {
        "Type": "AWS::CloudWatch::Alarm",
        "Properties": {
          "ComparisonOperator": "GreaterThanOrEqualToThreshold",
          "EvaluationPeriods": 3,
          "AlarmDescription": "Alarm for when the ES cluster has high write latency",
          "AlarmName": "ES_DOMAIN_HIGHWRITELATENCY",
          "Dimensions": [
            {
              "Name": "ClientId",
              "Value": "453055088523"
            },
            {
              "Name": "DomainName",
              "Value": "contents-simonyu"
            }
          ],
          "ExtendedStatistic": "p90",
          "MetricName": "WriteLatency",
          "Namespace": "AWS/ES",
          "Period": 300,
          "Statistic": "Average",
          "Threshold": 2,
          "TreatMissingData": "notBreaching"
        },
        "Metadata": {
          "aws:cdk:path": "Monitoring-Dev-simonyu/ES_DOMAIN_HIGHWRITELATENCY_ALARM/Resource"
        }
      },
```

### Environment

  - **CLI Version      : 1.23.0
  - **Framework Version: 1.23.0
  - **OS               : MacOS & Linux
  - **Language         : TypeScript

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
### Commit Message
fix(cloudwatch): can't override Alarm statistic with percentile

A simple statistic of a `Metric` couldn't be overridden with a
percentile statistic while creating an `Alarm`.

Because of the way the objects were combined, both `Statistic`
and `ExtendedStatistic` properties would be present in the resulting
object, which is an error for CloudWatch.

Fixes #7341.
### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-cloudwatch/lib/alarm.ts [hunk 1]
```diff
@@ -159,6 +159,21 @@ export class Alarm extends Resource implements IAlarm {
...
+    if (props.period) {
+      metricProps.period = props.period.toSeconds();
+    }
+    if (props.statistic) {
+      // Will overwrite both fields if present
+      Object.assign(metricProps, {
+        statistic: renderIfSimpleStatistic(props.statistic),
+        extendedStatistic: renderIfExtendedStatistic(props.statistic),
+      });
+    }
```
Comment (nija-at) [inline packages/@aws-cdk/aws-cloudwatch/lib/alarm.ts:175]: These `if`s are technically not required - 

```suggestion
    metricProps.period = props.period?.toSeconds();
    Object.assign(metricProps, {
      statistic: renderIfSimpleStatistic(props.statistic),
      extendedStatistic: renderIfExtendedStatistic(props.statistic),
    });
```

File: packages/@aws-cdk/aws-cloudwatch/test/test.alarm.ts [hunk 2]
```diff
@@ -105,6 +105,7 @@ export = {
       MetricName: 'Metric',
       Namespace: 'CDK/Test',
       Period: 300,
+      Statistic: ABSENT,
```
Comment (nija-at) [inline packages/@aws-cdk/aws-cloudwatch/test/test.alarm.ts:108]: Rather than modify an existing test, could we add a unit test focused on this particular issue - 

```ts
'only one of Statistic or ExtendedStatistic are present in the Alarm'(test:Test) {
}
```

File: packages/@aws-cdk/aws-cloudwatch/lib/alarm.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-cloudwatch/lib/alarm.ts:175]:
```
    metricProps.period = props.period?.toSeconds();
```

It's not the same. This will unconditionally overwrite `metricProps.period` with `undefined`, whereas the other one would overwrite `metricProps.period` only if there was a value to set.

Same for the other one.

File: packages/@aws-cdk/aws-cloudwatch/test/test.alarm.ts (hunk 2 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-cloudwatch/test/test.alarm.ts:108]: Disagree. The test should always have been this, but at the time it was written we didn't have the capacity to express `ABSENT` yet.

Doesn't make sense to me to have 2 tests for the same behavior, that a percentile statistic leads to `ExtendedStatistic` and ONLY `ExtendedStatistic` being set.

File: packages/@aws-cdk/aws-cloudwatch/lib/alarm.ts (hunk 1 above)
Comment (nija-at) [reply packages/@aws-cdk/aws-cloudwatch/lib/alarm.ts:175]: Gah.. you're right!

File: packages/@aws-cdk/aws-cloudwatch/test/test.alarm.ts (hunk 2 above)
Comment (nija-at) [reply packages/@aws-cdk/aws-cloudwatch/test/test.alarm.ts:108]: Is there another test somewhere that verifies `Statistic` property is valid and that `ExtendedStatistic` is `ABSENT`?

Comment (rix0rrr) [reply packages/@aws-cdk/aws-cloudwatch/test/test.alarm.ts:109]: There is now.
