### PR TITLE
fix(apigatewayv2): integration class does not render an integration resource

### LINKED ISSUE #13213: (apigatewayv2): AddRoutes caches lambda integrations incorrectly
When adding multiple routes with lambda integrations on a single http api, all routes end up sharing the same integration, instead of being correctly bound to the lambda which was provided.

### Reproduction Steps

```
httpApi.AddRoutes({
  path: '/service1',
  integration: new LambdaProxyIntegration({
    handler: lambda1,
  })
});
httpApi.AddRoutes({
  path: '/service2',
  integration: new LambdaProxyIntegration({
    handler: lambda2,
  })
});
```

### What did you expect to happen?

Two routes with their own integrations created

### What actually happened?

Correct routes/lambda permissions, but both routes share the same lambda integration (the first one which was added)

### Environment

  - **CDK CLI Version  : 1.90.1**
  - **Framework Version: 1.90.1**
  - **Node.js Version: 14.7.0**
  - **OS               : Windows**
  - **Language (Version): dotnetcore (3.1)**

### Other

It appears that the Lambda arn doesn't become part of the cache key?
https://github.com/aws/aws-cdk/blob/v1.90.1/packages/@aws-cdk/aws-apigatewayv2/lib/http/api.ts#L281

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by nija-at**
Routes on APIGateway V2 can integrate with different backends. This is
achieved by creating the CFN resource `AWS::ApiGatewayV2::Integration`
that is then referenced in the resource for the Route.

Currently, the `IHttpRouteIntegration` (and `IWebSocketRouteIntegration`)
interface represents a unique backend that a route can integrate with,
using the CDK "bind" pattern.
An integration can be bound to any number of routes but should be
rendered into a single instance of `AWS::ApiGatewayV2::Integration`
resource.
To achieve this currently, the `HttpApi` (and `WebSocketApi`) class
holds a cache of all integrations defined against its routes.

This is the wrong level of caching and causes a number of problems.

1. We rely on the configuration of the `AWS::ApiGateway::Integration`
   resource to determine if one already exists.
   This means that two instances of `IHttpRouteIntegration` can result
   in rendering only one instance of `AWS::ApiGateway::Integration`
   resource.

   Users may want to intentionally generate multiple instances of
   `AWS::ApiGateway::Integration` classes with the same configuration.
   Taking away this power with CDK "magic" is just confusing.

2. Currently, we allow using the same instance of
   `IHttpRouteIntegration` (or `IWebSocketRouteIntegration`) to be bound
   to routes in different `HttpApi`. When bound to the route, the CDK
   renders an instance of `AWS::ApiGatewayV2::Integration` for each API.

   This is another "magic" that has the potential for user confusion and
   bugs.

The solution is to KeepItSimple™.

Remove the API level caching and simply cache at the level of each
integration. This ensures that each instance of `HttpRouteIntegration`
(previously `IHttpRouteIntegration`) renders to exactly one instance of
`AWS::ApiGatewayV2::Integration`.

Disallow using the same instance of `HttpRouteIntegration` across
different instances of `HttpApi`.

fixes #13213

BREAKING CHANGE: The interface `IHttpRouteIntegration` is replaced by
the abstract class `HttpRouteIntegration`.
* **apigatewayv2:** The interface `IWebSocketRouteIntegration` is now
  replaced by the abstract class `WebSocketRouteIntegration`.
* **apigatewayv2:** Previously, we allowed the usage of integration
  classes to be used with routes defined in multiple `HttpApi` instances
  (or `WebSocketApi` instances). This is now disallowed, and separate
  instances must be created for each instance of `HttpApi` or
  `WebSocketApi`.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by nija-at** [comment]
cc @ayush987goyal

File: packages/@aws-cdk/aws-apigatewayv2/lib/http/integration.ts [hunk 1]
```diff
@@ -191,11 +192,46 @@ export interface HttpRouteIntegrationBindOptions {
...
+        method: config.method,
+        connectionId: config.connectionId,
+        connectionType: config.connectionType,
+        payloadFormatVersion: config.payloadFormatVersion,
+        secureServerName: config.secureServerName,
+        parameterMapping: config.parameterMapping,
+      });
+
+      function hash(x: any) {
+        const stringifiedConfig = JSON.stringify(Stack.of(options.scope).resolve(x));
```
Comment (otaviomacedo) [inline packages/@aws-cdk/aws-apigatewayv2/lib/http/integration.ts:223]: I don't know if it can happen with `Stack`s (maybe `resolve()` takes care of that), but if the order of the fields change or if the presence or absence of whitespaces change, the hash will be different.

Comment (nija-at) [reply packages/@aws-cdk/aws-apigatewayv2/lib/http/integration.ts:223]: Whitespace is not a problem here. Ordering maybe. I'll check.

**Comment by ayush987goyal** [comment]
>  Previously, we allowed the usage of integration
classes to be used with routes defined in multiple HttpApi instances
(or WebSocketApi instances). This is now disallowed, and separate
instances must be created for each instance of HttpApi or
WebSocketApi.

@nija-at If I am remember correctly, this was an explicit request from customers. I think this is something that the API Gateway console allows to do. That is, a single integration can be bound to multiple APIs and is typically created out of the scope of an API. Do you think this change might create a problem with that and/or customer might ask for it again?

File: packages/@aws-cdk/aws-apigatewayv2/lib/http/integration.ts (hunk 1 above)
Comment (nija-at) [reply packages/@aws-cdk/aws-apigatewayv2/lib/http/integration.ts:223]: Ordering is actually a bigger problem here than I thought. 

This PR is effectively not changing the logic of hashing. Just moving it to a different place (previously `integration-cache.ts`).

Do you mind if I take this on as a follow up PR? Easier to review as well.

**Review by otaviomacedo — APPROVED** [review]

**Comment by nija-at** [comment]
> That is, a single integration can be bound to multiple APIs and is typically created out of the scope of an API

I don't know how that is possible since the `AWS::ApiGatewayV2::Integration` resource has `ApiId` as one of its properties.

**Comment by ayush987goyal** [comment]
> I don't know how that is possible since the AWS::ApiGatewayV2::Integration resource has ApiId as one of its properties.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-integration.html#cfn-apigatewayv2-integration-apiid

Yeah that's true. Maybe I am remembering something else. The change LGTM!

**Review by ayush987goyal — APPROVED** [review]
