### PR TITLE
fix(logs): move log destinations into 'aws-logs-destinations'

### LINKED ISSUE #2444: aws-logs-destinations
Centralize all ILogSubscriptionDestination integrations into a single module

### PR DESCRIPTION
**Pull request by rix0rrr**
In accordance with new guidelines, we're centralizing cross-service
integrations into their own package. In this case, centralizing
CloudWatch Logs Subscription Destinations into
@aws-cdk/aws-logs-destinations.

Fixes #2444.

BREAKING CHANGE: using a Lambda or Kinesis Stream as Log Subscription
Destination now requires an integration
object from the @aws-cdk/aws-logs-destinations package.

----

### Pull Request Checklist

* [ ] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [ ] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
  - __Design__: For significant features, design document added to `design` folder
* [ ] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [ ] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-logs-destinations/lib/kinesis.ts [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+/**
+ * Use a Kinesis stream as the destination for a log subscription
+ */
+export class KinesisDestination implements logs.ILogSubscriptionDestination {
+  constructor(private readonly stream: kinesis.IStream) {
+  }
+
+  public bind(scope: Construct, _sourceLogGroup: logs.ILogGroup): logs.LogSubscriptionDestination {
+    // Following example from https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/SubscriptionFilters.html#DestinationKinesisExample
+    // Create a role to be assumed by CWL that can write to this stream and pass itself.
```
Comment (eladb) [inline packages/@aws-cdk/aws-logs-destinations/lib/kinesis.ts]: What happens if we want to bind two Kinesis streams? We need only a single role,
Right?

File: packages/@aws-cdk/aws-logs-destinations/lib/lambda.ts [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+  constructor(private readonly fn: lambda.IFunction) {
+  }
+
+  public bind(_scope: Construct, logGroup: logs.ILogGroup): logs.LogSubscriptionDestination {
+    const arn = logGroup.logGroupArn;
+
+    const logSubscriptionDestinationPolicyAddedFor: string[] = [];
+
+    if (logSubscriptionDestinationPolicyAddedFor.indexOf(arn) === -1) {
+      // NOTE: the use of {AWS::Region} limits this to the same region, which shouldn't really be an issue,
```
Comment (eladb) [inline packages/@aws-cdk/aws-logs-destinations/lib/lambda.ts]: Note might be stale?

File: packages/@aws-cdk/aws-logs-destinations/lib/kinesis.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-logs-destinations/lib/kinesis.ts]: A single role with multiple statements, yes. The role belongs conceptually to the log group, I would say.

Aren't we better off return an array of policystatements to be added to the role, instead of the role itself?
