### PR TITLE
fix(aws-lambda): java - invalid cast for inline LambdaRuntime members

### LINKED ISSUE #504: java.lang.ClassCastException: software.amazon.awscdk.services.lambda.LambdaRuntime cannot be cast to software.amazon.awscdk.services.lambda.InlinableJavascriptLambdaRuntime
I was trying to create a new Lambda construct, it compiles well but when running cdk synth I'm getting this error: 
```

Exception in thread "main" java.lang.ExceptionInInitializerError
        at ...MyStack.<init>(MyStack.java:25)
        at ..MyApp.<init>(MyApp.java:11)
        at ..MyApp.main(MyApp.java:15)
Caused by: java.lang.ClassCastException: software.amazon.awscdk.services.lambda.LambdaRuntime cannot be cast to software.amazon.awscdk.services.lambda.InlinableJavascriptLambdaRuntime
        at software.amazon.awscdk.services.lambda.LambdaRuntime.<clinit>(LambdaRuntime.java:11)
        ... 3 more

``` 

The code is simply 

```

    Lambda lambda = new Lambda("MyLambda",
        LambdaProps.builder()
            .withCode(LambdaCode.file(...))
            .withHandler(...).withRuntime(LambdaRuntime.JAVA8)
            .build()
```

### PR DESCRIPTION
**Pull request by eladb**
TypeScript uses inference to determine if a cast to an interface is legal but strongly-typed languages like Java require that the down-casted class will explicitly implement the interface.

The JavaRuntime class has static members that are down-casted from JavaRuntime to a set of interfaces, to allow strong-typing of properties for various Lambda use cases. These down-casts fail in e.g. Java because JavaRuntime doesn't implement these interfaces explicitly.

We should add a compile-time check in jsii for such a use case (awslabs/jsii#140)

Fixes #504

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-lambda/lib/runtime.ts [hunk 1]
```diff
@@ -9,18 +9,18 @@ export interface LambdaRuntimeProps {
 /**
  * Lambda function runtime environment.
  */
-export class LambdaRuntime {
+export class LambdaRuntime implements InlinableLambdaRuntime, InlinableJavascriptLambdaRuntime {
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-lambda/lib/runtime.ts]: Shouldn't we just get rid of these interfaces? Nothing takes them as arguments, `Lambda` just takes a `LambdaRuntime` argument, and since `LambdaRuntime` already exposes the `supportsInlineCode` property that code is looking for, we're already done.

File: packages/@aws-cdk/aws-lambda/lib/runtime.ts [hunk 2]
```diff
@@ -9,18 +9,18 @@ export interface LambdaRuntimeProps {
...
     public static readonly NodeJS = new LambdaRuntime('nodejs', { supportsInlineCode: true }) as InlinableJavascriptLambdaRuntime;
-    // Using ``as InlinableLambdaRuntime`` because that calss cannot be defined just yet
+    // Using ``as InlinableLambdaRuntime`` because that class cannot be defined just yet
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-lambda/lib/runtime.ts]: Don't know if this still matters since we should probably just get rid of the interfaces, but if this crops up again, the way to solve it is thusly:

```
public static get NodeJS43(): InlinableJavascriptLambda {
    return new LambdaRuntime(...);
}
```

I.e., use a getter to temporally decouple type declaration from returned type. Types *can* use forward references, instantiations *can't* (because JavaScript).

Comment (rix0rrr) [reply packages/@aws-cdk/aws-lambda/lib/runtime.ts]: Oh I see, `InlinableJavascriptLambda` was probably intended to be a class, but because of the issue of getting it to declare properly we made it an interface?

Comment (rix0rrr) [reply packages/@aws-cdk/aws-lambda/lib/runtime.ts]: So intended was probably:

```ts
public static get NodeJS43(): LambdaRuntime {
    return new InlinableJavascriptLambda(...);
}
```

But anyway, a concrete `LambdaRuntime` class without interfaces probably suffices.

File: packages/@aws-cdk/aws-lambda/lib/runtime.ts (hunk 1 above)
Comment (eladb) [reply packages/@aws-cdk/aws-lambda/lib/runtime.ts]: It is currently used by the (soon to be removed) [`InlineJavaScriptLambda`](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda/lib/inline.ts#L71)

Comment (eladb) [reply packages/@aws-cdk/aws-lambda/lib/runtime.ts]: I want to do a bit of overhaul on Lambda soon, but in the meantime, I just want to unblock Java users from using Lambda.

Comment (rix0rrr) [reply packages/@aws-cdk/aws-lambda/lib/runtime.ts]: In that case I would feel better if you turned `InlineJavaScriptLambda` into a class and used the pattern I described in the other comments. That restores the type safety and still compiles properly:

```ts
    public static get NodeJS(): InlinableJavascriptLambdaRuntime {
        return new InlinableJavascriptLambdaRuntime('nodejs');
    }
```

I will approve in any case; do what you deem best.
