### PR TITLE
fix(route53): improve fromHostedZoneId error message

### LINKED ISSUE #8406: Issue when using "route53.HostedZone.fromHostedZoneId" Method
### Reproduction Steps

When trying to import an HostedZone with : 
`route53.HostedZone.fromHostedZoneId(this, 'MyHostedZone', 'ID123456789')`

### Error Log

I've that error when launching the Stack : 
`HostedZone.fromHostedZoneId doesn't support "zoneName"`

### Environment

  - **CLI Version      : CDK 1.42.1 (build a4797b4)**
  - **Framework Version: 6.14.5**
  - **Node.js Version: v12.15.0** 
  - **OS               : Linux**
  - **Language (Version): TypeScript** 

### Other

So, I've imported that way : 
`route53.HostedZone.fromHostedZoneAttributes(this, 'R53Domain', {hostedZoneId: 'MyID123456789', zoneName: 'Toto'})`

What's wrong with **fromHostedZoneId** Method ?

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by peterwoodworth**
fixes #8406 

----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-route53/lib/hosted-zone.ts [hunk 1]
```diff
@@ -222,14 +222,16 @@ export class PublicHostedZone extends HostedZone implements IPublicHostedZone {
   /**
    * Import a Route 53 public hosted zone defined either outside the CDK, or in a different CDK stack
    *
+   * Use when hosted zone ID is known. Hosted zone name becomes unavailable through this query.
```
Comment (corymhall) [inline packages/@aws-cdk/aws-route53/lib/hosted-zone.ts:225]:
```suggestion
   * Use when hosted zone ID is known. If a HostedZone is imported with this method the zoneName cannot be referenced. If the zoneName is needed then the HostedZone should be imported with fromPublicHostedZoneAttributes.
```

Maybe something like this (for the other instances as well)? I'll leave it up to you.

**Review by corymhall — APPROVED** [review]
