### PR TITLE
fix(lambda-nodejs): build fails on Windows

### LINKED ISSUE #8107: NodejsFunction broken on Windows
NodejsFunction doesn't work on Windows. There's some sort of problem with the way it translates Windows paths (backslash) to Docker.

### Reproduction Steps
`lib/my-stack.ts`:
```ts
export class MyStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    new NodejsFunction(this, 'handler');
  }
}
```
`lib/my-stack.handler.ts`:
```ts
export const handler = () => 'anything';
```

### Error Log

```
PS E:\p\break> yarn cdk synth                                                                                                                                                                                                  yarn run v1.22.4
warning package.json: No license field
$ cdk synth
Failed to build file at E:\p\break\lib\my-stack.handler.ts: Error: [Status 125] stdout:


stderr: docker: Error response from daemon: the working directory '\project\lib' is invalid, it needs to be an absolute path.
See 'docker run --help'.
Subprocess exited with error 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment

  - **CLI Version      :** 1.40.0
  - **Framework Version:** 1.40.0
  - **OS               :** Windows 10
  - **Language         :** TypeScript on NodeJS v12.1.0

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by jogold**
This is because the operations of [`path`](https://nodejs.org/api/path.html) are
OS specific. But for the container working directory and inside the container we
never want to use Windows style paths.

Fixes #8107

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-lambda-nodejs/lib/builder.ts [hunk 1]
```diff
@@ -111,11 +111,11 @@ export class Builder {
         '-v', `${this.options.projectRoot}:${containerProjectRoot}`,
         '-v', `${path.resolve(this.options.outDir)}:${containerOutDir}`,
         ...(this.options.cacheDir ? ['-v', `${path.resolve(this.options.cacheDir)}:${containerCacheDir}`] : []),
-        '-w', path.dirname(containerEntryPath),
+        '-w', path.dirname(containerEntryPath).replace(/\\/g, '/'), // Always use POSIX paths in the container
```
Comment (eladb) [inline packages/@aws-cdk/aws-lambda-nodejs/lib/builder.ts:114]: sounds like something we should take to the bundling PR, no?

Comment (jogold) [reply packages/@aws-cdk/aws-lambda-nodejs/lib/builder.ts:114]: In #7898 we explicitly ask for a `workingDirectory` (optional prop) so the user knows that it's a POSIX style path?

Here we had to calculate it using `path` logic because we are mounting `projectRoot` but want to work closer to the entry file.
