### PR TITLE
fix(diff): handle YAML short-forms like '!GetAtt' in diff

### LINKED ISSUE #6537: cdk diff (and cdk deploy) complains about short functions in existing yaml
I have a stack deployed with an authored YAML template that uses short functions like `!GetAtt`. I am trying to convert this template to CDK, but `cdk diff` strips them.

### Reproduction Steps

1. Deploy a stack with a YAML file that uses !GetAtt authored outside of CDK
2. Re-create that stack using CDK, generating the same `Fn::GetAtt` references
3. Run `cdk diff my-stack`

### Error Log

(node:2590) YAMLWarning: The tag !GetAtt is unavailable, falling back to tag:yaml.org,2002:str
(node:2590) YAMLWarning: The tag !Ref is unavailable, falling back to tag:yaml.org,2002:str
(node:2590) YAMLWarning: The tag !Ref is unavailable, falling back to tag:yaml.org,2002:str
(node:2590) YAMLWarning: The tag !GetAtt is unavailable, falling back to tag:yaml.org,2002:str
(node:2590) YAMLWarning: The tag !ImportValue is unavailable, falling back to tag:yaml.org,2002:str
(node:2590) YAMLWarning: The tag !Ref is unavailable, falling back to tag:yaml.org,2002:str
(node:2590) YAMLWarning: The tag !GetAtt is unavailable, falling back to tag:yaml.org,2002:str
(node:2590) YAMLWarning: The tag !Sub is unavailable, falling back to tag:yaml.org,2002:str
(node:2590) YAMLWarning: The tag !Ref is unavailable, falling back to tag:yaml.org,2002:str
(node:2590) YAMLWarning: The tag !ImportValue is unavailable, falling back to tag:yaml.org,2002:str
(node:2590) YAMLWarning: The tag !ImportValue is unavailable, falling back to tag:yaml.org,2002:str
(node:2590) YAMLWarning: The tag !FindInMap is unavailable, falling back to tag:yaml.org,2002:seq

The !Fn is stripped, so the diff acts as if `Prop: !GetAtt Thing.myAtt` is actually the string `Prop: Thing.myAtt`

```
 │      [-]     "value": "MyKey.SecretAccessKey",
 │      [+]     "value": {
 │      [+]       "Fn::GetAtt": [
 │      [+]         "MyKey",
 │      [+]         "SecretAccessKey"
 │      [+]       ]
 │      [+]     },
```

### Environment

  - **CLI Version      :1.26.0**
  - **Framework Version:**
  - **OS               :MacOS**
  - **Language         :Typescript**

### Other

Here's my workaround for this.

Use cfn-flip to flip it to JSON:

```
aws cloudformation get-template --stack-name my-stack | jq ".TemplateBody" -r | cfn-flip -i yaml > cdk.out/my-stack.orig.json
```

Then, use `cdk diff` to compare to that:

```
 diff my-stack --template ./cdk.out/my-stack.orig.json
```

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by skinny85**
CloudFormation allows using short-form versions of intrinsic functions like `!GetAtt`.
We handled them correctly in the `@aws-cdk/cloudformation-include` module,
so extract that logic to a common package,
and use it from the CLI in the `diff` command as well.

Fixes #6537

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by skinny85** [comment]
I wasn't sure which package should have the common YAML-handling logic. I decided on `@aws-cdk/cx-api`, but it's possible it should be somewhere else.

File: packages/@aws-cdk/cx-api/lib/yaml.ts [hunk 1]
```diff
@@ -0,0 +1,95 @@
+import * as yaml from 'yaml';
```
Comment (rix0rrr) [inline packages/@aws-cdk/cx-api/lib/yaml.ts:1]: I'm not sure I support putting this stuff in `cx-api`. Doesn't seem to belong there.

I guess a new library?

**Review by rix0rrr — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/cx-api/lib/yaml.ts (hunk 1 above)
Comment (skinny85) [reply packages/@aws-cdk/cx-api/lib/yaml.ts]: Done. I called it `@aws-cdk/yaml-cfn`.

**Review by rix0rrr — APPROVED** [review]
