### PR TITLE
fix(cloudfront): make long function name deterministic

### LINKED ISSUE #20017: (cloudfront): (cloudfront function generated name is not deterministic and will change between synthesis)
### Describe the bug

When using `cloudfront.Function` without specifying the function name, the construct `cloudfront.Function` will generate a name automatically.  However this generated function name will change from time to time between synthesis due to the name truncated to a fixed length with a region token prefix in it. This change of name caused deployment failure when deploying onto an existing stack. 

For example, with below code in a stack named `CdkIssueWithALongNameStack`
```
    new cloudfront.Function(this, "MyCloudFrontFunction", {
      code: cloudfront.FunctionCode.fromInline(""),
    });
```

Running `cdk synth` multiple times, It can be observed that during some runs, in the synthesised CloudFormation template, we can find below. Please note the function name is  `CdkIssueWtackMyCloudFrontFunction6157953B`.

```
  "MyCloudFrontFunction18D9B9FD": {
   "Type": "AWS::CloudFront::Function",
   "Properties": {
    "Name": {
     "Fn::Join": [
      "",
      [
       {
        "Ref": "AWS::Region"
       },
       "CdkIssueWtackMyCloudFrontFunction6157953B"
      ]
     ]
    },
```
However, some other runs, the name will change to `CdkIssueWitackMyCloudFrontFunction6157953B`. Note the additional `i` after `CdkIssueW`. 

This name change of the cloudfront function will cause failure of deployment on an existing stack as CDK will report error like:  
```
Resource of type ‘AWS::CloudFront::Function’ with identifier ‘CdkIssueWtackMyCloudFrontFunction6157953B’ was not found.
```

### Expected Behavior

The automatically generated function name should remain the same during multiple cdk synth.

### Current Behavior

The name changes due to the following reason:

The following code snippet is how `cloudfront.Function` generate its function name if the name is not specified in the props. 

```
  private generateName(): string {
    const name = Stack.of(this).region + Names.uniqueId(this);
    if (name.length > 64) {
      return name.substring(0, 32) + name.substring(name.length - 32);
    }
    return name;
  }
}
```
https://github.com/aws/aws-cdk/blob/9487b39d6da4ab7efd884c3a8379b03e317786b9/packages/%40aws-cdk/aws-cloudfront/lib/function.ts#L178

it added `Stack.of(this).region` in front of the unique id of this construct and then took the first 32 chars and then last 32 chars if the string is longer than 64 chars, and concatenated these two parts together to form the name of the function. However, the region added in front of the name is still a token at this time, so the name string became: 
 
`${Token[AWS.Region.7]}CdkIssueWithALongNameStackMyCloudFrontFunction6157953B`

This string is then sent through `name.substring(0, 32) + name.substring(name.length - 32);` and resulted in two parts:  

`${Token[AWS.Region.7]}CdkIssueWi` and `tackMyCloudFrontFunction6157953B` and then they are concatenated together to make the name  `${Token[AWS.Region.7]}CdkIssueWitackMyCloudFrontFunction6157953B`, which eventually became the name in the CloudFormation template.

However, the region token string could be different every time cdk synth runs, sometimes, the region token will have a two digits value like 11 instead of 7, then the name above will be like:

`${Token[AWS.Region.11]}CdkIssueWithALongNameStackMyCloudFrontFunction6157953B`, which run through `name.substring(0, 32) + name.substring(name.length - 32);` and resulted in two parts: 

`${Token[AWS.Region.11]}CdkIssueW` and `tackMyCloudFrontFunction6157953B` and then they are concatenated together make the name `${Token[AWS.Region.11]}CdkIssueWtackMyCloudFrontFunction6157953B`.  This name is different from the name when the number in region token is one digit, and missed that `i`. 

Since the number in the region token is unpredictable so after a few rounds of cdk synth command, the name will change between those two results.

### Reproduction Steps

1. Create a cdk sample app  with command `cdk init sample-app --language=typescript`.
2. Add below into `lib/<app name>-stack.ts` 
```
import * as cloudfront from "aws-cdk-lib/aws-cloudfront";

...
// in the constructor, add below at the end

    new cloudfront.Function(this, "MyCloudFrontFunction", {
      code: cloudfront.FunctionCode.fromInline(""),
    });
```

3. add below into `bin/<app name>.ts`. Make sure the stack name is long enough
```
#!/usr/bin/env node
import { Construct } from "constructs";
import * as cloudfront from "aws-cdk-lib/aws-cloudfront";
import { Aspects } from "aws-cdk-lib";

class TestAspect implements cdk.IAspect {
  public visit(construct: Construct) {
    if (construct instanceof cloudfront.CfnFunction) {
      console.log(construct.name);
    }
  }
}

const app = new cdk.App();
Aspects.of(app).add(new TestAspect());
new CdkissueStack(app, "CdkIssueWithALongNameStack");
```
4. build with `npm run build` and run cdk synth with `npx cdk synth -q`, the following content will be printed out during the `cdk synth`
```
$ npx cdk synth -q
${Token[AWS.Region.10]}CdkIssueWtackMyCloudFrontFunction6157953B
```

5. when seeing this, check the generated CloudFormation Template in `cdk.out` and search for `AWS::CloudFront::Function` resource and there should be something like below:  

```
  "MyCloudFrontFunction18D9B9FD": {
   "Type": "AWS::CloudFront::Function",
   "Properties": {
    "Name": {
     "Fn::Join": [
      "",
      [
       {
        "Ref": "AWS::Region"
       },
       "CdkIssueWtackMyCloudFrontFunction6157953B"
      ]
     ]
    },
```
Write down the name

6. run `npx cdk synth -q` multiple times until you can see the number in the region token is one digit
```
$ npx cdk synth -q
${Token[AWS.Region.8]}CdkIssueWitackMyCloudFrontFunction6157953B
```
then check the generated CloudFormation template in `cdk.out`, and search for `AWS::CloudFront::Function` resource and you can see the name of the resource became `CdkIssueWitackMyCloudFrontFunction6157953B` with an additional `i`.

### Possible Solution

The quoted code snippet below are from  `cloudfront.Function` construct, instead of adding the region token into the name string first, it could perform the name truncating and concatenation without adding the region token in front of it, and then add the region as prefix after to make the new name. So the concatenated name will be stable and won't change due to the different length of the region token (the digits of the number in it) 

Below is one possible fix and it might need further validation:

```
  private generateName(): string {
    // currently the longest region name is ap-southeast-2 which is 14 chars
    const maxLengthOfRegionName = 14;
    // CloudFront Function has maximum 64 chars limit on function name
    const maxLengthOfName = 64 -  maxLengthOfRegionName;
    const longName = Names.uniqueId(this);
    if (longName.length > maxLengthOfName)) {
      const partLength = Math.floor(maxLengthOfName/2)
      return Stack.of(this).region  + longName.substring(0, partLength) + longName.substring(name.length - partLength);
    }
    return Stack.of(this).region  + longName;
  }
```

Current code in `cloudfront.Function`:
```
  private generateName(): string {
    const name = Stack.of(this).region + Names.uniqueId(this);
    if (name.length > 64) {
      return name.substring(0, 32) + name.substring(name.length - 32);
    }
    return name;
  }
}
```
https://github.com/aws/aws-cdk/blob/9487b39d6da4ab7efd884c3a8379b03e317786b9/packages/%40aws-cdk/aws-cloudfront/lib/function.ts#L178

### Additional Information/Context

_No response_

### CDK CLI Version

2.20.0 (build 738ef49)

### Framework Version

_No response_

### Node.js Version

v14.18.2

### OS

macOS Monterey 12.2.1

### Language

Typescript

### Language Version

Typescript(3.9.7)

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Leo10Gama**
### Issue # (if applicable)

Closes #20017 as well as #15523 and #28629 

### Reason for this change

Due to the way function names are generated using token strings with either single- or double-digit numbers, longer function names can be truncated differently, leading to inconsistency in generated CloudFormation templates.

### Description of changes

To ensure backwards compatibility, if names are longer than 64 characters and use region tokens, if the token uses a single-digit region number, it takes the first **31** characters + the last 32 characters; if the token uses a double-digit region number or otherwise, it takes the first **32** characters + the last 32 characters. This ensures it will always take the same first chunk of the actual function's name.

### Description of how you validated changes

A new unit test was added to verify the consistency of function names in the template.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by scanlonp — CHANGES_REQUESTED** [review]
Hey @Leo10Gama, I like the nature of the changes. A couple things to think about.

First, this looks like it may be a breaking change. From the comments in #15523 and #28641, changing this name will replace the CloudFront function. We may need to put this behind a feature flag.

Second, I think we can solve the consistency problems as well keeping the region in the name by adding the region to the name separately from the truncation. Say we do
```
const uniqueName = Lazy.string({
        produce: () => Names.uniqueResourceName(this, { maxLength: 40, allowedSpecialCharacters: '-_' }),
return Stack.of(this).region + uniqueName;
```
If the current longest region name is 14 characters (ap-southeast-1), we need to make sure the uniqueName is max 50 characters. Why not bake in some wiggleroom for future region names an make the max length 40.

#28641 used `Names.uniqueResourceName` in order to control the length, but truncating `Names.uniqueId` is also an option.

**Comment by Leo10Gama** [comment]
Hey @scanlonp, thanks for the feedback!

With regards to whether this would be a breaking change, I tried to find a solution that would only affect users facing this issue, hence why I wrote the if-else logic the way I did. My idea was to preserve the original logic, but rework it so that the newer logic only happens for affected users, hence the `.startsWith()` check at the beginning. In any other situation, the original name generation is preserved, so users who weren't affected won't see a difference, thus I don't see the need for using a flag.

The `Lazy.string()` approach seems like it would also work, since it would replace the name with a token like the region, but that would definitely introduce breaking changes and would need to go behind a feature flag as you said. Since this is a bug that's been affecting users for a while (given a few issues opened about it), I think it would be good to try prioritizing a fix that isn't hidden behind a flag, for ease of use for users. 

I wouldn't be opposed to making the lazy string change if the flag is necessary, since it does seem like a better way to generate names as well compared to the existing logic! But if we can find a way to maintain the original logic while only fixing the issue for affected users, we ought to do that. If breaking changes are unavoidable, then the flag and lazy string approach would definitely be the way to go, but I'd be open to trying to rework this logic if you know of any cases this would break.

If we go with the current implementation, though, I can also replace the magic number indicating how many digits are in the region token with a computed value for clarity lol

**Comment by scanlonp** [comment]
@Leo10Gama, I certainly agree with preserving the logic for users who do not run into this bug.

To what extent we can "break" customers depends on who is facing this bug right now. The non-deterministic behavior occurs when the function name is sufficiently long. Since we have non-deterministic behavior, we are possibly forcing replacements on every deploy, so it should be ok to just make the change without a feature flag in those cases. For customers whose function name is not that long, they have never faced the issue. I appreciate your concern for not changing the behavior for this second group of users.

With that in mind, I did some testing, and found that if the user's stack and function id's are 34 or more characters combined, we see the non-determinism. 
It appears that `Names.uniqueResourceName()` and `Names.uniqueId()` essentially have the same output - `uniqueResourceName()` just allows some configuration, such as the max length. Therefore, for users whose stack and function id's are 33 or less characters combined, `Names.uniqueResourceName()`with max characters >33 will generate the same name as the old composition, so those users will see no difference. (`Lazy.string()` also resolves the token at synth time, so there is not a concern there about introducing more tokens to the template or breaking users in that way.)

For users with stack + FunctionName >= 34, they are already broken, so the new generation will make their names standard. I also like using a function specialized for accommodating resource names with a max length rather than hacking it together with logic in the construct itself.

This is to say I believe we are free to change the name generation in this way without a feature flag at all!

**Review by scanlonp — CHANGES_REQUESTED** [review]
Do we need to check the length at all? I think we can just generate the name consistently from now on. I believe that the behavior will not change for users whose function name was <64 characters.

**Comment by Leo10Gama** [comment]
Yes, behaviour should be consistent now thanks to doing the name-splitting before appending the region. As you said, the current longest region name is 14 characters, so leaving the name at 40 shouldn't cause any issues, but I could add a quick check before the new logic's `return` to verify it's <64 characters, if that's preferred.

**Comment by scanlonp** [comment]
I meant that we would not even have to create the initial name and verify if it is less than 64 characters at all. We could simply use the new logic every time.

I am trying to test if this would make any difference. So far, it has not, but I need to look at the impact for when the Function is nested in the construct tree - defined within another construct or stack.

File: packages/aws-cdk-lib/aws-cloudfront/lib/function.ts [hunk 1]
```diff
@@ -222,11 +222,13 @@ export class Function extends Resource implements IFunction {
   }
 
   private generateName(): string {
-    const name = Stack.of(this).region + Names.uniqueId(this);
-    if (name.length > 64) {
-      return name.substring(0, 32) + name.substring(name.length - 32);
+    const maxNameLength = 64 - '${Token[AWS.Region.00]}'.length;
```
Comment (scanlonp) [inline packages/aws-cdk-lib/aws-cloudfront/lib/function.ts:225]: nit: this variable is not really the max name length
nit2: lets add a doc string here to explain what & why we are doing this. It is not clear since this was an edge case we are trying to avoid.

File: packages/aws-cdk-lib/aws-cloudfront/lib/function.ts [hunk 2]
```diff
@@ -222,11 +222,13 @@ export class Function extends Resource implements IFunction {
...
+    if (Names.uniqueId(this).length < maxNameLength) {
```
Comment (scanlonp) [inline packages/aws-cdk-lib/aws-cloudfront/lib/function.ts:226]:
```suggestion
    if (Names.uniqueId(this).length <= maxNameLength) {
```
Off by one I believe. Users are fine if their name came out to be this length as the non determinism comes when the token length plus the name is greater than 64.

**Review by scanlonp — CHANGES_REQUESTED** [review]
One small change, and a couple small nits. Otherwise, we are good to go.

Also lets untrack the Feature Flags file. Even if that is what needs to be in there, this PR is not the best place for it.

**Review by scanlonp — APPROVED** [review]
Nice work @Leo10Gama, looks great!

Pretty funny that the two integ tests straddle the character limit exactly.
