### PR TITLE
fix(apigateway): deployment fails when Model's contentType is not specified

### LINKED ISSUE #6161: API Gateway ModelOptions interface should require contentType
Cloudformation requires `contentType` to be defined in `ModelOptions`, but in API it is marked as optional.

### Reproduction Steps
```
    const model = new gateway.Model(this, 'Model', {
      restApi: props.resource.restApi,
      schema: {
        schema: gateway.JsonSchemaVersion.DRAFT4,
        type: gateway.JsonSchemaType.OBJECT,
        properties: {
          name: {
            type: gateway.JsonSchemaType.STRING,
          }
        }
      }
    });
```

### Environment

  - **CLI Version      :** 1.22.0 (build 309ac1b)
  - **Framework Version:** 1.22.0
  - **OS               :** MacOS
  - **Language         :** Typescript

### Other

Adding contentType property everything works fine.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by nija-at**
CloudFormation and hence the CDK has marked this property as optional,
however, it is not. CloudFormation deployment will fail if this property
is not specified.

Use 'application/json' as the default as this is the most common case
when specifying the content type of the RestApi Model.

fixes #6161

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-apigateway/lib/model.ts [hunk 1]
```diff
@@ -167,7 +167,7 @@ export class Model extends Resource implements IModel {
     const modelProps: CfnModelProps = {
       name: this.physicalName,
       restApiId: props.restApi.restApiId,
-      contentType: props.contentType,
+      contentType: props.contentType ?? 'application/json',
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-apigateway/lib/model.ts]: :heart:
