### PR TITLE
fix: log buckets don't have acls enabled

### LINKED ISSUE #25288: s3: breaking change, cannot create bucket anymore, InvalidBucketAclWithObjectOwn
### Describe the bug

Deployed S3 bucket last week into account A without issues and this week it fails on account B with a "Bucket cannot have ACLs set with "ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwnership; Request ID: K97VC1M7Z0YY14A5; S3 Extended Request ID: DZGiUrXpLClhwp+7nOjoGocVx15FGQCQd6V0NGXk/YSJ3n/OTZWOIg5sNZGagfs7T0wWX2hPw6M=; Proxy: null)".
Perhaps the announcement https://www.helpnetsecurity.com/2023/02/07/amazon-s3-bucket-security/ is the reason. 

### Expected Behavior

I expected the buckets to be created without issue, since this worked last week.

### Current Behavior

TERMINAL Output: The bucket creation fails with "1:43:11 PM | CREATE_FAILED        | AWS::S3::Bucket               | Servicesxxxcsvaccesslogstsm07305C09
Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwn
ership; Request ID: K97VC1M7Z0YY14A5; S3 Extended Request ID: DZGiUrXpLClhwp+7nOjoGocVx15FGQCQd6V0NGXk/YSJ3n/OTZWOIg5sNZGagfs7T0wWX2hPw6M=; Proxy: null)"

CFN Output:
2023-04-25 13:43:11 UTC+0200 | Servicesxxxcsvaccesslogstsm07305C09 | CREATE_FAILED | Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwnership; Request ID: K97VC1M7Z0YY14A5; S3 Extended Request ID: DZGiUrXpLClhwp+7nOjoGocVx15FGQCQd6V0NGXk/YSJ3n/OTZWOIg5sNZGagfs7T0wWX2hPw6M=; Proxy: null)
-- | -- | -- | --

### Reproduction Steps

        access_logs_bucket = s3.Bucket(
            self, "xxx-csv-access-logs-tsm", 
            encryption=s3.BucketEncryption.S3_MANAGED,
            versioned=True,
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
        )
        csv_bucket = s3.Bucket(
            self, "xxx-csv", 
            encryption=s3.BucketEncryption.KMS, 
            encryption_key=csv_bucket_key,
            versioned=True,
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            enforce_ssl=True,
            server_access_logs_bucket=access_logs_bucket
        )

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.76.0 (build 78c411b)

### Framework Version

_No response_

### Node.js Version

v19.8.1

### OS

macos

### Language

Python

### Language Version

Python 3.9.6

### Other information

_No response_

### PR DESCRIPTION
**Pull request by MrArnoldPalmer**
Set ObjectOwnership: ObjectWriter automatically if and only if:

   - It is not provided by the user
   - AccessControl ACLs are configured (only if AccessControl != PRIVATE)

If the user does supply ObjectOwnership != ObjectWriter AND they try to set ACLs, we should error.

`ObjectWriter` was essentially the default behavior before the change to disable ACLs by default for new buckets so though this will update existing buckets it should not cause any breakage or replacement.

Closes #25288

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by rix0rrr — APPROVED** [review]

**Comment by rix0rrr** [comment]
Changed my mind -- I think we should set `ObjectOwnership: ObjectWriter` automatically if and only if:

* It is not provided by the user 
* `AccessControl` ACLs are configured (potentially only if `AccessControl != PRIVATE`, which seems to still be allowed?)

If the user *does* supply `ObjectOwnership != ObjectWriter` AND they try to set ACLs, we should error.

File: packages/aws-cdk-lib/aws-s3/lib/bucket.ts [hunk 1]
```diff
@@ -2190,13 +2193,24 @@ export class Bucket extends BucketBase {
     }));
   }
 
-  private parseOwnershipControls({ objectOwnership }: BucketProps): CfnBucket.OwnershipControlsProperty | undefined {
-    if (!objectOwnership) {
+  private parseOwnershipControls(
+    objectOwnership?: ObjectOwnership,
+    accessControl?: BucketAccessControl,
+  ): CfnBucket.OwnershipControlsProperty | undefined {
```
Comment (rix0rrr) [inline packages/aws-cdk-lib/aws-s3/lib/bucket.ts:2199]: For style, since this function is only ever called with `this.whatever`, it doesn't need to take these as parameters.

It could just read them from the object immediately.

File: packages/aws-cdk-lib/aws-s3/lib/bucket.ts [hunk 2]
```diff
@@ -2190,13 +2193,24 @@ export class Bucket extends BucketBase {
...
+    // Enabling an ACL explicitly is required for all new buckets.
+    // https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/
+    const accessControlRequiresObjectOwnership = (accessControl && accessControl !== BucketAccessControl.PRIVATE);
+    if (!objectOwnership && !accessControlRequiresObjectOwnership) {
       return undefined;
     }
+
+    if (accessControlRequiresObjectOwnership && objectOwnership === ObjectOwnership.BUCKET_OWNER_ENFORCED) {
+      throw new Error (`objectOwnership cannot be set to "${ObjectOwnership.BUCKET_OWNER_ENFORCED}" when accessControl is "${accessControl}"`);
```
Comment (rix0rrr) [inline packages/aws-cdk-lib/aws-s3/lib/bucket.ts:2208]:
```suggestion
      throw new Error (`objectOwnership must be set to ObjectOwnership.OBJECT_WRITER when accessControl is "${accessControl}"`);
```

**Review by rix0rrr — APPROVED** [review]
Provisional approval with some small requests

File: packages/aws-cdk-lib/aws-s3/lib/bucket.ts (hunk 2 above)
Comment (corymhall) [reply packages/aws-cdk-lib/aws-s3/lib/bucket.ts]: Done!

**Comment by corymhall** [comment]
@Mergifyio refresh
