### PR TITLE
fix(assertions): `hasResourceProperties` is incompatible with `Match.not` and `Match.absent`

### LINKED ISSUE #16626: (assertions): `absentProperty()` and `not()` matchers are incompatible with `hasResourceProperties`
Given a template that has a resource with no Properties (just `Type`)

```json
{
  "Resources": {
    "IamUser1": {
      "Type": "AWS::IAM::User"
    }
  }
}
```

The following assertion should pass but throws the error `Template has 1 resources with type AWS::IAM::User, but none match as expected`.

```ts
Template.fromStack(stack).hasResourceProperties('AWS::IAM::User', {
  UserName: Match.absentProperty(),
});
```

Similarly, the assertion -

```ts
Template.fromStack(stack).hasResourceProperties('AWS::IAM::User', Match.not({
  UserName: 'MyUser',
}));
```

The workaround is to do -

```ts
Templte.fromStack(stack).hasResource('AWS::IAM::User', {
  Properties: Match.absentProperty(),
});
```

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by kaizencc**
Fixes #16626.

This PR modifies `hasResourceProperties()` so that it accounts for the special case where `Properties` does not exist on the template. The following assertions previously behaved incorrectly when `Properties` were not in the template and are now fixed:

```ts
template.fromStack(stack); // some template with no `Properties`.

// assert that `Properties` does not exist in the template. Returns true.
template.hasResourceProperties('Foo::Bar', Match.absent());

// assert that `baz` is not a `Property` of 'Foo::Bar'. Returns true.
template.hasResourceProperties('Foo::Bar', {
   baz: Match.absent(),
};

// assert that `baz` does not have a value of `qux` in the `Properties` object. Returns true.
template.hasResourceProperties('Foo::Bar', Match.not({baz: 'qux'});
```

It also moves `AbsentMatch` into the `private` folder so that it can be exposed internally as a special case for `hasResourceProperties()`.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/assertions/lib/private/resources.ts [hunk 1]
```diff
@@ -17,9 +18,9 @@ export function findResources(inspector: StackInspector, type: string, props: an
   return result.matches;
 }
 
-export function hasResource(inspector: StackInspector, type: string, props: any): string | void {
+export function hasResource(inspector: StackInspector, type: string, props: any, addProperties?: boolean): string | void {
   const section: { [key: string]: Resource } = inspector.value.Resources;
-  const result = matchSection(filterType(section, type), props);
```
Comment (nija-at) [inline packages/@aws-cdk/assertions/lib/private/resources.ts:22]: Can we instead slice this out into a method called `hasResourceProperties()` that does the necessary coercion and calls `hasResource()`? Feels like that would be cleaner than shimmying a boolean here.

File: packages/@aws-cdk/assertions/test/template.test.ts [hunk 2]
```diff
@@ -269,6 +269,64 @@ describe('Template', () => {
...
+        type: 'Foo::Bar',
+      });
+
+      const inspect = Template.fromStack(stack);
+      inspect.hasResourceProperties('Foo::Bar', { bar: Match.absentProperty() });
+
+      expect(() => inspect.hasResourceProperties('Foo::Bar', { bar: Match.absentProperty(), baz: 'qux' }))
+        .toThrow(/Missing key at \/Properties\/baz/);
+      // Add the below line when this is merged: https://github.com/aws/aws-cdk/pull/16653
+      // expect(inspect.hasResourceProperties('Foo::Bar', Match.absent()));
```
[the remark this answers is not in the document]
Comment (nija-at) [reply packages/@aws-cdk/assertions/test/template.test.ts:316]: I'm ok with supporting this. Seems reasonable given that it's now called `absent()` and not `absentProperty()`,

**Review by nija-at — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/assertions/lib/private/resources.ts (hunk 1 above)
Comment (kaizen3031593) [reply packages/@aws-cdk/assertions/lib/private/resources.ts:22]: I sorta disagree that that would be cleaner (but will do it if you double down on your opinion). I agree that this doesn't look very elegant. However, the alternative is having two functions with very similar bodies. I don't think its feasible for `hasResourceProperties()` to call `hasResource()` after it has added the empty Property objects. What would have to happen is a third internal function, say `matchResources()` which both `hasResourceProperties()` and `hasResource()` would call. And this complicates the special case of `hasResourceProperties('type', Match.absent())` that we agreed to support, since this would have to avoid adding empty property objects. It would look like this --

```ts
// private/resource.ts
hasResource(inspector: StackInspector, type: string, props: any): string | void {
  const section: { [key: string]: Resource } = inspector.value.Resources;
  return matchSection(filterType(section, type), type, props);
}

hasResourceProperties(inspector: StackInspector, type: string, props: any): string | void {
  const section: { [key: string]: Resource } = inspector.value.Resources;
  return matchSection(addEmptyProperties(filterType(section, type)), type, props);
}

matchSection(section: any, type: string, props: any): string | void {
  if (result.match) {
    return;
  }

  if (result.closestResult === undefined) {
    return `No resource with type ${type} found`;
  }

  return [
    `Template has ${result.analyzedCount} resources with type ${type}, but none match as expected.`,
    formatFailure(result.closestResult),
  ].join('\n');
}
```

And then of course the exposed API for `hasResourceProperties()` would have to account for the special case:

```ts
// template.ts
  public hasResourceProperties(type: string, props: any): void {
    if (props instanceof AbsentMatch) {
        return hasResource(this.inspector, type, Match.absent());
    }
    const matchError = hasResourceProperties(this.inspector, type, Match.objectLike({
      Properties: Matcher.isMatcher(props) ? props : Match.objectLike(props),
    }));
    if (matchError) {
      throw new Error(matchError);
    }
  }
```

So -- I think that the current implementation saves a lot of code and is easier to follow than the alternative. And since this is an internal API we do not have to worry about discoverability and all that jazz.

Laying out the options I can see. Happy to go with whichever you prefer.

Comment (nija-at) [reply packages/@aws-cdk/assertions/lib/private/resources.ts:22]: I'm having a hard time following what the problem is here.

Why not something like this -

```ts
hasResourceProperties(template: Template, type: string, props: any): string | void {
  const amended = addEmptyProperties(template);
  return hasResource(amended, type, props);
}
```

Comment (kaizen3031593) [reply packages/@aws-cdk/assertions/lib/private/resources.ts]: Good call. I think this was actually impossible with the previous version of the API with `inspector` as a parameter rather than `template`. It would be problematic to modify `inspector.template` since the modification would be persist beyond the particular test. Here we can deep copy `template`, modify it, and then send it to `hasResource`.
