### PR TITLE
fix(ssm): correctly deduplicate parameter names

### LINKED ISSUE #3076: Issue with machineImages when multiple autoscalinggroups in the same scope
* **I'm submitting a ...**
  - [X] :beetle: bug report

I create 2 AutoScalingGroups in the same scope but there seems to be a conflict in the creation of the machine image id.

```
<path>\node_modules\@aws-cdk\core\lib\construct.js:420
            throw new Error(`There is already a Construct with name '${childName}' in ${typeName}${name.length > 0 ? ' [' + name + ']' : ''}`);
            ^

Error: There is already a Construct with name 'SsmParameterValue:/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id:C96584B6-F00A-464E-AD19-53AFF4B05118.Parameter' in MyStack [MyStack]
```

Environment:
  - CDK CLI Version: 0.36.0
  - Module Version: 0.36.0
  - OS: Win10
  - Language: Typescript

### PR DESCRIPTION
**Pull request by rix0rrr**
Parameter names with '/' in them would not be correctly deduplicated,
since the '/' is also used to delimit identifiers in construct paths.

Change `findChild()` so it no longer traverses into the tree; if we assume it
will only ever find one child deep, we can do the same kind of escaping
there as we apply to construct IDs.

Fixes #3076.

BREAKING CHANGE:

* **core**: `construct.findChild()` can only find direct children anymore.

----

Please read the [contribution guidelines](https://github.com/awslabs/aws-cdk/blob/master/CONTRIBUTING.md) and follow the pull-request checklist.

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/core/lib/construct.ts [hunk 1]
```diff
@@ -727,3 +692,11 @@ function ignore(_x: any) {
 // Import this _after_ everything else to help node work the classes out in the correct order...
 
 import { Reference } from './reference';
+
+/**
+ * Return a sanitized version of an arbitrary string, so it can be used as an ID
+ */
+function sanitizeId(id: string) {
+  // Escape path seps as double dashes
+  return id.replace(/\//g, '--');
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/construct.ts]: Use PATH_SEP

**Comment by rix0rrr** [comment]
> Update PR description

To what?
