### PR TITLE
fix(dynamodb): throw error when grantee is an unsupported ServicePrincipal

### LINKED ISSUE #37273: DynamoDB Table construct started creating invalid resource-based policy with service principals after v2.222.0
### Describe the bug

After upgrading `aws-cdk-lib` from v2.207.0 to v2.222.0+, a DynamoDB Table construct started creating resource-based policies that include service principals, this caused the deployment to fail

### Versions tested
- **v2.220.0**: No issues
- **v2.222.0**: Build fails with dependency cycle error: "Template is undeployable, these resources have a dependency cycle"
- **v2.234.1**: Dependency cycle resolved, but deployment fails with:  Resource handler returned message: "One or more parameter values were invalid: Invalid policy document: Policy contains invalid service principal (Service: DynamoDb, Status Code: 400)"

### Possibly related PRs

- https://github.com/aws/aws-cdk/pull/35817
- https://github.com/aws/aws-cdk/pull/35554

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Library Version

v2.220.0

### Expected Behavior

DynamoDB Table construct should not generate resource-based policies with invalid service principals after upgrading CDK versions

### Current Behavior

The synthesized template includes an invalid service principal in the DDB resource-based policy, it caused cfn deployment to fail.

### Reproduction Steps

1. Create a DynamoDB Table with `grantReadWriteData` using a `ServicePrincipal`:

```
const table = new Table(this, 'MyTable', {
   tableName: 'my-table',
   partitionKey: {
       name: 'pk',
       type: AttributeType.STRING,
   },
   sortKey: {
       name: 'sk',
       type: AttributeType.STRING,
   },
   encryption: TableEncryption.CUSTOMER_MANAGED,
   billingMode: BillingMode.PAY_PER_REQUEST,
   removalPolicy: RemovalPolicy.RETAIN,
   pointInTimeRecovery: true,
});

table.grantReadWriteData(new ServicePrincipal('myservice.amazonaws.com'));

```
2. deploy with `aws-cdk-lib` v2.222.0 or later.

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### AWS CDK Library version (aws-cdk-lib)

2.222.0

### AWS CDK CLI version

2.1030.0

### Node.js Version

v20.18.3

### OS

macOS 15.7.4

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by kumsmrit**
### Issue # (if applicable)

Closes https://github.com/aws/aws-cdk/issues/37273.

### Reason for this change

After v2.222.0, calling `table.grantReadWriteData(new ServicePrincipal(...))` started generating DynamoDB resource-based policies containing service principals. This is a regression caused by the combination of [#35554](https://github.com/aws/aws-cdk/pull/35554) (which fixed `addToResourcePolicy` to actually take effect) and [#35817](https://github.com/aws/aws-cdk/pull/35817) (which enabled the grant framework to automatically discover DynamoDB resource policies). Previously, `addToResourcePolicy` was a no-op, so the grant silently did nothing.

For unsupported service principals (e.g. `myservice.amazonaws.com`), this produces an invalid resource policy that fails at CloudFormation deploy time with: *"Invalid policy document: Policy contains invalid service principal"*.

However, DynamoDB does support [specific service principals](https://github.com/aws/aws-cdk/issues/37273#issuecomment-4099645443) in resource policies:
- `redshift.amazonaws.com` — [Redshift zero-ETL integration](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/RedshiftforDynamoDB-zero-etl.html)
- `replication.dynamodb.amazonaws.com` — [Multi-account global tables](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/globaltables_MA_security.html)
- `glue.amazonaws.com` — [SageMaker Lakehouse zero-ETL via AWS Glue](https://docs.aws.amazon.com/glue/latest/dg/zero-etl-sources.html#zero-etl-config-source-dynamodb)

### Description of changes

1. **Throw `ValidationError` for unsupported service principals** — Grant methods (`grant`, `grantReadData`, `grantWriteData`, `grantReadWriteData`, `grantFullAccess`) on both `Table` and `TableV2` now detect `ServicePrincipal` grantees and throw a `ValidationError` at synth time, directing users to `table.addToResourcePolicy()` instead. This fails fast rather than producing an invalid template that fails at deploy time.

2. **Allowlist known-valid service principals** — Added `KNOWN_DYNAMODB_SERVICE_PRINCIPALS` allowlist in `private/principal-utils.ts` containing the three documented service principals. The new `isUnsupportedServicePrincipal()` function walks the principal wrapper chain (handling `PrincipalWithConditions`, `SessionTagsPrincipal`, etc.) to extract the service name and check it against the allowlist. Allowlisted principals pass through `grant*` methods normally.

3. **Integration test** — Added `integ.dynamodb.grant-service-principal` verifying the three allowlisted principals produce correct resource policies in the synthesized CloudFormation template.

### Describe any new or updated permissions being added

No new or updated IAM permissions. This change prevents invalid IAM resource policy statements from being generated for unsupported service principals, while allowing valid ones through.

### Description of how you validated changes

- Unit tests: `dynamodb.test.ts` (186 passing), `table-v2.test.ts` (135 passing)
  - Unsupported principals (`bedrock.amazonaws.com`, `lambda.amazonaws.com`) throw `ValidationError`
  - Allowlisted principals (`redshift`, `replication.dynamodb`, `glue`) succeed
  - Wrapped principals (via `.withConditions()`) handled correctly for both cases
- Integration test: `integ.dynamodb.grant-service-principal` deployed successfully with snapshot containing resource policy statements for all three allowlisted principals

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-dynamodb/lib/table-v2-base.ts [hunk 1]
```diff
@@ -541,6 +549,16 @@ export abstract class TableBaseV2 extends Resource implements ITableV2, IResourc
...
   }
 
+  private dropServicePrincipalGrant(grantee: IGrantable): Grant {
+    Annotations.of(this).addWarningV2(
+      '@aws-cdk/aws-dynamodb:servicePrincipalGrantDropped',
+      'DynamoDB grant* methods do not support ServicePrincipal grantees. ' +
+      'Use table.addToResourcePolicy() for an explicit service-specific table policy ' +
+      'with required service principal, actions, and conditions',
+    );
+    return Grant.drop(grantee, 'DynamoDB grant* does not support ServicePrincipal grantees');
```
Comment (mrgrain) [inline packages/aws-cdk-lib/aws-dynamodb/lib/table-v2-base.ts]: Kinda sounds like that SPs are never allowed here, but elsewhere you have stated at a small limited list of SPs is actually allowed. I don't think we should drop all SPs, but have a allow list.

Comment (kumsmrit) [reply packages/aws-cdk-lib/aws-dynamodb/lib/table-v2-base.ts]: Yes, there are few SPs documented for DynamoDB resource policies, but they are integration-specific and require their own actions/conditions (e.g. [replication.dynamodb.amazonaws.com](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/globaltables_MA_security.html)). The generic `grant*` methods add standard data actions (dynamodb:GetItem, dynamodb:PutItem, etc.), which are not the right action set for those service-principal resource policies.
So even if we had an allowlist of permitted SPs, the actions being granted by `grant*` methods could produce incorrect resource policy which might not fail deployment, but it could still be functionally incorrect.

Because of that, I think the right path for SPs is the explicit `addToResourcePolicy` API, where the caller can provide the correct integration-specific principal, actions, and conditions.

**Comment by Abogical** [comment]
Snapshot deployment passed: https://github.com/aws/aws-cdk/actions/runs/23655284133/job/68910779532?pr=37335

Removing label.

**Review by rix0rrr — APPROVED** [review]
