### PR TITLE
fix(aws-elasticloadbalancingv2): target group metrics

### LINKED ISSUE #1213: cloudwatch alarms: how to add alarm dependency?
Version: 0.18.0

I'm running into a dependency issue creating an alarm: the alarm dimensions indirectly refer to a target group and load balancer that have not yet been created during stack creation.  How do I add a dependency on these objects?  There doesn't seem to be a way to add the equivalent of "DependsOn" to a construct.

Code:
```
   new Alarm(this, 'TargetGroupUnhealthyHosts', {
      metric: service.targetGroup.metricUnhealthyHostCount(),
      threshold: 1,
      evaluationPeriods: 2,
    });
```

Error:
```
Template error: Fn::Select  cannot select nonexistent value at index 0
```

Generated snippet:
```
      Dimensions:
        - Name: TargetGroup
          Value:
            'Fn::GetAtt':
              - ServiceLBPublicListenerECSGroup0CC8688C
              - TargetGroupFullName
        - Name: LoadBalancer
          Value:
            'Fn::Join':
              - ''
              - - 'Fn::Select':
                    - 1
                    - 'Fn::Split':
                        - /
                        - 'Fn::Select':
                            - 0
                            - 'Fn::GetAtt':
                                - ServiceLBPublicListenerECSGroup0CC8688C
                                - LoadBalancerArns
                - /
                - 'Fn::Select':
                    - 2
                    - 'Fn::Split':
                        - /
                        - 'Fn::Select':
                            - 0
                            - 'Fn::GetAtt':
                                - ServiceLBPublicListenerECSGroup0CC8688C
                                - LoadBalancerArns
                - /
                - 'Fn::Select':
                    - 3
                    - 'Fn::Split':
                        - /
                        - 'Fn::Select':
                            - 0
                            - 'Fn::GetAtt':
                                - ServiceLBPublicListenerECSGroup0CC8688C
                                - LoadBalancerArns
```

### PR DESCRIPTION
**Pull request by rix0rrr**
TargetGroup metrics used to use ${TargetGroup.LoadBalancerArns} to find
the load balancer's full name, but that introduces a deployment-time
ordering dependency on the creation of the Listener object.

Instead, use the Listener ARN to get the load balancer name. We
now have an ordering requirement in the CDK code but that can be
detected early and solved by the user.

Fixes #1213.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-target-group.ts [hunk 1]
```diff
@@ -365,3 +360,9 @@ export interface LoadBalancerTargetProps {
    */
   targetJson?: any;
 }
+
+export function loadBalancerNameFromListenerArn(listenerArn: string) {
+    // arn:aws:elasticloadbalancing:us-west-2:123456789012:listener/app/my-load-balancer/50dc6c495c0c9188/f2f7dc8efc522ab2
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-target-group.ts]: Would prefer this to be part of the function JSDoc as an example, and I think it'd be nice to have the corresponding output, too (aka what part are we extracting in fact).

Comment (rix0rrr) [reply packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-target-group.ts]: Fair
