### PR TITLE
fix(stepfunctions): JsonPath does not support path with array

### LINKED ISSUE #9403: [aws-stepfunctions] JsonPath does not support path with array: $[0]
Caused by: 
```console
software.amazon.jsii.JsiiException: JSON path values must be exactly '$', '$$', start with '$.' or start with '$$.' Received: $[0].source.bucket
Error: JSON path values must be exactly '$', '$$', start with '$.' or start with '$$.' Received: $[0].source.bucket
```

### Reproduction Steps

```java
    private List<TaskEnvironmentVariable> environment() {
        return List.of(
                env("source_bucket", JsonPath.stringAt("$[0].source.bucket")),
                env("source_region", JsonPath.stringAt("$[0].source.region")),
                env("target_bucket", JsonPath.stringAt("$[0].target.bucket")),
                env("target_region", JsonPath.stringAt("$[0].target.region")),
                env("stream_name", JsonPath.stringAt("$[0].stream")),
                env("stream_region", JsonPath.stringAt("$[0].target.region")),
                env("credential_id", JsonPath.stringAt("$[0].source_credential_id")),
                env("token", JsonPath.getTaskToken()));
    }
```

### Error Log

Caused by: 
```console
software.amazon.jsii.JsiiException: JSON path values must be exactly '$', '$$', start with '$.' or start with '$$.' Received: $[0].source.bucket
Error: JSON path values must be exactly '$', '$$', start with '$.' or start with '$$.' Received: $[0].source.bucket
```

### Environment

  - **CLI Version      :** 2
  - **Framework Version:** 1.56
  - **Node.js Version:**  
  - **OS               :** Darwin
  - **Language (Version):**  Java 11

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by ayush987goyal**
Fix JsonPath not supporting array paths

closes #9403

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-stepfunctions/lib/fields.ts [hunk 1]
```diff
@@ -214,8 +214,10 @@ export class FieldUtils {
 }
 
 function validateJsonPath(path: string) {
-  if (path !== '$' && !path.startsWith('$.') && path !== '$$' && !path.startsWith('$$.')) {
-    throw new Error(`JSON path values must be exactly '$', '$$', start with '$.' or start with '$$.' Received: ${path}`);
+  if (path !== '$' && !path.startsWith('$.')
+    && path !== '$$' && !path.startsWith('$$.')
+    && !/^\$\[\d+\]$/.test(path) && !/^\$\[\d+\]\./.test(path)) {
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-stepfunctions/lib/fields.ts:219]: maybe put one condition per line to make this more readable.
should this just test for begins with `[` rather than the check for digits

Json path specification supports bracket or dot notation.
i.e. `$.field` is the same as `$['field']`

File: packages/@aws-cdk/aws-stepfunctions/lib/fields.ts [hunk 2]
```diff
@@ -214,8 +214,10 @@ export class FieldUtils {
...
+    throw new Error(`JSON path values must be exactly '$', '$$', '$[n]', start with '$.', start with '$$.' or start with '$[n].' Received: ${path}`);
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-stepfunctions/lib/fields.ts:220]: this would need to be updated based on the comment re: bracket notation

**Review by shivlaks — DISMISSED** [review]

**Review by shivlaks — APPROVED** [review]
