### PR TITLE
fix(elbv2): race condition for Lambda backends

### LINKED ISSUE #4663: Lambda as target in ALB fails to create due to Principal permission issue
When a Lambda function is registered as a target group in an Application Load Balancer it adds  a `AWS::Lambda::Permission` allowing the `Principal: elasticloadbalancing.amazonaws.com` to invoke the function.

However, the *Target group* does not contain a dependency on this permission and due to order of creation might fail if CloudFormation decides to create the TargetGroup before the Lambda permission.

### Reproduction Steps

```python
alb = ApplicationLoadBalancer(...)
listener = alb.add_listener("Listener", port=80, open=False)
lambda_function = Function(...)
listener.add_targets(
            "Target",
            targets=[LambdaTarget(lambda_function)],
            priority=1,
        )
```

### Error Log

From the CloudFormation console:

```
API: elasticloadbalancingv2:RegisterTargets elasticloadbalancing principal does not have permission to invoke arn:aws:lambda:us-west-2:********:function:LambdaFunctionF38095AF-1BKXQUR0FWO9P from target group arn:aws:elasticloadbalancing:us-west-2:***********:targetgroup/LambdaFunction6BJ8GFZ2AFNJ/40d175d269b48dec
```

### Environment

  - **CLI Version      :*1.14.0*
  - **Framework Version:*1.14.0*
  - **OS               :*N/A*
  - **Language         :*English*

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
DISCUSSION TOPIC:

What I'd *actually* like to do is break the return signature of `role.addToPolicy(): boolean` to a struct, otherwise it's going to be very hard to reliably implement this. *Fairly* sure this won't cause issues because few people will be checking the return value of `addToPolicy()`, but of course we technically speaking aren't allowed to do this.

### Commit Message
fix(elbv2): race condition for Lambda backends

Lambda Targets can get registered into a TargetGroup before the
`lambda:Invoke` permissions are added. Since the TargetGroup does
a permission test, deployment will fail.

Fixes #4663.

Adding a long-overdue mechanism to the IAM library to depend on Grants
that just got created, to ensure permissions are created before the
resources that depend on them (in effect: `Grant`s are made
`IDependable`).

Relates to the root cause of #7236.
### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by flemjame-at-amazon** [comment]
I hit this issue and had no idea what the heck was happening. Subsequent synthesis and deployment worked fine, which really confused me.

I think this is a reasonable breaking change to make, especially given what's being fixed.

**Comment by nija-at** [comment]
> What I'd actually like to do is break the return signature of role.addToPolicy(): boolean to a struct, otherwise it's going to be very hard to reliably implement this. Fairly sure this won't cause issues because few people will be checking the return value of addToPolicy(), but of course we technically speaking aren't allowed to do this.

Agree with your point. Not concerned about breaking a function changes its return type from `void` to something specific.

**Comment by rix0rrr** [comment]
> Agree with your point. Not concerned about breaking a function changes its return type from `void` to something specific.

No but unfortunately it's changing from `boolean` to something specific :(

File: packages/@aws-cdk/aws-ecr/lib/repository.ts [hunk 1]
```diff
@@ -424,11 +427,12 @@ export class Repository extends RepositoryBase {
     });
   }
 
-  public addToResourcePolicy(statement: iam.PolicyStatement) {
+  public addToResourcePolicy(statement: iam.PolicyStatement): iam.AddToResourcePolicyResult {
     if (this.policyDocument === undefined) {
       this.policyDocument = new iam.PolicyDocument();
     }
     this.policyDocument.addStatements(statement);
+    return { statementAdded: false, policyDependable: this.policyDocument };
```
Comment (eladb) [inline packages/@aws-cdk/aws-ecr/lib/repository.ts:435]: soooo much better!

File: packages/@aws-cdk/aws-iam/lib/principals.ts [hunk 2]
```diff
@@ -153,7 +181,11 @@ export class PrincipalWithConditions implements IPrincipal {
   }
 
   public addToPolicy(statement: PolicyStatement): boolean {
-    return this.principal.addToPolicy(statement);
+    return this.addToIdentityPolicy(statement).statementAdded;
+  }
+
+  public addToIdentityPolicy(statement: PolicyStatement): AddToIdentityPolicyResult {
```
Comment (eladb) [inline packages/@aws-cdk/aws-iam/lib/principals.ts:187]: Should these be called `addToPrincipalPolicy`?

File: packages/@aws-cdk/aws-iam/lib/principals.ts [hunk 3]
```diff
@@ -46,8 +46,32 @@ export interface IPrincipal extends IGrantable {
...
+export interface AddToIdentityPolicyResult {
+  /**
+   * Whether the statement was added to the identity's policies.
+   */
+  readonly statementAdded: boolean;
+
+  /**
+   * Dependable which allows depending on the policy change being applied
+   *
+   * @default - Required if `statementAdded` is true.
```
Comment (eladb) [inline packages/@aws-cdk/aws-iam/lib/principals.ts:72]: If this is always required if `statementAdded` is `true` then why do we need `statementAdded`? We can rename this field to `addedBy` or `owner` and require that it is set when a statement was added.

**Comment by eladb** [comment]
> What I'd actually like to do is break the return signature of role.addToPolicy(): boolean to a struct, otherwise it's going to be very hard to reliably implement this. Fairly sure this won't cause issues because few people will be checking the return value of addToPolicy(), but of course we technically speaking aren't allowed to do this.

This seems like something we should include in our v2.0 work. Add it to the list in https://github.com/aws/aws-cdk-rfcs/issues/79

File: packages/@aws-cdk/aws-iam/lib/principals.ts (hunk 2 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-iam/lib/principals.ts:187]: Maybe. Right now it's:

* **Principal**: anything you can grant permissions to, that goes into a policy (user, role, but also service principal or account principal)
* **Identity**: an IAM identity you create (user, role, group).

Policies only go on Identities, for example "adding to a service principal's policy" doesn't make any sense.

However, I will grant that this distinction might not be obvious, and it might confuse more than it helps.

Thoughts?

File: packages/@aws-cdk/aws-iam/lib/principals.ts (hunk 3 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-iam/lib/principals.ts:72]: `owner` doesn't really cover the load of what I'm trying to do here, which is strictly offer a way to add a dependency and nothing else.

As for `statementAdded`, yeah maybe it's superfluous. On the other hand it does make for more readable consumer code to say:

```ts
if (result.statementAdded) { /* do thing */ }
```

Rather than:

```ts
if (result.policyDependable !== undefined) { /* do a thing */ }
```

Open to a better name for the dependable though...

File: packages/@aws-cdk/aws-iam/lib/principals.ts (hunk 2 above)
Comment (eladb) [reply packages/@aws-cdk/aws-iam/lib/principals.ts:187]: I am okay with that distinction although I also think it's not 100% required in this case and `addToPrincipalPolicy` would have been a bit clearer

File: packages/@aws-cdk/aws-iam/lib/principals.ts (hunk 3 above)
Comment (eladb) [reply packages/@aws-cdk/aws-iam/lib/principals.ts:72]: Damn I don't.... Can we make this "@experimental"?
