### PR TITLE
fix(s3): auto-delete fails when bucket has been deleted manually

### LINKED ISSUE #16619: aws-s3: deleting stack with already deleted S3 bucket with auto_delete_objects fails
If a stack is created that has an S3 bucket with `auto_delete_objects=True` (and `RetentionPolicy.DESTROY`), and then the S3 bucket is deleted outside CloudFormation, then deleting the stack will fail with an error.

### Reproduction Steps

1. Create a stack with an S3 bucket with `auto_delete_objects=True`.
2. Manually delete the S3 bucket via the console.
3. Delete the stack.

### What did you expect to happen?

I expected the stack deletion to vacuously succeed. If the bucket in question had been deployed with `auto_delete_objects=False`, this would have been the observed behavior.

### What actually happened?

Deleting the custom resource failed, and thus so did deleting the stack.

### Environment

  - **CDK CLI Version  :** 1.118.0
  - **Framework Version:**
  - **Node.js Version:** 14.17.5
  - **OS               :** debian bullseye (running inside a container)
  - **Language (Version):** Python 3.9.6

### Other

The custom resource lambda should handle the "not found" exception from S3 and treat it as a vacuous success.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by otaviomacedo**
Even though buckets are not supposed to be deleted manually, this change makes the delete operation idempotent and thus more reliable.

Fixes #16619.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by LukvonStrom — CHANGES_REQUESTED** [review]
wouldn't using `emptyBucket()` in the `try`/`catch` alone suffice?

**Comment by otaviomacedo** [comment]
> wouldn't using `emptyBucket()` in the `try`/`catch` alone suffice?

Yes, thanks for catching this.

File: packages/@aws-cdk/aws-s3/lib/auto-delete-objects-handler/index.ts [hunk 1]
```diff
@@ -52,5 +52,10 @@ async function onDelete(bucketName?: string) {
   if (!bucketName) {
     throw new Error('No BucketName was provided.');
   }
-  await emptyBucket(bucketName);
+
+  try {
+    await emptyBucket(bucketName);
+  } catch (e) {
+    // Bucket doesn't exist. Ignoring
+  }
```
Comment (jogold) [inline packages/@aws-cdk/aws-s3/lib/auto-delete-objects-handler/index.ts:60]:
```suggestion
  } catch (e) {
    if (e.code !== 'NoSuchBucket') {
      throw e;
    }
    // Bucket doesn't exist. Ignoring
  }
```

**Review by jaresuth — APPROVED** [review]
