### PR TITLE
fix(cli): sdk logging is always present even when not turned on

### LINKED ISSUE #33320: cli: sdk logging present even though verbose logging is not turned on
### Describe the bug

When CDK Watch is used the SDK logger prints verbose logs continuously reducing the utility of CDK watch as it becomes difficult to view the lambda logs as invocations are made. This wasn't happening before. Based on the SDK logger code, it is supposed to print that if debug was true or trace was true or verbose was requested in the cli. In my case they are not set and uses the default. I also tried with debug as false, and trace as false and I was unable to reduce the verbosity. 

Refer screenshot for details (The SDK Info log in my case prints continuously for the CloudWatch.FilterLogEvents)

Image

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

2.176.0

### Expected Behavior

SDK Info logs is expected if debug, trace or verbose logging was requested.

### Current Behavior

SDK Info logs are always present and it doesn't appear to be configurable.

### Reproduction Steps

Running cdk watch on a stack

### Possible Solution

If debug is false (default), trace is false (default) and verbose was not requested then SDK Logger should not print SDK Info logs in the CLI output.

### Additional Information/Context

_No response_

### CDK CLI Version

2.178.0

### Framework Version

_No response_

### Node.js Version

20

### OS

Windows

### Language

TypeScript

### Language Version

5.x

### Other information

_No response_

### PR DESCRIPTION
**Pull request by mrgrain**
### Issue #33320

Closes #33320

### Reason for this change

In #33273 we introduced a bug that causes SDK logs to always be printed.

### Description of changes

Set the correct log level for SDK logs.

### Describe any new or updated permissions being added

n/a

### Description of how you validated changes

Manual test and updated unit test

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk/lib/api/aws-auth/sdk-logger.ts [hunk 1]
```diff
@@ -87,7 +87,7 @@ export class SdkToCliLogger implements Logger {
    * ```
    */
   public error(...content: any[]) {
-    this.notify('info', ...content);
+    this.notify('error', ...content);
```
Comment (mrgrain) [inline packages/aws-cdk/lib/api/aws-auth/sdk-logger.ts:90]: this was also wrong!

File: packages/aws-cdk/test/api/aws-auth/sdk-logger.test.ts [hunk 2]
```diff
@@ -12,13 +12,16 @@ describe(SdkToCliLogger, () => {
...
+    logger[method]('SDK Logger test message');
     expect(ioHost.notify).not.toHaveBeenCalled();
   });
 
   test.each(['info', 'warn', 'error'] as Array<keyof SdkToCliLogger>)('%s method logs to notify', (method) => {
-    logger[method]('test');
-    expect(ioHost.notify).toHaveBeenCalled();
+    logger[method]('SDK Logger test message');
+    expect(ioHost.notify).toHaveBeenCalledWith(expect.objectContaining({
+      level: 'trace',
```
Comment (mrgrain) [inline packages/aws-cdk/test/api/aws-auth/sdk-logger.test.ts:22]: explicitly expect the the level to be `trace`

**Review by kaizencc — APPROVED** [review]

**Comment by mrgrain** [comment]
@mergify refresh

**Comment by mrgrain** [comment]
@mergifyio queue priority-squash

**Comment by mrgrain** [comment]
@mergifyio requeue

**Comment by mrgrain** [comment]
@mergifyio refresh
