### PR TITLE
fix(aws-cdk): Auto-delete stacks that failed creating before new attempt

### LINKED ISSUE #901: toolkit: stacks can get stuck in ROLLBACK_COMPLETE
If the first deploy of a stack fails, the stack gets stuck in `ROLLBACK_COMPLETE` and requires out-of-band user intervention to delete it and try again:

```
$ cdk -a 'node integ.autoscaling.js' deploy
 ⏳  Starting deployment of stack aws-cdk-dynamodb...
 ❌  Deployment of stack aws-cdk-dynamodb failed: ValidationError: Stack:arn:aws:cloudformation:us-east-1:993655754359:stack/aws-cdk-dynamodb/540d7d70-cd53-11e8-b11c-50d5cd265c36 is in ROLLBACK_COMPLETE state and can not be updated.
Stack:arn:aws:cloudformation:us-east-1:993655754359:stack/aws-cdk-dynamodb/540d7d70-cd53-11e8-b11c-50d5cd265c36 is in ROLLBACK_COMPLETE state and can not be updated.
```

This didn't use to happen because we created an empty stack and updated from there: rollback would update back to a safe point from which we could try to deploy again. But right now, you have to use the AWS CLI to delete the stack, wait for that, and only THEN can you try using the CDK again. 

Pretty bad experience for first-time users who are almost guaranteed to get things wrong on the first try, and then get stuck in a position from which it's not obvious how to recover from.

### PR DESCRIPTION
**Pull request by RomainMuller**
Restore the previous behavior around stacks that failed creation,
detecting the condition and automatically deleting the stack before
making a new attempt.

The stack is not deleted after the failure in order to allow for
forensics to be performed. Also, deleting the stack on the next creation
attempt is more robust.

Fixes #901

### CODE REVIEW

File: packages/aws-cdk/lib/api/deploy-stack.ts [hunk 1]
```diff
@@ -43,6 +43,15 @@ export async function deployStack(stack: cxapi.SynthesizedStack,
   const cfn = await sdk.cloudFormation(stack.environment, Mode.ForWriting);
   const bodyParameter = await makeBodyParameter(stack, toolkitInfo);
 
+  if (await stackFailedCreating(cfn, deployName)) {
+    debug(`Found existing stack ${deployName} that had previously failed creation. Deleting it before attempting to re-create it.`);
+    await cfn.deleteStack({ StackName: deployName }).promise();
+    const deletedStack = await waitForStack(cfn, deployName, false);
+    if (deletedStack && deletedStack.StackStatus !== 'DELETE_COMPLETE') {
```
Comment (rix0rrr) [inline packages/aws-cdk/lib/api/deploy-stack.ts]: I don't see how we can ever get `DELETE_COMPLETE` state. To get the status of a deleted stack you need the full ARN (including unique ID), but `deployName` is amost certain to not include that? Or does it?

I assume this works by returning `undefined` as soon as the stack can't be fetched by just its name anymore?

**Comment by rix0rrr** [comment]
Merge as `fix(aws-cdk): ...`
