### PR TITLE
fix(aws-sqs): Queue.import() doesn't return a value

### LINKED ISSUE #879: Importing SQS Queue always returns undefined
I'm unable to import a QueueRef using the QueueRef.import function. The value returned is always `undefined`. I believe prepending a `return` to [this line](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-sqs/lib/queue-ref.ts#L15) should solve the issue. This is assuming the queue import should have the same semantics as the [S3 Bucket import](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L69) which returns a `BucketRef`.

### PR DESCRIPTION
**Pull request by eladb**
`QueueRef.import` did not return the created `ImportedQueue` object.
Added assertions to the relevant test to verify that indeed exports
and imports behave as expected.

Fixes #879

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-sqs/lib/queue-ref.ts [hunk 1]
```diff
@@ -11,8 +11,8 @@ export abstract class QueueRef extends cdk.Construct implements s3n.IBucketNotif
   /**
    * Import an existing queue
    */
-  public static import(parent: cdk.Construct, name: string, props: QueueRefProps) {
-    new ImportedQueue(parent, name, props);
+  public static import(parent: cdk.Construct, name: string, props: QueueRefProps): QueueRef {
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-sqs/lib/queue-ref.ts]: Ho ho that was sad :)
