### PR TITLE
fix(lambda-event-sources): incorrect documented defaults for stream types

### LINKED ISSUE #13908: aws-lambda: default values discrepancies between TypeScript and Web documentation
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.EventSourceMappingOptions.html

There seems to be some inconsistencies in the default values specified for the `EventSourceMappingOptions` interface between [TypeScript source](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda-event-sources/lib/stream.ts) and [Web](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.EventSourceMappingOptions.html) versions of the CDK package documentation.

At least, these are the ones that I found:
- `maxRecordAge`
  * Source says [`@default Duration.days(7)`](https://github.com/aws/aws-cdk/blob/f9b67505f3f5bf3f42be028f9d370c4096a9d4dc/packages/%40aws-cdk/aws-lambda-event-sources/lib/stream.ts#L44).
  * Web says *default: infinite or until the record expires*.
  * Empirical default value: `-1` (infinite)
- `retryAttempts`
  * Source says [`@default 10000`](https://github.com/aws/aws-cdk/blob/f9b67505f3f5bf3f42be028f9d370c4096a9d4dc/packages/%40aws-cdk/aws-lambda-event-sources/lib/stream.ts#L54).
  * Web says *default: infinite or until the record expires*.
  * Empirical default value: `-1` (infinite)

Please make default values consistent between TypeScript and Web versions of the documentation as many of us rely on TypeScript LSP for documentation.

---

This is a 📕 documentation issue

### PR DESCRIPTION
**Pull request by nija-at**
The defaults documented for `maxRecordAge` and `retryAttempts`
properties for event sources that are 'stream' type were documented
incorrectly.

The implementation falls back to the defaults provided by
CloudFormation.

fixes #13908

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-lambda-event-sources/lib/stream.ts [hunk 1]
```diff
@@ -41,7 +41,7 @@ export interface StreamEventSourceProps {
    * * Minimum value of 60 seconds
    * * Maximum value of 7 days
    *
-   * @default Duration.days(7)
+   * @default - the record is available for processing until it expires
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-lambda-event-sources/lib/stream.ts:44]: Isn't this a bit cyclic? Don't we want to know what the actual lifetime is?

**Review by rix0rrr — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-lambda-event-sources/lib/stream.ts (hunk 1 above)
Comment (nija-at) [reply packages/@aws-cdk/aws-lambda-event-sources/lib/stream.ts:44]: This will depend on the AWS service's own default and any customization the user might have done to the original resource.
For example, in Kinesis, the default (and max) is 24h but can be configured to any value less than that.

How do you propose we document this?

Comment (rix0rrr) [reply packages/@aws-cdk/aws-lambda-event-sources/lib/stream.ts:44]: `@default - the expiration delay configured on the Kinesis stream` ?

**Review by rix0rrr — APPROVED** [review]

File: packages/@aws-cdk/aws-lambda-event-sources/lib/stream.ts (hunk 1 above)
Comment (nija-at) [reply packages/@aws-cdk/aws-lambda-event-sources/lib/stream.ts:44]:
```suggestion
   * @default - the retention period configured on the stream
```
