### PR TITLE
fix(ssm): AWS::EC2::Image::Id parameter type

### LINKED ISSUE #4013: "AWS::SSM::Parameter::Value<String>" should be  AWS::SSM::Parameter::Value<AWS::EC2::Image::Id> for /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
### What is the problem?

Running cfn-lint on JSON file get Rule W2506 lint 
(venv) C:\>cfn-lint packages\bitcode\templates\bitcode-sky-03app-prod-0
-1-1.template.json
W2506 Parameter SsmParameterValueawsserviceamiamazonlinuxlatestamzn2amihvmx8664gp2C96584B6F00A464EAD1953AFF4B05
118Parameter should be of type [AWS::EC2::Image::Id, AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>]
packages\bitcode\templates\bitcode-sky-03app-prod-0-1-1.template.json:413:5

JSON looks like:
```
"Parameters": {
    "SsmParameterValueawsserviceamiamazonlinuxlatestamzn2amihvmx8664gp2C96584B6F00A464EAD1953AFF4B05118Parameter": {
      "Type": "AWS::SSM::Parameter::Value<String>",
      "Default": "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
    }
  },
```

### Expected 
Value in JSON to meet cfn-lint cloudformation Specs W2506
```
"Parameters": {
    "SsmParameterValueawsserviceamiamazonlinuxlatestamzn2amihvmx8664gp2C96584B6F00A464EAD1953AFF4B05118Parameter": {
      "Type": "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>",
      "Default": "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
    }
  },
```

### Reproduction Steps
Run cdk synth which calls machine-image

### Environment

  - **CDK CLI Version:**  1.6.1
  - **Module Version:** aws-ec-2
  - **OS:**  Windows 10
  - **Language:** TypeScript 
  - **cfn-python-lint:**  0.24.1

From https://github.com/aws-cloudformation/cfn-python-lint

### Other information
In the code search :  multiple locations shows it as <String> not <AWS::EC2::Image::Id>
example:
packages/@aws-cdk/aws-autoscaling/test/integ.amazonlinux2.expected.json
Shows it as 
``` 
"Type": "AWS::SSM::Parameter::Value<String>",
```

Assume this  is set in:
In packages/@aws-cdk/aws-ec2/lib/machine-image.ts

### PR DESCRIPTION
**Pull request by nmussy**
* use `AWS::EC2::Image::Id` SSM type for AMI resolved images
* add `valueForTypedStringParameter` method to allow this override

Fixes #4013

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-ssm/lib/parameter.ts [hunk 1]
```diff
@@ -161,6 +168,13 @@ export interface StringParameterAttributes {
    * @default The latest version will be retrieved.
    */
   readonly version?: number;
+
+  /**
+   * The type of the string parameter
+   *
+   * @default "String"
+   */
+  readonly type?: string;
```
Comment (eladb) [inline packages/@aws-cdk/aws-ssm/lib/parameter.ts]: Maybe an enum?

Comment (nmussy) [reply packages/@aws-cdk/aws-ssm/lib/parameter.ts]: Yeah I was thinking about it, but it would have required refactoring and exporting these constants into an enum: https://github.com/aws/aws-cdk/blob/b996cf5753767c86bef595f334d893964f7133ed/packages/%40aws-cdk/aws-ssm/lib/parameter.ts#L155-L157

Is that alright with you?

Comment (rix0rrr) [reply packages/@aws-cdk/aws-ssm/lib/parameter.ts]: I think that'd be great.

Comment (rix0rrr) [reply packages/@aws-cdk/aws-ssm/lib/parameter.ts]: I would expect to be writing something like `ParameterType.STRING`.

**Comment by rix0rrr** [comment]
The types are only used by and inside CloudFormation, right? And they would not apply if you specify a `version`, because we would then fall into a `{{resolve}}` primitive which doesn't take the type at all, correct?

What kind of behavior does the type cause? What are the advantages of specifying it?

File: packages/@aws-cdk/aws-ssm/lib/parameter.ts (hunk 1 above)
Comment (nmussy) [reply packages/@aws-cdk/aws-ssm/lib/parameter.ts]: Done

**Comment by nmussy** [comment]
I frankly have no idea, sorry 😄

File: packages/@aws-cdk/aws-ssm/lib/parameter.ts [hunk 2]
```diff
@@ -145,9 +152,12 @@ abstract class ParameterBase extends Resource implements IParameter {
   }
 }
 
-const STRING_PARAM_TYPE = 'String';
-const SECURE_STRING_PARAM_TYPE = 'SecureString';
-const STRINGLIST_PARAM_TYPE = 'StringList';
+export enum ParameterType {
+  STRING = 'String',
```
Comment (eladb) [inline packages/@aws-cdk/aws-ssm/lib/parameter.ts]: add documentation to each one (paste from AWS docs)

Comment (nmussy) [reply packages/@aws-cdk/aws-ssm/lib/parameter.ts]: I couldn't find a proper documentation page describing the types, but I pieced something together

**Comment by rix0rrr** [comment]
Sorry to complain about this, but I would like to get back to the following exchange:

> > What kind of behavior does the type cause? What are the advantages of specifying it?

> I frankly have no idea, sorry 😄

Why are we doing this change then?

**Comment by nmussy** [comment]
I looked around when I made the PR for explicit documentation about this use-case, but couldn't find it. What I got is:
* [cfn-lint W2506](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/docs/rules.md) (from the original issue)
* [An example at the end of this blog post](https://aws.amazon.com/blogs/compute/query-for-the-latest-amazon-linux-ami-ids-using-aws-systems-manager-parameter-store/), describing this exact stack.

If anyone has a better idea, feel free to share.
