### PR TITLE
fix(ec2): userData in launchTemplate is created automatically when machineImege is provided

### LINKED ISSUE #23592: ec2: userData in launchTemplate is not created automatically even when machineImege is provided
### Describe the bug

Reading [this doc](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.LaunchTemplate.html#userdata), `userData` is expected to be automatically created when `machineImage` is provided.

> (optional, default: This Launch Template creates a UserData based on the type of provided machineImage; no UserData is created if a machineImage is not provided)

However, it is not working as expected; `userData` is not automatically created at all. See reproduction steps for the actual code.

### Expected Behavior

`userData` is automatically created when `machineImage` is provided.

### Current Behavior

`userData` is not created even when `machineImage` is provided.

### Reproduction Steps
Synthesize the below stack:

```ts
export class Ec2UserdataStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const launchTemplate = new ec2.LaunchTemplate(this, 'LaunchTemplate', {
      instanceType: new ec2.InstanceType('t3.small'),
      machineImage: new ec2.AmazonLinuxImage({
        generation: ec2.AmazonLinuxGeneration.AMAZON_LINUX_2,
      }),
    });

    // this will cause an error
    launchTemplate.userData!.addCommands("yum -y update")
  }
}
```

and we get the following error:

```
/../ec2-userdata/lib/ec2-userdata-stack.ts:26
    launchTemplate.userData!.addCommands("yum -y update")
                             ^
TypeError: Cannot read properties of undefined (reading 'addCommands')
```

### Possible Solution

Current implementation is [here](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-ec2/lib/launch-template.ts#L560). We need to add code for creating userData depending on machineImage.

I guess we can follow the below implementation in `ec2.Instance`:

https://github.com/aws/aws-cdk/blob/f178c98d4473d8bb8d46d80c076fa520d03c623b/packages/%40aws-cdk/aws-ec2/lib/instance.ts#L349-L351

### Additional Information/Context
Adding this feature will not be a breaking change because we are just adding empty userData to launchTemplates whose userData was not specified explicitly, and it will not have any effect on the existing behavior.

### CDK CLI Version

2.59.0

### Framework Version

2.59.0

### Node.js Version

v16.18.1

### OS

macOS

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by tmokmss**
closes #23592

Reading through the discussion in PR https://github.com/aws/aws-cdk/pull/12385, which introduced the original code, I could not find any reason not to create userData when machineImage is provided. They also agreed with the design [here](https://github.com/aws/aws-cdk/pull/12385#discussion_r564614928), but it seems it accidentally became out of scope at the time.

This change should not be considered as a breaking change because we are just adding empty userData to launchTemplates whose userData is not specified explicitly, and it will not have any effect on the existing behavior.

* Users who already sets a userData explicitly:
   * will not see any change to their synthesized template, as this PR only modifies userData when it is not set explicitly.
* Users who is not using userData:
   * will see a userData is added to their template. But the userData is empty and does nothing. It should not have any effect on the previous behavior.

----

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [X] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [X] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by tmokmss** [comment]
hmm this change will require many downstream snapshots to be updated...

**Comment by tmokmss** [comment]
@rix0rrr @ddneilson Hi, what do you think of this change? I'd like to know if I'm missing about why the userData was not created in the original PR.

File: packages/@aws-cdk/aws-ec2/lib/launch-template.ts [hunk 1]
```diff
@@ -591,9 +591,14 @@ export class LaunchTemplate extends Resource implements ILaunchTemplate, iam.IGr
...
-    if (props.userData) {
-      this.userData = props.userData;
+    const imageConfig: MachineImageConfig | undefined = props.machineImage?.getImage(this);
+    if (imageConfig) {
+      this.osType = imageConfig.osType;
+      this.imageId = imageConfig.imageId;
     }
+
+    // priority: prop.userData -> userData from machineImage -> undefined
+    this.userData = props.userData ?? imageConfig?.userData;
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-ec2/lib/launch-template.ts:601]: Why can't we do

```suggestion
    if (props.userData || imageConfig?.userData) {
      this.userData = props.userData ?? imageConfig?.userData;
    }
```

and avoid the change to the templates? I understand that those won't require replacement or interruption, but we try to avoid changes to your diff caused only by upgrading. We'd have to put this behind a feature flag.

**Review by comcalvi — CHANGES_REQUESTED** [review]
This stack:

```
export class Ec2UserdataStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const launchTemplate = new ec2.LaunchTemplate(this, 'LaunchTemplate', {
      instanceType: new ec2.InstanceType('t3.small'),
      machineImage: new ec2.AmazonLinuxImage({
        generation: ec2.AmazonLinuxGeneration.AMAZON_LINUX_2,
      }),
    });

    // this will cause an error
    launchTemplate.userData!.addCommands("yum -y update")
```

results in an error. 

We can either update the docstring to reflect the current behavior or change the default so that `userData` is created by default. Why would we want `userData` to be created by default? I'd prefer we leave the current behavior and just update the docstring

**Comment by tmokmss** [comment]
The reasons I'd like to add this feature are:

1. It will be more convenient and ergonomic

```ts
    // previously
    // more code, duplicated knowledge about the instance OS
    const userData = ec2.UserData.forLinux();
    const launchTemplate = new ec2.LaunchTemplate(this, 'LaunchTemplate', {
      instanceType: new ec2.InstanceType('t3.small'),
      machineImage: new ec2.AmazonLinuxImage({
        generation: ec2.AmazonLinuxGeneration.AMAZON_LINUX_2,
      }),
      userData,
    });
    launchTemplate.userData!.addCommands("yum -y update")

    // becomes
    const launchTemplate = new ec2.LaunchTemplate(this, 'LaunchTemplate', {
      instanceType: new ec2.InstanceType('t3.small'),
      machineImage: new ec2.AmazonLinuxImage({
        generation: ec2.AmazonLinuxGeneration.AMAZON_LINUX_2,
      }),
    });
    launchTemplate.userData!.addCommands("yum -y update")
```

2. It will be consistent (and less confusing) with the behavior of the ec2.Instance construct.

```ts
// we can do this
    const instance = new ec2.Instance(this, 'Instance', {
      vpc,
      instanceType: new ec2.InstanceType('t3.small'),
      machineImage: new ec2.AmazonLinuxImage({
        generation: ec2.AmazonLinuxGeneration.AMAZON_LINUX_2,
      }),
    });
    instance.userData!.addCommands("yum -y update")
```

**Comment by MrArnoldPalmer** [comment]
hey @tmokmss, so I agree that making `LaunchTemplate` behave closer to `Instance` is worthwhile, but I do think @comcalvi is right that it will have to be behind a feature flag. Even if the behavior of resources for users who aren't specifying any user data is technically the same, changing the behavior of the the `asg.userData` getter [to throw when it previous didn't](https://github.com/aws/aws-cdk/pull/23593/files#diff-a495d44be0fe2ba21a619121ea78430f3288b5d924c40d7ca16482ee73d79078) and otherwise changing properties on construct instances that[ used to undefined to now not](https://github.com/aws/aws-cdk/pull/23593/files#diff-8d92a1dffa7849c491550a30187516eddd3cb8a0dade398d36a56bddeff986e7) can break some users code.

Reading through that discussion though I see some mention about the concept of "empty" user data not being easily defined. In the autoscaling snapshots we see the addition of

```json
     "UserData": {
      "Fn::Base64": "#!/bin/bash"
     }
```

Does an ` ec2.Instance` resource without user data defined also receive this same "empty" bash script?

**Comment by tmokmss** [comment]
Hi @MrArnoldPalmer OK, I agree with the possibility of breaking someone's code, so I'll add a feature flag for this.
As for empty UserData, yes, a shebang will also appear in an ec2.Instance template without explicit userData. 

For example, this code:

https://github.com/aws/aws-cdk/blob/5a0c627015619449cc47cedbfdaf931f09739193/packages/%40aws-cdk/aws-globalaccelerator-endpoints/test/integ.globalaccelerator.ts#L29-L33

will be synthesized to this:

https://github.com/aws/aws-cdk/blob/5a0c627015619449cc47cedbfdaf931f09739193/packages/%40aws-cdk/aws-globalaccelerator-endpoints/test/integ.globalaccelerator.js.snapshot/integ-globalaccelerator.template.json#L578-L580

**Comment by tmokmss** [comment]
@comcalvi @MrArnoldPalmer  I added a feature flag named `@aws-cdk/aws-ec2:launchTemplateDefaultUserData`. Hope you can review it 🙏

**Review by comcalvi — APPROVED** [review]
lgtm, leaving dnm so @MrArnoldPalmer can take a look.

**Comment by tmokmss** [comment]
@comcalvi 
CI failed on the merge commit bb4311bf05b64cc95a89a319743e3883fd3c5b15, but I don't have access to the CodeBuild log. Could you take a look at it just in case?
