### PR TITLE
fix(sns-subscriptions): enable cross region subscriptions to sqs and lambda

### LINKED ISSUE #7044: SQS subscription to cross-region SNS topic not working via addSubscription
When I try to subscribe an SQS queue in one account to an SNS topic in another account _and another region_ using `topic.addSubscription()`, I get error "Invalid parameter: TopicArn." This works when adding a subscription to a the same account/region or a different account but same region. But it fails when subscribing to a different account and region:

```ts
topicInRegionA.addSubscription(new SqsSubscription(queueInRegionB));
```

I thought this was supposed to be fixed by #3842?

### Reproduction Steps

1. Try to subscribe an SQS queue to a topic in another region using `addSubscription()`

### Error Log

```txt
1/13 | 5:11:07 PM | CREATE_FAILED        | AWS::SNS::Subscription          | MyQueue/MyServicealphauswest2MyTopic915AE08F (MyQueueMyServicealphauswest2MyTopic915AE08F58613436) Invalid parameter: TopicArn (Service: AmazonSNS; Status Code: 400; Error Code: InvalidParameter; Request ID: ...)
        new Subscription (...CDK/node_modules/@aws-cdk/aws-sns/lib/subscription.js:29:9)
        \_ Topic.addSubscription (...CDK/node_modules/@aws-cdk/aws-sns/lib/topic-base.js:23:9)
        \_ AppStack.bindCustomComponents (...CDK/dist/lib/custom/app-stack.js:48:43)
        \_ Object.<anonymous> (...CDK/dist/lib/app.js:66:18)
        ...
```

### Environment

  - **CLI Version      : 1.30.0 (build 4f54ff7)**
  - **OS               : Red Hat variant**
  - **Language         : TypeScript**

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by corymhall**
fixing cross region subscriptions to SQS and Lambda. This PR handles a
couple different scenarios. This only applies to SNS topics that are
instanceof sns.Topic, it does not apply to imported topics (sns.ITopic).
The current behavior for imported topics will remain the same.

1. SNS Topic and subscriber (sqs or lambda) are created in separate
   stacks with explicit environment.

In this case if the `region` is different between the two stacks then
the topic region will be provided in the subscription.

2. SNS Topic and subscriber (sqs or lambda) are created in separate
   stacks, and _both_ are env agnostic (no explicit region is provided)

In this case a region is not specified in the subscription resource,
which means it is assumed that they are both created in the same region.
The alternatives are to either throw an error telling the user to
specify a region, or to create a CfnOutput with the topic region. Since
it should be a rare occurrence for a user to be deploying a CDK app with
multiple env agnostic stacks that are meant for different environments,
I think the best option is to assume same region.

3. SNS Topic and subscriber (sqs or lambda) are created in separate
   stacks, and _one_ of them are env agnostic (no explicit region is provided)

In this case if the SNS stack has an explicit environment then we will
provide that in the subscription resource (assume that it is cross
region). If the SNS stack is env agnostic then we will do nothing
(assume they are created in the same region).

fixes #7044,#13707

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-sns-subscriptions/lib/lambda.ts [hunk 1]
```diff
@@ -36,6 +36,12 @@ export class LambdaSubscription implements sns.ITopicSubscription {
       principal: new iam.ServicePrincipal('sns.amazonaws.com'),
     });
 
+    // if the topic and function are created in different stacks
+    // then we need to make sure the topic is created first
+    if (topic.stack !== this.fn.stack) {
```
Comment (njlynch) [inline packages/@aws-cdk/aws-sns-subscriptions/lib/lambda.ts:41]: Is it possible this topic is an imported (`ITopic`)? If so, is this necessary?

My spidey sense tingles hard whenever we add a dependency like this; I feel like these types of aides lead to circular dependency bugs that aren't obvious and don't come to light until the next release. Just want to limit the blast radius to as small a use case as possible.

Comment (corymhall) [reply packages/@aws-cdk/aws-sns-subscriptions/lib/lambda.ts:41]: That's a good point. I could add a type check here as well. I did run into issues when testing this if the dependency is not explicit, the deployment would fail because the function (or sqs) stack was getting created before the topic stack.

Comment (corymhall) [reply packages/@aws-cdk/aws-sns-subscriptions/lib/lambda.ts]: updated.

**Review by njlynch — APPROVED** [review]
:+1:
