### PR TITLE
fix(cloudtrail): Trail fails during resource creation due to invalid template properties when management events are 'None' 

### LINKED ISSUE #15488: (aws-cloudtrail): incorrect Trail synthesis when management_events is False
Deploying a CloudTrail Trail which has `management_events=ReadWriteType.NONE` and a data event (S3 event selector) raises the following error in CFN:
```
Invalid combination of parameters in EventSelectors. When includeManagementEvents is false, DataResources must not be empty (Service: AWSCloudTrail; Status Code: 400; Error Code: InvalidEventSelectorsException; Request ID: 0dfd3be1-f327-4e8b-aa77-64a07c59059c; Proxy: null)
```

### Reproduction Steps
Below code will reproduce the error. Make sure to replace the `account` with a valid AWS account ID:
```
#!/usr/bin/env python3

from aws_cdk.aws_cloudtrail import ReadWriteType, S3EventSelector, Trail
from aws_cdk.aws_kms import Key
from aws_cdk.aws_s3 import BlockPublicAccess, Bucket, BucketAccessControl, BucketEncryption
from aws_cdk.core import App, Construct, Environment, RemovalPolicy, Stack

class TrailBugStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        cmk: Key = Key(
            self,
            "bucket-cmk",
            trust_account_identities=True,
        )

        bucket: Bucket = Bucket(
            self,
            "bucket",
            bucket_name=f"my-bucket-{self.region}-{self.account}",
            encryption=BucketEncryption.KMS,
            encryption_key=cmk,
            versioned=False,
            access_control=BucketAccessControl.BUCKET_OWNER_FULL_CONTROL,
            block_public_access=BlockPublicAccess.BLOCK_ALL,
            removal_policy=RemovalPolicy.DESTROY,
        )

        Trail(
            self,
            "trail",
            is_multi_region_trail=False,
            include_global_service_events=False,
            management_events=ReadWriteType.NONE,
        ).add_s3_event_selector(
            s3_selector=[
                S3EventSelector(bucket=bucket)
            ]
        )


app = App()
TrailBugStack(app, "TrailBugStack", env=Environment(account="111111111111", region="us-east-1"))

app.synth()
```

Now for the interesting part. I have used `cfn-flip` to flip the synthesized template from JSON to YAML and the event selector section of the trail definition looks like this:
```
      EventSelectors:
        - IncludeManagementEvents: false
        - DataResources:
            - Type: AWS::S3::Object
              Values:
                - !Join
                  - ''
                  - - !GetAtt 'bucket43879C71.Arn'
                    - /
```
 If you remove the hyphen before `DataResources`:
```
      EventSelectors:
        - IncludeManagementEvents: false
          DataResources:
            - Type: AWS::S3::Object
              Values:
                - !Join
                  - ''
                  - - !GetAtt 'bucket43879C71.Arn'
                    - /
```
and try to deploy the resulting YAML template, it succeeds. Whereas with the hyphen it fails. So it looks to me like the `cdk synth` for a CloudTrail Trail is broken.

### Environment

  - **CDK CLI Version : 1.110.1**
  - **Framework Version: 1.110.1**
  - **Node.js Version: v16.4.0** 
  - **OS: macOS Catalina**
  - **Language (Version): Python 3.7.7** 

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by 4naesthetic**
#### Overview 

Currently CDK produces invalid CloudFormation that fails validation by the CloudTrail API upon deployment when setting the `managementEvents` parameter to `ReadWriteType.NONE`.

Although this is a contribution to a stable module, I consider this change to not have breaking changes as the original implementation generates CloudFormation that would result in stack deployment failure so is currently broken.

#### Behaviour changes

*Setting `managementEvents` to `ReadWriteType.NONE`*

**Old behaviour:** Successfully synthesises but produces CloudFormation that fails to deploy.
**New behaviour:** Fails synthesis with a validation error if no additional event selectors are added to the trail, as the default behaviour of CloudTrail is to enable management events if no event selectors are provided. Sets `includeManagementEvents` to `false` by default when new event selectors are added unless overridden explicitly by the user.

#### Other options considered

The previous PR had a suggestion to just always set `includeManagementEvents` to `false` when adding additional event selectors rather than only setting it to `false` when the Trail was created with `ReadWriteType.NONE`. However, this would break backwards compatibility for some scenarios (such as where users don't set `managementEvents` when creating the trail and later add an event selector, as well as a bunch of other esoteric edge cases).

#### Related

Previous PR that was closed for staleness (#16387).

Closes #15488

----

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [X] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [X] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-cloudtrail/lib/cloudtrail.ts [hunk 1]
```diff
@@ -403,7 +403,7 @@ export class Trail extends Resource {
   }
 
   /**
-   * Log all Lamda data events for all lambda functions the account.
+   * Log all Lambda data events for all lambda functions the account.
```
Comment (HBobertz) [inline packages/@aws-cdk/aws-cloudtrail/lib/cloudtrail.ts:406]: good catch

File: packages/@aws-cdk/aws-cloudtrail/test/cloudtrail.test.ts [hunk 2]
```diff
@@ -625,19 +625,77 @@ describe('cloudtrail', () => {
         });
       });
 
-      test('managementEvents set to None correctly turns off management events', () => {
+      test('not provided and managementEvents set to None throws', () => {
```
Comment (HBobertz) [inline packages/@aws-cdk/aws-cloudtrail/test/cloudtrail.test.ts:628]: For this test can we specify the error instead of just "throws", i.e. using `toThrowError()`. I think the exception is `InvalidEventSelectorsException`, but whatever the error we expect is.

**Review by HBobertz — CHANGES_REQUESTED** [review]
looks good overall. I'd just like to see a minor change to a test

File: packages/@aws-cdk/aws-cloudtrail/test/cloudtrail.test.ts (hunk 2 above)
Comment (seawildau) [reply packages/@aws-cdk/aws-cloudtrail/test/cloudtrail.test.ts:628]: Is it just the description you want updated? As far as I understand, exceptions thrown using `node.addValidation(...)` use a generic `throw new Error(...)` rather than a custom exception class.

**Review by HBobertz — DISMISSED** [review]
Gotcha I think I misunderstood exactly what toThrow and what toThrowError did. I just wanted to ensure it wouldn't just capture any error, and it would look for that specific one. But it may have been doing that with toThrow anyway. Title is also more descriptive which always helps. Looks good to me

**Review by TheRealAmazonKendra — APPROVED** [review]
Mergify's gonna Mergify. Not sure why it's not working right now but I'm re-approving after manually updating.
