### PR TITLE
fix(codebuild): fails on using PR Events together with FILE_PATH filters in a FilterGroup

### LINKED ISSUE #8867: [aws-codebuild]  Codebuild source Github PR doesn't work with FILE_PATH
Trying to create codebuild project with github source and adding pull request created/updated trigger with file_path filter results in an error, while this succeeds doing in the UI.

### Reproduction Steps

```codebuild.FilterGroup.inEventOf(codebuild.EventAction.PULL_REQUEST_UPDATED).andFilePathIsNot("^my_path.*")```

### Error Log

```
node_modules/@aws-cdk/aws-codebuild/lib/source.ts:411
      throw new Error('A file path condition cannot be added if a Group contains any event action other than PUSH');
            ^
Error: A file path condition cannot be added if a Group contains any event action other than PUSH
    at FilterGroup.addFilePathFilter (node_modules/@aws-cdk/aws-codebuild/lib/source.ts:411:13)
    at FilterGroup.andFilePathIsNot (node_modules/@aws-cdk/aws-codebuild/lib/source.ts:360:17)
    at new CodebuildStack (src/codebuild-stack.ts:16:93)
    at Object.<anonymous> (bin/codebuild.ts:9:15)
```

### Environment

  - **CLI Version      :** 
  - **Framework Version:** 1.49.0
  - **Node.js Version:** 
  - **OS               :** 
  - **Language (Version):**  TypeScript (3.9.5)

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by JaseKirby**
Remove blocking validation on GitHub webhook file path filter when `event` is `PUSH` only.

Fixes #8867

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-codebuild/test/test.codebuild.ts [hunk 1]
```diff
@@ -582,6 +582,36 @@ export = {
 
       test.done();
     },
+    'with GitHub source including PULL_REQUEST_CREATED Event and FILE_PATH filter'(test: Test) {
```
Comment (skinny85) [inline packages/@aws-cdk/aws-codebuild/test/test.codebuild.ts:585]: Can you change the below test instead? To show that it works now.

File: packages/@aws-cdk/aws-codebuild/test/test.codebuild.ts [hunk 2]
```diff
@@ -1631,17 +1661,6 @@ export = {
...
-      const filterGroup = codebuild.FilterGroup.inEventOf(codebuild.EventAction.PULL_REQUEST_CREATED,
-        codebuild.EventAction.PUSH);
-
-      test.throws(() => {
-        filterGroup.andFilePathIsNot('.*\\.java');
-      }, /A file path condition cannot be added if a Group contains any event action other than PUSH/);
-
-      test.done();
-    },
-
```
Comment (skinny85) [inline packages/@aws-cdk/aws-codebuild/test/test.codebuild.ts:1644]:
```suggestion
    'can have file path conditions if the Group contains PUSH and PR_CREATED events'(test: Test) {
      codebuild.FilterGroup.inEventOf(
        codebuild.EventAction.PULL_REQUEST_CREATED,
        codebuild.EventAction.PUSH)
        .andFilePathIsNot('.*\\.java');

      test.done();
    },
```
