### PR TITLE
fix(stepfunctions): unable to run distributed map when only defined in nested StateGraphs

### LINKED ISSUE #35391: stepfunctions: DistributedMaps cannot be run if they are not declared in top level StateGraph
### Describe the bug

DistributedMaps only in the top level state graph add policies to the state machine. For example, if you only create a distributed map in a `Parallel` branch, it does not add any policies to the state machine, and will therefore fail to run.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Library Version

_No response_

### Expected Behavior

Distributed Maps declared in any state graph, nested or otherwise should add permissions to the state machine

### Current Behavior

The state machine execution fails to run with a missing `StartExecution` permissions error. Some issues with more details:

#29266 #28820

### Reproduction Steps

`parallel`, when added to a state machine, will fail to run.

```ts
const map = new DistributedMap(this, 'map').itemProcessor(new Pass(this, 'pass'))
const parallel = new Parallel(this, 'parallel').branch(map)
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### AWS CDK Library version (aws-cdk-lib)

v2.213.0

### AWS CDK CLI version

2.1023.0

### Node.js Version

20

### OS

Macos

### Language

TypeScript

### Language Version

_No response_

### Other information

I will make a PR for this once https://github.com/aws/aws-cdk/pull/34760 is merged, as the changes conflict. The plan is to just do a BFS of all state graphs to find all reachable states in the `StateGraph.bind` method.

### PR DESCRIPTION
**Pull request by Kasra-G**
### Issue \#

Closes #35391.

### Reason for this change

When the only instances of DistributedMap states were inside nested StateGraphs (most commonly reported as Parallel branches, see https://github.com/aws/aws-cdk/issues/28820), `StateGraph.bind` would fail to find these DistributedMaps and thus fail to add the necessary DistributedMap policies to the state machine's execution role. This means the state machine execution would fail as soon as it got to the nested DistributedMap state.

This was originally included in https://github.com/aws/aws-cdk/pull/34760, but aligned that it should go into its own PR https://github.com/aws/aws-cdk/pull/34760#discussion_r2313620609

### Description of changes

This change allows DistributedMap states in any level of nested StateGraphs to be discovered and considered for the DistributedMap policy additions.

Changes:
- Does a BFS of all nested StateGraphs when calling the root StateGraph's `bind()` method to find DistributedMap states
- DistributedMap states inside Parallel branches now add distributed map policies to the state machine as expected

The idea of recursing through state graphs can be attributed to https://github.com/aws/aws-cdk/pull/29913, but to avoid the recursion, I just converted the logic to use a loop.

### Describe any new or updated permissions being added

State machines with a DistributedMap state inside a Parallel branch will now receive the proper policy for execution (Documented here: https://docs.aws.amazon.com/step-functions/latest/dg/iam-policies-eg-dist-map.html#iam-policy-run-dist-map)

### Description of how you validated changes

Unit & new Integ test that deploys and runs a StateMachine with a DistributedMap inside a Parallel state.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map-parallel.ts [hunk 1]
```diff
@@ -0,0 +1,82 @@
+import * as s3 from 'aws-cdk-lib/aws-s3';
+import * as cdk from 'aws-cdk-lib/core';
+import * as integ from '@aws-cdk/integ-tests-alpha';
+import * as sfn from 'aws-cdk-lib/aws-stepfunctions';
+
+const CSV_KEY = 'my-key.csv';
+
+class DistributedMapParallelStack extends cdk.Stack {
```
Comment (kumvprat) [inline packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map-parallel.ts:8]: Is it possible to test out a bit more complex graph structure to ensure all subgraphs are properly traversed in the `bind` method ? (couple of level of nesting and distributed map states)

Comment (Kasra-G) [reply packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distributed-map-parallel.ts:8]: Sure, though I think I would prefer to do this via unit tests as we don't actually need to run the state machine to see if `bind()` is picking up the distributed map states. Let me know if you disagree. I was actually hesitant to add an integ test as theres no real cloudformation difference between running a distributed map inside a parallel state vs at the top level (no extra policies, etc)

File: packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts [hunk 2]
```diff
@@ -430,6 +430,201 @@ describe('State Machine', () => {
...
+    };
+
+    // THEN
+    Template.fromStack(stack).hasResourceProperties('AWS::IAM::Policy', {
+      PolicyDocument: {
+        Statement: Match.arrayWith([
+          {
+            Action: 'states:RedriveExecution',
+            Effect: 'Allow',
+            Resource: [
```
Comment (Kasra-G) [inline packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts:615]: Maybe we should alphabetically order by map run label. Currently, if a user swaps around the state order it would cause a policy template change depending on which states were encountered first.

Comment (Kasra-G) [inline packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts:615]: Maybe we should sort the resources by map run label. Currently, if a user swaps around the state order it would cause a policy template change depending on which states were encountered first. This could potentially change existing templates though.

File: packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts [hunk 3]
```diff
@@ -430,6 +430,201 @@ describe('State Machine', () => {
...
+    // WHEN
+    const map = new sfn.DistributedMap(stack, 'Map State');
+    map.itemProcessor(new sfn.Pass(stack, 'Pass'));
+    const stateMachine = new sfn.StateMachine(stack, 'MyStateMachine', {
+      stateMachineName: 'MyStateMachine',
+      definitionBody: sfn.DefinitionBody.fromChainable(map.next(map)),
+    });
+    const stateMachineLogicalId = stack.getLogicalId(stateMachine.node.defaultChild as sfn.CfnStateMachine);
+    const stateMachineRoleLogicalId = stack.getLogicalId(stateMachine.role.node.defaultChild as iam.CfnRole);
+    const stateMachineNameTemplate = {
```
Comment (Kasra-G) [inline packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts:447]: Realizing now we could just change the implementation to use `stateMachine.stateMachineName` and avoid this select + split arn logic [here](https://github.com/aws/aws-cdk/blob/d7f211fe7b6134c1f1f95561f352cb7e66a7d387/packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts#L203). It would change existing policy templates, though, ~~but I think it could be worth it because it would be simpler logic and show up much more cleanly in the iam policy changeset view.~~ not sure if it is worth it

**Comment by Kasra-G** [comment]
Not able to reproduce the Codebuild PR Build failure locally. Not sure how my previous commit could have affected integ tests... only changes were in a unit test file. Edit: I see the 3 million line PR haha - I will rebase & re-run the integ test

File: packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts (hunk 2 above)
Comment (kumvprat) [reply packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts:615]: >Currently, if a user swaps around the state order it would cause a policy template change depending on which states were encountered first. This could potentially change existing templates though.

This would imply that the user changed the ordering of the interaction between stepfunction states right ?
As long as our logic to determine the execution arns is deterministic (and doesn't change policy ordering when nothing has changed) we should be okay.

If you have some examples/use-cases where this would be impractical, I would be happy to hear your thoughts on this

File: packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts (hunk 3 above)
Comment (kumvprat) [reply packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts:447]: I am unclear about what you mean by below (also the link does not work for me)

> Realizing now we could just change the implementation to use stateMachine.stateMachineName and avoid this select + split arn logic [here](https://github.com/aws/aws-cdk/pull/35417/files/fddcaa1db6fb103671bb72493141ebae110b7e0a#diff-4559100aa146ca7b99f11f075f163b4abf1a86601f8f1818208eeb34a70e59bfR206).

Can you give some example around what you propose to change ?

File: packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts (hunk 2 above)
Comment (Kasra-G) [reply packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts:615]: It is deterministic, so in that case we are okay. I was thinking user might see unexpected iam policy change to review when they just did something like switch parallel branch declaration order, eg
```ts
parallel.branch(map1).branch(map2)
```
to
```ts
parallel.branch(map2).branch(map1)
```
which I think causes reordering of the resources in the distributed map run policy (assuming map1 and map2 are labeled)

File: packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts (hunk 3 above)
Comment (Kasra-G) [reply packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts:447]: Sure - Here's the fixed link (I updated the above as well) 
https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-stepfunctions/lib/state-graph.ts#L200-L205

I mean that I realized we are doing unnecessary ARN splitting to get the state machine name

```ts
    return Stack.of(stateMachine).formatArn({
      resource: 'execution',
      service: 'states',
      resourceName: `${Arn.split(stateMachine.stateMachineArn, ArnFormat.COLON_RESOURCE_NAME).resourceName}/${mapRunLabel}:*`,
      arnFormat: ArnFormat.COLON_RESOURCE_NAME,
    });
```

when it could just be `stateMachine.stateMachineName`

```ts
    return Stack.of(stateMachine).formatArn({
      resource: 'execution',
      service: 'states',
      resourceName: `${stateMachine.stateMachineName}/${mapRunLabel}:*`,
      arnFormat: ArnFormat.COLON_RESOURCE_NAME,
    });
```

Just wondering if its worth changing (it would add a few lines to the PR as the tests need to be updated)

Comment (kumvprat) [reply packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts:447]: I am not sure about the full implications of this change.
We can leave it the same for the scope of this PR

**Review by kumvprat — APPROVED** [review]
