### PR TITLE
fix(core): file asset publishing role not used in `cdk diff` to upload large templates

### LINKED ISSUE #29936: (core): file asset publishing role is not used while performing cdk diff with larger templates
### Describe the bug

Env's role is being used to upload the template to create the read-only change set to get the diff. If the user/role lacks permissions then an access denied error is thrown and fallback to template differences.

### Expected Behavior

File asset publish role to be used to upload templates for cdk diff

### Current Behavior

fail: Access Denied
Failed to publish one or more assets. See the error messages above for more information.

### Reproduction Steps

1. Create IAM user or role with deny all S3 actions.

2. Configure an environment with the role/user

3. Create a CDK project with one SQS queue 
```
new sqs.Queue(this, `Queue`, {});
```

4. Deploy 
5. Add similare resources and `cdk diff -v`
```
for (let i = 0; i < 300; i++) {
      new sqs.Queue(this, `Queue${i}`, {
      });
    }   
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.138.0

### Framework Version

_No response_

### Node.js Version

20.10

### OS

macos

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by sumupitchayan**
Closes #29936 

### Reason for this change

When running `cdk diff` on larger templates, the CDK needs to upload the diff template to S3 to create the ChangeSet. However, the CLI is currently not using the the [file asset publishing role](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml#L275) to do so and is instead using the IAM user/role that is configured by the user in the CLI - this means that if the user/role lacks S3 permissions then the `AccessDenied` error is thrown and users cannot see a full diff.

### Description of changes

This PR ensures that the `FileAssetPublishingRole` is used by `cdk diff` to upload assets to S3 before creating a ChangeSet by:
- Deleting the `makeBodyParameterAndUpload` function which was using the deprecated `publishAssets` function from [deployments.ts](https://github.com/aws/aws-cdk/blob/4b00ffeb86b3ebb9a0190c2842bd36ebb4043f52/packages/aws-cdk/lib/api/deployments.ts#L605)
- Building and Publishing the template file assets inside the `uploadBodyParameterAndCreateChangeSet` function within `cloudformation.ts` instead

### Description of how you validated changes

Integ test that deploys a simple CDK app with a single IAM role, then runs `cdk diff` on a large template change adding 200 IAM roles. I asserted that the logs did not contain the S3 access denied permissions errors, and also contained a statement for assuming the file publishing role. Reused the CDK app for the integ test from this [PR](https://github.com/aws/aws-cdk/pull/30568) by @sakurai-ryo which tried fixing this issue by adding another Bootstrap role (which we decided against).

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk/lib/api/deployments.ts [hunk 1]
```diff
@@ -350,11 +351,11 @@ export class Deployments {
     const cfn = stackSdk.cloudFormation();
 
     // Upload the template, if necessary, before passing it to CFN
-    const cfnParam = await makeBodyParameterAndUpload(
+    const cfnParam = await makeBodyParameter(
       stackArtifact,
       resolvedEnvironment,
+      new AssetManifestBuilder(),
```
Comment (sumupitchayan) [inline packages/aws-cdk/lib/api/deployments.ts:357]: syntax/style question: `makeBodyParameter` takes an `AssetManifestBuilder()` as an argument - should I make this argument optional so you don't have to pass in a `new AssetManifestBuilder()` like this if you don't want to?

File: packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts [hunk 2]
```diff
@@ -1031,6 +1031,35 @@ integTest(
...
+        NUMBER_OF_ROLES: '200',
+      },
+    });
+
+    // Assert that S3 upload and changeset creation error messages were not thrown:
+    expect(diff).not.toContain('Call failed: getBucketLocation');
+    expect(diff).not.toContain('not authorized to perform: s3:GetBucketLocation on resource');
+    expect(diff).not.toContain('Could not create a change set, will base the diff on template differences');
+
+    // Assert that the CLI assumes the file publishing role:
```
Comment (sumupitchayan) [inline packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts:1057]: Not sure if there is a better way to assert than checking for log statements like these ?

File: packages/aws-cdk/lib/api/deployments.ts (hunk 1 above)
Comment (sumupitchayan) [reply packages/aws-cdk/lib/api/deployments.ts:357]: I see it [used one other time in deploy-stack.ts here](https://github.com/aws/aws-cdk/blob/b0e4a544aecce86e8b41e7cd148a139c2e34bfbd/packages/aws-cdk/lib/api/deploy-stack.ts#L286) where it looks like we do want to pass in an `AssetManifestBuilder`, so I don't think we'd want to remove the argument entirely

**Comment by rix0rrr** [comment]
> Deleting the broken makeBodyParameterAndUpload function which wasn't actually uploading anything to S3.

This is not a correct statement. It definitely was uploading things to S3.

File: packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts [hunk 3]
```diff
@@ -1031,6 +1031,35 @@ integTest(
...
+      verbose: true,
+      modEnv: {
+        NUMBER_OF_ROLES: '200',
+      },
+    });
+
+    // Assert that S3 upload and changeset creation error messages were not thrown:
+    expect(diff).not.toContain('Call failed: getBucketLocation');
+    expect(diff).not.toContain('not authorized to perform: s3:GetBucketLocation on resource');
+    expect(diff).not.toContain('Could not create a change set, will base the diff on template differences');
```
Comment (rix0rrr) [inline packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts:1055]: This is not very robust testing. You're better off testing against something that you expect to see, vs something that you don't expect to see. There are a million things that could go wrong to make not exactly this error message show up.

File: packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts (hunk 2 above)
Comment (rix0rrr) [reply packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts:1057]: This will have to do.

File: packages/aws-cdk/lib/api/util/cloudformation.ts [hunk 4]
```diff
@@ -338,14 +340,54 @@ export async function createDiffChangeSet(options: PrepareChangeSetOptions): Pro
   return uploadBodyParameterAndCreateChangeSet(options);
 }
 
+/**
+ * Returns all file entries from an AssetManifestArtifact. This is used in the
+ * `uploadBodyParameterAndCreateChangeSet` function to find all template asset files to build and publish.
+ *
+ * Returns a tuple of [AssetManifest, FileManifestEntry[]]
+ */
+function entriesFromAssetManifestArtifact(artifact: cxapi.AssetManifestArtifact): [AssetManifest, FileManifestEntry[]] {
```
Comment (rix0rrr) [inline packages/aws-cdk/lib/api/util/cloudformation.ts:349]:
```suggestion
function fileEntriesFromAssetManifestArtifact(artifact: cxapi.AssetManifestArtifact): [AssetManifest, FileManifestEntry[]] {
```

?

File: packages/aws-cdk/lib/api/deployments.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/aws-cdk/lib/api/deployments.ts:357]: I agree that this looks sort of silly. But an `undefined` in the middle there is even sillier. Can we do some other refactor to tease out this useless parameter?

Comment (sumupitchayan) [reply packages/aws-cdk/lib/api/deployments.ts:357]: We could create another function called `makeBodyParameterFromNewManifest()` (or something like that) which takes all the same arguments as `makeBodyParameter` except for the `AssetManifestBuilder` and just calls `makeBodyParameter` with a new `AssetManifestBuilder`? Like so:

```ts
export async function makeBodyParameterFromNewManifest(
  stack: cxapi.CloudFormationStackArtifact,
  resolvedEnvironment: cxapi.Environment,
  resources: EnvironmentResources,
  sdk: ISDK,
  overrideTemplate?: any,
): Promise<TemplateBodyParameter> {
  return makeBodyParameter(stack, resolvedEnvironment, new AssetManifestBuilder(), resources, sdk, overrideTemplate);
}
```

Not sure if this is also a bit of silly API though.

**Review by rix0rrr — APPROVED** [review]
