### PR TITLE
fix(cli): short-lived credentials are not refreshed

### LINKED ISSUE #32287: CLI: short-lived credentials are not refreshed
### Describe the bug

If Role credentials are only valid for 15 minutes, and a deploy operation takes longer than that, the operation should complete successfully.

Make sure that credentials are correctly refreshed by the SDK.

### PR DESCRIPTION
**Pull request by rix0rrr**
The CLI immediately invokes credential *providers* to produce *credentials*, and passes the credentials around instead of the providers. This means that if short-lived credentials expire (like session credentials from roles), there is no way to refresh them.

CLI calls will start to fail if that happens.

To fix this, instead of resolving providers to credentials, pass providers around instead.

Implications for auth plugins
-------------

This widens the plugin protocol: the new plugin protocol *forced* a translation to V3 credentials, and had no way to return V3 providers. While it is now possible to return V3 Credential Providers from the plugin protocol, plugin writers cannot easily take advantage of that protocol because there have been ~8 CLI releases that only support V3 credentials and will fail at runtime of V3 providers are returned.

To support this, pass a new options argument into `getProvider()`: this will indicate whether V3 Providers are supported or not. Plugins can return a provider if the CLI indicates that it supports V3 providers, and avoid doing that if the CLI indicates it won't. That way, plugins can be rewritten to take advantage of returning V3 providers without crashing on CLI versions `2.167.0..(this releases)`.

This also affects #32111 in which the plugin contract is being moved.

Closes #32287.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk/lib/api/aws-auth/provider-caching.ts [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+ *
+ * Some credential providers in the SDKv3 are cached (the default Node
+ * chain, specifically) but most others are not.
+ *
+ * Since we want to avoid duplicate calls to `AssumeRole`, or duplicate
+ * MFA prompts or what have you, we are going to liberally wrap providers
+ * in caches which will return the cached value until it expires.
+ */
+export function makeCachingProvider(provider: AwsCredentialIdentityProvider): AwsCredentialIdentityProvider {
+  return memoize(
```
Comment (otaviomacedo) [inline packages/aws-cdk/lib/api/aws-auth/provider-caching.ts:15]: >Usage
>You probably shouldn't, at least directly.

A rebel, lol.
