### PR TITLE
fix(core): crossRegionReferences doesn't work when exporting to multiple regions

### LINKED ISSUE #24464: (core): crossRegionReference only works for first destination region
### Describe the bug

When referencing a value from a source stack in two destination regions, only the first region is granted permissions on the CrossRegionExportWriterCustomerResourceProvider/Role, resulting in a stack deployment failure with insufficient permissions on ssm:ListTagsForResource in the second destination region.

### Expected Behavior

Expected behaviour is for the IAM role to include each of the destination regions required.

### Current Behavior

**IAM Statement Changes:**
Resource: "arn:aws:ssm:ap-southeast-1:082966487824::parameter/cdk/exports/*"
Effect: Allow
Action: ssm:DeleteParameters, ssm:GetParameters,ssm:ListTagsForResource,ssm:PutParameter
Principal: AWS:${Custom::CrossRegionExportWriterCustomResourceProvider/Role}

**Error**
8:48:55 am | CREATE_FAILED        | Custom::CrossRegionExportWriter | ExportsWriterapsou...t2235C849A8E92266D
Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: User: arn:aws:sts::082966487824:assumed-role/sourceStack-
CustomCrossRegionExportWriterCustomRes-1L7WV0YX11H2H/sourceStack-CustomCrossRegionExportWriterCustomRes-XU6vlSVHMoXz is not authorized to perform: ssm:Lis
tTagsForResource on resource: arn:aws:ssm:ap-southeast-2:082966487824:parameter/cdk/exports/Region2Stack/sourceStackuseast1RefhostedZone861779BD20ED3C2C b
ecause no identity-based policy allows the ssm:ListTagsForResource action

### Reproduction Steps

Sample Repo Code:

import 'source-map-support/register';
import * as cdk from 'aws-cdk-lib';
import { Stack } from 'aws-cdk-lib';

const app = new cdk.App();
var sourceStack = new Stack(app, 'sourceStack', {  env: { account: process.env.CDK_DEFAULT_ACCOUNT, region: 'us-east-1' } });
var hostedZone = new cdk.aws_route53.HostedZone(sourceStack, "hostedZone", { zoneName: 'test.local'});

var destRegion1Stack = new Stack(app, 'Region1Stack',  {  env: { account: process.env.CDK_DEFAULT_ACCOUNT, region: 'ap-southeast-1' }, crossRegionReferences: true });
new cdk.aws_route53.TxtRecord(destRegion1Stack, "FirstARecord", { zone: hostedZone, recordName: 'ap-southeast-1', values: ['ap-southeast-1'] });

var destRegion2Stack = new Stack(app, 'Region2Stack',  {  env: { account: process.env.CDK_DEFAULT_ACCOUNT, region: 'ap-southeast-2' }, crossRegionReferences: true });
new cdk.aws_route53.TxtRecord(destRegion2Stack, "SecondARecord", { zone: hostedZone, recordName: 'ap-southeast-2', values: ['ap-southeast-2'] });

### Possible Solution

the IAM role should include permissions to all required regions.

### Additional Information/Context

_No response_

### CDK CLI Version

2.67.0 (build b6f7f39)

### Framework Version

_No response_

### Node.js Version

v18.13.0

### OS

MacOs/Linux/Agnostic

### Language

Typescript

### Language Version

Typescript (v10.9.1)

### Other information

_No response_

### PR DESCRIPTION
**Pull request by corymhall**
The cross region export writer was only being given permissions to the first region it would export to. Fixing this by adding each consuming region to the IAM policy.

fixes #24464

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/core/lib/custom-resource-provider/cross-region-export-providers/export-writer-provider.ts [hunk 1]
```diff
@@ -54,22 +55,31 @@ export class ExportWriter extends Construct {
...
+  private readonly resourceArns = new Set<string>;
   constructor(scope: Construct, id: string, props: ExportWriterProps) {
     super(scope, id);
     const stack = Stack.of(this);
     const region = props.region ?? stack.region;
+    this.resourceArns.add(
+      stack.formatArn({
+        service: 'ssm',
+        resource: 'parameter',
+        region,
```
Comment (otaviomacedo) [inline packages/aws-cdk-lib/core/lib/custom-resource-provider/cross-region-export-providers/export-writer-provider.ts:68]: Do we want to add this arn, even if it's unresolved here? If not, we can call `this.addRegionToPolicy()`.

**Review by otaviomacedo — APPROVED** [review]

**Comment by renschler** [comment]
is this fix live in the node aws-cdk library?

I ran into the bug but I'm still on aws-cdk 2.60.0 (build 2d40d77).

Does this PR being merged means that it was released?

**Comment by corymhall** [comment]
> is this fix live in the node aws-cdk library?

yep, it was released in `v2.77.0`
