### PR TITLE
fix(custom-resources): AwsCustomResource requires a policy which updates immutable roles

### LINKED ISSUE #13232: [custom-resources] allow for no policy to be specified
I do not have the ability to modify roles and the CDK assumes I do for an `AwsCustomResource`.  I can specify the execution role for the custom resource Lambda, but I _have_ to specify a policy, and `cdk deploy` fails for me because I don't have access to modify the execution role with the new policy. I would expect for _policy_ to be optional if _role_ is specified. I am in a corporate setting where permissions are "locked down" and roles exist but can not be modified.

### Reproduction Steps

```
export class ExistingS3BucketEventSource extends CDK.Construct {
  constructor(scope: CDK.Construct, id: string, props: S3NotificationLambdaProps) {
    super(scope, id);

    new CR.AwsCustomResource(scope, id + 'CustomResource', {
      onCreate: {
        ...
      },
      onDelete: {
        ...
      },
      policy: CR.AwsCustomResourcePolicy.fromStatements([]), // I don't want this! Also specifying no statements doesn't work!
      role: props.role // I want permissions from here!
    });

    props.lambda.addPermission('AllowS3Invocation', {
      action: 'lambda:InvokeFunction',
      principal: new IAM.ServicePrincipal('s3.amazonaws.com'),
      sourceArn: props.bucket.bucketArn
    });
  }
}

interface S3NotificationLambdaProps {
  role: IAM.IRole;
  bucket: S3.IBucket;
  lambda: Lambda.IFunction;
  events: string[];
  prefix: string;
}
```

### What did you expect to happen?

I do not want to modify the execution role.

### What actually happened?

The execution role is modified.

### Environment

  - **CDK CLI Version  : 1.90.0 (build 7edba31)**
  - **Framework Version: 1.90.0**
  - **Node.js Version: v12.18.3** 
  - **OS               : Catalina 10.15.7**
  - **Language (Version): TypeScript (3.8.3)**

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by haslam22**
This fixes #13232 by making the `policy` property optional in `AwsCustomResource` as long as `role` is specified.

Previously, if an immutable role was provided to `AwsCustomResource`, an IAM policy was still created with a reference to the provided role. This resulted in a call to `iam:PutRolePolicy` to update the immutable role when deploying the stack.

The underlying motivation for using an immutable role here is to support a restricted corporate environment where IAM role changes are not allowed.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by mattiamatrix** [comment]
Thank you for this PR @haslam22 :)

File: packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts [hunk 1]
```diff
@@ -260,10 +260,16 @@ export interface AwsCustomResourceProps {
...
+   * by default a new role is created which requires policy changes to access
+   * resources.
+   *
+   * @default - no policy added
+   *
    * @see Policy.fromStatements
    * @see Policy.fromSdkCalls
    */
-  readonly policy: AwsCustomResourcePolicy;
+  readonly policy?: AwsCustomResourcePolicy;
```
Comment (TheRealAmazonKendra) [inline packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts:272]: I'd like to see an integration test for when policy is not provided and role is.

File: packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts [hunk 2]
```diff
@@ -344,6 +350,10 @@ export class AwsCustomResource extends Construct implements iam.IGrantable {
       throw new Error('At least `onCreate`, `onUpdate` or `onDelete` must be specified.');
     }
 
+    if (!props.role && !props.policy) {
+      throw new Error('Either `policy` or `role` must be specified.');
```
Comment (TheRealAmazonKendra) [inline packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts:354]: This makes it sound like they are mutually exclusive. Can you refine this message a little more?

File: packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts [hunk 3]
```diff
@@ -421,9 +400,43 @@ export class AwsCustomResource extends Construct implements iam.IGrantable {
       },
     });
 
-    // If the policy was deleted first, then the function might lose permissions to delete the custom resource
-    // This is here so that the policy doesn't get removed before onDelete is called
-    this.customResource.node.addDependency(policy);
+    // Create the policy statements for the custom resource function role, or use the user-provided ones
```
Comment (TheRealAmazonKendra) [inline packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts:403]: Why move the location of this?

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Thank you for your contribution! Just a few quick comments inline.

**Comment by TheRealAmazonKendra** [comment]
Oh, actually one more note. On a fix, you want to describe the problem, not the solution you're implementing. Take a look at our changelog for examples.

File: packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts (hunk 1 above)
Comment (haslam22) [reply packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts:272]: Added an integration test which creates an `AwsCustomResource` with a `role` but no `policy`. Got this passing locally and updated the snapshot.

File: packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts (hunk 2 above)
Comment (haslam22) [reply packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts]: This was tricky to get correct, but I've modified the message slightly now to mention both can be used together.

File: packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts (hunk 3 above)
Comment (haslam22) [reply packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts:403]: The old code created the policy first, followed by the custom resource, and finally made the custom resource dependent on the policy. It felt a bit more natural to first create the custom resource, and then create the policy + dependency on the policy together in the same `if(props.policy) { ... }` block.

The alternative is to not move this around and wrap both the policy creation and dependency addition with `if(props.policy)`, but it feels neater in one block.

**Comment by haslam22** [comment]
> Oh, actually one more note. On a fix, you want to describe the problem, not the solution you're implementing. Take a look at our changelog for examples.

Thanks for the review @TheRealAmazonKendra. I've updated the PR title and addressed the other comments.

**Review by TheRealAmazonKendra — APPROVED** [review]
Looks good. Thanks for your contribution!
