### PR TITLE
fix(dynamodb): resolve circular dependency with AccountRootPrincipal grants

### LINKED ISSUE #35967: dynamodb: CDK Error WIth Stacks Containing Dynamodb
### Describe the bug

[23:13:03] ValidationError: Circular dependency between resources: 
Could not create a change set, will base the diff on template differences (run again with -v to see the reason)

Getting an error, I believe it with aws-cdk-lib [2.222.0](https://www.npmjs.com/package/aws-cdk-lib/v/2.222.0)

Any of my stack using dynamodb is having this problem

[23:13:02] Removing existing change set with name cdk-diff-change-set if it exists
[23:13:02] Attempting to create ChangeSet with name cdk-diff-change-set for stack <Stackname>
[23:13:03] ValidationError: Circular dependency between resources: [<tableName>]
Could not create a change set, will base the diff on template differences (run again with -v to see the reason)

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Library Version

2.221.1

### Expected Behavior

Deployment and diff works

### Current Behavior

Error and failure in deployment

### Reproduction Steps

Run a deploy using 2.222.0

### Possible Solution

The fix is revert

### Additional Information/Context

_No response_

### AWS CDK Library version (aws-cdk-lib)

2.222.0

### AWS CDK CLI version

2.1031.1 (build a560d1e)

### Node.js Version

NODE_VERSION=22.0.0

### OS

"Debian GNU/Linux"

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by pahud**
### Issue # (if applicable)

Closes #35967.

### Reason for this change

In CDK 2.222.0, PR #35554 fixed `addToResourcePolicy()` to actually work (it was previously a no-op). This exposed a circular dependency issue when using `grantReadData()` or other grant methods with `AccountRootPrincipal`.

When `AccountRootPrincipal` is used with grant methods, the IAM Grant system adds the policy to the table's resource policy (since it's in the same account). The resource policy statement included the table's ARN (`!GetAtt Table.Arn`), creating a circular dependency: Table → ResourcePolicy → Table.Arn → Table.

This is a regression that breaks existing user code that worked in 2.221.1.

### Description of changes

Applied the established KMS grant pattern to DynamoDB by adding `resourceSelfArns: ['*']` parameter to `Grant.addToPrincipalOrResource()` calls in the `combinedGrant` method.

**How it works:**
- `resourceArns` contains actual table ARNs → used for **principal policies** (IAM user/role policies)
- `resourceSelfArns: ['*']` → used for **resource policies** (table's resource policy)
- IAM Grant system automatically chooses which to use based on context
- No circular dependency because resource policy uses wildcard instead of `!GetAtt Table.Arn`

**Why wildcard is safe:**
- Wildcard is scoped to the table's resource policy (not global)
- Resource policy is attached to specific table resource
- Principal and Action fields still enforce access control
- Same pattern used by KMS for years in production

**Files modified:**
- `packages/aws-cdk-lib/aws-dynamodb/lib/table.ts` - Added `resourceSelfArns: ['*']` to `combinedGrant` method
- `packages/aws-cdk-lib/aws-dynamodb/lib/table-v2-base.ts` - Applied identical change for Table V2
- `packages/aws-cdk-lib/aws-dynamodb/README.md` - Added documentation about grant methods and resource policy interaction

**Before (causes circular dependency):**
```typescript
const table = new dynamodb.Table(this, 'Table', {
  partitionKey: { name: 'id', type: dynamodb.AttributeType.STRING },
});

// This caused circular dependency error in 2.222.0
table.grantReadData(new iam.AccountRootPrincipal());
// Error: Circular dependency between resources: [Table]
```

**After (no circular dependency):**
```typescript
const table = new dynamodb.Table(this, 'Table', {
  partitionKey: { name: 'id', type: dynamodb.AttributeType.STRING },
});

// This now works correctly
table.grantReadData(new iam.AccountRootPrincipal());
// ✓ Resource policy uses wildcard, no circular dependency
```

**CloudFormation template change:**
```json
{
  "Resources": {
    "Table": {
      "Type": "AWS::DynamoDB::Table",
      "Properties": {
        "ResourcePolicy": {
          "PolicyDocument": {
            "Statement": [{
              "Action": ["dynamodb:BatchGetItem", "dynamodb:GetItem", "dynamodb:Query", "dynamodb:Scan"],
              "Effect": "Allow",
              "Principal": { "AWS": "arn:aws:iam::ACCOUNT:root" },
              "Resource": "*"
            }]
          }
        }
      }
    }
  }
}
```

### Describe any new or updated permissions being added

N/A - This fix does not add new permissions. It resolves how existing grant methods generate resource policies to avoid circular dependencies.

### Description of how you validated changes

- **Unit tests**: Added 2 new tests validating `AccountRootPrincipal` with grant methods
  - `packages/aws-cdk-lib/aws-dynamodb/test/dynamodb.test.ts`: Test for Table V1
  - `packages/aws-cdk-lib/aws-dynamodb/test/table-v2.test.ts`: Test for Table V2
  - Both tests verify resource policy uses wildcard (`*`) to avoid circular dependency
  - All 348 unit tests pass (346 existing + 2 new)

- **Integration tests**: Enhanced existing integration test with grant scenario
  - `packages/@aws-cdk-testing/framework-integ/test/aws-dynamodb/test/integ.dynamodb.add-to-resource-policy.ts`
  - Added TEST 3: Validates `grantWriteData(new AccountRootPrincipal())` works without circular dependency
  - Successfully deployed to AWS (us-east-1)
  - CloudFormation synthesis succeeds, no circular dependency errors
  - Snapshots updated with GrantTable resource

- **Regression testing**: All 346 existing tests pass
  - Grant methods with IAM Users still work
  - Grant methods with IAM Roles still work
  - Grant methods with Service Principals still work
  - Tables with indexes work correctly
  - Global tables (Table V2) work correctly
  - Encrypted tables work correctly

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-dynamodb/lib/table.ts [hunk 1]
```diff
@@ -1046,6 +1046,10 @@ export abstract class TableBase extends Resource implements ITable, iam.IResourc
         grantee,
         actions: opts.tableActions,
         resourceArns: resources,
+        // Use wildcard for resource policy to avoid circular dependency when grantee is a resource principal
+        // (e.g., AccountRootPrincipal). This follows the same pattern as KMS (aws-kms/lib/key.ts).
+        // resourceArns is used for principal policies, resourceSelfArns is used for resource policies.
+        resourceSelfArns: ['*'],
```
Comment (Abogical) [inline packages/aws-cdk-lib/aws-dynamodb/lib/table.ts:1052]: Can we condition adding a wildcard iff the grantee is a resource?

**Review by Abogical — CHANGES_REQUESTED** [review]

File: packages/aws-cdk-lib/aws-dynamodb/lib/table.ts (hunk 1 above)
Comment (pahud) [reply packages/aws-cdk-lib/aws-dynamodb/lib/table.ts:1052]: The `resourceSelfArns: ['*']` is only used when `Grant.addToPrincipalOrResource()` creates a resource policy statement. Looking at the implementation in aws-iam/lib/grant.ts:

The logic is essentially like

```ts
public static addToPrincipalOrResource(options: GrantWithResourceOptions): Grant {
  // Step 1: Try to add to principal policy first
  const result = Grant.addToPrincipal(options);
  
  // Step 2: If successful AND same account, we're done - no resource policy needed
  if (result.success && sameAccount) {
    return result;  // resourceSelfArns is never used here
  }
  
  // Step 3: Otherwise, create a resource policy statement
  const statement = new PolicyStatement({
    actions: options.actions,
    resources: (options.resourceSelfArns || options.resourceArns),  // ← Only used here
    principals: [options.grantee!.grantPrincipal],
  });
  
  options.resource.addToResourcePolicy(statement);
}
```

so the wildcard of `resourceSelfArns` would ONLY apply to resource, not a principal. Please confirm.

**Review by Abogical — APPROVED** [review]
Thanks! I've asked for another reviewer to this.

**Review by gasolima — APPROVED** [review]

**Review by Abogical — APPROVED** [review]
