### PR TITLE
fix(apigateway): authorizerUri does not resolve to the correct partition

### LINKED ISSUE #8098: The API Gateway RequestAuthorizer URI is not partition based
* The requestURI for the the API GW authorizers does not take partition into account https://github.com/aws/aws-cdk/blob/986e2814e072f0334d8470a2d60ea73dcceadfe4/packages/%40aws-cdk/aws-apigateway/lib/authorizers/lambda.ts#L235
* It is always in the classic partition

### Reproduction Steps

* running cdk in a different partition such as china
```
 "AuthorizerUri": {
          "Fn::Join": [
            "",
            [
              "arn:aws:apigateway:cn-north-1:lambda:path/2015-03-31/functions/",
              {
                "Ref": "xyz"
              },
              "/invocations"
            ]
          ]
```

### Error Log
* Attempting to deploy this will cause the following error for API GW
```Authorizer URI should be a valid API Gateway ARN that represents a Lambda function invocation.```

### Environment

  - **CLI Version      :**
  - **Framework Version:**1.22.0
  - **OS               :**Mac
  - **Language         :**Tyepscript

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by DRNagar**
Add that the authorizerURI includes the correct partition. Previously, it
always used the aws partition.

fixes #8098

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by DRNagar** [comment]
Hi nija-at,

Thank you for the feedback. I have updated the commit accordingly :)

File: packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts [hunk 1]
```diff
@@ -126,6 +126,13 @@ abstract class LambdaAuthorizer extends Authorizer implements IAuthorizer {
       },
     });
   }
+
+  /**
+   * constructs the authorizerURIArn.
+   */
+  protected authorizerURIArn() {
+    return `arn:${Stack.of(this).partition}:apigateway:${Stack.of(this).region}:lambda:path/2015-03-31/functions/${this.handler.functionArn}/invocations`;
+  }
```
Comment (nija-at) [inline packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts:135]: This will expose this API as part of a public API. That is not necessary here.

Instead, make this a standalone function at the bottom of the file. 

```ts
  function lambdaAuthorizerArn(handler: Function) {
    return `arn:${Stack.of(handler).partition}:apigateway:${Stack.of(handler).region}:lambda:path/2015-03-31/functions/${handler.functionArn}/invocations`;
  }
```

**Comment by DRNagar** [comment]
I have added the changes :)
