### PR TITLE
fix(rds): deploy fails with "SubnetGroup not found"

### LINKED ISSUE #13976: (ServerlessCluster): cdk deploy failure with custom subnetgroup reference
### Description of the bug:
CDK deploy fails for an aurora serverless cluster when the subnetgroup name provided by user is uppercase. I had the resources in the cluster ( security group, subnetgroup etc) created with the names including the clustername as well; which was provided using a context value in cdk.json.

### Reproduction Steps
* Create Aurora serverless cluster construct with a subnet group defined rather than leaving it blank.
* The name of the subnet group is derived using the cluster name defined in the cdk.json.
* Cluster name is Uppercase and run a cdk synth .
* CDK/CloudFormation converts the subnetgroup name to lowercase.
* The cdk synth output shows cluster is referencing the id of the subnet group in cloudformation json/yaml.
* Deploy fails with the message " <subnetgroupname> does not exist" while the subnet group exists.

## Note: 
* The subnet group is created before the cluster as expected and then rolls back as the association to the cluster fails.

Screen Shot 2021-04-02 at 4 04 28 PM
Screen Shot 2021-04-02 at 4 02 32 PM
Screen Shot 2021-04-02 at 4 02 50 PM

Screen Shot 2021-04-02 at 4 07 08 PM
Screen Shot 2021-04-02 at 4 10 12 PM
Screen Shot 2021-04-02 at 4 10 06 PM
Screen Shot 2021-04-02 at 4 07 53 PM

### What did you expect to happen?
Since the reference was to the id of the subnetgroup, I would expect the cdk deploy to work and deploy the cluster

### What actually happened?
Error message as in screenshot below
Screen Shot 2021-04-02 at 4 07 08 PM

### Environment

  - **CDK CLI Version  :** 1.96.0
  - **Framework Version:**1.96.0
  - **OS               :** Linux ( CDK pipeline & Cloud9 environment)
  - **Language (Version):** Python 3.8

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by skinny85**
As it turns out, RDS stores the name of the SubnetGroup in lowercase on the server-side.
The problem is that we weren't changing the case in CloudFormation,
and thus expressions like `{ Ref: SubnetGroup }` were using the wrong casing,
resulting in the RDS service failing with a 404 error when providing a name for the SubnetGroup.

Fixes #13976

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-rds/lib/subnet-group.ts [hunk 1]
```diff
@@ -77,7 +77,10 @@ export class SubnetGroup extends Resource implements ISubnetGroup {
     // Using 'Default' as the resource id for historical reasons (usage from `Instance` and `Cluster`).
     const subnetGroup = new CfnDBSubnetGroup(this, 'Default', {
       dbSubnetGroupDescription: props.description,
-      dbSubnetGroupName: props.subnetGroupName,
+      // names are actually stored by RDS changed to lowercase on the server side,
+      // and not lowercasing them in CloudFormation means things like { Ref }
+      // do not work correctly
+      dbSubnetGroupName: props.subnetGroupName?.toLowerCase(),
```
Comment (njlynch) [inline packages/@aws-cdk/aws-rds/lib/subnet-group.ts:83]: This probably needs a Token check first.

Comment (skinny85) [reply packages/@aws-cdk/aws-rds/lib/subnet-group.ts]: Good catch. Added.

**Comment by skinny85** [comment]
Thanks for the review @njlynch - I've addressed your comment, would appreciate another look!

**Review by njlynch — APPROVED** [review]
