### PR TITLE
fix(cli): unable to update stacks in UPDATE_ROLLBACK_COMPLETE

### LINKED ISSUE #8126: Error while re-deploying a stack that is ROLLBACK_COMPLETE state
This occurs once when a stack is in `ROLLBACK_COMPLETE` and a `cdk deploy` command is issued to attempt another deployment. **Retrying `cdk deploy` succeeds.**

As far as I can tell this is not a race condition since this occurs no matter how long you wait between the stack going into `ROLLBACK_COMPLETE` and the issuance of the deploy command.

### Reproduction Steps

1. Create a stack via `cdk deploy` that is going to throw an error from CloudFormation during deployment. The stack should end up in a `ROLLBACK_COMPLETE` state.
2. Re-issue the `cdk deploy` and the above error should show up.

A second retry of `cdk deploy` will succeed.

### Error Log

Error message when running `cdk deploy --app <path to js file>` -

```
integ-user-pool-idp-social: deploying...
integ-user-pool-idp-social: creating CloudFormation changeset...

 ❌  integ-user-pool-idp-social failed: Error [ValidationError]: Stack [integ-user-pool-idp-social] does not exist
    at Request.extractError (/Users/nija/.nvm/versions/node/v12.16.3/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/nija/.nvm/versions/node/v12.16.3/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/nija/.nvm/versions/node/v12.16.3/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/nija/.nvm/versions/node/v12.16.3/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/nija/.nvm/versions/node/v12.16.3/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/nija/.nvm/versions/node/v12.16.3/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/nija/.nvm/versions/node/v12.16.3/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/nija/.nvm/versions/node/v12.16.3/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/nija/.nvm/versions/node/v12.16.3/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/nija/.nvm/versions/node/v12.16.3/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2020-05-21T10:45:53.471Z,
  requestId: '7b0e67c1-d3f0-4a60-bee0-722fec9fb71e',
  statusCode: 400,
  retryable: false,
  retryDelay: 290.0758012593673
}
Stack [integ-user-pool-idp-social] does not exist
```

### Environment

  - **CLI Version: 1.38.0**
  - **OS: OSX 10.14**

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by shivlaks**
Supersedes aws/aws-cdk#8779

The CLI determined that a stack in `UPDATE_ROLLBACK_COMPLETE`
status is not updateable. related [comment](https://github.com/aws/aws-cdk/pull/8779#issuecomment-655258569)

This change modifies this logic by splitting up `waitForStack` into `waitForStackDelete`
and `waitForStackDeploy` which evaluate stack status after it reaches a stable state
depending on the operation that was performed.

Closes aws/aws-cdk#8126 aws/aws-cdk-cli#823

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk/lib/api/util/cloudformation/stack-status.ts [hunk 1]
```diff
@@ -25,10 +25,6 @@ export class StackStatus {
     return this.name.endsWith('FAILED');
   }
 
-  get isRollback(): boolean {
-    return this.name.indexOf('ROLLBACK') !== -1;
-  }
-
   get isStable(): boolean {
```
[the remark this answers is not in the document]
Comment (shivlaks) [reply packages/aws-cdk/lib/api/util/cloudformation/stack-status.ts:28]: I like that suggestion, maps more naturally to the cfn status it represents and evaluates against

**Comment by rix0rrr** [comment]
I don't think this is the whole story.

`waitForStack()` is used in multiple places, and it's probably conflating logic based on that.

- It's used *before* we start doing work, to look up the current stack state.
- It's used *after* we did an update, to check the result.

If *after* an update, we end up in `UPDATE_ROLLBACK_COMPLETE`, that's an error! It means the update didn't succeed. Yes, we rolled back successfully, but the deployment failed (which we should tell the user) and we should NOT continue updating downstream stacks.

If *before* an update we find the stack in `UPDATE_ROLLBACK_COMPLETE`, that's fine. We can just retry a new operation.

We should have 2 different functions for 2 different purposes here (though they might share logic).

**Comment by rix0rrr** [comment]
Maybe the "did the update actually succeed" check can go into `deployStack()` as well. But please check all usage sites of this function.

**Comment by rix0rrr** [comment]
Probably we should actually be looking at the result of the ChangeSet, and not the state of the stack anyway.

File: packages/aws-cdk/test/integ/cli/cli.integtest.ts [hunk 2]
```diff
@@ -212,6 +212,57 @@ integTest('deploy with parameters', async () => {
   ]);
 });
 
+integTest('stack in UPDATE_ROLLBACK_COMPLETE state can be updated', async () => {
```
Comment (eladb) [inline packages/aws-cdk/test/integ/cli/cli.integtest.ts:215]: Let's add another test where the initial deployment fails and then a subsequent deployment succeeds (that's the case where we delete the stack on the user's behalf). I suspect there might be a bug there as well, but let's make sure

File: packages/aws-cdk/lib/api/util/cloudformation/stack-status.ts [hunk 3]
```diff
@@ -25,22 +25,14 @@ export class StackStatus {
     return this.name.endsWith('FAILED');
   }
 
-  get isRollback(): boolean {
-    return this.name.indexOf('ROLLBACK') !== -1;
-  }
-
-  get isStable(): boolean {
+  get isInProgress(): boolean {
     return !this.name.endsWith('_IN_PROGRESS');
```
Comment (eladb) [inline packages/aws-cdk/lib/api/util/cloudformation/stack-status.ts:29]: Be careful! The logic here needs to be reversed. This checks if the stack is not in progress.

Alternatively, rename to `isNotInProgress` but that's weird.

File: packages/aws-cdk/test/integ/cli/cli.integtest.ts (hunk 2 above)
Comment (shivlaks) [reply packages/aws-cdk/test/integ/cli/cli.integtest.ts:215]: good call, I did test that scenario but not in an integ test yet

**Comment by shivlaks** [comment]
took a run at splitting up validation based on site usage of `waitForStack` as suggested by @rix0rrr
could you have another look @eladb

File: packages/aws-cdk/lib/api/util/cloudformation/stack-status.ts [hunk 4]
```diff
@@ -25,20 +25,16 @@ export class StackStatus {
...
   }
 
   get isNotFound(): boolean {
     return this.name === 'NOT_FOUND';
   }
 
-  get isSuccess(): boolean {
-    return !this.isNotFound && !this.isRollback && !this.isFailure;
+  get isDeploySuccess(): boolean {
+    return !this.isNotFound && (this.name === 'CREATE_COMPLETE' || this.name === 'UPDATE_COMPLETE');
```
Comment (eladb) [inline packages/aws-cdk/lib/api/util/cloudformation/stack-status.ts:37]: What about `UPDATE_COMPLETE_CLEANUP_IN_PROGRESS`? Will the stack move to `UPDATE_COMPLETE` after the clean up is complete?

Comment (shivlaks) [reply packages/aws-cdk/lib/api/util/cloudformation/stack-status.ts:37]: it *should* end up in UPDATE_COMPLETE but can also get stuck in this state (which cannot be updated).

In both of our usage of `waitFor*` APIs, we wait for the stack to stabilize before we evaluate it's status.
We return `undefined` if it's in an `IN_PROGRESS` state and the stack otherwise if they pass the conditional logic.

I do think you're right that we might need to be more graceful. I haven't used nested stacks a ton yet, but most of the info I could dig up on this status is largely in that domain.

We have this block of code in `deployStack`:

```ts
      const finalStack = await waitForStackDeploy(cfn, deployName);
      // This shouldn't really happen, but catch it anyway. You never know.
      if (!finalStack) { throw new Error('Stack deploy failed (the stack disappeared while we were deploying it)'); }
```

In the `UPDATE_ROLLBACK_IN_PROGRESS` scenario, we would return undefined as the 'stack' and that would throw an error stating

> Stack deploy failed (the stack disappeared while we were deploying it

That might be misleading although it is there with a comment of "this shouldn't really happen".

Comment (eladb) [reply packages/aws-cdk/lib/api/util/cloudformation/stack-status.ts:37]: Not sure I understand.. are you saying that we know of a case where the "this should not happen" actually happens?

**Comment by ChristophMalassa** [comment]
this is very frustrating. Is there any ETA on the availability of the fix? Thank you!

**Comment by shivlaks** [comment]
> this is very frustrating. Is there any ETA on the availability of the fix? Thank you!

this is currently in PR (this review)... when the PR is merged, it will be included in the next release.

File: packages/aws-cdk/lib/api/util/cloudformation/stack-status.ts (hunk 4 above)
Comment (shivlaks) [reply packages/aws-cdk/lib/api/util/cloudformation/stack-status.ts:37]: @eladb - not quite what I was trying to say. It's that the "this should not happen" block has a blanket error message that would be confusing if it ever does happen. I guess it's just general uneasiness of that code existing at all.

Back to `UPDATE_COMPLETE_CLEANUP_IN_PROGRESS`, I've tested that if we end up there after a deploy, we will fail because we only deem an update to be successful if it ends up in `CREATE_COMPLETE` or `UPDATE_COMPLETE`. Otherwise, some work that we have performed did not succeed and we bail on deploying that stack and others it depended on.

Do you think something needs to change about how we check the deploy success status?

Comment (eladb) [reply packages/aws-cdk/lib/api/util/cloudformation/stack-status.ts:37]: If this is a possible status after a successful deploy, then it sounds like we need to consider it a successful deploy (am I missing something?)

Comment (shivlaks) [reply packages/aws-cdk/lib/api/util/cloudformation/stack-status.ts:37]: @eladb - it's *possible* as part of a successful deploy (could be on the path to success) but does not indicate success. It could also be a part of a deploy that gets stuck. The two possible outcomes when we see `UPDATE_COMPLETE_CLEANUP_IN_PROGRESS` are:
* it transitions to `UPDATE_COMPLETE` after that, which means we succeeded. This is the only state it can transition to.
* It gets stuck and stays in current state - which means we failed. It cannot be updated after that point and will need to be deleted/cleaned up.

Essentially, this status alone is not indicative of how the deployment went.

Comment (eladb) [reply packages/aws-cdk/lib/api/util/cloudformation/stack-status.ts:37]: Okay. Let's revisit if needed
