### PR TITLE
fix(cfn-diff): correctly handle Date strings in diff

### LINKED ISSUE #16444: (cli): `--hotswap` does not detect function env variables changes
The new hot-swap feature doesn't detect function prop changes like environment variables.

### Reproduction Steps

**app.ts**
```ts
export class BugStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: cdk.StackProps = {}) {
    super(scope, id, props);

    const dateString = new Date().toISOString();

    new lambda.Function(this, 'Function', {
      runtime: lambda.Runtime.NODEJS_14_X,
      code: lambda.Code.fromAsset(__dirname),
      handler: 'bug-handler.handler',
      environment: {
        ENV_VARS_LAST_UPDATE: dateString,
      },
    });
  }
}

const app = new cdk.App();
new BugStack(app, 'BugStack');
```

**bug-handler.js**
```js
exports.handler = async () => process.env.ENV_VARS_LAST_UPDATE || 'unset';
```

### What did you expect to happen?
I expected `cdk deploy BugStack --hotswap` to deploy the stack every time I ran it.

### What actually happened?
It said `(no changes)` on the second deployment, failing to update the environment variable.

### Environment

  - **CDK CLI Version  :** 1.122.0
  - **Framework Version:** 1.122.0
  - **Node.js Version:** v14.15.4
  - **OS               :** Windows
  - **Language (Version):** TypeScript (4.4.2)

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by skinny85**
Turns out, `parseFloat()` in JavaScript is even crazier than we thought,
and returns nonsense like `2021` for a string containing a Date like `'2021-10-25'`.
For that reason, add an explicit check that the string parsed looks like a number before calling `parseFloat()`.

Fixes #16444

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/cloudformation-diff/lib/diff/util.ts [hunk 1]
```diff
@@ -140,17 +140,21 @@ export function unionOf(lv: string[] | Set<string>, rv: string[] | Set<string>):
  * (for which JavaScript's parseFloat() returns 0).
  */
 function safeParseFloat(str: string): number {
+  const decimalNumberRegex = /^\d*(\.\d*)?$/;
```
Comment (rix0rrr) [inline packages/@aws-cdk/cloudformation-diff/lib/diff/util.ts:143]: According to the documentation of `parseFloat`:

> Consider [Number(value)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number) for stricter parsing, which converts to NaN for arguments with invalid characters anywhere.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat

Maybe do that instead?

**Review by rix0rrr — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/cloudformation-diff/lib/diff/util.ts (hunk 1 above)
Comment (skinny85) [reply packages/@aws-cdk/cloudformation-diff/lib/diff/util.ts:143]: Ah, JavaScript, you will always surprise me, no matter how long I use you 😃.

Will change!
