### PR TITLE
fix(ecs): correct logic of healthcheck command

### LINKED ISSUE #2461: [ecs] Healthcheck command always prepends CMD
**Describe the bug**
Adding a healthcheck command to an ECS container definition results in an invalid command after synthesizing. 

    Input: ['CMD', 'command']
    Output:
          HealthCheck:
            Command:
              - CMD
              - CMD
              - echo
              - z
    
    Input: ['CMD-SHELL', 'command']
    Output:
          HealthCheck:
            Command:
              - CMD
              - CMD-SHELL
              - echo
              - z

**To Reproduce**
```
#!/usr/bin/env node
import 'source-map-support/register';
import cdk = require('@aws-cdk/cdk');
import ecs = require('@aws-cdk/aws-ecs');
import ec2 = require('@aws-cdk/aws-ec2');

const app = new cdk.App();

export class Stack extends cdk.Stack {
  public constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const cluster = new ecs.Cluster(this, 'Cluster', {
      vpc: new ec2.VpcNetwork(this, 'VPC', { maxAZs: 2 }),
    });
    cluster.addCapacity('Capa', {
      instanceType: new ec2.InstanceType("t2.xlarge"),
      desiredCapacity: 3,
    });

    new ecs.LoadBalancedEc2Service(this, 'Service', {
      cluster,
      memoryLimitMiB: 512,
      image: ecs.ContainerImage.fromRegistry("amazon/amazon-ecs-sample"),
    });

    const ec2TaskDefinition = new ecs.Ec2TaskDefinition(this, 'TaskDef');

    ec2TaskDefinition.addContainer("WebContainer", {
      image: ecs.ContainerImage.fromRegistry("amazon/amazon-ecs-sample"),
      memoryLimitMiB: 1024,
      healthCheck: {
        command: ['CMD-SHELL', 'echo', 'z']
      }
    });
  }
}

new Stack(app, 'Demo');
```

**Expected behavior**

    Input: ['CMD', 'command']
    Output:
          HealthCheck:
            Command:
              - CMD
              - echo
              - z
    
    Input: ['CMD-SHELL', 'command']
    Output:
          HealthCheck:
            Command:
              - CMD-SHELL
              - echo
              - z

**Version:**
 - Arch Linux
 - Typescript
 - 0.29

### PR DESCRIPTION
**Pull request by uniquenode**
Adding a healthcheck command to an ECS container definition
results in an invalid command after synthesizing.

Before:

    Input: ['CMD', 'command']
    Output:
          HealthCheck:
            Command:
              - CMD
              - CMD
              - echo
              - z

    Input: ['CMD-SHELL', 'command']
    Output:
          HealthCheck:
            Command:
              - CMD
              - CMD-SHELL
              - echo
              - z

After:

    Input: ['CMD', 'command']
    Output:
          HealthCheck:
            Command:
              - CMD
              - echo
              - z

    Input: ['CMD-SHELL', 'command']
    Output:
          HealthCheck:
            Command:
              - CMD-SHELL
              - echo
              - z

fixes #2461

Signed-off-by: Chris Lahaye <dev@chrislahaye.com>

----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
  - __Design__: For significant features, design document added to `design` folder
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-ecs/lib/container-definition.ts [hunk 1]
```diff
@@ -478,7 +478,7 @@ function getHealthCheckCommand(hc: HealthCheck): string[] {
     return hcCommand;
   }
 
-  if (cmd[0] !== "CMD" || cmd[0] !== 'CMD-SHELL') {
+  if (cmd[0] !== "CMD" && cmd[0] !== 'CMD-SHELL') {
```
Comment (pkandasamy91) [inline packages/@aws-cdk/aws-ecs/lib/container-definition.ts]: Can you add a unit test to ensure that this check is working as expected?

Comment (SoManyHs) [reply packages/@aws-cdk/aws-ecs/lib/container-definition.ts]: @pkandasamy91 the [existing test ](https://github.com/awslabs/aws-cdk/pull/2462/files#diff-053089ea576f1ea4920bd44e82d220cbR363) should be sufficient.

Comment (pkandasamy91) [reply packages/@aws-cdk/aws-ecs/lib/container-definition.ts]: Will add missing tests in a separate PR.
