### PR TITLE
fix(stepfunctions): `DistributedMap` ResultWriter correct query language selection

### LINKED ISSUE #35403: stepfunctions: DitributedMap's ResultWriter with JsonATA isn't working
### Describe the bug

Regression of #33396

When specifying `DistributedMap.result_writer_v2`'s parameters in JsonATA format, the template should contain "Arguments", but it contains "Parameters"

This causes CF stack update with `These fields are required: [Arguments] at` followed by path to the `DistributedMap/ResultWriter` error message

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### Last Known Working CDK Library Version

_No response_

### Expected Behavior

DistributedMap/ResultWriter has `Arguments` property where target bucket and prefix is set.

```yml
      DefinitionString:
        Fn::Join:
          - ""
          - - '{"StartAt":"DistributedMap","States":{"DistributedMap":{"Type":"Map","QueryLanguage":"JSONata","End":true,"ItemProcessor":{"ProcessorConfig":{"Mode":"DISTRIBUTED","ExecutionType":"STANDARD"},"StartAt":"Pass","States":{"Pass":{"Type":"Pass","End":true}}},"ResultWriter":{"Resource":"arn:'
            - Ref: AWS::Partition
            - :states:::s3:putObject","Arguments":{"Bucket":"{% $states.input.bucket %}","Prefix":"{% $states.input.prefix %}"}}}}}
```

### Current Behavior

DistributedMap/ResultWriter has `Parameters` property where target bucket and prefix is set, even though the DistributedMap has JsonATA query language selected

```yml
      DefinitionString:
        Fn::Join:
          - ""
          - - '{"StartAt":"DistributedMap","States":{"DistributedMap":{"Type":"Map","QueryLanguage":"JSONata","End":true,"ItemProcessor":{"ProcessorConfig":{"Mode":"DISTRIBUTED","ExecutionType":"STANDARD"},"StartAt":"Pass","States":{"Pass":{"Type":"Pass","End":true}}},"ResultWriter":{"Resource":"arn:'
            - Ref: AWS::Partition
            - :states:::s3:putObject","Parameters":{"Bucket":"{% $states.input.bucket %}","Prefix":"{% $states.input.prefix %}"}}}}}
```

### Reproduction Steps

```python
from aws_cdk import aws_stepfunctions

distributed_map = aws_stepfunctions.DistributedMap(
    scope,
    'DistributedMap',
    query_language=aws_stepfunctions.QueryLanguage.JSONATA,
    result_writer_v2=aws_stepfunctions.ResultWriterV2(
        bucket_name_path='{% $states.input.bucket %}',
        prefix='{% $states.input.prefix %}'
    ),
)
distributed_map.item_processor(aws_stepfunctions.Pass(scope, 'Pass'))

aws_stepfunctions.StateMachine(
    scope,
    'StateMachine',
    definition_body=aws_stepfunctions.DefinitionBody.from_chainable(distributed_map),
    state_machine_name='state-machine',
)
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### AWS CDK Library version (aws-cdk-lib)

2.214.0

### AWS CDK CLI version

2.1027.0

### Node.js Version

v22.9.0

### OS

Ubuntu

### Language

Python

### Language Version

Python (3.13)

### Other information

_No response_

### PR DESCRIPTION
**Pull request by phuhung273**
### Issue # (if applicable)
Close #35403

### Reason for this change
- Incorrect template when using StateMachine JSONPath with DistributedMap's ResultWriter with JSONata
- Streamline JSONata migration. Without this fix, the only workaround is switching entire StateMachine to JSONata, requiring too much change.

### Description of changes
- DistributedMap add query language validation
- DistributedMap ResultWriter correct query language selection

### Description of how you validated changes
Unit + Integ

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map.ts [hunk 1]
```diff
@@ -314,17 +314,26 @@ export class DistributedMap extends MapBase implements INextable {
    * Return the Amazon States Language object for this state
    */
   public toStateJson(stateMachineQueryLanguage?: QueryLanguage): object {
+    // https://docs.aws.amazon.com/step-functions/latest/dg/statemachine-structure.html
```
Comment (kumvprat) [inline packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map.ts]: Can we have some undefined/optional checks on `stateMachineQueryLanguage` variable ?

File: packages/aws-cdk-lib/aws-stepfunctions/test/distributed-map.test.ts [hunk 2]
```diff
@@ -1615,6 +1615,86 @@ describe('Distributed Map State', () => {
     });
   }),
 
+  test('throw if using JSONPath with JSONata state machine', () => {
+    expect(() => {
+      // GIVEN
+      const stack = new cdk.Stack();
+
+      stack.node.setContext(STEPFUNCTIONS_USE_DISTRIBUTED_MAP_RESULT_WRITER_V2, true);
```
Comment (kumvprat) [inline packages/aws-cdk-lib/aws-stepfunctions/test/distributed-map.test.ts]: Is this something we need to set explicitly ?

What about the case where this feature flag is false ? We need to add tests for that use case as well

File: packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map.ts [hunk 3]
```diff
@@ -314,17 +314,26 @@ export class DistributedMap extends MapBase implements INextable {
...
       Annotations.of(this).addWarningV2('@aws-cdk/aws-stepfunctions:propertyIgnored', 'Property \'ProcessorConfig.executionType\' is ignored, use the \'mapExecutionType\' in the \'DistributedMap\' class instead.');
     }
 
     rendered.ItemProcessor.ProcessorConfig.ExecutionType = this.mapExecutionType;
-    const renderedResultWriter = this.renderResultWriter(stateMachineQueryLanguage);
-    this.addWarningIfResultWriterIsEmpty(renderedResultWriter);
     // ItemReader and ResultWriter configuration will base on the Map's query language.
     // If Map's query language is not specified, then use state machine's query language.
-    const stateQueryLanguage = this.queryLanguage ?? stateMachineQueryLanguage;
+    const stateQueryLanguage = stateMachineQueryLanguage == QueryLanguage.JSONATA
```
Comment (kumvprat) [inline packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map.ts]: The check above should take care of this, and we can keep the old logic : 


```
 if (stateMachineQueryLanguage == QueryLanguage.JSONATA && this.queryLanguage == QueryLanguage.JSON_PATH) {
      throw new ValidationError('When StateMachine query language is JSONata, individual states cannot use JSONPath.', this);
    }
```

File: packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map.ts (hunk 1 above)
Comment (kumvprat) [reply packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map.ts]: Also both state level query language and state machine query language both are optional so there should be checks for both of these varaibles.

**Review by kumvprat — COMMENTED** [review]
Thanks for your contribution.

Added a few inline comments 

Can you also give me context into the feature flag being used in the test ?
Overall we should test with and without the feature flag being set and check for proper query language setting .

File: packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map.ts (hunk 1 above)
Comment (phuhung273) [reply packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map.ts]: Thanks for taking a look. Turn out there is already a same validtion here https://github.com/aws/aws-cdk/blob/de261c03476e659e05a773ec1e9262916433e633/packages/aws-cdk-lib/aws-stepfunctions/lib/states/state.ts#L588-L592

The existing validation passes the new throw unit test, so I reverted this check.

File: packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map.ts (hunk 3 above)
Comment (phuhung273) [reply packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map.ts]: Yeah you're correct we don't need this logic. Not this file but `state.ts` already has a function handling `this.queryLanguage` https://github.com/aws/aws-cdk/blob/de261c03476e659e05a773ec1e9262916433e633/packages/aws-cdk-lib/aws-stepfunctions/lib/states/state.ts#L588-L598

Now we just need to move down `resultWriter` after the language selection. Then it have the same language as `iteamReader`

File: packages/aws-cdk-lib/aws-stepfunctions/test/distributed-map.test.ts (hunk 2 above)
Comment (phuhung273) [reply packages/aws-cdk-lib/aws-stepfunctions/test/distributed-map.test.ts]: I believe this is a defect of `getResultWriter` function https://github.com/aws/aws-cdk/blob/de261c03476e659e05a773ec1e9262916433e633/packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map.ts#L206-L210

Currently, to use `resultWriterV2` we need 2 steps:
1. Set the flag to true
2. Specify param `resultWriterV2: new stepfunctions.ResultWriterV2`

I think only step 2 should be enough. But won't change this logic for now.

My intention when first submitting the PR was ignoring unit test for V1 as we're encouraging migration to V2. It is now added anw. Pls have a look.

File: packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.sm-jsonpath-with-distributed-map-jsonata.ts [hunk 4]
```diff
@@ -0,0 +1,90 @@
...
+
+    this.stateMachine = new sfn.StateMachine(this, 'StateMachine', {
+      definition: distributedMap,
+    });
+  }
+}
+
+const app = new cdk.App({
+  context: {
+    [STEPFUNCTIONS_USE_DISTRIBUTED_MAP_RESULT_WRITER_V2]: true,
```
Comment (kumvprat) [inline packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.sm-jsonpath-with-distributed-map-jsonata.ts:47]: I would recommend that we don't set this flag explicitly, and let the integ test work with default values.

My understanding is that users using resultWriter v1 also are able to make use of this changes where correct query language is used for result writers.

Comment (phuhung273) [reply packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.sm-jsonpath-with-distributed-map-jsonata.ts:47]: Understand your point. But while trying to do that, I believe I found another bug: `resultWriter` v1 is skipped entirely. And it has been there for 8 months. We can see that by checking this integration:
- TS file has `resultWriter` https://github.com/aws/aws-cdk/blob/2cdfc8a909ce3752833e46dd2ed0106fee0e785a/packages/%40aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-with-result-writer-jsonata.ts#L26-L29
- Snapshot template has no `resultWriter`, only `reader` https://github.com/aws/aws-cdk/blob/2cdfc8a909ce3752833e46dd2ed0106fee0e785a/packages/%40aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.distribution-map-with-result-writer-jsonata.js.snapshot/aws-stepfunctions-map-with-result-writer.template.json#L201-L216

I believe this is another separate Issue or deprecation for V1.

Well I can remove the flag (tested and everything passed), but looking at the generated template, you will see the same behaviour as `integ.distribution-map-with-result-writer-jsonata.ts` with no resultWriter. Therefore, I think keeping V2 flag makes more sense than creating new misleading test. Somebody else have to cleanup 2 incorrect tests instead of just `integ.distribution-map-with-result-writer-jsonata.ts`.

Again, I completely agree with your idea of removing the flag. But this is kind of unexpected. Let me know what you think.

Comment (kumvprat) [reply packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.sm-jsonpath-with-distributed-map-jsonata.ts:47]: Thanks for the explanation.

I think we can hold off on removing the feature flag.

Can you share more details about below ? Even if it's deprecated I think existing users using it might run into these problems.
> believe I found another bug: resultWriter v1 is skipped entirely. And it has been there for 8 months


Since it an integration between step functions and s3, we should also have assertions on the S3 bucket output.
Currently we only asset on the step function completing successfully but don't check if the result is written to s3. 
I think we should add this extra check so in future any changes in resultWriterV2 is caught by thin integration test atleast.

Comment (phuhung273) [reply packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.sm-jsonpath-with-distributed-map-jsonata.ts:47]: Sure I've added assertion making sure something is written to the result bucket.

> Can you share more details about below ? Even if it's deprecated I think existing users using it might run into these problems.

#35966 created with more info since I think it should be a separate issue.

Comment (kumvprat) [reply packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.sm-jsonpath-with-distributed-map-jsonata.ts:47]: Thanks for creating the issue.

I see below permissions added to read the S3 bucket in the test. Is that necessary, because we have a putObject call above in the assertion that work without adding extra permissions ?

```
s3ApiCall.provider.addToRolePolicy({
  Effect: 'Allow',
  Action: ['s3:GetObject', 's3:ListBucket'],
  Resource: ['*'],
});
```

**Review by kumvprat — COMMENTED** [review]
Added a comment in the test changes, apart from that it looks good.

File: packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.sm-jsonpath-with-distributed-map-jsonata.ts (hunk 4 above)
Comment (phuhung273) [reply packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.sm-jsonpath-with-distributed-map-jsonata.ts:47]: Yes it is necessary, but just a workaround. You can see it everywhere with s3 object assertion https://github.com/aws/aws-cdk/blob/fda6e13be540cca53499ed19a79a84ef3a0a706a/packages/%40aws-cdk-testing/framework-integ/test/aws-s3-deployment/test/integ.bucket-deployment.ts#L117-L121

Assertion grants permission `<service_name>:<action>`. In this case:
- `integ.assertions.awsApiCall('S3', 'putObject',...)` grant `s3:putObject` => correct as this permission exist.
- `integ.assertions.awsApiCall('S3', 'listObjectsV2',...)` grants `S3:listObjectsV2` but such permission doesn't exist. So we have to grant `s3:listBucket` manually.

**Comment by phuhung273** [comment]
Thanks so much for the help @kumvprat

File: packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.sm-jsonpath-with-distributed-map-jsonata.ts (hunk 4 above)
Comment (kumvprat) [reply packages/@aws-cdk-testing/framework-integ/test/aws-stepfunctions/test/integ.sm-jsonpath-with-distributed-map-jsonata.ts:47]: Okay, I see it now

In documentation it is mentioned [here](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazons3.html) that the action is `ListBucket` the new api call is [`ListObjectsV2`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html)

And assertions logic is to have a 1:1 mapping between actions and the api call ([here](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/integ-tests-alpha/lib/assertions/sdk.ts#L82))

**Review by kumvprat — APPROVED** [review]
