### PR TITLE
fix(aws-ecs): correctly set MinimumHealthyPercentage to 0

### LINKED ISSUE #1660: DeploymentConfiguration minimumHealthyPercent incorrectly set to 50 when Service minimumHealthyPercent set to 0
If the `minimumHealthyPercent` is set to 0 for an ECS Service (Fargate or EC2), the DeploymentConfiguration minimumHealthyPercent actually get set to 50.

### PR DESCRIPTION
**Pull request by Don-CA**
Zero is a valid value for MinimumHealthyPercentage and therefore should
not be replaced with the default value.

BaseService now explicitly checks if minimumHealthyPercent is null
before setting default value. Fixes #1660.

----

### Pull Request Checklist

* [x] Testing
  - Unit test added
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [ ] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [ ] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-ecs/lib/base/base-service.ts [hunk 1]
```diff
@@ -109,7 +109,7 @@ export abstract class BaseService extends cdk.Construct
       loadBalancers: new cdk.Token(() => this.loadBalancers),
       deploymentConfiguration: {
         maximumPercent: props.maximumPercent || 200,
-        minimumHealthyPercent: props.minimumHealthyPercent || 50
+        minimumHealthyPercent: props.minimumHealthyPercent == null ? 50 : props.minimumHealthyPercent
```
Comment (eladb) [inline packages/@aws-cdk/aws-ecs/lib/base/base-service.ts]: We normally use `=== undefined`
