### PR TITLE
fix(stepfunctions-tasks): `CallAwsServiceCrossRegion` doesn't work with WAIT_FOR_TASK_TOKEN

### LINKED ISSUE #32746: stepfunctions-tasks: CallAwsServiceCrossRegion doesn't work with WAIT_FOR_TASK_TOKEN
### Describe the bug

`CallAwsServiceCrossRegion` task doesn't generate the correct `Resource` required for WAIT_FOR_TASK_TOKEN to work. Because of this, SFN doesn't recognize the task as WAIT_FOR_TASK_TOKEN and thus `$$.Task.Token` is not available in the task parameter to be passed to the call. See Reproduction Steps below.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

`CallAwsServiceCrossRegion` should work with IntegrationPattern.WAIT_FOR_TASK_TOKEN so that the StateMachine can pass task token to another service in different account and region and wait on task completion after making a cross region call.

The ASL generated from this task should be similar to the one generated by `CallAwsService`.

```json
"InvokeWrapper": {
      "Retry": [
        {
          "ErrorEquals": [
            "Lambda.ClientExecutionTimeoutException",
            "Lambda.ServiceException",
            "Lambda.AWSLambdaException",
            "Lambda.SdkClientException"
          ],
          "IntervalSeconds": 2,
          "MaxAttempts": 6,
          "BackoffRate": 2
        }
      ],
      "Type": "Task",
      "Resource": "arn:aws:states:::lambda:invoke.waitForTaskToken",
      "Parameters": {
        "FunctionName":"arn:aws:lambda:us-east-1:xxxx:function:xxxx-CrossRegionAwsSdkxxxx-qxxxw",
        "Payload":{
          "region.$": "$.wrapperStateMachineRegion",
          "action": "startExecution",
          "service": "stepfunctions",
          "parameters": {
            "StateMachineArn.$": "$.wrapperStateMachineArn",
            "Input": {
              "type": 1,
              "value": {
                "taskToken.$": "$$.Task.Token",
                "payload.$": "$.payload"
              }
            }
          }
        }
      }
    }
```

I understand that SendTaskSuccess can only be called with the token using the current account principal.

### Current Behavior

This task
```js
new CallAwsServiceCrossRegion(this, 'InvokeWrapper', {
      integrationPattern: IntegrationPattern.WAIT_FOR_TASK_TOKEN,
      service: 'stepfunctions',
      action: 'startExecution',
      region: JsonPath.stringAt('$.wrapperStateMachineRegion'),
      parameters: {
        StateMachineArn: JsonPath.stringAt('$.wrapperStateMachineArn'),
        Input: TaskInput.fromObject({
          taskToken: JsonPath.taskToken,
          payload: JsonPath.stringAt('$.payload'),
        }),
      },
      iamResources: ['*'],
    });
```

generates following ASL
```json
"InvokeWrapper": {
      "End": true,
      "Retry": [
        {
          "ErrorEquals": [
            "Lambda.ClientExecutionTimeoutException",
            "Lambda.ServiceException",
            "Lambda.AWSLambdaException",
            "Lambda.SdkClientException"
          ],
          "IntervalSeconds": 2,
          "MaxAttempts": 6,
          "BackoffRate": 2
        }
      ],
      "Type": "Task",
      "Resource": "arn:aws:lambda:us-east-1:xxxx:function:xxxx-CrossRegionAwsSdkxxxx-qxxxw",
      "Parameters": {
        "region.$": "$.wrapperStateMachineRegion",
        "action": "startExecution",
        "service": "stepfunctions",
        "parameters": {
          "StateMachineArn.$": "$.wrapperStateMachineArn",
          "Input": {
            "type": 1,
            "value": {
              "taskToken.$": "$$.Task.Token",
              "payload.$": "$.payload"
            }
          }
        }
      }
    }
```

which throws following error during execution
```
An error occurred while executing the state 'InvokeWrapper' (entered at the event id #2). The JSONPath '$$.Task.Token' specified for the field 'taskToken.$' could not be found in the input
```

### Reproduction Steps

See code snippets in the Current Behavior.

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.173.4

### Framework Version

_No response_

### Node.js Version

18

### OS

Mac

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by tmokmss**
### Issue # (if applicable)

Closes #32746

### Reason for this change

The Step Functions task `CallAwsServiceCrossRegion` did not work with `integrationPattern.WAIT_FOR_TASK_TOKEN`. This PR fixes the problem.

### Description of changes

The root cause of this problem is that we used an alterntive form of calling Lambda Invoke, which does not support waitForTaskToken integration pattern.

> Alternatively, you can invoke a Lambda function by specifying a function ARN directly in the "Resource" field. When you invoke a Lambda function in this way, you can't specify .waitForTaskToken, and the task result contains only the function output.

https://docs.aws.amazon.com/step-functions/latest/dg/connect-lambda.html#connect-lambda-api-examples

This PR fixes the code to align with the implementation in `LambdaInvoke` task, which supports both integration pattern.

https://github.com/aws/aws-cdk/blob/bbdd42c8f45916d5c6945f3429916f6199d2ec66/packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/lambda/invoke.ts#L146-L165

To fix this without breaking changes, we introduce `payloadResponseOnly` property (true by default), and fix the `_renderTask` method as above. Users who need other integration patterns can set `payloadResponseOnly: false`.

Additionally we throw an error if `payloadResponseOnly == true && integrationPattern != REQUEST_RESPONSE` to prevent misconfiguration. This is not a breaking change because the construct previously did not work at all when `integrationPattern != REQUEST_RESPONSE`.

### Describe any new or updated permissions being added

No.

### Description of how you validated changes

Added unit tests and integ tests.

### Checklist
- [X] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by mazyu36 — APPROVED** [review]

File: packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/lambda/call-aws-service-cross-region.ts [hunk 1]
```diff
@@ -101,12 +112,21 @@ export class CallAwsServiceCrossRegion extends sfn.TaskStateBase {
   protected readonly taskPolicies?: iam.PolicyStatement[];
   protected readonly lambdaFunction: IFunction;
 
+  private readonly payloadResponseOnly: boolean;
+
   constructor(scope: Construct, id: string, private readonly props: CallAwsServiceCrossRegionProps) {
     super(scope, id, props);
 
+    this.payloadResponseOnly = props.payloadResponseOnly ?? true;
```
Comment (QuantumNeuralCoder) [inline packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/lambda/call-aws-service-cross-region.ts:120]: The default value of the newly introduced prop is being set to true. Now in combination with line 126, it will throw and error for existing stacks where 
```typescript
props.integrationPattern === sfn.IntegrationPattern.WAIT_FOR_TASK_TOKEN
``` 
IMHO default should be false.

**Review by QuantumNeuralCoder — CHANGES_REQUESTED** [review]
See comment on default value set for payloadResponseOnly

File: packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/lambda/call-aws-service-cross-region.ts (hunk 1 above)
Comment (tmokmss) [reply packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/lambda/call-aws-service-cross-region.ts:120]: Hi @QuantumNeuralCoder thanks for the review.

Defaulting payloadResponseOnly to false is actually a breaking change, because the Step Function task output schema will change in non-compatible way. So the state machines previously deployed will break because it cannot read the output values, until they change e.g. `$.output.someOutputValue -> $.output.Payload.someOutputValue`.

```ts
// with payloadResponseOnly=true (previous behavior)
{
  "output": {
    "someOutputValue": "foo"
  }
}

// with payloadResponseOnly=false
{
  "output": {
    "Payload": {
      "someOutputValue": "foo"
    },
    "SdkHttpMetadata": { ... },
    "SdkResponseMetadata": {...},
    "StatusCode": 200
  }
}
```

As is pointed out in #32746, `props.integrationPattern === sfn.IntegrationPattern.WAIT_FOR_TASK_TOKEN` never worked on the previous implementation, so I believe throwing an error here is not a breaking change.

File: packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/lambda/call-aws-service-cross-region.ts [hunk 2]
```diff
@@ -196,15 +216,31 @@ export class CallAwsServiceCrossRegion extends sfn.TaskStateBase {
...
-      Resource: this.lambdaFunction.functionArn,
-      ...this._renderParametersOrArguments({
-        region: this.props.region,
-        endpoint: this.props.endpoint,
-        action: this.props.action,
-        service: this.props.service,
-        parameters: this.props.parameters,
-      }, queryLanguage),
-    };
+    if (this.payloadResponseOnly) {
```
Comment (QuantumNeuralCoder) [inline packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/lambda/call-aws-service-cross-region.ts:219]: Can we just get rid of the boolean `payloadResponseOnly`? Ideally a factory implementation might have been great. But the following works too. The conditional check worries me for changes later in time in this area. 
```
protected _renderTask(topLevelQueryLanguage?: sfn.QueryLanguage): any {
  const queryLanguage = sfn._getActualQueryLanguage(topLevelQueryLanguage, this.props.queryLanguage);

  // Use WAIT_FOR_TASK_TOKEN integration if that pattern is explicitly set.
  if (this.props.integrationPattern === sfn.IntegrationPattern.WAIT_FOR_TASK_TOKEN) {
    return {
      Resource: integrationResourceArn('lambda', 'invoke', sfn.IntegrationPattern.WAIT_FOR_TASK_TOKEN),
      ...this._renderParametersOrArguments({
        FunctionName: this.lambdaFunction.functionArn,
        Payload: {
          region: this.props.region,
          endpoint: this.props.endpoint,
          action: this.props.action,
          service: this.props.service,
          parameters: this.props.parameters,
        },
      }, queryLanguage),
    };
  }

  // Default behavior: direct Lambda invocation that returns just the payload.
  return {
    Resource: this.lambdaFunction.functionArn,
    ...this._renderParametersOrArguments({
      region: this.props.region,
      endpoint: this.props.endpoint,
      action: this.props.action,
      service: this.props.service,
      parameters: this.props.parameters,
    }, queryLanguage),
  };
}
```

**Review by QuantumNeuralCoder — CHANGES_REQUESTED** [review]
Please see the proposed change.

File: packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/lambda/call-aws-service-cross-region.ts (hunk 2 above)
Comment (tmokmss) [reply packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/lambda/call-aws-service-cross-region.ts]: I think that makese sense, so I implemented it accordingly.

My thoughts on this prop (fyi):
Initially I thought that exposing `payloadResponseOnly` property makes it easy for users to switch between integration patterns ; users who wants to switch integrationPattern frequently can set `payloadResponseOnly: true` to get the same consistent output schema. But after all I guess there are few use cases that requires to switch integration patterns frequently, and most users will just use request_response integration pattern only, so I removed payloadResponseOnly prop now.

File: packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md [hunk 3]
```diff
@@ -265,6 +265,8 @@ const getObject = new tasks.CallAwsServiceCrossRegion(this, 'GetObject', {
 
 Other properties such as `additionalIamStatements` can be used in the same way as the `CallAwsService` task.
 
+Note that when you use `integrationPattern.WAIT_FOR_TASK_TOKEN`, the output path changes under `Payload` property.
```
Comment (QuantumNeuralCoder) [inline packages/aws-cdk-lib/aws-stepfunctions-tasks/README.md:268]: Nice. Thanks for adding.

**Review by QuantumNeuralCoder — APPROVED** [review]

**Comment by mrgrain** [comment]
@mergifyio requeue

**Comment by QuantumNeuralCoder** [comment]
@Mergifyio requeue

**Review by QuantumNeuralCoder — APPROVED** [review]
