### PR TITLE
fix(core): use correct formatting for aggregate errors in `aws-cdk`

### LINKED ISSUE #32237: CLI: error message is sometimes empty
### Describe the bug

Sometimes when we print `e.message`, it turns out that `e` is an `AggregateError` without a `message` defined itself.

In those cases, we should probably build a message out of the messages of the errors inside the AggregateError.

I'm not sure where these can originate, but the SDKv3 sometimes produces errors like this.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

-

### Framework Version

_No response_

### Node.js Version

-

### OS

-

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by sumupitchayan**
Closes #32237

### Reason for this change

Sometimes when we print `e.message`, `e` is an `AggegateError` - so the message text is incomplete/not formatted correctly. This PR adds a new util function, `formatErrorMessage` which returns `e.message` if it exists, or a correctly formatted string of errors if `e` is an `AggregateError`.

### Description of changes

See `formatErrorMessage` function in the newly created file, `packages/aws-cdk/lib/util/error.ts`. All other changes are grunt work replacing `e.message` with `formateErrorMessage(e)`. This PR only does the finding and replacing in the `aws-cdk` package, TBD whether we need to do the same for the rest of the repo.

### Describe any new or updated permissions being added

None

### Description of how you validated changes

See unit tests in `packages/aws-cdk/test/api/util/error.test.ts`

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk/lib/util/error.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
+export function formatErrorMessage(error: any): string {
```
Comment (rix0rrr) [inline packages/aws-cdk/lib/util/error.ts:1]: I suppose do add a test for this

**Review by rix0rrr — APPROVED** [review]

File: packages/aws-cdk/lib/util/error.ts (hunk 1 above)
Comment (sumupitchayan) [reply packages/aws-cdk/lib/util/error.ts:9]: Just did see `packages/aws-cdk/test/api/util/error.test.ts`
