### PR TITLE
fix(aws-cdk): fix profile use in non-'aws' partitions

### LINKED ISSUE #1109: Can't use CDK to deploy to govcloud
When running `cdk deploy` from my command line when my `AWS_PROFILE` is set to my govcloud credentials. I get an error: `Need to perform AWS calls for account unknown-account, but no credentials found. Tried: default credentials.`. When I switch to a profile that is for a non-gov region, then it works just fine.

I have Administrator permissions in both accounts right now.

### LINKED ISSUE #1262: Cannot determine scope for context provider availability-zones for China regions
Current release of CDK (0.18.1) Cannot determine scope for context provider availability-zones for China regions (cn-north-1 and cn-northwest-1). 

I did setup default credentials with aws configure and can list S3 buckets without problem. But CDK was not able to get the account and region. 

``` bash 
sunhua@haorld_mac ~/Documents/Projects/github.com/nwcdlabs/openshift-on-aws-cn/scripts/infrastructure                [10:13:39]
> $ aws configure                                                                                              [±origin-3.11 ●]
AWS Access Key ID [****************TEMA]:
AWS Secret Access Key [****************RXxI]:
Default region name [cn-northwest-1]:
Default output format [json]:

sunhua@haorld_mac ~/Documents/Projects/github.com/nwcdlabs/openshift-on-aws-cn/scripts/infrastructure                [10:13:47]
> $ aws s3 ls                                                                                                  [±origin-3.11 ●]
2018-07-23 11:23:08 aws-logs-215043275130-cn-northwest-1
2018-08-14 13:44:13 cf-templates-m067e3zuzu6h-cn-north-1
2018-06-11 16:34:18 cf-templates-m067e3zuzu6h-cn-northwest-1
2018-11-11 19:13:29 cloudtrail-zhy-201811111912
2018-07-06 10:40:56 config-bucket-215043275130
2018-11-11 19:05:59 config-bucket-bjs-215043275130


sunhua@haorld_mac ~/Documents/Projects/github.com/nwcdlabs/openshift-on-aws-cn/scripts/infrastructure                [10:13:51]
> $ cdk diff                                                                                                   [±origin-3.11 ●]
[Error at /InfrastructureStack/okd_vpc] Cannot determine scope for context provider availability-zones with props: account=undefined,region=undefined.
This usually happens when AWS credentials are not available and the default account/region cannot be determined.
[Error at /InfrastructureStack/okd_vpc] Cannot determine scope for context provider availability-zones with props: account=undefined,region=undefined.
This usually happens when AWS credentials are not available and the default account/region cannot be determined.
Found errors

sunhua@haorld_mac ~/Documents/Projects/github.com/nwcdlabs/openshift-on-aws-cn/scripts/infrastructure                [10:14:08]
> $ cdk --version                                                                                              [±origin-3.11 ●]
0.18.1 (build 9f7af21)



```

### PR DESCRIPTION
**Pull request by rix0rrr**
Properly pass on the default region to the STS call we make to discover
the default AWS credentials.

Also, there is no way to make use of AssumeRole profiles without the
AWS_SDK_LOAD_CONFIG flag being set, so reintroduce setting that flag
if we discover the file to exist.

Fixes #1262 and fixes #1109.

----

### Pull Request Checklist

Please check all boxes (including N/A items)

#### Testing

- [x] Unit test and/or integration test added
- [x] __Toolkit change?:__ [integration
tests](https://github.com/awslabs/aws-cdk/blob/master/packages/aws-cdk/integ-tests/test.sh)
manually executed (paste output to the PR description)
- [x] __Init template change?:__ coordinated update of integration tests
(currently maintained in a private repo).

#### Documentation

- [x] __README__: README and/or documentation topic updated
- [x] __jsdocs__: All public APIs documented

### Title and description

- [x] __Change type__: Title is prefixed with change type:
  * `fix(module): <title>` bug fix (_patch_)
  * `feat(module): <title>` feature/capability (_minor_)
  * `chore(module): <title> ` won't appear in changelog
  * `build(module): <title>` won't appear in changelog
- [x] __Title format__: Title uses lower case and doesn't end with a period
- [x] __Breaking change?__: Last paragraph of description is: `BREAKING
  CHANGE: <describe exactly what changed and how to achieve similar behavior +
  link to documentation/gist/issue if more details are required>`
- [x] __References__: Indicate issues fixed via: `Fixes #xxx` or `Closes #xxx`

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/aws-cdk/lib/api/util/sdk.ts [hunk 1]
```diff
@@ -389,6 +406,15 @@ async function hasEc2Credentials() {
   return instance;
 }
 
+async function setConfigVariable() {
+  const homeDir = process.env.HOME || process.env.USERPROFILE
+    || (process.env.HOMEPATH ? ((process.env.HOMEDRIVE || 'C:/') + process.env.HOMEPATH) : null) || os.homedir();
```
Comment (eladb) [inline packages/aws-cdk/lib/api/util/sdk.ts]: Wouldn't `os.homedir()` just do all of this for you?

File: packages/aws-cdk/lib/api/util/sdk.ts [hunk 2]
```diff
@@ -222,6 +224,21 @@ class DefaultAWSAccount {
...
+      await setConfigVariable();
+
+      // support these
+      // This might try to load a profile which as AssumeRole credentials. This will normally work for the JS SDK
+      // if AWS_PROFILE/AWS_SDK_LOAD_CONFIG are set, but we don't set those (we work directly from the API).
+      //
+      // Since there is no way to pass a { region } argument to the STS client used for AssumeRole credentials
+      // (https://github.com/aws/aws-sdk-js/issues/2377), we must now configure the region globally so that it will
+      // be picked up there.
+      // AWS.config.update({
```
Comment (eladb) [inline packages/aws-cdk/lib/api/util/sdk.ts]: Is this not true anymore? I am confused...

File: packages/aws-cdk/lib/api/util/sdk.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/aws-cdk/lib/api/util/sdk.ts]: Don't know. This is exactly what the SDK code does, I don't want to risk us going out of sync because there's some environment variable effect somewhere that we haven't considered.

File: packages/aws-cdk/lib/api/util/sdk.ts (hunk 2 above)
Comment (rix0rrr) [reply packages/aws-cdk/lib/api/util/sdk.ts]: Ah, you're right. This wasn't sufficient. We *MUST* load the config, and we *MUST* set the env var to do so. Will remove.

**Comment by rix0rrr** [comment]
```
============================================================================================
test-cdk-context.sh
============================================================================================
Testing for the context value
Context value contextkey reset. It will be refreshed on the next SDK synthesis run.
No context value with key contextkey
✅  success
============================================================================================
test-cdk-deploy-all.sh
============================================================================================
| ensuring cdk-toolkit-integration-test-1 is cleaned up
| ensuring cdk-toolkit-integration-test-2 is cleaned up
cdk-toolkit-integration-test-1
cdk-toolkit-integration-test-1: deploying...
cdk-toolkit-integration-test-1: creating CloudFormation changeset...
 0/2 | 10:13:42 | CREATE_IN_PROGRESS   | AWS::SNS::Topic | topic (topic69831491) 
 0/2 | 10:13:42 | CREATE_IN_PROGRESS   | AWS::SNS::Topic | topic (topic69831491) Resource creation Initiated
 1/2 | 10:13:53 | CREATE_COMPLETE      | AWS::SNS::Topic | topic (topic69831491) 

 ✅  cdk-toolkit-integration-test-1

Stack ARN:
cdk-toolkit-integration-test-2
cdk-toolkit-integration-test-2: deploying...
cdk-toolkit-integration-test-2: creating CloudFormation changeset...
 0/3 | 10:14:07 | CREATE_IN_PROGRESS   | AWS::SNS::Topic | topic1 (topic152D84A37) 
 0/3 | 10:14:07 | CREATE_IN_PROGRESS   | AWS::SNS::Topic | topic2 (topic2A4FB547F) 
 0/3 | 10:14:07 | CREATE_IN_PROGRESS   | AWS::SNS::Topic | topic1 (topic152D84A37) Resource creation Initiated
 0/3 | 10:14:07 | CREATE_IN_PROGRESS   | AWS::SNS::Topic | topic2 (topic2A4FB547F) Resource creation Initiated
 1/3 | 10:14:17 | CREATE_COMPLETE      | AWS::SNS::Topic | topic1 (topic152D84A37) 
 2/3 | 10:14:18 | CREATE_COMPLETE      | AWS::SNS::Topic | topic2 (topic2A4FB547F) 
 3/3 | 10:14:19 | CREATE_COMPLETE      | AWS::CloudFormation::Stack | cdk-toolkit-integration-test-2 

 ✅  cdk-toolkit-integration-test-2

Stack ARN:
Stack deployed successfully
cdk-toolkit-integration-test-1: destroying...

 ✅  cdk-toolkit-integration-test-1: destroyed
cdk-toolkit-integration-test-2: destroying...

 ✅  cdk-toolkit-integration-test-2: destroyed
✅  success
============================================================================================
test-cdk-deploy.sh
============================================================================================
| ensuring cdk-toolkit-integration-test-1 is cleaned up
| ensuring cdk-toolkit-integration-test-2 is cleaned up
cdk-toolkit-integration-test-2: deploying...
cdk-toolkit-integration-test-2: creating CloudFormation changeset...
 0/3 | 10:14:50 | CREATE_IN_PROGRESS   | AWS::SNS::Topic | topic1 (topic152D84A37) 
 0/3 | 10:14:51 | CREATE_IN_PROGRESS   | AWS::SNS::Topic | topic2 (topic2A4FB547F) 
 0/3 | 10:14:51 | CREATE_IN_PROGRESS   | AWS::SNS::Topic | topic1 (topic152D84A37) Resource creation Initiated
 0/3 | 10:14:51 | CREATE_IN_PROGRESS   | AWS::SNS::Topic | topic2 (topic2A4FB547F) Resource creation Initiated
 1/3 | 10:15:01 | CREATE_COMPLETE      | AWS::SNS::Topic | topic1 (topic152D84A37) 
 2/3 | 10:15:01 | CREATE_COMPLETE      | AWS::SNS::Topic | topic2 (topic2A4FB547F) 

 ✅  cdk-toolkit-integration-test-2

Stack ARN:
Stack deployed successfully
| assert that last command returned 1 line(s)
cdk-toolkit-integration-test-2: destroying...

 ✅  cdk-toolkit-integration-test-2: destroyed
✅  success
============================================================================================
test-cdk-deploy-with-role.sh
============================================================================================

An error occurred (NoSuchEntity) when calling the ListRolePolicies operation: The role with name cdk-integ-test-role cannot be found.

An error occurred (NoSuchEntity) when calling the DeleteRole operation: The role with name cdk-integ-test-role cannot be found.
Role does not exist yet
Sleeping a bit to improve chances of the role having propagated
| ensuring cdk-toolkit-integration-test-1 is cleaned up
| ensuring cdk-toolkit-integration-test-2 is cleaned up
cdk-toolkit-integration-test-2: deploying...
cdk-toolkit-integration-test-2: creating CloudFormation changeset...
 0/3 | 10:15:37 | CREATE_IN_PROGRESS   | AWS::SNS::Topic | topic2 (topic2A4FB547F) 
 0/3 | 10:15:37 | CREATE_IN_PROGRESS   | AWS::SNS::Topic | topic1 (topic152D84A37) 
 0/3 | 10:15:37 | CREATE_IN_PROGRESS   | AWS::SNS::Topic | topic1 (topic152D84A37) Resource creation Initiated
 0/3 | 10:15:37 | CREATE_IN_PROGRESS   | AWS::SNS::Topic | topic2 (topic2A4FB547F) Resource creation Initiated
 1/3 | 10:15:48 | CREATE_COMPLETE      | AWS::SNS::Topic | topic1 (topic152D84A37) 
 2/3 | 10:15:48 | CREATE_COMPLETE      | AWS::SNS::Topic | topic2 (topic2A4FB547F) 
 3/3 | 10:15:49 | CREATE_COMPLETE      | AWS::CloudFormation::Stack | cdk-toolkit-integration-test-2 

 ✅  cdk-toolkit-integration-test-2

Stack ARN:
Stack deployed successfully
| assert that last command returned 1 line(s)
cdk-toolkit-integration-test-2: destroying...

 ✅  cdk-toolkit-integration-test-2: destroyed
✅  success
============================================================================================
test-cdk-diff.sh
============================================================================================
| ensuring cdk-toolkit-integration-test-1 is cleaned up
| ensuring cdk-toolkit-integration-test-2 is cleaned up
| assert that last command returned 2 line(s)
| assert that last command returned 3 line(s)
✅  success
============================================================================================
test-cdk-ls.sh
============================================================================================
| ensuring cdk-toolkit-integration-test-1 is cleaned up
| ensuring cdk-toolkit-integration-test-2 is cleaned up
| running cdk ls
✅  success
============================================================================================
test-cdk-synth.sh
============================================================================================
| ensuring cdk-toolkit-integration-test-1 is cleaned up
| ensuring cdk-toolkit-integration-test-2 is cleaned up
| running cdk synth cdk-toolkit-integration-test-1
| running cdk synth cdk-toolkit-integration-test-2
✅  success
```
