### PR TITLE
Simple heuristics to determine python executable name across platforms

### LINKED ISSUE #2181: Python init template does not work on Windows
1. Python 3.7 installs python.exe, not python3.exe

1. There is no 'source' command in Windows

1. The paths shown in the README.md file are Linux/Unix/Mac, not Windows paths

### PR DESCRIPTION
**Pull request by garnaat**
Fixes #2181.

Added a simple function that determines Python executable name depending on underlying platform.  Changed a number of init templates to take advantage of that.

----

### Pull Request Checklist

* [ ] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [ ] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
* [ ] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [ ] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/aws-cdk/lib/init.ts [hunk 1]
```diff
@@ -263,18 +275,15 @@ async function postInstallJava(canUseNetwork: boolean) {
...
+  print(`Executing ${colors.green('Creating virtualenv')}`);
   try {
-    await execute('python3', '-m venv', '.env');
+    await execute(python, '-m venv', '.env');
   } catch (e) {
-    throw new Error(`${colors.green('python3 -m venv .env')} failed: ` + e.message);
-  }
+    print('Unable to create virtualenv automatically');
+    print(`Please run ${colors.green('python3 -m venv .env')}!`);
+    }
```
Comment (eladb) [inline packages/aws-cdk/lib/init.ts]: indentation

File: packages/aws-cdk/lib/init.ts [hunk 2]
```diff
@@ -263,18 +275,15 @@ async function postInstallJava(canUseNetwork: boolean) {
...
+  const python = pythonExecutable();
+  print(`Executing ${colors.green('Creating virtualenv')}`);
   try {
-    await execute('python3', '-m venv', '.env');
+    await execute(python, '-m venv', '.env');
   } catch (e) {
-    throw new Error(`${colors.green('python3 -m venv .env')} failed: ` + e.message);
-  }
+    print('Unable to create virtualenv automatically');
+    print(`Please run ${colors.green('python3 -m venv .env')}!`);
```
Comment (eladb) [inline packages/aws-cdk/lib/init.ts]: replace `"python3"` with `python`
