### PR TITLE
fix(cdk): merge cloudFormation tags with aspect tags

### LINKED ISSUE #1725: Unable to set child tags when parent tags are inherited
It seems when you apply tags at a parent scope, any additional tags set on a child will not be set.

```
class MyParentConstruct extends cdk.Construct {
  constructor(scope: cdk.Construct, id: string) {
    super(scope, id);

    this.apply(new cdk.Tag('Foo', 'Bar'));

    new MyChildConstruct(this, 'Child');
  }
}

class MyChildConstruct extends cdk.Construct {
  constructor(scope: cdk.Construct, id: string) {
    super(scope, id);

    new cdkEc2.CfnVPC(this, 'Vpc', {
      cidrBlock: '10.0.0.0/16',
      tags: [
        {key: 'Name', value: 'MyVPC'},
      ]
    });
  }
}
```

Results:
```
Resources:
  testChildVpc5FFB6B5B:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Foo
          Value: Bar
    Metadata:
      aws:cdk:path: PartitionStack/test/Child/Vpc
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=0.24.1,@aws-cdk/aws-cloudwatch=0.24.1,@aws-cdk/aws-ec2=0.24.1,@aws-cdk/aws-iam=0.24.1,@aws-cdk/aws-logs=0.24.1,@aws-cdk/cdk=0.24.1,@aws-cdk/cx-api=0.24.1,jsii-runtime=node.js/v8.11.3
```

I would expect that the child object would have both a 'Foo' and 'Name' tag.

### PR DESCRIPTION
**Pull request by moofish32**
This modifies the behavior of TagManager to enable the merging of tags
provided during Cfn* properties with tag aspects. If a collision occurs
the aspects tag precedence.

fixes #1725

----

### Pull Request Checklist

* [x] Testing
  - Unit test added
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [ ] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/cdk/lib/cloudformation/resource.ts [hunk 1]
```diff
@@ -254,14 +256,13 @@ export class Resource extends Referenceable {
...
   }
-
 }
 
 export enum TagType {
   Standard = 'StandardTag',
-  AutoScalingGroup = 'AutoScalingGroupTag',
-  Map = 'StringToStringMap',
-  NotTaggable = 'NotTaggable',
+    AutoScalingGroup = 'AutoScalingGroupTag',
```
Comment (moofish32) [inline packages/@aws-cdk/cdk/lib/cloudformation/resource.ts]: I'll fix this -- not sure where I need to fix this in my auto-formatter 👎

File: packages/@aws-cdk/cdk/lib/core/tag-manager.ts [hunk 2]
```diff
@@ -150,4 +151,45 @@ export class TagManager {
     }
     return true;
   }
+
+  private mergeFrom(propertyTags: any): void {
```
Comment (moofish32) [inline packages/@aws-cdk/cdk/lib/core/tag-manager.ts]: I think I might be ready to refactor to some form a subclass or composition class for each type of tag. These switch statements are not clean in my opinion. Do you think it's worth it at this point?

**Comment by moofish32** [comment]
I unchecked tests I think I owe at least two more for the testing the raise statements.

File: packages/@aws-cdk/cdk/test/aspects/test.tag-aspect.ts [hunk 3]
```diff
@@ -130,7 +130,7 @@ export = {
     test.deepEqual(res2.tags.renderTags(), [{key: 'key', value: 'value'}]);
     test.done();
   },
-  'Aspects are mutually exclusive with tags created by L1 Constructor'(test: Test) {
+  'Aspects are merged with tags created by L1 Constructor'(test: Test) {
```
Comment (rix0rrr) [inline packages/@aws-cdk/cdk/test/aspects/test.tag-aspect.ts]: Haha

File: packages/@aws-cdk/cdk/lib/core/tag-manager.ts [hunk 4]
```diff
@@ -94,7 +94,8 @@ export class TagManager {
   /**
    * Renders tags into the proper format based on TagType
    */
-  public renderTags(): any {
+  public renderTags(propertyTags?: any): any {
+    this.mergeFrom(propertyTags);
```
Comment (rix0rrr) [inline packages/@aws-cdk/cdk/lib/core/tag-manager.ts]: I find this slightly scary because it will change the state of the `TagManager` class. If `renderTags()` gets called twice, do we know it does the same the 2nd time around?

I'd prefer merging on a local variable.

File: packages/@aws-cdk/cdk/lib/core/tag-manager.ts (hunk 2 above)
Comment (rix0rrr) [reply packages/@aws-cdk/cdk/lib/core/tag-manager.ts]: I totally think that's a good idea. Should there not be instances of `TagFormatter` that live on a taggable `Resource`?

File: packages/@aws-cdk/cdk/lib/core/tag-manager.ts (hunk 4 above)
Comment (moofish32) [reply packages/@aws-cdk/cdk/lib/core/tag-manager.ts]: agree - because of the current design it was **accidentally** idempotent, not the right thing.

**Comment by moofish32** [comment]
@eladb @rix0rrr  -- I'm now seeing:

```
@aws-cdk/cdk: [2019-02-16T14:43:04.217] [ERROR] jsii/compiler - Type model errors prevented the JSII assembly from being created
@aws-cdk/cdk: lib/core/tag-manager.ts:50:33 - error JSII0: Only string index maps are supported
@aws-cdk/cdk: 50   renderTags(propertyTags: any, tags: Tags ): {tags: any};
@aws-cdk/cdk:                                    ~~~~~~~~~~
```
this is no longer allowed is my guess?

```ts
/**
 * Properties Tags is a dictionary of tags as strings
 */
type Tags = { [key: string]: {value: string, props: TagProps }};

/**
/**
 * Properties for a tag
 */
export interface TagProps {
  /**
   * Handles AutoScalingGroup PropagateAtLaunch property
   */
  applyToLaunchedInstances?: boolean;

  /**
   * An array of Resource Types that will not receive this tag
   *
   * An empty array will allow this tag to be applied to all resources. A
   * non-empty array will apply this tag only if the Resource type is not in
   * this array.
   * @default []
   */
  excludeResourceTypes?: string[];

  /**
   * An array of Resource Types that will receive this tag
   *
   * An empty array will match any Resource. A non-empty array will apply this
   * tag only to Resource types that are included in this array.
   * @default []
   */
  includeResourceTypes?: string[];

  /**
   * Higher or equal priority tags will take precedence
   *
   * Setting priority will enable the user to control tags when they need to not
   * follow the default precedence pattern of last applied and closest to the
   * construct in the tree.
   * @default 0 for Tag 1 for RemoveTag
   */
  priority?: number;
}
```
Specifically the use of `type Tags` up there?

**Comment by moofish32** [comment]
@eladb @rix0rrr - I refactored to eliminate what I think might be the JSII issue too which is the complex `type`. This means I needed to use a simple dictionary to manage an array of objects. 

A question on the precedence in this PR. The current position is aspects will override L1 prop tags. This seems weird given our precedence of closest to the node is the chosen value. The L1 property seems to be the *closest*, but we are not letting it overwrite the aspect. I've coded this so we can easily reverse this thinking. What do you all think?

**Comment by rix0rrr** [comment]
> A question on the precedence in this PR. The current position is aspects will override L1 prop tags.

Given that we have an L2 mechanism, who would ever set L1 tags? L2 writers shouldn't because they can use the L2 mechanism. Is there a use case in which this is logical? Or is this because of legacy code that right now uses an L1 mechanism which we need to rewrite to use the L2 mechanism?

**Comment by moofish32** [comment]
@rix0rrr - The description [here](https://github.com/awslabs/aws-cdk/issues/1725#issuecomment-462779314) is how this started. Technically, it's not as simple as order in these cases. As long as users can access L1 tags though, then this issue occurs.

File: packages/@aws-cdk/cdk/lib/core/tag-manager.ts [hunk 5]
```diff
@@ -151,3 +157,64 @@ export class TagManager {
...
+  }
+}
+
+class NoFormat implements ITagFormatter {
+  public renderTags(_tags: ITag[], _propertyTags: any): any {
+    return undefined;
+  }
+}
+
+function mergeTags(target: any, source: any): any {
```
Comment (rix0rrr) [inline packages/@aws-cdk/cdk/lib/core/tag-manager.ts]: I don't particularly like that this thing can handle both arrays and objects, because we lose type information this way. It should just handle arrays, and the `MapFormatter` should just do the object assignment directly.

File: packages/@aws-cdk/cdk/lib/core/tag-manager.ts [hunk 6]
```diff
@@ -44,16 +40,31 @@ export interface TagProps {
...
+
 /**
  * TagManager facilitates a common implementation of tagging for Constructs.
  */
 export class TagManager {
 
-  private readonly tags: Tags = {};
-
+  private readonly tags: ITag[] = [];
+  private readonly tagSet: {[key: string]: number} = {};
```
[the remark this answers is not in the document]
Comment (moofish32) [reply packages/@aws-cdk/cdk/lib/core/tag-manager.ts]: This whole confusion was me not understanding the JSII error above was telling me that I was leaking a private type. Refactored this to use Map where appropriate.

File: packages/@aws-cdk/cdk/lib/core/tag-manager.ts (hunk 5 above)
Comment (moofish32) [reply packages/@aws-cdk/cdk/lib/core/tag-manager.ts]: Fair - I did this so I could later flip the precedence, but moved it back as you requested.

File: packages/@aws-cdk/cdk/lib/core/tag-manager.ts [hunk 7]
```diff
@@ -87,51 +99,44 @@ export class TagManager {
...
+    const formatter = this.tagFormatter();
+    const tags: ITag[] = [];
+    for (const key of Object.keys(this.tagSet)) {
+      tags.push(this.tags[this.tagSet[key]]);
+    }
+    return formatter.renderTags(tags, propertyTags);
+  }
+
+  private tagFormatter(): ITagFormatter {
     switch (this.tagType) {
```
[the remark this answers is not in the document]
Comment (moofish32) [reply packages/@aws-cdk/cdk/lib/core/tag-manager.ts]: I preferred to leave the codegen with just the simple enum and moved to the `const TAG_FORMATTERS ... ` pattern. If you strongly otherwise I'll move it to codegen.

**Comment by moofish32** [comment]
Hmm - looks like a testing blip. Let me know if you see something different.

File: packages/@aws-cdk/cdk/lib/core/tag-manager.ts [hunk 8]
```diff
@@ -140,14 +182,25 @@ export class TagManager {
       include.indexOf(this.resourceTypeName) === -1) {
       return false;
     }
-    if (this.tags[key]) {
-      if (this.tags[key].props.priority !== undefined) {
-        return priority >= this.tags[key].props.priority!;
+    if (this.tags.has(key)) {
```
[the remark this answers is not in the document]
Comment (moofish32) [reply packages/@aws-cdk/cdk/lib/core/tag-manager.ts]: @rix0rrr - good feedback. 

Quick follow **is this a push to remove include/exclude by resource type**?

I think the crux of this issue is: 
> Now, I understand that doesn't fit in the current model really well, where we don't even know the TYPE of the L1 tags until we get to the renderer, so I won't make you change it.

What if we change that? We have a format for tag input that is agnostic to output. If I change the code generation to generate a tag type that is uniform (for input) and unique on output (to keep validation the same as it is today), then this issue disappears. If we look at the current tag input structures:

```ts
    tags?: object | cdk.Token;
// OR
    tags?: Array<cdk.CfnTag | cdk.Token> | cdk.Token;
// OR
    tags?: Array<CfnAutoScalingGroup.TagPropertyProperty | cdk.Token> | cdk.Token;
// We standardize to
    interface CdkTag { // not sure on this name yet
       key: string;
       value: string;
       // default 50 or whatever we decide from above
       priority?: number;
       // default true
       applyToLaunchedInstances?: boolean;
    }
    tags?: CdkTag[];
```
I think with our ability to treat tokens as strings and the ability to now add tags later via aspect we no longer need the `... | cdk.Token` definitions anywhere. Now @eladb might beat me up on ergonomics here. Yes, I agree simple key, value would be better. However, this keeps the L1 in a true declarative state. The rule I'm clearly breaking here is, this is the first input property that doesn't directly match CloudFormation. If somebody was writing a generator to turn templates into CDK files this would now require special code. I personally think the standardization is a bigger win, and later if we do a declarative CDK at the L2 level we have a consistent definition of tag.

Then in the constructor to `TagManager` we can pass in initial tags and they are effectively applied immediately because these tags do not propagate like an aspect. Now we roll in your changes from above and I think this is a much cleaner code solution where `merge` isn't really necessary. If it is necessary we can create the `merge` on a tag class that does this algebra as you describe.

[the remark this answers is not in the document]
Comment (rix0rrr) [reply packages/@aws-cdk/cdk/lib/core/tag-manager.ts]: Counter-proposal: we keep the L1 type definitions as they are (I do think there's value in sticking closely to the CFN model, if only for predictability and explainability), AND we define the one uber-type of tag, and we make the `TagFormatter` be able to convert between them:

```ts
interface ITagFormatter {
  parseTags(l1tags: any): CdkUberTag[];
  formatTags(tags: CdkUberTag[]): any;
}
```

So in fact, the tag *formatter* becomes a tag *converter*, back and forth from our unified L2 type to the various L1 types.

I *would* type the `any` more strictly there, but doing so would require generics and I think we might run afoul of JSII. It's going to require unnatural gymnastics to keep the definition of `ITagFormatter` out of reach of the JSII parser; it's probably simpler to type as `any` and add some runtime checks.

And then we can still use `TagFormatter/Converter` in the constructor to get the initial set of tags applied and we don't need to do any merging.

File: packages/@aws-cdk/cdk/README.md [hunk 9]
```diff
@@ -117,11 +117,19 @@ has a few features that are covered later to explain how this works.
 
 ### API
 
-In order to enable additional controls a Tags can specifically include or
+In order to enable additional controls a Tag can specifically include or
 exclude a CloudFormation Resource Type, propagate tags for an autoscaling group,
 and use priority to override the default precedence. See the `TagProps` 
 interface for more details. 
 
+Tags can be configured by using the properties for the AWS CloudFormation layer
```
Comment (eladb) [inline packages/@aws-cdk/cdk/README.md]: It should also be possible to specify tags in L2s via props (see #1935)

Comment (rix0rrr) [reply packages/@aws-cdk/cdk/README.md]: Let's not complicate this PR even further, and update the readme when we implement #1935.

Comment (eladb) [reply packages/@aws-cdk/cdk/README.md]: Yes, just wanted to call that out

File: packages/@aws-cdk/cdk/lib/core/tag-manager.ts [hunk 10]
```diff
@@ -140,14 +237,6 @@ export class TagManager {
...
-    if (this.tags[key]) {
-      if (this.tags[key].props.priority !== undefined) {
-        return priority >= this.tags[key].props.priority!;
-      }
-    }
-    if (this.removedTags[key]) {
-      return priority >= this.removedTags[key];
-    }
-    return true;
+    return priority >= (this.priorities.get(key) || 0);
```
Comment (moofish32) [inline packages/@aws-cdk/cdk/lib/core/tag-manager.ts]: Is this simplification enough? or did you want me to look at removing the include/exclude checks above as well.

File: tools/cfn2ts/lib/codegen.ts [hunk 11]
```diff
@@ -302,6 +302,10 @@ export default class CodeGenerator {
     if (deprecated) {
       this.code.line(`this.node.addWarning('DEPRECATION: ${deprecation}');`);
     }
+    if (tagEnum !== `${TAG_TYPE}.NotTaggable`) {
+      this.code.line('const tags = props === undefined ? undefined : props.tags;');
+      this.code.line(`this.tags = new ${TAG_MANAGER}(${tagEnum}, ${resourceTypeName}, tags);`);
```
Comment (moofish32) [inline tools/cfn2ts/lib/codegen.ts]: Added this to eliminate the "merge" concept.

File: tools/cfn2ts/lib/codegen.ts [hunk 12]
```diff
@@ -581,7 +588,7 @@ export default class CodeGenerator {
         if (union.indexOf('|') !== -1) {
           alternatives.push(`Array<${union}>`);
         } else {
-          alternatives.push(`(${union})[]`);
+          alternatives.push(`${union}[]`);
```
Comment (moofish32) [inline tools/cfn2ts/lib/codegen.ts]: was this dead code? It broke for me and changing this fixes it, but it does leave me asking how did this work if it wasn't dead code?

**Comment by rix0rrr** [comment]
Okay I'm going to have to eat crow :). I see the constraints you were working under now. Sorry!

**Comment by moofish32** [comment]
Thanks @rix0rrr @eladb - I'll head over to look at L2 tags next.
