### PR TITLE
fix(lambda): SingletonFunction ignores explicit declared dependencies

### LINKED ISSUE #7568: SingletonFunction ignores explicit dependencies via node.add_dependency (or node.addDependency)
Explicitly declaring dependencies with SingletonFunction constructs are silently ignored. This is true in both directions:
- singletonFunction.node.add_dependency(another_construct)
- another_construct.node.add_dependency(singletonFunction)

### Reproduction Steps
```bash
cdk synth (or deploy)
```

```python
        lambda_name_1 = f'{id}-lambda-1'
        singleton_lambda_1 = _lambda.SingletonFunction(
            self, lambda_name_1,
            uuid="B34394B8-3CCA-47FA-B1D5-DCDFCC7ED9CD",  # from uuidgen
            description="An Example Lambda 1",
            runtime=_lambda.Runtime.NODEJS_10_X,
            code=_lambda.InlineCode("exports.handler = (event, context) => context.succeed('hello world1');"),
            handler='index.handler',
            function_name=lambda_name_1
        )

        lambda_name_2 = f'{id}-lambda-2'
        singleton_lambda_2 = _lambda.SingletonFunction(
            self, lambda_name_2,
            uuid="9D7113E8-B954-4B7F-B67E-3C17F641F69A",  # from uuidgen
            description="An Example Lambda 2 - which should explicitly depend on Lambda 1.",
            runtime=_lambda.Runtime.NODEJS_10_X,
            code=_lambda.InlineCode("exports.handler = (event, context) => context.succeed('hello world2');"),
            handler='index.handler',
            function_name=lambda_name_2
        )               
        singleton_lambda_2.node.add_dependency(singleton_lambda_1) # silently ignored dependency on lamda-1
        singleton_lambda_2.node.add_dependency(example_role) # silently ignore dependency on example-role

```

### Error Log

```json
    "SingletonLambda9D7113E8B9544B7FB67E3C17F641F69A4A2DA42D": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "ZipFile": "exports.handler = (event, context) => context.succeed('hello world2');"
        },
        "Handler": "index.handler",
        "Role": {
          "Fn::GetAtt": [
            "SingletonLambda9D7113E8B9544B7FB67E3C17F641F69AServiceRole58F57FC5",
            "Arn"
          ]
        },
        "Runtime": "nodejs10.x",
        "Description": "An Example Lambda 2 - which should explicitly depend on Lambda 1.",
        "FunctionName": "test-depends-lambda-2"
      },
      "DependsOn": [
        "SingletonLambda9D7113E8B9544B7FB67E3C17F641F69AServiceRole58F57FC5"
      ],
      "Metadata": {
        "aws:cdk:path": "test-depends/SingletonLambda9D7113E8B9544B7FB67E3C17F641F69A/Resource"
      }
    }
```
when I switch to vanilla Function, rather than SingletonFunction for both Lambda1 and Lambda2 I see the expected dependencies present from both Lambda 1, and my Example Role.

**Expected Result**:
```json
      "DependsOn": [
        "testdependsexamplerole9DFB4232",
        "testdependslambda1CE722EFB",
        "testdependslambda1ServiceRoleBA30F7B6",
        "testdependslambda2ServiceRole1FA22585"
      ],
```

Furthermore, if I leave lambda1 as a SingletonFunction - and make lambda2 a vanilla Function - it will ignore my explicit dependency with lambda1, but recognize my explicit dependency with Example Role:

```json
      "DependsOn": [
        "testdependsexamplerole9DFB4232",
        "testdependslambda2ServiceRole1FA22585"
      ],
```

### Environment

  - **CLI Version      : aws-cli/1.16.223 Python/3.7.4 Darwin/18.7.0 botocore/1.12.213
  - **Framework Version: 1.31.0 (build 8f3ac79), NOTE: _Same behavior after upgrading to 1.34.1 (build 7b21aa0)_
  - **OS               : macOS 10.14.6 
  - **Language         : python3

### Other

I'm not sure this issue is limited to only SingletonFunction constructs.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by nija-at**
### Commit Message
fix(lambda): SingletonFunction ignores explicit declared dependencies (#7997)

The problem here is that the Function construct underlying the
SingletonFunction construct is attached directly to the Stack to enforce
the Stack-wide singleton behaviour.

This commit adds additional methods `addDependencies()` and `dependOn()`
methods to let customers declare these.

fixes #7568 
### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-lambda/lib/singleton-lambda.ts [hunk 1]
```diff
@@ -65,6 +65,22 @@ export class SingletonFunction extends FunctionBase {
     return this.lambdaFunction.addPermission(name, permission);
   }
 
+  /**
+   * Using node.addDependency() does not work on this method as the underlying lambda function is modeled
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-lambda/lib/singleton-lambda.ts:69]: does not work on this construct?
