### PR TITLE
fix(ec2): cfn-init user data hash not updated if file asset changes

### LINKED ISSUE #10206: [aws-ec2] Asset based file fingerprint is not included in ec2 user data.
When using CFN init with an `ec2.Instance`, setting `userDataCausesReplacement` (not default) and `initOptions.embedFingerprint` (the default) normally means modifying the provided CloudFormationInit will replace the instance.

However, with `InitFile` (added in #9664) using `InitFile.FromAsset` to specify a local file to be delivered as an asset, updating the local file does not update the fingerprint embedded in the user data, so instances are not replaced, even though the new asset is deployed.

### Reproduction Steps

1. Create an [`ec2.Instance`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Instance.html) with `userDataCausesReplacement` and `initOptions.embedFingerprint` and a `CloudFormationInit` containing an `InitFile.FromAsset` with a local file.
2. Deploy.
3. Modify the local file.
3. Deploy

### What did you expect to happen?

The instance should be replaced.

### What actually happened?

The instance is not replaced, even though the asset is.

### Environment

  - **CLI Version      :** 1.62.0
  - **Framework Version:** 1.62.0
  - **Node.js Version:** v12.18.0
  - **OS               :** Linux
  - **Language (Version):** Typescript

### Other

This might be intended and/or desirable behavior. Regardless, a flag like `includeFileAssetsInFingerprint` on `initOptions` or `includeInFingerprint` on `initFileOptions` would be prudent.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by njlynch**
We fingerprint the cfn-init configuration to insert into the user data so
changes to the cfn-init config can trigger an instance replacement; however,
the fingerprint was being calculated on the raw config, including tokens,
so the asset hash was not being considered in the fingerprint.

This fix resolves the tokens so the fingerprint takes asset hashes into
consideration.

fixes #10206

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-ec2/lib/cfn-init.ts [hunk 1]
```diff
@@ -97,7 +97,9 @@ export class CloudFormationInit {
     // Note: This will not reflect mutations made after attaching.
     const bindResult = this.bind(attachedResource.stack, attachOptions);
     attachedResource.addMetadata('AWS::CloudFormation::Init', bindResult.configData);
-    const fingerprint = contentHash(JSON.stringify(bindResult.configData)).substr(0, 16);
+    // Need to resolve the various tokens from assets in the config so the fingerprint is accurate.
+    const resolvedConfig = attachedResource.stack.resolve(bindResult.configData);
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-ec2/lib/cfn-init.ts:101]: I hinted at this not being good enough in our chat conversation, but I didn't actually send you a link on this.

This solution will work *for now*, but it's going to run afoul of the same limitation as this issue: https://github.com/aws/aws-cdk/issues/10136

**Review by rix0rrr — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-ec2/lib/cfn-init.ts (hunk 1 above)
Comment (njlynch) [reply packages/@aws-cdk/aws-ec2/lib/cfn-init.ts:103]: Added an `assetHash` to the `InitElementConfig` type and am now propagating that up back to the fingerprint.

**Review by rix0rrr — APPROVED** [review]
