### PR TITLE
fix(ec2): instance resourceSignalTimeout overwrites initOptions.timeout

### LINKED ISSUE #30052: (aws-ec2): Instance resourceSignalTimeout overwrites initOptions.timeout
### Describe the bug

When specifiying both `resourceSignalTimeout` and `initOptions.timeout` in the options for creating an EC2 Instance, only the value from `resourceSignalTimeout` is used.

### Expected Behavior

A timeout consisting of the sum of the values, or a clear error that specifying both fields is not supported.

### Current Behavior

`resourceSignalTimeout` overrides `initOptions.timeout` completely.

### Reproduction Steps

In a new CDK project:
```
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as ec2 from 'aws-cdk-lib/aws-ec2';

export class CdkStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
	
	const vpc = ec2.Vpc.fromLookup(this, "VPC", {
      isDefault: true,
    });

    new ec2.Instance(this, 'Instance', {
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.SMALL),
      machineImage: ec2.MachineImage.latestWindows(ec2.WindowsVersion.WINDOWS_SERVER_2019_ENGLISH_FULL_BASE),
	  vpc,
      init: ec2.CloudFormationInit.fromElements(
        ec2.InitCommand.shellCommand('echo "Hello World"'),
      ),
      initOptions: {
        timeout: cdk.Duration.minutes(20),
      },
	  resourceSignalTimeout: cdk.Duration.minutes(20),
	})
  }
}

```

The resulting template lists for the instance:

```
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M
```

### Possible Solution

In https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-ec2/lib/instance.ts, `initOptions.timeout` is applied before `resourceSignalTimeout`. The code to apply `initOptions.timeout` adds it to any preexisting timeout. Swapping the order of setup here should fix the issue.

### Additional Information/Context

_No response_

### CDK CLI Version

2.136.0 (build 94fd33b)

### Framework Version

_No response_

### Node.js Version

v18.18.0

### OS

Windows

### Language

TypeScript

### Language Version

5.0.4

### Other information

_No response_

### PR DESCRIPTION
**Pull request by michelle-wangg**
### Issue # (if applicable)

Closes #30052 

### Reason for this change
When specifiying both `resourceSignalTimeout` and `initOptions.timeout` in the options for creating an EC2 Instance, only the value from `resourceSignalTimeout` is used.

### Description of changes
- If both `initOptions.timeout` and `resourceSignalTimeout` are set, timeout consisting of the sum of the values and a warning suggesting that only one field should be specified
- Else, timeout is set to field specified, else defaults to 5 min

### Description of how you validated changes
- Update integration test for `instance-init.js` with both fields and verify that warning is logged
- Add unit tests:
  - `initOptions.timeout` and `resourceSignalTimeout` are both not set, timeout is set to default of 5 min
  - `initOptions.timeout` set and `resourceSignalTimeout` not set, timeout is set to initOptions.timeout
  - `initOptions.timeout` not set and `resourceSignalTimeout` is set, timeout is set to `resourceSignalTimeout`
  - `initOptions.timeout` and `resourceSignalTimeout` are both set, timeout is set to sum of timeouts and warning is logged

### Checklist
- [ ] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-ec2/lib/instance.ts [hunk 1]
```diff
@@ -589,12 +589,15 @@ export class Instance extends Resource implements IInstance {
     this.instancePublicDnsName = this.instance.attrPublicDnsName;
     this.instancePublicIp = this.instance.attrPublicIp;
 
+    if (props.initOptions?.timeout && props.resourceSignalTimeout) {
+      Annotations.of(this).addWarning('two fields set')
+    }
+    this.applyUpdatePolicies(props);
```
Comment (GavinZZ) [inline packages/aws-cdk-lib/aws-ec2/lib/instance.ts:595]: Why did you decide to move `this.applyUpdatePolicies` to the front?

File: packages/aws-cdk-lib/aws-ec2/lib/instance.ts [hunk 2]
```diff
@@ -589,12 +589,15 @@ export class Instance extends Resource implements IInstance {
     this.instancePublicDnsName = this.instance.attrPublicDnsName;
     this.instancePublicIp = this.instance.attrPublicIp;
 
+    if (props.initOptions?.timeout && props.resourceSignalTimeout) {
+      Annotations.of(this).addWarning('two fields set')
```
Comment (GavinZZ) [inline packages/aws-cdk-lib/aws-ec2/lib/instance.ts:593]: You should use the `addWarningV2` method as the one you used it deprecated. Also give a better error mesaage.

File: packages/aws-cdk-lib/aws-ec2/lib/instance.ts [hunk 3]
```diff
@@ -702,7 +706,10 @@ export class Instance extends Resource implements IInstance {
       this.instance.cfnOptions.creationPolicy = {
         ...this.instance.cfnOptions.creationPolicy,
         resourceSignal: {
-          timeout: props.resourceSignalTimeout && props.resourceSignalTimeout.toIsoString(),
+          ...this.instance.cfnOptions.creationPolicy?.resourceSignal,
```
Comment (GavinZZ) [inline packages/aws-cdk-lib/aws-ec2/lib/instance.ts:709]: Nice, just to confirm that this is needed otherwise it would remove `Count` from `ResourceSignal` right?

File: packages/aws-cdk-lib/aws-ec2/lib/instance.ts [hunk 4]
```diff
@@ -702,7 +706,10 @@ export class Instance extends Resource implements IInstance {
...
+          timeout: props.initOptions?.timeout ?
+            props.resourceSignalTimeout.plus(props.initOptions?.timeout).toIsoString() :
+            props.resourceSignalTimeout.toIsoString(),
```
Comment (GavinZZ) [inline packages/aws-cdk-lib/aws-ec2/lib/instance.ts:712]: what if `props.resourceSignalTimeout` is undefined?

**Review by GavinZZ — CHANGES_REQUESTED** [review]
Nice Michelle! Left some comments.

I see your fix would now be summing the two values up. This would mean that users (who haven't changed their template) would have the values updated in their next deployment if they upgrade their CDK version. This is generally a sign of breaking change, however, in this case it's extending the timeout value. I think this can be argued to be a non-breaking change. Can you include @moelasmar  in the review and get his though?

File: packages/aws-cdk-lib/aws-ec2/lib/instance.ts (hunk 3 above)
Comment (michelle-wangg) [reply packages/aws-cdk-lib/aws-ec2/lib/instance.ts:709]: There is surrounding if statement specified [here](https://github.com/aws/aws-cdk/blob/b6ad97f4b4e1c185ddc53f60e15b0dabd8022694/packages/aws-cdk-lib/aws-ec2/lib/instance.ts#L701)  that checks if `resourceSignalTimeout` is specified before updating the timeout

File: packages/aws-cdk-lib/aws-ec2/lib/instance.ts (hunk 4 above)
Comment (michelle-wangg) [reply packages/aws-cdk-lib/aws-ec2/lib/instance.ts:712]: There is surrounding if statement specified [here](https://github.com/aws/aws-cdk/blob/b6ad97f4b4e1c185ddc53f60e15b0dabd8022694/packages/aws-cdk-lib/aws-ec2/lib/instance.ts#L701)  that checks if `resourceSignalTimeout` is specified before updating the timeout

File: packages/aws-cdk-lib/aws-ec2/lib/instance.ts (hunk 1 above)
Comment (michelle-wangg) [reply packages/aws-cdk-lib/aws-ec2/lib/instance.ts]: Addressed in new commit updates

File: packages/aws-cdk-lib/aws-ec2/lib/instance.ts (hunk 2 above)
Comment (michelle-wangg) [reply packages/aws-cdk-lib/aws-ec2/lib/instance.ts]: Addressed in new commit updates

File: packages/aws-cdk-lib/aws-ec2/lib/instance.ts (hunk 4 above)
Comment (GavinZZ) [reply packages/aws-cdk-lib/aws-ec2/lib/instance.ts:712]: Ah ok, I didn't see that. Thanks for clarifying it.

File: packages/aws-cdk-lib/aws-ec2/lib/instance.ts [hunk 5]
```diff
@@ -589,6 +589,10 @@ export class Instance extends Resource implements IInstance {
     this.instancePublicDnsName = this.instance.attrPublicDnsName;
     this.instancePublicIp = this.instance.attrPublicIp;
 
+    if (props.initOptions?.timeout && props.resourceSignalTimeout) {
+      Annotations.of(this).addWarningV2('@aws-cdk/aws-ec2:setSetimeout', 'Both initOptions.timeout and resourceSignalTimeout fields are set, timeout is summed together. It is suggested that only one of the two fields is set');
+    }
+
```
[the remark this answers is not in the document]
Comment (michelle-wangg) [reply packages/aws-cdk-lib/aws-ec2/lib/instance.ts]: Updated!

File: packages/aws-cdk-lib/aws-ec2/lib/instance.ts [hunk 6]
```diff
@@ -695,14 +695,24 @@ export class Instance extends Resource implements IInstance {
...
     if (props.resourceSignalTimeout !== undefined) {
       this.instance.cfnOptions.creationPolicy = {
         ...this.instance.cfnOptions.creationPolicy,
         resourceSignal: {
-          timeout: props.resourceSignalTimeout && props.resourceSignalTimeout.toIsoString(),
+          ...this.instance.cfnOptions.creationPolicy?.resourceSignal,
+          timeout: props.initOptions?.timeout ?
+            props.resourceSignalTimeout.plus(props.initOptions?.timeout).toIsoString() :
```
Comment (kaizencc) [inline packages/aws-cdk-lib/aws-ec2/lib/instance.ts:714]: can you double check this for me: i don't think you need the `?` on this line because typescript should be smart enough to know `props.initOptions` must exist to be on this side of the ternary operator.

Comment (michelle-wangg) [reply packages/aws-cdk-lib/aws-ec2/lib/instance.ts]: Yes, you are right! I have updated this.

File: packages/aws-cdk-lib/aws-ec2/lib/instance.ts [hunk 7]
```diff
@@ -695,14 +695,24 @@ export class Instance extends Resource implements IInstance {
...
+
     if (props.resourceSignalTimeout !== undefined) {
       this.instance.cfnOptions.creationPolicy = {
         ...this.instance.cfnOptions.creationPolicy,
         resourceSignal: {
-          timeout: props.resourceSignalTimeout && props.resourceSignalTimeout.toIsoString(),
+          ...this.instance.cfnOptions.creationPolicy?.resourceSignal,
+          timeout: props.initOptions?.timeout ?
+            props.resourceSignalTimeout.plus(props.initOptions.timeout).toIsoString() :
+            props.resourceSignalTimeout.toIsoString(),
```
Comment (moelasmar) [inline packages/aws-cdk-lib/aws-ec2/lib/instance.ts:715]: although it looks safe to add the 2 numbers, but this may cause a breaking change for customers if the sum of the 2 numbers is more than 12 hours .. this should be a very rare case, but ay be some customers set one of these numbers to the maximum value, and since we ignore the other one, it was working for them, but now it will stop working.

Also, I can see that the original intent was to sum these 2 numbers together based on this code https://github.com/aws/aws-cdk/blob/4fa7716e0bc50c06327bc30320c5871207a11c52/packages/aws-cdk-lib/aws-ec2/lib/instance.ts#L686-L694 That is why I think summing the 2 numbers is still Ok, but we should do it using a feature flag.

Comment (moelasmar) [reply packages/aws-cdk-lib/aws-ec2/lib/instance.ts:715]: one more thing it is not needed to do this change here, it is enough to change this snippet https://github.com/aws/aws-cdk/blob/4fa7716e0bc50c06327bc30320c5871207a11c52/packages/aws-cdk-lib/aws-ec2/lib/instance.ts#L592-L596 to move `this.applyUpdatePolicies(props);` before the if condition

Comment (GavinZZ) [reply packages/aws-cdk-lib/aws-ec2/lib/instance.ts:715]: I think you're right that it may cause breaking changes when the sum is over the max threshold. Thanks for pointing that out.

For the second point, I disagree that we put it inside if statement because users could choose not to specify `props.init` and still setup the timeout value. Now if we move it inside, it won't happen anymore.

Comment (moelasmar) [reply packages/aws-cdk-lib/aws-ec2/lib/instance.ts:715]: i did not mean to put it inside the if condition, what I recommend is something like this 
```
this.applyUpdatePolicies(props); 

if (props.init) { 
   this.applyCloudFormationInit(props.init, props.initOptions); 
 } 
```

and to remove the addition changes that @michelle-wangg added to the `applyUpdatePolicies` method and depend that the addition logic is already exist in `applyCloudFormationInit` method some how:
https://github.com/aws/aws-cdk/blob/4fa7716e0bc50c06327bc30320c5871207a11c52/packages/aws-cdk-lib/aws-ec2/lib/instance.ts#L661-L695
See the login in `waitForResourceSignal`, by this change we do not need to duplicate the addition logic in 2 places.

For the warning message, I also prefer to move it to the constructor after the validations.

Comment (michelle-wangg) [reply packages/aws-cdk-lib/aws-ec2/lib/instance.ts]: Sounds good! I have updated the implementation to use a feature flag. Since I have not changed the logic `waitForResourceSignal`, even if `initOptions.Timeout` is not specified and `resourceSignalTimeout` is specified, the timeout will add the default 5 min to the resourceSignalTimeout.

File: packages/aws-cdk-lib/aws-ec2/lib/instance.ts [hunk 8]
```diff
@@ -589,11 +590,23 @@ export class Instance extends Resource implements IInstance {
     this.instancePublicDnsName = this.instance.attrPublicDnsName;
     this.instancePublicIp = this.instance.attrPublicIp;
 
-    if (props.init) {
-      this.applyCloudFormationInit(props.init, props.initOptions);
+    if (props.initOptions?.timeout && props.resourceSignalTimeout) {
```
Comment (moelasmar) [inline packages/aws-cdk-lib/aws-ec2/lib/instance.ts:593]: I believe if the feature flag is enabled, so no need for this warning, as this is our recommended behaviour.

File: packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init.js.snapshot/integ-init.template.json [hunk 9]
```diff
@@ -581,8 +581,7 @@
    ],
    "CreationPolicy": {
     "ResourceSignal": {
-     "Count": 1,
```
Comment (moelasmar) [inline packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init.js.snapshot/integ-init.template.json:584]: I believe `Count` should stay in the template

**Review by moelasmar — CHANGES_REQUESTED** [review]
left minor comments, and you need to rerun the integration test cases with `--update-on-failed` flag

File: packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init.js.snapshot/EnableSumTimeoutInstanceTestDefaultTestDeployAssert5CD5B9B5.template.json [hunk 10]
```diff
@@ -0,0 +1,36 @@
...
+        ]
+       }
+      ]
+     },
+     "AssertDescription": "CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI."
+    }
+   ]
+  }
+ }
+}
```
Comment (GavinZZ) [inline packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init.js.snapshot/EnableSumTimeoutInstanceTestDefaultTestDeployAssert5CD5B9B5.template.json:36]: What is this assert stack/template? I don't see any assert used. Can you remove the snapshot folder and re-run the tests again?

File: packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init.js.snapshot/EnableSumTimeoutInstanceTestDefaultTestDeployAssert5CD5B9B5.assets.json [hunk 11]
```diff
@@ -0,0 +1,19 @@
+{
```
Comment (GavinZZ) [inline packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init.js.snapshot/EnableSumTimeoutInstanceTestDefaultTestDeployAssert5CD5B9B5.assets.json:1]: Same for this file

File: packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.enable-sum-timeout-instance-init.js.snapshot/EnableSumTimeoutInstanceTestDefaultTestDeployAssert5CD5B9B5.assets.json [hunk 12]
```diff
@@ -0,0 +1,19 @@
+{
```
Comment (GavinZZ) [inline packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.enable-sum-timeout-instance-init.js.snapshot/EnableSumTimeoutInstanceTestDefaultTestDeployAssert5CD5B9B5.assets.json:1]: this too

File: packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init.js.snapshot/EnableSumTimeoutInstanceTestDefaultTestDeployAssert5CD5B9B5.template.json (hunk 10 above)
Comment (michelle-wangg) [reply packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init.js.snapshot/EnableSumTimeoutInstanceTestDefaultTestDeployAssert5CD5B9B5.template.json]: Correct me if I'm wrong but I believe that these are generated because of using `integ.IntegTest`, passing in the stack as the test case as follows:
```
new integ.IntegTest(app, 'instance-init-test', {
  testCases: [stack],
});
```
Since I deleted the snapshot folder and regenerated, it registered as a new test and therefore needed `IntegTest` construct to configure the test

File: packages/aws-cdk-lib/aws-ec2/lib/instance.ts [hunk 13]
```diff
@@ -589,11 +590,19 @@ export class Instance extends Resource implements IInstance {
...
+    if (FeatureFlags.of(this).isEnabled(cxapi.EC2_SUM_TIMEOUT_ENABLED)) {
+      this.applyUpdatePolicies(props);
+
+      if (props.init) {
+        this.applyCloudFormationInit(props.init, props.initOptions);
+      }
+    } else {
+      if (props.init) {
+        this.applyCloudFormationInit(props.init, props.initOptions);
+      }
```
Comment (GavinZZ) [inline packages/aws-cdk-lib/aws-ec2/lib/instance.ts:602]: One more thing before I approve. Can you leave some comments here to explain the sum operation when FF is true and the override, non-breaking behaviour with previous versions when FF is false.

Comment (michelle-wangg) [reply packages/aws-cdk-lib/aws-ec2/lib/instance.ts:605]: Just added!

**Review by GavinZZ — APPROVED** [review]

**Comment by GavinZZ** [comment]
@mergify update
