### PR TITLE
fix(ecr): autoDeleteImages fails when repository is renamed

### LINKED ISSUE #26711: (ECR): (Custom::ECRAutoDeleteImages fails on repo rename)
### Describe the bug

Within the same deployment environment I perform cdk deploy for ECR repositories and images stacks 
1.  using code from a default branch and then
2.  I run it again (after successful deployment) to a feature branch. 

The default branch stacks deploy successfully but the feature branch deployment fails to update my stacks due to what seems to be a renaming issue on ECR repositories in connection with `Custom::ECRAutoDeleteImages` resources . This is my first error

```
The following resource(s) failed to update: [basimagerepoAutoDeleteImagesCustomResource9BC77A26].
```

Because of

```
Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: User: arn:aws:sts::1234567890:assumed-role/my-stack-prefix-CustomECRAutoDeleteImage-1ESL2R8Y9CLAL/my-stack-prefix-infrastr-CustomECRAutoDeleteImage-D9sNwuezjpai is not authorized to perform: ecr:DescribeRepositories on resource: arn:aws:ecr:us-east-1:543276908693:repository/my/base_image because no identity-based policy allows the ecr:DescribeRepositories action at throwDefaultError (/var/runtime/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22) at deserializeAws_json1_1DescribeRepositoriesCommandError (/var/runtime/node_modules/@aws-sdk/client-ecr/dist-cjs/protocols/Aws_json1_1.js:1212:51) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async /var/runtime/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24 at async /var/runtime/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:13:20 at async StandardRetryStrategy.retry (/var/runtime/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46) at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22 at async f (/var/task/index.js:1:3557) at async Runtime.handler (/var/task/index.js:1:1152) (RequestId: af95f9de-6958-4e02-af53-84a6a54d9b2c)
```

and then, when the rollback is attempted, the rollback fails on 

```
The following resource(s) failed to update: [baseimagerepoAutoDeleteImagesCustomResource9BC77A26].
```

because of

```
Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: User: arn:aws:sts::1234567890:assumed-role/my-stack-prefix-CustomECRAutoDeleteImage-1ESL2R8Y9CLAL/my-stack-prefix-CustomECRAutoDeleteImage-D9sNwuezjpai is not authorized to perform: ecr:DescribeRepositories on resource: arn:aws:ecr:us-east-1:1234567890:repository/my/new/base_image because no identity-based policy allows the ecr:DescribeRepositories action at throwDefaultError (/var/runtime/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22) at deserializeAws_json1_1DescribeRepositoriesCommandError (/var/runtime/node_modules/@aws-sdk/client-ecr/dist-cjs/protocols/Aws_json1_1.js:1212:51) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async /var/runtime/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24 at async /var/runtime/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:13:20 at async StandardRetryStrategy.retry (/var/runtime/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46) at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22 at async f (/var/task/index.js:1:3557) at async Runtime.handler (/var/task/index.js:1:1152) (RequestId: a6111bf7-1f99-4a5c-b9c4-224a039a04a0)
```

Note 1. that the the two error messages are different in that the initial failure includes my old repo name but the rollback failure includes the new name. Here they are side-by-side. The first one is UPDATE_FAILED, the second is UPDATE_ROLLBACK_FAILED

```
...User: arn:aws:sts::1234567890:assumed-role/my-stack-prefix-CustomECRAutoDeleteImage-1ESL2R8Y9CLAL/my-stack-prefix-CustomECRAutoDeleteImage-D9sNwuezjpai is not authorized to perform: ecr:DescribeRepositories on resource: arn:aws:ecr:us-east-1:1234567890:repository/my/base_image
...User: arn:aws:sts::1234567890:assumed-role/my-stack-prefix-CustomECRAutoDeleteImage-1ESL2R8Y9CLAL/my-stack-prefix-CustomECRAutoDeleteImage-D9sNwuezjpai is not authorized to perform: ecr:DescribeRepositories on resource: arn:aws:ecr:us-east-1:1234567890:repository/my/new/base_image
```

Note2. that all the newly named repos/images I created in ECR appeare to have deployed successfully, even though some them belonged to the failed stacks. So the issue seems to be isolated to the `Custom::ECRAutoDeleteImages` resource.

Note3. Termination protection is not enabled on these tasks or repositories and specifically we have on our ECR construct.
```
removal_policy = aws_cdk.RemovalPolicy.DESTROY
auto_delete_images = True
```

### Expected Behavior

1. Previously named repos would be destroyed along with any images they house
5.  New repos/images successful
6. `Custom::ECRAutoDeleteImages` updated successfully

### Current Behavior

See description section. Full errors logged there.

### Reproduction Steps

`cdk deploy` with
```
props = {}
props["repository_name"] = "name1"
props["removal_policy"] = aws_cdk.RemovalPolicy.DESTROY
props["auto_delete_images"] = True

Repository(
    scope=scope,
    id=construct_id,
    **props,
    **kwargs,
)
```
then presumably another deploy (in same stack) with
```
props = {}
props["repository_name"] = "name2"
props["removal_policy"] = aws_cdk.RemovalPolicy.DESTROY
props["auto_delete_images"] = True

Repository(
    scope=scope,
    id=construct_id,
    **props,
    **kwargs,
)
```

### Possible Solution

Race condition with custom resource settings needs resolve.

### Additional Information/Context

None

### CDK CLI Version

2.2.200

### Framework Version

2.89.0

### Node.js Version

16

### OS

Linux

### Language

Python

### Language Version

3.10.11

### Other information

_No response_

### PR DESCRIPTION
**Pull request by go-to-k**
This PR fixes the bug that ECRAutoDeleteImages fails on repo rename.

The customResource depends on the role, and when the repository name changes, the role is updated to match the new repository instead of the old one, before customResource runs and the old repository is deleted.

It was difficult to delete the old repo before the role update ran, so I changed the resource of the role to a wildcard.

Closes #26711.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by go-to-k** [comment]
Exemption Request because the unit tests covered changing role.

**Comment by go-to-k** [comment]
@rix0rrr 

Thanks for comments!

> I think a better solution for this would be add an `AWS::IAM::Policy` resource for every repository, and make sure the logical identifier of those resources is generated based off the repository name.

Does this mean using `iam.Policy` instead of `addToRolePolicy`?

```ts
new iam.Policy(this, `${this.repositoryName}Policy`, { // There may be differences in the rules between repositoryName and logical identifier
    roles: ... // specifying new role instance generated from provider.roleArn
    statements: ... // for the repository
});
```

I still don't understand why this is good.

When the repository name is changed, the old repository is deleted and a new one is created, and the images in the old repository are deleted, but doesn't the IAM policy also update to match the new repository name and eventually you no longer have permission to delete the old one?

**Comment by rix0rrr** [comment]
> Does this mean using iam.Policy instead of addToRolePolicy?

Yes.

Doing this, `this.repositoryName` may not be a token though so that may be hard to pull off.

> I still don't understand why this is good.

Because of the order of CloudFormation resource operations during a stack update. There are two phases during a deployment:

1. CREATE/UPDATE
2. CLEANUP (in fact, DELETE)

So the policy that grants permissions to the *old* repository name will be deleted during the CLEANUP phase, when the actual ECR repository itself is also cleaned up.

-------

I'm really not comfortable with the `*`.

If, because of the token-ness and unpredictability of `this.repositoryName`, this cannot work, a good compromise may be to put a tag on the ECR repository (`cdk:allow-deleting-images=true`; in fact there should already be a tag on there) and use [tag-based access control](https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr-supported-iam-actions-tagging.html) with a `Condition`.

File: packages/aws-cdk-lib/aws-ecr/lib/repository.ts [hunk 1]
```diff
@@ -881,10 +877,8 @@ export class Repository extends RepositoryBase {
           'ecr:ListImages',
           'ecr:ListTagsForResource',
         ],
-        Resource: Lazy.list({ produce: () => repoArns }),
+        Resource: [`arn:${Aws.PARTITION}:ecr:${Stack.of(this).region}:${Stack.of(this).account}:repository/*`],
       });
-    } else {
-      (provider as any)[REPO_ARN_SYMBOL].push(this._resource.attrArn);
     }
```
Comment (go-to-k) [inline packages/aws-cdk-lib/aws-ecr/lib/repository.ts:882]: @rix0rrr 

Are the following changes correct?

before
```ts
    if (firstTime) {
      const repoArns = [this._resource.attrArn];
      (provider as any)[REPO_ARN_SYMBOL] = repoArns;

      // Use a iam policy to allow the custom resource to list & delete
      // images in the repository and the ability to get all repositories to find the arn needed on delete.
      // We lazily produce a list of repositories associated with this custom resource provider.
      provider.addToRolePolicy({
        Effect: 'Allow',
        Action: [
          'ecr:BatchDeleteImage',
          'ecr:DescribeRepositories',
          'ecr:ListImages',
          'ecr:ListTagsForResource',
        ],
        Resource: Lazy.list({ produce: () => repoArns }),
      });
    } else {
      (provider as any)[REPO_ARN_SYMBOL].push(this._resource.attrArn);
    }
```

after
```ts
    const role = iam.Role.fromRoleArn(this, `${this.repositoryName}Role`, provider.roleArn);

    // Use a iam policy to allow the custom resource to list & delete
    // images in the repository and the ability to get all repositories to find the arn needed on delete.
    new iam.Policy(this, `${this.repositoryName}Policy`, {
      roles: [role],
      statements: [
        new iam.PolicyStatement({
          effect: iam.Effect.ALLOW,
          actions: [
            'ecr:BatchDeleteImage',
            'ecr:DescribeRepositories',
            'ecr:ListImages',
            'ecr:ListTagsForResource',
          ],
          resources: [this._resource.attrArn],
        }),
      ],
    });
```

I created a stack with this code and changed the repository name and got the following error.

(And the `${repositoryName}Policy` become to `undefinedPolicy`)

```
Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: User: arn:aws:sts::1234567890:assumed-role/aws-ecr-integ-stack-CustomECRAutoDeleteImagesCusto-14DD6ZRSES8VD/aws-ecr-integ-stack-CustomECRAutoDeleteImagesCusto-iDtGtDvsp9Yb is not authorized to perform: ecr:DescribeReposito
ries on resource: arn:aws:ecr:ap-northeast-1:1234567890:repository/delete-even-if-containing-images because no identity-based policy allows the ecr:DescribeRepositories action
```

> If, because of the token-ness and unpredictability of this.repositoryName, this cannot work, a good compromise may be to put a tag on the ECR repository (cdk:allow-deleting-images=true; in fact there should already be a tag on there) and use [tag-based access control](https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr-supported-iam-actions-tagging.html) with a Condition.

In that case, is this the way to go?

File: packages/aws-cdk-lib/aws-ecr/lib/repository.ts [hunk 2]
```diff
@@ -881,10 +877,13 @@ export class Repository extends RepositoryBase {
           'ecr:ListImages',
           'ecr:ListTagsForResource',
         ],
-        Resource: Lazy.list({ produce: () => repoArns }),
+        Resource: [`arn:${Aws.PARTITION}:ecr:${Stack.of(this).region}:${Stack.of(this).account}:repository/*`],
+        Condition: {
+          StringEquals: {
+            ['ecr:ResourceTag/' + AUTO_DELETE_IMAGES_TAG]: 'true',
+          },
+        },
```
Comment (go-to-k) [inline packages/aws-cdk-lib/aws-ecr/lib/repository.ts:885]: @rix0rrr 

I implemented tag-based access control with a Condition for now.

File: packages/aws-cdk-lib/aws-ecr/lib/repository.ts (hunk 1 above)
Comment (go-to-k) [reply packages/aws-cdk-lib/aws-ecr/lib/repository.ts:887]: @rix0rrr 

I used `physicalName` instead of `repositoryName` and it worked!

Because `this.repositoryName` is a Token (lazy value), but `physicalName` is `props.repositoryName`.

However, `props.repositoryName` may be unspecified, in which case the `props.repositoryName` will be `undefined` and duplicate the IAM policy, which is not a good practice.

Comment (rix0rrr) [reply packages/aws-cdk-lib/aws-ecr/lib/repository.ts:887]: I agree, you can't use `physicalName` in this case. We should probably go the tag route then, a naked `*` is too dangerous for my tastes.

**Review by rix0rrr — DISMISSED** [review]

**Review by rix0rrr — APPROVED** [review]
