### PR TITLE
fix(ec2): internet gateway is created even if public subnets are reserved

### LINKED ISSUE #28593: aws-ec2: Internet Gateway created when public subnets are reserved
### Describe the bug

An internet gateway is created for a VPC where address space is reserved for public subnets, but the public subnets do not actually exist

### Expected Behavior

An internet Gateway is not created for the Vpc when the address space for public subnets are reserved, but no public subnets actually exist

### Current Behavior

An internet gateway is created for a VPC where address space is reserved for public subnets, but the public subnets do not actually exist

### Reproduction Steps

```ts
import * as cdk from 'aws-cdk-lib';
import { SubnetType, Vpc } from 'aws-cdk-lib/aws-ec2';
export class MyStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    new Vpc(this, 'vpc', {
      subnetConfiguration: [
        {
          name: 'Isolated',
          subnetType: SubnetType.PRIVATE_ISOLATED,
          cidrMask: 22,
        },
        {
          name: 'Public',
          subnetType: SubnetType.PUBLIC,
          cidrMask: 26,
          reserved: true,
        },
      ],
    });
  }
};
const app = new cdk.App();
new MyStack(app, 'test');
app.synth();
```

CloudFormation Output
```yml
Resources:
  vpcA2121C38:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: test/vpc
    Metadata:
      aws:cdk:path: test/vpc/Resource
  vpcIsolatedSubnet1Subnet8B28CEB3:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      CidrBlock: 10.0.0.0/22
      MapPublicIpOnLaunch: false
      Tags:
        - Key: aws-cdk:subnet-name
          Value: Isolated
        - Key: aws-cdk:subnet-type
          Value: Isolated
        - Key: Name
          Value: test/vpc/IsolatedSubnet1
      VpcId:
        Ref: vpcA2121C38
    Metadata:
      aws:cdk:path: test/vpc/IsolatedSubnet1/Subnet
  vpcIsolatedSubnet1RouteTable0D6B2D3D:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: test/vpc/IsolatedSubnet1
      VpcId:
        Ref: vpcA2121C38
    Metadata:
      aws:cdk:path: test/vpc/IsolatedSubnet1/RouteTable
  vpcIsolatedSubnet1RouteTableAssociation172210D4:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: vpcIsolatedSubnet1RouteTable0D6B2D3D
      SubnetId:
        Ref: vpcIsolatedSubnet1Subnet8B28CEB3
    Metadata:
      aws:cdk:path: test/vpc/IsolatedSubnet1/RouteTableAssociation
  vpcIsolatedSubnet2Subnet2C6B375C:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      CidrBlock: 10.0.4.0/22
      MapPublicIpOnLaunch: false
      Tags:
        - Key: aws-cdk:subnet-name
          Value: Isolated
        - Key: aws-cdk:subnet-type
          Value: Isolated
        - Key: Name
          Value: test/vpc/IsolatedSubnet2
      VpcId:
        Ref: vpcA2121C38
    Metadata:
      aws:cdk:path: test/vpc/IsolatedSubnet2/Subnet
  vpcIsolatedSubnet2RouteTable3455CBFC:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: test/vpc/IsolatedSubnet2
      VpcId:
        Ref: vpcA2121C38
    Metadata:
      aws:cdk:path: test/vpc/IsolatedSubnet2/RouteTable
  vpcIsolatedSubnet2RouteTableAssociation8A8FAF70:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: vpcIsolatedSubnet2RouteTable3455CBFC
      SubnetId:
        Ref: vpcIsolatedSubnet2Subnet2C6B375C
    Metadata:
      aws:cdk:path: test/vpc/IsolatedSubnet2/RouteTableAssociation
  vpcIGWE57CBDCA:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: test/vpc
    Metadata:
      aws:cdk:path: test/vpc/IGW
  vpcVPCGW7984C166:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: vpcIGWE57CBDCA
      VpcId:
        Ref: vpcA2121C38
    Metadata:
      aws:cdk:path: test/vpc/VPCGW
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/02PTQ+CMAyGf4v3MYXExCvhYLwZMFzNGDWWj85sHcQQ/rtDSfDUt0+bp2ki4/gkDzs1ukjXbdRhJaeClW5FQHfQiZzKlxbZg8prJq4WB8VQ+IqAF7il3HiGm6o62PjGUueMRsVoaBlfiMGGhXOQjeq96tcu5XD/2QPxLHJwxlv9df7nzFCNi20WZGqQjdsP4ZH4GH5pHGJkPTH2IPNf/QDK5AK06AAAAA==
    Metadata:
      aws:cdk:path: test/CDKMetadata/Default
    Condition: CDKMetadataAvailable

```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.118.0 (build a40f2ec)

### Framework Version

_No response_

### Node.js Version

Node.js v18.15.0

### OS

Osx

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by go-to-k**
This PR fixes that Internet Gateway will be created even if (all) public subnets are reserved.

The `reserved` option is for not actually creating subnet resources. So IGW should not be created if all public subnets are reserved, because there is no public subnets in the VPC.

It would be appropriate to consider the `reserved` option since [we originally did not want to create an IGW if there was no public subnets](https://github.com/aws/aws-cdk/blob/v2.118.0/packages/aws-cdk-lib/aws-ec2/lib/vpc.ts#L1493-L1497).

Also, if this bug is not fixed, it will go to the [code where the NatGateway is created](https://github.com/aws/aws-cdk/blob/v2.118.0/packages/aws-cdk-lib/aws-ec2/lib/vpc.ts#L1513-L1517) without public subnets. (This will be stopped with another error, but...)

Closes #28593.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-ec2/lib/vpc.ts [hunk 1]
```diff
@@ -2403,7 +2403,7 @@ class ImportedSubnet extends Resource implements ISubnet, IPublicSubnet, IPrivat
 function determineNatGatewayCount(requestedCount: number | undefined, subnetConfig: SubnetConfiguration[], azCount: number) {
   const hasPrivateSubnets = subnetConfig.some(c => (c.subnetType === SubnetType.PRIVATE_WITH_EGRESS
     || c.subnetType === SubnetType.PRIVATE || c.subnetType === SubnetType.PRIVATE_WITH_NAT) && !c.reserved);
-  const hasPublicSubnets = subnetConfig.some(c => c.subnetType === SubnetType.PUBLIC);
+  const hasPublicSubnets = subnetConfig.some(c => c.subnetType === SubnetType.PUBLIC && !c.reserved);
```
Comment (go-to-k) [inline packages/aws-cdk-lib/aws-ec2/lib/vpc.ts:2406]: This issue can be solved without this change, but it should be changed in the same way.

File: packages/aws-cdk-lib/aws-ec2/lib/vpc.ts [hunk 2]
```diff
@@ -1491,7 +1491,7 @@ export class Vpc extends VpcBase {
 
     const createInternetGateway = props.createInternetGateway ?? true;
     const allowOutbound = this.subnetConfiguration.filter(
-      subnet => (subnet.subnetType !== SubnetType.PRIVATE_ISOLATED && subnet.subnetType !== SubnetType.ISOLATED)).length > 0;
+      subnet => (subnet.subnetType !== SubnetType.PRIVATE_ISOLATED && subnet.subnetType !== SubnetType.ISOLATED && !subnet.reserved)).length > 0;
```
Comment (go-to-k) [inline packages/aws-cdk-lib/aws-ec2/lib/vpc.ts:1494]: I honestly thought the following would be good here, but I'll leave it as is. (Because if there is no `PUBLIC` but `PRIVATE_WITH_EGRESS` in the code that follows, there will be an error.)

```suggestion
      subnet => (subnet.subnetType === SubnetType.PUBLIC && !subnet.reserved)).length > 0;
```

Comment (lpizzinidev) [reply packages/aws-cdk-lib/aws-ec2/lib/vpc.ts:1494]: The two implementations are different and `subnet => (subnet.subnetType === SubnetType.PUBLIC && !subnet.reserved)).length > 0;` would not allow the creation of internet or NAT gateways for `PRIVATE_WITH_EGRESS` subnets (unless at least a public subnet is present).
Can you please elaborate on why you considered making the change?

Comment (go-to-k) [reply packages/aws-cdk-lib/aws-ec2/lib/vpc.ts:1494]: > subnet => (subnet.subnetType === SubnetType.PUBLIC && !subnet.reserved)).length > 0; would not allow the creation of internet or NAT gateways for PRIVATE_WITH_EGRESS subnets (unless at least a public subnet is present).

The reason is that trying to create Nat gateways with `PRIVATE_WITH_EGRESS` without a public subnet in the first place would result in an error.

https://github.com/aws/aws-cdk/blob/v2.118.0/packages/aws-cdk-lib/aws-ec2/lib/vpc.ts#L2416-L2419

As for the Internet Gateway, I questioned whether there was a need to create it without a public subnet (like the following code). However, since it is not good to carelessly change the behavior, I left it as it was, just in case.

```ts
      new Vpc(stack, 'TheVPC', {
        subnetConfiguration: [
          {
            subnetType: SubnetType.PRIVATE_WITH_EGRESS,
            name: 'egress',
          },
        ],
        natGateways: 0,
      });
```

Comment (lpizzinidev) [reply packages/aws-cdk-lib/aws-ec2/lib/vpc.ts:1494]: Thanks for the clarification.
Yeah, I'd just leave it as is unless we have a specific reason to change it to avoid potential errors with existing deployments.

File: packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts [hunk 3]
```diff
@@ -379,6 +379,59 @@ describe('vpc', () => {
 
     });
 
+    test('with only reserved subnets as public subnets, should not create the internet gateway', () => {
```
Comment (lpizzinidev) [inline packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts:382]: Can you please add a similar test case with a  reserved `PRIVATE_WITH_EGRESS` subnet?

File: packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts [hunk 4]
```diff
@@ -379,6 +379,59 @@ describe('vpc', () => {
...
+          {
+            subnetType: SubnetType.PUBLIC,
+            name: 'public',
+            reserved: true,
+          },
+        ],
+      });
+      Template.fromStack(stack).resourceCountIs('AWS::EC2::InternetGateway', 0);
+      Template.fromStack(stack).resourceCountIs('AWS::EC2::VPCGatewayAttachment', 0);
+
```
Comment (lpizzinidev) [inline packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts:399]:
```suggestion
```

File: packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts [hunk 5]
```diff
@@ -379,6 +379,59 @@ describe('vpc', () => {
...
+      expect(() => new Vpc(stack, 'TheVPC', {
+        subnetConfiguration: [
+          {
+            subnetType: SubnetType.PRIVATE_WITH_EGRESS,
+            name: 'egress',
+          },
+        ],
+        natGateways: 1,
+      })).toThrow(/If you configure PRIVATE subnets in 'subnetConfiguration', you must also configure PUBLIC subnets to put the NAT gateways into \(got \[{"subnetType":"Private","name":"egress"}\]./);
+
```
Comment (lpizzinidev) [inline packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts:413]:
```suggestion
```

File: packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts [hunk 6]
```diff
@@ -379,6 +379,59 @@ describe('vpc', () => {
...
+            reserved: true,
+          },
+          {
+            subnetType: SubnetType.PRIVATE_WITH_EGRESS,
+            name: 'egress',
+          },
+        ],
+        natGateways: 1,
+      })).toThrow(/If you configure PRIVATE subnets in 'subnetConfiguration', you must also configure PUBLIC subnets to put the NAT gateways into \(got \[{"subnetType":"Public","name":"public","reserved":true},{"subnetType":"Private","name":"egress"}\]./);
+
```
Comment (lpizzinidev) [inline packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts:432]:
```suggestion
```

**Review by lpizzinidev — CHANGES_REQUESTED** [review]
Looks good 👍
I just left some notes for super minor adjustments.

**Comment by go-to-k** [comment]
@lpizzinidev 

Thanks, I fixed!

**Review by lpizzinidev — APPROVED** [review]
Thanks 👍

**Review by paulhcsun — APPROVED** [review]
Thanks for the fix @go-to-k and thanks for reviewing @lpizzinidev! Thanks for your patience for getting this over the line.
