### PR TITLE
fix(ec2):  dual-stack vpc without private subnets creates EgressOnlyInternetGateway (under feature flag)

### LINKED ISSUE #30981: (aws-ec2): Vpc creates EgressOnlyInternetGateway without private subnets
### Describe the bug

When creating a Dual Stack VPC, an EgressOnlyInternetGateway is created even if there are no private subnets. This comes from a vaulty condition, in `vpc.ts`:

https://github.com/aws/aws-cdk/blob/3f930279513b0f168333c6f6038b8ad81b99b7e1/packages/aws-cdk-lib/aws-ec2/lib/vpc.ts#L1644-L1647

`this.privateSubnets` check will also evaluate to true on empty arrays.

### Expected Behavior

No EgressOnlyInternetGateway is created without private subnets

### Current Behavior

EgressOnlyInternetGateway is created without private subnets

### Reproduction Steps

```
new Vpc(this, "Vpc", {
  ipProtocol: IpProtocol.DUAL_STACK,
  subnetConfiguration: [
    {
      subnetType: SubnetType.PUBLIC,
      name: "public",
    },
  ],
});
```

### Possible Solution

Check the length:
```
this.privateSubnets.length > 0
```

### Additional Information/Context

_No response_

### CDK CLI Version

2.150.0 (build 3f93027)

### Framework Version

_No response_

### Node.js Version

v22.5.1

### OS

MacOS

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by maharajhaider**
### Issue # (if applicable)

Closes #30981.

### Reason for this change
-> EgressOnlyInternetGateway was been created even without any private subnets

### Description of changes
-> Fixed the condition that determins if a EgressOnlyInternetGateway will be created
-> Added feature flag

### Describe any new or updated permissions being added
N/A

### Description of how you validated changes
I added two new unit tests that checks if EgressOnlyInternetGateway is created without a private subnet

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by paulhcsun** [comment]
For the PR title please change it to describe the bug and not the actual fix.

File: packages/aws-cdk-lib/cx-api/lib/features.ts [hunk 1]
```diff
@@ -137,6 +137,7 @@ export const DYNAMODB_TABLE_RETAIN_TABLE_REPLICA = '@aws-cdk/aws-dynamodb:retain
 export const LOG_USER_POOL_CLIENT_SECRET_VALUE = '@aws-cdk/cognito:logUserPoolClientSecretValue';
 export const PIPELINE_REDUCE_CROSS_ACCOUNT_ACTION_ROLE_TRUST_SCOPE = '@aws-cdk/pipelines:reduceCrossAccountActionRoleTrustScope';
 export const S3_TRUST_KEY_POLICY_FOR_SNS_SUBSCRIPTIONS = '@aws-cdk/s3-notifications:addS3TrustKeyPolicyForSnsSubscriptions';
+export const ENABLE_E2_REMOVE_EGRESSONLYGATEWAY_FROM_PUBLIC_SUBNET_VPC = '@aws-cdk/ec2:removeEgressOnlyGatewayFromPublicSubnetVPC';
```
Comment (paulhcsun) [inline packages/aws-cdk-lib/cx-api/lib/features.ts:140]: nit: I know it's not consistent but the convention is to prefix the service here with `aws-`. Also we should prefix the constant with the module name `EC2-` and update the name of the feature flag to more accurately reflect the behaviour. 

```suggestion
export const EC2_REQUIRE_PRIVATE_SUBNETS_FOR_EGRESSONLYINTERNETGATEWAY = '@aws-cdk/aws-ec2:requirePrivateSubnetsForEgressOnlyInternetGateway';
```

File: packages/aws-cdk-lib/cx-api/lib/features.ts [hunk 2]
```diff
@@ -1576,6 +1577,17 @@ export const FLAGS: Record<string, FlagInfo> = {
   },
 
   //////////////////////////////////////////////////////////////////////
+  [ENABLE_E2_REMOVE_EGRESSONLYGATEWAY_FROM_PUBLIC_SUBNET_VPC]: {
+    type: FlagType.BugFix,
+    summary: 'Remove EgressOnlyGateway resource when a a double stack vpc has only public subnets',
```
Comment (paulhcsun) [inline packages/aws-cdk-lib/cx-api/lib/features.ts:1582]: This doesn't seem entirely correct. Rather than "removing `EgressOnlyGateway` when a stack only has public subnets", a more accurate summary could be `"When enabled, the EgressOnlyGateway resource is only created if private subnets are defined in the VPC."`

File: packages/aws-cdk-lib/aws-ec2/lib/vpc.ts [hunk 3]
```diff
@@ -1649,7 +1649,13 @@ export class Vpc extends VpcBase {
     }
 
     // Create an Egress Only Internet Gateway and attach it if necessary
-    if (this.useIpv6 && this.privateSubnets) {
+
+    const redundantEgressOnlyGatewayRemovalFeatureFlag =
```
Comment (paulhcsun) [inline packages/aws-cdk-lib/aws-ec2/lib/vpc.ts:1653]: nit: variable name
```suggestion
    const isRequirePrivateSubnetsForEgressOnlyIgw =
```

File: packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts [hunk 4]
```diff
@@ -2747,6 +2747,90 @@ describe('vpc', () => {
       },
     });
   });
+  test('(default)EgressOnlyInternetGateWay is created when no private subnet configured in dual stack', () => {
```
Comment (paulhcsun) [inline packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts:2750]: Instead of `(default) EgressOnlyIGW....` maybe change this to say `"EgressOnlyIGW is created when....in dual stack when feature flag is enabled."`

File: packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts [hunk 5]
```diff
@@ -2747,6 +2747,90 @@ describe('vpc', () => {
...
+          subnetType: SubnetType.PUBLIC,
+          name: 'public',
+        },
+      ],
+    });
+
+    // THEN
+    Template.fromStack(stack).resourceCountIs('AWS::EC2::EgressOnlyInternetGateway', 1);
+  });
+  test('(default)EgressOnlyInternetGateWay is created when private subnet configured in dual stack', () => {
```
Comment (paulhcsun) [inline packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts:2769]: Same as above test.

File: packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts [hunk 6]
```diff
@@ -2747,6 +2747,90 @@ describe('vpc', () => {
...
+          subnetType: SubnetType.PRIVATE_WITH_EGRESS,
+          name: 'private',
+        },
+      ],
+    });
+
+    // THEN
+    Template.fromStack(stack).resourceCountIs('AWS::EC2::EgressOnlyInternetGateway', 1);
+  });
+  test(' (feature flag ENABLE_E2_REMOVE_EGRESSONLYGATEWAY_FROM_PUBLIC_SUBNET_VPC)EgressOnlyInternetGateWay is not created when private subnet configured in dual stack', () => {
```
Comment (paulhcsun) [inline packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts:2816]:
```suggestion
  test(' (feature flag ENABLE_E2_REMOVE_EGRESSONLYGATEWAY_FROM_PUBLIC_SUBNET_VPC)EgressOnlyInternetGateWay is not created when no private subnets are configured in dual stack', () => {
```

**Review by paulhcsun — COMMENTED** [review]
Nice work with this change! Just a few comments regarding the naming of the feature flag.

**Review by paulhcsun — APPROVED** [review]
LGTM, nice work!

**Comment by paulhcsun** [comment]
@mergifyio update
