### PR TITLE
fix(elasticloadbalancerV2): logicalId supports switch from addTargetGroups (under feature flag)

### LINKED ISSUE #29496: ElasticLoadBalancerV2: migration to addAction() from addTargetGroups() fails because of logicalId change
### Describe the bug

We need to access functionality not available in the `ApplicationListener.addTargetGroups()` helper method (specifically, `ListenerAction.weightedForward()`). To do this, we've changed from

Old code
```
      this.httpsListener.addTargetGroups(this.serviceRoot, {
        conditions: [ListenerCondition.pathPatterns(this.injectionPaths)],
        priority: this.injectionPriority,
        targetGroups: [this.taskTargetGroup],
      });
```

New code

```
      this.httpsListener.addAction(this.serviceRoot, {
        action: ListenerAction.weightedForward(this.weightedTargetGroups),        
        conditions: [ListenerCondition.pathPatterns(this.injectionPaths)],
        priority: this.injectionPriority,
      });
```

However, when I do a cdk diff of the stack, I get

```
Resources
[-] AWS::ElasticLoadBalancingV2::ListenerRule UsQaQaUsWest26/ClipsServiceInstance/https/--clips-service-v3 httpsclipsservicev36BE2E78C destroy
[+] AWS::ElasticLoadBalancingV2::ListenerRule UsQaQaUsWest26/ClipsServiceInstance/https/--clips-service-v3RuleRule httpsclipsservicev3RuleRule772FC4D6 
```

I note that [https://github.com/aws/aws-cdk/blob/050a305d6be65df7e5f1e17668cbf512ead34d23/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener.ts#L675-L676 ](https://github.com/aws/aws-cdk/blob/050a305d6be65df7e5f1e17668cbf512ead34d23/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener.ts#L675-L676) is adding the `Rule` suffix to the logicalId, which is driving a replacement rather than update.

### Expected Behavior

We should be able to go from the helper method to the underlying support method without a logicalId change.

### Current Behavior

Because of the logicalId change, Cfn wants to replace our ListenerRules. Create before destroy means that Cfn tries to create a new ListenerRule with the same priority as the existing ListnerRule, which fails, blocking upgrade path.

### Reproduction Steps

Sigh. 

### Possible Solution

Add a feature flag for not adding the `Rule` suffix to the logicalId in the `addAction()` method.

### Additional Information/Context

_No response_

### CDK CLI Version

2.100.0 (build e1b5c77)

### Framework Version

_No response_

### Node.js Version

20.5.1

### OS

MacOS

### Language

TypeScript

### Language Version

5.3.3

### Other information

_No response_

### PR DESCRIPTION
**Pull request by ahammond**
### Issue ELBv2 logicalId inconsistency of ApplicationListenerRule logicalIds

Mitigates #29496

### Reason for this change

People using ALBs who need to migrate from the `addTargetGroups()` convenience method to the lower level `addAction()` method should not be blocked due to inconsistent logicalId's. Further, the logicalIds should be consistent going forward.

### Description of changes

There are two feature flags, one which sets a migration compat mode and another which fixed the behaviour to be consistent.

### Description of how you validated changes

Unit testing.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by ahammond** [comment]
Per https://github.com/ahammond/aws-cdk/blob/62be9c7a06e3191ea8ada225eb69c626d22033e4/INTEGRATION_TESTS.md#L32 none of the conditions which require an integration test pertain.

File: packages/aws-cdk-lib/cx-api/lib/features.ts [hunk 1]
```diff
@@ -1034,6 +1036,41 @@ export const FLAGS: Record<string, FlagInfo> = {
...
+      enabling a migration from the \`addTargetGroups()\` method.
+
+      For new resources, see instead the ${ENABLE_ALBV2_EXTERNALAPPLICATIONLISTENER_ADDTARGETGROUP_CONSISTENT_LOGICALID} flag.
+    `,
+    introducedIn: { v2: 'V2NEXT' },
+    recommendedValue: false,
+  },
+
+  //////////////////////////////////////////////////////////////////////
+  [ENABLE_ALBV2_EXTERNALAPPLICATIONLISTENER_ADDTARGETGROUP_CONSISTENT_LOGICALID]: {
```
Comment (paulhcsun) [inline packages/aws-cdk-lib/cx-api/lib/features.ts:1063]: I think that just having the other feature flag is sufficient. I can only think of a couple of scenarios where we would want to have this second feature flag:
1. Users want to keep `Rule` in the logicalId
2. Eventually get everyone to use this feature flag and then we can remove the feature flags altogether and migrate to add `Rule` to the `addTargetGroups()` case which I can't see happening. 

Could you explain why you feel this second feature flag is necessary? My main worry is that it will cause confusion with the first feature flag.

File: packages/aws-cdk-lib/cx-api/lib/features.ts [hunk 2]
```diff
@@ -1034,6 +1036,41 @@ export const FLAGS: Record<string, FlagInfo> = {
     introducedIn: { v2: 'V2NEXT' },
     recommendedValue: true,
   },
+
+  //////////////////////////////////////////////////////////////////////
+  [ENABLE_ALBV2_EXTERNALAPPLICATIONLISTENER_ADDTARGETGROUP_TO_ADDACTION_MIGRATION]: {
```
Comment (paulhcsun) [inline packages/aws-cdk-lib/cx-api/lib/features.ts:1041]: I don't think we need to add `ENABLE` to the name here, also I feel like `MIGRATE` suggests future changes that might not necessarily be coming (if that makes sense). 

```suggestion
  [ALBV2_EXTERNALAPPLICATIONLISTENER_SWITCH_FROM_ADDTARGETGROUP_TO_ADDACTION]: {
```

File: packages/aws-cdk-lib/cx-api/lib/features.ts [hunk 3]
```diff
@@ -1034,6 +1036,41 @@ export const FLAGS: Record<string, FlagInfo> = {
...
+    type: FlagType.VisibleContext,
+    summary: 'When enabled, you can migrate from the \`addTargetGroups()\` method of declaring a \`ListenerRule\` to the \`addAction()\` method, without changing the logicalId and replacing your resource.',
```
Comment (paulhcsun) [inline packages/aws-cdk-lib/cx-api/lib/features.ts:1043]:
```suggestion
    summary: 'When enabled, you can switch from the \`addTargetGroups()\` method of declaring a \`ListenerRule\` to the \`addAction()\` method, without changing the logicalId and replacing your resource.',
```

File: packages/aws-cdk-lib/cx-api/lib/features.ts [hunk 4]
```diff
@@ -1034,6 +1036,41 @@ export const FLAGS: Record<string, FlagInfo> = {
...
+    detailsMd: `
+      When migrating from a less complex to a more complex use of ALB,
```
Comment (paulhcsun) [inline packages/aws-cdk-lib/cx-api/lib/features.ts:1045]:
```suggestion
      When switching from a less complex to a more complex use of ALB,
```

File: packages/aws-cdk-lib/cx-api/lib/features.ts [hunk 5]
```diff
@@ -1034,6 +1036,41 @@ export const FLAGS: Record<string, FlagInfo> = {
...
+      you will eventually need features not available in the \`addTargetGroups()\` convenience method.
+      In this case you will want to use the \`addAction()\` method.
+      Without this feature being activated, the change will also add a \`Rule\` suffix to the logicalId of your \`ListnerRule\`,
```
Comment (paulhcsun) [inline packages/aws-cdk-lib/cx-api/lib/features.ts:1048]:
```suggestion
      When this feature is not enabled, switching over to \`addAction()\` from using \`addTargetGroups()\` will add a \`Rule\` suffix to the logicalId of your \`ListnerRule\`,
```

File: packages/aws-cdk-lib/cx-api/lib/features.ts [hunk 6]
```diff
@@ -1034,6 +1036,41 @@ export const FLAGS: Record<string, FlagInfo> = {
...
+      causing CloudFormation to attempt to replace the resource.
+      Since ListenerRules have a unique priority,
+      CloudFormation will always fail when generating the new ListenerRule.
+
+      Setting this feature flag will cause the \`addAction()\` method to not add the \`Rule\` suffix on the logicalId,
+      enabling a migration from the \`addTargetGroups()\` method.
```
Comment (paulhcsun) [inline packages/aws-cdk-lib/cx-api/lib/features.ts:1054]:
```suggestion
      allowing you to switch from the \`addTargetGroups()\` method without having CloudFormation generate a new resource.
```

**Review by paulhcsun — CHANGES_REQUESTED** [review]
Thank you for your contribution @ahammond! The changes look good to me overall but I've just let some comments regarding the`ENABLE_ALBV2_EXTERNALAPPLICATIONLISTENER_ADDTARGETGROUP_CONSISTENT_LOGICALID` feature flag as well as some wording changes. 

We apologize for the delay in reviewing your PR. We'll make sure this gets prioritized and hopefully merged as part of the 2.136.0 release this week. We appreciate your patience.

File: packages/aws-cdk-lib/cx-api/lib/features.ts (hunk 1 above)
Comment (ahammond) [reply packages/aws-cdk-lib/cx-api/lib/features.ts:1063]: Users don't care about the contents of logicalIds until it causes them problems. This flag allows anyone who actually does care to be future friendly, while allowing the vast majority of users who don't care to continue not caring. When the logicalId changes, Cfn will attempt to replace the resource and fail. There is no way I can see to make this change painless for existing users. That said, maybe we should invert the logic here: make things consistent by default (breaking existing users), but provide a feature flag which allows legacy behaviour so existing users can punt until vNext. That said, this isn't what's blocking us, and maybe we should split this into two separate PRs?

Comment (ahammond) [reply packages/aws-cdk-lib/cx-api/lib/features.ts]: I did that. The consistency stuff can be a separate PR. We just need compatibility to get us unblocked.

File: packages/aws-cdk-lib/cx-api/lib/features.ts [hunk 7]
```diff
@@ -1034,6 +1035,26 @@ export const FLAGS: Record<string, FlagInfo> = {
...
+
+  //////////////////////////////////////////////////////////////////////
+  [ALBV2_EXTERNALAPPLICATIONLISTENER_SWITCH_FROM_ADDTARGETGROUP_TO_ADDACTION]: {
+    type: FlagType.VisibleContext,
+    summary: 'When enabled, you can switch from the \`addTargetGroups()\` method of declaring a \`ListenerRule\` to the \`addAction()\` method, without changing the logicalId and replacing your resource.',
+    detailsMd: `
+      When switching from a less complex to a more complex use of ALB,
+      you will eventually need features not available in the \`addTargetGroups()\` convenience method.
+      In this case you will want to use the \`addAction()\` method.
+      Before this feature is enabled, switching over to \`addAction()\` from using \`addTargetGroups()\` will add a \`Rule\` suffix to the logicalId of your \`ListenerRule\`,
```
Comment (paulhcsun) [inline packages/aws-cdk-lib/cx-api/lib/features.ts:1047]:
```suggestion
      Before this feature is enabled, switching over to \`addAction()\` from using \`addTargetGroups()\` 
      will add a \`Rule\` suffix to the logicalId of your \`ListenerRule\`,
```

**Review by paulhcsun — COMMENTED** [review]
Just adding a new line to keep the spacing consistent here.

**Review by paulhcsun — COMMENTED** [review]
Just adding a new line to keep the spacing consistent here.

**Comment by paulhcsun** [comment]
@Mergifyio update

**Comment by scanlonp** [comment]
Hey @ahammond, saw that the recommended value for this feature flag is false. This makes me question if we need a feature flag or not. I see feature flags as a way to change default behavior while staying backwards compatible. If you only need this behavior some of the time, I would think setting a property is the way to go.

Is adding an optional prop to `AddApplicationActionProps` that controls how the suffix is generated possible?

**Comment by ahammond** [comment]
@scanlonp I don't have a strong feeling either way here.

**Comment by scanlonp** [comment]
Got it. I saw @TheRealAmazonKendra commented on your related PR. I think there has been a concerted effort to limit our feature flags, and properties looks like the best path here, so let's go with properties.

**Comment by scanlonp** [comment]
Going to revert this specific PR, but I will be attentive to your two PRs so that we can get them in quickly for you.

**Comment by ahammond** [comment]
@scanlonp to clarify, I don't care how it is solved, I care that it is solved. We are now 4 weeks since this fix was initially pushed. Regarding the props based PR I pushed on Fri Apr 5th, I addressed the comments on Monday Apr 8th in the morning. FYI, as a workaround we have bundled the entire `aws-cdk-lib` package into one of our internal libs and are using `patch-package` to apply a hack-around. This is incredibly fragile and I would like to get us back to stock ASAP.
