### PR TITLE
docs(core): fix incorrect default RemovalPolicy documentation

### LINKED ISSUE #23897: aws_cdk.RemovalPolicy: Default is stated incorrectly as Destroy
### Describe the issue

**Destroy** is indicated as the default which is incorrect for AWS CDK as can be seen in:

-  CDK Developer Guide 
RemovalPolicy.RETAIN Keep the contents of the resource when destroying the stack (default). The resource is orphaned from the stack and must be deleted manually. If you attempt to re-deploy the stack while the resource still exists, you will receive an error message due to a name conflict
cdk

- API reference --> S3/Bucket class that shows: 
removal_policy (Optional[RemovalPolicy]) removal_policy (Optional[[RemovalPolicy] – Policy to apply when the bucket is removed from this stack. Default: - The bucket will be orphaned.

In essence, **Retain** is the default, not **Destroy**. 

Could we kindly have this updated. 
Many thanks for the help. 

### Links

https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk/RemovalPolicy.html#aws_cdk.RemovalPolicy.DESTROY

### PR DESCRIPTION
**Pull request by must1d**
### Issue # (if applicable)

Closes #23897.

### Reason for this change

The documentation for `RemovalPolicy.DESTROY` incorrectly states that it is the default removal policy, when in fact `RETAIN` is the actual default for most resources in the AWS CDK. This creates confusion for users who expect different behavior based on the documentation, potentially leading to unexpected costs or resource retention issues.

### Description of changes

Updated the JSDoc comment for `RemovalPolicy.DESTROY` in `removal-policy.ts` to remove the incorrect statement that it is the default removal policy. The comment now accurately describes that this policy will physically destroy resources when applied, without claiming it's the default behavior.

**Changes made:**
- Modified the JSDoc comment for `DESTROY` enum value to clarify it is not the default removal policy
- Ensured consistency with other CDK documentation that correctly states `RETAIN` is the default

**Alternatives considered:**
- Could have updated all related documentation simultaneously, but this focused change addresses the core issue in the source code
- Considered adding explicit mention of what the actual default is, but kept the change minimal to avoid over-documentation

**Design decisions:**
- Kept the change simple and focused on removing the incorrect information rather than adding extensive explanations
- Maintained consistency with existing comment style and format

### Describe any new or updated permissions being added

No new or updated IAM permissions are needed for this documentation change.

### Description of how you validated changes

- Verified the comment change accurately reflects the actual CDK behavior
- Confirmed the change aligns with existing CDK documentation that correctly states `RETAIN` is the default
- Reviewed related code in bucket.ts and other resources to ensure consistency
- Built and tested locally to ensure no compilation issues

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/core/lib/removal-policy.ts [hunk 1]
```diff
@@ -27,8 +27,9 @@
  */
 export enum RemovalPolicy {
   /**
-   * This is the default removal policy. It means that when the resource is
-   * removed from the app, it will be physically destroyed.
+   * When this removal policy is applied, the resource will be physically destroyed
+   * when it is removed from the stack or when the stack is deleted.
```
Comment (ozelalisen) [inline packages/aws-cdk-lib/core/lib/removal-policy.ts:31]: I suggest moving the default policy documentation to the RETAIN enum instead. Rather than documenting that DESTROY is not the default in its documentation, we should document that RETAIN is the default in its own documentation block. This would be more intuitive for developers looking up the default behavior, as they would find this information directly in the RETAIN enum documentation rather than as a reference in DESTROY.

**Review by ozelalisen — CHANGES_REQUESTED** [review]

File: packages/aws-cdk-lib/core/lib/removal-policy.ts (hunk 1 above)
Comment (must1d) [reply packages/aws-cdk-lib/core/lib/removal-policy.ts:31]: Applied comment. Can you please have a look again?
