### PR TITLE
fix(cfn-include): correctly parse YAML strings in short-form GetAtt

### LINKED ISSUE #10177: [cloudformation-include] Resource used in GetAtt not found when using single quotes in template
When the imported template uses single quotes like `!GetAtt 'MYID.Arn'` cdk synth fails with `Resource used in GetAtt expression with logical ID: ''MYID' not found` (note the double single quotes in the error message)

### Reproduction Steps

In my case:
```
NATIP:
        DependsOn: VPCGatewayAttachment
        Type: 'AWS::EC2::EIP'
        Properties:
            Domain: vpc

NATGateway:
        Type: 'AWS::EC2::NatGateway'
        Properties:
            AllocationId: !GetAtt 'NATIP.AllocationId'
            SubnetId: !Ref Subnet1
```

### What did you expect to happen?

I was trying to cdk synth having imported my (already working in and deployed) yaml template using this code in a new stack
```
    const templateFile = path.join(__dirname, '../templates/template.yml');
    const include = new CfnInclude(this, 'Template', {
      templateFile
    });
```

### What actually happened?

```
Resource used in GetAtt expression with logical ID: ''NATIP' not found
Subprocess exited with error 1
```

### Environment

  - **CLI Version      :** 1.62.0 (build 8c2d7fc)
  - **Framework Version:** 1.62.0
  - **Node.js Version:**  v14.3.0
  - **OS               :** mac Mojave 10.14.6
  - **Language (Version):**  Typescript ~4.0.2

### Other

Judging from the error message it seems an extra ' is making its way into the resource name somehow.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by skinny85**
We weren't recursively parsing the argument of the short-form `Fn::GetAtt`
if the arguments to it where given in the string form;
which meant, if they were quoted (which is legal in YAML),
we would add the quote to the logical ID of the resource,
which is obviously incorrect.

Fixes #10177

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/cloudformation-include/lib/file-utils.ts [hunk 1]
```diff
@@ -37,23 +37,26 @@ const shortForms: yaml_types.Schema.CustomTag[] = [
...
-        ]
-        : parseYamlStrWithCfnTags(cstNode.toString().substring('!GetAtt'.length)),
-    };
+    let value: any;
+    if (typeof parsedArguments === 'string') {
+      // if the arguments to Fn::GetAtt are a string,
+      // the part before the first '.' is the logical ID,
+      // and the rest is the attribute name
+      // (which can contain '.')
+      const firstDot = parsedArguments.indexOf('.');
```
Comment (njlynch) [inline packages/@aws-cdk/cloudformation-include/lib/file-utils.ts:48]: The return of this is never checked. If the value is malformed (no dot), this means the first value (logical ID) will be blank and second value will contain the entire string. How (and when) would this error manifest to the user? Would it be worth an explicit check here to validate?

**Review by njlynch — APPROVED** [review]
Looks good. Marked as 'do-not-merge' given one optional error-handling improvement.

File: packages/@aws-cdk/cloudformation-include/lib/file-utils.ts (hunk 1 above)
Comment (skinny85) [reply packages/@aws-cdk/cloudformation-include/lib/file-utils.ts:48]: Sure. Added.
