### PR TITLE
fix(core): fix use of references in toJsonString()

### LINKED ISSUE #3474: Cross stack references are not identified in stack.toJsonString()
* **I'm submitting a ...**
  - [x] :beetle: bug report

* **What is the current behavior?**

When using `stack.toJsonString` to stringify an object that includes references to resources in a different stack within the same region, these references (GetAtt/Ref) are not converted to exports/imports.

* **What is the expected behavior (or behavior of feature suggested)?**

Since these are cross stack references, we expect them to be identified as such and converted to exports/imports.

### PR DESCRIPTION
**Pull request by rix0rrr**
When tokens are identified to be References, leave their type unchanged
in `toJsonString()`, so that they'll be properly identified as
references and handled in a potentially cross-stack way.

Add checking to references so that they'll be used correctly in tests.

Fixes #3474

----

Please read the [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) and follow the pull-request checklist.

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/core/lib/private/cfn-reference.ts [hunk 1]
```diff
@@ -101,7 +101,12 @@ export class CfnReference extends Reference {
   public resolve(context: IResolveContext): any {
     // If we have a special token for this consuming stack, resolve that. Otherwise resolve as if
     // we are in the same stack.
-    const token = this.replacementTokens.get(Stack.of(context.scope));
+    const consumingStack = Stack.of(context.scope);
+    const token = this.replacementTokens.get(consumingStack);
+    if (!token && this.isCrossStackReference(consumingStack) && !context.preparing) {
+      throw new Error('Should have hadd a cross-stack reference, but not found. prepare() the reference first.');
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/private/cfn-reference.ts]: Very cryptic error and has a typo
