### PR TITLE
fix(appmesh): routes with weight 0 are assigned a weight of 1

### LINKED ISSUE #21365: (aws-appmesh): App Mesh Routes with a weight of 0 are being auto-assigned a weight of 1
### Describe the bug

I am creating an App Mesh route spec. where one virtual node (VN) has a weight of 100 (or 1 in relative terms), and the other virtual node has a weight of 0. 

However, once the CDK deployment is done, the route with the weight 0 is being changed to 1 automatically. This is regardless of the relative weight of the other route. 

For example, VN1 has a weight of 1 and VN2 has a weight of 0, it becomes 1 for both. Which means the traffic is split 50/50.
If VN1 has a weight of 100 and VN2 has a weight of 0, it becomes 100,1. In the case the traffic is split 99/1.

image

image

The weight has to be manually changed to 0  in the AWS Console UI.

### Expected Behavior

Routes with targets of weight 0 should not change to 1 automatically.

### Current Behavior

Routes with targets of weight 0 are being changed to 1 automatically.

### Reproduction Steps

Provision a mesh that has 2 virtual nodes. Add the virtual nodes to a virtual router as targets, and assign one node a weight of 0.

```c
this.virtualRouter = new appmesh.VirtualRouter(this, `${this.stackName}VritualRouter`, {
      mesh: this.mesh,
      virtualRouterName: "ColorTellerVirtualRouter",
      listeners: [appmesh.VirtualRouterListener.http(80)],
    });

    this.route = new appmesh.Route(this, `${this.stackName}BackendRoute`, {
      mesh: this.mesh,
      virtualRouter: this.virtualRouter,
      routeName: "ColorTellerRoute",
      routeSpec: appmesh.RouteSpec.http({
        weightedTargets: [
          {
            virtualNode: this.virtualNodeWhite,
            weight: 100,
          },
          {
            virtualNode: this.virtualNodeGreen,
            weight: 0,
          },
        ],
      }),
    });
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.27.0 (build 8e89048)

### Framework Version

_No response_

### Node.js Version

v18.3.0

### OS

macOS Monterey (12.4)

### Language

Typescript

### Language Version

3.9.7

### Other information

_No response_

### PR DESCRIPTION
**Pull request by ghost**
----

### All Submissions:

fixes #21365

This PR fixes an unexpected behaivor when creating an appmesh.

### Expected Behavior
Routes with targets of weight 0 should not change to 1 automatically.

### Current Behavior (without fix)
Routes with targets of weight 0 are being changed to 1 automatically.

### Solution

`t.weight || 1` will result in `0 || 1` if the `weight` is set to `0`. This will result in a route that can never have a weight of 0, since `0` is a `faulty` value.

To fix this, I compare the weight with `undefined` & return `1` only if the weight is undefined.

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-appmesh/lib/route-spec.ts [hunk 1]
```diff
@@ -585,7 +585,7 @@ function renderWeightedTargets(weightedTargets: WeightedTarget[]): CfnRoute.Weig
   for (const t of weightedTargets) {
     renderedTargets.push({
       virtualNode: t.virtualNode.virtualNodeName,
-      weight: t.weight || 1,
+      weight: t.weight == null ? 1 : t.weight,
```
Comment (TheRealAmazonKendra) [inline packages/@aws-cdk/aws-appmesh/lib/route-spec.ts:588]: You probably want to compare against `undefined` here instead of null.

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Please make sure that your PR title confirms to the conventional commit standard (fix, feat, chore) and that it is written in a style that will reflect correctly in the change log (See [Contributing Guide, Pull Requests](https://github.com/aws/aws-cdk/blob/v1-main/CONTRIBUTING.md#step-4-pull-request)).

Additionally, please make sure that your PR body describes the problem the PR is solving, and the design approach and alternatives considered. Explain why the PR solves the problem. A link to an issue is helpful, but does not replace an explanation of your thought process

File: packages/@aws-cdk/aws-appmesh/lib/route-spec.ts (hunk 1 above)
Comment (Xcalizorz) [reply packages/@aws-cdk/aws-appmesh/lib/route-spec.ts]: Done, thanks.

**Review by TheRealAmazonKendra — APPROVED** [review]

File: packages/@aws-cdk/aws-appmesh/lib/route-spec.ts [hunk 2]
```diff
@@ -585,7 +585,7 @@ function renderWeightedTargets(weightedTargets: WeightedTarget[]): CfnRoute.Weig
   for (const t of weightedTargets) {
     renderedTargets.push({
       virtualNode: t.virtualNode.virtualNodeName,
-      weight: t.weight || 1,
+      weight: t.weight == undefined ? 1 : t.weight,
```
Comment (ytsssun) [inline packages/@aws-cdk/aws-appmesh/lib/route-spec.ts:588]: Shouldn't this be `0`?

Comment (srinivas-kini) [reply packages/@aws-cdk/aws-appmesh/lib/route-spec.ts:588]: I agree with @ytsssun  This should be `weight: t.weight || 0`. Is there a reason we are defaulting to 1?

Comment (Xcalizorz) [reply packages/@aws-cdk/aws-appmesh/lib/route-spec.ts:588]: 0 would be a better default because [The total weight for all targets combined must be less than or equal to 100. ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appmesh-route-weightedtarget.html). But I wanted to keep this PR as small as possible without changing the established defaults.

It might be that changing this default could break something for some users. @TheRealAmazonKendra what do you think?
