### PR TITLE
fix(cfn2ts): correctly choose between string and object without required properties in a union

### LINKED ISSUE #12854: (aws-sam): cannot generate string policies for CfnFunction
The property `CfnFunctionProps.policies` accepts a list of both objects and strings. However, when I try to generate a list with a string, an empty object is generated instead.

### Reproduction Steps

Running `cdk synth` with the following construct:

```ts
new CfnFunction(scope, 'MyFunction', {
  policies: ['AWSLambdaExecute']
});
```

### What did you expect to happen?

```yaml
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AWSLambdaExecute
```

### What actually happened?

```yaml
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - {}
```

### Environment

  - **CDK CLI Version  :** 1.80.0
  - **Framework Version:**
  - **Node.js Version:** 12.18.3
  - **OS               :** Ubuntu 19.10
  - **Language (Version):** 

### Other

Note that if I use a string, instead of a list of strings, the output is correct.

```ts
new CfnFunction(scope, 'MyFunction', {
  policies: 'AWSLambdaExecute'
});
```

```yaml
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies: 'AWSLambdaExecute'
```
--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by skinny85**
In our code generation, in the validation functions for CFN complex types,
we never checked whether the argument we received is an object.
Because of that, passing a string was actually a correct candidate for a union with a complex type that had no required properties.
Fix that by checking for that error explicitly,
which removes the complex type without required properties from the candidates for the union type when a string is passed.

Fixes #12854

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: tools/cfn2ts/lib/codegen.ts [hunk 1]
```diff
@@ -684,6 +684,11 @@ export default class CodeGenerator {
 
     this.code.line(`const errors = new ${CORE}.ValidationResults();`);
 
+    // check that the argument is an object
+    this.code.openBlock("if (properties != null && typeof properties !== 'object')");
```
Comment (rix0rrr) [inline tools/cfn2ts/lib/codegen.ts:688]: Do you not mean 

```
if (properties == null || typeof properties !== 'object')
```

?

**Review by rix0rrr — CHANGES_REQUESTED** [review]

**Review by rix0rrr — APPROVED** [review]
