### PR TITLE
fix(cloudfront): associated lambda role requires edgelambda.amazonaws.com

### LINKED ISSUE #5180: CloudFront: Lambda edge service principal requires for Lambda association
Integ test `integ.cloudfront-lambda-association.js` for CloudFront does not deploy properly anymore, probably because CloudFront has tightened up their validation checks:

```
 5/6 | 11:27:59 AM | CREATE_FAILED        | AWS::CloudFront::Distribution | MyDistribution/CFDistribution (MyDistributionCFDistributionDE147309
) The function execution role must be assumable with edgelambda.amazonaws.com as well as lambda.amazonaws.com principals. Update the IAM role a
nd try again. Role: arn:aws:iam::123456789:role/aws-cdk-cloudfront-LambdaServiceRoleA8ED4D3B-1BALB6KE3O0MN (Service: AmazonCloudFront; Statu
s Code: 400; Error Code: InvalidLambdaFunctionAssociation; Request ID: 965db162-0c49-11ea-9d8a-bff40bbb21ec)
```

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by eladb**
When using AWS Lambda associations, CloudFront now requires that the AWS Lambda execution role will also trust edgelambda.amazonaws.com. This change adds a statement to the Lambda's trust policy to that effect.

Fixes #5180

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts [hunk 1]
```diff
@@ -827,6 +828,16 @@ export class CloudFrontWebDistribution extends cdk.Construct implements IDistrib
             lambdaFunctionArn: fna.lambdaFunction && fna.lambdaFunction.functionArn,
           }))
       });
+
+      // allow edgelambda.amazonaws.com to assume the functions' execution role.
+      for (const a of input.lambdaFunctionAssociations) {
+        if (a.lambdaFunction.role && a.lambdaFunction.role instanceof iam.Role && a.lambdaFunction.role.assumeRolePolicy) {
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts]: Ugh that use of `instanceof` 🤭. Don't we have a `Rome.isRole`?

Comment (RomainMuller) [reply packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts]: Also - I don't see the test for the case where the function doesn't have a role or has one you can't add statements to... 😇

Comment (eladb) [reply packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts]: `instanceof` is ok because we require a single version line through peer deps, so the issue `isXxx` addressed is no longer a problem.

I'll add a bunch of unit tests.
