### PR TITLE
fix(integ-tests): http flattenResponse

### LINKED ISSUE #30327: (integ-test): HttpApiCall seems to be broken
### Describe the bug

I am trying to build a test that codes roughly does:

```typescript
const getUploadUrl = integ.assertions
  .httpApiCall(`${testStack.apiUrl}outbox/${id}`, {
    method: 'PUT',
  })
  .expect(
    test.ExpectedResult.objectLike({
      status: 201,
      headers: {
        'content-type': ['application/json'],
      },
      body: {
        id: emailId,
      },
    }),
  )
  .waitForAssertions();
const uploadUrl = getUploadUrl.getAttString('body.uploadUrl');
```

as you can see I am trying to get my hands on `uploadUrl` from response body.
the assertion expressed in `expect` works fine (although there's no checkup for `uploadUrl` but just because I am not sure if I can nest expectation). Still, I am confident that `uploadUrl` is present in response body based on logs.

Is `httpApiCall` broken? I have located a lot of [examples](https://github.com/search?q=getAttString+repo%3Aaws%2Faws-cdk+path%3A**%2Finteg.*&type=code&ref=advsearch) where `getAtString` is used in `cdk` own test suites. Difference is that it is rather used with `awsSdkCall` or `lambdaInvokeFunction` rather then `httpApiCall`.

### Use case

Use case is to be able to integ test parts of bigger component.
Without a need to deploy the whole component.

### Expected Behavior

I can obtain part of response via `HttApiCall`

### Current Behavior

Test fails with `Vendor response doesn't contain apiCallResponse.body.uploadUrl`

### Reproduction Steps

```typescript
import 'source-map-support/register';

import * as test from '@aws-cdk/integ-tests-alpha';
import * as cdk from 'aws-cdk-lib';

const app = new cdk.App({
  analyticsReporting: false,
  stackTraces: true, 
});

const testStack = new cdk.Stack(app, 'repro-api-stack');
const integ = new test.IntegTest(app, 'repro-api-test', {
  testCases: [testStack],
});
const apiCall = integ.assertions.httpApiCall(
  'https://cat-fact.herokuapp.com/facts',
);
const value = apiCall.getAttString('body.0.user');

integ.assertions
  .httpApiCall(`https://cat-fact.herokuapp.com/users/${value}`)
  .expect(
    test.ExpectedResult.objectLike({
      status: 404,
    }),
  );
```

### Possible Solution

N/A

### Additional Information/Context

N/A

### CDK CLI Version

2.142.1

### Framework Version

_No response_

### Node.js Version

20.8

### OS

MacOS sierra

### Language

TypeScript

### Language Version

5.4

### Other information

_No response_

### PR DESCRIPTION
**Pull request by nmussy**
### Issue # (if applicable)

Closes #30327

### Reason for this change

There was a difference in the behavior of SDK and HTTP integration attribute extraction with the `getAtt` and `getAttString` methods. `awsApiCall` properly implemented and returned JSONPath-ish values by using a `flattenResponse` property. This PR adds the same functionality to `httpApiCall`

### Description of changes

Added an implemented `flattenResponse` in the `HttpHandler` custom resource

### Description of how you validated changes

Updated integ and unit tests

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by kornicameister** [comment]
@nmussy any idea when this could be merged, reviewed? Can't say I am not looking forward to it?

**Comment by nmussy** [comment]
@kornicameister I can't give an ETA for the review and release process, but I should have the PR ready some time this week

File: packages/@aws-cdk/integ-tests-alpha/lib/assertions/providers/lambda-handler/http.ts [hunk 1]
```diff
@@ -22,8 +24,17 @@ export class HttpHandler extends CustomResourceHandler<HttpRequest, HttpResponse
...
+
+    let resp: HttpResponseWrapper | { [key: string]: unknown };
+    if (request.flattenResponse === 'true') {
+      // Flatten and explode JSON fields
+      resp = flatten(deepParseJson({ apiCallResponse: result }));
+    } else {
+      // Otherwise just return the response as-is, without exploding JSON fields
+      resp = { apiCallResponse: result };
+    }
+    console.log(`Returning result ${JSON.stringify(resp)}`);
```
Comment (nmussy) [inline packages/@aws-cdk/integ-tests-alpha/lib/assertions/providers/lambda-handler/http.ts:36]: It might be worth considering a refactor of the `flattenResponse` in the common `CustomResourceHandler` props, given the SDK handler does pretty much the same thing:

https://github.com/aws/aws-cdk/blob/a2e8dc5e3cff91e64e5062a8fed630fb46982dbf/packages/%40aws-cdk/integ-tests-alpha/lib/assertions/providers/lambda-handler/sdk.ts#L18-L22

File: packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/http.test.ts [hunk 2]
```diff
@@ -113,7 +113,7 @@ describe('HttpHandler', () => {
     const response = await processEvent({ parameters: { url: 'x' } });
 
     // THEN
-    expect(response.apiCallResponse.body).toEqual({ key: 'value' });
```
Comment (nmussy) [inline packages/@aws-cdk/integ-tests-alpha/test/assertions/providers/lambda-handler/http.test.ts:116]: This change should not have any impact given `apiCallResponse` should only be used internally, but it is caused by the type change of the `HttpHandler` response from `HttpResponseWrapper` to `HttpResponseWrapper | { [key: string]: unknown }>`

**Comment by pahud** [comment]
Hi

This PR has been pending for community review for a while. Please consider posting it on the #contributing channel in cdk.dev. Community members will be on the lookout there as well for possible reviews.

Check [How to get your P2 PR community reviewed](https://github.com/aws/aws-cdk/wiki/CDK-Community-PR-Reviews#how-to-get-your-p2-pr-community-reviewed) for more details.

**Review by wladyslawczyzewski — APPROVED** [review]

**Review by GavinZZ — APPROVED** [review]

**Review by GavinZZ — APPROVED** [review]
