### PR TITLE
fix(iam): OIDC provider cannot be imported from parameter

### LINKED ISSUE #11705: (aws-iam): `OpenIdConnectProvider.openIdConnectProviderIssuer` is wrong for a provider that is imported using a token ARN
`OpenIdConnectProvider.openIdConnectProviderIssuer` is wrong for a provider that is imported using a token ARN.

### Reproduction Steps

Deploy the following:

```ts
const provider = new iam.OpenIdConnectProvider(this, 'Thumbprints', {
  url: 'https://oidc.eks.us-east-1.amazonaws.com/id/test4',
  thumbprints: [
    'aa00aa1122aa00aa1122aa00aa1122aa00aa1122',
    'aa00aa1122aa00aa1122aa00aa1122aa00aa1111',
  ],
});

const imported = iam.OpenIdConnectProvider.fromOpenIdConnectProviderArn(this, 'Imported', provider.openIdConnectProviderArn);

new cdk.CfnOutput(this, 'ImportedProviderIssuer', {
  value: imported.openIdConnectProviderIssuer,
});
```

### What did you expect to happen?

Expected the output value to be: `oidc.eks.us-east-1.amazonaws.com/id/test4`

### What actually happened?

Output value is: `oidc.eks.us-east-1.amazonaws.com`

### Environment

  - **CDK CLI Version  : ALL**
  - **Framework Version : ALL**
  - **Node.js Version: ALL** 
  - **OS               : ALL**
  - **Language (Version): ALL** 

### Other

Thanks to @jumi-dev investigation it looks like the error is coming from:

https://github.com/aws/aws-cdk/blob/13c05bee5882114ccdd4c917cb5cc0204ce15e49/packages/%40aws-cdk/core/lib/arn.ts#L266

This fails in case the resource name includes the separator. Like with an oidc ARN:

`arn:aws:iam::1234567:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/someid`

Originally reported here: https://github.com/aws/aws-cdk/issues/11682

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
The "resource name" part of the OIDC Provider ARN contains the
ARN separator (`/`), which cannot be properly split into components
using the primitives that CloudFormation gives us.

Introduce a new helper method on `Arn` which can obtain the
resource name, slashes and all, provided that we know the resource
type for a fact.

Fixes #11705.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/core/lib/arn.ts [hunk 1]
```diff
@@ -206,6 +189,39 @@ export class Arn {
...
+   * Only works if we statically know the expected `resourceType` beforehand, since we're going
+   * to use that to split the string on ':<resourceType>/' (and take the right-hand side).
+   *
+   * We can't extract the 'resourceType' from the ARN at hand, because CloudFormation Expressions
+   * only allow literals in the 'separator' argument to `{ Fn::Split }`, and so it can't be
+   * `{ Fn::Select: [5, { Fn::Split: [':', ARN] }}`.
+   *
+   * Only necessary for ARN formats for which the type-name separator is `/`.
+   */
+  public static extractResourceName(arn: string, resourceType: string): string {
```
Comment (nija-at) [inline packages/@aws-cdk/core/lib/arn.ts:207]: Make the 2nd parameter a `ExtractResourceNameOptions` so it's extensible.

File: packages/@aws-cdk/core/lib/arn.ts [hunk 2]
```diff
@@ -268,3 +284,45 @@ function parseToken(arnToken: string, sep: string = '/', hasName: boolean = true
...
+
+
+/**
+ * Validate that a string is either unparseable or looks mostly like an ARN
+ */
+function parseArnShape(arn: string): 'unparseable' | string[] {
+  const components = arn.split(':') as Array<string>;
+  const looksLikeArn = arn.startsWith('arn:') && components.length >= 6 && components.length <= 7;
+  if (Token.isUnresolved(arn) && !looksLikeArn) {
+    return 'unparseable';
```
Comment (nija-at) [inline packages/@aws-cdk/core/lib/arn.ts:296]: why not just `undefined`?

File: packages/@aws-cdk/core/test/arn.test.ts [hunk 3]
```diff
@@ -212,6 +213,31 @@ nodeunitShim({
       test.done();
     },
 
+    'extracing resource name from a complex ARN'(test: Test) {
```
Comment (nija-at) [inline packages/@aws-cdk/core/test/arn.test.ts:216]:
```suggestion
    'extracting resource name from a complex ARN'(test: Test) {
```

File: packages/@aws-cdk/core/lib/arn.ts [hunk 4]
```diff
@@ -268,3 +284,45 @@ function parseToken(arnToken: string, sep: string = '/', hasName: boolean = true
     return { partition, service, region, account, resource, resourceName, sep };
   }
 }
+
+
+/**
+ * Validate that a string is either unparseable or looks mostly like an ARN
+ */
+function parseArnShape(arn: string): 'unparseable' | string[] {
+  const components = arn.split(':') as Array<string>;
```
Comment (nija-at) [inline packages/@aws-cdk/core/lib/arn.ts:293]: do we need this cast? the compiler should be able to interpret this.

File: packages/@aws-cdk/core/lib/arn.ts [hunk 5]
```diff
@@ -268,3 +284,45 @@ function parseToken(arnToken: string, sep: string = '/', hasName: boolean = true
...
+
+  // If the ARN merely contains Tokens, but otherwise *looks* mostly like an ARN,
+  // it's a string of the form 'arn:${partition}:service:${region}:${account}:abc/xyz'.
+  // Parse fields out to the best of our ability.
+  // Tokens won't contain ":", so this won't break them.
+  const [arnPrefix, , service, , , sixth] = components;
+
+  if (arnPrefix !== 'arn') {
+    throw new Error('ARNs must start with "arn:": ' + arn);
+  }
```
Comment (nija-at) [inline packages/@aws-cdk/core/lib/arn.ts:315]: unreachable because of line 295. 
Maybe remove the `startsWith()` conditional in the looksLikeArn and let the error on this line show up.

File: packages/@aws-cdk/core/lib/arn.ts [hunk 6]
```diff
@@ -268,3 +284,45 @@ function parseToken(arnToken: string, sep: string = '/', hasName: boolean = true
...
+
+  // partition is not required, 'cognito-sync' doesn't use it.
```
Comment (nija-at) [inline packages/@aws-cdk/core/lib/arn.ts:317]: ?

File: packages/@aws-cdk/core/lib/arn.ts [hunk 7]
```diff
@@ -268,3 +284,45 @@ function parseToken(arnToken: string, sep: string = '/', hasName: boolean = true
...
   }
 }
+
+
+/**
+ * Validate that a string is either unparseable or looks mostly like an ARN
+ */
+function parseArnShape(arn: string): 'unparseable' | string[] {
+  const components = arn.split(':') as Array<string>;
+  const looksLikeArn = arn.startsWith('arn:') && components.length >= 6 && components.length <= 7;
```
Comment (nija-at) [inline packages/@aws-cdk/core/lib/arn.ts:294]: Nit: I like to use `<` and `>` over `<=` and `>=`. I find the extra "equals" harder to understand on what's included and excluded.

Maybe it's just my head 🤷‍♂️

**Review by nija-at — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/core/test/evaluate-cfn.ts [hunk 8]
```diff
@@ -83,3 +94,15 @@ export function evaluateCFN(object: any, context: {[key: string]: string} = {}):
     return intrinsics[name].apply(intrinsics, args);
   }
 }
+
+function parseIntrinsic(x: any): { name: string; arg: any } | undefined {
+  if (typeof x !== 'object' || x === null) { return undefined; }
```
Comment (njlynch) [inline packages/@aws-cdk/core/test/evaluate-cfn.ts:99]: Curious what spawned this new check. Presumably something broke. Worth a unit test?

File: packages/@aws-cdk/core/lib/arn.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/@aws-cdk/core/lib/arn.ts:207]: I don't really see the need for that. We have multiple extension points already:

* Optional 3rd parameter which can be a struct
* Additional method

No need for premature generalization.

File: packages/@aws-cdk/core/lib/arn.ts (hunk 2 above)
Comment (rix0rrr) [reply packages/@aws-cdk/core/lib/arn.ts:296]: Why yes `undefined`?

How is this not more clear?

File: packages/@aws-cdk/core/lib/arn.ts (hunk 5 above)
Comment (rix0rrr) [reply packages/@aws-cdk/core/lib/arn.ts:315]: It looks like it is, but it's not.

| Unresolved | LooksLikeArn | Behavior |
|------|-------|-----------|
| false | false | Will trip `arnPrefix` check |
| false | true | Will not trip `arnPrefix` check |
| true | false | Will be treated as unparseable |
| true | true | Check is superfluous |

I will change the order somewhat to make it more clear though.

File: packages/@aws-cdk/core/lib/arn.ts (hunk 6 above)
Comment (rix0rrr) [reply packages/@aws-cdk/core/lib/arn.ts:317]: Going off of this test, assuming it's accurate: https://github.com/aws/aws-cdk/blob/huijbers/fix-resource-path2/packages/@aws-cdk/core/test/arn.test.ts#L160

File: packages/@aws-cdk/core/lib/arn.ts (hunk 7 above)
Comment (rix0rrr) [reply packages/@aws-cdk/core/lib/arn.ts:294]: Don't tempt me or I'm going to write 

```
5 < components.length
```
😛

File: packages/@aws-cdk/aws-iam/lib/oidc-provider.ts [hunk 9]
```diff
@@ -5,9 +5,8 @@ import {
   CustomResourceProviderRuntime,
   IResource,
   Resource,
-  Stack,
   Token,
-  Fn,
+  Arn,
```
[the remark this answers is not in the document]
Comment (rix0rrr) [reply packages/@aws-cdk/aws-iam/lib/oidc-provider.ts:9]: I think the linter only complains about file name ordering, not about symbol names.

File: packages/@aws-cdk/core/test/evaluate-cfn.ts (hunk 8 above)
Comment (rix0rrr) [reply packages/@aws-cdk/core/test/evaluate-cfn.ts:99]: It didn't, really. I thought I needed it in 2 places, but turned out I didn't.

Left the code in because I think it reads more clearly.

Semi-specious argument: this is in test code by itself, and it is already tested by virtue of the existing tests still passing.

File: packages/@aws-cdk/core/lib/arn.ts (hunk 2 above)
Comment (nija-at) [reply packages/@aws-cdk/core/lib/arn.ts]: Why do something different from what we usually do? 
Returning `undefined` or throwing an error is the standard practice. What's the value of deviation?

File: packages/@aws-cdk/core/lib/arn.ts (hunk 1 above)
Comment (nija-at) [reply packages/@aws-cdk/core/lib/arn.ts:203]: I see the 2nd parameter is not optional, so ok.

File: packages/@aws-cdk/aws-iam/lib/oidc-provider.ts (hunk 9 above)
[the remark this answers is not in the document]
Comment (nija-at) [reply packages/@aws-cdk/aws-iam/lib/oidc-provider.ts]: @njlynch - https://github.com/aws/aws-cdk/blob/3cbc7fa58a69330b82935f9d464446fb2d410344/tools/cdk-build-tools/config/eslintrc.js#L81

Should be fixed (not in this PR of course).

File: packages/@aws-cdk/aws-iam/lib/oidc-provider.ts [hunk 10]
```diff
@@ -158,7 +149,7 @@ export class OpenIdConnectProvider extends Resource implements IOpenIdConnectPro
     });
 
     this.openIdConnectProviderArn = Token.asString(resource.ref);
-    this.openIdConnectProviderIssuer = Fn.select(1, Fn.split('oidc-provider/', this.openIdConnectProviderArn));
+    this.openIdConnectProviderIssuer = Arn.extractResourceName(this.openIdConnectProviderArn, 'oidc-provider');
```
Comment (nija-at) [inline packages/@aws-cdk/aws-iam/lib/oidc-provider.ts:152]: A bit worried that this method is going to go undiscovered when someone needs it. 
Anything we can do to make this more discoverable?

I've never actually used the `Arn` class but usually use `stack.parseArn()`.
How about adding it alongside `parseArn()` in the `Stack` class?

File: packages/@aws-cdk/core/lib/arn.ts [hunk 11]
```diff
@@ -206,6 +185,39 @@ export class Arn {
     });
   }
 
+  /**
+   * Extract the full resource name from an ARN
+   *
+   * Necessary for resource names (paths) that may contain the separator, like
+   * `arn:aws:iam::111111111111:role/path/to/role/name`.
```
Comment (nija-at) [inline packages/@aws-cdk/core/lib/arn.ts:192]: Can you clarify when to use `parse()` vs `extractResourceName()` here, and what's recommended in most cases?

File: packages/@aws-cdk/core/lib/arn.ts [hunk 12]
```diff
@@ -268,3 +280,36 @@ function parseToken(arnToken: string, sep: string = '/', hasName: boolean = true
     return { partition, service, region, account, resource, resourceName, sep };
   }
 }
+
+
+/**
+ * Validate that a string is either unparseable or looks mostly like an ARN
+ */
+function parseArnShape(arn: string): 'unparseable' | string[] {
```
Comment (nija-at) [inline packages/@aws-cdk/core/lib/arn.ts:288]: see https://github.com/aws/aws-cdk/pull/11789#discussion_r533300841

File: packages/@aws-cdk/core/lib/arn.ts [hunk 13]
```diff
@@ -135,39 +135,18 @@ export class Arn {
    *      components of the ARN.
    */
   public static parse(arn: string, sepIfToken: string = '/', hasName: boolean = true): ArnComponents {
```
Comment (nija-at) [inline packages/@aws-cdk/core/lib/arn.ts:137]: This applies to line 121 (which GH doesn't let me add a comment at)

Update the statement here recommending the use of `extractResourceName()`

File: packages/@aws-cdk/core/lib/arn.ts [hunk 14]
```diff
@@ -206,6 +185,39 @@ export class Arn {
...
+   * Only works if we statically know the expected `resourceType` beforehand, since we're going
+   * to use that to split the string on ':<resourceType>/' (and take the right-hand side).
+   *
+   * We can't extract the 'resourceType' from the ARN at hand, because CloudFormation Expressions
+   * only allow literals in the 'separator' argument to `{ Fn::Split }`, and so it can't be
+   * `{ Fn::Select: [5, { Fn::Split: [':', ARN] }}`.
+   *
+   * Only necessary for ARN formats for which the type-name separator is `/`.
+   */
+  public static extractResourceName(arn: string, resourceType: string): string {
```
Comment (nija-at) [inline packages/@aws-cdk/core/lib/arn.ts:203]: Keep the terminology consistent and name this `parseResourceName()`. It would help with discoverability as well.

**Review by nija-at — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/core/lib/arn.ts (hunk 6 above)
Comment (nija-at) [reply packages/@aws-cdk/core/lib/arn.ts:304]: cognito sync ARN should include the partition? https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazoncognitosync.html#amazoncognitosync-resources-for-iam-policies

File: packages/@aws-cdk/core/lib/arn.ts (hunk 2 above)
Comment (rix0rrr) [reply packages/@aws-cdk/core/lib/arn.ts]: Returning `undefined` is something we do because more expressive types are not supported in jsii. Since this piece of code is not hamstrung by those constraints, I don't see the point.

The value of deviation is that the return value is trying to connotate something other than what  `undefined` typically means. Generally, `undefined` means some kind of failure condition. That's not what I'm trying to convey here, though. This is a valid situation that needs to be handled by the calling code, just in a different way than if the ARN was parseable. 

Granted, the code word I chose was not very representative of that sentiment, because it sure looks like it represents an error. I will change it to `'token'` to represent that case better.

Alternatively, I can go full sum types and do something like:

```ts
{ shape: 'token' } | { shape: 'components'; components: string[] }
```

I had just though to short-circuit the above into:

```ts
'token' | string[]
```

Without much loss of generality or readability.

File: packages/@aws-cdk/aws-iam/lib/oidc-provider.ts (hunk 10 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-iam/lib/oidc-provider.ts:152]: I'm 100% against `stack.parseArn()` in the first place. It's a member function for no good reason, since it doesn't use any member of `stack`.

So I'm even more against polluting the interface of `Stack` even further by adding more of these member functions that should have been static utilities.

File: packages/@aws-cdk/core/lib/arn.ts (hunk 14 above)
Comment (rix0rrr) [reply packages/@aws-cdk/core/lib/arn.ts:203]: I will do what you ask in order to get this merged, but I'm against it. "parse resource name" is not a good name. The argument is not a resource name that needs parsing. The argument is an ARN that needs a part of it extracted.

Comment (nija-at) [reply packages/@aws-cdk/core/lib/arn.ts:203]: > I will do what you ask in order to get this merged

Don't do that please. 

You're right. `parseResourceName()` is not a good name. How about `parseResourceNameFromArn()`, `parseArnToResourceName()` or something else. I'm not good at names either.

If you still think `extract` is the best, I'm ok leaving it as is.

File: packages/@aws-cdk/aws-iam/lib/oidc-provider.ts (hunk 10 above)
Comment (nija-at) [reply packages/@aws-cdk/aws-iam/lib/oidc-provider.ts]: Could you then mark the one in stack as deprecated and recommend the use of the one in `Arn`?

Comment (rix0rrr) [reply packages/@aws-cdk/aws-iam/lib/oidc-provider.ts]: Honestly I think the better solution is to deprecate `stack.parseArn()` and introduce a new `Arn.parseArn()` that takes an `options` struct, which can have the functionality of `extractResourceName` integrated into as well.

I didn't do that before because I wanted this to be quick and simple and not mess too much with existing code, but I guess we're past the point of a quick fix now and we're going to clean house after all.

I thought you told me yesterday to do that change in a different PR. Should I interpret your comment as you wanting it in this PR anyway?

File: packages/@aws-cdk/core/lib/arn.ts (hunk 14 above)
Comment (rix0rrr) [reply packages/@aws-cdk/core/lib/arn.ts]: I do think `extract` is better, so I guess I will change it back.

This PR is already taking a lot more effort than I was willing to put into it, given its priority among all the other things we should be doing :(.

Comment (rix0rrr) [reply packages/@aws-cdk/core/lib/arn.ts:203]: BTW,

> parseResourceNameFromArn

Given that the full invocation will already read `Arn.extractResourceName()`, I don't think there's much to be gained from `Arn.parseResourceNameFromArn()`.

Willing to consider something like `Arn.resourceNameFrom()` or something, but I don't really see the point in stuttering `Arn` a whole lot.

File: packages/@aws-cdk/aws-iam/lib/oidc-provider.ts (hunk 10 above)
Comment (nija-at) [reply packages/@aws-cdk/aws-iam/lib/oidc-provider.ts:152]: Separate PR is fine.

**Review by nija-at — APPROVED** [review]

File: packages/@aws-cdk/core/lib/arn.ts (hunk 14 above)
Comment (nija-at) [reply packages/@aws-cdk/core/lib/arn.ts:203]: `Arn.resourceNameFrom()` sounds nice
