### PR TITLE
fix(pipelines): self-update role assumes hard-coded role names

### LINKED ISSUE #14877: (pipelines): SelfUpdate role assumes hardcoded role names
Right now, the selfupdate action assumes hardcoded `*-publishing-role-*` and `*-deploy-role-*` roles.

We have to resort to this because we can't know the ACTUAL role names (they will only be known when the CXASM is written, and by the time we're putting together the policies that hasn't happened yet).

The current situation is bad for 2 reasons:

* It breaks if users use non-standard role names.
* There is also a `*` that implies "any account". Even though there isn't really an exploit (if you are able to hijack the CDK CLI which runs there then you can also change the pipeline resources which gets you God mode in the pipeline account and hence also God mode in any of the deployment accounts), the fact that there is a wildcard makes people nervous.

The solution to both is to change to something like this:

```
Bootstrap roles are created with tags:
  `cdk_pipelines_self_mutate=true` (or something)

Policy changes to:
  Effect: Allow
  Action: sts:AssumeRole
  Resource: `arn:aws::${AWS::AccountId}:role/*`
  Condition:
    StringEquals:
      cdk_pipelines_self_mutate: true
```

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by njlynch**
Right now, the selfupdate action assumes hardcoded `*-publishing-role-*` and
`*-deploy-role-*` roles, because we can't know the actual role names at the time
the policies are being created.

This means pipelines' self-update is unusable for customers with custom
bootstrap role names. To solve this -- and other -- issue(s), tag the roles to
identify them, and change out the policy to use these tags instead.

This requires bumping the bootstrap stack template version, and the minimum
required version in the default synthesizer.

fixes #14877
related #9271

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts [hunk 1]
```diff
@@ -19,7 +19,7 @@ export const BOOTSTRAP_QUALIFIER_CONTEXT = '@aws-cdk/core:bootstrapQualifier';
 /**
  * The minimum bootstrap stack version required by this app.
  */
-const MIN_BOOTSTRAP_STACK_VERSION = 4;
+const MIN_BOOTSTRAP_STACK_VERSION = 6;
```
Comment (rix0rrr) [inline packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts:22]: I was hoping we could do this bump conditionally, only if you use CDK Pipelines.

But yeah, we don't have affordances for that right now.

Comment (njlynch) [reply packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts:22]: I was hoping the same, but couldn't find a reasonable way to do it.

The customer experience here is certainly something we should be aiming to improve, if my understanding is correct. This means any and all customers who upgrade to CDK v.1XX.0 will need to re-bootstrap all of their environments, even if they're not using pipelines, correct?

The only alternative that (quickly) comes to mind is to switch this minimum version on a feature flag, and allow people to opt-in to the v6 bootstrap stack only if they're using pipelines. However, as soon as we need to bump it again (whether for pipelines or something else), those customers will still need to upgrade; not sure if that's worth it. :/

File: packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml [hunk 2]
```diff
@@ -225,6 +225,9 @@ Resources:
               - Ref: AWS::NoValue
       RoleName:
         Fn::Sub: cdk-${Qualifier}-file-publishing-role-${AWS::AccountId}-${AWS::Region}
+      Tags:
+        - Key: aws-cdk:bootstrap-role
+          Value: file-publishing
```
Comment (njlynch) [inline packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml:230]: Open to advice on where we'd document this convention such that folks can now override these role names as long as they tag consistently.

**Review by eladb — COMMENTED** [review]
Isn't it possible to customize role names through the stack synthesizer? I was under the impression that this is how we enabled that use case.

Are there any security implications on using tags?

**Comment by njlynch** [comment]
> Isn't it possible to customize role names through the stack synthesizer? I was under the impression that this is how we enabled that use case.

Per @rix0rrr  on the linked issue:

> Right now, the selfupdate action assumes hardcoded *-publishing-role-* and *-deploy-role-* roles.
> We have to resort to this because we can't know the ACTUAL role names (they will only be known when the CXASM is written, and by the time we're putting together the policies that hasn't happened yet).

---

> Are there any security implications on using tags?

None that are called out in the relevant documentation: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_iam-assume-tagged-role.html

File: packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (njlynch) [reply packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts:22]: Because version 6 (see the bootstrap template) was when this functionality was introduced. I believe the changes made for bootstrap version 5 didn't impact the default synth process, which is why it wasn't bumped; however, I'm mostly pulling that from memory so I could be wrong.

File: packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml [hunk 3]
```diff
@@ -426,6 +432,9 @@ Resources:
           PolicyName: default
       RoleName:
         Fn::Sub: cdk-${Qualifier}-deploy-role-${AWS::AccountId}-${AWS::Region}
+      Tags:
+        - Key: aws-cdk:bootstrap-role
+          Value: deploy-artifacts
```
Comment (rix0rrr) [inline packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml:437]: This is a bit of a misnomer. This role doesn't just deploy artifacts, it deploys everything. Maybe just
```suggestion
          Value: deploy
```

To match the naming schema of the other roles?

File: packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml [hunk 4]
```diff
@@ -296,6 +299,9 @@ Resources:
             Version: '2012-10-17'
           PolicyName:
             Fn::Sub: cdk-${Qualifier}-lookup-role-default-policy-${AWS::AccountId}-${AWS::Region}
+      Tags:
+        - Key: aws-cdk:bootstrap-role
+          Value: image-publishing
```
Comment (rix0rrr) [inline packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml:304]: This one looks to be attached to the wrong role?

File: packages/@aws-cdk/pipelines/lib/actions/update-pipeline-action.ts [hunk 5]
```diff
@@ -97,7 +98,12 @@ export class UpdatePipelineAction extends CoreConstruct implements codepipeline.
     // allow the self-mutating project permissions to assume the bootstrap Action role
     selfMutationProject.addToRolePolicy(new iam.PolicyStatement({
       actions: ['sts:AssumeRole'],
-      resources: ['arn:*:iam::*:role/*-deploy-role-*', 'arn:*:iam::*:role/*-publishing-role-*'],
+      resources: [`arn:*:iam::${Stack.of(this).account}:role/*`],
+      conditions: {
+        'ForAnyValue:StringEquals': {
+          'iam:ResourceTag/aws-cdk:bootstrap-role': ['image-publishing', 'file-publishing', 'deploy-artifacts'],
```
Comment (rix0rrr) [inline packages/@aws-cdk/pipelines/lib/actions/update-pipeline-action.ts:104]:
```suggestion
          'iam:ResourceTag/aws-cdk:bootstrap-role': ['image-publishing', 'file-publishing', 'deploy'],
```

File: packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml (hunk 2 above)
Comment (rix0rrr) [reply packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml:230]: Needs to go here I think

https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html

**Review by rix0rrr — CHANGES_REQUESTED** [review]

File: packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml (hunk 4 above)
Comment (njlynch) [reply packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml:304]: Whoops. Bad merge conflict resolution, I think.

**Review by rix0rrr — APPROVED** [review]
LGTM; approval conditional on a manual test having been done

**Comment by njlynch** [comment]
> approval conditional on a manual test having been done

Yup, done. Hand-deployed the pipeline with self-updates enabled; verified the pipeline was successfully updated (back to the state prior to this PR).

File: packages/@aws-cdk/pipelines/lib/actions/update-pipeline-action.ts [hunk 6]
```diff
@@ -97,7 +98,12 @@ export class UpdatePipelineAction extends CoreConstruct implements codepipeline.
     // allow the self-mutating project permissions to assume the bootstrap Action role
     selfMutationProject.addToRolePolicy(new iam.PolicyStatement({
       actions: ['sts:AssumeRole'],
-      resources: ['arn:*:iam::*:role/*-deploy-role-*', 'arn:*:iam::*:role/*-publishing-role-*'],
+      resources: [`arn:*:iam::${Stack.of(this).account}:role/*`],
```
Comment (adriantaut) [inline packages/@aws-cdk/pipelines/lib/actions/update-pipeline-action.ts:101]: @njlynch we were taking benefit of the fact that the self mutating CodeBuild project has permissions to assume roles in ANY account with `arn:*:iam::*:role/` . We used this for deploying some prerequisites before the actual `application stage` to deploy something cross-account.

Now the `assumeRole` was restricted to `arn:*:iam::${Stack.of(this).account}:role/`...I know our approach might have been working by mistake, but if not, is it possible this restriction to be reverted back to `arn:*:iam::*:role/`?

@rix0rrr what are your thoughts?

Comment (rix0rrr) [reply packages/@aws-cdk/pipelines/lib/actions/update-pipeline-action.ts:101]: We are not going to revert this, but if you want to add additional permissions to assume roles, you can use the construct tree to dig out the relevant CodeBuild Project construct and call `addToRolePolicy()` on it for the roles that you need.
