### PR TITLE
fix(ec2): validate throughput property on EC2 instance block devices

### LINKED ISSUE #34033: ec2: aws go cdk ommit Throughput parameter for EBS block devices
### Describe the bug

I encounter an issue, When running cdk synth, the generated CloudFormation template lacks the Throughput parameter for EBS block devices, even though it is explicitly configured in the code. For example, the template should include:
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            Iops: 10000
            Throughput: 500 -->>> is missing. 
            VolumeSize: 500
            VolumeType: gp3
      EbsOptimized: false
Here, my code.
    ebsOptions := &awsec2.EbsDeviceOptions{
        VolumeType: ebsVolumeType,
        Throughput: jsii.Number(throughput),
        Iops:      jsii.Number(iops),
    }

The source file indicates it's supported. 
https://github.com/aws/aws-cdk-go/blob/awscdk/v2.187.0/awscdk/awsec2/EbsDeviceOptions.go#L33

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

Create EC2 with specified EBS throughput.

### Current Behavior

The EBS Size/IOPS are correct, but the throughput stays at 125M/s, the default value. 

### Reproduction Steps

Create ec2 with blockdevices and ebsOptions below. 
```
    ebsOptions := &awsec2.EbsDeviceOptions{
        VolumeType: ebsVolumeType,
        Throughput: jsii.Number(throughput),
        Iops:      jsii.Number(iops),
    }

....

awsec2.NewInstance(stack, jsii.String(xxxxxxxxx), &awsec2.InstanceProps {
       ...
       BlockDevices: &blockDevices,
       ...
    }


```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.1007.0

### Framework Version

_No response_

### Node.js Version

v22.14.0

### OS

MacOS/Gentoo Linux/Amazon Linux

### Language

Go

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by ozelalisen**
### Issue # (if applicable)

Closes #34033.

### Reason for this change

The throughput property for GP3 volumes is not supported on EC2 instances and only works with Launch Templates. This causes confusion for users who try to set throughput on EC2 instance block devices, as the property is silently ignored.

### Description of changes

Added synthesis-time validation in the instanceBlockDeviceMappings function to detect when throughput is specified for an EBS volume on an EC2 instance. The validation throws a clear error message directing users to use Launch Templates instead.

### Describe any new or updated permissions being added

No new or updated IAM permissions are needed.

### Description of how you validated changes

Added a unit test that verifies the validation works correctly by attempting to create an EC2 instance with a GP3 volume that has throughput specified and confirming that the expected error message is thrown.

### Checklist
• [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-ec2/lib/private/ebs-util.ts [hunk 1]
```diff
@@ -4,6 +4,15 @@ import { CfnInstance, CfnLaunchTemplate } from '../ec2.generated';
 import { BlockDevice, EbsDeviceVolumeType } from '../volume';
 
 export function instanceBlockDeviceMappings(construct: Construct, blockDevices: BlockDevice[]): CfnInstance.BlockDeviceMappingProperty[] {
+  for (const blockDevice of blockDevices) {
+    if (blockDevice.volume.ebsDevice?.throughput !== undefined) {
+      throw new ValidationError(
```
Comment (aemada-aws) [inline packages/aws-cdk-lib/aws-ec2/lib/private/ebs-util.ts:9]: This should be a warning not an error, otherwise this change is backwards incompatible. Users who had old stacks that deployed successfully with the attribute doing nothing will now fail to syntha.

**Review by aemada-aws — CHANGES_REQUESTED** [review]

File: packages/aws-cdk-lib/aws-ec2/lib/private/ebs-util.ts [hunk 2]
```diff
@@ -4,6 +4,14 @@ import { CfnInstance, CfnLaunchTemplate } from '../ec2.generated';
 import { BlockDevice, EbsDeviceVolumeType } from '../volume';
 
 export function instanceBlockDeviceMappings(construct: Construct, blockDevices: BlockDevice[]): CfnInstance.BlockDeviceMappingProperty[] {
+  for (const blockDevice of blockDevices) {
+    if (blockDevice.volume.ebsDevice?.throughput !== undefined) {
+      Annotations.of(construct).addWarning(
```
Comment (aemada-aws) [inline packages/aws-cdk-lib/aws-ec2/lib/private/ebs-util.ts:9]: Can we use addWarningV2? It allows the user to acknowledge the warning via the warning id.

File: packages/aws-cdk-lib/aws-ec2/test/instance.test.ts [hunk 3]
```diff
@@ -347,6 +347,26 @@ describe('instance', () => {
...
+            deviceName: 'ebs',
+            volume: BlockDeviceVolume.ebs(15, {
+              deleteOnTermination: true,
+              encrypted: true,
+              volumeType: EbsDeviceVolumeType.GP3,
+              throughput: 125,
+            }),
+          }],
+        });
+      }).toThrow(/The throughput property is not supported on EC2 instances. Use a Launch Template instead/);
```
Comment (aemada-aws) [inline packages/aws-cdk-lib/aws-ec2/test/instance.test.ts:367]: this will fail

**Comment by ozelalisen** [comment]
@aemada-aws Thank you for your review! I fixed your comments.

**Comment by ozelalisen** [comment]
Exemption Request: This pull request should be exempted from the integration test requirement as it only adds client-side validation warnings for the throughput property on EC2 instance block devices, which has been adequately validated through unit tests. The change doesn't modify any infrastructure behavior and focuses solely on improving developer experience by warning users when they attempt to use throughput settings that only work with Launch Templates.
