### PR TITLE
fix(lambda): function version ignores layer version changes

### LINKED ISSUE #19098: (aws-lambda): Layer updates not creating new function version
### What is the problem?

If my stack contains a Lambda LayerVersion and a Lambda Function with an alias pointing to the newest version, content changes within the layer do not trigger deployment of a new Function version.

### Reproduction Steps

Example stack demonstrating the problem:
```ts
export class CdkLayerExampleStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const layer = new lambda.LayerVersion(this, 'MyLayer', {
      code: lambda.Code.fromAsset('layer-code'),
      compatibleRuntimes: [lambda.Runtime.NODEJS_14_X],
      description: 'A layer to test the L2 construct',
    });

    const fn = new lambda.Function(this, 'MyLayeredLambda', {
      code: lambda.Code.fromAsset('function-code'),
      handler: 'index.handler',
      runtime: lambda.Runtime.NODEJS_14_X,
      layers: [layer],
    });

    fn.currentVersion.addAlias('live');
  }
}
```

The layer contents, defined in `layer-code/nodejs/node_modules/layer.js`:
```ts
exports.getLayerVersion = function() {
  return 'V1';
}
```

The Lambda function, defined in `function-code/index.js`:
```ts
const layer = require('layer');

exports.handler = async function(event, context) {
  const functionVersion = 'V1';
  const layerVersion = layer.getLayerVersion();

  return {
    functionVersion,
    layerVersion,
  }
};
```

In `cdk.json`:
```json
{
  "app": "npx ts-node --prefer-ts-exts bin/cdk-layer-example.ts",
  "context": {
    "@aws-cdk/core:newStyleStackSynthesis": "true",
    "@aws-cdk/aws-apigateway:usagePlanKeyOrderInsensitiveId": true,
    "@aws-cdk/core:enableStackNameDuplicates": "true",
    "aws-cdk:enableDiffNoFail": "true",
    "@aws-cdk/core:stackRelativeExports": "true",
    "@aws-cdk/aws-ecr-assets:dockerIgnoreSupport": true,
    "@aws-cdk/aws-secretsmanager:parseOwnedSecretName": true,
    "@aws-cdk/aws-kms:defaultKeyPolicies": true,
    "@aws-cdk/aws-s3:grantWriteWithoutAcl": true,
    "@aws-cdk/aws-ecs-patterns:removeDefaultDesiredCount": true,
    "@aws-cdk/aws-rds:lowercaseDbIdentifier": true,
    "@aws-cdk/aws-efs:defaultEncryptionAtRest": true,
    "@aws-cdk/aws-lambda:recognizeVersionProps": true,
    "@aws-cdk/aws-cloudfront:defaultSecurityPolicyTLSv1.2_2021": true
  }
}
```

### What did you expect to happen?

Making content changes within `layer-code/nodejs/node_modules/layer.js` should trigger deployment of a new layer version and new function version, updating the `live` alias to point to the new function version.

### What actually happened?

A new layer version was created, as expected, but a new function version was not created. Invoking the function directly shows that the new layer version is being used, but invoking the function alias shows the old layer version is still in use.

### CDK CLI Version

1.143.0 (build bebd295)

### Framework Version

_No response_

### Node.js Version

v16.13.2

### OS

macOS 12.2

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by kaizencc**
Fixes #19098.

This introduces two bug fixes that are hidden behind a feature flag to preserve the current hash:

- lambda layer order is ignored by the hash now 
- lambda layer version is included in the hash (along with other lambda layer attributes)

I also added a few more tests around this area to confirm the current behavior which should help demonstrate what the feature flag will change.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/cx-api/lib/features.ts [hunk 1]
```diff
@@ -255,6 +257,7 @@ export const FUTURE_FLAGS: { [key: string]: boolean } = {
   [RDS_LOWERCASE_DB_IDENTIFIER]: true,
   [EFS_DEFAULT_ENCRYPTION_AT_REST]: true,
   [LAMBDA_RECOGNIZE_VERSION_PROPS]: true,
+  [LAMBDA_RECOGNIZE_LAYER_VERSION]: true,
```
Comment (kaizencc) [inline packages/@aws-cdk/cx-api/lib/features.ts:260]: This line has been causing me problems. When set to `false`, the integ runner works fine. But as it is set to `true`, it seems like the integ runner picks this flag up and then changes the behavior for many of the lambda integ tests. 

A cursory glance at the integ runner shows me that future flags are a part of it:

https://github.com/aws/aws-cdk/blob/144b38ddde8994aa7c7b8fd292cb383c3b57fa9c/packages/%40aws-cdk/integ-runner/lib/runner/runner-base.ts#L369-L387

I see two paths forward -- either the integ runner shouldn't be picking up these flags, or we will have to be okay with a couple of lambda integ tests being changed as a result of this PR. I am leaning towards the latter being the path we want to go down, but want to get confirmation on it first.

File: packages/@aws-cdk/aws-lambda/test/function.test.ts [hunk 2]
```diff
@@ -1437,6 +1439,69 @@ describe('function', () => {
...
+    });
+
+    fn.addLayers(layer);
+
+    const newFnHash = calculateFunctionHash(fn);
+
+    expect(fnHash).not.toEqual(newFnHash);
+  });
+
+  test('with feature flag, layer version is baked into function version', () => {
```
Comment (kaizencc) [inline packages/@aws-cdk/aws-lambda/test/function.test.ts:1469]: This is the most important test that should validate that the bug is fixed. It is hard to actually model the process described in the issue, but I hope this is sufficient. My idea is that specifically, the `s3Key` will change when the layer code is updated, thereby changing the layershash. Curious if I am missing any considerations like if the s3Key is a token.

File: packages/@aws-cdk/aws-lambda/lib/function.ts [hunk 3]
```diff
@@ -640,7 +641,7 @@ export class Function extends FunctionBase {
 
   protected readonly canCreatePermissions = true;
 
-  private readonly layers: ILayerVersion[] = [];
+  public readonly layers: ILayerVersion[] = [];
```
Comment (kaizencc) [inline packages/@aws-cdk/aws-lambda/lib/function.ts:644]: The alternative to making this public is to send the layers directly into the `calculateFunctionHash()` like: `calculateFunctionHash(fn, fn.layers)`. That seems awkward to me so I chose to make this public.

**Review by kaizencc — COMMENTED** [review]
Reviving this PR that has been sitting in my local copy of cdk for a while. It's still a bit rough around the edges but I think it's worth getting out there.

File: packages/@aws-cdk/aws-lambda/test/function-hash.test.ts [hunk 4]
```diff
@@ -123,8 +123,114 @@ describe('function hash', () => {
...
+
+        const stack3 = new Stack();
+        const fn2 = new lambda.Function(stack3, 'MyFunction', {
+          runtime: lambda.Runtime.NODEJS_12_X,
+          code: lambda.Code.fromInline('foo'),
+          handler: 'index.handler',
+          layers: [layer2, layer1],
+        });
+
+        expect(calculateFunctionHash(fn1)).not.toEqual(calculateFunctionHash(fn2));
```
Comment (kaizencc) [inline packages/@aws-cdk/aws-lambda/test/function-hash.test.ts:206]: This test should assert the exact function hash, and not that they are different.

File: packages/@aws-cdk/aws-lambda/lib/function-hash.ts [hunk 5]
```diff
@@ -117,3 +122,25 @@ function sortProperties(properties: any) {
   }
   return ret;
 }
+
+function calculateLayersHash(layers: ILayerVersion[]): string {
+  const layerConfig: {[key: string]: any } = {};
+  for (const layer of layers) {
+    const stack = Stack.of(layer);
+    const layerResource = layer.node.defaultChild as CfnResource;
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-lambda/lib/function-hash.ts:130]: What if this thing is imported?

File: packages/@aws-cdk/aws-lambda/test/function.test.ts (hunk 2 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-lambda/test/function.test.ts:1469]: Yeah, it's not going to work when `s3Key` is a token.

File: packages/@aws-cdk/cx-api/lib/features.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/@aws-cdk/cx-api/lib/features.ts:260]: Agreed.

**Review by rix0rrr — APPROVED** [review]

File: packages/@aws-cdk/aws-lambda/README.md [hunk 6]
```diff
@@ -291,8 +291,15 @@ by default.
 Existing users will need to enable the [feature flag]
 `@aws-cdk/aws-lambda:recognizeVersionProps`. Since CloudFormation does not
 allow duplicate versions, they will also need to make some modification to
-their function so that a new version can be created. Any trivial change such as
```
Comment (kaizencc) [inline packages/@aws-cdk/aws-lambda/README.md:294]: updated this readme

File: packages/@aws-cdk/aws-lambda/lib/function.ts [hunk 7]
```diff
@@ -1269,3 +1284,23 @@ function undefinedIfNoKeys<A>(struct: A): A | undefined {
...
 }
+
+/**
+ * Aspect for upgrading function versions when the feature flag
+ * provided feature flag present. This can be necessary when the feature flag
+ * changes the function hash, as such changes must be associated with a new
+ * version. This aspect will change the function description in these cases,
+ * which "validates" the new function hash.
+ */
+export class FunctionVersionUpgrade implements IAspect {
```
Comment (kaizencc) [inline packages/@aws-cdk/aws-lambda/lib/function.ts:1295]: added this Aspect that should help users update their existing lambdas

File: packages/@aws-cdk/aws-lambda/test/integ.lambda.ts [hunk 8]
```diff
@@ -31,4 +32,8 @@ alias.addFunctionUrl({
   authType: lambda.FunctionUrlAuthType.NONE,
 });
 
+// Changes the function description when the feature flag is present
+// to validate the changed function hash.
+cdk.Aspects.of(stack).add(new lambda.FunctionVersionUpgrade(LAMBDA_RECOGNIZE_LAYER_VERSION));
```
Comment (kaizencc) [inline packages/@aws-cdk/aws-lambda/test/integ.lambda.ts:37]: Added this aspect here, so that `yarn integ --update-on-failed` succeeds. For the integ test updates in other modules, I just ran `yarn integ --update-on-failed --disable-update-workflow --dry-run`.

File: packages/@aws-cdk/aws-lambda/lib/function.ts (hunk 3 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-lambda/lib/function.ts:647]: `calculateFunctionHash` is a private function, so I don't really care about its signature. I care more about making this public, which this change does... so I'd rather you didn't.

**Review by rix0rrr — APPROVED** [review]
Conditionally approved

File: packages/@aws-cdk/aws-lambda/lib/function.ts (hunk 3 above)
Comment (kaizencc) [reply packages/@aws-cdk/aws-lambda/lib/function.ts:647]: Marked @internal instead. I need this to be publicly accessible for the aspect as well, and if my understanding of `@internal` is correct, this makes the most sense.

File: packages/@aws-cdk/aws-lambda/README.md [hunk 9]
```diff
@@ -304,6 +311,30 @@ record whether a new version should be generated when this property is changed.
 This can be typically determined by checking whether the property can be
 modified using the *[UpdateFunctionConfiguration]* API or not.
 
+### `currentVersion`: Updated hashing logic for layer versions
+
+An additional update to the hashing logic fixes two issues surrounding layers.
+Prior to this change, updating the lambda layer version would have no affect on
```
[the remark this answers is not in the document]
Comment (kaizencc) [reply packages/@aws-cdk/aws-lambda/README.md:317]: yep. version numbers aren't the whole picture because upgrading the version won't get the new behavior. It's the version number when you run `cdk init` that is binding, so I've updated the paragraph to reflect this.

File: packages/@aws-cdk/aws-lambda/lib/function-hash.ts [hunk 10]
```diff
@@ -117,3 +122,29 @@ function sortProperties(properties: any) {
...
+    // if there is no layer resource, then the layer was imported
+    if (layerResource === undefined) {
+      continue;
+    }
```
[the remark this answers is not in the document]
Comment (kaizencc) [reply packages/@aws-cdk/aws-lambda/lib/function-hash.ts:134]: included

**Comment by izsherpa** [comment]
modify cdk.json to enable this feature, pasting this inside the context:
{...
    "context": {
    "@aws-cdk/aws-lambda:recognizeLayerVersion": true,
    ....
    }
}
