### PR TITLE
fix(stepfunctions-tasks): stateMachine construct doesn't generate a valid policy for default StateMachineRole

### LINKED ISSUE #31714: aws_stepfunctions: StateMachine construct doesn't generate a valid policy for default StateMachineRole
### Describe the bug

When using `aws_stepfunctions.StateMachine`, the default IAM policy for the state machine role does not generate the correct statement for the action `ecs:RunTask`.

The difference being that we now must specify the revision number (or all revisions by omitting the number and simply adding `:`) tagged onto the task definition ARN.

From 15th October 2024, the statement generated will result in an AccessDeniedException when the state machine attempts to RunTask on the non-tagged task definition ARN.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

N/A

### Expected Behavior

The valid statement that should be generated:
```json
{
    "Action": "ecs:RunTask",
    "Resource": "arn:aws:ecs:eu-west-1:12345:task-definition/TaskDefinitionABC1234:1",
    "Effect": "Allow"
}
```

### Current Behavior

The statement generated: 
```json
{
    "Action": "ecs:RunTask",
    "Resource": "arn:aws:ecs:eu-west-1:12345:task-definition/TaskDefinitionABC1234",
    "Effect": "Allow"
}
```

### Reproduction Steps

```typescipt

// exectionRole

const taskDefinition = new ecs.FargateTaskDefinition(this, 'TaskDefinition', {
  cpu: 256,
  executionRole,
  memoryLimitMiB: 512,
});

// container definitions...

const stateMachineDefinition = new tasks.EcsRunTask(this, 'Run Traffic DB maintenance jobs', {
  cluster,
  launchTarget: new tasks.EcsFargateLaunchTarget(),
  taskDefinition,
  integrationPattern: sfn.IntegrationPattern.RUN_JOB,
});

const stateMachine = new sfn.StateMachine(this, 'StateMachine', {
    definition: stateMachineDefinition,
    stateMachineName: 'StateMachine',
    stateMachineType: sfn.StateMachineType.STANDARD,
    timeout: Duration.hours(2),
    tracingEnabled: true,
});
```

### Possible Solution

CDK synth should generate the correct IAM statement for state machines ecs:RunTask by using the task definition role ARN with the revision tag attached to the task definition.

Work around for the time being:

```typescipt

// exectionRole

const taskDefinition = new ecs.FargateTaskDefinition(this, 'TaskDefinition', {
  cpu: 256,
  executionRole,
  memoryLimitMiB: 512,
});

// container definitions...

const stateMachineDefinition = new tasks.EcsRunTask(this, 'Run Traffic DB maintenance jobs', {
  cluster,
  launchTarget: new tasks.EcsFargateLaunchTarget(),
  taskDefinition,
  integrationPattern: sfn.IntegrationPattern.RUN_JOB,
});

const stateMachine = new sfn.StateMachine(this, 'StateMachine', {
    definition: stateMachineDefinition,
    stateMachineName: 'StateMachine',
    stateMachineType: sfn.StateMachineType.STANDARD,
    timeout: Duration.hours(2),
    tracingEnabled: true,
});

// WORK AROUND 
// Create a new policy
const policy = new iam.Policy(this, 'RunTaskPolicy', {
  statements: [
    new iam.PolicyStatement({
      actions: ['ecs:RunTask'],
      resources: [`${taskDefinition.taskDefinitionArn}`]
    })
  ]
});

// Attach the new policy to the state machine
policy.attachToRole(stateMachine.role)
```

### Additional Information/Context

_No response_

### CDK CLI Version

2.161.1 (build 0a606c9)

### Framework Version

_No response_

### Node.js Version

v22.9.0

### OS

MacOS

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by xazhao**
### Issue # (if applicable)

Closes #31714.

### Reason for this change

Currently, the step functions `runEcsTask()` will create an IAM policy. The `Resource` section is an ARN constructed by CDK with wildcard `*` appending at the end. However, CDK should `Ref` the resource directly instead of constructing the ARN, while keeping the revision number.

### Description of changes

The same solution as https://github.com/aws/aws-cdk/pull/31615. However this change needs to behind a feature flag because it could be a breaking change.

### Description of how you validated changes

Integration test. Also checked the synth template.

### Checklist
- [ ] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/ecs/run-task.ts [hunk 1]
```diff
@@ -398,6 +399,19 @@ export class EcsRunTask extends sfn.TaskStateBase implements ec2.IConnectable {
     return policyStatements;
   }
 
+  private getTaskDefinitionArn(): string {
+    const tastDefinitionArn = this.props.taskDefinition.taskDefinitionArn;
+    let needsRevisionWildcard = false;
+    // Check if there is a taskdefinition revision
+    // (arn will end with : followed by digits) included in the arn already
+    if (!cdk.Token.isUnresolved(tastDefinitionArn)) {
```
Comment (samson-keung) [inline packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/ecs/run-task.ts:407]: This `EcsRunTask` class does not accept imported task definition (see [code](https://github.com/aws/aws-cdk/pull/31801/files#diff-9d5f521b191b7a78f695205cd6cdbf39fce4ffcae0de03b4c4a92d3c59c06f3cR29)). So we can skip this `if` block.

Comment (xazhao) [reply packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/ecs/run-task.ts:407]: Good point. Will remove this `if` block.

**Review by samson-keung — APPROVED** [review]

**Review by GavinZZ — APPROVED** [review]
LGTM
