### PR TITLE
fix(cloudfront): requirement of domainNames prevents moving a domain name between distributions

### LINKED ISSUE #29960: aws-cloudfront: cdk incorrectly prevents attaching certificate when no aliases are given
### Describe the bug

Hi, I am trying to follow the instructions on how to move an alias from an existing alias from one CloudFront distribution to another. The instructions says that I need to set up the target distribution with a certificate that includes the alternative domain name that I want to move: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-move-create-target

However when I try to set up the distribution with the certificate but without the alternative domain names (as directed in the instructions) I run into an error 'Must specify at least one domain name to use a certificate with a distribution' generated I think from this like of code within CDK:

[aws-cdk/packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts](https://github.com/aws/aws-cdk/blob/6fdc4582f659549021a64a4d676fce12fc241715/packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts#L323)
Line 323 in [6fdc458](https://github.com/aws/aws-cdk/commit/6fdc4582f659549021a64a4d676fce12fc241715)

```
 throw new Error('Must specify at least one domain name to use a certificate with a distribution'); 
``` 
 
It seems that CDK prevents me from adding a certificate unless I have a domain name; but that means I cannot follow the process for moving an alias from an old distribution to a new one. I can create a distribution with a certificate and no alias if I use the aws web console to do it; so I think CDK is wrong with this validation.

### Expected Behavior

CDK should allow me to create a cloudfront distribution that has an ACM certificate attached but no aliases

### Current Behavior

CDK raises an error message `'Must specify at least one domain name to use a certificate with a distribution'` when I try to create a cloudfront distribution that has an ACM certificate attached but no aliases

### Reproduction Steps

```
       distribution = cloudfront.Distribution(
            self,
            "Distribution",
            domain_names=[],
            default_behavior=cloudfront.BehaviorOptions(
                origin=origins.HttpOrigin(
                    dns_name,
                    protocol_policy=cloudfront.OriginProtocolPolicy.HTTPS_ONLY,
                    origin_ssl_protocols=[
                        cloudfront.OriginSslPolicy.TLS_V1_1,
                        cloudfront.OriginSslPolicy.TLS_V1_2,
                    ],
                    read_timeout=Duration.seconds(60),
                ),
                viewer_protocol_policy=cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
                origin_request_policy=cloudfront.OriginRequestPolicy.ALL_VIEWER,
                cache_policy=cache_policy,
                allowed_methods=cloudfront.AllowedMethods.ALLOW_ALL,
                compress=True,
            ),
            price_class=cloudfront.PriceClass.PRICE_CLASS_200,
            enabled=True,
            log_includes_cookies=False,
            log_bucket=logging_bucket,
            enable_logging=True,
            web_acl_id=waf_acl_arn,
            ssl_support_method=cloudfront.SSLMethod.SNI,
            certificate=my_certificate,
            minimum_protocol_version=cloudfront.SecurityPolicyProtocol.TLS_V1_2_2021,
        )
 ```

### Possible Solution

Remove the spurious validation check:

```
      if ((props.domainNames ?? []).length === 0) {
        throw new Error('Must specify at least one domain name to use a certificate with a distribution');
      }
```

### Additional Information/Context

_No response_

### CDK CLI Version

2.137.0 (build bb90b4c)

### Framework Version

_No response_

### Node.js Version

v21.7.1

### OS

Mac OS

### Language

Python

### Language Version

Python 3.11

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Tietew**
### Issue # (if applicable)

Closes #29960.

### Reason for this change

When I want to move a domain name from a distribution to another distribution,
I must create a distribution with a certificate associated but no domain names.

### Description of changes

Re-submit of previous #29329.
Removed the validation that `domainNames` must not be blank when a certificate is associated.

### Description of how you validated changes

Updated a unit test to allow absent domainNames when a certificate is associated.

See AWS Documentation for details: Using custom URLs by adding alternate domain names (CNAMEs) > Moving an alternate domain name to a different distribution
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-move

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by gracelu0** [comment]
> Exemption Request
> 
> There are no integ tests for a distribution with certificate.

Hi @Tietew , are there any issues preventing us from adding such an integ test? If not it would be great if you could add one as part of this PR.

**Comment by Tietew** [comment]
@gracelu0 Thank you for your comment.

Integ test for this PR needs an issued public ACM certificate, which requires a reachable DNS zone (Route53 public hosted zone).
I can run tests using my private domain, but others cannot reproduce it with the same domain.
They seem a reason why integ tests do not exist currently for distributions with certificate.
Unit tests may cover whether the generated template is correct.

File: packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts [hunk 1]
```diff
@@ -129,7 +129,10 @@ export interface DistributionProps {
    *
    * If you want to use your own domain name, such as www.example.com, instead of the cloudfront.net domain name,
    * you can add an alternate domain name to your distribution. If you attach a certificate to the distribution,
-   * you must add (at least one of) the domain names of the certificate to this list.
+   * you should add (at least one of) the domain names of the certificate to this list.
+   *
+   * When you want to move a domain name between distributions, you can associate a certificate without specifying any domain names.
+   * See [Moving an alternate domain name to a different distribution](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-move) for details.
```
Comment (gracelu0) [inline packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts:135]: Reading the docs, I see that moving the domain name requires calling the `associate-alias` CLI command. So this change just allows the user to create a target distribution but they would still need to call `associate-alias` correct?  I think it would be helpful to include an example of how someone would do this in CDK in the README.

**Review by gracelu0 — DISMISSED** [review]

File: packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts (hunk 1 above)
Comment (Tietew) [reply packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts:135]: Yes. We should call `associate-alias` cli command manually.
I will add the instructions.

Comment (Tietew) [reply packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts]: I've added a new section to the README.
Thanks for your suggestion!

**Review by gracelu0 — APPROVED** [review]
LGTM, thank you for contributing!
