### PR TITLE
fix(eks): ssm path for gpu optimized ami is invalid

### LINKED ISSUE #6891: EksOptimizedImage returns wrong image SSM path /aws/service/eks/optimized-ami/1.14/recommended/image_id
EksOptimizedImage returns the wrong image ssm path without amazon-linux-2 

`aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.14/recommended/image_id --query "Parameter.[Name,Value]" --output text

An error occurred (ParameterNotFound) when calling the GetParameter operation:
`

`aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.14/amazon-linux-2/recommended/image_id --query "Parameter.[Name,Value]" --output text
/aws/service/eks/optimized-ami/1.14/amazon-linux-2/recommended/image_id	ami-0d373fa5015bc43be
`

### Reproduction Steps

Create autoscaling group using EksOptimizedImage
`        asg = autoscaling.AutoScalingGroup(
            self, "KubeFleet",
            instance_type=InstanceType("t3.large"),
            machine_image=eks.EksOptimizedImage(),
            associate_public_ip_address=False,
            update_type=autoscaling.UpdateType.REPLACING_UPDATE,
            desired_capacity=3,
            vpc=vpc,
            vpc_subnets={'subnet_type': SubnetType.PRIVATE}
        )
`

### Error Log

```console
Error [ValidationError]: Unable to fetch parameters [/aws/service/eks/optimized-ami/1.14/recommended/image_id] from parameter store for this account.
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'Unable to fetch parameters [/aws/service/eks/optimized-ami/1.14/recommended/image_id] from parameter store for this account.',
```

### Environment

  - **CLI Version      :2.0.0**
  - **Framework Version: 1.28.0**
  - **OS               : OSX 10**
  - **Language         : Python 3.7.6**

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by pahud**
### Commit Message
fix(eks): ssm path for amazon linux 2 gpu ami is invalid (#7672)

According to the [document](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html), the path should be /**aws/service/eks/optimized-ami/1.15/amazon-linux-2/recommended/image_id**

Also fixes #6891 

### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by pahud** [comment]
copy @eladb

File: packages/@aws-cdk/aws-eks/lib/cluster.ts [hunk 1]
```diff
@@ -959,14 +959,14 @@ export class EksOptimizedImage implements ec2.IMachineImage {
   /**
    * Constructs a new instance of the EcsOptimizedAmi class.
    */
-  public constructor(props: EksOptimizedImageProps) {
-    this.nodeType = props && props.nodeType;
-    this.kubernetesVersion = props && props.kubernetesVersion || LATEST_KUBERNETES_VERSION;
+  public constructor(props: EksOptimizedImageProps = { }) {
+    this.nodeType = props.nodeType ?? NodeType.STANDARD;
```
Comment (eladb) [inline packages/@aws-cdk/aws-eks/lib/cluster.ts:963]: @pahud I piggy backed on your PR to fix another issue related to `EksOptimizedImage` (#6891). Can I bug you to add a unit test for this?

Comment (pahud) [reply packages/@aws-cdk/aws-eks/lib/cluster.ts:963]: Sure! One more thing - as the default cluster creation now goes to 1.15 as the default k8s version. Are we going to change `LATEST_KUBERNETES_VERSION` to 1.15 or just keep it as is(1.14)?

https://github.com/aws/aws-cdk/blob/307c8b021d5c00c1d675f4ce3cba8004a6a4a0a8/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L1018-L1019

Comment (pahud) [reply packages/@aws-cdk/aws-eks/lib/cluster.ts:963]: I was running the integ testing.

Now as the default version goes to `1.15`, the managed nodegroup AMI goes to 1.15

AMI ID **amazon-eks-node-1.15-v20200228 (ami-06abd5347585f6519)**

and the self-managed AMI will goes to `1.14` because of the `LATEST_KUBERNETES_VERSION`

AMI ID **amazon-eks-node-1.14-v20200423 (ami-0bc4f8babcbafed56)**

Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster.ts:963]: I think we should not offer a default Kubernetes version and require that version always be explicitly set. The current behavior is not sustainable 

Let’s do it in a separate PR though.
