### PR TITLE
fix(batch): remove default optimal for arm based instance types and add error checks

### LINKED ISSUE #31148: aws-cdk/aws-batch: Skip use of optimal instance type with graviton instances
### Describe the bug

I'm attempting to create an EC2 ECS compute environment using the AWS Batch constructs that makes use of only Graviton instances. When I deploy the stack I get the following error:

```bash
Error executing request, Exception : arm-based instance type cannot be used with other instance types.
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

When encountering a know arm-based instance class, the construct should not append `optimal` as it's [not supported for arm based instances](https://docs.aws.amazon.com/batch/latest/userguide/compute_environment_parameters.html#compute_environment_compute_resources)

### Current Behavior

When deploying a EC2 ECS Compute Environment, the error below is thrown.

```bash
14:57:17 | CREATE_FAILED        | AWS::Batch::ComputeEnvironment | MyECSComputeEnvironment6A03089C
Resource handler returned message: "Error executing request, Exception : arm-based instance type cannot be used with other instance types., RequestId: 167a0e5
f-0376-4ad4-a0b6-34a85a940cb7 (Service: Batch, Status Code: 400, Request ID: 167a0e5f-0376-4ad4-a0b6-34a85a940cb7)" (RequestToken: d266edf5-f5cd-d61f-866f-5e5
ecefa478c, HandlerErrorCode: InvalidRequest)
```

### Reproduction Steps

I'm declaring my compute environment as follows:

```typescript
const computeEnvironment = new ManagedEc2EcsComputeEnvironment(this, 'MyECSComputeEnvironment', {
    vpc,
    minvCpus: 0,
    maxvCpus: 8,
    instanceClasses: [InstanceClass.M6G],
})
```

When deploying there is an error: 

```bash
14:57:17 | CREATE_FAILED        | AWS::Batch::ComputeEnvironment | MyECSComputeEnvironment6A03089C
Resource handler returned message: "Error executing request, Exception : arm-based instance type cannot be used with other instance types., RequestId: 167a0e5
f-0376-4ad4-a0b6-34a85a940cb7 (Service: Batch, Status Code: 400, Request ID: 167a0e5f-0376-4ad4-a0b6-34a85a940cb7)" (RequestToken: d266edf5-f5cd-d61f-866f-5e5
ecefa478c, HandlerErrorCode: InvalidRequest)
```

### Possible Solution

When I inspect the synthesized CloudFormation Stack I can see that `optimal` has been appended to the `InstanceTypes` list:

image

Possible solution would be to fix logic in [renderInstances](https://github.com/aws/aws-cdk/blob/c1c800e33dd19fc2cc18c943a94760483114c413/packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts#L1134) to take into account the types of instances (Arm vs AMD).

## Workaround

I've found workaround by setting the `useOptimalInstanceClasses` to `false` but this is not expected behavior because I've explicitly set the types of instances I want.

```ts
const computeEnvironment = new ManagedEc2EcsComputeEnvironment(this, 'MyECSComputeEnvironment', {
    vpc,
    minvCpus: 0,
    maxvCpus: 8,
    instanceClasses: [InstanceClass.M6G],
    useOptimalInstanceClasses: false
})
```

### CDK CLI Version

2.152.0 (build faa7d79)

### Framework Version

_No response_

### Node.js Version

v20.14.0

### OS

ubuntu

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by 1kaileychen**
### Issue # (if applicable)

Closes #31148

### Reason for this change
When adding an arm-based instance, optimal instance is set by default which consists of an x86-based instance. This causes errors since arm and x86 instances can't be mixed together.

### Description of changes
- useOptimalInstanceClasses is set to false for all arm-based instances
- Throws error when trying to mix x86 and arm instances
  - Case 1: Instantiating the class
  - Case 2: addInstanceClass and addInstanceType functions
- Warning useOptimalInstanceClasses is being set to false for arm-based instances

### Description of how you validated changes
- Unit test where optimal doesn't get added for arm-based instances
- Unit tests to display errors when instantiating the class
- Unit tests to display errors when addInstanceClass and addInstanceType is adding mixed instances
- Unit tests to display warning for arm based instances

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts [hunk 1]
```diff
@@ -1131,15 +1141,61 @@ export class FargateComputeEnvironment extends ManagedComputeEnvironmentBase imp
...
+    }
   }
+
+  if (hasArmInstances && hasX86Instances) {
+    throw new Error('Cannot mix ARM and x86 instance types or classes');
+  }
+
+  if (hasArmInstances && (useOptimalInstanceClasses || useOptimalInstanceClasses === undefined)) {
+    Annotations.of(scope).addWarningV2('@aws-cdk/aws-batch:optimalNotSupportedWithARM', '\'optimal\' instance types are not supported with ARM instance types or classes, setting useOptimalInstanceClasses to false');
+    useOptimalInstanceClasses = false;
```
Comment (shikha372) [inline packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts:1196]: are we changing the value here, i don't think we should modify it just throw a warning to let users know and prompt them to set it if its undefined

File: packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts [hunk 2]
```diff
@@ -1131,15 +1141,61 @@ export class FargateComputeEnvironment extends ManagedComputeEnvironmentBase imp
...
+    const tempInstanceType = new ec2.InstanceType(`${instanceClass.toString()}.large`);
+    if (tempInstanceType.architecture === ec2.InstanceArchitecture.ARM_64) {
+      hasArmInstances = true;
+    } else {
+      hasX86Instances = true;
+    }
   }
+
+  if (hasArmInstances && hasX86Instances) {
+    throw new Error('Cannot mix ARM and x86 instance types or classes');
```
Comment (shikha372) [inline packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts:1191]: let's fallback to the warning here as well instead of error

File: packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts (hunk 1 above)
Comment (1kaileychen) [reply packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts:1196]: My reasoning for modifying `useOptimalInstanceClasses` is because if we don't change the value, the error when deploying would occur. There's actually no case where useOptimalInstanceClasses can be True and there are arm instances like pahud mentioned `if instanceClasses is defined as all arm instance types, useOptimalInstanceClasses has to be false`. I believe it would make sense in this case to change it for the user since that's the only option. Let me know if you think it still makes more sense for just the warning!

File: packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts (hunk 2 above)
Comment (1kaileychen) [reply packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts:1191]: If we don't throw the error here, there will be an error when deploying which is the error shown in the original issue. Just making sure, would we only want a warning even though there will be an error deploying?

Comment (shikha372) [reply packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts:1191]: yeah, i think i also was leaning towards throwing but since it affects both EC2 and EKS environment, want to be cautious in not causing regression with unexpected failures for existing customers but still keeping the validation to let them know about the expected behaviour beforehand, to confirm i did check the documentation , we can add it above the validation for future reference. 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-computeenvironment-computeresources.html#cfn-batch-computeenvironment-computeresources-instancetypes

File: packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts (hunk 1 above)
Comment (shikha372) [reply packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts:1196]: true, but we are kind of changing the field so if we want to do this i would say we might need to add feature flag, since we're kind of modifying the default behaviour now with setting it to `false` which i also agree is correct in this case, don;t want it to be intrusive for existing customers.

File: packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts (hunk 2 above)
Comment (1kaileychen) [reply packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts]: Updated here: [016a89a](https://github.com/aws/aws-cdk/pull/31510/commits/016a89a18ec4efba9f8d2d2d2a2f219419a913d1)!

File: packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts (hunk 1 above)
Comment (1kaileychen) [reply packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts]: Updated here: [e4b2864](https://github.com/aws/aws-cdk/pull/31510/commits/e4b286430863f31516705eaa22b1632ec3e8e5e9)!

**Review by shikha372 — APPROVED** [review]

**Comment by shikha372** [comment]
Marking it as do not merge for confirming test changes
