### PR TITLE
fix(lambda): failed to add permission to an imported lambda from another account

### LINKED ISSUE #11141: [lambda] CDK tries to add permission to an imported lambda in another account
We have an API Gateway (LambdaRestApi) that uses an authorization lambda, in version 1.68.0 and above of the packages it tries to add a lambda:InvokeFunction permission in the account where the authorization lambda is. But the role we're deploying with has no access to that account. In versions below 1.68.0 it doesn't try to add this permission.

What I get when running `cdk diff` with v1.68.0 and above.
image

When I run `cdk diff` with v1.67.0 or below I get "There were no differences".
 
We get the authorization lambda using the `Function.FromFunctionArn`-method.

### Reproduction Steps

1. Create an API GW in one account using an authorization lambda that exists in a different account.
2. CDK tries to add permission in the account where the authorization lambda is.

### What did you expect to happen?

I expected it to work as in versions below 1.68.0, where CDK don't try to add resources in a different account.

### What actually happened?

CDK tries to add resources in the wrong account.

### Environment

  - **CLI Version      :1.70.0 (build c145314)**
  - **Framework Version: .NET Core 3.1**
  - **Node.js Version: v14.12.0** 
  - **OS               : Windows 10**
  - **Language (Version): .NET Core 3.1** 

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by nija-at**
Originally, when a function was imported into an account agnostic stack,
it was assumed that the function was from a different account and hence
its permission cannot be modified.

A subsequent change - 99111f72adc210f48e269db50f2b8e8b78d21252 - changed
this behaviour to its opposite. When an account agnostic stack was
encountered in the context of an imported function, it was assumed that
the function was part of the same account.
This has caused customers to report regressions - #11278, #11141.

This change reverts this behaviour back to its original assumption, with
the additional ability to configure this explicitly by the user if
needed for an advanced use case.

fixes #11141

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-lambda/lib/function-base.ts [hunk 1]
```diff
@@ -149,6 +149,17 @@ export interface FunctionAttributes {
...
+  /**
+   * Setting this property informs the CDK that permissions can be added to this function.
+   * When not configured, the CDK attempts to auto-determine this. If determined as false, adding permission
+   * to this function will fail.
+   *
+   * Set this to property *ONLY IF* the imported function is in the same account as the stack
+   * it's imported in.
+   * @default - true, if the Stack is configured with an `env` and the account is the same as this function. false, otherwise.
+   */
+  readonly allowPermissions?: boolean;
```
Comment (njlynch) [inline packages/@aws-cdk/aws-lambda/lib/function-base.ts:162]: `~` `allowPermissions` doesn't quite read right to me. Maybe `allowCreatingPermissions` or `canCreatePermissions` (like the internal field)?

**Review by njlynch — COMMENTED** [review]
I feel like the error message in `grantInvoke` should be updated to reflect this, as we're going to break (other) existing customers with this revert. 

Also wouldn't mind a second set of eyes here.

File: packages/@aws-cdk/aws-lambda/lib/function-base.ts (hunk 1 above)
Comment (eladb) [reply packages/@aws-cdk/aws-lambda/lib/function-base.ts:162]: I agree that the name is not ideal.

What is the user intent here? Is the intent to block/forbid or to enable some behavior despite the default?

**Review by eladb — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-lambda/lib/function-base.ts (hunk 1 above)
Comment (nija-at) [reply packages/@aws-cdk/aws-lambda/lib/function-base.ts:162]: It is to enable a behaviour despite the default. Any suggestions?

Comment (nija-at) [reply packages/@aws-cdk/aws-lambda/lib/function-base.ts:162]: Specifically to enable the ability to modify permissions of an imported function.

Comment (eladb) [reply packages/@aws-cdk/aws-lambda/lib/function-base.ts:162]: Modify permissions for an imported function in environment agnostic stacks?

Would it make sense that this will be named something like `assumeSameEnvironment`?

Comment (nija-at) [reply packages/@aws-cdk/aws-lambda/lib/function-base.ts:162]: I don't mind calling it that. This is going to be a rarely used property with no way to easily describe it via a name, so I'm not fussed.

File: packages/@aws-cdk/aws-lambda/test/function.test.ts [hunk 2]
```diff
@@ -269,6 +269,24 @@ describe('function', () => {
...
+
+    test('imported Function w/ unresolved account & allowPermissions set', () => {
+      // GIVEN
+      const app = new cdk.App();
+      const stack = new cdk.Stack(app, 'Imports');
+
+      // WHEN
+      const iFunc = lambda.Function.fromFunctionAttributes(stack, 'iFunc', {
+        functionArn: 'arn:aws:lambda:us-east-1:123456789012:function:BaseFunction',
+        allowPermissions: true,
```
[the remark this answers is not in the document]
Comment (nija-at) [reply packages/@aws-cdk/aws-lambda/test/function.test.ts:284]: No, it's not. It's false since the stack is env agnostic.

File: packages/@aws-cdk/aws-lambda/lib/function-base.ts (hunk 1 above)
Comment (eladb) [reply packages/@aws-cdk/aws-lambda/lib/function-base.ts]: I think `sameEnvironment` is actually better because the default is conditional

File: packages/@aws-cdk/aws-lambda/test/function.test.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/aws-lambda/test/function.test.ts]: Got it. Add a comment.

File: packages/@aws-cdk/aws-lambda/lib/function-base.ts [hunk 3]
```diff
@@ -149,6 +149,18 @@ export interface FunctionAttributes {
...
+
+  /**
+   * Setting this property informs the CDK that the imported function is in the same environment as the stack.
+   * This affects certain behaviours such as, whether this function's permission can be modified.
+   * When not configured, the CDK attempts to auto-determine this. For environment agnostic stacks, i.e., stacks
+   * where the account is not specified with the `env` property, this is determined to be false.
+   *
+   * Set this to property *ONLY IF* the imported function is in the same account as the stack
+   * it's imported in.
+   * @default - true, if the Stack is configured with an `env` and the account is the same as this function. false, otherwise.
```
Comment (eladb) [inline packages/@aws-cdk/aws-lambda/lib/function-base.ts:161]:
```suggestion
   * @default - depends: true if the Stack is configured with an explicit `env` (account and region), and the account is the same as this function. For environment-agnostic stacks this will default to `false`, indicating that permissions cannot be added to this function.
```

**Review by eladb — APPROVED** [review]
