### PR TITLE
fix(codepipeline-actions): use token as CodeCommitSourceAction branch

### LINKED ISSUE #10263: [codepipeline-actions] Can't use a token for branchName in CodeCommitAction
If a token (e.g. a CfnParameter value) is used to define the branchName of the CodeCommit Repository in a CodeCommitAction, synthesis fails with:

```
Cannot use tokens in construct ID: <PipelineId>-${Token[TOKEN.192]}-EventRule
```

### Reproduction Steps

```
import { Stack, Construct, StackProps, CfnParameter } from '@aws-cdk/core';
import { Pipeline, Artifact } from '@aws-cdk/aws-codepipeline';
import { CodeCommitSourceAction } from '@aws-cdk/aws-codepipeline-actions';
import { Repository } from '@aws-cdk/aws-codecommit';

export default class FailingPipelineStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const branchName = new CfnParameter(this, 'BranchName', {
      type: 'String',
    });

    const repo = new Repository(this, 'Repository', {
      repositoryName: 'the-repository',
    });

    new Pipeline(this, 'FailingPipeline', {
      stages: [{
        stageName: 'source',
        actions: [
          new CodeCommitSourceAction({
            actionName: 'readSource',
            output: new Artifact('artifact'),
            repository: repo,
            branch: branchName.valueAsString,
          }),
        ],
      }],
    });
  }
}
```

### What did you expect to happen?

Stack is synthesised correctly.

### What actually happened?

Stack fails to synthesise with error:

``` 
Cannot use tokens in construct ID: DeploymentPipeline145A2410-${Token[TOKEN.192]}-EventRule
```

### Environment

  - **CLI Version      : 1.62.0**
  - **Framework Version:**
  - **Node.js Version: 12.18.3** 
  - **OS               : Linux (Debian Buster in Docker)**
  - **Language (Version): Typescript 3.9.7** 

### Other

I notice that the cause of this is during `SourceAction.bound()`:
```
if (createEvent) {
    const branchIdDisambiguator = this.branch === 'master' ? '' : `-${this.branch}-`;
    this.props.repository.onCommit(`${stage.pipeline.node.uniqueId}${branchIdDisambiguator}EventRule`, {
        target: new targets.CodePipeline(stage.pipeline),
        branches: [this.branch],
    });
}
```

`this.branch` should probably be checked to see if it's a usuable value (i.e. not a token) and if it is unusable as an ID, a random value created.

The workaround is to set `trigger: CodeCommitTrigger.NONE` and create my own cloudtrail trigger.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by alanraison**
When using the EVENTS trigger, an event is created based on the branch name of 
the event, however this is not possible if the branch name is an unresolved
value. Therefore generate a unique event name if this is the case.

Fixes #10263

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-codepipeline-actions/lib/codecommit/source-action.ts [hunk 1]
```diff
@@ -153,4 +153,23 @@ export class CodeCommitSourceAction extends Action {
...
+      while (this.props.repository.node.tryFindChild(candidate) !== undefined) {
+        counter += 1;
+        candidate = `${baseId}-Branch${counter}-`;
+      }
+      branchIdDisambiguator = candidate;
+    } else {
+      branchIdDisambiguator = `${baseId}-${this.branch}-`;
+    }
+    return `${branchIdDisambiguator}EventRule`;
+  }
```
Comment (skinny85) [inline packages/@aws-cdk/aws-codepipeline-actions/lib/codecommit/source-action.ts:174]: I have a hard time keeping up with this code. For example, `branchIdDisambiguator` sounds to me like it should be just the branch-changing part of the ID, but somehow it's the entire thing.

What do you think of this instead?

```suggestion
  private generateEventId(stage: codepipeline.IStage): string {
    const baseId = stage.pipeline.node.uniqueId;
    if (Token.isUnresolved(this.branch)) {
      let candidate = '';
      let counter = 0;
      do {
        candidate = this.eventIdFromPrefix(`${baseId}-${counter}`);
        counter += 1;
      } while (this.props.repository.node.tryFindChild(candidate) !== undefined);
      return candidate;
    } else {
      const branchIdDisambiguator = this.branch === 'master' ? '' : '-${this.branch}-';
      return this.eventIdFromPrefix(`${baseId}${branchIdDisambiguator}`);
    }
  }
  
  private eventIdFromPrefix(eventIdPrefix: string) {
    return `${eventIdPrefix}EventRule`;
  }
```

(Notice the different loop; the current one actually checks the wrong ID, without the `EvenRule` suffix!)

File: packages/@aws-cdk/aws-codepipeline-actions/test/codecommit/test.codecommit-source-action.ts [hunk 2]
```diff
@@ -224,6 +224,51 @@ export = {
...
+      p.addStage({
+        stageName: 'Build',
+        actions: [
+          new cpactions.CodeBuildAction({
+            actionName: 'Build',
+            project: new codebuild.PipelineProject(stack, 'CodeBuild'),
+            input: artifact,
+          }),
+        ],
+      });
```
Comment (skinny85) [inline packages/@aws-cdk/aws-codepipeline-actions/test/codecommit/test.codecommit-source-action.ts:260]: Gotta say, not a hue fan of these one-letter variable names 🙂. Do we actually need them for anything? Can't we do the setup in one expression?

```suggestion
      const sourceOutput = new codepipeline.Artifact();
      new codepipeline.Pipeline(stack, 'P', {
        stages: [
          {
            stageName: 'Source',
            actions: [
              new cpactions.CodeCommitSourceAction({
                actionName: 'CodeCommit',
                repository: new codecommit.Repository(stack, 'R', {
                  repositoryName: 'repository',
                }),
                branch: Lazy.stringValue({ produce: () => 'my-branch' }),
                output: sourceOutput,
              }),
            ],
          },
          {
            stageName: 'Build',
            actions: [
              new cpactions.CodeBuildAction({
                actionName: 'Build',
                project: new codebuild.PipelineProject(stack, 'CodeBuild'),
                input: sourceOutput,
              }),
            ],
          },
        ],
      });
```

File: packages/@aws-cdk/aws-codepipeline-actions/test/codecommit/test.codecommit-source-action.ts [hunk 3]
```diff
@@ -224,6 +224,51 @@ export = {
...
+
+      expect(stack).to(haveResourceLike('AWS::Events::Rule', {
+        EventPattern: {
+          detail: {
+            referenceName: [stack.resolve(branch)],
```
Comment (skinny85) [inline packages/@aws-cdk/aws-codepipeline-actions/test/codecommit/test.codecommit-source-action.ts:265]: Or just

```suggestion
            referenceName: ['my-branch'],
```

🙂

**Review by skinny85 — CHANGES_REQUESTED** [review]
Thanks for the PR @alanraison ! There's a bug lurking in the current proposal, so we need to address it before merging it in 🙂

File: packages/@aws-cdk/aws-codepipeline-actions/lib/codecommit/source-action.ts (hunk 1 above)
Comment (alanraison) [reply packages/@aws-cdk/aws-codepipeline-actions/lib/codecommit/source-action.ts:174]: Oops, thanks for spotting that! I think that your naming scheme with the counter needs a slight tweak though, so I will just update my branch with that.

**Review by skinny85 — APPROVED** [review]
Thanks for the fix @alanraison !

**Review by skinny85 — APPROVED** [review]

File: packages/@aws-cdk/aws-codepipeline-actions/lib/codecommit/source-action.ts (hunk 1 above)
Comment (geduld) [reply packages/@aws-cdk/aws-codepipeline-actions/lib/codecommit/source-action.ts]: @skinny85 This might include a bug:

```typescript
# Use buckticks instead
'-${this.branch}-' => `-${this.branch}-`
```
