### PR TITLE
fix(agentcore): `addToRolePolicy` for runtime with imported role destroys and recreates policies on every deployment

### LINKED ISSUE #35844: (agentcore): `addToRolePolicy` for runtime with imported role destroys and recreates policies on every deployment
### Describe the bug

The current `addToRolePolicy` for Runtime with imported role destroys and recreates policies on every deployment.

The reason is that `Date.now()` is used for a construct ID of a new Policy in the situation:

https://github.com/aws/aws-cdk/blob/v2.221.0/packages/%40aws-cdk/aws-bedrock-agentcore-alpha/agentcore/runtime/runtime-base.ts#L253

```ts
  public addToRolePolicy(statement: iam.PolicyStatement): IBedrockAgentRuntime {
    // Check if role is a concrete Role instance
    if (this.role instanceof iam.Role) {
      this.role.addToPolicy(statement);
    } else {
      // For imported roles (IRole), we need to attach via a new policy
      const policy = new iam.Policy(this, `CustomPolicy${Date.now()}`, {
        statements: [statement],
      });
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Library Version

_No response_

### Expected Behavior

The diff will not occur.

### Current Behavior

The diff will occur and destroy / recreate the policies.

### Reproduction Steps

1. Deploy your stack with the following CDK code:

```ts
const app = new cdk.App();
const stack = new cdk.Stack(app, 'aws-cdk-bedrock-agentcore-runtime-with-imported-role');

const runtimeArtifact = agentcore.AgentRuntimeArtifact.fromAsset(
  path.join(__dirname, 'testArtifact'),
);

const role = new iam.Role(stack, 'ExecutionRole', {
  assumedBy: new iam.ServicePrincipal('bedrock-agentcore.amazonaws.com'),
});
const imported = iam.Role.fromRoleArn(stack, 'ImportedRole', role.roleArn);

const runtime = new agentcore.Runtime(stack, 'TestRuntime', {
  runtimeName: 'integ_test_runtime',
  agentRuntimeArtifact: runtimeArtifact,
  executionRole: imported,
});

runtime.addToRolePolicy(new iam.PolicyStatement({
  actions: ['dynamodb:Query'],
  resources: ['arn:aws:dynamodb:us-east-1:123456789012:table/my-table'],
}));
```

2. Deploy or diff the stack with the same CDK code again.

3. The change will occur:

```
      [-] AWS::IAM::Policy TestRuntimeCustomPolicy1761380931769044921D2 destroy
      [+] AWS::IAM::Policy TestRuntimeCustomPolicy1761381522330E0DC0D40
```

### Possible Solution

Add a policy counter and change the construct ID with the counter:

```ts
  /**
   * Counter for policies attached to imported roles
   * @internal
   */
  private _policyCounter: number = 0;
```

```diff
    } else {
      // For imported roles (IRole), we need to attach via a new policy
-      const policy = new iam.Policy(this, `CustomPolicy${Date.now()}`, {
+      const policy = new iam.Policy(this, `CustomPolicy${this._policyCounter++}`, {
        statements: [statement],
      });
```

The approach has already been used in lambda:

- https://github.com/aws/aws-cdk/blob/v2.221.0/packages/aws-cdk-lib/aws-lambda/lib/function-base.ts#L331
- https://github.com/aws/aws-cdk/blob/v2.221.0/packages/aws-cdk-lib/aws-lambda/lib/function-base.ts#L432

### Additional Information/Context

_No response_

### AWS CDK Library version (aws-cdk-lib)

v2.221.0

### AWS CDK CLI version

2.1030.0

### Node.js Version

v22.14.0

### OS

Mac

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by go-to-k**
### Issue # (if applicable)

Closes #35844

### Reason for this change

The current `addToRolePolicy` for Runtime with imported role destroys and recreates policies on every deployment.

The reason is that `Date.now()` is used for a construct ID of a new Policy in the situation:

https://github.com/aws/aws-cdk/blob/v2.221.0/packages/%40aws-cdk/aws-bedrock-agentcore-alpha/agentcore/runtime/runtime-base.ts#L253

```ts
  public addToRolePolicy(statement: iam.PolicyStatement): IBedrockAgentRuntime {
    // Check if role is a concrete Role instance
    if (this.role instanceof iam.Role) {
      this.role.addToPolicy(statement);
    } else {
      // For imported roles (IRole), we need to attach via a new policy
      const policy = new iam.Policy(this, `CustomPolicy${Date.now()}`, {
        statements: [statement],
      });
```

#### Reproduction

1. Deploy your stack with the following CDK code:

```ts
const app = new cdk.App();
const stack = new cdk.Stack(app, 'aws-cdk-bedrock-agentcore-runtime-with-imported-role');

const runtimeArtifact = agentcore.AgentRuntimeArtifact.fromAsset(
  path.join(__dirname, 'testArtifact'),
);

const role = new iam.Role(stack, 'ExecutionRole', {
  assumedBy: new iam.ServicePrincipal('bedrock-agentcore.amazonaws.com'),
});
const imported = iam.Role.fromRoleArn(stack, 'ImportedRole', role.roleArn);

const runtime = new agentcore.Runtime(stack, 'TestRuntime', {
  runtimeName: 'integ_test_runtime',
  agentRuntimeArtifact: runtimeArtifact,
  executionRole: imported,
});

runtime.addToRolePolicy(new iam.PolicyStatement({
  actions: ['dynamodb:Query'],
  resources: ['arn:aws:dynamodb:us-east-1:123456789012:table/my-table'],
}));
```

2. Deploy or diff the stack with the same CDK code again.

3. The change will occur:

```
      [-] AWS::IAM::Policy TestRuntimeCustomPolicy1761380931769044921D2 destroy
      [+] AWS::IAM::Policy TestRuntimeCustomPolicy1761381522330E0DC0D40
```

### Description of changes

Use `addToPrincipalPolicy` directly instead.

### Description of how you validated changes

Both unit tests and an integ test.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-bedrock-agentcore-alpha/agentcore/runtime/runtime-artifact.ts [hunk 1]
```diff
@@ -50,6 +51,37 @@ export abstract class AgentRuntimeArtifact {
...
+   * Add any missing policy dependencies to the runtime resource.
+   *
+   * This ensures the Runtime waits for the policies (including ECR permissions) to be created.
+   * While the Runtime constructor already adds dependencies to the policies and their role, in the case
+   * where the role is imported, the policies are not yet generated in the role at that point, so the policy
+   * dependencies are not added. Therefore, this method explicitly adds the policy dependencies.
+   *
+   * @internal
+   */
+  protected _addMissingPolicyDependencies(runtime: Runtime) {
```
Comment (go-to-k) [inline packages/@aws-cdk/aws-bedrock-agentcore-alpha/agentcore/runtime/runtime-artifact.ts]: Permissions for ECR must be attached to the role before the Runtime is created. Otherwise, deployment will fail.

```
ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: Access denied while validating ECR URI '123456789012.dkr.ecr.us-east-1.amazonaws.com/cdk-hnb659fds-container-assets-123456789012-us-east-1:abcdefghijklmn'. The execution role requires permissions for ecr:GetAuthorizationToken, ecr:BatchGetImage, and ecr:GetDownloadUrlForLayer operations. (Service: BedrockAgentCoreControl, Status Code: 400, Request ID: 123456-1234-1234-a5d6-9deae6db742d) (SDK Attempt Count: 1)" (RequestToken: 123456-1234-1234-8044-7e188d566e8d, HandlerErrorCode: InvalidRequest)
```

Actually, this is already handled in the Runtime's constructor with `this.runtimeResource.node.addDependency(this.role)` (see: https://github.com/aws/aws-cdk/blob/v2.221.0/packages/%40aws-cdk/aws-bedrock-agentcore-alpha/agentcore/runtime/runtime.ts#L299-L301), but it doesn't work for the policies in the case where the role is imported. See the code comments for details.

Therefore, in that case, we need to add an explicit dependency on the policies added to the imported role.

FYI: This is triggered via the bind: https://github.com/aws/aws-cdk/blob/v2.221.0/packages/%40aws-cdk/aws-bedrock-agentcore-alpha/agentcore/runtime/runtime.ts#L401

**Review by mazyu36 — APPROVED** [review]

**Review by dineshSajwan — APPROVED** [review]
Thank you @go-to-k .
 LGTM.

File: packages/@aws-cdk/aws-bedrock-agentcore-alpha/agentcore/runtime/runtime-base.ts [hunk 2]
```diff
@@ -250,7 +256,7 @@ export abstract class RuntimeBase extends Resource implements IBedrockAgentRunti
       this.role.addToPolicy(statement);
     } else {
       // For imported roles (IRole), we need to attach via a new policy
-      const policy = new iam.Policy(this, `CustomPolicy${Date.now()}`, {
+      const policy = new iam.Policy(this, `CustomPolicy${this._policyCounter++}`, {
         statements: [statement],
       });
       this.role.attachInlinePolicy(policy);
```
Comment (Abogical) [inline packages/@aws-cdk/aws-bedrock-agentcore-alpha/agentcore/runtime/runtime-base.ts]: There is no need to create a new `Policy`object, just use `addtoPrincipalPolicy()`
```suggestion
      this.role.addToPrincipalPolicy(statement);
```

**Review by Abogical — DISMISSED** [review]

File: packages/@aws-cdk/aws-bedrock-agentcore-alpha/agentcore/runtime/runtime-base.ts (hunk 2 above)
Comment (go-to-k) [reply packages/@aws-cdk/aws-bedrock-agentcore-alpha/agentcore/runtime/runtime-base.ts]: Summarized it like this. Many other Constructs are done this way. How about it?

```diff
  public addToRolePolicy(statement: iam.PolicyStatement): IBedrockAgentRuntime {
-    // Check if role is a concrete Role instance
-    if (this.role instanceof iam.Role) {
-      this.role.addToPolicy(statement);
-    } else {
-      // For imported roles (IRole), we need to attach via a new policy
-      const policy = new iam.Policy(this, `CustomPolicy${Date.now()}`, {
-        statements: [statement],
-      });
-      this.role.attachInlinePolicy(policy);
-    }
+    this.role.addToPrincipalPolicy(statement);
    return this;
  }
```

**Review by Abogical — COMMENTED** [review]
Thanks! I have asked for a security review for this.

**Review by Abogical — DISMISSED** [review]

**Review by gasolima — DISMISSED** [review]

**Review by Abogical — APPROVED** [review]

**Comment by Abogical** [comment]
@mergifyio rebase

**Comment by go-to-k** [comment]
@Mergifyio update

**Comment by go-to-k** [comment]
@Mergifyio update

**Comment by Abogical** [comment]
@mergifyio requeue
