### PR TITLE
fix(vpc): typo VPC Endpoint Payment Cryptography

### LINKED ISSUE #33017: ec2: InterfaceEndpointTypo PAYMENT_CRYTOGRAPHY_DATAPLANE
https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts#L524

PAYMENT_CRYTOGRAPHY_DATAPLANE => PAYMENT_CRYPTOGRAPHY_DATAPLANE

### PR DESCRIPTION
**Pull request by Dringho**
### Issue # (if applicable)
https://github.com/aws/aws-cdk/issues/33017

Closes #33017.

### Reason for this change

Typo

### Description of changes
Fixed Typo

### Describe any new or updated permissions being added

NA

### Description of how you validated changes

No

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by kaizencc — DISMISSED** [review]
Hi @Dringho! thanks for noticing this! unfortunately we cannot just update the property name because that would be a breaking change....

instead we have to leave this one as is, and deprecate it. we can add a _new_ static property with the correct name. does that make sense?

File: packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts [hunk 1]
```diff
@@ -521,7 +521,7 @@ export class InterfaceVpcEndpointAwsService implements IInterfaceVpcEndpointServ
   public static readonly PARALLEL_COMPUTING_SERVICE = new InterfaceVpcEndpointAwsService('pcs');
   public static readonly PARALLEL_COMPUTING_SERVICE_FIPS = new InterfaceVpcEndpointAwsService('pcs-fips');
   public static readonly PAYMENT_CRYPTOGRAPHY_CONTROLPLANE = new InterfaceVpcEndpointAwsService('payment-cryptography.controlplane');
-  public static readonly PAYMENT_CRYTOGRAPHY_DATAPLANE = new InterfaceVpcEndpointAwsService('payment-cryptography.dataplane');
+  public static readonly PAYMENT_CRYPTOGRAPHY_DATAPLANE = new InterfaceVpcEndpointAwsService('payment-cryptography.dataplane');
```
Comment (aaythapa) [inline packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts:524]:
```suggestion
  /** @deprecated - Use InterfaceVpcEndpointAwsService.PAYMENT_CRYPTOGRAPHY_DATAPLANE instead. */
  public static readonly PAYMENT_CRYTOGRAPHY_DATAPLANE = new InterfaceVpcEndpointAwsService('payment-cryptography.dataplane');
  public static readonly PAYMENT_CRYPTOGRAPHY_DATAPLANE = new InterfaceVpcEndpointAwsService('payment-cryptography.dataplane');
```

**Comment by aaythapa** [comment]
@mergify update

**Review by aaythapa — APPROVED** [review]

**Comment by aaythapa** [comment]
@mergify update

**Comment by aaythapa** [comment]
@mergify requeue

**Comment by aaythapa** [comment]
@mergify update

**Comment by aaythapa** [comment]
@mergifyio requeue

**Comment by mrgrain** [comment]
@mergifyio requeue

**Comment by mrgrain** [comment]
@mergifyio dequeue

**Comment by mrgrain** [comment]
Dequeued again because build is failing.

**Comment by aaythapa** [comment]
@mergify update

**Comment by aaythapa** [comment]
@mergify requeue

**Review by moelasmar — APPROVED** [review]
