### PR TITLE
fix(codebuild): ARM images have the wrong type and compute kind

### LINKED ISSUE #5517: Can't Override BuildEnvironment.type to "ARM_CONTAINER"
There is no way to set the BuildEnvironment type setting so that you can set environment type to ARM_CONTAINER and use an ARM based build container, even when you set the build image to the ARM container.

### Reproduction Steps

```
from aws_cdk import core
from aws_cdk import aws_codebuild as codebuild
from aws_cdk import aws_s3 as s3
from aws_cdk import aws_efs as efs_
from aws_cdk import aws_ec2 as ec2


class PipelineStack(core.Stack):
    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        vpc = ec2.Vpc.from_lookup(self, "vpc", vpc_name="xxxxxxx-VPC")
        privateSubnets = vpc.private_subnets
        securityGroup = ec2.SecurityGroup.from_security_group_id(
            self, "sg", security_group_id='sg-xxxxxxxx'
        )

        efs = efs_.CfnFileSystem(
            self,
            "codebuildFS",
            encrypted=False,
            performance_mode="generalPurpose",
            throughput_mode="bursting",
        )

        efs_dns = efs.ref + "efs.us-east-2.amazonaws.com"

        mounts = []
        for subnet in privateSubnets:
            mounts.append(efs_.CfnMountTarget(
                self,
                "Mount-" + subnet.subnet_id,
                file_system_id=efs.ref,
                security_groups=[securityGroup.security_group_id],
                subnet_id=subnet.subnet_id,
            ))

        # The code that defines your stack goes here
        github_source = codebuild.Source.git_hub(
            owner="canada4663",
            repo=id,
            webhook=True,  # optional, default: true if `webhookFilteres` were provided, false otherwise
            webhook_filters=[
                codebuild.FilterGroup.in_event_of(
                    codebuild.EventAction.PUSH
                ).and_branch_is("master")
            ],
        )

        artifact_bucket = s3.Bucket(self, id + "-bucket")

        build_env = codebuild.BuildEnvironment(
            privileged=True,
            build_image=codebuild.LinuxBuildImage.AMAZON_LINUX_2_ARM,
        )
        build_env.type='ARM_CONTAINER' ##can't override here

        env_vars = {
            "EFS_DIR": codebuild.BuildEnvironmentVariable(value="/efs"),
            "EFS_DNS": codebuild.BuildEnvironmentVariable(value=efs_dns)
        }

        build = codebuild.Project(
            self,
            id + "-project",
            project_name=id,
            source=github_source,
            environment=build_env,
            environment_variables=env_vars,
            cache=codebuild.Cache.bucket(artifact_bucket),
            vpc=vpc,
            security_groups=[securityGroup],
        )
```

### Error Log

```
SINGLE_BUILD_CONTAINER_DEAD: Build container found dead before completing the build. Build container died because it was out of memory, or the Docker image is not supported
```

Upon inspecting the console, it is using the LINUX_CONTAINER instance sizes for ComputeType: BUILD_GENERAL1_LARGE - 15GB and 8vCPU, instead of 16GB and 8vCPU

When inspecting the [underlying code](https://github.com/aws/aws-cdk/blob/f10b3e64feab9c9ccc78c9820dc99a8b6b0971ec/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L1273) you can see that type is hardcoded to "LINUX_CONTAINER" and there is no way to override it.

### Environment

  - **CLI Version      :** 1.19
  - **Framework Version:** 1.19
  - **OS               :** Ubuntu Linux on Host Machine
  - **Language         :** Python

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by skinny85**
As it turns out, ARM images require specifying a different type than Linux images. They also only work with `ComputeType.LARGE`. Add a new, module-private, class of `IBuildImage`, `ArmImage`,
that implements that behavior and validation, and change `LinuxBuildImage.AMAZON_LINUX_2_ARM` to use the new class.

Fixes #5517

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-codebuild/lib/project.ts [hunk 1]
```diff
@@ -1157,9 +1182,12 @@ export class LinuxBuildImage implements IBuildImage {
   public static readonly STANDARD_1_0 = LinuxBuildImage.codeBuildImage('aws/codebuild/standard:1.0');
   public static readonly STANDARD_2_0 = LinuxBuildImage.codeBuildImage('aws/codebuild/standard:2.0');
   public static readonly STANDARD_3_0 = LinuxBuildImage.codeBuildImage('aws/codebuild/standard:3.0');
+
   public static readonly AMAZON_LINUX_2 = LinuxBuildImage.codeBuildImage('aws/codebuild/amazonlinux2-x86_64-standard:1.0');
   public static readonly AMAZON_LINUX_2_2 = LinuxBuildImage.codeBuildImage('aws/codebuild/amazonlinux2-x86_64-standard:2.0');
-  public static readonly AMAZON_LINUX_2_ARM = LinuxBuildImage.codeBuildImage('aws/codebuild/amazonlinux2-aarch64-standard:1.0');
+
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild/lib/project.ts]: Why is the usage of LinuxBuildImage and ArmBuildImage different? One uses a static method and one uses a constructor... lets normalize.

Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: It's because we don't want to expose the fact that `LinuxBuildImage` is the implementation used for methods like `LinuxBuildImage.codeBuildImage()`, `LinuxBuildImage. fromDockerRegistry()`, etc.  - that's why the constructor of `LinuxBuildImage` is private. We don't need to do the same for `ArmBuildImage`, as that entire class is module-private already.

Comment (eladb) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: Sounds good
