### PR TITLE
fix(eks): kubectl resources fail before fargate profiles are created

### LINKED ISSUE #8574: 1.45.0 introduces regression in EKS Cluster creation: Caller does not have permission to perform `iam:listAttachedRolePolicies`
### Reproduction Steps

`new eks.Cluster()`  in 1.45.0.

Works ok in 1.44.0

### Error Log

```
EKSCluster/Resource/Resource/Default (EKSClusterE11008B6) Failed to create resource. Error: Caller does not have permission to perform `iam:listAttachedRolePolicies`
    at invokeUserFunction (/var/task/framework.js:85:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Remote function error: InvalidParameterException: Caller does not have permission to perform `iam:listAttachedRolePolicies`
    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-s
        new CustomResource (/home/doug/projects/trustsrv.io/node_modules/@aws-cdk/core/lib/custom-resource.ts:115:21)
        \_ new ClusterResource (/home/doug/projects/trustsrv.io/node_modules/@aws-cdk/aws-eks/lib/cluster-resource.ts:114:22)
        \_ new Cluster (/home/doug/projects/trustsrv.io/node_modules/@aws-cdk/aws-eks/lib/cluster.ts:406:18)

```

### Environment

  - **CLI Version      :** 1.45.0
  - **Framework Version:** 1.45.0
  - **Node.js Version:** 14.2.0
  - **OS               :** debian
  - **Language (Version):** Typescript 3.7.3

### Other

This is :bug: Bug Report

### LINKED ISSUE #8854: [eks] Kubernetes resources fail to create if fargate profiles are not stable
When trying to deploy `kubectl` resources (such as `KubernetesResource` or `HelmChart`) against an EKS cluster with Fargate Profiles that are still being created, the API server may not be reachable. This causes these resources to to fail, the deployment to roll back and worst of all, as the rollback happens, CFN tries to delete the FargateProfile resources, but they still being creating. Basically leading to unrecoverable situation.

### Environment

  - **CLI Version      :**
  - **Framework Version:** 1.48.0
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by eladb**
When a Fargate profile is being created, the Kubernetes API server in EKS sometimes rejects requests. This means that kubectl-related resources such as KubernetesResources and Helm charts may fail during deployment.

To address this, we add a "barrier resource" (in the form of an SSM parameter) which waits for all fargate profiles to be created before allowing kubectl resources to continue. This is done by the barrier taking a dependency on all FargateProfile resources and all kubectl resources taking a dependency on the barrier.

Fixes #8854

This commit also fixes #8574 by adding `iam:ListAttachedRolePolicies` to the cluster's creation role IAM policy.

---

- [ ] Rebase against master after #8839 is merged

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-eks/lib/cluster.ts [hunk 1]
```diff
@@ -794,33 +820,59 @@ export class Cluster extends Resource implements ICluster {
...
+    }
+
+    // singleton
+    let provider = this.stack.node.tryFindChild(uid) as KubectlProvider;
+    if (!provider) {
+      // create the provider.
+      provider = new KubectlProvider(this.stack, uid);
+
+      // allow the kubectl provider to assume the cluster creation role.
+      this._clusterResource.addTrustedRole(provider.role);
```
Comment (iliapolo) [inline packages/@aws-cdk/aws-eks/lib/cluster.ts:866]: You moved this inside the singleton creation, but won't this mean that if two clusters are defined on the same stack, one of them wont have the trusted role?

Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/cluster.ts:866]: Yes, nice catch! Let me add a test and fix

**Comment by eladb** [comment]
Oops... Accidentally merged this into benisrae/improve-cr-errors.

**Comment by eladb** [comment]
New PR #8859
