### PR TITLE
fix: update all 'onXxx' methods to be CloudWatch Events

### LINKED ISSUE #2278: awslint:events
- [ ] Implement and apply rule **`awslint:events-in-interface`**: All "on" methods should be defined on the cosntruct interface
- [ ] Implement and apply rule **`awslint:events-method-signature`**: All "on" methods should have a signature that complies with the rules
- [ ] Implement and apply rule **`awslint:events-generic`**: A generic "onEvent" method should always be provided

### LINKED ISSUE #2443: Convert all "on" methods that are not CloudWatch events to integrations

### PR DESCRIPTION
**Pull request by rix0rrr**
Make all CloudWatch events methods consistent. All methods called
'onXxx()' are now guaranteed to be CloudWatch Events triggers, all
non-CWE methods that started with 'on' are now called differently.

Introduce the 'onCloudTrailEvent' convention, to clearly signal
that the indicated event depend on the presence of a CloudTrail
Trail to capture it (as opposed to being intrinsically supported
by the service itself).

Introduce awslint rules to enforce these conventions.

Fixes #2278, fixes #2443.

BREAKING CHANGES

* All `onXxx()` CloudWatch Event methods now have the signature:

```ts
resource.onEvent('SomeId', {
    target: new SomeTarget(...),
    // options
});
```

* CloudWatch: rename `onAlarm()` => `addAlarmAction()`, `onOk` =>
  `addOkAction`, `onInsufficientData` => `addInsufficientDataAction`.
* AutoScaling: rename `onLifecycleTransition` => `addLifecycleHook()`.
* LambdaDeploymentGroup: rename `onPreHook` => `addPreHook`,
  `onPostHook` => `addPostHook`.
* UserPool: rename all `onXxx` methods => `addXxxTrigger`.
* Repository: rename `onImagePushed` => `onCloudTrailImagePushed`.
* Bucket: rename `onEvent` => `addEventNotification`, `onObjectCreated`
  => `addObjectCreatedNotification`, `onObjectRemoved` =>
  `addObjectRemovedNotification`, `onPutObject` =>
  `onCloudTrailPutObject`.

----

### Pull Request Checklist

* [ ] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [ ] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
  - __Design__: For significant features, design document added to `design` folder
* [ ] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [ ] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by jogold** [comment]
CW events (old pattern) were added in https://github.com/awslabs/aws-cdk/pull/2326 (now merged).

**Comment by rix0rrr** [comment]
> CW events (old pattern/signature) were added in #2326 (now merged).

Ah of course. Thanks for the heads up. I think there are some more conflicting changes on master in the linter as well.

**Comment by jogold** [comment]
@rix0rrr there's also the example in the README https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-config/README.md#events

File: packages/@aws-cdk/aws-codebuild/lib/project.ts [hunk 1]
```diff
@@ -157,6 +164,23 @@ abstract class ProjectBase extends Resource implements IProject {
   /** The IAM service Role of this Project. */
   public abstract readonly role?: iam.IRole;
 
+  /**
+   * Defines a CloudWatch event rule triggered when something happens with this project.
+   *
+   * @see https://docs.aws.amazon.com/codebuild/latest/userguide/sample-build-notifications.html
+   */
+  public onEvent(id: string, options: events.OnEventOptions): events.Rule {
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild/lib/project.ts]: I guess I missed this in the previous PR, but it's now or never: I kind of think that "target" shouldn't be under "Options", so I can do `onEvent('foo', target)`. 

It also maps more cleanly to the fact that you pass in `options` to `events.Rule` and then `addTarget` separately.

I would also say that `events.RuleProps` should contain `targets` (plural) to allow adding targets declaratively...

File: tools/awslint/lib/linter.ts [hunk 2]
```diff
@@ -126,11 +125,19 @@ export class Evaluation<T> {
...
 
+    // Don't add a "Success" diagnostic. It will break if we run a compound
+    // linter rule which consists of 3 checks with the same scope (such
+    // as for example `assertSignature()`). If the first check fails, we would
+    // add a "Success" diagnostic and all other diagnostics would be skipped because
+    // of the deduplication check above. Changing the scope makes it worse, since
+    // the scope is also the ignore pattern and they're all conceptually the same rule.
+    //
+    // Simplest solution is to not record successes -- why do we even need them?
+    if (include && condition) { return condition; }
```
Comment (eladb) [inline tools/awslint/lib/linter.ts]: It was mostly for verbose logging, maybe we can emit those here in case we are in verbose mode?

File: tools/awslint/lib/rules/cloudwatch-events.ts [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+  public get directEventMethods() {
+    return this.classType.allMethods.filter(isDirectEventMethod);
+  }
+
+  public get cloudTrailEventMethods() {
+    return this.classType.allMethods.filter(isCloudTrailEventMethod);
+  }
+}
+
+const ON_EVENT_OPTIONS_FQN = '@aws-cdk/aws-events.OnEventOptions';
```
Comment (eladb) [inline tools/awslint/lib/rules/cloudwatch-events.ts]: Should we move these to `CoreTypes`, did Shiv merge this?

File: tools/awslint/lib/rules/cloudwatch-events.ts [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+const EVENT_RULE_FQN = '@aws-cdk/aws-events.Rule';
+
+eventsLinter.add({
+  code: 'events-in-interface',
+  message: `'onXxx()' methods should also be defined on construct interface`,
+  eval: e => {
+    for (const method of e.ctx.directEventMethods.concat(e.ctx.cloudTrailEventMethods)) {
```
Comment (eladb) [inline tools/awslint/lib/rules/cloudwatch-events.ts]: `e.ctx.eventMethods` might be more elegant

File: tools/awslint/lib/rules/cloudwatch-events.ts [hunk 5]
```diff
@@ -0,0 +1,71 @@
+import reflect = require('jsii-reflect');
```
Comment (eladb) [inline tools/awslint/lib/rules/cloudwatch-events.ts]: Should probably be called `events.ts` since it's not just CWE

File: packages/@aws-cdk/aws-codebuild/lib/project.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: I was bivaricating on that. I found the API very ugly that way.

Hmm.

Comment (rix0rrr) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: Actually, here's why I changed the signature: the signature with 3 arguments becomes very ugly if you have a complex target (such as an ECS task or CodeBuild project), or a complex payload (from a JSON message), *and then* also configuration after it.

It would look something like this:

```ts
source.onEvent('MyEvent', rule.addTarget(new targets.EcsEc2Task({
  cluster,
  taskDefinition,
  taskCount: 1,
  containerOverrides: [{
    containerName: 'TheContainer',
    environment: [{
      name: 'I_WAS_TRIGGERED',
      value: 'From CloudWatch Events'
    }]
  }]
}), {
  eventDescription: 'hello'
  eventPattern: {
    field: ['value']
  }
});
```

vs:

```ts
source.onEvent('MyEvent', {
  eventDescription: 'hello'
  eventPattern: {
    field: ['value']
  },
  target: new targets.EcsEc2Task({
    cluster,
    taskDefinition,
    taskCount: 1,
    containerOverrides: [{
        containerName: 'TheContainer',
        environment: [{
        name: 'I_WAS_TRIGGERED',
        value: 'From CloudWatch Events'
        }]
    }]
  })
});
```

I feel the bad case is a lot worse for the first API, where the 2nd API fixes that, and the regular case isn't THAT much worse.

Comment (rix0rrr) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: Also, I think `obj.method('id', { ...props... })` is more consistent with most of our other APIs.
