### PR TITLE
fix(events): now `EventBus.grantPutEventsTo` correctly handles service principals (under feature flag)

### LINKED ISSUE #22080: aws-events: Cannot grant `putEvents` to Service Principals
### Describe the bug

When trying to `grantPutEventsTo` an AWS SP, there is a no-op, and no warnings or errors.  I would expect if we added a grant to a `iam.ServicePrincipal` that the underlying grant/policy would be created. We can add an SP to the event bus in the console.  Tracing back code I myself didn't necessary find a place where this would have failed, or I would have expected if this was not possible to give a failure message. 

### Expected Behavior

I would expect the template to have grant policies attached.  If for some reason you weren't allowed to add SPs, I would expect a failure message and error.

### Current Behavior

Nothing is logged to the terminal when synthing the template snippet is 
```
 "Resources": {
  "bus707364D1": {
   "Type": "AWS::Events::EventBus",
   "Properties": {
    "Name": "MyCustomEventBus"
   },
   "Metadata": {
    "aws:cdk:path": "xxx/bus/Resource"
   }
  },
  "busMyArchiveF1010141": {
   "Type": "AWS::Events::Archive",
   "Properties": {
    "SourceArn": {
     "Fn::GetAtt": [
      "bus707364D1",
      "Arn"
     ]
    },
    "ArchiveName": "MyCustomEventBusArchive",
    "Description": "MyCustomerEventBus Archive",
    "EventPattern": {
     "account": [
      "264988854622"
     ]
    },
    "RetentionDays": 365
   },
```

### Reproduction Steps

```ts
    const bus = new events.EventBus(this, 'bus', {
      eventBusName: 'MyCustomEventBus'
    });
    
    bus.archive('MyArchive', {
      archiveName: 'MyCustomEventBusArchive',
      description: 'MyCustomerEventBus Archive',
      eventPattern: {
        account: [cdk.Stack.of(this).account],
      },
      retention: cdk.Duration.days(365),
    });

    bus.grantPutEventsTo(new iam.ServicePrincipal('lambda.amazonaws.com'));
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.23.0

### Framework Version

_No response_

### Node.js Version

14

### OS

MacOs/Linux

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by scorbiere**
### Issue #22080

Closes #22080.

### Reason for this change

When trying to grant PutEvents permissions to an AWS Service Principal using `grantPutEventsTo`, the method performed a no-op without any warnings or errors. This prevented users from properly granting permissions to service principals, even though this is a valid use case that can be done through the AWS Console. The change implements the correct behavior by creating an EventBusPolicy when dealing with service principals.

### Description of changes

- Added special handling for service principals in `EventBus.grantPutEventsTo` method
- When granting permissions to a service principal, creates an EventBusPolicy instead of attempting to modify IAM policies
- Returns `iam.Grant.drop()` for service principals to indicate permissions are handled via EventBusPolicy
- Added test cases to verify both service principal and IAM principal scenarios

### Describe any new or updated permissions being added

The change introduces the creation of EventBusPolicy resources with `events:PutEvents` permission when granting access to service principals. This is not a new permission, but rather a different way of granting the same permission through resource-based policies instead of identity-based policies.

### Description of how you validated changes

Added new test cases that verify:
- EventBusPolicy is correctly created when granting permissions to service principals
- IAM policies are correctly created when granting permissions to IAM roles/users

### Checklist
- [X] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by moelasmar — CHANGES_REQUESTED** [review]
thanks Seb for raising this PR, I left some comment

File: packages/aws-cdk-lib/aws-events/lib/event-bus.ts [hunk 1]
```diff
@@ -177,6 +177,21 @@ abstract class EventBusBase extends Resource implements IEventBus {
   }
 
   public grantPutEventsTo(grantee: iam.IGrantable): iam.Grant {
+    // Special handling for service principals
+    if (grantee.grantPrincipal instanceof iam.ServicePrincipal) {
```
[the remark this answers is not in the document]
Comment (moelasmar) [reply packages/aws-cdk-lib/aws-events/lib/event-bus.ts:181]: one more thing, I am not sure if it is Ok to create multiple EventBusPolicy resources for the same EventBus or not .. we need to have a test case for that.

File: packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus-grants.ts [hunk 2]
```diff
@@ -0,0 +1,176 @@
...
+import * as lambda from 'aws-cdk-lib/aws-lambda';
+import * as sfn from 'aws-cdk-lib/aws-stepfunctions';
+import * as tasks from 'aws-cdk-lib/aws-stepfunctions-tasks';
+import * as ssm from 'aws-cdk-lib/aws-ssm';
+import { ExpectedResult, IntegTest, Match } from '@aws-cdk/integ-tests-alpha';
+import * as cxapi from 'aws-cdk-lib/cx-api';
+import { STANDARD_NODEJS_RUNTIME } from '../../config';
+
+// Create a single app for both stacks
+const app = new App();
```
Comment (moelasmar) [inline packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus-grants.ts:12]: I think in this integ test case, there is no difference between with feature flag, and without. In both cases the permissions will be added to the Role .. may be this test case is designed to verify that the current customer code will stay working. so, can we have a new integ test case to verify the new behaviour of grant method, and also, to verify that we can call grant method more than one in the new approach.

File: packages/aws-cdk-lib/aws-events/test/event-bus.test.ts [hunk 3]
```diff
@@ -641,20 +642,6 @@ describe('event bus', () => {
...
-    const stack = new Stack(app, 'Stack');
-    const bus = new EventBus(stack, 'Bus');
-
-    // THEN
-    expect(() => bus.addToResourcePolicy(new iam.PolicyStatement({
-      effect: iam.Effect.ALLOW,
-      principals: [new iam.ArnPrincipal('arn')],
-      actions: ['events:PutEvents'],
-    }))).toThrow('Event Bus policy statements must have a sid');
-  });
```
Comment (moelasmar) [inline packages/aws-cdk-lib/aws-events/test/event-bus.test.ts:656]: I think this test case is still valid, right ?

File: packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts [hunk 4]
```diff
@@ -0,0 +1,554 @@
...
+            Effect: 'Allow',
+            Action: 'events:PutEvents',
+            Principal: { Service: 'states.amazonaws.com' },
+            Resource: Match.anyValue(),
+            Condition: Match.absent(),
+          }),
+        });
+      });
+
+      test('grantPutEventsTo creates both IAM and resource policies for cross-account service principal', () => {
```
Comment (moelasmar) [inline packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts:146]: I think the test title is wrong.

File: packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts [hunk 5]
```diff
@@ -0,0 +1,554 @@
...
+            },
+          },
+          StatementId: `cdk-${defaultSid}`,
+          EventBusName: { Ref: 'EventBus7B8748AA' },
+        });
+
+        expect(grant.success).toBeTruthy();
+      });
+
+      test('grantPutEventsTo creates both IAM and resource policies for cross-account role principal', () => {
```
Comment (moelasmar) [inline packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts:179]: this one as well, has a wrong title

File: packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts [hunk 6]
```diff
@@ -0,0 +1,554 @@
...
+            Resource: { 'Fn::GetAtt': ['EventBus7B8748AA', 'Arn'] },
+          },
+          StatementId: `cdk-${defaultSid}`,
+          EventBusName: { Ref: 'EventBus7B8748AA' },
+        });
+
+        expect(grant.success).toBeTruthy();
+      });
+
+      test('grantPutEventsTo creates both IAM and resource policies for cross-account organization principal', () => {
```
Comment (moelasmar) [inline packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts:209]: same here as well

File: packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts [hunk 7]
```diff
@@ -0,0 +1,554 @@
...
+          EventBusName: { Ref: 'EventBus7B8748AA' },
+        });
+
+        expect(grant.success).toBeTruthy();
+
+        Template.fromStack(stack).resourceCountIs('AWS::Events::EventBusPolicy', 1);
+        Template.fromStack(stack).resourceCountIs('AWS::IAM::Policy', 0);
+
+        // Verify all required parts of the organization policy
+        Template.fromStack(stack).hasResourceProperties('AWS::Events::EventBusPolicy', {
```
Comment (moelasmar) [inline packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts:242]: what is the difference between this check and check in line 217

File: packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts [hunk 8]
```diff
@@ -0,0 +1,554 @@
...
+          Statement: Match.objectLike({
+            Effect: 'Allow',
+            Action: 'events:PutEvents',
+            Principal: { Service: 'states.amazonaws.com' },
+            Resource: Match.anyValue(),
+            Condition: Match.absent(),
+          }),
+        });
+      });
```
[the remark this answers is not in the document]
Comment (scorbiere) [reply packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts:144]: Right, this is confusing and this 2nd assertion doesn't add much value. I will re-write the assertions with helper functions in order to improve the readability.

File: packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts [hunk 9]
```diff
@@ -0,0 +1,488 @@
...
+        assertIdentityBasedPolicy(stack, {
+          'Fn::Join': ['', [
+            'arn:',
+            { Ref: 'AWS::Partition' },
+            ':events:',
+            { Ref: 'AWS::Region' },
+            ':',
+            { Ref: 'AWS::AccountId' },
+            ':event-bus/',
+            { Ref: 'EventBus7B8748AA' },
```
Comment (moelasmar) [inline packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts:315]: similar to the previous comment, I expect to see some normal string value, instead of ref intrinsic function.

File: packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts [hunk 10]
```diff
@@ -0,0 +1,488 @@
...
+        expect(grant.success).toBeTruthy();
+      });
+    });
+
+    describe('token handling', () => {
+      test('creates identity-based policy for token account principal', () => {
+        // GIVEN
+        // Create a role with a token principal
+        const role = new iam.Role(stack, 'Role', {
+          assumedBy: new iam.AccountRootPrincipal(), // This will use the stack's account token
```
Comment (moelasmar) [inline packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts:329]: to understand, why do we care about this token .. how may this value change the process of adding the permissions?

File: packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts [hunk 11]
```diff
@@ -327,36 +333,17 @@ describe('EventBus grants', () => {
...
-
-        // Verify no warnings were created
-        const warnings = Annotations.fromStack(stack).findWarning('*', Match.anyValue());
-        expect(warnings).toHaveLength(0);
       });
     });
 
     describe('cross-stack scenarios', () => {
-      test('grantPutEventsTo works across stacks', () => {
+      test('creates identity-based policy in different stack', () => {
```
Comment (moelasmar) [inline packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts:346]: Can you add a test case to grant an imported role that is not managed by the CDK application. I expect in this scenario, we should see an Event Resource Policy instead of identity policy.

File: packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus-service-principal-grants.ts [hunk 12]
```diff
@@ -0,0 +1,142 @@
+import * as cdk from 'aws-cdk-lib';
```
Comment (moelasmar) [inline packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus-service-principal-grants.ts:1]: this test case is also miss leading, if you checked the generated template, you will find the following:
 - `TargetEventBuscdkEventsServicePrincipalGrant11A8AC78` Event resource policy that grant `events.amazonaws.com` service to put event on eventBus `TargetEventBus43DE6DE2` (this is the point we need to verify)
 - But also, you will find `ForwardingRuleEventsRoleDefaultPolicy5A4528E2` identity policy that grant role `ForwardingRuleEventsRole9F12172A` to put events on EventBus `TargetEventBus43DE6DE2`, and this role is attached to EventRule `ForwardingRule6039FF0D` which is linked to EventBus `SourceEventBusA326BD45`

So, I am not sure which policy is applied. .. can you try to change this logic, to add a lambda function that try to put some event to an event bus, and do not grant the function itself, but grant the Lambda Service, and see if this will work or not

**Review by moelasmar — CHANGES_REQUESTED** [review]
Thanks Seb, I still have some concern about the new integration test case

File: packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts [hunk 13]
```diff
@@ -65,85 +182,31 @@ describe('EventBus grants', () => {
...
-        expect(warnings).toHaveLength(0);
-
+        assertOnlyResourcePolicy(stack, grant);
         expect(grant.success).toBeTruthy();
       });
     });
 
     describe('cross-account scenarios', () => {
-      test('grantPutEventsTo creates EventBusPolicy for service principal without conditions', () => {
+      test('creates resource policy for service principal without conditions', () => {
```
[the remark this answers is not in the document]
Comment (scorbiere) [reply packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts:196]: Right, I will remove it.

File: packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus-service-principal-grants.ts (hunk 12 above)
Comment (scorbiere) [reply packages/@aws-cdk-testing/framework-integ/test/aws-events/test/integ.eventbus-service-principal-grants.ts:1]: Good catch, it seems that the `EventBus` class implementation ([link](https://github.com/aws/aws-cdk/blob/303ff44ec111a4057693a3d9859066715669b6e7/packages/aws-cdk-lib/aws-events-targets/lib/event-bus.ts#L35-L59)) of the method `bind` automatically tries to add the put event policy on its associated role (type `iam.IRole`), which is not compatible with the service principal we are using in this integ test.

File: packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts [hunk 14]
```diff
@@ -65,85 +182,31 @@ describe('EventBus grants', () => {
...
-            Action: 'events:PutEvents',
-            Principal: { Service: 'states.amazonaws.com' },
-            Resource: Match.anyValue(),
-            Condition: Match.absent(),
-          }),
-        });
       });
 
-      test('grantPutEventsTo creates both IAM and resource policies for cross-account service principal', () => {
+      test('creates resource policy for service principal with cross-account condition', () => {
```
[the remark this answers is not in the document]
Comment (scorbiere) [reply packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts:209]: Right, I will remove it as well.

File: packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts (hunk 10 above)
Comment (scorbiere) [reply packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts:329]: This case was making sense when I was trying to use the `Grant.addToPrincipalOrResource(...)` method in `EventBusBase.grantPutEventsTo(...)`. Which not the strategy used anymore. I will remove this test.

File: packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts (hunk 11 above)
Comment (scorbiere) [reply packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts:346]: I will add that test case, but the template generated is:
```
ImportedRoleIdPolicy878A765C :: {
      "Properties": {
        "PolicyDocument": {
          "Statement": [
            {
              "Action": "events:PutEvents",
              "Effect": "Allow",
              "Resource": {
                "Fn::GetAtt": [ "EventBus7B8748AA", "Arn" ],
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "PolicyName": "ImportedRoleIdPolicy878A765C",
        "Roles": [ "importedRoleName" ]
      },
      "Type": "AWS::IAM::Policy"
    }
```

Even when I use `iam.Role.fromRoleArn(...)`. The code in [Grant.addToPrincipal(...)](https://github.com/aws/aws-cdk/blob/303ff44ec111a4057693a3d9859066715669b6e7/packages/aws-cdk-lib/aws-iam/lib/grant.ts#L248) call directly [ImportedRole.addToPrincipalPolicy(...)](https://github.com/aws/aws-cdk/blob/303ff44ec111a4057693a3d9859066715669b6e7/packages/aws-cdk-lib/aws-iam/lib/private/imported-role.ts#L51)

File: packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts [hunk 15]
```diff
@@ -4,6 +4,135 @@ import { App, Stack, Token } from '../../core';
...
+function assertNoResourcePolicy(stack: Stack) {
+  Template.fromStack(stack).resourceCountIs('AWS::Events::EventBusPolicy', 0);
+}
+
+/**
+ * Verifies that no identity-based policy was created.
+ */
+function assertNoIdentityPolicy(stack: Stack) {
+  Template.fromStack(stack).resourceCountIs('AWS::IAM::Policy', 0);
+}
```
[the remark this answers is not in the document]
Comment (scorbiere) [reply packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts:23]: Fair enough, but I prefer the readability of the method name in the test.

File: packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts (hunk 11 above)
Comment (moelasmar) [reply packages/aws-cdk-lib/aws-events/test/event-bus.grant.test.ts:286]: when you call `fromRolexxx` function, set mutable flag to false .. https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.FromRoleArnOptions.html#mutable

This means that CDK could not attach policies to this Role.
