### PR TITLE
fix(logs): query strings can have multiple stats commands

### LINKED ISSUE #34578: (logs): Query strings may multiple stats commands in a single query
### Describe the bug

Docs: https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_QuerySyntax-Stats.html#CWL_QuerySyntax-stats-multi

And the props only support one:

https://github.com/aws/aws-cdk/blob/d8e6c09083d4958c1967bc19ff30cf15820580af/packages/aws-cdk-lib/aws-logs/lib/query-definition.ts#L57-L62

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Library Version

latest

### Expected Behavior

Support 2 stats.

> You can use **as many as two** stats commands in a single query. This enables you to perform an additional aggregation on the output of the first aggregation.

### Current Behavior

Supports 1 stats.

### Reproduction Steps

Look at the code.

### Possible Solution

Add support for 2 stats.

### Additional Information/Context

_No response_

### AWS CDK Library version (aws-cdk-lib)

N/A

### AWS CDK CLI version

N/A

### Node.js Version

N/A

### OS

N/A

### Language

TypeScript

### Language Version

N/A

### Other information

_No response_

### PR DESCRIPTION
**Pull request by msambol**
### Issue #34578

Closes #34578

### Checklist
- [ ] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by msambol** [comment]
@badmintoncryer Have time for a review here?

**Review by badmintoncryer — APPROVED** [review]
@msambol 

Thank you for creating this! I don't think there's any issue with the content.

Just to be safe, how about displaying a warning as an `Annotation` for users who set both 'stats' and 'statStatements' simultaneously, indicating that 'stats' will be ignored?

File: packages/aws-cdk-lib/aws-logs/lib/query-definition.ts [hunk 1]
```diff
@@ -55,12 +55,24 @@ export interface QueryStringProps {
...
+   * A single statement for using log field values to calculate aggregate statistics.
    *
+   * @deprecated Use `statsStatements` instead
    * @default - no stats in QueryString
    */
   readonly stats?: string;
 
+  /**
+   * An array of one or more statements for calculating aggregate statistics.
+   * CloudWatch Logs Insights supports up to two stats commands in a single query.
```
Comment (ozelalisen) [inline packages/aws-cdk-lib/aws-logs/lib/query-definition.ts:67]: There is no validation to enforce the limit for the size of two stats commands. Could you add this validation alongside with a unit test?

File: packages/aws-cdk-lib/aws-logs/lib/query-definition.ts [hunk 2]
```diff
@@ -119,6 +130,14 @@ export class QueryString {
     } else {
       this.filter = [];
     }
+
+    if (props.statsStatements) {
```
Comment (ozelalisen) [inline packages/aws-cdk-lib/aws-logs/lib/query-definition.ts:145]: When both properties are used, this could to lead unexpected behaviour. Could you add warning similar smth like:
```
Both stats and statsStatements properties are provided. The stats property is deprecated and will be ignored in favor of statsStatements
}
```

**Review by ozelalisen — CHANGES_REQUESTED** [review]
Left minor comments

**Comment by msambol** [comment]
> Left minor comments

Added both, thanks for the review!

File: packages/aws-cdk-lib/aws-logs/lib/query-definition.ts (hunk 2 above)
Comment (msambol) [reply packages/aws-cdk-lib/aws-logs/lib/query-definition.ts:145]: I think I need to throw this warning in `QueryDefinition` right?  If I do it in `QueryString`, I see the following:

```
Argument of type 'this' is not assignable to parameter of type 'IConstruct'.
  Property 'node' is missing in type 'QueryString' but required in type 'IConstruct'.
```

Unless there is a another way I can add the warning?
```
        Annotations.of(this).addWarningV2('QueryDefinitionStatsWarning',
          'Both stats and statsStatements properties are provided. The stats property is deprecated and will be ignored in favor of statsStatements.');
      }
```

I'd like to do it in `QueryString` if possible so I can avoid those public methods.

**Comment by ozelalisen** [comment]
Thanks for the changes, could you fix the build failure as well?

**Comment by msambol** [comment]
> Thanks for the changes, could you fix the build failure as well?

Done!

**Review by ozelalisen — DISMISSED** [review]
Thank you, LGTM!

**Review by ozelalisen — APPROVED** [review]
