### PR TITLE
fix(custom-resource-handlers): do not allow unauthorized connection for iam OIDC connection (under feature flag)

### LINKED ISSUE #32920: custom-resource-handlers: IAM OIDC Provider reject unauthorized connection
### Describe the bug

The current implementation allows unauthorized connection in IAM OIDC Provider. These options lead to vulnerability, and should not be used. Although this code is run in a custom resource lambda handler and there shouldn't be any real impact, we should still follow the best practice to reject unauthorized connections.

packages/@aws-cdk/custom-resource-handlers/lib/aws-iam/oidc-handler/external.ts
❯❱ problem-based-packs.insecure-transport.js-node.bypass-tls-verification.bypass-tls-verification
Checks for setting the environment variable NODE_TLS_REJECT_UNAUTHORIZED to 0, which disables TLS
verification. This should only be used for debugging purposes. Setting the option rejectUnauthorized
to false bypasses verification against the list of trusted CAs, which also leads to insecure
transport. 

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

Reject unauthorized OIDC connection

### Current Behavior

Allow unauthorized OIDC connection

### Reproduction Steps

N/A

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

any

### Framework Version

_No response_

### Node.js Version

Node 20

### OS

MacOs

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by GavinZZ**
### Issue # (if applicable)

Closes #32920

### Reason for this change

Follow security best practices to disable allow unauthorized connection

### Description of changes

Create a new feature flag that starting in the new feature, we will disable unauthorized connections

### Describe any new or updated permissions being added

N/A

### Description of how you validated changes

New integ and unit tests. Updated old tests.

### Checklist
- [ ] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-iam/lib/oidc-provider.ts [hunk 1]
```diff
@@ -146,6 +150,7 @@ export class OpenIdConnectProvider extends Resource implements IOpenIdConnectPro
         ClientIDList: props.clientIds,
         ThumbprintList: props.thumbprints,
         Url: props.url,
+        RejectUnauthoried: rejectUnauthorized,
```
Comment (gracelu0) [inline packages/aws-cdk-lib/aws-iam/lib/oidc-provider.ts:153]:
```suggestion
        RejectUnauthorized: rejectUnauthorized,
```

File: packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md [hunk 2]
```diff
@@ -84,9 +84,10 @@ Flags come in three types:
...
-| [@aws-cdk/aws-ecs:enableImdsBlockingDeprecatedFeature](#aws-cdkaws-ecsenableimdsblockingdeprecatedfeature) | When set to true along with canContainersAccessInstanceRole=false in ECS cluster, new updated commands will be added to UserData to block container accessing IMDS. **Applicable to Linux only. IMPORTANT: See [details.](#aws-cdkaws-ecsenableImdsBlockingDeprecatedFeature)** | V2NEXT | (temporary) |
+| [@aws-cdk/aws-ecs:disableEcsImdsBlocking](#aws-cdkaws-ecsdisableecsimdsblocking) | When set to true, CDK synth will throw exception if canContainersAccessInstanceRole is false. **IMPORTANT: See [details.](#aws-cdkaws-ecsdisableEcsImdsBlocking)** | 2.175.0 | (temporary) |
+| [@aws-cdk/aws-ecs:enableImdsBlockingDeprecatedFeature](#aws-cdkaws-ecsenableimdsblockingdeprecatedfeature) | When set to true along with canContainersAccessInstanceRole=false in ECS cluster, new updated commands will be added to UserData to block container accessing IMDS. **Applicable to Linux only. IMPORTANT: See [details.](#aws-cdkaws-ecsenableImdsBlockingDeprecatedFeature)** | 2.175.0 | (temporary) |
```
Comment (gracelu0) [inline packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md:88]: hmm should this be showing up as a change?

File: packages/aws-cdk-lib/cx-api/lib/features.ts [hunk 3]
```diff
@@ -1355,6 +1356,21 @@ export const FLAGS: Record<string, FlagInfo> = {
...
+  //////////////////////////////////////////////////////////////////////
+  [IAM_OIDC_REJECT_UNAUTHORIZED_CONNECTIONS]: {
+    type: FlagType.BugFix,
+    summary: 'When enabled, the default behaviour of OIDC provider will reject unauthorized connections',
+    detailsMd: `
+      When this feature flag is enabled, the default behaviour of OIDC Provider's custom resource handler will
+      default to reject unauthorized connections when downloading CA Certificates.
+      
+      When this feature flag is disabled, the behaviour will be the same as current and will allow downloading
+      thumbprints from unsecure connnections.`,
```
Comment (gracelu0) [inline packages/aws-cdk-lib/cx-api/lib/features.ts:1369]:
```suggestion
      thumbprints from unsecure connections.`,
```

File: packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md [hunk 4]
```diff
@@ -1484,11 +1642,32 @@ will allow IPv6 ingress from anywhere (::/0). Previously, the default security g
...
+
+### @aws-cdk/aws-iam:oidcRejectUnauthorizedConnections
+
+*When enabled, the default behaviour of OIDC provider will reject unauthorized connections* (fix)
+
+When this feature flag is enabled, the default behaviour of OIDC Provider's custom resource handler will
+default to reject unauthorized connections when downloading CA Certificates.
+
+When this feature flag is disabled, the behaviour will be the same as current and will allow downloading
+thumbprints from unsecure connnections.
```
Comment (gracelu0) [inline packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md:1662]:
```suggestion
thumbprints from unsecure connections.
```

File: packages/aws-cdk-lib/aws-iam/lib/oidc-provider.ts [hunk 5]
```diff
@@ -138,6 +140,8 @@ export class OpenIdConnectProvider extends Resource implements IOpenIdConnectPro
   public constructor(scope: Construct, id: string, props: OpenIdConnectProviderProps) {
     super(scope, id);
 
+    const rejectUnauthorized = FeatureFlags.of(this).isEnabled(IAM_OIDC_REJECT_UNAUTHORIZED_CONNECTIONS) ?? false;
```
Comment (gracelu0) [inline packages/aws-cdk-lib/aws-iam/lib/oidc-provider.ts:143]: can we add unit tests to https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-iam/test/oidc-provider.test.ts for checking cases when this flag is enabled/disabled?

**Review by gracelu0 — CHANGES_REQUESTED** [review]
Ty! Left a few comments, mostly typos

File: packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md (hunk 2 above)
Comment (GavinZZ) [reply packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md:88]: Yes, the feature flag markdown file should include all features flags. These are are somehow missed from the file and I don't want to create a separate PR to include these missing flags.

**Review by gracelu0 — APPROVED** [review]

**Comment by mrgrain** [comment]
@Mergifyio dequeue

**Comment by mrgrain** [comment]
@GavinZZ Dequeued this because the conflicts prevent it from merging and it's blocking the queue
