### PR TITLE
fix(assets): add exclude glob patterns to calculating fingerprint for staging

### LINKED ISSUE #5238: Lambda handlers with differing code exclusions end up with same asset
Created stack with two lambdas with the following configuration using `Code.fromAsset` with `exclude`. Expecting two different asset packages but both of the lambdas ended up with the same asset which only contained the `ProductSearchLambda.js` file.

### Reproduction Steps

```
    const commonApiHandlerProps = {
      runtime: Runtime.NODEJS_12_X,
      vpc: props.vpc,
      memorySize: 512,
      timeout: Duration.seconds(10),
      tracing: Tracing.ACTIVE,
    }

    const productSearchLambda = new Function(this, 'ProductSearchFunction', {
      handler: 'ProductSearchLambda.handler',
      code: Code.fromAsset(path.join(__dirname, 'resources'), {
        exclude: ['**', '!ProductSearchLambda.js'],
      }),
      ...commonApiHandlerProps,
    })

    const multiProductSearchLambda = new Function(this, 'MultiProductSearchFunction', {
      handler: 'MultiProductSearchLambda.handler',
      code: Code.fromAsset(path.join(__dirname, 'resources'), {
        exclude: ['**', '!MultiProductSearchLambda.js'],
      }),
      ...commonApiHandlerProps,
    })
```

### Error Log

```
      "Metadata": {
        "aws:cdk:path": "ProductApiStack/ProductSearchFunction/Resource",
        "aws:asset:path": "asset.1ebc9d3ac2033816c4abb63e4afd69d350b4aba8704cc9236b82ea520b74f4b0",
        "aws:asset:property": "Code"
      }
```

```
      "Metadata": {
        "aws:cdk:path": "ProductApiStack/MultiProductSearchFunction/Resource",
        "aws:asset:path": "asset.1ebc9d3ac2033816c4abb63e4afd69d350b4aba8704cc9236b82ea520b74f4b0",
        "aws:asset:property": "Code"
      }
```

### Environment

  - **CLI Version      :** 1.18.0
  - **Framework Version:**
  - **OS               :** OS X
  - **Language         :** TypeScript

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by Samrose-Ahmed**
Fixes #5238

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/assets/lib/fs/fingerprint.ts [hunk 1]
```diff
@@ -31,6 +31,7 @@ export function fingerprint(fileOrDirectory: string, options: FingerprintOptions
     ? fileOrDirectory
     : path.dirname(fileOrDirectory);
   const exclude = options.exclude || [];
+  _hashField(hash, 'options.exclude', exclude.toString());
```
Comment (eladb) [inline packages/@aws-cdk/assets/lib/fs/fingerprint.ts]: I rather we use JSON.stringify instead of toString

File: packages/@aws-cdk/assets/test/fs/test.fs-fingerprint.ts [hunk 2]
```diff
@@ -68,11 +68,13 @@ export = {
       const outdir = fs.mkdtempSync(path.join(os.tmpdir(), 'copy-tests'));
       libfs.copyDirectory(srcdir, outdir);
 
+      const options = { exclude: ['*.ignoreme'] };
```
Comment (eladb) [inline packages/@aws-cdk/assets/test/fs/test.fs-fingerprint.ts]: Please avoid modifying existing tests. Instead, add a new test that will verify the new behavior.

File: packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer-iam-role.expected.json [hunk 3]
```diff
@@ -36,7 +36,7 @@
       "Properties": {
         "Code": {
           "S3Bucket": {
-            "Ref": "AssetParameters6695c4a3dad80ddeef2797a1729306b7c136d67ce21d2187fdbc7bbad009993aS3Bucket115F9EA4"
```
Comment (eladb) [inline packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer-iam-role.expected.json]: Curious, why did so many test expectations change? Shouldn’t this only affect source hashes that used “exclude”?

Comment (Samrose-Ahmed) [reply packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer-iam-role.expected.json]: So, `_hashField` [includes the header](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/assets/lib/fs/fingerprint.ts#L84) so it's updating even when `options.exclude` is not used.
We could do 
```
if (options.exclude){
  _hashField(hash, 'options.exclude', exclude.toString());
}
```
so it only changes when `exclude` was used. I was just following what was done previously with `options.extra` which was also optional (`_hashField(hash, 'options.extra', options.extraHash || '');`)

File: packages/@aws-cdk/assets/test/fs/test.fs-fingerprint.ts (hunk 2 above)
Comment (Samrose-Ahmed) [reply packages/@aws-cdk/assets/test/fs/test.fs-fingerprint.ts]: This test will fail if they don't have the same `exclude` options since 
`const hashSrc = libfs.fingerprint(srcdir);` and
`const hashCopy = libfs.fingerprint(outdir, { exclude: ['*.ignoreme'] });` 
 aren't going to be equal.

File: packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer-iam-role.expected.json (hunk 3 above)
Comment (eladb) [reply packages/@aws-cdk/aws-apigateway/test/authorizers/integ.token-authorizer-iam-role.expected.json]: Got it. Let’s do this conditionally to reduce the noise this might create (basically invalidating all assets everywhere)

**Comment by anguslees** [comment]
Shouldn't the content hash already catch this?  I think including the exclude option hides a deeper bug here: the exclude handling of globs during fingerprinting is different to the exclude handling during actual asset creation.

To put it another way, two different Assets that reference the same directory, and exclude files that don't actually exist *should* generate the same hash.
