### PR TITLE
fix(pipelines): reduce assets IAM policy size

### LINKED ISSUE #9316: [@aws-cdk/pipelines] Maximum policy size of 10240 bytes exceeded for role
### The Question
After adding around 5 stacks to a single Pipeline Application (Stage) the pipeline references 15 assets and new reused PipelineAssetRole policy grows to be too large, blocking the pipeline and making it unusable.

Just tried out the latest fix (#9243) with v1.55.0 But now I am seeing this error when deploying.

```
Maximum policy size of 10240 bytes exceeded for role PipelineStack-PipelineAssetsRole9B011X83-1UOLXJQTUXXXX
```

### Environment

  - **CDK CLI Version:** 1.55.0 (build 48ccf09)
  - **Module Version:** 1.55.0
  - **Node.js Version:** v14.5.0
  - **OS:** OSX Catalina
  - **Language (Version):** TypeScript (3.9.7)

### Other information

Related: 
https://github.com/aws/aws-cdk/issues/9225

### PR DESCRIPTION
**Pull request by njlynch**
Collapse the PipelineAssetsRoleDefaultPolicy into a single up-front policy that
doesn't grow per-asset. This relaxes some of the permissions in exchange for
avoiding an O(N) policy size.

fixes #9316

_Testing notes:_ Successfully deployed a pipeline with 49 assets (25 file assets and 24 docker assets). 50 assets is the limit for a single stage of the pipeline. To scale out past 50 assets, we will need to segment the assets pipeline stage into multiple stages. I'm considering that out-of-scope for this bugfix.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/pipelines/lib/pipeline.ts [hunk 1]
```diff
@@ -321,9 +317,70 @@ class AssetPublishing extends Construct {
...
+        'codebuild:BatchGetBuilds',
+        'codebuild:StartBuild',
+        'codebuild:StopBuild',
+      ],
+    }));
+
+    // Publishing role access
+    assetRole.addToPolicy(new iam.PolicyStatement({
+      actions: ['sts:AssumeRole'],
+      resources: ['arn:*:iam::*:role/*-image-publishing-role-*', 'arn:*:iam::*:role/*-file-publishing-role-*'],
```
Comment (eladb) [inline packages/@aws-cdk/pipelines/lib/pipeline.ts:373]: As we discussed, let's at least separate these into two roles so docker image publishers won't be able to upload files to the assets bucket.

File: packages/@aws-cdk/pipelines/lib/pipeline.ts [hunk 2]
```diff
@@ -321,9 +317,70 @@ class AssetPublishing extends Construct {
...
+    const logGroupArn = Stack.of(this).formatArn({
+      service: 'logs',
+      resource: 'log-group',
+      sep: ':',
+      resourceName: '/aws/codebuild/*',
+    });
+    assetRole.addToPolicy(new iam.PolicyStatement({
+      resources: [logGroupArn],
+      actions: ['logs:CreateLogGroup', 'logs:CreateLogStream', 'logs:PutLogEvents'],
+    }));
```
Comment (eladb) [inline packages/@aws-cdk/pipelines/lib/pipeline.ts:342]: Would be nice to add a bunch of `grant` methods to `codebuild.Project`

Comment (njlynch) [reply packages/@aws-cdk/pipelines/lib/pipeline.ts:342]: Any 'normal' `grant` methods would include the specific resource ARN, right? Which is exactly what we're trying to avoid here. 

Unless you're picturing more of a static method, where the 
```ts
class Project extends ProjectBase {
  public static grantRead(grantee: iam.IGrantable, project?: Project) { ... }
}
```

File: packages/@aws-cdk/pipelines/lib/pipeline.ts (hunk 1 above)
Comment (njlynch) [reply packages/@aws-cdk/pipelines/lib/pipeline.ts:373]: Will do; I can have us create one role per asset type.
