### PR TITLE
Fix CloudFront origin error

### LINKED ISSUE #508: Possible error in generated template for CloudFront distributions
Hello,
I was trying to deploy a CloudFront Distribution, simply by following the examples provided in the documentation:

```js
new cloudfront.CloudFrontWebDistribution(
    this,
    'PublicWWWDistribution',
    {
        originConfigs: [
            {
                s3OriginSource: {
                    s3BucketSource: this.bucket,
                },
                behaviors: [
                    {
                        isDefaultBehavior: true,
                    },
                ],
            },
        ],
    }
);
```

But... when I run `cdk deploy`, the stack update fails with the following error:
```
n47E3983B
[4/7] Sun Aug 05 2018 20:10:59 GMT+0200 (CEST)  CREATE_FAILED       [AWS::CloudFront::Distribution] PublicWWWDistributionCFDistributionXXXX Exactly one of CustomOriginConfig and S3OriginConfig must be specified
```

I'm specifying an s3 Origin and, from what I can see from the [web_distribution](https://github.com/awslabs/aws-cdk/blob/bb956763e619d9ec39803f4e9672f165c32aa5f7/packages/%40aws-cdk/aws-cloudfront/lib/web_distribution.ts#L506) code in CDK, you are **not setting the `S3OriginConfig` property** ([required](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-origin.html#cfn-cloudfront-distribution-origin-s3origin) by CloudFormation). If I'm not wrong, in a YAML template this property can be specified as an empty object literal `S3OriginConfig: {}`.

Also, I see that the CloudFormation template that's *expect*ed in the [tests](https://github.com/awslabs/aws-cdk/pull/45/files#diff-13f9aba5b39fff941cc195392a461f17), does not work for the same reason.

```bash
$ cdk --version
0.8.0 (build bb95676)
```
Thanks,

### PR DESCRIPTION
**Pull request by mindstorms6**
When using CloudFront without an origin access identity, we were failing to include the "empty" property S3OriginConfig - this fixes that.

Also adds an integ test and a validate that verifies this.

Should fix #508

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts [hunk 1]
```diff
@@ -558,6 +567,16 @@ export class CloudFrontWebDistribution extends cdk.Construct {
 
     }
 
+    public validate(): string[] {
```
Comment (eladb) [inline packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts]: Is it possible to add origins after the construct is created (might be a useful feature)? If not, then why not just validate this in the constructor?

Comment (mindstorms6) [reply packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts]: I don't mind validating in the constructor - I just thought that was the point of the `validate` method. 

Is the idea that validate is only used if you have post-constructor modifications? (That makes sense to me, just trying to get a feel for how you see it)

Comment (eladb) [reply packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts]: Yap. It's a hook that allows you to perform validations just before synthesis. But the sooner you can perform a validation, the better, because the error will include the most context for the user to be able to understand what they did wrong.

Comment (mindstorms6) [reply packages/@aws-cdk/aws-cloudfront/lib/web_distribution.ts]: Understood. I'll drop the `validate` for the time being - I don't currently think adding a origin post creation is valuable. (In my mind - it's not.)

If someone opens a pull request later - it's easy enough to add that.
