### PR TITLE
fix: half-written asset zips can be uploaded if process is interrupted

### LINKED ISSUE #18459: (aws-lambda-nodejs): Uploaded file must be a non-empty zip
### What is the problem?

I updated lambda function dependancies and deploying the lambda function but it fails with following error. 

error

I also have another api under the same project and I updated its lambda function dependancies and it was deployed successfully. 

Both api's and its lambda functions are almost identical to each other. However only one gets deployed and another one doesn't.

I deleted the `cdk.out` folder and tried to deploy again and it fails with same error each time.

### Reproduction Steps

I have simple lambda function that I am trying to deploy as follows

```ts
import { NodejsFunction } from 'aws-cdk-lib/aws-lambda-nodejs';
import { Architecture, Code, Function, Runtime } from 'aws-cdk-lib/aws-lambda';

const authFn = new NodejsFunction(this, 'authNodeJs', {
      runtime: Runtime.NODEJS_14_X,
      entry: `${__dirname}/../auth/index.ts`,
      handler: 'auth',
      architecture: Architecture.ARM_64,
      memorySize: 1024,
      environment: {
        CLIENT_ID: appClientID
      }
    })

const auth1Fn = new Function(this, 'authGolang', {
      runtime: Runtime.GO_1_X,
      code: Code.fromAsset(`${__dirname}/../auth-1/`, {
        bundling: {
          image: Runtime.GO_1_X.bundlingImage,
          user: 'root',
          command: [
            'bash', '-c', [
              'cd /asset-input',
              'go build -o main main.go',
              'mv /asset-input/main /asset-output/'
            ].join(' && ')
          ]
        }
      }),
      handler: 'main',
      memorySize: 512,
      environment: {
        CLIENT_ID: appClientID
      }
    })
```

### What did you expect to happen?

I expected it to deploy all of my lambda functions.

### What actually happened?

It failed with error `Uploaded file must be a non-empty zip`

### CDK CLI Version

2.8.0

### Framework Version

_No response_

### Node.js Version

v16.13.2

### OS

Ubuntu 20.04 on WSL 2

### Language

Typescript

### Language Version

~3.9.7

### Other information

_No response_

### PR DESCRIPTION
**Pull request by rix0rrr**
Here's a possible scenario that can lead to "Uploaded file must be a non-empty zip":

- Bundling starts
- A partial zip file is written
- The process is interrupted (`^C` or similar) while writing.
- On next run, the destination file already exists, is taken to be complete, and uploaded.

In this fix, we'll write the zip to a temporary file and atomically rename it into place once finished, thereby avoiding this possible scenario.

Attempts to fix #18459.

I don't have tests for this, I don't know how to write them properly. To my mind, if the code looks good and we pass integration tests, that should be sufficient. Add a global asset salting mechanism so that we know all asset hashes are always unique.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/cdk-assets/lib/private/archive.ts [hunk 1]
```diff
@@ -44,6 +54,45 @@ export function zipDirectory(directory: string, outputFile: string): Promise<voi
     }
 
     await archive.finalize();
-
   });
+}
+
+/**
+ * Rename the file to the target location, taking into account that we may see EPERM on Windows
```
Comment (MrArnoldPalmer) [inline packages/cdk-assets/lib/private/archive.ts:61]: 🙈

**Review by MrArnoldPalmer — APPROVED** [review]

**Comment by jogold** [comment]
> * On next run, the destination file already exists, is taken to be complete, and uploaded.

How about checking the file size in the cache against `EMPTY_ZIP_FILE_SIZE` here?

https://github.com/aws/aws-cdk/blob/e0c0b56dded26a897dc6243298947bd4e69321b2/packages/cdk-assets/lib/private/handlers/files.ts#L140-L143

**Comment by rix0rrr** [comment]
> How about checking the file size in the cache against EMPTY_ZIP_FILE_SIZE here? (and rezip even if it exists in this case)

That will only catch the case if it's actually empty, not if we succesfully wrote 10MB and yet still failed because were supposed to write 100MB.
