### PR TITLE
fix(pipelines): use display name for `Asset` actions when `publishAssetsInParallel` is false

### LINKED ISSUE #34042: pipelines: action name `FileAsset` changed when `publishAssetsInParallel` is false
### Describe the bug

I have a CodePipline pipeline built by CDK pipelines.

After upgrading to aws-cdk-lib 2.188.0,
`cdk diff` tells me the action name `FileAssets` in the stage `Assets` is about to be changed to a strange name.

This seems occur when pipline's `publishAssetsInParallel` is false.

```
[~] AWS::CodePipeline::Pipeline CodePipeline CodePipelineB74E5936
 └─ [~] Stages
     └─ @@ -119,7 +119,7 @@
        [ ]     "Name": "Synth_Output"
        [ ]   }
        [ ] ],
        [-] "Name": "FileAsset",
        [+] "Name": "MyApp_MyAppStage_Next_Custom_S3AutoDeleteObjectsCustomResourceProvider_Code",
        [ ] "RoleArn": {
        [ ]   "Fn::GetAtt": [
        [ ]     "PipelineCodeBuildActionRole226DB0CB",
[~] AWS::CodeBuild::Project Pipeline/Assets/FileAsset PipelineAssetsFileAsset5D8C5DA6 may be replaced
 └─ [~] Description (may cause replacement)
     ├─ [-] Pipeline step MyApp/CodePipeline/Assets/FileAsset
     └─ [+] Pipeline step MyApp/CodePipeline/Assets/MyApp_MyAppStage_Next_Custom_S3AutoDeleteObjectsCustomResourceProvider_Code
```

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

2.186.0

### Expected Behavior

No template changes.

### Current Behavior

The name of action `FileAssets` has been changed.

### Reproduction Steps

The snnipet of my pipeline follows:

``` ts
const pipeline = new pipelines.CodePipeline(this, 'Pipeline', {
  synth: new pipelines.ShellStep('Synth', {
    input: pipelines.CodePipelineSource.connection('repo/name', 'main', { connectionArn }),
    commands: ['cdk synth'],
  }),
  publishAssetsInParallel: false, // HERE
});
pipeline.addStage(
  new MyAppStage(this, 'MyAppStage'); // stage includes one or more assets
);
```

### Possible Solution

Submitted #34049.

### Additional Information/Context

_No response_

### CDK CLI Version

2.1007.0 (build d3f6c3c)

### Framework Version

_No response_

### Node.js Version

22.14.0

### OS

Ubuntu

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Tietew**
### Issue # (if applicable)

Closes #34042.

### Reason for this change

The action name in `Assets` stage has been changed from `FileAssetN` to the display name of the asset in #33844.

When pipeline's `publishAssetsInParallel` is false, the action name is also changed to the display name of the _first_ asset in stages instead of `FileAsset`.
The action uploads _all_ assets, therefore, its name should indicate "all assets" rather than the first asset.

### Description of changes

Use a specific (stable) display name when `singlePublisher` is true (pipeline's `publishAssetsInParallel` is false), instead of `stackAsset.displayName`.

### Describe any new or updated permissions being added

N/A

### Description of how you validated changes

Added a unit test and a integ test.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/pipelines/lib/helpers-internal/pipeline-graph.ts [hunk 1]
```diff
@@ -344,8 +344,9 @@ export class PipelineGraph {
       const id = stackAsset.assetType === AssetType.FILE
         ? (this.singlePublisher ? 'FileAsset' : `FileAsset${++this._fileAssetCtr}`)
         : (this.singlePublisher ? 'DockerAsset' : `DockerAsset${++this._dockerAssetCtr}`);
+      const displayName = this.singlePublisher ? id : stackAsset.displayName;
```
Comment (matboros) [inline packages/aws-cdk-lib/pipelines/lib/helpers-internal/pipeline-graph.ts:347]: I am not too fond of depending on the id for displayname, as a maintainer assumption would be that that is an implementation detail. What about:
```suggestion
      const getDisplayName: (type: AssetType): string = (type) => {
        switch(type) {
            case AssetType.FILE: return 'FileAsset(s)';
            case AssetType.DOCKER_IMAGE: return 'DockerAsset(s)';
        };
      }
      const displayName = this.singlePublisher ? getDisplayName(stackAsset.assetType) : stackAsset.displayName;
```

File: packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-single-publisher.ts [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+
+    new sqs.Queue(stack, 'OtherQueue');
+  }
+}
+
+const app = new App({
+  postCliContext: {
+    '@aws-cdk/core:newStyleStackSynthesis': '1',
+    '@aws-cdk/aws-codepipeline:defaultPipelineTypeToV2': false,
+    '@aws-cdk/pipelines:reduceStageRoleTrustScope': true,
```
Comment (Abogical) [inline packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-single-publisher.ts:53]: Are these feature flags necessary?

File: packages/aws-cdk-lib/pipelines/lib/helpers-internal/pipeline-graph.ts (hunk 1 above)
Comment (Tietew) [reply packages/aws-cdk-lib/pipelines/lib/helpers-internal/pipeline-graph.ts:347]: Unfortunately, `FileAsset(s)` was replaced by `FileAsset_s_` :(
```
  CHANGED    pipelines/test/integ.newpipeline-single-publisher 3.847s
      Resources
[~] AWS::CodePipeline::Pipeline Pipeline9850B417
 └─ [~] Stages
     └─ @@ -121,7 +121,7 @@
        [ ]     "Name": "Synth_Output"
        [ ]   }
        [ ] ],
        [-] "Name": "FileAsset",
        [+] "Name": "FileAsset_s_",
        [ ] "RoleArn": {
        [ ]   "Fn::GetAtt": [
        [ ]     "PipelineCodeBuildActionRole226DB0CB",
```

Comment (matboros) [reply packages/aws-cdk-lib/pipelines/lib/helpers-internal/pipeline-graph.ts:347]: > Thanks for pointing out. But `switch-case` seems a bit long since `id` uses `?:`...

That might be, but it improves maintainability, since if you add a 3rd asset type, the switch code will stop compiling, while the other will happily assume that the new assets are just DockerAsset, and likely be a bug, unless someone finds all such places.

File: packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-single-publisher.ts (hunk 2 above)
Comment (Tietew) [reply packages/@aws-cdk-testing/framework-integ/test/pipelines/test/integ.newpipeline-single-publisher.ts]: Removed the flags!

File: packages/aws-cdk-lib/pipelines/lib/helpers-internal/pipeline-graph.ts (hunk 1 above)
Comment (matboros) [reply packages/aws-cdk-lib/pipelines/lib/helpers-internal/pipeline-graph.ts]: OK, lets just use plural, that is much more likely to be true.

PS. sorry for the slow answer, I was out for a bit.

File: packages/aws-cdk-lib/pipelines/lib/helpers-internal/pipeline-graph.ts [hunk 3]
```diff
@@ -429,3 +432,12 @@ function findUniqueName(parent: Graph<any>, parts: string[]): string {
   }
   return parts.join('.');
 }
+
+function getDisplayNameForSinglePublishStep(type: AssetType) {
+  switch (type) {
+    case AssetType.FILE:
+      return 'FileAsset';
```
Comment (matboros) [inline packages/aws-cdk-lib/pipelines/lib/helpers-internal/pipeline-graph.ts]:
```suggestion
      return 'FileAssets';
```

File: packages/aws-cdk-lib/pipelines/lib/helpers-internal/pipeline-graph.ts [hunk 4]
```diff
@@ -429,3 +432,12 @@ function findUniqueName(parent: Graph<any>, parts: string[]): string {
...
+    case AssetType.DOCKER_IMAGE:
+      return 'DockerAsset';
```
Comment (matboros) [inline packages/aws-cdk-lib/pipelines/lib/helpers-internal/pipeline-graph.ts]:
```suggestion
      return 'DockerAssets';
```

File: packages/aws-cdk-lib/pipelines/test/codepipeline/codepipeline.test.ts [hunk 5]
```diff
@@ -575,6 +575,32 @@ test('assets can have display names that conflict with calculated action names',
...
+  // THEN
+  const template = Template.fromStack(pipelineStack);
+
+  // We expect a single `FileAsset` action in the pipeline
+  template.hasResourceProperties('AWS::CodePipeline::Pipeline', {
+    Stages: Match.arrayWith([{
+      Name: 'Assets',
+      Actions: [
+        Match.objectLike({
+          Name: 'FileAsset',
```
Comment (matboros) [inline packages/aws-cdk-lib/pipelines/test/codepipeline/codepipeline.test.ts]:
```suggestion
          Name: 'FileAssets',
```

File: packages/aws-cdk-lib/pipelines/test/compliance/assets.test.ts [hunk 6]
```diff
@@ -594,7 +594,7 @@ describe('pipeline with single asset publisher', () => {
         Name: 'Assets',
         Actions: [
           // Only one file asset action
-          Match.objectLike({ RunOrder: 1, Name: 'Asset1' }),
+          Match.objectLike({ RunOrder: 1, Name: 'FileAsset' }),
```
Comment (matboros) [inline packages/aws-cdk-lib/pipelines/test/compliance/assets.test.ts]:
```suggestion
          Match.objectLike({ RunOrder: 1, Name: 'FileAssets' }),
```

File: packages/aws-cdk-lib/pipelines/test/compliance/assets.test.ts [hunk 7]
```diff
@@ -643,7 +643,7 @@ describe('pipeline with custom asset publisher BuildSpec', () => {
...
```
Comment (matboros) [inline packages/aws-cdk-lib/pipelines/test/compliance/assets.test.ts]:
```suggestion
          Match.objectLike({ RunOrder: 1, Name: 'FileAssets' }),
```

**Review by matboros — DISMISSED** [review]

File: packages/aws-cdk-lib/pipelines/lib/helpers-internal/pipeline-graph.ts (hunk 1 above)
Comment (Tietew) [reply packages/aws-cdk-lib/pipelines/lib/helpers-internal/pipeline-graph.ts]: Ok. Fixed.

**Review by matboros — APPROVED** [review]
lgtm
