### PR TITLE
fix(ecr-assets): incorrect handling of nested excludes in .dockerignore

### LINKED ISSUE #13636: (docker assets): .dockerignore is processed incorrectly before 1.73.0 and broken after 1.73.0
I'm using `ContainerImage.fromAsset` to build a Docker image out of my source code, but the .dockerignore file is not correctly processed. My source tree is roughly as follows:

project:
  - build (contains jar)
  - infra (contains all the infrastructure code, and thus cdk.out)
  - src (contains all the source code)
  - Dockerfile
  - .dockerignore

`.dockerignore` contains:
```
**
!build/libs/*.jar
```

When using version 1.93.0, and looking at what is copied over to cdk.out I see the following:
Screenshot 2021-03-16 at 14 28 05
This means that only the . folders and files are copied over, completely ignoring what is in .dockerignore. I manage to locate this issue starting from version 1.73.0. In 1.72.0 I see the following, which is also incorrect:
Screenshot 2021-03-17 at 10 27 42
this is practically copying over all my files and again completely ignoring what is in .dockerignore. This is particularly a problem since I ask for everything to be ignored besides that jar. When I keep the .dockeringore file as it is above, cdk will try to copy everything to cdk.out including cdk.out, which is part of the infra directory and there we get a hell loop that of course breaks with the error:
```
Exception in thread "main" software.amazon.jsii.JsiiException: ENAMETOOLONG: name too long, copyfile '......../infra/cdk.out/asset.9722b878afbb14ee8bf21b7e0a90c692dcb9865f12e685f6e59aead58f9c9c44/infra/......
```

In order to avoid this error, I have to add the infra directory to the .dockerignore file explicitly, like this:
```
**
infra
!build/libs/*.jar
```
but it and everything that isn't the jar should've been ignored by **. 

### What did you expect to happen?
I expected the .dockeringore to be processed (correctly) because of this comment: https://github.com/aws/aws-cdk/issues/5807#issuecomment-576368899. I haven't seen anything like this as part of the documentation.

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by Abogical**
### Issue #13636

Closes #13636.

### Reason for this change

Fixes a bug where asset copying does not correctly process .dockerignore files. CDK did not copy files excluded by a nested exclude pattern in `.dockerignore`.

### Description of changes

Added a new method in `DockerIgnoreStrategy` that determines whether a directory is fully or partially ignored. The method is `DockerIgnoreStrategy.completelyIgnores` and if it returns true, it means that the directory is ignored AND that all of its children are ignored as well. For directories that are ignored but not "completely" ignored, the copyDirectory function will still walk through them.

As this changes the behaviour of asset copying, this can potientally be a breaking change. Therefore, a new feature flag is added which enables this fix. The feature flag is `DOCKER_IGNORE_NESTED_EXCLUDE_FIX`.

### Describe any new or updated permissions being added

No new permissions are added.

### Description of how you validated changes

Unit tests and integration tests are added.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by rix0rrr** [comment]
Please make sure that your PR title confirms to the conventional commit standard (`fix`, `feat`, `chore`) and that it is written in a style that will reflect correctly in the change log. In particular, if this is a bug fix, please describe the bug that was fixed, *not* the change you made. (See [Contributing Guide, Pull Requests](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request))

File: packages/aws-cdk-lib/core/lib/fs/options.ts [hunk 1]
```diff
@@ -85,6 +98,11 @@ export interface CopyOptions extends FileOptions {
    * @default SymlinkFollowMode.NEVER
    */
   readonly follow?: SymlinkFollowMode;
+
+  /**
+   * Extra options for docker ignore mode.
+   */
+  readonly dockerIgnoreOptions?: DockerIgnoreOptions;
```
Comment (rix0rrr) [inline packages/aws-cdk-lib/core/lib/fs/options.ts]: https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md#flat ?

File: packages/aws-cdk-lib/core/lib/fs/options.ts [hunk 2]
```diff
@@ -58,6 +58,19 @@ export enum IgnoreMode {
...
+ * Extra options for docker ignore mode.
+ */
+export interface DockerIgnoreOptions {
+  /**
+   * If this is set to true, then when processing .dockerignore files, copy files that were excluded with a nested exclude pattern.
+   *
+   * @see {@link https://github.com/aws/aws-cdk/issues/13636} for more info on the bug this option fixes.
+   * @default true if the feature flag DOCKER_IGNORE_NESTED_EXCLUDE_FIX is set to true, otherwise false
+   */
+  readonly copyNestedExcludes?: boolean;
```
Comment (rix0rrr) [inline packages/aws-cdk-lib/core/lib/fs/options.ts]: Why would you copy "excludes" ?

Does this mean `respectedNestedIgnoreFiles` ?

File: packages/aws-cdk-lib/core/lib/fs/options.ts (hunk 1 above)
Comment (Abogical) [reply packages/aws-cdk-lib/core/lib/fs/options.ts]: Flattened the property.

File: packages/aws-cdk-lib/core/lib/fs/options.ts (hunk 2 above)
Comment (Abogical) [reply packages/aws-cdk-lib/core/lib/fs/options.ts]: "respect" seems to be a better description. I've renamed it to `dockerIgnoreRespectNestedExcludes`

Comment (rix0rrr) [reply packages/aws-cdk-lib/core/lib/fs/options.ts]: I think this is a bit verbose. Can you shorten it? For example, do both ignore and exclude not refer to the same thing? So do we need both?

Comment (rix0rrr) [reply packages/aws-cdk-lib/core/lib/fs/options.ts]: `respectNestedDockerIgnores`?

Comment (Abogical) [reply packages/aws-cdk-lib/core/lib/fs/options.ts]: "exclude" means something that is excluded from the .dockerignore, so an exclude and ignore are not the same thing, they're the opposite.

```
**            # Ignore
!build/*.js   # Exclude  
```

Comment (Abogical) [reply packages/aws-cdk-lib/core/lib/fs/options.ts]: It is verbose, but I don't think there's a good way to shorten it.

Comment (rix0rrr) [reply packages/aws-cdk-lib/core/lib/fs/options.ts]: Wait, are you saying that:

In nested `.dockerignore` files, we do respect positive (ignore) declarations, but we didn't use to respect negative (dont-ignore) declarations?

Comment (rix0rrr) [reply packages/aws-cdk-lib/core/lib/fs/options.ts]: So we were ignoring more files than necessary?

Comment (rix0rrr) [reply packages/aws-cdk-lib/core/lib/fs/options.ts]: In that case, I'm leaning towards this not needing a flag. Because we will only ever include more files into the bundle, right? We will never accidentally include too few files.

Which means the chances if this breaking someone are vanishingly small?

Comment (Abogical) [reply packages/aws-cdk-lib/core/lib/fs/options.ts]: Yes @rix0rrr , we were ignoring more files than necessary.

The behavior of including more files in the docker image is undefined. Chance of breaking change is still small regardless. If you think it's safe to remove the feature flag, I can do so.

**Review by rix0rrr — APPROVED** [review]
