### PR TITLE
fix(s3-deployment): broken cross stack reference when using Source.data

### LINKED ISSUE #22843: @aws-cdk/aws-s3-deployment: broken cross stack reference when used in Source.jsonData
### Describe the bug

I'm trying to use `S3Deployment` with a `Source.jsonData` source to deploy a json configuration file with values resolved at deploy time (eg cognito userpool id). These values, properties of a construct from another nested stack passed as StackProp to the S3Deployment nested stack, doesn't get resolved properly. 

### Expected Behavior

When I use values from another stack construct in a `Source.jsonData` source with `S3Deployment`, they are properly resolved at deploy time.

### Current Behavior

A 'unresolved resource dependencies' error is thrown.
```
1:20:17 PM | CREATE_FAILED        | AWS::CloudFormation::Stack | DeploymentNestedSt...ckResource3980C4F4
Template format error: Unresolved resource dependencies [UserPool6BA7E5F2] in the Resources block of the template

        new NestedStack (nested-stack.ts:133:21)
        \_ new DeploymentNestedStack (nested-stack-ref-bug-repro-lowing resource(s) failed to create: [ResourceNestedStackNestedStackResourceNestedStackNestedStackResourceCDDDB2BF, DeploymentNestedStackNestedStackDeploymentNestedStackNested
stack-bug-repro/app.ts:19:5)
        \_ new MainStack nest-stack-ref-bug-repro/app.ts:33:5)
        \_ Object.<anonymous> (nested-stack-b
ug-repro/app.ts:38:1)
        \_ Module._compile (internal/modules/cjs/loader.js:1072:14)
        \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
        \_ Module.load (internal/modules/cjs/loader.js:937:32)
        \_ Function.Module._load (internal/modules/cjs/loader.js:778:12)
        \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
        \_ internal/main/run_main_module.js:17:47
```

### Reproduction Steps

```typescript
import { App, Construct, Stack, NestedStack, StackProps, NestedStackProps } from '@aws-cdk/core'
import { UserPool, IUserPool } from '@aws-cdk/aws-cognito'
import { BucketDeployment, Source } from '@aws-cdk/aws-s3-deployment'
import { Bucket } from '@aws-cdk/aws-s3'

class ResourceNestedStack extends NestedStack {
  userPool: UserPool
  constructor (scope: Construct, id: string, props: NestedStackProps = {}){
    super(scope, id, props)
    this.userPool = new UserPool(this, 'UserPool')
  }
}

interface DeploymentNestedStackProps extends NestedStackProps {
  userPool: IUserPool
}
class DeploymentNestedStack extends NestedStack {
  constructor (scope: Construct, id: string, props: DeploymentNestedStackProps){
    super(scope, id, props)
    const bucket = new Bucket(this, 'Bucket')
    new BucketDeployment(this, 'Deployment', {
      destinationBucket: bucket,
      sources          : [
        Source.jsonData('appconfig.json', { userPoolId: props.userPool.userPoolId })
      ]
    })
  }
}
class MainStack extends Stack {
  constructor (scope: Construct, id: string, props: StackProps = {}){
    super(scope, id, props)
    const resourceNestedStack = new ResourceNestedStack(this, 'ResourceNestedStack')
    new DeploymentNestedStack(this, 'DeploymentNestedStack', { userPool: resourceNestedStack.userPool })
  }
}

const app = new App()
new MainStack(app, 'MainStack', {
  env: { account, region }
})


```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

1.180.0

### Framework Version

_No response_

### Node.js Version

14.19.0

### OS

Debian GNU/Linux 10 (buster)

### Language

Typescript

### Language Version

4.4.2

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Abogical**
### Issue #22843

Closes #22843.

### Reason for this change

The s3-deployment construct implementation had its own implmenetation of resolving references. This is unnecessary as these references should be resolved in the synthesis stage. Furthermore, this implementation did not support cross-stack references.

### Description of changes

The construct will now pass the tokens as is and let the app synthesis take care of resolving the references instead as expected. Non-tokens will not use markers.

Note: Credits to @smnrd who has written the reproduction steps here: https://github.com/aws/aws-cdk/issues/22843
This has helped in writing the nested stack integration test.

### Describe any new or updated permissions being added

No new permissions are added.

### Description of how you validated changes

Unit tests, Integrations tests, and manually via the AWS console.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts [hunk 1]
```diff
@@ -224,7 +224,11 @@ export class Source {
     }
     return {
       bind: (scope: Construct, context?: DeploymentSourceContext) => {
-        return Source.data(objectKey, Stack.of(scope).toJsonString(obj), markersConfig).bind(scope, context);
+        return Source.data(
+          objectKey,
+          Token.isUnresolved(obj)? Stack.of(scope).toJsonString(obj) : JSON.stringify(obj),
```
Comment (vishaalmehrishi) [inline packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts]: Let's move this to a separate statement with a meaningful variable name to explain the rationale for this condition

**Comment by tmokmss** [comment]
Note that this approach was once abandoned because it does not work well with larger files (https://github.com/aws/aws-cdk/issues/12903, https://github.com/aws/aws-cdk/pull/18659).

However, I think most use cases for this feature involve small files (e.g., `.env`), so it's a valuable trade-off imo. We might need something like `Source.dataV2` to avoid breaking changes though.

**Comment by Abogical** [comment]
@tmokmss

> Note that this approach was once abandoned because it does not work well with larger files (#12903, [#18659 ](https://github.com/aws/aws-cdk/pull/18659)).
> 
> However, I think most use cases for this feature involve small files (e.g., `.env`), so it's a valuable trade-off imo. We might need something like `Source.dataV2` to avoid breaking changes though.

- Just to be clear, are you saying that there was a previous implementation that directly passed tokens to markers? If so, where could I find it? I can't find any references to this on the links you provided.
- Likewise, I can't find an explanation on why this is will not work well with larger files.
- I don't see how this can be a breaking change, the assets once deployed will emit the same output as confirmed by the integration tests.

**Comment by tmokmss** [comment]
Hi @Abogical, sorry about my incomplete comment! I did a bit of archaeology on this issue before, and I can't resist commenting on it 🥲 

As far as I understand, this implementation is essentially the same as the one in the comment https://github.com/aws/aws-cdk/issues/12903#issuecomment-920397916, which passes the entire file content to the custom resource. However, another user claims that this approach has a size limit: https://github.com/aws/aws-cdk/issues/12903#issuecomment-964315506.

This is why the current hacky implementation with marker replacement is used. It should reduce the payload size for the custom resource in many cases.

I guess the current integration tests do not include test cases with large files. However, as long as the file size limit decreases, I think this can be a breaking change.

**Comment by Abogical** [comment]
> Hi @Abogical, sorry about my incomplete comment! I did a bit of archaeology on this issue before, and I can't resist commenting on it 🥲
> 
> As far as I understand, this implementation is essentially the same as the one in the comment [#12903 (comment)](https://github.com/aws/aws-cdk/issues/12903#issuecomment-920397916), which passes the entire file content to the custom resource. However, another user claims that this approach has a size limit: [#12903 (comment)](https://github.com/aws/aws-cdk/issues/12903#issuecomment-964315506).
> 
> This is why the current hacky implementation with marker replacement is used. It should reduce the payload size for the custom resource in many cases.
> 
> I guess the current integration tests do not include test cases with large files. However, as long as the file size limit decreases, I think this can be a breaking change.

Thanks for the clarification @tmokmss . You're right, I can see the case for this when using big json files in a single `jsonData` call. This PR combines all of the file contents into a single marker if it contains at least one token. Its an edge case that can indeed be a breaking change.

I'll have to modify the PR to handle this. I think a solution to this is for each token to have its own marker, but no token should be resolved regardless before synth.

Thank you for bringing this up! I'll mark this PR as `do-not-merge`.

File: packages/aws-cdk-lib/aws-s3-deployment/lib/render-data.ts [hunk 2]
```diff
@@ -1,82 +1,37 @@
...
-    }
-
-    const marker = `<<marker:0xbaba:${markerIndex++}>>`;
-    result.push(marker);
-    markers[marker] = part;
-  }
-
-  return { text: result.join(''), markers };
+  return {
+    text: Tokenization.reverseString(data).mapTokens(tokenMapper).join(new StringConcat()),
```
Comment (vishaalmehrishi) [inline packages/aws-cdk-lib/aws-s3-deployment/lib/render-data.ts:40]: This would benefit from a comment explaining what is being done, and more importantly _why_ (especially the `reverseString` part). Anyone trying to change this in the future will understand the risks better.

File: packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts [hunk 3]
```diff
@@ -241,7 +246,10 @@ export class Source {
   public static yamlData(objectKey: string, obj: any): ISource {
     return {
       bind: (scope: Construct, context?: DeploymentSourceContext) => {
-        return Source.data(objectKey, Stack.of(scope).toYamlString(obj)).bind(scope, context);
+        return Source.data(
+          objectKey,
+          Token.isUnresolved(obj)? Stack.of(scope).toYamlString(obj) : yaml_cfn.serialize(obj),
```
Comment (vishaalmehrishi) [inline packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts]: Let's move this to a separate statement with a meaningful variable name to explain the rationale for this condition

**Comment by tmokmss** [comment]
I think this looks good 👍 It's clear and more straightforward. (not entirelly sure why the hacky approach was initially taken though.)

File: packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts [hunk 4]
```diff
@@ -224,7 +225,15 @@ export class Source {
     }
     return {
       bind: (scope: Construct, context?: DeploymentSourceContext) => {
-        return Source.data(objectKey, Stack.of(scope).toJsonString(obj), markersConfig).bind(scope, context);
+        // toJsonString can generate extra tokens that would not be needed if the obj is not a token
```
Comment (vishaalmehrishi) [inline packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts:228]: Is it feasible to fix `toJsonString`/`toYamlString` to deal with this instead? If these functions are used in other places in the future, they might need conditional checks as well.

This is not a blocker, since getting the issue resolved is more important. If there is no straightforward path to fix the functions directly, let's add a backlog issue.

File: packages/aws-cdk-lib/aws-s3-deployment/lib/render-data.ts [hunk 5]
```diff
@@ -1,82 +1,44 @@
...
-type FnSelect = { 'Fn::Select': [number, string[] | FnSplit] };
+/**
+ * Renders the given string data as deployable content with markers substituted
+ * for all tokens.
+ *
+ * @param data The input data
+ * @returns The markered text (`text`) and a map that maps marker names to their
+ * values (`markers`).
+ */
+export function renderData(data: string): Content {
```
Comment (vishaalmehrishi) [inline packages/aws-cdk-lib/aws-s3-deployment/lib/render-data.ts:34]: Just noticed we don't have existing or new tests for this. IMO this would benefit from a unit test to prevent future regressions.

Comment (Abogical) [reply packages/aws-cdk-lib/aws-s3-deployment/lib/render-data.ts:34]: Unit tests for `renderData` are already added in `content.test.ts`.

Comment (vishaalmehrishi) [reply packages/aws-cdk-lib/aws-s3-deployment/lib/render-data.ts:34]: Ah, my bad. Thanks for clarifying!

File: packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts (hunk 4 above)
Comment (Abogical) [reply packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts:228]: `toJsonString` and `toYamlString` is used by different functions across CDK, so changing it has a high impact. The functions' behavior isn't a bug as they produce the correct values once resolved. Its just that within the context of our fix, we'd like to not generate extra tokens as we's like to process the underlying tokens directly to eventually replace them with markers.

Comment (vishaalmehrishi) [reply packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts:228]: Makes sense, thanks for clarifying.

**Review by vishaalmehrishi — APPROVED** [review]
