### PR TITLE
fix(ecs): update logic for secret JSON field with fargate task to fail

### LINKED ISSUE #7272: The new `ecs.Secret.fromSecretsManager(secret, field?)` is not working
There was an enhancement recently in CDK 1.32.0 for the `ecs.Secret.fromSecretsManager(secret, field?)` function. See: https://github.com/aws/aws-cdk/pull/6435/files

I actually want to use this but the container could not be started anymore. 

### Reproduction Steps

Make something like this:

```typescript
const cluster = new DatabaseCluster(this, 'Database', {
    engine: DatabaseClusterEngine.AURORA,
    masterUser: {
        username: 'admin'
    },
    instanceProps: {
        instanceType: ec2.InstanceType.of(ec2.InstanceClass.BURSTABLE2, ec2.InstanceSize.SMALL),
        vpc
    }
});

const loadBalancedFargateService = new ApplicationLoadBalancedFargateService(stack, 'Service', {
  cluster,
  memoryLimitMiB: 1024,
  cpu: 512,
  taskImageOptions: {
    image: ContainerImage.fromRegistry("amazon/amazon-ecs-sample"),
    secrets: {
      // Assign a JSON value from the secret to a environment variable
      MYSQL_HOST: Secret.fromSecretsManager(cluster.secret!, 'host'),
      MYSQL_PORT: Secret.fromSecretsManager(cluster.secret!, 'port'),
      MYSQL_USER: Secret.fromSecretsManager(cluster.secret!, 'username'),
      MYSQL_PASSWORD: Secret.fromSecretsManager(cluster.secret!, 'password'),
      MYSQL_DATABASE: Secret.fromSecretsManager(cluster.secret!, 'dbname'),
    }
  },
});
```

### Error Log

The container cannot be startet. The following was logged:

```
Fetching secret data from AWS Secrets Manager in region eu-central-1: secret arn:aws:secretsmanager:eu-central-1:123456789012:secret:DatabaseSecret3B817195-FpDznCMLC1bE-q13DbL:dbname::: ValidationException: Invalid name. Must be a valid name containing alphanumeric characters, or any of the following: -/_+=.@! status code: 400, request id: 9be60361-22a6-46be-a084-2370d3b63718;
```
The CloudFormation Template was generated like this:

```json
{
  "Name": "MYSQL_PASSWORD",
  "ValueFrom": {
    "Fn::Join": [
      "",
      [
        {
          "Ref": "DatabaseSecretAttachmentE5D1B020"
        },
        ":password::"
      ]
    ]
  }
}
```

I'm pretty sure that there is a `:SecretString` missing in between. Because it was referenced in another location like this:

```json
"MasterUserPassword": {
  "Fn::Join": [
    "",
    [
      "{{resolve:secretsmanager:",
      {
        "Ref": "DatabaseSecret3B817195"
      },
      ":SecretString:password::}}"
    ]
  ]
}
```

### Environment

  - **CLI Version      :** aws-cli/2.0.7 Python/3.8.2 Darwin/19.4.0 botocore/2.0.0dev11
  - **Framework Version:** 1.32.0
  - **OS               :** OSX 10.15.4
  - **Language         :** Typescript

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by jogold**
### Commit Message
fix(ecs): using secret JSON field with fargate task does not fail (#7317)

For tasks that use the Fargate launch type, it is only supported to inject
the full contents of a secret as an environment variable. Specifying a specific
JSON key or version is not supported at this time.

Also clean up/refactor a bit.

See https://docs.aws.amazon.com/AmazonECS/latest/userguide/specifying-sensitive-data-secrets.html#secrets-considerations

Closes #7272
### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-ecs/lib/container-definition.ts [hunk 1]
```diff
@@ -551,23 +564,35 @@ export class ContainerDefinition extends cdk.Construct {
...
+  private renderSecrets(): CfnTaskDefinition.SecretProperty[] | undefined {
+    if (!this.props.secrets) {
+      return undefined;
+    }
+
+    const secrets: CfnTaskDefinition.SecretProperty[] = [];
+
+    for (const [k, v] of Object.entries(this.props.secrets)) {
+      if (this.taskDefinition.isFargateCompatible && v.hasField) {
+        throw new Error(`Cannot specify secret JSON field for a task using the FARGATE launch type: '${k}' in container '${this.node.id}'`);
```
Comment (jogold) [inline packages/@aws-cdk/aws-ecs/lib/container-definition.ts:585]: Do this here or in the constructor?

Comment (pkandasamy91) [reply packages/@aws-cdk/aws-ecs/lib/container-definition.ts:585]: This would probably make more sense to be in the constructor.

**Comment by jogold** [comment]
@pkandasamy91 can you give another look?

File: packages/@aws-cdk/aws-ecs/lib/container-definition.ts [hunk 2]
```diff
@@ -36,11 +36,24 @@ export abstract class Secret {
...
   public abstract readonly arn: string;
+
+  /**
+   * Whether this secret uses a specific JSON field
+   */
+  public abstract readonly hasField?: boolean;
+
+  /**
+   * Grants reading the secret to a principal
+   */
```
Comment (efekarakus) [inline packages/@aws-cdk/aws-ecs/lib/container-definition.ts:56]: Thank you for adding comments to the public fields!
