### PR TITLE
fix(efs): EFS fails to create when using a VPC with multiple subnets per availability zone

### LINKED ISSUE #10170: [aws-efs] New EFS fails to create due to : "fsmt-123456 already exists in stack..." on existing VPC with other EFS mounts
When creating a new stack and just trying to create a new EFS, I receive numerous errors:

> fsmt-96f68d16 already exists in stack arn:aws:cloudformation:us-east-1:311209486165:stack/CodepipelineForEcrStack/9eee4d30-ee60-11ea-ab6f-12717722e021

Once for each subnet.

### Reproduction Steps

I am doing:
```
import * as cdk from '@aws-cdk/core';
import { Vpc } from '@aws-cdk/aws-ec2';
import { FileSystem, PerformanceMode, ThroughputMode } from '@aws-cdk/aws-efs';

export class CodepipelineForEcrStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // Import VPC
    const vpc = Vpc.fromLookup(this, "CdkTestVPC", {
      vpcId: "vpc-xxxxxxx"
    });

    // EFS
    const _efsName = 'cdkTest';
    const _efs = new FileSystem(this, 'CdkTestEFS', {
      vpc: vpc,
      performanceMode: PerformanceMode.GENERAL_PURPOSE,
      throughputMode: ThroughputMode.BURSTING,
      // fileSystemName: _efsName,
      removalPolicy: cdk.RemovalPolicy.DESTROY, // Destroy EFS when we delete the stack
    });    

  }
}
```

Then when I `cdk deploy` I get numerous errors about the file system mounts already exist.
During my numerous tests, I also was able to confirm [this issue](https://github.com/aws/aws-cdk/issues/7323) too.

I have manually checked and deleted both security groups and network interfaces but I still get these errors.

When the stack is rolled back, the security groups and the network interfaces persist. I have to manually delete them.

I am new to the CDK but I would expect that to launch the EFS into my existing VPC. 

### What did you expect to happen?

I was trying to create an EFS.

I was also hoping to control the subnets this mounted to but it seems to mount to all subnets as this is how many fsmt's it tried to deploy.

### What actually happened?

I received numerous errors:

> fsmt-96f68d16 already exists in stack arn:aws:cloudformation:us-east-1:311209486165:stack/CodepipelineForEcrStack/9eee4d30-ee60-11ea-ab6f-12717722e021

One of these for each fsmt for each subnet.

Then the stack rollsback and it takes 2 hours to resolve (only on EFS rollback). I spent 14 hours today on 7 edits... literally. Found it was faster to delete the efs parts myself to speed up the time. Didn't find this out until just now...

### Environment

  - **CLI Version      :** 1.61.1 (build 347918f)
  - **Framework Version:** 1.61.1 
  - **Node.js Version:**  v12.18.3
  - **OS               :** Linux Zeus 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
  - **Language (Version):** typescript (3.9.7)

### Other

I ran into this issue while working on my stack. I then decided to just try to create just the EFS and that's when I realized I was not able to do this. 

At first, I thought it was due to me using a custom name. So I commented that out and it still happens.

In case this helps, I just commented out my stack and used the code I posted above. Since it was in the same stack just destroyed than deployed, I don't think this would be an issue but wanted to make note.

Also, this VPC already has 2 EFS mounts in it that are named something completely different.

Thank you.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by daisuke-yoshimoto**
Fixes #10170

### Fixes

This PR has been modified so that it does not create a mount target if only VPC is specified in the EFS file system. 

### Bug

Currently, if a VPC is specified and no subnet is specified, the subnet search criteria are passed as undefined, all subnets in the VPC are retrieved, and mount targets are generated for all subnets in the VPC. I will. Since mount targets can only be created in one subnet for each Availability Zone, the above behavior will result in duplicate Availability Zones between mount targets, resulting in an error when creating the mount target.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by daisuke-yoshimoto** [comment]
This fix breaks the existing test. Existing tests expect a mount target to be created even if you only specify vpc. Is this the expected specification?

https://github.com/aws/aws-cdk/blob/3578d8434f842a5b5a7290b1d0108818cdaae0f6/packages/%40aws-cdk/aws-efs/test/efs-file-system.test.ts#L15

File: packages/@aws-cdk/aws-efs/lib/efs-file-system.ts [hunk 1]
```diff
@@ -272,11 +272,13 @@ export class FileSystem extends Resource implements IFileSystem {
       defaultPort: ec2.Port.tcp(FileSystem.DEFAULT_PORT),
     });
 
+    this.mountTargetsAvailable = [];
+    if (props.vpcSubnets === undefined) return;
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-efs/lib/efs-file-system.ts:276]: let's add a test for this. should there be a warning or error to indicate that mounts targets are not created

**Review by shivlaks — CHANGES_REQUESTED** [review]

**Comment by shivlaks** [comment]
@daisuke-yoshimoto thanks for submitting this fix! i'd been trying to reproduce the failure conditions for a little bit now. can you ensure you update the commit details to include the scenario where this case materializes?

It should be captured in the commit details along with the approach taken to resolve it.

**Review by shivlaks — DISMISSED** [review]
moving to `request changes` as mergify dismissed previous review - but there's still outstanding feedback.

**Comment by daisuke-yoshimoto** [comment]
@shivlaks 

Thank you for your review.

So, I will follow the instructions and write the explanation and add the test.

As for the specifications, like the console screen and CloudFormation, if we specify only VPC, the mount target will not be generated, so it's okay, isn't it?

**Comment by daisuke-yoshimoto** [comment]
@shivlaks 

Sorry I made you wait. I wrote a description of the PR and fixed the test cases.

**Comment by daisuke-yoshimoto** [comment]
@shivlaks

Can you please review this PR?
I wrote a description of the PR and fixed the test cases.

**Comment by daisuke-yoshimoto** [comment]
@shivlaks

Can you please review this PR?
I wrote a description of the PR and fixed the test cases.

File: packages/@aws-cdk/aws-efs/lib/efs-file-system.ts (hunk 1 above)
Comment (iliapolo) [inline packages/@aws-cdk/aws-efs/lib/efs-file-system.ts:276]: Using `return` is dangerous here. Imagine this line changes location during some refactoring, it will now prevent all other logic in the constructor to run.

better to do:

```ts
if (props.vpcSubnets) {
  // configure mounts here
}
```

File: packages/@aws-cdk/aws-efs/test/integ.efs.ts [hunk 2]
```diff
@@ -9,6 +9,7 @@ const vpc = new ec2.Vpc(stack, 'Vpc', { maxAzs: 3, natGateways: 1 });
 
 const fileSystem = new FileSystem(stack, 'FileSystem', {
   vpc,
+  vpcSubnets: vpc.selectSubnets(undefined),
```
Comment (iliapolo) [inline packages/@aws-cdk/aws-efs/test/integ.efs.ts:12]: This doesn't seem right.

1. Why is this needed? the `FileSystem` construct will already call `selectSubnets` with `undefined`.
2. The `selectSubnets` method returns `SelectedSubnets`, and not `SubnetSelection`, those two interfaces are not meant to be interchangeable, the fact they currently pass structural typing is somewhat accidental.

I'm pretty sure we can drop this change.

File: packages/@aws-cdk/aws-lambda/test/function.test.ts [hunk 3]
```diff
@@ -1822,6 +1822,7 @@ describe('function', () => {
 
       const fs = new efs.FileSystem(stack, 'Efs', {
         vpc,
+        vpcSubnets: vpc.selectSubnets(undefined),
```
Comment (iliapolo) [inline packages/@aws-cdk/aws-lambda/test/function.test.ts:1825]: Same here

File: packages/@aws-cdk/aws-efs/test/efs-file-system.test.ts [hunk 4]
```diff
@@ -22,7 +22,7 @@ test('default file system is created correctly', () => {
     DeletionPolicy: 'Retain',
     UpdateReplacePolicy: 'Retain',
   }, ResourcePart.CompleteDefinition));
-  expectCDK(stack).to(haveResource('AWS::EFS::MountTarget'));
+  expectCDK(stack).notTo(haveResource('AWS::EFS::MountTarget'));
```
Comment (iliapolo) [inline packages/@aws-cdk/aws-efs/test/efs-file-system.test.ts:25]: Thats ok, but we also need an additional test to make sure mounts are created when we expect them to.

**Comment by iliapolo** [comment]
@daisuke-yoshimoto Thanks for the PR, and apologies for the delayed response. 

I've taken over this one from @shivlaks. See my comments.

**Comment by iliapolo** [comment]
@daisuke-yoshimoto Should I do another round?

**Comment by iliapolo** [comment]
@daisuke-yoshimoto This is great, but missing a test.

**Comment by iliapolo** [comment]
@daisuke-yoshimoto You still up for wrapping this one out? Just a simple unit test would do.

File: packages/@aws-cdk/aws-efs/test/efs-file-system.test.ts [hunk 5]
```diff
@@ -240,3 +240,27 @@ test('can specify backup policy', () => {
...
+  });
+  new FileSystem(stack, 'EfsFileSystem', {
+    vpc,
+  });
+  // THEN
+  expectCDK(stack).to(haveResource('AWS::EFS::FileSystem', {
+    DeletionPolicy: 'Retain',
+    UpdateReplacePolicy: 'Retain',
+  }, ResourcePart.CompleteDefinition));
+  expectCDK(stack).to(haveResource('AWS::EFS::MountTarget'));
```
Comment (iliapolo) [inline packages/@aws-cdk/aws-efs/test/efs-file-system.test.ts:264]: This doesn't strictly assert that only one mount target is created per az. You should validate that only one such resource exists.

**Review by iliapolo — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-efs/test/efs-file-system.test.ts [hunk 6]
```diff
@@ -240,3 +240,46 @@ test('can specify backup policy', () => {
...
+        1,
+        {
+          'Fn::GetAZs': '',
+        },
+      ],
+    },
+  }));
+  expectCDK(stack).to(countResources('AWS::EFS::MountTarget', 2));
+  expectCDK(stack).to(haveResource('AWS::EFS::MountTarget', {
+    SubnetId: {
```
Comment (iliapolo) [inline packages/@aws-cdk/aws-efs/test/efs-file-system.test.ts:276]: Why does this ensure that the mount targets are created in different az's? 

Seems to me that the subnets you are asserting on might be in the same AZ.

I think your previous approach was good, creating a vpc with a single az and two subnets, you just needs to assert only a single mount target was created even though there are two subnets in the VPC.

File: packages/@aws-cdk/aws-efs/test/efs-file-system.test.ts [hunk 7]
```diff
@@ -240,3 +240,36 @@ test('can specify backup policy', () => {
...
+    AvailabilityZone: {
+      'Fn::Select': [
+        0,
+        {
+          'Fn::GetAZs': '',
+        },
+      ],
+    },
+  }));
+  expectCDK(stack).to(countResources('AWS::EFS::MountTarget', 2));
```
Comment (iliapolo) [inline packages/@aws-cdk/aws-efs/test/efs-file-system.test.ts:274]: Can be simplified by creating the VPC in such a way that it satisfied the conditions of the test. It's also not necessary to assert on the VPC, we can trust it behaves as the API says it does.

```suggestion
  // create a vpc with two subnets in the same availability zone.
  const oneAzVpc = new ec2.Vpc(stack, 'Vpc', {
    maxAzs: 1,
    subnetConfiguration: [{ name: 'One', subnetType: ec2.SubnetType.ISOLATED }, { name: 'Two', subnetType: ec2.SubnetType.ISOLATED }],
    natGateways: 0,
  });
  new FileSystem(stack, 'EfsFileSystem', {
    vpc: oneAzVpc,
  });
  // make sure only one mount target is created.
  expectCDK(stack).to(countResources('AWS::EFS::MountTarget', 1));
```

**Review by iliapolo — APPROVED** [review]

File: packages/@aws-cdk/aws-efs/test/efs-file-system.test.ts [hunk 8]
```diff
@@ -1,4 +1,4 @@
-import { expect as expectCDK, haveResource, ResourcePart } from '@aws-cdk/assert';
+import { expect as expectCDK, haveResource, ResourcePart, countResources, countResourcesLike } from '@aws-cdk/assert';
```
Comment (iliapolo) [inline packages/@aws-cdk/aws-efs/test/efs-file-system.test.ts:1]:
```suggestion
import { expect as expectCDK, haveResource, ResourcePart, countResources } from '@aws-cdk/assert';
```

**Review by iliapolo — APPROVED** [review]

**Review by iliapolo — APPROVED** [review]
