### PR TITLE
fix(elasticloadbalancingv2): ALB listeners with multiple forwardi…

### LINKED ISSUE #24805: elbv2: addTargetGroups add only 1 target group.
### Describe the bug

ApplicationListener.addTargets(id, props) fails to add more than 1 target group to the rule created. When adding more than one target group via this function the resulting template only has the second targetgroup on the array added to the loadbalancer listener rule. 

### Expected Behavior

All target groups are added with the same weight to the created rule. per the documentation.

Load balance incoming requests to the given load balancing targets.

This method implicitly creates an ApplicationTargetGroup for the targets involved, and a 'forward' action to route traffic to the given TargetGroup.

If you want more control over the precise setup, create the TargetGroup and use addAction yourself.

It's possible to add conditions to the targets added in this way. At least one set of targets must be added without conditions.

### Current Behavior

Only the second targetgroup in the array of target groups for the props is added. 

### Reproduction Steps

```ts
for (let index = 0; index < totalContainers; index++) {
      var containerDefinition = taskDefinition.addContainer('UnityContainer_' + index, {
        containerName: 'unity-render-' + index,
        image: ecs.ContainerImage.fromEcrRepository(repo),
        portMappings: [{ containerPort: 21075 }],
        memoryReservationMiB: 4096,
        cpu: 2048,
        environment:{wb_environment:"dev"},
        secrets: {wb_secret: ssmSecret},
        privileged: true,
        logging: ecs.LogDriver.awsLogs({ streamPrefix: 'unity-render', logGroup: containerLogs })
      });
      containerDefinition.addMountPoints({ containerPath: '/tmp', sourceVolume: 'tmp', readOnly: false })
     let targetGroup = new elbv2.ApplicationTargetGroup(ecsService, `ecsTarget-${process.env.CDK_ENV}-${index}`, {
        port: 80,
        targets: [ecsService.loadBalancerTarget({
          containerName: containerDefinition.containerName,
          containerPort: 21075,
        })],
        targetType: elbv2.TargetType.INSTANCE,
        targetGroupName: `ecsTarget-${process.env.CDK_ENV}-${index}`,
        deregistrationDelay: cdk.Duration.seconds(45),
        healthCheck: {
          interval: cdk.Duration.seconds(15),
          path: '/test/ok',
          timeout: cdk.Duration.seconds(5)
        },
        vpc: vpc,
      });
      ecsTargets.push(ecsTarget); 
     }
const http80Listener = lb.addListener(`HTTP-80-${process.env.CDK_ENV}`, {
      port: 80,
      open: true,
    });

 http80Listener.addTargetGroups('test',{
      targetGroups: ecsHttpTargets,
      conditions: [
        elbv2.ListenerCondition.pathPatterns(['/mypath/*'])
      ],
      priority:10
    })
```

### Possible Solution

Resulting template adds both targetgroups to the rule

### Additional Information/Context

_No response_

### CDK CLI Version

2.69.0 (build 60a5b2a)

### Framework Version

aws-cdk-lib@2.69.0

### Node.js Version

v16.13.1

### OS

22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:50:36 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6020 arm64

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Styerp**
…ng targets need weights specified

The [ELB docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#forward-actions) on this aren't explicit, but the examples do _not_ show a configuration with multiple targets, but no weighting. This change assigns a weight to the action, if one wasn't specified.

If specifying stickiness, but no weight, the template will change.

Fixes #24805.

Results in CFN like
  LBListener49E825B4:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - ForwardConfig: TargetGroups: - TargetGroupArn: Ref: TargetGroupOne7810CAFB Weight: 1 - TargetGroupArn: Ref: TargetGroupTwo593946E1 Weight: 1 Type: forward

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by Styerp** [comment]
From a design perspective:

I followed the intent of the construct in making the weights equal. There may be nuances around other actions and their weights I did not consider when choosing 1 as the weight. I'm not sure if what weights add up to is important or if it's just what % of the whole they are, for example. Any guidance or feedback welcome. 

From a rules of contribution perspective:

I haven't been able to get the integ test to actually run from within the aws-cdk repo, so I can't generate the snapshot. I can run it in a different project, link the cdk, re-install @aws-cdk/integ-runner (because it has broken references right now), then run the integ tests. The CFN template for the integration test is ostensibly valid, but deployment fails before the change. Thoughts?

File: packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener-rule.ts [hunk 1]
```diff
@@ -254,9 +254,9 @@ export class ApplicationListenerRule extends Construct {
       this.configureAction(props.action);
     }
 
-    (props.targetGroups || []).forEach((group) => {
-      this.configureAction(ListenerAction.forward([group]));
-    });
+    if(props.targetGroups) {
+        this.configureAction(ListenerAction.forward(props.targetGroups));
```
Comment (otaviomacedo) [inline packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener-rule.ts:258]: Wouldn't only this change be enough?

**Review by otaviomacedo — APPROVED** [review]

**Review by otaviomacedo — APPROVED** [review]
