### PR TITLE
fix(lambda-nodejs): unable to use `nodeModules` with pnpm

### LINKED ISSUE #21910: (lambda-nodejs): Unable to use `nodeModules` with pnpm
### Describe the bug

The `nodeModules` prop in `bundling` does not work with pnpm for two reasons:

- pnpm uses symlinks, meaning that only direct dependencies are put in the `node_modules` directory. This means that when `nodeModules` is bundled, it only includes direct dependencies and not sub-dependencies.
- When using pnpm workspaces, the install command does not install any modules into the local directory, as the install takes place in the workspace's `node_modules` not in the local directory

### Expected Behavior

Bundled node_modules includes dependencies as listed in `nodeModules`, as well as their own sub-dependencies

### Current Behavior

- `node_modules` only contains direct dependencies
- If using pnpm workspaces, there is no `node_modules` at all

### Reproduction Steps

- `cdk init app --language typescript`
- Delete `node_modules` and `package-lock.json`
- Run `pnpm install` (`npm install -g pnpm` to install pnpm)
- Install package that has at least one sub-dependency (i.e. `pnpm add axios`)
- `pnpm add esbuild`
- Add nodeJs lambda function to the stack

```ts
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as nodejs from 'aws-cdk-lib/aws-lambda-nodejs';
import { Runtime } from 'aws-cdk-lib/aws-lambda';
import * as path from 'path';

export class PnpmStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new nodejs.NodejsFunction(this, 'function', {
      entry: path.join(__dirname, 'index.ts'),
      runtime: Runtime.NODEJS_16_X,
      bundling: {
        nodeModules: ['axios'],
      },
    });
  }
}
```

- Create `index.ts` file
- `cdk synth`
- Inspect the `node_modules` directory inside the asset in the `cdk.out` directory
  - At the top level, it only contains axios and not any of axios' dependencies

---
- Remove `cdk.out`
- Create `pnpm-workspace.yaml`

```yaml
packages:
  - '!**'
```

- `cdk synth`

- The asset in the `cdk.out` directory has no `node_modules` directory

### Possible Solution

- `--shameless-hoist` can be used when running `pnpm install` to ensure that all dependencies are at the top level in `node_modules`
- Creating a `pnpm-workspace.yaml` file inside the local directory when running the install means any higher `pnpm-workspace.yaml` files will be ignored

### Additional Information/Context

_No response_

### CDK CLI Version

2.40.0

### Framework Version

_No response_

### Node.js Version

16.15.0

### OS

Mac OS

### Language

Typescript

### Language Version

3.9.10

### Other information

_No response_

### PR DESCRIPTION
**Pull request by cecheta**
Fixes #21910

By default, pnpm uses symlinks when installing dependencies, and modules only have access to dependencies in their `package.json`. This means when trying to bundle, dependencies of depedencies are not installed. This PR fixes this by using the ` --config.node_linker=hoisted` flag to create a flat `node_modules` structure. [Docs](https://pnpm.io/npmrc#node-linker).

The second problem this PR fixes is when using pnpm workspaces. With workspaces, modules are installed within the workspace the command is run in. This means that when installing as part of bundling in a nested directory, no `node_modules` directory is produced at all. By creating a new `pnpm-workspace.yaml` file locally before installing, this essentially creates a new (nested) workspace, and `node_modules` is installed here. An empty file is enough for this to suffice.

The PR also removes a `.modules.yaml` file from the `node_modules` after installing.  This file contains a datetime of the last install, therefore it would cause the lambda code to change on each deployment if it was included in the bundle.

I have tested this fix locally on both Mac and Windows. I have also included an integration test which failed before these changes, however I am not sure if it should be included due to the `node_modules` in the assets.

----

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [X] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [X] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by TheRealAmazonKendra — DISMISSED** [review]
Thank you for your contribution! I don't think we can review this effectively at present. With 395 changes files, this almost certainly contains some unintended changes. I can't tell now many of these would be intentionally added to this PR.

**Comment by cecheta** [comment]
> Thank you for your contribution! I don't think we can review this effectively at present. With 395 changes files, this almost certainly contains some unintended changes. I can't tell now many of these would be intentionally added to this PR.

The large number of files comes from the assets in the integration tests, as I tried to write a test for a scenario which wouldn't have worked prior to this fix.

I've removed the integ test for now

**Comment by TheRealAmazonKendra** [comment]
> > Thank you for your contribution! I don't think we can review this effectively at present. With 395 changes files, this almost certainly contains some unintended changes. I can't tell now many of these would be intentionally added to this PR.
> 
> The large number of files comes from the assets in the integration tests, as I tried to write a test for a scenario which wouldn't have worked prior to this fix.
> 
> I've removed the integ test for now

In that case, I'll want that test back in once we've done a review of this. Apologies for assuming it was an unintentional addition.

File: packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts [hunk 1]
```diff
@@ -298,13 +299,17 @@ interface BundlingCommandOptions {
 class OsCommand {
   constructor(private readonly osPlatform: NodeJS.Platform) {}
 
-  public writeJson(filePath: string, data: any): string {
-    const stringifiedData = JSON.stringify(data);
+  public write(filePath: string, data: any): string {
```
Comment (TheRealAmazonKendra) [inline packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts:302]: Can you provide further context on why this additional function is needed?

File: packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts [hunk 2]
```diff
@@ -298,13 +299,17 @@ interface BundlingCommandOptions {
...
     if (this.osPlatform === 'win32') {
-      return `echo ^${stringifiedData}^ > "${filePath}"`;
+      return `echo ^${data}^ > "${filePath}"`;
     }
 
-    return `echo '${stringifiedData}' > "${filePath}"`;
+    return `echo '${data}' > "${filePath}"`;
+  }
+
+  public writeJson(filePath: string, data: any): string {
```
Comment (TheRealAmazonKendra) [inline packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts:310]: And why this doesn't need the extra check for OS?

File: packages/@aws-cdk/aws-lambda-nodejs/lib/package-manager.ts [hunk 3]
```diff
@@ -39,7 +39,7 @@ export class PackageManager {
       case LockFile.PNPM:
         return new PackageManager({
           lockFile: LockFile.PNPM,
-          installCommand: logLevel && logLevel !== LogLevel.INFO ? ['pnpm', 'install', '--reporter', 'silent'] : ['pnpm', 'install'],
+          installCommand: logLevel && logLevel !== LogLevel.INFO ? ['pnpm', 'install', '--reporter', 'silent', '--shamefully-hoist'] : ['pnpm', 'install', '--shamefully-hoist'],
```
Comment (TheRealAmazonKendra) [inline packages/@aws-cdk/aws-lambda-nodejs/lib/package-manager.ts:42]: Pretend I don't know shit about pnpm here (because I don't). What is `--shamefully-hoist` doing here?

File: packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts [hunk 4]
```diff
@@ -219,6 +219,7 @@ export class Bundling implements cdk.BundlingOptions {
 
       // Create dummy package.json, copy lock file if any and then install
       depsCommand = chain([
+        this.packageManager.lockFile === LockFile.PNPM ? osCommand.write(pathJoin(options.outputDir, 'pnpm-workspace.yaml'), ''): '',
```
Comment (TheRealAmazonKendra) [inline packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts:222]: If the only instance where you're using `write` has no value for `data`, I'm not sure I get why that function takes in two values and why it's being used here. Are you just creating an empty file titled `pnpm-workspace.yaml`? Also, why use an empty string instead of undefined for this.packageManager.lockFile if it's not pnpm?

**Review by TheRealAmazonKendra — DISMISSED** [review]

File: packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts (hunk 1 above)
Comment (cecheta) [reply packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts]: I have created `write()` which takes a string and outputs it to a file. This is required for the `.npmrc` and `pnpm-workspace.yaml` files.

`writeJson()` receives any input, stringifies it, then calls `write()`.

This way I have avoided duplicate code.

File: packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts (hunk 2 above)
Comment (cecheta) [reply packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts:314]: The OS check has been moved to the `write()` function

File: packages/@aws-cdk/aws-lambda-nodejs/lib/package-manager.ts (hunk 3 above)
Comment (cecheta) [reply packages/@aws-cdk/aws-lambda-nodejs/lib/package-manager.ts]: I've changed from `--shamefully-hoist` to use a `.npmrc` file, I think this way is better

I have explained what it does in the PR description

File: packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts (hunk 4 above)
Comment (cecheta) [reply packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts]: Yes creating an empty `pnpm-workspace.yaml` file avoids a problem when using workspaces. I am now calling the `write()` function twice, once with data. I have updated the PR description to explain.

I am using an empty string as `chain()` takes an array of strings.

**Comment by cecheta** [comment]
> > > Thank you for your contribution! I don't think we can review this effectively at present. With 395 changes files, this almost certainly contains some unintended changes. I can't tell now many of these would be intentionally added to this PR.
> > 
> > 
> > The large number of files comes from the assets in the integration tests, as I tried to write a test for a scenario which wouldn't have worked prior to this fix.
> > I've removed the integ test for now
> 
> In that case, I'll want that test back in once we've done a review of this. Apologies for assuming it was an unintentional addition.

I have added the test back, again the large number of files is due to the node_modules included in the tests.

I have chosen `axios` for the test as this package has a dependency, therefore demonstrating the issue, however it only has one dependency to hopefully keep the asset size low

File: packages/@aws-cdk/aws-lambda-nodejs/lib/package-manager.ts (hunk 3 above)
Comment (cecheta) [reply packages/@aws-cdk/aws-lambda-nodejs/lib/package-manager.ts]: I'm now using `--config.node_linker=hoisted`, as explained in the PR description

File: buildspec-pr.yaml [hunk 5]
```diff
@@ -16,6 +16,9 @@ phases:
       # Install yarn if it wasn't already present in the image
       - yarn --version || npm -g install yarn
 
+      # Install pnpm if it wasn't already present in the image
+      - pnpm --version || npm -g install pnpm
```
Comment (corymhall) [inline buildspec-pr.yaml:20]: We shouldn't need this.

File: buildspec.yaml [hunk 6]
```diff
@@ -16,6 +16,9 @@ phases:
       # Install yarn if it wasn't already present in the image
       - yarn --version || npm -g install yarn
 
+      # Install pnpm if it wasn't already present in the image
+      - pnpm --version || npm -g install pnpm
```
Comment (corymhall) [inline buildspec.yaml:20]: We shouldn't need this.

File: packages/@aws-cdk/aws-lambda-nodejs/test/integ.dependencies-pnpm.ts [hunk 7]
```diff
@@ -0,0 +1,33 @@
...
+  },
+  depsLockFilePath: path.join(__dirname, 'pnpm/pnpm-lock.yaml'),
+});
+
+new triggers.Trigger(stack, 'Trigger', {
+  handler,
+});
+
+new integ.IntegTest(app, 'PnpmTest', {
+  testCases: [stack],
```
Comment (corymhall) [inline packages/@aws-cdk/aws-lambda-nodejs/test/integ.dependencies-pnpm.ts:30]:
```suggestion
  testCases: [stack],
  stackUpdateWorkflow: false, // this will tell the runner to not check in assets.
```

File: yarn.lock [hunk 8]
```diff
@@ -2668,6 +2668,13 @@ aws4@^1.8.0:
   resolved "https://registry.npmjs.org/aws4/-/aws4-1.11.0.tgz#d61f46d83b2519250e2784daf5b09479a8b41c59"
   integrity sha512-xh1Rl34h6Fi1DC2WWKfxUTVqRsNnr6LsKz2+hfwDxQJWmrx8+c7ylaqBMcHfl1U1r2dsifOvKX3LQuLNZ+XSvA==
 
+axios@0.26.1:
```
Comment (corymhall) [inline yarn.lock:2671]: I  don't think this file should have been updated.

**Review by corymhall — DISMISSED** [review]
@cecheta this looks great! I just have a couple of minor comments.

File: packages/@aws-cdk/aws-lambda-nodejs/test/integ.dependencies-pnpm.ts (hunk 7 above)
Comment (cecheta) [reply packages/@aws-cdk/aws-lambda-nodejs/test/integ.dependencies-pnpm.ts:30]: Done, thank you

File: buildspec-pr.yaml (hunk 5 above)
Comment (cecheta) [reply buildspec-pr.yaml]: I get `bash: pnpm: command not found` if I remove it, although I'm not sure if it's needed for just one of the files or both

image

File: yarn.lock (hunk 8 above)
Comment (cecheta) [reply yarn.lock]: Changed the version of axios to use a version already in the lock file

File: packages/@aws-cdk/aws-lambda-nodejs/test/integ.dependencies-pnpm.ts (hunk 7 above)
Comment (cecheta) [reply packages/@aws-cdk/aws-lambda-nodejs/test/integ.dependencies-pnpm.ts:30]: FYI I ran into a bug when updating the tests, raised #23407

File: packages/@aws-cdk/aws-lambda-nodejs/test/integ.dependencies-pnpm.ts [hunk 9]
```diff
@@ -0,0 +1,34 @@
...
+
+const handler = new lambda.NodejsFunction(stack, 'Function', {
+  entry: path.join(__dirname, 'integ-handlers/dependencies-pnpm.ts'),
+  runtime: Runtime.NODEJS_18_X,
+  bundling: {
+    minify: true,
+    // Will be installed, not bundled
+    // (axios is a package with sub-dependencies,
+    // will be used to ensure pnpm bundling works as expected)
+    nodeModules: ['axios'],
```
Comment (corymhall) [inline packages/@aws-cdk/aws-lambda-nodejs/test/integ.dependencies-pnpm.ts:20]: Can you add `forceDockerBundling: true`? I think if we force it to bundle inside docker it removes the need to add any of the dependencies in the repo.

**Review by corymhall — DISMISSED** [review]

File: packages/@aws-cdk/aws-lambda-nodejs/test/integ.dependencies-pnpm.ts (hunk 9 above)
Comment (cecheta) [reply packages/@aws-cdk/aws-lambda-nodejs/test/integ.dependencies-pnpm.ts:20]: I switched to Docker bundling, but doing so demonstrated another issue, which is that when you use Docker bundling, the pnpm store is included in the asset by default. This is also the case on `main`.

I've added a tmp directory for the store into the Dockerfile, and added `--config.package-import-method=copy` when running `pnpm install` which resolves this issue

File: packages/@aws-cdk/aws-lambda-nodejs/package.json [hunk 10]
```diff
@@ -78,7 +78,9 @@
     "@aws-cdk/integ-runner": "0.0.0",
     "@aws-cdk/integ-tests": "0.0.0",
     "@aws-cdk/pkglint": "0.0.0",
+    "@aws-cdk/triggers": "0.0.0",
     "@types/jest": "^27.5.2",
+    "axios": "^0.27.2",
```
Comment (corymhall) [inline packages/@aws-cdk/aws-lambda-nodejs/package.json:83]:
```suggestion
```

I don't think this is needed anymore

**Review by corymhall — CHANGES_REQUESTED** [review]
Just one minor thing and then this is ready to go! 🚀

File: packages/@aws-cdk/aws-lambda-nodejs/package.json (hunk 10 above)
Comment (cecheta) [reply packages/@aws-cdk/aws-lambda-nodejs/package.json]: Removed

Comment (cecheta) [reply packages/@aws-cdk/aws-lambda-nodejs/package.json]: For some reason, the tests in `test/docker.test.js` are now failing

I can see in the logs:

```
time="2022-12-27T14:51:42.954645757Z" level=info msg="Attempting next endpoint for pull after error: denied: User: arn:aws:sts::464831875156:assumed-role/Ops-cdk-autobuild-prs-AutoBuildv2ProjectRoleC688F4-CY3ZTUL6CY8Q/AWSCodeBuild-b78b1055-51c8-4066-8449-8e563d561d94 is not authorized to perform: ecr:BatchGetImage on resource: arn:aws:ecr:us-east-1:464831875156:repository/library/esbuild because no identity-based policy allows the ecr:BatchGetImage action"
```

Comment (cecheta) [reply packages/@aws-cdk/aws-lambda-nodejs/package.json]: Squashing commits seemed to fix it, not sure why

**Review by corymhall — APPROVED** [review]
