### PR TITLE
fix(aws-autoscaling): Add hook ordering dependency

### LINKED ISSUE #1212: ecs: lifecycle hook needs a dependency on SNS publish role policy
During creation the lifecycle hook will write a test message to SNS, which might fail if the policy gets added later:

```
24/41 | 12:56:27 | CREATE_FAILED        | AWS::AutoScaling::LifecycleHook           | Cluster/DefaultAutoScalingGroup/LifecycleHookDrainHook (ClusterDefaultAutoScalingGroupLifecycleHookDrainHook4A9A4325) Unable to publish test message to notification target arn:aws:sns:us-east-1:209640446841:greeting-stack-ClusterDefaultAutoScalingGroupDrainECSHookTopicFF0E6CF4-1JFOXBKO9CQ1U using IAM role arn:aws:iam::209640446841:role/greeting-stack-ClusterDefaultAutoScalingGroupLifec-3SF76AMBEH5O. Please check your target and role configuration and try to put lifecycle hook again. (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: 6fc2dfc0-ec24-11e8-84a2-fb1b7f6a78f3)
```

### PR DESCRIPTION
**Pull request by rix0rrr**
Add an ordering dependency between the LifecycleHook and the role policy
that grants permissions to perform the action (publish to a topic or
queue).

Without this ordering dependency, the template might fail to deploy.

Fixes #1212.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-autoscaling/lib/util.ts [hunk 1]
```diff
@@ -0,0 +1,12 @@
+import cdk = require('@aws-cdk/cdk');
+/**
+ * Allow lazy evaluation of a list of dependables
+ */
+export class LazyDependable implements cdk.IDependable {
+  constructor(private readonly depList: cdk.IDependable[]) {
```
Comment (eladb) [inline packages/@aws-cdk/aws-autoscaling/lib/util.ts]: Accept an `IDependable` in the ctor instead of a dep list
