### PR TITLE
fix(aws-elasticloadbalancingv2): Set stickiness.enabled unless target type is lambda

### LINKED ISSUE #17261: aws-elasticloadbalancingv2: cannot create lambda TargetGroup
### What is the problem?

Cannot create  lambda TargetGroup as the created cfn template has `stickiness.enabled` set as true in TargetGroupAttributes. Seems like this attribute is not expected for lambda based target groups.

### Reproduction Steps

const lambdaTargetGroup = new ApplicationTargetGroup(this, `TargetGroup`, {
       targets: [new targets.LambdaTarget(lambdaFunction)],
    });

You should be able to see `stickiness.enabled` set in cfn template. During deployment , deployment fails with 

`The provided target group attribute is not supported (Service: AmazonElasticLoadBalancing; Status Code: 400`

### What did you expect to happen?

Target group with lambda targets getting created successfully

### What actually happened?

Target group with lambda targets are not getting created

### CDK CLI Version

1.130

### Framework Version

_No response_

### Node.js Version

17.0.1

### OS

macos 11.3.1

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by topecongiro**
Avoid setting `stickiness.enabled` to `false` when the target group type is lambda as it breaks on deployment.

Fixes #17261.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts [hunk 1]
```diff
@@ -147,7 +147,7 @@ export class ApplicationTargetGroup extends TargetGroupBase implements IApplicat
 
       if (props.stickinessCookieDuration) {
         this.enableCookieStickiness(props.stickinessCookieDuration, props.stickinessCookieName);
-      } else {
+      } else if (this.targetType !== TargetType.LAMBDA) {
```
Comment (peterwoodworth) [inline packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts:150]: I don't think this would be effective with your use case. Line 157 would call the function that sets the target type based on the target

File: packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/target-group.test.ts [hunk 2]
```diff
@@ -19,6 +19,23 @@ describe('tests', () => {
...
   });
 
+  test('Lambda target should not have stickiness.enabled set', () => {
+    const app = new cdk.App();
+    const stack = new cdk.Stack(app, 'Stack');
+    new elbv2.ApplicationTargetGroup(stack, 'TG', {
+      targetType: elbv2.TargetType.LAMBDA,
+    });
+
+    expect(stack).not.toHaveResource('AWS::ElasticLoadBalancingV2::TargetGroup', {
```
Comment (peterwoodworth) [inline packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/target-group.test.ts:29]: You'll want `toHaveResourceLike` here. Otherwise, this just checks to make sure there's not a `TargetGroup` with _only_ the attributes you specify

**Review by peterwoodworth — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts (hunk 1 above)
Comment (njlynch) [reply packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts:150]: Just to clarify what @peterwoodworth  is saying here -- this fixes the functionality when the `targetType` is explicitly defined as an input prop, but not when the type is not defined at creation, and is instead set by the target itself. Here's an example test that breaks with this implementation, but should work:

```ts
  test('Lambda target should not have stickiness.enabled set', () => {
    const app = new cdk.App();
    const stack = new cdk.Stack(app, 'Stack');
    const tg = new elbv2.ApplicationTargetGroup(stack, 'TG');
    tg.addTarget({
      attachToApplicationTargetGroup(_targetGroup: elbv2.IApplicationTargetGroup): elbv2.LoadBalancerTargetProps {
        return {
          targetType: elbv2.TargetType.LAMBDA,
          targetJson: { id: 'arn:aws:lambda:eu-west-1:123456789012:function:myFn' },
        };
      },
    });

    expect(stack).not.toHaveResourceLike('AWS::ElasticLoadBalancingV2::TargetGroup', {
      TargetGroupAttributes: [
        {
          Key: 'stickiness.enabled',
          Value: 'false',
        },
      ],
    });
  });
```

I think unfortunately we're going to have to do something kind of ugly, like detect when a Lambda targetType is added, and then unset the attribute if so (in addition to what you've done here).

File: packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/target-group.test.ts [hunk 3]
```diff
@@ -19,6 +19,23 @@ describe('tests', () => {
...
+      TargetGroupAttributes: [
+        {
+          Key: 'stickiness.enabled',
+          Value: 'false',
```
Comment (gburke-ppb) [inline packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/target-group.test.ts:33]: you can remove this line also.  That way the test will fail even if this is set to `'true'`

File: packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts (hunk 1 above)
Comment (topecongiro) [reply packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts:150]: @peterwoodworth @njlynch Sorry for the late reply, and thank you for your reviews! Will take a look.

File: packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/target-group.test.ts (hunk 2 above)
Comment (topecongiro) [reply packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/target-group.test.ts:29]: @peterwoodworth Hmm, this doesn't seem to work anymore; maybe related to https://github.com/aws/aws-cdk/pull/17344? What can I use to test that a certain field does not exist in the resource?

```
    Not None of 1 resources matches resource 'AWS::ElasticLoadBalancingV2::TargetGroup' with {
      "$deepObjectLike": {
        "TargetGroupAttributes": [
          {
            "Key": "stickiness.enabled"
          }
        ]
      }
    }.
    - Field TargetGroupAttributes missing in:
        {
          "Type": "AWS::ElasticLoadBalancingV2::TargetGroup",
          "Properties": {
            "TargetType": "lambda"
          }
        }
```

Comment (topecongiro) [reply packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/target-group.test.ts:29]: Never mind, it was just that I forgot to run `yarn bulid` before running `yarn test` 🤦‍♂️

**Review by njlynch — APPROVED** [review]
