### PR TITLE
fix(core): detect and resolve stringified number tokens

### LINKED ISSUE #19546: (stepfunctions-tasks): AWS Batch integration with container overrides breaks with token values
### What is the problem?

I was eagerly awaiting 1.149 as it appeared to fix the issue that prevents container overrides of memory and cpu:

https://github.com/aws/aws-cdk/issues/18993
https://github.com/aws/aws-cdk/pull/19298

However, now I get the following error:

```json
{
  "resourceType": "batch",
  "resource": "submitJob.sync",
  "error": "Batch.ClientException",
  "cause": "Value -1.888154589709072e+289 for type MEMORY in resourceRequirement is not valid. Provide a valid number as input. (Service: AWSBatch; Status Code: 400; Error Code: ClientException; Request ID: dcd8c27a-baac-414a-9b64-da5733cc1344; Proxy: null)"
}
```

### Reproduction Steps

This is the code that sets up the container overrides

```js
BatchContainerOverrides containerOverrides = BatchContainerOverrides.builder()
                .command(JsonPath.listAt("$." + SOLVER_TASK_PARAMETERS + "." + COMMAND))
                .vcpus(JsonPath.numberAt("$." + SOLVER_TASK_PARAMETERS + "." + CPU))
                .memory(Size.mebibytes(JsonPath.numberAt("$." + SOLVER_TASK_PARAMETERS + "." + MEMORY)))
                .build();
```

After I updated to 1.149 there is still no resourceRequirements field on BatchContainerOverrides. Based on the fix it appears that these values would just be copied from the top-level vcpus and memory.

Previously I was receiving the warning that my container overrides were being ignored, but the job would still execute.

### What did you expect to happen?

I expected that with this update my container overrides would be respected.

### What actually happened?

```json
{
  "resourceType": "batch",
  "resource": "submitJob.sync",
  "error": "Batch.ClientException",
  "cause": "Value -1.888154589709072e+289 for type MEMORY in resourceRequirement is not valid. Provide a valid number as input. (Service: AWSBatch; Status Code: 400; Error Code: ClientException; Request ID: dcd8c27a-baac-414a-9b64-da5733cc1344; Proxy: null)"
}
```

### CDK CLI Version

1.149.0

### Framework Version

_No response_

### Node.js Version

12.22.11

### OS

MacOS 10.15.7

### Language

Java

### Language Version

Java 11

### Other information

_No response_

### PR DESCRIPTION
**Pull request by rix0rrr**
Number tokens are encoded as a range of very large negative numbers (for
example: -1.888154589709072e+289). When these are naively stringified,
the `resolve()` method doesn't recognize and translate them anymore,
and these numbers end up in the target template in a confusing way.

However, recognizing them is actually not that hard and can be done
using a regex. We can then do the token resolution appropriately, making
it so that construct authors do not have to call
`Tokenization.stringifyNumber()` anymore in order to support
stringification of number values.

Fixes #19546, closes #19550.

----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `cdk-integ` to deploy the infrastructure and generate the snapshot (i.e. `cdk-integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by peterwoodworth** [comment]
This looks like a much more stable fix than mine, should we close #19550?

File: packages/@aws-cdk/core/lib/private/cloudformation-lang.ts [hunk 1]
```diff
@@ -43,8 +43,8 @@ export class CloudFormationLang {
 
     // Some case analysis to produce minimal expressions
     if (parts.length === 1) { return parts[0]; }
-    if (parts.length === 2 && typeof parts[0] === 'string' && typeof parts[1] === 'string') {
-      return parts[0] + parts[1];
+    if (parts.length === 2 && ['string', 'number'].includes(typeof parts[0]) && ['string', 'number'].includes(typeof parts[1])) {
```
Comment (skinny85) [inline packages/@aws-cdk/core/lib/private/cloudformation-lang.ts:46]: Can we use ` isConcatable()` here? Or can these actually be Tokens themselves? If so, do we need a different helper?

**Review by skinny85 — APPROVED** [review]
"I understand some of these words" 😃
