### PR TITLE
fix(cloudformation-diff): cdk diff not picking up differences if old/new value is in format n.n.n

### LINKED ISSUE #15935: cdk diff not picking up differences if old/new value is in format x.y.z
"cdk diff" in the current version (1.117.0 / 2.0.0-rc.16) doesn't pick up differences if the old/new value has a number-like format but actually isn't a number (e.g. 0.31.1)

### What did you expect to happen?

I expected the differences are picked up and shown

### What actually happened?

I received "There are no differences"

### Environment

  - **CDK CLI Version  : 2.0.0-rc.16
  - **Node.js Version:** 14.17.0
  - **OS               :** MacOs
  - **Language (Version):** TypeScript (4.1.3)

### PR DESCRIPTION
**Pull request by vincent-turato**
"cdk diff" in the current version doesn't pick up differences if the old/new value has a number-like format but actually isn't a number (e.g. 0.31.1)

Example: two version strings like "0.31.1-prod" and "0.31.2-prod" are both parsed into "0.31" (and hence incorrectly considered equal).

Closes #15935. 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by aleksil** [comment]
We just hit this bug, but with IP-addresses when working with WAF IP Sets. Changes to the two last octets are not picked up (e.g. changing IP from 1.1.1.1 to 1.1.2.2). I don't think your patch fixes this edge case either, the regex could probably be changed to only allow one dot in a float?

File: packages/@aws-cdk/cloudformation-diff/lib/diff/util.ts [hunk 1]
```diff
@@ -141,11 +141,16 @@ export function unionOf(lv: string[] | Set<string>, rv: string[] | Set<string>):
  */
 function safeParseFloat(str: string): number {
   const ret = parseFloat(str);
+  const nonNumericRegex = /[^\d\-\.]/;
```
Comment (BenChaimberg) [inline packages/@aws-cdk/cloudformation-diff/lib/diff/util.ts:144]: I think this is too restrictive. Let's try `/\d*\.\d+\./`?

**Review by BenChaimberg — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/cloudformation-diff/test/diff-template.test.ts [hunk 2]
```diff
@@ -581,3 +581,48 @@ test('when a property changes including equivalent DependsOn', () => {
   differences = diffTemplate(newTemplate, currentTemplate);
   expect(differences.resources.differenceCount).toBe(1);
 });
+
+test('when a property with a number-like format changes', () => {
+  const bucketName = 'ShineyBucketName';
+  const oldTags = ['0.31.1-prod'];
+  const newTags = ['0.31.2-prod'];
```
Comment (BenChaimberg) [inline packages/@aws-cdk/cloudformation-diff/test/diff-template.test.ts:588]: please add some more test cases from the comments on this PR and from the issue

**Review by BenChaimberg — APPROVED** [review]
