### PR TITLE
fix(core): Durations in the expected unit are not tested for integer-ness

### LINKED ISSUE #17814: (@aws-cdk/events): Lambda Scheduled events cannot be run in fractions of a minute
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-events.Rule.html#schedule

### Describe your issue?

The CDK documentation states that when creating a new instance of the [Rule class](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-events/lib/rule.ts) and utilizing the [Schedule](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/lib/duration.ts) constructor property. If the user is choosing to leverage the [static method rate](https://github.com/aws/aws-cdk/blob/dd5e12d43231d991971de3121928377569b2dd63/packages/%40aws-cdk/aws-events/lib/schedule.ts#L19) it accepts ANY valid [Duration](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/lib/duration.ts) value. However this method will throw and it is expected to throw if that value is not a whole number of minutes. Currently it is expected of the user to click on and read [this documentation](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns.html). The aforementioned documentation link that is provided does not immediately discuss this limitation it is better defined [here](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-rule-schedule.html) to understand that this is not a possibility. I think this would provide some clarity to new users interfacing with Rules for the first time.

### PR DESCRIPTION
**Pull request by scanlonp**
----
Converting from a type to itself would not check the integral flag and simply return the current duration amount rather than throwing an error if the amount converted to was fractional.

Commands such as `toSeconds()` or `toMinutes()` had the same behavior since they leverage `convert()`.

`Duration.minutes(0.5).toMinutes();` previously would not throw an error, but `Duration.seconds(30).toMinutes();` would. 
`Duration.minutes(0.5).toMinutes();` will now throw an error while `Duration.minutes(0.5).toMinutes({ integral: false});` will not.

fix(@aws-cdk/aws-events/schedule.ts): `rate()` now correctly catches if a duration is defined in fractions of a minute. The root cause was the use of `Duration.toMinutes()` in `rate()`. Now all rates defined with durations must be in whole minutes.

docs: this limitation on rates is highlighted more clearly in the documentation for aws-events/schedule.ts and aws-events/rule.ts. 

This closes #17814.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-events/lib/schedule.ts [hunk 1]
```diff
@@ -31,6 +31,9 @@ export abstract class Schedule {
     if (duration.toSeconds() === 0) {
       throw new Error('Duration cannot be 0');
     }
+    if (duration.toSeconds() % 60 !== 0) {
+      throw new Error(`'Duration must be a whole number of minutes, Duration provided was ${duration.toMinutes()} minutes'`);
+    }
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-events/lib/schedule.ts:36]: Why this? You didn't really explain the motivation for the change, but as far as I can tell on line `40` below we do `duration.toMinutes({ integral: true })`, which will throw if the duration is not convertible to a whole number of minutes.

You just added a different exception that will throw if the duration is not convertible to a whole number of minutes.

It looks like you're trading out one error for another, so: why?

- Is the original error message not good enough? If so: is that maybe something we should be clearing up instead? Can we/should we change the original error message?
  - If that's your thought process, and you considered and rejected updating the error produced by `Duration.toMinutes()`, then that would be helpful to include in your PR description, because it would give me insight into things you have considered and rejected, and will help me understand why you came up with the solution you came up with.

Comment (rix0rrr) [reply packages/@aws-cdk/aws-events/lib/schedule.ts:36]: The original issue asks for a change to the documentation (to explain that the duration has to be a whole number of minutes, because this was apparently a surprise to the reporter), not for a code change.

Was it a conscious decision to forego the documentation update? Did you misread the original bug report?

**Review by rix0rrr — CHANGES_REQUESTED** [review]
Hey Parker,

Thanks for the submit! What I'm going to say in my review might sound a little harsh and abrasive and challenging. I will be asking "Why" a lot. Know it's intended with all ❤️ and I'm just trying to focus your thought processes, and make sure you think about what you're trying to achieve while doing something!

(Also, the messages below sound generic and repetitive and that's because they are. I'm experimenting with standard responses to PRs because--believe it or not--a lot of people keep forgetting to do the same things over and over again and I'm starting to get tired of typing the same replies over and over again 🙃)

------

Please make sure that your PR title confirms to the conventional commit standard (`fix`, `feat`, `chore`) and that it is written in a style that will reflect correctly in the change log (See [Contributing Guide, Pull Requests](https://github.com/aws/aws-cdk/blob/v1-main/CONTRIBUTING.md#step-4-pull-request))

------

Please make sure that your PR body describes the problem the PR is solving, and the design approach and alternatives considered. Explain why the PR solves the problem. A link to an issue is helpful, but does not replace an explanation of your thought process (See [Contributing Guide, Pull Requests](https://github.com/aws/aws-cdk/blob/v1-main/CONTRIBUTING.md#step-4-pull-request))

File: packages/@aws-cdk/aws-events/lib/rule.ts [hunk 2]
```diff
@@ -37,30 +37,34 @@ export interface RuleProps {
 
   /**
    * The schedule or rate (frequency) that determines when EventBridge
-   * runs the rule. For more information, see Schedule Expression Syntax for
+   * runs the rule.
+   *
+   * You must specify this property, the `eventPattern` property, or both.
+   *
+   * Note that rates cannot be defined in fractions of minutes.
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-events/lib/rule.ts:44]: Doesn't it make more sense to put this on `Schedule.rate()` ?

**Review by rix0rrr — DISMISSED** [review]
Please also still adjust the PR on the GitHub website (edit the title and body).

File: packages/@aws-cdk/aws-events/test/schedule.test.ts [hunk 3]
```diff
@@ -81,4 +69,40 @@ describe('schedule', () => {
       events.Schedule.rate(Duration.seconds(Lazy.number({ produce: () => 5 })));
     }).toThrow(/Allowed units for scheduling/);
   });
-});
+
+  test('rate cannot be a fractional amount of minutes (defined with seconds)', () => {
```
Comment (kaizencc) [inline packages/@aws-cdk/aws-events/test/schedule.test.ts:73]: Minor nit: since these tests are pretty similar, I suggest you wrap them all in a “describe” block — we do this elsewhere in our tests so you can search it up for an example. Would be good to add in all tests that have to do with rate.

**Review by kaizencc — CHANGES_REQUESTED** [review]
Hey @scanlonp :). This is looking good! Also, sorry I’m on mobile so no clue how this review will turn out. I suggest you take a look at how our merged PRs are titled and emulate that. Also I’d link you the GitHub docs for this but since I’m on mobile I’ll tell you: GitHub recognizes when you say something like “closes #xxxxx” and will link that issue to be closed when this PR is merged. You should change your PR description to have that phrase rather than “addresses” so that GitHub will pick it up.

**Review by TheRealAmazonKendra — DISMISSED** [review]
I think this PR somewhat misunderstands the problem. There isn't actually a bug here. The function behaves as we expect it to but we're not providing clear documentation on the fact that we expect certain failures.

**Comment by rix0rrr** [comment]
I think the test is wrong. 1.1 seconds doesn't look like valid input, I don't know why that was chosen.

File: packages/@aws-cdk/aws-events/lib/rule.ts (hunk 2 above)
Comment (scanlonp) [reply packages/@aws-cdk/aws-events/lib/rule.ts:44]: It does, putting it on `Schedule.rate()` instead.

File: packages/@aws-cdk/aws-events/lib/schedule.ts [hunk 4]
```diff
@@ -19,6 +23,8 @@ export abstract class Schedule {
 
   /**
    * Construct a schedule from an interval and a time unit
+   *
+   * Rates cannot be defined in fractions of minutes and cannot be 0
```
[the remark this answers is not in the document]
Comment (scanlonp) [reply packages/@aws-cdk/aws-events/lib/schedule.ts:27]: I will update it here to be more positive in what the user should do rather than what they are prevented from doing.

**Review by rix0rrr — APPROVED** [review]
