### PR TITLE
fix(ecs): outdated linux commands for `canContainersAccessInstanceRole=false` and also deprecate property

### LINKED ISSUE #28518: aws-ecs: Cloud-init script for EC2 fails when using AWS Linux 2023
### Describe the bug

When using EC2 as the capacity provider in the `addAsgCapacityProvider` method, the user is expected to specify the `machineImageType` for the capcity provider. In doing so, it will add a user data script that will inject additional data that is relevant to the user for the /etc/ecs/ecs.config file 

One of the commands that is injected is: 

```
autoScalingGroup.addUserData('sudo iptables --insert FORWARD 1 --in-interface docker+ --destination 169.254.169.254/32 --jump DROP');
autoScalingGroup.addUserData('sudo service iptables save');
```

On AWS Linux 2023 running the Linux 6.1.66-91.160.amzn2023.x86_64 kernel, this command results in an error when executing the cloud-init file. 

```
+ sudo iptables --insert FORWARD 1 --in-interface docker+ --destination 169.254.169.254/32 --jump DROP
+ sudo service iptables save
The service command supports only basic LSB actions (start, stop, restart, try-restart, reload, reload-or-restart, try-reload-or-restart, force-reload, status, condrestart). For other actions, please try to use systemctl.
2023-12-29 06:11:05,181 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2023-12-29 06:11:05,184 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_scripts_user.py'>) failed
```

This results in the line after
```
echo ECS_AWSVPC_BLOCK_IMDS=true >> /etc/ecs/ecs.config
```
to not get run which is not ideal. 

### Expected Behavior

It should successfully run the required ECS setup configs when the EC2 instance starts. 

### Current Behavior

The cloud-init script will fail with the error message `The service command supports only basic LSB actions (start, stop, restart, try-restart, reload, reload-or-restart, try-reload-or-restart, force-reload, status, condrestart). For other actions, please try to use systemctl.`

### Reproduction Steps

Start an ECS Cluster with an EC2 capacity provider and the AMI in the launch template for the autoscaling group to be the latest AWS Linux 2023 AMI (`ecs.EcsOptimizedImage.amazonLinux2023(AmiHardwareType.STANDARD)`). The error will occur when the instance starts up and the logs can be found in `/var/log/cloud-init-output.log`

### Possible Solution

Introduce a new `machineImageType` in the `addAsgCapacityProvider` method and name it `AMAZON_LINUX_2023`. In the `configureAutoScalingGroup` method in `cluster.ts`, add in a new switch condition to render different user data for the ECS Optimized AMI for AWS Linux 2023. In particular, the `sudo service iptables save` will be changed to `sudo iptables-save > /etc/sysconfig/iptables` which will not throw the same error as above. 

### Additional Information/Context

_No response_

### CDK CLI Version

2.114.1 (build 02bbb1d)

### Framework Version

_No response_

### Node.js Version

v18.17.0

### OS

macOS 14.2

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by samson-keung**
### Issue # (if applicable)

Closes #28518.

### Reason for this change

When `canContainersAccessInstanceRole=false`, wrong commands are added to the ASG UserData, as described in the issue linked above.

Reason for deprecating the `canContainersAccessInstanceRole` option is detailed in https://github.com/aws/aws-cdk/discussions/32609.

### Description of changes

- Added deprecation tag to all `canContainersAccessInstanceRole` options. 
- Created two feature flags to control the `canContainersAccessInstanceRole` behaviour
- Added new commands if customer opted to use them via setting the right feature flags

### Describe any new or updated permissions being added

None

### Description of how you validated changes

A new integ test is added to ensure the commands in UserData executes without throwing errors.

The existing integ tests are updated to have the default feature flag values and they are passing. This should prove that there will not be any change to existing CDK apps.

Unit tests are added for each platform, combination of possible values for `canContainersAccessInstanceRole` + possible values for the feature flags (3 platforms * 3 possible values for `canContainersAccessInstanceRole` * 2 possible values for `@aws-cdk/aws-ecs:disableEcsImdsBlocking` * 2 possible values for `@aws-cdk/aws-ecs:enableImdsBlockingDeprecatedFeature` = 36 unit tests).

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-ecs/lib/cluster.ts [hunk 1]
```diff
@@ -631,6 +677,48 @@ export class Cluster extends Resource implements ICluster {
...
+    }
+
+    if (options.canContainersAccessInstanceRole === false ||
+      options.canContainersAccessInstanceRole === undefined) {
+
+      if (!FeatureFlags.of(this).isEnabled(Disable_ECS_IMDS_Blocking) &&
+        FeatureFlags.of(this).isEnabled(Enable_IMDS_Blocking_Deprecated_Feature)) {
+        // new commands
+        autoScalingGroup.addUserData('sudo yum install -y iptables-services; sudo iptables --insert DOCKER-USER 1 --in-interface docker+ --destination 169.254.169.254/32 --jump DROP');
+        autoScalingGroup.addUserData('sudo iptables-save | sudo tee /etc/sysconfig/iptables && sudo systemctl enable --now iptables');
```
Comment (godwingrs22) [inline packages/aws-cdk-lib/aws-ecs/lib/cluster.ts:707]: nit: May be it would be nice to add the official AWS link doc as a comment above this line from where these commands were taken.

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html#task-iam-role-considerations

**Review by godwingrs22 — COMMENTED** [review]
Thanks @samson-keung for the contribution. LGTM. Just left a nit comment.

File: packages/aws-cdk-lib/aws-ecs/lib/cluster.ts [hunk 2]
```diff
@@ -631,6 +677,48 @@ export class Cluster extends Resource implements ICluster {
...
+      FeatureFlags.of(this).isEnabled(Disable_ECS_IMDS_Blocking)) {
+      throw new Error('The canContainersAccessInstanceRole option is not supported. See https://github.com/aws/aws-cdk/discussions/32609');
+    }
+
+    if (options.canContainersAccessInstanceRole === false ||
+      options.canContainersAccessInstanceRole === undefined) {
+
+      if (!FeatureFlags.of(this).isEnabled(Disable_ECS_IMDS_Blocking) &&
+        FeatureFlags.of(this).isEnabled(Enable_IMDS_Blocking_Deprecated_Feature)) {
+        // new commands
```
Comment (samson-keung) [inline packages/aws-cdk-lib/aws-ecs/lib/cluster.ts:705]:
```suggestion
        // new commands from https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html#task-iam-role-considerations
```

**Review by godwingrs22 — APPROVED** [review]
