### PR TITLE
fix(lambda-nodejs): breaking change in esbuild causes import module error

### LINKED ISSUE #30717: :exclamation: NOTICE (aws-lambda-nodejs): Runtime.ImportModuleError: `Cannot find module 'module'`
Please add your +1 👍 to let us know you have encountered this
---

### Status: RESOLVED

Fixed in v2.147.3.

### Overview:

With the [v0.22 release of esbuild](https://github.com/evanw/esbuild/releases/tag/v0.22.0), the default bundling behavior has been changed to omit imported packages from the bundle by default when the platform is node. The recommendation is to set the `packages` option to `bundle` to get the desired bundling behavior.

### Complete Error Message:
```
Cannot find module 'source-map-support/register'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs
```

### Workaround: 

We recommend pinning the version to `0.2.15`
```
nodejs_bundling_options = NodejsBundlingOptions(esbuild_version="0.21.5")

some_lambda = NodejsFunction(
    scope=self,
    ...
    bundling=nodejs_bundling_options,
)
```
Note: You may also add the flag `--packages=bundle` but this may result in other errors and is not recommended.

### Solution:

We have pinned the version of esbuild used when no version is already installed to `0.2.15`.

----------------------------------------------------
### Expected Behavior

When executing the lambda, `import package from 'somePackage'` imports the target package

### Current Behavior

When executing the lambda, `import package from 'somePackage'` throws a `Runtime.ImportModuleError` with message `Cannot find module 'somePackage'`

### Reproduction Steps

1. Clone https://github.com/ykageyama-mondo/esbuild-issue-recreation
2. Install and deploy
3. Execute deployed lambda

### Possible Solution

Add `--packages=bundle` to the default esbuildCommand created. Tried this on the reproduction lambda but seems to error with `Must use "outdir" when there are multiple input files`. I'm not familiar enough with esbuild to understand why this is happening and how to fix it.

### Additional Information/Context

_No response_

### CDK CLI Version

2.147.2

### Framework Version

2.147.2

### Node.js Version

18.17.1

### OS

Ubuntu 22.04.4 LTS

### Language

TypeScript

### Language Version

5.5.2

### Other information

_No response_

### PR DESCRIPTION
**Pull request by xazhao**
### Issue # (if applicable)

Closes #30717.

### Reason for this change

esbuild introduced a breaking change in v0.22 which caused the build error in `aws-lambda-nodejs` module.

### Description of changes

Pin the esbuild version to 0.21 in Dockerfile

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.esbuildArgs.js.snapshot/tree.json [hunk 1]
```diff
@@ -20,8 +20,8 @@
                     "id": "ImportServiceRole",
                     "path": "cdk-integ-lambda-nodejs-esbuildArgs/ts-handler/ServiceRole/ImportServiceRole",
                     "constructInfo": {
-                      "fqn": "constructs.Construct",
-                      "version": "10.3.0"
+                      "fqn": "aws-cdk-lib.Resource",
+                      "version": "0.0.0"
```
Comment (scanlonp) [inline packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.esbuildArgs.js.snapshot/tree.json:24]: Are these supposed to be changing like this? Are these updates that should have happened but are only being found now?

**Review by scanlonp — APPROVED** [review]
Not sure what is going on with the tree.json changes. The code changes look good.

File: packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.esbuildArgs.js.snapshot/tree.json (hunk 1 above)
Comment (TheRealAmazonKendra) [reply packages/@aws-cdk-testing/framework-integ/test/aws-lambda-nodejs/test/integ.esbuildArgs.js.snapshot/tree.json:24]: Unrelated, but these haven't been updated in a while so it's likely as a result of the jsii changes that were merged recently. I expected some of this.
