### PR TITLE
fix(ecr-assets): unable to use one Dockerfile to build multiple images

### LINKED ISSUE #5683: ecr-assets: unable to use one Dockerfile to build multiple images
Creating two `DockerImageAsset`s, using a different `target` in each of them, will result in only one of the images actually built and pushed. As well as only one ECR repository created. 

Similarly, this will also happen when specifying different `build-args` in each asset definition.

### Reproduction Steps

Consider the following stack definition:

```typescript
export class AwsCdkPlaygroundStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new ecr.DockerImageAsset(this, 'Image1', {
      directory: path.join(__dirname, 'image'),
      target: "builder"
    })

    new ecr.DockerImageAsset(this, 'Image2', {
      directory: path.join(__dirname, 'image'),
      target: "runner",
    })

  }
}
```

Just for context, the (degenerate) `Dockerfile` looks something like this:

```Dockerfile
FROM golang:1.7.3 AS builder
FROM alpine:latest AS runner 

```
This setup should result in two images, one for the `builder` target and one for the `runner`.

### Error Log

Its not actually causing any errors, but you can see in the output that it only pushed one image to a single repository.

```console
AwsCdkPlaygroundStack: deploying...
Sending build context to Docker daemon  2.048kB
Step 1/1 : FROM golang:1.7.3 AS builder
 ---> ef15416724f6
Successfully built ef15416724f6
Successfully tagged 185706627232.dkr.ecr.us-east-2.amazonaws.com/cdk/awscdkplaygroundstackimage19f2089d4:latest
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
 ⌛ Pushing Docker image for cdk.out/asset.1f6cca87ce602dc2fe4066751259f3ebdffea55b31e70d95051694bd0b9f048a; this may take a while.
The push refers to repository [185706627232.dkr.ecr.us-east-2.amazonaws.com/cdk/awscdkplaygroundstackimage19f2089d4]
2d9a008a6ee1: Preparing
a3e878ca1a1c: Preparing
4588c2179cdc: Preparing
9168b67dbc50: Preparing
9f17712cba0b: Preparing
223c0d04a137: Preparing
fe4c16cbf7a4: Preparing
223c0d04a137: Waiting
fe4c16cbf7a4: Waiting
2d9a008a6ee1: Pushed
a3e878ca1a1c: Pushed
223c0d04a137: Pushed
9f17712cba0b: Pushed
9168b67dbc50: Pushed
fe4c16cbf7a4: Pushed
4588c2179cdc: Pushed
latest: digest: sha256:37d263ccd240e113a752c46306ad004e36532ce118eb3131d9f76f43cc606d5d size: 1792
185706627232.dkr.ecr.us-east-2.amazonaws.com/cdk/awscdkplaygroundstackimage19f2089d4@sha256:37d263ccd240e113a752c46306ad004e36532ce118eb3131d9f76f43cc606d5d|golang@sha256:340212e9c5d062f3bfe58ff02768da70234ea734bd022a357ee6be2a6d963505|
AwsCdkPlaygroundStack: creating CloudFormation changeset..
```

### Environment

  - **CLI Version      :** 1.19.0 (build 5597bbe)
  - **Framework Version:** 1.19.0 (build 5597bbe)
  - **OS               :** OSX
  - **Language         :** Typescript

### Other

This also affects use cases where one has multiple `Dockerfile`s and uses the [`file`](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts#L48) property to specify different files for different images. 

#### Root Cause

Since the asset directory is the same in both assets, the resulting `hash` is the same as well, which causes a **false** deduplication. 

#### Proposed Solution

The `Hash` of the asset should consider the command used to actually build the container. This way, passing a different `target/build-arg/file` will result in a new hash, and everything else should follow.

Funnily enough, we already thought of [this](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/assets/lib/fs/fingerprint.ts#L15) a while back.

#### Other affected modules?

This problem isn't necessarily tied to docker, it will happen in every asset that can produce multiple artifacts from the same directory content. Can we think of something else that might be affected?

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by eladb**
Since we use the source hash as the image ID, if we use different docker build options such as specifying a different `target`, `buildArgs` or a custom docker file name, we still get the same image ID. This means that if this image ID already exists, we skip the build. This makes it impossible to use the same docker build context to build multiple images.

This fix exposes the ability to include extra information to the source hash fingerprint algorithm (in `assets.Staging`), and utilizes this capability to "salt" the hash with build arguments if they are provided.

Fixes #5683

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/assets/lib/fs/copy-options.ts [hunk 1]
```diff
@@ -18,3 +18,16 @@ export interface CopyOptions {
    */
   readonly exclude?: string[];
 }
+
+/**
+ * Options related to calculating source hash.
+ */
+export interface FingerprintOptions extends CopyOptions {
```
Comment (iliapolo) [inline packages/@aws-cdk/assets/lib/fs/copy-options.ts]: Why did you move this here? Seems like a more natural place for `FingerprintOptions` is the `fingerprint` file where those options are actually being used.

File: packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts [hunk 2]
```diff
@@ -5,7 +5,7 @@ import * as fs from 'fs';
 import * as path from 'path';
 import { AdoptedRepository } from './adopted-repository';
 
-export interface DockerImageAssetProps extends assets.CopyOptions {
+export interface DockerImageAssetProps extends assets.FingerprintOptions {
```
Comment (iliapolo) [inline packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts]: This is a bit confusing. Why make it extend `FingerprintOptions`? This means the `FingerprintOptions.extra` property is now exposed to users, intentional?

Actually, I guess the same argument can be made for extending `CopyOptions` in the first place. Seems like this type if information is not the user's concern.

File: packages/@aws-cdk/assets/test/test.staging.ts [hunk 3]
```diff
@@ -57,5 +57,22 @@ export = {
...
+
+  'allow specifying extra data to include in the source hash'(test: Test) {
+    // GIVEN
+    const app = new App();
+    const stack = new Stack(app, 'stack');
+    const directory = path.join(__dirname, 'fs', 'fixtures', 'test1');
+
+    // WHEN
+    const withoutExtra = new Staging(stack, 'withoutExtra', { sourcePath: directory });
+    const withExtra = new Staging(stack, 'withExtra', { sourcePath: directory, extra: 'boom' });
```
Comment (RomainMuller) [inline packages/@aws-cdk/assets/test/test.staging.ts]: The `extra` here doesn't appear related to the fingerprint at all (the indication is entirely contained in the interface that declares the field initially). This doesn't read so friendly on the usage site :/

File: packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts [hunk 4]
```diff
@@ -93,10 +93,24 @@ export class DockerImageAsset extends Construct implements assets.IAsset {
...
+    if (props.file) {
+      extraHash.push({ file: props.file });
+    }
+
     const staging = new assets.Staging(this, 'Staging', {
       ...props,
       exclude,
-      sourcePath: dir
+      sourcePath: dir,
+      extra: extraHash.length === 0 ? undefined : extraHash.map(x => JSON.stringify(x)).join('=====')
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts]: Why not just make ExtraHash a stringified JSON object? What is the added value of it being an array here?

File: packages/@aws-cdk/assets/test/test.staging.ts (hunk 3 above)
Comment (eladb) [reply packages/@aws-cdk/assets/test/test.staging.ts]: Yeah, good point. Let me see if I can change this without backwards compat breakage. I suspect I can since `FingerprintOptions` was internal.

File: packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts [hunk 5]
```diff
@@ -93,10 +93,24 @@ export class DockerImageAsset extends Construct implements assets.IAsset {
...
+    if (props.buildArgs) {
+      extraHash.push({ buildArgs: props.buildArgs });
+    }
+    if (props.target) {
+      extraHash.push({ target: props.target });
+    }
+    if (props.file) {
+      extraHash.push({ file: props.file });
+    }
+
```
Comment (iliapolo) [inline packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts]: What about `props.repositoryName`? Though it doesn't affect the content of the image, it does affect its name. I think user's will find it surprising that changing the repo name will not have an affect on the asset.

File: packages/@aws-cdk/assets/test/test.staging.ts (hunk 3 above)
Comment (eladb) [reply packages/@aws-cdk/assets/test/test.staging.ts]: Renamed to `extraHash`

Comment (RomainMuller) [reply packages/@aws-cdk/assets/test/test.staging.ts]: Maybe `hashSalt` or `fingerprintSalt` would be better (aka somewhat more descriptive), but `extraHash` is okay, too.

File: packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts (hunk 4 above)
Comment (eladb) [reply packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts]: Done damn you

File: packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts (hunk 2 above)
Comment (eladb) [reply packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts]: This is intentionally exposed to users, so they have control over how the asset is used. For example, they can decide to exclude certain files, or add their own salt to the fingerprint.

Comment (iliapolo) [reply packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts]: Got it 👍

File: packages/@aws-cdk/assets/lib/fs/copy-options.ts (hunk 1 above)
Comment (eladb) [reply packages/@aws-cdk/assets/lib/fs/copy-options.ts]: Renamed the file to `options.ts`

File: packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts (hunk 5 above)
Comment (eladb) [reply packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts]: Added as well

**Comment by amirfireeye** [comment]
Can this behavior be disabled or tuned with some flag? We have the opposite problem where we pass CodeArtifact token as a build arg so every single synth generates a new Docker image.
