### PR TITLE
fix(ecr-assets): give accurate error when Tokens are being used

### LINKED ISSUE #3795: InvalidParameterType error when trying to pass repository_name to DockerImageAsset
### What is the problem?
trying to pass the ECR repository name defined in a Repository object to the DockerImageAsset repository_name attribute and receiving an error upon deployment:

```my-stack-cdk-1 failed: InvalidParameterType: Expected params.repositoryNames[0] to be a string
Expected params.repositoryNames[0] to be a string
```

i'm using the inherited ecr.Repository.repository_name attribute, which should be a string, to pass to the DockerImageAsset but it says that it's not?

### Reproduction Steps
```
        repo = ecr.Repository(
            self,
            id='repo_id',
            repository_name='my-repo',
            lifecycle_rules=[ecr.LifecycleRule(max_image_count=10)]
        )

        repo_image = ecr_assets.DockerImageAsset(
            self,
            id='repo_image_id',
            directory='repo_dir',
            repository_name=repo.repository_name
        )
```

```$ cdk deploy```

### Verbose Log
```
my-stack-cdk-1: deploying...

 ❌  my-stack-cdk-1 failed: InvalidParameterType: Expected params.repositoryNames[0] to be a string
Expected params.repositoryNames[0] to be a string
```

### Environment

  - **CDK CLI Version:** 1.5.0
  - **Module Version:** 1.5.0
  - **OS:** Amazon Linux 2
  - **Language:** Python

### Other information
CDK is awesome! keep up the good work!

### PR DESCRIPTION
**Pull request by rix0rrr**
Fixes #3795.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts [hunk 1]
```diff
@@ -134,6 +134,16 @@ export class DockerImageAsset extends cdk.Construct implements assets.IAsset {
   }
 }
 
+function validateProps(props: DockerImageAssetProps) {
+  for (const [key, value] of Object.entries(props)) {
+    if (Token.isUnresolved(value)) {
+      throw new Error(`Cannot use Token as value of '${key}': this value is used before deployment starts`);
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-ecr-assets/lib/image-asset.ts]: Would be sweet to have some info about what it's used for before deployment starts...
