### PR TITLE
fix(cli): fix the behaviour for the `--generate-only` flag

### LINKED ISSUE #5030: Init with --generate-only is not skipping git init or npm install
Init flag `--generate-only` does not seem to be working as described.  Should skip the git init and npm install, but it is still performing these.

### Reproduction Steps
```
$ cdk init --language=javascript --generate-only
Applying project template app for javascript
Initializing a new git repository...
Executing npm install...
```
```
$ cdk init --language=typescript --generate-only
Applying project template app for typescript
Initializing a new git repository...
Executing npm install...
```

### Environment

  - **CLI Version      :** 1.16.2 (build 5893301)
  - **Framework Version:**
  - **OS               :** MacOS Mojave
  - **Language         :**

### Other
Was able to replicate on other users machines on 1.12.0 (build 923055e), and 1.16.1 (build 9a5a761)

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by netroy**
[Settings stores the flag in camelCase](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/settings.ts#L236). 
But, the flag is [currently read in kebab-case](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/bin/cdk.ts#L241).

This PR fixes the bug, & adds some tests for expected behavior.

Fixes #5030

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk/bin/cdk.ts [hunk 1]
```diff
@@ -238,7 +238,7 @@ async function initCommandLine() {
 
       case 'init':
         const language = configuration.settings.get(['language']);
-        const generateOnly = configuration.settings.get(['generate-only']);
+        const generateOnly = configuration.settings.get(['generateOnly']);
```
Comment (shivlaks) [inline packages/aws-cdk/bin/cdk.ts]: `args.generateOnly` would also be fine here

File: packages/aws-cdk/test/integ/init/test-generate-only.sh [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+
+header "--generate-only"
+
+#------------------------------------------------------------------
+
+echo "Trying --generate-only"
+
+setup
+
+cdk init -l javascript -t app --generate-only
```
Comment (shivlaks) [inline packages/aws-cdk/test/integ/init/test-generate-only.sh]: nit: `app` is already the default and doesn't need to be explicitly specified

File: packages/aws-cdk/test/integ/init/test-generate-only.sh [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+
+if [ -f .git ]
```
Comment (shivlaks) [inline packages/aws-cdk/test/integ/init/test-generate-only.sh]: should this be `-d`, you're checking for a file but `.git` is a directory

File: packages/aws-cdk/bin/cdk.ts (hunk 1 above)
Comment (netroy) [reply packages/aws-cdk/bin/cdk.ts]: Should I remove `generateOnly` from the settings completely then?
Doesn't seem to be used anywhere else.

**Comment by netroy** [comment]
> just to confirm one of the PR checklist items did you also re-run the integ tests and verify they all pass?
@shivlaks I did.
