### PR TITLE
fix(cognito): callback URLs are specified when OAuth is disabled for user pool clients

### LINKED ISSUE #10311: [cognito] UserPoolClient CallbackURLs specified when `disableOAuth` is true
When `disableOAuth` is `true`, `cdk synth` still produces an array of CallbackURLs for a UserPoolClient.

### Reproduction Steps

```ts
import * as cdk from '@aws-cdk/core';
import * as cognito from '@aws-cdk/aws-cognito';

export class CdkStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const userPool = new cognito.UserPool(this, 'UserPool');
    const userPoolClient = new cognito.UserPoolClient(this, 'UserPoolClient', {
      userPool,
      disableOAuth: true
    })
  }
}
```

### What did you expect to happen?

I didn't expect any OAuth values to be present in the `synth`-ed document.

### What actually happened?

```yaml
Resources:
  UserPool6BA7E5F2:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_phone_number
            Priority: 1
          - Name: verified_email
            Priority: 2
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      EmailVerificationMessage: The verification code to your new account is {####}
      EmailVerificationSubject: Verify your new account
      SmsVerificationMessage: The verification code to your new account is {####}
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
        EmailMessage: The verification code to your new account is {####}
        EmailSubject: Verify your new account
        SmsMessage: The verification code to your new account is {####}
    Metadata:
      aws:cdk:path: CdkStack/UserPool/Resource
  UserPoolClient2F5918F7:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId:
        Ref: UserPool6BA7E5F2
      AllowedOAuthFlowsUserPoolClient: false
      CallbackURLs:
        - https://example.com
      SupportedIdentityProviders:
        - COGNITO
    Metadata:
      aws:cdk:path: CdkStack/UserPoolClient/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.62.0,@aws-cdk/assets=1.62.0,@aws-cdk/aws-applicationautoscaling=1.62.0,@aws-cdk/aws-autoscaling-common=1.62.0,@aws-cdk/aws-cloudwatch=1.62.0,@aws-cdk/aws-codeguruprofiler=1.62.0,@aws-cdk/aws-cognito=1.62.0,@aws-cdk/aws-ec2=1.62.0,@aws-cdk/aws-events=1.62.0,@aws-cdk/aws-iam=1.62.0,@aws-cdk/aws-kms=1.62.0,@aws-cdk/aws-lambda=1.62.0,@aws-cdk/aws-logs=1.62.0,@aws-cdk/aws-s3=1.62.0,@aws-cdk/aws-s3-assets=1.62.0,@aws-cdk/aws-sqs=1.62.0,@aws-cdk/aws-ssm=1.62.0,@aws-cdk/cloud-assembly-schema=1.62.0,@aws-cdk/core=1.62.0,@aws-cdk/custom-resources=1.62.0,@aws-cdk/cx-api=1.62.0,@aws-cdk/region-info=1.62.0,jsii-runtime=node.js/v12.18.3
    Condition: CDKMetadataAvailable
```

Specifically, I didn't expect this block to be present:

```yaml
CallbackURLs:
  - https://example.com
```

### Environment

  - **CLI Version      :** 1.62.0 (build 8c2d7fc)
  - **Framework Version:** 1.62.0
  - **Node.js Version:**  v12.18.3
  - **OS               :** macOS
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by shivlaks**
When the `UserPoolClient` property `disableOAuth` is set, callback URLs should not be
rendered as it represents a list of allowed redirects for identity providers.

Added in a condition that only renders the callback URL default of `https://example.com`
if OAuth is enabled.

Closes #10311

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts [hunk 1]
```diff
@@ -320,7 +320,7 @@ export class UserPoolClient extends Resource implements IUserPoolClient {
       explicitAuthFlows: this.configureAuthFlows(props),
       allowedOAuthFlows: props.disableOAuth ? undefined : this.configureOAuthFlows(),
       allowedOAuthScopes: props.disableOAuth ? undefined : this.configureOAuthScopes(props.oAuth),
-      callbackUrLs: callbackUrls && callbackUrls.length > 0 ? callbackUrls : undefined,
+      callbackUrLs: callbackUrls && callbackUrls.length > 0 && !props.disableOAuth ? callbackUrls : undefined,
       logoutUrLs: props.oAuth?.logoutUrls,
```
Comment (nija-at) [inline packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts:324]: I believe we should apply this for logoutUrLs as well.

**Review by nija-at — CHANGES_REQUESTED** [review]
Nice! One small comment.

File: packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts (hunk 1 above)
Comment (shivlaks) [reply packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts:324]: I looked into it, but logoutUrls are embedded inside the `oAuth` (`OAuthSettings` struct) property.
There's validation that currently verifies that `oAuth` and `disableOAuth` are not both simultaneously defined.

It's why I ended up leaving it alone. Let me know if I'm misreading though!

Comment (nija-at) [reply packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts:324]: Oh yes. That's fine then.

File: packages/@aws-cdk/aws-cognito/test/user-pool-client.test.ts [hunk 2]
```diff
@@ -175,6 +175,30 @@ describe('User Pool Client', () => {
...
+    expect(stack).not.toHaveResourceLike('AWS::CognitoUserPoolClient', {
+      CallbackURLs: ['https://example.com'],
+    });
+
+    expect(stack).toHaveResource('AWS::Cognito::UserPoolClient', {
+      AllowedOAuthFlowsUserPoolClient: false,
+      SupportedIdentityProviders: [
+        'COGNITO',
+      ],
+    });
```
Comment (nija-at) [inline packages/@aws-cdk/aws-cognito/test/user-pool-client.test.ts:199]: This test can be made a bit more robust. As it is now, it will pass if the logic you're adding is reverted and the default is changed. Something like this instead would be more accurate - 

```suggestion
    // WHEN
    new UserPoolClient(stack, 'PoolClient', {
      userPool: pool,
      disableOAuth: true,
      callbackUrls: [ 'https://some-other-example.com' ],
    });

    // THEN
    expect(stack).toHaveResourceLike('AWS::CognitoUserPoolClient', {
      CallbackURLs: ABSENT,
    });
```

**Review by nija-at — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-cognito/test/user-pool-client.test.ts (hunk 2 above)
Comment (shivlaks) [reply packages/@aws-cdk/aws-cognito/test/user-pool-client.test.ts]: neat, didn't know about `ABSENT`, will work it in. 

`callbackUrls` are a property contained in the `OAuthSettings` so the test wouldn't quite have that example. Adding the `oAuth` property would again run into validation because we don't allow `oAuth` to be specified if `disableOauth` is set to true.

nonetheless, updating the test!

**Review by nija-at — APPROVED** [review]
