### PR TITLE
fix(toolkit): fix context passed in from command-line

### LINKED ISSUE #1911: Context variable is not found
I am requiring a context variable like so:

```typescript 
this.node.requireContext('env');
const env = this.node.getContext('env');
```

Using aws-cdk 0.25.0, the `env` context variable is not found. Using 0.24.1, this was not an issue:

```
» npx cdk --version
0.25.0 (build 54b5da1)
» npx cdk synth -c env=test

/Users/spgingras/myproject/node_modules/@aws-cdk/cdk/lib/core/construct.ts:243
      throw new Error(`You must supply a context value named '${key}'`);
            ^
Error: You must supply a context value named 'env'
    at ConstructNode.requireContext (/Users/spgingras/myproject/node_modules/@aws-cdk/cdk/lib/core/construct.ts:243:13)
    at new CdkAppStack (/Users/spgingras/myproject/lib/cdk-app-stack.ts:11:15)
    at Object.<anonymous> (/Users/spgingras/myproject/bin/cdk-app.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
Subprocess exited with error 1
» npm i aws-cdk@0.24.1
npm WARN dashboard@0.1.0 No repository field.
npm WARN dashboard@0.1.0 No license field.

+ aws-cdk@0.24.1
added 12 packages from 7 contributors, updated 4 packages and audited 586 packages in 9.536s
found 0 vulnerabilities

» npx cdk --version
0.24.1 (build 67fcf6d)
» npx cdk synth -c env=test
Resources:
[... redacted ...]
```

### PR DESCRIPTION
**Pull request by rix0rrr**
Fix issue where context passed in via command-line was ignored.

Migration behavior has been changed: context that looks like it
has been generated by context providers (keys containing ":")
will upon loading be migrated to `cdk.context.json`; other
context in `cdk.json` will be left as-is and treated as readonly.

Fixes #1911.

----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/aws-cdk/lib/settings.ts [hunk 1]
```diff
@@ -18,10 +18,11 @@ const CONTEXT_KEY = 'context';
  */
 export class Configuration {
   public settings = new Settings();
-  public context = new Context(new Settings(), [], new Settings());
+  public context = new Context(new Settings());
```
Comment (eladb) [inline packages/aws-cdk/lib/settings.ts]: what's up here?

Comment (eladb) [inline packages/aws-cdk/lib/settings.ts]: what's up here?

Comment (eladb) [inline packages/aws-cdk/lib/settings.ts]: what's up here?

File: packages/aws-cdk/lib/settings.ts [hunk 2]
```diff
@@ -40,7 +42,12 @@ export class Configuration {
     this.projectConfig = await loadAndLog(PROJECT_CONFIG);
     this.projectContext = await loadAndLog(PROJECT_CONTEXT);
 
-    this.context = new Context(this.projectConfig, [CONTEXT_KEY], this.projectContext);
+    await this.migrateLegacyContext();
+
+    this.context = new Context(
+        this.commandLineContext,
+        this.projectConfig.subSettings([CONTEXT_KEY]).makeReadOnly(),
+        this.projectContext);
```
Comment (eladb) [inline packages/aws-cdk/lib/settings.ts]: This is a bit tricky, can we special-case it a bit more? Feel wrong to migrate all context that has `:` in it, or we should block this from user-defined context keys.

File: packages/aws-cdk/lib/settings.ts [hunk 3]
```diff
@@ -55,66 +62,103 @@ export class Configuration {
...
+ * writable one.
  */
 export class Context {
-  public modifiedBottom = false;
+  private readonly bags: Settings[];
 
-  constructor(private readonly bottom: Settings, private readonly bottomPrefixPath: string[], private readonly top: Settings) {
+  constructor(bag: Settings, ...bags: Settings[]) {
+    this.bags = [bag, ...bags];
   }
```
Comment (eladb) [inline packages/aws-cdk/lib/settings.ts]: Throw?

Comment (eladb) [inline packages/aws-cdk/lib/settings.ts]: Throw?

Comment (eladb) [inline packages/aws-cdk/lib/settings.ts]: Throw?

**Comment by eladb** [comment]
I guess we need an integ test...

File: packages/aws-cdk/lib/settings.ts (hunk 2 above)
Comment (rix0rrr) [reply packages/aws-cdk/lib/settings.ts]: I'll agree it's not fantastic, but I'd prefer just to take out the migration behavior a couple of releases in the future (maybe for GA) rather than complicate things now.
