### PR TITLE
fix(toolkit): improve error message for large templates

### LINKED ISSUE #34: Error message when trying to deploy without bootstrap stack is confusing
The error message reads as follows:

```
 ⏳  Starting deployment of stack cdk-build-pipelines...
The template for stack cdk-build-pipelines is 170837 bytes long, a CDK Toolkit stack is required for deployment of templates larger than 51,200 bytes. A CDK Toolkit stack can be created using cdk bootstrap '993655754359/us-east-1'
 ❌  Deployment of stack cdk-build-pipelines failed: Error: The template for stack cdk-build-pipelines is larger than 50,200 bytes, and no CDK Toolkit info was provided
The template for stack cdk-build-pipelines is larger than 50,200 bytes, and no CDK Toolkit info was provided
```
The very first error message seems fine. However:

* Basically the same error is shown 3 times.
* There is an inconsistency between the sizes mentioned: one is 51k, the other one is 50.
* "No toolkit info provided" is too low-level to show to the user. "Toolkit info" is terminology internal to the Toolkit implementation, and does not concern the user.

### PR DESCRIPTION
**Pull request by eladb**
Improves the error message the toolkit emits for large templates.

Here's an example output (ignore the template size):

screen shot 2018-10-11 at 2 24 51 pm

Fixes #34

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/aws-cdk/lib/api/deploy-stack.ts [hunk 1]
```diff
@@ -104,11 +106,15 @@ async function makeBodyParameter(stack: cxapi.SynthesizedStack, toolkitInfo?: To
...
-        'A CDK Toolkit stack can be created using %s',
-        stack.name, templateJson.length, colors.blue(`cdk bootstrap '${stack.environment!.name}'`));
-    throw new Error(`The template for stack ${stack.name} is larger than 50,200 bytes, and no CDK Toolkit info was provided`);
+  } else if (templateJson.length > LARGE_TEMPLATE_SIZE_KB * 1024) {
+
+    error(
+      `The template for stack "${stack.name}" is ${Math.round(templateJson.length / 1024)}KiB. ` +
+      `Templates larger than ${LARGE_TEMPLATE_SIZE_KB}KiB must be uploaded to S3.\n` +
+      'Run the following command in order to setup an S3 bucket in this environment, and then re-deploy:\n\n',
+      colors.blue(`    $ cdk bootstrap ${stack.environment!.name}\n`));
```
Comment (RomainMuller) [inline packages/aws-cdk/lib/api/deploy-stack.ts]: Worth using `\t` in there?

File: packages/aws-cdk/lib/api/deploy-stack.ts [hunk 2]
```diff
@@ -104,11 +106,15 @@ async function makeBodyParameter(stack: cxapi.SynthesizedStack, toolkitInfo?: To
...
+
+    throw new Error(`Template for stack "${stack.name}" > ${LARGE_TEMPLATE_SIZE_KB}KiB`);
```
Comment (RomainMuller) [inline packages/aws-cdk/lib/api/deploy-stack.ts]: I would refrain from over-synthesizing the message here...

File: packages/aws-cdk/lib/api/deploy-stack.ts (hunk 1 above)
Comment (eladb) [reply packages/aws-cdk/lib/api/deploy-stack.ts]: done
