### PR TITLE
fix(cli): OS usernames cannot have Unicode characters

### LINKED ISSUE #10401: [cli] cdk deploy using newStyleStackSynthesis cannot handle non-ASCII characters in username
### Steps to reproduce
* Create/use a windows user with a username containing å (might also need to set computer to swedish locale or similar)
* Create a CDK project using newStyleStackSynthesis: true
* Run `cdk deploy <stackname>`

### What did you expect to happen?
Stack to be deployed

### What actually happened?
An error is reported:
```
Could not assume role in target account (did you bootstrap the environment with the right '--trust's?): 1 validation error detected: Value 'aws-cdk-PerGårdebrink' at 'roleSessionName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w+=,.@-]*
```

### Environment

  - **CLI Version      : 1.61-1.63 (at least)**
  - **Framework Version: .NET Core 3.1**
  - **Node.js Version: 12.16.1**
  - **OS               : Windows 10**
  - **Language (Version):**

### Other
This seems like it could be related to the same problem I had before: https://github.com/aws/aws-cdk/issues/7456

I tried to impersonate another local windows user without å in the username and then it worked perfectly with the same AWS credentials

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
When assuming a role for uploading assets in the new-style synthesized
stacks, the OS username was used to build the session name out of.

OS usernames have a character set that is wider than the allowed
characters in `RoleSessionName` though, so we needed to sanitize
them.

Fixes #10401.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by njlynch — CHANGES_REQUESTED** [review]
Code itself looks good; can we add a test?

File: packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts [hunk 1]
```diff
@@ -362,4 +362,13 @@ function readIfPossible(filename: string): string | undefined {
...
+}
+
+/**
+ * Return the username with characters invalid for a RoleSessionName removed
+ *
+ * @see https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html#API_AssumeRole_RequestParameters
+ */
+function safeUsername() {
+  return os.userInfo().username.replace(/[^\w+=,.@-]/g, '@');
 }
```
Comment (nija-at) [inline packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts:374]: Move this into a reusable spot? `os.ts` sounds appropriate?

**Review by nija-at — DISMISSED** [review]

File: packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts:374]: If you are addressing the repetition in this PR, please note that the changes are in 2 different packages and there's no good shared package to put this functionality in otherwise.

If you are addressing potential future reuse, I would argue against optimizing for that beforehand.

**Review by njlynch — APPROVED** [review]
