### PR TITLE
fix(aws-apigateway): make LambdaRestApi proxy by default

### LINKED ISSUE #959: apigateway: default proxypath unless addResource(), ... are called
Today, you must decide whether supply `proxyPath: "/"`, or NOT supply `proxyPath` and call `addResource()`.

For maximum usability, we can default to `proxyPath: /` but reset it to undefined once one of the `addXxx()` methods are called.

Also, if "/" is used for the proxy path, we should automatically install an `ANY` method on the root resource:

```ts
api.root.addMethod('ANY');
```

Otherwise, the root will not route to the proxy.

### PR DESCRIPTION
**Pull request by rix0rrr**
The LambdaRestApi construct now takes a 'proxyAll' argument to enable
forwarding all requests to the given Lambda Function.

BREAKING CHANGE: specifying a path no longer works. If you used to
provide a '/', now supply true. Otherwise, you will have to construct
more complex resource paths yourself.

Fixes #959.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-apigateway/lib/lambda-api.ts [hunk 1]
```diff
@@ -13,15 +15,14 @@ export interface LambdaRestApiProps {
...
-   * An API path for a greedy proxy with an "ANY" method, which will route all
-   * requests under that path to the defined handler.
+   * If true, route all requests to the Lambda Function
    *
-   * If not defined, you will need to explicitly define the API model using
+   * If not set to true, you will need to explicitly define the API model using
    * `addResource` and `addMethod` (or `addProxy`).
    *
-   * @default undefined
+   * @default false
```
Comment (eladb) [inline packages/@aws-cdk/aws-apigateway/lib/lambda-api.ts]: We want the default to be true

File: packages/@aws-cdk/aws-apigateway/lib/lambda-api.ts [hunk 2]
```diff
@@ -49,16 +50,26 @@ export class LambdaRestApi extends RestApi {
...
-    if (proxyPath) {
-      const route = proxyPath.split('/').filter(x => x);
-      let curr = this.root;
-      for (const part of route) {
-        curr = curr.addResource(part);
-      }
-      curr.addProxy();
+    if (props.proxyAll) {
+      this.root.addProxy();
+      this.root.addMethod('ANY');
```
Comment (eladb) [inline packages/@aws-cdk/aws-apigateway/lib/lambda-api.ts]: I am wondering if this should always be done in `addProxy`...

File: packages/@aws-cdk/aws-apigateway/test/test.lambda-api.ts [hunk 3]
```diff
@@ -18,9 +18,14 @@ export = {
     });
 
     // WHEN
-    new apigw.LambdaRestApi(stack, 'lambda-rest-api', { handler, proxyPath: '/' });
+    const api = new apigw.LambdaRestApi(stack, 'lambda-rest-api', { handler, proxyAll: true });
 
-    // THEN
+    // THEN -- can't customize further
+    test.throws(() => {
+      api.root.addResource('cant-touch-this');
```
Comment (eladb) [inline packages/@aws-cdk/aws-apigateway/test/test.lambda-api.ts]: 😉

File: packages/@aws-cdk/aws-apigateway/lib/restapi.ts [hunk 4]
```diff
@@ -214,6 +214,8 @@ export class RestApi extends RestApiRef implements cdk.IDependable {
         return new Method(this, httpMethod, { resource: this.root, httpMethod, integration, options });
       },
       addProxy: (options?: ResourceOptions) => {
+        // Must have ANY method on the root when doing this
+        this.root.addMethod('ANY');
```
Comment (eladb) [inline packages/@aws-cdk/aws-apigateway/lib/restapi.ts]: Would have been nicer if you put this logic in `ProxyResource` in case someone uses it directly. Ideally we want the `addXxx` APIs to behave exactly like using the APIGW constructs directly. You should be able to identify that "parent" is "root" by going back to the API object

File: packages/@aws-cdk/aws-apigateway/lib/resource.ts [hunk 5]
```diff
@@ -179,6 +179,11 @@ export class ProxyResource extends Resource {
       defaultMethodOptions: props.defaultMethodOptions,
     });
 
+    // Add ANY method to parent but only if it's the root
```
Comment (eladb) [inline packages/@aws-cdk/aws-apigateway/lib/resource.ts]: Didn't we say we want this behavior in an override of `addMethod`, so it will apply to methods added manually as well?

**Comment by eladb** [comment]
@rix0rrr merge?
