### PR TITLE
fix(lambda-nodejs): cannot bundle when entry file is named index.ts

### LINKED ISSUE #9709: [@aws-cdk/aws-lambda-nodejs] Bundle fails on 1.58 due to incorrect path.
This is similar to #9673. Though I think that specific error can be resolved by clearing the output cache.

Synth/Deploy fails when using NodeJSFunction on 1.58. Project synthed and deployed fine on 1.56. 

### Reproduction Steps

Upgraded to 1.58 with NodeJSFunction.

```typescript
const forwarderFunction = new NodejsFunction(this, 'myFunction', {
  entry: 'lib/functions/myFunction/index.ts',
  handler: 'handler',
});
```

`cdk synth`

### What did you expect to happen?

Bundle NodeJSFunction code and synth.

### What actually happened?

At first I received:

```shell
../../../../asset-output/index.js    4.3 KB    738ms
mv: ‘/asset-output/index.js’ and ‘/asset-output/index.js’ are the same file
```

Tried to change the name of my entry point

```typescript
const forwarderFunction = new NodejsFunction(this, 'myFunction', {
  entry: 'lib/functions/myFunction/index2.ts',
  handler: 'handler',
});
```

`cdk synth`

```shell
Bundling asset MyStack/myFunction/Code/Stage...
Building index2.ts...
Bundling...
🚨 Build failed.
Error: ENOENT: no such file or directory, stat '/asset-input/lib/functions/myFunction/index.ts'
Error: ENOENT: no such file or directory, stat '/asset-input/lib/functions/myFunction/index.ts'
```

Same error as #9673. **Notice that this is the old path.** Deleted `/.cdk.staging`, `cdk.out`, `.parcel-cache`.

`cdk synth` 

```shell
Bundling asset MyStack/myFunction/Code/Stage...
Building index2.ts...
Bundling...
Packaging index.js...
Optimizing index.js...
✨ Built in 3.21s

../../../../asset-output/index.js    4.3 KB    743ms
mv: cannot stat ‘/asset-output/index2.js’: No such file or directory
```

**Notice it is looking for `index2.js` and not `index.js`.**

### Environment

  - **CLI Version      : 1.58.0**
  - **Framework Version: 1.58.0**
  - **Node.js Version: 10.19.0** 
  - **OS               : Windows 10 - WSL 2 - Ubuntu 20.04 - Docker version 19.03.12, build 48a66213fe**
  - **Language (Version):** TypeScript (3.8.3) -->

### Other

It looks like NodeJSFunction or assets are confusing the file name of the entry point with the computed `/asset-output/index.js`. Using an entry point called `index.ts` has a different error than when the entry point is named something unique. I am also curious if the folder depth matters, but it doesn't seem to since I already am 4 layers deep.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by jogold**
Do not rename the dist file if it's already named `index.js`.

Fixes #9709

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts [hunk 1]
```diff
@@ -168,7 +168,7 @@ export class Bundling {
       // Always rename dist file to index.js because Lambda doesn't support filenames
       // with multiple dots and we can end up with multiple dots when using automatic
       // entry lookup
-      `mv ${cdk.AssetStaging.BUNDLING_OUTPUT_DIR}/${distFile} ${cdk.AssetStaging.BUNDLING_OUTPUT_DIR}/index.js`,
+      distFile !== 'index.js' ? `mv ${cdk.AssetStaging.BUNDLING_OUTPUT_DIR}/${distFile} ${cdk.AssetStaging.BUNDLING_OUTPUT_DIR}/index.js` : '',
```
Comment (thantos) [inline packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts:171]: Would it be less error prone to just have parcel output as index.js? https://github.com/parcel-bundler/parcel/issues/884

Doesn't look like using the entry name has any value and we could remove the parsing on line 155.

```suggestion
      '--out-file index.js'
```

Comment (jogold) [reply packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts:171]: Unfortunately `--out-file` is a Parcel v1 option, not v2. In v2 you need to configure it in the `package.json` but I want to avoid this to allow #9632

Comment (thantos) [reply packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts:171]: Ah, I see. Parcel seems like a pile.
