### PR TITLE
fix(ecs): nat network mode for windows tasks

### LINKED ISSUE #4272: ECS: TaskDefinition.network mode does not support empty (aka <default>) value
When working with ECS clusters and using Windows containers, ```networkMode``` has to be empty. See CloudFormation docs [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-networkmode):

> When you register a task definition with Windows containers, **you must not specify a network mode**.  If you use the console to register a task definition with Windows containers, you must choose the <default> network mode object. 

Current implementation does not support that case. Despite the fact that ```networkMode``` property is nullable, TaskDefinition construct maps it to the default value for Fargate/EC2 enironment:

https://github.com/aws/aws-cdk/blob/462055269c62a475201bbd51dc29768d32e31add/packages/%40aws-cdk/aws-ecs/lib/base/task-definition.ts#L248-L249

### Reproduction Steps

Here is the snippet (in C#, TypeScript would be a direct equivalent):
```c#
    var taskDefinition = new TaskDefinition(this, "apiTask", new TaskDefinitionProps()
    {
        // Important to specify this, see https://github.com/Microsoft/IIS.ServiceMonitor/issues/34
        Cpu = "1024",
        MemoryMiB = "1024",
        Compatibility = Compatibility.EC2,

        // Important for Windows containers! (but it does not work as you would hope)
        NetworkMode = null,
    });
```
Resulting CloudFormation snippet:

```yaml
      NetworkMode: bridge
      RequiresCompatibilities:
        - EC2
```
### Other

I understand that we can't change the current behavior to preserve backward compatibility. What if we add a new ```DEFAULT``` value to [NetworkMode](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.NetworkMode.html) enum to support this Windows-specific case?

I can work on a PR for this.

### PR DESCRIPTION
**Pull request by kolomied**
Add NAT network mode to support Windows container networking.
This is the only network mode supported by Windows.
See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/windows_task_IAM_roles.html for additional details.

fixes #4272

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by kolomied** [comment]
@SoManyHs I'm afraild I need you help here - here is the error from the build:

```
Installing from NPM...
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-cdk/aws-ec2@^1.10.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@aws-cdk/aws-servicediscovery'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-01T15_27_25_592Z-debug.log

[Container] 2019/10/01 15:27:25 Command did not exit successfully /bin/bash ./build.sh exit status 1
[Container] 2019/10/01 15:27:25 Phase complete: BUILD State: FAILED
[Container] 2019/10/01 15:27:25 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: /bin/bash ./build.sh. Reason: exit status 1
```
Just successfully re-run ./build.sh locally without any errors. I'm puzzled because I didn't change **ec2** module at all.

File: packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts [hunk 1]
```diff
@@ -428,6 +428,18 @@ export class TaskDefinition extends TaskDefinitionBase {
   private findContainer(containerName: string): ContainerDefinition | undefined {
     return this.containers.find(c => c.containerName === containerName);
   }
+
+  private isEphemeralPortMappingSupported(networkMode: NetworkMode): boolean {
+    return networkMode === NetworkMode.BRIDGE || networkMode === NetworkMode.NAT;
+  }
+
+  private renderNetworkMode(networkMode: NetworkMode): string | undefined {
+    // 'NAT' is the only supported network mode for Windows containers,
```
Comment (iamhopaul123) [inline packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts]: Since it is also explained in the ENUM def, I think you can combine those lines of comment into the ENUM one.

File: packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts [hunk 2]
```diff
@@ -275,7 +275,7 @@ export class TaskDefinition extends TaskDefinitionBase {
         ...(isEc2Compatible(props.compatibility) ? ["EC2"] : []),
         ...(isFargateCompatible(props.compatibility) ? ["FARGATE"] : []),
       ],
-      networkMode: this.networkMode,
+      networkMode: this.renderNetworkMode(this.networkMode),
```
[the remark this answers is not in the document]
Comment (kolomied) [reply packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts]: Please correct me if my understanding is inaccurate or I miss your point.

The only special case we have for ```networkMode``` is when explicit value is _not_ provided by the caller. In this case we fallback to ```AWS_VPN``` or ```BRIDGE``` depending on Fargate compatibility.

If network mode is explicitly provided it should be used by the construct. In other words, the following test should pass:

```typescript
// GIVEN
const stack = new cdk.Stack();

// WHEN
const taskDefinition = new ecs.TaskDefinition(stack, 'TD', {
  compatibility: ecs.Compatibility.EC2,
  networkMode: NetworkMode.NAT
});

// THEN
test.equal(taskDefinition.networkMode, NetworkMode.NAT);
```
My understanding was that we keep simple/unambiguous API on ```TaskDefinition``` level (as defined above) and "work our magic" during translation into CloudFormation representation. 

That is what ```renderNetworkMode``` does - it encapsulates peculiar knowledge about network mode for Windows containers which must be represented as undefined value in CloudFormation template. 

Note that this method does not change construct's ```networkMode``` - it merely  translates it into appropriate CloudFormation value. Therefore, I believe, port range mapping below will work correctly - both ```BRIDGE``` and ```NAT``` modes support ephemeral ports and I verify that in unit tests.

File: packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts (hunk 1 above)
Comment (kolomied) [reply packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts]: Sure, makes sense. Thanks!

File: packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (iamhopaul123) [reply packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts]: Got you! I agree with that.

File: packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts [hunk 3]
```diff
@@ -428,6 +428,14 @@ export class TaskDefinition extends TaskDefinitionBase {
   private findContainer(containerName: string): ContainerDefinition | undefined {
     return this.containers.find(c => c.containerName === containerName);
   }
+
+  private isEphemeralPortMappingSupported(networkMode: NetworkMode): boolean {
+    return networkMode === NetworkMode.BRIDGE || networkMode === NetworkMode.NAT;
```
Comment (pkandasamy91) [inline packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts]: nit: personally, I'd prefer these conditions in the if statement itself, just to allow for ease of debugging.

Comment (kolomied) [reply packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts]: No problem, will address that
