### PR TITLE
fix(cli): `cdk deploy` hangs when stack deployment fails

### LINKED ISSUE #6403: CDK won't exit if the deployment of nested stack failed and rollback completed
CDK cli stuck on running if the deployment of nested stack failed and rollback completed. Have to kill the process to exit the CDK app.

### Reproduction Steps

1. create an app with nested stack
1. successfully deploy the stack and nested stack 
1. modify the nested stack to cause deployment failure, such as running ec2 instances exceeding the limit
1. deploy the updated stack again, the nested stack will fail, but the cdk command is still running the nested stack and parent stack have been rollbacked completely.

### Error Log

image

### Environment

  - **CLI Version      :*1.25.0*
  - **Framework Version:**
  - **OS               :*macosx*
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by shivlaks**
Previously, when a stack would fail deployment we were using process.exit() which exited as quickly as possible, even if async operations were pending.

We rectified that by setting process.exitCode = 1 to allow all output to be flushed before a graceful exit. However, since we were not handling deployment errors, the Stack Activity Monitor was still polling every 5 seconds as the monitor is never explicitly halted.

With this change, when a stack deployment fails, we halt the monitor before throwing the error. This ensures that there are no open handles when we call process.exitCode = 1

Root caused by installing [wtfnode](https://www.npmjs.com/package/wtfnode) as a dev dependency and calling `wtf.dump()` at the exit point. The only outstanding handle was the polling that the Stack Activity Monitor performs every 5 seconds. 

Fixes #6403

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk/lib/api/deploy-stack.ts [hunk 1]
```diff
@@ -151,7 +151,16 @@ export async function deployStack(options: DeployStackOptions): Promise<DeploySt
     // tslint:disable-next-line:max-line-length
     const monitor = options.quiet ? undefined : new StackActivityMonitor(cfn, deployName, options.stack, (changeSetDescription.Changes || []).length).start();
     debug('Execution of changeset %s on stack %s has started; waiting for the update to complete...', changeSetName, deployName);
-    await waitForStack(cfn, deployName);
+    try {
+      await waitForStack(cfn, deployName);
+    } catch (e) {
```
Comment (eladb) [inline packages/aws-cdk/lib/api/deploy-stack.ts]: why not `finally`?

**Comment by eladb** [comment]
plz add an integ test

File: packages/aws-cdk/lib/api/deploy-stack.ts (hunk 1 above)
Comment (shivlaks) [reply packages/aws-cdk/lib/api/deploy-stack.ts]: no good reason, that's cleaner! thanks for the suggestion

**Comment by iliapolo** [comment]
@eladb @rix0rrr added the integ test. Notice that the test isn't really failing, it will just hang if we introduce the bug again. I imagine we have timeout configured on the build right? Are we good with this in the meantime? 

I thought about using the `timeout` command to limit the execution, but it doesn't exist on mac and also requires some twicking to get the asserts just right. I will work on it but i think this should be fine for now so we can release.

File: packages/aws-cdk/test/integ/cli/app/app.js [hunk 2]
```diff
@@ -117,6 +118,23 @@ class DockerStackWithCustomFile extends cdk.Stack {
 
 }
 
+class FailedStack extends cdk.Stack {
+
+  constructor(parent, id, props) {
+    super(parent, id, props);
+
+    new s3.Bucket(this, 'MyBucket1', {
+      bucketName: 'one-will-fail'
```
Comment (eladb) [inline packages/aws-cdk/test/integ/cli/app/app.js]: Add deletionPolicy and use a very long and creepy name 

Bucket names are world global

Comment (iliapolo) [reply packages/aws-cdk/test/integ/cli/app/app.js]: will do

File: packages/aws-cdk/lib/api/deploy-stack.ts [hunk 3]
```diff
@@ -151,9 +151,12 @@ export async function deployStack(options: DeployStackOptions): Promise<DeploySt
...
     const monitor = options.quiet ? undefined : new StackActivityMonitor(cfn, deployName, options.stack, (changeSetDescription.Changes || []).length).start();
     debug('Execution of changeset %s on stack %s has started; waiting for the update to complete...', changeSetName, deployName);
-    await waitForStack(cfn, deployName);
-    if (monitor) {
-      await monitor.stop();
+    try {
+      await waitForStack(cfn, deployName);
+    } finally {
+      if (monitor) {
+        await monitor.stop();
```
Comment (rix0rrr) [inline packages/aws-cdk/lib/api/deploy-stack.ts]: Not that you need to change it, but I think we can forego the `if` and write`

```ts
await monitor?.stop();
```

These days...

File: packages/aws-cdk/test/integ/cli/app/app.js (hunk 2 above)
Comment (rix0rrr) [reply packages/aws-cdk/test/integ/cli/app/app.js]: Can we not make an invalid CloudFormation deployment some other way, rather than involving S3?

For example, create a role and add an empty IAM Policy with `force: true`.

Comment (rix0rrr) [reply packages/aws-cdk/test/integ/cli/app/app.js]: Or just make an empty CfnResource which is an `AWS::IAM::Policy` with nothing else, will fail as well.

File: packages/aws-cdk/test/integ/cli/test-cdk-failed-deploy-doesnt-hang.sh [hunk 4]
```diff
@@ -0,0 +1,17 @@
...
+set -euo pipefail
+scriptdir=$(cd $(dirname $0) && pwd)
+source ${scriptdir}/common.bash
+# ----------------------------------------------------------
+
+setup
+
+set +e
+# this will hang if we introduce https://github.com/aws/aws-cdk/issues/6403 again.
+cdk deploy -v ${STACK_NAME_PREFIX}-failed
```
Comment (rix0rrr) [inline packages/aws-cdk/test/integ/cli/test-cdk-failed-deploy-doesnt-hang.sh]: Can we also verify that it exited with an error code, while we're at it?

Comment (iliapolo) [reply packages/aws-cdk/test/integ/cli/test-cdk-failed-deploy-doesnt-hang.sh]: yeap

File: packages/aws-cdk/test/integ/cli/app/app.js (hunk 2 above)
Comment (iliapolo) [reply packages/aws-cdk/test/integ/cli/app/app.js]: That sounds better. I'll try it.
