### PR TITLE
fix(apigatewayv2): vpclink - explicit subnet specification still causes private subnets to be included

### LINKED ISSUE #12083: (apigatewayv2): VpcLink subnet selection ignored
```typescript
new apiGateway.VpcLink(stack, 'VpcLink', {
   vpc: props.vpc,
   vpcLinkName: 'VpcLink',
   subnets: []
})
```
would result in all VPC subnets being added
```Yaml
  VpcLink66988216:
    Type: AWS::ApiGatewayV2::VpcLink
    Properties:
      Name: VpcLink
      SubnetIds:
        - Ref: XXXSubnet1SubnetC63F3793
        - Ref: XXXSubnet2SubnetB84D1BD7
        - Ref: XXXSubnet3Subnet6C7F7A39
      SecurityGroupIds: []
```
while
```typescript
new apiGateway.VpcLink(stack, 'VpcLink', {
   vpc: props.vpc,
   vpcLinkName: 'VpcLink',
   subnets: [subnet2, subnet3]
})
```
would result in all VPC subnets being added PLUS the extras repeated
```Yaml
  VpcLink66988216:
    Type: AWS::ApiGatewayV2::VpcLink
    Properties:
      Name: VpcLink
      SubnetIds:
        - Ref: XXXSubnet1SubnetC63F3793
        - Ref: XXXSubnet2SubnetB84D1BD7
        - Ref: XXXSubnet3Subnet6C7F7A39
        - Ref: XXXSubnet2SubnetB84D1BD7
        - Ref: XXXSubnet3Subnet6C7F7A39
      SecurityGroupIds: []
```

### What did you expect to happen?

Select only specific subnets to deploy link to to resolve an issue with
`Subnet 'subnet-0dfd3813bb77f3d7a' is in Availability Zone 'ape1-az1' where service is not available (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException;` happening for unknown reasons

### What actually happened?

Cannot make workaround as the problematic subnet remains in the list in CloudFormation

### Environment

  - **CDK CLI Version  :** 1.78
  - **Framework Version:** 1.78
  - **Node.js Version:** 12.20.0
  - **OS               :** MacOS 10.15.7
  - **Language (Version):** Typescript 3.9.7

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by ayush987goyal**
fix(apigatewayv2): specifying subnets to vpclink explicitly adds extra subnets

BREAKING CHANGE: `subnets` prop in `VpcLink` resource now takes `SubnetSelection` instead of `ISubnet[]`

closes #12083

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-apigatewayv2/lib/http/vpc-link.ts [hunk 1]
```diff
@@ -99,10 +99,10 @@ export class VpcLink extends Resource implements IVpcLink {
 
     this.vpcLinkId = cfnResource.ref;
 
-    this.addSubnets(...props.vpc.privateSubnets);
-
-    if (props.subnets) {
```
Comment (nija-at) [inline packages/@aws-cdk/aws-apigatewayv2/lib/http/vpc-link.ts:104]: Should we switch `subnets` property from `ec2.ISubnet[]` to `ec2.SubnetSelection`? The latter seems more suitable here.

(Sorry if we've discussed this already in the original PR, and I've forgotten)

Comment (ayush987goyal) [reply packages/@aws-cdk/aws-apigatewayv2/lib/http/vpc-link.ts:104]: This is the reasoning I gave in the original PR
>The `vpc` itself only has `ISubnet` array as the member variable and I couldn't find an easy way to convert one to other. Hence kept it `ISubnet`

Let me explore it again once.

Comment (ayush987goyal) [reply packages/@aws-cdk/aws-apigatewayv2/lib/http/vpc-link.ts:104]: @nija-at Used `SubnetSelection` instead of `ISubnet[]` and I do agree this is a better API. This will hence be a breaking change. Updated the title description accordingly

**Review by nija-at — APPROVED** [review]
Nice! 💯

**Comment by ayush987goyal** [comment]
@nija-at The title of this fix can be misleading since by default we add private subnets of the VPC
