### PR TITLE
fix(ssm): invalid parameter arn

### LINKED ISSUE #4672: bug in the ssm grant_read
Hi, 
when I trust my lambda with ssm, the resource generated forget the "/":

arn:aws:ssm:REGION:ACCOUNT:parameter**SSMPARAM**
the correct way is:
arn:aws:ssm:REGION:ACCOUNT:parameter/**SSMPARAM**

### Reproduction Steps

self.api_key_ssm_param.grant_read(lambda)

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :** MACOS
  - **Language         :** python3

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by eladb**
We were missing a "/" as a prefix to the parameter name when rendering
parameter ARNs.

Fixes #4672

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-ssm/test/test.parameter.ts [hunk 1]
```diff
@@ -445,5 +445,43 @@ export = {
...
+    const case1 = ssm.StringParameter.fromStringParameterName(stack, `p${i++}`, 'bam');
+    const case2 = ssm.StringParameter.fromStringParameterName(stack, `p${i++}`, '/bam');
+    const case3 = ssm.StringParameter.fromStringParameterName(stack, `p${i++}`, param.valueAsString);
+    const case4 = ssm.StringParameter.fromStringParameterAttributes(stack, `p${i++}`, { parameterName: 'bam' });
+    const case5 = ssm.StringParameter.fromStringParameterAttributes(stack, `p${i++}`, { parameterName: '/bam' });
+    const case6 = ssm.StringParameter.fromStringParameterAttributes(stack, `p${i++}`, { parameterName: param.valueAsString });
+    const case7 = ssm.StringParameter.fromSecureStringParameterAttributes(stack, `p${i++}`, { parameterName: 'bam', version: 10 });
+    const case8 = ssm.StringParameter.fromSecureStringParameterAttributes(stack, `p${i++}`, { parameterName: '/bam', version: 10 });
+    const case9 = ssm.StringParameter.fromSecureStringParameterAttributes(stack, `p${i++}`, { parameterName: param.valueAsString, version: 10 });
+    const case10 = new ssm.StringParameter(stack, `p${i++}`, { stringValue: 'value' });
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-ssm/test/test.parameter.ts]: minor: this grouping seems fine, but it still feels like this test is doing a lot. might be time to simplify and split it into tests for each of the `from*` methods

Comment (eladb) [reply packages/@aws-cdk/aws-ssm/test/test.parameter.ts]: I don't think we should over-engineer this.
