### PR TITLE
fix(core): CFN version and description template sections were merged incorrectly

### LINKED ISSUE #8151: Multiple instances of CfnInclude cause TypeError
Upon using cdk.CfnInclude multiple times, a TypeError is raised. The content or ordering of the templates doesn't appear to make a difference. Both the templates in the below example will synth correctly when used individually.

### Reproduction Steps

```ts
import * as cdk from '@aws-cdk/core';
import * as fs from 'fs';
import * as YAML from 'yaml';

export class CdkStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new cdk.CfnInclude(this, "Artifacts", {
      template: YAML.parse(
        fs.readFileSync("../test1.yml").toString()
      ),
    });

    new cdk.CfnInclude(this, "Buckets", {
      template: YAML.parse(
        fs.readFileSync("../test2.yml").toString()
      ),
    });
}
```

### Error Log

```
/Users/jd/git/admin/build/cdk/node_modules/@aws-cdk/core/lib/stack.ts:988
        if (id in dest) {
              ^
TypeError: Cannot use 'in' operator to search for '0' in 2010-09-09
    at merge (/Users/jd/git/admin/build/cdk/node_modules/@aws-cdk/core/lib/stack.ts:988:15)
    at CdkStack._toCloudFormation (/Users/jd/git/admin/build/cdk/node_modules/@aws-cdk/core/lib/stack.ts:846:7)
    at CdkStack.synthesize (/Users/jd/git/admin/build/cdk/node_modules/@aws-cdk/core/lib/stack.ts:762:38)
    at CdkStack.onSynthesize (/Users/jd/git/admin/build/cdk/node_modules/@aws-cdk/core/lib/construct-compat.ts:123:10)
    at Node.synthesize (/Users/jd/git/admin/build/cdk/node_modules/constructs/lib/construct.ts:407:28)
    at Function.synth (/Users/jd/git/admin/build/cdk/node_modules/@aws-cdk/core/lib/construct-compat.ts:231:22)
    at App.synth (/Users/jd/git/admin/build/cdk/node_modules/@aws-cdk/core/lib/app.ts:142:36)
    at process.<anonymous> (/Users/jd/git/admin/build/cdk/node_modules/@aws-cdk/core/lib/app.ts:121:45)
    at Object.onceWrapper (events.js:428:26)
    at process.emit (events.js:321:20)
Subprocess exited with error 1
```

### Environment

  - **CLI Version      :** 1.41.0 (build 9e071d2)
  - **Framework Version:** uncertain
  - **OS               :** MacOS 10.15.1
  - **Language         :** English

### Other

Contents of the test templates:

test1.yml:
```yaml
---
AWSTemplateFormatVersion: "2010-09-09"
Description: Test 1

Resources:
  DummyResource:
    Type: AWS::CloudFormation::WaitConditionHandle

```

test2.yml:
```yaml
---
AWSTemplateFormatVersion: "2010-09-09"
Description: Test 2

Resources:
  DummyResource:
    Type: AWS::CloudFormation::WaitConditionHandle

```

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by skinny85**
In the merge logic in Stack when rendering the template,
it was mistakenly assumed that all CFN sections are objects.
However, there are some sections, like Description and AWSTemplateFormatVersion,
that are in fact strings.
Add special logic for those cases in the merge functionality
(multiple provided CFN versions are checked for being identical,
and multiple descriptions are merged together, with a newline in between).

Fixes #8151

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/core/lib/stack.ts [hunk 1]
```diff
@@ -848,12 +848,32 @@ function merge(template: any, part: any) {
...
+          dest[id] = src[id];
+        }
+      } else {
+        // the sections are strings, like Description and AWSTemplateFormatVersion
+        // treat each differently
+        switch (section) {
+          case 'Description':
+            // merge the two descriptions, with a newline in between
+            template[section] = `${dest}\n${src}`;
+            break;
```
Comment (nija-at) [inline packages/@aws-cdk/core/lib/stack.ts:866]: This is a weird choice. I would say either error or destination wins. 

In the case of CfnInclude, I think it's fair to say that if the description was altered after import, the altered description wins.

Comment (skinny85) [reply packages/@aws-cdk/core/lib/stack.ts:866]: This is not about "altering" - this is the case when `Description` was provided from multiple places. See the test for this:

```ts
    new CfnInclude(stack, 'T1', {
      template: {
        AWSTemplateFormatVersion: '2010-09-09',
        Description: 'Test 1',
      },
    });
    new CfnInclude(stack, 'T2', {
      template: {
        AWSTemplateFormatVersion: '2010-09-09',
        Description: 'Test 2',
      },
    });
```

File: packages/@aws-cdk/core/lib/stack.ts [hunk 2]
```diff
@@ -848,12 +848,32 @@ function merge(template: any, part: any) {
     if (!dest) {
       template[section] = dest = src;
     } else {
-      // add all entities from source section to destination section
-      for (const id of Object.keys(src)) {
-        if (id in dest) {
-          throw new Error(`section '${section}' already contains '${id}'`);
+      if (typeof dest === 'object') {
```
Comment (rix0rrr) [inline packages/@aws-cdk/core/lib/stack.ts:851]: This will do in a pinch, but you're assuming the source templates already conform to a schema without mistakes, and your code will do unexpected things otherwise.  Also, this code is getting long in the tooth and needs to be broken up into functions which each do a clearly defined small thing.

I'd rather see something like this:

```ts
function merge(a: object, b: object) {
  const ret: any = {};
  for (const key of new Set(Object.keys(a).concat(Object.keys(b)))) {
    ret[key] = mergeSection(key, a[key], b[key]);
  }
  return ret;
}

function mergeSection(section: string, a: any, b: any) {
  switch (section) {
    case 'Description': /* ... validate a and b are string | undefined */ return `${a}\n${b}`;
    case 'AWSTemplateFormatVersion': // ...;
    case 'Resources':
    case 'Conditions':
    case 'Parameters':
    case 'Outputs':
     return mergeObjectsWithoutDuplicates(a, b);  // mergeObjects should validate that they are indeed objects | undefined
    default: 
     throw new Error(`Wut? I don't know how to merge ${section}`);
  }
}
```

Comment (skinny85) [reply packages/@aws-cdk/core/lib/stack.ts]: Done!
