### PR TITLE
fix(core): throw on intrinsics in CFN update and create policies

### LINKED ISSUE #27578: core: CfnParser incorrectly drops UpdatePolicy elements that use intrinsic functions
### Describe the bug

The CfnParser class does not correctly parse UpdatePolicy attributes that use intrinsic functions.  CloudFormation allows the use of intrinsic functions, such as `Fn::If` in Update Policy attributes (see [CFN docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html)).  If you have a CloudFormation template that uses intrinsics in an Update Policy and try to parse it using CfnInclude, the CfnParser will completely drop the unsupported Update Policy attributes from what gets included into the CfnInclude construct.

I've tracked down this behavior to the `parseUpdatePolicy()` [method ](https://github.com/aws/aws-cdk/blob/v2.99.1/packages/aws-cdk-lib/core/lib/helpers-internal/cfn-parse.ts#L412) in the CfnParser class.  It first invokes the `parseValue()` method, which will correctly return any Resolvable objects or intrinsics without modification.  The problem comes from the parse methods for individual attributes, like [parseAutoScalingRollingUpdate()](https://github.com/aws/aws-cdk/blob/v2.99.1/packages/aws-cdk-lib/core/lib/helpers-internal/cfn-parse.ts#L435).  Those functions all expect to find the specific keys that the attribute supports, so if they get an intrinsic like `Fn::If` instead, they will return undefined, effectively removing the UpdatePolicy attribute from the parsed result.

### Expected Behavior

When using CfnInclude with a template that includes UpdatePolicy attributes with intrinsics in them, the UpdatePolicy should be correctly parsed and included in the CDK construct.

### Current Behavior

Any UpdatePolicy attributes that use intrinsics get lost when parsing with CfnInclude

### Reproduction Steps

Create a CloudFormation template with an UpdatePolicy that looks like this:
```
{
  "Type": "AWS::AutoScaling::AutoScalingGroup",
  "Properties" : {...},
  "UpdatePolicy": {
    "AutoScalingRollingUpdate": {
      "Fn::If": [
        "AutoReplaceHosts",
        {
          "MinInstancesInService": {
          "Fn::If": [
            "SetMinInstancesInServiceToZero",
            0,
            1
          ]
        },
        "MaxBatchSize": {
          "Ref": "ReplaceHostsMaxBatchSize"
        },
        "PauseTime": {
          "Ref": "ASGTimeout"
        },
        "WaitOnResourceSignals": "true"
      },
      {
        "Ref": "AWS::NoValue"
      }
    ]
  }
}
```

Then include that template into a CDK app with CfnInclude:
```
const importedTemplate = new CfnInclude(stack, 'importedTemplate', {templateFile: 'path/to/template.json'});
```

If you look at the final stack definition template generated by the CDK you'll see that the AutoScalingGroup is missing the UpdatePolicy defined in the originally included CFN template.

### Possible Solution

The logic in `CfnParser.parseUpdatePolicy‎()` should be updated to leave any parsed values that contain Resolvable objects or Intrinsics unmodified, similar to what the `parseValue()` function does.  The biggest challenge here is going to be the type system -- `parseUpdatePolicy` returns a strongly typed `CfnUpdatePolicy` object and the type system there doesn't really account for intrinsics or tokens.  Returning an `IResolvable` (via `Token.asAny()`) is probably the best alternative that stays within the type system, but I don't know what the downstream impact of that would be, since it would require changing the type definitions in CfnUpdatePolicy.  The other alternative is to just cast it to CfnUpdatePolicy and ignore the fact that the types don't actually match.

### Additional Information/Context

_No response_

### CDK CLI Version

2.94

### Framework Version

_No response_

### Node.js Version

18.16.0

### OS

Linux

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### LINKED ISSUE #30740: CfnLoadBalancer: CfnInclude broken for conditional tags
### Describe the bug

When you attempt to CfnInclude a `AWS::ElasticLoadBalancingV2::LoadBalancer` resource with valid conditional tags CDK errors out

### Expected Behavior

CfnInclude should succeed

### Current Behavior

An error is thrown:

```
CfnSynthesisError: Resolution error: Supplied properties not correct for "CfnLoadBalancerProps"                                                                                                                                                                                              
  tags: element 1: {} should have a 'key' and a 'value' property. 
  ```

### Reproduction Steps

Create a stack and include the following:

```
const template = `{                                                                                                                         
  "AWSTemplateFormatVersion": "2010-09-09",                             
  "Parameters": {                                                      
    "IsExtraTag": {                                                       
      "Type": "String",            
      "AllowedValues": [                                                  
        "true",                                                           
        "false"                             
      ],                                                                                                                                            
      "Default": "false"                                                                                                                                                                                                                                                                                 
    }                                                                                                                                                                                                                                                                                                    
  },                                                                                                                                                
  "Conditions": {                        
    "AddExtraTag": {                                                 
      "Fn::Equals": [                                                                                                                               
        {                                                                                                                                           
          "data": "IsExtraTag",                                  
          "type": "Ref",                                 
          "isCfnFunction": true                                                                                                                     
        },                                                             
        "true"                                                                                                                                      
      ]                                                        
    }                                                                                                                                               
  },                                                                                                                                                
  "Resources": {                                                                                                                                    
    "MyLoadBalancer": {                                                
      "Type": "AWS::ElasticLoadBalancingV2::LoadBalancer",                                                                                          
      "Properties": {                                        
        "Name": "my-load-balancer",                                                                                                                 
        "Subnets": [                                                                                                                                
          "subnet-0123456789abcdef0"                                                                                                                                                                                                                                                                     
        ],                                                                                                                                          
        "SecurityGroups": [                                               
          "sg-0123456789abcdef0"                                                                                                                    
        ],                                                                
        "Scheme": "internet-facing",                                                                                                                
        "LoadBalancerAttributes": [                                       
          {                                                                                                                                         
            "Key": "idle_timeout.timeout_seconds",                      
            "Value": "60"                                                                                                                           
          }                                                               
        ],                         
        "IpAddressType": "ipv4",                                          
        "Tags": [                                                                                                                                   
          {                                 
            "Key": "Name",                                                                                                                          
            "Value": "MyLoadBalancer"                                                                                                                                                                                                                                                                    
          },                                                                                                                                                                                                                                                                                             
          {                                                                                                                                         
            "data": [                          
              "IsExtraTag",                                          
              {                                                                                                                                     
                "Key": "Name2",                                                                                                                     
                "Value": "MyLoadBalancer2"                       
              },                                         
              {                                                                                                                                     
                "data": "AWS::NoValue",                                
                "type": "Ref",                                                                                                                      
                "isCfnFunction": true                          
              }                                                                                                                                     
            ],                                                                                                                                      
            "type": "Fn::If",                                                                                                                       
            "isCfnFunction": true                                      
          }                                                                                                                                         
        ]                                                    
      }                                                                                                                                             
    }                                                                                                                                               
  }
}`;

const tmpobj = tmp.fileSync();                                                                                                                    
                                                                          
fs.writeFileSync(tmpobj.fd, template);                                                                                                            
                                                                          
new CfnInclude(this, 'MyStack', {                                                                                                                 
    templateFile: tmpobj.name                                         
});                                                                                                                                               
                                                                          
tmpobj.removeCallback();  
```

You will get the exception
```
CfnSynthesisError: Resolution error: Supplied properties not correct for "CfnLoadBalancerProps"                                                     
  tags: element 1: {} should have a 'key' and a 'value' property.    
  ```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.87.0

### Framework Version

_No response_

### Node.js Version

v18.18.2

### OS

AL2

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by comcalvi**
### Issue # (if applicable)

Closes #27578, Closes #30740.

### Reason for this change

`cfn-include` only allows Intrinsics in resource update and create policies to wrap primitive values. If Intrinsics are included anywhere else, `cfn-include` silently drops them. 

CDK's type system [does not allow](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/core/lib/cfn-resource-policy.ts) intrinsics in resource policies unless they define a primitive value. `cfn-include` adheres to this type system and drops any resource policies that use an intrinsic to define a complex value. This is an example of a forbidden use of intrinsics:

```
  "Resources": {
    "ResourceSignalIntrinsic": {
     // ....
      "CreationPolicy": {
        "ResourceSignal": {
          "Fn::If": [
            "UseCountParameter",
            {
              "Count": { "Ref": "CountParameter" }
            },
            5
          ]
        }
      }
    }
  }
}
```

This is forbidden because an intrinsic contains the `Count` property of this policy. CFN allows this, but CDK's type system does not permit it. 

### Description of changes

`cfn-include` will throw if any intrinsics break the type system, instead of silently dropping them.

CDK's type system is a useful constraint around these resource update / create policies because it allows constructs that modify them, like autoscaling, to not be token-aware. Tokens are not resolved at synthesis time, so it makes it impossible to modify these with simple arithmetic if they contain tokens. 

The CDK will never (or at least should not) generate a token that breaks this type system.

Thus, the only use-case for allowing these tokens is `cfn-include`. Supporting these customers would require the CDK type system to allow these, and thus CDK L2s should handle such cases; except, for L2 customers, this use-case does not happen. Explicitly reject templates that don't conform to this. 

Throwing here is a breaking change, so this is under a feature flag. 

Additionally add a new property, `dehydratedResources` -- a list of logical IDs that `cfn-include` will not parse. Those resources still exist in the final template.

This does not impact L2 users.

### Description of how you validated changes

Unit testing. 

Manually verified that this does not impact any L2s. 

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by rix0rrr — APPROVED** [review]

File: packages/aws-cdk-lib/cloudformation-include/lib/cfn-include.ts [hunk 1]
```diff
@@ -66,6 +66,14 @@ export interface CfnIncludeProps {
    * @default - will throw an error on detecting any cyclical references
    */
   readonly allowCyclicalReferences?: boolean;
+
+  /**
+   * Specifies a list of LogicalIDs for resources that will be included in the CDK Stack,
+   * but will not be parsed and converted to CDK types. This allows you to use CFN templates
+   * that rely on Intrinsic placement that `cfn-include`
+   * would otherwise reject, such as non-primitive values in resource update policies.
```
Comment (rix0rrr) [inline packages/aws-cdk-lib/cloudformation-include/lib/cfn-include.ts:74]: `*@default - All resources are hydrated`
