### PR TITLE
fix(scheduler): scheduleName returns undefined when imported from ARN

### LINKED ISSUE #36361: aws_scheduler: `scheduleName` returns `undefined`
### Describe the bug

Using the `scheduleName` property for an `ISchedule` does not return the name. Instead, it returns undefined.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Library Version

_No response_

### Expected Behavior

To retrieve the `scheduleName`

### Current Behavior

`scheduleName` is undefined

### Reproduction Steps

Using an imported schedule, try to retrieve the `scheduleName` property, this will not work unfortunately. 

### Possible Solution

After looking into this a bit more, I've noticed in the code, we use the [following](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-scheduler/lib/schedule.ts#L260) function to retrieve the name from the ARN (since the ARN is provided, not the schedule name). Extracting the result of the function call itself (not the property) returns the following:
```JSON
{
  "partition": "aws",
  "service": "scheduler",
  "region": "ab-cdef-0",
  "account": "xxxxxxxxxxx",
  "resource": "schedule",
  "resourceName": "SCHEDULE-GROUP",
  "sep": "/",
  "arnFormat": "arn:aws:service:region:account:resource/resourceName"
}
```
So it seems to return the `SCHEDULE-GROUP` name only, and since [the code](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-scheduler/lib/schedule.ts#L260) does a `.split` and retrieves the second element, this is undefined.

To fix this, I would suggest the following:
1. This would probably be done within the `core` module, to include an option for this ARN format.
2. Either update this property to actually return the schedule name, or add a new property for backwards compatibility (e.g. `scheduleNameV2`)
3. An optional extra, but there could be a new property for the schedule group (`scheduleGroup`)

### Additional Information/Context

_No response_

### AWS CDK Library version (aws-cdk-lib)

aws-cdk-lib@2.209.1

### AWS CDK CLI version

2.1023.0

### Node.js Version

v20.11.0

### OS

Windows 11

### Language

TypeScript

### Language Version

TypeScript (5.3.3)

### Other information

_No response_

### PR DESCRIPTION
**Pull request by mazyu36**
### Issue # (if applicable)

Closes #36361.

### Reason for this change

When importing a schedule using `Schedule.fromScheduleArn()`, the `scheduleName` property returns `undefined` instead of the actual schedule name.

### Description of changes

Fixed the ARN parsing logic in `Schedule.fromScheduleArn()` to correctly extract the schedule name from the resource path. AWS Scheduler ARNs have the format `arn:aws:scheduler:region:account:schedule/GROUP/NAME`, and the previous implementation only captured the group name.

### Describe any new or updated permissions being added

No new or updated permissions.

### Description of how you validated changes

Added unit tests to verify correct parsing and error handling.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by mazyu36** [comment]
Exemption Request:  This change only fixes ARN parsing logic in a static import method and does not interact with AWS APIs. Unit tests fully cover the parsing logic and error handling.

File: packages/aws-cdk-lib/aws-scheduler/lib/schedule.ts [hunk 1]
```diff
@@ -255,9 +255,22 @@ export class Schedule extends Resource implements ISchedule {
    * Import an existing schedule using the ARN.
    */
   public static fromScheduleArn(scope: Construct, id: string, scheduleArn: string): ISchedule {
+    // Format: arn:aws:scheduler:region:account:schedule/SCHEDULE-GROUP/SCHEDULE-NAME
+    const arnComponents = Arn.split(scheduleArn, ArnFormat.NO_RESOURCE_NAME);
```
Comment (Abogical) [inline packages/aws-cdk-lib/aws-scheduler/lib/schedule.ts]: No reason to change the ArnFormat for splitting. We can use it to parse the resource path directly.
```suggestion
    const arnComponents = Arn.split(scheduleArn, ArnFormat.SLASH_RESOURCE_NAME);
```

**Review by Abogical — DISMISSED** [review]

**Comment by mazyu36** [comment]
@Abogical 
Sorry for the delay. Thanks for the review, I've addressed it.

**Review by Abogical — APPROVED** [review]
Thank you!
