### PR TITLE
fix(cloudwatch): `AlarmRule.concat` cover empty operands

### LINKED ISSUE #34662: (aws-cloudwatch): AlarmRule static methods can synth into an invalid template
### Describe the bug

`AlarmRule.anyOf(...alarms)` or `AlarmRule.allOf(...alarms)` where alarms is empty will result in `alarmRule: "()"` in the synth'ed CFN template which is not a valid alarm rule.

### Expected Behavior

Users should be able to `cdk synth` if Alarm Rule is invalid

### Current Behavior

`cdk synth` passes and users will only find out the alarm rule is invalid during deployment time in CloudFormation with a not so straight forward error message
```
Resource handler returned message: "Error in AlarmRule [Unsupported token ')' at char 1] (Service: AmazonCloudWatch ...)
```

### Reproduction Steps

```
const alarms: Alarm[] = [];
new CompositeAlarm(this, 'CompositeAlarm', {
  compositeAlarmName: "CompositeAlarm",
  alarmRule: AlarmRule.anyOf(...alarms),
});
```

### Possible Solution

Both `AlarmRule.anyOf(...alarms)` and `AlarmRule.allOf(...alarms)`  calls the `concat` function below

https://github.com/aws/aws-cdk/blob/dc30faa3d7506537ce4c56f291874b20d2c61334/packages/aws-cdk-lib/aws-cloudwatch/lib/alarm-rule.ts#L111-L121

We could consider having CDK throw an error if expression is undefined so users don't need to wait till deployment time to find out the alarm rule is invalid. Maybe something like
```
private static concat(operator: Operator, ...operands: IAlarmRule[]): IAlarmRule {
    return new class implements IAlarmRule {
      public renderAlarmRule(): string {
        const expression = operands
          .map(operand => `${operand.renderAlarmRule()}`)
          .join(` ${operator} `);
        if (!expression) {
            // Throw exception here
        }
        return `(${expression})`;
      }
    };
}
```

### Additional Information/Context

Originally reported in https://github.com/aws/aws-cdk/issues/14387 but was closed for staleness. It is still an issue with the latest cdk version

### AWS CDK Library version (aws-cdk-lib)

2.181.1

### AWS CDK CLI version

2.1007.0

### Node.js Version

20.18.0

### OS

Amazon Linux 2

### Language

TypeScript

### Language Version

5.8.2

### Other information

_No response_

### PR DESCRIPTION
**Pull request by phuhung273**
### Issue # (if applicable)

Closes #34662

### Reason for this change
Invalid template for empty operands

### Description of changes
Set to `FALSE` when empty operands. Alarm is in OK state

### Description of how you validated changes
Unit + Integ

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-cloudwatch/lib/alarm-rule.ts [hunk 1]
```diff
@@ -111,6 +111,10 @@ export class AlarmRule {
   private static concat(operator: Operator, ...operands: IAlarmRule[]): IAlarmRule {
     return new class implements IAlarmRule {
       public renderAlarmRule(): string {
+        if (operands.length === 0) {
```
Comment (kumvprat) [inline packages/aws-cdk-lib/aws-cloudwatch/lib/alarm-rule.ts:115]: Overall the idea looks good but I have a few questions :

- When creating empty alarms it might be better to return an empty string instead of something that cannot be interpreted.
- Will this lead to composite alarms being created but with empty details, for example will the 'FALSE' value returned keep alarm in an alarmed state ?
- Can we have a warning or a log statement so that the CDK user can track/debug as to why an alarm was created with no underlying alarm ?

All of this is assuming it does create an alarm in the user's account, if Cloudformation ignore such alarms and doesn't create any resources behind it

File: packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.composite-alarm.ts [hunk 2]
```diff
@@ -59,6 +59,14 @@ class CompositeAlarmIntegrationTest extends Stack {
       alarmRule,
       actionsSuppressor: alarm5,
     });
+
+    new CompositeAlarm(this, 'EmptyAnyOf', {
```
Comment (kumvprat) [inline packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.composite-alarm.ts]: With the empty alarm cases can we have assertions on the `CfnOutput` and/or on api calls ?
For example if these alarms only exist in template and not actually create a resource we can have an assertion that checks that these alarms are not created at all(since they are basically empty shells)

Comment (phuhung273) [reply packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.composite-alarm.ts]: Of course, I've added API assertion that composite alarm with FALSE rule must be created, and the state is OK.

File: packages/aws-cdk-lib/aws-cloudwatch/lib/alarm-rule.ts (hunk 1 above)
Comment (phuhung273) [reply packages/aws-cdk-lib/aws-cloudwatch/lib/alarm-rule.ts:115]: Thank you for taking a look at this. Here are the explanations:
- We cannot put empty string since AlarmRule is required with minimum length of 1. Ref https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-cloudwatch-compositealarm.html#cfn-cloudwatch-compositealarm-alarmrule
- FALSE value makes the alarm remains in OK state forever. We can even say its useless 😅
- I've added a `console.warn`. I'm fully aware about the `Annotations.of(construct).addWarningV2()` pattern, but we cannot do that here since there is no construct to pass in. Do you know any better way to do this than `console.warn`?

Comment (kumvprat) [reply packages/aws-cdk-lib/aws-cloudwatch/lib/alarm-rule.ts:115]: I think the main reason behind the reported issue was : 

>We could consider having CDK throw an error if expression is undefined so users don't need to wait till deployment time to find out the alarm rule is invalid. Maybe something like


The current changes would create an alarm which will not be usable or will not be useful, maybe changing the `concat` function to handle the `operands.length === 0` check and then not generating a `IAlarmRule` instance might be better choice. Again I am not aware of the full implication, so open to have a discussion around it(I assume you might know better as you have looked at the code)


**Main point being that we don't want users to have a new unused/(not useful) alarm unknowingly showing up in their AWS account**

Comment (phuhung273) [reply packages/aws-cdk-lib/aws-cloudwatch/lib/alarm-rule.ts:115]: After reconsider, i agree with that. Throwing when empty is definitely a better option. Updated.

**Comment by phuhung273** [comment]
Exemption Request: throwing error doesn't need integration

**Review by kumvprat — APPROVED** [review]

**Comment by kumvprat** [comment]
@phuhung273 Please edit the PR description to remove the line : `Set to FALSE when empty operands. Alarm is in OK state
`
