### PR TITLE
fix(pipelines): CodeBuild images have (too) old Node version

### LINKED ISSUE #9070: [@aws-cdk/pipelines] Incorrect CodeBuild image used in default synth action
When creating a CDK pipeline the default CodeBuild image in use is the old 1.0 one; 4.0 is the latest and specifying it manually allows the pipeline to build successfully. The issue is the 1.0 build image has an older version of node that is no longer supported by `ts-jest`.

### Reproduction Steps
Follow the readme for `aws-cdk/pipelines` and create a single s3 bucket in the target stack

To resolve the error, change the following on the `synthAction`:
```
environment: { buildImage: codebuild.LinuxBuildImage.STANDARD_4_0 },
```

### Error Log
During the codebuild phase right after the source stage I get the following error: 
```
error ts-jest@26.1.2: The engine "node" is incompatible with this module. Expected version ">= 10.21.0". Got "10.19.0"
```

### Environment

  - **CLI Version:** 1.51
  - **Framework Version:** 1.51
  - **Node.js Version:** v12.13.1
  - **OS               :** MacOS
  - **Language (Version):** Typescript

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by justin8**
fixes #9070

This change moves CDK pipelines from standard build image 1.0 to 4.0

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by justin8** [comment]
Is there any build output from the codebuild step? The change worked for build, unit and integration tests for me on a clean environment.

File: packages/@aws-cdk/pipelines/lib/actions/deploy-cdk-stack-action.ts [hunk 1]
```diff
@@ -1,11 +1,11 @@
+import * as path from 'path';
```
Comment (justin8) [inline packages/@aws-cdk/pipelines/lib/actions/deploy-cdk-stack-action.ts:1]: This was a part of using `--fix` to clean up linting issues. It seems it had a bad import order throwing a warning beforehand anyway.
