### PR TITLE
fix(apigateway): cross-stack lambda integration causes a cyclic reference

### LINKED ISSUE #3705: APIGateway and Lambdas in separate stacks fails
### What is the problem?

I have what I would expect a very typical scenario: APIGateway that exposes several of my lambdas. I frequently have to delete the whole stack and would like to avoid destroying the APIGateway (so as not to change the URL and apikeys). So I wanted to split them to two stacks, one for the APIGateway and one for Lambdas. I first tried with CDK 1.1.0. This caused cyclic dependency errors (which I mentioned [here](https://github.com/aws/aws-cdk/issues/1709). In hopes of it being fixed, I upgraded to 1.4.0. Now with the same setup I get:

```
cfn-reference.ts:108
      throw new Error(`Cross-stack reference (${context.scope.node.path} -> ${this.target.node.path}) has not been assigned a value--call prepare() first`);
            ^
Error: Resolution error: Resolution error: Resolution error: Cross-stack reference (ipk-PostiKioskiBackendStack-development -> ipk-PostiKioskiLambdaStack-development/ipk-ConfigLambda-development/Resource) has not been assigned a value--call prepare() first.
Object creation stack:
  at new Intrinsic (/Users/vertti/dev/posti/itsepalvelu-posti/posti-kioski-backend/node_modules/@aws-cdk/core/lib/private/intrinsic.ts:28:26)
  at new Reference (/Users/vertti/dev/posti/itsepalvelu-posti/posti-kioski-backend/node_modules/@aws-cdk/core/lib/reference.ts:21:5)
```

### Reproduction Steps

Backend defined with:
```
const app = new core.App()
const stackLambda = new PostiKioskiLambdaStack(app, `ipk-PostiKioskiLambdaStack-${environment}`)
const stackBE = new PostiKioskiBackendStack(app, `ipk-PostiKioskiBackendStack-${environment}`, { configLambda: stackLambda.configLambda })
```

where `PostiKioskiLambdaStack` creates a lambda to a public `configLambda` property which is given in the props to `stackBE`.

The lambda in question is put inside a specific vpc:

```
    this.configLambda = new awsLambda.Function(this, `ipk-ConfigLambda-${environment}`, {
      role,
      vpc,

      code: awsLambda.Code.asset('resources'),
      handler: 'config_lambda.handler',
      runtime: awsLambda.Runtime.NODEJS_10_X,
    })
```

### Verbose Log

https://gist.github.com/vertti/4883548b587774d1f1d2a75e78b640a1

### Environment

  - **CDK CLI Version:** 1.4.0 (build 175471f)
  - **OS:** OSX Mojave
  - **Language:** TypeScript

### Other information 

There's been lots of fixes done for similar cases where Lambdas are in one stack and for example SNS is in another, all of those seemed to cause cyclic dependency errors.

### PR DESCRIPTION
**Pull request by nija-at**
1. Token resolution of Deployment construct must not resolve the entire
   stack, specifically during the prepare phase.

   stack.resolve() works only after the CDK app has been fully prepared.
   During the 'prepare' phase, token resolution should instead resolve
   the token partially and within the local context.

2. Scope the lambda.CfnPermission construct closer to the consumer of
   the permission rather than being closer to the lambda function.

   For instance, when a lambda function is being consumed by an
   APIGateway RestApi Method as a cross-stack reference, placing the
   lambda.CfnPermission construct closer to the RestApi Method reduces
   the possibility of cyclic dependencies.

fixes #3705, #3000

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-apigateway/lib/deployment.ts [hunk 1]
```diff
@@ -56,14 +56,14 @@ export interface DeploymentProps  {
  * model. Use the `node.addDependency(dep)` method to circumvent that. This is done
  * automatically for the `restApi.latestDeployment` deployment.
  */
-export class Deployment extends Resource {
+export class Deployment extends cdk.Resource {
```
Comment (eladb) [inline packages/@aws-cdk/aws-apigateway/lib/deployment.ts]: Please revert. For core classes we import the class directly.

File: packages/@aws-cdk/aws-apigateway/lib/deployment.ts [hunk 2]
```diff
@@ -121,19 +121,30 @@ class LatestDeploymentResource extends CfnDeployment {
...
       const md5 = crypto.createHash('md5');
       this.hashComponents
-        .map(c => stack.resolve(c))
+        .map(c => {
+          try {
+            // TODO: Remove the code in the try block with next major version release of CDK.
+            // It's here to be backwards compatible, i.e., prevent LogicalIds to change.
+            return stack.resolve(c);
+          } catch (e) {
+            return cdk.Tokenization.resolve(c, {
```
Comment (eladb) [inline packages/@aws-cdk/aws-apigateway/lib/deployment.ts]: Please add some comments explaining why an error can occur here

File: packages/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts [hunk 3]
```diff
@@ -1,5 +1,6 @@
 import iam = require('@aws-cdk/aws-iam');
 import lambda = require('@aws-cdk/aws-lambda');
+import cdk = require('@aws-cdk/core');
```
Comment (eladb) [inline packages/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts]: Import core classes directly (`import { Construct } from '@aws-cdk/core'`). The rational is that we think of core classes, like `Construct` as "part of the programming language".

File: packages/@aws-cdk/aws-lambda/lib/function-base.ts [hunk 4]
```diff
@@ -1,14 +1,14 @@
 import cloudwatch = require('@aws-cdk/aws-cloudwatch');
 import ec2 = require('@aws-cdk/aws-ec2');
 import iam = require('@aws-cdk/aws-iam');
-import { ConstructNode, IResource, Resource } from '@aws-cdk/core';
+import cdk = require('@aws-cdk/core');
```
Comment (eladb) [inline packages/@aws-cdk/aws-lambda/lib/function-base.ts]: Revert please

File: packages/@aws-cdk/aws-lambda/lib/function-base.ts [hunk 5]
```diff
@@ -178,17 +183,20 @@ export abstract class FunctionBase extends Resource implements IFunction {
   /**
    * Adds a permission to the Lambda resource policy.
    * @param id The id ƒor the permission construct
+   * @param permission The permission to grant to this Lambda function. @see Permission for details.
+   * @param scope An optional scope to which this permission should be attached. By default, this will be the function handler.
    */
-  public addPermission(id: string, permission: Permission) {
+  public addPermission(id: string, permission: Permission, scope?: cdk.Construct) {
```
Comment (eladb) [inline packages/@aws-cdk/aws-lambda/lib/function-base.ts]: Feels like this should be added to `Permission` and not as a 3rd argument to `addPermission`

File: packages/@aws-cdk/core/lib/token.ts [hunk 6]
```diff
@@ -150,6 +151,11 @@ export interface ResolveOptions {
    * The resolver to apply to any resolvable tokens found
    */
   readonly resolver: ITokenResolver;
+
+  /**
+   * Whether the resolution is being executed during the prepare phase or not.
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/token.ts]: Add a comment explaining what is the implication of setting this to `true` and also add a "@default" value.

File: packages/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts [hunk 7]
```diff
@@ -60,14 +61,14 @@ export class LambdaIntegration extends AwsIntegration {
     this.handler.addPermission(`ApiPermission.${desc}`, {
       principal,
       sourceArn: method.methodArn,
-    });
+    }, method.node.scope as cdk.Construct);
```
Comment (eladb) [inline packages/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts]: Why not `method`? It's usually a bad practice to add constructs to scopes you don't "own". What happens if the parent scope has two methods? The namespace is not "clean"...

File: packages/@aws-cdk/aws-lambda/lib/function-base.ts (hunk 5 above)
Comment (nija-at) [reply packages/@aws-cdk/aws-lambda/lib/function-base.ts]: Is that ok?

I wasn't sure if I can push information unrelated to modeling the 'permission' itself into this structure. I chose the option similar to the constructors where the scope and id are outside of the props.
Thoughts?

File: packages/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts (hunk 7 above)
Comment (nija-at) [reply packages/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts]: All good points. Fixing up.

File: packages/@aws-cdk/aws-apigateway/lib/deployment.ts [hunk 8]
```diff
@@ -128,12 +128,34 @@ class LatestDeploymentResource extends CfnDeployment {
...
+            /*
+              stack.resolve() will error out when there is a cross stack reference to another stack. The entire stack
+              can be resolved only after completion of the 'prepare' phase. However, this method is part of the
+              preparation.
+              The correct thing to do here is to resolve the partially token within its current scope, as being done
+              in the catch block below.
+
+              Leaving the incorrect logic in the try block to not break existing CDK apps. Apps without cross-stack
+              reference for API Gateway resource would not have encountered this error; however, changing this logic
+              would change the LogicalId of the Deployment resource and indicate Cloudformation to replace the resource.
```
Comment (eladb) [inline packages/@aws-cdk/aws-apigateway/lib/deployment.ts]: Thinking about this a little further, why is replacement of the deployment resource an issue? We replace it automatically every time the API changes anyway... It shouldn't cause a service disruption.

**Comment by ashwgupt** [comment]
Can someone please share the release version carrying this fix?

We are still seeing this issue when using v 1.10.0

**Comment by nija-at** [comment]
It was released in 1.9.0. You can usually find this information in our [CHANGELOG.md](https://github.com/aws/aws-cdk/blob/master/CHANGELOG.md#190-2019-09-19).

Make sure your application is using the CDK packages >=1.9.0 and not just a later CLI version (for typescript, by checking `package-lock.json`).

If you think this is still occurring, feel free to open a new issue with repro steps.

**Comment by wywarren** [comment]
Has this been resolved for python? We're seeing similar cyclic problems with API Gateway and Lambda being separated into two stacks and passing the reference of the API gateway into the Lambda stack.
