### PR TITLE
fix(pipelines): changing synth action doesn't restart pipeline

### LINKED ISSUE #9458: [cdk-pipelines] Changing the buildspec (e.g. adding tests) does not restart the pipeline (but it should!)
See title

### PR DESCRIPTION
**Pull request by rix0rrr**
Pipeline structure looks like this:

```
┌────────┐        ┌────────┐        ┌──────────┐
│        │        │        │        │          │
│  src   │───────▶│ synth  │───────▶│selfupdate│─────▶...(deploy)...
│        │        │        │        │          │
└────────┘        └────────┘        └──────────┘
```

When changing the pipeline structure, we expect it to restart (and it
does).

However, when changing something about the "synth" action (such as
adding tests to the list of commands), we would ALSO expect the pipeline to restart.
This would ensure that if we add tests, the tests get executed and
must pass before we start the actual deployments. That is, we'd like
to run the tests on the CURRENT commit as well, but by the time
we update the buildspec to run the tests, we've already passed the stage
where the tests would be run.

This is because doing something like adding
a test didn't actually change the *Pipeline structure* (causing
a restart). Instead, it would change the buildspec of the
CodeBuild Project the pipeline was referencing, leaving the pipeline
unchanged and ready to continue deploying. The tests would
only be executed for FUTURE commits, leaving the current commit
untested.

The solution is a hash of the buildspec somewhere, but where?

We could have put it in the CodeBuild Project's logical id, so that we
would have torn down and created a new CodeBuild project to ensure that
the pipeline would restart. However, doing so would prevent giving the
CodeBuild project a deterministic display name (replacement would fail).
Plus, a simpler and cheaper solution is to put a hash of the buildspec
in the Action that references the CodeBuild project.

There is exactly one field where we can stash some user-specified
data that doesn't impact the build result: `EnvironmentVariables`.
We add an environment variable with an unlikely name, which is not
used by the build itself. Its sole purpose is to make the pipeline
definition change when the buildspec changes, causing a pipeline
restart.

Fixes #9458.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/pipelines/lib/synths/simple-synth-action.ts [hunk 1]
```diff
@@ -262,32 +263,47 @@ export class SimpleSynthAction implements codepipeline.IAction {
...
+    // to restart the pipeline if one of them changes). projectName is not necessary to include
+    // here because the pipeline will definitely restart if projectName changes.
+    const projectConfigHash = hash({
+      environment,
+      buildSpecString: buildSpec.toBuildSpec(),
+      environmentVariables,
+    });
+
+    const project = new codebuild.PipelineProject(scope, 'CdkBuildProject', {
+      projectName: this.props.projectName ?? this.props.projectName,
```
Comment (nija-at) [inline packages/@aws-cdk/pipelines/lib/synths/simple-synth-action.ts:303]: ?

File: packages/@aws-cdk/pipelines/lib/synths/simple-synth-action.ts [hunk 2]
```diff
@@ -300,6 +316,13 @@ export class SimpleSynthAction implements codepipeline.IAction {
       actionName: this.actionProperties.actionName,
       input: this.props.sourceArtifact,
       outputs: [this.props.cloudAssemblyArtifact, ...(this.props.additionalArtifacts ?? []).map(a => a.artifact)],
+
+      // Inclusion of the hash here will lead to the pipeline structure changing if the
+      // buildspec changes, and hence the pipeline being restarted. This is necessary if
+      // the users adds (for example) build or test commands to the buildspec.
```
Comment (nija-at) [inline packages/@aws-cdk/pipelines/lib/synths/simple-synth-action.ts:322]: Not just the buildspec but anything around the CodeBuild project.

```suggestion
      // Inclusion of the hash here will lead to the pipeline structure changing for any
      // changes to the underlying CodeBuild project, and hence the pipeline being restarted.
      // This is necessary if the users adds (for example) build or test commands to the buildspec.
```

File: packages/@aws-cdk/pipelines/test/builds.test.ts [hunk 3]
```diff
@@ -219,6 +220,75 @@ test('Standard (NPM) synth can output additional artifacts', () => {
...
+  }));
+  const hash4 = synthWithAction((sa, cxa) => cdkp.SimpleSynthAction.standardNpmSynth({
+    sourceArtifact: sa,
+    cloudAssemblyArtifact: cxa,
+    environmentVariables: {
+      xyz: { value: 'SOME-VALUE' },
+    },
+  }));
+
+  expect(hash1).not.toEqual(hash2);
```
Comment (njlynch) [inline packages/@aws-cdk/pipelines/test/builds.test.ts:248]: `~` I wonder if it's worth having two hashes be equal as well (e.g., hash2 calculated from the exact same parameters of hash3). As-is, this test would pass if the hash was random data each time.

**Review by njlynch — APPROVED** [review]

File: packages/@aws-cdk/assert/lib/assertions/have-resource-matchers.ts [hunk 4]
```diff
@@ -281,6 +281,90 @@ export function notMatching(matcher: any): PropertyMatcher {
   });
 }
 
+export type TypeValidator<T> = (x: any) => x is T;
```
Comment (nija-at) [inline packages/@aws-cdk/assert/lib/assertions/have-resource-matchers.ts:284]: Add corresponding entries in the README for these new features

File: packages/@aws-cdk/assert/lib/assertions/have-resource-matchers.ts [hunk 5]
```diff
@@ -281,6 +281,90 @@ export function notMatching(matcher: any): PropertyMatcher {
...
+ * @example
+ *
+ * const someValue = Capture.aString();
+ * expect(stack).toHaveResource({
+ *    // ...
+ *    Value: someValue.capture(stringMatching('*a*')),
+ * });
+ * console.log(someValue.capturedValue);
+ */
+export class Capture<T=any> {
```
Comment (nija-at) [inline packages/@aws-cdk/assert/lib/assertions/have-resource-matchers.ts:298]: *sigh* one more thing to consider when rewriting this module as a JSII-able module. 

I would've asked - why not just

```ts
const notThisHash = ...;

expect(stack).not.toHaveResourceLike('AWS::CodeBuild::Project', {
  ...
  Value: notThisHash
});
```

But looking at the usage and the deep nesting, I understand why you had to do this.

**Review by nija-at — DISMISSED** [review]

File: packages/@aws-cdk/assert/lib/assertions/have-resource-matchers.ts (hunk 5 above)
Comment (rix0rrr) [reply packages/@aws-cdk/assert/lib/assertions/have-resource-matchers.ts:298]: The functionality is legit and should be ported, I feel.

The jsii-able version of this might drop the type assertions but I didn't see any point in having this wobbly-typed since this module is long past jsii-ability anyway.

Comment (nija-at) [reply packages/@aws-cdk/assert/lib/assertions/have-resource-matchers.ts:298]: Fine by me.

We'll definitely consider for this to be ported. Just wanted to make note that the form might have to change.
