### PR TITLE
fix(eks): pass `--use-max-pods` to bootstrap options when false

### LINKED ISSUE #4752: EKS --use-max-pods=false not working
In [bootstrap.sh](https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh), option `--use-max-pods` can be `true` or `false` and default to `true`.

However, in CDK `--use-max-pods` option would be appended to `extraArgs` only if it's `true` and omitted when `false`. As a result, if I want to disable this behavior and pass `false` as `bootstrapOptions`, it would generate `LaunchConfiguration` with no `--use-max-pods` option and thus default to `true` in `bootstrap.sh` script. Which is not intended.

### Reproduction Steps

Set `useMaxPods` to `false` in `bootstrapOptions` when pass options in `AutoScalingGroup`.

### Error Log

No logs. Generated CF templates are not included desired option.

### Environment

  - **CLI Version**: 1.13.1
  - **Framework Version**: 1.13.1
  - **OS**: MacOS
  - **Language**: TypeScript

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by progamesigner**
The EKS `useMaxPods` in `bootstrapOptions` is dropped `--use-max-pods` when set
to `false` but in `bootstrap.sh` it would default to `true` and cause unexpected
stacks.

Fixes #4752

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-eks/lib/user-data.ts [hunk 1]
```diff
@@ -12,8 +12,10 @@ export function renderUserData(clusterName: string, autoScalingGroup: autoscalin
 
   const extraArgs = new Array<string>();
 
-  if (options.useMaxPods) {
-    extraArgs.push('--use-max-pods');
+  if (options.useMaxPods === true) {
+    extraArgs.push(`--use-max-pods`);
+  } else if (options.useMaxPods === false) {
+    extraArgs.push(`--use-max-pods ${options.useMaxPods}`);
```
Comment (eladb) [inline packages/@aws-cdk/aws-eks/lib/user-data.ts]: Can we simply always pass this parameter and reduce complexity?

Comment (progamesigner) [reply packages/@aws-cdk/aws-eks/lib/user-data.ts]: Yes, I think we could, but there are some concerns about that.

`useMaxPods` has 3 cases:
 - `true`: same behavior as before
 - `false`: fixed behavior which passing `--use-max-pods false` option
 - `undefined`: default value and I assume that would generate no `--use-max-pods` option

Because all tests assume `undefined` value (which imply `true` of course) and assert no `--use-max-pods` option, I am not intended to make such big change (need discussion) at that time.

If we default to `true` (same as bootstrap.sh), all tests require adding `--use-max-pods` to them and all generated templates would include `--use-max-pods`; if we default to `false`, still we have to add `--use-max-pods false` to all tests and `false` is also a bad default which conflict with bootstrap.sh option.

It's a potential breaking changes, so I would prefer preserving behavior. However, we can discuss and still make such change.

Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/user-data.ts]: I think we should just make `true` the default, always render `--use-max-pods true` and update all test expectations.

Comment (progamesigner) [reply packages/@aws-cdk/aws-eks/lib/user-data.ts]: Ok, I will update them later.
