### PR TITLE
fix(cli): add validation of --notification-arns structure

### LINKED ISSUE #20806: (cli): `--notification-arns` not validated
### Describe the bug

When deploying using the `--notification-arns` argument, it's possible to pass in an invalid arn as an SNS topic arn, causing a change set to be uploaded with an invalid arn. If possible, the cli should at least validate the structure of the notification arn's being passed in.

Creating a change set with an invalid SNS arn seems to put the stack into a bad state, as the change seemingly cannot be deleted. So far I've found the only remedy is to delete the stack

### Expected Behavior

Expected the cli to throw when receiving invalid notification arns. 

### Current Behavior

The deploy still uploads a change set with an invalid SNS topic arn.

### Reproduction Steps

This can be reproduced easily with any type of stack. 

1) Deploy stack without using `--notification-arns` `cdk deploy --require-approval never --all`
2) Make a change to the stack and deploy using an invalid notification arn such as `arn:aws:sns:us-east-1::some-sns-topic` `cdk deploy --require-approval never --all --notification-arns arn:aws:sns:us-east-1::some-sns-topic`
3) The deploy will fail with a validation error.
```
 ❌  dev001-ct-s3-test-s3 failed: Error [ValidationError]: Invalid parameter: AccountId (Service: AmazonSNS; Status Code: 400; Error Code: InvalidParameter; Request ID: 8089a9f5-8661-5487-b5db-f2df5a335207; Proxy: null)
    at Request.extractError (/Users/christopher.taormina/src/intern-cdk/cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/christopher.taormina/src/intern-cdk/cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/christopher.taormina/src/intern-cdk/cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/christopher.taormina/src/intern-cdk/cdk/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/Users/christopher.taormina/src/intern-cdk/cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/christopher.taormina/src/intern-cdk/cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/christopher.taormina/src/intern-cdk/cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/christopher.taormina/src/intern-cdk/cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/christopher.taormina/src/intern-cdk/cdk/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/Users/christopher.taormina/src/intern-cdk/cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2022-06-20T20:35:30.070Z,
  requestId: 'a5b58918-f6cd-4b36-a9fe-a89aa2f915f7',
  statusCode: 400,
  retryable: false,
  retryDelay: 772.0194690899034
}
```
4) Try to delete the change set by cli, met with the error `An error occurred (InvalidChangeSetStatus) when calling the DeleteChangeSet operation: An operation on this ChangeSet is currently in progress.  Please attempt this operation again later.`
5) Try to deploy the stack with a valid SNS topic. This is met with the following error 
```
 ❌  dev001-ct-s3-test-s3 failed: InvalidChangeSetStatus: An operation on this ChangeSet is currently in progress.  Please attempt this operation again later.
    at Request.extractError (/Users/christopher.taormina/src/intern-cdk/cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/christopher.taormina/src/intern-cdk/cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/christopher.taormina/src/intern-cdk/cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/christopher.taormina/src/intern-cdk/cdk/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/Users/christopher.taormina/src/intern-cdk/cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/christopher.taormina/src/intern-cdk/cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/christopher.taormina/src/intern-cdk/cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/christopher.taormina/src/intern-cdk/cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/christopher.taormina/src/intern-cdk/cdk/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/Users/christopher.taormina/src/intern-cdk/cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'InvalidChangeSetStatus',
  time: 2022-06-20T20:39:18.375Z,
  requestId: '83a73e9a-77fc-456c-87ee-ac8a5416946f',
  statusCode: 400,
  retryable: false,
  retryDelay: 92.08934678630065
}
```

### Possible Solution

The nicest thing to have is making a check to see if the SNS topic in fact exists. However even the simplest check for a valid SNS arn structure could prevent this from occurring.

### Additional Information/Context

_No response_

### CDK CLI Version

2.27.0

### Framework Version

_No response_

### Node.js Version

14.19.1

### OS

Macos Monterey

### Language

Typescript

### Language Version

Typescrit 4.5.5

### Other information

_No response_

### PR DESCRIPTION
**Pull request by TrygviZL**
When deploying using the `--notification-arns` argument, it's possible to pass in an invalid arn as an SNS topic arn, causing a change set to be uploaded with an invalid arn. This PR adds a check for the structure of the input ARN.

I was originally looking into possibly adding the check earlier in the process such as adding a .check() method to the yargs option in [packages/aws-cdk/lib/cli.ts](https://github.com/aws/aws-cdk/blob/f66f94e9201b9c9d5e0f1b713a6f30194b323b28/packages/aws-cdk/lib/cli.ts). But as I see it there are no tests for these, so it was difficult to validate the change.

closes #20806 

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk/lib/cdk-toolkit.ts [hunk 1]
```diff
@@ -127,6 +128,14 @@ export class CdkToolkit {
       return this.watch(options);
     }
 
+    if (options.notificationArns) {
+      options.notificationArns.map( arn => {
+        if (!validateSnsTopicArn(arn)) {
```
Comment (otaviomacedo) [inline packages/aws-cdk/lib/cdk-toolkit.ts:133]:
```suggestion
        if (!Token.unresolved(arn) && !validateSnsTopicArn(arn)) {
```

Also please add a test for this condition.

**Review by otaviomacedo — DISMISSED** [review]

File: packages/aws-cdk/lib/cdk-toolkit.ts (hunk 1 above)
Comment (TrygviZL) [reply packages/aws-cdk/lib/cdk-toolkit.ts:133]: @otaviomacedo I have looked into it and can indeed add the !Token.isUnresolved(arn) condition to the check of notification arn. However, as this check happens prior to stack synthesis, it seems redundant to check if the token has been resolved. 
Let me know if I am misunderstanding :)

Comment (otaviomacedo) [reply packages/aws-cdk/lib/cdk-toolkit.ts:133]: `arn` may be a "normal" string (in which case it makes sense to validate it) or it may a token, which is a special kind of string, that is a stand-in for something else (in which case it doesn't make sense to validate it because it will always fail). In the second case, `Token isUnresolved()` returns true.

Comment (TrygviZL) [reply packages/aws-cdk/lib/cdk-toolkit.ts:133]: @otaviomacedo thanks for the reply! I do get that tokens can be passed around and are converted to strings during synthesis to CloudFormation templates.
What I am thinking is that the Arn in this specific case is passed as a parameter when using the CLI. for example:
`cdk deploy --all --notification-arns arn:aws:sns:us-east-1::some-sns-topic`
in which case the arn will never be a token as these only exist in a stack prior to synthesis.

Again, I might be wrong, but is there a case where the arn is passed to the CLI command as a token?

Comment (TrygviZL) [reply packages/aws-cdk/lib/cdk-toolkit.ts:133]: @otaviomacedo Readng around I found #8581 which does ask to implement a way to add the notification arn to the stack prior to synthesis. The issue has been open for a while, but would require the Token.isUnresolved() in the check.

What do you think? should we add it just in case?

**Review by otaviomacedo — APPROVED** [review]
