### PR TITLE
fix(s3): updating blockPublicAccess to enable default true settings (under feature flag)

### LINKED ISSUE #32811: aws-s3: `blockPublicAccess` has a counterintuitive behaviour
### Describe the bug

When a bucket is created without specifying the `blockPublicAccess` property:

```ts
const myBucket = new Bucket(this, "MyBucket");
```

It is equivalent to explicitly setting all `BlockPublicAccess` options to `true`:

```ts
const myBucket = new Bucket(this, "MyBucket", {
  blockPublicAccess: new BlockPublicAccess({
    blockPublicAcls: true,
    ignorePublicAcls: true,
    blockPublicPolicy: true,
    restrictPublicBuckets: true,
  }),
});
```

This might lead you to assume that all `BlockPublicAccess` options default to `true`. However, that's not the case. For example, if you deploy a bucket like this:

```ts
const myBucket = new Bucket(this, "MyBucket", {
  blockPublicAccess: new BlockPublicAccess({
    blockPublicPolicy: false,
    restrictPublicBuckets: false,
  }),
});
```

You would get this configuration:

image

This happens because all options within `BlockPublicAccess` are `undefined` by default, which is equivalent to `false`.

This behavior is counterintuitive. If you do not define `blockPublicAccess`, all options default to `true`. However, if you define a `BlockPublicAccess`, any unspecified options default to `false`.

This seemingly paradoxical situation stems from a [change](https://aws.amazon.com/about-aws/whats-new/2023/04/amazon-s3-security-best-practices-buckets-default/) introduced a couple of years ago.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

see above.

### Current Behavior

see above.

### Reproduction Steps

see above.

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.174.1

### Framework Version

_No response_

### Node.js Version

22.12.0

### OS

Ubuntu 24.04.1

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by IkeNefcy**
V3 but I think we got there

### Issue #

Closes #32811

### Reason for this change

By default when you create an s3 bucket, all public access is already blocked. However if you then use CDK to specify 1 or more access point you want to unblock, all undefined block types will be auto set to false, and when it deploys you will see everything uncheck even if you only wanted to uncheck 1 thing.

So to fix this we should instead default all values to true when at least 1 option is specified, to mimic to experience when a user in the console unchecks the boxes.

### Description of changes

deprecating `BLOCK_ACLS` method of `BlockPublicAccess`. Adding `BLOCK_ACLS_ONLY`. 
```
  public static readonly BLOCK_ACLS_ONLY = new BlockPublicAccess({
    blockPublicAcls: true,
    blockPublicPolicy: false,
    ignorePublicAcls: true,
    restrictPublicBuckets: false,
  });
```
This is just a general revamp to match what the feature will bring, it's separate from the feature itself. The point being that for any shortcut methods like this, we should be specifying all 4 options to ensure the default true behavior remains.

Created function `setBlockPublicAccessDefaults()`

```
  /**
   * Function to set the blockPublicAccessOptions to a true default if not defined.
   * If no blockPublicAccessOptions are specified at all, this is already the case as an s3 default in aws
   * @see https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html
   */
  private setBlockPublicAccessDefaults(blockPublicAccessOptions: BlockPublicAccessOptions) {
    return {
      blockPublicAcls: blockPublicAccessOptions.blockPublicAcls ?? true,
      blockPublicPolicy: blockPublicAccessOptions.blockPublicPolicy ?? true,
      ignorePublicAcls: blockPublicAccessOptions.ignorePublicAcls ?? true,
      restrictPublicBuckets: blockPublicAccessOptions.restrictPublicBuckets ?? true,
    };
  }
```

but this method is only called if the FF is enabled

```
    let blockPublicAccess: BlockPublicAccessOptions | undefined = props.blockPublicAccess;
    if (props.blockPublicAccess && FeatureFlags.of(this).isEnabled(cxapi.S3_BLOCK_PUBLIC_ACCESS_OPTION_AUTO_TRUE)) {
      blockPublicAccess = this.setBlockPublicAccessDefaults(props.blockPublicAccess);
    }
```

Of course the FF itself was added.

### Description of how you validated changes

Added tests that are duplicates of others, just testing for both behaviors with and without the FF.

```
  describe('bucket with custom block public access setting', () => {
    ...
    test('S3_BLOCK_PUBLIC_ACCESS_OPTION_AUTO_TRUE Enabled', () => {
      const app = new cdk.App({
        context: {
          [cxapi.S3_BLOCK_PUBLIC_ACCESS_OPTION_AUTO_TRUE]: true,
        },
      });
      const stack = new cdk.Stack(app);
      new s3.Bucket(stack, 'MyBucket', {
        blockPublicAccess: new s3.BlockPublicAccess({ restrictPublicBuckets: false }),
      });

      Template.fromStack(stack).templateMatches({
        'Resources': {
          'MyBucketF68F3FF0': {
            'Type': 'AWS::S3::Bucket',
            'Properties': {
              'PublicAccessBlockConfiguration': {
                'BlockPublicAcls': true,
                'BlockPublicPolicy': true,
                'IgnorePublicAcls': true,
                'RestrictPublicBuckets': false,
              },
            },
            'DeletionPolicy': 'Retain',
            'UpdateReplacePolicy': 'Retain',
          },
        },
      });
    });
```

```
  describe('bucket with custom block public access setting', () => {
    ...
    test('S3_BLOCK_PUBLIC_ACCESS_OPTION_AUTO_TRUE Enabled', () => {
      const app = new cdk.App({
        context: {
          [cxapi.S3_BLOCK_PUBLIC_ACCESS_OPTION_AUTO_TRUE]: true,
        },
      });
      const stack = new cdk.Stack(app);
      new s3.Bucket(stack, 'MyBucket', {
        blockPublicAccess: new s3.BlockPublicAccess({ restrictPublicBuckets: false }),
      });

      Template.fromStack(stack).templateMatches({
        'Resources': {
          'MyBucketF68F3FF0': {
            'Type': 'AWS::S3::Bucket',
            'Properties': {
              'PublicAccessBlockConfiguration': {
                'BlockPublicAcls': true,
                'BlockPublicPolicy': true,
                'IgnorePublicAcls': true,
                'RestrictPublicBuckets': false,
              },
            },
            'DeletionPolicy': 'Retain',
            'UpdateReplacePolicy': 'Retain',
          },
        },
      });
    });
```

Also added an integ that just tests different combinations of the blocking. 
https://github.com/aws/aws-cdk/blob/51ffe2112e048f5866e5c0d811377b4deca7920d/packages/%40aws-cdk-testing/framework-integ/test/aws-s3/test/integ.bucket-block-access.ts#L1-L42
There was no `BlockPublicAccess` integ before so I did not add the context for the FF disabled anywhere. The tests should still be working since it's not used that often. But if the team needs me to, I can add a 2nd integ with the old behavior

### Checklist
- [X] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by IkeNefcy** [comment]
Another ff was added without a readme..

**Comment by IkeNefcy** [comment]
please wait for https://github.com/aws/aws-cdk/pull/33867 so I can resolve conflict

**Comment by IkeNefcy** [comment]
wake me up when I need to resolve conflicts and this is actually assigned

**Comment by IkeNefcy** [comment]
error Error: https://registry.npmjs.org/@types/mime-types/-/mime-types-2.1.4.tgz: Request failed "500 Internal Server Error"

hmm

File: packages/aws-cdk-lib/aws-s3/lib/bucket.ts [hunk 1]
```diff
@@ -2205,6 +2223,11 @@ export class Bucket extends BucketBase {
 
     Bucket.validateBucketName(this.physicalName);
 
+    let blockPublicAccess: BlockPublicAccessOptions | undefined = props.blockPublicAccess;
```
Comment (QuantumNeuralCoder) [inline packages/aws-cdk-lib/aws-s3/lib/bucket.ts:2226]: the name is a bit misleading as it sounds like we are blocking public access - `blockPublicAccess`. This is just a  `publicAccessBlockConfig`. We are ensuring that the default configuration blocks it which you have implemented in setBlockPublicAccessDefaults. Again that methodname could be setDefaultPublicAccessBlockConfig or setPublicAccessBlockConfigDefault

File: packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md [hunk 2]
```diff
@@ -99,6 +99,7 @@ Flags come in three types:
 | [@aws-cdk/pipelines:reduceCrossAccountActionRoleTrustScope](#aws-cdkpipelinesreducecrossaccountactionroletrustscope) | When enabled, scopes down the trust policy for the cross-account action role | 2.189.0 | new default |
 | [@aws-cdk/core:aspectPrioritiesMutating](#aws-cdkcoreaspectprioritiesmutating) | When set to true, Aspects added by the construct library on your behalf will be given a priority of MUTATING. | 2.189.1 | new default |
 | [@aws-cdk/s3-notifications:addS3TrustKeyPolicyForSnsSubscriptions](#aws-cdks3-notificationsadds3trustkeypolicyforsnssubscriptions) | Add an S3 trust policy to a KMS key resource policy for SNS subscriptions. | V2NEXT | (fix) |
+| [@aws-cdk/aws-s3:blockPublicAccessOptionAutoTrue](#aws-cdkaws-s3blockpublicaccessoptionautotrue) | When enabled, setting any combination of options for BlockPublicAccess will automatically set true for any options not defined. | V2NEXT | (fix) |
```
Comment (QuantumNeuralCoder) [inline packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md:102]: Same note. Maybe the better name is `s3publicAccessBlockedByDefault`

File: packages/aws-cdk-lib/aws-s3/test/bucket.test.ts [hunk 3]
```diff
@@ -900,28 +901,62 @@ describe('bucket', () => {
...
+  describe('bucket with custom block public access setting', () => {
+    test('S3_BLOCK_PUBLIC_ACCESS_OPTION_AUTO_TRUE Disabled', () => {
+      const app = new cdk.App({
+        context: {
+          [cxapi.S3_BLOCK_PUBLIC_ACCESS_OPTION_AUTO_TRUE]: false,
+        },
+      });
+      const stack = new cdk.Stack(app);
+      new s3.Bucket(stack, 'MyBucket', {
+        blockPublicAccess: new s3.BlockPublicAccess({ restrictPublicBuckets: true }),
```
Comment (QuantumNeuralCoder) [inline packages/aws-cdk-lib/aws-s3/test/bucket.test.ts:913]: Can we have test cases with `feature flag = false` as well

**Review by QuantumNeuralCoder — DISMISSED** [review]

File: packages/aws-cdk-lib/aws-s3/lib/bucket.ts (hunk 1 above)
Comment (IkeNefcy) [reply packages/aws-cdk-lib/aws-s3/lib/bucket.ts:2226]: swapping to `setDefaultPublicAccessBlockConfig` and `publicAccessBlockConfig`

File: packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md (hunk 2 above)
Comment (IkeNefcy) [reply packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md:102]: swapping

File: packages/aws-cdk-lib/aws-s3/test/bucket.test.ts (hunk 3 above)
Comment (IkeNefcy) [reply packages/aws-cdk-lib/aws-s3/test/bucket.test.ts:913]: checking

Comment (IkeNefcy) [reply packages/aws-cdk-lib/aws-s3/test/bucket.test.ts:913]: this is the false test I believe 
`[cxapi.S3_BLOCK_PUBLIC_ACCESS_OPTION_AUTO_TRUE]: false,`
I just bundled the old test in a describe with the ff, so this 
`describe('bucket with custom block public access setting', () =>`
has both an enabled and disabled. 
I will be renaming the flag with the other change but unsure if there is a specific line you mean?

Comment (IkeNefcy) [reply packages/aws-cdk-lib/aws-s3/test/bucket.test.ts:913]: So the hierarchy is like 
```
describe('bucket with custom block public access setting', () => {
  test('S3_PUBLIC_ACCESS_BLOCKED_BY_DEFAULT Disabled', () => {}
  test('S3_PUBLIC_ACCESS_BLOCKED_BY_DEFAULT Enabled', () => {}
}

describe('bucket with custom block public access setting', () => {
  test('S3_PUBLIC_ACCESS_BLOCKED_BY_DEFAULT Disabled', () => {}
  test('S3_PUBLIC_ACCESS_BLOCKED_BY_DEFAULT Enabled', () => {}
}
```

**Review by QuantumNeuralCoder — APPROVED** [review]
lgtm

**Comment by IkeNefcy** [comment]
```
    Mergify doesn't have permission to update

    For security reasons, Mergify can't update this pull request. Try updating locally.
    GitHub response: refusing to allow a GitHub App to create or update workflow .github/workflows/pr-linter-exemption-labeler.yml without workflows permission
```

hmm there's a new one

**Comment by QuantumNeuralCoder** [comment]
Please hold of making any changes. We are looking into this

**Review by samson-keung — APPROVED** [review]
Approving on @QuantumNeuralCoder's behalf as the auto-merge should work now.

**Comment by samson-keung** [comment]
@IkeNefcy can you fix the merge conflicts? Thank you!

**Comment by IkeNefcy** [comment]
Will do in a few

**Review by samson-keung — APPROVED** [review]
Approving again as merge conflict is addressed
