### PR TITLE
fix(pipelines): self-update build fails with named pipeline stack

### LINKED ISSUE #10782: [pipelines] self-update build fails with named pipeline stack
When naming the pipeline stack using the `stackName` property with a different name than the `id`, the self-update build fails with an error that it cannot find the stack.

### Reproduction Steps

Create a pipeline project and give the pipeline stack a custom name.
```typescript
import * as cdk from '@aws-cdk/core';
import { PipelineStack } from '../lib/pipeline-stack';

const app = new cdk.App();

new PipelineStack(app, 'PipelineStack', {
    stackName: 'Pipeline'
});

app.synth();
```
Then deploy the project and have a look at the pipeline execution.

### What did you expect to happen?

I expected the pipeline stack to be named 'Pipeline'. This happened successfully on the first deploy from my local command line. Then I expected the pipeline build to execute successfully and update the pipeline, however this step failed. It works fine, when I don't supply a `stackName`.

### What actually happened?

The update build failed with the error message that it could not find the stack 'Pipeline'. 

```
95	No stack found matching 'Pipeline'. Use "list" to print manifest
96	Error: No stack found matching 'Pipeline'. Use "list" to print manifest
97	    at CloudAssembly.selectStacks (/usr/local/lib/node_modules/aws-cdk/lib/api/cxapp/cloud-assembly.ts:115:15)
98	    at CdkToolkit.selectStacksForDeploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:381:35)
99	    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:111:20)
100	    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:197:9)
```

### Environment

  - **CLI Version      : 1.66.0**
  - **Framework Version: 1.66.0**
  - **Node.js Version: v14.11.0** 
  - **OS               :  Linux x86_64**
  - **Language (Version): Typescript** 

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by otaviomacedo**
Fixes #10782

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by rix0rrr — CHANGES_REQUESTED** [review]
As discussed, probably better to update the pipelines library to generate the correct command...

File: packages/@aws-cdk/pipelines/lib/pipeline.ts [hunk 1]
```diff
@@ -197,7 +197,7 @@ export class CdkPipeline extends CoreConstruct {
         stageName: 'UpdatePipeline',
         actions: [new UpdatePipelineAction(this, 'UpdatePipeline', {
           cloudAssemblyInput: this._cloudAssemblyArtifact,
-          pipelineStackName: pipelineStack.stackName,
+          pipelineStackName: pipelineStack.node.path,
```
Comment (rix0rrr) [inline packages/@aws-cdk/pipelines/lib/pipeline.ts:200]: Property name is now wrong.

Can you `@deprecate` this one, and a new one with the correct name?

**Review by rix0rrr — APPROVED** [review]
