### PR TITLE
fix(secretsmanager): secretName for owned secrets includes suffix (under feature flag)

### LINKED ISSUE #11727: (secretsmanager): secret_name returns the end of the ARN with 6 character suffix
Reopen the issue https://github.com/aws/aws-cdk/issues/11573

Need to create an external secret in EKS, which is retrieved from secrets manager. Currently, CDK returns a secret name with secrets manager's 6 character suffix.  Hopefully it can be fixed. Or a workaround would be appreciated.

It caused the error: `{"level":50,"time":1606359303455,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-5648bf6544-p87vp","message":"Secrets Manager can't find the specified secret.","code":"ResourceNotFoundException"`

### Reproduction Steps
1. create a random secret in secrets manager:
`
my_secret = Secret(self, 'xx', 
                    generate_secret_string=SecretStringGenerator(secret_string_template=json.dumps({'username': 'tester'}), generate_string_key="password")
 )
`
2.  create an external secret resource in EKS while replacing the place holder in the yaml file:
```
eks.KubernetesManifest(self,'xx',
            cluster=my_cluster,
            manifest=loadYamlReplaceVarLocal('ex-secret.yaml', 
                fields= {
                    "{{secret_name}}": my_secret.secret_name
                })
        )
```
The content of ex-secret.yaml:
```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jupyter-external-secret
  namespace: jupyter
spec:
  backendType: secretsManager
  data:
    - key: {{secret_name}}
      name: password
      property: password          
```

### What did you expect to happen?
I want to get the correct secret name that matches the name in secrets manager console.

### What actually happened?

in CDK, `my_secret.secret_name` returns the end of full ARN with 6 character suffix, ie.`jHubSecretArn6E48ECC3-0YhYd3BbaFH5-qeNyUO`. The external secret object in EKS is actually expecting `jHubSecretArn6E48ECC3-0YhYd3BbaFH5`

### Environment

  - **CDK CLI Version  :** 1.74.0 (build e86602f)
  - **Framework Version:** 1.74.0
  - **Node.js Version:** v12.16.2
  - **OS               :** macOS Catalina 10.15.7
  - **Language (Version) :** Python 3.8.5

### Other

in CFN, it looks like this. can we further split it by '-', then take the first & second parts to construct the secret name?
"Value": {
        "Fn::Select": [6,{"Fn::Split": [":",{ "Ref": "jHubSecretArn6E48ECC3" }]}]
      }

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by njlynch**
Proper (tokenized) secret names for owned secrets was introduced in #11202. This
caused `Secret.secretName` to return the full resource name (secret name + suffix)
for owned secrets. This was done to ensure that the secretName was a Tokenized
value that would create a dependency between the Secret and its consumer.

However, Secrets Manager's DescribeSecret API does not accept the resourceName
as an input; it accepts the full ARN, a partial ARN (without the suffix), or the
secret name (without the suffix). This leads to several integrations with other
services or custom scripts to fail when using the secretName from an owned
Secret.

For owned secrets, we can parse the resourceName to get the secretName based on
either (a) knowing the secret name or (b) knowing the format that CloudFormation
uses when secret names aren't specified. This fix introduces proper parsing of
secret names for owned secrets (behind a feature flag).

BREAKING CHANGE: (feature flag) Secret.secretName for owned secrets will now
only the secret name (without suffix) and not the full resource name. This is
enabled through the `@aws-cdk/secretsmanager:parseOwnedSecretName` flag.

fixes #11727

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-secretsmanager/lib/secret.ts [hunk 1]
```diff
@@ -707,6 +711,39 @@ function parseSecretName(construct: IConstruct, secretArn: string) {
   throw new Error('invalid ARN format; no secret name provided');
 }
 
+/**
+ * Parses the secret name from the ARN of an owned secret. With owned secrets we know that a few things we don't with imported secrets:
```
Comment (eladb) [inline packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:715]:
```suggestion
 * Parses the secret name from the ARN of an owned secret. With owned secrets we know a few things we don't with imported secrets:
```

File: packages/@aws-cdk/aws-secretsmanager/lib/secret.ts [hunk 2]
```diff
@@ -707,6 +711,39 @@ function parseSecretName(construct: IConstruct, secretArn: string) {
...
+ * - The ARN is guaranteed to be a full ARN, with suffix.
+ * - The name -- if provided -- will tell us how many hyphens to expect in the final secret name.
+ * - If the name is not provided, we know the format used by CloudFormation for auto-generated names.
+ *
+ * Note: This is done rather than just returning the secret name passed in by the user to keep the relationship
```
Comment (eladb) [inline packages/@aws-cdk/aws-secretsmanager/lib/secret.ts:720]: Btw, I was just discussing with @iliapolo the idea of introducing a feature in core of tokens that encode a dependency. Similarly to how cross stack references work, The framework will identify these tokens, resolve them to their concrete value and automatically add a dependency between the two resources.

This way, we won't have to be limited to use CfN intrinsic to enforce the dependency

File: packages/@aws-cdk/aws-secretsmanager/test/integ.secret-name-parsed.ts [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+    const serviceToken = cdk.CustomResourceProvider.getOrCreate(this, resourceType, {
+      codeDirectory: path.join(__dirname, 'integ.secret-name-parsed.handler'),
+      runtime: cdk.CustomResourceProviderRuntime.NODEJS_12,
+      policyStatements: [{
+        Effect: 'Allow',
+        Resource: secrets.map(s => s.secretArn),
+        Action: ['secretsmanager:DescribeSecret'],
+      }],
+    });
+    new cdk.CustomResource(this, 'SecretNameVerification', {
```
Comment (eladb) [inline packages/@aws-cdk/aws-secretsmanager/test/integ.secret-name-parsed.ts:31]: I love this. actually intend to do a twitch session to build a general purpose "hooks" feature that can be used for exactly this purpose.

File: packages/@aws-cdk/cx-api/lib/features.ts [hunk 4]
```diff
@@ -56,6 +56,15 @@ export const STACK_RELATIVE_EXPORTS_CONTEXT = '@aws-cdk/core:stackRelativeExport
...
 export const DOCKER_IGNORE_SUPPORT = '@aws-cdk/aws-ecr-assets:dockerIgnoreSupport';
 
+/**
+ * Secret.secretName for an "owned" secret will attempt to parse the secretName from the ARN,
+ * rather than the default full resource name, which includes the SecretsManager suffix.
+ *
+ * If this flag is not set, Secret.secretName will include the SecretsManager suffix, which cannot be directly
+ * used by SecretsManager.DescribeSecret, and must be parsed by the user first (e.g., Fn:Join, Fn:Select, Fn:Split).
+ */
+export const SECRETS_MANAGER_PARSE_OWNED_SECRET_NAME = '@aws-cdk/aws-secretsmanager:parseOwnedSecretName';
```
Comment (eladb) [inline packages/@aws-cdk/cx-api/lib/features.ts:66]: Come to think about this a bit more this might be a bit tricky to introduce under a global feature flag. 

Consider an app that enables this feature which uses a library that was developed with this feature disabled. Now the library will effectively get a different behavior then it originally was tested with.

I recon it's unlikely to happen, especially given 2.0 is not too far out and we'll clean this up... but thought I'd bring it up.

**Review by eladb — APPROVED** [review]

File: packages/@aws-cdk/cx-api/lib/features.ts (hunk 4 above)
Comment (njlynch) [reply packages/@aws-cdk/cx-api/lib/features.ts:66]: It's a valid point. That being said, I think there are four mitigations.
1. As you said, 2.0 is not far out.
2. This functionality (owned secret names) has only been out for three releases, limiting the timeframe for someone to have built a library based on this.
3. The existing functionality really is only marginally useful; any use case I'm aware of would likely need to be manually using Split/Select to make use of the name, so I think more users are avoiding it rather than embracing it (for owned secrets).

That being said, one thing I *can* do is add something to the README or secretName docs to advertise this feature flag so a user is less likely to get the wrong behaviour.

**Review by eladb — APPROVED** [review]
