### PR TITLE
fix(apigateway): error defining lambda integration on imported RestApi

### LINKED ISSUE #8679: Defining Resources on imported RestApi Error on LambdaIntegration
When we try to use the imported RestApi Gateway to define resources across stacks, it is not allowing to add new LambdaIntegration on the imported Gateway. However it work with MockIntegration as expected. 
The following error is thrown on synth or deployment:
`RestApi is not available on Resource not connected to an instance of RestApi. Use `api` instead`

This works:
```
 const api = RestApi.fromRestApiAttributes(this, 'RestApi', {
      restApiId: props.restApiId,
      rootResourceId: props.rootResourceId
    });

    const method = api.root.addResource('pets').addMethod(
      'GET',
      new MockIntegration({
        integrationResponses: [
          {
            statusCode: '200'
          }
        ],
        passthroughBehavior: PassthroughBehavior.NEVER,
        requestTemplates: {
          'application/json': '{ "statusCode": 200 }'
        }
      }),
      {
        methodResponses: [{ statusCode: '200' }]
      }
    );
```

This doesn't:
```
const api = RestApi.fromRestApiAttributes(this, 'RestApi', {
      restApiId: props.restApiId,
      rootResourceId: props.rootResourceId
    });

    const method = api.root.addResource('pets').addMethod(
      'GET',
      new LambdaIntegration(
        new lambda.Function(this, 'MyLambda', {
          code: new lambda.AssetCode('src'),

          handler: 'index.main',
          runtime: lambda.Runtime.PYTHON_3_6
        })
      ),
      {
        methodResponses: [{ statusCode: '200' }]
      }
    );
```
PS: From the repo code it is clear that  "**restApi** throws an error on imported while **api** returns correctly".
When we use LambdaIntegration, it intrinsically calls ${method.restApi.node.uniqueId} which will throw an error for imported gateway. Workarounds?

### PR DESCRIPTION
**Pull request by nija-at**
Root cause here was that `LambdaIntegration` used the deprecated
`restApi` property on its binding Method. This property does not work
on imported RestApi and has been superceded by the property `api`.

A further bug that was discovered was that the API `methodArn()` on the
Method construct did not work on imported RestApi. This has been fixed
up such that if a `deploymentStage` is not defined for the imported
RestApi, the ARN will return '*' as its stage (shorthand for 'all
stages').

fixes #8679

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-apigateway/lib/method.ts [hunk 1]
```diff
@@ -237,27 +237,22 @@ export class Method extends Resource {
    *   arn:aws:execute-api:{region}:{account}:{restApiId}/{stage}/{method}/{path}
    *
    * NOTE: {stage} will refer to the `restApi.deploymentStage`, which will
```
Comment (njlynch) [inline packages/@aws-cdk/aws-apigateway/lib/method.ts:239]:
```suggestion
   * NOTE: {stage} will refer to the `api.deploymentStage`, which will
```

**Comment by zubairzahoor** [comment]
@nija-at Expected ETA for npm release containing these changes?
