### PR TITLE
fix(codepipeline): correctly validate Artifacts used by Actions in th…

### LINKED ISSUE #2549: CodePipeline Artifact validation fails on valid use case
**Describe the bug**
The validation mechanism for CodePipeline artifacts fails in certain cases that are valid. 

Error: Validation failed with the following errors:
Artifact 'buildArtifact1' was used as input before being used as output
    at Synthesizer.synthesize (/.../node_modules/@aws-cdk/cdk/lib/synthesis.js:22:23)
    at App.run (/.../node_modules/@aws-cdk/cdk/lib/app.js:44:31)
    at Object.<anonymous> (/.../bin/infra.js:8:5)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
    at internal/main/run_main_module.js:17:11

**To Reproduce**
Create a pipeline that has the following stages and dependencies between actions:
buildAction1 has run order 1, input sourceArtifact1 and output buildArtifact1
buildAction2 has run order 2, input sourceArtifact2, extra inputs buildArtifact1 and output buildArtifact2

stages: [
    {
        name: 'Source',
        actions: [sourceAction1, sourceAction2]
    },
    {
        name: 'Build',
        actions: [buildAction1, buildAction2]
    },
   {
      ....
   }
]

**Expected behavior**
The validation should pass. This is a valid pipeline that worked correctly before codepipeline.Artifact construct was introduced.

**Version:**
 - OS MacOS 10.13
 - Programming Language TypeScript
 - CDK Version 0.31.0

### PR DESCRIPTION
**Pull request by skinny85**
…e same Stage.

The bug was: we were incorrectly iterating though the Actions of a given Stage: first we were iterating through all of the Actions looking at their inputs, and then we looped through the Actions again to look at the outputs. But that won't work if the input of an Action is the output of a different Action in the same Stage with a lower `runOrder`. The fix is to iterate through all of the inputs of a given Action, and then the outputs, and only then move on to the next Action in increasing `runOrder` sequence in the same Stage.

Fixes #2549

----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
  - __Design__: For significant features, design document added to `design` folder
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-codepipeline/test/test.artifacts.ts [hunk 1]
```diff
@@ -123,6 +123,55 @@ export = {
...
+                output: new codepipeline.Artifact('buildOutput2'),
+                runOrder: 2,
+              }),
+            ],
+          },
+        ],
+      });
+
+      expect(stack).to(haveResourceLike('AWS::CodePipeline::Pipeline', {
+        //
```
Comment (eladb) [inline packages/@aws-cdk/aws-codepipeline/test/test.artifacts.ts]: What's up here?

Comment (skinny85) [reply packages/@aws-cdk/aws-codepipeline/test/test.artifacts.ts]: The bug is a validation error, so the `expect` is used only to trigger validation. This test fails without the production code changes.
