### PR TITLE
fix(s3-deployment): `Source.jsonData()` fails with null JSON values

### LINKED ISSUE #36052: aws-s3-deployment: Can't upload JSON Data with null values
### Describe the bug

Trying to upload a Source.jsonData() to an S3 bucket, using JSON data that contains a `null` value, causes an error to be thrown.

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### Last Known Working CDK Library Version

2.145.0

### Expected Behavior

No error

### Current Behavior

TypeError is thrown

```
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at Source.escapeTokens (<project path>/node_modules/aws-cdk-lib/aws-s3-deployment/lib/source.js:1:3685)
    at <project path>/node_modules/aws-cdk-lib/aws-s3-deployment/lib/source.js:1:3729
    at Array.map (<anonymous>)
    at Source.escapeTokens (<project path>/node_modules/aws-cdk-lib/aws-s3-deployment/lib/source.js:1:3698)
    at Object.bind (<project path>/node_modules/aws-cdk-lib/aws-s3-deployment/lib/source.js:1:3134)
    at <project path>/node_modules/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.js:1:4556
    at Array.map (<anonymous>)
    at new BucketDeployment2 (<project path>/node_modules/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.js:1:4537)
    at new BucketDeployment2 (<project path>/node_modules/aws-cdk-lib/core/lib/prop-injectable.js:1:488)
```

### Reproduction Steps

```
Source.jsonData('test.json', JSON.parse('{"a":1, "b": null}'))
```

### Possible Solution

https://github.com/aws/aws-cdk/blob/61360ea5d27a3da232f7612fcd9a7512f20967df/packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts#L278-L286

This line should have a null check to skip trying to escape tokens on null values (and just let the nulls pass through)

### Additional Information/Context

_No response_

### AWS CDK Library version (aws-cdk-lib)

aws-cdk-lib@2.219.0

### AWS CDK CLI version

2.1029.4 (build 09c0061)

### Node.js Version

v20.19.5

### OS

Linux

### Language

TypeScript

### Language Version

Typescript (5.9.3)

### Other information

Will create a PR shortly

### PR DESCRIPTION
**Pull request by Lukanite**
In cdk-lib aws-s3-deployment, creating a Source.jsonData() will fail if the JSON has any null fields in it due to `escapeTokens` trying to build an object from it, resulting in `TypeError: Cannot convert undefined or null to object`

### Issue # (if applicable)

Closes #36052.

### Reason for this change

Can't create a Source.jsonData() when `null` values are present in the JSON data itself

### Description of changes

Added a null check around `escapeTokens()` to prevent it from trying to process `null` values

### Describe any new or updated permissions being added

N/A

### Description of how you validated changes

Tested by hand via modifying the compiled JS in my project to add the check, and was able to successfully upload a JSON file to S3 with a null value contained inside. Also added coverage via unit tests/integration tests for the PR build to chew through.

### Checklist
- [X] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by Lukanite** [comment]
Thanks @pahud for kicking off the PR build, I'm committing these changes from another machine that isn't set up yet. I see the style errors, will address and update the commit shortly!

File: packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts [hunk 1]
```diff
@@ -275,7 +275,7 @@ export class Source {
       return obj.map(v => Source.escapeTokens(scope, v));
     }
 
-    if (typeof obj === 'object') {
+    if (obj !== null && typeof obj === 'object') {
```
Comment (Abogical) [inline packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts:283]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof#typeof_null

_Javascript, wth._ 🤦

**Review by Abogical — APPROVED** [review]

**Review by leonmk-aws — APPROVED** [review]

**Comment by leonmk-aws** [comment]
Thank you @Lukanite for reporting the issue and fixing it so quickly !
