### PR TITLE
fix(aws-elasticloadbalancingv2): fix rule dependency

### LINKED ISSUE #1160: AWS::ECS::Service needs DependsOn AWS::ElasticLoadBalancingV2::ListenerRule
```
22/26 | 10:15:33 | CREATE_FAILED        | AWS::ECS::Service                         | greeting-service/Service (greetingserviceService8DA58640) The target group with targetGroupArn arn:aws:elasticloadbalancing:us-east-1:209640446841:targetgroup/greet-inter-7A1DWCFAH8FU/c4bab708f6cad935 does not have an associated load balancer. (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: f6e72ff4-e756-11e8-afbf-dd214588018c)
```

When creating a service and adding it to a load balancer the CloudFormation template fails to deploy with the above error. Example code:

```js
const greeterService = new ecs.Ec2Service(this, 'greeter-service', {
      cluster: cluster,
      desiredCount: 2,
      taskDefinition: greeterTaskDefinition
    });

     // Internet facing load balancer for the frontend services
    const externalLB = new elbv2.ApplicationLoadBalancer(this, 'external', {
      vpc: vpc,
      internetFacing: true
    });

    const externalListener = externalLB.addListener('PublicListener', { port: 80, open: true });

    externalListener.addTargets('greeter', {
      port: 80,
      targets: [greeterService]
    });
```

This is probably happening because the `AWS::ECS::Service` resource needs a `DependsOn` to the `AWS::ElasticLoadBalancingV2::ListenerRule` resource. Otherwise it is a race condition that causes a failure if the service resource creation starts before the listener rule is ready.

### PR DESCRIPTION
**Pull request by rix0rrr**
When ALB listener rules are used, the ordering dependency for services
that require an attachment to a Load Balancer has to be on the
`AWS::ElasticLoadBalancingV2::ListenerRule` object, not on the
`Listener` object (as the current implementation does).

Fixes #1160.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-target-group.ts [hunk 1]
```diff
@@ -250,9 +250,20 @@ export abstract class BaseTargetGroup extends cdk.Construct implements ITargetGr
 
   /**
    * Return an object to depend on the listeners added to this target group
+   *
+   * @deprecated Use 'loadBalancerDependency' instead.
```
Comment (eladb) [inline packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-target-group.ts]: Should we just remove?

File: packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-target-group.ts [hunk 2]
```diff
@@ -250,9 +250,20 @@ export abstract class BaseTargetGroup extends cdk.Construct implements ITargetGr
...
-    return new LazyDependable(this.dependableListeners);
+    return this.loadBalancerDependency();
+  }
+
+  /**
+   * Return an object to depend on this TargetGroup being attached to a load balancer
+   *
+   * @deprecated Use 'loadBalancerDependency' instead.
+   */
+  public loadBalancerDependency(): cdk.IDependable {
```
Comment (eladb) [inline packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-target-group.ts]: Should we just remove?
