### PR TITLE
fix(glue-alpha): prefix validation logic is incorrect

### LINKED ISSUE #27396: (@aws-cdk/aws-glue-alpha): New Prefix check logic is not follow normal S3 prefix format
### Describe the bug

The latest version of job.ts in @aws-cdk/aws-glue-alpha package added check on prefix, and require prefix must begin with "/" and not end with "/"
https://github.com/aws/aws-cdk/blame/0bb49b42406b9b3692063537e6194af80d65c7f9/packages/%40aws-cdk/aws-glue-alpha/lib/job.ts#L847
But, normally for S3 prefix, it should not start with "/" and for the folder, it should end with "/",
https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-prefixes.html

### Expected Behavior

The prefix validation should check prefix must end with "/" not start with "/"

### Current Behavior

            throw new Error(`Invalid prefix format (value: ${prefix})${os_1.EOL}${errors.join(os_1.EOL)}`);
            ^

Error: Invalid prefix format (value: sparkHistoryLogs/CxRfMtrc_RefinementMetric/)
Prefix must begin with '/'
Prefix must not end with '/'
    at Job.validatePrefix (/Volumes/workplace/MarcaGlueDataProcessing/src/MarcaGlueDataProcessingCDK/node_modules/@aws-cdk/aws-glue-alpha/lib/job.js:451:19)

### Reproduction Steps

Create Job construct with "/' ended sparkHistoryLogs parameter

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.99.0-alpha.0

### Framework Version

_No response_

### Node.js Version

18.0

### OS

Macos

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by mikewrighton**
There was logic in `aws-glue-alpha.Job` that expected `SparkUIProps.prefix` to be specified in the form `/prefix-name`, instead of the more conventional `prefix-name/`. This fix addresses the validation and handling of this prefix field to support the correct format. 

BREAKING CHANGE: `SparkUIProps.prefix` strings in the original `/prefix-name` format will now result in a validation error. To retain the same behavior, prefixes must be changed to the new `prefix-name/` format.

Closes #27396.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by scanlonp — APPROVED** [review]
Change looks good. We should clean up the documentation in the `SparkUIProps`. Line 392 should be updated to reflect the new validation. Once that is done, feel free to merge.

File: packages/@aws-cdk/aws-glue-alpha/lib/job.ts [hunk 1]
```diff
@@ -406,13 +406,15 @@ export interface SparkUIProps {
 export interface SparkUILoggingLocation {
   /**
    * The bucket where the Glue job stores the logs.
+   *
```
Comment (scanlonp) [inline packages/@aws-cdk/aws-glue-alpha/lib/job.ts:409]:
```suggestion
   *
```
