### PR TITLE
fix(scheduler-targets-alpha): imported lambda function as schedule target throws synth error

### LINKED ISSUE #29284: (aws-scheduler-targets-alpha): Cannot use imported function ARN with `LambdaInvoke` target
### Describe the bug

I'm trying to invoke a "singleton" lambda created in another Stack. I expose the Function ARN via a CloudFormation output. If the lambda function ARN is being imported from a CFN output (e.g., `Fn.importValue`), even with `sameEnvironment: true`, an error is thrown at synth time.

### Expected Behavior

I expected the validation for the region to be ignored if I use `Lambda.fromFunctionAttributes` with the `sameEnvironment` value set to `true`.

### Current Behavior

I get this error:

```
/private/tmp/bug-report/node_modules/@aws-cdk/aws-scheduler-targets-alpha/lib/lambda-invoke.ts:21
      throw new Error(`Cannot assign function in region ${this.func.env.region} to the schedule ${Names.nodeUniqueId(schedule.node)} in region ${schedule.env.region}. Both the schedule and the function must be in the same region.`);
            ^
Error: Cannot assign function in region ${Token[TOKEN.22]} to the schedule BugReportStackSchedule10380292 in region us-east-2. Both the schedule and the function must be in the same region.
    at LambdaInvoke.addTargetActionToRole (/private/tmp/bug-report/node_modules/@aws-cdk/aws-scheduler-targets-alpha/lib/lambda-invoke.ts:21:13)
    at LambdaInvoke.bindBaseTargetConfig (/private/tmp/bug-report/node_modules/@aws-cdk/aws-scheduler-targets-alpha/lib/target.ts:80:10)
    at LambdaInvoke.bind (/private/tmp/bug-report/node_modules/@aws-cdk/aws-scheduler-targets-alpha/lib/target.ts:103:17)
    at new Schedule (/private/tmp/bug-report/node_modules/@aws-cdk/aws-scheduler-alpha/lib/schedule.ts:315:39)
    at new BugReportStack (/private/tmp/bug-report/lib/bug-report-stack.ts:29:5)
    at Object.<anonymous> (/private/tmp/bug-report/bin/bug-report.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module.m._compile (/private/tmp/bug-report/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.require.extensions.<computed> [as .ts] (/private/tmp/bug-report/node_modules/ts-node/src/index.ts:1621:12)
```

### Reproduction Steps

```ts
import { Schedule, ScheduleExpression } from '@aws-cdk/aws-scheduler-alpha';
import { ScheduleTargetInput } from '@aws-cdk/aws-scheduler-alpha/lib/input';
import { LambdaInvoke } from '@aws-cdk/aws-scheduler-targets-alpha';
import * as cdk from 'aws-cdk-lib';
import { Fn } from 'aws-cdk-lib';
import { Function } from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

export class BugReportStack extends cdk.Stack {
  constructor(scope: Construct, id: string) {
    super(scope, id, {
      env: {
        account: '123456789012',
        region: 'us-east-2',
      }
    });

    const functionArn = Fn.importValue("MyImportArn");
    const lambda = Function.fromFunctionAttributes(this, "ImportedFunction", {
      functionArn,
      sameEnvironment: true,
    });

    const target = new LambdaInvoke(lambda, {
      input: ScheduleTargetInput.fromObject({
        foo: "bar"
      }),
    });
    new Schedule(this, "Schedule", {
      schedule: ScheduleExpression.rate(cdk.Duration.minutes(5)),
      target,
    });
  }
}
```

### Possible Solution

If `sameEnvironment` is set to `true` on the imported lambda, the validations should be skipped.

### Additional Information/Context

Alpha versions are latest as well

```json
{
  "name": "bug-report",
  "version": "0.1.0",
  "bin": {
    "bug-report": "bin/bug-report.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "cdk": "cdk"
  },
  "devDependencies": {
    "@types/jest": "^29.5.12",
    "@types/node": "20.11.19",
    "aws-cdk": "2.130.0",
    "jest": "^29.7.0",
    "ts-jest": "^29.1.2",
    "ts-node": "^10.9.2",
    "typescript": "~5.3.3"
  },
  "dependencies": {
    "@aws-cdk/aws-scheduler-alpha": "^2.130.0-alpha.0",
    "@aws-cdk/aws-scheduler-targets-alpha": "^2.130.0-alpha.0",
    "aws-cdk-lib": "2.130.0",
    "constructs": "^10.0.0",
    "source-map-support": "^0.5.21"
  }
}
```

### CDK CLI Version

2.130.0 (build bd6e5ee)

### Framework Version

_No response_

### Node.js Version

20.x

### OS

MacOS

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by samson-keung**
### Issue # (if applicable)

Closes #29284.

Tracking #31785.

### Reason for this change

Removed the same env check between the Schedule and the Lambda target to allow use of imported Lambda function as target.

### Description of changes

Removed the check that forces the Schedule and the Lambda function to be in the same account and region.

### Description of how you validated changes

- Unit test added to ensure no synth error when using imported Lambda function.
- Integ test added to ensure imported function works. The test ensures the lambda is executed and did what it is supposed to do (i.e. added tag to itself).

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-scheduler-targets-alpha/lib/lambda-invoke.ts [hunk 1]
```diff
@@ -1,34 +1,23 @@
...
+  private readonly func: lambda.IFunction;
+
   constructor(
-    private readonly func: lambda.IFunction,
-    private readonly props: ScheduleTargetBaseProps,
+    func: lambda.IFunction,
+    props: ScheduleTargetBaseProps,
   ) {
     super(props, func.functionArn);
+    this.func = func;
```
Comment (GavinZZ) [inline packages/@aws-cdk/aws-scheduler-targets-alpha/lib/lambda-invoke.ts:17]: why is this needed?

File: packages/@aws-cdk/aws-scheduler-targets-alpha/lib/lambda-invoke.ts [hunk 2]
```diff
@@ -1,34 +1,23 @@
...
   }
 
-  protected addTargetActionToRole(schedule: ISchedule, role: IRole): void {
-    if (!sameEnvDimension(this.func.env.region, schedule.env.region)) {
```
Comment (GavinZZ) [inline packages/@aws-cdk/aws-scheduler-targets-alpha/lib/lambda-invoke.ts:20]: While this would fix the problem mentioned in the issue, I don't think this is a good fix in general since it removes check even for functions and scheduler with known account & regions.

**Review by GavinZZ — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-scheduler-targets-alpha/lib/lambda-invoke.ts (hunk 2 above)
Comment (samson-keung) [reply packages/@aws-cdk/aws-scheduler-targets-alpha/lib/lambda-invoke.ts:20]: That is correct. The reasoning to remove the check is explained [here](https://github.com/aws/aws-cdk/pull/29615).

File: packages/@aws-cdk/aws-scheduler-targets-alpha/lib/lambda-invoke.ts (hunk 1 above)
Comment (samson-keung) [reply packages/@aws-cdk/aws-scheduler-targets-alpha/lib/lambda-invoke.ts:17]: So because `props` is no longer used in `addTargetActionToRole`, TS was complaining:
```
TS6138: Property props is declared but its value is never read
```
To fix, it could be:
```ts
constructor(
    private readonly func: lambda.IFunction,
    props: ScheduleTargetBaseProps,
  ) {
    super(props, func.functionArn);
  }
```
But I do not want to mix the 2 style. So went with what it is now to make the code more consistent.

**Comment by gracelu0** [comment]
What is the deployment behaviour now without this validation if the account/region don't match? Is there any documentation on this restriction? I wasn't able to find anything.

File: packages/@aws-cdk/aws-scheduler-targets-alpha/lib/lambda-invoke.ts (hunk 1 above)
Comment (GavinZZ) [reply packages/@aws-cdk/aws-scheduler-targets-alpha/lib/lambda-invoke.ts:17]: oh I see, I thought `func` is not used either so I asked this question, but I missd that it's still used at the end `this.func.grantInvoke(role);`.

Comment (gracelu0) [reply packages/@aws-cdk/aws-scheduler-targets-alpha/lib/lambda-invoke.ts:17]: Will this apply to other target types as well? If so we should document as TODO to keep the code consistent

Comment (samson-keung) [reply packages/@aws-cdk/aws-scheduler-targets-alpha/lib/lambda-invoke.ts:17]: Yes, same will apply to the other targets if they have the same change. But since it is a code styling issue (no functional difference), we can update the other targets as they get graduated.

**Comment by samson-keung** [comment]
> What is the deployment behaviour now without this validation if the account/region don't match? Is there any documentation on this restriction? I wasn't able to find anything.

From my testing, different account works (although not explicitly documented). Different region will throw error at template deploy time.

File: packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.ts [hunk 3]
```diff
@@ -15,60 +22,111 @@ import { LambdaInvoke } from '../lib';
  * The assertion checks that the expected tag is created by calling listTags on the lambda function
  */
 const app = new cdk.App();
-const stack = new cdk.Stack(app, 'aws-cdk-schedule');
+/**
+ * 1st stack creates a lambda which will be imported ot 2nd stack to test using imported lambda
```
[the remark this answers is not in the document]
Comment (gracelu0) [reply packages/@aws-cdk/aws-scheduler-targets-alpha/test/integ.lambda-invoke.ts:26]: ^nit

**Review by GavinZZ — APPROVED** [review]

**Review by gracelu0 — APPROVED** [review]
