### PR TITLE
fix(s3): `autoDeleteObjects` had redundant `GetObject*` permissions

### LINKED ISSUE #14572: (s3): autoDeleteObjects policy attached to S3 bucket allows s3:GetObject permission
The policy attached to an S3 bucket when you specify `autoDeleteObjects` contains more permissions than needed. In particular `s3:GetObject` is a concern in my case, as I'm dealing with privacy sensitive information.

The lambda works fine without this permission, so I propose this gets removed from this policy.

### Use Case

Dealing with privacy sensitive information, so must restrict access as much as possible.

### Proposed Solution

Remove s3:GetObject from the automatically created policy.

### PR DESCRIPTION
**Pull request by berenddeboer**
This should fix  #14572.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-s3/lib/bucket.ts [hunk 1]
```diff
@@ -1840,7 +1840,9 @@ export class Bucket extends BucketBase {
     // objects in the bucket
     this.addToResourcePolicy(new iam.PolicyStatement({
       actions: [
-        ...perms.BUCKET_READ_ACTIONS, // list objects
+        // list objects
+        's3:GetBucket*',
```
Comment (iliapolo) [inline packages/@aws-cdk/aws-s3/lib/bucket.ts:1844]: For consistency, put these in `perms.ts` under a new `BUCKET_READ_METADATA_ACTIONS` constant. 

Also - you have a linter violation here with indentation.

**Review by iliapolo — CHANGES_REQUESTED** [review]
I expected to see a change in the corresponding [expectation file](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-s3/test/integ.bucket-auto-delete-objects.expected.json). Did you run the [integration test](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-s3/test/integ.bucket-auto-delete-objects.ts)?

See https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#integration-tests

**Review by iliapolo — APPROVED** [review]
