### PR TITLE
fix(s3): grantDelete with KMS SSE

### LINKED ISSUE #4380: s3.Bucket.grantDelete on bucket with KMS SSE generates invalid policy
### Reproduction Steps
This simple stack
``` ts
Key sseKmsKey = new Key(this, "lapinr-see-kms-key");

BucketProps bucketProperties = BucketProps.builder()
                                          .bucketName("lapinr-test-bucket")
                                          .encryption(BucketEncryption.KMS)
                                          .encryptionKey(sseKmsKey)
                                          .build();
Bucket bucket = new Bucket(this,
                           "LapinrTestBucket",
                           bucketProperties);

RoleProps clientRoleProps = RoleProps.builder()
                                     .roleName("lapinr-access-role")
                                     .assumedBy(new ArnPrincipal("arn:aws:iam::1234567890:role/external-role"))
                                     .build();
Role clientRole = new Role(this,
                           "LapinrAccessRole",
                           clientRoleProps);

bucket.grantDelete(clientRole);
```

Generates the following policy
``` js
"LapinrAccessRoleDefaultPolicy0F01FF42": {
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyDocument": {
          "Statement": [
            {
              "Action": "s3:DeleteObject*",
              "Effect": "Allow",
              "Resource": {
                "Fn::Join": [
                  "",
                  [
                    {
                      "Fn::GetAtt": [
                        "LapinrTestBucketDB437746",
                        "Arn"
                      ]
                    },
                    "/*"
                  ]
                ]
              }
            },
            {
              "Effect": "Allow",
              "Resource": {
                "Fn::GetAtt": [
                  "lapinrseekmskey4CB31ADE",
                  "Arn"
                ]
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "PolicyName": "LapinrAccessRoleDefaultPolicy0F01FF42",
        "Roles": [
          {
            "Ref": "LapinrAccessRole015FF5A4"
          }
        ]
      }
```

The problematic part is below, note lack of 'Action' block
``` javascript
{
    "Effect": "Allow",
    "Resource": {
         "Fn::GetAtt": [
            "lapinrseekmskey4CB31ADE",
            "Arn"
         ]
    }
}
```
### Error Log

During CloudFormation stack update, the update fails with a Malformed Policy error due to missing Action block.

### Environment

  - **CLI Version      : 1.9.0**
  - **Framework Version: 1.9.0**
  - **OS               : Linux**
  - **Language         : Java**

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by shreyasdamle**
### Commit Message
fix(s3): grantDelete with KMS SSE (#7528)

Added empty array check for keyActions. This will make sure that `grantDelete` will not create malformed policy when used with `KMS` key. 

Added a new integ test to check CloudFormation will not error out during the deployment.

Fixes #4380

### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by shreyasdamle** [comment]
Sorry, I'm not sure why this request is showing commits that are already in master branch. However, this link will show the correct comparison: https://github.com/aws/aws-cdk/compare/master...shreyasdamle:sdamle-s3

File: packages/@aws-cdk/aws-s3/lib/bucket.ts [hunk 1]
```diff
@@ -597,7 +597,9 @@ abstract class BucketBase extends Resource implements IBucket {
     }
 
     if (this.encryptionKey) {
-      this.encryptionKey.grant(grantee, ...keyActions);
+      if (keyActions.length !== 0 || keyActions === undefined) {
```
Comment (iliapolo) [inline packages/@aws-cdk/aws-s3/lib/bucket.ts:600]: This will actually error if `keyActions` is `undefined`. To you really want to pass `undefined` to `encryptionKey.grant`? I suggest just:

```typescript
if (this.encryptionKey && keyActions && keyActions.length !== 0) {
  this.encryptionKey.grant(grantee, ...keyActions);
}
```

Comment (shreyasdamle) [reply packages/@aws-cdk/aws-s3/lib/bucket.ts]: Sorry, my bad. I'm not sure what I was thinking there. You are absolutely right, `keyActions === undefined` check is totally wrong in this context. I have fixed my mistake.

Thanks for your review @iliapolo

Comment (iliapolo) [reply packages/@aws-cdk/aws-s3/lib/bucket.ts]: 👍
