### PR TITLE
fix: breaking change to deployment config props

### LINKED ISSUE #22566: ‼️ (codedeploy): ServerDeploymentConfig Type Error in java
Please add your +1 👍 to let us know you have encountered this
---

### Overview:

In Java, using [ServerDeploymentConfig.ONE_AT_A_TIME](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codedeploy.ServerDeploymentConfig.html#static-one_at_a_time) with [ServerDeploymentGroupProps](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codedeploy.ServerDeploymentGroupProps.html) results in a type error.

### Workaround: 

The current workaround is to stay on 2.44.0.

----

[Original Issue]

### Describe the bug

Using [ServerDeploymentConfig.ONE_AT_A_TIME](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codedeploy.ServerDeploymentConfig.html#static-one_at_a_time) with [ServerDeploymentGroupProps](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codedeploy.ServerDeploymentGroupProps.html) results in a type error.

The [DeploymentConfig Property](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codedeploy.ServerDeploymentGroupProps.html#deploymentconfig) expects a type of [IServerDeploymentConfig](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codedeploy.IServerDeploymentConfig.html), but the static enums in [ServerDeploymentConfig](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codedeploy.ServerDeploymentConfig.html#static-one_at_a_time) where changed to be typed as [IBaseDeploymentConfig](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codedeploy.IBaseDeploymentConfig.html)

I observed this bug in the latest release of the Java CDK bindings.

### Expected Behavior

I expect `ServerDeploymentGroupProps.builder().deploymentConfig(ServerDeploymentConfig.ONE_AT_A_TIME)` to not result in a type error as it was working in 2.44.0, but became broken in 2.45.0.

### Current Behavior

Using `ServerDeploymentGroupProps.builder().deploymentConfig(ServerDeploymentConfig.ONE_AT_A_TIME)` in Java results in a type error.

### Reproduction Steps

Install latest CDK, try to create a ServerDeploymentGroupProps.builder() instance and pass ServerDeploymentConfig.ONE_AT_A_TIME to the deploymentConfig method.

This also impacts LambdaDeploymentGroup.builder(), and I imagine others.

### Possible Solution

I think the issue stems from these lines https://github.com/aws/aws-cdk/commit/6840d8e43381793bd7a51191bddaffc4cb6641d6#diff-93f73231716deb0056687ee155c13d03ccabe2222fd191a33be9caeb7ad87ebaL82-L85 that used to call https://github.com/aws/aws-cdk/commit/6840d8e43381793bd7a51191bddaffc4cb6641d6#diff-93f73231716deb0056687ee155c13d03ccabe2222fd191a33be9caeb7ad87ebaL126-L131 that had the correct type.

However now https://github.com/aws/aws-cdk/commit/6840d8e43381793bd7a51191bddaffc4cb6641d6#diff-93f73231716deb0056687ee155c13d03ccabe2222fd191a33be9caeb7ad87ebaR36 calls https://github.com/aws/aws-cdk/commit/6840d8e43381793bd7a51191bddaffc4cb6641d6#diff-40567274e0d0eeca9055e6d9bce3a1c5b325045f8e21f14e60f08076eebdd061R118 which has the incorrect type.

### Additional Information/Context

_No response_

### CDK CLI Version

2.45.0

### Framework Version

_No response_

### Node.js Version

14.20

### OS

Amazon Linux 2

### Language

Java

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by MrArnoldPalmer**
Change all `deploymentConfig` static method implementations on
`EcsDeploymentConfig`, `LambdaDeploymentConfig`, and
`ServerDeploymentConfig` to return their corresponding specific
interfaces instead of `IBaseDeploymentConfig`. This reverts breaking
changes to Java users introduced in https://github.com/aws/aws-cdk/pull/22159

Fixes #22566

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by MrArnoldPalmer** [comment]
@clareliguori I removed all of the "more specific" deployment config interfaces as part of fixing this, instead of re-implementing the `deploymentConfig` and `fromDeploymentConfigNasme` methods in all of the deployment config classes (with the more specific return types) since I couldn't think of any case off the top of my head where these interfaces may be needed with additional properties etc.

Additionally we should be able to add them back with additional optional properties in the future in a non-breaking way, just keeping them around seems dangerous as it opens us to this bug of structural interfaces are implemented somewhere where an explicit type is actually needed for Java compatibility.

**Comment by kaizencc** [comment]
Exempting tests. Our typescript tests are insufficient to test this anyhow. I will test this locally in java before merging this PR.

**Comment by MrArnoldPalmer** [comment]
A user explicitly importing and defining the more specific interfaces would be broken  by this, but leaving them in feels like leaving the foot gun loaded.

```ts
import { IServerDeploymentConfig } from '';

const myThing: IServerDeploymentConfig { ... };
```

We may have to though, @kaizencc @corymhall what do you think?

File: packages/@aws-cdk/aws-codedeploy/lib/ecs/deployment-config.ts [hunk 1]
```diff
@@ -1,23 +1,7 @@
...
- *
- * If you want to reference an already existing deployment configuration,
- * or one defined in a different CDK Stack,
- * use the {@link EcsDeploymentConfig#fromEcsDeploymentConfigName} method.
- *
- * The default, pre-defined Configurations are available as constants on the {@link EcsDeploymentConfig} class
- * (for example, `EcsDeploymentConfig.AllAtOnce`).
- */
-export interface IEcsDeploymentConfig extends IBaseDeploymentConfig {
-}
```
Comment (clareliguori) [inline packages/@aws-cdk/aws-codedeploy/lib/ecs/deployment-config.ts:19]: This seems like a breaking change compared to an older release like v2.44.0, where IEcsDeploymentConfig was defined as follows:
https://github.com/aws/aws-cdk/blob/v2.44.0/packages/%40aws-cdk/aws-codedeploy/lib/ecs/deployment-config.ts#L13-L16

And fromEcsDeploymentConfigName explicitly returned IEcsDeploymentConfig:
https://github.com/aws/aws-cdk/blob/v2.44.0/packages/%40aws-cdk/aws-codedeploy/lib/ecs/deployment-config.ts#L38-L40

IIUC if someone has Java code using fromEcsDeploymentConfigName in v2.44.0, they will break on updating to this, since the return type is changing for that function and the class is being removed, right?
```java
IEcsDeploymentConfig config = EcsDeploymentConfig.fromEcsDeploymentConfigName(...);
```

File: packages/@aws-cdk/aws-codedeploy/lib/lambda/deployment-config.ts [hunk 2]
```diff
@@ -1,23 +1,7 @@
...
- *
- * If you want to reference an already existing deployment configuration,
- * or one defined in a different CDK Stack,
- * use the {@link LambdaDeploymentConfig#fromLambdaDeploymentConfigName} method.
- *
- * The default, pre-defined Configurations are available as constants on the {@link LambdaDeploymentConfig} class
- * (`LambdaDeploymentConfig.AllAtOnce`, `LambdaDeploymentConfig.Canary10Percent30Minutes`, etc.).
- */
-export interface ILambdaDeploymentConfig extends IBaseDeploymentConfig {
-}
```
Comment (clareliguori) [inline packages/@aws-cdk/aws-codedeploy/lib/lambda/deployment-config.ts:19]: Same as above with ECS, this interface already existed in older versions:
https://github.com/aws/aws-cdk/blob/v2.44.0/packages/%40aws-cdk/aws-codedeploy/lib/lambda/deployment-config.ts#L13-L16

**Comment by corymhall** [comment]
> @madeline-k pointed out a user explicitly importing and defining the more specific interfaces would be broken by this, but leaving them in feels like leaving the foot gun loaded.

Yeah I think we probably should leave them in. If we mark them as deprecated thats probably good enough to prevent them from being used in the future.

File: packages/@aws-cdk/aws-codedeploy/package.json [hunk 3]
```diff
@@ -161,7 +161,13 @@
...
       "docs-public-apis:@aws-cdk/aws-codedeploy.IEcsApplication.applicationArn",
       "docs-public-apis:@aws-cdk/aws-codedeploy.IEcsApplication.applicationName",
-      "props-physical-name:@aws-cdk/aws-codedeploy.CustomLambdaDeploymentConfigProps"
+      "props-physical-name:@aws-cdk/aws-codedeploy.CustomLambdaDeploymentConfigProps",
+      "from-signature:@aws-cdk/aws-codedeploy.EcsDeploymentConfig.fromEcsDeploymentConfigName",
+      "from-signature:@aws-cdk/aws-codedeploy.LambdaDeploymentConfig.fromLambdaDeploymentConfigName",
+      "from-signature:@aws-cdk/aws-codedeploy.ServerDeploymentConfig.fromServerDeploymentConfigName",
+      "no-unused-type:@aws-cdk/aws-codedeploy.IEcsDeploymentConfig",
+      "no-unused-type:@aws-cdk/aws-codedeploy.ILambdaDeploymentConfig",
+      "no-unused-type:@aws-cdk/aws-codedeploy.IServerDeploymentConfig"
```
Comment (kaizencc) [inline packages/@aws-cdk/aws-codedeploy/package.json:170]: I've looked over these and they seem reasonable from our changes, but want to highlight them just in case.

File: packages/@aws-cdk/aws-codedeploy/lib/ecs/deployment-config.ts (hunk 1 above)
Comment (MrArnoldPalmer) [reply packages/@aws-cdk/aws-codedeploy/lib/ecs/deployment-config.ts]: yeah upon further though we can't change these 😄

**Comment by MrArnoldPalmer** [comment]
Went back to keeping all of the interface types and instead of calling `BaseDeploymentConfig.deploymentConfig` from each implementor call a free floating function in `utils.ts` since overriding a protected method and changing the return type is not allowed by JSII. This should be non-breaking as `BaseDeploymentConfig` class is abstract.

**Review by kaizencc — APPROVED** [review]
I tested this by running a java app against my local aws-cdk-lib with this change, and did not get an error. I also tested it against a normal aws-cdk-lib and did get the error. Putting my stamp of approval on this and shipping it.
