### PR TITLE
fix(init): 'cdk init' doesn't leave .d.ts files

### LINKED ISSUE #2314: init csharp: add-project.hook.d.ts is copied into target folder
**Describe the bug**

A file that is used for `cdk init` processing is copied into the user's source folder. It shouldn't be.

**To Reproduce**

```
cdk init --language=csharp
```

### PR DESCRIPTION
**Pull request by rix0rrr**
`cdk init` was leaving `add-project.hook.d.ts` in the .NET project
directory, since that file was not matching the regex intended to
catch those files.

Fix that, and add a test to make sure.

Fixes #2314.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk/lib/init.ts [hunk 1]
```diff
@@ -116,7 +116,8 @@ export class InitTemplate {
       } else if (file.match(/^.*\.template\.[^.]+$/)) {
         await this.installProcessed(fromFile, toFile.replace(/\.template(\.[^.]+)$/, '$1'), project);
         continue;
-      } else if (file.match(/^.*\.hook\.[^.]+$/)) {
+      } else if (file.match(/^.*\.hook\.(d.)?[^.]+$/)) {
+        console.log(file);
```
Comment (eladb) [inline packages/aws-cdk/lib/init.ts]: oops

**Comment by shivlaks** [comment]
can you add Fixes #2314 to the commit body as well please :)
