### PR TITLE
fix(core): tags not working for cognito user pools

### LINKED ISSUE #3882: Tags not applied to Cognito UserPools
### What is the problem?
In short, Cognito User Pool resources generated by the CDK do not have their parent Stack's Tags applied to them.

It's perhaps a bit of a stretch to call this a bug with the CDK. The problem appears to be that the CloudFormation syntax for defining tags on a Cognito User Pool resource differs from the norm. This may be breaking whatever convention the CDK uses to apply tags to resources.

For User Pools, Tags must be supplied as a property called UserPoolTags and follow a JSON structure, see more here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-userpooltags

### Reproduction Steps

```
class TestStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    // just to confirm tags are propagating, create a resource where the stack level tags are applied.
    new dynamodb.Table(this, "TablesGetTagsNoProblems", {
      partitionKey: { name: "pk", type: AttributeType.STRING },
      sortKey: { name: "sk", type: AttributeType.STRING },
      billingMode: BillingMode.PAY_PER_REQUEST
    });

    const testUserPool = new cognito.UserPool(this, "TestUserPool");

    testUserPool;

    // Here's a workaround
    /*
    const cfnPool = testUserPool.node.defaultChild as cognito.CfnUserPool;

    cfnPool.userPoolTags = {
      TagAppliedDirect: "TestTagValue",
      AnotherTagAppliedDirect: "TestTagValue2"
    };
    */
  }
}

const testStack = new TestStack(app, "TestStack");

Tag.add(testStack, "TestTag", "TestTagValue"); // this is applied to the DDB Table but not the Cognito User Pool
```

### Verbose Log
Here's the CloudFormation output when I use the workaround above, note the differences in how tags are applied to the resources

```
Resources:
  TablesGetTagsNoProblems170A1452:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: TestTag
          Value: TestTagValue
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: TestStack/TablesGetTagsNoProblems/Resource
  TestUserPool83C2ABD0:
    Type: AWS::Cognito::UserPool
    Properties:
      LambdaConfig: {}
      UserPoolTags:
        TagAppliedDirect: TestTagValue
        AnotherTagAppliedDirect: TestTagValue2
    Metadata:
      aws:cdk:path: TestStack/TestUserPool/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.6.1,@aws-cdk/assets=1.6.1,@aws-cdk/aws-apigateway=1.6.1,@aws-cdk/aws-applicationautoscaling=1.6.1,@aws-cdk/aws-autoscaling-common=1.6.1,@aws-cdk/aws-cloudwatch=1.6.1,@aws-cdk/aws-cognito=1.6.1,@aws-cdk/aws-dynamodb=1.6.1,@aws-cdk/aws-ec2=1.6.1,@aws-cdk/aws-events=1.6.1,@aws-cdk/aws-iam=1.6.1,@aws-cdk/aws-kms=1.6.1,@aws-cdk/aws-lambda=1.6.1,@aws-cdk/aws-lambda-event-sources=1.6.1,@aws-cdk/aws-logs=1.6.1,@aws-cdk/aws-s3=1.6.1,@aws-cdk/aws-s3-assets=1.6.1,@aws-cdk/aws-s3-notifications=1.6.1,@aws-cdk/aws-sns=1.6.1,@aws-cdk/aws-sns-subscriptions=1.6.1,@aws-cdk/aws-sqs=1.6.1,@aws-cdk/aws-ssm=1.6.1,@aws-cdk/core=1.6.1,@aws-cdk/cx-api=1.6.1,@aws-cdk/region-info=1.6.1,jsii-runtime=node.js/v10.16.0
```

### Environment

  - **CDK CLI Version:** 1.6.1
  - **Module Version:** 1.6.1
  - **OS:** all
  - **Language:** TypeScript 

### Other information
I brought this up in the Gitter channel and it was suggested I raise an issue for it to be investigated: https://gitter.im/awslabs/aws-cdk?at=5d68b4392efeca1df51cb710

### PR DESCRIPTION
**Pull request by moofish32**
Cognito user pool tags do not use the property name `Tags`. In order to support properties without the name `Tags` the code needs to support arbitrary names for the tags field. I moved all references to `Tags` into the schema package such that `codegen` does not share any of the knowledge about special names for tag fields.
  
 * moved all knowledge about tag names into the schema package and
 included UserPoolTags as taggable name
 * refactored codegen to use new schema package to identify tag
 properties
 * TagManager now supports additional optional TagManagerOptions to control the naming of the tag property field and enable future extensions without breaking changes

Fixes #3882

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/cfnspec/lib/schema/property.ts [hunk 1]
```diff
@@ -222,6 +222,19 @@ export function isPropertyScrutinyType(str: string): str is PropertyScrutinyType
   return (PropertyScrutinyType as any)[str] !== undefined;
 }
 
+const tagPropertyNames = {
+  Tags: "",
+  UserPoolTags: "",
+};
+
+export type TagPropertyName = keyof typeof tagPropertyNames;
```
Comment (moofish32) [inline packages/@aws-cdk/cfnspec/lib/schema/property.ts]: Not sure if there are reasons I can't do this, but it was the cleanest way to check a literal type. I suppose I could go enum?

File: packages/@aws-cdk/cfnspec/lib/schema/resource-type.ts [hunk 2]
```diff
@@ -1,5 +1,8 @@
 import { Documented, PrimitiveType } from './base-types';
-import { isTagProperty, Property, TagProperty } from './property';
+import { isTagProperty, isTagPropertyAutoScalingGroup, isTagPropertyJson,
```
Comment (moofish32) [inline packages/@aws-cdk/cfnspec/lib/schema/resource-type.ts]: this got long -- if I should move to a require let me know.

File: packages/@aws-cdk/cfnspec/lib/schema/property.ts (hunk 1 above)
Comment (nmussy) [reply packages/@aws-cdk/cfnspec/lib/schema/property.ts]: Is JSII complaining about this?

```ts
export type TagPropertyName = 'Tags' | 'UserPoolTags';
```

If that's the case, I can see a slightly cleaner way that doesn't require instantiating an "unused" const:

```ts
interface TagProperty {
  Tags: never;
  UserPoolTags: never;
}

export type TagPropertyName = keyof TagProperty;
```

Comment (moofish32) [reply packages/@aws-cdk/cfnspec/lib/schema/property.ts]: jsii didn't complain locally -- figured the full suite would tell me.

Comment (nmussy) [reply packages/@aws-cdk/cfnspec/lib/schema/property.ts]: I meant complaining about my first snippet:

```ts
export type TagPropertyName = 'Tags' | 'UserPoolTags';
```

Sorry if I wasn't clear. And if you don't get errors building the cognito package, you should be good. 👍

**Comment by moofish32** [comment]
is my fail just the breaking change? If so I can revert to avoid the break to one of the options identified above.

```API elements with incompatible changes:
err  - INITIALIZER @aws-cdk/core.TagManager.<initializer>: argument tagType, takes @aws-cdk/core.TagManagerProps (formerly @aws-cdk/core.TagType): @aws-cdk/core.TagType is an enum different from @aws-cdk/core.TagManagerProps [incompatible-argument:@aws-cdk/core.TagManager.<initializer>]
err  - INITIALIZER @aws-cdk/core.TagManager.<initializer>: argument resourceTypeName, not accepted anymore. [removed-argument:@aws-cdk/core.TagManager.<initializer>]
err  - INITIALIZER @aws-cdk/core.TagManager.<initializer>: argument tagStructure, not accepted anymore. [removed-argument:@aws-cdk/core.TagManager.<initializer>]
@aws-cdk/custom-resources... OK.
@aws-cdk/cx-api... OK.
@aws-cdk/region-info... OK.
Some packages seem to have undergone breaking API changes. Please avoid.```

**Comment by nmussy** [comment]
Breaking changes are checked near the end of the build IIRC, so you should
be good for the rest yes

File: packages/@aws-cdk/cfnspec/lib/schema/resource-type.ts [hunk 3]
```diff
@@ -31,10 +34,42 @@ export interface ResourceType extends Documented {
...
+    Tags: TagPropertyStandard;
+    UserPoolTags: TagPropertyStandard;
+    [name: string]: Property;
+  }
+}
+
+export interface TaggableResourceAutoScalingGroup extends TaggableResource {
+  Properties: {
+    Tags: TagPropertyAutoScalingGroup;
+    UserPoolTags: TagPropertyAutoScalingGroup;
```
Comment (eladb) [inline packages/@aws-cdk/cfnspec/lib/schema/resource-type.ts]: Does it make sense that an autoscaling group will have a `UserPoolTags` property?

File: packages/@aws-cdk/core/lib/tag-manager.ts [hunk 4]
```diff
@@ -215,18 +239,27 @@ export class TagManager {
...
+   */
+  public readonly tagPropertyName: string;
+
   private readonly tags = new Map<string, Tag>();
   private readonly priorities = new Map<string, number>();
   private readonly tagFormatter: ITagFormatter;
   private readonly resourceTypeName: string;
   private readonly initialTagPriority = 50;
 
-  constructor(tagType: TagType, resourceTypeName: string, tagStructure?: any) {
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/tag-manager.ts]: I don't think we can break this API. It's marked as stable.

You can add a fourth optional argument with `TagManagerOptions` and add the the 2.0 issue a note to clean this up later.

File: packages/@aws-cdk/cfnspec/lib/schema/resource-type.ts (hunk 3 above)
Comment (eladb) [reply packages/@aws-cdk/cfnspec/lib/schema/resource-type.ts]: Why do we need all these interfaces? Not sure I understand this change

Comment (moofish32) [reply packages/@aws-cdk/cfnspec/lib/schema/resource-type.ts]: you are totally right -- now that I have the `keyOf` working, I don't need these.

File: packages/@aws-cdk/core/lib/tag-manager.ts (hunk 4 above)
Comment (moofish32) [reply packages/@aws-cdk/core/lib/tag-manager.ts]: yep -- change coming up.

**Comment by moofish32** [comment]
Where do I open the v2 issue or did I miss a document telling me about this?

**Comment by eladb** [comment]
Hey @moofish32 what's up? How are you?

- The v2.0 issue is here: https://github.com/aws/aws-cdk/issues/3398 (I pinned it now).
- What's the next step here? Are you waiting for my review?

File: packages/@aws-cdk/core/test/test.tag-manager.ts [hunk 5]
```diff
@@ -52,6 +59,7 @@ export = {
   },
   '#renderTags() handles standard, map, keyValue, and ASG tag formats'(test: Test) {
     const tagged: TagManager[] = [];
+    // const props = Object.assign({}, defaultProps, {tagType: TagType.AUTOSCALING_GROUP});
```
Comment (moofish32) [inline packages/@aws-cdk/core/test/test.tag-manager.ts]: I will remove this.

File: packages/@aws-cdk/aws-s3/lib/notifications-resource/notifications-resource-handler.ts [hunk 6]
```diff
@@ -63,7 +63,7 @@ export class NotificationsResourceHandler extends cdk.Construct {
 
     const resourceType = 'AWS::Lambda::Function';
     class InLineLambda extends cdk.CfnResource {
-      public readonly tags: cdk.TagManager = new cdk.TagManager(cdk.TagType.STANDARD, resourceType);
+      public readonly tags: cdk.TagManager = new cdk.TagManager( cdk.TagType.STANDARD, resourceType);
```
Comment (moofish32) [inline packages/@aws-cdk/aws-s3/lib/notifications-resource/notifications-resource-handler.ts]: will fix white space

**Comment by moofish32** [comment]
@eladb  - I refactored to make this backwards compatible. I think I'm ready for one more review I have a couple of clean up comments against my self.  I'm still not sure how I should handle a breaking change in the constructor.

I went to an optional additional parameter:

```ts
constructor(tagType: TagType, resourceTypeName: string, tagStructure?: any, options?: TagManagerOptions)
```

Going forward it seems like it would make more sense to move the constructor to:

```ts
export interface TagManagerOptions {
  /**
   * The initial CloudFormation tags
   *
   * If the user set tags on the lower level Cfn* object this are passed here to
   * ensure they are set on the final contruct. Based on the TagType these are
   * validated and parsed.
   */
  readonly cfnTags?: any;
  /**
   * The name of the property in CloudFormation for these tags
   *
   * Normally this is Tags, but Cognito UserPool uses UserPoolTags
   * @default tags
   */
  readonly tagPropertyName?: string;
}


constructor(tagType: TagType, resourceTypeName: string, options?: TagManagerOptions)
```

Based on the V2 issue, how to deprecate a constructor.

File: packages/@aws-cdk/core/lib/tag-manager.ts [hunk 7]
```diff
@@ -215,18 +225,27 @@ export class TagManager {
...
+  constructor(tagType: TagType, resourceTypeName: string, tagStructure?: any, options?: TagManagerOptions) {
     this.resourceTypeName = resourceTypeName;
     this.tagFormatter = TAG_FORMATTERS[tagType];
     if (tagStructure !== undefined) {
       this._setTag(...this.tagFormatter.parseTags(tagStructure, this.initialTagPriority));
     }
+    this.tagPropertyName = options !== undefined ? options.tagPropertyName || 'tags' : 'tags';
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/tag-manager.ts]: I prefer:

```ts
options = options || {};
this.tagPropertyName = options.tagPropertyName || 'tags';
```

File: packages/@aws-cdk/core/test/test.tag-manager.ts (hunk 5 above)
Comment (eladb) [reply packages/@aws-cdk/core/test/test.tag-manager.ts]: please

**Comment by moofish32** [comment]
@eladb - I think this last push addresses your comments.

**Comment by moofish32** [comment]
I am not this build failure is due to this change?

File: packages/@aws-cdk/core/lib/cfn-resource.ts [hunk 8]
```diff
@@ -272,8 +272,12 @@ export class CfnResource extends CfnRefElement {
   }
 
   protected get cfnProperties(): { [key: string]: any } {
-    const tags = TagManager.isTaggable(this) ? this.tags.renderTags() : {};
-    return deepMerge(this._cfnProperties || {}, {tags});
+    if (TagManager.isTaggable(this) && this.tags.renderTags() !== undefined) {
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/cfn-resource.ts]: call `renderTags` once and reuse the result

File: packages/@aws-cdk/core/lib/cfn-resource.ts [hunk 9]
```diff
@@ -272,8 +272,12 @@ export class CfnResource extends CfnRefElement {
...
+      const tags: {[key: string]: any} = {};
+      tags[this.tags.tagPropertyName] = this.tags.renderTags();
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/cfn-resource.ts]: Maybe we can refactor this so that we rename `renderTags` to `applyTagsProperty` or something like that and it will take care of everything:

```
this.tags.applyTagsProperty(this._cfnProperties);
```

Comment (moofish32) [reply packages/@aws-cdk/core/lib/cfn-resource.ts]: What do you think about: 

`this.tags.asCfnProperty()` ?

File: packages/@aws-cdk/core/lib/tag-manager.ts [hunk 10]
```diff
@@ -215,18 +229,28 @@ export class TagManager {
...
+  public readonly tagPropertyName: string;
+
   private readonly tags = new Map<string, Tag>();
   private readonly priorities = new Map<string, number>();
   private readonly tagFormatter: ITagFormatter;
   private readonly resourceTypeName: string;
   private readonly initialTagPriority = 50;
 
-  constructor(tagType: TagType, resourceTypeName: string, tagStructure?: any) {
+  constructor(tagType: TagType, resourceTypeName: string, tagStructure?: any, options?: TagManagerOptions) {
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/tag-manager.ts]:
```suggestion
  constructor(tagType: TagType, resourceTypeName: string, tagStructure?: any, options: TagManagerOptions = { }) {
```

File: packages/@aws-cdk/core/lib/tag-manager.ts [hunk 11]
```diff
@@ -215,18 +229,28 @@ export class TagManager {
...
     this.resourceTypeName = resourceTypeName;
     this.tagFormatter = TAG_FORMATTERS[tagType];
     if (tagStructure !== undefined) {
       this._setTag(...this.tagFormatter.parseTags(tagStructure, this.initialTagPriority));
     }
+    options = options || {};
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/tag-manager.ts]: Not needed anymore:

```suggestion
```

File: packages/@aws-cdk/core/lib/tag-manager.ts [hunk 12]
```diff
@@ -259,6 +283,24 @@ export class TagManager {
...
+   * Creates the Tags property object
+   *
+   * The object contains a single key for the tag property name with a value of
+   * the properly formatted tags
+   */
+  public asCfnProperty(): {[key: string]: any} {
+    const tagsProp: {[key: string]: any} = {};
+    tagsProp[this.tagPropertyName] = this.renderTags();
+    return tagsProp;
+  }
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/tag-manager.ts]: Why do we need this method? `renderTags` and `tagPropertyName` are both public. Why not just put this logic within `CfnResource`?

Comment (moofish32) [reply packages/@aws-cdk/core/lib/tag-manager.ts]: So I started to consider consolidation but how should I view a breaking change? If I take away a public method is that breaking? Should we make the refactor and start deprecating methods.

Comment (eladb) [reply packages/@aws-cdk/core/lib/tag-manager.ts]: Yes, let's move to `CfnResource` and keep` tagPropertyName` and `renderTags` public.

File: packages/@aws-cdk/core/lib/cfn-resource.ts [hunk 13]
```diff
@@ -318,8 +318,12 @@ export class CfnResource extends CfnRefElement {
...
 
   protected get cfnProperties(): { [key: string]: any } {
-    const tags = TagManager.isTaggable(this) ? this.tags.renderTags() : {};
-    return deepMerge(this._cfnProperties || {}, {tags});
+    if (TagManager.isTaggable(this)) {
+      const tagsProp: { [key: string]: any } = {};
+      tagsProp[this.tags.tagPropertyName] = this.tags.renderTags();
+      return deepMerge(this._cfnProperties || {}, tagsProp);
+    }
+    return this._cfnProperties;
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/cfn-resource.ts]:
```suggestion
    return this._cfnProperties || {};
```

**Comment by moofish32** [comment]
I believe I'm complete for all comments, let me know if I need to update branch or take any other action.

**Comment by nmussy** [comment]
3rd test body
