### PR TITLE
fix(s3): bucketKey does not support SSE-S3

### LINKED ISSUE #30183: s3: bucketKey should support SSE-S3
### Describe the bug

`bucketKeyEnabled` not allowed when the encryption is SSE-S3.

https://github.com/aws/aws-cdk/blob/65f2bd99d857234a81efe82845133f2e8c7381b8/packages/aws-cdk-lib/aws-s3/test/bucket.test.ts#L577-L587

But there's no document about this restriction and CloudFormation and console actually allow you to specify that.

image

Workaround:

```ts
    // create a s3 bucket with SSE
    const bucket = new s3.Bucket(this, 'Bucket', {
      encryption: s3.BucketEncryption.S3_MANAGED,
    });
    (bucket.node.defaultChild as s3.CfnBucket).addPropertyOverride('BucketEncryption.ServerSideEncryptionConfiguration.0.BucketKeyEnabled', true)
```

### Expected Behavior

Allows BucketEncryption with SSE-S3.

### Current Behavior

not allowed

### Reproduction Steps

```ts
 const bucket = new s3.Bucket(this, 'Bucket', {
      encryption: s3.BucketEncryption.S3_MANAGED,
      bucketKeyEnabled: true,
    });
```

### Possible Solution

fix the logic here

https://github.com/aws/aws-cdk/blob/65f2bd99d857234a81efe82845133f2e8c7381b8/packages/aws-cdk-lib/aws-s3/lib/bucket.ts#L2130-L2136

### Additional Information/Context

_No response_

### CDK CLI Version

v2.141.0

### Framework Version

_No response_

### Node.js Version

all

### OS

all

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by pahud**
### Issue # (if applicable)

Closes #30183 

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-s3/lib/bucket.ts [hunk 1]
```diff
@@ -2127,12 +2129,18 @@ export class Bucket extends BucketBase {
...
     if (
       props.bucketKeyEnabled &&
-      ![BucketEncryption.KMS, BucketEncryption.KMS_MANAGED, BucketEncryption.DSSE, BucketEncryption.DSSE_MANAGED].includes(encryptionType)
+      ![
+        BucketEncryption.KMS,
+        BucketEncryption.KMS_MANAGED,
+        BucketEncryption.DSSE,
+        BucketEncryption.DSSE_MANAGED,
+        BucketEncryption.S3_MANAGED,
+      ].includes(encryptionType)
```
Comment (aaythapa) [inline packages/aws-cdk-lib/aws-s3/lib/bucket.ts:2141]: I see in the `BucketEncryption` enum that the error is now only thrown when the encryptionType is `UNENCRYPTED`. Should this check be changed to throw the error if `encryptionType == BucketEncryption.UNENCRYPTED`?

File: packages/aws-cdk-lib/aws-s3/lib/bucket.ts [hunk 2]
```diff
@@ -1440,7 +1440,8 @@ export interface BucketProps {
    *   attendant cost implications of that).
    * - If enabled, S3 will use its own time-limited key instead.
    *
-   * Only relevant, when Encryption is set to `BucketEncryption.KMS` or `BucketEncryption.KMS_MANAGED`.
+   * Only relevant, when Encryption is set to `BucketEncryption.KMS`, `BucketEncryption.KMS_MANAGED` or
+   * `BucketEncryption.S3_MANAGED`.
```
Comment (aaythapa) [inline packages/aws-cdk-lib/aws-s3/lib/bucket.ts:1444]: Is it not also relevant for DSSE_MANAGED and DSSE

**Review by aaythapa — COMMENTED** [review]
looks good overall, some small comments

File: packages/aws-cdk-lib/aws-s3/lib/bucket.ts (hunk 1 above)
Comment (pahud) [reply packages/aws-cdk-lib/aws-s3/lib/bucket.ts:2141]: Agree!

**Comment by pahud** [comment]
All addressed.

**Review by aaythapa — APPROVED** [review]
🚀
