### PR TITLE
fix(cloudwatch): Alarm can't use `MathExpression` without submetrics

### LINKED ISSUE #7155: Attempting to create an Alarm on an INSIGHT_RULE_METRIC results in "Period must not be null"
**Action:** create a stack containing a Log Insights Rule, and an Alarm that uses the Insight Rule as a source
**Expected:** successful creation
**Actual:** Stack creation fails, with an `ValidationError` when trying to create the Alarm, with message "Period must not be null"

### Reproduction Steps
```
import json
from aws_cdk.core import App, Stack, Duration, Construct
from aws_cdk.aws_logs import LogGroup
from aws_cdk.aws_cloudwatch import CfnInsightRule, Alarm, MathExpression


def create_log_group_insight_rule(
        scope: Construct,
        rule_name: str,
        aggregate_metric: str,
        log_group_names: list,
        keys: list = [],
        filters: list = []
):
    rule_body = json.dumps({
        "Schema": {
            "Name": "CloudWatchLogRule",
            "Version": 1
        },
        "LogGroupNames": log_group_names,
        "LogFormat": "JSON",
        "Contribution": {
            "Keys": keys,
            "Filters": filters
        },
        "AggregateOn": aggregate_metric
    })

    return CfnInsightRule(
        scope,
        rule_name,
        rule_body=rule_body,
        rule_name=rule_name,
        rule_state='ENABLED'
    )


app = App()
stack = Stack(app, 'MinimalReproOfPeriodBug')
log_group = LogGroup(stack, 'log_group')
insight_rule = create_log_group_insight_rule(
    stack,
    'rule_name',
    'Count',
    [log_group.log_group_name],
    ['$.customerId']
)
insight_rule.node.add_dependency(log_group)
Alarm(
    stack, "Alarm",
    alarm_name='alarm_name',
    datapoints_to_alarm=2,
    evaluation_periods=1,
    metric=MathExpression(
            expression='INSIGHT_RULE_METRIC("' + insight_rule.attr_rule_name + \
                       '", UniqueContributors")',
            using_metrics={},
            period=Duration.seconds(60)
        ),
    period=Duration.seconds(60),
    threshold=1)
app.synth()
```
`cdk deploy` the code above to reproduce.

Note that, according to the docs [here](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.Alarm.html), `Alarm.period` should not be used with `MathExpression`s - I tried it both with and without, same error both times.

### Error Log

```
Period must not be null (Service: AmazonCloudWatch; Status Code: 400; Error Code: ValidationError; Request ID: <requestId>)
```

### Environment

  - **CLI Version      :** 1.31.0 (build 8f3ac79)
  - **Framework Version:** Unknown
  - **OS               :** MacOS 10.14.6
  - **Language         :** Python3

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
### Commit Message
fix(cloudwatch): Alarm can't use `MathExpression` without submetrics

`MathExpression`s without submetrics (like for example, `INSIGHT_RULE_METRIC`) will end up without a `period`, which is not allowed.

Add a `period` field to the schema (it's not in the upstream schema
yet), and render it out when submetrics are missing.

Fixes #7155.
### End Commit Message

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-cloudwatch/lib/metric-types.ts [hunk 1]
```diff
@@ -315,6 +315,11 @@ export interface MetricExpressionConfig {
    * Metrics used in the math expression
    */
   readonly usingMetrics: Record<string, IMetric>;
+
+  /**
+   * How many seconds to aggregate over
+   */
+  readonly period: number;
```
Comment (nija-at) [inline packages/@aws-cdk/aws-cloudwatch/lib/metric-types.ts:322]: `core.Duration`?
