### PR TITLE
fix(redshift): single-node clusters fail with node count error

### LINKED ISSUE #9856: [aws-redshift] Single-node clusters fail with node count error
### Issue

Unable to deploy a single node Redshift cluster using the high level 'Cluster' construct.

### Reproduction Steps

```

class RedshiftStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        # Define a VPC
        my_vpc = ec2.Vpc(self, id='my-vpc', cidr='10.0.0.0/16', enable_dns_hostnames=True, enable_dns_support=True)

        # Define a Redshift cluster
        my_redshift_cluster = redshift.Cluster(self, id='my-redshift-cluster', master_user=redshift.Login(master_username='username'), vpc=my_vpc, cluster_type=redshift.ClusterType.SINGLE_NODE)

```

### What did you expect to happen?

A successful deployment of a basic 1 node Redshift cluster.

### What actually happened?

Error with deployment.

8:09:58 PM | CREATE_FAILED        | AWS::Redshift::Cluster                      | my-redshift-cluster
Number of nodes must be not be supplied for cluster type single-node. (Service: AmazonRedshift; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 57b21bf4-0b33-4b60-a6c1-4bdada5ed268)

### Environment

  - **CLI Version      :** aws-cdk@1.60.0
  - **Framework Version:** 1.60.0
  - **Node.js Version:** v12.18.3
  - **OS               :** Ubuntu 20.04.1 LTS
  - **Language (Version):** Python 3.8.2

### Suggestion

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html#cfn-redshift-cluster-clustertype

ClusterType

    The type of the cluster. When cluster type is specified as

        single-node, the NumberOfNodes parameter is not required.

        multi-node, the NumberOfNodes parameter is required.

    Valid Values: multi-node | single-node

    Default: multi-node 

NumberOfNodes

    The number of compute nodes in the cluster. This parameter is required when the ClusterType parameter is specified as multi-node.

    For information about determining how many nodes you need, go to Working with Clusters in the Amazon Redshift Cluster Management Guide.

    If you don't specify this parameter, you get a single-node cluster. When requesting a multi-node cluster, you must specify the number of nodes that you want in the cluster. 

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by njlynch**
Single-node clusters defaulted to a `numberOfNodes` of 1; while this makes
sense, CloudFormation actually throws if any number of nodes is defined for a
single-node cluster. This change fixes this to default to `undefined` and
extends the validation for multi-node clusters.

fixes #9856

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-redshift/lib/cluster.ts [hunk 1]
```diff
@@ -537,4 +533,20 @@ export class Cluster extends ClusterBase {
       target: this,
     });
   }
+
+  private validateNodeCount(clusterType: ClusterType, numberOfNodes?: number): number | undefined {
+    if (clusterType === ClusterType.SINGLE_NODE) {
+      // This property must not be set for single-node clusters; be generous and treat a value of 1 node as undefined.
+      if (numberOfNodes !== undefined && numberOfNodes !== 1) {
+        throw new Error('Number of nodes must be not be supplied for cluster type single-node');
```
Comment (eladb) [inline packages/@aws-cdk/aws-redshift/lib/cluster.ts:541]:
```suggestion
        throw new Error('Number of nodes must be not be supplied or be 1 for cluster type single-node');
```

File: packages/@aws-cdk/aws-redshift/lib/cluster.ts [hunk 2]
```diff
@@ -537,4 +533,20 @@ export class Cluster extends ClusterBase {
       target: this,
     });
   }
+
+  private validateNodeCount(clusterType: ClusterType, numberOfNodes?: number): number | undefined {
```
Comment (eladb) [inline packages/@aws-cdk/aws-redshift/lib/cluster.ts:537]: rename to `parseNodeCode` because it returns a value. Usually "validateXxxx" methods return `void`.

**Review by eladb — APPROVED** [review]

**Comment by eladb** [comment]
added do-not-merge label

File: packages/@aws-cdk/aws-redshift/lib/cluster.ts (hunk 2 above)
Comment (njlynch) [reply packages/@aws-cdk/aws-redshift/lib/cluster.ts:537]: `validateXxxx` methods usually return void, and `parseXxxx` methods usually parse something. Neither really fits here IMO. I personally prefer "validate" here as describing more of the "main" intent rather than "parse", which doesn't describe the method at all.

That being said, I see only a few "validate" methods with return types (one of which was also my fault), and lots of "parse" methods that don't actually parse anything, so I guess that's the defined convention at this point. Would something like `validateAndReturnXxx` or `validateOrDefault` or something like that be any better?
