### PR TITLE
fix(codedeploy): LambdaDeploymentGroup now takes IRole

### LINKED ISSUE #1833: codedeploy.LambdaDeploymentGroup role is not "IRole"
In the construction of the LambdaDeploymentGroup, the "role" property is of type "Role" rather than IRole.

https://github.com/awslabs/aws-cdk/blob/488935ce9e2a414c94fbf13fc24c95c9626f7d11/packages/%40aws-cdk/aws-codedeploy/lib/lambda/deployment-group.ts#L79

### PR DESCRIPTION
**Pull request by rix0rrr**
Change the arguments of LambdaDeploymentGroup to take interfaces
wherever possible.

Fixes #1833.

BREAKING CHANGE: If an existing role is provided to a LambdaDeploymentGroup, 
you will need to provide the assuming service principal (`codedeploy.amazonaws.com`) 
yourself.

----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by skinny85** [comment]
cc @sam-goodwin

File: packages/@aws-cdk/aws-codedeploy/lib/lambda/deployment-group.ts [hunk 1]
```diff
@@ -136,24 +136,15 @@ export class LambdaDeploymentGroup extends cdk.Construct implements ILambdaDeplo
     this.application = props.application || new LambdaApplication(this, 'Application');
     this.alarms = props.alarms || [];
 
-    let serviceRole: iam.Role | undefined = props.role;
-    if (serviceRole) {
-      if (serviceRole.assumeRolePolicy) {
-        serviceRole.assumeRolePolicy.addStatement(new iam.PolicyStatement()
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-codedeploy/lib/lambda/deployment-group.ts]: This part of the behavior is not retained by the new code. That constitutes a breaking change.

Either it needs to be restored (if `props.role` is set, then make the role assumable by `code deploy.amazonaws.com`), or the breaking change needs to be mentioned.

Comment (rix0rrr) [reply packages/@aws-cdk/aws-codedeploy/lib/lambda/deployment-group.ts]: You are right.

I removed it because this doesn't match our behavior anywhere else where we do BOYR, but it does constitute a breaking change. And the build is probably failing because there's a test asserting that we DO do this :).
