### PR TITLE
fix(aws-s3-assets): support asset url with two extension name like tar.gz

### LINKED ISSUE #12699: (aws-s3-assets): Object keys don't preserve the full extension name
I'm using aws-s3-assets to upload data artifacts I used for a Sagemaker model. According to the documentation of Sagemaker, the S3 object needs to end with `tar.gz` extension. However, the uploaded asset is renamed to `<random-id>.gz`.

### Reproduction Steps
```
import * as cdk from "@aws-cdk/core";
import * as s3assets from "@aws-cdk/aws-s3-assets";

export class ModelStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);
        const modelArtifactAsset = new s3assets.Asset(this, 'ModelArtifact', {
            path: "artifact.tar.gz"
        });
        new cdk.CfnOutput(this, "modelArtifactS3Url", {
            description: "S3 url to the model artifact.",
            exportName: "modelArtifactS3Url",
            value: modelArtifactAsset.s3ObjectUrl,
        });
    }
}
```
### What did you expect to happen?
I expect the s3 object key is ended with `tar.gz`

### What actually happened?
The generated object is named as `<id>.gz`. Here is an example output from one run:
`s3://<bucket-name>/assets/f43ce33c42b10b3e1fe78d87a46cd0dff8611c37637edcf1857a36c33f302ee5.gz`

### Environment

  - **CDK CLI Version  :**: 1.85.0
  - **Framework Version:**: 1.86.0
  - **Node.js Version:**: v15.2.0
  - **OS               :**  Mac OS X
  - **Language (Version):** Typescript 3.9.7

### Other
A possible fix is to add an optional parameter for customize the extension name of the asset.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by ntachukwu**
using aws-s3-assets to upload data artifacts of extension `tar.gz` returns an uploaded asset renamed to `<random Id>.gz`. 

This PR proposes that the AssetStaging Object should be able to check if the uploaded artifact is a `tar.gz` or any other archive tar file with a compression extension and return the appropriate extension name as stagedPath.

closes #12699

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/core/lib/asset-staging.ts [hunk 1]
```diff
@@ -268,9 +268,19 @@ export class AssetStaging extends Construct {
...
-      ? this.sourcePath
-      : path.resolve(this.assetOutdir, renderAssetFilename(assetHash, path.extname(this.sourcePath)));
+    let stagedPath: string;
+
+    if (this.stagingDisabled) {
+      stagedPath = this.sourcePath;
+    } else {
+      let extensionName: string = path.extname(this.sourcePath);
+      const sourceName: string = path.basename(this.sourcePath).replace(extensionName, '');
+      const doubleArchive = ARCHIVE_EXTENSIONS.includes(path.extname(sourceName)) ? true : false;
```
Comment (kellertk) [inline packages/@aws-cdk/core/lib/asset-staging.ts:278]: `Array.prototype.includes()` already returns `true` or `false`. This ternary construction is unnecessary.

File: packages/@aws-cdk/core/lib/asset-staging.ts [hunk 2]
```diff
@@ -268,9 +268,19 @@ export class AssetStaging extends Construct {
    */
   private stageByCopying(): StagedAsset {
     const assetHash = this.calculateHash(this.hashType);
-    const stagedPath = this.stagingDisabled
-      ? this.sourcePath
-      : path.resolve(this.assetOutdir, renderAssetFilename(assetHash, path.extname(this.sourcePath)));
+    let stagedPath: string;
```
Comment (kellertk) [inline packages/@aws-cdk/core/lib/asset-staging.ts:271]: Is it possible to refactor the implementation without using `let` and without the code becoming too difficult to read? You want to use `const` if at all possible.

**Review by kellertk — CHANGES_REQUESTED** [review]
Instead of overloading `ARCHIVE_EXTENSIONS`, would it be possible to genericize the implementation? So you can use any arbitrary number of extensions on a file an they'd all be preserved.

File: packages/@aws-cdk/core/lib/asset-staging.ts (hunk 2 above)
Comment (Th3nn3ss) [reply packages/@aws-cdk/core/lib/asset-staging.ts:271]: I could create a method that checks for double extensions and returns an extension string? This will replace `path.extname(this.sourcePath)`

**Comment by Th3nn3ss** [comment]
> Instead of overloading `ARCHIVE_EXTENSIONS`, would it be possible to genericize the implementation? So you can use any arbitrary number of extensions on a file an they'd all be preserved.

The idea behind overloading `ARCHIVE_EXTENSIONS` was to prevent invalid extension names as the basename might contain multiple dots e.g `/path/to/artifact/artifact.da.vinci.monalisa.tar.gz` which could be mistaken for extension names. Is this not something to be concerned about?

**Comment by indrora** [comment]
Looks great! I would love to see a unit test or two for the new function just to make sure that it handles some common cases. `path/to/artifact/artifact.da.vinci.monalisa.tar.gz` absolutely deserves a spot in those tests because it's a wonderfully ambiguous one. A file with no extension (for instance `Dockerfile` and `bob`) should return something useful... Verify that. 

A nitpick: one common extension for compressed tar archives is `.tgz` and the typical `.tar` should be in there too for uncompressed tarballs.

**Review by indrora — APPROVED** [review]
