### PR TITLE
fix(efs): support imported subnet

### LINKED ISSUE #33876: aws-efs: FileSystem deployment fails if vpcSubnets are referenced from existing subnets
### Describe the feature

Code 
```
    const efs = new FileSystem(this, 'FileSystem', {
      vpc,
      encrypted: true,
      lifecyclePolicy: LifecyclePolicy.AFTER_7_DAYS,
      vpcSubnets: { subnets: [ Subnet.fromSubnetAttributes(this, subnetId, {subnetId: subnetId, availabilityZone: az}) ] },
      removalPolicy: RemovalPolicy.DESTROY,
    });
```

Error:
```
Error: Resolution error: ID components may not include unresolved tokens: EfsMountTarget-${Token[TOKEN.1221]}.
Object creation stack:
  at Execute again with CDK_DEBUG=true to capture stack traces
    at makeUniqueId (/Users/dev/workspace/github/org/core/node_modules/aws-cdk-lib/core/lib/private/uniqueid.js:1:660)
    at orgStack.allocateLogicalId (/Users/dev/workspace/github/org/core/node_modules/aws-cdk-lib/core/lib/stack.js:1:19234)
    at orgStack.getLogicalId (/Users/dev/workspace/github/org/core/node_modules/aws-cdk-lib/core/lib/stack.js:1:8662)
    at CfnMountTarget.synthesizeLogicalId (/Users/dev/workspace/github/org/core/node_modules/aws-cdk-lib/core/lib/cfn-element.js:2:687)
    at Object.produce (/Users/dev/workspace/github/org/core/node_modules/aws-cdk-lib/core/lib/cfn-element.js:1:915)
    at LazyString.resolve (/Users/dev/workspace/github/org/core/node_modules/aws-cdk-lib/core/lib/lazy.js:1:4176)
    at RememberingTokenResolver.resolveToken (/Users/dev/workspace/github/org/core/node_modules/aws-cdk-lib/core/lib/resolvable.js:1:1401)
    at RememberingTokenResolver.resolveToken (/Users/dev/workspace/github/org/core/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:4116)
    at resolve (/Users/dev/workspace/github/org/core/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2747)
    at Object.resolve (/Users/dev/workspace/github/org/core/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:1115)```

Related: https://github.com/aws/aws-cdk/pull/26155 where I see it uses `EfsMountTarget-${subnet.node.id}` as the stack ID of mount target

### Use Case

Create FileSystem with subnets from references

### CDK version used

2.185.0

### Environment details (OS name and version, etc.)

macOS Sequoia 15.3.2

### PR DESCRIPTION
**Pull request by phuhung273**
### Issue # (if applicable)

Closes #33876

### Description of changes
LogicalId generation cover unresolved token case.

### Description of how you validated changes
Unit + Integ

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-efs/lib/efs-file-system.ts [hunk 1]
```diff
@@ -860,11 +860,14 @@ export class FileSystem extends FileSystemBase {
 
     // we explicitly use FeatureFlags to maintain backwards compatibility
     const useMountTargetOrderInsensitiveLogicalID = FeatureFlags.of(this).isEnabled(cxapi.EFS_MOUNTTARGET_ORDERINSENSITIVE_LOGICAL_ID);
+    const useMountTargetImportedSubnetAwareLogicalID = FeatureFlags.of(this).isEnabled(cxapi.EFS_MOUNTTARGET_IMPORTED_SUBNET_AWARE_LOGICAL_ID);
+
     this.mountTargetsAvailable = [];
-    if (useMountTargetOrderInsensitiveLogicalID) {
+    if (useMountTargetOrderInsensitiveLogicalID || useMountTargetImportedSubnetAwareLogicalID) {
```
Comment (shikha372) [inline packages/aws-cdk-lib/aws-efs/lib/efs-file-system.ts:866]: Can’t we handle this specifically for unresolved token values? For example, we could check if subnet.node.id is an unresolved token — if it is, we replace it with a unique ID; otherwise, we leave it as is. From what I see, the current implementation likely doesn't work correctly when the value is unresolved. This check should allow us to conditionally update the value. Let me know if you can think of any scenarios where it would work with token values — in that case, we might need to introduce a feature flag.

Comment (phuhung273) [reply packages/aws-cdk-lib/aws-efs/lib/efs-file-system.ts]: Thank you for your guidance, i should have done that in the 1st place. This logic is updated as suggested, please have a check.

Comment (shikha372) [reply packages/aws-cdk-lib/aws-efs/lib/efs-file-system.ts]: Thank you @phuhung273 , looking at this again, i can think of one more use case for this scenario, where you're referring to the subnet ID of an existing VPC and not an imported subnet, something like

const vpc = new ec2.Vpc(stack, 'Vpc', {
  natGateways: 1,
  restrictDefaultSecurityGroup: false,
  subnetConfiguration: [
    {
      name: 'test',
      subnetType: ec2.SubnetType.PUBLIC,
    },
  ],
});

new FileSystem(stack, 'FileSystem', {
  vpc,
  vpcSubnets: {
    subnets: Subnet.byIds(vpc.publicSubnets[0].node.id),
  },
  removalPolicy: RemovalPolicy.DESTROY,
});
want to make sure that we don't change this mistakenly for any case of non-imported subnets

Comment (phuhung273) [reply packages/aws-cdk-lib/aws-efs/lib/efs-file-system.ts]: Sorry this took a while as I had no idea how to validate all cases, but here are what I found:

### For the case that you're referring to
Can confirm that `subnet.node.id` is not a token, therefore still keep old logic.
Screenshot 2025-04-26 065958

### Checking ec2.Vpc constructor
All subnets created by constructor are given a non-token id, following pattern `Subnet1, Subnet2, Subnet3`, matching with the behaviour of above case
https://github.com/aws/aws-cdk/blob/7f378b6ee87a9ad89772d3cdd77c89d6a9ab8209/packages/aws-cdk-lib/aws-ec2/lib/vpc.ts#L1761
https://github.com/aws/aws-cdk/blob/7f378b6ee87a9ad89772d3cdd77c89d6a9ab8209/packages/aws-cdk-lib/aws-ec2/lib/util.ts#L42-L44

### Most important point
If there is any case that we haven't covered, and it is a token, then it doesn't even work from the first place, yelling the same error as the originated issue.

Your amazing suggestion to use `Token.isUnresolved` ensures we only cover those cases that never work. I think it's totally safe. Let me know if you can think of any other cases.

Comment (shikha372) [reply packages/aws-cdk-lib/aws-efs/lib/efs-file-system.ts]: Awesome, thank you @phuhung273
