### PR TITLE
fix(codebuild): API cleanup

### LINKED ISSUE #2037: Move CodeBuild Sources & Artifacts to a separate package
According to what we agreed to in #1743, we need to move CodeBuild's Sources and Artifacts to a separate package.

We should also make a decision whether we should have 2 new packages: one for Sources, one for Artifacts, or should we put both Sources and Artifacts in one new package.

### PR DESCRIPTION
**Pull request by skinny85**
Change the names of the source classes to be more consistent with other integrations. Make the abstract Source classes package-private. Add static factory methods to Source.

Change the names of artifacts classes to be more consistent with other integrations. Add static factory methods to Artifacts.

Make CodePipelineSource, CodePipelineArtifacts, NoSource, and NoArtifacts package-private.

Get rid of the SourceType enum.

BREAKING CHANGE:
* codebuild: rename BuildSource to Source, S3BucketSource to S3Source, BuildArtifacts to Artifacts, S3BucketBuildArtifacts to S3Artifacts
* codebuild: the classes CodePipelineBuildSource, CodePipelineBuildArtifacts, NoBuildSource, and NoBuildArtifacts have been removed
* codebuild: rename buildScriptAsset and buildScriptAssetEntrypoint to buildScript and buildScriptEntrypoint, respectively

----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
  - __Design__: For significant features, design document added to `design` folder
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-codebuild-artifacts/lib/artifacts.ts [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+  protected readonly type = 'S3';
+
+  constructor(private readonly props: S3BucketBuildArtifactsProps) {
+    super(props);
+  }
+
+  /**
+   * @internal
+   */
+  public _bind(project: codebuild.Project) {
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-codebuild-artifacts/lib/artifacts.ts]: Since we're touching this anyway... the `bind()` pattern changed a little:

* We implement an interface `IBuildArtifact`.
* `bind` has signature `bind(scope: Construct, project: codebuild.IProject): BuildArtifactConfig`.
  * Project interface, not class.
  * `toArtifactsProperty()` can be removed, it becomes the output of `bind()`.
* Doesn't have to be `@internal` anymore.

**Comment by rix0rrr** [comment]
Also, I would be fine with names a la `S3Source`, `S3Artifacts`. 

In effect, service + integration type. This is what we've been settling on for *most* of the integration classes (except the SFN tasks one, where it's an action verb, `WriteToS3` or similar).

File: packages/@aws-cdk/aws-codebuild-artifacts/lib/artifacts.ts [hunk 2]
```diff
@@ -0,0 +1,84 @@
+import codebuild = require("@aws-cdk/aws-codebuild");
+import s3 = require("@aws-cdk/aws-s3");
+
+/**
+ * CodePipeline Artifact definition for a CodeBuild Project.
+ * *Note*: this type cannot be used as a secondary artifact,
+ * and because of that, you're not allowed to specify an identifier for it.
+ */
+export class CodePipelineBuildArtifacts extends codebuild.BuildArtifacts {
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild-artifacts/lib/artifacts.ts]: omit the words "build" and "artifacts" if they already exist in the package name. The package name/namespace is part of the name of the class. That's why it's @aws-cdk/aws-lambda.Function and not LambdaFunction.

Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild-artifacts/lib/artifacts.ts]: How does that work if you want Artifacts to be merged into `@aws-cdk/aws-codebuild-sources`? `codebuild_sources.CodePipeline???`?

Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild-artifacts/lib/artifacts.ts]: Also, that's not consistent with how we name other integrations, for example `codepipeline_actions.GitHubSource**Action**`.

**Comment by skinny85** [comment]
> +1 on merging artifacts into -sources (or leaving in @aws-cdk/codebuild).

Just so I understand - for the second option, are you saying to leave just Artifacts in `@aws-cdk/aws-codebuild`, but still extract Sources into `@aws-cdk/aws-codebuild-sources`, or are you saying that you'd rather leave **both** Sources and Artifacts in `@aws-cdk/aws-codebuild`?

File: packages/@aws-cdk/aws-codebuild-artifacts/lib/artifacts.ts (hunk 2 above)
Comment (eladb) [reply packages/@aws-cdk/aws-codebuild-artifacts/lib/artifacts.ts]: In the API reviews, we actually just said we wanted to remove the "Action" postfix from codepipeline_actions

Comment (eladb) [reply packages/@aws-cdk/aws-codebuild-artifacts/lib/artifacts.ts]: Let's just leave sources in the codebuild module...

**Comment by eladb** [comment]
+1 for leaving sources in codebuild

**Comment by skinny85** [comment]
Any justification why do we want to make CodeBuild inconsistent with our other integration packages?

**Comment by eladb** [comment]
Are you asking about the sources? It seems to be codebuild sources are not really “integrations”, but if you feel strongly about it, I don’t have a strong opinion.

**Comment by skinny85** [comment]
Whatever then.

Let's change this PR to finalize the names, in that case (and do small cleanups, like removing the `SourceType` enum, making the intermediate Source classes package-private, etc.).

Currently, the names are:

* Sources:
  - `BuildSource`
  - `NoSource`
  - `S3BucketSource`
  - `CodePipelineSource`
  - `CodeCommitSource`
  - `GitHubSource`
  - `GitHubEnterpriseSource`
  - `BitBucketSource`
* Artifacts:
 - `BuildArtifacts`
  - `NoBuildArtifacts`
  - `S3BucketBuildArtifacts`
  - `CodePipelineBuildArtifacts`

I'm thinking of removing the `Build` prefix, so leaving it just as `Source` / `Artifacts`. So:

* Sources:
  - `Source`
  - `S3Source`
  - `CodePipelineSource`
  - `CodeCommitSource`
  - `GitHubSource`
  - `GitHubEnterpriseSource`
  - `BitBucketSource`
* Artifacts:
 - `Artifacts`
  - `S3Artifacts`
  - `CodePipelineArtifacts`

I think I would also like to get rid of the `NoSource` / `NoArtifacts` classes (make them package-private). I don't see a reason why would a customer ever want to use them.

**Comment by eladb** [comment]
Names look good. Not sure why you think NoSource and NoArtifacts are not useful. It’s actually a very common use case in the CDK’s ops app (all our canaries are codebuild projects without a source)

**Comment by skinny85** [comment]
Because `NoSource` / `NoArtifacts` is the default.

**Comment by eladb** [comment]
got it. Yeah I guess as long as users can use these features I guess you can hide those.

**Comment by skinny85** [comment]
I've re-purposed the PR for general changes in the CodeBuild modules (see description).

File: packages/@aws-cdk/aws-codebuild-artifacts/lib/artifacts.ts (hunk 1 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild-artifacts/lib/artifacts.ts]: Done, for both `Artifacts` and `Source`.

**Comment by skinny85** [comment]
Please re-review when you have a chance @eladb @rix0rrr .

File: packages/@aws-cdk/aws-codebuild/README.md [hunk 3]
```diff
@@ -81,18 +77,17 @@ import s3 = require('@aws-cdk/aws-s3');
 
 const bucket = new s3.Bucket(this, 'MyBucket');
 new codebuild.Project(this, 'MyProject', {
-  source: new codebuild.S3BucketSource({
+  source: new codebuild.S3Source({
     bucket: bucket,
     path: 'path/to/file.zip',
   }),
 });
+// or: codebuild.Source.s3({
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild/README.md]: Let's recommend the union-like approach instead of the free-floating classes. I would even argue that the classes should be internal. Not sure there is value in exposing them at all.

File: packages/@aws-cdk/aws-codebuild/README.md [hunk 4]
```diff
@@ -231,7 +244,7 @@ const project = new codebuild.Project(this, 'MyProject', {
     }),
   ],
   secondaryArtifacts: [
-    new codebuild.S3BucketBuildArtifacts({
+    new codebuild.S3Artifacts({
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild/README.md]: Do we want union-like for `codebuild.Artifacts` as well (e.g. `codebuild.Artifacts.s3(...)`)

File: packages/@aws-cdk/aws-codebuild/lib/artifacts.ts [hunk 5]
```diff
@@ -1,11 +1,27 @@
...
+
+/**
+ * The type returned from {@link IArtifacts#bind}.
+ */
+export interface ArtifactsConfig {
+  readonly artifactsProperty: CfnProject.ArtifactsProperty;
+}
+
+export interface IArtifacts {
+  readonly identifier?: string;
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild/lib/artifacts.ts]: why is identifier needed?

File: packages/@aws-cdk/aws-codebuild/lib/artifacts.ts [hunk 6]
```diff
@@ -1,11 +1,27 @@
...
+import { IProject } from './project';
+
+/**
+ * The type returned from {@link IArtifacts#bind}.
+ */
+export interface ArtifactsConfig {
+  readonly artifactsProperty: CfnProject.ArtifactsProperty;
+}
+
+export interface IArtifacts {
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild/lib/artifacts.ts]: missing docstrings

File: packages/@aws-cdk/aws-codebuild/lib/artifacts.ts [hunk 7]
```diff
@@ -1,11 +1,27 @@
...
+import { Construct } from '@aws-cdk/cdk';
 import { CfnProject } from './codebuild.generated';
-import { Project } from './project';
+import { IProject } from './project';
+
+/**
+ * The type returned from {@link IArtifacts#bind}.
+ */
+export interface ArtifactsConfig {
+  readonly artifactsProperty: CfnProject.ArtifactsProperty;
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild/lib/artifacts.ts]: missing docstrings

File: packages/@aws-cdk/aws-codebuild/lib/codepipeline-artifacts.ts [hunk 8]
```diff
@@ -0,0 +1,14 @@
+import { Artifacts } from './artifacts';
+
+/**
+ * CodePipeline Artifact definition for a CodeBuild Project.
+ * *Note*: this type cannot be used as a secondary artifact,
+ * and because of that, you're not allowed to specify an identifier for it.
+ */
+export class CodePipelineArtifacts extends Artifacts {
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild/lib/codepipeline-artifacts.ts]: should be on the `Artifacts` union-like, and probably internal

File: packages/@aws-cdk/aws-codebuild/lib/codepipeline-source.ts [hunk 9]
```diff
@@ -0,0 +1,15 @@
+import { Source } from './source';
+import { CODEPIPELINE_SOURCE_ARTIFACTS_TYPE } from './source-types';
+
+/**
+ * CodePipeline Source definition for a CodeBuild Project.
+ * *Note*: this type cannot be used as a secondary source,
+ * and because of that, you're not allowed to specify an identifier for it.
+ */
+export class CodePipelineSource extends Source {
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild/lib/codepipeline-source.ts]: Ditto, should be accessible through `codebuild.Source.codePipeline()` and internal

File: packages/@aws-cdk/aws-codebuild/lib/project.ts [hunk 10]
```diff
@@ -385,14 +418,14 @@ export interface CommonProjectProps {
    *
    * @default - No asset build script.
    */
-  readonly buildScriptAsset?: assets.Asset;
+  readonly buildScript?: assets.ZipDirectoryAsset;
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild/lib/project.ts]: I realized something: this is basically `codebuild.Source.asset(directory)`. No need for a special prop.

File: packages/@aws-cdk/aws-codebuild/lib/project.ts [hunk 11]
```diff
@@ -385,14 +418,14 @@ export interface CommonProjectProps {
...
 
   /**
    * The script in the asset to run.
    *
    * @default build.sh
    */
-  readonly buildScriptAssetEntrypoint?: string;
+  readonly buildScriptEntrypoint?: string;
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild/lib/project.ts]: Not needed. Let's just support an asset source type and let users specify buildSpec.

We can create a subclass of `Project` like `ScriptProject` if we want a higher level abstraction to just run a script from an asset.

File: packages/@aws-cdk/aws-codebuild/lib/source.ts [hunk 12]
```diff
@@ -18,67 +49,54 @@ export interface BuildSourceProps {
...
+  public static gitHub(props: GitHubSourceProps): GitHubSource {
+    return new GitHubSource(props);
+  }
+
+  public static gitHubEnterprise(props: GitHubEnterpriseSourceProps): GitHubEnterpriseSource {
+    return new GitHubEnterpriseSource(props);
+  }
+
+  public static bitBucket(props: BitBucketSourceProps): BitBucketSource {
+    return new BitBucketSource(props);
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild/lib/source.ts]: Nice... Let's make all the classes internal

File: packages/@aws-cdk/aws-codebuild/README.md (hunk 3 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/README.md]: Done.

File: packages/@aws-cdk/aws-codebuild/README.md (hunk 4 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/README.md]: We already have it.

File: packages/@aws-cdk/aws-codebuild/lib/artifacts.ts (hunk 5 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/artifacts.ts]: It's used for naming your sources/artifacts, and is required when using secondary sources/artifacts.

File: packages/@aws-cdk/aws-codebuild/lib/artifacts.ts (hunk 6 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/artifacts.ts]: Added.

File: packages/@aws-cdk/aws-codebuild/lib/artifacts.ts (hunk 7 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/artifacts.ts]: Added.

File: packages/@aws-cdk/aws-codebuild/lib/codepipeline-artifacts.ts (hunk 8 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/codepipeline-artifacts.ts]: This class is actually private to this package, so I don't want to expose it on `Artifacts` at all.

File: packages/@aws-cdk/aws-codebuild/lib/codepipeline-source.ts (hunk 9 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/codepipeline-source.ts]: Same as above - this Source type is actually private to the CodeBuild package, and not available to customers at all.

File: packages/@aws-cdk/aws-codebuild/lib/project.ts (hunk 10 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: What....? I don't understand what this means.... What's the type of the source in the case it's `Source.asset(directory)`?

File: packages/@aws-cdk/aws-codebuild/lib/project.ts (hunk 11 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: See above - I don't understand what you mean by this comment.

File: packages/@aws-cdk/aws-codebuild/lib/source.ts (hunk 12 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/source.ts]: Done.

**Comment by skinny85** [comment]
Changes taking into account the comments from the previous revision.

File: packages/@aws-cdk/aws-codebuild/lib/project.ts (hunk 10 above)
Comment (eladb) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: The underlying source type will be S3. Basically the asset will be copied by the CDK to an S3 location and the CodeBuild project will use this location as the source for the build. Magic! 🥇

Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: That's a completely different feature though, right? I mean, this is not at all how this feature works now (right now, there is no source in the resulting CodeBuild Project, and the file is downloaded from S3 during build, unzipped, and then the entrypoint is executed).

Does this fall under API cleanup then...? Perhaps I should remove these 2 attributes from Project, and come back to this?

Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: Also, what's the relationship between `Source.asset(directory)`, and `buildpsec` in that world?

Comment (eladb) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: Let’s remove this feature and add it later. You are right.

Comment (eladb) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: Issue?

Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: Removed.

Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/project.ts]: Issue: https://github.com/awslabs/aws-cdk/issues/2897

**Comment by skinny85** [comment]
Latest batch of changes.

File: packages/@aws-cdk/aws-codebuild/README.md [hunk 13]
```diff
@@ -324,7 +331,7 @@ const securityGroup = new ec2.SecurityGroup(stack, 'SecurityGroup1', {
     vpc: vpc,
 });
 new Project(stack, 'MyProject', {
-    buildScriptAsset: new assets.ZipDirectoryAsset(stack, 'Bundle', { path: 'script_bundle' }),
+    buildScript: new assets.ZipDirectoryAsset(stack, 'Bundle', { path: 'script_bundle' }),
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild/README.md]: Didn't we remove this feature?

File: packages/@aws-cdk/aws-codebuild/lib/codepipeline-artifacts.ts (hunk 8 above)
Comment (eladb) [reply packages/@aws-cdk/aws-codebuild/lib/codepipeline-artifacts.ts]: In the future, we said that we will prefix file names of non-exported types with an underscore to indicate they are private.

File: packages/@aws-cdk/aws-codebuild/lib/codepipeline-source.ts (hunk 9 above)
Comment (eladb) [reply packages/@aws-cdk/aws-codebuild/lib/codepipeline-source.ts]: Not sure I understand... Do we only allow people to use the high level `PipelineProject` in order to set up a codebuild into a pipeline. Doesn't sound right. I don't see a problem exposing `Source.codePipeline` (and TBH, `Source.none` as well...

File: packages/@aws-cdk/aws-codebuild/README.md (hunk 13 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/README.md]: Fix backported to #2662.
