### PR TITLE
fix(cli): cdk synth doesn't output yaml for stacks with dependency stacks

### LINKED ISSUE #3721: cli: cdk synth doesn't output yaml when having dependency stacks
## :question: General Issue

I have a `LambdaStack` depending on `NetworkStack`'s vpc. There is the code
#### LambdaStack
```typescript
import cdk = require('@aws-cdk/core');
import lambda = require('@aws-cdk/aws-lambda');
import iam = require('@aws-cdk/aws-iam');
import vpc = require('@aws-cdk/aws-ec2')

interface LambdaStackProps extends cdk.StackProps {
  vpc: vpc.Vpc
}

export class LambdaStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: LambdaStackProps) {
    super(scope, id, props);
    // define lambdas by using props.vpc
  }
}
```

#### NetworkStack
```typescript
import cdk = require('@aws-cdk/core');
import ec2 = require("@aws-cdk/aws-ec2");
import iam = require("@aws-cdk/aws-iam");


interface NetworkStackProps extends cdk.StackProps { }

export class NetworkStack extends cdk.Stack {
  public readonly vpc: ec2.Vpc;
  constructor(scope: cdk.Construct, id: string, prop: NetworkStackProps) {
    super(scope, id, prop);
    this.vpc = new ec2.Vpc(some code here);
  }
}
```
#### app
```typescript
const networkStack = new NetworkStack(app, 'network-stack-dev', { env: UsEast1Env });
const lambdaStack = new LambdaStack(app, 'lambda-stack-dev', { 
  env: UsEast1Env,
  vpc: networkStack.vpc
});
```

I tried to generate yaml file for `LambdaStack` by executing
```bash
cdk synth lambda-stack-dev > template.yaml
```
Then I got
```bash
Including dependency stacks: network-stack-dev
Successfully synthesized to /Users/whao/Developer/serverless-dev/cdk.out
Supply a stack name (network-stack-dev, lambda-stack-dev) to display its template.
```
I tried `cdk synth network-stack-dev lambda-stack-dev` but it gave the same output. I am kinda confused with what `Supply a stack name (network-stack-dev, lambda-stack-dev) to display its template.` means

I have read issue #3259 but I didn't find it helpful.
Forgive me if I am asking stupid questions.

### Environment

  - **CDK CLI Version:** 1.4.0 (build 175471f)
  - **Module Version:** N/A
  - **OS:** macOS 10.14.6
  - **Language:** TypeScript

### PR DESCRIPTION
**Pull request by madeline-k**
fixes #3721

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk/lib/cdk-toolkit.ts [hunk 1]
```diff
@@ -296,7 +296,10 @@ export class CdkToolkit {
    * OUTPUT: If more than one stack ends up being selected, an output directory
    * should be supplied, where the templates will be written.
    */
-  public async synth(stackNames: string[], exclusively: boolean, quiet: boolean): Promise<any> {
+  public async synth(stackNames: string[], exclusively?: boolean, quiet?: boolean): Promise<any> {
```
Comment (madeline-k) [inline packages/aws-cdk/lib/cdk-toolkit.ts:299]: I made `exclusively` and `quiet` optional so that I could pass in `undefined` in the new unit test to replicate the default behavior when the user does not specify those parameters. Definitely open to ideas for better ways to imitate that scenario.

Comment (rix0rrr) [reply packages/aws-cdk/lib/cdk-toolkit.ts:299]: I think I'd prefer to have made this change in `cdk.ts` where the command line arguments get parsed and then passed to this function.

Is there a reason you decided to do it here instead of there?

File: packages/aws-cdk/test/cdk-toolkit.test.ts [hunk 2]
```diff
@@ -231,12 +231,25 @@ describe('synth', () => {
...
+
+    await expect(toolkit.synth([MockStack.MOCK_STACK_D.stackName], undefined)).resolves.toBeDefined();
+  });
 });
 
 class MockStack {
   public static readonly MOCK_STACK_A: TestStackArtifact = {
     stackName: 'Test-Stack-A',
-    template: { Resources: { TempalteName: 'Test-Stack-A' } },
+    template: { Resources: { TemplateName: 'Test-Stack-A' } },
```
Comment (rix0rrr) [inline packages/aws-cdk/test/cdk-toolkit.test.ts:252]: Ha! Good catch 😅

**Review by rix0rrr — CHANGES_REQUESTED** [review]
Consider making the change in `cdk.ts` ?

**Review by rix0rrr — APPROVED** [review]
