### PR TITLE
fix(autoscaling): cooldown cannot be set with step scaling actions

### LINKED ISSUE #29779: aws-autoscaling: Step scaling properties expose unsupported `cooldown` property
### Describe the bug

The [`StepScalingPolicyProps` interface](https://github.com/aws/aws-cdk/blob/a7b4e2953c09ef59d25ec409b879d12a894318ab/packages/aws-cdk-lib/aws-autoscaling/lib/step-scaling-policy.ts#L35) and related `StepScalingActionProps` interface expose a `cooldown` property, which if specified becomes the `cooldown` property of a `CfnScalingPolicy` here:

https://github.com/aws/aws-cdk/blob/a7b4e2953c09ef59d25ec409b879d12a894318ab/packages/aws-cdk-lib/aws-autoscaling/lib/step-scaling-action.ts#L77

However, `cooldown` is not a supported property for step scaling policies. The documentation for the `AWS::AutoScaling::ScalingPolicy` resource [says](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-autoscaling-scalingpolicy.html#cfn-autoscaling-scalingpolicy-cooldown):
> Valid only if the policy type is `SimpleScaling`. For more information, see [Scaling cooldowns for Amazon EC2 Auto Scaling](https://docs.aws.amazon.com/autoscaling/ec2/userguide/Cooldown.html) in the Amazon EC2 Auto Scaling User Guide.

Specifying this property has no effect and can cause CloudFormation deployment errors in some regions (such as ap-southeast-4).

### Expected Behavior

Since this property has no effect and can cause deployment errors, it should not be possible to specify for step scaling policies and should be deprecated.

### Current Behavior

The property can be specified and results in an `AWS::AutoScaling::ScalingPolicy` with `PolicyType` set to `StepScaling` and the `Cooldown` property present. This is ineffectual or can cause the following error on deployment, depending on the region:

```plain
Property Cooldown cannot be specified.
```

### Reproduction Steps

The following application reproduces the deployment error when deployed to ap-southeast-4.

```typescript
import { App, Duration, Stack, StackProps } from 'aws-cdk-lib';
import { AutoScalingGroup, } from 'aws-cdk-lib/aws-autoscaling';
import { AmazonLinuxCpuType, InstanceClass, InstanceSize, InstanceType, MachineImage, Vpc } from 'aws-cdk-lib/aws-ec2';
import { Construct } from 'constructs';
import { Metric } from 'aws-cdk-lib/aws-cloudwatch';

export class ReproStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const vpc = new Vpc(this, "VPC");
    const asg = new AutoScalingGroup(this, "ASG", {
      vpc,
      machineImage: MachineImage.latestAmazonLinux2023({ cpuType: AmazonLinuxCpuType.ARM_64 }),
      instanceType: InstanceType.of(InstanceClass.T4G, InstanceSize.MICRO),
    });

    const metric = new Metric({
      namespace: "Repro",
      metricName: "Metric",
    });

    asg.scaleOnMetric("MetricScale", {
      metric,
      scalingSteps: [
        { upper: 10, change: -5 },
        { lower: 50, change: 5 }
      ],
      cooldown: Duration.minutes(5),
    })
  }
}

const app = new App();
new ReproStack(app, "Repro");
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.136.1

### Framework Version

_No response_

### Node.js Version

v18.0.0

### OS

macOS

### Language

TypeScript

### Language Version

5.4.3

### Other information

(Amazon ticket D120666119 has some more detail.)

### PR DESCRIPTION
**Pull request by GavinZZ**
### Issue # (if applicable)

Closes #29779 

### Reason for this change

`cooldown` cannot be set on step scaling and can cause deployment failure in certain regions.

### Description of changes

Deprecate the property and ignore the value. Give a warning.

### Description of how you validated changes

Unit test added.

### Checklist
- [ ] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-autoscaling/lib/step-scaling-action.ts [hunk 1]
```diff
@@ -71,10 +72,16 @@ export class StepScalingAction extends Construct {
   constructor(scope: Construct, id: string, props: StepScalingActionProps) {
     super(scope, id);
 
+    // Specify cooldown property in StepScaling policy type is ineffective and may cause deployment failure
+    // in certain regions. We can't simply remove the property since it break existing users. Since setting
+    // this value is ineffective, we can safely ignore the value of this property with a warning.
+    if (props.cooldown && props.cooldown.toSeconds().toString()) {
```
Comment (aaythapa) [inline packages/aws-cdk-lib/aws-autoscaling/lib/step-scaling-action.ts:78]: Do we have to check for `props.cooldown.toSeconds().toString()` here? Should `props.cooldown` be enough?

**Review by aaythapa — APPROVED** [review]
