### PR TITLE
fix(opensearchservice): use KMS Key ARN for cross-account encryption

### LINKED ISSUE #36017: (aws-opensearchservice): Domain construct should use KMS Key ARN instead of KeyId for cross-account reference
### Describe the bug

Unable to use a KMS key from another AWS account when creating an OpenSearch Domain.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Library Version

_No response_

### Expected Behavior

```ts
const remoteKey = kms.Key.fromKeyArn(this, 'RemoteEncryptionKey', "arn:aws:kms:us-east-1:<different-account-id>:key/xxxx");

const domain = new Domain(this, 'Domain', {
  /*... Other settings ... */
  encryptionAtRest: {
    enabled: true,
    kmsKey: remoteKey,
  },
})
```

When used with a cross-account KMS Key reference, should create an opensearch domain using the specified KMS Key Arn.

### Current Behavior

Results in an error:

```
Invalid request provided: Error in Accessing KmsKeyID with details:Key 'arn:aws:kms:us-east-1:<current-account-id>:key/xxxx' does not exist (Service: AWSKMS; Status Code: 400; Error Code: NotFoundException; Request ID: xxx; Proxy: null) (Service: OpenSearch, Status Code: 400, Request ID: xxx) (SDK Attempt Count: 1)" (RequestToken: xxx, HandlerErrorCode: InvalidRequest)
```

### Reproduction Steps

1. Create a KMS key in a AWS account A with appropriate grants to be used by AWS account B.
2. Create Opensearch domain in CDK code as specified above using the ARN of the KMS key in account A.
3. Deploy the CDK code to account B

### Possible Solution

The current code in https://github.com/aws/aws-cdk/blob/v2.223.0/packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts#L1991 passes the KMS Key Id to the underlying constructs instead of the ARN.  It should use the Key ARN instead when available.

As a workaround, I am using the following code to bypass the issue:

```ts
const remoteKey = kms.Key.fromKeyArn(this, 'RemoteEncryptionKey', "arn:aws:kms:us-east-1:<different-account-id>:key/xxxx");
const domain = new Domain(this, 'Domain', {
  /*... Other settings ... */
  encryptionAtRest: {
    enabled: true,
    kmsKey:
      remoteKey &&
      ({
        keyRef: { keyArn: remoteKey.keyArn, keyId: remoteKey.keyArn },
      } as kms.IKeyRef),
  },
})
```
This works and creates the domain successfully using the correct key, suggesting that the code should be updated to use the ARN if available rather than the Key Id.

### Additional Information/Context

_No response_

### AWS CDK Library version (aws-cdk-lib)

2.219.0

### AWS CDK CLI version

2.1029.4 (build 09c0061)

### Node.js Version

20

### OS

linux

### Language

TypeScript

### Language Version

5.9.3

### Other information

_No response_

### PR DESCRIPTION
**Pull request by pahud**
### Issue # (if applicable)

Closes #36017.

### Reason for this change

OpenSearch Domain construct fails when using cross-account KMS keys for encryption at rest. The construct currently uses KMS Key ID (`keyRef.keyId`) which doesn't work for cross-account scenarios - OpenSearch requires the full ARN to properly identify and access keys from different accounts.

This blocks users from implementing cross-account encryption patterns, which are common in enterprise multi-account architectures.

### Description of changes

Added intelligent KMS key identifier selection logic that chooses between Key ID and Key ARN based on the key's account and region:

- **Cross-account keys**: Uses full ARN (enables previously broken scenarios)
- **Cross-region keys**: Uses full ARN (additional support)
- **Same-account, same-region keys**: Uses Key ID (maintains backward compatibility)

Implementation details:
- Added `selectKmsKeyIdentifier()` private method to Domain class
- Uses `Stack.of()` and `Token.isUnresolved()` for account/region comparison
- Properly handles unresolved tokens (deploy-time values)
- Modified line 1991 in `domain.ts` to use the new selection logic

This follows the same pattern used in the DynamoDB construct for encryption key handling.

### Why not always use ARN?

While CDK's versioning policy states that CloudFormation template changes are acceptable if intent is preserved, **changing `KmsKeyId` from Key ID to ARN format causes CloudFormation to replace the OpenSearch domain**, resulting in data loss.

We verified this behavior with a live deployment test:

```
# CloudFormation event log when changing KmsKeyId from keyId to keyArn:

ResourceStatusReason: "Requested update requires the creation of a new 
physical resource; hence creating one."

# Domain was REPLACED:
- Old domain: domain-xydpwjq5pbn0 → DELETE_COMPLETE
- New domain: domain-mmhf4ngxjkuz → UPDATE_COMPLETE
```

This is because CloudFormation's `AWS::OpenSearchService::Domain` resource treats `KmsKeyId` changes as requiring replacement (per [CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-properties-opensearchservice-domain-encryptionatrestoptions.html): "if you change this property after it's already been set within a template, the domain is deleted and recreated").

Therefore, we intentionally preserve the existing Key ID format for same-account, same-region keys to prevent unexpected domain replacement and data loss for existing users.

### Describe any new or updated permissions being added

N/A - No new IAM permissions required. This change only affects how the KMS key identifier is passed to CloudFormation.

### Description of how you validated changes

- **Unit tests**: Added 3 comprehensive test cases:
  1. Same-account KMS key usage (validates backward compatibility - uses Key ID)
  2. Cross-account KMS key usage (validates bug fix - uses ARN)
  3. Cross-region KMS key usage (validates edge case - uses ARN)
  
- **Integration tests**: All 18 OpenSearch integration tests passed with UNCHANGED snapshots, confirming no breaking changes to existing scenarios

- **Test results**: 1,709/1,709 unit tests passed (100% pass rate)

- **Backward compatibility**: Verified via UNCHANGED integration test snapshots - existing same-account scenarios continue to use Key ID format

- **Live deployment test**: Confirmed that changing `KmsKeyId` from Key ID to ARN format triggers CloudFormation domain replacement (see "Why not always use ARN?" section above)

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by pahud** [comment]
Exemption Request - we have unit tests covered.

File: packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts [hunk 1]
```diff
@@ -2197,6 +2197,42 @@ export class Domain extends DomainBase implements IDomain, ec2.IConnectable {
...
+                          keyAccount !== stackAccount;
+    const isCrossRegion = !cdk.Token.isUnresolved(keyRegion) &&
+                         !cdk.Token.isUnresolved(stackRegion) &&
+                         keyRegion !== stackRegion;
+
+    if (isCrossAccount || isCrossRegion) {
+      return key.keyRef.keyArn;
+    }
+
+    // For same-account, same-region keys, use keyId (maintains backward compatibility)
```
Comment (gasolima) [inline packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts:2260]: What do you mean here by backward compatibility? This kind of change yes will change the CF template, but will not change anything in the behaviour. We never promised customers that we will keep the CF template same forever, but we promised them to have the same intent.

[Reference](https://docs.aws.amazon.com/cdk/v2/guide/versioning.html#aws-construct-lib-semver) for what i'm saying

> Features are described by intent
We aim to minimize unexpected changes, but will favor intent over implementation stability. The AWS Construct Library does not guarantee that constructs always synthesize to the exact same CloudFormation template or use the exact same set of resources. This especially applies to higher-level constructs, where the same goal can often be achieved in different ways.


If u agree with what i'm saying then this PR can be way more simplified

**Review by gasolima — CHANGES_REQUESTED** [review]

File: packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts (hunk 1 above)
Comment (pahud) [reply packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts:2260]: If we make everyone using KeyArn then existing  deployed clusters using KeyID will be subject to replacement  and lose all data. That's why we don't want to make template change for existing deployed clusters.

image


wdyt?

Comment (pahud) [reply packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts:2260]: Let me have a quick experiment and get back here.

Comment (pahud) [reply packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts:2260]:
```
Stack OpenSearchKmsTest
Resources
[~] AWS::OpenSearchService::Domain Domain Domain may be replaced
 └─ [~] EncryptionAtRestOptions (may cause replacement)
     └─ [~] .KmsKeyId:
         ├─ [+] Added: .Fn::GetAtt
         └─ [-] Removed: .Ref

Outputs
[~] Output KmsKeyFormat KmsKeyFormat: {"Value":"KeyId"} to {"Value":"ARN"}
[~] Output KmsKeyValue KmsKeyValue: {"Value":{"Ref":"EncryptionKey1B843E66"}} to {"Value":{"Fn::GetAtt":["EncryptionKey1B843E66","Arn"]}}
```


```
┌─────────────────────────────────────────────────────────────────────────────────────┐
│                        🔴 CONFIRMED: DOMAIN WAS REPLACED! 🔴                        │
└─────────────────────────────────────────────────────────────────────────────────────┘

  CloudFormation Events Timeline:
  ════════════════════════════════

  1. Original domain created with KeyId:
     PhysicalResourceId: "domain-xydpwjq5pbn0"
     KmsKeyId: "c5ec58c9-de7b-4f28-945d-37978d29aa92"  (KeyId format)

  2. Update triggered (KeyId → ARN):
     ResourceStatusReason: "Requested update requires the creation of a 
                            NEW PHYSICAL RESOURCE; hence creating one."

  3. NEW domain created:
     PhysicalResourceId: "domain-mmhf4ngxjkuz"  ◄── DIFFERENT!
     KmsKeyId: "arn:aws:kms:us-east-1:903779448426:key/c5ec58c9-..."  (ARN format)

  4. Old domain DELETED:
     PhysicalResourceId: "domain-xydpwjq5pbn0"
     ResourceStatus: "DELETE_COMPLETE"


  PROOF:
  ══════

  domain-xydpwjq5pbn0  →  DELETED (old, used KeyId)
  domain-mmhf4ngxjkuz  →  CREATED (new, uses ARN)

  ⚠️  IN PRODUCTION THIS MEANS DATA LOSS! ⚠️

└─────────────────────────────────────────────────────────────────────────────────────┘


  CONCLUSION:
  ═══════════

  ┌─────────────────────────────────────────────────────────────────────┐
  │                                                                     │
  │                                                                     │
  │  Changing from keyId → keyArn DOES cause domain replacement,       │
  │  which means DATA LOSS for existing users.                         │
  │                                                                     │                                      │
  │                                                                     │
  └─────────────────────────────────────────────────────────────────────┘
```

OK. I can confirm this will cause data loss.

Comment (gasolima) [reply packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts:2260]: oh really good point totally forget the replacement problems 😓

File: packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts [hunk 2]
```diff
@@ -2197,6 +2197,42 @@ export class Domain extends DomainBase implements IDomain, ec2.IConnectable {
...
+   * For cross-account or cross-region KMS keys, OpenSearch requires the full ARN.
+   * For same-account, same-region keys, keyId is sufficient.
+   *
+   * @param key The KMS key to use for encryption
+   * @returns The key identifier to use in CloudFormation
+   */
+  private selectKmsKeyIdentifier(key: kms.IKeyRef): string {
+    const stack = cdk.Stack.of(this);
+
+    // Check if the key is from a different account or region
```
Comment (gasolima) [inline packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts]: can we remove this comment? it's irrelevant in this line also in line 2220 there's already a comment saying what it do

File: packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts [hunk 3]
```diff
@@ -2197,6 +2197,42 @@ export class Domain extends DomainBase implements IDomain, ec2.IConnectable {
...
   }
+
+  /**
+   * Selects the appropriate KMS key identifier (keyId or keyArn) based on whether
+   * the key is from the same account and region as the domain.
+   *
+   * For cross-account or cross-region KMS keys, OpenSearch requires the full ARN.
+   * For same-account, same-region keys, keyId is sufficient.
+   *
+   * @param key The KMS key to use for encryption
```
Comment (gasolima) [inline packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts]: Can we remove this part? to make our codebase more consistent since other functions doesn't have this part

**Review by gasolima — APPROVED** [review]
approved the PR, but left minor comments feel free to address them then remove the label do not merge

File: packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts (hunk 2 above)
Comment (pahud) [reply packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts]: OK will address accordingly when I get into the office later.
