### PR TITLE
fix(batch): grant execution role logs:CreateLogStream by default

### LINKED ISSUE #25675: aws_batch_alpha: Role permissions error after upgrade from v2.73 to v2.79
### Describe the bug

After changing ComputeEnvironment, JobDefinition, and other related Batch constructs to ManagedEc2EcsComputeEnvironment, EcsJobDefinition, etc. due to breaking changes in v2.79, Batch jobs fail with a CloudWatch permissions error.

### Expected Behavior

I expected any default IAM roles created by Batch constructs to have necessary permissions for the default logging configuration.

### Current Behavior

Batch jobs fail with the following error:  `CannotStartContainerError: Error response from daemon: failed to initialize logging driver: failed to create Cloudwatch log stream: AccessDeniedException: User: <BatchContainerDefinitionExecutionRole ARN>.`

### Reproduction Steps

This is the section of code that is currently used to generate the Batch infrastructure producing the error:
```
batch_security_group = ec2.SecurityGroup(
    self, id="BatchSecurityGroup", vpc=vpc, allow_all_outbound=True
)
postgres.connections.allow_default_port_from(batch_security_group)
batch_environ = batch.ManagedEc2EcsComputeEnvironment(
    self,
    "BatchEnvironment",
    compute_environment_name=f"{stack_name}-env",
    security_groups=[batch_security_group],
    spot=True,
    vpc=vpc,
)

seeder_queue = batch.JobQueue(
    self,
    "BatchSeedsJobQueue",
    job_queue_name=f"{stack_name}-seeds",
    compute_environments=[
        batch.OrderedComputeEnvironment(
            compute_environment=batch_environ, order=1
        ),
    ],
    priority=1,
)

wfs_job_def = batch.EcsJobDefinition(
    self,
    "WFSBatchJobDefinition",
    job_definition_name=f"{stack_name}-meta",
    parameters={
        "tasks": "ALL",
    },
    container=batch.EcsEc2ContainerDefinition(
        self,
        "WFSBatchContainerDefinition",
        image=ecs.ContainerImage.from_asset('./metadata'),
        environment={
            "POSTGRES_HOST": postgres.db_instance_endpoint_address,
            "POSTGRES_PORT": postgres.db_instance_endpoint_port,
            "POSTGRES_DB_NAME": "postgres",
            "POSTGRES_PASS": postgres.secret.secret_value_from_json(
                "password"
            ).to_string(),
        },
        cpu=1,
        memory=Size.mebibytes(8192),
    ),
)

wfs_datasets = [
    "test a",
    "test b",
    "test c",
    "test d",
]

wfs_jobs = step.Parallel(self, "WFSParallelJobs")
for idx, ds in enumerate(wfs_datasets):
    wfs_jobs.branch(
        tasks.BatchSubmitJob(
            self,
            f"WFSJobSubmit_{idx}",
            job_name=f"WFSJobSubmit_{idx}",
            job_queue_arn=seeder_queue.job_queue_arn,
            job_definition_arn=wfs_job_def.job_definition_arn,
            container_overrides=tasks.BatchContainerOverrides(
                environment={"DATASETS": ds}
            ),
        )
    )

wfs_state_machine = step.StateMachine(
    self,
    "WFSStateMachine",
    definition=wfs_jobs,
)

wfs_target = events_targets.SfnStateMachine(
    machine=wfs_state_machine,
)

events.Rule(
    self,
    "MetaRule",
    schedule=events.Schedule.rate(Duration.days(2)),
    targets=[wfs_target],
)
```

### Possible Solution

It appears as if the default container execution role of EcsEc2ContainerDefinition is not granted `logs:CreateLogStream` permissions.  If you manually remove the container execution role from the job definition, the job will succeed.  I'm guessing it gets the necessary permissions from the BatchEnvironmentInstanceProfileRole.  However, if you set the EcsJobDefinition `execution_role` property to None it will still create and assign a default execution role, which will fail with the permissions error.

### Additional Information/Context

Batch jobs created with JobDefinition/JobDefinitionContainer in v2.73 _do not_ appear to use a default execution role, whereas batch jobs created in v2.79 do.

### CDK CLI Version

2.79.1

### Framework Version

_No response_

### Node.js Version

16.20

### OS

Ubuntu 22.04.2

### Language

Python

### Language Version

3.8

### Other information

_No response_

### PR DESCRIPTION
**Pull request by comcalvi**
Grant `CreateLogStream` to the job definition's execution role by default. Without this permission, jobs will fail if they produce any output, unless `logging` is specified.

Closes #25675.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by comcalvi** [comment]
adding the exempt-integ-test, because the snapshots have been changed; there's no need to change the test code itself here, the snapshot change is sufficient.

File: packages/@aws-cdk/aws-batch-alpha/lib/ecs-container-definition.ts [hunk 1]
```diff
@@ -965,9 +965,17 @@ export class EcsFargateContainerDefinition extends EcsContainerDefinitionBase im
...
 
 function createExecutionRole(scope: Construct, id: string): iam.IRole {
-  return new iam.Role(scope, id, {
+  const execRole = new iam.Role(scope, id, {
     assumedBy: new iam.ServicePrincipal('ecs-tasks.amazonaws.com'),
     // needed for cross-account access with TagParameterContainerImage
     roleName: PhysicalName.GENERATE_IF_NEEDED,
   });
+
+  // all jobs will fail without this if they produce any output at all when no logging is specified
```
Comment (mrgrain) [inline packages/@aws-cdk/aws-batch-alpha/lib/ecs-container-definition.ts:974]: Can we only do this then when no logging is specified?

**Review by mrgrain — CHANGES_REQUESTED** [review]
