### PR TITLE
fix(eks): kubectl provider out-of-memory for large manifests/charts (now 1GiB)

### LINKED ISSUE #11787: (aws-eks): kubectlProvider can run out of memory
When using the HelmChart resource it is possible to deploy changes that cause the provider to run out of memory. 

### Reproduction Steps

create an `eks.HelmChart` for a large chart update. In my case it was to `efs-provisioner`.

### What did you expect to happen?

It to work.

### What actually happened?
```2:20:16 PM | UPDATE_FAILED        | Custom::AWSCDK-EKS-HelmChart | ChartD6199871
Response object is too long.

        new CustomResource (/home/doug/projects/trustsrv.io/node_modules/@aws-cdk/core/lib/custom-resource.ts:115:21)
        \_ new HelmChart (/home/doug/projects/trustsrv.io/node_modules/@aws-cdk/aws-eks/lib/helm-chart.ts:104:5)
        \_ Object.exports.deployRelease (/home/doug/projects/trustsrv.io/src/core/cluster/charts.ts:68:5)
        \_ Object.exports.systemCharts (/home/doug/projects/trustsrv.io/src/core/cluster/charts.ts:104:9)
        \_ processTicksAndRejections (internal/process/task_queues.js:97:5)
```

In the logs for the kubectl provider lambda function i got:

```fatal error: runtime: out of memory```

and a whole lot of go traceback.

### Environment

  - **CDK CLI Version  :** 1.59.0
  - **Framework Version:** 1.59.0
  - **Node.js Version:** 14.2
  - **OS               :** Debian
  - **Language (Version):** Typescript 3.7.3

### Other

I resolved this by manually changing the memory on the kubectl provider python lambda function and giving it 1024MB, using the console.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by eladb**
Increase the default memory size of the kubectl provider's lambda function to 1GiB and introduce a `kubectlMemory` option that can be used to control memory allocation if needed.

Fixes #11787

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-eks/lib/kubectl-provider.ts [hunk 1]
```diff
@@ -67,6 +67,7 @@ export class KubectlProvider extends NestedStack {
     }
 
     const layer = cluster.kubectlLayer ?? getOrCreateKubectlLayer(this);
+    const memorySize = cluster.kubectlMemory ? cluster.kubectlMemory.toMebibytes() : 1024;
```
Comment (iliapolo) [inline packages/@aws-cdk/aws-eks/lib/kubectl-provider.ts:70]: I don't think we should change the default size, it has cost implications and seems like 256 is enough for most manifests.

**Review by iliapolo — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-eks/lib/kubectl-provider.ts (hunk 1 above)
Comment (eladb) [reply packages/@aws-cdk/aws-eks/lib/kubectl-provider.ts:70]: The monthly cost for 500 requests of 10min is:
- $1.25US for 256MiB
- $2.50 for 512MiB
- $5US for 1024MiB

I think 1GiB should be fine.

Comment (iliapolo) [reply packages/@aws-cdk/aws-eks/lib/kubectl-provider.ts:70]: I'm ok with saying we are productionizing the configuration, but let's make sure we mention the value change in the changelog.

**Review by iliapolo — APPROVED** [review]
