### PR TITLE
fix(codebuild): add validation for source when badge is enabled

### LINKED ISSUE #1749: Bug: PipelineProject badge error
When creating a new PipelineProject I get an error when trying to enable badge

```ts
 const project = new codebuild.PipelineProject(this, 'TestProject', {
      environment: {
        buildImage: codebuild.LinuxBuildImage.UBUNTU_14_04_NODEJS_8_11_0
      },
      badge: true
    });
```

```
UPDATE_FAILED  | AWS::CodeBuild::Project  | TestProject (TestProjectF1529E8A) Failed to call UpdateProject, reason: Build badges are not supported for CodePipeline source (Service: AWSCodeBuild; Status Code: 400; Error Code: InvalidInputException; 
```

### PR DESCRIPTION
**Pull request by Kaixiang-AWS**
Badge should not be allow to set to true if source is not GITHUB, GITHUB_ENTERPRISE or BITBUCKET

Fixes #1749

----

### Pull Request Checklist

* [Y] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [Y] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
* [Y] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [N] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by eladb** [comment]
LGTM; @skinny85 I'll let you merge

File: packages/@aws-cdk/aws-codebuild/lib/source.ts [hunk 1]
```diff
@@ -52,6 +52,10 @@ export abstract class BuildSource {
     return undefined;
   }
 
+  public isBadgeSupported(): boolean {
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-codebuild/lib/source.ts]: I would rather have this be a read-only property...

File: packages/@aws-cdk/aws-codebuild/lib/source.ts [hunk 2]
```diff
@@ -22,6 +22,7 @@ export interface BuildSourceProps {
 export abstract class BuildSource {
   public readonly identifier?: string;
   public abstract readonly type: SourceType;
+  public readonly badgeAllowed: boolean = false;
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild/lib/source.ts]: I think badgeSupported makes more sense than allowed
