### PR TITLE
fix(mixins-preview): service exports are different then in `aws-cdk-lib`

### LINKED ISSUE #36210: (mixins-preview): `@aws-cdk/mixins-preview` is using different exports than `aws-cdk-lib`

### PR DESCRIPTION
**Pull request by mrgrain**
### Issue

Fixes #36210

### Reason for this change

`@aws-cdk/mixins-preview` exports services as `aws_s3` (note the underscore).
But `aws-cdk-lib` exports them as `aws-s3` (note the dash).

The intention was to align how the exports are named for ease of future migration. Better to fix this now.

### Description of changes

Renaming `aws_<SERVICE>` to `aws-<service>` and the required update of `cdk-generate-synthetic-examples`.

### Describe any new or updated permissions being added

n/a

### Description of how you validated changes

test pipeline

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/mixins-preview/lib/services/aws-iotcoredeviceadvisor/mixins.ts [hunk 1]
```diff
@@ -1 +1 @@
-export * from './iotcoredeviceadvisor.generated';
+export * from './cfn-props-mixins.generated';
```
Comment (rix0rrr) [inline packages/@aws-cdk/mixins-preview/lib/services/aws-iotcoredeviceadvisor/mixins.ts]: This is going to cause conflicts with the events PR :(

**Review by rix0rrr — COMMENTED** [review]
-

**Review by rix0rrr — APPROVED** [review]

File: packages/@aws-cdk/mixins-preview/scripts/gen.ts
Comment (vishaalmehrishi) [inline packages/@aws-cdk/mixins-preview/scripts/gen.ts:78]: Does this need to change as well?

```suggestion
      serviceIndexExports.push(`export * as ${moduleConfig.name} from './${moduleConfig.name}';`);
```

**Review by vishaalmehrishi — DISMISSED** [review]

File: packages/@aws-cdk/mixins-preview/scripts/gen.ts
Comment (vishaalmehrishi) [reply packages/@aws-cdk/mixins-preview/scripts/gen.ts:78]: Not sure why the suggestion formatting was messed up, but here's what I am referring to specifically:

`export * as ${moduleConfig.submodule}` -> `export * as ${moduleConfig.name}`

Comment (mrgrain) [reply packages/@aws-cdk/mixins-preview/scripts/gen.ts:78]: No. These exported symbols are using `_` in `aws-cdk-lib` (also symbols cannot have a `-` in their name). It's only the export paths that use `-`.

**Comment by mrgrain** [comment]
@mergifyio refresh
