### PR TITLE
fix(stepfunctions): the Retry field in the statesJson in CustomState is always overwrited

### LINKED ISSUE #28769: aws-stepfunctions: Retry in statesJson no longer appears in StateMachine definition
### Describe the bug

As called out in #28586. Prior to `v2.115.0` If the user had a `Retry` block defined within the `statesJson` object passed to `sfn.CustomState`, the resulting State Machine definition would contain the retry block.

However since `v2.116.0` this is no longer the case.

Although in #28598, an `addRetry` function was added which allows users to define a retry block after the CustomState is created. The regression introduced in `v2.116.0` is not fixed, and there is no documentation advising customers to move to using `addRetry` instead (If this regression cannot be fixed)

### Expected Behavior

The Retry block within `statesJson` passed to [CustomState](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-stepfunctions/lib/states/custom-state.ts) in the constructor should appear in the resulting State Machine definition as observed in versions `2.115.0` and before

### Current Behavior

Users that previously had the Retry block defined during instantiation time of `CustomState` will find that their State Machined definitions now no longer have a `Retry` block

### Reproduction Steps

```
const stateJson = {
    Type: 'Task',
    Resource: 'arn:aws:states:::lambda:invoke.waitForTaskToken',
    ResultPath: '$',
    Parameters: {
        Payload: {
            'TASK_TOKEN.$': '$$.Task.Token',
            'INPUT_FOR_TASK.$': '$'
        },
        'FunctionName.$': '$.lambdaFunctionName'
    },
    Retry: [
        {
            ErrorEquals: [
                'Lambda.ServiceException',
                'Lambda.AWSLambdaException',
                'Lambda.SdkClientException',
                'Lambda.TooManyRequestsException'
            ],
            IntervalSeconds: 1,
            MaxAttempts: 3,
            BackoffRate: 2
        }
    ],
    End: true,
    Comment: 'Lambda invoker for test runs'
};

const RunTaskState = new sfn.CustomState(this, 'LambdaRunTask.', {
    stateJson: stateJson
});
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.121.1

### Framework Version

_No response_

### Node.js Version

v18.18.2

### OS

Amazon Linux 2

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by sakurai-ryo**
After https://github.com/aws/aws-cdk/pull/28422 was merged, the regression that overwrites the Retry field defined in the stateJson was introduced.
The `this.renderRetryCatch()` method overwrites the Retry field in the stateJson.
https://github.com/aws/aws-cdk/blob/45b8398bec9ba9c03f195c14f3b92188c9058a7b/packages/aws-cdk-lib/aws-stepfunctions/lib/states/custom-state.ts#L74

This PR fixes this regression and clarifies the current behavior for configuring the Retry and Catch field.

Previously, I added the `addRetry` method to add the Retry field and did not render the Retry field in the stateJson in https://github.com/aws/aws-cdk/pull/28598, but this is initially a regression and should have been fixed.

Closes #28769
Relates #28586

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-stepfunctions/lib/states/custom-state.ts [hunk 1]
```diff
@@ -68,10 +68,17 @@ export class CustomState extends State implements IChainable, INextable {
...
    */
   public toStateJson(): object {
-    return {
+    const state = {
       ...this.renderNextEnd(),
       ...this.stateJson,
       ...this.renderRetryCatch(),
     };
+
+    // merge the Retry filed defined in the stateJson into the state
```
Comment (sakurai-ryo) [inline packages/aws-cdk-lib/aws-stepfunctions/lib/states/custom-state.ts:77]: The Retry is configured in two ways(the `addRetry` method and defining it in the stateJson), so we need to merge them.

**Comment by jacklin213** [comment]
Nicely done, fix looks good to me. Thanks @sakurai-ryo for updating the documentation for clarification too.
Will wait for someone from aws-cdk team to sign off :)

File: packages/aws-cdk-lib/aws-stepfunctions/README.md [hunk 2]
```diff
@@ -562,6 +562,10 @@ Custom states can be chained together with any of the other states to create you
 definition. You will also need to provide any permissions that are required to the `role` that
 the State Machine uses.
 
+The Retry and Catch fields are available for error handling.
+You can configure the Retry field by defining it in the JSON object or by adding it using the `addRetry` method.
+However, the Catch field cannot be configured by defining it in the JSON object, so it must be added using the `addCatch` method.
```
Comment (moelasmar) [inline packages/aws-cdk-lib/aws-stepfunctions/README.md:567]: why not to do the same for the Catch field?

Comment (sakurai-ryo) [reply packages/aws-cdk-lib/aws-stepfunctions/README.md:567]: @moelasmar 
Thanks for clarifying.
As mentioned in the comments (https://github.com/aws/aws-cdk/issues/25798#issuecomment-1749916284), the method of defining the `Catch` directly in JSON for the `CustomState` did not render well and forced us to call `_addCatch` in the base `State` class.
The `addCatch` method was added to solve this (https://github.com/aws/aws-cdk/pull/28422), but now it overrides the `Catch` and `Retry` fields in the JSON.
So it will take some investigation and changes to be able to define the `Catch` directly in JSON.

Comment (moelasmar) [reply packages/aws-cdk-lib/aws-stepfunctions/README.md:567]: thanks @sakurai-ryo for the clarifying.

**Review by moelasmar — DISMISSED** [review]

**Comment by GavinZZ** [comment]
@Mergify update

**Comment by moelasmar** [comment]
https://github.com/Mergifyio update

**Comment by sakurai-ryo** [comment]
Thanks @moelasmar  @GavinZZ 
Do I need to do the update locally?

**Comment by moelasmar** [comment]
[@Mergifyio](https://github.com/Mergifyio) update

**Comment by moelasmar** [comment]
> Thanks @moelasmar @GavinZZ Do I need to do the update locally?

for some reason mergify is not working, could you please do the update locally, and update your branch

**Review by moelasmar — APPROVED** [review]
