### PR TITLE
fix(ecs): validation for task definition fails when task-level memory is defined but container-level memory and memoryReservation are not defined with EC2 compatibility

### LINKED ISSUE #25275: ecs: task definition validation container bug
### Describe the bug

When I add a container definition to a fargate task definition, I am prompted to include `memory` or `memoryReservation` as a required field. This is not a container-level requirement if memory is already specified in the task.

### Expected Behavior

I expect the CDK to let me create a container without specifying `memory`. 

### Current Behavior

```
Error: Validation failed with the following errors:
  [EcsWorkspaceStack/nginxTaskDef] ECS Container web must have at least one of 'memoryLimitMiB' or 'memoryReservationMiB' specified
    at validateTree (/Users/petderek/experiments/ecs-workspace/node_modules/aws-cdk-lib/core/lib/private/synthesis.ts:356:11)
    at synthesize (/Users/petderek/experiments/ecs-workspace/node_modules/aws-cdk-lib/core/lib/private/synthesis.ts:49:5)
    at App.synth (/Users/petderek/experiments/ecs-workspace/node_modules/aws-cdk-lib/core/lib/stage.ts:217:33)
    at process.<anonymous> (/Users/petderek/experiments/ecs-workspace/node_modules/aws-cdk-lib/core/lib/app.ts:195:45)
```

### Reproduction Steps

Something like this should repro:

```
        const basicNginxTask = new aws_ecs.TaskDefinition(this, "nginxTaskDef", {
            compatibility: aws_ecs.Compatibility.EC2_AND_FARGATE,
            cpu: "256",
            executionRole: task_execution_role,
            family: "nginx",
            memoryMiB: "512",
            networkMode: aws_ecs.NetworkMode.AWS_VPC,
        });
        basicNginxTask.addContainer("nginxContainer", {
            containerName: "web",
            essential: true,
            image: aws_ecs.ContainerImage.fromRegistry("public.ecr.aws/nginx/nginx:stable"),
            portMappings: [{containerPort: 80}],
            // uncomment this to 'fix' and compile
            //memoryReservationMiB: 512,
        });
```

### Possible Solution

One solution would be to check if there is `memory` set at in the parent before validating the existence of `memory` in the container.

### Additional Information/Context

The correct behavior is mentioned in the `register-task-definition` documentation.

> If using the Fargate launch type, this parameter is optional.
> If using the EC2 launch type, you must specify either a task-level memory value or a container-level memory value. If you specify both a container-level memory and memoryReservation value, memory must be greater than memoryReservation . If you specify memoryReservation , then that value is subtracted from the available memory resources for the container instance where the container is placed. Otherwise, the value of memory is used.

### CDK CLI Version

2.76.0 (build 78c411b)

### Framework Version

_No response_

### Node.js Version

v18.16.0

### OS

mac

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by tam0ri**
Currently, validation for ECS task definition fails when task-level memory is defined but container-level memory and memoryReservation are not defined with EC2 compatibility. On the other hand, if we specify task-level memory, we can omit container-level memory and memoryReservation parameters from ECS API perspective. This PR solves the issue by skipping the validation when task-level memory is defined.

Closes #25275

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts [hunk 1]
```diff
@@ -736,9 +739,11 @@ export class TaskDefinition extends TaskDefinitionBase {
       // EC2 mode validations
 
       // Container sizes
-      for (const container of this.containers) {
-        if (!container.memoryLimitSpecified) {
-          ret.push(`ECS Container ${container.containerName} must have at least one of 'memoryLimitMiB' or 'memoryReservationMiB' specified`);
+      if (!this._memory) {
```
Comment (corymhall) [inline packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts:742]: We should also account for the scenario where both are provided.

> If using the EC2 launch type, you must specify either a task-level memory value or a container-level memory value. If you specify both a container-level memory and memoryReservation value, memory must be greater than memoryReservation . If you specify memoryReservation , then that value is subtracted from the available memory resources for the container instance where the container is placed. Otherwise, the value of memory is used.

**Review by corymhall — CHANGES_REQUESTED** [review]
Looks great! Just 1 comment

File: packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts (hunk 1 above)
Comment (tam0ri) [reply packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts:742]: Hi @corymhall, thank you for your review!

Please let me clearify your comment. What do you mean `the scenario where both are provided`? Is the scenario where both a task-level memory value and a container-level memory value are specified? Currently I don't understand what we should account for additionaly in the scenario.

In my understanding,

pattern 1: only task-level memory value is specified.
--> In that case, we don't have to check whether container-level memory value is specified.

pattern 2: only container-level memory value is specified.
--> In that case, we should check whether either memoryLimitMiB or memoryReservationMiB is specified. This validation is already implemented.

pattern 3: both a task-level memory value and a container-level memory value are specified.
--> In that case, we don't have to check whether container-level memory value is specified.

Comment (tam0ri) [reply packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts:742]: In my understanding, this is already validated here.
https://github.com/aws/aws-cdk/blob/f8a94d8fc3a43711c4079d83d1abf0817209fc42/packages/aws-cdk-lib/aws-ecs/lib/container-definition.ts#L490-L492

Comment (corymhall) [reply packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts:742]: ah yep  you are right.

**Review by corymhall — APPROVED** [review]
