### PR TITLE
fix(core): top-level resources cannot use long logical ids

### LINKED ISSUE #6190: Logical ID must adhere to the regular expression: /^[A-Za-z][A-Za-z0-9]{1,254}$/, got -----------
### Reproduction Steps

1 - Parent Stack extending Child Stack 
2 - Cdk synth
3 - Got error :  Logical ID must adhere to the regular expression because the logical expression resulted out of one level of nested stack is : 

referencetoDEVEVACCTAdapterQfreeStackDEVEVACCTAdapterFargateLBNestedStackDEVEVACCTAdapterFargateLBNestedStackResourceB049C71FOutputsDEVEVACCTAdapterQfreeStackDEVEVACCTAdapterFargateLBDEVEVACCTLBEvaAdapterDEVEVACCTAdapterBackendLoadBalancerTargetGroupD7A814A5Ref

### Error Log

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by eladb**
When allocating a logical ID for a CloudFormation resource we normally render the id by taking in the full construct path, trim it down to 240 characters and append a hash to it to make sure its unique. This technically allows construct IDs to be of any length.

However, when a resource is defined as a top-level resource (i.e. the child of a stack), it won't get this treatment and we will just use the construct id as it's logical id.

In this case, synthesis will fail with an error indicating the logical ID is invalid (too long).

This might work ok if the logical ID is human provided, but in some cases (like #6190), the id is actually created automatically and in some cases can be longer than 255.

This fix will only apply the special treatment to top-level resources if their construct ID is shorter than the maximum allowed length (255). Otherwise, it will use the same mechanism to trim them and append the hash.

Fixes #6190.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/core/lib/private/uniqueid.ts [hunk 1]
```diff
@@ -45,7 +46,7 @@ export function makeUniqueId(components: string[]) {
   // top-level resources will simply use the `name` as-is in order to support
   // transparent migration of cloudformation templates to the CDK without the
   // need to rename all resources.
-  if (components.length === 1) {
+  if (components.length === 1 && components[0].length < MAX_ID_LEN) {
```
Comment (rix0rrr) [inline packages/@aws-cdk/core/lib/private/uniqueid.ts]: We need to check the max length after removing nonalphanums, no?

Comment (eladb) [reply packages/@aws-cdk/core/lib/private/uniqueid.ts]: Good catch. Otherwise it's can potentially be a breaking change. ON IT.

Comment (eladb) [reply packages/@aws-cdk/core/lib/private/uniqueid.ts]: The right approach would have been to use the hash mode if there are any non-alpha (because otherwise we can get a conflict). But this will be a breaking change.

Comment (eladb) [reply packages/@aws-cdk/core/lib/private/uniqueid.ts]: https://github.com/aws/aws-cdk/issues/6421
