### PR TITLE
fix(s3-notifications): unable to delete the existing S3 event notifications  (under feature flag)

### LINKED ISSUE #28915: @aws-cdk/aws-s3: Unable to delete the existing S3 event notifications
### Describe the bug

I'm facing an issue while trying to delete the existing S3 event notifications.

The problem arises with S3 bucket event notification handler Lambda(AWS CloudFormation handler for "Custom::S3BucketNotifications" resources (@aws-cdk/aws-s3)), where it fails and reports an error: when calling the PutBucketNotificationConfiguration operation: Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type.

Custom event notification handler reference :  https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/custom-resource-handlers/lib/aws-s3/notifications-resource-handler/index.py

The issue is likely related to the change: https://github.com/aws/aws-cdk/commit/37be7b9b5d2abe04aa5f632a7b78aed3e9c233d8

The offending line is Line 39 - we are updating the ID of a JSON object, but the ID is inside of that object when it comes from outside. (https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/custom-resource-handlers/lib/aws-s3/notifications-resource-handler/index.py#L39)

### Expected Behavior

Should delete the existing event notifications

### Current Behavior

Unable to delete the existing filters: 
Error: when calling the PutBucketNotificationConfiguration operation: Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type.

### Reproduction Steps

1. Add few event notifications
2. Remove some of the the added notifications.
Please find the example stack attached to reproduce the issue.
[s3-event-notifications.txt](https://github.com/user-attachments/files/15928937/s3-event-notifications.txt)

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.124.0

### Framework Version

_No response_

### Node.js Version

v20.11.0

### OS

Linux

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by sarangarav**
### Issue # (if applicable)

Closes #28915 

### Reason for this change

Fix to address the issues deleting the existing S3 event notifications and adding new event notifications on top of existing notifications.

### Description of changes
We fixed the hashing logic used to identify old vs external S3 event notifications

### Description of how you validated changes
Manually tested, integration and unit tested the changes

yes
### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-s3/lib/notifications-resource/notifications-resource-handler.ts [hunk 1]
```diff
@@ -84,13 +84,9 @@ export class NotificationsResourceHandler extends Construct {
 
     const handlerSource = fs.readFileSync(path.join(__dirname, '..', '..', '..', 'custom-resource-handlers', 'dist', 'aws-s3', 'notifications-resource-handler', 'index.py'), 'utf8');
 
-    // Removing lines that starts with '#' (comment lines) in order to fit the 4096 limit
+    // Removing lines that starts with '#' (comment lines)
     const handlerSourceWithoutComments = handlerSource.replace(/^ *#.*\n?/gm, '');
 
-    if (handlerSourceWithoutComments.length > 4096) {
```
Comment (sarangarav) [inline packages/aws-cdk-lib/aws-s3/lib/notifications-resource/notifications-resource-handler.ts:90]: Inline function code can now exceed 4096 bytes. It can support up to 4MB now.

Latest public documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html#cfn-lambda-function-code-zipfile

File: packages/@aws-cdk/custom-resource-handlers/lib/aws-s3/notifications-resource-handler/index.py [hunk 2]
```diff
@@ -34,20 +35,31 @@ def handle_managed(request_type, notification_configuration):
     return {}
   return notification_configuration
 
-def handle_unmanaged(bucket, stack_id, request_type, notification_configuration, old):
+def handle_unmanaged(bucket, stack_id, request_type, notification_configuration, old, s3NotificationsDeleteFeatureFlagEnabled):
+  def get_id(n):
+    n['Id'] = ''
```
Comment (GavinZZ) [inline packages/@aws-cdk/custom-resource-handlers/lib/aws-s3/notifications-resource-handler/index.py:40]: Why do we need to set `n['Id'] = ''` here?

File: packages/@aws-cdk/custom-resource-handlers/lib/aws-s3/notifications-resource-handler/index.py [hunk 3]
```diff
@@ -34,20 +35,31 @@ def handle_managed(request_type, notification_configuration):
...
+    strToHash=json.dumps(n, sort_keys=True).replace('"Name": "prefix"', '"Name": "Prefix"').replace('"Name": "suffix"', '"Name": "Suffix"')
+    return f"{stack_id}-{hash(strToHash)}"
   def with_id(n):
-    n['Id'] = f"{stack_id}-{hash(json.dumps(n, sort_keys=True))}"
+    if s3NotificationsDeleteFeatureFlagEnabled:
+      n['Id'] = get_id(n)
```
Comment (GavinZZ) [inline packages/@aws-cdk/custom-resource-handlers/lib/aws-s3/notifications-resource-handler/index.py:45]: Can the `get_id` uses the same naming format where it starts with `stack-id` so the `Delete` event can handle it correctly since it relies on `{stack-id}` prefix.

File: packages/aws-cdk-lib/aws-s3/lib/notifications-resource/notifications-resource.ts [hunk 4]
```diff
@@ -133,6 +135,7 @@ export class BucketNotifications extends Construct {
           BucketName: this.bucket.bucketName,
           NotificationConfiguration: cdk.Lazy.any({ produce: () => this.renderNotificationConfiguration() }),
           Managed: managed,
+          S3NotificationsDeleteFeatureFlagEnabled: FeatureFlags.of(this).isEnabled(S3_EXISTING_NOTIFICATIONS_DELETE_ENABLED),
```
Comment (GavinZZ) [inline packages/aws-cdk-lib/aws-s3/lib/notifications-resource/notifications-resource.ts:138]: I think this name is a bit misleading. We're not actually changing the `Delete` event but more of the `Update` event, and it's not something that users can modified so we don't need to mention it's a feature flag. Can we change the name to something like `ApplyNameTransformations` or anything better that you can think of.

**Review by GavinZZ — CHANGES_REQUESTED** [review]
Left some feedbacks

File: packages/@aws-cdk/custom-resource-handlers/lib/aws-s3/notifications-resource-handler/index.py (hunk 2 above)
Comment (sarangarav) [reply packages/@aws-cdk/custom-resource-handlers/lib/aws-s3/notifications-resource-handler/index.py:40]: To exclude the "Id" field while computing the hash values for existing vs old notifications. Despite the content of the old and existing notifications being the same, their hash values are being generated differently due to a mismatch in the capitalization of the "Prefix" field (e.g., "Prefix" vs "prefix") and id field in existing notifications.

File: packages/@aws-cdk/custom-resource-handlers/lib/aws-s3/notifications-resource-handler/index.py (hunk 3 above)
Comment (sarangarav) [reply packages/@aws-cdk/custom-resource-handlers/lib/aws-s3/notifications-resource-handler/index.py:45]: Yes, it's using the same format.

File: packages/aws-cdk-lib/aws-s3/lib/notifications-resource/notifications-resource.ts (hunk 4 above)
Comment (sarangarav) [reply packages/aws-cdk-lib/aws-s3/lib/notifications-resource/notifications-resource.ts:138]: How about ApplyS3EventNotificationNameTransformations?

Comment (GavinZZ) [reply packages/aws-cdk-lib/aws-s3/lib/notifications-resource/notifications-resource.ts:138]: IMO S3EventNotification is a bit redundant since this custom resource handler is for s3 notification already.

File: packages/@aws-cdk/custom-resource-handlers/lib/aws-s3/notifications-resource-handler/index.py (hunk 3 above)
Comment (GavinZZ) [reply packages/@aws-cdk/custom-resource-handlers/lib/aws-s3/notifications-resource-handler/index.py:45]: Oh yeah, my bad for not noticing it's using the same format. Thanks for addressing this.

**Comment by GavinZZ** [comment]
@mergify update

**Comment by sarangarav** [comment]
@mergify update

**Review by GavinZZ — DISMISSED** [review]

**Review by GavinZZ — DISMISSED** [review]

**Review by GavinZZ — DISMISSED** [review]

**Comment by sarangarav** [comment]
@mergifyio refresh

**Review by GavinZZ — APPROVED** [review]
