### PR TITLE
fix(ecr): scanOnPush not supported in certain regions

### LINKED ISSUE #19918: (aws-ecr): repository automatically adds imageScanningConfiguration even when imageScanOnPush is undefined
### Describe the bug

Hi CDK team,

A [recent change to Repository](https://github.com/aws/aws-cdk/commit/78bc8703bb932822ceeb16fd57fa576714aa5732) started automatically adding `ImageScanningConfiguration` to the generated CloudFormation for `AWS::ECR::Repository` even when `scanOnPush` is `undefined`. This property is not supported in all regions (e.g. `us-iso-east-1`) and causes CloudFormation deployments to fail on the unrecognized property. 

Line in question: https://github.com/aws/aws-cdk/blob/d0ace8f2db53d56cdb670979c7c173ee17b6bcd8/packages/%40aws-cdk/aws-ecr/lib/repository.ts#L537

Suggested logic:

```ts
imageScanningConfiguration: props.imageScanOnPush === undefined ? undefined : { scanOnPush: props.imageScanOnPush },

```

---

The current workaround is to remove that property via escape hatch, however customers only know to do this after the deployment has already failed which is far from ideal.

```
const cfnRepo = somRepository.node.defaultChild as CfnRepository;
cfnRepo.addPropertyDeletionOverride('ImageScanningConfiguration');
```

### Expected Behavior

`ImageScanningConfiguration` property is only added to `AWS::ECR::Repository`  when `scanOnPush` is explicitly defined.

### Current Behavior

`ImageScanningConfiguration` is always added even for unsupported regions. 

### Reproduction Steps

// Note: imageScanOnPush is not being set
const repo = new Repository(this, 'SomeRepo', {});

### Possible Solution

(untested) Change the line to:

```
imageScanningConfiguration: props.imageScanOnPush === undefined ? undefined : { scanOnPush: props.imageScanOnPush },
```

### Additional Information/Context

_No response_

### CDK CLI Version

2.18.0 (build 75c90fa)

### Framework Version

_No response_

### Node.js Version

node-v14.19.1

### OS

MacOS

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by peterwoodworth**
fixes #19918 

----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-ecr/lib/repository.ts [hunk 1]
```diff
@@ -534,7 +534,7 @@ export class Repository extends RepositoryBase {
       // It says "Text", but they actually mean "Object".
       repositoryPolicyText: Lazy.any({ produce: () => this.policyDocument }),
       lifecyclePolicy: Lazy.any({ produce: () => this.renderLifecyclePolicy() }),
-      imageScanningConfiguration: props.imageScanOnPush ? { scanOnPush: true } : { scanOnPush: false },
+      imageScanningConfiguration: props.imageScanOnPush ? { scanOnPush: props.imageScanOnPush } : undefined,
```
Comment (tiefps) [inline packages/@aws-cdk/aws-ecr/lib/repository.ts:537]: My earlier suggestion was wrong (and syntactically incorrect doh!). It should be

```js
imageScanningConfiguration: props.imageScanOnPush === undefined ? undefined : { scanOnPush: props.imageScanOnPush }
```

Comment (peterwoodworth) [reply packages/@aws-cdk/aws-ecr/lib/repository.ts:537]: You're right, I'll fix that up and add a test to verify functionality

**Review by comcalvi — APPROVED** [review]
