### PR TITLE
fix(events,applicationautoscaling): specifying a schedule rate in seconds results in an error

### LINKED ISSUE #13566: (events): specifying a schedule duration in seconds results in an error
## :question: General Issue

This [PR](https://github.com/aws/aws-cdk/pull/13064) breaks `Schedule.rule()` in `aws-events`. Previously it was possible to define a `Duration` in seconds, now it throws an error.

### PR DESCRIPTION
**Pull request by nija-at**
A previous change - b1449a17 - introduced a validation that should have
been applied only when Duration is specified as a token. Instead, it was
applied for non token values as well.

Adjusting the validation so it only applies to when the duration is a
token.

fixes #13566

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-applicationautoscaling/lib/schedule.ts [hunk 1]
```diff
@@ -17,11 +17,11 @@ export abstract class Schedule {
...
-    if (!validDurationUnit.includes(duration.unitLabel())) {
-      throw new Error("Allowed unit for scheduling is: 'minute', 'minutes', 'hour', 'hours', 'day' or 'days'");
-    }
     if (duration.isUnresolved()) {
+      const validDurationUnit = ['minute', 'minutes', 'hour', 'hours', 'day', 'days'];
+      if (!validDurationUnit.includes(duration.unitLabel())) {
+        throw new Error("Allowed units for scheduling are: 'minute', 'minutes', 'hour', 'hours', 'day' or 'days'");
+      }
       return new LiteralSchedule(`rate(${duration.formatTokenToNumber()})`);
     }
```
Comment (NetaNir) [inline packages/@aws-cdk/aws-applicationautoscaling/lib/schedule.ts:26]:
```suggestion
    if (duration.isUnresolved()) {
          return new LiteralSchedule(`rate(${duration.formatTokenToNumber()})`)
    }
    
      const validDurationUnit = ['minute', 'minutes', 'hour', 'hours', 'day', 'days'];
      if (!validDurationUnit.includes(duration.unitLabel())) {
        throw new Error("Allowed units for scheduling are: 'minute', 'minutes', 'hour', 'hours', 'day' or 'days'");
      }
    
    
```
```suggestion
    if (duration.isUnresolved()) {
      const validDurationUnit = ['minute', 'minutes', 'hour', 'hours', 'day', 'days'];
      if (!validDurationUnit.includes(duration.unitLabel())) {
        throw new Error("Allowed units for scheduling are: 'minute', 'minutes', 'hour', 'hours', 'day' or 'days'");
      }
      return new LiteralSchedule(`rate(${duration.formatTokenToNumber()})`);
    }
```

Comment (NetaNir) [reply packages/@aws-cdk/aws-applicationautoscaling/lib/schedule.ts:26]: I think there is still a problem here. If duration is unresolved, it will go through the validation.

**Review by NetaNir — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-applicationautoscaling/lib/schedule.ts (hunk 1 above)
Comment (NetaNir) [inline packages/@aws-cdk/aws-applicationautoscaling/lib/schedule.ts:26]:
```suggestion
    if (duration.isUnresolved()) {
          return new LiteralSchedule(`rate(${duration.formatTokenToNumber()})`);
    }
    
      const validDurationUnit = ['minute', 'minutes', 'hour', 'hours', 'day', 'days'];
      if (!validDurationUnit.includes(duration.unitLabel())) {
        throw new Error("Allowed units for scheduling are: 'minute', 'minutes', 'hour', 'hours', 'day' or 'days'");
      }
```

Comment (NetaNir) [reply packages/@aws-cdk/aws-applicationautoscaling/lib/schedule.ts:26]: GitHub is being weird, so I'll just comment here. It seems like there is still a problem in code, if duration is unresolved the validation will still happen?

Comment (nija-at) [reply packages/@aws-cdk/aws-applicationautoscaling/lib/schedule.ts:26]: > if duration is unresolved the validation will still happen?

Yes, that's the intended change here. If duration is a token, it is not possible to perform unit conversion. So the original units specified during construction of the `Duration` object will be used. However, AWS events has a fixed set of units and hence the validation is required.

If Duration is not a token, then the units can be converted from the unsupported set of units to the supported set of units.

Makes sense?

Comment (NetaNir) [reply packages/@aws-cdk/aws-applicationautoscaling/lib/schedule.ts:26]: Thanks! I missed that `duration.isUnresolved()` is calling the `isUnresolved` method from the `Duration` class rather than the `Token.isUnresolved` method

**Review by NetaNir — APPROVED** [review]
