### PR TITLE
fix(aws-cdk): Improvements to IAM diff rendering

### LINKED ISSUE #1458: diff ui: `replace` is as dangerous as `destroy` - so should be in red
Adding an attribute to Cognito user group destroys the old one (with manually added users) with no warning..

Diff show's `replace` against the top level, but that's not as clear as when I remove an attribute and it has `destroy` in red!

I didn't realise it was replacing the whole thing, not just the schema change I'd made.. maybe : change it to `replace (e.g. destroy/create)` on the diff output? and have it in red?

### LINKED ISSUE #1495: IAM Diff Thrash with Lambda Permissions
Enhanced IAM diff generates the following when I'm replacing a lambda function (changing function name).

screen shot 2019-01-08 at 1 40 00 am

The permission is new, but should we capture that source account? It leads a user to think the source account is lost, but it's added back by default.

### PR DESCRIPTION
**Pull request by rix0rrr**
Contains the following changes:

- Print table to STDOUT instead of STDERR. This ensures the diff output and the "confirm (y/n)" prompt that follows it don't interleave on the terminal, degrading readability.
- Control table width to not exceed the terminal width, so that it doesn't wrap and lead to a mess of lines.
- Switch back to the new version of the `table` library (instead of `cli-table`) which now has in-cell newline support, to get rid of the rendering bugs in `cli-table` that would occasionally eat newlines.
- Render resource `replace` impact as red instead of yellow, to indicate that data loss will be happening here (fixes #1458).
- Change replacement diffing in order to not trigger IAM changes dialog (fixes #1495).

Explanation: 

We used to modify the new target template in place, causing changes to
the logical ids of replaced resources, which would trigger downstream
changes, which would further trigger potential downstream replacements, etc. 

This would properly calculate the set of impacted resources, but would also lead to the modified logical ID popping up in the IAM diff, which was not desirable.

In this change, we do the same processing but we throw away the
template after all changes have been propagated, and only copy
the resultant property *statuses* onto the diff object that gets
returned to the user. This leads to the same displayed result
without the changes to the template actually propagating.

In the course of this modification, the diff classes have been changed
to also have objects in places of resources and properties that
didn't actually change (so that they could be modified in-place),
and diff objects have a boolean telling whether they are actual
changes or not.

----

### Pull Request Checklist

* [x] Testing
  - Unit test added
  - __CLI change?:__ manually run [integration tests](https://github.com/awslabs/aws-cdk/blob/master/packages/aws-cdk/integ-tests/test.sh) and paste output as a PR comment
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by eladb** [comment]
Could you please upload a nice little screenshot?

**Comment by rix0rrr** [comment]
selection_033

File: packages/@aws-cdk/cloudformation-diff/lib/diff/types.ts [hunk 1]
```diff
@@ -75,19 +75,19 @@ export class TemplateDiff implements ITemplateDiff {
...
-    count += this.parameters.count;
-    count += this.resources.count;
-    count += this.unknown.count;
+    count += this.conditions.differenceCount;
+    count += this.mappings.differenceCount;
+    count += this.metadata.differenceCount;
+    count += this.outputs.differenceCount;
+    count += this.parameters.differenceCount;
+    count += this.resources.differenceCount;
+    count += this.unknown.differenceCount;
```
Comment (sam-goodwin) [inline packages/@aws-cdk/cloudformation-diff/lib/diff/types.ts]: nit: scope these under a single object so you can `enumerate` and `reduce`?

File: packages/@aws-cdk/cloudformation-diff/lib/diff/types.ts [hunk 2]
```diff
@@ -436,12 +458,13 @@ export enum ResourceImpact {
...
-    [ResourceImpact.MAY_REPLACE]: 3,
-    [ResourceImpact.WILL_REPLACE]: 4,
-    [ResourceImpact.WILL_DESTROY]: 5,
+    [ResourceImpact.NO_CHANGE]: 0,
+    [ResourceImpact.WILL_UPDATE]: 1,
+    [ResourceImpact.WILL_CREATE]: 2,
+    [ResourceImpact.WILL_ORPHAN]: 3,
+    [ResourceImpact.MAY_REPLACE]: 4,
+    [ResourceImpact.WILL_REPLACE]: 5,
+    [ResourceImpact.WILL_DESTROY]: 6,
```
Comment (sam-goodwin) [inline packages/@aws-cdk/cloudformation-diff/lib/diff/types.ts]: Why declare this in the function scope?

File: packages/@aws-cdk/cloudformation-diff/lib/format-table.ts [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+function lineBetween(rowA: string[], rowB: string[]) {
+  return rowA[1] !== rowB[1];
+}
+
+function buildColumnConfig(widths: Array<number | undefined>): { [index: number]: table.ColumnConfig } {
+  const ret: { [index: number]: table.ColumnConfig } = {};
+  widths.forEach((width, i) => {
+    ret[i] = { width, useWordWrap: true } as any; // 'useWordWrap' is not in @types/table
+    if (width === undefined) {
+      delete ret[i].width;
```
Comment (sam-goodwin) [inline packages/@aws-cdk/cloudformation-diff/lib/format-table.ts]: This `undefined` terminal width has penetrated the logic everywhere. Can we not switch it on/off in a simpler way to avoid `delete ret[i].width` and `Array<number | undefined>`? It seems to have a single source: `formatTable(_, columns: number | undefined)`.

File: packages/@aws-cdk/cloudformation-diff/lib/format-table.ts [hunk 4]
```diff
@@ -0,0 +1,111 @@
...
+ * We do this by calculating a fair share for every column. Extra width smaller
+ * than the fair share is evenly distributed over all columns that exceed their
+ * fair share.
+ */
+function calculcateColumnWidths(rows: string[][], terminalWidth: number | undefined): Array<number | undefined> {
+  // use 'string-width' to not count ANSI chars as actual character width
+  const columns = rows[0].map((_, i) => Math.max(...rows.map(row => stringWidth(row[i]))));
+
+  // If we have no terminal width, do nothing
+  if (terminalWidth === undefined) { return columns.map(_ => undefined); }
```
Comment (sam-goodwin) [inline packages/@aws-cdk/cloudformation-diff/lib/format-table.ts]: array of undefined? Is this the optimal signal?

File: packages/@aws-cdk/cloudformation-diff/lib/format-table.ts [hunk 5]
```diff
@@ -0,0 +1,111 @@
...
+      const width = distributableWidth < 2 * fairDistributable ? distributableWidth : fairDistributable;
+      ret.push(width);
+      distributableWidth -= width;
+    }
+  }
+
+  return ret;
+}
+
+function sum(xs: number[]): number {
```
Comment (sam-goodwin) [inline packages/@aws-cdk/cloudformation-diff/lib/format-table.ts]: `xs.reduce((a,b) => a + b, 0)`

File: packages/aws-cdk/lib/util/tables.ts [hunk 6]
```diff
@@ -1,13 +1,43 @@
...
 export function renderTable(cells: string[][], options: RenderTableOptions = {}): string {
-  const head = cells.splice(0, 1)[0];
+  const columns: {[col: number]: table.ColumnConfig} = {};
 
-  const table = new Table({ head, style: { head: [] }, colWidths: options.colWidths });
-  table.push(...cells);
-  return table.toString();
+  if (options.colWidths) {
+    options.colWidths.forEach((width, i) => {
+      columns[i] = { width, useWordWrap: true } as any; // @types doesn't have this type
```
Comment (sam-goodwin) [inline packages/aws-cdk/lib/util/tables.ts]: Why do you need to cast to `any` here? You have the type, `table.ColumnConfig`, is this not the correct shape?

File: packages/aws-cdk/lib/util/tables.ts [hunk 7]
```diff
@@ -1,13 +1,43 @@
...
+  bottomLeft: tableColor('└'),
+  bottomRight: tableColor('┘'),
+  bodyLeft: tableColor('│'),
+  bodyRight: tableColor('│'),
+  bodyJoin: tableColor('│'),
+  joinBody: tableColor('─'),
+  joinLeft: tableColor('├'),
+  joinRight: tableColor('┤'),
+  joinJoin: tableColor('┼')
+};
```
Comment (sam-goodwin) [inline packages/aws-cdk/lib/util/tables.ts]: I've seen this table twice .. redundant?

Comment (rix0rrr) [reply packages/aws-cdk/lib/util/tables.ts]: One is in `@aws-cdk/cloudformation-diff` and the other one is in `aws-cdk`. I'd prefer to keep the table rendering private to the package, because it doesn't seem like an exportable feature of @aws-cdk/cloudformationd-diff`, and extracting to another package just to share seemed a bit too much.

File: packages/@aws-cdk/cloudformation-diff/lib/diff/types.ts (hunk 2 above)
Comment (sam-goodwin) [reply packages/@aws-cdk/cloudformation-diff/lib/diff/types.ts]: Is it optimized away? :)
