### PR TITLE
fix(autoscaling): move lifecycle hook targets to their own module

### LINKED ISSUE #2447: aws-autoscaling-hooks
- [ ] Centralize all `ILifecycleHook` implementation into a single module.
- [ ] Consider getting rid of aws-autoscaling-api

### PR DESCRIPTION
**Pull request by rix0rrr**
In accordance with new guidelines, we're centralizing cross-service
integrations into their own package. In this case, centralizing
AutoScaling Lifecycle Hook Targets into
`@aws-cdk/aws-autoscaling-hooktargets`.

Fixes #2447.

BREAKING CHANGE: using a Topic, Queue or Lambda as Lifecycle Hook
Target now requires an integration
object from the `@aws-cdk/aws-autoscaling-hooktargets` package.

----

### Pull Request Checklist

* [ ] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [ ] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
  - __Design__: For significant features, design document added to `design` folder
* [ ] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [ ] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-autoscaling-hooktargets/.gitignore [hunk 1]
```diff
@@ -1,5 +1,3 @@
-lambda/bundle.zip
```
Comment (eladb) [inline packages/@aws-cdk/aws-autoscaling-hooktargets/.gitignore]: Should we leave this package for another version as we deprecate it?

File: packages/@aws-cdk/aws-autoscaling-hooktargets/lib/lambda-hook.ts [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+/**
+ * Use a Lambda Function as a hook target
+ *
+ * Internally creates a Topic to make the connection.
+ */
+export class FunctionHook implements autoscaling.ILifecycleHookTarget {
+  constructor(private readonly fn: lambda.IFunction) {
+  }
+
+  public bind(lifecycleHook: autoscaling.ILifecycleHook): autoscaling.LifecycleHookTargetProps {
```
Comment (eladb) [inline packages/@aws-cdk/aws-autoscaling-hooktargets/lib/lambda-hook.ts]: I wonder if `bind` should pass a `scope: Construct` (sounds like a useful pattern in general).
