### PR TITLE
fix(ecs): adding a circuit breaker causes Service replacement (under feature flag)

### LINKED ISSUE #16126: (aws-ecs): Adding circuitBreaker config causes service replacement if deploymentController was not previously set
When adding the circuitBreaker configuration to an ECS service, it automatically sets the `DeploymentController` to `ECS` in the resulting Cloudformation stack. If the `deploymentController` was not specified within the CDK previously, the default value of `ECS` is used when the service is created anyway. 

Unfortunately Cloudformation sees this as a change requiring replacement of the service.

### Reproduction Steps

Pre-existing service:
```
new FargateService(this, "Service", {
  cluster: cluster,
  taskDefinition: taskDefinition
})
```

Adding the circuitBreaker config:
```
new FargateService(this, "Service", {
  cluster: cluster,
  taskDefinition: taskDefinition,
  circuitBreaker: { enabled: true, rollback: true }
})
```
Deploying the above causes service replacement.

### What did you expect to happen?

Expected the `DeploymentController` to be left undefined, since that still results in the default value of `ECS` being used. 

### What actually happened?

Upon deployment the service required replacement, which will have been disruptive due to autoscaled values not carrying across to the new service.

Ended up using escape hatches to set the circuitBreak properties without adding the `DeploymentController` configuration.

### Environment

  - **CDK CLI Version  :** 1.118.0
  - **Framework Version:** 1.118.0
  - **Node.js Version:** v14.15.1 
  - **OS               :** Mac OS 11.5
  - **Language (Version):** Typescript (4.3.3) 

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by fergusdixon**
Fixes #16126

Copied from #16919 with review comments as it went stale and closed.
Initial implementation #22328 reverted because it was not backward compatible.

Introduces feature flag:

* `@aws-cdk/aws-ecs:disableExplicitDeploymentControllerForCircuitBreaker`

Enable this feature flag to avoid setting the "ECS" deployment controller when adding a circuit breaker to an
ECS Service, as this will trigger a full replacement which fails to deploy when using set service names.
This does not change any behaviour as the default deployment controller when it is not defined is ECS.

_cdk.json_

```json
{
  "context": {
    "@aws-cdk/aws-ecs:disableExplicitDeploymentControllerForCircuitBreaker": true
  }
}
```

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-ecs/lib/base/base-service.ts [hunk 1]
```diff
@@ -54,6 +54,13 @@ export interface DeploymentCircuitBreaker {
    */
   readonly rollback?: boolean;
 
+  /**
+   * Whether to use the explicit DeploymentControllerType.ECS when defining the circuit breaker.
+   * To avoid a service replacement when add a CircuitBreaker to an existing ECS service, set this to False.
+   * @default true
```
Comment (xXPOLYGONXx) [inline packages/@aws-cdk/aws-ecs/lib/base/base-service.ts:60]: Would it not be better to set this parameter to false as a default? 
This would prevent service replacements from happening by accident and should not have any drawbacks since Cloudformation doesnt need the explicit Deploymentcontrollertype set to ECS right?

File: packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-https.ts [hunk 2]
```diff
@@ -27,6 +27,7 @@ new ApplicationLoadBalancedFargateService(stack, 'myService', {
     zoneName: 'example.com.',
   }),
   redirectHTTP: true,
+  circuitBreaker: { rollback: true, useExplicitEcsDeploymentController: false },
```
Comment (TheRealAmazonKendra) [inline packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-https.ts:30]: I would prefer to have a new test written instead of just updating the current test.

File: packages/@aws-cdk/aws-ecs/lib/base/base-service.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (TheRealAmazonKendra) [reply packages/@aws-cdk/aws-ecs/lib/base/base-service.ts:60]: The default should be the current behavior to avoid breaking changes.

File: packages/@aws-cdk/aws-ecs/lib/base/base-service.ts [hunk 3]
```diff
@@ -466,6 +477,15 @@ export abstract class BaseService extends Resource
       Annotations.of(this).addWarning('taskDefinition and launchType are blanked out when using external deployment controller.');
     }
 
+    // If the circuit breaker chooses not to set the DeploymentController, and it has been manually set to something other than ECS
+    // Add an error that it is not supported
+    if (props.circuitBreaker
```
Comment (TheRealAmazonKendra) [inline packages/@aws-cdk/aws-ecs/lib/base/base-service.ts:482]: Reading this, I'm wondering if we need to redefine the contract somewhat and deprecate this current version instead of adding in this error.

**Review by TheRealAmazonKendra — DISMISSED** [review]

File: packages/@aws-cdk/aws-ecs/lib/base/base-service.ts (hunk 1 above)
Comment (fergusdixon) [reply packages/@aws-cdk/aws-ecs/lib/base/base-service.ts:60]: I believe https://github.com/aws/aws-cdk/pull/22467#discussion_r998894146 was a reply to this

File: packages/@aws-cdk/aws-ecs/lib/base/base-service.ts (hunk 3 above)
Comment (fergusdixon) [reply packages/@aws-cdk/aws-ecs/lib/base/base-service.ts:482]: Do you have some guidance/examples on how this would be achieved?

File: packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-https.ts (hunk 2 above)
Comment (fergusdixon) [reply packages/@aws-cdk/aws-ecs-patterns/test/fargate/integ.alb-fargate-service-https.ts]: Done

File: packages/@aws-cdk/aws-ecs/lib/base/base-service.ts [hunk 4]
```diff
@@ -54,6 +54,13 @@ export interface DeploymentCircuitBreaker {
    */
   readonly rollback?: boolean;
 
+  /**
+   * Whether to use the explicit DeploymentControllerType.ECS when defining the circuit breaker.
+   * To avoid a service replacement when adding a CircuitBreaker to an existing ECS service, set this to false.
+   * @default true
+   */
+  readonly useExplicitEcsDeploymentController?: boolean;
```
Comment (corymhall) [inline packages/@aws-cdk/aws-ecs/lib/base/base-service.ts:62]: @fergusdixon I've been thinking about this and as much as a don't want to introduce a new feature flag I think that's the best thing to do here. We **want** the new default behavior to be `false` and a feature flag is the only way to accomplish that. 

https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#feature-flags

**Review by corymhall — DISMISSED** [review]

File: packages/@aws-cdk/aws-ecs/lib/base/base-service.ts (hunk 4 above)
Comment (fergusdixon) [reply packages/@aws-cdk/aws-ecs/lib/base/base-service.ts:62]: Sure will give it a bash next week, thanks!

Comment (fergusdixon) [reply packages/@aws-cdk/aws-ecs/lib/base/base-service.ts:62]: @corymhall I have a working implementation with the flag, however I'm struggling to see this to `false` in the integration tests specifically. Should the integration tests cover new or old behaviour (I would imagine both), however I cant seem to set the feature flag value the same way as the unit tests do?

Comment (fergusdixon) [reply packages/@aws-cdk/aws-ecs/lib/base/base-service.ts:62]: It seems the [integ-helper sets all feature flags](https://github.com/fergusdixon/aws-cdk/blob/9e508fdbc8ec7e5b199a342bc7380641a0a0951c/tools/@aws-cdk/cdk-integ-tools/lib/integ-helpers.ts#L382) to `FUTURE_FLAGS` (new behaviour), and this takes precedence over the `context` prop passed to `App` in the test. So from this it seems integration tests should test new behaviour and unit tests for both?

Comment (corymhall) [reply packages/@aws-cdk/aws-ecs/lib/base/base-service.ts:78]: If you want to test the old behavior you can use the [postCliContext](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.AppProps.html#postclicontext) parameter on `App`.

Comment (fergusdixon) [reply packages/@aws-cdk/aws-ecs/lib/base/base-service.ts:78]: Have done, worked a charm, thanks!

Comment (rix0rrr) [reply packages/@aws-cdk/aws-ecs/lib/base/base-service.ts:78]: I really want to ship this, but this property is giving me pause. I really don't see the need for it.

* If you want the ECS controller explicitly, you can just supply it ("The customer is always right", below)
* If you do NOT want the ECS controller, you can set the feature flag 
  * If you want the ECS controller for *some* services and not other, you can either set the feature flag globally and add the explicit parameter to *some* services, or set the feature flag locally (you can flip a flag at any construct scope, it's all just context which is freely manipulable).

I think we can do without this, no?

Other than that, this is great!

**Review by rix0rrr — DISMISSED** [review]

**Review by rix0rrr — DISMISSED** [review]

**Comment by fergusdixon** [comment]
@rix0rrr any idea why the deploy queue failed?

File: packages/@aws-cdk/aws-ecs/lib/base/base-service.ts (hunk 4 above)
Comment (rgoltz) [reply packages/@aws-cdk/aws-ecs/lib/base/base-service.ts]: Just to cross-check "the need for the 'correct' default after this PR is merged": Now with current CDKv2 versions today, CFN output always has an ECS DeploymentController defined, if you have an CircuitBreaker enabled (even if you not aware as CDK user).
Once a stack has an ECS DeploymentController definied (= all stack build by CDK with CircuitBreaker enabled), you are not able to simply "remove this CFN-lines from JSON output" - If a new/upcoming CDK version would start to _not_ output ECS DeploymentController (by default) to JSON, all existing Services of existing Stacks would run into a replacement - Just because you update your CDK version.

As I understood the current code from Fergus, this default = true would remain the same behaviour as older CDKv2 version, right? - From my point of view that, it's an important brick, isn't it?

**Review by rix0rrr — APPROVED** [review]

**Comment by shellscape** [comment]
@fergusdixon is there a means to programmatically set feature flags? we've got around 20 fargate services going up, each with their own `cdk.json` and managing feature flags (specifically setting this one, since all of our services use set names) via `cdk.json` for each is a bit of a PITA.

**Comment by shellscape** [comment]
@rix0rrr is there a means to programmatically set feature flags? we've got around 20 fargate services going up, each with their own `cdk.json` and managing feature flags (specifically setting this one, since all of our services use set names) via `cdk.json` for each is a bit of a PITA. happy to open a new issue but wanted to ping first.

**Comment by corymhall** [comment]
@shellscape yes you can set it programmatically using `setContext`

```ts
node.setContext('@aws-cdk/aws-ecs:disableExplicitDeploymentControllerForCircuitBreaker', true);
```

This will apply the feature flag to all constructs within that scope.
