### PR TITLE
fix(s3): Add validations for S3 bucket names

### LINKED ISSUE #1308: Add bucket name check
Wonder if can do this at cdk diff stage

`
1/5 | 11:43:29 | UPDATE_FAILED | AWS::S3::Bucket | seleniumbase_bucket (seleniumbasebucket4FC88E60) Bucket name should not contain '_'
`

### PR DESCRIPTION
**Pull request by nija-at**
Bucket names are verified to conform with rules published by S3 -
https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

fixes #1308

----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [ ] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [ ] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-s3/lib/bucket.ts [hunk 1]
```diff
@@ -669,6 +670,9 @@ export class Bucket extends BucketBase {
     super(scope, id);
 
     const { bucketEncryption, encryptionKey } = this.parseEncryption(props);
+    if (props.bucketName) {
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-s3/lib/bucket.ts]: Include `&& !cdk.Token.unresolved(props.bucketName)`

File: packages/@aws-cdk/aws-s3/lib/bucket.ts [hunk 2]
```diff
@@ -776,6 +780,31 @@ export class Bucket extends BucketBase {
...
+    if (!/^[a-z0-9.-]+$/.test(bucketName)) {
+      errors.push('Bucket name must only contain lowercase characters and the symbols, period (.) and dash (-)');
+    }
+    if (!/[a-z0-9]/.test(bucketName.charAt(0)) || !/[a-z0-9]/.test(bucketName.charAt(bucketName.length - 1))) {
+      errors.push('Bucket name must start and end with a lowercase character or number');
+    }
+    if (/\.-|-\.|\.\./.test(bucketName)) {
+      errors.push('Bucket name must not have dash next to period, or period next to dash, or consecutive periods');
+    }
+    if (/\d+\.\d+\.\d+\.\d+/.test(bucketName)) {
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-s3/lib/bucket.ts]: Is this how S3 validates? I feel like this might be prohibiting certain options that S3 would permit...

File: packages/@aws-cdk/aws-s3/lib/bucket.ts [hunk 3]
```diff
@@ -776,6 +780,31 @@ export class Bucket extends BucketBase {
     return this.onEvent(EventType.ObjectRemoved, dest, ...filters);
   }
 
+  private validateBucketName(bucketName: string) {
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-s3/lib/bucket.ts]: This is great, but I would appreciate if we could put the offending bucket name in the error messages, too... Like end with `(provided: "${bucketName}")`.

If you can make this fancier even and somehow highlight the offending part, this would be absolutely awesome... But may be challenging to make it "look right", so feel free not to.

Being said, it could be interesting to know the position of the offending element at least, due to the presence of unicode homoglyphs, for example:

OK | Not OK
---|---
`-` | `‐`, `－`
`a`| `ɑ`, `а`, `ａ`
`.` | `․`, `．`

Comment (nija-at) [reply packages/@aws-cdk/aws-s3/lib/bucket.ts]: Thanks @RomainMuller 

Bucket name is in the error message. See line 804.

I'll include the offending character position in the error message, best effort.

File: packages/@aws-cdk/aws-s3/lib/bucket.ts (hunk 2 above)
Comment (nija-at) [reply packages/@aws-cdk/aws-s3/lib/bucket.ts]: Not sure if this is how S3 does it. I've reversed engineered their validations based on their [rules here](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html) and manually trying out combinations.

Some of these are pretty straight forward, like length and character set, but the ones around IP and symbol combinations get more tricky. 
I've picked combinations and regex that I should be more liberal than S3 (in that, S3 might have additional/stricter checks I don't have here), but happy to drop the more tricky ones if you think they might break customers.

What do you think?

File: packages/@aws-cdk/aws-s3/test/test.bucket.ts [hunk 4]
```diff
@@ -72,6 +72,106 @@ export = {
     test.done();
   },
 
+  'valid bucket names'(test: Test) {
+    const stack = new cdk.Stack();
+
+    test.ok(() => new s3.Bucket(stack, 'MyBucket1', {
```
Comment (nija-at) [inline packages/@aws-cdk/aws-s3/test/test.bucket.ts]: Turns out `ok` does not fail if there is, in fact, an exception thrown. I'll be switching this around to use `doesNotThrow`

File: packages/@aws-cdk/aws-s3/lib/bucket.ts (hunk 1 above)
Comment (nija-at) [reply packages/@aws-cdk/aws-s3/lib/bucket.ts]: Thanks for pointing this out. I was not aware of the CDK's token feature.

Fixed in updated PR.

File: packages/@aws-cdk/aws-s3/lib/bucket.ts (hunk 3 above)
Comment (nija-at) [reply packages/@aws-cdk/aws-s3/lib/bucket.ts]: Added offending character offset in the error message. 

For each class of error, I only report the first offence that occur. 

The code has gotten slightly more complex with this change, although I've tried to keep it as readable as I could.

File: packages/@aws-cdk/aws-s3/test/test.bucket.ts [hunk 5]
```diff
@@ -72,6 +72,120 @@ export = {
...
+    const stack = new cdk.Stack();
+
+    test.doesNotThrow(() => new s3.Bucket(stack, 'MyBucket', {
+      bucketName: new cdk.Token(() => '_BUCKET').toString()
+    }));
+
+    test.done();
+  },
+
+  'fails if bucket name has less than 3 or more than 63 characters'(test: Test) {
```
Comment (eladb) [inline packages/@aws-cdk/aws-s3/test/test.bucket.ts]: Can you please add another failure test that asserts against the entire message? (especially good for CRs).

Comment (nija-at) [reply packages/@aws-cdk/aws-s3/test/test.bucket.ts]: Added and updated PR.
