### PR TITLE
fix(dynamodb): unsupported actions added to table resource policy

### LINKED ISSUE #32230: aws_dynamodb: Unable to create table with resource policy with certain dynamodb actions
### Describe the bug

Unable to create dynamodb table v2 with a resource policy that contains certain dynamodb actions relating to streams.

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "DynamoDBIndexAndStreamAccess",
            "Effect": "Allow",
            "Action": [
                "dynamodb:GetShardIterator",
                "dynamodb:Scan",
                "dynamodb:Query",
                "dynamodb:DescribeStream",
                "dynamodb:GetRecords",
                "dynamodb:ListStreams"
            ],
            "Principal": {
                "AWS": [
                    "arn:aws:iam::123456789012:role/test-ddb-role-1",
                    "arn:aws:iam::123456789012:role/test-ddb-role-2",
                    "arn:aws:iam::123456789012:role/test-ddb-role-3"
                ]
            },
            "Resource": [
                "arn:aws:dynamodb:ap-southeast-2:123456789012:table/ddb-table-test/index/*",
                "arn:aws:dynamodb:ap-southeast-2:123456789012:table/ddb-table-test/stream/*"
            ]
        },
        {
            "Sid": "DynamoDBTableAccess",
            "Effect": "Allow",
            "Action": [
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
                "dynamodb:ConditionCheckItem",
                "dynamodb:PutItem",
                "dynamodb:DescribeTable",
                "dynamodb:DeleteItem",
                "dynamodb:GetItem",
                "dynamodb:Scan",
                "dynamodb:Query",
                "dynamodb:UpdateItem"
            ],
            "Principal": {
                "AWS": [
                    "arn:aws:iam::123456789012:role/test-ddb-role-1",
                    "arn:aws:iam::123456789012:role/test-ddb-role-2",
                    "arn:aws:iam::123456789012:role/test-ddb-role-3"
                ]
            },
            "Resource": [
                "arn:aws:dynamodb:ap-southeast-2:123456789012:table/ddb-table-test"
            ]
        }
    ]
}
```

Following example from: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/iam-policy-example-data-crud.html

Resource handler returned message: "One or more parameter values were invalid: Invalid policy document: The following action names are invalid: "dynamodb:GetRecords", "dynamodb:GetShardIterator", "dynamodb:DescribeStream", "dynamodb:ListStreams" (Service: DynamoDb, Status Code: 400, ... HandlerErrorCode: InvalidRequest)

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

DynamoDB Table V2 should be created with expected resource policy given.

### Current Behavior

Failure to create DynamoDB Table V2

### Reproduction Steps

Repo: https://github.com/frankpengau/aws-cdk-ddbv2-resource-policy-issue

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.169.0

### Framework Version

_No response_

### Node.js Version

22.11.0

### OS

macOS Sonoma 14.7.1 (Darwin 23.6.0)

### Language

TypeScript

### Language Version

Typescript (5.6.3)

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Abogical**
### Issue # (if applicable)

Closes #32230.

### Reason for this change

`Table` and `TableV2` were adding actions `GetShardItem` and `GetRecord` to the table's resource policy for cross-account resources, service and account principals. The issue is that these actions are not supported in the resource policies. Hence creating a deployment failure

### Description of changes

Separated these actions to only be added to the IAM principal, but not the resource for `Table` and `TableV2` constructs.

### Describe any new or updated permissions being added

No new permissions are added. The `GetShardItem` and `GetRecord` permissions are removed for resource policies.

### Description of how you validated changes

Unit and Integration tests have been modified. The integration test failed to deploy before the fix, but now it succeeds after this fix.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-dynamodb/lib/table-grants.ts [hunk 1]
```diff
@@ -47,6 +47,12 @@ export interface TableGrantsProps {
  * A set of permissions to grant on a Table
  */
 export class TableGrants {
+  private static _add_principal_read_actions(grant: iam.Grant): iam.Grant {
+    if (grant.principalStatements.length > 0) {
+      grant.principalStatements[0].addActions(...perms.PRINCIPAL_ONLY_READ_DATA_ACTIONS);
```
Comment (rix0rrr) [inline packages/aws-cdk-lib/aws-dynamodb/lib/table-grants.ts]: This seems dangerous to me, making a lot of assumptions on what the `Grant` method actually returns.

Why not 2 different grants?

```ts
const x = Grant.addToPrincipalOrResource(...);
const y = Grant.addToPrincipal(...);
return x.combine(y);   // This might not exist but we could make it exist
```

Comment (rix0rrr) [reply packages/aws-cdk-lib/aws-dynamodb/lib/table-grants.ts]: (Also I definitely don't like this private static function -- this isn't Java, you can make free functions that are not attached to any class -- and the naming scheme isn't `camelCase`)

Comment (Abogical) [reply packages/aws-cdk-lib/aws-dynamodb/lib/table-grants.ts]: There is a combine function, but it creates 2 separate statements instead of just merging the actions. I didn't find a cleaner way to just add actions to an already existing policy statement.

Comment (Abogical) [reply packages/aws-cdk-lib/aws-dynamodb/lib/table-grants.ts]: I will edit the PR to use combine instead.

Comment (Abogical) [reply packages/aws-cdk-lib/aws-dynamodb/lib/table-grants.ts]: Done.

File: packages/aws-cdk-lib/aws-dynamodb/lib/table-grants.ts [hunk 2]
```diff
@@ -107,22 +111,15 @@ export class TableGrants {
    * @param grantee The principal to grant access to
    */
   public readData(grantee: iam.IGrantable): iam.Grant {
-    const actions = [...perms.READ_DATA_ACTIONS, perms.DESCRIBE_TABLE];
+    const actions = [...perms.RESOURCE_READ_DATA_ACTIONS, perms.DESCRIBE_TABLE];
```
Comment (kumvprat) [inline packages/aws-cdk-lib/aws-dynamodb/lib/table-grants.ts:114]: Can you attach a documentation link which talks about this ?

Mainly a documentation link that talks about the specific actions here being segregated into resource and principal only are limited to their respective counterparts.

Comment (Abogical) [reply packages/aws-cdk-lib/aws-dynamodb/lib/table-grants.ts:114]: I couldn't really find an official documentation that specifies which action is supported by resources and which is only supported by the principal. I only know by deploying these 2 actions that they fail to be attached to the resource.

File: packages/aws-cdk-lib/aws-dynamodb/lib/perms.ts [hunk 3]
```diff
@@ -1,12 +1,20 @@
...
   'dynamodb:BatchGetItem',
-  'dynamodb:GetRecords',
-  'dynamodb:GetShardIterator',
   'dynamodb:Query',
   'dynamodb:GetItem',
   'dynamodb:Scan',
   'dynamodb:ConditionCheckItem',
 ];
+
+export const PRINCIPAL_ONLY_READ_DATA_ACTIONS = [
```
Comment (kumvprat) [inline packages/aws-cdk-lib/aws-dynamodb/lib/perms.ts:9]: Based on this : https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazondynamodb.html#amazondynamodb-actions-as-permissions

These actions are only ever allowed for streams, and this is the [section of cdk code](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-dynamodb/lib/stream-grants.ts#L86-L96) that takes care of that. [Doc](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_GetRecords.html)

Are these allowed actions on simple table reads ?

Please share if I am missing something

File: packages/aws-cdk-lib/aws-dynamodb/lib/table-grants.ts (hunk 2 above)
Comment (kumvprat) [reply packages/aws-cdk-lib/aws-dynamodb/lib/table-grants.ts:114]: You can see : https://github.com/aws/aws-cdk/pull/36228#discussion_r2572227029

Comment (kumvprat) [reply packages/aws-cdk-lib/aws-dynamodb/lib/table-grants.ts:114]: This should be okay since `READ_STREAM_DATA_ACTIONS` also contains `dynamodb:DescribeStream` which is missing from these set of read permissions

This change should be backward compatible with existing setups and avoid giving full stream read accesses to users due to missing permissions

[Dynamo DB Actions](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazondynamodb.html#amazondynamodb-actions-as-permissions)

**Review by kumvprat — APPROVED** [review]
