### PR TITLE
fix(codedeploy): unable to remove alarms from deployment group

### LINKED ISSUE #23307: (codedeploy): unable to remove alarms from deployment group
### Describe the bug

At present, it is not possible to remove alarms from a deployment group using the CDK, once the alarms have been added to the deployment group.

### Expected Behavior

When you remove alarms from a deployment group, the alarms are disassociated from the deployment group.

### Current Behavior

The alarms are still associated with the deployment group.

### Reproduction Steps

Deploy the following stack:

```ts
const func = new lambda.Function(this, 'Function', {
  code: lambda.Code.fromInline('exports.handler = async () => {};'),
  handler: 'index.handler',
  runtime: lambda.Runtime.NODEJS_18_X
});

const alias = new lambda.Alias(this, 'Alias', {
  aliasName: 'alias',
  version: func.currentVersion
});

const alarm = new cloudwatch.Alarm(this, 'Alarm', {
  evaluationPeriods: 1,
  threshold: 1,
  metric: func.metricErrors()
});

new codedeploy.LambdaDeploymentGroup(this, 'DeploymentGroup', {
  alias,
  alarms: [alarm]
});
```

Remove the alarms, and update the stack

```ts
const func = new lambda.Function(this, 'Function', {
  code: lambda.Code.fromInline('exports.handler = async () => {};'),
  handler: 'index.handler',
  runtime: lambda.Runtime.NODEJS_18_X
});

const alias = new lambda.Alias(this, 'Alias', {
  aliasName: 'alias',
  version: func.currentVersion
});

const alarm = new cloudwatch.Alarm(this, 'Alarm', {
  evaluationPeriods: 1,
  threshold: 1,
  metric: func.metricErrors()
});

new codedeploy.LambdaDeploymentGroup(this, 'DeploymentGroup', {
  alias,
  // alarms: [alarm]
});
```

Observe the deployment group.

```json
{
    "deploymentGroupInfo": {
        "applicationName": "AppStack-DeploymentGroupApplication7B89ABEB-vHVXmlxfdO58",
        "deploymentGroupId": "18945fb8-75a1-45a4-8572-c4230602c822",
        "deploymentGroupName": "AppStack-DeploymentGroup6D277AF0-YVQ96F70YFZ5",
        "deploymentConfigName": "CodeDeployDefault.LambdaCanary10Percent5Minutes",
        "ec2TagFilters": [],
        "onPremisesInstanceTagFilters": [],
        "autoScalingGroups": [],
        "serviceRoleArn": "arn:aws:iam::***:role/AppStack-DeploymentGroupServiceRoleA00955F3-MGDC3WLZ3RZ8",
        "triggerConfigurations": [],
        "alarmConfiguration": {
            "enabled": true,
            "ignorePollAlarmFailure": false,
            "alarms": [
                {
                    "name": "AppStack-Alarm7103F465-DKDK1JADH0VI"
                }
            ]
        },
        "autoRollbackConfiguration": {
            "enabled": true,
            "events": [
                "DEPLOYMENT_FAILURE",
                "DEPLOYMENT_STOP_ON_ALARM"
            ]
        },
        "deploymentStyle": {
            "deploymentType": "BLUE_GREEN",
            "deploymentOption": "WITH_TRAFFIC_CONTROL"
        },
        "outdatedInstancesStrategy": "UPDATE",
        "computePlatform": "Lambda"
    }
}
```

### Possible Solution

`AlarmConfiguration.Enabled` needs to be set to `false` when there are no alarms.

### Additional Information/Context

_No response_

### CDK CLI Version

2.54.0

### Framework Version

_No response_

### Node.js Version

18

### OS

Mac OS

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by cecheta**
----

Closes #23307.

Disables CodeDeploy deployment group alarm configuration when alarms are removed from the deployment group. Also allows user to disable an alarm configuration even if alarms are associated with the group.

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [X] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [X] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-codedeploy/lib/ecs/deployment-group.ts [hunk 1]
```diff
@@ -146,6 +146,13 @@ export interface EcsDeploymentGroupProps {
    */
   readonly alarms?: cloudwatch.IAlarm[];
 
+  /**
+   * Whether to enable the alarm configuration.
+   *
+   * @default true if the deployment group is associated with alarms, otherwise false
+   */
+  readonly alarmsEnabled?: boolean;
+
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-codedeploy/lib/ecs/deployment-group.ts:155]: why does this need to be user-facing? The linked issue states that the alarms aren't being disabled when the alarms are finished. Can we just render alarms as disabled when there are no alarms?

**Review by comcalvi — CHANGES_REQUESTED** [review]
This PR adds an extra configuration property to solve a problem that's caused by the construct logic not automatically removing something that it should. Can we scope this back to remove the manual option, and just disable it as needed? If a user really needs to configure this by hand they can use escape hatches, unless there's a use case for manually configuring them.

File: packages/@aws-cdk/aws-codedeploy/lib/ecs/deployment-group.ts (hunk 1 above)
Comment (cecheta) [reply packages/@aws-cdk/aws-codedeploy/lib/ecs/deployment-group.ts]: Removed

File: packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-code-deploy.js.snapshot/aws-cdk-codepipeline-codedeploy.template.json [hunk 2]
```diff
@@ -59,6 +59,9 @@
       "Arn"
      ]
     },
+    "AlarmConfiguration": {
+     "Enabled": false
+    },
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-code-deploy.js.snapshot/aws-cdk-codepipeline-codedeploy.template.json:64]: A user upgrading to a new version will see this in their diff, which we try to avoid. I don't think there's a way around this here, and we can allow it for this change.

File: packages/@aws-cdk/aws-codedeploy/test/lambda/deployment-group.test.ts [hunk 3]
```diff
@@ -43,6 +43,10 @@ describe('CodeDeploy Lambda DeploymentGroup', () => {
           'Arn',
         ],
       },
+      AlarmConfiguration: {
+        Enabled: false,
+        Alarms: Match.absent(),
+      },
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-codedeploy/test/lambda/deployment-group.test.ts:49]: Please add a test that confirms that `AlarmConfiguration` can still be enabled.

**Review by comcalvi — DISMISSED** [review]
Nice work on this! Just an extra test and we can merge it.

File: packages/@aws-cdk/aws-codedeploy/test/lambda/deployment-group.test.ts (hunk 3 above)
Comment (cecheta) [reply packages/@aws-cdk/aws-codedeploy/test/lambda/deployment-group.test.ts:49]: Is it not already covered in existing tests?

https://github.com/cecheta/aws-cdk/blob/3c7e9b97515bbafa9919b69ba074b1313b02e389/packages/%40aws-cdk/aws-codedeploy/test/lambda/deployment-group.test.ts#L238

File: packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-code-deploy.js.snapshot/aws-cdk-codepipeline-codedeploy.template.json (hunk 2 above)
Comment (comcalvi) [reply packages/@aws-cdk/aws-codepipeline-actions/test/integ.pipeline-code-deploy.js.snapshot/aws-cdk-codepipeline-codedeploy.template.json:64]: This is a breaking change (however minor) so we need a feature flag for it. Take a look at #20765 for an example of adding a feature flag.

**Review by comcalvi — CHANGES_REQUESTED** [review]
This is a breaking change (however minor) so we need a feature flag for it. Take a look at #20765 for an example of adding a feature flag.

**Comment by cecheta** [comment]
> This is a breaking change (however minor) so we need a feature flag for it. Take a look at #20765 for an example of adding a feature flag.

Added

**Review by comcalvi — APPROVED** [review]
looks good granting provisional approval until the merge conflicts are fixed

**Review by comcalvi — APPROVED** [review]
