### PR TITLE
fix(cli): S3 asset uploads are rejected by commonly referenced encryption SCP (introduces bootstrap stack v9)

### LINKED ISSUE #11265: [cli] deploy cannot specify S3 SSE for asset upload
### Reproduction Steps

1. cdk bootstrap with legacy bootstrap, provide kms key id as param
2. have a SCP setup that denies s3:PutObject if s3:x-amz-server-side-encryption is missing
3. create a CDK app that provisions a lambda asset
4. execute cdk deploy
5. deploy fails and receive Access Denied error

### What did you expect to happen?
i expect CDK deploy to explicitly use the kms key i specified in the bootstrap when uploading assets.

### What actually happened?
cdk deploy does not provide SSE and the deploy fails with `Access Denied`.
It appears to be relying on the S3 default encryption instead of specifying the SSE options to the S3 put object request.

### Environment

  - **CLI Version      :** 1.71.0
  - **Framework Version:**
  - **Node.js Version:** v12.16.1
  - **OS               :** Windows 10
  - **Language (Version):** Python 3.8.5

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by ArlindNocaj**
Many organizations around the world have started to use a specific Service Control Policy (SCP) from this blog post: https://aws.amazon.com/blogs/security/how-to-prevent-uploads-of-unencrypted-objects-to-amazon-s3/ in order to make sure all S3 bucket uploads are encrypted.

CDK configures the `DefaultEncryptionConfiguration` on the bucket so that objects are always encrypted by default, but this specific SCP can only check that individual upload actions include the "enable encryption" option. That means that even though the end result would still be satisfied (objects are encrypted in S3), the SCP would nevertheless reject the CDK upload. We would rather people use AWS Config to make sure all buckets have `DefaultEncryptionConfiguration` set, so that this SCP is not necessary... but there is no arguing with deployed reality.

Change the CDK upload code path to first read out the default encryption configuration from the bucket, only to then mirror those exact same settings in the `PutObject` call so that the SCP can see that they are present.

This requires adding a new permission to the `cdk-assets` role, namely `s3:GetEncryptionConfiguration`, so requires a new bootstrap stack version: version 9.

If you want this new behavior because your organization applies this specific SCP, you must upgrade to bootstrap stack version 9. If you do not care about this new behavior you don't have to do anything: if the call to `getEncryptionConfiguration` fails, the CDK will fall back to the old behavior (not specifying any header).

Fixes #11265.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/cdk-assets/lib/private/handlers/files.ts [hunk 1]
```diff
@@ -44,17 +43,42 @@ export class FileAssetHandler implements IAssetHandler {
...
+    let paramsEncryption: {[index: string]:any}= {};
+    const encryption2 = await bucketEncryption(s3, destination.bucketName);
+    switch (encryption2) {
+      case BucketEncryption.NO_ENCRYPTION:
+        break;
+      case BucketEncryption.SSEAlgorithm_AES256:
+        paramsEncryption = { ServerSideEncryption: 'AES256' };
+        break;
+      case BucketEncryption.SSEAlgorithm_aws_kms:
+        paramsEncryption = { ServerSideEncryption: 'aws:kms' };
```
Comment (rix0rrr) [inline packages/cdk-assets/lib/private/handlers/files.ts:57]: Don't we potentially need to include the correct KMS key ARN? 

If the user has configured a custom key ARN as "DefaultEncryption" and we just pass `ServerSideEncryption: 'aws:kms'`, which key is going to be used? The user's key or `aws/s3` ?

File: packages/cdk-assets/lib/private/handlers/files.ts [hunk 2]
```diff
@@ -111,6 +135,39 @@ async function bucketOwnership(s3: AWS.S3, bucket: string): Promise<BucketOwners
...
 
+enum BucketEncryption {
+  NO_ENCRYPTION,
+  SSEAlgorithm_AES256,
+  SSEAlgorithm_aws_kms,
+  ACCES_DENIED,
+  DOES_NOT_EXIST
+}
+
+async function bucketEncryption(s3: AWS.S3, bucket: string) {
```
Comment (rix0rrr) [inline packages/cdk-assets/lib/private/handlers/files.ts:146]: Can we add caching to this function so we're not going to do the same lookup more than once?

File: packages/cdk-assets/lib/private/handlers/files.ts [hunk 3]
```diff
@@ -44,17 +43,42 @@ export class FileAssetHandler implements IAssetHandler {
...
+      case BucketEncryption.NO_ENCRYPTION:
+        break;
+      case BucketEncryption.SSEAlgorithm_AES256:
+        paramsEncryption = { ServerSideEncryption: 'AES256' };
+        break;
+      case BucketEncryption.SSEAlgorithm_aws_kms:
+        paramsEncryption = { ServerSideEncryption: 'aws:kms' };
+        break;
+      case BucketEncryption.DOES_NOT_EXIST:
+        this.host.emitMessage(EventType.UPLOAD, `No bucket named '${destination.bucketName}'. Is account ${await account()} bootstrapped?`);
```
Comment (rix0rrr) [inline packages/cdk-assets/lib/private/handlers/files.ts:60]: I'm not sure at what level `EventType.UPLOAD` shows, but I'd like this level to be one that is not displayed by default (but only if you add `-v`). Can you confirm that?

**Review by rix0rrr — CHANGES_REQUESTED** [review]

File: packages/cdk-assets/lib/private/handlers/files.ts (hunk 1 above)
Comment (ArlindNocaj) [reply packages/cdk-assets/lib/private/handlers/files.ts:57]: I tested the following setups
* encryption key type: a) Amazon S3 key (SSE-S3) -> yields to { ServerSideEncryption: 'AES256' };, no key configurable
* encryption key type: b) AWS Key Management Service key (SSE-KMS)
  * b1) AWS managed key (aws/s3)
  * b2) custom AWS KMS key

see details below for the configurations.

In summary:
We set the SSEAlgorithm, and the bucket automatically use whatever encryption is currently set up as default in the bucket. The bucket stores which is the default key to be used for default encryption. In fact the bucket would use the default encryption anyway but we need the header to get through the SCP rules.
I tried all the below scenarios below and deploy works.  It would not make sense for default encryption to use another key than configured in the bucket.

a)
```
{
    "ServerSideEncryptionConfiguration": {
        "Rules": [
            {
                "ApplyServerSideEncryptionByDefault": {
                    "SSEAlgorithm": "AES256"
                },
                "BucketKeyEnabled": false
            }
        ]
    }
}
```

b1)
```
{
    "ServerSideEncryptionConfiguration": {
        "Rules": [
            {
                "ApplyServerSideEncryptionByDefault": {
                    "SSEAlgorithm": "aws:kms",
                    "KMSMasterKeyID": "arn:aws:kms:us-east-1:703956386855:alias/aws/s3"
                },
                "BucketKeyEnabled": true
            }
        ]
    }
}
```

b2)
```
{
    "ServerSideEncryptionConfiguration": {
        "Rules": [
            {
                "ApplyServerSideEncryptionByDefault": {
                    "SSEAlgorithm": "aws:kms",
                    "KMSMasterKeyID": "arn:aws:kms:us-east-1:703956386855:key/833b292e-bc1f-47ec-af3f-1c1b6504815b"
                },
                "BucketKeyEnabled": true
            }
        ]
    }
}
```

Screenshot 2021-11-24 at 15 13 44

File: packages/cdk-assets/lib/private/handlers/files.ts (hunk 2 above)
Comment (ArlindNocaj) [reply packages/cdk-assets/lib/private/handlers/files.ts:146]: there are a lot of methods not being cached like bucketOwner etc. If we add caching it would make sense to add it to a level which ensures that the cache does have an effect. Right now I do not understand the system well enough to add caching.

Comment (rix0rrr) [reply packages/cdk-assets/lib/private/handlers/files.ts:146]: Fair enough. Will do that myself then.

File: packages/cdk-assets/lib/private/handlers/files.ts (hunk 3 above)
Comment (ArlindNocaj) [reply packages/cdk-assets/lib/private/handlers/files.ts]: the mapping is as follows:

```
const EVENT_TO_LEVEL: Record<EventType, LogLevel> = {
  build: 'verbose',
  cached: 'verbose',
  check: 'verbose',
  debug: 'verbose',
  fail: 'error',
  found: 'verbose',
  start: 'info',
  success: 'info',
  upload: 'verbose',
};
```

Nevertheless, adjusted logging to debug type since message is not directly related to upload.

**Review by rix0rrr — APPROVED** [review]

File: packages/cdk-assets/lib/private/handlers/files.ts (hunk 1 above)
Comment (vludax) [reply packages/cdk-assets/lib/private/handlers/files.ts:59]: Hmm that's odd -- the behaviour we are seeing is that when CDK only includes the `x-amz-server-side-encryption: aws:kms` header, the objects end up being encrypted with `aws/s3` key, which currently is not permitted by our bucket policy.

Comment (ArlindNocaj) [reply packages/cdk-assets/lib/private/handlers/files.ts:59]: @vludax 
Do you have default bucket encryption enabled for the bucket? 
Did you use `cdk bootstrap` to reinitialize the cdk resources? 
Can you also provide the bucket policy, so that I can reproduce it?

Comment (vludax) [reply packages/cdk-assets/lib/private/handlers/files.ts:59]: image
The following bucket policy statement blocks the uploads -- when we remove this statement, the files get uploaded successfully and encrypted with `aws/s3`:
```
{
    "Sid": "Enforce default bucket encryption by rejecting any overrides",
    "Effect": "Deny",
    "Principal": "*",
    "Action": "s3:PutObject",
    "Resource": "arn:aws:s3:::<bucket-name>/*",
    "Condition": {
        "Null": {
            "s3:x-amz-server-side-encryption": "false"
        },
        "StringNotLikeIfExists": {
            "s3:x-amz-server-side-encryption-aws-kms-key-id": "arn:aws:kms:ap-southeast-2:XXX:key/YYY"
        }
    }
}
```

We did not run the bootstrap as we are using a custom synthesizer in our CDK -- that doesn't seem to specify encryption options anywhere. I'd also note that our uploads are working as expected with v1.118.0 of the CDK -- the files are successfully uploaded and encrypted with the right KMS key with the above policy statement in place.

Comment (ArlindNocaj) [reply packages/cdk-assets/lib/private/handlers/files.ts:59]: @vludax please note that this is already being addressed and fixed here: https://github.com/aws/aws-cdk/issues/18262
