### PR TITLE
fix(cli): hotswapping StateMachines with a name fails

### LINKED ISSUE #17716: (CLI): Hotswap raises Invalid Arn when updating state machine definition
### What is the problem?

CDK deploy with hotswap fails with `Invalid ARN prefix` error as follows when updating a state definition :

```
> cdk deploy --hotswap

.......

MyWorkflow123456 failed: InvalidArn: Invalid Arn: 'Invalid ARN prefix: MyWorkflow123456'
    at Request.extractError (####/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (####/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (####/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (####/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (####/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (####/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at ####/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (####/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (####/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (####/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'InvalidArn',
  time: 2021-11-25T16:08:44.977Z,
  requestId: '###################',
  statusCode: 400,
  retryable: false,
  retryDelay: 40.19606554280166
}
Invalid Arn: 'Invalid ARN prefix: MyWorkflow123456'
```

This may be due to this: https://github.com/aws/aws-cdk/blob/557f9c33541e74f94ca6a3a3b70106a8160d766c/packages/aws-cdk/lib/api/hotswap/stepfunctions-state-machines.ts#L59

### Reproduction Steps

Deploying with `--hotswap` a state machine in my AWS / CDK environment. A normal deploy (without hotswap) works fine.

### What did you expect to happen?

AWS Step Functions State machine updated successfully with hotswap.

### What actually happened?

Command line failure to update AWS Step Functions state machine.

### CDK CLI Version

1.134.0 (build dd5e12d)

### Framework Version

_No response_

### Node.js Version

16.13.0

### OS

macOS 12.0.1 (Monterey)

### Language

Typescript

### Language Version

4.4.3

### Other information

_No response_

### PR DESCRIPTION
**Pull request by comcalvi**
Before, when the `stateMachineName` property was used, the value of `stateMachineName` was passed directly to the SDK where an ARN was required. Now, when the `stateMachineName` property is used, we construct the ARN from its value, and pass that ARN to the SDK.

Closes #17716

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk/lib/api/hotswap/stepfunctions-state-machines.ts [hunk 1]
```diff
@@ -12,14 +12,18 @@ export async function isHotswappableStateMachineChange(
   }
 
   const machineNameInCfnTemplate = change.newValue?.Properties?.StateMachineName;
-  const machineName = await establishResourcePhysicalName(logicalId, machineNameInCfnTemplate, evaluateCfnTemplate);
-  if (!machineName) {
+
+  const machineArn = machineNameInCfnTemplate ? await evaluateCfnTemplate.evaluateCfnExpression({
+    'Fn::Sub': 'arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:' + machineNameInCfnTemplate,
+  }) : await establishResourcePhysicalName(logicalId, machineNameInCfnTemplate, evaluateCfnTemplate);
```
[the remark this answers is not in the document]
Comment (skinny85) [reply packages/aws-cdk/lib/api/hotswap/stepfunctions-state-machines.ts:18]: Does it really make sense to call `establishResourcePhysicalName()` here (in the second branch of the ternary expression)? 

We know that `machineNameInCfnTemplate` is `undefined` in this branch, which means [this code](https://github.com/aws/aws-cdk/blob/8e3269b11ae013c74fd46046697ebd4d647bb7ed/packages/aws-cdk/lib/api/hotswap/common.ts#L66) will simply call `evaluateCfnTemplate.findPhysicalNameFor(logicalId);`.

Given that, can we just do that ourselves instead? Otherwise, this is pretty confusing code.

File: packages/aws-cdk/lib/api/hotswap/stepfunctions-state-machines.ts [hunk 2]
```diff
@@ -12,14 +12,18 @@ export async function isHotswappableStateMachineChange(
   }
 
   const machineNameInCfnTemplate = change.newValue?.Properties?.StateMachineName;
-  const machineName = await establishResourcePhysicalName(logicalId, machineNameInCfnTemplate, evaluateCfnTemplate);
-  if (!machineName) {
+
+  const machineArn = machineNameInCfnTemplate ? await evaluateCfnTemplate.evaluateCfnExpression({
```
Comment (skinny85) [inline packages/aws-cdk/lib/api/hotswap/stepfunctions-state-machines.ts:16]: Let's call this variable `stateMachineArn` instead.

File: packages/aws-cdk/lib/api/hotswap/stepfunctions-state-machines.ts [hunk 3]
```diff
@@ -12,14 +12,18 @@ export async function isHotswappableStateMachineChange(
   }
 
   const machineNameInCfnTemplate = change.newValue?.Properties?.StateMachineName;
```
Comment (skinny85) [inline packages/aws-cdk/lib/api/hotswap/stepfunctions-state-machines.ts:14]: Let's call this variable `stateMachineNameInTemplate` instead.

File: packages/aws-cdk/lib/api/hotswap/stepfunctions-state-machines.ts [hunk 4]
```diff
@@ -12,14 +12,18 @@ export async function isHotswappableStateMachineChange(
...
-  const machineName = await establishResourcePhysicalName(logicalId, machineNameInCfnTemplate, evaluateCfnTemplate);
-  if (!machineName) {
+
```
Comment (skinny85) [inline packages/aws-cdk/lib/api/hotswap/stepfunctions-state-machines.ts:15]: I don't think we need this empty line.

File: packages/aws-cdk/test/api/hotswap/state-machine-hotswap-deployments.test.ts [hunk 5]
```diff
@@ -168,14 +168,14 @@ test('calls the updateStateMachine() API when it receives a change to the defini
   });
 
   // WHEN
-  setup.pushStackResourceSummaries(setup.stackSummaryOf('Machine', 'AWS::StepFunctions::StateMachine', 'mock-machine-resource-id'));
+  setup.pushStackResourceSummaries(setup.stackSummaryOf('Machine', 'AWS::StepFunctions::StateMachine', 'mock-state-machine-arn'));
```
Comment (skinny85) [inline packages/aws-cdk/test/api/hotswap/state-machine-hotswap-deployments.test.ts:171]: Can we make these actual ARNs please?

File: packages/aws-cdk/test/api/hotswap/state-machine-hotswap-deployments.test.ts [hunk 6]
```diff
@@ -281,13 +281,14 @@ test('can correctly hotswap old style synth changes', async () => {
   });
 
   // WHEN
+  setup.pushStackResourceSummaries( setup.stackSummaryOf('Machine', 'AWS::StepFunctions::StateMachine', 'mock-state-machine-arn'));
```
Comment (skinny85) [inline packages/aws-cdk/test/api/hotswap/state-machine-hotswap-deployments.test.ts:284]:
```suggestion
  setup.pushStackResourceSummaries(setup.stackSummaryOf('Machine', 'AWS::StepFunctions::StateMachine', 'mock-state-machine-arn'));
```

Comment (skinny85) [reply packages/aws-cdk/test/api/hotswap/state-machine-hotswap-deployments.test.ts:284]: Again, let's make these actual ARNs.

Comment (skinny85) [reply packages/aws-cdk/test/api/hotswap/state-machine-hotswap-deployments.test.ts:284]: And let's make them consistent with the physical name of the resource, not different.

File: packages/aws-cdk/test/api/hotswap/state-machine-hotswap-deployments.test.ts [hunk 7]
```diff
@@ -348,7 +349,7 @@ test('calls the updateStateMachine() API when it receives a change to the defini
 
   // WHEN
   setup.pushStackResourceSummaries(
-    setup.stackSummaryOf('Machine', 'AWS::StepFunctions::StateMachine', 'mock-machine-resource-id'),
+    setup.stackSummaryOf('Machine', 'AWS::StepFunctions::StateMachine', 'mock-state-machine-arn'),
```
Comment (skinny85) [inline packages/aws-cdk/test/api/hotswap/state-machine-hotswap-deployments.test.ts:352]: Again, let's make these actual ARNs.

File: packages/aws-cdk/test/api/hotswap/state-machine-hotswap-deployments.test.ts [hunk 8]
```diff
@@ -446,7 +447,7 @@ test("will not perform a hotswap deployment if it doesn't know how to handle a s
     },
   });
   setup.pushStackResourceSummaries(
-    setup.stackSummaryOf('Machine', 'AWS::StepFunctions::StateMachine', 'my-machine'),
+    setup.stackSummaryOf('Machine', 'AWS::StepFunctions::StateMachine', 'arn:aws:states:here:123456789012:stateMachine:my-machine'),
```
Comment (skinny85) [inline packages/aws-cdk/test/api/hotswap/state-machine-hotswap-deployments.test.ts:450]: Like here 🙂.

**Review by skinny85 — CHANGES_REQUESTED** [review]
Looks great! A few minor comments before we merge this in.

**Review by skinny85 — APPROVED** [review]
👍
