### PR TITLE
fix(ssm): malformed ARNs for parameters with physical names that use path notation

### LINKED ISSUE #2777: SSM Module: String Parameter assumes parameter will have a '/' at the front of the string.
**Describe the bug**

When creating a string parameter in SSM parameter store, CDK makes the assumption that a '/' will be placed in front of the parameter. This is not a requirement of SSM parameter store; hence, when creating a parameter without a '/' in the front of the string and granting access from another resource to this parameter, cdk will provide an ARN that is invalid. This isn't immediately noticable as the IAM policy will still get created, but one would have to dig to figure out why the requested access is not working as expected. 

See here:

https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-ssm/lib/parameter.ts#L125

**To Reproduce**

`cdk deploy`

app.py:

```python
#!/usr/bin/env python3

from aws_cdk import (
    aws_lambda,
    aws_ssm,
    cdk
)


class LambdaTestSSMParam(cdk.Stack):
    def __init__(self, app: cdk.App, id: str) -> None:
        super().__init__(app, id)

        string_param = aws_ssm.StringParameter(
            self, "StringParameterWithoutSlash",
            name="NO_SLASH_STRING_PARAM",
            string_value="test"
        )

        # If you want to see the function actually fail due to lack of permissions
        lambda_code = """
#!/usr/bin/env python3
def lambda_handler(event, context):
    import boto3 
    client = boto3.client('ssm')
    return client.get_parameter(
        Name='{}',
        WithDecryption=False
    )
""".format(string_param.parameter_name)

        lambda_function = aws_lambda.Function(
            self, "BasicLambda",
            code=aws_lambda.InlineCode(lambda_code),
            handler="index.lambda_handler",
            timeout=30,
            runtime=aws_lambda.Runtime.PYTHON37,
        )

        string_param.grant_read(lambda_function)


app = cdk.App()
LambdaTestSSMParam(app, "LambdaCronExample")
app.run()
```

IAM policy that is created:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "ssm:DescribeParameters",
                "ssm:GetParameter",
                "ssm:GetParameterHistory"
            ],
            "Resource": "arn:aws:ssm:us-west-2:580961807929:parameterNO_SLASH_STRING_PARAM",
            "Effect": "Allow"
        }
    ]
}
```

**Expected behavior**

IAM Policy : 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "ssm:DescribeParameters",
                "ssm:GetParameter",
                "ssm:GetParameterHistory"
            ],
            "Resource": "arn:aws:ssm:us-west-2:580961807929:parameter/NO_SLASH_STRING_PARAM",
            "Effect": "Allow"
        }
    ]
}
```

**Version:**
 - Mac OSX 10.13.6
 - Python 3.7.3
 - CDK Version: `0.33.0 (build 50d71bf)`

### LINKED ISSUE #4803: ssm: malformed ARNs for parameters with physical names that use path notation
Code that was working is suddenly failing on an IAM mismatch.   We suspect a CDK update is the culprit.
Currently working to isolate it. The "proof" is in the Error Log section below.
Have reproduced the error using a minimum of independent code, shown below.

### Reproduction Steps

    const role = new Role(this, 'myRole', {
      assumedBy: new ServicePrincipal('lambda.amazonaws.com'),
    })

    const param = new StringParameter(this, 'myParam', {
      stringValue: 'myValue',
      parameterName: '/path/to/parameter',
    })

    const readSsmStatement = new PolicyStatement({ effect: Effect.ALLOW })
    readSsmStatement.addActions('ssm:DescribeParameters', 'ssm:GetParameter')
    readSsmStatement.addResources(param.parameterArn)

    role.addToPolicy(readSsmStatement)

Deploy this and you will see the double // in the Resource section of the policy statement

### Error Log

AccessDeniedException: User: [redacted] is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-west-2:[redacted]:parameter/x/y/z

Where the generated IAM role contains:
          {
            "Action": [
              "ssm:DescribeParameters",
              "ssm:GetParameter"
            ],
            "Resource": "arn:aws:ssm:us-west-2:[redacted]:parameter//x/y/z"
            "Effect": "Allow"
          }

Note the double // in the parameter ARN.        Manually edititng the role in the console fixes the problem.  We cannot, however get CDK to generate it properly.                     

### Environment

  - **CLI Version      :aws-cli/1.16.107 Python/2.7.16 Darwin/18.7.0 botocore/1.12.97**
  - **Framework Version:1.15.0**
  - **OS               :MacOS on desktop and Ubuntu in CI pipeline (both affected)**
  - **Language         :typescript**

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by eladb**
SSM parameter names can have one of two forms: “simpleName” or “/path/name”. This makes it impossible to render an ARN for the parameter is the name is an unresolvable token (such as a “Ref”) because we can’t decide whether a “/“ separator is required in the ARN. 

The previous implementation assumed "Ref" always returns the name without a "/" prefix, and therefore did not use the "/" separator. 

This fix will use the physical name itself (if possible) to determine the separator (and also assume that generated names will not use the path notation) and in the case where there is no concrete name to use, it requires that users explicitly specify the ARN separator through an attribute or a prop.

This change also adds a validation that verifies that if a physical name is provided and uses path notation, it must begin with a "/".

Fixes #4803 
Fixes #2777

Misc: re-add `install.sh` to call `npx yarn install`

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-ssm/lib/parameter.ts [hunk 1]
```diff
@@ -186,10 +187,25 @@ export enum ParameterType {
...
+   * Determines the separator used to render the ARN for the SSM parameter.
+   * Valid values are `"/"` or `""`.
+   *
+   * If `parameterName` is a path (i.e. begins with "/"), the separator must be
+   * `""`. Otherwise, it must be `"/"`.
+   *
+   * @default - automatically determined based on the value of `parameterName`
+   * unless it is a token, in which case this field is required.
+   */
+  readonly parameterArnSeparator?: string;
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-ssm/lib/parameter.ts]: Don't entirely understand why we need this. Doesn't a parameter name in an ARN always need to start with a `/`?

Comment (rix0rrr) [reply packages/@aws-cdk/aws-ssm/lib/parameter.ts]: Ah yeah this looks unused.

File: packages/@aws-cdk/aws-ssm/lib/util.ts [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+        return {
+          sep: physicalName.startsWith('/') ? '' : '/',
+          resourceName: parameterName
+        };
+      }
+
+      // parameterName is a token and physical name is not helping us (either missing or a token itself)
+      // in this use case we will need to synthesize a CloudFormation condition that will be used to determine
+      // if the name has a "/" prefix or not.
+      const startsWithSlash = startsWithCondition(scope as Construct, parameterName, "/");
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-ssm/lib/util.ts]: Oh shit. After thinking about it some more, I'm not sure this is going to work. At least, this won't work for `{ Refs }`s, as `Condition`s need to evaluate before `Resource`s are.

File: packages/@aws-cdk/aws-ssm/lib/parameter.ts (hunk 1 above)
Comment (eladb) [reply packages/@aws-cdk/aws-ssm/lib/parameter.ts]: yeah, old code. nice catch

File: packages/@aws-cdk/aws-ssm/lib/util.ts (hunk 2 above)
Comment (eladb) [reply packages/@aws-cdk/aws-ssm/lib/util.ts]: Yes, you are right:

```
 ❌  integ-parameter-arns failed: ValidationError: Template format error: Unresolved dependencies [StringDeployTime8EC8E402]. Cannot reference resources in the Conditions block of the template
```

File: install.sh [hunk 3]
```diff
@@ -0,0 +1,3 @@
+#!/bin/bash
+set -euo pipefail
+exec npx yarn install
```
Comment (rix0rrr) [inline install.sh]: `--frozen-lockfile`

File: packages/@aws-cdk/aws-ssm/lib/parameter.ts [hunk 4]
```diff
@@ -94,6 +95,18 @@ export interface ParameterOptions {
...
+   * Determines the separator used to render the ARN for this SSM parameter.
+   * Valid values are `"/"` or `""`.
+   *
+   * If `parameterName` is a path (i.e. begins with "/"), the separator must be
+   * an empty string `""`, otherwise, it must be `"/"`.
+   *
+   * @default - automatically determined based on the value of `parameterName`
+   * unless it is a token, in which case this field is required.
+   */
+  readonly parameterArnSeparator?: string;
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-ssm/lib/parameter.ts]: Why is this not simply a boolean `startsWithSlash` or not?

Comment (eladb) [reply packages/@aws-cdk/aws-ssm/lib/parameter.ts]: I don't know. I am dumb?

Comment (eladb) [reply packages/@aws-cdk/aws-ssm/lib/parameter.ts]: Will fix.

Comment (Chandru-B) [reply packages/@aws-cdk/aws-ssm/lib/parameter.ts]: Please fix!! I am getting **Unable to determine ARN separator for SSM parameter since the parameter name is an unresolved token. Use "fromAttributes" and specify "simpleName" explicitly**

Comment (eladb) [reply packages/@aws-cdk/aws-ssm/lib/parameter.ts]: Can you please raise a new issue with a retro?
