### PR TITLE
fix(dynamodb): replicas not created on table replacement

### LINKED ISSUE #12332: (aws-dynamodb): No replica created when new table created via Update event
### Reproduction Steps
1. Create a DynamoDB Table using AWS CDK with replication_regions set
```
aws_dynamodb.Table(
   self,
   "lcrCalculatorStatusTable",
   partition_key={"name": "RunId", "type": aws_dynamodb.AttributeType.STRING},
   sort_key=None,
   billing_mode=aws_dynamodb.BillingMode.PAY_PER_REQUEST,
   server_side_encryption=True,
   replication_regions=["eu-central-1"],
)
```
2. Synth and Deploy
3. Update the partition key of the Table using AWS CDK (RunId to RUN_ID in this case)
```
aws_dynamodb.Table(
   self,
   "lcrCalculatorStatusTable",
   partition_key={"name": "RUN_ID", "type": aws_dynamodb.AttributeType.STRING},
   sort_key=None,
   billing_mode=aws_dynamodb.BillingMode.PAY_PER_REQUEST,
   server_side_encryption=True,
   replication_regions=["eu-central-1"],
)
```
4. Synth and Deploy (CDK attempts to update the table, and subsequently creates a new one)

```
5/28 | 12:29:06 PM | UPDATE_IN_PROGRESS   | AWS::DynamoDB::Table                | lcrCalculatorStatusTable (lcrCalculatorStatusTable99128E5D) Requested update requires the creation of a new physical resource; hence creating one.
5/28 | 12:29:06 PM | UPDATE_IN_PROGRESS   | AWS::DynamoDB::Table                | lcrCalculatorStatusTable (lcrCalculatorStatusTable99128E5D) Resource creation Initiated
7/28 | 12:29:37 PM | UPDATE_COMPLETE      | AWS::DynamoDB::Table                | lcrCalculatorStatusTable (lcrCalculatorStatusTable99128E5D) 
```

### What did you expect to happen?
Since a new table is created as part of the update, I expected the new table to be automatically replicated and the deployment to succeed.

### What actually happened?
CDK attempts to create a new table with the new partition key but a replica is not created. This causes the DynamoDBReplica custom resource to hang in the UPDATE_COMPLETE_CLEANUP_IN_PROGRESS state.

Screenshot 2021-01-04 at 11 17 19

This eventually fails the deployment due to timeout
```
 15/28 | 1:00:51 PM | UPDATE_FAILED        | Custom::DynamoDBReplica             | lcrCalculatorStatusTable/Replicaeu-central-1/Default (lcrCalculatorStatusTableReplicaeucentral169ED77F2) Failed to update resource. Operation timed out
	new CustomResource (/tmp/jsii-kernel-ixys5V/node_modules/@aws-cdk/core/lib/custom-resource.js:28:25)
	\_ Table.createReplicaTables (/tmp/jsii-kernel-ixys5V/node_modules/@aws-cdk/aws-dynamodb/lib/table.js:875:35)
	\_ new Table (/tmp/jsii-kernel-ixys5V/node_modules/@aws-cdk/aws-dynamodb/lib/table.js:487:18)
	\_ /usr/local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:3556:49
	\_ Kernel._wrapSandboxCode (/usr/local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:4040:16)
	\_ Kernel._create (/usr/local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:3556:26)
	\_ Kernel.create (/usr/local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:3300:21)
	\_ KernelHost.processRequest (/usr/local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:13119:28)
	\_ KernelHost.run (/usr/local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:13057:14)
	\_ Immediate._onImmediate (/usr/local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:13060:37)
```

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:** CDK 1.74.0
  - **Node.js Version:** 12.20.0
  - **OS               :** [python:3.7 Docker Image](https://hub.docker.com/_/python) (running on Bitbucket Pipelines)
  - **Language (Version):** Python 3.7.9

### Other

I think the reason this happens is that despite creating a new table the event is marked as an Update (shown below). 

Screenshot 2021-01-04 at 12 01 01

The code generated by CDK to handle DynamoDB replication only checks for Create and Delete events, so a replica isn't created (shown below).

Screenshot 2021-01-04 at 16 27 25

This is reinforced by the fact that deleting and rebuilding the stack fixes the issue. CDK attempts to Create the table from scratch, rather than Update an existing one, and a replica is created successfully. If I update the partition key of the table again, I expect to run into this issue again.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by jogold**
Process `Update` events resulting from table replacements.

Include the table name in the physical resource id to receive a `Delete`
event when the table is replaced. This allows to clean "old" replicas.

Use a managed policy instead of an inline policy for the custom resource.
An update of the description property of a managed policy requires a
replacement. If we use the table name in the description it forces a
managed policy replacement when the table name changes. This way we preserve
permissions to delete old replicas in case of a table replacement: a new
managed policy with permissions for the new table is created during the
update phase and the old managed policy with permissions for the old table is
removed only during the update clean up phase.

The logical ID of the `SourceTableAttachedPolicy` needs to be updated because
CF doesn't allow to change a resource type.

Closes #12332

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jogold** [comment]
@skinny85 still need to fix the unit tests of the replica provider here but would love to have your feedback!

**Comment by jogold** [comment]
Successfully tested the following:
* Deploy `integ.global.js` with version on master
* Redeploy with version in this branch: existing replicas are preserved, inline policies are replaced by managed policies
* Update partition key from `id` to `new_id` and deploy: a new table is created, new managed policies are created, new replicas are created, old replicas are deleted, old managed policies are deleted, old table is deleted
* Delete stack: successful

**Comment by skinny85** [comment]
Sorry @jogold , I was on vacation. I'll look at the PR this week.

Thanks for the contribution!

File: packages/@aws-cdk/aws-dynamodb/lib/replica-handler/index.ts [hunk 1]
```diff
@@ -5,27 +5,37 @@ import { DynamoDB } from 'aws-sdk'; // eslint-disable-line import/no-extraneous-
...
   console.log('Event: %j', event);
 
-  /**
-   * Process only Create and Delete requests. We shouldn't receive any
-   * update request and in case we do there is nothing to update.
-   */
+  const dynamodb = new DynamoDB();
+
+  let updateTableAction: 'Create' | 'Update' | 'Delete';
+
```
Comment (skinny85) [inline packages/@aws-cdk/aws-dynamodb/lib/replica-handler/index.ts:11]: I wouldn't have an empty line here.

File: packages/@aws-cdk/aws-dynamodb/lib/replica-handler/index.ts [hunk 2]
```diff
@@ -5,27 +5,37 @@ import { DynamoDB } from 'aws-sdk'; // eslint-disable-line import/no-extraneous-
...
-      ],
-    }).promise();
-    console.log('Update table: %j', data);
+      },
+    ],
+  }).promise();
+  console.log('Update table: %j', data);
+
+  if (event.RequestType === 'Create' || event.RequestType === 'Update') {
+    return { PhysicalResourceId: `${event.ResourceProperties.TableName}-${event.ResourceProperties.Region}` };
```
Comment (skinny85) [inline packages/@aws-cdk/aws-dynamodb/lib/replica-handler/index.ts:35]: This is actually 2 functional changes, correct?

1. Previously, we returned `PhysicalResourceId` also for deletes, now we don't.
2. We used to return `event.ResourceProperties.Region` as the physical ID, now we return `` `${event.ResourceProperties.TableName}-${event.ResourceProperties.Region}` ``.

So, is 1. intentional, or accidental? And what about 2. - what will be the behavior for existing customers of global DB Tables?

File: packages/@aws-cdk/aws-dynamodb/lib/replica-handler/index.ts [hunk 3]
```diff
@@ -5,27 +5,37 @@ import { DynamoDB } from 'aws-sdk'; // eslint-disable-line import/no-extraneous-
...
   }
 
-  return { PhysicalResourceId: event.ResourceProperties.Region };
+  return {};
```
Comment (skinny85) [inline packages/@aws-cdk/aws-dynamodb/lib/replica-handler/index.ts:38]: Can we actually rewrite this into one expression instead?

```suggestion
  return event.RequestType === 'Create' || event.RequestType === 'Update'
    ? { PhysicalResourceId: `${event.ResourceProperties.TableName}-${event.ResourceProperties.Region}` }
    : {};
```

File: packages/@aws-cdk/aws-dynamodb/lib/table.ts [hunk 4]
```diff
@@ -1670,12 +1670,19 @@ interface ScalableAttributePair {
...
-
-    const policy = new iam.Policy(this, 'Resource', { roles: [role] });
+    super(sourceTable, `SourceTableAttachedManagedPolicy-${Names.nodeUniqueId(role.node)}`);
+
+    const policy = new iam.ManagedPolicy(this, 'Resource', {
+      // A CF update of the description property of a managed policy requires
+      // a replacement. Use the table name in the description to force a managed
+      // policy replacement when the table name changes. This way we preserve permissions
+      // to delete old replicas in case of a table replacement.
+      description: `DynamoDB replication managed policy for table ${sourceTable.tableName}`,
```
Comment (skinny85) [inline packages/@aws-cdk/aws-dynamodb/lib/table.ts:1683]: This is an awesome trick! I'll have to remember this one to use in other Custom Resources.

I'm just a little worried about the delete order - since this depends on the Table, won't it be deleted first, before the replica?

**Review by skinny85 — DISMISSED** [review]
Some comments/question, but in general looks great as always @jogold !

Did you go through an entire cycle of 1) creating a global Table with the old code, 2) updating the Table to this new code, to see if nothing breaks, 3) forcing a replacement, and 4) verifying the replacement is handled correctly? If not, could you please? Thanks!

**Comment by jogold** [comment]
> Did you go through an entire cycle of 1) creating a global Table with the old code, 2) updating the Table to this new code, to see if nothing breaks, 3) forcing a replacement, and 4) verifying the replacement is handled correctly? If not, could you please? Thanks!

Yes, see https://github.com/aws/aws-cdk/pull/13300#issuecomment-786802544

File: packages/@aws-cdk/aws-dynamodb/lib/replica-handler/index.ts (hunk 2 above)
Comment (jogold) [reply packages/@aws-cdk/aws-dynamodb/lib/replica-handler/index.ts:35]: For existing users of global DB tables if they update to new the code the only thing that will happen is the replacement of the inline policies with managed policies. This is because nothing changes on the properties of the custom resource so it won't receive any event (Create/Update/Delete).

Now if later a user decides to remove one or more replica regions, the custom resource will receive a Delete event. If we don't change how the physical resource id is returned for a Delete event then CF will receive a new physical resource id (`table-region` instead of `region`). Changing the physical resource id in a Delete event is not allowed by CF and the Delete will fail (from a CF perspective and this also means that it will not wait for `isComplete`). So yes 1. is intentional.

Returning an empty object on delete ensures that the custom resource provider framework uses the physical resource id from the event (should have been done in the first place).

File: packages/@aws-cdk/aws-dynamodb/lib/table.ts (hunk 4 above)
Comment (jogold) [reply packages/@aws-cdk/aws-dynamodb/lib/table.ts:1683]: This is fine because it depends on the role used by `onEventHandler` and `isCompleteHandler`, see also https://github.com/aws/aws-cdk/pull/8224 for more context on this `SourceTableAttachedPolicy`

See also my test https://github.com/aws/aws-cdk/pull/13300#issuecomment-786802544.

**Review by skinny85 — APPROVED** [review]
Thanks for the fix @jogold!
