### PR TITLE
fix(s3): add support for uppercase characters in legacy bucket names

### LINKED ISSUE #31731: aws-s3: Unable to use Bucket.fromBucketName on legacy s3 bucket with Uppcase Letters in the name
### Describe the bug

I'm attempting to reference an s3 bucket in my cdk code that was created in **2013** outside of cdk. The bucket has Capital letters in its name, which was legal for buckets before March 1, 2018 (new buckets can't have Capital letters  or underscores in their names). I've tried referencing the bucket with both Bucket.fromBucketName and Bucket.fromBucketAttributes, but both throw this error:
(note that I've slightly changed the name of the actual bucket for privacy)

Error: Invalid S3 bucket name (value: ABCD_Central_1)
Bucket name must only contain lowercase characters and the symbols, period (.), underscore (_), and dash (-) (offset: 0)
Bucket name must start and end with a lowercase character or number (offset: 0)
    at Function.validateBucketName (cdk-bug-test/node_modules/aws-cdk-lib/aws-s3/lib/bucket.js:1:19752)
    at Function.fromBucketAttributes (cdk-bug-test/node_modules/aws-cdk-lib/aws-s3/lib/bucket.js:1:15111)
    at Function.fromBucketName (cdk-bug-test/node_modules/aws-cdk-lib/aws-s3/lib/bucket.js:1:14511)

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

I expect to be able to import the bucket.

### Current Behavior

See error message in the description

### Reproduction Steps

```
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';

export class CdkBugTestStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    //
    let bucket = cdk.aws_s3.Bucket.fromBucketName(this, 'test-bucket', 'ABCD_Central_1');
    // also didnt work
    //let fromBucketName = cdk.aws_s3.Bucket.fromBucketArn(this, 'test-bucket', 'arn:aws:s3:::ABCD_Central_1');
    /*let fromBucketName = cdk.aws_s3.Bucket.fromBucketAttributes(this, 'test-bucket', {
      bucketName: 'NDAR_Central_1'
    });*/
  }
}

```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.161.1

### Framework Version

_No response_

### Node.js Version

v20.15.0

### OS

Ubuntu via (Window Subsystem for Linux)

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by 5d**
### Issue # (if applicable)

Closes #31731

### Reason for this change

As @GavinZZ [commented](https://github.com/aws/aws-cdk/issues/31731#issuecomment-2417649670) in issue #31731, the official AWS S3 documentation stated that uppercase characters were permitted in bucket names prior to March 1, 2018.

### Description of changes

- add support for uppercase characters in legacy bucket names

### Description of how you validated changes

- added new unit test cases and updated the integration test cases with legacy bucket names

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-s3/lib/bucket.ts [hunk 1]
```diff
@@ -1897,24 +1897,37 @@ export class Bucket extends BucketBase {
...
-    if (!/[a-z0-9]/.test(bucketName.charAt(bucketName.length - 1))) {
-      errors.push('Bucket name must start and end with a lowercase character or number '
-        + `(offset: ${bucketName.length - 1})`);
+    if (!allowedEdgeCharsetRegEx.test(bucketName.charAt(bucketName.length - 1))) {
+      errors.push(allowLegacyBucketNaming
+        ? 'Bucket name must start and end with an uppercase, lowercase character or number'
+        : 'Bucket name must start and end with a lowercase character or number'
+        + ` (offset: ${bucketName.length - 1})`,
+      );
     }
```
Comment (moelasmar) [inline packages/aws-cdk-lib/aws-s3/lib/bucket.ts:1925]: nit: either you merge the 2 checks in 1 check, and use the current generic error message (start or end) .. or to give different error messaging for each scenario

**Review by moelasmar — DISMISSED** [review]
in general it looks good, left some minor comment

**Review by moelasmar — APPROVED** [review]

**Review by moelasmar — APPROVED** [review]
