### PR TITLE
fix(ecs-patterns): taskDefinition ignored by queueProcessingFargateService

### LINKED ISSUE #27360: aws-ecs-patterns: taskDefinition prop ignored on QueueProcessingFargateService
### Describe the bug

I am trying to set up a Fargate task that processes items from an SQS queue and stumbled onto the `QueueProcessingFargateService` construct which appears to do just that. However, after configuring the construct, I am getting the following error when running `cdk deploy`:

```
"Invalid request provided: Create TaskDefinition: Container list cannot be empty. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: 00000000-0000-0000-0000-000000000000; Proxy: null)"
```

### Expected Behavior

The CDK stack deploys successfully.

### Current Behavior

The CDK stack fails to deploy.

```bash
> cdk@0.0.0 cdk
> cdk deploy --require-approval never

✨  Synthesis time: 4.1s

ProjectStack:  start: Building db6c89048d09ecd82cfbaeaa88cd73a91eb853fb29d321a61d90014df27f3740:************-*********
ProjectStack:  success: Built db6c89048d09ecd82cfbaeaa88cd73a91eb853fb29d321a61d90014df27f3740:************-*********
ProjectStack:  start: Publishing db6c89048d09ecd82cfbaeaa88cd73a91eb853fb29d321a61d90014df27f3740:************-*********
ProjectStack:  success: Published db6c89048d09ecd82cfbaeaa88cd73a91eb853fb29d321a61d90014df27f3740:************-*********
ProjectStack: deploying... [1/1]
ProjectStack: creating CloudFormation changeset...
ProjectStack |  0/18 | 2:54:13 PM | UPDATE_IN_PROGRESS   | AWS::CloudFormation::Stack                  | ProjectStack User Initiated
ProjectStack |  0/18 | 2:54:19 PM | UPDATE_IN_PROGRESS   | AWS::IAM::Policy                            | QueueProcessingService/QueueProcessingTaskDef/TaskRole/DefaultPolicy (QueueProcessingServiceQueueProcessingTaskDefTaskRoleDefaultPolicy0AD99632)
ProjectStack |  0/18 | 2:54:19 PM | UPDATE_IN_PROGRESS   | AWS::IAM::Policy                            | QueueProcessingService/QueueProcessingTaskDef/ExecutionRole/DefaultPolicy (QueueProcessingServiceQueueProcessingTaskDefExecutionRoleDefaultPolicyC4BA62EF)
ProjectStack |  0/18 | 2:54:19 PM | UPDATE_IN_PROGRESS   | AWS::ECS::TaskDefinition                    | TaskDefinition (TaskDefinitionB36D86D9) Requested update requires the creation of a new physical resource; hence creating one.
ProjectStack |  0/18 | 2:54:19 PM | UPDATE_IN_PROGRESS   | AWS::ECS::TaskDefinition                    | QueueProcessingService/QueueProcessingTaskDef (QueueProcessingServiceQueueProcessingTaskDefAEA09787) Requested update requires the creation of a new physical resource; hence creating one.
ProjectStack |  0/18 | 2:54:20 PM | UPDATE_FAILED        | AWS::ECS::TaskDefinition                    | TaskDefinition (TaskDefinitionB36D86D9) Resource handler returned message: "Invalid request provided: Create TaskDefinition: Container list cannot be empty. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: 00000000-0000-0000-0000-000000000000; Proxy: null)" (RequestToken: 00000000-0000-0000-0000-000000000000, HandlerErrorCode: InvalidRequest)
ProjectStack |  0/18 | 2:54:21 PM | UPDATE_FAILED        | AWS::IAM::Policy                            | QueueProcessingService/QueueProcessingTaskDef/TaskRole/DefaultPolicy (QueueProcessingServiceQueueProcessingTaskDefTaskRoleDefaultPolicy0AD99632) Resource update cancelled
ProjectStack |  0/18 | 2:54:21 PM | UPDATE_FAILED        | AWS::IAM::Policy                            | QueueProcessingService/QueueProcessingTaskDef/ExecutionRole/DefaultPolicy (QueueProcessingServiceQueueProcessingTaskDefExecutionRoleDefaultPolicyC4BA62EF) Resource update cancelled
ProjectStack |  0/18 | 2:54:21 PM | UPDATE_FAILED        | AWS::ECS::TaskDefinition                    | QueueProcessingService/QueueProcessingTaskDef (QueueProcessingServiceQueueProcessingTaskDefAEA09787) Resource creation cancelled
ProjectStack |  0/18 | 2:54:21 PM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack                  | ProjectStack The following resource(s) failed to update: [QueueProcessingServiceQueueProcessingTaskDefExecutionRoleDefaultPolicyC4BA62EF, QueueProcessingServiceQueueProcessingTaskDefTaskRoleDefaultPolicy0AD99632, QueueProcessingServiceQueueProcessingTaskDefAEA09787, TaskDefinitionB36D86D9].
ProjectStack |  1/18 | 2:54:25 PM | UPDATE_COMPLETE      | AWS::ECS::TaskDefinition                    | TaskDefinition (TaskDefinitionB36D86D9)
ProjectStack |  1/18 | 2:54:25 PM | UPDATE_IN_PROGRESS   | AWS::IAM::Policy                            | QueueProcessingService/QueueProcessingTaskDef/ExecutionRole/DefaultPolicy (QueueProcessingServiceQueueProcessingTaskDefExecutionRoleDefaultPolicyC4BA62EF)
ProjectStack |  2/18 | 2:54:25 PM | UPDATE_COMPLETE      | AWS::ECS::TaskDefinition                    | QueueProcessingService/QueueProcessingTaskDef (QueueProcessingServiceQueueProcessingTaskDefAEA09787)
ProjectStack |  2/18 | 2:54:25 PM | UPDATE_IN_PROGRESS   | AWS::IAM::Policy                            | QueueProcessingService/QueueProcessingTaskDef/TaskRole/DefaultPolicy (QueueProcessingServiceQueueProcessingTaskDefTaskRoleDefaultPolicy0AD99632)
ProjectStack |  3/18 | 2:54:41 PM | UPDATE_COMPLETE      | AWS::IAM::Policy                            | QueueProcessingService/QueueProcessingTaskDef/ExecutionRole/DefaultPolicy (QueueProcessingServiceQueueProcessingTaskDefExecutionRoleDefaultPolicyC4BA62EF)
ProjectStack |  4/18 | 2:54:41 PM | UPDATE_COMPLETE      | AWS::IAM::Policy                            | QueueProcessingService/QueueProcessingTaskDef/TaskRole/DefaultPolicy (QueueProcessingServiceQueueProcessingTaskDefTaskRoleDefaultPolicy0AD99632)
ProjectStack |  5/18 | 2:54:44 PM | UPDATE_ROLLBACK_COMP | AWS::CloudFormation::Stack                  | ProjectStack
ProjectStack |  5/18 | 2:54:45 PM | DELETE_IN_PROGRESS   | AWS::ECS::TaskDefinition                    | QueueProcessingService/QueueProcessingTaskDef (QueueProcessingServiceQueueProcessingTaskDefAEA09787)
ProjectStack |  4/18 | 2:54:45 PM | DELETE_COMPLETE      | AWS::ECS::TaskDefinition                    | TaskDefinition (TaskDefinitionB36D86D9)
ProjectStack |  3/18 | 2:54:46 PM | DELETE_COMPLETE      | AWS::ECS::TaskDefinition                    | QueueProcessingService/QueueProcessingTaskDef (QueueProcessingServiceQueueProcessingTaskDefAEA09787)
ProjectStack |  4/18 | 2:54:46 PM | UPDATE_ROLLBACK_COMP | AWS::CloudFormation::Stack                  | ProjectStack

Failed resources:
ProjectStack | 2:54:20 PM | UPDATE_FAILED        | AWS::ECS::TaskDefinition                    | TaskDefinition (TaskDefinitionB36D86D9) Resource handler returned message: "Invalid request provided: Create TaskDefinition: Container list cannot be empty. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: 00000000-0000-0000-0000-000000000000; Proxy: null)" (RequestToken: 00000000-0000-0000-0000-000000000000, HandlerErrorCode: InvalidRequest)

❌  ProjectStack failed: Error: The stack named ProjectStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: Create TaskDefinition: Container list cannot be empty. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: 00000000-0000-0000-0000-000000000000; Proxy: null)" (RequestToken: 00000000-0000-0000-0000-000000000000, HandlerErrorCode: InvalidRequest)
at FullCloudFormationDeployment.monitorDeployment (/home/circleci/project/cdk/node_modules/aws-cdk/lib/index.js:467:10232)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.deployStack2 [as deployStack] (/home/circleci/project/cdk/node_modules/aws-cdk/lib/index.js:470:179911)
at async /home/circleci/project/cdk/node_modules/aws-cdk/lib/index.js:470:163159

❌ Deployment failed: Error: The stack named ProjectStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: Create TaskDefinition: Container list cannot be empty. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: 00000000-0000-0000-0000-000000000000; Proxy: null)" (RequestToken: 00000000-0000-0000-0000-000000000000, HandlerErrorCode: InvalidRequest)
at FullCloudFormationDeployment.monitorDeployment (/home/circleci/project/cdk/node_modules/aws-cdk/lib/index.js:467:10232)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.deployStack2 [as deployStack] (/home/circleci/project/cdk/node_modules/aws-cdk/lib/index.js:470:179911)
at async /home/circleci/project/cdk/node_modules/aws-cdk/lib/index.js:470:163159

The stack named ProjectStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: Create TaskDefinition: Container list cannot be empty. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: 00000000-0000-0000-0000-000000000000; Proxy: null)" (RequestToken: 00000000-0000-0000-0000-000000000000, HandlerErrorCode: InvalidRequest)

Exited with code exit status 1
```

### Reproduction Steps

```typescript
import { App, Duration, Stack, StackProps } from 'aws-cdk-lib';
import { DockerImageAsset } from 'aws-cdk-lib/aws-ecr-assets';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as ecs from 'aws-cdk-lib/aws-ecs';
import { QueueProcessingFargateService } from 'aws-cdk-lib/aws-ecs-patterns';
import { LogGroup } from 'aws-cdk-lib/aws-logs';
import * as path from 'node:path';
import { config } from '../config';

export class FargateServiceStack extends Stack {
  constructor(scope: App, id: string, props?: StackProps) {
    super(scope, id, props);

    const asset = new DockerImageAsset(this, 'TestDockerImage', {
      directory: path.join(__dirname, '..', '..', 'images', 'test'),
    });

    const vpc = ec2.Vpc.fromLookup(this, 'Vpc', {
      vpcName: config.vpcName,
    });

    const cluster = new ecs.Cluster(this, 'EcsCluster', {
      vpc,
      clusterName: config.clusterName,
    });

    const logGroup = new LogGroup(this, 'LogGroup', {
      logGroupName: config.logGroupName,
    });

    const logDriver = new ecs.AwsLogDriver({
      logGroup,
      streamPrefix: config.streamPrefix,
    });

    const taskDefinition = new ecs.FargateTaskDefinition(this, 'TaskDefinition', {
      cpu: 256,
      memoryLimitMiB: 512,
      runtimePlatform: {
        cpuArchitecture: ecs.CpuArchitecture.ARM64,
      },
    });

    new QueueProcessingFargateService(this, 'QueueProcessingAiService', {
      cluster,
      logDriver,
      taskDefinition,
      image: ecs.ContainerImage.fromDockerImageAsset(asset),
      enableLogging: true,
      maxScalingCapacity: 5,
      minScalingCapacity: 0,
      platformVersion: ecs.FargatePlatformVersion.VERSION1_4,
      serviceName: config.serviceName,
      visibilityTimeout: Duration.minutes(1),
    });
  }
}

```

### Possible Solution

Maybe I just misconfigured the construct? 🤷 

Is there some kind of underlying change needed to support `ecs.ContainerImage.fromDockerImageAsset(asset)` vs `ecs.ContainerImage.fromRegistry('test')`?

### Additional Information/Context

_No response_

### CDK CLI Version

2.99.0 (build 0aa1096)

### Framework Version

_No response_

### Node.js Version

18.18.0

### OS

ubuntu-2204:2023.02.1

### Language

Typescript

### Language Version

5.2.2

### Other information

_No response_

### PR DESCRIPTION
**Pull request by badmintoncryer**
Fixed a bug in queueProcessingFargateService where the taskDefinition provided as an argument was not being used, and a default taskDefinition was always being generated instead.

Closes #27360
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by badmintoncryer** [comment]
In QueueProcessingServiceBaseProps, the image is defined and this is inherited by both QueueProcessingEc2ServiceProps and QueueProcessingFargateServiceProps.

Here, I want to make the image mandatory for QueueProcessingEc2ServiceProps, but optional for QueueProcessingFargateServiceProps.

Currently, the definition in QueueProcessingServiceBaseProps is set as optional, and in QueueProcessingEc2Service, a check for props.image != null is being performed.

Is this approach acceptable? Please advise if there is a more preferable approach.

File: packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts [hunk 1]
```diff
@@ -65,27 +65,34 @@ export class QueueProcessingFargateService extends QueueProcessingServiceBase {
...
-      family: props.family,
-      runtimePlatform: props.runtimePlatform,
-    });
-
-    const containerName = props.containerName ?? 'QueueProcessingContainer';
+    if (props.taskDefinition != null && props.image != null) {
+      throw new Error('You must specify only one of TaskDefinition or Image');
+    } else if (props.taskDefinition != null) {
+      this.taskDefinition = props.taskDefinition;
+    } else if (props.image != null) {
```
Comment (lpizzinidev) [inline packages/aws-cdk-lib/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts:75]:
```suggestion
    if (props.taskDefinition && props.image) {
      throw new Error('You must specify only one of taskDefinition or image');
    } else if (props.taskDefinition) {
      this.taskDefinition = props.taskDefinition;
    } else if (props.image) {
```
Some cleanup.

File: packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/queue-processing-fargate-service.test.ts [hunk 2]
```diff
@@ -740,3 +740,52 @@ it('throws validation errors of the specific queue prop, when setting queue and
     });
   }).toThrow(new Error('visibilityTimeout can be set only when queue is not set. Specify them in the QueueProps of the queue'));
 });
+
+test('test Fargate queue worker service construct - with task definition', () => {
```
Comment (lpizzinidev) [inline packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/queue-processing-fargate-service.test.ts:744]: We should add test coverage for:
* `FargateTaskDefinition` with no taskDefinition or image
* `FargateTaskDefinition` with taskDefinition and image

Also, a test should be added for [`QueueProcessingEc2Service`](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-ecs-patterns/test/ec2/queue-processing-ecs-service.test.ts) to verify that an error is thrown if `image` is missing.

File: packages/aws-cdk-lib/aws-ecs-patterns/lib/ecs/queue-processing-ecs-service.ts [hunk 3]
```diff
@@ -103,9 +103,15 @@ export class QueueProcessingEc2Service extends QueueProcessingServiceBase {
...
    */
-  constructor(scope: Construct, id: string, props: QueueProcessingEc2ServiceProps) {
+  constructor(scope: Construct, id: string, props: QueueProcessingEc2ServiceProps = {}) {
     super(scope, id, props);
 
+    // In the queueProcessingFargateService, props.image is optional, which is why image is optional in the queue-processing-service-base.ts.
+    // However, in the queueProcessingEcsService, image is mandatory, so null checks have been introduced.
+    if (props.image == null) {
+      throw new Error('Cannot create a QueueProcessingEc2Service with props.image is undefined');
+    }
```
Comment (lpizzinidev) [inline packages/aws-cdk-lib/aws-ecs-patterns/lib/ecs/queue-processing-ecs-service.ts:113]:
```suggestion
    if (!props.image) {
      throw new Error('image must be specified for EC2 queue processing service');
    }
```
Documentation is already provided in the property's comments.

File: packages/aws-cdk-lib/aws-ecs-patterns/lib/base/queue-processing-service-base.ts [hunk 4]
```diff
@@ -38,8 +38,16 @@ export interface QueueProcessingServiceBaseProps {
...
   /**
    * The image used to start a container.
+   *
+   * For QueueProcessingFargateService:
+   * Either 'image' or 'taskDefinition' must be specified, but not both.
+   *
+   * For QueueProcessingEc2Service:
+   * 'image' is required and must be specified.
+   *
+   * @default - none
```
Comment (lpizzinidev) [inline packages/aws-cdk-lib/aws-ecs-patterns/lib/base/queue-processing-service-base.ts:48]:
```suggestion
   * For `QueueProcessingFargateService`, either `image` or `taskDefinition` must be specified, but not both.
   * For QueueProcessingEc2Service, `image` is required.
   *
   * @default - the image of the task definition is used for Fargate, required otherwise
```
Cleanup.

**Review by lpizzinidev — CHANGES_REQUESTED** [review]
Thanks for the contribution! 👍
Looks good overall, I left some comments for some cleanup and missing test cases.
Suggestion for title: `fix(ecs-patterns): taskDefinition ignored by queueProcessingFargateService`.

File: packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/queue-processing-fargate-service.test.ts (hunk 2 above)
Comment (badmintoncryer) [reply packages/aws-cdk-lib/aws-ecs-patterns/test/fargate/queue-processing-fargate-service.test.ts:744]: Thank you for the review! I have added the test cases and made the necessary adjustments.

File: packages/aws-cdk-lib/aws-ecs-patterns/lib/base/queue-processing-service-base.ts [hunk 5]
```diff
@@ -38,8 +38,13 @@ export interface QueueProcessingServiceBaseProps {
 
   /**
    * The image used to start a container.
+   *
+   * For `QueueProcessingFargateService`, either `image` or `taskDefinition` must be specified, but not both.
+   * For QueueProcessingEc2Service, `image` is required.
```
Comment (lpizzinidev) [inline packages/aws-cdk-lib/aws-ecs-patterns/lib/base/queue-processing-service-base.ts:43]:
```suggestion
   * For `QueueProcessingEc2Service`, `image` is required.
```

**Review by lpizzinidev — CHANGES_REQUESTED** [review]
Thanks 👍
I forgot to add backticks on the documentation during the first review, sorry for that.
If you could fix it then this will be good to go for me.

**Review by lpizzinidev — APPROVED** [review]

**Review by sumupitchayan — APPROVED** [review]

**Review by sumupitchayan — APPROVED** [review]
