### PR TITLE
fix(route53-targets): beanstalk allow specifying `hostedZoneId` to support token endpoint with default value derived from stack region or endpointUrl

### LINKED ISSUE #31843: Route53: ElasticBeanstalkEnvironmentEndpointTarget throws exception for single instance environment
### Describe the bug

I'm deploying elastic beanstalk single instance application and getting error when creating an A record alias to the EB environment. 

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

Exception is not thrown during sync/deploy and the alias A record is created

### Current Behavior

```
Unhandled exception. System.Exception: Cannot use an EBS alias as `environmentEndpoint`. You must find your EBS environment endpoint via the AWS console. See the Elastic Beanstalk developer guide: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customdomains.html
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Send[TRequest,TResponse](TRequest requestObject)
   at Amazon.JSII.Runtime.Services.Client.Create(CreateRequest request)
   at Amazon.JSII.Runtime.Services.Client.Create(String fullyQualifiedName, Object[] arguments, Override[] overrides, String[] interfaces)
   at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)
   at Constructs.Construct..ctor(DeputyProps props)
   at Amazon.CDK.Resource..ctor(DeputyProps props)
   at Amazon.CDK.AWS.Route53.RecordSet..ctor(DeputyProps props)
   at Amazon.CDK.AWS.Route53.ARecord..ctor(Construct scope, String id, IARecordProps props)
```

### Reproduction Steps

```csharp
CfnEnvironment env = ...
var hostedZone = HostedZone.FromLookup(this, "HostedZone", new HostedZoneProviderProps
{
    DomainName = props.HostedZoneName
});
var aRecord = new ARecord(this, "AliasRecord", new ARecordProps
{
    RecordName = props.DnsName,
    Zone = hostedZone,
    Target = RecordTarget.FromAlias(new ElasticBeanstalkEnvironmentEndpointTarget(env.AttrEndpointUrl))
});
```

### Possible Solution

_No response_

### Additional Information/Context

I know that `AttrEndpointUrl` returns IP address for the single instance deployment. I tried to resolve the environment url using a custom resource, but that didn't help either, though `environmentUrl` is accurate in response. 

```csharp
CfnEnvironment apiEnvironment;

var getEnvironmentUrl = new AwsCustomResource(this, "GetEnvironmentUrl", new AwsCustomResourceProps
{
    OnUpdate = new AwsSdkCall
    {
        Service = "elasticbeanstalk",
        Action = "DescribeEnvironments",
        Parameters = new Dictionary<string, object>
        {
            ["EnvironmentNames"] = new[] { apiEnvironment.EnvironmentName }
        },
        PhysicalResourceId = PhysicalResourceId.Of(DateTime.Now.ToString(CultureInfo.InvariantCulture))
    },
    Policy = AwsCustomResourcePolicy.FromSdkCalls(new SdkCallsPolicyOptions
    {
        Resources = AwsCustomResourcePolicy.ANY_RESOURCE
    })
});

getEnvironmentUrl.Node.AddDependency(apiEnvironment);

var environmentUrl = getEnvironmentUrl.GetResponseField("Environments.0.CNAME");
var hostedZone = HostedZone.FromLookup(this, "HostedZone", new HostedZoneProviderProps
{
    DomainName = "example.com"
});
var aRecord = new ARecord(this, "AliasRecord", new ARecordProps
{
    RecordName = "api.example.com",
    Zone = hostedZone,
    Target = RecordTarget.FromAlias(new ElasticBeanstalkEnvironmentEndpointTarget(environmentUrl))
});

aRecord.Node.AddDependency(getEnvironmentUrl);
```

Unfortunately, this produces the same exception. The only thing that helps is to hardcode the environment url

```csharp
var aRecord = new ARecord(this, "AliasRecord", new ARecordProps
{
    RecordName = "api.example.com",
    Zone = hostedZone,
    Target = RecordTarget.FromAlias(new ElasticBeanstalkEnvironmentEndpointTarget("hardcoded environment url"))
});
```

I found in the [source code](https://github.com/aws/aws-cdk/blob/f1e2f3b602899b28610849b8b55748f288f50fcd/packages/aws-cdk-lib/aws-route53-targets/lib/elastic-beanstalk-environment-target.ts#L17) that environment url doesn't support tokens. Why?

I believe if I write that in CloudFormation that would be simple `!Ref` to the function response value. 

### CDK CLI Version

2.162.1 (build 10aa526)

### Framework Version

_No response_

### Node.js Version

22.9.0

### OS

windows 11 - 22H2 (22621.4317)

### Language

.NET

### Language Version

.net 8

### Other information

_No response_

### PR DESCRIPTION
**Pull request by phuhung273**
### Issue # (if applicable)

Closes #31843

### Reason for this change
- Support Beanstalk environment endpoint as token

### Description of changes
- Allow user to specify Beanstalk `hostedZoneId`
- Default value if not specified derived from stack region or Beanstalk environment endpoint

### Description of how you validated changes
Unit + Integ

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-route53-targets/lib/elastic-beanstalk-environment-target.ts [hunk 1]
```diff
@@ -15,23 +15,25 @@ export class ElasticBeanstalkEnvironmentEndpointTarget implements route53.IAlias
   constructor( private readonly environmentEndpoint: string, private readonly props?: IAliasRecordTargetProps) {}
 
   public bind(record: route53.IRecordSet, _zone?: route53.IHostedZone): route53.AliasRecordTargetConfig {
-    if (cdk.Token.isUnresolved(this.environmentEndpoint)) {
-      throw new ValidationError('Cannot use an EBS alias as `environmentEndpoint`. You must find your EBS environment endpoint via the AWS console. See the Elastic Beanstalk developer guide: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customdomains.html', record);
+    let hostedZoneId: string | undefined;
+
+    let { region } = cdk.Stack.of(record);
```
Comment (shikha372) [inline packages/aws-cdk-lib/aws-route53-targets/lib/elastic-beanstalk-environment-target.ts:20]: i think this is not very transparent to the users that this will be auto-determined based on current region configured in stack, if I understand this problem correctly, issue occurs when environmentEndpoint is a token value, that doesn't necessarily mean that we want to determine the hosted zone id based on region, what would be better is to allow a prop for the hosted zone id instead.

**Review by shikha372 — DISMISSED** [review]
imo it should not be based on the stack region value, instead we allow users to pass in a prop for hostedzone id, let me know your thoughts on this.

File: packages/aws-cdk-lib/aws-route53-targets/lib/elastic-beanstalk-environment-target.ts (hunk 1 above)
Comment (phuhung273) [reply packages/aws-cdk-lib/aws-route53-targets/lib/elastic-beanstalk-environment-target.ts:20]: Concerning user experience not to add another prop, can we make it optional. If not specified then we use this logic to generate the correct zone id: `auto generate from environmentEndpoint or stack region`

Comment (shikha372) [reply packages/aws-cdk-lib/aws-route53-targets/lib/elastic-beanstalk-environment-target.ts:20]: yeah, i think default for an optional value should be okay, atleast they'll be aware of that it will be populated from the stack region in case its not provide

Comment (phuhung273) [reply packages/aws-cdk-lib/aws-route53-targets/lib/elastic-beanstalk-environment-target.ts]: Thanks for the suggestion, I've updated the implementation. Please have a look.

File: packages/aws-cdk-lib/aws-route53-targets/lib/shared.ts [hunk 2]
```diff
@@ -2,6 +2,13 @@
  * Properties the alias record target
  */
 export interface IAliasRecordTargetProps {
+  /**
+   * Target Hosted zone ID.
+   *
+   * @default - no hosted zone id, can be auto detected for some kinds of target
```
Comment (shikha372) [inline packages/aws-cdk-lib/aws-route53-targets/lib/shared.ts:8]:
```suggestion
   * @default - hosted zone ID for the EBS endpoint will be retrieved based on the stack's region.
```

**Review by shikha372 — APPROVED** [review]

**Comment by phuhung273** [comment]
@mergifyio requeue

**Comment by phuhung273** [comment]
Hi @shikha372, could you help me with this, it is stuck somehow.

**Review by shikha372 — APPROVED** [review]
