### PR TITLE
fix(codepipeline): S3 source Action with trigger=Events fails for bucketKey a Token

### LINKED ISSUE #9554: [aws-codepipeline-actions] Not able to use EVENTS based S3 trigger when bucketKey contains a CDK token
### The Question

I am trying to use `S3SourceAction` class to define a bunch of S3 sources for a Pipeline. The bucket key for the source action is determined during deployment time using a CFN custom resource. This is how I am building an object for `S3SourceAction`:

```java
public S3SourceAction createS3SourceAction(String projectName, Artifact outputArtifact) {
        // The getFileName() method will create a custom resource which will determine the filename.
        String bucketKey = "rpms/" + projectName + "/" + getFileName(projectName, artifactsBucketName);
        return S3SourceAction.Builder.create()
                .actionName(projectName)
                .bucket(artifactsBucket)
                .bucketKey(bucketKey)
                .output(outputArtifact)
                .trigger(S3Trigger.EVENTS)
                .build();
    }
```

Now, because the S3 trigger is set to EVENTS, CDK will automatically create a corresponding CloudWatch Events rule as a dependency. I noticed that the logical ID of the CW rule will include the bucket key in it. And because of the way I am setting bucket key, the bucket key contains a CDK token during stack synthesis.

So when I try to synthesize my stack, it throws the following error:
```
Exception in thread "main" software.amazon.jsii.JsiiException: Cannot use tokens in construct ID: <dynamically-generated-logical-ID>/rpms/${Token[Default.Response.4408]}
```

I came across [#1374](https://github.com/aws/aws-cdk/issues/1374) which explains why CDK does not allow to use tokens in construct ID. 

So my question is - Since I have no control over the logical ID of the dependent CloudWatch Events rule, is it possible to set an event based trigger on a dynamically generated bucket key? If there is a workaround or a better way to this then that would be great.

### Environment

  - **CDK CLI Version:**  1.42.0 (build 3b64241)
  - **Module Version:**  Same as CDK version (1.42.0)
  - **Node.js Version:**  v12.16.3
  - **OS:**  macOS Mojave
  - **Language (Version):**  Java 8

### PR DESCRIPTION
**Pull request by skinny85**
We use bucketKey to differentiate between multiple source actions
that observe the same bucket using trigger=Events.
However, we can't do that if bucketKey is a lazy value,
as Tokens can't be used as parts of identifier for the created Event.
So, check for that case explicitly.

Fixes #9554

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-codepipeline-actions/lib/s3/source-action.ts [hunk 1]
```diff
@@ -110,7 +110,12 @@ export class S3SourceAction extends Action {
   protected bound(_scope: Construct, stage: codepipeline.IStage, options: codepipeline.ActionBindOptions):
   codepipeline.ActionConfig {
     if (this.props.trigger === S3Trigger.EVENTS) {
-      const id = stage.pipeline.node.uniqueId + 'SourceEventRule' + this.props.bucketKey;
+      const id = stage.pipeline.node.uniqueId + 'SourceEventRule' +
+        // we can't use Tokens in construct IDs,
+        // however, if bucketKey is not a Token,
+        // we want it to differentiate between multiple actions
+        // observing the same Bucket with different keys
+        (Token.isUnresolved(this.props.bucketKey) ? '' : this.props.bucketKey);
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-codepipeline-actions/lib/s3/source-action.ts:118]: Using an empty string here is good enough for now, but I can already taste the next bug report coming in: "hey it doesn't work if I use 2 S3 source triggers based off of tokens"

**Comment by skinny85** [comment]
> I'd prefer you handle the case of multiple tokens as well but up to you.

@rix0rrr done! Let me know how you like it.

**Comment by skinny85** [comment]
Resolved conflicts related to #9637 . @rix0rrr this is still waiting for your review!
