### PR TITLE
fix(cli): colored text is unreadable when using light themes 

### LINKED ISSUE #5242: cli: improve colors used in CLI output to be friendly for dark/light background terminals
Screenshot 2019-11-28 at 16 33 04

### Reproduction Steps

Run `cdk init app --language=typescript` in a Terminal with a light background color. I used VS Code Insiders with the [i Light](https://marketplace.visualstudio.com/items?itemName=ctrlplusb.i-minimal-theme) color theme.

### Environment

  - **CLI Version      :** 1.18.0 (build bc924bc)
  - **Framework Version:**
  - **OS               :** macOS Catalina 10.15.1 (19B88)
  - **Language         :** 

### Other

In general I recommend disabling color output unless the user explicitly requests it.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by netroy**
fixes #5242

For someone using a light-colored background on their terminal, white colored text is unreadable.
This change respects the user's foreground color preferences.

### Light color scheme
light-theme

### Dark color scheme
dark-theme

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by shivlaks** [comment]
@netroy - mentioned this in #5242 but we have the `--no-color` option to support disabling color and style from console output.

Is there a gap that the option does not cover?

**Comment by netroy** [comment]
@shivlaks This change is still relevant for users with light colour scheme, who do want to use colours.
I suppose it comes down to the question: How many such users of CDK exist? and, If CDK should provide them with the same options as everyone else? or, Is it safe to assume that users of CDK predominately prefer dark color schemes.

**Comment by shivlaks** [comment]
> @shivlaks This change is still relevant for users with light colour scheme, who do want to use colours.
> I suppose it comes down to the question: How many such users of CDK exist? and, If CDK should provide them with the same options as everyone else? or, Is it safe to assume that users of CDK predominately prefer dark color schemes.

that makes more sense to me. Users who want colors in light-colored terminals should have a better experience. Can you add some screenshots of what this looks like (with light and dark colored terminals).

**Comment by netroy** [comment]
### For Dark scheme
Dark Scheme

### Currently for Light Scheme
Light Scheme (master)

### Proposed for Light Scheme
Light Scheme (proposed)

**Comment by netroy** [comment]
I just realized that `logging.print` is using `console.error`, which does it's own set of colors (in my case red).
I do believe we need a fix. But, I doubt the changes in this PR are alone going to fix it.

Also, the `colors.white` makes sense now. 
I think that it might have been done to override the color red from `console.error`.

@shivlaks if you believe that we should fix this, I can update `logging.ts` to directly use `stdout`/`stderr` instead, since none of the console API features are used, & the current code seems to be working around the defaults of that API. I can add some tests as well.

**Comment by netroy** [comment]
>     * Can you update the body of the request to capture the rationale as well as the screenshots with this implementation for posterity
will do

>     * There's a merge conflict to straighten out
done

>     * I'm wondering if there's something we could be doing to test this?
I'm open to ideas. The only thing i see, that I can test, is the behavior of the debug function. But testing that behavior seems unrelated to the changes in this PR.

**Comment by netroy** [comment]
@shivlaks can you please have a look at this again?
cheers :bowing_man:

**Comment by netroy** [comment]
rebased

**Comment by netroy** [comment]
@shivlaks just rebased this again.
Can you please have a look at this again?
Thanks

File: packages/aws-cdk/lib/logging.ts [hunk 1]
```diff
@@ -1,43 +1,33 @@
 import * as colors from 'colors/safe';
+import { Writable } from 'stream';
 import * as util from 'util';
 
-// tslint:disable:no-console the whole point of those methods is precisely to output to the console...
```
Comment (shivlaks) [inline packages/aws-cdk/lib/logging.ts]: it would be good to provide the rationale for dropping `console.*` and moving to using stdout/stderr and manually adding newlines - maybe in the commit body itself

Comment (netroy) [reply packages/aws-cdk/lib/logging.ts]: @shivlaks I did exactly that. the commit message says
> console methods use their own set of colors, which CDK then has to override.
Switching to stdout/stderr streams gets rid of this step.

**Comment by netroy** [comment]
Thanks a lot @shivlaks 🤗

**Comment by A-KL** [comment]
Hi, I'm working on a migration from SAM to CDK and it ran into an issue where CDK. Its output sometimes looks like a list of errors in AzureDevOps or locally (using .NET Core based process-runner), even if the process was successfully executed.

After investigation, I found these lines: https://github.com/aws/aws-cdk/blob/d7c40c5e6209de320d2b89f27e8684bebce35cf0/packages/aws-cdk/lib/logging.ts#L29

Looks like writing to `stderr` was intentional, but why??

File: packages/aws-cdk/lib/logging.ts [hunk 2]
```diff
@@ -1,43 +1,33 @@
...
-
-export function data(fmt: string, ...args: any[]) {
-  console.log(util.format(fmt, ...args));
-}
+export const debug = (fmt: string, ...args: any[]) => isVerbose && _debug(fmt, ...args);
+export const error = logger(stderr, [colors.red]);
+export const warning = logger(stderr, [colors.yellow]);
+export const success = logger(stderr, [colors.green]);
+export const highlight = logger(stderr, [colors.bold]);
+export const print = logger(stderr);
```
Comment (A-KL) [inline packages/aws-cdk/lib/logging.ts:29]: Hi, I'm working on a migration from SAM to CDK and it ran into an issue where CDK. Its output sometimes looks like a list of errors in AzureDevOps or locally (using .NET Core based process-runner), even if the process was successfully executed.

After investigation, I found these lines. Looks like writing to `stderr` was intentional, but why??
