### PR TITLE
fix(cdk): only make Outputs Exports when necessary

### LINKED ISSUE #903: core: Disable export-by-default
This might run us into Export limits at some point (50-ish per account?)

Suggested fix: only make them exports once `makeImportValue()` is called (or `export: true` is passed).

### LINKED ISSUE #1611: RestApi Endpoint Output Name & Export
The `Endpoint` child created by RestApi doesn't seem usable because it has random characters appended to it (e.g. apiEndpoint9349E63C) and the exported name collides across multiple stack instances (I'm synthesizing the stack once in a build step and deploying multiple instances of it from CodePipeline).

Can we remove the `Endpoint` child construct so 1) I don't have to use findChild to disable exporting the output (see below) and 2) I don't have unnecessary stack outputs?

```typescript
     const restApi = new api.RestApi(this, 'api', {
      restApiName: (new cdk.AwsStackName()) as any
    });
    // Don't export the stack output because it collides when multiple
    // CloudFormation stacks are created in one account.
    restApi.findChild('Endpoint')['export'] = undefined;

    new cdk.Output(this, 'Endpoint', {
      value: restApi.urlForPath(),
      disableExport: true
    });
```

### PR DESCRIPTION
**Pull request by rix0rrr**
Export names must be unique and can conflict, so automatically turning
every Output into an Export can lead to problems for customers who
deploy the same template multiple times. Especially when the outputs
are created for them and they have no control over them.

We'll turn Outputs into exports on-demand (when .makeImportValue() is
called).

Fixes #903, fixes #1611.

----

### Pull Request Checklist

* [x] Testing
  - Unit test added
  - __CLI change?:__ manually run [integration tests](https://github.com/awslabs/aws-cdk/blob/master/packages/aws-cdk/integ-tests/test.sh) and paste output as a PR comment
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/cdk/lib/cloudformation/output.ts [hunk 1]
```diff
@@ -16,21 +16,22 @@ export interface OutputProps {
...
+   * called.
    */
   export?: string;
 
   /**
    * Disables the automatic allocation of an export name for this output.
    *
-   * @default false, which means that an export name is either explicitly
-   * specified or allocated based on the output's logical ID and stack name.
+   * This disables use of `makeImportValue()` if `export` is  not given.
```
Comment (RomainMuller) [inline packages/@aws-cdk/cdk/lib/cloudformation/output.ts]: I would say `prohibits` rather than `disables` here... What is disabled is *auto-allocation of an export name*, and the corollary is you cannot use `makeImportValue()` unless an `export` name was provided at creation time.

File: packages/@aws-cdk/cdk/lib/cloudformation/output.ts [hunk 2]
```diff
@@ -76,16 +81,16 @@ export class Output extends StackElement {
     this._value = props.value;
     this.condition = props.condition;
 
+    this.disableExport = props.disableExport !== undefined ? props.disableExport : false;
```
Comment (RomainMuller) [inline packages/@aws-cdk/cdk/lib/cloudformation/output.ts]: `!!props.disableExport` ?

File: packages/@aws-cdk/cdk/lib/cloudformation/output.ts [hunk 3]
```diff
@@ -76,16 +81,16 @@ export class Output extends StackElement {
...
+
+    if (props.export && this.disableExport) {
+      throw new Error('Cannot set `disableExport` and specify an export name');
```
Comment (RomainMuller) [inline packages/@aws-cdk/cdk/lib/cloudformation/output.ts]: This seems to contradict what the `props` documentation says. But TBH I prefer this... And I'd suggest replacing `disableExport` with something like `exportable` (semantic is flipped:  if `!exportable`, then you cannot provide - or have allocated - an `export` name).

File: packages/@aws-cdk/cdk/lib/cloudformation/output.ts [hunk 4]
```diff
@@ -124,6 +132,19 @@ export class Output extends StackElement {
...
+  /**
+   * Automatically determine an output name for use with FnImportValue
+   *
+   * This gets called in case the user hasn't specified an export name but is
+   * taking an action that requires exporting. We namespace with the stack name
+   * to reduce chances of collissions between CDK apps.
+   */
+  private uniqueOutputName() {
+    // prefix export name with stack name since exports are global within account + region.
+    const stackName = require('./stack').Stack.find(this).name;
```
Comment (RomainMuller) [inline packages/@aws-cdk/cdk/lib/cloudformation/output.ts]: I do not like this inline `require` call. Why not import `Stack` normally?

File: packages/@aws-cdk/cdk/lib/cloudformation/output.ts [hunk 5]
```diff
@@ -124,6 +132,19 @@ export class Output extends StackElement {
...
+    return (stackName ? stackName + ':' : '') + this.logicalId;
```
Comment (RomainMuller) [inline packages/@aws-cdk/cdk/lib/cloudformation/output.ts]: Why bother for the case of an un-named stack? I guess this only ever happens in unit tests, where this shouldn't matter. I'd be up for using

```ts
return `${stackName}:${this.logicalId}`;
```

**Comment by eladb** [comment]
@rix0rrr any updates?

File: packages/@aws-cdk/cdk/lib/cloudformation/output.ts (hunk 4 above)
Comment (rix0rrr) [reply packages/@aws-cdk/cdk/lib/cloudformation/output.ts]: Cyclic dependencies. The core library is rife with them. :(

**Comment by tylerkatz** [comment]
This has not been added to the Golang CDK library.  Exports are automatically created.
