### PR TITLE
fix(rds): setting timezone on DatabaseInstance causes internal failure

### LINKED ISSUE #6439: Changing timezone or engineVersion on a DatabaseInstance results in an Internal Failure
When creating a Postgres RDS database as follows:
```
    const appDB = new DatabaseInstance(this, 'TestPostgresInstance', {
      engine: DatabaseInstanceEngine.POSTGRES,
      instanceClass: InstanceType.of(InstanceClass.BURSTABLE3, InstanceSize.MICRO),
      masterUsername: dbUserName,
      databaseName: dbName,
      vpc,
      allocatedStorage: 10,
      backupRetention: Duration.days(3),
    });
```

and then would like to add the `timezone` and `engineVersion` at a later time like so:
```
    const appDB = new DatabaseInstance(this, 'TestlPostgresInstance', {
      engine: DatabaseInstanceEngine.POSTGRES,
      instanceClass: InstanceType.of(InstanceClass.BURSTABLE3, InstanceSize.MICRO),
      masterUsername: dbUserName,
      databaseName: dbName,
      vpc,
      allocatedStorage: 10,
      backupRetention: Duration.days(3),
      timezone: 'Europe/Zurich',
      engineVersion: '11.5',
    });
```

It will always result in an `Internal Failure` and rollback the stack change.

I tried to determine the possible values for the `engineVersion` using:
```
aws rds describe-db-engine-versions --engine postgres --query "DBEngineVersions[].EngineVersion"
```

The chosen `engineVersion` mirrors the currently deployed one, the TZ is different from what I could gather.

### Reproduction Steps

Create a Database Instance as follows:
```
    const vpc = new Vpc(this, 'TestVPC', {
      natGateways: 1,
      maxAzs: 2,
    });

    const appDB = new DatabaseInstance(this, 'TestPostgresInstance', {
      engine: DatabaseInstanceEngine.POSTGRES,
      instanceClass: InstanceType.of(InstanceClass.BURSTABLE3, InstanceSize.MICRO),
      masterUsername: 'test',
      databaseName: 'test,
      vpc,
      allocatedStorage: 10,
      backupRetention: Duration.days(3),
    });
```

Deploy the stack; Afterwards change the code to the following:
```
    const appDB = new DatabaseInstance(this, 'TestPostgresInstance', {
      engine: DatabaseInstanceEngine.POSTGRES,
      instanceClass: InstanceType.of(InstanceClass.BURSTABLE3, InstanceSize.MICRO),
      masterUsername: 'test',
      databaseName: 'test',
      vpc,
      allocatedStorage: 10,
      backupRetention: Duration.days(3),
      timezone: 'Europe/Zurich',
      engineVersion: '11.5',
    });
```

Try to deploy the change.

### Error Log

Stack Event Log:

1. StackName UPDATE_IN_PROGRESS: User Initiated
2. DatabaseInstance UPDATE_FAILED: Internal Failure
3. StackName UPDATE_ROLLBACK_IN_PROGRESS: The following resource(s) failed to update: [DatabaseInstance].

### Environment

  - **CLI Version:** 1.25.0
  - **Framework Version:** 1.25.0
  - **OS:** MacOS
  - **Language:** English

### Other

The documentation regarding the possible values for `engineVersion` could be extended to at least document the necessary commands to determine allowed values. The same goes for the timezone documentation.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by nija-at**
Per documentation[1], 'Timezone' property is only supported on Microsoft
SQL Server. Setting this property on a DatabaseInstance with a different
database engine causes deployment to fail (1) with a validation error
for a new instance of `AWS::RDS::DBInstance` and (2) internal failure
when modifying an existing instance of `AWS::RDS::DBInstance`.

[1]:https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-timezone

fixes #6439

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-rds/lib/instance.ts [hunk 1]
```diff
@@ -678,6 +678,11 @@ abstract class DatabaseInstanceSource extends DatabaseInstanceNew implements IDa
     this.singleUserRotationApplication = props.engine.singleUserRotationApplication;
     this.multiUserRotationApplication = props.engine.multiUserRotationApplication;
 
+    if (props.timezone && props.engine !== DatabaseInstanceEngine.SQL_SERVER_EE && props.engine !== DatabaseInstanceEngine.SQL_SERVER_EX
```
Comment (eladb) [inline packages/@aws-cdk/aws-rds/lib/instance.ts]: Can we turn this into an array.contains instead of a long if statement?

File: packages/@aws-cdk/aws-rds/test/test.instance.ts [hunk 2]
```diff
@@ -685,4 +685,52 @@ export = {
...
+    const stack = new cdk.Stack();
+    const dbConfig = {
+      instanceClass: ec2.InstanceType.of(ec2.InstanceClass.C5, ec2.InstanceSize.SMALL),
+      masterUsername: 'master',
+      timezone: 'Europe/Zurich',
+      vpc: new ec2.Vpc(stack, 'myvpc'),
+    };
+
+    // THEN
+    test.ok(new rds.DatabaseInstance(stack, 'sqlserver-ee-db', {
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-rds/test/test.instance.ts]: These tests could be 2 `for` loops.

Comment (nija-at) [reply packages/@aws-cdk/aws-rds/test/test.instance.ts]: duh...
