### PR TITLE
fix(appsync): strongly type `expires` prop in apiKeyConfig

### LINKED ISSUE #8698: appsync - apiKeyConfig expires outputting incorrect format
When specifying the attribute "expires" for apiKeyConfig, the rendered cloudformation gets a value of null.

### Reproduction Steps
```
const api = new GraphQLApi(this, 'api', {
            name: getResourceName('graphql'),
            authorizationConfig: {
                defaultAuthorization: {
                    authorizationType: AuthorizationType.API_KEY,
                    apiKeyConfig: {
                        name: "api-key",
                        description: "api-key",
                        expires: "1614164998"
                    }
                },    
            schemaDefinitionFile: 'schema.graphql',
        });
```

### Error Log

Synth gives:
```
 apiapikeyApiKeyXXXXXX:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId:
        Fn::GetAtt:
          - apiCXXXXXX
          - ApiId
      Description: api-key
      Expires: null
```

### Environment

  - **CLI Version      :** 1.46.0
  - **Framework Version:** 1.46.0
  - **Node.js Version:** v12.16.1 
  - **OS               :** OSX
  - **Language (Version):** 3.8.3 

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by BryanPan342**
**[ISSUE]**
`apiKeyConfig` has prop `expires` that has unclear documentation/not strongly typed and is prone to user errors. 

**[APPROACH]**
Force `expires` to take `Expiration` class from `core` and will be able to output api key configurations easily through `Expiration` static functions: `after(...)`, `fromString(...)`, ` atDate(...)`, `atTimeStamp(...)`.

Fixes #8698 

BREAKING CHANGE:  force `apiKeyConfig` require a Expiration class instead of string
- **appsync**: Parameter `apiKeyConfig` takes `Expiration` class instead of `string`

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts [hunk 1]
```diff
@@ -118,12 +118,13 @@ export interface ApiKeyConfig {
   readonly description?: string;
 
   /**
-   * The time from creation time after which the API key expires, using RFC3339 representation.
+   * The time from creation time after which the API key expires.
    * It must be a minimum of 1 day and a maximum of 365 days from date of creation.
    * Rounded down to the nearest hour.
-   * @default - 7 days from creation time
+   *
+   * @default - 7 days rounded down to nearest hour
```
Comment (iliapolo) [inline packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts:125]: Why did you make this round to the nearest hour?

File: packages/@aws-cdk/core/lib/expires.ts [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+
+  private constructor(value: string, date: Date) {
+    this.value = value;
+    this.date = date;
+  }
+  /**
+   * Exipration Value in a formatted Unix Epoch Time in seconds
+   * @param format - round down to nearest formated number, default is seconds
+   */
+  public getEpoch(format?: EpochFormat): number {
```
Comment (iliapolo) [inline packages/@aws-cdk/core/lib/expires.ts:74]: Im not sure this method is warranted, nor does the `EpochFormat` enum. I only see one [usage](https://github.com/BryanPan342/aws-cdk/blob/appsync-expires/packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts#L527) of it that essentially could be replaced with `/ 1000` (which was also the original code). 

I'd rather not introduce code we don't really use, even if it might seem sensible.

File: packages/@aws-cdk/core/lib/expires.ts [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+   */
+  SECOND = 1000,
+}
+
+/**
+ * Represents a date of expiration.
+ *
+ * The amount can be specified either as a Date object, timestamp, Duration or string.
+ */
+export class Expires {
```
Comment (iliapolo) [inline packages/@aws-cdk/core/lib/expires.ts:30]: Lets add some tests

**Comment by iliapolo** [comment]
@BryanPan342 Note that breaking changes should be specified with a `BREAKING CHANGE` prefix in the PR body. Like so: https://github.com/aws/aws-cdk/pull/9016

File: packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts (hunk 1 above)
Comment (BryanPan342) [reply packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts:125]: The documentation [here](https://docs.aws.amazon.com/appsync/latest/APIReference/API_ApiKey.html) defines the `expires` parameter as:

> The time after which the API key expires. The date is represented as seconds since the epoch, rounded down to the nearest hour.

File: packages/@aws-cdk/core/lib/expires.ts (hunk 2 above)
Comment (BryanPan342) [reply packages/@aws-cdk/core/lib/expires.ts:74]: Fair, I originally had it in the `appsync` code but thought that it might be applicable elsewhere.

File: packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts (hunk 1 above)
Comment (iliapolo) [reply packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts:125]: @BryanPan342 Hmm, doesn't that mean though that they are doing the rounding? what happens if we send a 'non-rounded' epoch?

File: packages/@aws-cdk/core/lib/expires.ts (hunk 2 above)
Comment (iliapolo) [reply packages/@aws-cdk/core/lib/expires.ts:74]: 👍

File: packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts (hunk 1 above)
Comment (BryanPan342) [reply packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts:125]: Huh never tested that to be honest.. it probably rounds it for you but will try.

Comment (BryanPan342) [reply packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts:125]: oh sweet it does :) thanks for the insight

File: packages/@aws-cdk/core/lib/expires.ts [hunk 4]
```diff
@@ -0,0 +1,47 @@
+import { Duration } from './duration';
+/**
+ * Represents a date of expiration.
+ *
+ * The amount can be specified either as a Date object, timestamp, Duration or string.
+ */
+export class Expires {
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/expires.ts:7]: I think this should be called `Expiration` rather than `Expires`. Class names should be nouns.

File: packages/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts [hunk 5]
```diff
@@ -327,34 +326,6 @@ export enum StorageClass {
   DEEP_ARCHIVE = 'DEEP_ARCHIVE'
 }
 
-/**
- * Used for HTTP expires header, which influences downstream caches. Does NOT influence deletion of the object.
- * @see https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#SysMetadata
- */
-export class Expires {
```
Comment (eladb) [inline packages/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts:334]: Are we comfortable with this breaking change?

File: packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts [hunk 6]
```diff
@@ -518,23 +519,20 @@ export class GraphQLApi extends Construct {
...
-      expires = new Date(config.expires).valueOf();
-      const days = (d: number) =>
-        Date.now() + Duration.days(d).toMilliseconds();
-      if (expires < days(1) || expires > days(365)) {
-        throw Error('API key expiration must be between 1 and 365 days.');
-      }
-      expires = Math.round(expires / 1000);
+  private createAPIKey(config: ApiKeyConfig): string {
+    if (config.expires &&
+      (config.expires?.date < Expires.after(Duration.days(1)).date
```
Comment (eladb) [inline packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts:524]: Feels like it could be a useful method on `Expires`:

```ts
if (config.expires?.lessThan(Duration.days(1)) || config?.expires.greaterThan(Duration.days(365)) {
  throw new Error(...)
}

File: packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts [hunk 7]
```diff
@@ -518,23 +519,20 @@ export class GraphQLApi extends Construct {
...
-    if (config.expires) {
-      expires = new Date(config.expires).valueOf();
-      const days = (d: number) =>
-        Date.now() + Duration.days(d).toMilliseconds();
-      if (expires < days(1) || expires > days(365)) {
-        throw Error('API key expiration must be between 1 and 365 days.');
-      }
-      expires = Math.round(expires / 1000);
+  private createAPIKey(config: ApiKeyConfig): string {
+    if (config.expires &&
```
Comment (eladb) [inline packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts:523]: `if (config.expires)` is not needed since use use `.?`

File: packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts [hunk 8]
```diff
@@ -518,23 +519,20 @@ export class GraphQLApi extends Construct {
...
+      (config.expires?.date < Expires.after(Duration.days(1)).date
+        || config.expires?.date > Expires.after(Duration.days(365)).date)) {
+      throw Error('API key expiration must be between 1 and 365 days.');
     }
+    const getEpoch = (d: Expires) => { return Math.floor( d.date.getTime() / 86400000) * 86400; };
```
Comment (eladb) [inline packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts:528]: Add `expires.asEpoch()` perhaps?

File: packages/@aws-cdk/aws-appsync/test/appsync.auth.graphql [hunk 9]
```diff
@@ -0,0 +1,12 @@
+type test {
+  id: Int!
+  version: String!
+}
+
+type Query {
+  getTests: [ test! ]
```
Comment (eladb) [inline packages/@aws-cdk/aws-appsync/test/appsync.auth.graphql:7]: How is this related to this change?

File: packages/@aws-cdk/aws-appsync/test/integ.auth-apikey.ts [hunk 10]
```diff
@@ -0,0 +1,68 @@
...
+  removalPolicy: RemovalPolicy.DESTROY,
+});
+
+const testDS = api.addDynamoDbDataSource('testDataSource', 'Table for Tests"', testTable);
+
+testDS.createResolver({
+  typeName: 'Query',
+  fieldName: 'getTests',
+  requestMappingTemplate: MappingTemplate.dynamoDbScanTable(),
+  responseMappingTemplate: MappingTemplate.dynamoDbResultList(),
```
Comment (eladb) [inline packages/@aws-cdk/aws-appsync/test/integ.auth-apikey.ts:58]: How is this related to this change?

File: packages/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts (hunk 5 above)
Comment (BryanPan342) [reply packages/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts:334]: thoughts on writing the `@deprecated` tag to the doc string and add `Expiration` to core?

File: packages/@aws-cdk/aws-appsync/test/appsync.auth.graphql (hunk 9 above)
Comment (BryanPan342) [reply packages/@aws-cdk/aws-appsync/test/appsync.auth.graphql:7]: just for the integrity test to see if the API Key works for query/mutation

File: packages/@aws-cdk/aws-appsync/test/integ.auth-apikey.ts (hunk 10 above)
Comment (BryanPan342) [reply packages/@aws-cdk/aws-appsync/test/integ.auth-apikey.ts:58]: same as the comment above

> just for the integrity test to see if the API Key works for query/mutation

File: packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts (hunk 8 above)
Comment (BryanPan342) [reply packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts:528]: Eli commented before and said that it would be best to move this function out of the expires class.

> Im not sure this method is warranted, nor does the EpochFormat enum. I only see one usage of it that essentially could be replaced with / 1000 (which was also the original code).
> 
>  I'd rather not introduce code we don't really use, even if it might seem sensible.

File: packages/@aws-cdk/aws-appsync/test/integ.auth-apikey.ts (hunk 10 above)
Comment (BryanPan342) [reply packages/@aws-cdk/aws-appsync/test/integ.auth-apikey.ts:58]: @eladb o i see.. i just need to check if the apikey exist is that right?

**Comment by BryanPan342** [comment]
@iliapolo

I was suggested to move the equivalent of `asEpoch()` into `core` by @eladb and I'm more inclined to go with that because of the suggestion to implement an `expires?.lessThan(...)`  into the `Expiration` class.

If we add those functions to `Expiration` I dont see why we can't do the same for `asEpoch`:
https://github.com/aws/aws-cdk/blob/8803379e39231dcce45c36bad84aa1b9270b5c33/packages/%40aws-cdk/aws-appsync/lib/graphqlapi.ts#L528

wdyt?

File: packages/@aws-cdk/aws-appsync/test/integ.auth-apikey.ts (hunk 10 above)
Comment (BryanPan342) [reply packages/@aws-cdk/aws-appsync/test/integ.auth-apikey.ts:53]: i think its important to test the connection else i can just remove the integ test all together

**Comment by iliapolo** [comment]
@BryanPan342 Yeah that sounds good. The `asEpoch` method you refer to here is a much more trimmed down version of the `getEpoch(format: Format)` method we had before, so i'm ok with adding it.

I'd also suggest using `before/after` semantics for the methods rather than `lessThan/greaterThan` as these are dates, not numbers.

```typescript
if (expires.before(Expiration.after(Duration.days(365))) {
...
}
```

**Comment by BryanPan342** [comment]
@eladb @iliapolo @shivlaks would love to see this PR get merged by the end of the week if possible 😊

I addressed most of the changes so I dont think there is anything too controversial, but if anything arises I'll fix it immediately!

**Review by iliapolo — APPROVED** [review]

**Comment by iliapolo** [comment]
@BryanPan342 I'm ok with these changes. Added the `do-not-merge` label to wait for other participants approval.

File: packages/@aws-cdk/core/lib/expiration.ts [hunk 11]
```diff
@@ -0,0 +1,69 @@
...
+   * Expire at specified date, represented as a string
+   *
+   * @param s the string that represents date to expire at
+   */
+  public static fromString(s: string) { return new Expiration(s, new Date(s)); }
+
+  /**
+   * Expiration value as a string
+   */
+  public readonly value: string;
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/expiration.ts:36]: Why is this needed? Seems like this the UTC representation of the date, which can be obtained from `x.date.toUTCString()`, no?

File: packages/@aws-cdk/core/lib/expiration.ts [hunk 12]
```diff
@@ -0,0 +1,69 @@
...
+   * @param t the duration to wait before expiring
+   */
+  public static after(t: Duration) { return Expiration.atDate(new Date(Date.now() + t.toMilliseconds())); }
+
+  /**
+   * Expire at specified date, represented as a string
+   *
+   * @param s the string that represents date to expire at
+   */
+  public static fromString(s: string) { return new Expiration(s, new Date(s)); }
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/expiration.ts:31]: Why is this needed? `Expiration.atDate(new Date(s))` is short enough, no?

**Review by eladb — CHANGES_REQUESTED** [review]
Still feels like this PR includes two different changes: one is the introduction of the `Expiration` class in core and using it in various places and the second is the change to the appsync library and the apikey tests.

File: packages/@aws-cdk/core/lib/expiration.ts (hunk 12 above)
Comment (BryanPan342) [reply packages/@aws-cdk/core/lib/expiration.ts:31]: It existed in the s3-deployment version and I don't have the domain knowledge to know if this is something that should keep maybe @iliapolo knows more about this

File: packages/@aws-cdk/core/lib/expiration.ts (hunk 11 above)
Comment (BryanPan342) [reply packages/@aws-cdk/core/lib/expiration.ts:36]: s3-deployments uses the `value` property, I added the `date` property myself, but I wouldn't mind just removing the `date` property entirely.

**Comment by BryanPan342** [comment]
> Still feels like this PR includes two different changes: one is the introduction of the `Expiration` class in core and using it in various places and the second is the change to the appsync library and the apikey tests.

would it be better if I separated this PR?

File: packages/@aws-cdk/core/lib/expiration.ts (hunk 12 above)
Comment (eladb) [reply packages/@aws-cdk/core/lib/expiration.ts:31]: From a user's mental model, I think `.date` makes much more sense then `.value`. We can change `s3-deployment` to use `.date.toUTCString()` or whatever it needs.

**Comment by eladb** [comment]
> > Still feels like this PR includes two different changes: one is the introduction of the `Expiration` class in core and using it in various places and the second is the change to the appsync library and the apikey tests.
> 
> @eladb would it be better if I separated this PR?

Yes, I think it makes sense to separate.

**Comment by BryanPan342** [comment]
@iliapolo @eladb separated to #10192

**Comment by BryanPan342** [comment]
@MrArnoldPalmer @shivlaks got #10192 approved! Would love it you guys could take a pass at this today. I dont think there is anything too controversial here. Maybe the integ test is unnecessary?

**Review by MrArnoldPalmer — APPROVED** [review]
