### PR TITLE
fix(events): archive construct does not have defaultChild set

### LINKED ISSUE #21263: aws-events: Archive construct does not have defaultChild set
### Describe the bug

Archive construct has defaultChild as `undefined` instead of an instance of `CfnArchive`

### Expected Behavior

I expect `archive.node.defaultChild` to return instance of `CfnArchive`, but it is currently undefined

### Current Behavior

`archive.node.defaultChild` returns undefined

### Reproduction Steps

```ts
const app = new App();
const stack = new Stack(app);
const eventBus = new EventBus(stack, 'eventbus', {
      eventBusName: 'EventBus',
    });
const archive = new Archive(eventBus, 'archive', {
      sourceEventBus: eventBus,
      eventPattern: {
        source: ['test'],
      },
    });
const cfnArchive = archive.node.defaultChild as CfnArchive; // This fails
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.20.0

### Framework Version

_No response_

### Node.js Version

14.19.1

### OS

Ubuntu 18

### Language

Typescript

### Language Version

4.4.4

### Other information

_No response_

### PR DESCRIPTION
**Pull request by daschaa**
Fixes #21263 

Adds id 'Default' to CfnArchive in Archive construct.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
This feels(?) like a breaking change but I can't actually tell if it is. Part of the problem is that no integration tests were written for this module. Even though this is a fix, not a feat, I think we need an integration test here.

**Comment by daschaa** [comment]
@TheRealAmazonKendra Yeah maybe you are right.. Do you think about some logical ID matching stuff out in the wild? Should I introduce a feature flag for this then? It would feel weird to make a feature flag for a fix tbh.. What would be the best way to keep backwards compatibility? I will definitely add Integration tests!

And btw: is this even the best way to define the `CfnArchive` as defaultChild? Or is there a better way?

File: packages/@aws-cdk/aws-events/lib/archive.ts [hunk 1]
```diff
@@ -64,7 +64,7 @@ export class Archive extends Resource {
   constructor(scope: Construct, id: string, props: ArchiveProps) {
     super(scope, id, { physicalName: props.archiveName });
 
-    let archive = new CfnArchive(this, 'Archive', {
+    let archive = new CfnArchive(this, 'Default', {
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-events/lib/archive.ts:67]: This is unfortunately the wrong way to solve this particular bug. It will destroy everyone's existing archives.

This needs to be fixed by setting `this.node.defaultChild = archive`

**Review by rix0rrr — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-events/lib/archive.ts (hunk 1 above)
Comment (daschaa) [reply packages/@aws-cdk/aws-events/lib/archive.ts:67]: Sorry! I will fix it

**Comment by daschaa** [comment]
Sorry @rix0rrr - I have now changed the code and implemented your suggestion.

File: packages/@aws-cdk/aws-events/test/archive.test.ts [hunk 2]
```diff
@@ -77,4 +77,20 @@ describe('archive', () => {
...
+
+    const archive = new Archive(stack, 'Archive', {
+      sourceEventBus: eventBus,
+      eventPattern: {
+        account: [stack.account],
+      },
+      retention: Duration.days(10),
+    });
+
+    expect(archive.node.defaultChild).toBeDefined();
```
Comment (TheRealAmazonKendra) [inline packages/@aws-cdk/aws-events/test/archive.test.ts:94]: I think this should test this against what we expect the value to be, not just for it to be defined or not.

**Review by TheRealAmazonKendra — DISMISSED** [review]
Just one quick comment on the unit test and I'd still like to see an integ tests added.

File: packages/@aws-cdk/aws-events/test/archive.test.ts (hunk 2 above)
Comment (daschaa) [reply packages/@aws-cdk/aws-events/test/archive.test.ts]: I have now changed the test. I'm not sure if it is the best way..

**Comment by daschaa** [comment]
@TheRealAmazonKendra Thanks for your feedback :) I have added an integration test and changed the unit test according to your review.

**Review by TheRealAmazonKendra — DISMISSED** [review]
Thank you for adding the tests. We just need the integration test to use the new IntegTest construct, per the [integration testing guide](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md).

**Comment by daschaa** [comment]
@TheRealAmazonKendra I have added the `IntegTest` structure like in the example of the markdown file you provided. Is this correct?

**Review by TheRealAmazonKendra — APPROVED** [review]
Looks great!
