### PR TITLE
fix(apigateway): rest api deployment does not depend on authorizers

### LINKED ISSUE #16554: (apigateway): Changes to authorizer does not cause latest deployment to update
When you have an authorizer that has an imported Lambda from another stack set as handler (authorizerUri), and you change that ARN, authorizer will start failing with AuthorizerConfigurationException on requests to API endpoints that have that authorizer attached.

API Gateway logs reveal that the authorizer is still trying to invoke the Lambda with the old ARN, and fails because Lambda permission has already been replaced with one that contains the new ARN.

This is most likely because CDK won't create a new REST API deployment despite of updating the authorizerUri of the CfnAuthorizer construct.

### Reproduction Steps

1. Add a new Lambda, REST API, authorizer and method to your stack. Authorizer Lambda should already exist in another stack:
```
    // Lambda that should be served via your API
    const yourLambda = new lambda.Function(...)

    // Authorizer that uses a Lambda from another stack
    const authorizerLambdaFuncArn = 'authorizer-lambda-arn-goes-here'
    const someAuthorizer = new TokenAuthorizer(this, 'SomeAuthorizer', {
      authorizerName: 'someAuthorizer',
      handler: Function.fromFunctionArn(this, 'SomeAuthorizerFunction', authorizerLambdaFuncArn),
    })

    // REST API
    const restApi = new RestApi(this, 'SomeApi', {
      restApiName: 'some-api',
    })

    // API method configured with your Lambda and the authorizer
    restApi.root.addMethod('GET', new LambdaIntegration(yourLambda), {
      authorizationType: AuthorizationType.CUSTOM,
      authorizer: someAuthorizer,
    })
```
2. `cdk deploy` your stack
3. Requests to your API endpoint should successfully pass to the authorizer
4. Change `authorizerLambdaFuncArn` to some other Lambda function's ARN
5. Repeat step 2
6. Requests to your API endpoint should now return `AuthorizerConfigurationException`

### What did you expect to happen?

CDK should create a new deployment so that requests will be forwarded to the correct authorizer Lambda

### What actually happened?

No new deployment created but Lambda Permission is updated, which leads to permission error.

### Environment

  - **CDK CLI Version  : 1.123.0**
  - **Framework Version: 1.123.0**
  - **Node.js Version: v14.17.5**
  - **OS               : MacOS 10.15.7**
  - **Language (Version): TypeScript 4.3.5**

#### Workaround:

Add the following in your code:
```
    if (restApi.latestDeployment) {
      restApi.latestDeployment.addToLogicalId({
        someAuthorizerFunctionArn: authorizerLambdaFuncArn,
      })
    }
```

This will cause CDK to create a new API deployment.

--- 

This is :bug: Bug Report

### LINKED ISSUE #22808: TokenAuthorizer (api-gateway): TokenAuthorizer doesn't update when handler changes
### Describe the bug

TokenAuthorizer doesn't update the lambda handler connection when the handler dependency changes "location". This is both if you add a new name to a current TokenAuthorizer lambda or if you simply add an alias to the function.

The authorization then starts failing with a 500 server error with the response: { message: null } and the API gateway logs say: "Execution failed due to configuration error: Invalid permissions on Lambda function".

### Expected Behavior

TokenAuthorizer updates when the handler changes version.

### Current Behavior

TokenAuthorizer doesn't update when handler changes version.

### Reproduction Steps

deploy the following:

```
const apiGateway: ApiGateway;
const IntegrationLambda: NodeJSLambda;
const authLambda: new NodeJSLambda(this, 'auth-lambda');
const authorizer = new TokenAuthorizer(this, 'authorizer', {
	handler: authLambda,
	resultsCacheTtl: Duration.seconds(0),
});
apiGateway.root
  .addResource('{proxy+}')
  .addMethod('ANY', new LambdaIntegration(integrationLambda, {
    timeout: Duration.seconds(10)
  }),
  {
    authorizer,
  }
);
```

Then deploy the following on top of it:

```
const apiGateway: ApiGateway;
const IntegrationLambda: NodeJSLambda;
const authLambda: new NodeJSLambda(this, 'auth-lambda-v2');
const authorizer = new TokenAuthorizer(this, 'authorizer', {
	handler: authLambda,
	resultsCacheTtl: Duration.seconds(0),
});
apiGateway.root
  .addResource('{proxy+}')
  .addMethod('ANY', new LambdaIntegration(integrationLambda, {
    timeout: Duration.seconds(10)
  }),
  {
    authorizer,
  }
);
```

You should now start seeing 500 errors when contacting the API Gateway

### Possible Solution

The easy fix for now is changing the id of the TokenAuthorizer together with the lambda.

```
const apiGateway: ApiGateway;
const IntegrationLambda: NodeJSLambda;
const authLambda: new NodeJSLambda(this, 'auth-lambda');
const authorizer = new TokenAuthorizer(this, `authorizer-v${authLambda.currentVersion}`, {
	handler: authLambda,
	resultsCacheTtl: Duration.seconds(0),
});
apiGateway.root
  .addResource('{proxy+}')
  .addMethod('ANY', new LambdaIntegration(integrationLambda, {
    timeout: Duration.seconds(10)
  }),
  {
    authorizer,
  }
);
```

So my best guess on a reason and fix is that the TokenAuthorizer is missing a dependency on the handler. It seems like it doesn't update its connection to the Authorizer lambda in case it gets moved to a different arn.

### Additional Information/Context

There is no issue when running `synth`

As I said - quick fix is changing the TokenAuthorizer id.

This also happened when we created an alias to the function.

### CDK CLI Version

2.45.0

### Framework Version

_No response_

### Node.js Version

16.15.1

### OS

macOS Monterey

### Language

Typescript

### Language Version

Typescript (4.7.4)

### Other information

_No response_

### PR DESCRIPTION
**Pull request by cecheta**
----

Closes #16554 (formerly #22808)

The Rest API deployment needs to depend on all authorizers attached to the API, so there is a new deployment if any of the authorizers change. This is similar to what is already done for `Method`s. Includes trivial change to integ test.

Note - Because this will change the logical ID of existing deployments, this is technically a breaking change, so I am not sure if it requires a feature flag.

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [X] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-apigateway/lib/authorizers/cognito.ts [hunk 1]
```diff
@@ -96,6 +103,14 @@ export class CognitoUserPoolsAuthorizer extends Authorizer implements IAuthorize
     }
 
     this.restApiId = restApi.restApiId;
+
+    const deployment = restApi.latestDeployment;
+    if (deployment) {
+      deployment.node.addDependency(this);
+      deployment.addToLogicalId({
+        authorizer: this.authorizerProps,
+      });
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-apigateway/lib/authorizers/cognito.ts:112]: As I understand it, the dependency just ensures resource deployment order, and it won't force an update to another resource. We really need a test to ensure that whenever the lambda function changes, the construct that needs to be updated is actually updated.

**Review by comcalvi — CHANGES_REQUESTED** [review]
I'm not sure this PR actually solves the underlying issue. I'm going to see how this pairs with the reproduction code posted by the issue opener, once I can successfully reproduce.

File: packages/@aws-cdk/aws-apigateway/lib/authorizers/cognito.ts (hunk 1 above)
Comment (cecheta) [reply packages/@aws-cdk/aws-apigateway/lib/authorizers/cognito.ts:112]: I've made a change and added a new test which checks that the deployment changes when the lambda function changes name

File: packages/@aws-cdk/aws-apigateway/test/authorizers/integ.request-authorizer.lit.ts [hunk 2]
```diff
@@ -24,6 +24,7 @@ const restapi = new RestApi(stack, 'MyRestApi', { cloudWatchRole: true });
 const authorizer = new RequestAuthorizer(stack, 'MyAuthorizer', {
   handler: authorizerFn,
   identitySources: [IdentitySource.header('Authorization'), IdentitySource.queryString('allow')],
+  resultsCacheTtl: Duration.minutes(5),
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-apigateway/test/authorizers/integ.request-authorizer.lit.ts:27]: why? This doesn't add anything to this integration test.

**Review by comcalvi — CHANGES_REQUESTED** [review]
Please add an integration test that verifies that `addToLogicalId()` is correctly used.

File: packages/@aws-cdk/aws-apigateway/test/authorizers/integ.request-authorizer.lit.ts (hunk 2 above)
Comment (cecheta) [reply packages/@aws-cdk/aws-apigateway/test/authorizers/integ.request-authorizer.lit.ts:27]: I edited this test to re-run this integration test and verify that `addToLogicalId()` worked correctly, however I will instead create a separate test

Comment (cecheta) [reply packages/@aws-cdk/aws-apigateway/test/authorizers/integ.request-authorizer.lit.ts]: I think this is a breaking change so I also tried to add a feature flag

File: packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts [hunk 3]
```diff
@@ -90,6 +93,34 @@ abstract class LambdaAuthorizer extends Authorizer implements IAuthorizer {
...
+    } else {
+      // imported, just take the function name.
+      functionName = this.handler.functionName;
+    }
+
+    let authorizerToken;
+
+    if (!Token.isUnresolved(functionName)) {
+      authorizerToken = JSON.stringify({ functionName });
+    }
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts:112]: You can pass tokens to `addToLogicalId()`, why do we check for them here?

File: packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts [hunk 4]
```diff
@@ -90,6 +93,34 @@ abstract class LambdaAuthorizer extends Authorizer implements IAuthorizer {
...
+
+    const addToLogicalId = FeatureFlags.of(this).isEnabled(APIGATEWAY_AUTHORIZER_CHANGE_DEPLOYMENT_LOGICAL_ID);
+
+    const deployment = restApi.latestDeployment;
+    if (deployment && addToLogicalId) {
+      deployment.node.addDependency(this);
+      deployment.addToLogicalId({
+        authorizer: this.authorizerProps,
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts:120]: Is the `authorizerToken` not enough?

**Review by comcalvi — DISMISSED** [review]
You are correct, this needs a feature flag. I think you've added it correctly.

File: packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts (hunk 3 above)
Comment (cecheta) [reply packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts:112]: I have copied the existing logic from [here](https://github.com/aws/aws-cdk/blob/32781f825352f9cb43d8fed5c122b454275b3076/packages/%40aws-cdk/aws-apigateway/lib/integrations/lambda.ts#L91)

I am guessing it is because the token can change which could cause the logical ID to change, even though the function name hadn't changed

File: packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts (hunk 4 above)
Comment (cecheta) [reply packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts:120]: I think we need all of them; if any of the authorizer properties change, we need a new deployment, otherwise the changes will not be reflected in the API

File: packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts (hunk 3 above)
Comment (comcalvi) [reply packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts:112]: The other logic did not use this method, and `addToLogicalId()` has a particular way of dealing with tokens. Please remove this token check and just pass it through to `addToLogicalId()`.

File: packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts [hunk 5]
```diff
@@ -90,6 +93,34 @@ abstract class LambdaAuthorizer extends Authorizer implements IAuthorizer {
     }
 
     this.restApiId = restApi.restApiId;
+
+    let functionName;
```
Comment (comcalvi) [inline packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts:97]: is there a reason to do any of this if the feature flag is disabled?

**Review by comcalvi — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts (hunk 5 above)
Comment (cecheta) [reply packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts]: Moved

File: packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts (hunk 3 above)
Comment (cecheta) [reply packages/@aws-cdk/aws-apigateway/lib/authorizers/lambda.ts]: I think the other logic I linked to is used in the `addToLogicalId()` call [here](https://github.com/aws/aws-cdk/blob/4f83e02b85229ebdff3f32ba6fd662ffd707d8db/packages/%40aws-cdk/aws-apigateway/lib/method.ts#L239), however I have reworked it to handle unresolved tokens

**Review by comcalvi — APPROVED** [review]
Thanks for the fix!
