### PR TITLE
docs(cfn-include): fixed CfnOutput comment docs

### LINKED ISSUE #9368: [cfn-include]: broken js docs for CfnOutput fields
Given a CfnOutput output, invoking `output.description` and hovering over `description` in VS Code yields

"Returns the description of this Output Sets this output's description to the parameter"

as a description.

---

This is a 📕 documentation issue

I will be opening a PR to address this.

### PR DESCRIPTION
**Pull request by comcalvi**
----

Closes #9368 

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/core/lib/cfn-output.ts [hunk 1]
```diff
@@ -60,61 +60,57 @@ export class CfnOutput extends CfnElement {
...
-   * Sets this output's description to the parameter
-   * @param description the description to update this Output's description to
-   */
   public set description(description: string | undefined) {
     this._description = description;
   }
 
   /**
-   * Returns the value of this Output
+   * The value of the property returned by the aws cloudformation describe-stacks command.
```
Comment (skinny85) [inline packages/@aws-cdk/core/lib/cfn-output.ts:77]: Sorry, what does this mean? :)

Comment (comcalvi) [reply packages/@aws-cdk/core/lib/cfn-output.ts:77]: That comment is taken from the props. So the description of the prop's value field and the CfnOutput's value field are the same

Comment (skinny85) [reply packages/@aws-cdk/core/lib/cfn-output.ts:77]: Fine :)
