### PR TITLE
fix(rds): clusterScailabilityType is spelled wrong and should be clusterScalabilityType

### LINKED ISSUE #32415: rds: scalability is spelled wrong
### Describe the bug

In this recent PR:

https://github.com/aws/aws-cdk/pull/32151/files#diff-49b4a9e1bf0b7db3ab71f4f08580da0cb2191d84605dc82a70c324bd122d5cf7

this introduced a new `clusterScailabilityType` property which is spelled wrong and will cause confusion

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

I expected things to be spelled correctly.

### Current Behavior

There is a typo, `clusterScailabilityType` should be `clusterScalabilityType`

### Reproduction Steps

None, it's a typo

### Possible Solution

replace all `Scailability` with `Scalability`

### Additional Information/Context

_No response_

### CDK CLI Version

-

### Framework Version

_No response_

### Node.js Version

-

### OS

-

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by iankhou**
### Issue #32415 

Closes #32415 .

### Reason for this change

Misspelling of the `ClusterScalabilityType` type, enum, and prop.

### Description of changes

Deprecated misspellings of **ClusterScailabilityType**/**clusterScailabilityType** and aliased the misspelling for backwards compatibility. The misspelled name will be removed in the next MV release.

### Describe any new or updated permissions being added

No permissions changes.

### Description of how you validated changes

Added unit tests for the new spelling (ClusterScalabilityType/clusterScalabilityType), and kept unit tests that tested the misspelling.
```zsh
# in packages/aws-cdk-lib
yarn test aws-rds
```
Screenshot 2025-01-09 at 16 10 04

Ran the relevant integration test.
```zsh
# in packages/@aws-cdk-testing/framework-integ
yarn integ test/aws-rds/test/integ.cluster-limitless.js
```
Screenshot 2025-01-09 at 17 03 44

Ran Rosetta to verify README changes.
```zsh
./scripts/run-rosetta.sh
```
No complications from README changes in these commits.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-rds/lib/cluster.ts [hunk 1]
```diff
@@ -802,7 +831,7 @@ abstract class DatabaseClusterNew extends DatabaseClusterBase {
       throw new Error('`enablePerformanceInsights` disabled, but `performanceInsightRetention` or `performanceInsightEncryptionKey` was set');
     }
 
-    if (props.clusterScailabilityType === ClusterScailabilityType.LIMITLESS) {
+    if (props.clusterScalabilityType === ClusterScalabilityType.LIMITLESS || props.clusterScailabilityType === ClusterScailabilityType.LIMITLESS) {
```
Comment (rix0rrr) [inline packages/aws-cdk-lib/aws-rds/lib/cluster.ts:834]: Also needs a check to ensure that you can't set both the old and new property at the same time. And that should be mentioned in the docstring as well.

File: packages/aws-cdk-lib/aws-rds/test/cluster.test.ts [hunk 2]
```diff
@@ -419,6 +440,240 @@ describe('cluster new api', () => {
       });
     });
 
+    describe('limitless database', () => {
```
Comment (rix0rrr) [inline packages/aws-cdk-lib/aws-rds/test/cluster.test.ts:443]: Lotsa new tests for a simple feature? Copy/paste or GenAI?

I'd rather turn existing tests into data-driven tests for both ways of passing props.

```ts
test.each([
  { clusterScailabilityType: ClusterScailabilityType.LIMITLESS },
  { clusterScalabilityType: ClusterScalabilityType.LIMITLESS },
])('my test with input %p, (partialProps) => {
  // ...
});
```

**Review by rix0rrr — CHANGES_REQUESTED** [review]

File: packages/aws-cdk-lib/aws-rds/lib/cluster.ts (hunk 1 above)
Comment (iankhou) [reply packages/aws-cdk-lib/aws-rds/lib/cluster.ts:834]: Thanks, will make this change.

File: packages/aws-cdk-lib/aws-rds/lib/cluster.ts [hunk 3]
```diff
@@ -701,6 +730,10 @@ abstract class DatabaseClusterNew extends DatabaseClusterBase {
   constructor(scope: Construct, id: string, props: DatabaseClusterBaseProps) {
     super(scope, id);
 
+    if (props.clusterScalabilityType !== undefined && props.clusterScailabilityType !== undefined) {
+      throw new Error('You cannot specify both clusterScalabilityType and clusterScailabilityType (deprecated). Use clusterScalabilityType.');
```
Comment (iankhou) [inline packages/aws-cdk-lib/aws-rds/lib/cluster.ts:734]: @rix0rrr here I disallow both options to be set.

**Review by rix0rrr — APPROVED** [review]
