### PR TITLE
chore(cli): fix bugs introduced in stack monitor

### LINKED ISSUE #9470: [CLI] cdk deploy keeps calling describeStackEvents() for ~10 minutes after stack update
AWS CDK `cdk deploy` keeps calling describeStackEvents() for about 10 minutes after the CloudFormation stack has been successfully updated. It seems that CDK iterates through the entire event history of the stack in 5 second intervals. This makes the `cdk deploy` command take a very long time.

During the delay AWS CDK appears to be stuck in the "creating CloudFormation changeset" phase. In reality it has already created the changeset and applied it to the CloudFormation stack.

### Reproduction Steps

You might need a CloudFormation stack that has a lot of event history to notice that AWS CDK iterates through all of them, causing the long delay.

You can see the `describeStackEvents()` iteration in debug output by using `cdk deploy -v -v -v`. It will keep showing entries like this (with different NextToken as it progresses):

    [AWS cloudformation 200 5.499s 0 retries] describeStackEvents({
      StackName: 'webcat-registrar-dev',
      NextToken: 'f73Uze7bI/CdCn4qrXZ31hZlkhi5jbWWog...'
    }) 

### What did you expect to happen?

`cdk deploy` should finish in about 3 minutes.

### What actually happened?

`cdk deploy` takes 14 minutes to complete.

### Environment

  - **CLI Version      :** 1.56.0
  - **Framework Version:** 1.56.0
  - **Node.js Version:** v12.18.2
  - **OS               :** Linux (Ubuntu in Docker)
  - **Language (Version):** TypeScript 3.9.7

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
In #9795, I was under the impression that the `DescribeStackEvents`
would list events in chronological order.

This was a misunderstanding resulting from not reading the documentation--
in fact, the events are returned in reverse chronological order.

The paging logic was therefore wrong and the events would be fed into
the activity printer in the wrong order, leading to incorrect progress
reporting.

This is a critical bug and must be fixed immediately!

While I was in there, fixed two other paper cuts around the
printer at the same time:

- Events occurring near the start of the monitor would be missed. This
  was because time-based filtering would be employed based on the
  client machine's local clock, which might be out of sync with the
  remote clock. Use the server's clock instead, by using the
  `CreationTime` of the ChangeSet as the start time.

- Events occurring near the end of the monitor would be missed. This
  was because `DescribeStackStatus` might return a completion state
  before the monitor had polled the events that led up to the completion.
  Fix by doing a final poll after the stop call has been received,
  so we are guaranteed to have seen all events.

The actual claim in that PR was incorrect. We were *not* quadratic (we
wouldn't list all pages on every tick), we were just more linear than
necessary (we *would* list all pages on the *first* tick... which is still
a lot). The current PR properly fixes the issue by stopping paging
not just if we've already seen the events, but also if the events are
starting to fall outside the time window we are interested in.

This *actually* fixes #9470.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts [hunk 1]
```diff
@@ -83,7 +96,7 @@ export class StackActivityMonitor {
   /**
    * Determines which events not to display
    */
-  private startTime = Date.now();
+  private readonly startTime: number;
```
Comment (skinny85) [inline packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts:99]: Any reason not to leave this as a `Date`?

Comment (rix0rrr) [reply packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts:99]: Just simpler implementation, and since it doesn't affect the public API I prefer this.
