### PR TITLE
fix(lambda): can't find entry file under ESM module system

### LINKED ISSUE #21630: aws-lambda-nodejs: Default entry finding fails when defining file starts with "file://"
### Describe the bug

Attempting to create a lambda with NodejsFunction, which should auto find the handler based on the defining files path.  

I get an error that looks like this: 

```
Error: Cannot find handler file file:///Users/stack.handler.ts, file:///Users/<path>/stack.handler.js or file:///Users/<path>/stack.handler.mjs
```

where the middle of the path has been replaced with <path> for brevity and privacy. 

[This](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-lambda-nodejs/lib/function.ts#L189) implies the paths being checked start with "file://", which I've tested and does not work with Node 16.13.1.

Those paths are produced from [this function](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-lambda-nodejs/lib/function.ts#L195-L211), which I believe is incorrect.  

This is running on macos 12.5, with the a fore mentioned version of nodejs. 

### Expected Behavior

I expected it to find the file, as the path was correct without the `file://` prefix.  

### Current Behavior

Error: Cannot find handler file file:///Users/stack.handler.ts, file:///Users/<path>/stack.handler.js or file:///Users/<path>/stack.handler.mjs

### Reproduction Steps

Create a lambda function using `NodejsFunction` with no `entry` parameter specified, and synthesize. 

### Possible Solution

`callsites()` produces paths that start with file:// when they are local files, and `findDefiningFile` doesn't scrub the path. Maybe make findDefining file remove the prefix when it's `file://`

### Additional Information/Context

_No response_

### CDK CLI Version

2.37.1 (build f15dee0)

### Framework Version

_No response_

### Node.js Version

16.13.1

### OS

macos 12.5

### Language

Typescript

### Language Version

4.7.2

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Abogical**
### Issue # (if applicable)

Closes #21630.

### Reason for this change

In the ESM module system, callsites returns filenames prefixed with 'file://'. This is not compatible with the NodeJS file utility functions such as fs.existsSync().

### Description of changes

Remove 'file://' prefix.

### Describe any new or updated permissions being added

No new IAM permissions are added.

### Description of how you validated changes

Unit tests. Integration test cannot be added as the integration test system uses CommonJS, it will be impossible to replicate the error which only happens under an ESM system. 

### Credits

This is mostly inspired by @okko for [his PR](https://github.com/aws/aws-cdk/pull/21802). He found the root cause and fix for this issue, but it didn't get merged due to a lack of integration tests.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-lambda-nodejs/lib/function.ts [hunk 1]
```diff
@@ -292,5 +292,14 @@ function findDefiningFile(scope: Construct): string {
...
+  let definingFile = sites[definingIndex].getFileName();
+
+  // Fixes issue #21630.
+  // ESM modules return a 'file://' prefix to the filenames, this should be removed for
+  // compatibility with the NodeJS filesystem functions.
+  if (definingFile.startsWith('file://')) {
+    definingFile = definingFile.slice('file://'.length);
+  }
+
+  return definingFile;
```
Comment (aemada-aws) [inline packages/aws-cdk-lib/aws-lambda-nodejs/lib/function.ts]:
```suggestion
  // Fixes issue #21630.
  // ESM modules return a 'file://' prefix to the filenames, this should be removed for
  // compatibility with the NodeJS filesystem functions.
  return sites[definingIndex].getFileName().replace(/^file:\/\//, '')
```

Comment (Abogical) [reply packages/aws-cdk-lib/aws-lambda-nodejs/lib/function.ts]: I just want to replace once in the beginning, not in any place of the string.

Comment (okko) [reply packages/aws-cdk-lib/aws-lambda-nodejs/lib/function.ts]: `^file` only matches in the beginning of the string because of `^`.

Comment (Abogical) [reply packages/aws-cdk-lib/aws-lambda-nodejs/lib/function.ts]: Oh, I missed that. Thanks @okko

**Review by aemada-aws — APPROVED** [review]
