### PR TITLE
fix(stepfunctions): add docs and warning DistributedMap Class ignores executionType in the ProcessorConfig

### LINKED ISSUE #30194: aws-stepfunctions: Distributed Map State Item Processor executionType doesn't recognize ProcessorType.EXPRESS
### Describe the bug

I have the following piece of CDK code but when I deploy it and check in AWS console, the step function execution type for the map run is `Standard` instead of `Express`.

The code:
```
    const qotOverrideDistributedMapState = new DistributedMap(this, 'Distributed Map State', {
      maxConcurrency: 1000,
      itemBatcher: new ItemBatcher({
        maxItemsPerBatch: 10
      }),
      itemReader: new S3CsvItemReader({
        bucket: qotOverrideBucket,
        key: JsonPath.stringAt('$.s3Key'),
        csvHeaders: CsvHeaders.useFirstRow()
      }),
      resultWriter: new ResultWriter({
        bucket: qotOverrideBucket,
        prefix: 'QoTOverrideProcessingResult',
      }),
      toleratedFailureCount: 0,
    }).itemProcessor(new LambdaInvoke(this, 'Invoke Lambda Processor', {
      lambdaFunction: qotOverrideProcessor,
    }), {
      mode: ProcessorMode.DISTRIBUTED,
      executionType: ProcessorType.EXPRESS,
    })

    const qotOverrideFileProcessor = new StateMachine(this, 'QoT Override File Processor', {
      role: Role.fromRoleArn(this, 'QoT-Override-File-Processor-SfnRole', qotOverrideSfnRole.roleArn, {
        mutable: false,
      }),
      definitionBody: DefinitionBody.fromChainable(qotOverrideDistributedMapState),
      stateMachineName: 'QoT-Override-File-Processor-Sfn',
      stateMachineType: StateMachineType.STANDARD,
      logs: {
        destination: new LogGroup(this, 'QoT-Override-File-Processor-LogGroup', {
          retention: RetentionDays.THREE_MONTHS,
          logGroupName: 'QoT-Override-File-Processor-Log',
        }),
        level: LogLevel.ERROR,
        includeExecutionData: true,
      },
    })
```

The generated State Machine definition copied from AWS console:
```
{
  "StartAt": "Distributed Map State",
  "States": {
    "Distributed Map State": {
      "Type": "Map",
      "End": true,
      "ItemProcessor": {
        "ProcessorConfig": {
          "Mode": "DISTRIBUTED",
          "ExecutionType": "STANDARD"
        },
        "StartAt": "Invoke Lambda Processor",
        "States": {
          "Invoke Lambda Processor": {
            "End": true,
            "Retry": [
              {
                "ErrorEquals": [
                  "Lambda.ClientExecutionTimeoutException",
                  "Lambda.ServiceException",
                  "Lambda.AWSLambdaException",
                  "Lambda.SdkClientException"
                ],
                "IntervalSeconds": 2,
                "MaxAttempts": 6,
                "BackoffRate": 2
              }
            ],
            "Type": "Task",
            "Resource": "arn:aws:states:::lambda:invoke",
            "Parameters": {
              "FunctionName": "arn:aws:lambda:us-east-1:502523373620:function:QoTOverrideProcessor",
              "Payload.$": "$"
            }
          }
        }
      },
      "MaxConcurrency": 1000,
      "ItemReader": {
        "Resource": "arn:aws:states:::s3:getObject",
        "ReaderConfig": {
          "InputType": "CSV",
          "CSVHeaderLocation": "FIRST_ROW"
        },
        "Parameters": {
          "Bucket.$": "$.s3Bucket",
          "Key.$": "$.s3Key"
        }
      },
      "ItemBatcher": {
        "MaxItemsPerBatch": 10
      },
      "ResultWriter": {
        "Resource": "arn:aws:states:::s3:putObject",
        "Parameters": {
          "Bucket.$": "$.s3Bucket",
          "Prefix": "QoTOverrideProcessingResult"
        }
      }
    }
  }
}
```

### Expected Behavior

The ItemProcessor execution type should be Express

### Current Behavior

The ItemProcessor execution type is Standard and the specified type in CDK is ignored.

### Reproduction Steps

```
    const bucket = new Bucket(this, 'Bucket', {});
    const distributedMapState = new DistributedMap(this, 'Distributed Map State', {
      maxConcurrency: 1000,
      itemReader: new S3CsvItemReader({
        bucket: bucket,
        key: JsonPath.stringAt('$.s3Key'),
        csvHeaders: CsvHeaders.useFirstRow()
      }),
      toleratedFailureCount: 0,
    }).itemProcessor(new Pass(this, 'Pass State', {}), {
      mode: ProcessorMode.DISTRIBUTED,
      executionType: ProcessorType.EXPRESS,
    })

    const fileProcessor = new StateMachine(this, 'File Processor', {
      definitionBody: DefinitionBody.fromChainable(distributedMapState),
      stateMachineName: 'File-Processor-Sfn',
      stateMachineType: StateMachineType.STANDARD,
    })
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.136.0

### Framework Version

_No response_

### Node.js Version

NodeJS-18

### OS

macOS Sonoma 14.4.1

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by mazyu36**
### Issue # (if applicable)

Closes #30194 

### Reason for this change
In #27913, the ItemProcessor was introduced for use with the Map Class. With the executionType in the ProcessorConfig, it was possible to specify the executionType for the Map.
On the other hand, in #28821, the DistributedMap Class was introduced. The mapExecutionType of the DistributedMap class always overwrites the executionType of the ProcessorConfig.
Therefore, when using the DistributedMap class, the implementation ignores the executionType of the ProcessorConfig. However, this behavior cannot be inferred from the documentation.

### Description of changes
* Added to the docs that when using the DistributedMap Class, the executionType in the ProcessorConfig is ignored.
* Also added a warning.

### Description of how you validated changes
Add unit tests and integ tests

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map.ts [hunk 1]
```diff
@@ -234,9 +235,10 @@ export class DistributedMap extends MapBase implements INextable {
    */
   public toStateJson(): object {
     let rendered: any = super.toStateJson();
-    if (this.mapExecutionType) {
```
Comment (mazyu36) [inline packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map.ts:237]: Removed this conditional statement as it is meaningless, because in the following code, mapExecutionType is always set, making the condition always evaluate to true.

https://github.com/aws/aws-cdk/blob/a37bc7283d2937a43a6c19d8a66a3347167cef75/packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map.ts#L129

File: packages/aws-cdk-lib/aws-stepfunctions/lib/types.ts [hunk 2]
```diff
@@ -220,14 +220,17 @@ export interface ProcessorConfig {
...
    */
   readonly mode?: ProcessorMode;
 
   /**
    * Specifies the execution type for the Map workflow.
    *
-   * You must provide this field if you specified `DISTRIBUTED` for the `mode` sub-field.
+   * If you use the `Map` class, you must provide this field if you specified `DISTRIBUTED` for the `mode` sub-field.
+   *
+   * If you use the `DistributedMap` class, this property ig ignored.
```
Comment (gracelu0) [inline packages/aws-cdk-lib/aws-stepfunctions/lib/types.ts:232]:
```suggestion
   * If you use the `DistributedMap` class, this property is ignored.
```

**Review by gracelu0 — DISMISSED** [review]
Hi @mazyu36 , thanks for working on this! Could you add a note in the docstring for the `mapExecutionType` property and update the README file as well so users know they should use that property to set the execution type for ItemProcessor. Thanks!

**Comment by mazyu36** [comment]
@gracelu0 
Thank you for the review!
I have updated the documentation and README.​​​​​​​​​​​​​​​​

File: packages/aws-cdk-lib/aws-stepfunctions/README.md [hunk 3]
```diff
@@ -595,6 +595,21 @@ const distributedMap = new sfn.DistributedMap(this, 'Distributed Map State', {
 distributedMap.itemProcessor(new sfn.Pass(this, 'Pass State'));
 ```
 
+If you want to specify the execution type for the DistributedMap, you must set the `mapExecutionType` property in the `DistributedMap` class. When using the `DistributedMap` class, the `ProcessorConfig.executionType` property is ignored.
```
Comment (gracelu0) [inline packages/aws-cdk-lib/aws-stepfunctions/README.md:598]: Do we mean 'execution type for `ItemProcessor`'? I don't see a mapExecutionType property in the [docs](https://docs.aws.amazon.com/step-functions/latest/dg/use-dist-map-orchestrate-large-scale-parallel-workloads.html#map-state-distributed-additional-fields)

File: packages/aws-cdk-lib/aws-stepfunctions/README.md [hunk 4]
```diff
@@ -595,6 +595,21 @@ const distributedMap = new sfn.DistributedMap(this, 'Distributed Map State', {
...
+
+In the following example, the execution type for the DistributedMap is set to `EXPRESS` based on the value specified for `mapExecutionType`.
```
Comment (gracelu0) [inline packages/aws-cdk-lib/aws-stepfunctions/README.md:600]: Same as above, `itemProcessor` instead of `DistributedMap`?

File: packages/aws-cdk-lib/aws-stepfunctions/README.md (hunk 3 above)
Comment (mazyu36) [reply packages/aws-cdk-lib/aws-stepfunctions/README.md]: Thank you for the review.
As you correctly understood, I have revised the expression to 'ItemProcessor in the DistributedMap' for more accurate phrasing.

**Comment by gracelu0** [comment]
@Mergifyio update

**Review by gracelu0 — APPROVED** [review]
Thank you for contributing!
