### PR TITLE
fix(cli): partition is not being resolved at missing value lookup

### LINKED ISSUE #15119: Error during codepipeline build when cdk.contest.json is removed
### The Question

With [#8905](https://github.com/aws/aws-cdk/issues/8905) being fixed I tried to remove the local cdk.context.json from one of my pipelines and re bootstrapped each account but received the following error for each account/stage I was deploying to (accounts and other variables replaced, note ${AWS::Partition} was not resolved):

Could not assume role in target account using current credentials (which are for account <pipeline account>) User: arn:aws:sts::_pipeline_account_:assumed-role/MyPipeline-PipelineBuildSynthCdkBuildProjec-GZQLAFL0MUF7/AWSCodeBuild-3755ba61-9da9-498b-8282-307bc9a94fcb is not authorized to perform: sts:AssumeRole on resource: arn:${AWS::Partition}:iam::1234:role/cdk-xyz789abc-lookup-role-1234-us-east-1 . Please make sure that this role exists in the account. If it doesn't exist, (re)-bootstrap the environment with the right '--trust', using the latest version of the CDK CLI.

I was able to get around the issue by setting the synth in my stage class

```
export class MyStage extends Stage {

    constructor(scope: Construct, id: string, props?: StageProps) {
        super(scope, id, props);

        const LOOKUP_ROLE_ARN = `arn:aws:iam::${this.account}:role/cdk-\${Qualifier}-lookup-role-${this.account}-${this.region}`;

        new Stack(this, 'MyStack, {
            synthesizer: new DefaultStackSynthesizer({
                lookupRoleArn: LOOKUP_ROLE_ARN,
            }),
        });

```
But I'm not sure why the default role isn't working

I also had to add permission for MyPipeline-PipelineBuildSynthCdkBuildProjec-GZQLAFL0MUF7 to sts:AssumeRole

### Environment

  - **CDK CLI Version:** 1.108.1
  - **Module Version:** 1.108.1
  - **Node.js Version:** 16.3.0
  - **OS:** 
  - **Language:** TypeScript

### Other information
related to #8905

### PR DESCRIPTION
**Pull request by otaviomacedo**
The partition component of the lookup role ARN, when present, was not being resolved. Normally, this resolution is done in the path that handles stacks and assets. The lookup, however, happens before that, so we have to replace the environment placeholders there as well.

Fixes #15119

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk/lib/api/cxapp/cloud-executable.ts [hunk 1]
```diff
@@ -87,7 +87,11 @@ export class CloudExecutable {
         if (tryLookup) {
           debug('Some context information is missing. Fetching...');
 
-          await contextproviders.provideContextValues(assembly.manifest.missing, this.props.configuration.context, this.props.sdkProvider);
+          await contextproviders.provideContextValues(
+            assembly.manifest.missing,
+            this.props.configuration.context,
+            this.props.sdkProvider,
+            assembly.stacks[0].environment);
```
Comment (rix0rrr) [inline packages/aws-cdk/lib/api/cxapp/cloud-executable.ts:94]: This is a dangerous assumption to make, and not necessarily true.

There could be multiple stacks with multiple environments in the same cloud assembly, each having a "missing context" that needs a lookup.

The answer is we don't have a nice neat object that has what you need already lying around--however, every `MissingContext` object that *could* have an `assumeRoleArn` MUST ALSO have `account` and `region` fields, so you can construct the target `Environment` on the fly from those two fields.

**Review by rix0rrr — CHANGES_REQUESTED** [review]

File: packages/aws-cdk/lib/api/cloudformation-deployments.ts [hunk 2]
```diff
@@ -244,7 +244,7 @@ export class CloudFormationDeployments {
   /**
    * Replace the {ACCOUNT} and {REGION} placeholders in all strings found in a complex object.
    */
-  private async replaceEnvPlaceholders<A extends { }>(object: A, env: cxapi.Environment): Promise<A> {
+  public async replaceEnvPlaceholders<A extends { }>(object: A, env: cxapi.Environment): Promise<A> {
```
Comment (rix0rrr) [inline packages/aws-cdk/lib/api/cloudformation-deployments.ts:247]: I think I'd rather extract this function out and make it take all necessary objects as arguments, than doing it this way around.

**Review by rix0rrr — CHANGES_REQUESTED** [review]

File: packages/aws-cdk/test/context-providers/generic.test.ts [hunk 3]
```diff
@@ -27,6 +27,36 @@ test('errors are reported into the context value', async () => {
   expect(context.get('asdf').$providerError).toBe('Something went wrong');
 });
 
+test('lookup role ARN is resolved', async () => {
+  // GIVEN
+  contextproviders.registerContextProvider(TEST_PROVIDER, class {
+    public async getValue(args: {[key: string]: any}): Promise<any> {
+      if (args.lookupRoleArn != null) {
```
Comment (rix0rrr) [inline packages/aws-cdk/test/context-providers/generic.test.ts:34]: This is not testing that the partition has been resolved to the right value. For all we know there could still be `${AWS::Partition}` in there.

**Review by rix0rrr — CHANGES_REQUESTED** [review]

**Review by rix0rrr — APPROVED** [review]
