### PR TITLE
fix(aws_route53): cannot use CfnParameter.valueAsNumber for L2 RecordSet weight

### LINKED ISSUE #31810: aws_route53: cannot use CfnParameter.valueAsNumber for L2 RecordSet weight
### Describe the bug

Cannot construct `ARecord` (and presumably any `RecordSet`) with `weight` resolved by `CfnParameter` value.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

`RecordSet` should successfully be synthesized with the parameter's token value for the weight.

### Current Behavior

Synthesis fails, token value representing a number outside the bounds of a valid weight (0-255).

```
Error: weight must be between 0 and 255 inclusive, got: -1.888154589708757e+289
    at new RecordSet (/.../node_modules/aws-cdk-lib/aws-route53/lib/record-set.js:1:3296)
    at new ARecord (/.../node_modules/aws-cdk-lib/aws-route53/lib/record-set.js:1:7665)
    ...
```

### Reproduction Steps

```typescript
import { aws_route53 as r53, CfnParameter } from 'aws-cdk-lib';

const weightParameter: CfnParameter = new CfnParameter(this, 'Weight', {
  default: 0,
  maxValue: 255,
  minValue: 0,
  type: 'Number'
});

const zone = r53.HostedZone.fromLookup(this, 'HostedZone', {
  domainName: 'example.com'
});

const aRecord = new r53.ARecord(this, 'ARecord', {
  weight: weightParameter.valueAsNumber,
  zone
});
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.151.0 (build b8289e2)

### Framework Version

_No response_

### Node.js Version

v20.13.1

### OS

Linux 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 GNU/Linux

### Language

TypeScript

### Language Version

_No response_

### Other information

Currently using this workaround:

```typescript
...

const aRecord = new r53.ARecord(this, 'ARecord', {
  weight: 0,
  zone
});

(aRecord.node.defaultChild as r53.CfnRecordSet).addPropertyOverride('Weight', weightParameter.valueAsNumber);
```

### PR DESCRIPTION
**Pull request by nicholaschiasson**
### Issue # (if applicable)

Closes #31810.

### Reason for this change

Could not use CfnParameter.valueAsNumber for L2 RecordSet weight.

### Description of changes

Adding validation of weight property as a potential Token in RecordSet constructor.

### Description of how you validated changes

Added unit and integration test.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by GavinZZ — DISMISSED** [review]

**Comment by GavinZZ** [comment]
@nicholaschiasson The integ test `aws-route53/test/integ.record-weight-from-cfnparameter` failed, would you be able to fix that and I'm happy to approve again to get this merged in.

**Comment by nicholaschiasson** [comment]
@GavinZZ thanks! The integ test is now fixed.

**Review by GavinZZ — APPROVED** [review]

**Comment by nicholaschiasson** [comment]
Hey @GavinZZ , sorry, I had misunderstood the first time around why the integration test was unstable, but I am confident I have solved it now. The issue was related to how the set identifier was derived if one was not provided with constructor options.

I realized that when generating a set ID, the method restricts the length of the ID to 64 characters. Since `token.valueAsNumber` produces a very long and non-deterministic-length (stringified) number, the test could now fail randomly. (Eg. `-1.8881545897089744e+289`)

To solve this, I modified the `configureSetIdentifier` method to check if the weight property is a token, and in that case, essentially mock the weight value as a three character string, since we can't know the parameter value at synthesis time, but we know that the maximum value allowed for weight is `255`. After generating the identifier, I inject the Token as string instead of as number, just so it may be more helpful for a developer maybe for debugging sake (Eg. `${Token[TOKEN.1037]}`). Regardless of if it is asNumber or asString, this will be substituted during synthesis. During CDK runtime however, maybe it could be helpful.

Let me know if this is a satisfactory solution. At the very least, the integ test should now be stable.

**Review by GavinZZ — DISMISSED** [review]

File: packages/aws-cdk-lib/aws-route53/lib/record-set.ts [hunk 1]
```diff
@@ -406,8 +406,15 @@ export class RecordSet extends Resource implements IRecordSet {
...
-      return this.createIdentifier(idPrefix);
+      if (Token.isUnresolved(this.weight)) {
+        const replacement = 'XXX'; // XXX simply because 255 is the highest value for a record weight
+        const idPrefix = `WEIGHT_${replacement}_ID_`;
+        const idTemplate = this.createIdentifier(idPrefix);
+        return idTemplate.replace(replacement, Token.asString(this.weight));
+      } else {
+        const idPrefix = `WEIGHT_${this.weight}_ID_`;
+        return this.createIdentifier(idPrefix);
+      }
```
Comment (GavinZZ) [inline packages/aws-cdk-lib/aws-route53/lib/record-set.ts:417]: Can you help me understand why this change is needed? I'm a bit worried on this change since it mutate the values when users update CDK version. CloudFormation marks `setIdentifier` property as non-interrupting property which means it won't cause resource replacement, but I'd like to understand this change more to make sure it's a safe change.

Comment (nicholaschiasson) [reply packages/aws-cdk-lib/aws-route53/lib/record-set.ts:417]: Hi @GavinZZ sure, I left a comment above trying to explain this. So as a matter of fact, this change is to make sure each synthesis yields the same result with no change.

By nature of supporting a CfnParameter value as the record weight property, the set ID gets kind of broken. This is only the case if a set ID is not provided in the constructor props, so the RecordSet constructor generates its own set ID.

So in the above code, before my change, if a `CfnParameter.valueAsNumber` was provided for the weight property, the actual value would look something like this `-1.8881545897089744e+289`. This would be stringified in the set ID, which significantly reduces the allowed length of the set ID (because we know that a record weight should be a number of 1, 2, or 3 characters in length usually). During synthesis though, this value would get substituted out, but the real problem is the fact that this value is non-deterministic. So on one run the token value for the parameter could be that which I pasted above, but it could be different on a subsequent run. This is what I found when rerunning the integration tests in my local environment. I found sometimes its length could vary by 1 or two characters, and break my tests, since that would affect the generated set ID.

To better understand what I'm trying my best to explain, you might have more luck drilling down into what `RecordSet.createIdentifier` is doing (and the method it calls).

So basically to fix this, because it is not possible to know the parameter value during synthesis time, I am imposing the constraint that if a weight is provided as a CfnParameter, or in other words as an unresolved Token, then we synthetically generate the set ID as if the weight value is 3 characters in length (since that is the maximum length by contract, ie. 255). Then after getting the generated set ID, I replace the dummy part with the token reference (this time using `.valueAsString` instead for better readability), and then we will see it resolved properly post-synthesis and we can be sure that the set ID is reproducible and will not change between seperate syntheses.

I hope that explanation makes sense. Let me know if this is still unclear or if you believe this is actually a breaking change.

Comment (GavinZZ) [reply packages/aws-cdk-lib/aws-route53/lib/record-set.ts:417]: Thanks for this detailed explanation. I actually totally missed your previous comment. Apologize for that.

I do see that you wrapped the code in an if statement `if (Token.isUnresolved(this.weight))` so it shouldn't affect other use case. My concern is that the final `setIdentifier` value will replace `XXX` with the value of `Token.asString(this.weight)`. 

You're right that the value of `this.weight` (when it's a token) is non-deterministic, and my understanding is that the value `Token.asString(this.weight)` would be non-deterministic either, no?

Comment (GavinZZ) [reply packages/aws-cdk-lib/aws-route53/lib/record-set.ts:417]: This solution makes sense to me!

File: packages/aws-cdk-lib/aws-route53/lib/record-set.ts [hunk 2]
```diff
@@ -406,8 +406,15 @@ export class RecordSet extends Resource implements IRecordSet {
     }
 
     if (this.weight !== undefined) {
-      const idPrefix = `WEIGHT_${this.weight}_ID_`;
-      return this.createIdentifier(idPrefix);
+      if (Token.isUnresolved(this.weight)) {
+        const replacement = 'XXX'; // XXX simply because 255 is the highest value for a record weight
+        const idPrefix = `WEIGHT_${replacement}_ID_`;
+        const idTemplate = this.createIdentifier(idPrefix);
+        return idTemplate.replace(replacement, Token.asString(this.weight));
```
Comment (GavinZZ) [inline packages/aws-cdk-lib/aws-route53/lib/record-set.ts:413]:
```suggestion
        const idPrefix = `WEIGHT_${Tokenization.stringifyNumber(this.weight)}_ID_`;
        return this.createIdentifier(idPrefix);
```

**Review by GavinZZ — CHANGES_REQUESTED** [review]
One minor comment for a slight improvement, and I'm happy to approve again.

File: packages/aws-cdk-lib/aws-route53/lib/record-set.ts (hunk 2 above)
Comment (nicholaschiasson) [reply packages/aws-cdk-lib/aws-route53/lib/record-set.ts:413]: Hi @GavinZZ , I am not sure if we can say that the length will be consistent by using `Tokenization.stringifyNumber`. Maybe you know more the internals than I do, but from what I can tell, this is basically like using `Token.asString` except it is type safe. So it is building a string like `${Token[TOKEN.0]}` and caching that using the `TokenMap` class.

The problem is that the numeric index part of that key is non-deterministic as well. I performed multiple runs of synthesis and always get a different value for that index. Each run, by chance, the number is always four digits in length, so I had values like `${Token[TOKEN.1032]}`, but from what I see in the code, we can't assume that will always be the case.

That numeric part is coming from `TokenMap`'s private field `tokenCounter` which is initialized as a random number. For each new token that is registered, the value is incremented. There could potentially be the case where our stringified token has one more or one fewer digits, just by chance.

This length could also be influenced by modifying code before the evaluation of our token. So suppose a developer adds code which is resolving a bunch of tokens before constructing their RecordSet (for example, adding and using a bunch more CfnParameters). Suddenly CDK may detect a change to the set ID because the length of the stringified token will be different, and thus the generated set ID will be shortened.

So it's for this reason that I decided to spoof the weight value when generating the set ID. If the things I mentioned above don't actually raise any concerns, then we can go ahead apply your suggestion and merge after.

Comment (GavinZZ) [reply packages/aws-cdk-lib/aws-route53/lib/record-set.ts:413]: You're right. This could technically result in some error case. I tested it out and in some cases, it does return less digits. I'm happy to approve your current solution.

**Review by GavinZZ — DISMISSED** [review]

**Comment by nicholaschiasson** [comment]
Hi @GavinZZ , it seems like something is blocking the merge. Do you have any detail about that?

**Review by GavinZZ — APPROVED** [review]
