### PR TITLE
Assets: upload to and grant permissions on prefix

### LINKED ISSUE #484: Assets: grant permissions on a wildcard
Right now, we only grant permissions on specific versions of an asset. That means that if we publish a new version, the Lambda or CodeBuild role using the assets immediately loses permissions to all previous versions of the asset, causing them to fail.

This is inconvenient for CodeBuilds, but will prevent gradual Lambda deployments for example.

We should probably name the asset something like

```
$BUCKET/assets/$ID/abcdef12345.zip
```

And give permissions on the `$ID` prefix, so that all versions are accepted.

### PR DESCRIPTION
**Pull request by rix0rrr**
We need to give asset consumers permissions on all versions of
an asset, not just the latest version. Otherwise, we will never
be able to do rolling updates.

Also add caching on AWS client instances, so with multiple
asset uploads we don't have to construct a new S3 client for
every asset (incurring credential lookups for each one).

This fixes #484.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by rix0rrr** [comment]
Practical changes: 

The assets are now uploaded to something like:

```
s3://cdktoolkit-stagingbucket-i0tp1gw9qhfn/assets/cdk-dev-huijbersWindowsInstallationTestDirectory46EF3817/978e060951d0c6ad5319aee80a274a0a214db401526914729cbf8b604a105fbb.zip
```

And we give permissions on the prefix `assets/cdk-dev-huijbersWindowsInstallationTestDirectory46EF3817/*`

I'm not entirely sure I like the additional input `Parameter` to the template to specify the prefix. We might run out of Parameters quickly this way. A number of ideas to solve this:

* Make all assets require to use the same bucket
* Encode multiple parameters into a single parameter string, split on a magic character like `|` or something.
* Mandate that the asset URL structure is *ALWAYS* the same, (has the same number of components), so we can split on `/` and append the `*`. Because CFN doesn't have a concept of slices, we must know exactly how many path components there will be in that case, though (we'll have to do `join('/', [select(1, split('/', p)), select(2, split('/', p)), ..., '*'])`)

File: packages/@aws-cdk/assets/lib/asset.ts [hunk 1]
```diff
@@ -84,33 +86,45 @@ export class Asset extends cdk.Construct {
...
         // form the s3 URL of the object key
         this.s3Url = this.bucket.urlForObject(this.s3ObjectKey);
 
+        // Get a unique identifier for this asset, which will be used
+        // as a folder to group different versions of the same asset together.
+        //
+        // Even though this code looks horrible, this is actually not a terrible thing
+        // to do. The generated ID will contain the *stack name* as well, which is a
+        // perfectly nice thing to do to disambiguate similarly named assets in different stacks.
+        const uniqueId = new cdk.HashedAddressingScheme().allocateAddress(this.path.split('/'));
```
Comment (eladb) [inline packages/@aws-cdk/assets/lib/asset.ts]: I keep wondering if we should just expose a `uniqueId` in the `Construct` level (and use for `resource.logicalId`). This keeps coming back and I think might be useful generally, and not only for CloudFormation resource identifiers.

File: packages/@aws-cdk/assets/lib/asset.ts [hunk 2]
```diff
@@ -124,7 +138,11 @@ export class Asset extends cdk.Construct {
      * Grants read permissions to the principal on the asset's S3 object.
      */
     public grantRead(principal?: iam.IPrincipal) {
-        this.bucket.grantRead(principal, this.s3ObjectKey);
+        // We give permissions on all files with the same prefix. Presumably
+        // different versions of the same file will have the same prefix
+        // and we don't want to accidentally revoke permission on old versions
+        // when deploying a new version.
+        this.bucket.grantRead(principal, new cdk.FnConcat(this.s3PrefixParam.value, "*"));
```
Comment (eladb) [inline packages/@aws-cdk/assets/lib/asset.ts]: We should implement #24

File: packages/@aws-cdk/assets/lib/asset.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/@aws-cdk/assets/lib/asset.ts]: I agree, but their scopes are different, which complicates it a bit.

In a tree like this:

```
root
└── Stack
      └── Construct
             └── Construct

    ├─────── path ───────┤

         ├─ logical id ──┤
```

The `.path` is from the root to the construct, but the logical ID is only calculated off the nearest enclosing stack to the construct. If we didn't do that, all enclosing logical IDs would being with the stack name, which is not terrible for the IDs that they are, but they're also used to generate human-readable names, where that would be quite ugly (and in fact CFN sometimes--but not always!--prepends the stack name itself as well).

So we should probably still keep them separated, or have something like `uniqueIdRelativeTo(ancestor)`

Comment (eladb) [reply packages/@aws-cdk/assets/lib/asset.ts]: We could allow constructs to opt-out of the human portion of name generation, so they will be "skipped" when producing the human portion (something like `hideName = true`).

**Comment by rix0rrr** [comment]
This change is pending https://github.com/awslabs/aws-cdk/pull/518

File: packages/@aws-cdk/assets/lib/asset.ts [hunk 3]
```diff
@@ -84,15 +89,15 @@ export class Asset extends cdk.Construct {
...
-            description: `S3 object for asset "${this.path}"`
+            description: `S3 key for asset version "${this.path}"`
         });
 
         this.s3BucketName = bucketParam.value;
-        this.s3ObjectKey = keyParam.value;
-
-        // grant the lambda's role read permissions on the code s3 object
+        this.s3Prefix = new cdk.FnSelect(0, new cdk.FnSplit(cxapi.ASSET_PREFIX_SEPARATOR, keyParam.value));
+        const s3Filename = new cdk.FnSelect(1, new cdk.FnSplit(cxapi.ASSET_PREFIX_SEPARATOR, keyParam.value));
```
Comment (RomainMuller) [inline packages/@aws-cdk/assets/lib/asset.ts]: You realize (however unlikely that is), that `||` might actually be part of the object key?

Comment (rix0rrr) [reply packages/@aws-cdk/assets/lib/asset.ts]: That is going to be true for any separator we pick. So yeah, I'm balancing aesthetics vs likelihood

Comment (rix0rrr) [reply packages/@aws-cdk/assets/lib/asset.ts]: That is going to be true for any separator we pick. So yeah, I'm balancing aesthetics vs likelihood

Comment (rix0rrr) [reply packages/@aws-cdk/assets/lib/asset.ts]: You do realize that git commit hashes may clash? :p
