### PR TITLE
fix(cloudfront): all origin access identities have identical names

### LINKED ISSUE #9580: [cloudfront-origins] All origin access identities have identical names
Currently when you use the new cloudfront-origins package to create S3 origins, it generates an OAI with the exact same name each time. If you have multiple origins/distributions you end up with a list of identities all labeled `Allows CloudFront to reach the bucket`. In the console when you inspect the distribution it resolves the comment/name field for this, so you can't tell what distribution is using what without enumerating them using the API.

I'd suggest propagating the origin's logical name in to the comment field to make it clearer which OAI is in use for which bucket/origin.

### Environment

  - **CLI Version      :** 1.57
  - **Framework Version:** 1.57
  - **Node.js Version:** 1.12
  - **OS               :** MacOS
  - **Language (Version):** all

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by njlynch**
Replaces the single hard-coded value for the origin access identity comment
field with one that refernces the origin's ID.

fixes #9580

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-cloudfront-origins/lib/s3-origin.ts [hunk 1]
```diff
@@ -58,7 +58,9 @@ class S3BucketOrigin extends cloudfront.OriginBase {
 
   public bind(scope: cdk.Construct, options: cloudfront.OriginBindOptions): cloudfront.OriginBindConfig {
     if (!this.originAccessIdentity) {
-      this.originAccessIdentity = new cloudfront.OriginAccessIdentity(scope, 'S3Origin');
+      this.originAccessIdentity = new cloudfront.OriginAccessIdentity(scope, 'S3Origin', {
+        comment: `Access identity for ${options.originId}`,
```
Comment (nija-at) [inline packages/@aws-cdk/aws-cloudfront-origins/lib/s3-origin.ts:62]: Minor suggestion

```suggestion
        comment: `Access identity for origin [${options.originId}]`,
```

**Review by nija-at — APPROVED** [review]
quick reminder to keep commit titles lower case (except when referring to a class name, property key or such) - https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#step-4-commit

File: packages/@aws-cdk/aws-cloudfront-origins/lib/s3-origin.ts (hunk 1 above)
Comment (njlynch) [reply packages/@aws-cdk/aws-cloudfront-origins/lib/s3-origin.ts:62]: This property is already super-long in the console experience, and the IDs all have 'origin' in them by definition, so I would rather opt for the more succinct version in this case.
