### PR TITLE
fix(aws-ecs): fix default daemon deploymentConfig values

### LINKED ISSUE #2209: Daemon scheduling sets wrong deploymentConfiguration defaults
The following code raises an error:
```
import ecs = require('@aws-cdk/aws-ecs');
import ec2 = require('@aws-cdk/aws-ec2');
import cdk = require('@aws-cdk/cdk');

const app = new cdk.App();
const stack = new cdk.Stack(app, 'aws-ecs-integ-ecs');

// Create a cluster
const vpc = new ec2.VpcNetwork(stack, 'Vpc', { maxAZs: 2 });
const cluster = new ecs.Cluster(stack, 'EcsCluster', { vpc });
cluster.addCapacity('DefaultAutoScalingGroup', {
  instanceType: new ec2.InstanceType('t2.micro')
});

// Create Task Definition with placement constraint
const taskDefinition = new ecs.Ec2TaskDefinition(stack, 'TaskDef');
const container = taskDefinition.addContainer('web', {
  image: ecs.ContainerImage.fromRegistry("amazon/amazon-ecs-sample"),
  memoryLimitMiB: 256,
});

container.addPortMappings({
  containerPort: 80,
  hostPort: 8080,
  protocol: ecs.Protocol.Tcp
});

// Create Service
new ecs.Ec2Service(stack, "Service", {
  cluster,
  taskDefinition,
  daemon: true,
});

app.run();
```
Error:
```
 | Service/Service (ServiceD69D759B) The daemon scheduling strategy does not support values above 100 for maximumPercent on a deployment configuration. Change the maximumPercent value to 100, and try again (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: xxxxxxxx-5b19-11e9-9a23-f1a4d7df54a9)
```

This is bc base service sets max/min defaults to 200/50, respectively. when it should be 100/0.

From the [docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_services.html#service_scheduler):

If deploymentConfiguration is specified, the maximum percent parameter must be 100. The default value for a daemon service for maximumPercent is 100%. The default value for a daemon service for minimumHealthyPercent is 0% for the AWS CLI, the AWS SDKs, and the APIs, and 50% for the AWS Management Console.

### PR DESCRIPTION
**Pull request by SoManyHs**
Fixes #2209

----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [ ] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-ecs/lib/ec2/ec2-service.ts [hunk 1]
```diff
@@ -70,6 +70,14 @@ export class Ec2Service extends BaseService implements elb.ILoadBalancerTarget {
       throw new Error('Daemon mode launches one task on every instance. Don\'t supply desiredCount.');
     }
 
+    if (props.daemon && props.maximumPercent !== undefined && props.maximumPercent !== 100) {
```
Comment (eladb) [inline packages/@aws-cdk/aws-ecs/lib/ec2/ec2-service.ts]: Document these defaults/constraints in Props

Comment (SoManyHs) [reply packages/@aws-cdk/aws-ecs/lib/ec2/ec2-service.ts]: done!

Comment (eladb) [reply packages/@aws-cdk/aws-ecs/lib/ec2/ec2-service.ts]: I would also document the requirement that this has to be 100/0 for daemon mode (not just that it’s the default)
