### PR TITLE
fix(cloudfront): truncate long ResponseHeaderPolicy names

### LINKED ISSUE #21524: (aws-cloudfront): ResponseHeadersPolicy policy name can exceed maximum
### Describe the bug

The auto-generated `Name` for a CloudFront `ResponseHeadersPolicy` can be longer than the (unpublished) maximum of 129 characters. These very long stack names are common when using CDK Pipelines.

### Expected Behavior

I expected CDK to truncate the auto-generated name to be shorter than the maximum allowed policy name.

### Current Behavior

When the name field is too long, it produces this very opaque error message:

```
1:43:29 PM | CREATE_FAILED        | AWS::CloudFront::ResponseHeadersPolicy | ResponseHeadersPolicy
Resource handler returned message: "Invalid request provided: AWS::CloudFront::ResponseHeadersPolicy"
(RequestToken: d86fa560-67f9-db71-29af-402e0fdee080, HandlerErrorCode: InvalidRequest)
1:43:30 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack             | AVeryLongCdkBugRep...eAct
uallyQuiteLong
The following resource(s) failed to create: [ResponseHeadersPolicy13DBF9E0]. Rollback requested by use
r.
1:43:30 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack             | AVeryLongCdkBugRep...eAct
uallyQuiteLong
The following resource(s) failed to create: [ResponseHeadersPolicy13DBF9E0]. Rollback requested by use
r.
```

I was able to determine the `Name` field was too long by trying to create a policy in via the UI with the same name. The UI gave me back a much better error message:

> The parameter Name is too big.

Screen Shot 2022-08-09 at 13 49 21

### Reproduction Steps

https://github.com/blimmer/cdk-bug-reports/commit/2e519b8ba962b09276a71fa26344d1a2d457a572

This commit shows the problem. This is a fresh repo generated by `cdk init` with just the changes indicated in the diff.

### Possible Solution

There are lots of examples scattered throughout the code where a name is restricted in length, e.g.: 

https://github.com/aws/aws-cdk/blob/74318c7d22bfc00de9e005f68a0a6aaa58c7db39/packages/%40aws-cdk/aws-codeguruprofiler/lib/profiling-group.ts#L197-L203

The character limit isn't defined explicitly in the [CFN docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-responseheaderspolicy-responseheaderspolicyconfig.html#cfn-cloudfront-responseheaderspolicy-responseheaderspolicyconfig-name) or in the API docs:

```
Name -> (string)
  A name to identify the response headers policy.

  The  name  must  be unique for response headers policies in this
  Amazon Web Services account.
```

From trial and error in the console, it appears the limit is 129 characters.

### Additional Information/Context

_No response_

### CDK CLI Version

2.36.0 (build 7cde279)

### Framework Version

_No response_

### Node.js Version

16.14.0

### OS

macOS

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by blimmer**
Fixes #21524

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-cloudfront/lib/response-headers-policy.ts [hunk 1]
```diff
@@ -140,6 +140,14 @@ export class ResponseHeadersPolicy extends Resource implements IResponseHeadersP
       xssProtection: behavior.xssProtection,
     };
   }
+
+  private generateUniqueId(): string {
+    const name = Names.uniqueId(this);
+    if (name.length > 128) {
```
Comment (blimmer) [inline packages/@aws-cdk/aws-cloudfront/lib/response-headers-policy.ts:146]: Even though it appears you can successfully create up to 129 characters, I used 128 because that seemed more standard.

**Review by otaviomacedo — APPROVED** [review]

File: packages/@aws-cdk/aws-cloudfront/lib/response-headers-policy.ts [hunk 2]
```diff
@@ -140,6 +140,14 @@ export class ResponseHeadersPolicy extends Resource implements IResponseHeadersP
       xssProtection: behavior.xssProtection,
     };
   }
+
+  private generateUniqueId(): string {
```
Comment (blimmer) [inline packages/@aws-cdk/aws-cloudfront/lib/response-headers-policy.ts:144]: This pattern exists in a few places. It might be nice to have `Names.uniqueId` take an optional second parameter for the maximum allowed length. That way, we could get rid of all these `generateUniqueId` methods and just say `Names.uniqueId(this, 128)`.

Comment (TheRealAmazonKendra) [reply packages/@aws-cdk/aws-cloudfront/lib/response-headers-policy.ts:144]: it would be better to use `Names.uniqueResourceName()` instead. It has length handling built in.

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
One quick question: does this have the potential to create breaking changes for existing resources? I think no, but I'm not 100% positive.

File: packages/@aws-cdk/aws-cloudfront/lib/response-headers-policy.ts (hunk 2 above)
Comment (blimmer) [reply packages/@aws-cdk/aws-cloudfront/lib/response-headers-policy.ts:144]: Hmm, I can't seem to find that `uniqueResourceName` anywhere with a quick grep.

**Comment by blimmer** [comment]
@TheRealAmazonKendra, the Name property can be updated without replacement, it looks like.

I think the only potential for breaking existing resources would be if someone managed to create a 129-character policy name (which appears to be allowed, but is not documented) and imported it outside of CDK by name somewhere else. It feels like 129 is so random (seems like it should be 128), so that's why I truncated to 128. IMO this scenario's pretty unlikely, but it is technically possible.

File: packages/@aws-cdk/aws-cloudfront/lib/response-headers-policy.ts (hunk 2 above)
Comment (TheRealAmazonKendra) [reply packages/@aws-cdk/aws-cloudfront/lib/response-headers-policy.ts:144]: Here you go: https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/core/lib/names.ts#L84

**Comment by TheRealAmazonKendra** [comment]
> @TheRealAmazonKendra, the Name property can be updated without replacement, it looks like.
> 
> I think the only potential for breaking existing resources would be if someone managed to create a 129-character policy name (which appears to be allowed, but is not documented) and imported it outside of CDK by name somewhere else. It feels like 129 is so random (seems like it should be 128), so that's why I truncated to 128. IMO this scenario's pretty unlikely, but it is technically possible.

Cool, thanks for the verification.

File: packages/@aws-cdk/aws-cloudfront/lib/response-headers-policy.ts (hunk 2 above)
Comment (blimmer) [reply packages/@aws-cdk/aws-cloudfront/lib/response-headers-policy.ts:144]: Doh, my fork was out of date 😅 - thank you!

Comment (blimmer) [reply packages/@aws-cdk/aws-cloudfront/lib/response-headers-policy.ts]: updated with [`63bc9b6` (#21525)](https://github.com/aws/aws-cdk/pull/21525/commits/63bc9b63741f9029cc39d3b81488d28451a66b89)

**Review by TheRealAmazonKendra — APPROVED** [review]
