### PR TITLE
fix(apigateway): changes to gateway response does not trigger auto deployment

### LINKED ISSUE #10963: [api-gateway] RestApi construct does not automatically create new deployments after addGatewayResponse
When calling the `addGatewayResponse` method on a `RestApi`, any `GatewayResponse` added doesn't come into effect because it doesn't trigger a new deployment. Manually creating a new deployment through AWS UI fixes this.

Similar to https://github.com/aws/aws-cdk/issues/8024
Related: https://github.com/aws/aws-cdk/issues/5354#issuecomment-591824660

### Reproduction Steps

First deploy:
```typescript
    const restApi = new RestApi(this,"MyRestApi");

    const restNotes = restApi.root.addResource("notes");
    restNotes.addMethod(HttpMethod.GET, ...);
```

Subsequent deploy:
```typescript
    const restApi = new RestApi(this,"MyRestApi");

    restApi.addGatewayResponse("4xxGatewayResponse", {
      type: ResponseType.DEFAULT_4XX,
      responseHeaders: {
        "Access-Control-Allow-Origin": "'*'",
        "Access-Control-Allow-Headers": "'*'",
      },
    });

    const restNotes = restApi.root.addResource("notes");
    restNotes.addMethod(HttpMethod.GET, ...);
```

### What did you expect to happen?

A change in the `GatewayResponse` for an API should trigger a deployment, as that's what's required when using the UI.

### What actually happened?

No new deployment was created when the `GatewayResponse` resource was changed.

### Environment

  - **CLI Version      :1.51.0**
  - **Framework Version: 1.53.0**
  - **Node.js Version: 10.16.3** 
  - **OS               : MacOS**
  - **Language (Version): TypeScript (3.9.6)** 

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by nija-at**
The auto deployment feature is implemented by recording changes to the
RestApi and replacing the AWS::ApiGateway::Deployment resource on any
changes.

The GatewayResponse construct was not registered, and hence no
deployments occurred on changes to this.

fixes #10963

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-apigateway/lib/gateway-response.ts [hunk 1]
```diff
@@ -58,13 +58,25 @@ export class GatewayResponse extends Resource implements IGatewayResponse {
...
       responseParameters: this.buildResponseParameters(props.responseHeaders),
       responseTemplates: props.templates,
       statusCode: props.statusCode,
-    });
+    };
+
+    const resource = new CfnGatewayResponse(this, 'Resource', gatewayResponseProps);
+
+    const deployment = props.restApi.latestDeployment;
+    if (deployment) {
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-apigateway/lib/gateway-response.ts:72]: Is there value in generalizing this?

**Review by rix0rrr — APPROVED** [review]
