### PR TITLE
fix(events-targets): make LogGroupTargetInput extend RuleTargetInput for JSII compatibility

### LINKED ISSUE #36733: (aws_events_targets): Unable to instantiate `targets.CloudWatchLogGroup` in Python due to bad typeguard checks
### Describe the bug

the docstring for LogGroupTargetInput shows an example:

```python
        rule.add_target(targets.CloudWatchLogGroup(log_group,
            log_event=targets.LogGroupTargetInput.from_object_v2(
                timestamp=events.EventField.from_path("$.time"),
                message=events.EventField.from_path("$.detail-type")
            )
        ))
```

When attempting to use idiom this I get the following error at deploy time:

>   File "/home/circleci/project/infra/constructs/notifications.py", line 107, in __init__
>     self.log_target = events_targets.CloudWatchLogGroup(
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/circleci/project/.venv/lib/python3.11/site-packages/jsii/_runtime.py", line 118, in __call__
>     inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/circleci/project/.venv/lib/python3.11/site-packages/aws_cdk/aws_events_targets/__init__.py", line 1801, in __init__
>     props = LogGroupProps(
>             ^^^^^^^^^^^^^^
>   File "/home/circleci/project/.venv/lib/python3.11/site-packages/aws_cdk/aws_events_targets/__init__.py", line 5798, in __init__
>     check_type(argname="argument log_event", value=log_event, expected_type=type_hints["log_event"])
>   File "/home/circleci/project/.venv/lib/python3.11/site-packages/aws_cdk/aws_events_targets/__init__.py", line 819, in check_type
>     return typeguard.check_type(argname=argname, value=value, expected_type=expected_type) # type:ignore
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/circleci/project/.venv/lib/python3.11/site-packages/typeguard/__init__.py", line 757, in check_type
>     checker_func(argname, value, expected_type, memo)
>   File "/home/circleci/project/.venv/lib/python3.11/site-packages/typeguard/__init__.py", line 558, in check_union
>     raise TypeError('type of {} must be one of ({}); got {} instead'.
> TypeError: type of argument log_event must be one of (aws_cdk.aws_events_targets.LogGroupTargetInput, NoneType); got aws_cdk.aws_events._RuleTargetInputProxy instead

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Library Version

_No response_

### Expected Behavior

it works - my code matches the docstring example in passing log_event kwarg as `log_event=targets.LogGroupTargetInput.from_object_v2(...)`

### Current Behavior

the error implies that the runtime return type of `LogGroupTargetInput.from_object_v2` is actually `aws_cdk.aws_events._RuleTargetInputProxy` rather than the `LogGroupTargetInput` it's annotated as (and was given as the expectation to typeguard)

### Reproduction Steps

I have the following code:

```python
import json

from aws_cdk import (
    RemovalPolicy,
    Stack,
    aws_events as events,
    aws_events_targets as events_targets,
    aws_logs as logs,
)
from constructs import Construct


class MyConstruct(Construct):
    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        **kwargs,
    ):
        super().__init__(scope, construct_id, **kwargs)

        message = {
            "type": "message",
            "attachments": [
                {
                    "contentType": "application/vnd.microsoft.card.adaptive",
                    "contentUrl": None,
                    "content": {
                        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                        "type": "AdaptiveCard",
                        "version": "1.2",
                        "body": [
                            {
                                "type": "TextBlock",
                                "text": "❗ Step Function Failure",
                            },
                            {
                                "type": "TextBlock",
                                "text": f"Time: {events.EventField.from_path('$.time')}",
                                "wrap": True,
                            },
                            {
                                "type": "TextBlock",
                                "text": f"ARN: {events.EventField.from_path('$.detail.stateMachineArn')}",
                                "wrap": True,
                            },
                            {
                                "type": "TextBlock",
                                "text": f"Error: {events.EventField.from_path('$.detail.error')}",
                                "wrap": True,
                            },
                            {
                                "type": "TextBlock",
                                "text": f"Cause: {events.EventField.from_path('$.detail.cause')}",
                                "wrap": True,
                            },
                        ],
                    },
                }
            ],
        }
        log_group = logs.LogGroup(
            self,
            "TeamsWebhookEventLogs",
            retention=logs.RetentionDays.ONE_MONTH,
            removal_policy=RemovalPolicy.DESTROY,
        )
        self.log_target = events_targets.CloudWatchLogGroup(
            log_group,
            log_event=events_targets.LogGroupTargetInput.from_object_v2(
                timestamp=events.EventField.from_path("$.time"),
                message=json.dumps(message),
            ),
        )


class MyStack(Stack):
    def __init__(
        self,
        scope: Construct,
        construct_id: str,
    ):
        super().__init__(scope, construct_id)
        MyConstruct(self, "Test")
```

### Possible Solution

_No response_

### Additional Information/Context

Relevant CDK code...

https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-events-targets/lib/log-group.ts#L54-L65

in the resulting Python CDK lib looks like:
```python
    @jsii.member(jsii_name="fromObjectV2")
    @builtins.classmethod
    def from_object_v2(
        cls,
        *,
        message: typing.Any = None,
        timestamp: typing.Any = None,
    ) -> "LogGroupTargetInput":
        '''Pass a JSON object to the the log group event target.

        May contain strings returned by ``EventField.from()`` to substitute in parts of the
        matched event.

        :param message: The value provided here will be used in the Log "message" field. This field must be a string. If an object is passed (e.g. JSON data) it will not throw an error, but the message that makes it to CloudWatch logs will be incorrect. This is a likely scenario if doing something like: EventField.fromPath('$.detail') since in most cases the ``detail`` field contains JSON data. Default: EventField.detailType
        :param timestamp: The timestamp that will appear in the CloudWatch Logs record. Default: EventField.time
        '''
        options = LogGroupTargetInputOptions(message=message, timestamp=timestamp)

        return typing.cast("LogGroupTargetInput", jsii.sinvoke(cls, "fromObjectV2", [options]))
```

https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-events-targets/lib/log-group.ts#L76-L103

in Python CDK lib looks like:

```python
@jsii.data_type(
    jsii_type="aws-cdk-lib.aws_events_targets.LogGroupProps",
    jsii_struct_bases=[TargetBaseProps],
    name_mapping={
        "dead_letter_queue": "deadLetterQueue",
        "max_event_age": "maxEventAge",
        "retry_attempts": "retryAttempts",
        "event": "event",
        "install_latest_aws_sdk": "installLatestAwsSdk",
        "log_event": "logEvent",
    },
)
class LogGroupProps(TargetBaseProps):
    def __init__(
        self,
        *,
        dead_letter_queue: typing.Optional["_IQueue_7ed6f679"] = None,
        max_event_age: typing.Optional["_Duration_4839e8c3"] = None,
        retry_attempts: typing.Optional[jsii.Number] = None,
        event: typing.Optional["_RuleTargetInput_6beca786"] = None,
        install_latest_aws_sdk: typing.Optional[builtins.bool] = None,
        log_event: typing.Optional["LogGroupTargetInput"] = None,
    ) -> None:
        '''Customize the CloudWatch LogGroup Event Target.

        :param dead_letter_queue: The SQS queue to be used as deadLetterQueue. Check out the `considerations for using a dead-letter queue <https://docs.aws.amazon.com/eventbridge/latest/userguide/rule-dlq.html#dlq-considerations>`_. The events not successfully delivered are automatically retried for a specified period of time, depending on the retry policy of the target. If an event is not delivered before all retry attempts are exhausted, it will be sent to the dead letter queue. Default: - no dead-letter queue
        :param max_event_age: The maximum age of a request that Lambda sends to a function for processing. Minimum value of 60. Maximum value of 86400. Default: Duration.hours(24)
        :param retry_attempts: The maximum number of times to retry when the function returns an error. Minimum value of 0. Maximum value of 185. Default: 185
        :param event: (deprecated) The event to send to the CloudWatch LogGroup. This will be the event logged into the CloudWatch LogGroup Default: - the entire EventBridge event
        :param install_latest_aws_sdk: Whether the custom resource created wll default to install latest AWS SDK. Default: - install latest AWS SDK
        :param log_event: The event to send to the CloudWatch LogGroup. This will be the event logged into the CloudWatch LogGroup Default: - the entire EventBridge event

        :exampleMetadata: infused

        Example::

            import aws_cdk.aws_logs as logs
            # log_group: logs.LogGroup
            # rule: events.Rule
            
            
            rule.add_target(targets.CloudWatchLogGroup(log_group,
                log_event=targets.LogGroupTargetInput.from_object_v2(
                    message=JSON.stringify({
                        "CustomField": "CustomValue"
                    })
                )
            ))
        '''
        if __debug__:
            type_hints = typing.get_type_hints(_typecheckingstub__955ae13452482b1f3001946153d6bfa138fb7c7e8a5c482a52178f35142a7c9c)
            check_type(argname="argument dead_letter_queue", value=dead_letter_queue, expected_type=type_hints["dead_letter_queue"])
            check_type(argname="argument max_event_age", value=max_event_age, expected_type=type_hints["max_event_age"])
            check_type(argname="argument retry_attempts", value=retry_attempts, expected_type=type_hints["retry_attempts"])
            check_type(argname="argument event", value=event, expected_type=type_hints["event"])
            check_type(argname="argument install_latest_aws_sdk", value=install_latest_aws_sdk, expected_type=type_hints["install_latest_aws_sdk"])
            check_type(argname="argument log_event", value=log_event, expected_type=type_hints["log_event"])
        self._values: typing.Dict[builtins.str, typing.Any] = {}
        if dead_letter_queue is not None:
            self._values["dead_letter_queue"] = dead_letter_queue
        if max_event_age is not None:
            self._values["max_event_age"] = max_event_age
        if retry_attempts is not None:
            self._values["retry_attempts"] = retry_attempts
        if event is not None:
            self._values["event"] = event
        if install_latest_aws_sdk is not None:
            self._values["install_latest_aws_sdk"] = install_latest_aws_sdk
        if log_event is not None:
            self._values["log_event"] = log_event
```

### AWS CDK Library version (aws-cdk-lib)

2.235.0

### AWS CDK CLI version

2.1034.0 (build 82fb0f3)

### Node.js Version

v18.18.0

### OS

CircleCI ubuntu-2204:2023.10.1

### Language

Python

### Language Version

3.11

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Abogical**
### Issue # (if applicable)

Closes #36733.

### Reason for this change

`LogGroupTargetInput.fromObjectV2()` returns a `FieldAwareEventInput` (which extends `RuleTargetInput`) but is typed as `LogGroupTargetInput` — an unrelated abstract class. This works in TypeScript via structural typing but fails at runtime in Python and Java because JSII generates nominal type checks (`typeguard` in Python). Passing the result of `fromObjectV2()` as the `logEvent` prop raises a `TypeError` in those languages.

### Description of changes

- Made `LogGroupTargetInput` extend `RuleTargetInput`, establishing a proper type hierarchy.
- Introduced a private `LogGroupFieldAwareInput` class that extends `LogGroupTargetInput` and wraps a `FieldAwareEventInput`, delegating `bind()` to it.
- `fromObjectV2()` now returns `LogGroupFieldAwareInput` instead of a raw `FieldAwareEventInput`, so the returned object is nominally a `LogGroupTargetInput`.
- The deprecated `fromObject()` method is unchanged and still returns `RuleTargetInput`. Its parameter type was widened to `any` with a default of `{}` to satisfy JSII inheritance constraints while preserving backward compatibility.

**Known trade-off:** Because `LogGroupTargetInput` now extends `RuleTargetInput`, JSII languages expose inherited static methods like `LogGroupTargetInput.fromText()` and `LogGroupTargetInput.fromEventPath()`. These return `RuleTargetInput`, not `LogGroupTargetInput`, which could be confusing since `LogGroupTargetInput` is meant to constrain input to `{timestamp, message}`. This is accepted as a pragmatic fix for a P1 bug — the clean alternative (extracting an `IRuleTargetInput` interface) would require changes to the core `aws-events` API surface. See [CDK Design Guidelines](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md) on preferring interfaces over inheritance.

Alternatives considered:
- Making `FieldAwareEventInput` extend `LogGroupTargetInput` — rejected because it would create a weird coupling between `aws-events` and `aws-events-targets`.

### Describe any new or updated permissions being added

N/A — no IAM permission changes.

### Description of how you validated changes

- All existing unit tests in `log-group.test.ts` pass with identical synthesized CloudFormation output.
- Added two new tests verifying `fromObjectV2()` returns `instanceof LogGroupTargetInput` and `instanceof RuleTargetInput`.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

BREAKING CHANGE: The deprecated function LogGroupTargetInput.fromObject changes its options argument from optional to required. This is necessary for the interface inheritance. Since this is deprecated, users are encouraged to use fromObjectV2.

### CODE REVIEW

File: packages/aws-cdk-lib/aws-events-targets/lib/log-group.ts [hunk 1]
```diff
@@ -46,7 +46,7 @@ export abstract class LogGroupTargetInput {
    *
    * @deprecated use fromObjectV2
    */
-  public static fromObject(options?: LogGroupTargetInputOptions): RuleTargetInput {
+  public static fromObject(options: any): RuleTargetInput {
```
Comment (vishaalmehrishi) [inline packages/aws-cdk-lib/aws-events-targets/lib/log-group.ts:50]: This changes `fromObject` from optional to required parameter, breaking existing code that calls `LogGroupTargetInput.fromObject()` without arguments. Per CDK stability guarantees in [CONTRIBUTING.md § API surface changes](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#api-surface-changes):

> Changes that will make existing programs fail to compile are not allowed. Typical examples of that are:
> - Adding required properties to a struct that is used as an input to a constructor or method. **This also includes changing a type from nullable to non-nullable.**

The breaking change is avoidable — the implementation already handles undefined via optional chaining (`options?.timestamp ?? EventField.time`). Adding a default value satisfies JSII inheritance while preserving backward compatibility:

```ts
public static fromObject(options: any = {}): RuleTargetInput {
```

This would also remove the need for the `allowed-breaking-changes.txt` entry and the test changes from `fromObject()` to `fromObject({})`.

File: packages/aws-cdk-lib/aws-events-targets/lib/log-group.ts [hunk 2]
```diff
@@ -37,7 +37,7 @@ export interface LogGroupTargetInputOptions {
 /**
  * The input to send to the CloudWatch LogGroup target
  */
-export abstract class LogGroupTargetInput {
+export abstract class LogGroupTargetInput extends RuleTargetInput {
```
Comment (vishaalmehrishi) [inline packages/aws-cdk-lib/aws-events-targets/lib/log-group.ts:41]: Now that `LogGroupTargetInput extends RuleTargetInput`, users in JSII languages can call inherited static methods like `LogGroupTargetInput.fromText("...")` or `LogGroupTargetInput.fromEventPath("$.detail")`. These return `RuleTargetInput`, not `LogGroupTargetInput`, which could be confusing since `LogGroupTargetInput` is meant to constrain the input format to `{timestamp, message}`.

This is acceptable as a pragmatic fix for a P1 bug, but worth noting in the PR description or a code comment. Per the [CDK Design Guidelines](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md): "Prefer representing polymorphic behavior through interfaces and not through inheritance."

**Review by vishaalmehrishi — CHANGES_REQUESTED** [review]

File: packages/aws-cdk-lib/aws-events-targets/lib/log-group.ts (hunk 2 above)
Comment (Abogical) [reply packages/aws-cdk-lib/aws-events-targets/lib/log-group.ts:41]: I've noted this trade-off in the PR description. This isn't ideal as we are working around the issue of `RuleTargetConfig.input` expects a RuleTargetInput instance, not an interface type like `IRuleTargetInput`. Changing this type to an interface could resolve this but it would have a big blast radius and could have unknown side effects, so I've opted not to do this.

File: packages/aws-cdk-lib/aws-events-targets/lib/log-group.ts (hunk 1 above)
Comment (Abogical) [reply packages/aws-cdk-lib/aws-events-targets/lib/log-group.ts:50]: I can't do this. I tried making it optional this way to avoid the breaking change but this breaks the JSII build, see: https://github.com/aws/aws-cdk/actions/runs/24344584329/job/71081890367?pr=37451

Comment (Abogical) [reply packages/aws-cdk-lib/aws-events-targets/lib/log-group.ts:50]: Extending RuleTargetInput mandates a required argument in `fromObject`. JSII will not accept it being optional as a result.

**Review by vishaalmehrishi — APPROVED** [review]
