### PR TITLE
fix(core): cannot use container assets with new-style synthesis

### LINKED ISSUE #8540: ContainerImage.fromAsset in new asset system after 1.45
When using ContainerImage.fromAsset the generated CFN template looks like this:

```
            "Image": {
              "Fn::Sub": {
                "Fn::Join": [
                  "",
                  [
                    "<id>.dkr.ecr.eu-central-1.",
                    {
                      "Ref": "AWS::URLSuffix"
                    },
                    "/cdk-<my-asset-ecr>:<hash>"
                  ]
                ]
              }
            },
```
This is invalid CloudFormation as Join is not valid inside Sub:

E1019 Sub should be a string or array of 2 items for Resources/TaskDef3BF4F22B/Properties/ContainerDefinitions/0/Image/Fn::Sub

The problem might be here https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts#L281 as it creates an `Fn::Sub` containing an `Fn::Join` which is not valid.

@rix0rrr see https://github.com/aws/aws-cdk/issues/3463#issuecomment-643502229

### Reproduction Steps

Use any `ContainerImage.fromAsset`

### Environment

  - **CLI Version      :** 1.45.0
  - **Framework Version:** 1.45.0
  - **Node.js Version:** v14
  - **OS               :** MacOS
  - **Language (Version):** TypeScript

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
When referencing loations that contained unresolved Tokens (
account, region, URL suffix) the synthesizer generated:

    {Fn::Sub: { Fn::Join: ... }}

That is not allowed, the first argument to `{Fn::Sub}` must be a string
literal.

This was a problem for all asset types, but the most-used file asset
(`lambda.Code`) would only render `{ bucketName, objectKey }` which
typically don't contain tokens, so you'd only notice when using
Docker image assets.

Fixes #8540.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts [hunk 1]
```diff
@@ -275,10 +276,12 @@ export class DefaultStackSynthesizer implements IStackSynthesizer {
       },
     };
 
+    const { account, region, urlSuffix } = stackLocationOrInstrinsics(this.stack);
+
     // Return CFN expression
     return {
       repositoryName: cfnify(this.repositoryName),
-      imageUri: cfnify(`${this.stack.account}.dkr.ecr.${this.stack.region}.${this.stack.urlSuffix}/${this.repositoryName}:${imageTag}`),
+      imageUri: cfnify(`${account}.dkr.ecr.${region}.${urlSuffix}/${this.repositoryName}:${imageTag}`),
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts:284]: should we add a check that `imageTag` and `this.repositoryName` are not tokens?

**Comment by rix0rrr** [comment]
The changes to `evaluate-cfn.ts` are the test.

File: packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts:284]: They are *very unlikely* to be tokens and the right behavior would be rejecting (which CFN will do on our behalf by failing).

So, *I guess* we can add that check, but I don't think it's very valuable to have it...
