### PR TITLE
fix(pipelines): stack tags

### LINKED ISSUE #9260: [cdk-pipelines] stacks cannot be tagged
It does not appear that pipeline applies aspects properly.  Ideally, it should apply the aspects to itself and stages.  stage appears to apply aspects that are added directly, but do not apply tagging aspects.

### Reproduction Steps
See #9256 and #9259 for the initial steps.  In that both of these cases showed higher level issues.  

First I attempted to solve the PermissionsBoundary issue.  I used the App.node.applyAspects(...) and received success for the initial pipeline stack.  I.e., all roles created in the pipeline stack had the PermissionsBoundary from the aspect applied.  

Problem solved, right?  Well, then I continued with the [tutorial][1] and when I added a 'stage' the issue re-appeared.  In that the stack associated with the Stage did not have the PermissionsBoundary aspect applied.  So I did the next level pipeline.node.applyAspects(...) and still no result.  So I did the next level stage.node.applyAspects(...) and successfully the PermissionsBoundary aspect was applied to all IAM Roles in the Stage/Stack.  

At this point I noticed that the Tags had been lost.  I traced that back to the first update after the create of the Pipeline STack.  So I started the same adventure, only this time I figured that the PermissionsBoundary aspect was a clue and so I did not apply at each level, but started at the two points that I had found to work.  I.e., Tags.add(stage, "key", "value") and sure enough it did not work.  So I had to go down the next level to the 'stack' itself that the stage was composed of.  And success as the tags were resources.  However, the tags are missing on the stack itself.  

Ideally, if tags are specified at the App they should be applied at each component.  And because Tagging is an aspect this leads to the next issue of consistency. 

Ideally, if an aspect is specified at the App it should be applied to all components, including the pipeline/stage/stacks/resources.

[1]:  https://aws.amazon.com/blogs/developer/cdk-pipelines-continuous-delivery-for-aws-cdk-applications/

### Error Log
Observed missing aspects.

### Environment

  - **CLI Version      :** 1.54.0 (build c01b9b9)
  - **Framework Version:**
  - **Node.js Version:** v12.18.3
  - **OS               :** osx 10.15.6
  - **Language (Version):** all

### Other

I have a private git repo with the tutorial on it and each commit I made to discover the issues described above.  I can provide that if it would be of interest or help.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
Apply stack tags to the stacks deployed using CDK Pipelines.

Taking this opportunity to make tags easier to work with -- move them from metadata into cloud artifact properties.

Fixes #9260.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by rix0rrr** [comment]
(Not ready to be merged yet, needs more tests)

File: packages/@aws-cdk/cx-api/test/util.ts [hunk 1]
```diff
@@ -0,0 +1,23 @@
+import * as fs from 'fs';
+import * as path from 'path';
+
+/**
+ * rm -rf reimplementation, don't want to depend on an NPM package for this
```
Comment (eladb) [inline packages/@aws-cdk/cx-api/test/util.ts:5]: What's wrong with using an npm package for tests?

File: packages/@aws-cdk/pipelines/lib/actions/deploy-cdk-stack-action.ts [hunk 2]
```diff
@@ -156,12 +162,25 @@ export class DeployCdkStackAction implements codepipeline.IAction {
...
     const appAsmRoot = assemblyBuilderOf(appOf(scope)).outdir;
     const fullTemplatePath = path.join(artifact.assembly.directory, artifact.templateFile);
-    const templatePath = path.relative(appAsmRoot, fullTemplatePath);
+
+    let fullConfigPath;
+    if (Object.keys(artifact.tags).length > 0) {
+      fullConfigPath = `${fullTemplatePath}.config.json`;
+
+      // Write the template configuration file (for parameters into CreateChangeSet call that
+      // cannot be configured any other way). They must come from a file, and there's unfortunately
```
Comment (eladb) [inline packages/@aws-cdk/pipelines/lib/actions/deploy-cdk-stack-action.ts:171]: What's wrong with this way?

**Review by eladb — APPROVED** [review]

File: packages/@aws-cdk/pipelines/lib/actions/deploy-cdk-stack-action.ts (hunk 2 above)
Comment (rix0rrr) [reply packages/@aws-cdk/pipelines/lib/actions/deploy-cdk-stack-action.ts:171]: Feels like this would be an excellent case for a construct adding an artifact to the synthesized output of a cloud assembly, as an implementation detail of the construct.

What's happening now is that we're writing a file which is right next to another file that we *assume* is going to be in a cloud assembly, of which we kinda guess the name is probably going to be unused, which is invisible any of the rest of the framework.

File: packages/@aws-cdk/cx-api/test/util.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/@aws-cdk/cx-api/test/util.ts:5]: Let's see. I can either have this 10-line function or

```
└─┬ rimraf@3.0.2
  └─┬ glob@7.1.6
    ├── fs.realpath@1.0.0
    ├─┬ inflight@1.0.6
    │ ├── once@1.4.0 deduped
    │ └── wrappy@1.0.2
    ├── inherits@2.0.4
    ├─┬ minimatch@3.0.4
    │ └─┬ brace-expansion@1.1.11
    │   ├── balanced-match@1.0.0
    │   └── concat-map@0.0.1
    ├─┬ once@1.4.0
    │ └── wrappy@1.0.2 deduped
    └── path-is-absolute@1.0.1
```
