### PR TITLE
fix(core): dependencies across stack boundaries of all kinds

### LINKED ISSUE #4406: DependsOn does not take Nested Stacks into account
When using Nested stacks, with the Vpc and the ApplicationLoadBalancer defined in different Nested Stacks, the ApplicationLoadBalancer construct appends a DependsOn entry to Routes that are created in the Nested Stack of the Vpc. **As the dependency is not present in the same template file, the stack creation fails in CloudFormation.**

When using multiple Stacks (top-level - not nested), the same DependsOn entry is not there.

### Reproduction Steps

``` py
from aws_cdk import (
    aws_cloudformation as cfn,
    aws_ec2 as ec2,
    aws_elasticloadbalancingv2 as elbv2,
    core,
)

class SkeletonStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        self.vpc = ec2.Vpc(
            self, 'Vpc',
            cidr='10.0.0.0/16',
            max_azs=99, # use all available AZs,
            subnet_configuration=[ 
                { 'cidrMask': 27, 'name': 'public-lb', 'subnetType': ec2.SubnetType.PUBLIC }
            ]
        )

class LoadBalancerStack(cfn.NestedStack):

    def __init__(
        self,
        scope: core.Construct,
        id: str,
        vpc: ec2.IVpc,
        **kwargs
    ) -> None:
        super().__init__(scope, id, **kwargs)

        self.alb = elbv2.ApplicationLoadBalancer(
            self, 'ApplicationLoadBalancer',
            vpc=vpc,
            internet_facing=True,
            vpc_subnets={'subnetName': 'public-lb'}
        )

app = core.App()
skeleton = SkeletonStack(app, 'skeleton', env=_REPLACE_ME_)
load_balancer = LoadBalancerStack(skeleton, 'load-balancer', vpc=skeleton.vpc)
app.synth()

```

### Error Log

```
Template format error: Unresolved resource dependencies
```

### Environment

  - **CLI Version      : 1.12**
  - **Framework Version: 1.12**
  - **OS               :**
  - **Language         : python**

### Other

--- 

This is :bug: Bug Report

### LINKED ISSUE #4474: Cross stack vpc causes unresolved resource dependencies error
Hi,
creating a vpc in a child stack (not nested), and creating some resources, that depend on the vpc, in another child stack will result in a ValidationError.
I was able to reproduce this with application loadbalancers (only internet facing) aswell as an aurora cluster (public and private).

### Reproduction Steps

``` ts
import cdk = require('@aws-cdk/core');
import { NetworkStack } from './Network-stack';
import { InstancesStack } from './Instances-stack';

export class TestStack extends cdk.Stack {
    constructor(scope: cdk.App, id: string, props: cdk.StackProps) {
        super(scope, id, props);
        const network = new NetworkStack(this, "NetworkStack", props);

        new InstancesStack(this, "Instances", {
            env: props.env,
            network: network
        });
    }
}
```
``` ts
import cdk = require('@aws-cdk/core');
import ec2 = require('@aws-cdk/aws-ec2');

export class NetworkStack extends cdk.Stack {
    public readonly vpc: ec2.Vpc;

    constructor(scope: cdk.Stack, id: string, props: cdk.StackProps) {
        super(scope, id, props);

        this.vpc = new ec2.Vpc(this, "vpc", {
            cidr: "10.0.0.0/16",
            maxAzs: 3,
            subnetConfiguration: [
                {
                    cidrMask: 20,
                    subnetType: ec2.SubnetType.PRIVATE,
                    name: "subnet-private"
                },
                {
                    cidrMask: 20,
                    subnetType: ec2.SubnetType.PUBLIC,
                    name: "subnet-public"
                }
            ],
            natGateways: 2
        });
    }
}
```
``` ts
import cdk = require('@aws-cdk/core'); 
import loadbalancer = require('@aws-cdk/aws-elasticloadbalancingv2');
import { NetworkStack } from './Network-stack';
 
export interface theseProps extends cdk.StackProps { 
    network: NetworkStack
} 
 
export class InstancesStack extends cdk.Stack {
 
    constructor(scope: cdk.Stack, id: string, props: theseProps) { 
        super(scope, id, props);
        
        new loadbalancer.ApplicationLoadBalancer(this, "testLB", {
            vpc: props.network.vpc,
            internetFacing: true
        });
    } 
}
```

### Error Log

``` bash
cdk deploy *
TestStack
TestStack: deploying...
TestStack: creating CloudFormation changeset...

 ✅  TestStack (no changes)

Stack ARN:
arn:aws:cloudformation:eu-west-1:123456789:stack/TestStack/f7358b50-ec24-11e9-8e0e-02c03455965c
TestStackNetworkStackE68E9FD0
TestStackNetworkStackE68E9FD0: deploying...
TestStackNetworkStackE68E9FD0: creating CloudFormation changeset...
...

 ✅  TestStackNetworkStackE68E9FD0

Outputs:
TestStackNetworkStackE68E9FD0.ExportsOutputRefvpcsubnetpublicSubnet1SubnetF125D982384FC8F2 = subnet-05bb64c9b53308b7c
TestStackNetworkStackE68E9FD0.ExportsOutputRefvpcA2121C384D1B3CDE = vpc-02997d94566f805bf
TestStackNetworkStackE68E9FD0.ExportsOutputRefvpcsubnetpublicSubnet2Subnet2731CC5E2E3D2FF3 = subnet-0b862d79b52959ec6
TestStackNetworkStackE68E9FD0.ExportsOutputRefvpcsubnetpublicSubnet3Subnet7494E9BC8FCFC236 = subnet-03944fc3ed16a79b4

Stack ARN:
arn:aws:cloudformation:eu-west-1:123456789:stack/TestStackNetworkStackE68E9FD0/2d351770-ec25-11e9-9415-06982f8c16e4
TestStackInstancesF0B37D31
TestStackInstancesF0B37D31: deploying...
TestStackInstancesF0B37D31: creating CloudFormation changeset...

 ❌  TestStackInstancesF0B37D31 failed: ValidationError: Template format error: Unresolved resource dependencies [vpcsubnetpublicSubnet3DefaultRoute3905C18B, vpcsubnetpublicSubnet2DefaultRoute7436D83A, vpcsubnetpublicSubnet1Defau
ltRouteA1448C8B] in the Resources block of the template
Template format error: Unresolved resource dependencies [vpcsubnetpublicSubnet3DefaultRoute3905C18B, vpcsubnetpublicSubnet2DefaultRoute7436D83A, vpcsubnetpublicSubnet1DefaultRouteA1448C8B] in the Resources block of the template  
```

### Environment

  - **CLI Version      : 1.16.232**
  - **Framework Version: 1.12.0**
  - **OS               : Windows 10**
  - **Language         : TypeScript**

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by eladb**
`stack.addDependency` can now be called between any two stacks in the app and the dependency will be applied at the right scope, either between top-level stacks at the assembly (app) level or between `AWS::CloudFormation::Stack` resources that represent nested stacks in a common stack. 

Similarly, `cfnResource.addDependsOn` can now be called for any two `CfnResource`s in the app, and thew dependency will be applied at the right scope (either between the two resources directly, between nested stack resources or at the assembly/app level).

This is implemented generically for both resources and stacks in `deps.ts/addDependency` through the following algorithm:

- Lookup the lowest common stack
- If not found, apply the dependency at the assembly level (between two top-level stacks).
- If found, identify the two CloudFormation resources which represent this relationship within the scope of the common stack (this could be the actual resource if they are both in the same stack or the `AWS::CloudFormation::Stack` resource if the source or target are with in a nested stack).
- Apply the dependency at the CloudFormation level (add `DependsOn`).

To be able to find the `AWS::CloudFormation::Stack` resource for nested stacks, the `nestedStackResource` property was added to `core.Stack` and assigned by  `NestedStack`

Created a thorough test suite to examine various cases under `@aws-cdk/aws cloudformation/test.deps.ts`. Note that this suite includes tests for nested stacks and for regular cases, but decided to put them all in a single suite to make it easier to reason about coverage.

This change also introduces a cache for `Stack.of(x)` by attaching the result to `x` via a hidden property. This method is widely used and the cache hit rate is quite large (at the time of this writing, @aws-cdk/core unit tests hit this cache 1,112 times, @aws-cdk/aws-cloudformation unit tests hit this 2,435 times).

Fixes #4406 
Fixes #4474

### CODE REVIEW

File: packages/@aws-cdk/core/lib/stack.ts [hunk 1]
```diff
@@ -318,28 +326,64 @@ export class Stack extends Construct implements ITaggable {
...
+    }
+
+    // at this point, we know that both source and target are nested stacks
+    if (!source.nestedStackResource || !target.nestedStackResource) {
+      throw new Error(`Unexpected: both '${source.node.path}' and '${target.node.path}' are expected to be nested stacks`);
     }
+
+    // both source and target are nested, so we are going to transfer the dependency to the
+    // respective AWS::CloudFormation::Stack resources that share the same common stack.
+    const sourceResource = findCommonCfnResource(source.nestedStackResource, common);
```
Comment (rix0rrr) [inline packages/@aws-cdk/core/lib/stack.ts]: `nestedStackResource` is only used for the purposes of `findCommonCfnResource()`. So seems like if we make that a virtual method on `Stack`, we don't need the tight coupling between `core` and `aws-cloudformation` and we can leave `NestedStack` where it is?

```ts
Stack.of(source).findRepresentingResource(source, common);

class Stack {
  public findRepresentingResource(resource: CfnResource, inside: Stack) {
    if (inside !== this) {
      throw new Error('Ruh-roh!');
    }
    return resource;
  }
}

class NestedStack {
  public findRepresentingResource(resource: CfnResource, inside: Stack) {
    if (inside === this) {
      return resource;
    }
    return Stack.of(this).findRepresentingResource(this.nestedStackResource, inside);
  }
}
```

**Comment by rix0rrr** [comment]
For the record, I'm almost positive we should be able to cut down on the amount of `if`s even more if we put our mind to it. Feels like an elegant recursive solution is juuuust out of reach.

File: packages/@aws-cdk/core/lib/cfn-resource.ts [hunk 2]
```diff
@@ -226,8 +227,33 @@ export class CfnResource extends CfnRefElement {
...
+
+    // ignore
+    if (source === target) { return; }
+
+    const sourceStack = Stack.of(source);
+    const targetStack = Stack.of(target);
+
+    // find the "deepest" (lowest) stack that is a parent of both the source and
+    // the target stacks.
+    const lca = findCommonStack(sourceStack, targetStack);
```
[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/core/lib/cfn-resource.ts]: Done

File: packages/@aws-cdk/core/lib/stack.ts [hunk 3]
```diff
@@ -156,6 +156,14 @@ export class Stack extends Construct implements ITaggable {
    */
   public readonly parentStack?: Stack;
 
+  /**
+   * The AWS::CloudFormation::Resource that represents this nested stack (if
```
[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/core/lib/stack.ts]: Done

File: packages/@aws-cdk/core/lib/stack.ts [hunk 4]
```diff
@@ -318,28 +326,64 @@ export class Stack extends Construct implements ITaggable {
...
-    if (dep !== undefined) {
-        // tslint:disable-next-line:max-line-length
-        throw new Error(`'${stack.node.path}' depends on '${this.node.path}' (${dep.join(', ')}). Adding this dependency (${reason}) would create a cyclic reference.`);
+    if (source === target) { return; }
+
+    const common = findCommonStack(source, target);
+
+    // if there is no common stack (i.e. we got to the root), then define an assembly-
+    // level dependency between the two top-level stacks
+    if (!common) {
```
[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/core/lib/stack.ts]: Done

File: packages/@aws-cdk/core/lib/stack.ts (hunk 1 above)
Comment (eladb) [reply packages/@aws-cdk/core/lib/stack.ts]: Done

File: packages/@aws-cdk/core/lib/util.ts [hunk 5]
```diff
@@ -92,3 +93,77 @@ export class PostResolveToken extends Intrinsic implements IPostProcessor {
...
+
+  // return the last before diff
+  return path1[i - 1];
+}
+
+/**
+ * @returns the list of stacks that lead from the top-level stack (non-nested) all the way to a nested stack.
+ */
+export function pathToTopLevelStack(s: Stack): Stack[] {
+  if (s.parentStack) {
```
[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/core/lib/util.ts]: Discussed verbally.

File: packages/@aws-cdk/core/lib/stack.ts [hunk 6]
```diff
@@ -65,7 +67,23 @@ export class Stack extends Construct implements ITaggable {
...
+    // the object. anecdotally, at the time of this writing, @aws-cdk/core unit
+    // tests hit this cache 1,112 times, @aws-cdk/aws-cloudformation unit tests
+    // hit this 2,435 times).
+    const cache = (construct as any)[MY_STACK_CACHE] as Stack | undefined;
+    if (cache) {
+      return cache;
+    } else {
+      const value = _lookup(construct);
+      Object.defineProperty(construct, MY_STACK_CACHE, {
+        enumerable: false,
```
Comment (rix0rrr) [inline packages/@aws-cdk/core/lib/stack.ts]: Aren't these `false`s all the defaults?

File: packages/@aws-cdk/core/lib/stack.ts [hunk 7]
```diff
@@ -65,7 +67,23 @@ export class Stack extends Construct implements ITaggable {
    * @param construct The construct to start the search from.
    */
   public static of(construct: IConstruct): Stack {
-    return _lookup(construct);
+    // we want this to be as cheap as possible. cache this result by mutating
+    // the object. anecdotally, at the time of this writing, @aws-cdk/core unit
+    // tests hit this cache 1,112 times, @aws-cdk/aws-cloudformation unit tests
```
Comment (rix0rrr) [inline packages/@aws-cdk/core/lib/stack.ts]: But how much time does it save?

File: packages/@aws-cdk/core/lib/stack.ts [hunk 8]
```diff
@@ -151,10 +169,19 @@ export class Stack extends Construct implements ITaggable {
 
   /**
    * Returns the parent stack if this stack is nested.
+   * This is `undefined` for top-level (non-nested) stacks.
    *
    * @experimental
    */
-  public readonly parentStack?: Stack;
+  public readonly nestedStackParent?: Stack;
```
Comment (rix0rrr) [inline packages/@aws-cdk/core/lib/stack.ts]: `protected` for both?

Also, doesn't it make more sense to have a single property `nestedStackInfo?: NestedStackInfo` ?

File: packages/@aws-cdk/core/lib/stack.ts [hunk 9]
```diff
@@ -573,6 +590,15 @@ export class Stack extends Construct implements ITaggable {
     };
   }
 
+  /**
+   * Returns the parent of a nested stack.
+   *
+   * @deprecated use `nestedStackParent`
+   */
+  public get parentStack() {
```
Comment (rix0rrr) [inline packages/@aws-cdk/core/lib/stack.ts]: I would be okay skipping this backwards compat thingy. It was `@experimental` for a reason...

File: packages/@aws-cdk/core/lib/stack.ts (hunk 7 above)
Comment (eladb) [reply packages/@aws-cdk/core/lib/stack.ts]: Not sure, but since `Stack.of` is a public API and heavily used both by the framework and by users, I think it's worth the opportunistic optimization.

File: packages/@aws-cdk/core/lib/stack.ts (hunk 6 above)
Comment (eladb) [reply packages/@aws-cdk/core/lib/stack.ts]: Yes, but I wanted to be explicit

File: packages/@aws-cdk/core/lib/stack.ts (hunk 8 above)
Comment (eladb) [reply packages/@aws-cdk/core/lib/stack.ts]: I've changed this slightly so `NestedStack` only needs to set `nestedStackResource` and the stack is deduced from it (`Stack.of`). It can't be protected since it is used by thing like the assertion library and the `addDependency` code.

As mentioned, I think this will undergo some more changes when we move `NestedStack` into `@aws-cdk/core`.

File: packages/@aws-cdk/core/lib/stack.ts (hunk 9 above)
Comment (eladb) [reply packages/@aws-cdk/core/lib/stack.ts]: I'll leave it for now to avoid churn, since I think this API will change again soon.
