### PR TITLE
fix(aws-cloudformation): change use of Role to IRole in CodePipeline Actions

### LINKED ISSUE #1361: CloudFormation CodePipeline Actions should accept `IRole` instead of `Role`
Accepting `Role` means we can't use it with `import`ed Roles.

Reported by @rhboyd on our Gitter channel.

### PR DESCRIPTION
**Pull request by skinny85**
BREAKING CHANGE: this changes the type of the `role` property in CFN CodePipeline Actions
from `Role` to `IRole`.

This is needed to use imported Roles when creating Actions.

Fixes #1361

----

### Pull Request Checklist

Please check all boxes, including N/A items:

#### Testing

- [x] Unit test and/or integration test added
- [x] __Toolkit change?:__ [integration tests](https://github.com/awslabs/aws-cdk/blob/master/packages/aws-cdk/integ-tests/test.sh) manually executed (paste output to the PR description)
- [x] __Init template change?:__ coordinated update of integration tests (currently maintained in a private repo).

#### Documentation

- [x] __README__: README and/or documentation topic updated
- [x] __jsdocs__: All public APIs documented

### Title and description

- [x] __Change type__: Title is prefixed with change type:
  * `fix(module): <title>` bug fix (_patch_)
  * `feat(module): <title>` feature/capability (_minor_)
  * `chore(module): <title> ` won't appear in changelog
  * `build(module): <title>` won't appear in changelog
- [x] __Title format__: Title uses lower case and doesn't end with a period
- [x] __Breaking change?__: Last paragraph of description is: `BREAKING CHANGE: <describe exactly what changed and how to achieve similar behavior + link to documentation/gist/issue if more details are required>`
- [x] __References__: Indicate issues fixed via: `Fixes #xxx` or `Closes #xxx`

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by RomainMuller** [comment]
I've added the necessary (hopefully sufficient) fix to `@aws-cdk/app-delivery`.

**Comment by skinny85** [comment]
Thanks for taking this one over @RomainMuller!

**Comment by skinny85** [comment]
I think it's still a breaking change, as `Role` is a supertype of `IRole`. A change the other way would be backwards compatible.

File: packages/@aws-cdk/app-delivery/lib/pipeline-deploy-stack-action.ts [hunk 1]
```diff
@@ -51,7 +51,7 @@ export interface PipelineDeployStackActionProps {
    *
    * @default A fresh role with admin or no permissions (depending on the value of `adminPermissions`).
    */
-  role?: iam.Role;
+  role?: iam.IRole;
```
Comment (eladb) [inline packages/@aws-cdk/app-delivery/lib/pipeline-deploy-stack-action.ts]: The change in props is not a breaking change (code that passed `Role` here would still work)

File: packages/@aws-cdk/app-delivery/lib/pipeline-deploy-stack-action.ts [hunk 2]
```diff
@@ -97,7 +97,7 @@ export class PipelineDeployStackAction extends cdk.Construct {
   /**
    * The role used by CloudFormation for the deploy action
    */
-  public readonly role: iam.Role;
+  public readonly role: iam.IRole;
```
Comment (eladb) [inline packages/@aws-cdk/app-delivery/lib/pipeline-deploy-stack-action.ts]: This *is* a breaking change (code that expects to find `Role` here now finds something more abstract).

File: packages/@aws-cdk/app-delivery/test/test.pipeline-deploy-stack-action.ts [hunk 3]
```diff
@@ -188,7 +188,7 @@ export = nodeunit.testCase({
       adminPermissions: false,
       role
     });
-    test.deepEqual(role.id, deployAction.role.id);
+    test.deepEqual(role.id, (deployAction.role as iam.Role).id);
```
Comment (eladb) [inline packages/@aws-cdk/app-delivery/test/test.pipeline-deploy-stack-action.ts]: This looks fishy. Maybe we should just check equality between the objects?

Comment (skinny85) [reply packages/@aws-cdk/app-delivery/test/test.pipeline-deploy-stack-action.ts]: Done.

**Comment by skinny85** [comment]
Changed the test according to @eladb's suggestion.
