### PR TITLE
fix(rds): cannot use s3ImportBuckets or s3ExportBuckets with aurora postgres

### LINKED ISSUE #4419: aws-rds doesn't support AssociatedRoles attribute
### The Question
Using RDS AssociatedRoles is required in order to setup RDS S3 integration for Oracle and likely other database types. For example, to be able to restore an newly created database from a backup stored in an S3 bucket. 

The AssociatedRoles element is supported through CloudFormation (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-associatedroles). At the same there is no way to use this functionality with DatabaseInstance construct. 

Please consider adding this capability in  CDK API.

### Environment

  - **CDK CLI Version:** 1.12.0 (build 923055e)
  - **Module Version:** aws-cdk.aws-rds (1.10.0)
  - **OS:** Windows 10
  - **Language:** Python

### LINKED ISSUE #8201: Error when adding s3ImportBucket to RDS Aurora Postgresql
When adding an s3ImportBucket to a standard (non-severless) RDS Aurora Postgresql cluster an error occurs. 

When omitting the last line, the cluster works as expected.

```ts
    const importBucket = new s3.Bucket(this, 'importbucket');
    const cluster = new rds.DatabaseCluster(this, "Database", {
      engine: rds.DatabaseClusterEngine.AURORA_POSTGRESQL,
      masterUser: { username: "a-username-here" },
      instanceProps: {
        instanceType: ec2.InstanceType.of(
          ec2.InstanceClass.T3,
          ec2.InstanceSize.MEDIUM
        ),
        vpc: props?.vpc!,
        vpcSubnets: { subnetType: ec2.SubnetType.ISOLATED },
      },
      defaultDatabaseName: "a-db-name-here",

      parameterGroup: rds.ParameterGroup.fromParameterGroupName(
        this,
        "ParameterGroup",
        "default.aurora-postgresql11"
      ),
      instances: 1,
      s3ImportBuckets: [importBucket], // <- this creates an error
    });
```

The error-log shows an error regarding the feature-name: 
`The feature-name parameter must be provided with the current operation for the Aurora (PostgreSQL) engine. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: XXX)
        new DatabaseCluster (/cdkpath/node_modules/@aws-cdk/aws-rds/lib/cluster.ts:438:21)`

### Environment

  - **CLI Version      :1.41
  - **Framework Version:1.41
  - **OS               :OSX
  - **Language         :TypeScript

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by shivlaks**
When the `s3ImportBuckets` or `s3ExportBuckets` properties are set, we also need
to include the name of the feature for the DB instance that the IAM role is to be associated with. 

Excluding the feature name causes a deploy-time failure as follows:
> The feature-name parameter must be provided with the current operation ...

Added an `EngineFeatures` struct to specify the feature name for `s3Import` and `s3Export`

Closes #4419
Closes #8201

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts [hunk 1]
```diff
@@ -49,6 +49,36 @@ export interface ClusterEngineConfig {
...
+   *
+   * @default - no features
+   */
+  readonly features?: EngineFeatures;
+}
+
+/**
+ * Represents Database Engine features
+ */
+export interface EngineFeatures {
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:66]: `ClusterEngineFeatures`? We might have `InstanceEngineFeatures` in the future as well.

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts [hunk 2]
```diff
@@ -49,6 +49,36 @@ export interface ClusterEngineConfig {
...
+  /**
+   * Feature for the DB instance that the IAM role to access the S3 bucket for import
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:68]: I think it's "Name of the feature (...)", not just "Feature (...)".

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts [hunk 3]
```diff
@@ -49,6 +49,36 @@ export interface ClusterEngineConfig {
...
+   * is to be associated with.
+   *
+   * @default - no s3Import feature
+   */
+  readonly s3Import?: string;
+
+  /**
+   * Feature for the DB instance that the IAM role to export to S3 bucket is to be
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:76]: Same comment here ("Feature" -> "Name of feature").

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts [hunk 4]
```diff
@@ -49,6 +49,36 @@ export interface ClusterEngineConfig {
...
+
+/**
+ * Represents Database Engine features
+ */
+export interface EngineFeatures {
+  /**
+   * Feature for the DB instance that the IAM role to access the S3 bucket for import
+   * is to be associated with.
+   *
+   * @default - no s3Import feature
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:71]:
```suggestion
   * @default - no s3Import feature name
```

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts [hunk 5]
```diff
@@ -49,6 +49,36 @@ export interface ClusterEngineConfig {
...
+   */
+  readonly s3Import?: string;
+
+  /**
+   * Feature for the DB instance that the IAM role to export to S3 bucket is to be
+   * associated with.
+   *
+   * @default - no s3Export feature
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:79]:
```suggestion
   * @default - no s3Export feature name
```

File: packages/@aws-cdk/aws-rds/lib/engine.ts [hunk 6]
```diff
@@ -28,4 +29,11 @@ export interface IEngine {
    *   (which means the major version of the engine is also not known)
    */
   readonly parameterGroupFamily?: string;
+
+  /**
+   * Supported Features by the database engine
+   *
+   * @see https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DBEngineVersion.html
+   */
+  readonly features?: EngineFeatures;
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/engine.ts:38]: Why add this? I don't think this is used anywhere?

File: packages/@aws-cdk/aws-rds/lib/cluster.ts [hunk 7]
```diff
@@ -405,19 +405,20 @@ export class DatabaseCluster extends DatabaseClusterBase {
...
-    }
-
     // bind the engine to the Cluster
     const clusterEngineBindConfig = props.engine.bindToCluster(this, {
       s3ImportRole,
       s3ExportRole,
       parameterGroup: props.parameterGroup,
     });
+
+    if (s3ImportRole) {
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster.ts:415]: Can you move `clusterAssociatedRoles` here as well? In general, variables should be defined as close to where they are used as possible.

File: packages/@aws-cdk/aws-rds/test/test.cluster.ts [hunk 8]
```diff
@@ -681,6 +681,45 @@ export = {
...
+    // THEN
+    expect(stack).to(haveResource('AWS::RDS::DBCluster', {
+      AssociatedRoles: [{
+        RoleArn: {
+          'Fn::GetAtt': [
+            'DatabaseS3ImportRole377BC9C0',
+            'Arn',
+          ],
+        },
+        FeatureName: 's3Import',
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/test/test.cluster.ts:716]: We need a test for export as well.

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts [hunk 9]
```diff
@@ -76,11 +106,13 @@ interface ClusterEngineBaseProps {
   readonly multiUserRotationApplication: secretsmanager.SecretRotationApplication;
   readonly defaultPort?: number;
   readonly engineVersion?: EngineVersion;
+  readonly features?: EngineFeatures;
 }
 
 abstract class ClusterEngineBase implements IClusterEngine {
   public readonly engineType: string;
   public readonly engineVersion?: EngineVersion;
+  public readonly features?: EngineFeatures;
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:115]: Any reason this is `public`? I think it can safely be `private`.

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts [hunk 10]
```diff
@@ -369,17 +403,17 @@ export class AuroraPostgresEngineVersion {
   /** Version "10.6". */
   public static readonly VER_10_6 = AuroraPostgresEngineVersion.of('10.6', '10');
   /** Version "10.7". */
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:405]: No feature names for any above versions?

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts [hunk 11]
```diff
@@ -389,18 +423,22 @@ export class AuroraPostgresEngineVersion {
    * @param auroraPostgresMajorVersion the major version of the engine,
    *   for example "9.6"
    */
-  public static of(auroraPostgresFullVersion: string, auroraPostgresMajorVersion: string): AuroraPostgresEngineVersion {
-    return new AuroraPostgresEngineVersion(auroraPostgresFullVersion, auroraPostgresMajorVersion);
+  public static of(auroraPostgresFullVersion: string, auroraPostgresMajorVersion: string,
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:426]: I have a slightly different idea here.

Since the feature name is always `s3Import` / `s3Export`, how about we do this?

```ts
export interface AuroraPostgresEngineFeatures {
  readonly s3ImportFeature?: boolean;
  readonly s3ExportFeature?: boolean;
}

export class AuroraPostgresEngineVersion {
  public static of(auroraPostgresFullVersion: string, auroraPostgresMajorVersion: string, features?: AuroraPostgresEngineFeatures) {
    // ..
  }
}
```

And then default the feature names `s3Import` / `s3Export` inside the implementation of `AuroraPostgresEngineVersion` - much less duplication.

If, in the future, there is a new feature name for S3 Import / S3 Export, we can always add more properties to `AuroraPostgresEngineFeatures`.

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts [hunk 12]
```diff
@@ -389,18 +423,22 @@ export class AuroraPostgresEngineVersion {
...
+    auroraPostgresFeatures?: EngineFeatures): AuroraPostgresEngineVersion {
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:427]: Can you leave an empty line when the signature and body are indented on the same level? Makes it more readable.

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts [hunk 13]
```diff
@@ -389,18 +423,22 @@ export class AuroraPostgresEngineVersion {
...
+    return new AuroraPostgresEngineVersion(auroraPostgresFullVersion, auroraPostgresMajorVersion, auroraPostgresFeatures);
   }
 
   /** The full version string, for example, "9.6.25.1". */
   public readonly auroraPostgresFullVersion: string;
   /** The major version of the engine, for example, "9.6". */
   public readonly auroraPostgresMajorVersion: string;
+  /** The supported features for the DB engine */
+  public readonly auroraPostgresFeatures?: EngineFeatures;
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:436]: I would probably call it `_features`, and make it `@internal` (I don't see a good reason to increase the surface area here).

**Review by skinny85 — CHANGES_REQUESTED** [review]
Looks really good! Some comments / ideas.

**Comment by skinny85** [comment]
Also, can you verify whether the feature names are needed for the Postgres Aurora engine without a version?

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts (hunk 1 above)
Comment (shivlaks) [reply packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:66]: i like it.makes sense with our current usage

One reason I was keeping it general was because the supported features list was essentially retrieved from running `aws rds describe-db-engine-versions` and the documentation wasn't especially specific on where they're used.

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts (hunk 2 above)
Comment (shivlaks) [reply packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:68]: good call

File: packages/@aws-cdk/aws-rds/lib/engine.ts (hunk 6 above)
Comment (shivlaks) [reply packages/@aws-cdk/aws-rds/lib/engine.ts:38]: oops, had removed it but didn't push yet - yeah it's not needed :)
good catch.

File: packages/@aws-cdk/aws-rds/test/test.cluster.ts (hunk 8 above)
Comment (shivlaks) [reply packages/@aws-cdk/aws-rds/test/test.cluster.ts:716]: absolutely, added!

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts (hunk 9 above)
Comment (shivlaks) [reply packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:115]: I think private is fine for now. I was originally thinking it might be useful for other features but we can always walk through that door if it makes sense to.

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts (hunk 11 above)
Comment (shivlaks) [reply packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:426]: yeah I was actually doing exactly this after I'd put it into draft :) - glad to have some validation that it's the way to DRY this up

**Comment by skinny85** [comment]
@shivlaks can you resolve the conflicts with the current `master`? Thanks!

File: packages/@aws-cdk/aws-rds/test/test.cluster.ts [hunk 14]
```diff
@@ -1125,7 +1259,7 @@ export = {
     // WHEN
     new DatabaseCluster(stack, 'Database', {
       engine: DatabaseClusterEngine.auroraPostgres({
-        version: AuroraPostgresEngineVersion.VER_11_4,
+        version: AuroraPostgresEngineVersion.VER_11_6,
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/test/test.cluster.ts:1262]: Why this change here...?

**EDIT**: ah, is it because `11.4` in fact doesn't support one of the features used in the test...? 🙂

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts [hunk 15]
```diff
@@ -428,9 +493,23 @@ class AuroraPostgresClusterEngine extends ClusterEngineBase {
...
 
+  public bindToCluster(scope: core.Construct, options: ClusterEngineBindOptions): ClusterEngineConfig {
+    const config = super.bindToCluster(scope, options);
+    if (options.s3ImportRole && !(config.features?.s3Import)) {
+      throw new Error (`s3Import is not supported for engine: ${this.engineVersion?.fullVersion}. Use an engine version that supports the s3Import feature.`);
+    }
+    if (options.s3ExportRole && !(config.features?.s3Export)) {
+      throw new Error (`s3Export is not supported for engine: ${this.engineVersion?.fullVersion}. Use an engine version that supports the s3Export feature.`);
+    }
+    return {
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:508]: I'm pretty sure you can just `return config;` here 🙂

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts [hunk 16]
```diff
@@ -428,9 +493,23 @@ class AuroraPostgresClusterEngine extends ClusterEngineBase {
...
         }
         : undefined,
+      features: version?._features,
     });
   }
 
+  public bindToCluster(scope: core.Construct, options: ClusterEngineBindOptions): ClusterEngineConfig {
+    const config = super.bindToCluster(scope, options);
+    if (options.s3ImportRole && !(config.features?.s3Import)) {
+      throw new Error (`s3Import is not supported for engine: ${this.engineVersion?.fullVersion}. Use an engine version that supports the s3Import feature.`);
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:503]:
```suggestion
      throw new Error(`s3Import is not supported for Postgres version: ${this.engineVersion?.fullVersion}. Use a version that supports the s3Import feature.`);
```

(surprised the linter din't catch this...)

File: packages/@aws-cdk/aws-rds/test/test.cluster.ts [hunk 17]
```diff
@@ -839,6 +839,140 @@ export = {
...
+          vpc,
+        },
+        s3ExportBuckets: [bucket],
+      });
+    }), /s3Import is not supported for engine version 10.4. Use an engine version that supports the s3Import feature./;
+
+    test.done();
+  },
+
+  'cluster with s3 export bucket adds supported feature name to IAM role'(test: Test) {
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/test/test.cluster.ts:937]: Maybe one positive test-case with import and export at the same time? I don't think splitting them adds much.

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts [hunk 18]
```diff
@@ -428,9 +493,23 @@ class AuroraPostgresClusterEngine extends ClusterEngineBase {
...
+    }
+    if (options.s3ExportRole && !(config.features?.s3Export)) {
+      throw new Error (`s3Export is not supported for engine: ${this.engineVersion?.fullVersion}. Use an engine version that supports the s3Export feature.`);
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:506]:
```suggestion
      throw new Error(`s3Export is not supported for Postgres version: ${this.engineVersion?.fullVersion}. Use a version that supports the s3Export feature.`);
```

BTW, this will be a weird message for the unversioned engine... Do you need a default? Like `${this.engineVersion?.fullVersion ?? '<unversioned>'}` or something?

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts [hunk 19]
```diff
@@ -428,9 +493,23 @@ class AuroraPostgresClusterEngine extends ClusterEngineBase {
...
+      features: version?._features,
     });
   }
 
+  public bindToCluster(scope: core.Construct, options: ClusterEngineBindOptions): ClusterEngineConfig {
+    const config = super.bindToCluster(scope, options);
+    if (options.s3ImportRole && !(config.features?.s3Import)) {
+      throw new Error (`s3Import is not supported for engine: ${this.engineVersion?.fullVersion}. Use an engine version that supports the s3Import feature.`);
+    }
+    if (options.s3ExportRole && !(config.features?.s3Export)) {
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:505]: These `if`s here mean that the unversioned Postgres engine doesn't support S3 import/export at all. Is that true? Have you verified it?

**Review by skinny85 — COMMENTED** [review]
Overall looks great!

Couple of minor questions before I give my 'ShipIt' 🙂

File: packages/@aws-cdk/aws-rds/test/test.cluster.ts (hunk 14 above)
Comment (shivlaks) [reply packages/@aws-cdk/aws-rds/test/test.cluster.ts:1262]: yep!

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts (hunk 15 above)
Comment (shivlaks) [reply packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:508]: haha, absolutely

File: packages/@aws-cdk/aws-rds/test/test.cluster.ts (hunk 17 above)
Comment (shivlaks) [reply packages/@aws-cdk/aws-rds/test/test.cluster.ts:937]: fair point, folding them into one test

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts (hunk 18 above)
Comment (shivlaks) [reply packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:506]: I was going to go with major version but perhaps unversioned is better

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts (hunk 19 above)
Comment (shivlaks) [reply packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:505]: you're right that this code precludes supporting these features for the unversioned Postgres version.
The only reason I added these conditions are because it's a latent failure and it felt like adding validation would help users in getting ahead of it.

The reason I left out the unversioned feature support is because we've already marked them deprecated and the feature is not supported today. I didn't think it was a good idea to try and support it and keep that usage going and was hoping to nudge users towards the guidance we're providing in our doc string.

What do you think? is this validation worth it? should we drop it altogether?
This may also affect the default message for the error (should probably drop the `?? <unversioned>`).

Comment (skinny85) [reply packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:505]: My opinion is the following: if the RDS service supports it, we should support it as well.

Note that we might also have to "un-deprecate" these fields at some point before CDK v2.0 hits - see the discussion [here](https://github.com/aws/aws-cdk-rfcs/pull/241#discussion_r480448417), which makes fully supporting them even more relevant.

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts (hunk 18 above)
Comment (shivlaks) [reply packages/@aws-cdk/aws-rds/lib/cluster-engine.ts]: dropped this when adding support for unversioned - we're going to skip validation when the unversioned aurorapostgres is requested

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts (hunk 19 above)
Comment (shivlaks) [reply packages/@aws-cdk/aws-rds/lib/cluster-engine.ts]: gotcha, I didn't realize we weren't fully convinced that we wanted to keep it marked as `@deprecated`
added support for this case and skipped validation if the featurename is supported.

When unversioned is specified, both features are marked as supported. This is true today, but may not be if the version is changed out from underneath. I'm not sure the constant can support it both ways

Comment (skinny85) [reply packages/@aws-cdk/aws-rds/lib/cluster-engine.ts]: I would mark is as supported for both, always (otherwise, this feature has no chance of working with the unversioned engine at all).

Worst comes to worst, it will fail at deploy time, which is fine by me.

Comment (skinny85) [reply packages/@aws-cdk/aws-rds/lib/cluster-engine.ts]: Actually, here's a thought.

Today, you always return the features names in the `features` property of `ClusterEngineConfig`. I wonder whether a better strategy would be to only return them if `s3ImportRole` / `s3ExportRole` was passed in `ClusterEngineBindOptions`...?

Yes, I understand the code in Cluster today uses the feature names only if `s3ImportRole` / `s3ExportRole`  are != `undefined`... but I wonder whether that will e obvious when we implement other feature names, and whether it's actually better to not return them if they were not requested...

Thoughts on this change?

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts [hunk 20]
```diff
@@ -345,6 +379,25 @@ class AuroraMysqlClusterEngine extends MySqlClusterEngineBase {
   }
 }
 
+/**
+ * Features supported by Aurora Postgres database engine
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:383]:
```suggestion
 * Features supported by this version of the Aurora Postgres cluster engine.
```

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts [hunk 21]
```diff
@@ -345,6 +379,25 @@ class AuroraMysqlClusterEngine extends MySqlClusterEngineBase {
...
+ */
+export interface AuroraPostgresEngineFeatures {
+  /**
+   * Whether the IAM role can access the S3 bucket for importing data
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:387]:
```suggestion
   * Whether this version of the Aurora Postgres cluster engine supports the S3 data import feature.
```

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts [hunk 22]
```diff
@@ -345,6 +379,25 @@ class AuroraMysqlClusterEngine extends MySqlClusterEngineBase {
...
+   *
+   * @default false
+   */
+  readonly s3Import?: boolean;
+
+  /**
+   * Whether the IAM role can access the S3 bucket for exporting data
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:394]:
```suggestion
   * Whether this version of the Aurora Postgres cluster engine supports the S3 data export feature.
```

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts [hunk 23]
```diff
@@ -389,18 +442,30 @@ export class AuroraPostgresEngineVersion {
...
   /** The full version string, for example, "9.6.25.1". */
   public readonly auroraPostgresFullVersion: string;
   /** The major version of the engine, for example, "9.6". */
   public readonly auroraPostgresMajorVersion: string;
+  /**
+   * The supported features for the DB engine
+   *
+   * @internal
+   */
+  public readonly _features?: ClusterEngineFeatures;
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:460]: Actually, this is never `undefined`, right? So this should be `  public readonly _features: ClusterEngineFeatures;`, and that simplifies the code in `AuroraPostgresClusterEngine`.

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts [hunk 24]
```diff
@@ -428,9 +493,22 @@ class AuroraPostgresClusterEngine extends ClusterEngineBase {
           majorVersion: version.auroraPostgresMajorVersion,
         }
         : undefined,
+      features: version ? version._features : { s3Import: 's3Import', s3Export: 's3Export' },
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:496]: I don't like the fact the names are repeated here again... how about this?

```ts
  export class AuroraPostgresEngineVersion {
    // ...
    public readonly _features?: AuroraPostgresEngineFeatures;
    // ...
  }
```

And then you can do:

```suggestion
      features: version
       ? {
         s3Import: version._features.s3Import ? this.S3_IMPORT_FEATURE_NAME : undefined,
         s3Export: version._features.s3Export ? this.S3_EXPORT_FEATURE_NAME : undefined,
       }
       : {  s3Import: this.S3_IMPORT_FEATURE_NAME, s3Export: this.S3_EXPORT_FEATURE_NAME },
```

And we add the private static constants `S3_IMPORT_FEATURE_NAME` and `S3_EXPORT_FEATURE_NAME` to this class? Something like that ;p.

File: packages/@aws-cdk/aws-rds/lib/cluster-engine.ts [hunk 25]
```diff
@@ -428,9 +493,22 @@ class AuroraPostgresClusterEngine extends ClusterEngineBase {
...
     });
   }
 
+  public bindToCluster(scope: core.Construct, options: ClusterEngineBindOptions): ClusterEngineConfig {
+    const config = super.bindToCluster(scope, options);
+    // skip validation for unversioned as it might be supported/unsupported. we cannot reliably tell at compile-time
+    if (options.s3ImportRole && this.engineVersion && !(config.features?.s3Import)) {
```
Comment (skinny85) [inline packages/@aws-cdk/aws-rds/lib/cluster-engine.ts:503]: I'd rather not repeat the `this.engineVersion` condition if possible... so:

```suggestion
    if (this.engineVersion?.fullEngineVersion) {
      if (options.s3ImportRole && !(config.features?.s3Import)) {
        throw new Error(`s3Import is not supported for Postgres version: ${this.engineVersion.fullVersion}. Use a version that supports the s3Import feature.`);
      }
      if (options.s3ExportRole && this.engineVersion && !(config.features?.s3Export)) {
        throw new Error(`s3Export is not supported for Postgres version: ${this.engineVersion.fullVersion}. Use a version that supports the s3Export feature.`);
      }
    }

**Review by skinny85 — APPROVED** [review]
Looks great! A few last notes if you want to hear them 🙂
