### PR TITLE
fix(rds): SQL Server instance engine uses incorrect major version

### LINKED ISSUE #9171: [aws-rds] Incorrect output of the Engine version in OptionGroup
If you specify a SQLServer engine when defining an OptionGroup, the MajorEngineVersion is not correct.

### Reproduction Steps

When you define an OptionGroup as shown below, the code output to CloudFormation will look like this

cdk code:
```python
        option_group = rds.OptionGroup(self, "OptionGroup",
                                       configurations=[
                                           rds.OptionConfiguration(
                                               name="SQLSERVER_BACKUP_RESTORE",
                                               settings={
                                                   "IAM_ROLE_ARN": backup_restore_role.role_arn
                                               }
                                           )
                                       ],
                                       engine=rds.DatabaseInstanceEngine.sql_server_web(
                                           version=rds.SqlServerEngineVersion.VER_11)
                                       )
```

output cloudformation:

```
  OptionGroup:
    Type: AWS::RDS::OptionGroup
    Properties:
      EngineName: sqlserver-web
      MajorEngineVersion: "11.0"
      OptionConfigurations:
        - OptionName: SQLSERVER_BACKUP_RESTORE
          OptionSettings:
            - Name: IAM_ROLE_ARN
              Value:
                Fn::GetAtt:
                  - MSSqlServerBuckupRoleF4E03AFB
                  - Arn
```

As shown above, MajorEngineVersion is output as `11.0`, but the correct version is `11.00`.

### Error Log

When running a deployment in its current state, CloudFromation generates an error `Cannot find major version 11.0 for sqlserver-web`.

### Environment

  - **CLI Version      : aws-cli/2.0.12 Python/3.7.4 Darwin/19.5.0 botocore/2.0.0dev16
  - **Framework Version: 1.53.0 (build 6c326cb)
  - **Node.js Version: v12.12.0
  - **OS               : MacOS 10.15.5
  - **Language (Version): Python (3.7.6)

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by skinny85**
Apparently, even though SQL Server ParameterGroup family ends in '.0',
the major version used in OptionGroup and Instance needs to end in '.00'.

Fixes #9171

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-rds/lib/instance-engine.ts [hunk 1]
```diff
@@ -899,7 +899,13 @@ abstract class SqlServerInstanceEngineBase extends InstanceEngineBase {
           majorVersion: props.version.sqlServerMajorVersion,
         }
         : undefined,
-      parameterGroupFamily: props.version ? `${props.engineType}-${props.version.sqlServerMajorVersion}` : undefined,
+      parameterGroupFamily: props.version
+        // for some reason, even though SQL Server major versions usually end in '.00',
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-rds/lib/instance-engine.ts:903]: when it says *usually* how often is it something other than `.00`?
does this always need to be truncated to the first digit or does it have to end with `.0`?

Comment (skinny85) [reply packages/@aws-cdk/aws-rds/lib/instance-engine.ts:903]: Currently, all major versions defined by constants end with `.00`. However, we also have the `of` methods that allow creating an arbitrary version (including a major version). I figured if there was a major version like `15.0`, we probably shouldn't change the parameter group family to be `sql-server-15.`.

Does this heuristic make sense?

Comment (shivlaks) [reply packages/@aws-cdk/aws-rds/lib/instance-engine.ts:903]: seems reasonable to me! thanks for clarifying
