### PR TITLE
fix(cli): cross-account deployment no longer works

### LINKED ISSUE #11792: (cli): cdk diff cdk-assume-role-credential-plugin auth issue introduced in v1.75.0
I recently upgraded from v1.74.0 to v1.75.0, and our cdk diff started failing with the an auth error.  We use the cdk-assume-role-credential-plugin to allow cdk to run via a user in our central authentication account.

Strangely, cdk deploy works fine, so this only affects cdk diff.

### Reproduction Steps

We bootstrap our account using the CloudFormation template (https://raw.githubusercontent.com/aws/aws-cdk/master/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml) with the following params:
          "TrustedAccounts": "our auth account id",
          "Qualifier": "infra",
          "CloudFormationExecutionPolicies": "arn:aws:iam::aws:policy/AdministratorAccess"

### What did you expect to happen?

cdk diff should output differences between the stack definitions and the current deployed stacks.

### What actually happened?

We get the following error message:

Could not assume role in target account (did you bootstrap the environment with the right '--trust's?): User: arn:aws:sts::676932xxxxxx:assumed-role/cdk-infra-deploy-role-676932xxxxxx-us-east-1/676932xxxxxx-0-session is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::676932xxxxxx:role/cdk-infra-deploy-role-676932xxxxxx-us-east-1

### Environment

  - **CDK CLI Version  :** 1.75.0
  - **Framework Version:** ?
  - **Node.js Version:** v15.3.0
  - **OS               :** Debian Buster
  - **Language (Version):** OpenJDK Runtime Environment (build 11.0.9+11-post-Debian-1deb10u1) 

We run our CDK in the following docker container, if that helps at all: 

https://hub.docker.com/repository/docker/strategicblue/cdk

```dockerfile
FROM node:buster

ENV MVN_VERSION 3.6.3

RUN npm install -g aws-cdk cdk-assume-role-credential-plugin \
  && apt-get update \
  && apt-get install -y openjdk-11-jdk \
  && curl -fsSLO --compressed "https://downloads.apache.org/maven/maven-3/$MVN_VERSION/binaries/apache-maven-$MVN_VERSION-bin.tar.gz" \
  && tar -xzf "apache-maven-$MVN_VERSION-bin.tar.gz" -C /usr/local --strip-components=1 --no-same-owner \
  && rm "apache-maven-$MVN_VERSION-bin.tar.gz"
```

### Other

The failure message is weird, because it suggests that cdk has already assumed the correct role in the target account, but is then trying to assume the role again, and that role doesn't have sts permissions to assume itself, so that fails.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
This addresses a regression introduced in #11350 and reported in #11792.

The original PR added support for using a credential provider as a source
for credentials that will be used to assume the CDK Deploy Roles
(created by Modern Bootstrapping and used by Default Synthesis).

However, by doing so, it broke support for using current AWS credentials
to do the same.

## Original Behavior

- In case of legacy stack, use "current credentials" if they are for the right account, otherwise ask credential provider plugins, fail if current credentials are for the wrong account
- In case of DefaultSynthesized stack, always use "current credentials" to assume role

## Broken Behavior

- In case of legacy stack, use "current credentials" if they are for the right account, otherwise ask credential provider plugins for credentials to the target account, fail if current credentials are for the wrong account
- In case of DefaultSynthesized stack, 
  - Use "current credentials" if they are for the right account, otherwise ask credential provider plugins for credentials to the target account, fail if current credentials are for the wrong account (reusing the logic from legacy stacks)
  - Then assume role using credentials obtained in the previous step

The reuse of the same "credential obtaining" logic here broke cross-account role assumption, because we'd fail as soon as the current credentials would be for the wrong account instead of still trying to use them for AssumeRole.

## New Behavior

- Try to get "base credentials" for a target environment: 
  - Use "current credentials" if they are for the right account
  - Ask credential provider plugins
  - Use "current credentials" if they are for the wrong account (but remember that they were wrong)
- In case of a legacy stack:
  - If the credentials are for the wrong account, fail
- In case of a DefaultSynthesized stack:
  - Use the set of "base credentials" to try to assume the target role
  - If that succeeds, we're done
  - (Fallback) If it fails and the base credentials were already for the right account, use them after all. This fallback will allow people already using credential plugins to keep on using them, even when interoperating with DefaultSynthesized stacks. It will also allow people who seed their terminal with "ReadOnly" credentials (which might not have `sts:AssumeRole` permissions) to still run `cdk diff` as in the past.

## Changes to tests

There has been a major refactoring of the tests around this.

The current way of testing (mocking some calls left and right) was completely insufficient to test these mechanisms properly. I've therefore resorted to implementing a fake, in-memory version of STS's `GetCallerIdentity` and `AssumeRole`, and using the testing library `nock` to redirect network calls to that in-memory service. This will allow us to test the entire chain from our code down to and including the SDK's behavior, and make sure the right behavior happens without worrying about exact call orders.

At the same time, the single gigantic test fixture (with the `~/.aws/credentials` and `~/.aws/config` files) was becoming rather cumbersome. Instead, each test now includes just the one or two profile sections it uses, and a helper function creates both the config files as well as immediately creates those users in-memory in the fake STS service.

Closes #11792.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by rix0rrr** [comment]
Still needs tests, and needs more explanation in the PR body. Getting this out as quickly as possible to start collecing comments.

**Comment by redbaron** [comment]
@rix0rrr , I am trying to understand, how does it help to do cross account deployment? For `cdk deploy` to work cross accounts, effective credentials need to be able to:
 - do all necessary lookups (lookup by id, CDKToolkit lookup, etc)
 - assume roles created by bootstrap stack

When we boostrap account A with `--trust B` and make depoyment from `B`, we still can't do lookups in `A`, right? Therefore new role in account A has to be created still.

**Comment by rix0rrr** [comment]
> When we boostrap account A with --trust B and make depoyment from B, we still can't do lookups in A, right?

Lookups are out of scope for this, and a separate backlog item: https://github.com/aws/aws-cdk/issues/8905.

It will work if you deploy stacks that do not require context lookups though.

File: packages/aws-cdk/lib/api/aws-auth/credential-plugins.ts [hunk 1]
```diff
@@ -44,11 +44,15 @@ export class CredentialPlugins {
 
       // Backwards compatibility: if the plugin returns a ProviderChain, resolve that chain.
       // Otherwise it must have returned credentials.
-      if ((providerOrCreds as any).resolvePromise) {
-        return (providerOrCreds as any).resolvePromise();
-      }
-      return providerOrCreds;
+      const credentials = (providerOrCreds as any).resolvePromise ? await (providerOrCreds as any).resolvePromise() : providerOrCreds;
```
Comment (nija-at) [inline packages/aws-cdk/lib/api/aws-auth/credential-plugins.ts:47]: minor: could we do better than `as any`? What type are we expecting here?

File: packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts [hunk 2]
```diff
@@ -126,49 +141,53 @@ export class SdkProvider {
...
-      stsConfig: {
-        region,
-        ...this.sdkOptions,
-      },
-      masterCredentials: masterCredentials,
-    });
+    // We will proceed to AssumeRole using whatever we've been given.
+    const sdk = await this.withAssumedRole(baseCreds, options.assumeRoleArn, options.assumeRoleExternalId, env.region);
+
+    // Do a call on this SDK. We don't care about the answer, but we want to excercise the AssumeRoleCredentialsProvider
```
Comment (nija-at) [inline packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts:161]:
```suggestion
    // Do a call on this SDK. We don't care about the answer, but we want to exercise the AssumeRoleCredentialsProvider
```

File: packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts [hunk 3]
```diff
@@ -126,49 +141,53 @@ export class SdkProvider {
...
+    try {
+      await sdk.currentAccount();
+      return sdk;
+    } catch (e) {
+      // AssumeRole failed. Proceed and warn *if and only if* the baseCredentials were already for the right account
+      // or returned from a plugin. This is to cover some current setups for people using plugins or preferring to
+      // feed the CLI credentials which are sufficient by themselves. Prefer to assume the correct role if we can,
+      // but if we can't then let's just try with available credentials anyway.
+      if (baseCreds.source === 'correctDefault' || baseCreds.source === 'plugin') {
+        debug(e.message);
```
Comment (nija-at) [inline packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts:172]: minor: also place the stack trace into debug logs.

File: packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts [hunk 4]
```diff
@@ -126,49 +141,53 @@ export class SdkProvider {
...
-      const env = await this.resolveEnvironment(environment);
-      masterCredentials = await this.obtainCredentials(env.account, mode);
-      region = env.region;
-    } else {
-      region = this.defaultRegion;
-      masterCredentials = await this.defaultCredentials();
+    // Simple case is if we don't need to "assumeRole" here. If so, we must now have credentials for the right
+    // account.
+    if (options?.assumeRoleArn === undefined) {
+      if (baseCreds.source === 'incorrectDefault') { throw new Error(fmtObtainCredentialsError(env.account, baseCreds)); }
```
Comment (nija-at) [inline packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts:154]: curious: why should credentials from a plugin when there is no role to assume an error?

**Review by nija-at — APPROVED** [review]
Thanks for adding comments along. Made the logic so much easier to review.

Minor comments below.

File: packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts (hunk 4 above)
Comment (rix0rrr) [reply packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts:154]: That's not what this says though. This says if the default credentials are for the wrong account.

File: packages/aws-cdk/lib/api/aws-auth/credential-plugins.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/aws-cdk/lib/api/aws-auth/credential-plugins.ts:47]: >       // Backwards compatibility: if the plugin returns a ProviderChain, resolve that chain.
>      // Otherwise it must have returned credentials.

**Comment by redbaron** [comment]
@rix0rrr , this change fixed `cdk diff` (it now assumes `cdk-deploy` role natively without plugins), but assets uploads during `cdk deploy`  still produce following error:

```
[0%] start: Publishing 4a3609ad912843e581892f37ae9d6fb0fa1648b547693aaa562b0119452b8956:1454xxxxxxx-eu-west-2
[50%] fail: Need to perform AWS calls for account 1454xxxxxxx, but the current credentials are for 0147xxxxxxx
```
