### PR TITLE
docs(stepfunctions-tasks): fix up all code snippets so they compile

### LINKED ISSUE #12606: (stepfunctions) in the readme doc, functions from stepfunction_tasks where mistaken from stepfunction
Issue with link:

https://github.com/aws/aws-cdk/blob/3967c6e54cef5d3bc7e137ebcf827f884ec5ee04/packages/%40aws-cdk/aws-stepfunctions-tasks/README.md

Description:

CreateEndpointConfig was from tasks, and a few other functions in that page were also from tasks,

Another related issue:

in https://pypi.org/project/aws-cdk.aws-stepfunctions-tasks/  the parameters were incorrect.

Thanks

---

This is a 📕 documentation issue

### PR DESCRIPTION
**Pull request by shivlaks**
closes #12606

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-stepfunctions-tasks/rosetta/with-lambda.ts-fixture [hunk 1]
```diff
@@ -0,0 +1,22 @@
+// Fixture with packages imported, but nothing else
+import { Stack } from '@aws-cdk/core';
+import { Construct } from 'constructs';
+import * as sfn from '@aws-cdk/aws-stepfunctions';
+import * as tasks from '@aws-cdk/aws-stepfunctions-tasks';
+import * as lambda from '@aws-cdk/aws-lambda';
+
+class Fixture extends Stack {
```
Comment (nija-at) [inline packages/@aws-cdk/aws-stepfunctions-tasks/rosetta/with-lambda.ts-fixture:8]: What do you think about collapsing this and the DDB fixture into the default fixture?

Would that get too confusing? I'm wondering what the best practice could be here.

cc @rix0rrr

Comment (shivlaks) [reply packages/@aws-cdk/aws-stepfunctions-tasks/rosetta/with-lambda.ts-fixture:8]: i'm okay with that.
I was also unsure about what the heuristics should be to determine whether a separate fixture is required. I split them up because I imagined the next `n` integrations would probably bloat the default fixture but maybe I got ahead of where we're at currently.

Comment (nija-at) [reply packages/@aws-cdk/aws-stepfunctions-tasks/rosetta/with-lambda.ts-fixture:8]: That's not clear to me either, but probably prudent to start with fewer fixtures and then diverge as needed.

Comment (shivlaks) [reply packages/@aws-cdk/aws-stepfunctions-tasks/rosetta/with-lambda.ts-fixture:8]: sure, i'm on board with that. will simplify it down into the default fixture!

Comment (shivlaks) [reply packages/@aws-cdk/aws-stepfunctions-tasks/rosetta/with-lambda.ts-fixture]: done

**Review by nija-at — APPROVED** [review]
