### PR TITLE
fix(stepfunctions): disabling logging still requires LogGroup

### LINKED ISSUE #30814: (stepfunctions): cannot disable StateMachine logging with removing LogGroup
### Describe the bug

When I have a StateMachine with logging enabled,
to disable logging still requires an existing LogGroup.

### Expected Behavior

This configuration should be correct:
``` ts
new sfn.StateMachine(stack, 'StateMachine', {
  definitionBody: sfn.DefinitionBody.fromChainable(...),
  logs: { level: sfn.LogLevel.OFF },
});
```

### Current Behavior

TypeScript compile error occurs:
```
error TS2741: Property 'destination' is missing in type '{ level: sfn.LogLevel.OFF; }' but required in type 'LogOptions'.
```

Omitting `logs` property does not modify StateMachine's logging configuration.

### Reproduction Steps

Deploy a StateMachine described in Expected Behavior.

### Possible Solution

Make `LogOptions.destination` optional.
CDK should also verify `destination` is specified (or create one) when `level` is not OFF.

### Additional Information/Context

CloudFormation Documentation says:
https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-stepfunctions-statemachine-loggingconfiguration.html
> Destinations
> Required, if your log level is not set to OFF.

Workaround (Escape hatch):
``` ts
const states = new sfn.StateMachine(stack, 'StateMachine', {
  definitionBody: sfn.DefinitionBody.fromChainable(...),
});
(states.node.defaultChild as sfn.CfnStateMachine).addPropertyOverride('LoggingConfiguration', { Level: 'OFF' });
```

### CDK CLI Version

2.148.0

### Framework Version

_No response_

### Node.js Version

v20.15.1

### OS

Ubuntu

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Tietew**
### Issue # (if applicable)

Closes #30814.

### Reason for this change

To disable logging on a StateMachine (with logging enabled), we should specify `LogLevel.OFF` to `LogOptions.level`. But cannot remove the LogGroup because `LogOptions.destination` is required.

``` ts
new sfn.StateMachine(this, 'StateMachine', {
  definitionBody: ...,
  logs: { level: sfn.LogLevel.OFF } // allow to disable logging
});
```

### Description of changes

- Make `LogOptions.destination` optional.
- Validate `LogOptions.destination` is present when `LogOptions.level` is not `OFF`.

### Description of how you validated changes

Unit and integ tests that verify `LogOptions.destination` is opitional when `LogOptions.level` is `OFF` and throw an exception otherwise.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by Tietew** [comment]
Clarification Request
Existing integration tests do not include StateMachine with logging enabled.
Needed to add integ tests?

File: packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts [hunk 1]
```diff
@@ -507,26 +509,32 @@ export class StateMachine extends StateMachineBase {
...
-        'logs:ListLogDeliveries',
-        'logs:PutResourcePolicy',
-        'logs:DescribeResourcePolicies',
-        'logs:DescribeLogGroups',
-      ],
-      resources: ['*'],
-    }));
+    if (logOptions.level !== LogLevel.OFF && !logOptions.destination) {
+      throw new Error('Logs destination is required when level is not OFF.');
+    }
```
Comment (ChakshuGupta13) [inline packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts:514]: shall this validation be done earlier (at line [427](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts#L427)) with other validations instead?
```
if (!logs && !logs.level != LogLevel.OFF && !logs.destination) { ...
```

reasons for ask: 
- with current change, validations will be split across various places and as this file is big (and keep getting bigger), hence, it will become difficult to have complete picture of validation 
- ideally, caller shall not even call `buildLoggingConfiguration` if prerequisites are not met

File: packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts [hunk 2]
```diff
@@ -507,26 +509,32 @@ export class StateMachine extends StateMachineBase {
...
+        resources: ['*'],
+      }));
+    }
 
     return {
-      destinations: [{
+      destinations: logOptions.destination ? [{
         cloudWatchLogsLogGroup: { logGroupArn: logOptions.destination.logGroupArn },
-      }],
+      }] : undefined,
```
Comment (ChakshuGupta13) [inline packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts:537]: if we do this like as follows - will it reduce need to check `logOptions.destination` twice and simplify a bit?
```
let destinations = undefined;
if (logOptions.destination) {
  // Policy addition
  destinations = [{
    cloudWatchLogsLogGroup: { logGroupArn: logOptions.destination.logGroupArn },
  }];
}

return {
  destinations,
  ...,
  level: logOptions.level || LogLevel.ERROR
}
```

File: packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts [hunk 3]
```diff
@@ -60,8 +60,10 @@ export enum LogLevel {
 export interface LogOptions {
   /**
    * The log group where the execution history events will be logged.
+   *
+   * @default No log group. Required if your log level is not set to OFF.
    */
-  readonly destination: logs.ILogGroup;
+  readonly destination?: logs.ILogGroup;
```
Comment (ChakshuGupta13) [inline packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts:66]: will this not be a breaking change for existing usage? example:
```
const logOptions: LogOptions = {
  destination: <LogGroup>
}

const stateMachine: StateMachine = new StateMachine(parent, 'ID', {
  logs: logOptions,
  ...
}
... 

stateMachine.logs.destination.logGroupName // Error
stateMachine.logs.destination!.logGroupName // Change needed
```
Some user(s) might be utilising `ILogGroup`'s public properties from `logOptions` which will now cause issues because now such users will need to make non-null assertions before using such properties (e.g. with `!`)

Comment (Tietew) [reply packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts:66]: According to the [jsii-diff documentation](https://github.com/aws/jsii/blob/main/packages/jsii-diff/BREAKING_CHANGES.md#making-properties-optional):
> You are allowed to make _inputs_ optional

So i think this change is not a breaking change.

File: packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts (hunk 1 above)
Comment (Tietew) [reply packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts:517]: added a separate validation method validateLogOptions()

File: packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts [hunk 4]
```diff
@@ -307,6 +307,37 @@ describe('State Machine', () => {
...
+    });
+  });
+
+  test('log configuration throws when no destination specified', () => {
+    // GIVEN
+    const stack = new cdk.Stack();
+
+    expect(() => {
+      new sfn.StateMachine(stack, 'MyStateMachine', {
+        definitionBody: sfn.DefinitionBody.fromChainable(sfn.Chain.start(new sfn.Pass(stack, 'Pass'))),
```
[the remark this answers is not in the document]
Comment (Tietew) [reply packages/aws-cdk-lib/aws-stepfunctions/test/state-machine.test.ts:335]: it's just a copy & paste.
README also uses `sfn.Chain.start()` instead of bare `sfn.Pass`.

File: packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts (hunk 2 above)
Comment (Tietew) [reply packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts]: updated.

File: packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts (hunk 3 above)
Comment (GavinZZ) [reply packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts:69]: I think @Tietew is right here. The example Chakshu mentioned is output property while the changed code is for input property.

**Review by GavinZZ — DISMISSED** [review]
LGTM, thank you and apologize for the wait on the review!

**Comment by Tietew** [comment]
@mergifyio update

**Comment by aaythapa** [comment]
@mergify update

**Review by aaythapa — APPROVED** [review]
