### PR TITLE
fix(ec2): allow NAT instance to associate public IP

### LINKED ISSUE #31711: ec2: `NatProvider.instanceV2` does not work when `mapPublicIpOnLaunch=false` for public subnets
### Describe the bug

When we set `mapPublicIpOnLaunch=false` for public subnets, NAT instances does not get public IP addresses assigned, resulting in non-working NAT instances.

Disabling mapPublicIpOnLaunch is recommended as AWS Config rule (and cdk-nag as well.)
https://docs.aws.amazon.com/config/latest/developerguide/subnet-auto-assign-public-ip-disabled.html

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

NAT instance works.

### Current Behavior

NAT instance does not work.

### Reproduction Steps

Deploy the below VPC, and you can see the NAT instances does not have public IP addresses assigned; traffic cannot go to the Internet because of that.

```ts
new Vpc(this, 'Vpc', {
  natGatewayProvider: NatProvider.instanceV2({
    instanceType: InstanceType.of(InstanceClass.T4G, InstanceSize.MICRO),
  }),
  subnetConfiguration: [
    {
      subnetType: SubnetType.PUBLIC,
      name: 'Public',
      // NAT instance does not work when this set to false.
      mapPublicIpOnLaunch: false,
    },
    {
      subnetType: SubnetType.PRIVATE_WITH_EGRESS,
      name: 'Private',
    },
  ],
});
```

### Possible Solution

Expose [associatePublicIpAddress](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.Instance.html#associatepublicipaddress) property maybe?

### Additional Information/Context

_No response_

### CDK CLI Version

2.160.0

### Framework Version

_No response_

### Node.js Version

20

### OS

macos

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by GavinZZ**
### Issue # (if applicable)

Closes #31711

### Reason for this change

When we set mapPublicIpOnLaunch=false for public subnets, NAT instances does not get public IP addresses assigned, resulting in non-working NAT instances.

Disabling mapPublicIpOnLaunch is recommended as AWS Config rule (and cdk-nag as well.)
https://docs.aws.amazon.com/config/latest/developerguide/subnet-auto-assign-public-ip-disabled.html

### Description of changes

Support `associatePublicIpAddress`

### Description of how you validated changes

New unit and integ tests.

### Checklist
- [ ] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-ec2/lib/nat.ts [hunk 1]
```diff
@@ -188,6 +188,13 @@ export interface NatInstanceProps {
    */
   readonly instanceType: InstanceType;
 
+  /**
+   * Whether to associate a public IP address to the primary network interface attached to this instance.
+   *
+   * @default false
```
Comment (moelasmar) [inline packages/aws-cdk-lib/aws-ec2/lib/nat.ts:194]: I believe here you are referring to the CFN default value, but not the CDK one. I think it is better to mention that default value is null.

**Review by moelasmar — COMMENTED** [review]
LGTM, left minor comment

**Review by moelasmar — APPROVED** [review]
