### PR TITLE
fix(s3): cannot deploy multiple replication source buckets (under feature flag)

### LINKED ISSUE #33355: s3: replication only allows a single source bucket
### Describe the bug

[v2.177.0](https://github.com/aws/aws-cdk/releases/tag/v2.177.0) introduced the ability to set up S3 replication. This supports replicating from one source bucket to multiple destination buckets. But as soon as you configure a second source bucket, the stack fails to deploy (synth and diff work fine) with the error: `CDKReplicationRole already exists ...`

This appears to be caused by the replication feature using a role with [a hardcoded name](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-s3/lib/bucket.ts#L2788) without any checks if a role by that name already exists.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

Deployment does not generate any errors and all source buckets are set up with functioning replication.

### Current Behavior

During deployment an error occurs:
`CDKReplicationRole already exists in stack arn:aws:cloudformation:eu-west-1:xxxxxxxxxxxx:stack/test-BucketsInfraStack/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`

### Reproduction Steps

```ts
#!/usr/bin/env node
import { App } from 'aws-cdk-lib'
import { BucketsStage } from '../lib/BucketsStage'

const app = new App()
new BucketsStage(app, 'test', {})
app.synth()
```

```ts
import { Stage, StageProps } from 'aws-cdk-lib'
import { Construct } from 'constructs'
import { BucketsDrStack } from './BucketsDRStack'
import { BucketsInfraStack } from './BucketsInfraStack'

export class BucketsStage extends Stage {
  constructor(scope: Construct, id: string, props: StageProps) {
    super(scope, id, props)

    /**
     * Disaster recovery to a different region
     */
    const bucketsDrStack = new BucketsDrStack(this, 'BucketsDrStack', {
      env: {
        account: 'xxxxxxxxxxxx',
        region: 'eu-central-1'
      },
      crossRegionReferences: true,
      description: 'Disaster recovery to a different region'
    })

    /**
     * Infra stack sets up the basic and statefull infra
     */
    new BucketsInfraStack(this, 'BucketsInfraStack', {
      env: {
        account: 'xxxxxxxxxxxx',
        region: 'eu-west-1'
      },
      bucketsDrStack,
      crossRegionReferences: true,
      description: 'Infra stack sets up the basic and statefull infra'
    })
  }
}
```

```ts
import { RemovalPolicy, Stack, StackProps } from 'aws-cdk-lib'
import { BlockPublicAccess, Bucket, BucketEncryption, IBucket } from 'aws-cdk-lib/aws-s3'
import type { Construct } from 'constructs'

export class BucketsDrStack extends Stack {
  readonly bucketAReplica: IBucket
  readonly bucketBReplica: IBucket

  constructor (scope: Construct, id: string, props: StackProps) {
    super(scope, id, props)

    this.bucketAReplica = new Bucket(this, 'bucketAReplica', {
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
      encryption: BucketEncryption.S3_MANAGED,
      enforceSSL: true,
      versioned: true,
      removalPolicy: RemovalPolicy.DESTROY
    })

    this.bucketBReplica = new Bucket(this, 'bucketBReplica', {
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
      encryption: BucketEncryption.S3_MANAGED,
      enforceSSL: true,
      versioned: true,
      removalPolicy: RemovalPolicy.DESTROY
    })
  }
}
```

```ts
import {
  RemovalPolicy,
  Stack,
  StackProps
} from 'aws-cdk-lib'
import { BlockPublicAccess, Bucket, BucketEncryption } from 'aws-cdk-lib/aws-s3'
import type { Construct } from 'constructs'
import { BucketsDrStack } from './BucketsDRStack'

export interface OrInfraStackProps extends StackProps {
  bucketsDrStack: BucketsDrStack;
}

export class BucketsInfraStack extends Stack {
  readonly privateBucket: Bucket
  readonly publicBucket: Bucket

  constructor(
    scope: Construct,
    id: string,
    props: OrInfraStackProps
  ) {
    super(scope, id, props)

    const { bucketsDrStack } = props

    // The S3 bucket for the private assets
    this.privateBucket = new Bucket(this, 'PrivateBucket', {
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
      encryption: BucketEncryption.S3_MANAGED,
      enforceSSL: true,
      versioned: true,
      replicationRules: [{
        deleteMarkerReplication: true,
        destination: bucketsDrStack.bucketAReplica,
        priority: 1,
      }],
      removalPolicy: RemovalPolicy.DESTROY
    })

    // The S3 bucket for the public (accessible through CloudFront) assets
    this.publicBucket = new Bucket(this, 'PublicBucket', {
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
      encryption: BucketEncryption.S3_MANAGED,
      enforceSSL: true,
      versioned: true,
      /* uncommenting the next lines will cause the error
      replicationRules: [{
        deleteMarkerReplication: true,
        destination: bucketsDrStack.bucketBReplica,
        priority: 1,
      }],
      */
      removalPolicy: RemovalPolicy.DESTROY
    })
  }
}
```

### Possible Solution

The source bucket should accept an explicit replication role and add permissions to it instead of creating a role.

### Additional Information/Context

_No response_

### CDK CLI Version

2.178.1 (build ae342cb)

### Framework Version

_No response_

### Node.js Version

v22.13.0

### OS

Linux

### Language

TypeScript

### Language Version

5.7.3

### Other information

_No response_

### PR DESCRIPTION
**Pull request by badmintoncryer**
### Issue # (if applicable)

Closes #33355.

### Reason for this change

We cannot deploy multiple source buckets for object replication due to the explicitly set replication role name.

### Description of changes

Set replication role name by `PhysicalName.GENERATE_IF_NEEDED`.

### Describe any new or updated permissions being added

None

### Description of how you validated changes

Update both unit and integ test.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jochemd** [comment]
How does this work in a scenario where multiple stages are deployed to 1 account? So we have 2 buckets from the TEST stage being replicated and 2 buckets from the PRD stage being replicated? Will they use the same role? And what if the replication is cross-account?

I was more thinking along the lines of adding an optional `replicationRole: Role` property to the `ReplicationRule` interface and use that role if it is passed in. That gives the control to the user on when to use the same and when to use different roles. The destination bucket already allows the user to specify the role (ARN) in the `addReplicationPolicy` method. Or possibly refactor `renderReplicationConfiguration` so that the part that creates the policy for the source bucket becomes a public method to allow people to set up permissions easily when they cutomize their stack (similar to how the `addReplicationPolicy` method is public for the destination bucket).

BTW, https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-s3/lib/bucket.ts#L2853 appears to be confusing the buckets: `addReplicationPolicy()` can be used to set permissions on the destination bucket.

**Comment by badmintoncryer** [comment]
@jochemd 
I'm sorry for my late reply. Thank you for your feedback!

> How does this work in a scenario where multiple stages are deployed to 1 account? So we have 2 buckets from the TEST stage being replicated and 2 buckets from the PRD stage being replicated? Will they use the same role? And what if the replication is cross-account?

One replication role is generated for each source bucket, regardless of stage differences or whether cross-account access is involved. 
In the case of cross-account access, an explicit role name is specified, but there are no other differences.

> I was more thinking along the lines of adding an optional replicationRole: Role property to the ReplicationRule interface and use that role if it is passed in. 

Since one replication role executes replication according to multiple replication rules, it seems difficult to simply add a `role` property to the `ReplicationRule` interface. However, since I think the idea itself is excellent, how about posting it as a separate issue?
For this PR, I think it's better to focus on fixing the bug where multiple source buckets cannot be defined in the first place.

> BTW, https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-s3/lib/bucket.ts#L2853 appears to be confusing the buckets: addReplicationPolicy() can be used to set permissions on the destination bucket.

Oh! I've not realized this. I'll resolve this problem in another PR.

**Comment by badmintoncryer** [comment]
@jochemd 
I noticed that in the [original issue](#33355) you suggested making the role receivable as an argument.

From my perspective, since the current implementation is problematic, I think it would be best to first merge this PR to remove the hardcoded role name, and then create a new PR as a new feature to accept an optional replication role.

**Comment by jochemd** [comment]
Sounds good to me. Unfortunately I am not able to give an actual review or serious testing of this PR as when I try to go through the steps in the contributing guide I get errors on the linking step.

File: packages/aws-cdk-lib/aws-s3/lib/bucket.ts [hunk 1]
```diff
@@ -2787,9 +2788,7 @@ export class Bucket extends BucketBase {
 
     const replicationRole = new iam.Role(this, 'ReplicationRole', {
       assumedBy: new iam.ServicePrincipal('s3.amazonaws.com'),
-      // To avoid the error where the replication role cannot be used during cross-account replication,
-      // it is necessary to set the `roleName`.
-      roleName: 'CDKReplicationRole',
+      roleName: FeatureFlags.of(this).isEnabled(cxapi.SET_UNIQUE_REPLICATION_ROLE_NAME) ? PhysicalName.GENERATE_IF_NEEDED : 'CDKReplicationRole',
```
Comment (GavinZZ) [inline packages/aws-cdk-lib/aws-s3/lib/bucket.ts:2791]: should we have a common prefix and generate the rest instead?

**Review by GavinZZ — COMMENTED** [review]
Just a nit comment. The changes look good to me.

File: packages/aws-cdk-lib/aws-s3/lib/bucket.ts (hunk 1 above)
Comment (GavinZZ) [reply packages/aws-cdk-lib/aws-s3/lib/bucket.ts:2791]: Actually, nvm, I don't think we have this kind of precendence before.

**Review by GavinZZ — DISMISSED** [review]
Thank you as always for contributing!

**Comment by badmintoncryer** [comment]
@GavinZZ Thank you always too!

**Comment by phuhung273** [comment]
Guys is it weird the PR stuck too long while being the 1st in queue ?

**Comment by badmintoncryer** [comment]
@mergify update

**Comment by badmintoncryer** [comment]
@mergify dequeue

**Comment by badmintoncryer** [comment]
@GavinZZ Could you please resolve this mergify problem??

**Comment by badmintoncryer** [comment]
@mergify requeue

**Comment by badmintoncryer** [comment]
@mergify update

**Comment by GavinZZ** [comment]
@badmintoncryer somehow I can't update latest main branch to this PR.. The PR seems to stuck at `Checking for the ability to merge automatically...`. I'll keep an eye out for this but we may need to create a new PR instead.

**Review by GavinZZ — APPROVED** [review]
