### PR TITLE
fix(elasticloadbalancingv2): dualstack ALB missing default IPv6 ingress rule

### LINKED ISSUE #7043: Generated Security Group for Dualstack ALB Doesn't Allow IPv6 Connections
**Expected Behavior**
When creating an application load balancer (adapted from [this example](https://github.com/aws-samples/aws-cdk-examples/blob/master/typescript/ecs/ecs-service-with-advanced-alb-config/index.ts#L37-L41)), if I configure `ipAddressType` to be dualstack, and set `internetFacing` to true, I would expect the automatically generated security group to allow inbound connections from `0.0.0.0/0` and `::/0`.  

**Actual Behavior**
The automatically generated security group only allows inbound connections from `0.0.0.0/0`.

### Reproduction Steps

Create an application load balancer

```js
    // Create ALB
    const lb = new ApplicationLoadBalancer(
      this,
      camelCase(`alb-${REGION}-${ENV_CODE}-api-load-balancer`),
      {
        vpc,
        internetFacing: true,
        ipAddressType: IpAddressType.DUAL_STACK,
        vpcSubnets: {
          subnets: IPV6EnabledSubnets
        },
      }
    );
```

Note generated security  group

Screen Shot 2020-03-27 at 1 54 51 PM

### Error Log

n/a

### Environment

  - aws-cli/2.0.1 Python/3.7.4 Darwin/19.3.0 botocore/2.0.0dev5
  - 1.31.0 (build 8f3ac79)
  - MacOS Catalina (10.15.3)
  - English

### Other

I was able to workaround this by creating a security group for the load balancer manually and referencing the autoscaling group security group.

```js
    // Create ALB
    // Configure security group for load balancer
    // TODO: I would expect IPv6 to be included for free, this is a workaround in the meantime.
    const lbSecurityGroup = new SecurityGroup(
      this,
      camelCase(`sg-${REGION}-${ENV_CODE}-api-load-balancer`),
      {
        vpc,
        description: "The API load balancer security group",
      }
    );

    // Add ingress and egress rules for load balancer
    lbSecurityGroup.addIngressRule(Peer.anyIpv4(), Port.tcp(443), "Allow IPv4 connections to the security group on port 443");
    lbSecurityGroup.addIngressRule(Peer.anyIpv6(), Port.tcp(443), "Allow IPv6 connections to the security group on port 443");
    lbSecurityGroup.addEgressRule(autoScalingGroup.connections.securityGroups[0], Port.tcp(80), "Allow port 80 IPv4 connections to the autoscaling group");

    const lb = new ApplicationLoadBalancer(
      this,
      camelCase(`alb-${REGION}-${ENV_CODE}-api-load-balancer`),
      {
        vpc,
        internetFacing: true,
        ipAddressType: IpAddressType.DUAL_STACK,
        vpcSubnets: {
          subnets: IPV6EnabledSubnets
        },
        securityGroup: lbSecurityGroup
      }
    );
```

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by BryanPan342**
**[ISSUE]**
ALB configured with `ipAddressType: dualstack` and `internetFacing: true` missing ingress rule for IPv6. 

**[APPROACH]**
Add a property in `IApplicationLoadBalancer` to obtain `ipAddressType` in listener constructor.
Add a check in `ApplicationListener` constructor to check for `ipAddressType` of `dualstack` 

**[NOTE]**
Implemented `dualstack` check only in the constructor because any additional ingress rule should be specified by the user upon further use.

Fixes #7043

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by BryanPan342** [comment]
**[TODO]** 
- [ ] Update documentation for IApplicationLoadBalancer
- [x] Add integration tests for 'dualstack' ALB

**Comment by BryanPan342** [comment]
I found creating a IPv6 subnet to be a pain point and it seems some customers agree (#894). Since there is a workaround, I don't think it needs immediate attention but wanted to just point it out to ensure that it doesn't get forgotten. I would also be willing to work on it if I have free time!

File: packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts [hunk 1]
```diff
@@ -65,6 +66,7 @@ export class ApplicationLoadBalancer extends BaseLoadBalancer implements IApplic
       ipAddressType: props.ipAddressType,
     });
 
+    this.ipAddressType = props.ipAddressType || IpAddressType.IPV4;
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts:69]:
```suggestion
    this.ipAddressType = props.ipAddressType ?? IpAddressType.IPV4;
```

preferred to use nullish coalescing now that we're on TypeScript 3.7+

File: packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.alb3.ts [hunk 2]
```diff
@@ -0,0 +1,116 @@
+#!/usr/bin/env node
+import * as ec2 from '@aws-cdk/aws-ec2';
+import * as cdk from '@aws-cdk/core';
+import * as elbv2 from '../lib';
+
+/* Credit to @TrueBrain and @misterjoshua for the IPv6 workaround */
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.alb3.ts:6]: is there an issue or comment this can point to instead

File: packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.alb3.ts [hunk 3]
```diff
@@ -0,0 +1,116 @@
...
+const valueOrDie = <T, C extends T = T>(value: T | undefined, err: Error): C => {
+  if (value === undefined) { throw err; }
+  return value as C;
+};
+
+/**
+ * Integration test to deployability and use of dualstack ALB. Creates an ALB
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.alb3.ts:13]: consider renaming this test file to `integ.alb.dualstack` or something similar

File: packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/test.listener.ts [hunk 4]
```diff
@@ -76,6 +76,41 @@ export = {
     test.done();
   },
 
+  'Listener default to open - Dualstack'(test: Test) {
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-elasticloadbalancingv2/test/alb/test.listener.ts:79]:
```suggestion
  'Listener default to open - IPv4 and IPv6 (dualstack)'(test: Test) {
```

File: packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts [hunk 5]
```diff
@@ -458,6 +460,11 @@ export interface IApplicationLoadBalancer extends ILoadBalancerV2, ec2.IConnecta
    */
   readonly vpc?: ec2.IVpc;
 
+  /**
+   * The IP Address Type for this load balancer
+   */
+  readonly ipAddressType?: IpAddressType;
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts:466]: include an `@default` doc so consumer can easily figure out behaviour when unset

```suggestion
   *
   * @default IpAddresstype.IPV4
   */
  readonly ipAddressType?: IpAddressType;
```

File: packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts [hunk 6]
```diff
@@ -186,6 +186,10 @@ export class ApplicationListener extends BaseListener implements IApplicationLis
     if (props.open !== false) {
       this.connections.allowDefaultPortFrom(ec2.Peer.anyIpv4(), `Allow from anyone on port ${port}`);
     }
+
+    if (props.open !== false && this.loadBalancer.ipAddressType === IpAddressType.DUAL_STACK) {
+      this.connections.allowDefaultPortFrom(ec2.Peer.anyIpv6(), `Allow from anyone on port ${port}`);
+    }
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts:192]: why not just nest the `if (this.loadBalancer.ipAddressType === ...` condition into the if statement above?

it helps with readibility to keep the related logic in the same control flow block and saves on checking props.open a second time

File: packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.alb3.ts (hunk 2 above)
Comment (BryanPan342) [reply packages/@aws-cdk/aws-elasticloadbalancingv2/test/integ.alb3.ts:6]: #894 

Seems like an oldy but I couldn't find another method of implementation with existing cdk packages. Should I just reference it with URL?
