### PR TITLE
fix(sns): contentBasedDeduplication is always false for imported topic

### LINKED ISSUE #29532: sns.Topic.fromTopicArn: importinig topic forces contentBasedDeduplication = false
### Describe the bug

When importing a topic by Arn, the constructor sets contentBasedDeduplication = false. 

This means that when we call the resource method getContentBasedDeduplication(), it returns false always.

### Expected Behavior

I would expect that when the resource is imported, the ARN is checked to determine whether or not contentBasedDeduplication is enabled on the Topic, then return a result that contains this.

### Current Behavior

Currently .getContentBasedDeduplication() always returns false, regardless of the configuration of the actual Topic imported. This is only for imported Topics. Newly created topics return the actual value of the property. 

### Reproduction Steps

JAVA code:

        // Existing Topic with ContentBasedDeduplication enabled
        final ITopic assetTopic = Topic.fromTopicArn(this, "asset topic","arn:aws:sns:us-east-1:123456789012:myTopic.fifo");
        // returns false
        System.out.println(assetTopic.getContentBasedDeduplication());
        // New Topic created with ContentBasedDeduplication enabled
        Topic newTopic = Topic.Builder.create(this,"new topic")
                .contentBasedDeduplication(true)
                .displayName("my new topic")
                .fifo(true)
                .build();
        //Returns true, correctly
        System.out.println(newTopic.getContentBasedDeduplication());    

### Possible Solution

_No response_

### Additional Information/Context

See linked commit for when the property was set. Not sure if there is possibly an underlying reason why this value needs to be false for imports, if so please let me know.

### CDK CLI Version

2.131.0

### Framework Version

_No response_

### Node.js Version

NA

### OS

Win11

### Language

Java

### Language Version

openjdk version "21.0.2" 2024-01-16 LTS

### Other information

_No response_

### PR DESCRIPTION
**Pull request by msambol**
Closes #29532.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-sns/lib/topic.ts [hunk 1]
```diff
@@ -154,13 +154,14 @@ export class Topic extends TopicBase {
...
+   * @param contentBasedDeduplication If content-based deduplication is enabled
    */
-  public static fromTopicArn(scope: Construct, id: string, topicArn: string): ITopic {
+  public static fromTopicArn(scope: Construct, id: string, topicArn: string, contentBasedDeduplication?: boolean): ITopic {
     class Import extends TopicBase {
       public readonly topicArn = topicArn;
       public readonly topicName = Stack.of(scope).splitArn(topicArn, ArnFormat.NO_RESOURCE_NAME).resource;
       public readonly fifo = this.topicName.endsWith('.fifo');
-      public readonly contentBasedDeduplication = false;
+      public readonly contentBasedDeduplication = contentBasedDeduplication ?? false;
```
Comment (msambol) [inline packages/aws-cdk-lib/aws-sns/lib/topic.ts:164]: keep default `false` for backwards compatibility.

**Comment by msambol** [comment]
Exemption request: I don't believe an integration test is needed here.

File: packages/aws-cdk-lib/aws-sns/lib/topic.ts [hunk 2]
```diff
@@ -154,13 +154,14 @@ export class Topic extends TopicBase {
    * @param scope The parent creating construct
    * @param id The construct's name
    * @param topicArn topic ARN (i.e. arn:aws:sns:us-east-2:444455556666:MyTopic)
+   * @param contentBasedDeduplication If content-based deduplication is enabled
    */
-  public static fromTopicArn(scope: Construct, id: string, topicArn: string): ITopic {
+  public static fromTopicArn(scope: Construct, id: string, topicArn: string, contentBasedDeduplication?: boolean): ITopic {
```
Comment (lpizzinidev) [inline packages/aws-cdk-lib/aws-sns/lib/topic.ts:159]: 🤔 Not sure about this approach.
Do we have a way to detect if `contentBasedDeduplication` is enabled from the `topicArn`?
If not, I'd prefer to create a separate `fromTopicAttributes` method to address the use case as done in other constructs.

**Review by lpizzinidev — CHANGES_REQUESTED** [review]

File: packages/aws-cdk-lib/aws-sns/lib/topic.ts (hunk 2 above)
Comment (msambol) [reply packages/aws-cdk-lib/aws-sns/lib/topic.ts:159]: Yeah let me fix this....

**Comment by msambol** [comment]
@lpizzinidev This should be better now..

**Review by lpizzinidev — CHANGES_REQUESTED** [review]
Thanks for the changes 👍
Left some comments for further adjustments.
Also, can you please add integration test coverage for the `Topic.fromTopicArn` and `Topic.fromTopicAttributes` methods?

**Comment by msambol** [comment]
@lpizzinidev This should be better now.

File: packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns.ts [hunk 3]
```diff
@@ -40,6 +40,9 @@ class SNSInteg extends Stack {
       successFeedbackRole: feedbackRole,
       successFeedbackSampleRate: 50,
     });
+
+    // Can import topic from arn
+    Topic.fromTopicArn(this, 'ImportedTopic', topic.topicArn);
```
Comment (lpizzinidev) [inline packages/@aws-cdk-testing/framework-integ/test/aws-sns/test/integ.sns.ts:45]:
```suggestion
    const topic2 = new Topic(this, 'MyTopic2', {
      topicName: 'fooTopic2',
      displayName: 'fooDisplayName2',
      masterKey: key,
    });
    const importedTopic = Topic.fromTopicArn(this, 'ImportedTopic', topic2.topicArn);
    
    importedTopic.addLoggingConfig({
      protocol: LoggingProtocol.HTTP,
      failureFeedbackRole: feedbackRole,
      successFeedbackRole: feedbackRole,
      successFeedbackSampleRate: 50,
    });
```
Can you please add an extra topic so that the snapshot will get updated and the pipeline will be green? 
Also, since `fromTopicArn` is calling `fromTopicAttributes`, I think you can remove the change in [integ.sns-fifo.ts](https://github.com/aws/aws-cdk/pull/29542/files#diff-bd9737da387a76c89a9eeb2d47667280f85b2dfb8435ccae19dd8653a44365af)

**Review by lpizzinidev — APPROVED** [review]
Thanks 👍
Looks good to me, just a final adjustment on the integration tests is needed in my opinion

**Comment by shikha372** [comment]
Thanks @msambol for your contribution, as per my understanding content based deduplication is available only for the FIFO queue, so if we are allowing users to set this value for imported topics, they might mistakenly set it for standard queue and face issue during deployment. Could we add validation that this is being set from attributes only in case in fifo queue.

**Comment by msambol** [comment]
> Thank you @msambol for your contribution, as per my understanding content based deduplication is available only for the FIFO queue, so if we are allowing users to set this value for imported topics, they might mistakenly set it for standard queue and face issue during deployment. Could we add validation that this is being set from attributes only in case in fifo queue.

Great catch! Updated.

**Review by shikha372 — APPROVED** [review]
LGTM .. Thank you @msambol for contributing and @lpizzinidev for review
