### PR TITLE
fix(config): Creating multiple rules from the same lambda

### LINKED ISSUE #17582: (aws-config): Creating multiple rules from the same lambda fails
### What is the problem?

If you create a (python) lambda and use it as the lambda function for multiple custom config rules, it will fail with the following error:
`jsii.errors.JSIIError: There is already a Construct with name 'Permission' in PythonFunction [MonolithicConfigRuleLambda]`

This appears to be similar to https://github.com/aws/aws-cdk/issues/9756 which was fixed in 1.61.0

### Reproduction Steps

Create a (python) lambda function and use it to create more than one custom AWS Config rule

```python
        rule_lambda = aws_lambda_python.PythonFunction(
            self,
            f"MonolithicConfigRuleLambda",
            runtime=aws_lambda.Runtime.PYTHON_3_9,
            entry=str(Path(__file__).parent / "config_lambda"),
            index="handler.py",
            handler="lambda_handler",
            memory_size=512,
            timeout=core.Duration.seconds(60),
        )
        aws_config.CustomRule(
            self,
            "Rule1",
            config_rule_name="Rule1",
            rule_scope=aws_config.RuleScope.from_tag("Key"),
            configuration_changes=True,
            lambda_function=rule_lambda,
        )
        aws_config.CustomRule(
            self,
            "Rule2",
            config_rule_name="Rule2",
            rule_scope=aws_config.RuleScope.from_tag("Key"),
            configuration_changes=True,
            lambda_function=rule_lambda,
        )
```

### What did you expect to happen?

Create many config rules using a single labmda

### What actually happened?

The following error is received:
`jsii.errors.JSIIError: There is already a Construct with name 'Permission' in PythonFunction [MonolithicConfigRuleLambda]`

### CDK CLI Version

1.130.0

### Framework Version

_No response_

### Node.js Version

15.14.0

### OS

MacOS

### Language

Python

### Language Version

3.9

### Other information

You can work around it by referencing the function by arn for subsequent calls:

```python
        rule_lambda = aws_lambda_python.PythonFunction(
            self,
            f"MonolithicConfigRuleLambda",
            runtime=aws_lambda.Runtime.PYTHON_3_9,
            entry=str(Path(__file__).parent / "config_lambda"),
            index="handler.py",
            handler="lambda_handler",
            memory_size=512,
            timeout=core.Duration.seconds(60),
        )
        aws_config.CustomRule(
            self,
            "Rule1",
            config_rule_name="Rule1",
            rule_scope=aws_config.RuleScope.from_tag("Key"),
            configuration_changes=True,
            lambda_function=rule_lambda,
        )
        rule_lambda_copy = aws_lambda.Function.from_function_arn(self, "MonolithicConfigRuleLambdaCopy", rule_lambda.function_arn)
        aws_config.CustomRule(
            self,
            "Rule2",
            config_rule_name="Rule2",
            rule_scope=aws_config.RuleScope.from_tag("Key"),
            configuration_changes=True,
            lambda_function=rule_lambda_copy,
        )
        aws_config.CustomRule(
            self,
            "Rule3",
            config_rule_name="Rule3",
            rule_scope=aws_config.RuleScope.from_tag("Key"),
            configuration_changes=True,
            lambda_function=rule_lambda_copy,
        )

```

### PR DESCRIPTION
**Pull request by watany-dev**
fixes #17582 

because the id of ".addPermission" is set to a fixed value of ″permission″, which means that only one can be set in the stack.

1. and add a unique suffix to the id. This will allow multiple custom rules to be handled in one stack.
2. Do the id check before addPermission. This will allow only one permission to be granted to a custom rule from the config service.

Addendum:.
I have created a hash from FunctionName, AccountID, and Region to make the suffix unique.
Therefore, the omitted parts in the test code have been modified to fix the result.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by watany-dev** [comment]
@corymhall 

Hi.
I understand from the PR that the CDK team is busy and it pains me to say this, but may I ask when you expect to be able to review this?
*If you look at it a little and see something obviously missing, a rough comment would be fine!

File: packages/@aws-cdk/aws-config/lib/rule.ts [hunk 1]
```diff
@@ -352,11 +352,14 @@ export class CustomRule extends RuleNew {
...
-    props.lambdaFunction.addPermission('Permission', {
-      principal: new iam.ServicePrincipal('config.amazonaws.com'),
-      sourceAccount: this.env.account,
-    });
+    const customRuleFnName: string = props.lambdaFunction.node.id;
+    const customRulePermissionId: string = `customRulePermission-${customRuleFnName}`;
+    if (!props.lambdaFunction.permissionsNode.tryFindChild(customRulePermissionId)) {
+      props.lambdaFunction.addPermission(customRulePermissionId, {
+        principal: new iam.ServicePrincipal('config.amazonaws.com'),
+        sourceAccount: this.env.account,
```
Comment (corymhall) [inline packages/@aws-cdk/aws-config/lib/rule.ts:360]: I think this wouldn't work if we had multiple config rules in different accounts. This would only add the permission for the first account. I think we somehow need to add the account into the id.

Comment (corymhall) [reply packages/@aws-cdk/aws-config/lib/rule.ts:360]: And actually I wonder if it would be better to handle this in the `addPermission` method since this problem is probably not unique to config. We could probably do something similar to what we do for `grantInvoke`

https://github.com/aws/aws-cdk/blob/8a733bad022fb2ac0551e32fd26a4847c0b36ff2/packages/%40aws-cdk/aws-lambda/lib/function-base.ts#L433-L414

**Review by corymhall — DISMISSED** [review]

File: packages/@aws-cdk/aws-config/lib/rule.ts (hunk 1 above)
Comment (watany-dev) [reply packages/@aws-cdk/aws-config/lib/rule.ts:360]: Thanks for the quick review!
It seems more natural to use a random hash rather than forcing it to get an accountid, and it seems to be more natural to use a random hash, and the ids don't conflict. I will give it a try.

**Comment by watany-dev** [comment]
Addendum:.
I have created a hash from FunctionName, AccountID, and Region to make the suffix unique.
Therefore, the omitted parts in the test code have been modified to fix the result.

File: packages/@aws-cdk/aws-config/lib/rule.ts (hunk 1 above)
Comment (watany-dev) [reply packages/@aws-cdk/aws-config/lib/rule.ts:367]: Addendum:.
I have created a hash from FunctionName, AccountID, and Region to make the suffix unique.
Therefore, the omitted parts in the test code have been modified to fix the result.

**Comment by watany-dev** [comment]
@corymhall 

Excuse me for being busy, I tried to fix it with reference to the lambda implementation, but what do you think?

File: packages/@aws-cdk/aws-config/lib/rule.ts (hunk 1 above)
Comment (corymhall) [reply packages/@aws-cdk/aws-config/lib/rule.ts:367]: @watany-dev what do you think about my suggestion for doing this in the `addPermission` method instead? That would be a more global fix for this issue.

**Review by corymhall — CHANGES_REQUESTED** [review]
Putting back in request changes.

**Review by corymhall — CHANGES_REQUESTED** [review]
back in request changes.

File: packages/@aws-cdk/aws-config/lib/rule.ts (hunk 1 above)
Comment (corymhall) [reply packages/@aws-cdk/aws-config/lib/rule.ts:367]: yeah I see your point. Ok i'm good with your solution, just a couple of comments on the integ tests.

File: packages/@aws-cdk/aws-config/test/integ.rule.lit.ts [hunk 2]
```diff
@@ -16,6 +16,7 @@ class ConfigStack extends cdk.Stack {
       code: lambda.AssetCode.fromInline('exports.handler = (event) => console.log(event);'),
       handler: 'index.handler',
       runtime: lambda.Runtime.NODEJS_14_X,
+      functionName: 'coolrule',
```
Comment (corymhall) [inline packages/@aws-cdk/aws-config/test/integ.rule.lit.ts:19]:
```suggestion
```

File: packages/@aws-cdk/aws-config/test/integ.rule.lit.ts [hunk 3]
```diff
@@ -38,5 +39,7 @@ class ConfigStack extends cdk.Stack {
   }
 }
 
-new ConfigStack(app, 'aws-cdk-config-rule-integ');
+new ConfigStack(app, 'aws-cdk-config-rule-integ', {
+  env: { account: '123456789012', region: 'us-east-1' },
```
Comment (corymhall) [inline packages/@aws-cdk/aws-config/test/integ.rule.lit.ts:43]:
```suggestion
```

The integ tests stacks should be environment agnostic.

File: packages/@aws-cdk/aws-config/test/integ.scoped-rule.ts [hunk 4]
```diff
@@ -4,12 +4,15 @@ import * as config from '../lib';
 
 const app = new cdk.App();
 
-const stack = new cdk.Stack(app, 'aws-cdk-config-rule-scoped-integ');
+const stack = new cdk.Stack(app, 'aws-cdk-config-rule-scoped-integ', {
+  env: { account: '123456789012', region: 'us-east-1' },
```
Comment (corymhall) [inline packages/@aws-cdk/aws-config/test/integ.scoped-rule.ts:8]:
```suggestion
```

File: packages/@aws-cdk/aws-config/test/integ.scoped-rule.ts [hunk 5]
```diff
@@ -4,12 +4,15 @@ import * as config from '../lib';
...
+});
 
 const fn = new lambda.Function(stack, 'CustomFunction', {
   code: lambda.AssetCode.fromInline('exports.handler = (event) => console.log(event);'),
   handler: 'index.handler',
   runtime: lambda.Runtime.NODEJS_14_X,
+  functionName: 'coolrule',
```
Comment (corymhall) [inline packages/@aws-cdk/aws-config/test/integ.scoped-rule.ts:15]:
```suggestion
```

File: packages/@aws-cdk/aws-config/lib/rule.ts [hunk 6]
```diff
@@ -352,11 +353,20 @@ export class CustomRule extends RuleNew {
...
-      sourceAccount: this.env.account,
-    });
+    const hash = createHash('sha256')
+      .update(JSON.stringify({
+        fnName: props.lambdaFunction.functionName.toString,
+        accountId: this.env.account,
+        region: this.env.region,
+      }), 'utf8')
+      .digest('base64');
+    const customRulePermissionId: string = `customRulePermission-${hash}`;
```
Comment (corymhall) [inline packages/@aws-cdk/aws-config/lib/rule.ts:363]:
```suggestion
    const customRulePermissionId: string = `CustomRulePermission${hash}`;
```

nit.

**Review by corymhall — DISMISSED** [review]

**Comment by watany-dev** [comment]
Thanks for confirming. I was satisfied with your comments and have incorporated all of them.
I have imported them with the suggestion feature of Github and will add the test now.

File: packages/@aws-cdk/aws-config/test/integ.rule.lit.ts (hunk 3 above)
Comment (watany-dev) [reply packages/@aws-cdk/aws-config/test/integ.rule.lit.ts:42]: Let me leave this comment as it is. It is certainly not a process that asks for region and account ID. However, if it is randomized, the hash seed of the snapshot test will change every time, and the test will not converge.

File: packages/@aws-cdk/aws-config/test/integ.scoped-rule.ts (hunk 4 above)
Comment (watany-dev) [reply packages/@aws-cdk/aws-config/test/integ.scoped-rule.ts:8]: Let me leave this comment as it is. It is certainly not a process that asks for region and account ID. However, if it is randomized, the hash seed of the snapshot test will change every time, and the test will not converge.

File: packages/@aws-cdk/aws-config/test/integ.rule.lit.ts (hunk 3 above)
Comment (corymhall) [reply packages/@aws-cdk/aws-config/test/integ.rule.lit.ts:42]: I think it's probably because when the env is not defined then the account and region are tokens.

I left a review comment on what you need to updated.

File: packages/@aws-cdk/aws-config/lib/rule.ts [hunk 7]
```diff
@@ -352,11 +353,20 @@ export class CustomRule extends RuleNew {
...
     }
-
-    props.lambdaFunction.addPermission('Permission', {
-      principal: new iam.ServicePrincipal('config.amazonaws.com'),
-      sourceAccount: this.env.account,
-    });
+    const hash = createHash('sha256')
+      .update(JSON.stringify({
+        fnName: props.lambdaFunction.functionName.toString,
+        accountId: this.env.account,
```
Comment (corymhall) [inline packages/@aws-cdk/aws-config/lib/rule.ts:359]: Both account and region need to be resolved. This should fix the issue you are having with the environment agnostic integ tests.

```ts
accountId: Stack.of(this).resolve(this.env.account),
```

**Review by corymhall — DISMISSED** [review]

**Comment by watany-dev** [comment]
I am glad to have gained another knowledge.I was able to put the test independent of region,account.
Thanks for sharing your tips.

File: packages/@aws-cdk/aws-config/test/rule.test.ts [hunk 8]
```diff
@@ -417,4 +413,47 @@ describe('rule', () => {
     });
   });
 
-});
+  test('create two custom rule and one function', () => {
```
Comment (Naumel) [inline packages/@aws-cdk/aws-config/test/rule.test.ts:416]: [nit] `rule` --> `rules`

File: packages/@aws-cdk/aws-config/lib/rule.ts [hunk 9]
```diff
@@ -352,11 +353,20 @@ export class CustomRule extends RuleNew {
...
-      sourceAccount: this.env.account,
-    });
+    const hash = createHash('sha256')
+      .update(JSON.stringify({
+        fnName: props.lambdaFunction.functionName.toString,
+        accountId: Stack.of(this).resolve(this.env.account),
+        region: Stack.of(this).resolve(this.env.region),
+      }), 'utf8')
+      .digest('base64');
+    const customRulePermissionId: string = `CustomRulePermission${hash}`;
```
Comment (Naumel) [inline packages/@aws-cdk/aws-config/lib/rule.ts:363]: Perhaps it is late in the day and I should not be reviewing, but is there a reason why the rules should not be part of the class attributes?
This looks like the `Create` part of CRUD -- is there no scenario by which management is required?

**Review by Naumel — COMMENTED** [review]
Hi, I have a question and a nit pick.

I'm always curious to hear what I might be missing, so I'm all metaphorical ears regarding your perspective 😄

File: packages/@aws-cdk/aws-config/test/rule.test.ts (hunk 8 above)
Comment (watany-dev) [reply packages/@aws-cdk/aws-config/test/rule.test.ts:416]: thank you! Good job. The typo has been fixed.

**Comment by watany-dev** [comment]
@Naumel 
How did you fix the comment (typo) you received? I am sending you a reviewer once, but if you need to change it, I would appreciate it if you could reply.

**Comment by corymhall** [comment]
@watany-dev sorry for the delay on this. We have been discussing this change internally and our hesitation is whether or not changing the logicalId of the permission resource is a breaking change or not. When the logicalId changes a new resource will be created and the existing resource will be deleted. I _think_ that should be fine because the new permission will be created first, establishing the permission and then the old one will be deleted. What we don't know is whether there is any delay in this taking place. For this to work, the change needs to be instant and not cause any permission errors.

We need to test this scenario to be sure, but i'm not sure how.

**Comment by watany-dev** [comment]
@corymhall 
Thank you for your answer.
To be honest, it's hard for me to come up with test ideas right away.
If you hesitate to implement a variable fixed ID for the purpose of avoiding duplication like this time, it is a concern that the CDK may become a complicated implementation that creates a stack for each resource.

Here's a suggested implementation

1. The resource for the first time sets the id to a fixed value. Specifically, it searches for id="permission" and sets "permission" to id if it does not exist. If it exists, use this implementation to make the id variable. The latter pattern is a bug in this issue and should not exist now, so it seems that there is no existing impact.
2. Add an option `manualPermissionId` to set the id dynamically. This breaking change will be done as planned, and if you really want to avoid replacing existing resources, specify "permission" manually. If this conflicts, it is the user's responsibility to change.

I will follow and respond to the above implementation suggestions, or better ideas.

**Review by corymhall — DISMISSED** [review]

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
We now need the conflicts resolved.

**Comment by watany-dev** [comment]
Removed the conflict. please confirm.

**Comment by Naumel** [comment]
Is this conversation
> I will follow and respond to the above implementation suggestions, or better ideas.

concluded?

**Review by Naumel — APPROVED** [review]
♻️ conflicts were addressed and the PR has been previously approved.
