### PR TITLE
fix(aws-ec2): change maxAZs default for VPCs to 3

### LINKED ISSUE #996: VPC: Default AZs to 3
Right now, the default for the # of AZs is "as many as you can get", which leads to consistent problems in us-east-1 (because it has so many AZs): I can't start a default VPC because I run out of EIPs.

What's worse, code that runs fine in one region fails to start in us-east-1 because of this, which is worse. You think you've tested something, but then it doesn't work.

Since there's diminishing returns of additional AZs after the 3rd, why not default to 3? (But let users raise the number, obviously, if they really want to).

Also, we should probably make it possible to define an offset as well, so that you can have two VPCs spread over all 6 AZs (one a-b-c, the other d-e-f).

### PR DESCRIPTION
**Pull request by rix0rrr**
For most users, default deployments of a VPC in `us-east-1` would fail
because that region has more AZs (6) than the allowed EIP allocations in
an acccount (5).

This is a very poor experience. Plus, it is wasteful since there is
not much additional value in using more than 3 AZs for a VPC.

Fixes #996.

----

### Pull Request Checklist

* [x] Testing
  - Unit test added
  - __CLI change?:__ manually run [integration tests](https://github.com/awslabs/aws-cdk/blob/master/packages/aws-cdk/integ-tests/test.sh) and paste output as a PR comment
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-ec2/lib/vpc.ts [hunk 1]
```diff
@@ -58,7 +58,7 @@ export interface VpcNetworkProps {
    * If the region has more AZs than you want to use (for example, because of EIP limits),
    * pick a lower number here. The AZs will be sorted and picked from the start of the list.
    *
-   * @default All AZs in the region
+   * @default 3
```
Comment (eladb) [inline packages/@aws-cdk/aws-ec2/lib/vpc.ts]: Indicate what users should do if they want to use all AZs (even if it's "99")
