### PR TITLE
fix(appsync): resolver unable to set pipelineConfig

### LINKED ISSUE #6923: Pipeline config not showing up on synth output
Screen Shot 2020-03-21 at 3 54 21 PM

### Reproduction Steps

```js
const lambdaWithStash = `
#set($ctx.stash.newId = $util.autoId())
{"version": "2017-02-28", "operation": "Invoke", "payload": $util.toJson($ctx)}
`
const passThrough = `$util.toJson($ctx.result)`

export const resolverDefaults = {
  requestMappingTemplate: Appsync.MappingTemplate.fromString(lambdaWithStash),
  responseMappingTemplate: Appsync.MappingTemplate.fromString(passThrough),
}

// this == CDK.Stack
new Appsync.Resolver(this, 'pipeline', {
      ...resolverDefaults,
      api: Graphql, // Appsync.GraphQLApi
      typeName: 'Conversation',
      fieldName: 'messages',
      pipelineConfig: {
        functions: ['lambda1', 'lambda2'] // valid lambdas on my Lambda console
      }
    })
```

### Error Log

see screnshot

### Environment

  - **CLI Version      :** 1.27.0 (build a98c0b3)
  - **Framework Version:** not sure what this means.
  - **OS               :** macos 10.14.6
  - **Language         :** typescript

### Other

I'm passing a valid, as per cdk types, `pipelineConfig` but it shows as undefined in my `cdk synth` output, causing deploy to fail even though my cdk code looks correct

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by BryanPan342**
**[ISSUE]**
`pipelineConfig` was be labeled as `undefined` while using the `Resolver` class instead of `createResolver`. Also, no way to set `kind` parameter for resolvers, so implemented that as well.

**[APPROACH]**
Created a property that takes `pipelineConfig` for `AppSync` functions. 

**[NOTE]**
`pipelineConfig` takes a string array for the name of `AppSync Functions` not `Lambda Functions`

Fixes #6923  

BREAKING CHANGE: `pipelineConfig` is now an array of `string` instead of `CfnResolver.PipelineConfigProperty` for usability.
- **appsync**: `pipelineConfig` parameter takes in `string []`

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-appsync/lib/resolver.ts [hunk 1]
```diff
@@ -15,10 +33,16 @@ export interface BaseResolverProps {
    * name of the GraphQL fiel din the given type this resolver is attached to
    */
   readonly fieldName: string;
+  /**
+   * type of resolver
+   *
+   * @default - UNIT resolver, single data source
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-appsync/lib/resolver.ts:39]:
```suggestion
   * @default ResolverType.UNIT
```

File: packages/@aws-cdk/aws-appsync/lib/resolver.ts [hunk 2]
```diff
@@ -15,10 +33,16 @@ export interface BaseResolverProps {
...
+   */
+  readonly kind?: ResolverType;
   /**
    * configuration of the pipeline resolver
    *
-   * @default - create a UNIT resolver
+   * @default - No pipelineConfig
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-appsync/lib/resolver.ts:45]:
```suggestion
   * @default - no pipeline resolver configuration
```

File: packages/@aws-cdk/aws-appsync/test/appsync.test.ts [hunk 3]
```diff
@@ -19,3 +19,27 @@ test('should not throw an Error', () => {
   // Then
   expect(when).not.toThrow();
 });
+
+test('should not throw an Error', () => {
+  // Given
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-appsync/test/appsync.test.ts:24]:
```suggestion
  // GIVEN
```

File: packages/@aws-cdk/aws-appsync/test/appsync.test.ts [hunk 4]
```diff
@@ -19,3 +19,27 @@ test('should not throw an Error', () => {
...
+  const stack = new cdk.Stack();
+
+  // When
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-appsync/test/appsync.test.ts:27]:
```suggestion
  // WHEN
```

File: packages/@aws-cdk/aws-appsync/test/appsync.test.ts [hunk 5]
```diff
@@ -19,3 +19,27 @@ test('should not throw an Error', () => {
...
+  const when = () => {
+    new appsync.Resolver(stack, 'resolver', {
+      api: api,
+      typeName: 'test',
+      fieldName: 'test2',
+      kind: appsync.ResolverType.PIPELINE,
+    });
+  };
+
+  // Then
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-appsync/test/appsync.test.ts:43]:
```suggestion
  // WHEN
```

File: packages/@aws-cdk/aws-appsync/test/appsync.test.ts [hunk 6]
```diff
@@ -19,3 +19,27 @@ test('should not throw an Error', () => {
   // Then
   expect(when).not.toThrow();
 });
+
+test('should not throw an Error', () => {
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-appsync/test/appsync.test.ts:23]: how about a more descriptive name that contain the conditions under test

File: packages/@aws-cdk/aws-appsync/test/appsync.test.ts [hunk 7]
```diff
@@ -19,3 +19,27 @@ test('should not throw an Error', () => {
...
+    new appsync.Resolver(stack, 'resolver', {
+      api: api,
+      typeName: 'test',
+      fieldName: 'test2',
+      kind: appsync.ResolverType.PIPELINE,
+    });
+  };
+
+  // Then
+  expect(when).not.toThrow();
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-appsync/test/appsync.test.ts:44]: can we verify the expected cloudformation template?

File: packages/@aws-cdk/aws-appsync/lib/resolver.ts [hunk 8]
```diff
@@ -18,9 +19,10 @@ export interface BaseResolverProps {
   /**
    * configuration of the pipeline resolver
    *
-   * @default - create a UNIT resolver
+   * @default - no pipeline resolver configuration
+   * An empty array | undefined sets resolver to be of kind, unit
    */
-  readonly pipelineConfig?: CfnResolver.PipelineConfigProperty | IResolvable;
+  readonly pipelineConfig?: string[];
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-appsync/lib/resolver.ts:25]: can this be more strongly typed? or is there a good reason why strings would be ideal?

this motivation for this is not covered in the commit body, can we add that?
it's especially important since this is a breaking change (also needs mention in commit body)

File: packages/@aws-cdk/aws-appsync/test/appsync.test.ts [hunk 9]
```diff
@@ -16,6 +16,78 @@ test('should not throw an Error', () => {
...
+  new appsync.Resolver(stack, 'resolver', {
+    api: api,
+    typeName: 'test',
+    fieldName: 'test2',
+  });
+
+  // THEN
+  expect(stack).toHaveResourceLike('AWS::AppSync::Resolver', {
+    Kind: 'UNIT',
+  });
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-appsync/test/appsync.test.ts:68]: worth verifying the `pipelineConfig` property as well since kind is driven by it

File: packages/@aws-cdk/aws-appsync/lib/resolver.ts (hunk 8 above)
Comment (BryanPan342) [reply packages/@aws-cdk/aws-appsync/lib/resolver.ts:25]: mmmm originally the type would have been this:
```
{
  functions: [...]
}
```

where the functions parameter just took a `string []` anyways, so changed it to just a `string []` after following Mitch's suggestion.

File: packages/@aws-cdk/aws-appsync/test/appsync.test.ts (hunk 9 above)
Comment (BryanPan342) [reply packages/@aws-cdk/aws-appsync/test/appsync.test.ts:68]: i'm a little confused?

if `pipelineConfig` is not configured, then `Kind` will be `UNIT`.. if `pipelineConfig` is configured then `Kind` will be `PIPELINE`.

File: packages/@aws-cdk/aws-appsync/lib/resolver.ts (hunk 8 above)
Comment (BryanPan342) [reply packages/@aws-cdk/aws-appsync/lib/resolver.ts:25]: also is this a breaking change?

the `pipelineConfig` prop doesn't actually do anything

Comment (shivlaks) [reply packages/@aws-cdk/aws-appsync/lib/resolver.ts:25]: do we have an issue for pipelineConfig doing nothing?

consider this:
* user has a  CDK application where they have specified a pipelineConfig of type `PipelineConfigProperty`

after this change, when they "upgrade" and just build.. it will fail saying the type is not a match. They have not changed anything about their application other than upgrade, but their build is now failing.

I think it would break which is why I'd consider this to be a breaking change. what do you think?

File: packages/@aws-cdk/aws-appsync/test/appsync.test.ts (hunk 9 above)
Comment (shivlaks) [reply packages/@aws-cdk/aws-appsync/test/appsync.test.ts:68]: i meant verify the resource itself rather than a subset of properties but you're right, this doesn't need to happen right now. marking it as resolved.

File: packages/@aws-cdk/aws-appsync/lib/resolver.ts (hunk 8 above)
Comment (MrArnoldPalmer) [reply packages/@aws-cdk/aws-appsync/lib/resolver.ts:25]: @shivlaks issue is here https://github.com/aws/aws-cdk/issues/6923

Flattening out the object is a convenience I think since it's the only property. Technically cfn could add more optional properties in the future and we would have to handle those but that happens either way.

I think the more strongly typed could be 'IFunction[]'. @BryanPan342 does that make sense to you?

**Comment by BryanPan342** [comment]
> I think typing to 'IFunction[]' for pipelineConfig probably makes sense. We can also change the property name to 'pipelineFunctions' to make it more descriptive and different to the L1 prop.

@MrArnoldPalmer so `pipelineConfig` doesn't take Lambda Functions. It takes AppSync's own type of Functions that use VTL to perform operations.

See documentation on `pipelineConfig` [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-resolver-pipelineconfig.html).

See documentation on `functionConfiguration` [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-functionconfiguration.html).

See documentation on `appsync:CreateFunction` [here](https://docs.aws.amazon.com/appsync/latest/APIReference/API_CreateFunction.html).

I opened up an issue #9092 for a feature request for AppSync function creation. Currently you can make an L1 version of it. But the `pipelineConfg` prop only takes a name of a AppSync Function.
