### PR TITLE
fix(custom-resources): cannot set logging for state machine generated in CompleteHandler

### LINKED ISSUE #27283: custom resources: Generated step function generates finding due to missing logging
### Describe the bug

When custom resources with provider framework has a completedHandler function it generates a aws step function for polling for completion with a configured interval and total timeout. 

This generated step function however has no logging configuration. Which causes the [StepFunctions.1](https://docs.aws.amazon.com/securityhub/latest/userguide/stepfunctions-controls.html#stepfunctions-1) rule from the [AWS Foundational Security Best Practices (FSBP) standard](https://docs.aws.amazon.com/securityhub/latest/userguide/fsbp-standard.html) set to be triggered. 

This is due to the missing logging configuration. The provider construct however also does not provide any option to configure this logging.

### Expected Behavior

The provider construct adds logging by default following the foundational best practice and/or allows this to be configured.

### Current Behavior

The provider construct does not add logging configuration on step function nor does it allow for it to be configured through construct props. 

### Reproduction Steps

Enable StepFunctions.1 rule.
Create stack with custom resource with both evenHandler and isCompleteHandler to trigger generation of state machine.
Deploy generated template
This template should triggger the rule due to missing logging configuration

### Possible Solution

- Add logging configuration by default (with logRetention from props if provided)
- And/or allow for loggroup (configuration) to be provided to provider construct for use in state machine.

### Additional Information/Context

_No response_

### CDK CLI Version

2.96.0

### Framework Version

_No response_

### Node.js Version

18

### OS

Ubuntu 20.04

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by go-to-k**
This PR fixes the case that `StateMachine` generated for `CompleteHandler` in `Provider` cannot set logging.

Closes #27283.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts [hunk 1]
```diff
@@ -49,6 +92,32 @@ export class WaiterStateMachine extends Construct {
...
+          'logs:DeleteLogDelivery',
+          'logs:ListLogDeliveries',
+          'logs:PutLogEvents',
+          'logs:PutResourcePolicy',
+          'logs:DescribeResourcePolicies',
+          'logs:DescribeLogGroups',
+        ],
+        resources: ['*'],
+      }));
+    }
```
Comment (go-to-k) [inline packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts:119]: `The following is an example policy you can use to configure your permissions. As shown in the following example, you need to specify * in the Resource field because CloudWatch API actions, such as CreateLogDelivery and DescribeLogGroups, don't support [Resource types defined by Amazon CloudWatch Logs](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazoncloudwatchlogs.html#amazoncloudwatchlogs-resources-for-iam-policies).`

https://docs.aws.amazon.com/step-functions/latest/dg/cw-logs.html#cloudwatch-iam-policy

**Comment by go-to-k** [comment]
I will fix the build errors.

```
error: [awslint:docs-public-apis:aws-cdk-lib.custom_resources.WaiterStateMachine.stateMachineArn] Public API element must have a docstring 
error: [awslint:docs-public-apis:aws-cdk-lib.custom_resources.WaiterStateMachine.grantStartExecution] Public API element must have a docstring
error: [awslint:docs-public-apis:aws-cdk-lib.custom_resources.WaiterStateMachineLogOptions] Public API element must have a docstring 
error: [awslint:docs-public-apis:aws-cdk-lib.custom_resources.WaiterStateMachineProps] Public API element must have a docstring 
Error: /Users/goto/pc/github/aws-cdk/tools/@aws-cdk/cdk-build-tools/bin/cdk-awslint exited with error code 1
```

File: packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts [hunk 2]
```diff
@@ -49,6 +97,32 @@ export class WaiterStateMachine extends Construct {
...
+          'logs:GetLogDelivery',
+          'logs:UpdateLogDelivery',
+          'logs:DeleteLogDelivery',
+          'logs:ListLogDeliveries',
+          'logs:PutLogEvents',
+          'logs:PutResourcePolicy',
+          'logs:DescribeResourcePolicies',
+          'logs:DescribeLogGroups',
+        ],
+        resources: ['*'],
```
Comment (go-to-k) [inline packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts:122]: `The following is an example policy you can use to configure your permissions. As shown in the following example, you need to specify * in the Resource field because CloudWatch API actions, such as CreateLogDelivery and DescribeLogGroups, don't support [Resource types defined by Amazon CloudWatch Logs](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazoncloudwatchlogs.html#amazoncloudwatchlogs-resources-for-iam-policies).`

https://docs.aws.amazon.com/step-functions/latest/dg/cw-logs.html#cloudwatch-iam-policy

**Comment by go-to-k** [comment]
Some integ tests failed because the errors occurred in `ProviderframeworkonEvent` logs in an eks module.

The `outbound.js` may or may not indeed be in the assets directory. Even if it is there, it sometimes fails. Some integ tests succeed.

```
2023-09-29T22:24:44.332Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module './outbound'\nRequire stack:\n- /var/task/cfn-response.js\n- /var/task/framework.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module './outbound'",
        "Require stack:",
        "- /var/task/cfn-response.js",
        "- /var/task/framework.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1061:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1093:21)",
        "    at async start (file:///var/runtime/index.mjs:1256:23)",
        "    at async file:///var/runtime/index.mjs:1262:1"
    ]
}
```

File: packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/Dockerfile [hunk 3]
```diff
@@ -1,4 +1,4 @@
-FROM  --platform=linux/amd64 node:18-alpine3.13
```
Comment (go-to-k) [inline packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/Dockerfile:1]: `node:18-alpine3.13` image is no longer accessible and has been renewed.

File: packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/package-lock.json [hunk 4]
```diff
@@ -6,7 +6,7 @@
     "": {
       "name": "eks-service-account-sdk-call-integ-test",
       "dependencies": {
-        "@aws-sdk/client-s3": "^3.408.0"
```
Comment (go-to-k) [inline packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/package-lock.json:9]: I updated package-lock.json since it was not updated.

File: packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/Dockerfile [hunk 5]
```diff
@@ -1,4 +1,4 @@
...
+FROM --platform=linux/amd64 node:18-alpine3.17
```
Comment (go-to-k) [inline packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/Dockerfile:1]: `node:18-alpine3.13` image is no longer accessible.

Comment (go-to-k) [inline packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/Dockerfile:1]: changed because `node:18-alpine3.13` image is no longer accessible.

File: packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts [hunk 6]
```diff
@@ -49,6 +99,34 @@ export class WaiterStateMachine extends Construct {
...
+      }));
+    }
```
Comment (go-to-k) [inline packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts:128]: The doc suggests using a wildcard in the Resource.

```
The following is an example policy you can use to configure your permissions. As shown in the following example, you need to specify * in the Resource field because CloudWatch API actions, such as CreateLogDelivery and DescribeLogGroups, don't support [Resource types defined by Amazon CloudWatch Logs](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazoncloudwatchlogs.html#amazoncloudwatchlogs-resources-for-iam-policies).
```

https://docs.aws.amazon.com/step-functions/latest/dg/cw-logs.html#cloudwatch-iam-policy

File: packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts [hunk 7]
```diff
@@ -126,6 +126,25 @@ export interface ProviderProps {
...
+   * @default - no log options
+   */
+  readonly waiterStateMachineLogOptions?: WaiterStateMachineLogOptions;
+
+  /**
+   * Disable logging for `WaiterStateMachine` with `isCompleteHandler` in the provider.
+   *
+   * This property must not be used if `isCompleteHandler` is not specified.
+   *
+   * @default false
```
Comment (lpizzinidev) [inline packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts:145]:
```suggestion
  /**
   * Whether logging for the waiter state machine is disabled.
   *
   * @default - false
```

File: packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts [hunk 8]
```diff
@@ -126,6 +126,25 @@ export interface ProviderProps {
...
    */
   readonly providerFunctionEnvEncryption?: kms.IKey;
+
+  /**
+   * Log options for `WaiterStateMachine` with `isCompleteHandler` in the provider.
+   *
+   * This property must not be used if `isCompleteHandler` is not specified or
+   * `disableWaiterStateMachineLogging` is true.
+   *
+   * @default - no log options
```
Comment (lpizzinidev) [inline packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts:136]:
```suggestion

  /**
   * Defines what execution history events of the waiter state machine are logged and where they are logged.
   *
   * @default - A default log group will be created if logging for the waiter state machine is enabled.
```

File: packages/aws-cdk-lib/custom-resources/test/provider-framework/provider.test.ts [hunk 9]
```diff
@@ -180,6 +181,11 @@ test('if isComplete is specified, the isComplete framework handler is also inclu
   new cr.Provider(stack, 'MyProvider', {
     onEventHandler: handler,
     isCompleteHandler: handler,
+    waiterStateMachineLogOptions: {
+      includeExecutionData: true,
+      level: LogLevel.ALL,
+    },
+    disableWaiterStateMachineLogging: false,
```
Comment (lpizzinidev) [inline packages/aws-cdk-lib/custom-resources/test/provider-framework/provider.test.ts:188]:
```suggestion
```
Redundant.
Can you please add a unit test for `disableWaiterStateMachineLogging: true` and modify the `hasResourceProperties('AWS::StepFunctions::StateMachine'` of one of the above to verify that `LoggingConfiguration` is set by default?

File: packages/aws-cdk-lib/custom-resources/test/provider-framework/waiter-state-machine.test.ts [hunk 10]
```diff
@@ -78,6 +104,77 @@ describe('state machine', () => {
...
+      backoffRate,
+      interval,
+      maxAttempts,
+      disableLogging: true,
+    });
+
+    // THEN
+    const roleId = 'statemachineRole52044F93';
+    Template.fromStack(stack).resourceCountIs('AWS::Logs::LogGroup', 0);
     Template.fromStack(stack).hasResourceProperties('AWS::IAM::Policy', {
```
Comment (lpizzinidev) [inline packages/aws-cdk-lib/custom-resources/test/provider-framework/waiter-state-machine.test.ts:178]:
```suggestion
```
`Template.fromStack(stack).resourceCountIs('AWS::Logs::LogGroup', 0);` is enough for this test case.

**Review by lpizzinidev — CHANGES_REQUESTED** [review]
Thanks 👍
The implementation looks correct.
Some adjustments are needed in my opinion.
Also, I don't see an integration test for a provider with all 3 attributes of `waiterStateMachineLogOptions` parameter set, can you please add it?

File: packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts [hunk 11]
```diff
@@ -75,18 +153,34 @@ export class WaiterStateMachine extends Construct {
...
+        Level: props.logOptions?.level ?? LogLevel.ERROR,
+      },
+    } : undefined;
+
     const resource = new CfnResource(this, 'Resource', {
       type: 'AWS::StepFunctions::StateMachine',
       properties: {
         DefinitionString: definition,
         RoleArn: role.roleArn,
+        ...logOptions,
```
[the remark this answers is not in the document]
Comment (go-to-k) [reply packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts:173]: Thanks, I will change like this.

However I will use `if (disableLogging) return undefined;` instead of `if (!logOptions || disableLogging) return undefined;`. Because it needs to create logs and policies by default even if `logOptions` is not specified, according to this issue.

File: packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts [hunk 12]
```diff
@@ -181,6 +208,10 @@ export class Provider extends Construct implements ICustomResourceProvider {
     const onEventFunction = this.createFunction(consts.FRAMEWORK_ON_EVENT_HANDLER_NAME, props.providerFunctionName);
 
     if (this.isCompleteHandler) {
+      if (props.disableWaiterStateMachineLogging && props.waiterStateMachineLogOptions) {
+        throw new Error('waiterStateMachineLogOptions must not be used if disableWaiterStateMachineLogging is true');
+      }
+
```
[the remark this answers is not in the document]
Comment (go-to-k) [reply packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts:214]: Actually, that's what I was wondering too. I think I'll change it to what it says.

File: packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts (hunk 11 above)
[the remark this answers is not in the document]
Comment (go-to-k) [reply packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts:173]: And I think a return value type of the method cannot be `CfnStateMachine.LoggingConfigurationProperty`.

Because `AWS::StepFunctions::StateMachine` is created by not L1 Construct for `StateMachine` but `CfnResource`.

So I will return by not specifying type for now.

https://github.com/aws/aws-cdk/pull/27310/files#diff-ba99cb0b24f721e7bd6405b5f84ba44cd64f95932fa1f0974d7676855680a25bR168-R172

[the remark this answers is not in the document]
Comment (go-to-k) [reply packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts:173]: Or how about using `CfnStateMachine` instead of `CfnResource` as follows?

```ts
    const resource = new CfnStateMachine(this, 'Resource', {
      definitionString: definition,
      roleArn: role.roleArn,
      loggingConfiguration: this.renderLoggingConfiguration(role, props.logOptions, props.disableLogging),
    });
```

File: packages/aws-cdk-lib/custom-resources/test/provider-framework/provider.test.ts (hunk 9 above)
Comment (go-to-k) [reply packages/aws-cdk-lib/custom-resources/test/provider-framework/provider.test.ts]: I changed, please see [them](https://github.com/aws/aws-cdk/pull/27310/commits/3ebccbd1d2cc5a4ed06c89582e618ff1c438547c#diff-f4e9d2a297a5917954bf071f5007abf62375eaff321e3f9380576ade2e5aafb1R265-R301).

**Comment by go-to-k** [comment]
> Also, I don't see an integration test for a provider with all 3 attributes of waiterStateMachineLogOptions parameter set, can you please add it?

OH, it sure seems not. I will add it!

**Comment by go-to-k** [comment]
> > Also, I don't see an integration test for a provider with all 3 attributes of waiterStateMachineLogOptions parameter set, can you please add it?

> OH, it sure seems not. I will add it!

It seems to be in the `aws-rds/test/integ.cluster-snapshot.ts`.

https://github.com/aws/aws-cdk/pull/27310/files#diff-978d5beb456b794b6198b5707680a6251e6e93b72cbe8e2bd8f1ceddba529f3eR111-R115

But this is confusing, so I added a new test.

https://github.com/aws/aws-cdk/pull/27310/commits/494e381c3a6eb91aa38ecf95f240d7a48bc39938

I have now made corrections to all the reviews and ask that you review them again.

**Comment by go-to-k** [comment]
@lpizzinidev 

I have now made corrections to all the reviews and ask that you review them again.

File: packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts [hunk 13]
```diff
@@ -1,8 +1,39 @@
...
+   * The log group where the execution history events will be logged.
+   *
+   * @default - a new log group will be created
+   */
+  readonly destination?: ILogGroup;
+
+  /**
+   * Determines whether execution data is included in your log.
+   *
+   * @default false
```
Comment (lpizzinidev) [inline packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts:22]:
```suggestion
   * @default - false
```

File: packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts [hunk 14]
```diff
@@ -1,8 +1,39 @@
...
+   */
+  readonly includeExecutionData?: boolean;
+
+  /**
+   * Defines which category of execution history events are logged.
+   *
+   * @default ERROR
```
Comment (lpizzinidev) [inline packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts:29]:
```suggestion
   * @default - ERROR
```

File: packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts (hunk 11 above)
[the remark this answers is not in the document]
Comment (lpizzinidev) [reply packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts]: I think that the current implementation should be fine.
Thanks for the clarification and the adjustment on the `if` condition.

File: packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/package-lock.json (hunk 4 above)
Comment (lpizzinidev) [reply packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/package-lock.json:9]: I saw that you opened a separate [PR](https://github.com/aws/aws-cdk/pull/27686) for this, which is great.
If the build does not fail can you remove the changes to this and the corresponding Dockerfile so we can keep them separate?

**Review by lpizzinidev — CHANGES_REQUESTED** [review]
Thanks for the changes 👍
Just a super-minor adjustment on documentation and a question on the edited Dockerfile.

File: packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/package-lock.json (hunk 4 above)
Comment (go-to-k) [reply packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/package-lock.json:9]: Actually, the build fails with the original implementation. I'm not sure if this issue will be merged, so I created another PR. What should we do?

Comment (lpizzinidev) [reply packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/package-lock.json:9]: Ok, just align the node version to `node:18-alpine3.18` here as well so if this gets merged the other one can just be closed.

**Comment by lpizzinidev** [comment]
@go-to-k https://github.com/aws/aws-cdk/pull/27310#discussion_r1374737603

File: packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/package-lock.json (hunk 4 above)
Comment (go-to-k) [reply packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/sdk-call-integ-test-docker-app/app/package-lock.json:9]: Yes, I changed it to `node:18-alpine3.18`.

**Comment by go-to-k** [comment]
@lpizzinidev 

Thanks, I changed that. Please review again.

https://github.com/aws/aws-cdk/pull/27310#discussion_r1375580693

**Review by lpizzinidev — APPROVED** [review]
Looks good to me 👍

File: packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts [hunk 15]
```diff
@@ -75,23 +123,61 @@ export class WaiterStateMachine extends Construct {
       },
     });
 
-    const resource = new CfnResource(this, 'Resource', {
-      type: 'AWS::StepFunctions::StateMachine',
-      properties: {
-        DefinitionString: definition,
-        RoleArn: role.roleArn,
-      },
+    const resource = new CfnStateMachine(this, 'Resource', {
```
Comment (kaizencc) [inline packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts:126]: We previously used `CfnResource` here because we did not want to depend on `aws-stepfunctions` module (back in CDK v1 where individual modules were released. Now that they are both part of `aws-cdk-lib`, this change is ok. But there are comments on line 80 that need to be updated to reflect this. I would document that we previously used `CfnResource` to avoid depending on `aws-stepfunctions`, but now it is okay.

File: packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts [hunk 16]
```diff
@@ -75,23 +123,61 @@ export class WaiterStateMachine extends Construct {
...
   }
+
+  private renderLoggingConfiguration(
+    role: Role,
+    logOptions?: LogOptions,
+    disableLogging?: boolean,
+  ): CfnStateMachine.LoggingConfigurationProperty | undefined {
+    if (disableLogging) return undefined;
+
+    // https://docs.aws.amazon.com/step-functions/latest/dg/cw-logs.html#cloudwatch-iam-policy
```
Comment (kaizencc) [inline packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts:154]: Thanks for this link. Let's also copy in the important piece of information from this link: 

```ts
// You need to specify `*` in the Resource field because CloudWatch API actions, such as CreateLogDelivery and DescribeLogGroups, don't support Resource types defined by Amazon CloudWatch Logs.
```

**Review by kaizencc — DISMISSED** [review]
Thanks for the lengthy review @lpizzinidev and for waiting patiently @go-to-k. Sorry for the delay. I just have two documentation comments and then I think we're good to go!

**Comment by go-to-k** [comment]
@kaizencc 

Thanks for your review! I fixed.

**Review by kaizencc — APPROVED** [review]
Thanks @go-to-k!

**Comment by ashleydaley** [comment]
@kaizencc @go-to-k  Hit guys, before I raise an issue, I want to know if this is expected with this PR. We are getting problems with replication of DynamoDB table which creates a state machine, however since this change went in we are getting the following error and breaking our pipelines on existing resources:

"Invalid Logging Configuration: The CloudWatch Logs Resource Policy size was exceeded. We suggest prefixing your CloudWatch log group name with /aws/vendedlogs/states/. (Service: AWSStepFunctions; Status Code: 400; Error Code: InvalidLoggingConfiguration; Request ID: 4ba96f98-4be5-450c-a069-3d4cbf93271a; Proxy: null)"

If this is a state machine log group, should it not be prefixed with /aws/vendedlogs/states/ as per the suggestion from the error message? We normally prefix all of our manually created state machines log groups as such
