### PR TITLE
fix(cfn-include): allow parameters to be replaced across nested stacks

### LINKED ISSUE #9838: [cfn-include] `parameters` don't work with nested stacks
The [`parameters` property in `CfnIncludeProps`](https://github.com/aws/aws-cdk/blob/dfe2c5c665a5662972098415e713d73e742e93cd/packages/%40aws-cdk/cloudformation-include/lib/cfn-include.ts#L39-L39) doesn't work correctly when used in combination with the [`nestedStacks` property](https://github.com/aws/aws-cdk/blob/dfe2c5c665a5662972098415e713d73e742e93cd/packages/%40aws-cdk/cloudformation-include/lib/cfn-include.ts#L29-L29).

### PR DESCRIPTION
**Pull request by comcalvi**
Fixes #9838

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts [hunk 1]
```diff
@@ -514,6 +514,7 @@ export class CfnInclude extends core.CfnElement {
     const template = new CfnInclude(nestedStack, nestedStackId, {
       templateFile: propStack.templateFile,
       nestedStacks: propStack.nestedStacks,
+      parameters: propStack.parameters,
```
Comment (skinny85) [inline packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts:517]: How about we get rid of this error-prone plucking method completely, and do:

```ts
    const template = new CfnInclude(nestedStack, nestedStackId, this.nestedStacksToInclude[nestedStackId]);
```

File: packages/@aws-cdk/cloudformation-include/test/nested-stacks.test.ts [hunk 2]
```diff
@@ -611,6 +611,43 @@ describe('CDK Include', () => {
...
+              "TemplateURL": "https://cfn-templates-set.s3.amazonaws.com/grandchild-import-stack.json",
+              "Parameters": {
+                // not a reference, so it isn't replaced
+                "MyBucketParameter": "some-other-bucket-name",
+              },
+            },
+          },
+        },
+      });
+    });
```
Comment (skinny85) [inline packages/@aws-cdk/cloudformation-include/test/nested-stacks.test.ts:650]: Missing assertion from the parent stack that `MyBucketParameter` is no longer passed to `ChildStack`.

**Comment by skinny85** [comment]
@njlynch can you take another look? I did a small refactoring of the code. Thanks!

**Review by njlynch — APPROVED** [review]
