### PR TITLE
fix(elasticloadbalancingv2-targets): add AlbListenerTarget for NLBs, deprecate AlbTarget due to ALB listener race conditions (#17208)

### LINKED ISSUE #17208: (aws-elasticloadbalancingv2): Cannot use a single application load balancer as a target for the network load balancer
### What is the problem?

I am trying to use a single application load balancer as a target for the network load balancer and I am defining this in CDK. Whenever I try to deploy this I get an errorMsg and the stack fails to deploy

### Reproduction Steps

Use the example code on https://docs.aws.amazon.com/cdk/api/latest/docs/aws-elasticloadbalancingv2-readme.html#using-application-load-balancer-targets  in a stack.

This is my code (adjusted example from above) that fails:
```ts
import * as cdk from '@aws-cdk/core';
import * as ec2 from '@aws-cdk/aws-ec2';
import * as iam from "@aws-cdk/aws-iam";
import * as elbv2 from '@aws-cdk/aws-elasticloadbalancingv2';
import * as targets from '@aws-cdk/aws-elasticloadbalancingv2-targets';
import * as ecs from '@aws-cdk/aws-ecs';
import * as patterns from '@aws-cdk/aws-ecs-patterns';

/**
 * Test Nbl to Alb CDK
 */
export class NblToAlbStack extends cdk.Stack {
    constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
        super(scope, id, props);

        //This is required due to company policy
        const boundary = iam.ManagedPolicy.fromManagedPolicyName(this, 'Boundary', 'Core-PermissionBoundaryPolicy');
        iam.PermissionsBoundary.of(this).apply(boundary);

        //Get existing VPC
        const coreVpc = ec2.Vpc.fromLookup(this, 'CoreVPC',{isDefault: false,vpcName: 'core-vpc' });

        const task = new ecs.FargateTaskDefinition(this, 'Task', { cpu: 256, memoryLimitMiB: 512 });
        task.addContainer('nginx', {
            image: ecs.ContainerImage.fromRegistry('public.ecr.aws/nginx/nginx:latest'),
            portMappings: [{ containerPort: 80 }],
        });

        const svc = new patterns.ApplicationLoadBalancedFargateService(this, 'Service', {
            vpc: coreVpc,
            taskDefinition: task,
            publicLoadBalancer: false,
        });

        const nlb = new elbv2.NetworkLoadBalancer(this, 'Nlb', {
            vpc:coreVpc,
            crossZoneEnabled: true,
            internetFacing: true,
        });

        const listener = nlb.addListener('listener', { port: 80 });
        const albTarget = new targets.AlbTarget(svc.loadBalancer, 80);

        listener.addTargets('Targets', {
            targets: [albTarget],
            port: 80,
        });

        new cdk.CfnOutput(this, 'NlbEndpoint', { value: `http://${nlb.loadBalancerDnsName}`})

    }
}
```
### What did you expect to happen?

I expected stack to de deployed OK.

### What actually happened?
```
Failed resources:
 10:37:47 AM | CREATE_FAILED        | AWS::ElasticLoadBalancingV2::TargetGroup  | Nlb/listener/TargetsGroup (NlblistenerTargetsGroupDD2A3CB0) If the target type is ALB, the target must have at least one listener that matches the target group port or any specified port overrides (Service: AmazonElasticLoadBalancing; Status Code: 400; Error Code: ValidationError; Request ID: 671fe9d5-e9af-4652-aee7-467e682fcdfa; Proxy: null)
        new TargetGroupBase (/Users/ad03490/projects/bitbucket/cdk-document-converter/node_modules/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-target-group.ts:129:21)
        \_ new NetworkTargetGroup (/Users/ad03490/projects/bitbucket/cdk-document-converter/node_modules/@aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-target-group.ts:49:5)
        \_ NetworkListener.addTargets (/Users/ad03490/projects/bitbucket/cdk-document-converter/node_modules/@aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-listener.ts:160:19)
        \_ new NblToAlbStack (/Users/ad03490/projects/bitbucket/cdk-document-converter/lib/nbl-to-alb-stack.ts:42:18)
        \_ Object.<anonymous> (/Users/ad03490/projects/bitbucket/cdk-document-converter/bin/cdk-document-converter.ts:23:23)
        \_ Module._compile (node:internal/modules/cjs/loader:1095:14)
        \_ Module.m._compile (/Users/ad03490/projects/bitbucket/cdk-document-converter/node_modules/ts-node/src/index.ts:1056:23)
        \_ Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
        \_ Object.require.extensions.<computed> [as .ts] (/Users/ad03490/projects/bitbucket/cdk-document-converter/node_modules/ts-node/src/index.ts:1059:12)
        \_ Module.load (node:internal/modules/cjs/loader:975:32)
        \_ Function.Module._load (node:internal/modules/cjs/loader:816:12)
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
        \_ main (/Users/ad03490/projects/bitbucket/cdk-document-converter/node_modules/ts-node/src/bin.ts:198:14)
        \_ Object.<anonymous> (/Users/ad03490/projects/bitbucket/cdk-document-converter/node_modules/ts-node/src/bin.ts:288:3)
        \_ Module._compile (node:internal/modules/cjs/loader:1095:14)
        \_ Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
        \_ Module.load (node:internal/modules/cjs/loader:975:32)
        \_ Function.Module._load (node:internal/modules/cjs/loader:816:12)
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
        \_ node:internal/main/run_main_module:17:47

 ❌  NblToAlbStack failed: Error: The stack named NblToAlbStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:305:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at prepareAndExecuteChangeSet (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:352:26)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:189:24)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:225:9)
The stack named NblToAlbStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
Error: The stack named NblToAlbStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:305:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at prepareAndExecuteChangeSet (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:352:26)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:189:24)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:225:9)
```

### CDK CLI Version

1.127.0 (build 0ea309a)

### Framework Version

_No response_

### Node.js Version

v16.4.2

### OS

 System Version:	macOS 11.5.2 (20G95)   Kernel Version:	Darwin 20.6.0

### Language

Typescript

### Language Version

Typescript Version 3.9.10

### Other information

_No response_

### PR DESCRIPTION
**Pull request by stm29**
### Issue # (if applicable)
Closes #17208 .

### Description of changes

- This PR replaces `AlbTarget` with `AlbListenerTarget`, allowing us to automatically add a dependency between the provided ALB listener and the associated NLB target group. Without such a dependency stacks may fail to deploy if the listener is not created when the target group attempts to be created.
- Also, As described - https://github.com/aws/aws-cdk/issues/17208#issuecomment-1681475590 , it will handle graceful deletion of resources.
### Description of how you validated changes
- Added UnitTests
- Ran integrationTests as below,
```
$ yarn integ aws-elasticloadbalancingv2-targets/test/integ.alb-listner-target.js --update-on-failed
```

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by stm29** [comment]
@paulhcsun , I am on my initial stages of my contribution, where should I reach out to get this reviewed by community?

**Review by mmuller88 — APPROVED** [review]
This looks great

File: packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts [hunk 1]
```diff
@@ -43,3 +51,37 @@ export class AlbTarget extends AlbArnTarget {
...
+    super(albListener.loadBalancer.loadBalancerArn, albListener.port);
+  }
+
+  private attach(targetGroup: elbv2.ITargetGroup): elbv2.LoadBalancerTargetProps {
+    targetGroup.node.addDependency(this.albListener);
+    return super._attach(targetGroup);
+  }
+
+  /**
+   * Register this alb target with a load balancer
```
Comment (msambol) [inline packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts:76]: nit: `Register this ALB target with a load balancer.`

File: packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts [hunk 2]
```diff
@@ -43,3 +51,37 @@ export class AlbTarget extends AlbArnTarget {
...
+   * Don't call this, it is called automatically when you add the target to a
+   * load balancer.
+   *
+   * This Adds Dependency on albLisner because creation of ALB Listner and NLB can vary during runtime.
+   * More Details on - https://github.com/aws/aws-cdk/issues/17208
+   */
+  public attachToNetworkTargetGroup(targetGroup: elbv2.INetworkTargetGroup): elbv2.LoadBalancerTargetProps {
+    return this.attach(targetGroup);
+  }
+}
```
Comment (msambol) [inline packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts:87]: nit: newline

File: packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts [hunk 3]
```diff
@@ -43,3 +51,37 @@ export class AlbTarget extends AlbArnTarget {
...
+    return super._attach(targetGroup);
+  }
+
+  /**
+   * Register this alb target with a load balancer
+   *
+   * Don't call this, it is called automatically when you add the target to a
+   * load balancer.
+   *
+   * This Adds Dependency on albLisner because creation of ALB Listner and NLB can vary during runtime.
```
Comment (msambol) [inline packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts:81]: spelling errors in this comment.

File: packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2-targets/test/integ.alb-listner-target.ts [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+    });
+  }
+}
+
+// EXPECT
+const stack = new ALBListenerStack(app, 'nlb-alb-listner-stack');
+new IntegTest(app, 'Integ', {
+  testCases: [stack],
+});
+app.synth();
```
Comment (msambol) [inline packages/@aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2-targets/test/integ.alb-listner-target.ts:36]: nit: newline

File: packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts [hunk 5]
```diff
@@ -32,8 +36,12 @@ export class AlbArnTarget implements elbv2.INetworkLoadBalancerTarget {
 }
 
 /**
- * A single Application Load Balancer as the target for load balancing.
- */
+  * A single Application Load Balancer as the target for load balancing.
+  * @deprecated Use AlbListenerTarget instead. This target does not automatically
```
Comment (msambol) [inline packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts:40]: nit: Use `AlbListenerTarget` instead.

File: packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts [hunk 6]
```diff
@@ -32,8 +36,12 @@ export class AlbArnTarget implements elbv2.INetworkLoadBalancerTarget {
...
+  * add a dependency between the ALB listener and resulting NLB target group, without
+  * which may cause stack deployments to fail if the NLB target group is provisioned
+  * before the listener has been fully created.
+  */
```
Comment (tmokmss) [inline packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts:44]: An alternative would be to keep using `AlbTarget` and set dependencies using [`ApplicationLoadBalancer.listeners`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancingv2.IApplicationLoadBalancer.html#listeners). Which do you think is better?

File: packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts [hunk 7]
```diff
@@ -43,3 +51,37 @@ export class AlbTarget extends AlbArnTarget {
...
+export class AlbListenerTarget extends AlbArnTarget {
+  /**
+   * Create a new ALB target.
+   * The associated target group will automatically have a dependency added
+   * against the ALB's listener.
+   *
+   * @param albListener The application load balancer listener to target.
+   */
+  constructor(private albListener: elbv2.ApplicationListener) {
+    super(albListener.loadBalancer.loadBalancerArn, albListener.port);
```
Comment (tmokmss) [inline packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts:67]: (memo) using `albListener.port` here seems a right thing to do. (previously it was not validated at all that a corresponding listener to the port exists) 

> the Application Load Balancer you choose from the list must have a listener on the same port as the target group you’re creating.
> https://docs.aws.amazon.com/elasticloadbalancing/latest/network/application-load-balancer-target.html

**Review by tmokmss — COMMENTED** [review]
Thanks for working on this! I (as a community reviewer) made some comments on an alternative approach. I'm not super familiar with NLB + ALB target, so sorry if my comments are irrelevant  (at least I read [this doc](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/application-load-balancer-target.html) 🙏).

File: packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts (hunk 6 above)
Comment (stm29) [reply packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts:44]: This is due to the same reason provided on this following PR - https://github.com/aws/aws-cdk/pull/17248#issue-1040439161

> While `AlbTarget` could have logic added to it to add dependencies, this would not work if the provided ALB doesn't have any items in its listener property (e.g. `new ApplicationListener(...)` instead of `alb.addListener(...)`)

Comment (tmokmss) [reply packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts:44]: Thanks, that makes sense.

Comment (tmokmss) [reply packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts:44]: @stm29 My concern was that this change will make imported ALBs not usable as a NLB target. But I found that they can still use `AlbArnTarget` for that purpose.  How about adding a comment like: `Use AlbListenerTarget instead or AlbArnTarget for an imported load balancer.`

File: packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts [hunk 8]
```diff
@@ -43,3 +51,37 @@ export class AlbTarget extends AlbArnTarget {
...
+ */
+export class AlbListenerTarget extends AlbArnTarget {
+  /**
+   * Create a new ALB target.
+   * The associated target group will automatically have a dependency added
+   * against the ALB's listener.
+   *
+   * @param albListener The application load balancer listener to target.
+   */
+  constructor(private albListener: elbv2.ApplicationListener) {
```
[the remark this answers is not in the document]
Comment (tmokmss) [reply packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts:66]: If adding IApplicationListener support requires lots of effort, I'm okay with the current api. (they can still use AlbArnTarget anyway.)

File: packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts (hunk 6 above)
Comment (stm29) [reply packages/aws-cdk-lib/aws-elasticloadbalancingv2-targets/lib/alb-target.ts:45]: @tmokmss , 
>My concern was that this change will make imported ALBs not usable as a NLB target

Got it

Modified comment as follows:
```
Use `AlbListenerTarget` instead or `AlbArnTarget` for an imported load balancer
```

**Review by tmokmss — APPROVED** [review]

**Review by TheRealAmazonKendra — DISMISSED** [review]
I do love a good deprecation. Thanks for your contribution!

**Comment by stm29** [comment]
@TheRealAmazonKendra , I Merged main - **branch** commits in this PR.
I did this because, it was alerting current branch is not in sync **unable to Merge**.

Can you **re-review** this?

**Comment by stm29** [comment]
@TheRealAmazonKendra , would you mind just **re-approving** this?

And regarding merging the changes, will you be merging this PR?, why because I did all these changes because I got confused with **mergify** messages...

**Review by shikha372 — DISMISSED** [review]

**Comment by shikha372** [comment]
@mergifyio update

**Comment by stm29** [comment]
@shikha372 seems there is permission issue, should I add some permission?

**Review by shikha372 — APPROVED** [review]
