### PR TITLE
fix(apigateway): move url property to RestApiBase

### LINKED ISSUE #27501: Cloudfront Origin does not support SpecRestApi
### Describe the bug

The `RestApiOrigin` constructor only supports `RestApi` and not `RestApiBase`. This means a API created via `SpecRestApi` cannot be used to create a Cloudfront origin.

### Expected Behavior

Passing an instance of `SpecRestApi` to `RestApiOrigin` should be accepted and create the origin.

### Current Behavior

When passing `SpecRestApi` to `RestApiOrigin` an error is generated

```
TypeError: type of argument rest_api must be aws_cdk.aws_apigateway.RestApi; got aws_cdk.aws_apigateway.SpecRestApi instead
```

### Reproduction Steps

1. Create a RestAPI from a OpenAPI spec file
2. Create a Cloudfront distribution that contains an API origin and use the RestAPI generated in step 1

### Possible Solution

Update `RestApiOrigin` constructor to accept `RestApiBase` for restApi

### Additional Information/Context

_No response_

### CDK CLI Version

2.96.0 (build e6322aa)

### Framework Version

_No response_

### Node.js Version

v18.17.1

### OS

MacOS

### Language

Python

### Language Version

3.11.4

### Other information

_No response_

### PR DESCRIPTION
**Pull request by hariprakash-j**
Moved the url property from RestApi class to the RestApiBase to have the url property on all derived class. This will fix the problem mentioned in the issue where SpecRestApi does not work with the RestApiOrigin construct.

PS. I could not perform the integration tests as the free tier on my personal account expired.

Closes #27501.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by hariprakash-j** [comment]
Exemption Request

I just moved the property to the base class, I am not sure what tests are required for this. If there is any thing that I can do for this please let me know.

**Comment by hariprakash-j** [comment]
@sumupitchayan Thanks for the help with the integration tests and I added the integ tests and the unit tests.

**Comment by hariprakash-j** [comment]
@sumupitchayan I was able to find a aws account with free tier to run the integ tests and generate the snapshots

File: packages/aws-cdk-lib/aws-cloudfront-origins/lib/rest-api-origin.ts [hunk 1]
```diff
@@ -35,7 +35,7 @@ export interface RestApiOriginProps extends cloudfront.OriginProps {
  */
 export class RestApiOrigin extends cloudfront.OriginBase {
 
-  constructor(restApi: apigateway.RestApi, private readonly props: RestApiOriginProps = {}) {
+  constructor(restApi: apigateway.RestApiBase, private readonly props: RestApiOriginProps = {}) {
```
Comment (sumupitchayan) [inline packages/aws-cdk-lib/aws-cloudfront-origins/lib/rest-api-origin.ts:38]: @hariprakash-j Can you explain the reasoning behind this change and why it is necessary?

Comment (hariprakash-j) [reply packages/aws-cdk-lib/aws-cloudfront-origins/lib/rest-api-origin.ts:38]: Earlier the url property was only in the class RestApi and the classes that extended it. The SpecRestApi class did not inherit from this class as it extended RestApiBase and thus caused an error when one tried to use it a SpecRestApi with RestApiOrigin . Now, however you can use any class that extends the RestApiBase since i have moved the url property to the to this class. This will fix the the issue that was outlined in the issue and prevent this from happening in any new RestApi construct as they will all inherit from the RestApiBase or a class that extends it.

Comment (hariprakash-j) [reply packages/aws-cdk-lib/aws-cloudfront-origins/lib/rest-api-origin.ts:38]: @sumupitchayan , let me know if I'm missing something here

File: packages/aws-cdk-lib/aws-apigateway/test/restapi.test.ts [hunk 2]
```diff
@@ -379,29 +379,29 @@ describe('restapi', () => {
...
-      ['https://',
-        { Ref: 'apiC8550315' },
-        '.execute-api.',
-        { Ref: 'AWS::Region' },
-        '.',
-        { Ref: 'AWS::URLSuffix' },
-        '/',
-        { Ref: 'apiDeploymentStageprod896C8101' },
-        '/']],
+        ['',
```
Comment (sumupitchayan) [inline packages/aws-cdk-lib/aws-apigateway/test/restapi.test.ts:382]: What are these new space changes? If this was a formatting change can you remove this?

Comment (hariprakash-j) [reply packages/aws-cdk-lib/aws-apigateway/test/restapi.test.ts:382]: @sumupitchayan , do you think i should do something here ?

**Review by sumupitchayan — DISMISSED** [review]

**Review by vinayak-kukreja — APPROVED** [review]

**Comment by vinayak-kukreja** [comment]
@Mergifyio update

**Review by vinayak-kukreja — APPROVED** [review]

**Comment by vinayak-kukreja** [comment]
@Mergifyio update
