### PR TITLE
fix(ec2): add `MachineImage` factory, document instance replacement

### LINKED ISSUE #5675: ec2: MachineImages that use SSM queries get unwantedly replaced on deployments
## General Issue

I currently have a CDK project with many stacks in them and the issue I am having is I have one stack that is a generic load balancer shared between applications and the other is an EC2 instance that is accessed through the load balancer. I am making a change to the load balancer but the CDK deploy function seems to run the deploy on any stacks that have resources referenced by my load balancer stack. The EC2 instance stack has no changes and when I run cdk diff on that stack it shows no changes but when I run deploy on the EC2 stack or on the load balancer stack which runs deploy on the EC2 stack it detects the AMI for the latest version of windows is different and tries to replace my instance. The issue is I deployed the EC2 stack back in November which for my region used AMI `ami-07d23537f44fe67c1` but now the latest version in my region is `ami-06eed5c2539ba3e74`. I am using the `ca-central-1` region.

I feel like this is a bug as I can't see why an EC2 instance should be replaced after deployment just because the latest AMI was updated.

### Environment

  - **CDK CLI Version:** 1.19.0
  - **Module Version:** 1.19.0
  - **OS:** macOS 10.15.2
  - **Language:** Typescript

### PR DESCRIPTION
**Pull request by rix0rrr**
Some MachineImages get updated automatically (causing unexpected
instance replacement), and some don't. Update the documentation to very
clearly note which image is which, and that using a particular type of
image may cause your instance to be replaced.

Also add a class with static factory functions to make an enum-like
pattern, to be in line with other places where the user has a choice
of implementations.

Fixes #5675.

Also note that VPC lookups are cached, which hopefully addresses #6025.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-ec2/lib/vpc.ts [hunk 1]
```diff
@@ -859,12 +859,14 @@ export class Vpc extends VpcBase {
...
-   *
    * Calling this method will lead to a lookup when the CDK CLI is executed.
    * You can therefore not use any values that will only be available at
    * CloudFormation execution time (i.e., Tokens).
+   *
+   * The VPC information will be cached in `cdk.context.json` and the same VPC
+   * will be used on future runs. To refresh the lookup, you will have to
+   * evict the value from the cache using the `cdk context` command. See
+   * https://docs.aws.amazon.com/cdk/latest/guide/context.html for more information.
    */
```
Comment (NetaNir) [inline packages/@aws-cdk/aws-ec2/lib/vpc.ts]: Much needed!
