### PR TITLE
 fix(codedeploy): DeploymentGroup's physical name not propagated to Application

### LINKED ISSUE #13337: (codedeploy.ServerDeploymentGroup): Creating ServerDeploymentGroup does not create Application implicitly
## :question: General Issue
I tried to create ServerDeploymentGroup and ran into this error -

> Error: Resolution error: Resolution error: Resolution error: Resolution error: Cannot use resource 'DeploymentGroupStack/my-app/Application' in a cross-environment fashion, the resource's physical name must be explicit set or use PhysicalName.GENERATE_IF_NEEDED.

Code - 

```typescript
new codedeploy.ServerDeploymentGroup(this, props.applicationName, {
         deploymentGroupName: PhysicalName.GENERATE_IF_NEEDED,
         ec2InstanceTags: new codedeploy.InstanceTagSet({
        'Name': [props.applicationName],
      }),
    })
```

To resolve this error I had to create Application first 

```typescript
const application = new codedeploy.ServerApplication(this, 'App', {
      applicationName: PhysicalName.GENERATE_IF_NEEDED,
    });

new codedeploy.ServerDeploymentGroup(this, props.applicationName, {
      deploymentGroupName: PhysicalName.GENERATE_IF_NEEDED,
      application: application,
      ec2InstanceTags: new codedeploy.InstanceTagSet({
        'Name': [props.applicationName],
      }),
    });
```

### Expected Result

I think doing this should automatically create the Application owning the Deployment Group also with PhysicalName.GENERATE_IF_NEEDED.

```typescript 
    new codedeploy.ServerDeploymentGroup(this, props.applicationName, {
      deploymentGroupName: PhysicalName.GENERATE_IF_NEEDED,
    });
```

Refer - [Discussion](https://github.com/aws/aws-cdk/discussions/13069#discussioncomment-420215) 
### Environment

  - **CDK CLI Version:**  1.89.0
  - **Module Version:**  1.89.0
  - **Node.js Version:** 12.16.1
  - **OS:**  Windows 10
  - **Language (Version):**  Typescript

### PR DESCRIPTION
**Pull request by BLasan**
fixes #13337

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by BLasan** [comment]
@skinny85 Please review

File: packages/@aws-cdk/aws-codedeploy/lib/server/deployment-group.ts [hunk 1]
```diff
@@ -269,7 +269,7 @@ export class ServerDeploymentGroup extends ServerDeploymentGroupBase {
       physicalName: props.deploymentGroupName,
     });
 
-    this.application = props.application || new ServerApplication(this, 'Application');
+    this.application = props.application || new ServerApplication(this, this.physicalName);
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-codedeploy/lib/server/deployment-group.ts:272]: This is not the right fix for this issue. The fix is that if the parent `DeploymentGroup` has a `PhysicalName.GENERATE_IF_NEEDED`, so should the `ServerApplication`.

The poster suggested as much under [Expected Result](https://github.com/aws/aws-cdk/issues/13337).

Also the title of this PR doesn't cover the change it's making. The title as written makes it sound as if no Application was created before, whereas now there is. This is not true though, an Application was already being created before. 

We generally also write the PR title in terms of things the user would care about, and specifically for fixes it describes the bug that is now fixed (users will see these titles in the CHANGELOG, so think about what would make sense to them when viewed there).

**Review by rix0rrr — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-codedeploy/lib/server/deployment-group.ts (hunk 1 above)
Comment (BLasan) [reply packages/@aws-cdk/aws-codedeploy/lib/server/deployment-group.ts]: @rix0rrr  Thanks for the review. I made the changes. Please have a look

**Review by rix0rrr — DISMISSED** [review]

File: packages/@aws-cdk/aws-codedeploy/lib/server/deployment-group.ts [hunk 2]
```diff
@@ -4,6 +4,7 @@ import * as ec2 from '@aws-cdk/aws-ec2';
 import * as iam from '@aws-cdk/aws-iam';
 import * as s3 from '@aws-cdk/aws-s3';
 import * as cdk from '@aws-cdk/core';
+import { isGeneratedWhenNeededMarker } from '@aws-cdk/core/lib/private/physical-name-generator';
```
[the remark this answers is not in the document]
Comment (BLasan) [reply packages/@aws-cdk/aws-codedeploy/lib/server/deployment-group.ts:7]: I initially tried `cdk.PhysicalName.GENERATE_IF_NEEDED` . But after going through the logic resides inside the resources.ts file, I came up with this logic :) I hope `name == PhysicalName.GENERATE_IF_NEEDED` would work fine. will changes that

**Comment by BLasan** [comment]
@rix0rrr Please review

File: packages/@aws-cdk/aws-codedeploy/test/server/test.deployment-group.ts [hunk 3]
```diff
@@ -28,6 +28,21 @@ export = {
       test.done();
     },
 
+    'creating an application with physical name if needed'(test: Test) {
+      const stack = new cdk.Stack();
+      new codedeploy.ServerDeploymentGroup(stack, 'MyDG', {
+        deploymentGroupName: cdk.PhysicalName.GENERATE_IF_NEEDED,
+      });
+
+      expect(stack).to(haveResource('AWS::CodeDeploy::DeploymentGroup', {
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-codedeploy/test/server/test.deployment-group.ts:37]: You need to be asserting something about the `AWS::CodeDeploy::Application`, not the DeploymentGroup.

**Review by rix0rrr — DISMISSED** [review]

File: packages/@aws-cdk/aws-codedeploy/test/server/test.deployment-group.ts (hunk 3 above)
Comment (BLasan) [reply packages/@aws-cdk/aws-codedeploy/test/server/test.deployment-group.ts:37]: Yuh, but there won't be a field called `ApplicationName` in the output. That fails the build.

Comment (rix0rrr) [reply packages/@aws-cdk/aws-codedeploy/test/server/test.deployment-group.ts:37]: Then the issue is not fixed.

Comment (BLasan) [reply packages/@aws-cdk/aws-codedeploy/test/server/test.deployment-group.ts:37]:
```
- Field ApplicationName missing in:
    {
      "Type": "AWS::CodeDeploy::Application",
      "Properties": {
        "ComputePlatform": "Server"
      }
    }
```
output for the test case with the resource type `AWS::CodeDeploy:;DeploymentGroup`. Same output will be received when the resource type of `can be created by explicitly passing an Application` test changed

File: packages/@aws-cdk/aws-codedeploy/test/server/test.deployment-group.ts [hunk 4]
```diff
@@ -28,6 +28,19 @@ export = {
...
     },
 
+    'creating an application with physical name if needed'(test: Test) {
+      const stack = new cdk.Stack();
+      new codedeploy.ServerDeploymentGroup(stack, 'MyDG', {
+        deploymentGroupName: cdk.PhysicalName.GENERATE_IF_NEEDED,
+      });
+
+      expect(stack).to(haveResource('AWS::CodeDeploy::Application', {
+        'ComputePlatform': 'Server',
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-codedeploy/test/server/test.deployment-group.ts:38]: We do need an `ApplicationName` provided here.

If it doesn't appear, then the fix is not sufficient. It may be the that the ServerApplication does not respect PhysicalNames, for example. 

Try and step through the code to see where the discrepancy between what we expect and what actually happens comes from.

**Review by rix0rrr — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-codedeploy/test/server/test.deployment-group.ts (hunk 4 above)
Comment (BLasan) [reply packages/@aws-cdk/aws-codedeploy/test/server/test.deployment-group.ts:38]: Can we give a custom name and check whether we'll be receiving the out as expected instead of a PhysicaName?

**Review by rix0rrr — APPROVED** [review]
