### PR TITLE
fix(aws-stepfunctions, aws-stepfunctions-tasks): missing suffix in fi…

### LINKED ISSUE #2937: fix(aws-stepfunctions, aws-stepfunctions-tasks): missing suffix ".$" in field names of reference paths
**Describe the bug**
The suffix ".$" is missing in the field "token" whose value is a reference path "$$.Task.Token" in the following unit test:
https://github.com/awslabs/aws-cdk/blob/ea10f0d141a48819ec0000cd7905feda993870a9/packages/%40aws-cdk/aws-stepfunctions-tasks/test/invoke-function.test.ts#L78
Users can create their state machine with such definition but runtime exception will be thrown because of the missing suffix when they start any execution. 

**Expected behavior**
All the fields with reference paths in the state machine definition should end with ".$". 
The payload field should look like:
```
"Payload": {
    "token.$": "$$.Task.Token"
}
```

**Reference**
https://states-language.net/spec.html

**Version:**
 - CDK Version: v0.35.0
 - Related Issue: #2686

### PR DESCRIPTION
**Pull request by wqzoww**
…eld names of reference paths

* add suffix ".$" for the fields whose values are reference paths, including json path and context object
* fix unit tests and integration test for lambda task

fixes #2937

----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
  - __Design__: For significant features, design document added to `design` folder
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-stepfunctions/lib/state-graph.ts [hunk 1]
```diff
@@ -101,7 +102,7 @@ export class StateGraph {
     public toGraphJson(): object {
         const states: any = {};
         for (const state of this.allStates) {
-            states[state.stateId] = state.toStateJson();
+            states[state.stateId] = FieldUtils.renderObject(state.toStateJson());
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-stepfunctions/lib/state-graph.ts]: I feel like this should be the responsibility of the individual tasks. It only makes sense in the `Parameters` field, no?

Comment (wqzoww) [reply packages/@aws-cdk/aws-stepfunctions/lib/state-graph.ts]: Yes, you are right. I forgot the reference path only applies for `Parameters` field, rather than the entire block of state.
