### PR TITLE
 fix(codebuild): remove oauthToken property from source 

### LINKED ISSUE #2199: GitHub source authentication works differently
In our GitHubSource, `oauthToken` is required, but it doesn't actually do anything.

You're supposed to authenticate the whole of CodeBuild against all of your repositories using OAuth in the console. Afterwards, you don't have to pass a token value, you just have to set auth-type to "OAUTH" and it'll work.

For reference, the following seems to work fine:

```ts
new GitHubSource({
      owner: 'rix0rrr',
      repo: 'somerepoihave',
      oauthToken: cdk.SecretValue.plainText(''),
 })
```

@skinny85, any clue?

### PR DESCRIPTION
**Pull request by Kaixiang-AWS**
Auth field should not be set since it's ignored by CodeBuild
https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ProjectSource.html#CodeBuild-Type-ProjectSource-auth

Refactored some unit tests as well

BREAKING CHANGE: customers who use GitHub, GitHubEnterprise or Bitbucket as source
will need to remove the oauthToken field as it's no longer available

Fixes #2199

----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-codebuild/lib/source.ts [hunk 1]
```diff
@@ -261,7 +251,6 @@ export class GitHubSource extends GitBuildSource {
 
   protected toSourceProperty(): any {
     return {
-      auth: { type: 'OAUTH', resource: this.oauthToken },
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-codebuild/lib/source.ts]: I don't think this is correct. I believe you still need to supply `auth: { type: 'OAUTH' }` here.

File: packages/@aws-cdk/aws-codebuild/README.md [hunk 2]
```diff
@@ -103,7 +100,7 @@ This source type can be used to build code from a BitBucket repository.
 
 ## Environment
 
-By default, projects use a small instance with an Ubuntu 14.04 image. You
+By default, projects use a small instance with an Ubuntu 18.04 image. You
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-codebuild/README.md]: If you want to update this, you will also need to update:

https://github.com/awslabs/aws-cdk/blob/huijbers/bump-jsii/packages/@aws-cdk/aws-codebuild/lib/project.ts#L944
https://github.com/awslabs/aws-cdk/blob/huijbers/bump-jsii/packages/@aws-cdk/aws-codebuild/lib/project.ts#L625

And add a new image here:

https://github.com/awslabs/aws-cdk/blob/huijbers/bump-jsii/packages/@aws-cdk/aws-codebuild/lib/project.ts#L1026

Comment (Kaixiang-AWS) [reply packages/@aws-cdk/aws-codebuild/README.md]: Sorry for not mentioning that in the PR. I have already pushed a commit to change the image, but forgot to update the documentation in the previous commit.

https://github.com/awslabs/aws-cdk/commit/87b1ea00a280157037b11a8bd7e580d7849ccd4a

File: packages/@aws-cdk/aws-codebuild/lib/source.ts (hunk 1 above)
Comment (skinny85) [reply packages/@aws-cdk/aws-codebuild/lib/source.ts]: @Kaixiang-AWS can you confirm whether the `auth: { type: 'OAUTH' }` is still required here, even without the Token?

Comment (Kaixiang-AWS) [reply packages/@aws-cdk/aws-codebuild/lib/source.ts]: I have updated the PR and added an integ test against github source to make sure it can deploy.

I can confirm that `auth` field is not required. There might be an issue with the doc. I will report it to the doc writer and ask him to update the doc.

**Comment by rix0rrr** [comment]
I think it would also be good to add an example of an ImportCredentials call. Can you add this to the README in a section title "Using GitHub repositories" or something similar?

```
aws codebuild import-source-credentials --server-type GITHUB --auth-type PERSONAL_ACCESS_TOKEN --token <token_value>
```
