### PR TITLE
fix(stepfunctions): the retry field in CustomState is not iterable

### LINKED ISSUE #29274: aws-stepfunctions: state.Retry is not iterable
### Describe the bug

When creating a CustomState within a state machine, and specifying the retry behaviour within the inline definition, we get back an error saying `state.Retry is not iterable`. However, adding the retry behaviour separately with `.addRetry` seems to fix this issue. I strongly suspects this is linked to the following PR #28793 

### Expected Behavior

The state machine should create successfully

### Current Behavior

Throws
```
TypeError: state.Retry is not iterable
    at CustomState.toStateJson
```

### Reproduction Steps

Creating a state machine with the following state

```        
const myLambdaState: sfn.CustomState = new sfn.CustomState(this, 'Call Lambda', {
            stateJson: {
                Type: "Task",
                Resource: "arn:aws:states:::lambda:invoke",
                OutputPath: "$.Payload",
                Parameters: {
                    'Payload.$': "$",
                    "FunctionName": "arn:aws:lambda:us-east-1:<<ACCOUNT>>:function:print1:$LATEST"
                },
                Retry: [
                    {
                        "ErrorEquals": [
                            "Lambda.ServiceException",
                            "Lambda.AWSLambdaException",
                            "Lambda.SdkClientException",
                            "Lambda.TooManyRequestsException"
                        ],
                        "IntervalSeconds": 1,
                        "MaxAttempts": 3,
                        "BackoffRate": 2
                    }
                ],
                Catch: [
                    {
                        ErrorEquals: [
                            "States.ALL"
                        ],
                        Next: "fail.id"
                    }
                ]
                ,
            }
        });
```

However, doing the following works:
```
      const success: sfn.Succeed = new sfn.Succeed(this, 'Success Name');
        const fail: sfn.Fail = new sfn.Fail(this, 'Fail Name');

        const myLambdaState: sfn.CustomState = new sfn.CustomState(this, 'Call Lambda', {
            stateJson: {
                Type: "Task",
                Resource: "arn:aws:states:::lambda:invoke",
                OutputPath: "$.Payload",
                Parameters: {
                    'Payload.$': "$",
                    "FunctionName": "arn:aws:lambda:us-east-1:<<ACCOUNT-ID>>:function:print1:$LATEST"
                }
            }
        });
        myLambdaState.addRetry({
            maxAttempts: 1,
            maxDelay: cdk.Duration.seconds(5),
            jitterStrategy: sfn.JitterType.FULL,
        });

        myLambdaState.addCatch(fail, {
            errors: ['States.ALL']
        }
        )
        myLambdaState.next(success);
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.128.0

### Framework Version

_No response_

### Node.js Version

v21.6.2

### OS

Mac 14.3.1

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by abdelnn**
### Issue # (if applicable)

Closes #29274 

### Reason for this change

CDK users were unable to specify their retry strategy if it was specified inline in their ASL state machine definition

### Description of changes

Checks if the state definition has an inline retry policy defined. If it does, add it to the existing strategy defined using `addRetry` (if there is one defined, this is where it was failing before)

### Description of how you validated changes

Added unit and integration tests

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-stepfunctions/lib/states/custom-state.ts [hunk 1]
```diff
@@ -76,7 +76,7 @@ export class CustomState extends State implements IChainable, INextable {
 
     // merge the Retry filed defined in the stateJson into the state
```
Comment (lpizzinidev) [inline packages/aws-cdk-lib/aws-stepfunctions/lib/states/custom-state.ts:77]:
```suggestion
    // merge the Retry field defined in the stateJson into the state
```

**Review by lpizzinidev — APPROVED** [review]
Thanks 👍

**Review by aaythapa — APPROVED** [review]
