### PR TITLE
fix(apigatewayv2): cyclic dependency between HttpApi and the lambda function

### LINKED ISSUE #9075: [apigatewayv2, lambda] Cyclic dependency between Lambda and HttpGateway
Trying to have lambda in a separate stack than the httpgateway results in a cyclic dependency.

Similar issues fixed earlier: https://github.com/aws/aws-cdk/pull/4010

### Reproduction Steps

aws.ts
```

#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from '@aws-cdk/core';
import { HttpGatewayStack } from '../lib/http-gateway-stack';
import LambdaStack from '../lib/lambda-stack'

const app = new cdk.App();
const lambdaStack = new LambdaStack(app, 'ApiLambdaStack')

new HttpGatewayStack(app, 'ApiHttpGatewayStack', {
  handler: lambdaStack.function
});
```

Lambda Stack:

```
import * as cdk from '@aws-cdk/core'
import * as lambda from '@aws-cdk/aws-lambda';
import * as path from 'path';

export default class LambdaStack extends cdk.Stack {
  public readonly function: lambda.Function

  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props)

    this.function = new lambda.Function(this, 'ApiLambda', {
      runtime: lambda.Runtime.NODEJS_12_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../api')),
    });
  }
}
```

HttpGatewayStack:

```
import * as cdk from '@aws-cdk/core'
import * as httpGateway from '@aws-cdk/aws-apigatewayv2'
import * as lambda from '@aws-cdk/aws-lambda'

export class HttpGatewayStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: cdk.StackProps & {
    handler: lambda.Function,
  }) {
    super(scope, id, props)

    const api = new httpGateway.HttpApi(this, 'Api', {
      defaultIntegration: new httpGateway.LambdaProxyIntegration({
        handler: props.handler
      }),
    })

  }
}

```
### Error Log

Error: 'ApiLambdaStack' depends on 'ApiHttpGatewayStack' (ApiLambdaStack -> ApiHttpGatewayStack/Api/Resource.Ref). Adding this dependency (ApiHttpGatewayStack -> ApiLambdaStack/ApiLambda/Resource.Arn) would create a cyclic reference.

### Environment

  - **CLI Version    1.51 
  - **Framework Version: 1.51
  - **Node.js Version: v12.18.2
  - **OS              : mac catalina
  - **Language (Version): typescript 3.9

### PR DESCRIPTION
**Pull request by nija-at**
As part of Lambda proxy integration, a `AWS::Lambda::Permission`
resource is created to provide the HTTP service permission to invoke
the lambda function, creating the dependency, Permission → API.
The API, on the other hand, needs to refer to the Function's ARN and
hence creates the dependency, API → Function.

However, when the lambda function and the HTTP API are placed in
different stacks, this creates a cyclic dependency between these two
stacks.

A picture is worth a thousand words:

```
 +--------------------------------------------------------------+
 | Lambda stack                                                 |
 |                                                              |
 |    +-------------------+            +-----------------+      |
 |    |                   | via ARN    |                 |      |
 |    | Lambda Permission +----------->| Lambda Function |      |
 |    |                   |            |                 |      |
 |    +-------+-----------+            +-----------------+      |
 |            |                                ^                |
 +------------|--------------------------------|----------------+
              |via ARN                         |via ARN
              |                                |
 +------------|--------------------------------|-----------------+
 |            v                                |                 |
 |      +-----------+               +----------+---------+       |
 |      |           |    via ID     |                    |       |
 |      |  Http API |<--------------+  API Integration   |       |
 |      |           |               |                    |       |
 |      +-----------+               +--------------------+       |
 |                                                               |
 | API Gateway stack                                             |
 +---------------------------------------------------------------+
```

The fix here is to move the Lambda Permission resource into the same
stack as where the API integration is defined, thereby breaking the
dependency cycle. 
Now the 'API Gateway stack' will depend one way on the 'Lambda
stack'.

fixes #9075

BREAKING CHANGE: The parameter for the method `bind()` on
`IHttpRouteIntegration` has changed to accept one of type
`HttpRouteIntegrationBindOptions`. The previous parameter
`IHttpRoute` is now a property inside the new parameter under
the key `route`.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-apigatewayv2/lib/http/integration.ts [hunk 1]
```diff
@@ -112,14 +112,31 @@ export class HttpIntegration extends Resource implements IHttpIntegration {
...
+ */
+export interface HttpRouteIntegrationBindOptions {
+  /**
+   * The route to which this is being bound.
+   */
+  readonly route: IHttpRoute;
+
+  /**
+   * The current scope in which the bind is occurring.
+   * If the `HttpRouteIntegration` being ound create additionaly constructs,
```
Comment (njlynch) [inline packages/@aws-cdk/aws-apigatewayv2/lib/http/integration.ts:126]:
```suggestion
   * If the `HttpRouteIntegration` being bound creates additional constructs,
```
