### PR TITLE
fix(cognito): authFlows require refreshToken in all scenarios

### LINKED ISSUE #7625: Cognito REFRESH_TOKEN_AUTH should always be allowed
From my usage, it appears that `cognito.UserPoolClient.authFlows` needs `refreshToken` to be `true` in every scenario. Because of this, should we default it to `true`, instead of `false`?

https://github.com/aws/aws-cdk/blob/feadd6cb643b415ae002191ba2cb4622221a5af6/packages/%40aws-cdk/aws-cognito/lib/user-pool-client.ts#L34-L38

### Reproduction Steps

```ts
const userPool = new UserPool(this, "SystemUserPool", {
      userPoolName: id,
      signInAliases: { username: true },
      lambdaTriggers: {
        preSignUp: preSignUpLambda
        preTokenGeneration: preTokenLambda
      },
    });
new UserPoolClient(this, "UserPoolClient", {
      userPool,
      userPoolClientName: "my-client",
      authFlows: {
        userSrp: true,
      },
    });
```

### Error Log

```
 2/3 | 12:22:00 PM | UPDATE_FAILED        | AWS::Cognito::UserPoolClient | UserPoolClient (UserPoolClient2F5918F7) REFRESH_TOKEN_AUTH should always be allowed. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: 61d7876f-96c0-4703-ae94-85dba259d380)
```

### Environment

  - **CLI Version      :** 1.35.0
  - **Framework Version:** 1.35.0
  - **OS               :** MacOS
  - **Language         :** English

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by ayush987goyal**
refreshToken always allowed when authFlows present in UserPoolClient

BREAKING CHANGE: `refreshToken` property is now removed from
UserPoolClient. It will be included if any other `authFlow` is enabled.

closes #7625

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts [hunk 1]
```diff
@@ -33,7 +33,7 @@ export interface AuthFlow {
 
   /**
    * Enable authflow to refresh tokens
-   * @default false
+   * @default true
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts:36]: is this a breaking change? - flipping the behaviour from false to true?

potential follow up question: if it must always be enabled, is there any value in accepting it as a boolean

File: packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts [hunk 2]
```diff
@@ -343,12 +343,20 @@ export class UserPoolClient extends Resource implements IUserPoolClient {
...
+    if (props.authFlows.adminUserPassword) { authFlows.push('ALLOW_ADMIN_USER_PASSWORD_AUTH'); }
+    if (props.authFlows.custom) { authFlows.push('ALLOW_CUSTOM_AUTH'); }
+    if (props.authFlows.userSrp) { authFlows.push('ALLOW_USER_SRP_AUTH'); }
+
+    // refreshToken should always be allowed if authFlows are present
+    if (props.authFlows.refreshToken === undefined) {
+      authFlows.length && authFlows.push('ALLOW_REFRESH_TOKEN_AUTH');
+    } else {
+      props.authFlows.refreshToken && authFlows.push('ALLOW_REFRESH_TOKEN_AUTH');
+    }
```
Comment (shivlaks) [inline packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts:359]: seems like we could clean this up a little bit - it shouldn't be undefined since we're defining it on line 348 and initializing it to be empty.

```suggestion
    if (authFlows.length > 0 || props.authFlows?.refreshToken) {
      authFlows.push('ALLOW_REFRESH_TOKEN_AUTH')
    }
```

**Review by shivlaks — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts (hunk 1 above)
Comment (ayush987goyal) [reply packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts:36]: This should not be a breaking change since, as pointed out in the issue, this flag is anyway required if we are providing authFlows.

There is no specific point of accepting it as boolean. But removing it would then be a breaking change. What do you think?

File: packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts (hunk 2 above)
Comment (ayush987goyal) [reply packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts:359]: Will do.

File: packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts (hunk 1 above)
Comment (ayush987goyal) [reply packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts]: Removed the prop and marking this change as breaking

File: packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts [hunk 3]
```diff
@@ -343,12 +337,18 @@ export class UserPoolClient extends Resource implements IUserPoolClient {
...
-    if (props.authFlows?.refreshToken) { authFlows.push('ALLOW_REFRESH_TOKEN_AUTH'); }
+    if (props.authFlows.userPassword) { authFlows.push('ALLOW_USER_PASSWORD_AUTH'); }
+    if (props.authFlows.adminUserPassword) { authFlows.push('ALLOW_ADMIN_USER_PASSWORD_AUTH'); }
+    if (props.authFlows.custom) { authFlows.push('ALLOW_CUSTOM_AUTH'); }
+    if (props.authFlows.userSrp) { authFlows.push('ALLOW_USER_SRP_AUTH'); }
+
+    // refreshToken should always be allowed if authFlows are present
+    if (authFlows.length > 0) {
+      authFlows.push('ALLOW_REFRESH_TOKEN_AUTH');
+    }
```
Comment (nija-at) [inline packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts:351]: Are we sure there is no use case where a customer would configure an authFlow but explicitly not want refresh tokens?

Should we add an optional property `disableRefreshToken` that defaults to `false`?

**Comment by nija-at** [comment]
Use the 'breaking changes' format as documented here - https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#step-4-commit

File: packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts (hunk 3 above)
Comment (ayush987goyal) [reply packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts:351]: As mentioned in the issue and from the CFN error it is pretty clear that it is always required. Therefore adding a property to disable is would mean that it can potentially be disabled.

Comment (nija-at) [reply packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts:351]: That's fair.

**Review by nija-at — APPROVED** [review]

**Comment by phawxby** [comment]
@nija-at your prediction came true. 

> To enable refresh token rotation, you must disable ALLOW_REFRESH_TOKEN_AUTH in this app client and update tokens with the GetTokensFromRefreshToken operation or the /oauth2/token endpoint instead.

This change may need reverting.
