### PR TITLE
fix(cli): CLI timeout fetching notices prints "unreachable" branch error message

### LINKED ISSUE #20069: (cli): Notices timeout works but uses the second catch
### Describe the bug

As written in the comment and error message [here](https://github.com/aws/aws-cdk/blob/fd306ee05cfa7ebaa8d997007500d89d62868897/packages/aws-cdk/lib/notices.ts#L148-L154) we should not see the error but that is exactly what we are seeing.
The request is being terminated and the command does not hang anymore, but the error message says to open an issue, so here I am.

### Expected Behavior

Should not see the error message but instead use the timeout.

### Current Behavior

Forcefully shuts down the request.

### Reproduction Steps

Create a pipeline which uses the SelfMutate option and runs in a private subnet.

### CDK CLI Version

2.21.1
### Node.js Version

16.14.0

### OS

MacOS Monetery 12.3

### Language

Typescript

### PR DESCRIPTION
**Pull request by Naumel**
fixes #20069

Problem: the [error message](https://github.com/aws/aws-cdk/blob/fd306ee05cfa7ebaa8d997007500d89d62868897/packages/aws-cdk/lib/notices.ts#L148-L154) should not be displayed. It was part of a backup timer acting as a fail-safe.

Additionally, the timer from `setTimeout()` is not cleared. the issue is being addressed by invoking `unref()`.

Overall, the behavior is correct: the request is being terminated, but the error message prompted the users encountering it to open an issue.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk/lib/notices.ts [hunk 1]
```diff
@@ -138,22 +145,10 @@ export class WebsiteNoticeDataSource implements NoticeDataSource {
...
-        // Add a backup timer that will destroy the request after all.
-        // (This is at least necessary to make the tests pass, but that's probably because of 'nock'.
-        // It's not clear whether users will hit this).
-        setTimeout(() => {
-          req.destroy(new Error('Request timed out. You should never see this message; if you do, please let us know at https://github.com/aws/aws-cdk/issues'));
-        }, timeout + 200);
       } catch (e) {
         reject(new Error(`HTTPS 'get' call threw an error: ${e.message}`));
+      } finally {
+        clearTimeout(timer);
```
Comment (rix0rrr) [inline packages/aws-cdk/lib/notices.ts:151]: Since the `finally` will execute immediately after starting the async process, we'll immediately cancel the timer and the timeout will never fire. The `unref` by itself should do it.

**Review by rix0rrr — DISMISSED** [review]

**Comment by kaizencc** [comment]
@Naumel If you change the PR description to say `fixes #20308` my github action will pick up this link and label your PR with the correct priority of `p1` rather than the current `p2`.

(That's how github [suggests](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) we link issues, but i guess it still picks up other ways too. Unfortunately, the github action I wrote is not as robust...)

File: packages/aws-cdk/lib/notices.ts [hunk 2]
```diff
@@ -108,8 +109,18 @@ export class WebsiteNoticeDataSource implements NoticeDataSource {
   fetch(): Promise<Notice[]> {
     const timeout = 3000;
     return new Promise((resolve, reject) => {
+      var req: ClientRequest;
```
Comment (rix0rrr) [inline packages/aws-cdk/lib/notices.ts:112]: Please make this a `let`. Also, let's be a bit more honest about the type.

```suggestion
      let req: ClientRequest | undefined;
```

File: packages/aws-cdk/lib/notices.ts [hunk 3]
```diff
@@ -108,8 +109,18 @@ export class WebsiteNoticeDataSource implements NoticeDataSource {
...
+
+      var timer = setTimeout(() => {
```
Comment (rix0rrr) [inline packages/aws-cdk/lib/notices.ts:114]: Same
```suggestion
      let timer = setTimeout(() => {
```

File: packages/aws-cdk/lib/notices.ts [hunk 4]
```diff
@@ -108,8 +109,18 @@ export class WebsiteNoticeDataSource implements NoticeDataSource {
...
+          req.destroy(new Error('Request timed out'));
+        }
+      }, timeout);
+
+      timer.unref();
+
       try {
-        const req = https.get('https://cli.cdk.dev-tools.aws.dev/notices.json',
+        req = https.get('https://cli.cdk.dev-tools.aws.dev/notices.json',
           { timeout },
```
Comment (rix0rrr) [inline packages/aws-cdk/lib/notices.ts:124]: No point in passing `{ timeout }` here anymore then.

**Review by rix0rrr — DISMISSED** [review]

**Comment by rix0rrr** [comment]
Conditionally approved.

**Review by rix0rrr — DISMISSED** [review]

**Review by rix0rrr — APPROVED** [review]

**Comment by kaizencc** [comment]
@Naumel I added the `pr-linter/exempt-test` label because I don't think you need to modify or add to the existing tests. However, I re-added `pr/do-not-merge` because the PR build does not automatically run CLI integ tests that will get run when the PR is merged to `main`. Can you run these integ tests locally, or on the `test-pipeline` to make sure that they will succeed? Then, I'm happy to remove the `do-not-merge` label.

**Comment by rix0rrr** [comment]
I am confident and will deal with the consequences :)
