### PR TITLE
fix(lambda): unable to add permissions to imported lambda functions 

### LINKED ISSUE #7588: Permission resource is not created for imported lambda function
Resource Policy is not being created for Lambda when using Lambda version but is being created when using new Lambda. 

### Reproduction Steps:

* Create a new lambda function and publish a new version for it. 

* Create a new resource policy for the created lambda version. 

Example shows creating new resource policy for api gateway to invoke weatherFunction lambda version 13
```
_lambda.Version.from_version_attributes(self, id='stageVersion',lambda_=weatherFunction,version='13').add_permission(id='invokeweatherfnversion13',principal=iam.ServicePrincipal(service='apigateway.amazonaws.com'),
        action='lambda:InvokeFunction',source_arn=api.arn_for_execute_api(stage='dev', method='GET',path='/')
        )
```

### Error Log

No error message 

### Environment

  - **CLI Version      : 1.34.1
  - **Framework Version: 1.34.1
  - **OS               : Mac Mojave 10.14.6
  - **Language         :Python

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by BryanPan342**
**[ISSUE]**
Imported Lambda functions unable to add new resource policy

**[APPROACH]**
Add a check for imported Lambda Functions between the account id and the account id from imported Lambda Function. If they match, imported function can add permissions.  

Fixes #7588 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by BryanPan342** [comment]
[ACTIONABLES]
- [ ] Double check logic
- [ ] Write unit tests
- [ ] Update documentation
- [ ] Write integration tests

**Comment by BryanPan342** [comment]
Right now my logic is to just make everything that is imported to be `canAddPermissions` to `true`. There is a conflict with the documentation as it stands with the following https://github.com/aws/aws-cdk/blob/9ee61eb96de54fcbb71e41a2db2c1c9ec6b7b8d9/packages/%40aws-cdk/aws-lambda/lib/function-base.ts#L182-L187
I think it's a valid point that imported Lambdas could potentially be from different accounts thus an inability to create resource policies. 

I suggest implementing something similar to the way `route53` implements a `fromLookup` through a context provider. https://github.com/aws/aws-cdk/blob/9ee61eb96de54fcbb71e41a2db2c1c9ec6b7b8d9/packages/%40aws-cdk/aws-route53/lib/hosted-zone.ts#L95-L98

This would require implementing another function and updating the README, but wouldn't interfere with the current implementation of `lambda` which so many users currently use. 

@nija-at Open to suggestions to an alternative and will revisit fresh tomorrow morning.

File: packages/@aws-cdk/aws-lambda/lib/function-base.ts [hunk 1]
```diff
@@ -182,7 +182,7 @@ export abstract class FunctionBase extends Resource implements IFunction {
   /**
    * Whether the addPermission() call adds any permissions
    *
-   * True for new Lambdas, false for imported Lambdas (they might live in different accounts).
+   * True for new Lambdas, false for version $LATEST.
```
Comment (nija-at) [inline packages/@aws-cdk/aws-lambda/lib/function-base.ts:185]: Will this now work for imported lambdas in other accounts? 

If not, maybe we should check the account id from the ARN in the `fromXXX()` API

File: packages/@aws-cdk/aws-lambda/test/integ.function-import.ts [hunk 2]
```diff
@@ -0,0 +1,31 @@
+import * as iam from '@aws-cdk/aws-iam';
```
Comment (nija-at) [inline packages/@aws-cdk/aws-lambda/test/integ.function-import.ts:1]: Drop this integration test and switch to a unit test instead.

**Review by nija-at — DISMISSED** [review]

File: packages/@aws-cdk/aws-lambda/lib/function-base.ts (hunk 1 above)
Comment (BryanPan342) [reply packages/@aws-cdk/aws-lambda/lib/function-base.ts:185]: Does this mean we would force users to set up a `env` for the account id? Because if not the account id will only get resolved at deploy time so we wouldn't be able to check if the arns matched. Unless there is another way to get the account id that I do not know of...

Comment (nija-at) [reply packages/@aws-cdk/aws-lambda/lib/function-base.ts:185]: For imported lambda functions, account id should be available in the ARN specified during import.

Comment (BryanPan342) [reply packages/@aws-cdk/aws-lambda/lib/function-base.ts:185]: yes but in order to check the account id with the users account, we would need to get the account tied to the stack right? but if the `env` (using a Context Provider) is not supplied to the app, then the token will only be resolved at deploy time.

Comment (nija-at) [reply packages/@aws-cdk/aws-lambda/lib/function-base.ts:185]: Fair enough. 

You could add a check if the user had in fact called it using [`withResolved()`](https://github.com/aws/aws-cdk/blob/1fe9684ea6b2dcaac1d97b64edfd4ef87cc65c0f/packages/%40aws-cdk/core/lib/token.ts#L199)

File: packages/@aws-cdk/aws-lambda/lib/function-base.ts [hunk 3]
```diff
@@ -346,6 +347,27 @@ export abstract class FunctionBase extends Resource implements IFunction {
...
+   *
+   * @returns true if account id of function matches this account
+   *
+   * @internal
+   */
+  protected _checkAccountIdFromArn(): boolean {
+    if (Token.isUnresolved(this.stack.account) || Token.isUnresolved(this.functionArn)) {
+      return false;
+    }
+    return Fn.select(4, Fn.split(':', this.functionArn)) === this.stack.account;
```
Comment (nija-at) [inline packages/@aws-cdk/aws-lambda/lib/function-base.ts:368]: I believe you can just use `this.stack.parseArn()`.

File: packages/@aws-cdk/aws-lambda/test/test.lambda.ts [hunk 4]
```diff
@@ -283,6 +283,30 @@ export = {
     // THEN
     test.deepEqual(imported.functionArn, 'arn:aws:lambda:us-east-1:123456789012:function:ProcessKinesisRecords');
     test.deepEqual(imported.functionName, 'ProcessKinesisRecords');
+    expect(stack2).notTo(haveResource('AWS::Lambda::Permission'));
+    test.done();
+  },
+
+  'imported Function w/ resolved account and function arn can addPermissions'(test: Test) {
```
Comment (nija-at) [inline packages/@aws-cdk/aws-lambda/test/test.lambda.ts:290]: Add another test case that `addPermission()` fails if account doesn't match.

File: packages/@aws-cdk/aws-lambda/lib/function-base.ts [hunk 5]
```diff
@@ -346,6 +347,27 @@ export abstract class FunctionBase extends Resource implements IFunction {
...
+   *   arn:aws:lambda:region:account-id:function:function-name
+   *
+   * ..which means that in order to extract the `account-id` component from the ARN, we can
+   * split the ARN using ":" and select the component in index 4.
+   *
+   * @returns true if account id of function matches this account
+   *
+   * @internal
+   */
+  protected _checkAccountIdFromArn(): boolean {
```
Comment (nija-at) [inline packages/@aws-cdk/aws-lambda/lib/function-base.ts:364]: Better name maybe `_isStackAccount()`

**Review by nija-at — CHANGES_REQUESTED** [review]
Logic looks good. Some code comments.

**Review by nija-at — APPROVED** [review]
