### PR TITLE
fix(route53): delegation fails with public and private hosted zones with same name

### LINKED ISSUE #30262: CrossAccountZoneDelegationRecord: Validation fails for public and private hosted zone with the same name
### Describe the bug

CrossAccountZoneDelegationRecord complains about more than 1 matching zone when only one of them is public.

### Expected Behavior

Validate that there is only one **public** hosted zone matching the name.

### Current Behavior

Validates that there is only one (no filter by public) hosted zone matching the name. The logic is here: https://github.com/aws/aws-cdk/blob/623cedb429fba5bcf6ecdf2bb8277fcc2b88eba4/packages/%40aws-cdk/custom-resource-handlers/lib/aws-route53/cross-account-zone-delegation-handler/index.ts#L79

### Reproduction Steps

Create a public and private hosted zone in one account with the same name and then a CrossAccountZoneDelegationRecord in the other.

### Possible Solution

Filter by public hosted zone here: https://github.com/aws/aws-cdk/blob/623cedb429fba5bcf6ecdf2bb8277fcc2b88eba4/packages/%40aws-cdk/custom-resource-handlers/lib/aws-route53/cross-account-zone-delegation-handler/index.ts#L79

### Additional Information/Context

_No response_

### CDK CLI Version

2.136.0

### Framework Version

_No response_

### Node.js Version

8.19.4

### OS

Linux

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by samson-keung**
### Issue # (if applicable)

Closes #30262.

### Reason for this change

Route53 does not support subdomain delegation on Private Hosted Zones ([source](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zone-private-considerations.html#hosted-zone-private-considerations-delegating-subdomain)). `CrossAccountZoneDelegationRecord` should ignore Private Hosted Zones instead of throwing error.

### Description of changes

In `CrossAccountZoneDelegationRecord` handler, filter out Private Hosted Zones.

### Description of how you validated changes

Deployed a stack that uses the updated `CrossAccountZoneDelegationRecord` handler where the parent account has both public and private hosted zones with the same domain name.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/custom-resource-handlers/lib/aws-route53/cross-account-zone-delegation-handler/index.ts [hunk 1]
```diff
@@ -77,7 +77,12 @@ async function cfnEventHandler(props: ResourceProperties, isDeleteEvent: boolean
 
 async function getHostedZoneIdByName(name: string, route53: Route53): Promise<string> {
   const zones = await route53.listHostedZonesByName({ DNSName: name });
-  const matchedZones = zones.HostedZones?.filter(zone => zone.Name === `${name}.`) ?? [];
+  const matchedZones = zones.HostedZones?.filter(zone => {
+    const matchZoneName = zone.Name === `${name}.`;
+    const isPublic = zone.Config?.PrivateZone === false || zone.Config?.PrivateZone === undefined;
```
Comment (aaythapa) [inline packages/@aws-cdk/custom-resource-handlers/lib/aws-route53/cross-account-zone-delegation-handler/index.ts:82]: does `const isPublic = zone.Config?.PrivateZone !== true` work here?

File: packages/@aws-cdk/custom-resource-handlers/test/aws-route53/cross-account-zone-delegation-handler.test.ts [hunk 2]
```diff
@@ -104,13 +104,18 @@ test('calls create resource record set with DELETE for Delete event', async () =
...
   const parentZoneId = 'zone-id';
 
   mockStsClient.assumeRole.mockResolvedValueOnce({ Credentials: { AccessKeyId: 'K', SecretAccessKey: 'S', SessionToken: 'T' } });
-  mockRoute53Client.listHostedZonesByName.mockResolvedValueOnce({ HostedZones: [{ Name: `${parentZoneName}.`, Id: parentZoneId }] });
+  mockRoute53Client.listHostedZonesByName.mockResolvedValueOnce({
+    HostedZones: [
+      { Name: `${parentZoneName}.`, Id: parentZoneId },
+      { Name: `${parentZoneName}.`, Id: parentZoneId, Config: { PrivateZone: true } },
+    ],
+  });
```
Comment (aaythapa) [inline packages/@aws-cdk/custom-resource-handlers/test/aws-route53/cross-account-zone-delegation-handler.test.ts:118]: same question as integ test, does this test the change thats implemented?

File: packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.ts [hunk 3]
```diff
@@ -47,6 +48,12 @@ class ParentStack extends cdk.Stack {
     const parentZone = new route53.PublicHostedZone(this, 'HostedZone', {
       zoneName: parentZoneName,
     });
+    new route53.PrivateHostedZone(this, 'PrivateHostedZone', {
+      zoneName: parentZoneName,
+      vpc: new ec2.Vpc(this, 'TheVPC', {
+        ipAddresses: ec2.IpAddresses.cidr('10.0.0.0/16'),
+      }),
+    });
```
Comment (aaythapa) [inline packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.ts:56]: might be missing something but how does this test the change thats implemented?

File: packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.rename-cross-account-zone-delegation.js.snapshot/asset.392b3833f117607db3f72dc30f3acf726cd6b17317a3da1598e52003fd21f86b/__entrypoint__.js
Comment (aaythapa) [inline packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.rename-cross-account-zone-delegation.js.snapshot/asset.392b3833f117607db3f72dc30f3acf726cd6b17317a3da1598e52003fd21f86b/__entrypoint__.js:1]: Any idea why snapshots in this test changed even thought there was no change to the integ test itself?

File: packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.ts (hunk 3 above)
Comment (samson-keung) [reply packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.ts:56]: The issue this PR fixes is the following:

When the parent account has 2 Hosted Zones with the same name (e.g. `abc.com`), and then when `CrossAccountZoneDelegationRecord` is deployed to a child account in order to delegate a subdomain (e.g. `xyz.abc.com`) to this child account, the `CrossAccountZoneDelegationRecord` handler/lambda would throw an error.

Therefore, I updated this integ test such that the parent account has one public and one private hosted zones with the same name. Then when the child account deploys `CrossAccountZoneDelegationRecord`, there shouldn't be any error with this PR fix.

File: packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.rename-cross-account-zone-delegation.js.snapshot/asset.392b3833f117607db3f72dc30f3acf726cd6b17317a3da1598e52003fd21f86b/__entrypoint__.js
Comment (samson-keung) [reply packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.rename-cross-account-zone-delegation.js.snapshot/asset.392b3833f117607db3f72dc30f3acf726cd6b17317a3da1598e52003fd21f86b/__entrypoint__.js:1]: The `integ.rename-cross-account-zone-delegation` integ test uses the `CrossAccountZoneDelegationRecord` construct (Not sure why we have 2 integ tests for this construct). Since I changed the `CrossAccountZoneDelegationRecord` handler/lambda, the assets for this test also changed.

File: packages/@aws-cdk/custom-resource-handlers/lib/aws-route53/cross-account-zone-delegation-handler/index.ts (hunk 1 above)
Comment (samson-keung) [reply packages/@aws-cdk/custom-resource-handlers/lib/aws-route53/cross-account-zone-delegation-handler/index.ts:82]: Yea. Should work and it makes the logic simpler. Will update

File: packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.ts (hunk 3 above)
Comment (aaythapa) [reply packages/@aws-cdk-testing/framework-integ/test/aws-route53/test/integ.cross-account-zone-delegation.ts:56]: ah I see, so before the change this integ test with the private zone should've failed. Makes sense thanks for the explanation

**Review by aaythapa — APPROVED** [review]
