### PR TITLE
fix(aws-autoscaling): notificationTargetArn should be optional in LifecycleHook

### LINKED ISSUE #14641: (aws-autoscaling): notificationTarget shouldn't be compulsory in LifecycleHook
The `notificationTarget` property can be unset and by default it will be able to use CWE to deliver Autoscaling Group notifications.

ASG API - https://docs.aws.amazon.com/cli/latest/reference/autoscaling/put-lifecycle-hook.html , keeps `[--notification-target-arn <value>]` as an optional param.

I was able to use L1 construct - `CfnLifecycleHook` as such without providing the `notificationTarget`

```
        const lcHook = new autoscaling.CfnLifecycleHook(this, "LCHook", {
            autoScalingGroupName: nodegroup.autoScalingGroupName,
            lifecycleTransition: LifecycleTransition.INSTANCE_TERMINATING,
            defaultResult: DefaultResult.CONTINUE,
            lifecycleHookName: "TerminateLifecycleHook",
            heartbeatTimeout: 300
        })
``` 

### Reproduction Steps

Documentation shows property is mandatory - https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-autoscaling.LifecycleHook.html

### What did you expect to happen?

notificationTarget should be optional or should have a way to use the default CWE integration.

### What actually happened?

Could not use CWE integration which is how aws-node-termination-handler needs to be configured

### Environment

  - **CDK CLI Version  :** 1.97.0
  - **Framework Version:**
  - **Node.js Version:**  v15.9.0
  - **OS               :** Mac
  - **Language (Version):**  TypeScript

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by comcalvi**
This makes the notificationTargetArn optional in LifecycleHook. CloudFormation docs specify it as optional [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-as-lifecyclehook.html). Closes #14641. 
To achieve this, the `role` parameter was made optional. To avoid breaking users, a role is provided if users specify a `notificationTarget` (which they currently all do, as it is a required property) and is not provided otherwise.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-autoscaling/lib/lifecycle-hook.ts [hunk 1]
```diff
@@ -46,13 +46,15 @@ export interface BasicLifecycleHookProps {
 
   /**
    * The target of the lifecycle hook
+   *
+   * @default - No target.
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-autoscaling/lib/lifecycle-hook.ts:50]: When I said "explain it" I actually didn't just mean "explain it to me"... explain it to everyone! Describe in the doc comment what not having a target does.

How are users supposed to decide whether or not it makes sense for them to leave this optional parameter out otherwise?

Answer "because CFN said so" isn't good enough, I'm afraid, because it doesn't lead to any *understanding*, and it doesn't help me make a choice. At this point you're going to have to look at the service documentation for this feature and tease out what it means.

If you can't find that information, that would be a good opportunity to cut a ticket to the docs team (there's a way to do that at the bottom of every page) to call out that missing information.

File: packages/@aws-cdk/aws-autoscaling/lib/lifecycle-hook.ts [hunk 2]
```diff
@@ -73,18 +75,36 @@ export interface LifecycleHookProps extends BasicLifecycleHookProps {
 export interface ILifecycleHook extends IResource {
   /**
    * The role for the lifecycle hook to execute
+   *
+   * @default - A default role is created if 'notificationTarget' is specified.
+   * Otherwise, no role is created.
    */
-  readonly role: iam.IRole;
+  role: iam.IRole;
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-autoscaling/lib/lifecycle-hook.ts:82]: I don't think this should become read/write.

I know the API doesn't let you do what you need to do, which sucks. We'll have to find a way around that, but this is not the right way. We're going to either (a) have to break the api or (b) do type hackery.

Let's do (a), this once.

File: packages/@aws-cdk/aws-autoscaling-hooktargets/lib/lambda-hook.ts [hunk 3]
```diff
@@ -23,16 +24,22 @@ export class FunctionHook implements autoscaling.ILifecycleHookTarget {
   constructor(private readonly fn: lambda.IFunction, private readonly encryptionKey?: kms.IKey) {
   }
 
-  public bind(scope: Construct, lifecycleHook: autoscaling.ILifecycleHook): autoscaling.LifecycleHookTargetConfig {
-    const topic = new sns.Topic(scope, 'Topic', {
+  public bind(_scope: Construct, lifecycleHook: autoscaling.ILifecycleHook): autoscaling.LifecycleHookTargetConfig {
+    const topic = new sns.Topic(_scope, 'Topic', {
       masterKey: this.encryptionKey,
     });
+    try { lifecycleHook.role; } catch (noRoleError) {
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-autoscaling-hooktargets/lib/lambda-hook.ts:31]: Ew :/

How about we change the signature of `bind()` to:

```ts
public bind(scope: Construct, options: BindHookTargetOptions): BindHookTargetResult;
```

Then we will have:

```
interface BindHookTargetOptions {
  readonly lifecycleHook: autoscaling.ILifecycleHook;
  readonly role?: iam.IRole;
}

interface BindHookTargetResult {
  readonly createdRole?: iam.IRole;
}
```

The linter will yell at you that it's a breaking change, but you have my permission to silence it (by adding it to `allowed-breaking-changes.txt`).

**Review by rix0rrr — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-autoscaling/lib/lifecycle-hook.ts (hunk 2 above)
Comment (comcalvi) [reply packages/@aws-cdk/aws-autoscaling/lib/lifecycle-hook.ts:82]: Do you mean removing this logic
```
private readonly _role?: iam.IRole;

public get role(): iam.IRole {
  if (!this._role) { throw new Error('Oh no we don\'t have a role'); }
  return this._role;
}
```
and going back to having `public readonly role?: iam.IRole;` like we had [previously](https://github.com/aws/aws-cdk/pull/16187#discussion_r696420739)?

File: packages/@aws-cdk/aws-autoscaling/lib/lifecycle-hook-target.ts [hunk 4]
```diff
@@ -1,26 +1,61 @@
...
+ */
+export interface ILifecycleHookTarget {
+  /**
+   * Called when this object is used as the target of a lifecycle hook
+   * @param options [disable-awslint:ref-via-interface] The lifecycle hook to attach to and a role to use
+   */
+  bind(scope: constructs.Construct, options: BindHookTargetOptions): LifecycleHookTargetConfig;
+}
+
+export function createRole(scope: constructs.Construct, _role?: iam.IRole) {
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-autoscaling/lib/lifecycle-hook-target.ts:52]: This is a hacky private API (accidentally public to TS users), that I'm not sure this is worth sharing between `aws-autoscaling` and `aws-autoscaling-hooktargets` in this way. Just move it to the other library I would say.

**Review by rix0rrr — APPROVED** [review]
Thanks! Conditional approval based on a tiny change.
