### PR TITLE
fix(rds): publiclyAccessible=false set on an instance is ignored when cluster is placed in a public subnet

### LINKED ISSUE #28037: rds: AuroraClusterInstance ignores publiclyAccessible set to false when cluster is placed in public subnet
### Describe the bug

Even though publiclyAccessible set to false, the value is ignored if the cluster is placed in a public subnet.

There are legitimate cases where a cluster could be placed in a public subnet, but it still should not have a public IP address.

```typescript
declare const scope: cdk.IResource
declare const vpc: ec2.IVpc

const cluster = new rds.DatabaseCluster(scope, 'Resource', {
  clusterIdentifier: 'cluster-one',
  engine: rds.DatabaseClusterEngine.auroraMysql({ version: rds.AuroraMysqlEngineVersion.VER_3_04_0 }),
  writer: rds.ClusterInstance.serverlessV2('writer', {
    instanceIdentifier: 'writer-instance',
    publiclyAccessible: false
  }),
  readers: [
    rds.ClusterInstance.serverlessV2('reader', {
      instanceIdentifier: 'reader-instance',
      publiclyAccessible: false,
    })
  ],
  vpc,
  vpcSubnets: {
    subnetType: ec2.SubnetType.PUBLIC
  },
})
```

### Expected Behavior

The publiclyAccessible attribute should be honored if it is set, even if it is false.

### Current Behavior

If the vpc and the vpcSubnets.subnetType is set to PUBLIC it ignores the value provided in publiclyAccessible attribute.

The documentation does not specify that it will be ignored. 

### Reproduction Steps

```typescript
declare const scope: cdk.IResource
declare const vpc: ec2.IVpc

const cluster = new rds.DatabaseCluster(scope, 'Resource', {
  clusterIdentifier: 'cluster-one',
  engine: rds.DatabaseClusterEngine.auroraMysql({ version: rds.AuroraMysqlEngineVersion.VER_3_04_0 }),
  writer: rds.ClusterInstance.serverlessV2('writer', {
    instanceIdentifier: 'writer-instance',
    publiclyAccessible: false
  }),
  readers: [
    rds.ClusterInstance.serverlessV2('reader', {
      instanceIdentifier: 'reader-instance',
      publiclyAccessible: false,
    })
  ],
  vpc,
  vpcSubnets: {
    subnetType: ec2.SubnetType.PUBLIC
  },
})
```

### Possible Solution

Check if the publiclyAccessible attribute is NOT undefined, then set the value based on the vpc and vpc subnets.

### Additional Information/Context

_No response_

### CDK CLI Version

2.108.1

### Framework Version

2.108.1

### Node.js Version

18.18.2

### OS

macOS 14.0 (23A344)

### Language

TypeScript

### Language Version

TypeScript (4.9.5)

### Other information

_No response_

### PR DESCRIPTION
**Pull request by juanheyns**
This change fixes the incorrect behavior as explained in #28037. 

Using null coalescing operator in TypeScript will use the original value of `publiclyAccessible` set on the `ServerlessV2ClusterInstanceProps`.

Closes #28037.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-rds/lib/aurora-cluster-instance.ts [hunk 1]
```diff
@@ -450,11 +450,13 @@ class AuroraClusterInstance extends Resource implements IAuroraClusterInstance {
...
     let internetConnected;
-    let publiclyAccessible = props.publiclyAccessible;
+    let publiclyAccessible;
     if (isOwnedResource) {
       const ownedCluster = props.cluster as DatabaseCluster;
       internetConnected = ownedCluster.vpc.selectSubnets(ownedCluster.vpcSubnets).internetConnectivityEstablished;
-      publiclyAccessible = ownedCluster.vpcSubnets && ownedCluster.vpcSubnets.subnetType === ec2.SubnetType.PUBLIC;
+      publiclyAccessible = props.publiclyAccessible ?? (ownedCluster.vpcSubnets && ownedCluster.vpcSubnets.subnetType === ec2.SubnetType.PUBLIC);
+    } else {
+      publiclyAccessible = props.publiclyAccessible;
```
Comment (lpizzinidev) [inline packages/aws-cdk-lib/aws-rds/lib/aurora-cluster-instance.ts:459]:
```suggestion
```
See the comment above.

File: packages/aws-cdk-lib/aws-rds/lib/aurora-cluster-instance.ts [hunk 2]
```diff
@@ -450,11 +450,13 @@ class AuroraClusterInstance extends Resource implements IAuroraClusterInstance {
 
     const isOwnedResource = Resource.isOwnedResource(props.cluster);
     let internetConnected;
-    let publiclyAccessible = props.publiclyAccessible;
+    let publiclyAccessible;
```
Comment (lpizzinidev) [inline packages/aws-cdk-lib/aws-rds/lib/aurora-cluster-instance.ts:453]:
```suggestion
    let publiclyAccessible = props.publiclyAccessible;
```
Is the `else` statement necessary?

File: packages/aws-cdk-lib/aws-rds/lib/aurora-cluster-instance.ts [hunk 3]
```diff
@@ -450,11 +450,13 @@ class AuroraClusterInstance extends Resource implements IAuroraClusterInstance {
...
     if (isOwnedResource) {
       const ownedCluster = props.cluster as DatabaseCluster;
       internetConnected = ownedCluster.vpc.selectSubnets(ownedCluster.vpcSubnets).internetConnectivityEstablished;
-      publiclyAccessible = ownedCluster.vpcSubnets && ownedCluster.vpcSubnets.subnetType === ec2.SubnetType.PUBLIC;
+      publiclyAccessible = props.publiclyAccessible ?? (ownedCluster.vpcSubnets && ownedCluster.vpcSubnets.subnetType === ec2.SubnetType.PUBLIC);
```
Comment (lpizzinidev) [inline packages/aws-cdk-lib/aws-rds/lib/aurora-cluster-instance.ts:457]:
```suggestion
      const isInPublicSubnet = ownedCluster.vpcSubnets && ownedCluster.vpcSubnets.subnetType === ec2.SubnetType.PUBLIC;
      publiclyAccessible = isInPublicSubnet && (props.publiclyAccessible ?? true);
```
I don't think a public IP is needed if the instance is in a non-public subnet.

File: packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-public-subnets.ts [hunk 4]
```diff
@@ -0,0 +1,72 @@
...
+        },
+      }),
+    );
+  }
+}
+
+const app = new App();
+new IntegTest(app, 'integ-test', {
+  testCases: [new TestStack(app, 'integ-aurora-pub-sn-cluster')],
+});
```
Comment (lpizzinidev) [inline packages/@aws-cdk-testing/framework-integ/test/aws-rds/test/integ.cluster-public-subnets.ts:72]:
```suggestion
import { IntegTest } from '@aws-cdk/integ-tests-alpha';
import { App, RemovalPolicy, Stack, StackProps } from 'aws-cdk-lib';
import { SubnetType, Vpc } from 'aws-cdk-lib/aws-ec2';
import * as rds from 'aws-cdk-lib/aws-rds';
import { ClusterInstance } from 'aws-cdk-lib/aws-rds';
import { Construct } from 'constructs';

interface TestCaseProps extends Pick<rds.DatabaseClusterProps, 'writer'> { }

const testCases: TestCaseProps[] = [
  {
    writer: ClusterInstance.serverlessV2('writer'),
  },
  {
    writer: ClusterInstance.serverlessV2('writer', {
      publiclyAccessible: true,
    }),
  },
  {
    writer: ClusterInstance.serverlessV2('writer', {
      publiclyAccessible: false,
    }),
  },
];

export class TestStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);
    const vpc = new Vpc(this, 'Integ-VPC');

    testCases.forEach((p: TestCaseProps, i) =>
      new rds.DatabaseCluster(this, `Integ-Cluster-${i}`, {
        engine: rds.DatabaseClusterEngine.auroraMysql({ version: rds.AuroraMysqlEngineVersion.VER_3_03_0 }),
        writer: p.writer,
        removalPolicy: RemovalPolicy.DESTROY,
        vpc,
        vpcSubnets: {
          subnetType: SubnetType.PUBLIC,
        },
      }));
  }
}

const app = new App();

const stack = new TestStack(app, 'integ-aurora-pub-sn-cluster');

new IntegTest(app, 'test-aurora-pub-sn-cluster', {
  testCases: [stack],
});

app.synth();
```
A bit cleaner.

**Review by lpizzinidev — CHANGES_REQUESTED** [review]
Thanks for the contribution!
Feel free to comment on the proposed changes.
Also, the documentation for `publiclyAccessible` should be updated [here](https://github.com/aws/aws-cdk/blob/15f7b7afd83de84fc950ddc64a6d884e4b788827/packages/aws-cdk-lib/aws-rds/lib/aurora-cluster-instance.ts#L220) and [here](https://github.com/aws/aws-cdk/blob/15f7b7afd83de84fc950ddc64a6d884e4b788827/packages/aws-cdk-lib/aws-rds/README.md?plain=1#L521-L525).
Finally, the title should _describe the bug (not the solution)_, as per [guidelines](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request).

File: packages/aws-cdk-lib/aws-rds/lib/aurora-cluster-instance.ts (hunk 3 above)
Comment (juanheyns) [reply packages/aws-cdk-lib/aws-rds/lib/aurora-cluster-instance.ts]: This will be contrary to the behavior indicated in the documentation here:
https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk-lib/aws-rds#setting-public-accessibility

I believe the correct behavior here is to honor the user's setting if provided as a `publiclyAccessible ` property. If no value is provided we can default based on the interpreted intent from the subnet placement.

**Comment by juanheyns** [comment]
@lpizzinidev Ready for another review:

 - I have updated the title of the PR
 - Updated documentation [here](https://github.com/juanheyns/aws-cdk/blob/fix_issue_28037/packages/aws-cdk-lib/aws-rds/lib/instance.ts#L711), [here](https://github.com/juanheyns/aws-cdk/blob/fix_issue_28037/packages/aws-cdk-lib/aws-rds/lib/aurora-cluster-instance.ts#L224) and [here](https://github.com/juanheyns/aws-cdk/blob/fix_issue_28037/packages/aws-cdk-lib/aws-rds/README.md?plain=1#L519)
 - Also see my comment above about forcing publiclyAccessible=false if the instance is in a private subnet.

**Comment by lpizzinidev** [comment]
@juanheyns 
Thanks for the clarification on the default behavior.
If you could please update the snapshot for the integration test (the build is failing because of that) I will then approve the PR.

**Comment by juanheyns** [comment]
> @juanheyns Thanks for the clarification on the default behavior. If you could please update the snapshot for the integration test (the build is failing because of that) I will then approve the PR.

Hi @lpizzinidev I can see it is failing because of the integration test, I updated it with `yarn integ --update-on-failed test/aws-rds/test/integ.cluster-public-subnets.js`. See [2f410b8](https://github.com/aws/aws-cdk/pull/28038/commits/2f410b855828324e8ce4f8298d24e8a658ac75f4)

I am wondering if I need to configure a different account to deploy the integration test into? If I am missing something with running the test locally please point me to the documentation on how to set it up.

**Comment by lpizzinidev** [comment]
@juanheyns 
It looks like the integration test snapshot has not been updated after the last changes.
It still contains the original resources.
You should build it and execute it again:
1. `cd packages/@aws-cdk-testing/framework-integ`
2. `yarn build`
3. `yarn integ --update-on-failed test/aws-rds/test/integ.cluster-public-subnets.js`

**Comment by juanheyns** [comment]
> @juanheyns It looks like the integration test snapshot has not been updated after the last changes. It still contains the original resources. You should build it and execute it again:
> 
> 1. `cd packages/@aws-cdk-testing/framework-integ`
> 2. `yarn build`
> 3. `yarn integ --update-on-failed test/aws-rds/test/integ.cluster-public-subnets.js`

@lpizzinidev my bad, I forgot to build the stack first.

**Comment by juanheyns** [comment]
@lpizzinidev All checks are passing now, ready to review.

**Review by lpizzinidev — APPROVED** [review]

**Review by scanlonp — APPROVED** [review]
The logic change for aurora cluster instance looks good to me. I think the standardization in instance is good even though the logic is the same. Good tests.
Thanks @lpizzinidev for the review comments! And thank you @juanheyns for the contribution!
