### PR TITLE
fix: gracefully handle absence fo the `~/.aws/credentials` file

### LINKED ISSUE #540: CDK requires presence of ~/.aws/credentials
The CDK requires presence of the `~/.aws/credentials` file in order to operate, due to a mis-configuration of the `CredentialsProvider` used by the toolkit.

A workaround is to create a blank `~/.aws/credentials` file if you don't currently have one.

### PR DESCRIPTION
**Pull request by RomainMuller**
The JS SDK assumes the file exists when it is passed as an argument, so
this change makes the CDK Toolkit check for file existence before
passing down to the SDK layer. Additionally, the SDK "ini file"
re-implementation failed to check for file existece before attempting to
load file contents.

Fixes #540

### CODE REVIEW

**Comment by eladb** [comment]
Please fix your commit title and message to adhere to [conventional commits](https://conventionalcommits.org/)

File: packages/aws-cdk/lib/api/util/sdk_ini_file.ts [hunk 1]
```diff
@@ -44,9 +45,9 @@ export class SharedIniFile {
 
   private ensureFileLoaded() {
     if (!this.parsedContents) {
-      this.parsedContents = (AWS as any).util.ini.parse(
-        (AWS as any).util.readFileSync(this.filename)
-      );
+      this.parsedContents = fs.pathExistsSync(this.filename)
```
Comment (rix0rrr) [inline packages/aws-cdk/lib/api/util/sdk_ini_file.ts]: Are you sure this is necessary? I'm positive I tested this WITHOUT an `~/.aws/config` file and no crash.

Comment (RomainMuller) [reply packages/aws-cdk/lib/api/util/sdk_ini_file.ts]: My observations show that a missing `~/.aws/credentials` would blow up right this spot.

**Comment by RomainMuller** [comment]
@eladb I though my issue title **is** following [*conventional commits*](https://conventionalcommits.org) format already.

**Comment by eladb** [comment]
@RomainMuller it was "Gracefully handle absence fo the `~/.aws/credentials` file"
