### PR TITLE
fix(cli): assets are KMS-encrypted using wrong key

### LINKED ISSUE #18262: (assets): S3 asset publishing does not use the specified KMS Key
### What is the problem?

When publishing assets to the assets bucket, the files are not encrypted using the same KMS key as the default encryption method of the bucket. If the buckets' default encryption is set to KMS with a Customer Managed key, the objects will be encrypted with the AWS Managed key. This will make it impossible to shared the objects with the rest of the Organizational accounts. In this case it is not possible to deploy a stackset with assets. 

### Reproduction Steps

Create the bootstrapping stack with a KMS key:
cdk bootstrap --bootstrap-kms-key-id '' aws://<account>/<region>

This will create a bucket that uses a new Customer Managed key as default encryption (not AWS_MANAGED_KEY)

Create a cdk app with assets and synthesize the app.

Publish assets:
cdk-assets publish --path cdk.out/<stackname>-<region>.assets.json

### What did you expect to happen?

The objects should be encrypted with the Customer managed key.

### What actually happened?

The object are encrypted with the AWS Managed KMS Key

### CDK CLI Version

2.3.0

### Framework Version

_No response_

### Node.js Version

16

### OS

Mac

### Language

Typescript

### Language Version

_No response_

### Other information

I think the behaviour changed with the following change: 
https://github.com/aws/aws-cdk/commit/8191f1f1d4072feeba74844a31c942909cee7d83#diff-1f59ad129e9c6ce901748465a75693927875be1babb51d0f0871530c31678842

If I remove the s3:GetEncryptionConfiguration permissions, objects will be uploaded using the proper default encryption method (without the encryption header).

### PR DESCRIPTION
**Pull request by rix0rrr**
Even though a custom KMS key is specified as the default encryption key
on the file assets bucket, all uploaded assets are encrypted using the
default key.

The reason is that in #17668 we added an explicit `encryption: kms`
parameter to the `putObject` operation, so that an SCP that is
commonly in use across large organizations to prevent files from
ending up unencrypted, can be used (the SCP can only validate
call parameters, such as whether the `putObject` call includes
the parameter that reuests encryption, not the effective end result,
such as whether a file would end up encrypted).

However, we did not include the KMS Key Id into the `putObject`
request, which caused S3 to fall back to the default key.

Solution: also look up the key id and pass that along as well.

Fixes #18262.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by RomainMuller — APPROVED** [review]

File: packages/cdk-assets/lib/private/handlers/files.ts [hunk 1]
```diff
@@ -126,13 +130,13 @@ enum BucketOwnership {
...
-  ACCES_DENIED,
-  DOES_NOT_EXIST
-}
+type BucketEncryption =
+  | { readonly type: 'no_encryption' }
+  | { readonly type: 'aes256' }
+  | { readonly type: 'kms'; readonly kmsKeyId?: string }
+  | { readonly type: 'access_denied' }
+  | { readonly type: 'does_not_exist' }
+  ;
```
Comment (RomainMuller) [inline packages/cdk-assets/lib/private/handlers/files.ts:139]: Kinda sorta wonder why you didn't go and turn the `type` field into a constant... To keep compile-time referential checks in place?

**Comment by rix0rrr** [comment]
Fun times

```
Get "https://public.ecr.aws/v2/": Get "https://public.ecr.aws/token/?account=AWS&client_id=docker&offline_token=true&service=public.ecr.aws": net/http: TLS handshake timeout
```

**Comment by rix0rrr** [comment]
Choo choo all aboard the merge train
