### PR TITLE
fix(autoscaling): can't use block devices

### LINKED ISSUE #5868: create AutoScalingGroup fail with block_devices
Create AutoScalingGroup fail with block_devices definition in cdk deploy (python)

**Cloudformation fail on error**
> Cannot specify both EBS volume and no-device for block devices. (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError;

**Python code**
```python
autoscaling.AutoScalingGroup(self, "ASG",
    vpc=vpc,
    instance_type=ec2.InstanceType.of(ec2.InstanceClass.BURSTABLE2, ec2.InstanceSize.MICRO),
    machine_image=ec2.AmazonLinuxImage(),
    block_devices=[autoscaling.BlockDevice(device_name="/dev/sdb", volume=autoscaling.BlockDeviceVolume.ebs(20))]
)
```

**CloudFormation Output**
```json
        "BlockDeviceMappings": [
          {
            "DeviceName": "/dev/xvda",
            "Ebs": {
              "DeleteOnTermination": true,
              "VolumeSize": 12,
              "VolumeType": "gp2"
            },
            "NoDevice": false
          }
        ],
```
> The older version cdk hasn't this issue with same cdk coding, it didn't output "NoDevice" key.

### Environment
aws-cdk@1.21.1

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
Block Devices for AutoScalingGroups were broken because they would
always synthesize `NoDevice: true|false`, but the `NoDevice` key should
not be present at all if it is not intended. In essence, `NoDevice:
false` should never occur.

Add a feature to the `@aws-cdk/assert` library to assert absence
of certain keys (by use of a magic value).

Fixes #5868.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Commit Message
fix(autoscaling): can't use block devices

Block Devices for AutoScalingGroups were broken because they would
always synthesize `NoDevice: true|false`, but the `NoDevice` key should
not be present at all if it is not intended. In essence, `NoDevice:
false` should never occur.

Add a feature to the `@aws-cdk/assert` library to assert absence
of certain keys (by use of a magic value).

Fixes #5868.

### CODE REVIEW

File: packages/@aws-cdk/assert/lib/assertions/have-resource.ts [hunk 1]
```diff
@@ -1,6 +1,11 @@
 import { Assertion, JestFriendlyAssertion } from "../assertion";
 import { StackInspector } from "../inspector";
 
+/**
+ * Magic value to signify that a certain key should be absent from the property bag
+ */
+export const ABSENT = '{{ABSENT}}';
```
Comment (RomainMuller) [inline packages/@aws-cdk/assert/lib/assertions/have-resource.ts]: Noice!

Just wondering if this should be a `Symbol` to avoid possibly conflicting with a legitimate string value?

File: packages/@aws-cdk/assert/lib/assertions/have-resource.ts [hunk 2]
```diff
@@ -117,67 +122,89 @@ export interface InspectionFailure {
...
     return false;
   }
-  if (typeof obj === 'object') {
-    for (const key of Object.keys(obj)) {
-      if (!(key in superObj)) {
-        errors.push(`Field ${key} missing`);
+  if (typeof pattern === 'object') {
+    for (const [patternKey, patternValue] of Object.entries(pattern)) {
+      if (patternValue === ABSENT) {
+        if (superObj[patternKey] !== undefined) { errors.push(`Field ${patternKey} present, but shouldn't be`); }
```
Comment (RomainMuller) [inline packages/@aws-cdk/assert/lib/assertions/have-resource.ts]: Maybe should use `if (!(patternKey in superObj))` instead of an `undefined` check? Feels like it's a better semantic match?

```js
const obj = { a: undefined, b: 1337 };

obj['a'] !== undefined;
// => false
'a' in obj;
// => true
```

Otherwise I guess the doc of `ABSENT` should probably clarify that it signals the value must be: *absent or explicitly set to `undefined`* (which from the rest of the code seems to be a sufficient condition).

Comment (rix0rrr) [reply packages/@aws-cdk/assert/lib/assertions/have-resource.ts]: Since in the rest of the CDK we don't really make a difference between `undefined` and key absence (they end up the same in the final JSON), I don't artificially want to start making a distinction here. Feels like it would only serve to annoy.

File: packages/@aws-cdk/assert/lib/assertions/have-resource.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/@aws-cdk/assert/lib/assertions/have-resource.ts]: I considered that for a moment, and I guess worrying about jsii compatibility is a little premature at the moment, but I didn't do that because it wouldn't be representable there.

**Comment by nija-at** [comment]
It would also have been useful to split this up into two separate PRs only because the CHANGELOG can now have a feat(assert) and a fix(autoscaling) correctly reflecting a new feature and a fix.

Something to keep in mind for next time, if not this time.
