### PR TITLE
fix(custom-resource): provider framework lambda missing GetFunction permission

### LINKED ISSUE #26838: custom_resources: Provider Lambda function is missing lambda:GetFunctionConfiguration
### Describe the bug

The [Landing Zone Accelerator](https://github.com/awslabs/landing-zone-accelerator-on-aws) solution leverages the custom_resources module to create service-linked roles via CDK custom resources. When this custom resource Lambda function is invoked several times in succession, users intermittently receive the following error:

```
Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: Resource is not in the state functionActive
```

We believe this is the result of queuing incoming requests and the role attached to the `cdk.custom_resources.Provider` function is missing the permission: `lambda:GetFunctionConfiguration`

### Expected Behavior

Custom resource provider implements appropriate permissions and retries to execute successfully when invoked several times in succession. 

### Current Behavior

Transient failures:

```
Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: Resource is not in the state functionActive
```

### Reproduction Steps

Deploy v1.4.3 of the Landing Zone Accelerator on AWS.

For a smaller sample that can be extracted without deploying the entire LZA solution, you may use this custom resource construct that is used by LZA to create the service-linked roles:

https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/1614a01824c5a43f97fadfb8ec0c3627a0f343dd/source/packages/%40aws-accelerator/constructs/lib/aws-iam/service-linked-role.ts#L87

### Possible Solution

Add `lambda:GetFunctionConfiguration` permission to the provider Lambda function's IAM role.

### Additional Information/Context

_No response_

### CDK CLI Version

2.79

### Framework Version

_No response_

### Node.js Version

16.20.1

### OS

Amazon Linux

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by samson-keung**
### Issue # (if applicable)

Closes #26838.

### Reason for this change

In the Provider Framework lambda code, there is a logic to catch error arise from invoking the User Defined handler lambda. Upon error, it polls the state of the User Defined handler until it is in ACTIVE state (https://github.com/aws/aws-cdk/pull/22612 added this logic):

https://github.com/aws/aws-cdk/blob/64b865ba7697f454a1f091a67bf54a6d4ad0e76e/packages/aws-cdk-lib/custom-resources/lib/provider-framework/runtime/outbound.ts#L66-L80

The polling uses the AWS SDK `waitUntilFunctionActiveV2` function, which calls the Lambda GetFunction API:
https://github.com/aws/aws-sdk-js-v3/blob/6858c7e04730a2b524b06355969e4076c28ae863/clients/client-lambda/src/waiters/waitForFunctionActiveV2.ts#L57

However, the Provider Framework lambda does not have the `lambda:GetFunction` permission.

##### Why is the issue saying the `lambda:GetFunctionConfiguration` is needed instead of `lambda:GetFunction`?

At some point in time, the retry logic used `waitUntilFunctionActive` for polling, which use the `GetFunctionConfiguration`. But this is no longer the case after https://github.com/aws/aws-cdk/commit/c3a4b7b899289b04fffb6d65b3289cc5526d5397#diff-85920270c638d83b082246e0026f1a316dd39aaa3cd8720fdaeb3d526e438f7fR66

### Description of changes

Added the `lambda:GetFunction` permission on the role used by the Provider Framework lambda.

### Describe any new or updated permissions being added

The `lambda:GetFunction` permission is added.

### Description of how you validated changes

There isn't a straight forward way to test the INACTIVE lambda scenario as one need to wait 14 days for a Lambda function to become INACTIVE. Therefore, I am not able to create an integ test.

What I did was locally changing the Provider Framework lambda code to throw an error such that it executes the catch block. Then I verified in CloudTrail that the Provider Framework lambda called `GetFunction` successfully and then it was also able to invoke the User Defined Handler lambda. 

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by samson-keung** [comment]
Exemption Request

It requires waiting 14 days for a lambda to be in INACTIVE state. Therefore, we don't have a way to integ test this change.

File: packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts [hunk 1]
```diff
@@ -250,6 +250,20 @@ export class Provider extends Construct implements ICustomResourceProvider {
     };
   }
 
+  private addPermissions(frameworkLambda: lambda.Function, arnOfUserDefinedHandlerLambda: lambda.IFunction) {
```
Comment (moelasmar) [inline packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts:253]: nit: the name `arnOfUserDefinedHandlerLambda` is miss leading, I believe it should be `userDefinedHandlerLambda`

**Review by moelasmar — APPROVED** [review]
In general the change looks good, I left a minor comment

File: packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts [hunk 2]
```diff
@@ -250,6 +250,20 @@ export class Provider extends Construct implements ICustomResourceProvider {
...
+    /*
+    lambda:GetFunction is needed as the framework Lambda use it to poll the state of User Defined
+    Handler until it is ACTIVE state
+     */
+    frameworkLambda.addToRolePolicy(new iam.PolicyStatement({
+      effect: iam.Effect.ALLOW,
+      actions: ['lambda:GetFunction'],
+      resources: [arnOfUserDefinedHandlerLambda.functionArn],
+    }));
+  }
```
Comment (samson-keung) [inline packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts:265]:
```suggestion
  private addPermissions(frameworkLambda: lambda.Function, userDefinedHandlerLambda: lambda.IFunction) {
    userDefinedHandlerLambda.grantInvoke(frameworkLambda);

    /*
    lambda:GetFunction is needed as the framework Lambda use it to poll the state of User Defined
    Handler until it is ACTIVE state
     */
    frameworkLambda.addToRolePolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: ['lambda:GetFunction'],
      resources: [userDefinedHandlerLambda.functionArn],
    }));
  }
```
