### PR TITLE
fix(core): allow embedding condition expression as strings

### LINKED ISSUE #1984: Fn.conditionIf(...).toString() fails to serialize in Java
In CDK for Java 0.21.0, the `FnIf` condition extends `Token`, providing an implementation of `toString()` that performs as I expect: rendering the if-condition as    a CloudFormation token string:
```
{
  "Fn::If": [
    "Condition",
    "IfTrue",
    "IfFalse"
  ]
}
```
After v0.21.0, specifically in the latest version 0.25.2, the new `Fn.conditionIf` method returns an `IConditionExpression` which does *not* extend `Token` or        implement `toString()`.  As such, when calling `toString()` on the result of `Fn.conditionIf`, which is required to pass the result of the condition to any "props"   that expects a `String`, serializes the Java object directly:
```
"software.amazon.awscdk.IConditionExpression$Jsii$Proxy@3bbc39f8"
```

This makes CDK >0.21.0 unusable from Java if your stack expects to use "Fn::If".  I believe that [feat: cloudformation condition chaining (#1494)](https://github.com/awslabs/aws-cdk/commit/216901570d6b3772d98e5b45f9debe61b5da3418) switched from returning an `FnCondition`, which extended `CloudFormationToken`, to returning `IConditionExpression`.  Instead, it should simply have returned `FnConditionBase`, `CloudFormationToken`, or even just `String`.

### PR DESCRIPTION
**Pull request by eladb**
Expose the underlying `toString` in the `IConditionExpression` interface
so they can be embedded as string values in jsii languages.

Fixes #1984

----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

**Comment by eladb** [comment]
> Why not implicitly expose toString() for all objects, like is true in Java?

That's a good point. I will follow up with a PR in jsii to address this: https://github.com/awslabs/jsii/issues/380

I still think it makes sense to call this out here explicitly given the string tokensization behavior, no?

**Comment by rix0rrr** [comment]
I suppose

File: packages/@aws-cdk/cdk/lib/cloudformation/condition.ts [hunk 1]
```diff
@@ -74,4 +74,23 @@ export interface IConditionExpression {
...
+   * new sqs.Queue(this, 'MyQueue', {
+   *   queueName: Fn.conditionIf('Condition', 'Hello', 'World').toString()
+   * });
+   * ```
+   *
+   * NOTE: we need this explicitly here despite the fact that in JavaScript this would
+   * "just work" since conditions are eventually tokens that implement `toString`,
+   * in order for jsii languages like Java to proxy this to jsii.
+   */
+  toString(): string;
```
Comment (RomainMuller) [inline packages/@aws-cdk/cdk/lib/cloudformation/condition.ts]: Should this instead have extended some `IToken` interface? I wonder?

Comment (eladb) [reply packages/@aws-cdk/cdk/lib/cloudformation/condition.ts]: #79
