### PR TITLE
fix(s3): add validation for lifecycle rule transitions

### LINKED ISSUE #22103: (@aws-cdk/aws-s3): Add validation for lifecycleRules
### Describe the bug

When a bucket is initialised without either transitionDate or transitionAfter being set in lifecycleRules, the stack will build successfully but fail to deploy. Similarly, if both transitionDate and transitionAfter are set, it will fail to deploy as well.

### Expected Behavior

Should throw an error when both transitionDate and transitionAfter are undefined, or both are defined.

### Current Behavior

Build successfully, and got errors below during deployment
```
SampleBucket: creating CloudFormation changeset...
1:56:12 pm | CREATE_FAILED        | AWS::S3::Bucket    | sampleBucket
Exactly one of TransitionDate and TransitionInDays must be specified


 ❌  SampleBucket failed: Error: The stack named sampleBucket failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Exactly one of TransitionDate and TransitionInDays must be specified
    at prepareAndExecuteChangeSet (/Users/cdk/sample/node_modules/aws-cdk/lib/api/deploy-stack.ts:386:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at deployStack2 (/Users/cdk/sample/node_modules/aws-cdk/lib/cdk-toolkit.ts:240:24)
    at /Users/cdk/sample/node_modules/aws-cdk/lib/deploy.ts:39:11
    at run (/Users/cdk/sample/node_modules/p-queue/dist/index.js:163:29)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named sampleBucket failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Exactly one of TransitionDate and TransitionInDays must be specified
    at deployStacks (/Users/cdk/sample/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (/Users/cdk/sample/node_modules/aws-cdk/lib/cdk-toolkit.ts:312:7)
    at initCommandLine (/Users/cdk/sample/node_modules/aws-cdk/lib/cli.ts:349:12)

Stack Deployments Failed: Error: The stack named sampleBucket failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Exactly one of TransitionDate and TransitionInDays must be specified
```

### Reproduction Steps

Deploy the stack below
```
import { Stack, StackProps, aws_s3 as s3 } from "aws-cdk-lib";
import { Construct } from "constructs";

export class TestStack extends Stack {
  bucket: s3.Bucket;

  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    this.bucket = new s3.Bucket(this, "test-s3-bucket", {
      lifecycleRules: [
        {
          transitions: [{ storageClass: s3.StorageClass.GLACIER }],
        },
      ],
    });
  }
}

```

### Possible Solution

Add validation to cdk

### Additional Information/Context

_No response_

### CDK CLI Version

2.41.0

### Framework Version

2.41.0

### Node.js Version

16.13.1

### OS

Linux

### Language

Typescript

### Language Version

TypeScript(4.7.4)

### Other information

_No response_

### PR DESCRIPTION
**Pull request by scorbiere**
### Issue #22103

Closes #22103.

### Reason for this change

When configuring S3 bucket lifecycle rules with transitions, CloudFormation requires exactly one of `TransitionDate` or `TransitionInDays` to be specified. However, the CDK currently allows configurations where neither or both properties are specified, which leads to deployment failures. This change adds validation during synthesis to catch these invalid configurations earlier in the development process.

### Description of changes

This change adds validation during synthesis to ensure that exactly one of transitionDate or transitionAfter is specified in S3 bucket lifecycle rule transitions. Previously, this validation was only performed during deployment, leading to failed deployments when neither or both properties were specified.

The validation is added to the `parseLifecycleRule` function in the S3 bucket implementation, which checks each transition in the lifecycle rules.

### Describe any new or updated permissions being added

No new or updated IAM permissions are required for this change. This is purely a validation improvement in the CDK synthesis process.

### Description of how you validated changes

Added two unit tests to verify the validation:
1. A test that verifies an error is thrown when neither `transitionDate` nor `transitionAfter` is specified
2. A test that verifies an error is thrown when both `transitionDate` and `transitionAfter` are specified

Also ran integration tests to ensure that the change doesn't affect existing valid configurations. No snapshots were updated, confirming that the change only adds validation and doesn't modify the CloudFormation output for valid configurations.

### Checklist
- [X] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by 5d — APPROVED** [review]

File: packages/aws-cdk-lib/aws-s3/lib/bucket.ts [hunk 1]
```diff
@@ -2545,6 +2545,22 @@ export class Bucket extends BucketBase {
         throw new ValidationError('All rules for `lifecycleRules` must have at least one of the following properties: `abortIncompleteMultipartUploadAfter`, `expiration`, `expirationDate`, `expiredObjectDeleteMarker`, `noncurrentVersionExpiration`, `noncurrentVersionsToRetain`, `noncurrentVersionTransitions`, or `transitions`', self);
       }
 
+      // Validate transitions: exactly one of transitionDate or transitionAfter must be specified
+      if (rule.transitions) {
```
Comment (godwingrs22) [inline packages/aws-cdk-lib/aws-s3/lib/bucket.ts:2549]: nit: It will be good to update the README with the correct example [here](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-s3/README.md?plain=1#L856-L857)

**Comment by scorbiere** [comment]
Exemption Request: This change adds validation during synthesis to ensure that exactly one of transitionDate or transitionAfter is specified in S3 bucket lifecycle rule transitions. Previously, this validation was only performed during deployment, leading to failed deployments when neither or both properties were specified.

**Review by godwingrs22 — APPROVED** [review]
