### PR TITLE
fix(custom-resources): unable to use a resource attributes as dictionary keys in AwsCustomResource

### LINKED ISSUE #13063: (custom-resources): unable to use a tokens in dictionary keys in AwsCustomResource
### Reproduction Steps

In the following example, we are using `CfnJson` to render the request for a `dynamodb:BatchWriteItem` request. The reason `CfnJson` is needed is because this request has the table name as a dictionary key. Since table name can only be resolved during deployment, we need to pass it through `CfnJson` so it is serialized appropriately.

```ts
const table = new Table(this, 'MyDynamoTable', { partitionKey: { name: 'ID', type: AttributeType.STRING } });
const cfnJson = new CfnJson(this, 'Request', {
  value: {
    RequestItems: {
      [table.tableName]: [
        { PutRequest: { Item: { ID: { S: 'Item1' }, Value: { S: 'World' } } } },
        { PutRequest: { Item: { ID: { S: 'Item2' }, Value: { S: 'World' } } } }
      ]
    }          
  }
});

new AwsCustomResource(this, 'BatchWrite', {
  onCreate: {
    action: 'batchWriteItem',
    service: 'DynamoDB',
    physicalResourceId: PhysicalResourceId.of('PHYSICAL_RESOURCE_ID'),
    parameters: cfnJson,
  },
  policy: AwsCustomResourcePolicy.fromSdkCalls({ resources: [ table.tableArn ] })
});
```

### What did you expect to happen?

We expected "parameters" to resolve from the CfnJson custom resource's "Value" attribute:

```json
"parameters": { "Fn::GetAtt": [ "Request4BE5F30C", "Value" ] }
```

### What actually happened?

The output CloudFormation template renders like this:

```json
"parameters": {
  "Fn::Join": [
    "",
    [
      "{\"RequestItems\":{\"",
      {
        "Ref": "MyDynamoTableACB5AA21"
      },
      "\":[{\"PutRequest\":{\"Item\":{\"ID\":{\"S\":\"Item1\"},\"Value\":{\"S\":\"World\"}}}},{\"PutRequest\":{\"Item\":{\"ID\":{\"S\":\"Item2\"},\"Value\":{\"S\":\"World\"}}}}]}}"
    ]
  ]
}
```

### Environment

  - **CDK CLI Version  :** 1.89.0
  - **Framework Version:** 1.89.0
  - **Node.js Version:** v14.15.4
  - **OS               :** Mac
  - **Language (Version):** TypeScript

### Other

The root cause seems to be the fact that `encodeBoolean` calls `JSON.stringify()` on the parameters object [here](https://github.com/aws/aws-cdk/blob/83b8df8c390a27e10bf362f49babfb24ee425506/packages/%40aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts#L460), combined with the fact that `CfnJson` implements `toJSON()` [here](https://github.com/aws/aws-cdk/blob/92080a22fdda6f68d17a32a7efa27b841c8afcdb/packages/%40aws-cdk/core/lib/cfn-json.ts#L73), which returns the encoded JSON string of the /input/ instead of a token to the `Value` attribute.

I am not 100% sure why `toJSON()` of `CfnJson` does not return a token that resolves to the attribute, but I am also wondering if perhaps `AwsCustomResource` might be able to utilize a similar approach as `CfnJson` so to allow arbitrary JSON blobs in `parameters` without restrictions (basically the parameters field will need to be encoded as a string when passed to the AwsCustomResource handler).

## Workaround

As a workaround, one can dynamically replace the `toJSON()` method on the `CfnJson` object to:

```ts
cfnJson.toJSON = () => Stack.of(this).resolve(cfnJson);
```
--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by eladb**
AWS calls sometimes require to specify resource names or ARNs in dictionary keys (e.g. `dynamodb:BatchWriteItem`). Since resource attributes resolve only during deployment, we
expect to be able to pass them in dictionary keys. This does not work out of the box because JSON only allows strings in dictionary keys and attributes in CFN are modeled as JSON objects (`{ "Fn::GetAtt": ["X", "Y" ] }`, etc).

To address this, we simply encode `Create`, `Update` and `Delete` properties passed to the custom resource as token-aware JSON strings using `stack.toJsonString()`, and decode them in the custom resource.

Since the entire object is encoded, the special-casing for boolean encoding is no longer needed.

Additionally, we added support for `toJSON()` in the token resolution logic (`stack.resolve()`). If resolve encounters an object that has a `toJSON()` method, it will call it and continue resolution with the output value. This is needed here before `AwsCustomResource` uses this standard JS behavior to encode physical name references in requests.

We also made `CfnJson.value` public to allow directly accessing the referenced value in case it is needed (this could have been used as an alternative to the built-in support for token-aware stringification if we didn’t support it in AwsCustomResource) - see referenced issue.

Resolves #13063

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by eladb** [comment]
@jogold can you please take a look?

File: packages/@aws-cdk/core/lib/cfn-json.ts [hunk 1]
```diff
@@ -43,7 +43,7 @@ export class CfnJson extends CoreConstruct implements IResolvable {
    * Normally there is no need to use this property since `CfnJson` is an
    * IResolvable, so it can be simply used as a value.
    */
-  private readonly value: Reference;
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/cfn-json.ts:46]: See https://github.com/aws/aws-cdk/issues/13063 for some context no why this would have been needed if this fix was not introduced.

**Review by jogold — APPROVED** [review]

File: packages/@aws-cdk/core/lib/private/resolve.ts [hunk 2]
```diff
@@ -154,6 +154,13 @@ export function resolve(obj: any, options: IResolveOptions): any {
     throw new Error('Trying to resolve() a Construct at ' + pathName);
   }
 
+  // respect JavaScript's toJSON(): if the object has a toJSON() method, call it
+  // and continue with the returned value.
+  if ('toJSON' in obj && typeof(obj.toJSON) === 'function') {
```
Comment (rix0rrr) [inline packages/@aws-cdk/core/lib/private/resolve.ts:159]: This should not really be necessary and fills me with dread.

Comment (eladb) [reply packages/@aws-cdk/core/lib/private/resolve.ts:159]: Why does it fill you with dread?

Comment (rix0rrr) [reply packages/@aws-cdk/core/lib/private/resolve.ts:159]: * This is a finicky part of the code, and this change will touch a lot of runtime cases
* Token classes we use have a `toJSON` method, but it doesn't do anything meaningful (on purpose, because you can't/shouldn't use it!)
* This `toJSON` hook is being used in `CloudFormation.toJsonString()` to do some black magic
* I conceptually don't know how I feel about this change. Is `resolve()`ing the same as json-ifying? Feels like they should be two separate operations.

Is this so we can write:

```ts
const json = new CfnJson(this, 'Json', /* ... */);

useValue(json);
// instead of
useValue(json.jsonString);
```
?

Comment (rix0rrr) [reply packages/@aws-cdk/core/lib/private/resolve.ts:159]: Come to think of it... This code could just be doing what (for example) Sfn StateMachine is doing, or CW Dashboard is doing, right?

No need for any changes to the resolve protocol

Comment (rix0rrr) [reply packages/@aws-cdk/core/lib/private/resolve.ts:159]: And no need for CfnJson either?

Comment (eladb) [reply packages/@aws-cdk/core/lib/private/resolve.ts:159]: My mental model is that `resolve()` is designed to take only data (or tokens) as input. If you pass an object with e.g. methods or prototype to it, it will likely not do what you want. To that end, `toJSON()` is the JavaScript way to convert an object to data and as such I think it actually makes sense for `resolve()` to respect it. 

I added this _after_ we check if the value is a token, so tokens are handled before we get here. In this point of "resolve", we basically assume that the value is a "pure" data object.

This change actually surfaced a minor bug in [one of our tests] which to resolved a `PolicyStatement` object and the result was not an actual statement.

The reason this was needed here is not for `CfnJson` but because of how [`PhysicalResourceIdReference`](https://github.com/aws/aws-cdk/blob/762c8102d9315546f154047399be36d83a684127/packages/%40aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts#L17) is implemented in `AwsCustomResource`. It's a strong-type which represents a reference to the resource name and there's some encoding implemented via `toJSON()` for it in the custom resource protocol so it's possible to just use it anywhere in AWS API requests to plug in the reference to the resource name.

[one of our tests]: https://github.com/aws/aws-cdk/pull/13074/files#diff-8f1241f652c5d43f439b55aac2ac8edc274e48e6ff8d4a9ea020a29de5bc45d1L130

Comment (rix0rrr) [reply packages/@aws-cdk/core/lib/private/resolve.ts:159]: > It's a strong-type which represents a reference to the resource name and there's some encoding implemented via toJSON() for it in the custom resource protocol so it's possible to just use it anywhere in AWS API requests to plug in the reference to the resource name.

But effectively, implementing `IResolvable` for that class would do the same thing. Why don't we do that?

Comment (eladb) [reply packages/@aws-cdk/core/lib/private/resolve.ts:159]: I can implement IResolvable But I actually think this is moving us forward. 

The previous implementation used JSON.stringify and therefore used toJSON, and as I replaced it with stack.stringifyJson it broke. For me, it surfaced this gap in support in the resolve/stringifyJson path.

**Review by rix0rrr — APPROVED** [review]
I think the `toJSON` implementation is unnecessary, and could equally well be achieved by implementing `IResolvable` (I know implementing `IResolvable` is a bit of a chore because of the `stackTrace` requirement--but I'm not sure that alone is enough reason to ditch it).

That is the canonical way of having an object "render" to something else during `resolve()`.

Yes, we *could* use `toJSON` as an `IResolvable`-lite. But we don't really *need* to, so why should we?

----

I agree that having an arbitrary class object in the `resolve()` operation is a bad idea, because it will almost never do what you want. Probably a good enough reason to check if the object we have has an `object.constructor` which is not `Object`, and then throwing if it does AND it's not `IResolvable`.

----

I can *kinda* see the argument through my eyelashes that `toJSON` should be similar to `toString`, for implicit conversions.

The thing is that both of these methods have a well-defined meaning already. While `toString()` is established do implicit string conversions, `toJSON` is used in (and only in) the `JSON.stringify()`. It's not as "implicit" as `toString()` is already established to be... and I hesitate to make it thus. I'm afraid of unforeseen side effects when we start to combine this with other features.

----

In the interest of speeding things up: after having voiced my objections, I'm not going to block the review on this. The rest looks fine, I'll leave it up to you to decide whether or not this is a good idea.

File: packages/@aws-cdk/core/lib/private/resolve.ts (hunk 2 above)
Comment (eladb) [reply packages/@aws-cdk/core/lib/private/resolve.ts]: Just to summarize: we decided to use `IResolvable` in this PR and in add support for `toJSON()` in `resolve()` together with some additional checks afterwards to protect against passing non-data objects to `resolve()`.

File: packages/@aws-cdk/aws-cognito/test/integ.user-pool-client-explicit-props.expected.json [hunk 3]
```diff
@@ -27,9 +27,7 @@
           "EmailSubject": "Verify your new account",
           "SmsMessage": "The verification code to your new account is {####}"
         }
-      },
```
Comment (eladb) [inline packages/@aws-cdk/aws-cognito/test/integ.user-pool-client-explicit-props.expected.json:30]: I'll revert .

**Review by rix0rrr — APPROVED** [review]

**Comment by hughevans** [comment]
I guess this is what broke my use of `getResponseField()` on `AwsCustomResource` in `v1.92.0`.

So now I need to somehow use `CfnJson` to retrieve those values? It's not immediately clear to me how to do that.

<details>
  <summary>Broken custom resource</summary>

```
1:17:15 pm | UPDATE_FAILED        | AWS::IAM::Policy                    | …/WildcardCer...Role/DefaultPolicy
CustomResource attribute error: Vendor response doesn't contain HostedZone.Id key in object arn:aws:cloudformation:…
```

``` ts
// Allows CDK to use a reusable delegation set. Sourced from:
// https://pablissimo.com/1100/creating-a-route-53-public-hosted-zone-with-a-reusable-delegation-set-id-in-cdk

import {
  AwsCustomResource,
  AwsCustomResourcePolicy,
} from "@aws-cdk/custom-resources";
import { Construct, Fn, Names } from "@aws-cdk/core";
import {
  IPublicHostedZone,
  PublicHostedZone,
  PublicHostedZoneProps,
} from "@aws-cdk/aws-route53";
import { PhysicalResourceId } from "@aws-cdk/custom-resources";

export interface PublicHostedZoneWithReusableDelegationSetProps
  extends PublicHostedZoneProps {
  delegationSetId: string;
}

export class PublicHostedZoneWithReusableDelegationSet extends Construct {
  private publicHostedZone: AwsCustomResource;
  private hostedZoneName: string;

  constructor(
    scope: Construct,
    id: string,
    props: PublicHostedZoneWithReusableDelegationSetProps
  ) {
    super(scope, id);

    this.hostedZoneName = props.zoneName;

    const normaliseId = (id: string) => id.split("/").slice(-1)[0];
    const normalisedDelegationSetId = normaliseId(props.delegationSetId);

    this.publicHostedZone = new AwsCustomResource(
      this,
      "CreatePublicHostedZone",
      {
        onCreate: {
          service: "Route53",
          action: "createHostedZone",
          parameters: {
            CallerReference: Names.uniqueId(this),
            Name: this.hostedZoneName,
            DelegationSetId: normalisedDelegationSetId,
            HostedZoneConfig: {
              Comment: props.comment,
              PrivateZone: false,
            },
          },
          physicalResourceId: PhysicalResourceId.fromResponse("HostedZone.Id"),
        },
        policy: AwsCustomResourcePolicy.fromSdkCalls({
          resources: AwsCustomResourcePolicy.ANY_RESOURCE,
        }),
      }
    );

    new AwsCustomResource(this, "DeletePublicHostedZone", {
      onDelete: {
        service: "Route53",
        action: "deleteHostedZone",
        parameters: {
          Id: this.publicHostedZone.getResponseField("HostedZone.Id"),
        },
      },
      policy: AwsCustomResourcePolicy.fromSdkCalls({
        resources: AwsCustomResourcePolicy.ANY_RESOURCE,
      }),
    });
  }

  asPublicHostedZone(): IPublicHostedZone {
    return PublicHostedZone.fromHostedZoneAttributes(
      this,
      "CreatedPublicHostedZone",
      {
        hostedZoneId: Fn.select(
          2,
          Fn.split("/", this.publicHostedZone.getResponseField("HostedZone.Id"))
        ),
        zoneName: this.hostedZoneName,
      }
    );
  }
}
```
</details>

**Comment by charles-salmon** [comment]
The changes that were made here are actually breaking, from the perspective of `@aws-cdk/assert`. The [release notes](https://github.com/aws/aws-cdk/releases/tag/v1.92.0) don't currently make this clear (although I acknowledge that this is not a breaking change to any particular _feature_).

Specifically, this makes usage of the [`hasResourceLike`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/assert/lib/assertions/have-resource.ts#L37) function fairly awkward, if testing against specific properties under the `Create`, `Update` or `Delete` properties, given that these have now been encoded. Further, I believe this now enforces that tests must specify all properties in the same order as those that are output.

I see that a number of tests have been refactored as part of this PR to include the entire encoded contents of the `Create`, `Update` or `Delete` properties. I believe this potentially adds some fragility to the tests.

@rix0rrr Can you potentially comment as to whether or not implementing `IResolvable`, as opposed to encoding these properties, would alleviate these pains?

**Comment by seeebiii** [comment]
> Specifically, this makes usage of the hasResourceLike function fairly awkward, if testing against specific properties under the Create, Update or Delete properties, given that these have now been encoded. Further, I believe this now enforces that tests must specify all properties in the same order as those that are output.

In response to @charles-salmon , I had to go through this problem with tests defined in my constructs, e.g. [@seeebiii/ses-verify-identities](https://github.com/seeebiii/ses-verify-identities). Here's how I solved it in case anyone else faces this "breaking change":

## Simple Checks

If your custom resource parameters are rather simple and don't reference other resources, you can use a combination of `encodedJson()` and `objectLike()` (from `@aws-cdk/assert`) to verify the properties:

```typescript
// testing a custom resource using AwsCustomResource that is executing SES:deleteIdentity

expectCDK(stack).to(
    haveResourceLike('Custom::AWS', {
      Create: encodedJson(objectLike({
        service: 'SES',
        action: 'deleteIdentity',
        parameters: {
          Identity: emailAddress,
        },
      })),
    }),
  );
```

## Advanced Checks

In cases where your parameters reference other resources, CDK adds a `Fn::Join` to the `Create`/`Update`/`Delete` parameter and builds the JSON string by breaking it up into separate parts, so they can reference other resources. Here testing is a bit harder and I solved it using `deepObjectLike()` and `stringLike()` and `anything()` (you can get all from `@aws-cdk/assert`):

```typescript
// testing a custom resource using AwsCustomResource that is executing SES:setIdentityNotificationTopic

const domain = ...

expectCDK(stack).to(haveResourceLike('Custom::AWS', {
      Create: deepObjectLike({
        'Fn::Join': [
          '', [
            stringLike(`{\"service\":\"SES\",\"action\":\"setIdentityNotificationTopic\",\"parameters\":{\"Identity\":\"${domain}\",\"NotificationType\":\"Bounce\"*`),
            anything(),
            anything(),
          ],
        ],
      }),
    }));
```

This isn't pretty but it's enough in my case. You can use `stringLike()` by having a string with a glob pattern, e.g. `stringLike(foo*)`. I'm using `anything()` for the rest of the JSON string because I don't care about the remaining contents in this case.

I hope this helps anyone in case you run into the same problem when upgrading your CDK construct to 1.92.0.
