### PR TITLE
fix(cognito): quote or mime-encode `fromName` to comply RFC 5322

### LINKED ISSUE #18903: cognito/ses: "Provided From email address is invalid" when using email address for from_name
### What is the problem?

specifying an email address for a from_name parameter results in a broken Cfn parameter for `"From"`.

### Reproduction Steps

the following python code (but specific to cognito construct):

```
user_pool = cognito.UserPool(
            self,
           .
           .
           .
            email=cognito.UserPoolEmail.with_ses(
                ses_region="us-east-1",
                from_email="someemail@somedomain.edu",
                from_name="someemail@somedomain.edu",
                reply_to="someemail@somedomain.edu",
            ),
```

This results in the below behavior.

### What did you expect to happen?

Simply use the email address as the name.

### What actually happened?

resulted in the following Cfn template output:
```
"EmailConfiguration": {
          "EmailSendingAccount": "DEVELOPER",
          "From": "someemailaddr@somedomain.edu <someemailaddr",
          "ReplyToEmailAddress": "someemailaddr@somedomain.edu",
```

As you can see the `"From"` param is malformed likely due to a string manipulation/prune on the from_name cdk value.

### CDK CLI Version

1.142.0

### Framework Version

_No response_

### Node.js Version

v14.18.1

### OS

Linux/Ubuntu 20.04

### Language

Python

### Language Version

3.8.10

### Other information

Now, I know what you're going to say, "Don't put an email address where a name is expected", to which I will direct your attn to exhibit 1: in the AWS console if you navigate to the Messaging tab of the cognito user pool, the `FROM sender name` clearly shows an email address when configured manually. So, regardless of how strict the heuristics are for CDK/Cfn, they should align with what is allowable in the console. :-)

### PR DESCRIPTION
**Pull request by Tietew**
Closes #18903

When `fromName` of `UserPoolEmail.withSES()` does not comply RFC 5322 atom or quoted-string, it will be quoted or mime-encoded.

For example:
|`fromName`|Template|Description|
|-|-|-|
|`'simple atom'`|`"simple atom <address@example.com>"`|as is|
|`'"quoted string"'`|`"\"quoted string\" <address@example.com>"`|as is|
|`'あいう'`|`"=?UTF-8?B?44GC44GE44GG?= <address@example.com>"`|mime encode (RFC 2047)|
|`'name@company'`|`"\"name@company\" <address@example.com>"`|make quoted-string|

For details, see [RFC 5322 Section 3.4](https://www.rfc-editor.org/rfc/rfc5322#section-3.4) and [RFC 2047](https://www.rfc-editor.org/rfc/rfc2047)

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by Tietew** [comment]
I tried to update integration test but it failed with following error:
> Stack Deployments Failed: Error: The stack named integ-user-pool-signup-code failed to deploy: UPDATE_FAILED (The following resource(s) failed to update: [myuserpool01998219]. ): Cognito received the following error from Amazon SES when attempting to send email: Email address is not verified. The following identities failed the check in region US-EAST-1: arn:aws:ses:us-east-1:884577364007:identity/example.com (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: ef20db4e-9e68-49df-ae9c-7c174fe9cd37; Proxy: null)

I cannot verify `example.com` domain. How do I fix this?

**Comment by Tietew** [comment]
Is it acceptable to try following steps?
1. replace existing test's domain from `example.com` to my private domain which is SES verified in us-east-1
2. remove the old snapshot not to create a stack with `example.com` domain
3. run `yarn integ --update-on-failed`
4. confirm successful
5. replace the test's domain back to `example.com`
6. run `yarn integ --update-on-failed --dry-run` to recreate the snapshot including `example.com` domain

**Comment by TheRealAmazonKendra** [comment]
> Is it acceptable to try following steps?
> 
> 1. replace existing test's domain from `example.com` to my private domain which is SES verified in us-east-1
> 2. remove the old snapshot not to create a stack with `example.com` domain
> 3. run `yarn integ --update-on-failed`
> 4. confirm successful
> 5. replace the test's domain back to `example.com`
> 6. run `yarn integ --update-on-failed --dry-run` to recreate the snapshot including `example.com` domain

This is an excellent solution.

**Comment by Tietew** [comment]
`yarn integ --update-on-failed` succeeded with my private domain.

screenshot 2022-12-08 160233

**Review by corymhall — DISMISSED** [review]

**Comment by Tietew** [comment]
@corymhall Thank you for review! I refactored them to separate functions and more explanations.

File: packages/@aws-cdk/aws-cognito/lib/user-pool-email.ts [hunk 1]
```diff
@@ -202,3 +203,59 @@ function encodeAndTest(input: string | undefined): string | undefined {
     return undefined;
   }
 }
+
+/**
+ * Formats `fromName` to comply RFC 5322
+ *
+ * @see https://www.rfc-editor.org/rfc/rfc5322#section-3.4
+ */
+function formatFromName(fromName: string): string {
```
Comment (corymhall) [inline packages/@aws-cdk/aws-cognito/lib/user-pool-email.ts:212]: Thanks this is much easier to follow! The only question I have is how this
handles different types of quotes? Will it still work if you use `"` or ```

```ts
fromName: "'foo.bar'"
fromName: `'${someVar}'`
```

**Review by corymhall — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-cognito/lib/user-pool-email.ts (hunk 1 above)
Comment (Tietew) [reply packages/@aws-cdk/aws-cognito/lib/user-pool-email.ts:212]: Per RFC 5322, both the single quote `'` and the backquote ``` ` ``` are "atext". They are same as alphabet/digit letters. But surprising, the dot `.` is a "specials".

```
   atext           =   ALPHA / DIGIT /    ; Printable US-ASCII
                       "!" / "#" /        ;  characters not including
                       "$" / "%" /        ;  specials.  Used for atoms.
                       "&" / "'" /
                       "*" / "+" /
                       "-" / "/" /
                       "=" / "?" /
                       "^" / "_" /
                       "`" / "{" /
                       "|" / "}" /
                       "~"
```

Note: White space is not defined as "atext", but also allowed.

Examples:

| source | template | cause |
|-|-|-|
| `"'foo.bar'"` | quoted-string<br>`"From": "\"'foo.bar'\" <addr@example.com>"` | the dot `.` is "specials" |
| `"'foo bar'"` | bare<br>`"From": "'foo bar' <addr@example.com>"` | all chars are "atext" |
| `"Foo's Bar"` | bare<br>`"From": "Foo's Bar <addr@example.com>"` | all chars are "atext" |
| `'${price}'` | bare<br>`"From": "${price} <addr@example.com>"` | all chars are "atext" | 
| ``` "`foo bar`" ``` | bare<br>``` "From": "`foo bar` <addr@example.com>" ``` | all chars are "atext" |
| `'Café'` | mime encode<br>`"From": "=?UTF-8?B?Q2Fmw6k=?= <addr@example.com>"` | `é` is not US-ASCII |
| `'"Café"'` | entire `"Café"` including double quote `"` is mime encoded<br>`"From": "=?UTF-8?B?IkNhZsOpIg==?= <addr@example.com>"` | `é` is not US-ASCII |
| ``` `'${someVar}'` ``` | mime encode if `someVar` is not US-ASCII<br>quoted-string if `someVar` includes "specials"<br>otherwise, as-is | ``` `~` ``` is evaluated at runtime<br>single quote `'` is atext |
| ``` `"${someVar}"` ``` | mime encode if `someVar` is not US-ASCII<br>quoted-string again if `someVar` includes malformed escape<br>otherwise, as-is | already quoted-string form

**Review by corymhall — APPROVED** [review]
