### PR TITLE
fix(core): `isTaggable` function can return undefined instead of false

### LINKED ISSUE #26495: aws-cdk-lib.TagManager: (is_taggable function stopped working in while migrating from 2.70.0 to 2.88.0)
### Describe the bug

aws-cdk-lib.TagManager.is_taggable has stopped working wth cdk python version 2.88.0 with the below error message
Screenshot 2023-07-25 at 16 40 33

### Expected Behavior

it should just return the boolean value during the runtime.

### Current Behavior

just fails with the error message as in the screenshot.

### Reproduction Steps

Try to run synth after migrating to the cdk version2.88.0, it will through the same error message as in the screenshot attached.

### Possible Solution

It was working since cdk 2.0 not sure what has changed behind the scen..i see new method called is_taggable_v2 being added to the TagManager class using this will not break the code but it will remove the existing tags.

### Additional Information/Context

_No response_

### CDK CLI Version

2.88.0

### Framework Version

_No response_

### Node.js Version

14.17.6

### OS

macos: ventura 13.5 

### Language

Python

### Language Version

3.8.8

### Other information

_No response_

### PR DESCRIPTION
**Pull request by sumupitchayan**
Closes #26495 

### Reason for this change

The `isTaggable` function of the `TagManager` class is currently broken in Python, as it can return `undefined` instead of `true` or `false`.

### Description of changes

In JS/TS, the logical AND operator (`&&`) returns the first falsy value it encounters, even if that value is `undefined` instead of `false` - so the current implementation of `isTaggable` allows for `undefined` to be returned if `tags` is undefined:

```ts
public static isTaggable(construct: any): construct is ITaggable {
  const tags = (construct as any).tags;
  return tags && typeof tags === 'object' && (tags as any)[TAG_MANAGER_SYM];
}
```

The fix is simply changing the return line to the following to handle cases where tags is `null` or `undefined`:

```ts
return tags !== undefined && tags !== null && typeof tags === 'object' && (tags as any)[TAG_MANAGER_SYM];
```

### Description of how you validated changes

Added a unit test to assert that `isTaggable` returns `false`, not `undefined` for a non-taggable Construct (and still returns `true` for a taggable construct).

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/core/lib/tag-manager.ts [hunk 1]
```diff
@@ -303,7 +303,7 @@ export class TagManager {
    */
   public static isTaggable(construct: any): construct is ITaggable {
     const tags = (construct as any).tags;
-    return tags && typeof tags === 'object' && (tags as any)[TAG_MANAGER_SYM];
+    return typeof tags === 'object' && (tags as any)[TAG_MANAGER_SYM];
```
Comment (rix0rrr) [inline packages/aws-cdk-lib/core/lib/tag-manager.ts:306]: But this now explodes if `tags` is `null`. It shouldn't be, but it could be.

Sillily, in JS it's:

```
typeof null == 'object'
```

So you can't really get away from the truthiness test. The only thing you have to do is make sure the truth-tested falsy value doesn't leak through.

**Review by rix0rrr — CHANGES_REQUESTED** [review]

File: packages/aws-cdk-lib/core/lib/tag-manager.ts (hunk 1 above)
Comment (sumupitchayan) [reply packages/aws-cdk-lib/core/lib/tag-manager.ts]: Good to know - just updated the return statement:

```ts
return tags !== undefined && tags !== null && ...
```
