### PR TITLE
fix(codebuild): Rename includeBuildID property of S3BucketBuildArtifacts

### LINKED ISSUE #1347: S3BucketBuildArtifacts ignoring "withIncludeBuildId" value
When creating an S3BucketBuildArtifacts instance, using the S3BucketBuildArtifactsProps.builder() methods, specifically the `withIncludeBuildId`, it doesn't matter if I set the property to `true` or `false`.  When I execute `cdk synth` on my Stack, the Artifact always indicates a `NamespaceType: BUILD_ID`.  I'd like that to be "None".

Code snippet:
```
S3BucketBuildArtifacts codebuildS3BucketBuildArtifacts = new S3BucketBuildArtifacts(
	S3BucketBuildArtifactsProps.builder()
		.withBucket(deploymentBucket)
		.withPath("Workflow-Path")
		.withName("Workflow-Name")
		.withPackageZip(Boolean.FALSE)
		.withIncludeBuildId(Boolean.FALSE)  // doesn't matter what I put here...
		.build())
```
Thanks for any help/advice.

### PR DESCRIPTION
**Pull request by RomainMuller**
The property name ending with `ID` caused a mismatch of names to appear
in non-TypeScript languages, as the name translation rules would convert
back to `Id`.

BREAKING CHANGE: the `includeBuildID` property of
`S3BucketBuildArtifacts` was renamed to `includeBuildId` (note the
lower-case trailing `d`).

Fixes #1347

----

### Pull Request Checklist

Please check all boxes, including N/A items:

#### Testing

- [ ] Unit test and/or integration test added
- [ ] __Toolkit change?:__ [integration tests](https://github.com/awslabs/aws-cdk/blob/master/packages/aws-cdk/integ-tests/test.sh) manually executed (paste output to the PR description)
- [ ] __Init template change?:__ coordinated update of integration tests (currently maintained in a private repo).

#### Documentation

- [ ] __README__: README and/or documentation topic updated
- [ ] __jsdocs__: All public APIs documented

### Title and description

- [X] __Change type__: Title is prefixed with change type:
  * `fix(module): <title>` bug fix (_patch_)
  * `feat(module): <title>` feature/capability (_minor_)
  * `chore(module): <title> ` won't appear in changelog
  * `build(module): <title>` won't appear in changelog
- [X] __Title format__: Title uses lower case and doesn't end with a period
- [X] __Breaking change?__: Last paragraph of description is: `BREAKING CHANGE: <describe exactly what changed and how to achieve similar behavior + link to documentation/gist/issue if more details are required>`
- [X] __References__: Indicate issues fixed via: `Fixes #xxx` or `Closes #xxx`

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-codebuild/lib/artifacts.ts [hunk 1]
```diff
@@ -30,6 +30,8 @@ export abstract class BuildArtifacts {
 
   public toArtifactsJSON(): cloudformation.ProjectResource.ArtifactsProperty {
     const artifactsProp = this.toArtifactsProperty();
+    // tslint:disable-next-line
```
Comment (eladb) [inline packages/@aws-cdk/aws-codebuild/lib/artifacts.ts]: delete

Comment (RomainMuller) [reply packages/@aws-cdk/aws-codebuild/lib/artifacts.ts]: Duh.
