### PR TITLE
fix(ecs): cannot disable container insights of an ECS cluster

### LINKED ISSUE #9149: [ecs] Cannot disable containerInsights of a cluster whose setting is enabled
I tried disabling containerInsights of an ECS cluster but it failed.
It seems CFn doesn't support removing the setting but replacing.

### Reproduction Steps
1. deploy a cluster with containerInsights enabled:

```ts
new ecs.Cluster(this, "cluster", {
    clusterName: "cluster",
    vpc: vpc,
    containerInsights: true,
});
```

2. re-deploy the cluster after switching containerInsights to disabled:
```ts
new ecs.Cluster(this, "cluster", {
    clusterName: "cluster",
    vpc: vpc,
    containerInsights: false,
});
```

c.f. cdk diff when deploying in 2nd step

```
Resources
[~] AWS::ECS::Cluster cluster cluster611F8AFF 
 └─ [-] ClusterSettings
     └─ [{"Name":"containerInsights","Value":"enabled"}]
```

### Error Log
When deploying in 2nd step, an error occurs:

```
11:34:57 | UPDATE_FAILED        | AWS::ECS::Cluster       | cluster611F8AFF
Error occurred during operation 'Settings can only be modified, not removed. Required Settings: [containerInsights]'.
```

### Environment

  - **CLI Version      :1.50.0**
  - **Framework Version:1.50.0**
  - **Node.js Version:v13.11.0** 
  - **OS               :macOS 10.15.4**
  - **Language (Version): TypeScript** 

### Other
The cdk diff is supposed to be below:

```
[~] AWS::ECS::Cluster cluster cluster611F8AFF 
 └─ [~] ClusterSettings
     └─ @@ -1,6 +1,6 @@
        [ ] [
        [ ]   {
        [ ]     "Name": "containerInsights",
        [-]     "Value": "enabled"
        [+]     "Value": "disabled"
        [ ]   }
        [ ] ]
```

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by tmokmss**
fixes #9149 

The clusterSettings should be explicitly defined even when container insights is disabled, because CFn doesn't allow to remove the existing settings (as described in the issue.)

By this change, users who sets `containerInsights` prop `false` will see a diff like below, but it won't be a problem because by default container insights is disabled hence no actual change to existing resources: 

```
Resources
[~] AWS::ECS::Cluster cluster cluster611F8AFF 
 └─ [+] ClusterSettings
     └─ [{"Name":"containerInsights","Value":"disabled"}]
```

To prevent the existing tests from failing, the clusterSettings is only defined when `containerInsight` prop is explicitly defined(i.e. `true` or `false`, not `undefined`.)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by tmokmss** [comment]
@allisaurus @uttarasridhar 
Hi, is there any obstacle to merge this PR? I'd like to fix them if any.
Thanks.

File: packages/@aws-cdk/aws-ecs/lib/cluster.ts [hunk 1]
```diff
@@ -124,8 +124,10 @@ export class Cluster extends Resource implements ICluster {
       physicalName: props.clusterName,
     });
 
-    const containerInsights = props.containerInsights !== undefined ? props.containerInsights : false;
-    const clusterSettings = containerInsights ? [{ name: 'containerInsights', value: 'enabled' }] : undefined;
+    let clusterSettings = undefined;
+    if (props.containerInsights !== undefined) {
+      clusterSettings = [{ name: 'containerInsights', value: props.containerInsights ? 'enabled' : 'disabled' }];
+    }
```
Comment (SoManyHs) [inline packages/@aws-cdk/aws-ecs/lib/cluster.ts:130]: What do you think about constantizing the allowed values for the `containerInsights` setting? i.e.

```
export enum ContainerInsights {
  /**
   * Enable CloudWatch Container Insights will be enabled for the cluster
   */,

  ENABLED = 'enabled',

  /**
   * Disable CloudWatch Container Insights will be enabled for the cluster
   */,
  DISABLED = 'disabled',
}
```

And since the default is to disable container insights, we can not worry about whether `clusterSettings` is undefined so maybe:

```suggestion
    const containerInsights = props.containerInsights !== undefined ? props.containerInsights : false;
    // Explicitly set containerInsights as 'enabled' or 'disabled'
    const containerInsightsSetting = containerInsights ? ContainerInsights.ENABLED : ContainerInsights.DISABLED;
    const clusterSettings = [{ name: 'containerInsights', value: containerInsightsSetting }]


```

File: packages/@aws-cdk/aws-ecs/test/test.ecs-cluster.ts [hunk 2]
```diff
@@ -1457,7 +1457,27 @@ export = {
     test.done();
   },
 
-  'default container insights undefined'(test: Test) {
+  'disable container insights'(test: Test) {
```
Comment (SoManyHs) [inline packages/@aws-cdk/aws-ecs/test/test.ecs-cluster.ts:1460]:
```suggestion
  'disable container insights by default'(test: Test) {
```

**Review by SoManyHs — COMMENTED** [review]
LGTM! Just a small suggestion!

**Review by SoManyHs — APPROVED** [review]

File: packages/@aws-cdk/aws-ecs/test/test.ecs-cluster.ts [hunk 3]
```diff
@@ -1457,7 +1457,27 @@ export = {
...
+          Name: 'containerInsights',
+          Value: 'disabled',
+        },
+      ],
+    }, ResourcePart.Properties));
+
+    test.done();
+  },
+
+  'default container insights is disabled'(test: Test) {
```
Comment (SoManyHs) [inline packages/@aws-cdk/aws-ecs/test/test.ecs-cluster.ts:1480]:
```suggestion
  'default container insights is undefined'(test: Test) {
```

**Comment by tmokmss** [comment]
Finally! Thanks for approving the PR!

**Comment by SoManyHs** [comment]
@tmokmss Thank you so much for contributing! And apologies about the long delay 🙇‍♀️ Really appreciate your work!!
