### PR TITLE
fix(core): Access Denied using legacy synthesizer with new bootstrap

### LINKED ISSUE #9607: [cdk-pipelines] shellable and s3-deployments in a legacy stack don't work with new bootstrap resources
New bootstrap bucket is encrypted, but legacy apps have no knowledge of the fact that buckets even COULD be encrypted and won't ever add `kms:Decrypt` permission to roles using assets.

Not a problem for Lambdas, but is a problem for in-line roles trying to read file assets.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
We always intended the FileAsset KMS Key to be transparently
usable by any IAM identity allowed to read from and write to the
FileAsset Bucket. We incorrectly implemented this, however.

We used to use the following key policy:

```
     - Action: [...]
       Principal: { AWS: "123456789012" }
       Condition:
         StringEquals:
           kms:ViaService: Fn::Sub: s3.${AWS::Region}.amazonaws.com
```

And this was intended to mean "any identity from the given account". That is *not* how KMS interprets it, though.

`Principal: { AWS: "123456789012" }` is equivalent to `Principal: { AWS: "arn:aws:iam::123456789012:root" }`,
and `arn:aws:iam::123456789012:root` is a principal which is treated
in a special way by KMS, and it means "use the caller's IAM Identity Policy instead".

So while I was under the impression that it was strictly necessary for
KMS usage permissions to exist both on the key and on the identity, this
is only true if you use the `arn:aws:iam::123456789012:root` principal.

The correct way to express the condition we had intended to express was
instead to use a condition called `kms:CallerAccount` in combination
with the principal `*`:

```
     - Action: [...]
       Principal: { AWS: "*" }
       Condition:
         StringEquals:
           kms:CallerAccount: "123456789012"
           kms:ViaService: Fn::Sub: s3.${AWS::Region}.amazonaws.com
```

This PR changes the key policy in the bootstrap resources to use the
policy that we always had intended. This now gets rid of the requirement
for IAM identities to list `kms:Decrypt` in their role policy, and so
gets rid of the requirement for them to know the KMS key ARN.

This makes the stack synthesized by the legacy stack synthesizer work
with the new bootstrap stack, and also removes the need for the new
synthesizer to import the KMS key ARN using `Fn::ImportValue`.

---

However, the new stack synthesizer *does* now require that you have
the newest bootstrap stack installed, and since templates are likely
deployed using a pipeline, the CLI is not involved to do the
`MINIMUM_BOOTSTRAP_STACK` version check.

Originally I had intended to use the version `Export` to add version
checking to the template, but that doesn't actually work for 2 reasons:

- `Fn::ImportValue` can only occur in a limited set of positions in
  the CloudFormation template.
- If an `Export` is used by a Stack, it cannot be changed anymore. That
  means that even if we had done the check using `Fn::ImportValue`,
  users wouldn't have been allowed to update the bootstrap stack
  anymore.

What we should have done from the start, and what this PR
introduces, is storing the bootstrap stack version in an SSM Parameter
Store Parameter. This value can be inspected in a CloudFormation
**Rules** section, which will produce a readable error message
about why the template cannot be deployed.

Any assertion failure reasons will be reported on a
`ROLLBACK_IN_PROGRESS` event, so classify those appropriately
in the stack monitor so the error message gets displayed.

Fixes #9607.

BREAKING CHANGE: (cdk-pipelines) users of CDK Pipelines (and other users
of the new stack synthesizer) will need to update their bootstrap stack
by running `cdk bootstrap` with the new CLI. Until they do, deployments
will fail with the error: `Unable to fetch parameters
[/aws-cdk-bootstrap/hnb659fds/version]`

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts [hunk 1]
```diff
@@ -462,3 +465,38 @@ function stackLocationOrInstrinsics(stack: Stack) {
...
+    type: 'AWS::SSM::Parameter::Value<String>',
+    description: 'Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store.',
+    default: `/CdkBootstrap/${qualifier}/Version`,
+  });
+
+  // There is no >= check in CloudFormation, so we have to check the number
+  // is NOT in [1, 2, 3, ... <required> - 1]
+  const oldVersions = range(1, requiredVersion).map(n => `${n}`);
+
+  new CfnRule(stack, 'CheckBootstrapVersion', {
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts:486]: TIL. Very cool

File: packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml [hunk 2]
```diff
@@ -350,6 +353,15 @@ Resources:
...
       RoleName:
         Fn::Sub: cdk-${Qualifier}-cfn-exec-role-${AWS::AccountId}-${AWS::Region}
+  # The SSM parameter is used in pipeline-deployed templates to verify the version
+  # of the bootstrap resources.
+  CdkBootstrapVersion:
+    Type: AWS::SSM::Parameter
+    Properties:
+      Type: String
+      Name:
+        Fn::Sub: '/CdkBootstrap/${Qualifier}/Version'
```
Comment (eladb) [inline packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml:363]: I think ssm parameters are conventionally lower case. Also, please add `aws` somewhere. Maybe:

```
/aws-cdk-bootstrap/${qualifier}/version
```

File: packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml [hunk 3]
```diff
@@ -359,6 +371,9 @@ Outputs:
     Description: The domain name of the S3 bucket owned by the CDK toolkit stack
     Value:
       Fn::Sub: "${StagingBucket.RegionalDomainName}"
+  # @deprecated - This Export can be removed at some future point in time.
+  # We can't do it today because if there are stacks that use it, the bootstrap
+  # stack cannot be updated. Not used anymore by apps >= 1.60.0
   FileAssetKeyArn:
     Description: The ARN of the KMS key used to encrypt the asset bucket
```
Comment (eladb) [inline packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml:378]: Add `(deprecated)` in the description perhaps?

File: packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml [hunk 4]
```diff
@@ -373,10 +388,9 @@ Outputs:
     Description: The name of the ECR repository which hosts docker image assets
     Value:
       Fn::Sub: "${ContainerAssetsRepository}"
+  # The Output is used by the CLI to verify the version of the bootstrap resources.
```
Comment (eladb) [inline packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml:391]: Do we really need this to be validated both by CFN and the CLI? Maybe we can omit the CLI now?

File: packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts [hunk 5]
```diff
@@ -354,7 +354,7 @@ abstract class ActivityPrinterBase implements IActivityPrinter {
       this.resourcesInProgress[activity.event.LogicalResourceId] = activity;
     }
 
-    if (status.endsWith('_FAILED')) {
+    if (hasErrorMessage(status)) {
```
Comment (eladb) [inline packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts:357]: This is not related, right?

**Review by eladb — APPROVED** [review]
We should synthesize the bootstrap template from a CDK app (still maintain it as a template and use L1s, but I don't see a good reason not to use CDK to define it and avoid duplicates and stuff).

File: packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml (hunk 4 above)
Comment (rix0rrr) [reply packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml:391]: CLI also does the check before uploading assets and, in the future, before querying context. 

Even if we start reading the SSM parameter today (which is not a bad idea) we'll still need the the CLI to support old bootstrap stacks.

File: packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts (hunk 5 above)
Comment (rix0rrr) [reply packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts:357]: It is, it's to make the "failed assertion" messages properly show up in the stack monitor. Otherwise the only thing you see is `ROLLBACK_COMPLETE` which is not very helpful.

Comment (eladb) [reply packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts:357]: Cool beans

File: packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts [hunk 6]
```diff
@@ -462,3 +465,38 @@ function stackLocationOrInstrinsics(stack: Stack) {
...
+ * Add a CfnRule to the Stack which checks the current version of the bootstrap stack this template is targeting
+ *
+ * The CLI normally checks this, but in a pipeline the CLI is not involved
+ * so we encode this rule into the template in a way that CloudFormation will check it.
+ */
+function addBootstrapVersionRule(stack: Stack, requiredVersion: number, qualifier: string) {
+  const param = new CfnParameter(stack, 'BootstrapVersion', {
+    type: 'AWS::SSM::Parameter::Value<String>',
+    description: 'Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store.',
+    default: `/aws-cdk-bootstrap/${qualifier}/version`,
```
Comment (NetaNir) [inline packages/@aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts:479]: Shouldn't this be a version number?
