### PR TITLE
fix(cli): can't use credential providers for stacks with assets

### LINKED ISSUE #7005: cdk-assets does not honour plugins of type CredentialProviderSource
With the introduction of the new assets manager in 1.29.0 publishing assets seems to now require a separate authentication workflow, specifically a CredentialProviderSource plugin that the main cdk-cli is configured to use, will be ignored.

This is breaking a contract from previous versions that CredentialProviderSource plugins can be used to assume required permissions for the whole of the deployment process.

### Reproduction Steps
Sorry, no code yet, but here's the step.

1. Create a minimal Stack with cdk 1.28.0
2. Add at least one asset to be uploaded.
3. Ensure NO credentials are setup at all
4. `cdk deploy` will fail
5. Add a CredentialProviderSource, e.g. one that hardcodes a secret access key
6. `cdk deploy` will now pass
7. Upgrade to cdk 1.29.0 or above
8. `cdk deploy` should fail with error message like below
### Error Log
[0%] start: Publishing 3aaa0e2f3b491f430fd098334ea6c4ec62dc3b5bec0c426c6e14e59b3a656a35:current
[50%] fail: AWS credentials are required to upload assets. Please configure environment variables or ~/.aws/credentials.
[50%] start: Publishing 5741f85917ffca30b209ad61e375d3d3bae0457270071f7aca8ca81be19bd22a:current
[100%] fail: AWS credentials are required to upload assets. Please configure environment variables or ~/.aws/credentials.

### Environment

  - **CLI Version      : 1.29.0**
  - **Framework Version:  1.29.0**
  - **OS               : macOS**
  - **Language         : Typescript**

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rix0rrr**
Stacks with assets were broken for environments that completely
used credential providers (and no other sources of AWS credentials).

Not because the wrong credentials were being used (as you would expect
it to be broken). Instead, an error was being thrown because the
"current" account lookup was incorrectly forwarding to the "default"
account lookup (fix: we know what the current account is. Just return
that instead).

What's worse, this value wasn't even being used! It was being looked up
so that if something was wrong finding the target bucket, we could
format a nice error message containing the account id. Even happy
paths were failing due to the premature lookup though (fix: only
look up when we actually need the value).

Fixes #7005.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk/lib/util/asset-publishing.ts [hunk 1]
```diff
@@ -33,15 +40,18 @@ class PublishingAws implements cdk_assets.IAws {
...
+    return this.targetEnv.region;
   }
 
   public async discoverCurrentAccount(): Promise<cdk_assets.Account> {
+    // Try to discover the current partition given default credentials. If we
+    // don't have "default" credentials, (such as when we're using a
+    // CredentialProvider), then we'll just guess the partition to be 'aws'. Our
+    // credential provider protocol currently doesn't provide for partition
+    // information.
     const account = await this.aws.defaultAccount();
```
Comment (eladb) [inline packages/aws-cdk/lib/util/asset-publishing.ts]: Shouldn't that be based on `this.targetEnv.account` instead of `defaultAccount`?

Comment (rix0rrr) [reply packages/aws-cdk/lib/util/asset-publishing.ts]: It should. I was making a simplification with a plan to fix it later. But we could just take the current configuration to look up the partition anyway.

It'll be less efficient but more correct.
