### PR TITLE
fix(ec2-alpha): readme updates, new unit tests, logic update

### LINKED ISSUE #30762: Tracking: Full Control VPC
### Overview

Full Control VPC provides feasibility to add custom route table and subnets to your network with the support of creating your VPC with Ipv6 Addresses.

The main components of this VPC construct is:

- Add Secondary Address to the VPC
- IP address allocation using AWS IPAM
- Subnets With Custom IP range
- Custom Routing Support with Gateways

### Link to the service’s CDK Construct Library API reference page.

https://github.com/aws/aws-cdk-rfcs/blob/57fd92a7f20e242b96885264c12567493f5e867f/text/0507-subnets.md

### Maturity: CloudFormation Resources Only

Experimental

### Implementation

###Features and Support

### VPC

| Done | Item | Needed for Graduation | Link to issue or docs |
| ---- | ---- | ---- | ---- |
| ✔️| Support for Secondary Address Ipv4 | ✔️ | |
| ✔️| Support for Secondary Address Ipv6 | ✔️ | |
| ✔️| Provision IP address using IPAM IPv4 | ✔️ | |
| ✔️| Provision IP address using IPAM IPv6(Amazon-Owned) Addresses  | ✔️ | |
| ✔️| Validation of Secondary Ipv4 address per RFC1918 range | ✔️ | |
| ✔️| Create VPC using BYOIP Ipv6 | ✔️ | |
|✔️ | Import existing VPC to this construct| ✔️ | |
| ✔️| Add Tagging capabilites to VPC and its components| ✔️| |

### Subnet
| Done | Item | Needed for Graduation | Link to issue or docs |
| ---- | ---- | ---- | ---- |
| ✔️| Support for custom Ipv4 range in subnet  | ✔️ | |
| ✔️| Support for custom Ipv6 range in subnet  | ✔️ | |
| ✔️| (Public Subnet) Construct Implementation of Nat and Internet Gateway| ✔️ | |
| ✔️| Validation for overlapping IP ranges |  ✔️| |
| ✔️| Validation for IP range lies within VPC range | ✔️ | |
| ✔️ | Support for custom Ipv6 range(BYOIP) in subnet  | ✔️ | |
| | Support for direct IPAM allocation in subnet | X | |

### Routing
| Done | Item | Needed for Graduation | Link to issue or docs |
| ---- | ---- | ---- | ---- |
| ✔️ | Route L2 construct | ✔️ | |
| ✔️ | RouteTable L2 construct | ✔️ | |
| ✔️ | Egress-only internet gateway L2 construct | ✔️ | |
| ✔️ | VPN gateway L2 construct | ✔️ | |
| ✔️ | Internet gateway L2 construct | ✔️ | |
| ✔️ | NAT gateway L2 construct | ✔️ | |
| ✔️ | VPC peering connection L2 construct | ✔️  | |
|  | Network interface L2 construct |  | |
| ✔️ | Compatability with existing VPC endpoint constructs | ✔️ | |
| | Transit gateway L2 construct | ✔️ | |
|X | Carrier gateway L2 construct |X | |

### Issue list

- [5927] (https://github.com/aws/aws-cdk/issues/5927)

### PR DESCRIPTION
**Pull request by shikha372**
### Issue # (if applicable)

Closes #30762 .

### Reason for this change

Adding more unit tests to meet the global coverage before module graduation to `developer-preview`.

### Description of changes

- Add more unit test case to cover all `if branches` test cases.

- As per the discussion with service team, added optional field under IGW to allow users to choose the subnets for gateway routing, as there can be Public Subnet without an IGW attached( eg. using VPNGW to access internet).

- Update IPAM README to higlight the problem of IPAM pool deletion as discussed with service team.

- Update SubnetV2 README to higlight that a custom route table is being created through CDK.

### Describe any new or updated permissions being added

No changes to IAM permissions.

### Description of how you validated changes

`yarn build`
`yarn test`

```
yarn run v1.22.21
$ cdk-test
PASS test/ipam.test.ts
PASS test/subnet-v2.test.ts
PASS test/vpc-tagging.test.ts
PASS test/util.test.ts
PASS test/route.test.ts
PASS test/vpc-add-method.test.ts
PASS test/vpcv2-import.test.ts
PASS test/vpc-v2.test.ts

=============================== Coverage summary ===============================
Statements   : 89.88% ( 640/712 )
Branches     : 81.68% ( 223/273 )
Functions    : 82.6% ( 133/161 )
Lines        : 89.89% ( 614/683 )
================================================================================

Test Suites: 8 passed, 8 total
Tests:       126 passed, 126 total
Snapshots:   0 total
Time:        2.244 s
Ran all test suites.

Verifying integration test snapshots...

  UNCHANGED  integ.byoip-ipv6 0.888s
  UNCHANGED  integ.ipam 0.928s
  UNCHANGED  integ.subnet-v2 1.036s
  UNCHANGED  integ.vpc-v2-alpha 1.047s
  UNCHANGED  integ.test-import 1.053s
  UNCHANGED  integ.peering-cross-account 1.101s
  UNCHANGED  integ.vpc-v2-tagging 1.264s
  UNCHANGED  integ.route-v2 1.29s

Snapshot Results: 

Tests:    8 passed, 8 total
Tests successful. Total time (4.5s) | /Users/shikagg/vpc_peering/aws-cdk/node_modules/jest/bin/jest.js (2.7s) | integ-runner (1.8s)
✨  Done in 4.87s.
```

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

BREAKING CHANGE: `operatingRegion` property under IPAM class is now renamed to `operatingRegions`.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-ec2-alpha/lib/ipam.ts [hunk 1]
```diff
@@ -514,7 +514,7 @@ export class Ipam extends Resource {
     if (props?.ipamName) {
```
Comment (samson-keung) [inline packages/@aws-cdk/aws-ec2-alpha/lib/ipam.ts:514]: Is it possible for `ipamName` to be a token?

File: packages/@aws-cdk/aws-ec2-alpha/lib/ipam.ts [hunk 2]
```diff
@@ -514,7 +514,7 @@ export class Ipam extends Resource {
...
       Tags.of(this).add(NAME_TAG, props.ipamName);
     }
-    if (!props?.operatingRegion && !Stack.of(this).region) {
+    if (!props?.operatingRegion && Token.isUnresolved(Stack.of(this).region)) {
```
Comment (samson-keung) [inline packages/@aws-cdk/aws-ec2-alpha/lib/ipam.ts:517]: 2 questions:

1. The `!props?.operatingRegion` condition catch the case where the `operatingRegion` prop is not provided by user (i.e. value being `undefined`). What if `operatingRegion` is an empty array?
2. For the 2nd condition, why do we add `Token.isUnresolved`? I would thought that if user is not providing any regions, then we can use `Stack.of(this).region`, even if it is a token. I see further down on line 521 that token is allowed as a value assigned to `this.operatingRegions`.

File: packages/@aws-cdk/aws-ec2-alpha/lib/route.ts [hunk 3]
```diff
@@ -608,12 +608,8 @@ export class RouteTargetType {
   readonly endpoint?: IVpcEndpoint;
 
   constructor(props: RouteTargetProps) {
-    if ((props.gateway && props.endpoint) || (!props.gateway && !props.endpoint)) {
-      throw new Error('Exactly one of `gateway` or `endpoint` must be specified.');
```
Comment (samson-keung) [inline packages/@aws-cdk/aws-ec2-alpha/lib/route.ts:612]: I see this is moved into the `Route` constructor. Curious about the reasoning

File: packages/@aws-cdk/aws-ec2-alpha/lib/vpc-v2-base.ts [hunk 4]
```diff
@@ -477,9 +489,19 @@ export abstract class VpcV2Base extends Resource implements IVpcV2 {
...
+    if (options?.subnets) {
+      // Use Set to ensure unique subnets
+      const processedSubnets = new Set<string>();
+      const subnets = flatten(options.subnets.map(s => this.selectSubnets(s).subnets));
+      subnets.forEach((subnet) => {
+        if (!processedSubnets.has(subnet.node.id)) {
+          this.addDefaultInternetRoute(subnet, igw, options);
+          processedSubnets.add(subnet.node.id);
+        };
+      }); // If there are no input subnets defined, default route will be added to all public subnets
```
Comment (samson-keung) [inline packages/@aws-cdk/aws-ec2-alpha/lib/vpc-v2-base.ts:502]: My understanding is that if a subnet has a route to the internet, then it becomes a public subnet.

So should we allow adding internet gateway to private subnets? If we do, should we warn the users so that they do not accidentally make their subnets, intended to be private, public?

**Review by samson-keung — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-ec2-alpha/lib/route.ts (hunk 3 above)
Comment (shikha372) [reply packages/@aws-cdk/aws-ec2-alpha/lib/route.ts:612]: While adding unit tests, stack was not throwing expected error while using addRoute method with both endpoint and target as an input, so moved it from RouteTargetType class to `Route`
`addRoute`

File: packages/@aws-cdk/aws-ec2-alpha/lib/vpc-v2-base.ts (hunk 4 above)
Comment (shikha372) [reply packages/@aws-cdk/aws-ec2-alpha/lib/vpc-v2-base.ts:506]: Yes, this was my understanding as well but after talking to service team there can be cases with VPNGW type of attachment where customer might be leveraging their on-premises network to route the traffic to internet.
I was thinking of adding warning as well for private subnets, but there can be different categories under private subnets too. But I still think notifying is good idea, so added a warning for all kinds of subnets except PUBLIC.

File: packages/@aws-cdk/aws-ec2-alpha/lib/ipam.ts (hunk 2 above)
Comment (shikha372) [reply packages/@aws-cdk/aws-ec2-alpha/lib/ipam.ts]: Good point for 1, changed the condition to check for empty array as well.
For 2, I wanted to prevent the deployment for stacks that has any unresolved token reference while synth, but looking at the template again i think even with no environment variable, it will look like below which is going to be resolved at deployment time which should be okay, in any case i don't think we need to check for this, updated the condition.
{
  "RegionName": {
    "Ref": "AWS::Region"
  }
}

File: packages/@aws-cdk/aws-ec2-alpha/lib/vpc-v2-base.ts (hunk 4 above)
Comment (samson-keung) [reply packages/@aws-cdk/aws-ec2-alpha/lib/vpc-v2-base.ts:505]: > there can be cases with VPNGW type of attachment where customer might be leveraging their on-premises network to route the traffic to internet.

And in such case, it won't be a private subnet? Is it correct to say that "Private Subnet" is a concept to describe a subnet that is configured to not able to access the internet? I am thinking if we should keep the public vs private subnet concept in CDK since, say, a private subnet may become public due to drifting.

Anyways, this is not a blocking comment. We can discuss further offline. Thank you for explaining.

File: packages/@aws-cdk/aws-ec2-alpha/lib/ipam.ts [hunk 5]
```diff
@@ -511,7 +511,7 @@ export class Ipam extends Resource {
     if (props?.ipamName) {
       Tags.of(this).add(NAME_TAG, props.ipamName);
     }
-    if (!props?.operatingRegion && !Stack.of(this).region) {
+    if (props?.operatingRegion && (props.operatingRegion.length === 0)) {
```
Comment (samson-keung) [inline packages/@aws-cdk/aws-ec2-alpha/lib/ipam.ts:514]: nit: The `operatingRegion` is a list so it should be named `operatingRegions`.

File: packages/@aws-cdk/aws-ec2-alpha/lib/vpc-v2-base.ts [hunk 6]
```diff
@@ -60,6 +60,13 @@ export interface InternetGatewayOptions{
    * @default - provisioned without a resource name
    */
   readonly internetGatewayName?: string;
+
+  /**
+   * List of subnets where route to IGW will be added
+   *
+   * @default - route created for all subnets with Type `SubnetType.Public`
+   */
+  readonly subnets?: SubnetSelection[];
```
Comment (samson-keung) [inline packages/@aws-cdk/aws-ec2-alpha/lib/vpc-v2-base.ts:69]: nit: Naming this `subnetSelections` seems better so users are not confused that it may be of the type `SubnetV2[]`.

**Review by samson-keung — CHANGES_REQUESTED** [review]

File: packages/@aws-cdk/aws-ec2-alpha/lib/vpc-v2-base.ts (hunk 6 above)
Comment (shikha372) [reply packages/@aws-cdk/aws-ec2-alpha/lib/vpc-v2-base.ts:69]: actually, tried to keep it consistent per the functions in main lib with the current options in main lib for adding interfaces and endpoints, https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts#L110 , where mySubnet is a new subnet defined using SubnetV2.

myVpc.addInternetGateway({
  ipv4Destination: '192.168.0.0/16',
  subnets: [mySubnet],
});

File: packages/@aws-cdk/aws-ec2-alpha/lib/ipam.ts (hunk 5 above)
Comment (shikha372) [reply packages/@aws-cdk/aws-ec2-alpha/lib/ipam.ts]: addressed in latest rev but this would be breaking change which should be okay for alpha, added in PR description

BREAKING CHANGE: operatingRegion property under IPAM class is now renamed to operatingRegions.

**Review by samson-keung — APPROVED** [review]
Thank you. LGTM

**Comment by samson-keung** [comment]
Code looks good. I missed that the title needs to be updated as well. `chore` will not be included in change log, hence, the BERAKING CHANGE line will not be picked up I think.

**Comment by shikha372** [comment]
@mergifyio update
