### PR TITLE
fix(sqs): SSE-SQS is enabled by default and can't be disabled

### LINKED ISSUE #22137: SQS: CDK Deploy by default adding Amazon SQS key(SSE-SQS) encryption
### Describe the bug

SQS constructor for CDK v2 by default adding encryption of Amazon SQS key(SSE-SQS) encryption. As mentioned in the description of the encryption variable below.
**"
Whether the contents of the queue are encrypted, and by what type of key.
Be aware that encryption is not available in all regions, please see the docs for current availability details.
@default
Unencrypted
"**
It should not add any encryption in SQS.

### Expected Behavior

On SQS AWS Console Encryption should be disabled.

### Current Behavior

On SQS AWS Console Encryption is enabled with  Amazon SQS key(SSE-SQS).
CDK Code =
` 
new sqs.Queue(this, 'test-queue', {
        queueName: "test-queue-name"
      });
`
Generated CFT Template = 
`Resources:
  testqueueA58C838B:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: test-queue-name
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: test-stack/test-queue/Resource
`

CDK Dependencies -
"aws-cdk-lib": "2.37.0",
"aws-cdk": "2.37.0"

### Reproduction Steps

1. Create new SQS in the sample project without adding any properties
2. After creation observe in AWS Console SQS will be created with Encryption as Amazon SQS key(SSE-SQS)

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.37.0

### Framework Version

_No response_

### Node.js Version

16.15.0

### OS

Windows

### Language

Typescript

### Language Version

3.9.7

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jumic**
AWS has changed the the default behavior for SQS queue encryption. All newly created queues are encrypted by default ([see docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-configure-sse-existing-queue.html)):
> To protect the data in a queue’s messages, Amazon SQS has server-side encryption (SSE) enabled by default for all newly created queues.

This PR mentions the new default encryption (SSE-SQS) for newly created queues in docstrings and README.

In addition, attribute `SqsManagedSseEnabled` will be set to `false` if encryption mode `UNENCRYPTED` is used. Otherwise the queue would be encrypted since this is the new default behavior.

Fixes #22137.

Small additional change: Remove note that SSE-SQS is not supported in China region. [It is available ](https://www.amazonaws.cn/en/new/2021/server-side-encryption-amazon-sqs-managed-encryption-keys-sse-sqs-amazon-web-services-china-regions/) in the meanwhile.

----

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [X] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [X] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
Hmm. How long has this new default behavior been in place?

Given that the SQS has changed its default behavior, I don't think that we should break from that. I would think that a user would assume we'd also use that default. Also, because we're currently using that behavior, this change would disable encryption on queues when the user upgrades versions. We definitely don't want that. While we do need the ability to disable it, I think the default needs to be encrypted.

**Comment by jumic** [comment]
I don't now exactly when this behavior was introduced. It was reported 13 days ago in #22137.

Yes, we can also change the default in CDK. I thought about it yesterday, too. And it's also an option that I like. I will update the PR.

File: packages/@aws-cdk/aws-sqs/lib/queue.ts [hunk 1]
```diff
@@ -87,7 +87,7 @@ export interface QueueProps {
    * Be aware that encryption is not available in all regions, please see the docs
    * for current availability details.
    *
-   * @default Unencrypted
+   * @default SQS_MANAGED (SSE-SQS) for newly created queues, otherwise unencrypted
```
Comment (corymhall) [inline packages/@aws-cdk/aws-sqs/lib/queue.ts:90]:
```suggestion
   * @default SQS_MANAGED (SSE-SQS)
```

I wouldn't differentiate between newly created or not here. How do I know whether _my_ queue is "newly" created or not?

**Review by corymhall — CHANGES_REQUESTED** [review]
Just one minor comment.

File: packages/@aws-cdk/aws-sqs/lib/queue.ts (hunk 1 above)
Comment (jumic) [reply packages/@aws-cdk/aws-sqs/lib/queue.ts]: Yes, you don't know when the queue was created and whether it uses the old or the new default value. I changed the description as proposed.

File: packages/@aws-cdk/aws-sqs/README.md [hunk 2]
```diff
@@ -44,7 +44,8 @@ The following encryption modes are supported:
 * KMS key that you can managed yourself
 * Server-side encryption managed by SQS (SSE-SQS)
 
-Support for SSE-SQS is available in all AWS Commercial and GovCloud Regions except the China Regions.
+All newly created queues are encrypted by default with SSE-SQS since this is the new default encryption for SQS queues. Queues created in the past are unencrypted by default.
```
Comment (jumic) [inline packages/@aws-cdk/aws-sqs/README.md:47]: @corymhall Should I also remove explanation of the old default value here? Then it's similar to the docstring. On the other hand, users could ask why their queue isn't encrypted. In this case, the explanation could help to understand the new behavior.

Comment (corymhall) [reply packages/@aws-cdk/aws-sqs/README.md:47]: I think if know the date that this behavior was enabled (was it when they released SSE-SQS?) then we can say queues created prior to DATE ... etc.

Comment (jumic) [reply packages/@aws-cdk/aws-sqs/README.md:47]: Unfortunately, I can't find a date since when this change is active. The issue was reported 13 days ago (#22137). Therefore, I don't think that the default is active since SQS was released in November 2021. Moreover, the [announcement](https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-sqs-server-side-encryption-keys-sse/) does not contain any reference to this. 

I also tried to figure out the date looking at the SQS documentation. There is a version on GitHub, unfortunately the change isn't replicated [there](https://github.com/awsdocs/amazon-sqs-developer-guide/blob/main/doc_source/sqs-configure-sse-existing-queue.md).

So how should we proceed? To you have another idea? Or should I just remove the note that explains the old default value (unencrypted)?

Comment (corymhall) [reply packages/@aws-cdk/aws-sqs/README.md:47]: I would say lets just remove any mention of the old behavior.

**Review by TheRealAmazonKendra — APPROVED** [review]

**Comment by jumic** [comment]
FYI - There is now also an official announcement for this change:
[Amazon SQS announces Server-Side Encryption with Amazon SQS-managed encryption keys (SSE-SQS) by default
](https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-sqs-announces-server-side-encryption-ssq-managed-sse-sqs-default/)
