### PR TITLE
fix(codebuild): cannot use immutable roles for Project

### LINKED ISSUE #1408: Escape hatch: be able to delete an entire resource from the subtree
Sometimes users might want to delete an entire resource.

See https://github.com/awslabs/aws-cdk/pull/1404 for a use case

### PR DESCRIPTION
**Pull request by rix0rrr**
## Commit Message
fix(codebuild): cannot use immutable roles for Project

Immutably imported `Role`s could not be used for CodeBuild
`Project`s, because they would create a policy but be unable
to attach it to the Role. That leaves an unattached Policy,
which is invalid.

Fix this by making `Policy` objects only render to an `AWS::IAM::Policy`
resource if they actually have any effect. It is perfectly allowed to
create new unattached Policy objects, or have empty Policy objects.
Only if and when they actually need to mutate the policy of an IAM
identity will they render themselves to the CloudFormation template.
Being able to abstract away these kinds of concerns is exactly the value
of a higher-level programming model.

To allow for the rare cases where an empty Policy object would be
considered a programming error, we still have the flag `mustCreate`
which triggers the legacy behavior of alwyas creating the
`AWS::IAM::Policy` resource which must have a statement and be
attached to an identity.

Fixes #1408.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-iam/lib/policy.ts [hunk 1]
```diff
@@ -160,19 +173,60 @@ export class Policy extends Resource implements IPolicy {
...
+  private get isAttached() {
+    return this.groups.length + this.users.length + this.roles.length > 0;
+  }
+
+  /**
+   * Whether the policy resource should be created
+   */
+  private get shouldExist() {
+    return this.mustCreate || this.referenceTaken || (!this.document.isEmpty && this.isAttached);
+  }
```
Comment (eladb) [inline packages/@aws-cdk/aws-iam/lib/policy.ts]: since this is temporal (i.e. only relevant after the tree has been fully initialized) and used only in one place, I think this code should just be part of `prepare` to avoid accidentally using it in the future from the wrong context.

File: packages/@aws-cdk/core/lib/construct.ts [hunk 2]
```diff
@@ -438,6 +438,15 @@ export class ConstructNode {
     return ret;
   }
 
+  /**
+   * Remove the child with the given name, if present.
+   *
+   * It is not an error if a child with the given name does not exist.
+   */
+  public removeChild(childName: string) {
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/construct.ts]: Maybe rename to `tryRemoveChild` to indicate it won't throw, and return a boolean indicating if the child was actually removed or not.

I am a bit worried by potential abuse of this API. Maybe we can make it a bit safer and only allow this during "prepare" somehow? What do you think? Can you please also mark this as `@experimental`?

This also resolves https://github.com/aws/aws-cdk/issues/1408

Comment (rix0rrr) [reply packages/@aws-cdk/core/lib/construct.ts]: I'm not too worried about misuse. The methods on `node` are pretty much "plumbing sticking out" anyway, not sure they're part of people's day-to-day operations with the API.

I would hope that people venturing there will be aware they're messing with internals which can do what they want, or have unintentional effects they themselves will be responsible for cleaning up. Not sure that limiting to `prepare()` is necessary.

File: packages/@aws-cdk/aws-iam/lib/policy.ts [hunk 3]
```diff
@@ -56,6 +56,22 @@ export interface PolicyProps {
...
+   * (for example, if it remains unattached to an IAM identity or if it has no
+   * statements). This is generally desired behavior, since it prevents
+   * creating invalid--and hence undeployable--CloudFormation templates.
+   *
+   * In cases where you know the policy must be created and it is actually
+   * an error if no statements have been added to it, you can se this to `true`.
+   *
+   * @default false
+   */
+  readonly mustCreate?: boolean;
```
Comment (skinny85) [inline packages/@aws-cdk/aws-iam/lib/policy.ts]: I still don't love this name... I proposed changing it to `lazy?: boolean` in the previous PR, but I'm also open to other suggestions 🙂

Comment (rix0rrr) [reply packages/@aws-cdk/aws-iam/lib/policy.ts]: forceResource?

mustExist?

Comment (rix0rrr) [reply packages/@aws-cdk/aws-iam/lib/policy.ts]: I feel "lazy" is usually used to communicate something else.

Comment (eladb) [reply packages/@aws-cdk/aws-iam/lib/policy.ts]: Maybe just `force`?

Comment (rix0rrr) [reply packages/@aws-cdk/aws-iam/lib/policy.ts]: I was considering `force`, slightly on the fence but I also don't have a better alternative. I can do `force`.

File: packages/@aws-cdk/aws-iam/lib/policy.ts [hunk 4]
```diff
@@ -160,19 +173,54 @@ export class Policy extends Resource implements IPolicy {
...
+  }
+
   protected validate(): string[] {
     const result = new Array<string>();
 
     // validate that the policy document is not empty
     if (this.document.isEmpty) {
-      result.push('Policy is empty. You must add statements to the policy');
+      if (this.force) {
+        result.push('Policy created with mustCreate=true is empty. You must add statements to the policy');
```
Comment (skinny85) [inline packages/@aws-cdk/aws-iam/lib/policy.ts]: References old property name.

File: packages/@aws-cdk/aws-iam/lib/policy.ts [hunk 5]
```diff
@@ -160,19 +173,54 @@ export class Policy extends Resource implements IPolicy {
...
+      }
+      if (!this.force && this.referenceTaken) {
+        result.push('Policy name has been read of empty policy. You must add statements to the policy so it can exist.');
```
Comment (skinny85) [inline packages/@aws-cdk/aws-iam/lib/policy.ts]: See https://github.com/aws/aws-cdk/pull/5569#discussion_r361709620

File: packages/@aws-cdk/aws-iam/lib/policy.ts [hunk 6]
```diff
@@ -160,19 +173,54 @@ export class Policy extends Resource implements IPolicy {
...
 
     // validate that the policy is attached to at least one principal (role, user or group).
-    if (this.groups.length + this.users.length + this.roles.length === 0) {
-      result.push(`Policy must be attached to at least one principal: user, group or role`);
+    if (!this.isAttached) {
+      if (this.force) {
+        result.push(`Policy created with mustCreate=true must be attached to at least one principal: user, group or role`);
+      }
+      if (!this.force && this.referenceTaken) {
+        result.push('Policy name has been read of unattached policy. Attach to at least one principal: user, group or role.');
```
Comment (skinny85) [inline packages/@aws-cdk/aws-iam/lib/policy.ts]: See here: https://github.com/aws/aws-cdk/pull/5569#discussion_r361709620

File: packages/@aws-cdk/aws-iam/lib/policy.ts [hunk 7]
```diff
@@ -160,19 +173,54 @@ export class Policy extends Resource implements IPolicy {
...
+        result.push('Policy name has been read of empty policy. You must add statements to the policy so it can exist.');
+      }
     }
 
     // validate that the policy is attached to at least one principal (role, user or group).
-    if (this.groups.length + this.users.length + this.roles.length === 0) {
-      result.push(`Policy must be attached to at least one principal: user, group or role`);
+    if (!this.isAttached) {
+      if (this.force) {
+        result.push(`Policy created with mustCreate=true must be attached to at least one principal: user, group or role`);
```
Comment (skinny85) [inline packages/@aws-cdk/aws-iam/lib/policy.ts]: References old property name.

File: packages/@aws-cdk/aws-iam/lib/policy.ts (hunk 3 above)
Comment (Jerry-AWS) [reply packages/@aws-cdk/aws-iam/lib/policy.ts]: forceReify? forceRender?
