### PR TITLE
fix(assets): docker asset versions are pushed to separate repositories

### LINKED ISSUE #4535: ECR assets all pushed to the same repository
After the changes introduced in #2821 ECR assets are *all pushed to the same repository* (one per stack, named `cdk/<stack name>`)

Is this intentional? Not sure...

The problem lies in here (L535):
https://github.com/aws/aws-cdk/blob/443394cbe671c5438ff5d28f84989111721e6d10/packages/%40aws-cdk/core/lib/stack.ts#L525-L536

`this` in `L535` always refers to the stack here (not the asset anymore).

⚠️ **For stacks with more than 5 images, the lifecycle policy deployed by the CDK on the repository will delete ECR assets.**

This has also consequences here:
https://github.com/aws/aws-cdk/blob/443394cbe671c5438ff5d28f84989111721e6d10/packages/aws-cdk/lib/docker.ts#L47-L55

where `latest` has no meaning anymore because different assets are mixed in a repository...

### Reproduction Steps
Deploy a stack with multiple ECR assets.

### Environment

  - **CLI Version      :** >=1.12.0
  - **Framework Version:** >=1.12.0
  - **OS               :** all
  - **Language         :** all

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by jogold**
After the changes introduced in #2821, ECR assets were all uploaded to the same repository.
This is because the asset id was always referring to the stack.

Moved the default behavior on the `repositoryName` prop of `DockerImageAsset` to
its constructor which brings back the naming based on the asset id.

We need to derive the repository name from the asset id otherwise the CDK will
create a new repository each time the image changes (which will make layer
caching useless).

Fixes #4535

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by jogold** [comment]
It may be better to do something with `repositoryName` directly.

File: packages/@aws-cdk/core/lib/stack.ts [hunk 1]
```diff
@@ -532,7 +532,7 @@ export class Stack extends Construct implements ITaggable {
       params = new DockerImageAssetParameters(this.assetParameters, asset.sourceHash);
 
       const metadata: cxapi.ContainerImageAssetMetadataEntry = {
-        id: this.node.uniqueId,
+        id: asset.id,
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/stack.ts]: how about using `asset.directoryName` instead?

File: packages/@aws-cdk/core/lib/assets.ts [hunk 2]
```diff
@@ -23,6 +23,14 @@ export interface FileAssetSource {
 }
 
 export interface DockerImageAssetSource {
+  /**
+   * The id for the image.
+   *
+   * This will be used to construct the repository name if `repositoryName`
+   * is not specified.
+   */
+  readonly id: string;
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/assets.ts]: This was intentionally omitted since as part of our work on CI/CD (#3437) we are planning to push all images into a single ECR.

Comment (jogold) [reply packages/@aws-cdk/core/lib/assets.ts]: You mean you want to maintain this "one repository per stack" behavior for now? This means changing the lifecycle policy

What about layer caching/docker build times in CI with this approach?

File: packages/@aws-cdk/core/lib/stack.ts (hunk 1 above)
Comment (jogold) [reply packages/@aws-cdk/core/lib/stack.ts]: `asset.directoryName` referes to the staging directory when assets are staged, this is equivalent to using `asset.sourceHash` which will recreate a repository with each change.

File: packages/aws-cdk/lib/api/toolkit-info.ts [hunk 3]
```diff
@@ -107,15 +107,7 @@ export class ToolkitInfo {
...
-    let repositoryName;
-    if ( asset.repositoryName ) {
-      // Repository name provided by user
-      repositoryName = asset.repositoryName;
-    } else {
-      // Repository name based on asset id
-      const assetId = asset.id;
-      repositoryName = 'cdk/' + assetId.replace(/[:/]/g, '-').toLowerCase();
-    }
+    const repositoryName = asset.repositoryName;
```
Comment (jogold) [inline packages/aws-cdk/lib/api/toolkit-info.ts]: Moved the default behavior on the `repositoryName` prop of `DockerImageAsset` to its constructor. Cleaner and makes more sense.

File: packages/@aws-cdk/core/lib/stack.ts (hunk 1 above)
Comment (eladb) [reply packages/@aws-cdk/core/lib/stack.ts]: Good point. damn!

File: packages/@aws-cdk/core/lib/assets.ts (hunk 2 above)
Comment (eladb) [reply packages/@aws-cdk/core/lib/assets.ts]: No, I am okay with trying to fix this, but just not with extending the API surface in order to do that

File: packages/@aws-cdk/core/lib/assets.ts [hunk 4]
```diff
@@ -60,13 +60,10 @@ export interface DockerImageAssetSource {
...
-   * Specify this property if you need to statically address the image, e.g.
-   * from a Kubernetes Pod. Note, this is only the repository name, without the
-   * registry and the tag parts.
-   *
-   * @default - automatically derived from the asset's ID.
+   * Note, this is only the repository name, without the registry and
+   * the tag parts.
    */
-  readonly repositoryName?: string;
+  readonly repositoryName: string;
```
[the remark this answers is not in the document]
Comment (jogold) [reply packages/@aws-cdk/core/lib/assets.ts]: You are right we can keep this optional but as it is now `repositoryName` will always be defined when calling `addDockerImageAsset`, no? You want to avoid the breaking change?

[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/core/lib/assets.ts]: Yes, I want to avoid the breaking change, and also, `addDockerImageAsset` is lower-level and we might introduce another `ImageAsset` as we implement the new CI/CD support.

[the remark this answers is not in the document]
Comment (jogold) [reply packages/@aws-cdk/core/lib/assets.ts]: If make this back optional you either have to make it also optional in `ContainerImageAssetMetadataEntry` and then `throw` if undefined in `prepareEcrRepository`? or set a default when defining `metadata`, what default and how would you document it because you don't have access to the `asset` node there (I would leave the default behavior on `repositoryName` in `DockerImageAsset`)?

[the remark this answers is not in the document]
Comment (eladb) [reply packages/@aws-cdk/core/lib/assets.ts]: I believe it was already optional in `ContainerImageAssetMetadataEntry`, no?

File: packages/@aws-cdk/cx-api/lib/assets.ts [hunk 5]
```diff
@@ -83,15 +83,12 @@ export interface ContainerImageAssetMetadataEntry extends BaseAssetMetadataEntry
...
-   * ID is used instead. Specify this property if you need to statically
-   * address the image, e.g. from a Kubernetes Pod.
+   * ECR repository name.
+   *
    * Note, this is only the repository name, without the registry and
    * the tag parts.
-   *
-   * @default automatically derived from the asset's ID.
    */
-  readonly repositoryName?: string;
```
Comment (eladb) [inline packages/@aws-cdk/cx-api/lib/assets.ts]: revert

File: packages/@aws-cdk/core/lib/stack.ts [hunk 6]
```diff
@@ -532,7 +532,7 @@ export class Stack extends Construct implements ITaggable {
       params = new DockerImageAssetParameters(this.assetParameters, asset.sourceHash);
 
       const metadata: cxapi.ContainerImageAssetMetadataEntry = {
-        id: this.node.uniqueId,
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/stack.ts]: This is fine

File: packages/@aws-cdk/core/lib/assets.ts [hunk 7]
```diff
@@ -60,13 +60,10 @@ export interface DockerImageAssetSource {
...
    *
-   * Specify this property if you need to statically address the image, e.g.
-   * from a Kubernetes Pod. Note, this is only the repository name, without the
-   * registry and the tag parts.
-   *
-   * @default - automatically derived from the asset's ID.
+   * Note, this is only the repository name, without the registry and
+   * the tag parts.
    */
-  readonly repositoryName?: string;
```
Comment (eladb) [inline packages/@aws-cdk/core/lib/assets.ts]: Revert

File: allowed-breaking-changes.txt [hunk 8]
```diff
@@ -27,3 +27,4 @@ incompatible-argument:@aws-cdk/aws-servicediscovery.Service.fromServiceAttribute
 removed:@aws-cdk/core.ConstructNode.addReference
 removed:@aws-cdk/core.ConstructNode.references
 removed:@aws-cdk/core.OutgoingReference
+incompatible-argument:@aws-cdk/core.Stack.addDockerImageAsset
```
Comment (eladb) [inline allowed-breaking-changes.txt]: Revert

**Comment by jogold** [comment]
> I feel like I am missing something. Why not just pass a `repositoryName` in `ImageAsset`? I don't understand why we need to expose the ID as an option now...

Yes, we can do that but I don't like the fact that in `ContainerImageAssetMetadataEntry` and `DockerImageAssetSource` the `repositoyName` remains optional with a default stating that it will be *automatically derived from the asset's ID*. This is not true anymore because the default behavior is not handled in `prepareEcrRepository()` anymore.

**Comment by jogold** [comment]
The question is the following: if we do `props.repositoryName || 'cdk/' + this.node.uniqueId.replace(/[:/]/g, '-').toLowerCase()` in `DockerImageAsset` then in `prepareEcrRepository()` where `repositoryName` can still be `undefined` (to avoid breaking change) what is the default behavior there?

**Comment by jogold** [comment]
OK, just simplified like you wanted it to be I think. This means that we now have two places where `repositoryName` is checked:
https://github.com/aws/aws-cdk/blob/4f42e3ce3fc96e566c5df08a0fb6aee931ecfbb3/packages/%40aws-cdk/aws-ecr-assets/lib/image-asset.ts#L95-L100
and
https://github.com/aws/aws-cdk/blob/4f42e3ce3fc96e566c5df08a0fb6aee931ecfbb3/packages/aws-cdk/lib/api/toolkit-info.ts#L110-L118

The only question is what you want to pass as `id` here:
https://github.com/aws/aws-cdk/blob/4f42e3ce3fc96e566c5df08a0fb6aee931ecfbb3/packages/%40aws-cdk/core/lib/stack.ts#L534-L537

`this.node.uniqueId` = constant for all assets or `asset.sourceHash`?

File: packages/@aws-cdk/core/test/test.stack.ts [hunk 9]
```diff
@@ -674,6 +674,38 @@ export = {
     test.deepEqual(asm.getStack(child.stackName).findMetadataByType('foo'), [
       { path: '/parent/child', type: 'foo', data: 'bar' }
     ]);
+
+    test.done();
+  },
+
+  'addDockerImageAsset correctly sets metadata and creates a parameter'(test: Test) {
```
Comment (eladb) [inline packages/@aws-cdk/core/test/test.stack.ts]: I believe we should have a test like this in `test.assets.ts`

**Comment by eladb** [comment]
If I had to choose, I would like to use the sourceHash

**Comment by jogold** [comment]
@eladb is this OK now?
