### PR TITLE
fix(assertions): output and mapping assertions do not accept logical id

### LINKED ISSUE #16242: (assertions): Mapping and Output section assertions should accept the key
Take the sample CFN template -

```json
{
  "Outputs": {
    "Out1": { "Value": "Val1" },
    "Out2": { "Value": "Val2" }
  }
}
```

The assertion here currently looks like -

```ts
template.hasOutput({
  Value: "Val1",
});
```

This is ambiguous and makes it impossible to assert that the correct values are present beside the correct keys.

The API should be corrected to include the key so as to fix this.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by kaizencc**
Closes #16242. 

The asset template functions for `mapping` and `output` do not consider the logicalId of the cloudformation output, leading to possible ambiguity in the testing framework. For example, one could have these outputs:

```ts
{
  "Outputs": {
    "Out1": { "Value": "Val1" },
    "Out2": { "Value": "Val2" }
  }
}
```

Using `template.hasOutput({ Value: "Val1" })` does not give the user control over which output they are expecting the value to be under. Potentially, the user could assert for `val1` and expect it to be under `Out2` when in reality it is under `Out1`.

This PR fixes the API by requiring a new parameter, `logicalId` with the possibility of defaulting to all outputs via the `'*'` token. The original functionality still exists by sending in `'*'` as the `logicalId` and you get more fine-grained tests by being able to assert with a specific `logicalId`. This functionality is added to both the `output` methods and the `mapping` methods.

BREAKING CHANGE: `hasOutput(props: any)` becomes `hasOutput(logicalId: string, props: any)`
* **assertions:** `findOutputs(props: any = {})` becomes `findOutputs(logicalId: string, props: any = {})`
* **assertions:** `hasMapping(props: any)` becomes `hasMapping(logicalId: string, props: any)`
* **assertions:** `findMappings(props: any = {})` becomes `findMappings(logicalId: string, props: any = {})`
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/assertions/lib/template.ts [hunk 1]
```diff
@@ -109,10 +109,11 @@ export class Template {
    * Assert that an Output with the given properties exists in the CloudFormation template.
    * By default, performs partial matching on the resource, via the `Match.objectLike()`.
    * To configure different behavour, use other matchers in the `Match` class.
+   * @param outputName the name of the output.
    * @param props the output as should be expected in the template.
    */
-  public hasOutput(props: any): void {
-    const matchError = hasOutput(this.inspector, props);
+  public hasOutput(outputName: string, props: any): void {
```
Comment (nija-at) [inline packages/@aws-cdk/assertions/lib/template.ts:115]: We should probably also change `findOutputs()`.

**Review by nija-at — CHANGES_REQUESTED** [review]
This is a good start.

1. Update the tests that are failing to use the updated API

2. Any changes to the README.md?

3. You need a add [breaking changes clause](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#step-4-pull-request)

4. PR description text gets converted into the final git commit message upon merge. 
   I would suggest updating the message to spell out what the problem was or motivation and a brief on what the fix is.
  This is very useful when looking at a commit message many months from now to determine why a change was made and why it was made in a specific way.
  There are tons of articles online on writing good commit messages - check them out.

File: packages/@aws-cdk/assertions/lib/template.ts (hunk 1 above)
Comment (kaizen3031593) [reply packages/@aws-cdk/assertions/lib/template.ts:115]: It seems like for `findOutputs`, we should be less stringent about the `outputName` and still allow for users to search for some `value` among all outputs like so:

```ts
test('matching', () => {
      const stack = new Stack();
      new CfnOutput(stack, 'Foo', {
        value: 'Fred',
        description: 'FooFred',
      });
      new CfnOutput(stack, 'Bar', {
        value: 'Fred',
        description: 'BarFred',
      });
      new CfnOutput(stack, 'Baz', {
        value: 'Waldo',
        description: 'BazWaldo',
      });

      const inspect = Template.fromStack(stack);
      const result = inspect.findOutputs({ Value: 'Fred' });
      expect(result).toEqual([
        { Value: 'Fred', Description: 'FooFred' },
        { Value: 'Fred', Description: 'BarFred' },
      ]);
    });
```

With that in mind, do you think we should:

a) still require an `outputName` in `findOutputs` (what I read that you are suggesting in the above comment)
b) make `outputName` optional
c) figure out some way to return the `outputName` so the user has the full picture.

If it were up to me I think that `c)` is the best option though it would require us to make a change to `matchSection()` so we return the `logicalId` along with the rest of the output. What do you think?

Comment (nija-at) [reply packages/@aws-cdk/assertions/lib/template.ts:115]: I like your suggestion of making `outputName` optional and returning the `logicalId`. How about we split this into two changes? In this PR, implement (b) and in a subsequent PR, implement (c) but for all `find*()` APIs.

Comment (kaizen3031593) [reply packages/@aws-cdk/assertions/lib/template.ts:115]: It seems like making `outputName` optional is problematic in its own right. We get `public findOutputs(outputName?: string, props?: string)` which doesn't really work because of the two optional parameters. The user experience for not wanting to specify an `outputName` would be `findOutputs(undefined, MyProps)`. I feel like that is unacceptable, but I'm open to input.

Otherwise, the three options I can think of are overloading the method (but typescript barely supports this and I have no reference that this happens anywhere in the CDK) or refactoring to a method signature of `findOutputs(options: findOptions)`. I am also sympathetic towards having all the `find` and `has` methods similar in signature, so perhaps it is time to start thinking about all of these methods taking in a `findXXXOptions` or `hasXXXOptions` instead.

My last option is the one I like best and the one I am currently implementing. I think we should require `outputName` and clearly document that a particular token (`'*'`) represents all outputs. Then, the user experience for not wanting to specify an outputName would be `findOutputs('*', MyProps)` which I think makes more sense than `undefined`.

**Comment by kaizen3031593** [comment]
@nija-at thanks for the first review, I think I'm ready for another pass. 

Re: README changes, there does not look to be much documentation for `mapping` and `output` - they are mentioned briefly under `Other Sections`. I'm happy to build out their README documentation more but wanted to check to make sure that's what you want. 

Hopefully you like what I've done with the methods, because I know we talked about making `outputName` optional and I did not end up doing that. But I think that this idea is more robust in that it opens up the current functionality of `hasMapping` and `hasOutput` as well as the more fine-tuned options we now support. But I am as always happy to discuss/change the implementation.

File: packages/@aws-cdk/assertions/lib/template.ts [hunk 2]
```diff
@@ -109,46 +109,50 @@ export class Template {
    * Assert that an Output with the given properties exists in the CloudFormation template.
    * By default, performs partial matching on the resource, via the `Match.objectLike()`.
    * To configure different behavour, use other matchers in the `Match` class.
+   * @param outputName the name of the output. Provide '*' to match all Output names in the template.
    * @param props the output as should be expected in the template.
    */
-  public hasOutput(props: any): void {
-    const matchError = hasOutput(this.inspector, props);
+  public hasOutput(outputName: string, props: any): void {
```
Comment (nija-at) [inline packages/@aws-cdk/assertions/lib/template.ts:115]: In Mappings they call it "logical name" - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html, and in Outputs they call it "logical id" - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html.
I suggest we use "logical id" in both cases.

Let's use `logicalId` everywhere instead of `outputName`.

File: packages/@aws-cdk/assertions/lib/template.ts [hunk 3]
```diff
@@ -109,46 +109,50 @@ export class Template {
...
   /**
    * Assert that a Mapping with the given properties exists in the CloudFormation template.
    * By default, performs partial matching on the resource, via the `Match.objectLike()`.
    * To configure different behavour, use other matchers in the `Match` class.
+   * @param outputName the name of the output. Provide '*' to match all Output names in the template.
    * @param props the output as should be expected in the template.
    */
-  public hasMapping(props: any): void {
-    const matchError = hasMapping(this.inspector, props);
+  public hasMapping(outputName: string, props: any): void {
```
Comment (nija-at) [inline packages/@aws-cdk/assertions/lib/template.ts:140]: This should not be `outputName`

File: packages/@aws-cdk/assertions/lib/template.ts [hunk 4]
```diff
@@ -109,46 +109,50 @@ export class Template {
...
-    return findOutputs(this.inspector, props);
+  public findOutputs(outputName: string, props: any = {}): { [key: string]: any }[] {
+    return findOutputs(this.inspector, outputName, props);
   }
 
   /**
    * Assert that a Mapping with the given properties exists in the CloudFormation template.
    * By default, performs partial matching on the resource, via the `Match.objectLike()`.
    * To configure different behavour, use other matchers in the `Match` class.
+   * @param outputName the name of the output. Provide '*' to match all Output names in the template.
```
Comment (nija-at) [inline packages/@aws-cdk/assertions/lib/template.ts:137]: Looks copy-paste error. This API is `hasMapping()`.

File: packages/@aws-cdk/assertions/lib/private/section.ts [hunk 5]
```diff
@@ -55,4 +55,13 @@ export function formatFailure(closestResult: MatchResult): string {
 function leftPad(x: string, indent: number = 2): string {
   const pad = ' '.repeat(indent);
   return pad + x.split('\n').join(`\n${pad}`);
+}
+
+export function filterLogicalId(section: { [key: string]: {} }, outputName: string): { [key: string]: {} } {
```
Comment (nija-at) [inline packages/@aws-cdk/assertions/lib/private/section.ts:60]:
```suggestion
export function filterLogicalId(section: { [key: string]: {} }, logicalId: string): { [key: string]: {} } {
```

**Review by nija-at — CHANGES_REQUESTED** [review]
Code looks good to me. See some feedback around docs and param naming below.

> Re: README changes, there does not look to be much documentation for mapping and output - they are mentioned briefly under Other Sections. I'm happy to build out their README documentation more but wanted to check to make sure that's what you want.

Would be nice to expand the `Other Sections` part of the README. Provide a short example or two, similar to the above sections, mention the `*` special case. It's fine to just expand either `Output` or `Mapping` and simply state that the other follows a similar pattern.

**Comment by kaizen3031593** [comment]
Hi @nija-at! Thanks for taking a look. I think this is ready for a final pass.

File: packages/@aws-cdk/assertions/README.md [hunk 6]
```diff
@@ -107,16 +107,32 @@ By default, the `hasResource()` and `hasResourceProperties()` APIs perform deep
 partial object matching. This behavior can be configured using matchers.
 See subsequent section on [special matchers](#special-matchers).
 
-## Other Sections
+## Output and Mapping Matching
```
Comment (nija-at) [inline packages/@aws-cdk/assertions/README.md:110]:
```suggestion
## Output and Mapping sections
```

File: packages/@aws-cdk/assertions/README.md [hunk 7]
```diff
@@ -107,16 +107,32 @@ By default, the `hasResource()` and `hasResourceProperties()` APIs perform deep
...
 
-Similar to the `hasResource()` and `findResources()`, we have equivalent methods
-to check and find other sections of the CloudFormation resources.
+The module allows you to assert that an output or matching has specific properties.
```
Comment (nija-at) [inline packages/@aws-cdk/assertions/README.md:112]:
```suggestion
The module allows you to assert that the CloudFormation template contains an Output that matches specific properties.
```

File: packages/@aws-cdk/assertions/README.md [hunk 8]
```diff
@@ -107,16 +107,32 @@ By default, the `hasResource()` and `hasResourceProperties()` APIs perform deep
...
+The following code asserts that a resource contains an output with a `logicalId` of
```
Comment (nija-at) [inline packages/@aws-cdk/assertions/README.md:113]:
```suggestion
The following code asserts that a template contains an Output with a `logicalId` of
```

File: packages/@aws-cdk/assertions/README.md [hunk 9]
```diff
@@ -107,16 +107,32 @@ By default, the `hasResource()` and `hasResourceProperties()` APIs perform deep
...
-* Mapping - `hasMapping()` and `findMappings()`
+```ts
+assert.hasOutput('Foo', { 
+  Value: 'Bar',
+  Export: { Name: 'ExportBaz' }, 
+});
+```
+
+Alternatively, if you want to match the value to all outputs, you can use the `'*'`
+special case as the `logicalId`.
```
Comment (nija-at) [inline packages/@aws-cdk/assertions/README.md:124]:
```suggestion
If you want to match against all Outputs in the template, use `*` as the `logicalId`.
```

File: packages/@aws-cdk/assertions/README.md [hunk 10]
```diff
@@ -107,16 +107,32 @@ By default, the `hasResource()` and `hasResourceProperties()` APIs perform deep
...
+  Value: 'Bar',
+  Export: { Name: 'ExportBaz' },
+});
+```
 
-All of the defaults and behaviour documented for `hasResource()` and
-`findResources()` apply to these methods.
+`findOutputs()` will return a list of outputs that match the `logicalId` and `props`,
+and you can use the `'*'` special case as well. `hasMapping()` and `findMappings()`
+follow a similar pattern to output matching.
```
Comment (nija-at) [inline packages/@aws-cdk/assertions/README.md:135]:
```suggestion
and you can use the `'*'` special case as well. 

The APIs `hasMapping()` and `findMappings()` provide similar functionalities.
```

**Review by nija-at — APPROVED** [review]
Looks great. I've made some suggestions on the README.

Approved but I've added the 'do-not-merge' label. Remove this label once you've addressed my comments below.

**Comment by nideveloper** [comment]
Hey,

I want to make sure I understand this functionality correctly before taking other actions. I have functionality in a construct requested by users that allows them to specify the export name for an output but the actual logicalid doesn't matter. I want to be able to test for that test-export-name below without having to know websiteDeployURLC068EA32 but it seems like you have made an architectural decision that the logicalid should always be part of the tests?

`Outputs:
  websiteDeployURLC068EA32:
    Description: The url of the website
    Value:
      Fn::GetAtt:
        - websiteDeployWebsiteBucket8C75CFAA
        - WebsiteURL
    Export:
      Name: test-export-name`
