### PR TITLE
fix(cloudfront): use wildcard when grant some cloudfront permission

### LINKED ISSUE #33249: aws-cloudfront: cloudfront:ListDistributions does not support resource-level
### Describe the bug

When using the `grantXXX` command on a resource it applies the actions against the ARN of the current resources. While this is often what you want, some AWS services and actions do not support resource-level protection and require the use of wildcards. For example, when specifying `cloudfront:ListDistributions` the resource must be `*` otherwise it will fail.

To assist users in this process the `grantXXX` function for CloudFront should be updated to use `*` when `cloudfront:ListDistributions` is present within the action list.

https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_aws-services-that-work-with-iam.html

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

When using the `grantXXX` function for CloudFront with `cloudfront:ListDistributions` the resource field should be `*`

### Current Behavior

The resource field is the ARN of the distribution which fails.

### Reproduction Steps

Create a test role that uses `cloudfront:ListDistributions` and set the resource to a specific distribution id and then run the list command, it will fail stating that permissions are lacking.

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.160.0

### Framework Version

_No response_

### Node.js Version

20.11.1

### OS

Mac 13.7.2

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by phuhung273**
### Issue # (if applicable)

Closes #33249

### Reason for this change
CloudFront doesn't support resource-level permission for some permission as per [Actions, resources, and condition keys for Amazon CloudFront](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazoncloudfront.html)

### Description of changes
Use wildcard(*) when grant some cloudfront permission

### Describe any new or updated permissions being added
Use wildcard(*) when grant some cloudfront permission

### Description of how you validated changes
Unit + Integ

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/aws-cdk-lib/aws-cloudfront/lib/private/utils.ts [hunk 1]
```diff
@@ -1,6 +1,62 @@
 import { IDistribution } from '..';
+import * as iam from '../../../aws-iam';
 import { Stack } from '../../../core';
 
+// List of CloudFront actions supporting resource-level permissions
```
Comment (kumsmrit) [inline packages/aws-cdk-lib/aws-cloudfront/lib/private/utils.ts]: The comment should be reframed here as `not supporting`, right?

Comment (phuhung273) [reply packages/aws-cdk-lib/aws-cloudfront/lib/private/utils.ts]: Thank you, that's correct

File: packages/aws-cdk-lib/aws-cloudfront/lib/private/utils.ts [hunk 2]
```diff
@@ -1,6 +1,62 @@
...
+// https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazoncloudfront.html#amazoncloudfront-actions-as-permissions
+const wildcardOnlyActions = [
+  'cloudfront:CreateFieldLevelEncryptionConfig',
+  'cloudfront:CreateFieldLevelEncryptionProfile',
+  'cloudfront:CreateKeyGroup',
+  'cloudfront:CreateMonitoringSubscription',
+  'cloudfront:CreateOriginAccessControl',
+  'cloudfront:CreatePublicKey',
+  'cloudfront:CreateSavingsPlan',
+  'cloudfront:CreateVpcOrigin',
```
Comment (kumsmrit) [inline packages/aws-cdk-lib/aws-cloudfront/lib/private/utils.ts]: This action does support condition keys ([aws:RequestTag/${TagKey}](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazoncloudfront.html#amazoncloudfront-aws_RequestTag___TagKey_),  [aws:TagKeys](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazoncloudfront.html#amazoncloudfront-aws_TagKeys)); so it would be safer to exclude it from the `wildcardActions` and let users apply condition-based scoping.

**Review by kumsmrit — COMMENTED** [review]
Thank you for your contribution; the PR looks good, except for a few minor comment.

File: packages/aws-cdk-lib/aws-cloudfront/lib/private/utils.ts (hunk 2 above)
Comment (phuhung273) [reply packages/aws-cdk-lib/aws-cloudfront/lib/private/utils.ts]: Thank you for spotting that.

Just want to clarify that you want to remove `cloudfront:CreateVpcOrigin` from `wildcardOnlyActions`. This means user cannot use `distribution.grant(role, 'cloudfront:CreateVpcOrigin')` and they need to find another way else to grant this permission. This can help them applying condition because `distribution.grant` doesn't support condition.

Is my understanding correct ?

Comment (kumsmrit) [reply packages/aws-cdk-lib/aws-cloudfront/lib/private/utils.ts]: Yes, that was my suggestion so that `distribution.grant(...)` does not implicitly grant it with `Resource: '*'`; this would align better with the principle of least privilege and gives users more control over scoping permissions securely.

Comment (phuhung273) [reply packages/aws-cdk-lib/aws-cloudfront/lib/private/utils.ts]: Sure thanks for your confirmation. I've updated the list.
