### PR TITLE
fix(elbv2): allow multiple certificates on ALB listener

### LINKED ISSUE #3757: ApplicationLoadBalancer.addListener fails with "Up to '1' certificate ARNs can be specified, but '2' were specified"
### What is the problem?
ApplicationLoadBalancer.addListener fails with "Up to '1' certificate ARNs can be specified, but '2' were specified"

The `certificateArns` property is a list, but providing multiple certificates will cause a deployment failure.

### Reproduction Steps
```

    const listener = loadBalancer
      .addListener(`${awsAppPrefix}HttpsListener`, {
        port: 443,
        // Use two certs
        certificateArns: certificates.map((cert) => cert.certificateArn),
        open: false,
      });
```

### Environment

  - **CDK CLI Version:** 1.5.0
  - **OS:** Macbook
  - **Language:** TypeScript

### PR DESCRIPTION
**Pull request by MrArnoldPalmer**
Fixes a cloudformation error when attaching multiple certificates to an alb listener. Cloudformation allows only a single certificate attached to the `LoadBalancer` resource. If multiple certificates are passed to the construct on initialization or through the `.addCertificateArns` method, separate `ListenerCertificate` resources are created for all after the first.

Closes #3757

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by MrArnoldPalmer** [comment]
This potentially creates multiple `ListenerCertificate` constructs where technically only one would be necessary.

```
const listener = lb.addListener(this, "x", {
  certificateArns: ["cert0"]
});
listener.addCertificateArns("ListenerCert1", ["cert1", "cert2"]);
listener.addCertificateArns("ListenerCert2", ["cert3", "cert4"]);
```

Attaches `cert0` to the listener resource, and creates two separate ListenerCertificate resources, one with certs 1 and 2, the second with certs 3 and 4. If we built the list of cert arns and created the resources within `prepare` we could limit the number of these constructs needed.

This was done to avoid the usage of the `prepare` method. I was warned that `prepare` can cause breakage in automatic dependency resolution.

We may want to add a section on attaching certificates to load balancers to the documentation to detail what resources get created under different conditions. If that is something that the team believes should be included with this fix, let me know.

File: packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts [hunk 1]
```diff
@@ -124,7 +124,11 @@ export class ApplicationListener extends BaseListener implements IApplicationLis
     this.loadBalancer = props.loadBalancer;
     this.protocol = protocol;
     this.certificateArns = [];
-    this.certificateArns.push(...(props.certificateArns || []));
+
+    // Attach certificates
+    if (props.certificateArns) {
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts]: This does not preclude it from being an empty list, just means it's not `undefined`.

File: packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts [hunk 2]
```diff
@@ -143,8 +147,20 @@ export class ApplicationListener extends BaseListener implements IApplicationLis
   /**
    * Add one or more certificates to this listener.
    */
-  public addCertificateArns(_id: string, arns: string[]): void {
-    this.certificateArns.push(...arns);
+  public addCertificateArns(id: string, arns: string[]): void {
+    const [first, ...rest] = arns;
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts]: Neat!

File: packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts [hunk 3]
```diff
@@ -143,8 +147,20 @@ export class ApplicationListener extends BaseListener implements IApplicationLis
...
+    const additionalCertArns = this.certificateArns.length ? arns : rest;
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts]: I'd rather you explicitly test `length > 0` than rely on truthiness of 0.

File: packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts [hunk 4]
```diff
@@ -143,8 +147,20 @@ export class ApplicationListener extends BaseListener implements IApplicationLis
...
+
+    if (!this.certificateArns.length && typeof first === "string") {
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts]: Is this to deal with the case where an empty list was passed? I'd rather you test for that explicitly than rely on the (to me somewhat obscure) behavior that:

```ts
const [x, ...xs] = [];
// x === undefined
```

I would have expected that to throw. Obviously not, because JavaScript :), but the `typeof` check confused me before I tried this out in the REPL.

I'd much rather see a

```ts
if (arns.length === 0) { return; }
```

At the top.

File: packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts [hunk 5]
```diff
@@ -143,8 +147,20 @@ export class ApplicationListener extends BaseListener implements IApplicationLis
...
+      this.certificateArns.push(first);
+    }
+
+    if (additionalCertArns.length) {
+      new ApplicationListenerCertificate(this, id, {
+        listener: this,
+        certificateArns: additionalCertArns
+      });
+    }
```
Comment (rix0rrr) [inline packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts]: I agree that the whole logic here is a little hairy to handle different cases. What if we embraced mutability, and do something like this:

```ts
addCertificateArns(id, arns: string[]) {
  if (arns.length > 0 && this.certificateArns.length === 0) {
    // Pop off the first certificate and put it on the main resource
    const first = arns.splice(0, 1)[0];
    this.certificateArns.push(first);
  } 

  if (arns.length > 0) { 
    new ApplicationListenerCertificate(this, id, { ... });
  }
}
```

If you feel bad about mutating the input argument (reasonable! :) then we can always copy it into a local variable.

File: packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts (hunk 4 above)
Comment (MrArnoldPalmer) [reply packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts]: This was to defend against an empty array being passed, I agree that explicitly testing that condition is better.

File: packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts (hunk 1 above)
Comment (MrArnoldPalmer) [reply packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts]: Added a check for an empty list as well.

File: packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts [hunk 6]
```diff
@@ -142,9 +146,25 @@ export class ApplicationListener extends BaseListener implements IApplicationLis
...
+   * resources since cloudformation requires the certificates array on the
+   * listener resource to have a length of 1.
    */
-  public addCertificateArns(_id: string, arns: string[]): void {
-    this.certificateArns.push(...arns);
+  public addCertificateArns(id: string, arns: string[]): void {
+    const additionalCertArns = [...arns];
+
+    if (this.certificateArns.length === 0 && additionalCertArns.length > 0) {
+      const first = additionalCertArns.splice(0, 1)[0];
```
Comment (MrArnoldPalmer) [inline packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts]: using `.shift` feels better but because of the type definition, requires a non-null assertion operator like so:
```
const first = additionalCertArns.shift()!;
```
Otherwise typescript sees the type of `first` being `string | undefined` even though its guarded against by checking that `additionalCertArns.length` is gt 0.

Comment (rix0rrr) [reply packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts]: Oh yeah, `shift` is totally better, I forgot that existed :)

Comment (rix0rrr) [reply packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts]: But I'm happy to accept the PR as-is

Comment (rix0rrr) [reply packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts]: Thanks!
