### PR TITLE
fix(cloudformation-include): parse MinActiveInstancesPercent in AutoScalingRollingUpdate policy

### LINKED ISSUE #33810: (CfnInclude): CfnInclude omits aws_autoscaling. UpdatePolicy that dont exists in the CDK (MinActiveInstancesPercent)
### Describe the bug

When CfnInclude references a template that has an [UpdatePolicy for autoscaling groups](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_autoscaling.UpdatePolicy.html) it silently omits the  [MinActiveInstancesPercent](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html#cfn-attributes-updatepolicy-rollingupdate-minactiveinstancespercent) property because the code in [cfn-parse.ts](CFNhttps://github.com/aws/aws-cdk/blob/b2a895ef285e5451e64c21e179172e998c479582/packages/aws-cdk-lib/core/lib/helpers-internal/cfn-parse.ts#L435C53-L435C80) does not include the property:

```


      return undefinedIfAllValuesAreEmpty({
        maxBatchSize: FromCloudFormation.getNumber(p.MaxBatchSize).value,
        minInstancesInService: FromCloudFormation.getNumber(p.MinInstancesInService).value,
        minSuccessfulInstancesPercent: FromCloudFormation.getNumber(p.MinSuccessfulInstancesPercent).value,
        pauseTime: FromCloudFormation.getString(p.PauseTime).value,
        suspendProcesses: FromCloudFormation.getStringArray(p.SuspendProcesses).value,
        waitOnResourceSignals: FromCloudFormation.getBoolean(p.WaitOnResourceSignals).value,
      });
```
> [source](https://github.com/aws/aws-cdk/blob/v2.99.1/packages/aws-cdk-lib/core/lib/helpers-internal/cfn-parse.ts#L437C1-L445C10)

The result is that the property is omitted completely and silently :(  

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

MinActiveInstancesPercent should be included in the output template 

### Current Behavior

The result is that the property is omitted completely and silently :(  

### Reproduction Steps

Create a CFN template with an autoscaling group and an update policy which includes [MinActiveInstancesPercent](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html#cfn-attributes-updatepolicy-rollingupdate-minactiveinstancespercent), reference the template file using `CfnInclude`, the `MinActiveInstancesPercent` will not exist in the template in cdk.out 

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.1003.0

### Framework Version

2.132.0

### Node.js Version

18

### OS

MacOs

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by scorbiere**
### Issue #33810 

Closes #33810.

### Reason for this change

When using CfnInclude to import existing CloudFormation templates, the MinActiveInstancesPercent property in AutoScaling 
group update policies was being silently dropped because it was missing from both the `CfnAutoScalingRollingUpdate` 
interface in `cfn-resource-policy.ts` and the parser in the `parseAutoScalingRollingUpdate` function in `cfn-parse.ts`.

### Description of changes

This fix adds:
1. The missing `minActiveInstancesPercent` property to the `CfnAutoScalingRollingUpdate` interface in `cfn-resource-policy.ts`
2. The corresponding property parser to the `parseAutoScalingRollingUpdate` function in `cfn-parse.ts`

These changes ensure that the `MinActiveInstancesPercent` property is correctly preserved when importing templates with 
`AutoScalingRollingUpdate` policies.

### Describe any new or updated permissions being added

N/A

### Description of how you validated changes

Added a comprehensive test that verifies all properties of `AutoScalingRollingUpdate` are correctly parsed, including a new
test template with all properties and explicit assertions for each property.

### Checklist
- [X] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by scorbiere** [comment]
Exemption Request: this fix is focused on the correct parsing and preservation of a CloudFormation property during template import, which is fully testable with unit tests.

File: packages/aws-cdk-lib/core/lib/cfn-resource-policy.ts [hunk 1]
```diff
@@ -187,6 +187,13 @@ export interface CfnAutoScalingRollingUpdate {
    */
   readonly minSuccessfulInstancesPercent?: number;
 
+  /**
+   * Specifies the percentage of instances in an Auto Scaling group that must remain in service while AWS CloudFormation
+   * updates old instances. You can specify a value from 0 to 100. AWS CloudFormation rounds to the nearest tenth of a percent.
+   * For example, if you update five instances with a minimum active percentage of 50, three instances must remain in service.
+   */
+  readonly minActiveInstancesPercent?: number;
```
Comment (godwingrs22) [inline packages/aws-cdk-lib/core/lib/cfn-resource-policy.ts:195]: I have some concerns about potential breaking changes:

Based on the CFN [doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html#cfn-attributes-updatepolicy-rollingupdate-minactiveinstancespercent) as indicated below,

>Setting MinActiveInstancesPercent in your UpdatePolicy will also affect instances launched when the DesiredCapacity property of the AWS::AutoScaling::AutoScalingGroup resource is set higher than the current desired capacity of that Auto Scaling group.

Currently, `minActiveInstancesPercent` is silently ignored when parsing templates in CfnInclude, which means customers are effectively getting the default behavior (100% active instances). By adding direct support for this property, we could potentially impact existing customers in the following ways:

1. Customers who have `MinActiveInstancesPercent` specified in their templates but it's currently being ignored would suddenly see different scaling behavior when their `DesiredCapacity` increases
2. This could affect application availability during scaling events and might break assumptions in their deployment processes

// Example scenario
```
// Template has:
UpdatePolicy: {
  AutoScalingRollingUpdate: {
    MinActiveInstancesPercent: 50
  }
}
// Current behavior: 100% instances stay active
// New behavior with this change: Only 50% instances stay active
```


I think we should handle this with feature flag since it will change existing behaviour. Please help to check.

File: packages/aws-cdk-lib/cloudformation-include/test/valid-templates.test.ts
Comment (godwingrs22) [inline packages/aws-cdk-lib/cloudformation-include/test/valid-templates.test.ts:1]: I would recommend we have a integ test for this [here](https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk-testing/framework-integ/test/cloudformation-include/test) with a similar UpdatePolicy [json](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk-testing/framework-integ/test/cloudformation-include/test/test-templates/resource-attribute-update-policy.json) for the EC2 autoscaling resource

File: packages/aws-cdk-lib/core/lib/helpers-internal/cfn-parse.ts
Comment (godwingrs22) [inline packages/aws-cdk-lib/core/lib/helpers-internal/cfn-parse.ts:1]: nit: I suggest we have a unit test for this parser [here](https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk-lib/core/test/helpers-internal). Atleast for this `parseAutoScalingRollingUpdate` method

**Review by godwingrs22 — CHANGES_REQUESTED** [review]
Thanks @scorbiere for your contribution. I have left some comments with some concerns. Please help to check once.

File: packages/aws-cdk-lib/core/lib/cfn-resource-policy.ts (hunk 1 above)
Comment (shikha372) [reply packages/aws-cdk-lib/core/lib/cfn-resource-policy.ts:195]: While I don’t believe this will cause an immediate traffic disruption for customers—since it only affects the update behavior—users will only notice the change in the number of active instances during an update operation, not during regular traffic on the auto-scaling group. However, the impact could be on operations where previously 100% of `in-service` instances were required for success, but now will be marked as successfully updated earlier with fewer instances. To be cautious, we can introduce a feature flag, but even then, the default behavior should be to consider the `minActiveInstancesPresent` field.

Comment (godwingrs22) [reply packages/aws-cdk-lib/core/lib/cfn-resource-policy.ts:195]: While I don't anticipate availability issues during rolling updates with this change, I think it will be good to verify the behaviour when enforcing the `MinActiveInstancesPercent` property during rolling updates. This property specifies the percentage of instances that must be in `InService` state relative to the ASG's desired capacity for an update to succeed. Currently, since this property is silently ignored, it effectively defaults to 100%. I'm thinking if an existing customer has specified `MinActiveInstancesPercent` as 50% with a desired capacity of 4, will enforcing this property allow the rolling update to proceed with only 2 active instances (50% of desired capacity), whereas currently it might be maintaining more instances in service during the update process?

I feel it is good to compare the current rolling update behavior against the behavior with this property enforced, specifically focusing on the number of `InService` instances available during the update process. For example, if the current behavior maintains 3 active instances during a rolling update, but with `MinActiveInstancesPercent: 50` only maintains 2 active instances, this would indicate reduced availability as fewer instances would be handling the application traffic during the rolling update period. To be clear, this concern is specifically about availability during the rolling update event, not about the general availability of the application after the update.

If we can verify there's no reduction in the number of available instances during rolling updates compared to current behavior, I'm comfortable proceeding without a feature flag. However, if we cannot conclusively verify the availability impact, it would be better to implement this with a feature flag as a safety measure. Given that rolling update behavior is also influenced by multiple other UpdatePolicy properties working in combination (MinInstancesInService, MaxBatchSize, etc.), it's challenging to predict all possible scenarios.

Comment (scorbiere) [reply packages/aws-cdk-lib/core/lib/cfn-resource-policy.ts:195]: TLDR; I agree to stay on the safe side and implement a feature flag, because we cannot guarantee the potential drop in availability will not negatively impact existing services.

Here is the analysis summary.

### Current Behavior (Before Fix)
Currently, when a customer imports a CloudFormation template with `MinActiveInstancesPercent` using `CfnInclude`, this property is silently dropped during parsing. When the CDK app synthesizes the template, this property is missing from the output, effectively using the default value of 100%.

### New Behavior (After Fix)
After the fix, when a customer imports a CloudFormation template with `MinActiveInstancesPercent` using `CfnInclude`, this property will be correctly parsed and included in the synthesized template, using the value specified in the original template.

### Potential Impact
According to the [AWS CloudFormation documentation on UpdatePolicy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html#cfn-attributes-updatepolicy-rollingupdate-minactiveinstancespercent), the `MinActiveInstancesPercent` property affects:

1. **During Rolling Updates**: It determines the percentage of instances that must remain in service during an update.
2. **When Scaling Up**: It affects instances launched when the desired capacity increases.

If a customer had templates with `MinActiveInstancesPercent` set to a value lower than 100%, but this property was being dropped by CDK, they were effectively getting 100% active instances during updates. After the fix, they will get the percentage they specified, which could be lower and potentially affect application availability during updates.

### Actions That Trigger Rolling Updates
The following actions can trigger a rolling update for an Auto Scaling group:

1. **Changes to the Launch Template or Launch Configuration**
2. **Changes to the Auto Scaling Group Properties**
3. **Stack Updates** with an UpdatePolicy attribute
4. **Desired Capacity Changes** when increased above the current capacity

Comment (scorbiere) [reply packages/aws-cdk-lib/core/lib/cfn-resource-policy.ts:195]: ## Update
There is no need for adding a new feature flag, because the property `MinActiveInstancesPercent` is automatically added when using CfnInclude since this PR: https://github.com/aws/aws-cdk/pull/32321

For the sake of clarity, I think it is good to keep the changes which include the explicit handling of this property in the CfnParse code and the tests (unit and integ).

**Review by godwingrs22 — APPROVED** [review]
