### PR TITLE
fix(ec2): don't use inferenceAccellerators in the constructors if not needed

### LINKED ISSUE #33505: aws-ecs: aws-cdk-lib.aws_ecs.TaskDefinitionProps#inferenceAccelerators
### Describe the bug

I started to see multiple instances of the same warning (for every ECS Service created):
```
[WARNING] aws-cdk-lib.aws_ecs.TaskDefinitionProps#inferenceAccelerators is deprecated.
  ECS TaskDefinition's inferenceAccelerator is EOL since April 2024
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_ecs.TaskDefinitionProps#inferenceAccelerators is deprecated.
  ECS TaskDefinition's inferenceAccelerator is EOL since April 2024
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_ecs.TaskDefinitionProps#inferenceAccelerators is deprecated.
  ECS TaskDefinition's inferenceAccelerator is EOL since April 2024
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_ecs.TaskDefinitionProps#inferenceAccelerators is deprecated.
  ECS TaskDefinition's inferenceAccelerator is EOL since April 2024
  This API will be removed in the next major release.
```

even though I am not even using that `inferenceAccelerators` property. I'm happy that the warning is there, but it should not be displayed if I am not using this property (without adding any flag).

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

No warning should be displayed if property is not used.

### Current Behavior

As above.

### Reproduction Steps

As above.

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.178.1 (build ae342cb)

### Framework Version

_No response_

### Node.js Version

v22.14.0

### OS

MacOS

### Language

TypeScript

### Language Version

└── typescript@5.7.3

### Other information

_No response_

### PR DESCRIPTION
**Pull request by rantoniuk**
### Issue # (if applicable)

Closes #33505 

### Reason for this change

The Ec2TaskDefinition should not pass the `@deprecated` `props.inferenceAccelerators` property if it's  unset or empty, because this results in showing deprecation notices in the console.
See [this comment](https://github.com/aws/aws-cdk/issues/33505#issuecomment-2770818825).

### Description of changes

Do not rely only on passing the props, but check if the array actually contains any elements.

### Description of how you validated changes

Cannot test by hand due to #34610.
UPDATE: manually tested in a production CDK stack. Result as expected, warnings are not shown during `cdk diff`.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by rantoniuk** [comment]
Clarification Request: I don't see any case like this being tested in `packages/aws-cdk-lib/aws-ecs/test/task-definition.test.ts` and I think this is a cosmetic change to how the condition is evaluated.

I'm happy to add a test _if required_ but please suggest the correct place and approach.

**Comment by rantoniuk** [comment]
@leonmk-aws any thoughts?

**Comment by leonmk-aws** [comment]
Thank you for your contribution, I have looked at this PR, unfortunately I don't believe it will close the issue that is linked.
Here is my reasoning:
The value of the optional list of inference accelerators `props.inferenceAccelerator` is undefined when not specified, which means that the `addInferenceAccelerator` is never called because of the conditional check:
https://github.com/aws/aws-cdk/blob/89d2d5c561860c1a9b55e1660efeec068fc4e6a3/packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts#L492-L494

I also tried to see if the fix was working by pulling your change in my repo, and using the the reproduction stack posted in the [issue thread](https://github.com/aws/aws-cdk/issues/33505#issuecomment-2669433969), I had the same warning without and with the changes.
I am not sure how you validated that the changes were working in your setup, here is how I did it: 
- First compile the repo without your changes, use the linker script to link it to a fresh cdk app containing the reproduction stack linked above, run `cdk list` (or any cdk command like `cdk synth`, note that you don't need to deploy the stack for the warning to appear), the warning should be printed in the console.
- In a second time, make your changes to the repo and rebuild it, in the same cdk app you used in step 1, re-run the same command, if the changes are working the warning should have disappeared.

**Comment by rantoniuk** [comment]
Hold your horses gh-bot, I will take a look at this this week

**Comment by rantoniuk** [comment]
I can confirm I can reproduce it using the small stack but I'm sure that it worked for my prod stack (but it doesn't now), very weird. 

I see one big difference between the two, ES2022 vs ES2020 so I had to juggle the tsconfig settings a bit. 
I'll try to find the root cause, appreciate it!

**Comment by rantoniuk** [comment]
@leonmk-aws that should do it - I checked this with both, the sample app and my prod stack.

**Comment by rantoniuk** [comment]
I see some checks have failed but at first glance it doesn't look they are related to my change?

File: packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts [hunk 1]
```diff
@@ -487,7 +487,7 @@ export class TaskDefinition extends TaskDefinitionBase {
       assumedBy: new iam.ServicePrincipal('ecs-tasks.amazonaws.com'),
     });
 
-    if (props.inferenceAccelerators) {
+    if (props.inferenceAccelerators && props.inferenceAccelerators.length > 0) {
```
Comment (leonmk-aws) [inline packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts]: I don't think this change is needed

File: packages/aws-cdk-lib/aws-ecs/lib/ec2/ec2-task-definition.ts [hunk 2]
```diff
@@ -143,14 +143,25 @@ export class Ec2TaskDefinition extends TaskDefinition implements IEc2TaskDefinit
...
   constructor(scope: Construct, id: string, props: Ec2TaskDefinitionProps = {}) {
-    super(scope, id, {
-      ...props,
-      compatibility: Compatibility.EC2,
-      placementConstraints: props.placementConstraints,
-      ipcMode: props.ipcMode,
-      pidMode: props.pidMode,
-      inferenceAccelerators: props.inferenceAccelerators,
-    });
+    if (props.inferenceAccelerators && props.inferenceAccelerators.length > 0) {
```
Comment (leonmk-aws) [inline packages/aws-cdk-lib/aws-ecs/lib/ec2/ec2-task-definition.ts]: Nit: We don't need to check the length

Comment (leonmk-aws) [inline packages/aws-cdk-lib/aws-ecs/lib/ec2/ec2-task-definition.ts]: Let's add a comment stating that this is done to prevent the warning

**Review by leonmk-aws — CHANGES_REQUESTED** [review]
Thank you for finding the issue, I added some comments. Regarding the failing checks I believe it is because the branch is out-of-date, you can rebase before making the changes I added in the comments and we'll see if that fixes the issue.

File: packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts (hunk 1 above)
Comment (rantoniuk) [reply packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts]: It's not but it doesn't hurt and it's actually following the pattern in [other places in this file](https://github.com/aws/aws-cdk/pull/34618/files#diff-30f86f37a5e24e67c95f88ca520635cbeac2f6ee44b69e321ad5381fcd97ff4eL459)

File: packages/aws-cdk-lib/aws-ecs/lib/ec2/ec2-task-definition.ts (hunk 2 above)
Comment (rantoniuk) [reply packages/aws-cdk-lib/aws-ecs/lib/ec2/ec2-task-definition.ts]: keeping a consistent approach + also just in case someone passes an empty array ;)

Comment (rantoniuk) [reply packages/aws-cdk-lib/aws-ecs/lib/ec2/ec2-task-definition.ts]: Added, if you'd like a different wording, please use _add a suggestion_ so that we don't delay this

Comment (leonmk-aws) [reply packages/aws-cdk-lib/aws-ecs/lib/ec2/ec2-task-definition.ts]: I would argue the warning should be shown when passing an empty array as the field is deprecated.
If we show a warning even when passing an empty array, users are more likely to remove this line of code (the empty array) to fix the warning which can be considered "good practice".

File: packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts (hunk 1 above)
Comment (leonmk-aws) [reply packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts]: I agree that the pattern is used to check for `ValidationError` and it makes sense there, but here the only thing in that conditional statement is a `forEach` loop, so we don't need to check it as nothing will happen with an empty list.
Let's try to keep changes as minimal as possible.

**Review by leonmk-aws — APPROVED** [review]
Thank you for the fix, approved

**Comment by rantoniuk** [comment]
@leonmk-aws is it still waiting for Exemption Request?
