### PR TITLE
fix(apigateway): deployment not invalidated when integration is changed

### LINKED ISSUE #4551: apigateway: deployment is not invalidated when using a different lambda handler
As described in https://github.com/aws-samples/aws-cdk-intro-workshop/issues/83, when changing a Lambda integration to point to a different handler, the APIGW is not invalidated as it should be.

### Reproduction Steps

```ts
    // GIVEN
    const stack1 = new Stack();
    const stack2 = new Stack();
    const handler1 = new lambda.Function(stack1, 'handler1', {
      code: lambda.Code.fromAsset(path.join(__dirname, 'integ.cors.handler')),
      runtime: lambda.Runtime.NODEJS_10_X,
      handler: 'index.handler'
    });
    const handler2 = new lambda.Function(stack2, 'handler2', {
      code: lambda.Code.fromAsset(path.join(__dirname, 'integ.cors.handler')),
      runtime: lambda.Runtime.NODEJS_10_X,
      handler: 'index.handler'
    });

    // WHEN
    const api1 = new apigateway.RestApi(stack1, 'myapi', {
      defaultIntegration: new apigateway.LambdaIntegration(handler1)
    });
    const api2 = new apigateway.RestApi(stack2, 'myapi', {
      defaultIntegration: new apigateway.LambdaIntegration(handler2)
    });
    api1.root.addMethod('GET');
    api2.root.addMethod('GET');

    // THEN
    expect(stack1).to(haveResource('AWS::ApiGateway::Stage', {
      DeploymentId: { Ref: 'myapiDeploymentB7EF8EB7e0b8372768854261d2d1218739e0a307' }
    }));
    expect(stack2).to(haveResource('AWS::ApiGateway::Stage', {
      DeploymentId: { Ref: 'myapiDeploymentB7EF8EB77c517352b0f7ab73c333e36585c8f1f3' }
    }));
    test.done();
```

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by eladb**
The calculation of the deployment logical id is based on a hash of the apigateway model, which includes components such as the resource and method configurations. method integrations, which are part of the method configuration are also included, and could possible include references to other resources such as lambda functions.

When the hash was calculated, tokens have been resolved using `StringConcat` which basically converted all tokens to `[Object object]`. This means, for example, that if we changed the reference of an integration lambda to a different handler, the hash would remain the same.

There is no apparent reason why we can't simply resolve tokens using the CloudFormation concatenation function during "prepare", which means that if we now reference a different resource, the token will resolve to a different value and deployment will be invalidated.

Fixes #4551
Fixes https://github.com/aws-samples/aws-cdk-intro-workshop/issues/77

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/@aws-cdk/aws-apigateway/lib/deployment.ts [hunk 1]
```diff
@@ -121,20 +121,13 @@ class LatestDeploymentResource extends CfnDeployment {
...
-        .map(c => {
-          return Tokenization.resolve(c, {
-            scope: this,
-            resolver: new DefaultTokenResolver(new StringConcat()),
-            preparing: true,
-          });
-        })
-        .forEach(c => md5.update(JSON.stringify(c)));
-
+      this.hashComponents.map(x => stack.resolve(x)).forEach(c => md5.update(JSON.stringify(c)));
```
Comment (nija-at) [inline packages/@aws-cdk/aws-apigateway/lib/deployment.ts]: You're reverting a part of this commit - https://github.com/aws/aws-cdk/commit/17fc967d. 
This specific piece of code was aimed at fixing https://github.com/aws/aws-cdk/issues/3705. Perhaps the fix wasn't accurate in using `StringConcat()`? 

I suspect (and hope so we don't regress) this will fail a unit test.

The original problem was you can't 'resolve' the entire stack before it was finished 'prepare'ing

Comment (eladb) [reply packages/@aws-cdk/aws-apigateway/lib/deployment.ts]: seems like #239 resolved the issue since cross stack reference resolution was moved from the element level to the stack level so we are all good.
