### PR TITLE
fix(ec2): descriptive error message when selecting 0 subnets

### LINKED ISSUE #2011: VpcNetwork should throw a descriptive error when selecting 0 subnets
Trying to set up a ecs cluster with asg in a existing non-cdk managed vpc. 
The `externalVpc` is used without issue when working with Lambdas, but with ASG it fails due to AvailabilityZones being empty, but they do exist and they do work with at least one other resource.

```typescript
const externalVpc = ec2.VpcNetwork.import(this, 'exampleVPC', {
  availabilityZones: [cdk.Fn.importValue('az1'), cdk.Fn.importValue('az1')],
  publicSubnetIds: [cdk.Fn.importValue('publicsubnet1'), cdk.Fn.importValue('publicsubnet2')],
  vpcId: cdk.Fn.importValue('vpcId'),
});

// Cluster config
const cluster = new ecs.Cluster(this, 'cluster-test', {
  clusterName: 'cluster-test',
  vpc: externalVpc,
});

cluster.addCapacity('asg-test', {
  instanceType: new ec2.InstanceType('t3.small'),
  taskDrainTimeSeconds: 0,
});
```

results in

```
 CREATE_FAILED        | AWS::AutoScaling::AutoScalingGroup

 Property AvailabilityZones cannot be empty.
        new AutoScalingGroup (code\aws\node_modules\@aws-cdk\aws-autoscaling\lib\auto-scaling-group.ts:297:29)
        \_ Cluster.addCapacity (code\aws\node_modules\@aws-cdk\aws-ecs\lib\cluster.ts:78:30)
        \_ new ContainerRegistryStack (ode\operator-interface\aws\lib\container-repository-stack\ecr.ts:32:13)
        \_ Object.<anonymous> (code\operator-interface\aws\bin\aws.ts:12:1)
        \_ Module._compile (internal/modules/cjs/loader.js:689:30)
        \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
        \_ Module.load (internal/modules/cjs/loader.js:599:32)
        \_ tryModuleLoad (internal/modules/cjs/loader.js:538:12)
        \_ Function.Module._load (internal/modules/cjs/loader.js:530:3)
        \_ Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
        \_ startup (internal/bootstrap/node.js:283:19)
        \_ bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

The actual error is that ```
      vpcPlacement: {
        subnetsToUse: SubnetType.Public
      }
``` is missing in the config to `config.addCapacity`.

`vpcPlacement` is an optional parameter, but without it you get an error in this case.

### PR DESCRIPTION
**Pull request by rix0rrr**
Selecting 0 subnets is invalid for most CFN resources. We move the check
for this upstream to the VPC construct, which can throw a nicely
descriptive error message if it happens to not contain any subnets that
match the type we're looking for.

The alternative is that the error happens during CloudFormation
deployment, but then it's not very clear anymore what the cause for
the error was.

Fixes #2011.

----

### Pull Request Checklist

* [x] Testing
  - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
  - __CLI change?:__ coordinate update of integration tests with team
  - __cdk-init template change?:__ coordinated update of integration tests with team
* [x] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated
* [x] Title and Description
  - __Change type__: title prefixed with **fix**, **feat** will appear in changelog
  - __Title__: use lower-case and doesn't end with a period
  - __Breaking?__: last paragraph: "BREAKING CHANGE: <describe what changed + link for details>"
  - __Issues__: Indicate issues fixed via: "**Fixes #xxx**" or "**Closes #xxx**"
* [x] Sensitive Modules (requires 2 PR approvers)
  - IAM Policy Document (in @aws-cdk/aws-iam)
  - EC2 Security Groups and ACLs (in @aws-cdk/aws-ec2)
  - Grant APIs (only if not based on official documentation with a reference)

----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license.

### CODE REVIEW

File: packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts [hunk 1]
```diff
@@ -62,9 +62,23 @@ export interface IVpcNetwork extends IConstruct {
 
   /**
    * Return the subnets appropriate for the placement strategy
+   *
+   * Prefer using {@link subnetIds} if you need to pass subnet IDs to a
+   * CloudFormation Resource.
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts]: What do you mean "pass subnet IDs to a CloudFormation Resource"? It feels to me like this is all you'll ever be doing with subnets. Probably deserves a little hint at why it is preferable to use `subnetIds`, so the user feels like they understand the guidance.

File: packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts [hunk 2]
```diff
@@ -62,9 +62,23 @@ export interface IVpcNetwork extends IConstruct {
...
    */
   subnets(placement?: VpcPlacementStrategy): IVpcSubnet[];
 
+  /**
+   * Return IDs of the subnets appropriate for the given placement strategy
+   *
+   * Requires that at least once subnet is matched, throws a descriptive
+   * error message otherwise.
+   *
+   * Prefer to use this method over {@link subnets} if you need to pass subnet
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts]: This sentence strikes me as a little confusing to a user... I kinda feel like that should provide more info on why this guidance exists, and the guidance should be more clear as to how you'd be "extracting IDs" out of `subnets` otherwise.

File: packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts [hunk 3]
```diff
@@ -227,6 +239,20 @@ export abstract class VpcNetworkBase extends Construct implements IVpcNetwork {
...
 
+  /**
+   * Returns IDs of selected subnets
+   */
+  public subnetIds(placement: VpcPlacementStrategy = {}): string[] {
+    placement = reifyDefaultsPlacement(placement);
+
+    const nets = this.subnets(placement);
+    if (nets.length === 0) {
+      throw new Error(`There are no ${describePlacement(placement)} in this VPC. Use a different VPC placement strategy.`);
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts]: Could we maybe hint at what strategies would have matched something? Or are placement strategies too complex?

File: packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts [hunk 4]
```diff
@@ -335,3 +361,34 @@ export interface VpcSubnetImportProps {
...
+
+/**
+ * If the placement strategy is completely "default", reify the defaults so
+ * consuming code doesn't have to reimplement the same analysis every time.
+ *
+ * Returns "private subnets" by default.
+ */
+function reifyDefaultsPlacement(placement: VpcPlacementStrategy): VpcPlacementStrategy {
+    if (placement.subnetsToUse !== undefined && placement.subnetName !== undefined) {
+      throw new Error('At most one of subnetsToUse and subnetName can be supplied');
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts]: Would phrase this as `Only one of subnetsToUse and subnetName can be supplied`. The "at most" to me is implied by "can". Not feeling very strongly though.

File: packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts [hunk 5]
```diff
@@ -335,3 +361,34 @@ export interface VpcSubnetImportProps {
    */
   subnetId: string;
 }
+
+/**
+ * If the placement strategy is completely "default", reify the defaults so
+ * consuming code doesn't have to reimplement the same analysis every time.
+ *
+ * Returns "private subnets" by default.
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts]: You'll have to propagate that default behavior to the documentation of every place that accepts a `VpcPlacementStrategy`. I have a felling some users will sometimes expect "all subnets" to be the default...

File: packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts [hunk 6]
```diff
@@ -335,3 +361,34 @@ export interface VpcSubnetImportProps {
...
+ * Describe the given placement strategy
+ */
+function describePlacement(placement: VpcPlacementStrategy) {
+  if (placement.subnetsToUse !== undefined) {
+    return `'${DEFAULT_SUBNET_NAME[placement.subnetsToUse]}' subnets`;
+  }
+  if (placement.subnetName !== undefined) {
+    return `subnets named '${placement.subnetName}'`;
+  }
+  return '???';
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts]: If you get there you've effectively reached the default behavior, I believe. Then you should probably return `private subnets`. If you are willing to assume that the defaults have always been reified before you get here, then why not throw instead of returning `???`?

File: packages/@aws-cdk/aws-ec2/test/test.vpc.ts [hunk 7]
```diff
@@ -666,7 +666,24 @@ export = {
 
       test.done();
     },
+
+    'selecting default subnets in a VPC with only public subnets'(test: Test) {
```
Comment (RomainMuller) [inline packages/@aws-cdk/aws-ec2/test/test.vpc.ts]: Would be nice to also have tests covering:
- selecting "default" subnet IDs returns private subnets IDs
- selecting "Public" subnet IDs returns public subnet IDs
- selecting "named X" subnet IDs returns subnet IDs named X

Now I feel we're only covering the default behavior, which means if there was a bug in the method that reifies the defaults (which would always override what you passed with the defaults), we wouldn't know.

I would also be tempted to nest the tests fo `subnetIDs` under a different test namespace, so that their descriptions are effectively disambiguated from those of `subnets`.

File: packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts]: You would expect, but this is not true. What also happens to them is testing for publicness, and adding dependencies to their internetconnectivity.

A fair argument would be that those should be changed to [SOA instead of AOS](https://en.wikipedia.org/wiki/AOS_and_SOA) accessors as well, but I wanted to keep the change small.

How do you feel about those?

File: packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts (hunk 3 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts]: They are not necessarily, but what are you proposing?

`"The VPC network contains 1 Public subnet group with name "Public" and 2 Private subnets groups with names "MyDatabases","MyLambdas"`

File: packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts (hunk 4 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts]: You're right on phrasing.

File: packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts (hunk 5 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts]: I don't think "all subnets" is a viable or expected default.

Furthermore, if a construct wants to change the default from `Private` to `Public`, all they have to add is an `if(undefined)` to their usage of this API.

This method only exists so that in the interplay between `subnetIds()` and `subnets()`, we don't have to do the same `if(undefined)` analysis twice.

File: packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts (hunk 6 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts]: I was thinking to throw, but at the same time I didn't want to block a customer from using this construct if we ever forget a code path. Rather have ugly behavior but allow the user to continue (so that we can fix the issue when we have capacity) rather than block them completely by throwing an error and now we have to scramble to get a fix out.

Comment (RomainMuller) [reply packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts]: Right but then at least avoid the question marks... Maybe `JSON.stringify` what you've been given.

File: packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts (hunk 3 above)
Comment (RomainMuller) [reply packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts]: I mean I wouldn't put the `Use a different VPC placement strategy` if you can't hint at which are "valid".

File: packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts (hunk 1 above)
Comment (RomainMuller) [reply packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts]: Hmm yeah I think that might offer a cleaner API overall, and might allow to focus the user better on what they should do.

File: packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts (hunk 3 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-ec2/lib/vpc-ref.ts]: I used that terminology on purpose because:

* It's okay to state an error, but it's better to state a path to a solution.
* I want to use the words "VPC placement" here on purpose, because previously asked questions have shown that people don't think of this term.

Although maybe the better solution is to change the parameter name to `subnetSelection`, or something, under the "s" where people that already know things about AWS and CFN are going to look for it.

File: packages/@aws-cdk/aws-ec2/test/test.vpc.ts (hunk 7 above)
Comment (rix0rrr) [reply packages/@aws-cdk/aws-ec2/test/test.vpc.ts]: Will add the test on the defaults.

The other ones are already tested.
