### PR TITLE
fix(elasticloadbalancingv2): open, dual-stack-without-public-ipv4 ALB does not allow IPv6 inbound traffic (under feature flag)

### LINKED ISSUE #32197: aws-elasticloadbalancingv2: ApplicationListener open prop does not account for LB type DUAL_STACK_WITHOUT_PUBLIC_IPV4
### Describe the bug

The automatically generated security group ingress rules for an ALB are incorrect when 1) an ApplicationLoadBalancer IP address type is set to `DUAL_STACK_WITHOUT_PUBLIC_IPV4` and 2) a listener on the LB is set to allow anyone to connect to the load balancer on the listener port `open: true`.  The generated rules only allow IPV4 inbound traffic and no IPV6 inbound traffic, which effectively allows no external traffic.

Support for DUAL_STACK_WITHOUT_PUBLIC_IPV4 was added in CDK [v2.159.0](https://github.com/aws/aws-cdk/releases/tag/v2.159.0), but missed this change.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

Example security group ingress rules:
```json
    "SecurityGroupIngress": [
     {
      "CidrIp": "0.0.0.0/0",
      "Description": "Allow from anyone on port 80",
      "FromPort": 80,
      "IpProtocol": "tcp",
      "ToPort": 80
     },
     {
      "CidrIp": "::/0",
      "Description": "Allow from anyone on port 80",
      "FromPort": 80,
      "IpProtocol": "tcp",
      "ToPort": 80
     }
    ],
```

### Current Behavior

Example security group ingress rules:
```json
    "SecurityGroupIngress": [
     {
      "CidrIp": "0.0.0.0/0",
      "Description": "Allow from anyone on port 80",
      "FromPort": 80,
      "IpProtocol": "tcp",
      "ToPort": 80
     }
    ],
```

### Reproduction Steps

I'm using the ECS patterns module, which automatically generated the load balancer:
```typescript
new patterns.ApplicationLoadBalancedFargateService(this, 'Service', {
      cluster,
      desiredCount: 1,
      domainName,
      domainZone,
      protocol: ApplicationProtocol.HTTPS,
      redirectHTTP: true,
      assignPublicIp: false,
      ipAddressType: elb.IpAddressType.DUAL_STACK_WITHOUT_PUBLIC_IPV4,
      taskImageOptions: {
...
```

### Possible Solution

I have what I believe is a fix, but I still need to update tests and validate:
```diff
diff --git a/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener.ts b/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener.ts
index 07cfb949f3..35ba804721 100644
--- a/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener.ts
+++ b/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener.ts
@@ -303,7 +303,8 @@ export class ApplicationListener extends BaseListener implements IApplicationLis
 
     if (props.open !== false) {
       this.connections.allowDefaultPortFrom(ec2.Peer.anyIpv4(), `Allow from anyone on port ${port}`);
-      if (this.loadBalancer.ipAddressType === IpAddressType.DUAL_STACK) {
+      if (this.loadBalancer.ipAddressType === IpAddressType.DUAL_STACK ||
+        this.loadBalancer.ipAddressType === IpAddressType.DUAL_STACK_WITHOUT_PUBLIC_IPV4) {
         this.connections.allowDefaultPortFrom(ec2.Peer.anyIpv6(), `Allow from anyone on port ${port}`);
       }
     }

```

### Additional Information/Context

_No response_

### CDK CLI Version

2.164.1

### Framework Version

_No response_

### Node.js Version

v20.18.0

### OS

Linux

### Language

TypeScript

### Language Version

5.6.2

### Other information

_No response_

### PR DESCRIPTION
**Pull request by gracelu0**
### Issue # (if applicable)

Closes #32197 .

### Reason for this change

Default generated security group ingress rules for open, dual-stack-without-public-ipv4 ALB does not allow IPv6 traffic. Only a rule for IPv4 ingress traffic is added to the security group rules currently.

### Description of changes

Introduced a new feature flag which is enabled by default so that default generated security group ingress rules now have an additional rule that allows IPv6 ingress from anywhere. 

### Describe any new or updated permissions being added

No new IAM permissions. Added IPv6 security group ingress rules for open, internet-facing ALBs if IP address type  is `dual-stack-without-public-ipv4` and feature flag is set to `true` (default).

### Description of how you validated changes

Added unit test which checks the security group rules for both cases where feature flag is enabled/disabled. Updated integration test snapshot.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

Co-authored-by: Clare Liguori <clareliguori@users.noreply.github.com>

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by gracelu0** [comment]
@Mergifyio update

File: packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener.ts [hunk 1]
```diff
@@ -303,7 +303,9 @@ export class ApplicationListener extends BaseListener implements IApplicationLis
 
     if (props.open !== false) {
       this.connections.allowDefaultPortFrom(ec2.Peer.anyIpv4(), `Allow from anyone on port ${port}`);
-      if (this.loadBalancer.ipAddressType === IpAddressType.DUAL_STACK) {
+      if (this.loadBalancer.ipAddressType === IpAddressType.DUAL_STACK ||
+        (this.loadBalancer.ipAddressType === IpAddressType.DUAL_STACK_WITHOUT_PUBLIC_IPV4 &&
```
Comment (samson-keung) [inline packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener.ts:307]: I recommend updating [the doc](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancingv2.IpAddressType.html) for `IpAddressType.DUAL_STACK_WITHOUT_PUBLIC_IPV4` to mention how it behaves differently depending on the feature flag.

File: packages/aws-cdk-lib/cx-api/lib/features.ts [hunk 2]
```diff
@@ -1299,6 +1300,22 @@ export const FLAGS: Record<string, FlagInfo> = {
...
+    type: FlagType.ApiDefault,
+    summary: 'When enabled, the default security group ingress rules will allow IPv6 ingress from anywhere',
+    detailsMd: `
+      For internet facing ALBs with 'dualstack-without-public-ipv4' IP address type, the default security group rules
+      will allow IPv6 ingress from anywhere (::/0). Previously, the default security group rules would only allow IPv4 ingress.
+
+      Using a feature flag to make sure existing customers who might be relying
+      on the overly restrictive permissions are not broken.`,
+    introducedIn: { v2: 'V2NEXT' },
+    defaults: { v2: true },
```
Comment (samson-keung) [inline packages/aws-cdk-lib/cx-api/lib/features.ts:1315]: I believe setting the default to true means existing projects will automatically have this feature flag as true, which means they will get the new behaviour automatically, which is a breaking change. Can you double check?

**Review by samson-keung — CHANGES_REQUESTED** [review]

File: packages/aws-cdk-lib/cx-api/lib/features.ts (hunk 2 above)
Comment (gracelu0) [reply packages/aws-cdk-lib/cx-api/lib/features.ts:1315]: Thanks Samson, you're correct that they would automatically get the new ingress rules upon re-deploying. I set the default to `true` thinking we would want new projects to setup the ingress rules to allow IPv6 by default, but it looks like that is what the `recommended` value is for. Will update.

File: packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md [hunk 3]
```diff
@@ -111,27 +116,27 @@ for imported or looked up Load Balancers.
...
+* **Weighted Target Groups**: use `ListenerAction.weightedForward()`
   to give different weights to different target groups.
-- **Fixed Responses**: use `ListenerAction.fixedResponse()` to serve
+* **Fixed Responses**: use `ListenerAction.fixedResponse()` to serve
   a static response (ALB only).
-- **Redirects**: use `ListenerAction.redirect()` to serve an HTTP
+* **Redirects**: use `ListenerAction.redirect()` to serve an HTTP
   redirect response (ALB only).
-- **Authentication**: use `ListenerAction.authenticateOidc()` to
+* **Authentication**: use `ListenerAction.authenticateOidc()` to
```
Comment (samson-keung) [inline packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md:139]: Did you run some Markdown linting to catch these things? Does it auto fix?

**Review by samson-keung — APPROVED** [review]
Thank you!

File: packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md (hunk 3 above)
Comment (gracelu0) [reply packages/aws-cdk-lib/aws-elasticloadbalancingv2/README.md:139]: Yes I think I installed the `markdownlint` VSCode extension mentioned in RFC repo readme: https://github.com/aws/aws-cdk-rfcs?tab=readme-ov-file#4-rfc-document which auto-formats markdown files.

**Comment by gracelu0** [comment]
@Mergifyio update
