### PR TITLE
fix(ecs): remove empty CfnClusterCapacityProviderAssociations resource

### LINKED ISSUE #35699: ecs: unable to create managed instances capacity provider
### Describe the bug

I'm unable to create a managed instance capacity provider. It appears the current L2 constructs creates an invalidate (and not required) `ClusterCapacityProviderAssociations` resource. 

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Library Version

_No response_

### Expected Behavior

The managed instances capacity provider gets added to the cluster.

### Current Behavior

The creation of the stack fails because the Capacity Provider Associate resource fails

### Reproduction Steps

Template:

```
    // Create ECS Cluster
    const cluster = new ecs.Cluster(this, 'MyEcsCluster', {
      vpc: vpc,
      clusterName: `${this.stackName}-cluster`,
    });

    // Create a Default Managed Instances Capacity Provider
    const miDefaultCapacityProvider = new ecs.ManagedInstancesCapacityProvider(this, 'MIDefaultCapacityProvider', {
      infrastructureRole: ecsInfrastructureRole,
      ec2InstanceProfile: ecsInstanceProfile,
      subnets: vpc.privateSubnets,
      securityGroups: [miDefaultSecurityGroup]
    });

    cluster.addManagedInstancesCapacityProvider(miDefaultCapacityProvider);
```

When I synth this, I get the following template:

```
  MyEcsCluster989E66E0:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: CdkStack-cluster
    Metadata:
      aws:cdk:path: CdkStack/MyEcsCluster/Resource
  MyEcsCluster9940BE40:
    Type: AWS::ECS::ClusterCapacityProviderAssociations
    Properties:
      CapacityProviders: []
      Cluster:
        Ref: MyEcsCluster989E66E0
      DefaultCapacityProviderStrategy: []
    Metadata:
      aws:cdk:path: CdkStack/MyEcsCluster/MyEcsCluster
  MIDefaultCapacityProvider07546591:
    Type: AWS::ECS::CapacityProvider
    Properties:
      ClusterName:
        Ref: MyEcsCluster989E66E0
      ManagedInstancesProvider:
        InfrastructureRoleArn:
          Fn::GetAtt:
            - ECSInfrastructureRoleE492121F
            - Arn
        InstanceLaunchTemplate:
          Ec2InstanceProfileArn:
            Fn::GetAtt:
              - ECSInstanceProfileBA4A4DA9
              - Arn
          NetworkConfiguration:
            SecurityGroups:
              - Fn::GetAtt:
                  - MIDefaultSecurityGroup4EADDF9A
                  - GroupId
            Subnets:
              - Ref: MyVpcPrivateSubnetSubnet1SubnetE8BD536C
              - Ref: MyVpcPrivateSubnetSubnet2SubnetE3BFCF91
    Metadata:
      aws:cdk:path: CdkStack/MIDefaultCapacityProvider/MIDefaultCapacityProvider
```

Then why I attempt to deploy it, the `ClusterCapacityProviderAssociations` will fail.

> Resource handler returned message: "Name is null" (RequestToken: f0729928-71d8-e634-55ef-aedadadfc136, HandlerErrorCode: InternalFailure)

### Possible Solution

This additional Provider Association resource is not required with Managed Instances as the cluster name is in the capacity provider. I did wonder why we needed a `cluster.addManagedInstancesCapacityProvider()` resource at all, we could have just added a cluster name attribute to `ecs.ManagedInstancesCapacityProvider()` which would map to what the cloudformation looks like. 

### Additional Information/Context

_No response_

### AWS CDK Library version (aws-cdk-lib)

2.219.0

### AWS CDK CLI version

2.1029.4

### Node.js Version

v22.14

### OS

Ubuntu 22.04

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by aemada-aws**
### Issue # (if applicable)

Closes #35699
Related to: #35742

### Reason for this change

CfnClusterCapacityProviderAssociations is not needed when using only managed instances as a capacity provider, but it was being created anyway with empty values. It is needed if default capacity providers are set, or the capacity provider is not of the managed instances type.

### Description of changes

Removed the `clusterScopedCapacityProviderNames` check when creating CfnClusterCapacityProviderAssociations.

Destructive changes: CfnClusterCapacityProviderAssociations will be deleted if user does not provide default capacity providers or default fargate and uses only ManagedInstancesCapacityProvider.

### Describe any new or updated permissions being added

None

### Checklist
- [X] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by isker — APPROVED** [review]

File: packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.managedinstances-no-default-capacity-provider.ts [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+      capacityProvider: miCapacityProvider.capacityProviderName,
+      weight: 1,
+    },
+  ],
+  desiredCount: 1,
+});
+
+new integ.IntegTest(app, 'ManagedInstancesCapacityProviders', {
+  testCases: [stack],
+  regions: ['us-west-2'],
```
Comment (aemada-aws) [inline packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/integ.managedinstances-no-default-capacity-provider.ts:104]:
```suggestion
```

**Review by Abogical — CHANGES_REQUESTED** [review]
I believe a unit test checking if the CfnClusterCapacityProviderAssociations resource is removed needs to be added.

**Comment by aemada-aws** [comment]
> I believe a unit test checking if the CfnClusterCapacityProviderAssociations resource is removed needs to be added.

added one

**Review by Abogical — APPROVED** [review]
Thanks!

**Comment by Abogical** [comment]
@mergifyio update

**Comment by Abogical** [comment]
@mergifyio requeue
